4teamwork/opengever.core

docs/HISTORY.txt
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20170615114951_disable_swfobject_js_from_c_quickupload/jsregistry.xml
opengever/core/upgrades/20170615114951_disable_swfobject_js_from_c_quickupload/upgrade.py

I was no able to recognise any negative effects after disabling the swfobjects.js
There's no JS error in the console of IE11, FF, Chrome.
To completely remove Flash from GEVER, this PR https://github.com/4teamwork/collective.js.extjs/pull/3 is also needed.

Disbale swfobject.js - no longer load Flash fallback for multiuploads.

---

docs/HISTORY.txt
opengever/journal/configure.zcml
opengever/journal/handlers.py
opengever/journal/tests/test_document_journalization.py

After copy and paste the new document has only one journal entry:
- The Doc created journal entry.
Fixes #2196

Reset journal after copy a document.

---

docs/HISTORY.txt
opengever/core/upgrades/20170616071527_make_private_folders_title_a_string/upgrade.py
opengever/private/folder.py
opengever/private/tests/test_folder.py

The Title accessor needs to return bytestring not unicode. The users label is always unicode.
Needs backport to: 2017.2-stable
🐷  already filled 😉

Fix PrivateFolders Title encoding.

---

opengever/meeting/tests/test_protocol.py

In https://github.com/4teamwork/ftw.testbrowser/pull/55 a bug has been fixed where the view would be exposed as `browser.context`. Unfortunately a test actually relied on that behaviour 😂 . This PR rewrites the test to only test against the model.
_CL should not be required i'd say_

Catch up tests with ftw.testbrowser bugfix.

---

docs/HISTORY.txt
opengever/base/configure.zcml

This allow us to include opengever.core zcmls from a policy packages, which has to be loaded before opengever.core so that customized translations works correctly.

Include missing permission definitions from Products.CMFCore.

---

docs/HISTORY.txt
opengever/ogds/base/sync/ldap_util.py
sources.cfg

- Use our own [Products.LDAPUserFolder](https://github.com/4teamwork/Products.LDAPUserFolder) and [Products.LDAPUserFolder](https://github.com/4teamwork/Products.LDAPMultiPlugins) forks.
- Respect recently introduced `lookup_groups_base` during OGDS group synchronisation (see https://github.com/4teamwork/Products.LDAPMultiPlugins/pull/1)
⚠️  depends on https://github.com/4teamwork/Products.LDAPMultiPlugins/pull/1

Replace our LDAP stack with our own forks

---

docs/HISTORY.txt
opengever/dossier/tests/test_templatefolder.py
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

Show userid instead of E-Mail address on responsible field of dossier.

---

docs/HISTORY.txt
opengever/core/profiles/default/cssregistry.xml
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20170608134918_change_to_original_plone_formwidget_autocomplete/cssregistry.xml
opengever/core/upgrades/20170608134918_change_to_original_plone_formwidget_autocomplete/jsregistry.xml
opengever/core/upgrades/20170608134918_change_to_original_plone_formwidget_autocomplete/upgrade.py
sources.cfg

Since the OGIP 15 task responsible rework, it's no longer necessary to dynamically change the data source on task responsible fields. Therefore our fork of the `plone.formwidget.autocomplete` is no longer necessary.
This change should allow us to switch to the latests plone 4.3.x release.
Styles: https://github.com/4teamwork/plonetheme.teamraum/pull/555
Closes #1152

Switch back to the original plone.formwidget.autocomplete package.

---

opengever/core/testing.py
opengever/core/tests/test_fixture.py
opengever/core/tests/test_integration_testing_setup.py
opengever/testing/__init__.py
opengever/testing/fixtures.py
opengever/testing/helpers.py
opengever/testing/integration_test_case.py

The integration testing layer sets up a fixture with commonly used objects.
By setting up a fixture instead of creating all the objects in each test we want to speed up the test suite.
Since we cannot rollback commits in SQL, we use integration testing and avoid unwanted commits so that we can achieve isolation between tests by rolling back to savepoints.
This change provides the infrastructure for building the fixture and gradually switching tests to the new integration testing.
It is a conscious decision to call the new testing "integration testing" and the old testing "functional testing" in order to have a simple language to communicate between developers.

Add integration testing layer with fixture.

---

docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/metadata.rst

Ergänzung des Unterkapitels "Einschränkung Metadaten", in welchem kurz beschrieben wird, dass seit das Öffentlichkeitsgesetzt in Kraft getreten ist, gewisse Status bei Lebenszyklus und Sichtbarkeit nur eingeschränkt eingesetzt werden können.

Ergänzung Unterkapitels "Einschränkung Metdaten"

---

docs/HISTORY.txt
opengever/dossier/move_items.py
opengever/dossier/templatefolder/tabs.py
opengever/dossier/tests/test_move_items.py
opengever/dossier/tests/test_templatefolder.py

This PR allows move items in the documents tab within the templatefolder.
closes #2401

Allow move items in the documents tab within the templatefolder.

---

opengever/core/tests/test_fixture.py
opengever/repository/tests/test_deletion.py
opengever/repository/tests/test_menu.py
opengever/repository/tests/test_reference_behavior.py
opengever/repository/tests/test_reference_prefix_manager.py
opengever/repository/tests/test_repository_workflow.py
opengever/repository/tests/test_repositoryfolder.py
opengever/repository/tests/test_repositoryfolder_byline.py
opengever/repository/tests/test_subscribers.py
opengever/testing/fixtures.py

"repository" refers more to the whole tree, including the root. Therefore the term "repository folder" or short "repofolder" is more accurate.

Rename repository to repofolder in fixtures.

---

docs/HISTORY.txt
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_task_link.py
opengever/tabbedview/browser/tasklisting.py
opengever/tabbedview/tests/test_tasklisting.py

This PR fixes two issue:
- breadcrumb part of the title
- containing dossier title

Escape html of content on the task listing tab

---

sources.cfg

To include a fix which has been made for oracle backends, see https://github.com/4teamwork/opengever.ogds.models/pull/46.

Add opengever.ogds.models to development-packages.

---

.gitignore
README.rst

I have updated the testing documentation in the README:
- Remove the old gever-testbrowser documentation; `ftw.testbrowser` shall be used.
- Add a section about functional and integration testing.
- Add an example integration test case.
- Add some best practices.
@4teamwork/gever please have a look.

Update testing documentation in readme

---

docs/HISTORY.txt
opengever/ogds/base/upgrades/20160211150813_enlarge_profileid_in_migration_tracking_table/upgrade.py

Because Oracle is not able to change a Integer column to a BigInteger, when it contains data. I've add a separate implementation for oracle backends to  the `EnlargeProfileidInMigrationTrackingTable` upgradestep. Instead of changing the column type, it now renames the column, add the new one, copies the data and drops the old_column.

Fix schema migration EnlargeProfileidInMigrationTrackingTable for oracle backend.

---

docs/HISTORY.txt
opengever/document/checkout/checkout.py
opengever/document/document.py
opengever/dossier/templatefolder/form.py
opengever/dossier/tests/test_templatefolder.py
opengever/officeconnector/helpers.py

I'm not totally certain about the second commit, which refactors some code:
https://github.com/4teamwork/opengever.core/commit/b7fe2f1778eef5aeabedec660045eb4a5f898e8e#diff-f6f40726c157ab858647bea6cd2a2b37L77
https://github.com/4teamwork/opengever.core/commit/b7fe2f1778eef5aeabedec660045eb4a5f898e8e#diff-f6f40726c157ab858647bea6cd2a2b37L83
and
https://github.com/4teamwork/opengever.core/commit/b7fe2f1778eef5aeabedec660045eb4a5f898e8e#diff-f6f40726c157ab858647bea6cd2a2b37R74
I dislike the fact that we're using `objects[0]` and `self.context` first and use only `objects[0]` afterwards... is it the same object?
Maybe @Rotonen can explain what's going on there.
Resolves #3044

Create document from template using office connector

---

docs/HISTORY.txt
opengever/journal/form.py
opengever/journal/tests/test_manual_entry.py

Because z3c.form could not handle the inherited add and the new cancel button, also the add button hat do be defined by the `ManualJournalEntryAddForm` itself.
Besides that I've also fixed the styling of the add button.

Added missing cancel button for the manual journal entry form.

---

sources.cfg

To include the latest fix https://github.com/4teamwork/ftw.mobilenavigation/pull/45 to include portal tabs. Closes #2993

Add `ftw.mobilenavigation` to development-packages,

---

docs/HISTORY.txt
opengever/portlets/tree/resources/init_tree.js

Closes https://github.com/4teamwork/opengever.core/issues/3014

Fix filetree scroll position of current item.

---

README.rst
opengever/core/testing.py
opengever/core/tests/test_integration_testing_setup.py
opengever/repository/tests/test_reference_behavior.py
opengever/repository/tests/test_reference_prefix_manager.py
opengever/repository/tests/test_repositoryfolder.py
opengever/testing/integration_test_case.py
opengever/testing/tests/test_fixtures.py
opengever/testing/tests/test_integration_test_case.py

Tests should start anonymously by default, because:
- as a test reader, I want to see for each test with which user it runs  (as in BBD `As a dossier responsible, In order to .., I want to ..`)
- from a security / QA perspective I want to lead devopers to making an active decision for who this test should be
- as a developer I would like to have consistency between test-code and browser-code regarding who is the user under test.
``self.login`` is now also a context manager which resets to the prior security. This makes it easier to do authenticated preparations in the ``setUp`` method without the side effect the the user is now authorized in the test method.

Integration testing: start tests anonymously.

---

docs/HISTORY.txt
opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/ftw.tabbedview.pot
opengever/core/profiles/default/types/opengever.inbox.forwarding.xml
opengever/core/profiles/default/types/opengever.task.task.xml
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/tests/test_bumblebee_gallery.py
opengever/task/browser/related_documents.py
opengever/task/upgrades/20170627091144_use_task_related_documents_proxy_view/upgrade.py

This PR adds the bumblebee-gallery view for the relateddocuments-tab which will be used by `opengever.task.task` and `opengever.inbox.forwarding`.
closes #3043

Add bumblebee gallery view for related documents tab on tasks.

---

docs/HISTORY.txt
opengever/dossier/dossiertemplate/form.py

While creating a dossier from a template, the user fills out fields on different wizard steps. Each step requires a new request. In the first step, the user chooses which dossiertemplate he wants to add, in the second step he fills out the dossier-fields prefilled from the choosen dossiertemplate and then he can save the dossier. We use an object-storage to retrive the dossietemplate in the next request. In some cases, this object looses its acquisitionwrapper which ends in an exception.
To fix this issue, we changed the implementation to use a path-storage and we retrieve the object in each request through traversing.
Issuer: https://extranet.4teamwork.ch/support/kunde-stadt-nidau/tracker/54
See related sentry issue: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3436/

Fix an issue where creating a dossier from template ended in an exception.

---

docs/HISTORY.txt
opengever/document/browser/overview.py
opengever/document/browser/templates/related_documents.pt
opengever/document/document.py
opengever/document/tests/test_overview.py

... also improve overview's `get_css_class` method.
When adding / editing a document (let's say A), related documents
(sat B and C) can be selected. These are listed under "related
documents" in the document overview (A lists B and C)..
Those related objects should list the documents which are related to
them as well (B and C should display A as well).
TODO: Add CSS assets to style the list of documents
Resolves: #1498 
See also: https://github.com/4teamwork/plonetheme.teamraum/pull/559

Add related documents method to document overview

---

docs/HISTORY.txt
opengever/task/response_syncer/workflow.py
opengever/task/tests/test_response_syncer.py

Closes #3097. 
This problem has been "introduced" with the syncer refactoring (see #2828).

Make sure that remote task state changes are synced to globalindex

---

docs/HISTORY.txt
opengever/base/schema.py
opengever/meeting/tests/test_meeting.py

This PR fixes an issue when creating meetings that don't have an end date.
Fixes #3102.

Fix datetime converter when input is empty.

---

docs/HISTORY.txt
opengever/globalindex/model/task.py
opengever/tabbedview/helper.py
opengever/tabbedview/tests/test_tasklisting.py

For tasks inside a dossier/subdossier with umlauts in the title the task listing rendering has failed with the following traceback:
```
Module ftw.tabbedview.browser.tabbed, line 167, in listing
Module ftw.tabbedview.browser.listing, line 124, in __call__
Module ftw.tabbedview.browser.listing, line 274, in render_listing
Module ftw.table.utils, line 102, in generate
Module ftw.table.utils, line 213, in get_value
Module opengever.tabbedview.helper, line 126, in linked_containing_maindossier
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 5: ordinal not in range(128)
```
@elioschmutz  💰 -> 🐷 , …

Fix UnicodeEncodeError in task listings

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/menu.py

Nobody, not even a Manager, should change the "layout" property via the UI (contentmenu), therefore it makes sense to completely disable this menu-item.
This fixes #3101.

Disable the displaymenu-item in contentmenu for all types.

---

docs/HISTORY.txt
opengever/document/browser/overview.py
opengever/document/document.py
opengever/document/tests/test_overview.py

Skip proposal and task from the back relations list. Closes #3112.
A more specific relation catalog query is not possible, because the relation field on the task and the proposal schema have the same name than the one in the `IRelatedDocuments` behavior. Therefore we have to filter the list afterwards.

List only documents as related_documents in the documents overview.

---

docs/HISTORY.txt
opengever/core/profiles/default/rolemap.xml

It is not necessary to refedine roles alredy defined by plone.
Also remove comments from profile-merge to allow sorting the roles alphabetically.

Cleanup rolemap, don't redefine plone roles.

---

versions.cfg

opengever.core was added to the versions.cfg while releasing 2017.3.0 in
order to let it appear in the versions.cfg of the tag for use in
buildout extends.
It was not removed after the release.  
@phgross 💣 🐷 😏

Remove opengever.core version pinning.

---

docs/HISTORY.txt
opengever/core/profiles/default/registry.xml
opengever/core/profiles/default/types/opengever.dossier.templatefolder.xml
opengever/core/upgrades/20170629160641_remove_dossier_behavior_for_template_folder/types/opengever.dossier.templatefolder.xml
opengever/core/upgrades/20170629160641_remove_dossier_behavior_for_template_folder/upgrade.py
opengever/core/upgrades/20170703121423_allow_zipexport_on_template_folder/registry.xml
opengever/core/upgrades/20170703121423_allow_zipexport_on_template_folder/upgrade.py
opengever/document/base.py
opengever/dossier/base.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/templatefolder/subscribers.py
opengever/dossier/templatefolder/templatefolder.py
opengever/dossier/tests/test_templatefolder.py
opengever/journal/tests/test_integration.py
opengever/setup/profiles/default_content/content_creation/01_default_content.json

A templatefolder is a contenttype who is displaying a tabbedview... but it have been implemented as a Dossier.
That means, the templatefolder inherits the whole behavior of a dossier and also its schema.
But we don't want the schema of a dossier and we don't want the behavior of a dossier. We just want a templatefolder with templates.
Why this change?
Initially, the responsible field of a templatefolder was prefilled with
a dummy-user to be able to create an initial templatefolder while
installing opengever.
This was a workaround because the responsible field is required and the IDossier interface defines it and the templatefolder is a dossier :-)
Editing the templatefolder raised an exception because the responsible user
could not be found. One solution would have been to adjust the …

Remove dossier inheritance of templatefolder

---

opengever/core/testing.py
opengever/core/tests/test_integration_testing_setup.py

The problem is that we use the same connection / transaction for preparation as for performing a request with `ftw.testbrowser`.
This means that we may already have changed objects on the connection, but the change is not from within the request.
We fix that by marking all objects which are already marked as changed on the current as safe for CSRF. This also means that the auto protection does no longer trigger within the test for the followed requests.
This PR also activates the transaction interceptors savepoint simulation. This is necessary because `plone.protect` calls `transaction.abort()` when the CSRF validation fails. We want the state to be rollback to before the request in this state. The savepoint simulation does exactly that.
Based on …

Integration testing support for plone.protects auto CSRF protection

---

test-plone-4.3.x.cfg
test-xml-convention.cfg

It is important that we pin all versions in order to have a reproducable state. The `versions.cfg` is the master and all testing jobs should extend from it. This will make it easier to branch off of an old release and the tests will have a higher chance to still pass.
- plone tests
- remove un-pinnings from `test-plone-4.3.x.cfg`
- no longer use [ftw-buildout's `test-versions.cfg`](https://github.com/4teamwork/ftw-buildouts/blob/master/test-versions.cfg)
- it is already included in [ftw-buildout's `test-plone-4.3.x.cfg`](https://github.com/4teamwork/ftw-buildouts/blob/master/test-plone-4.3.x.cfg#L6)
- we want to be in charge of our versions in the `versions.cfg`
- xml convention test: use `versions.cfg`
The docs-tests seem to require the newest versions of Sphinx; do we want to include …

Ensure test versions are used correctly.

---

docs/HISTORY.txt
opengever/bumblebee/configure.zcml
opengever/bumblebee/document.py
opengever/bumblebee/tests/test_document_adapter.py
opengever/document/extra_mimetypes.py
opengever/policy/base/profiles.zcml
opengever/policy/base/profiles/mimetype/metadata.xml
opengever/policy/base/profiles/mimetype/mimetypes.xml
opengever/policy/base/upgrades_mimetypes/20170705162948_use_outlook_eml_file_for_bumblebee_conversions_if_available/mimetypes.xml
opengever/policy/base/upgrades_mimetypes/20170705162948_use_outlook_eml_file_for_bumblebee_conversions_if_available/upgrade.py

Dieser PR benutzt die Originale .msg-Datei bei Mails sofern diese vorhanden ist.
Er stellt u.a. einen Upgradestep zur Verfügung welcher vorhandene Mails mit .eml Dateien neu konvertiert.
closes #3023

Use OGMail original_message-file for bumblebee-conversion if available.

---

sources.cfg
test-plone-4.3.x.cfg

Update sources.cfg to extend from 4teamwork-psc.cfg, configuring our PSC as source in find-links and adding the authentication extensions.
In order for this to work, each host must have a `~/.pypirc` with the necessary credentials configured.

Include psc configuration in sources.cfg

---

docs/HISTORY.txt
opengever/task/response_syncer/comment.py
opengever/task/tests/test_comment_response.py

Because a forwarding predecessor is always closed and stored in the yearfolder, comments made on the task should not be synced to the "predecessor".
Closes #3133

Do not sync comments to a predecessor forwarding.

---

docs/HISTORY.txt
opengever/base/behaviors/classification.py
opengever/base/behaviors/lifecycle.py
opengever/dossier/handlers.py
opengever/journal/handlers.py
opengever/repository/subscribers.py
opengever/repository/tests/test_sharing.py

Since the new plone version, a LocalRolesModified event is fired when changing local roles on a object (see https://github.com/plone/plone.app.workflow/commit/cc75f6d96584462d8a74017769b6225e46b34384). Because the `LocalRolesModified` inherits from `ObjectModifiedEvent`, all IObjectModifiedEvent subscribers, wich assumes that the event.descriptions provides an list `attributes`, are called as well and are failing. Closes #3119.

Ignore LocalRolesModified events in repositoryfolder ModifiedEvent subscribers

---

docs/HISTORY.txt
opengever/base/service.py
opengever/base/tests/test_api.py
opengever/document/static/officeconnector.js

Now that OfficeConnector (since 1.2.1) also does a WebDAV LOCK , change the javascript to check for that instead.
The document status JSON endpoint now also includes the document lock status.

Amend the OfficeConnector JS to only refresh after a LOCK is acquired

---

docs/HISTORY.txt
opengever/document/browser/download.py
opengever/document/events.py
opengever/document/tests/test_download.py
opengever/journal/handlers.py
opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/opengever.journal.pot
opengever/journal/tests/test_integration.py
opengever/mail/tests/test_mail_download_copy.py

It's not possible to determine which file version the user downloaded from the journal entries.
This is improved by adding the version number (or `current version` if the downloaded version was the working copy) to the title.
Resolves: #3075

Add version number to journal's download entries

---

docs/HISTORY.txt
setup.py

- Cleanup changelog after bugfix release 2017.3.1 (Release has been created via `2017.3-stable` branch)
- Bump next version to 2017.4.0.

Cleanup changelog after bugfix release and bump version for next release

---

docs/HISTORY.txt
opengever/ogds/base/tests/test_cookie_storage.py
opengever/ogds/base/utils.py

This fix an issue, which the OrgUnit selector had shown a "wrong" current orgunit in some cases, for example when viewing the personal overview.

Define cookie path when setting the current orgunit id in the cookie.

---

docs/HISTORY.txt
opengever/base/tests/test_require_login.py
opengever/core/hooks.py
opengever/core/upgrades/20170717182153_enable_secure_flag_for_cookies/upgrade.py

Activate option `Only Send Cookie Over HTTPS` in the acl_users session plugin.
Closes https://github.com/4teamwork/opengever.ftw/issues/37

Enable secure flag for cookies.

---

opengever/disposition/tests/test_excel_export.py

As per https://bitbucket.org/openpyxl/openpyxl/src/0f8537998f95c9d8d44913c2edb367516b799d4a/openpyxl/worksheet/worksheet.py?at=default&fileviewer=file-view-default#worksheet.py-302 we should not use cell-level fetching in openpyxl.

Squelch an openpyxl deprecation warning.

---

docs/HISTORY.txt
opengever/meeting/proposal.py

The repository folder title should be stored as unicode into the proposal SQL in order to prevent encoding issues when testing with sqlite.
This change is similar to what #3109 changed in the task globalindex.
I could only reproduce the problem with an sqlite database. The postgres driver seems to handle enconding in this case. I want this to be fixed so that we can use non-ASCII strings in tests, such as it will be introduced with the integration testing fixture.
The error I fix is:
```python
File "/Users/jone/projects/python/cache/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 400, in run_layer
setup_layer(options, layer, setup_layers)
File "/Users/jone/projects/python/cache/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/run …
```

Ensure unicode in proposal SQL.

---

docs/HISTORY.txt
opengever/inbox/browser/tabs.py
opengever/inbox/tests/test_tabs.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview.pot

Because documents inside the inbox does not have a meaningful reference number, the recently introduced column should be removed for the document listing of inboxes.

Disable reference number column in the document listing of the inbox.

---

docs/HISTORY.txt
opengever/document/base.py
opengever/document/browser/actionbuttons.py
opengever/document/browser/overview.py
opengever/document/tests/test_document.py
opengever/document/tests/test_document_tooltip.py
opengever/mail/browser/download.py
opengever/mail/browser/mail.py
opengever/mail/mail.py
opengever/mail/tests/test_mail_download_copy.py

- Fix mail download: Convert LF to CRLF only for EML mails.
- Enable *.msg download for all download copy links, also in the tooltip or bumblebeeoverlay

Fix original message (*.msg) download

---

docs/HISTORY.txt
opengever/core/upgrades/20170720153900_cleanup_i_creator_interfaces_from_relation_catalog/upgrade.py

With #2949 the `ICreator` and `ICreatorAware` interfaces has been removed. But because the zc.relation cataog persists provided interfaces, the removed interfaces has been removed manually from the zc.relation catalog.
Closes #3164

Add upgradestep to cleanup no longer existing interfaces from zc.relation catalog.

---

docs/HISTORY.txt
opengever/meeting/committee.py

The token of a vocabulary term must be a bytestring because it will be sent over HTTP. The VocabularyTerm class casts tokens to bytestring in it's __init__, which will throw an encoding error when the token is a unicode containing non-ASCII characters.
Simply encoding the unicode as utf-8-bytestring will not work because the z3cform validation will fail and not allow to select the term.
A good token does only contain ASCII characters while beeing reproducable and hopefully not conflicting with other terms. Therefore I changed the token to be a normalized string generated from the group ID.
It seems that groups usually have no title. We should not fallback to the normalized string then but to the original group id.
---
Without this fix, the encoding problem can be produced by editing a any …

Fix unicode error in committee group vocabulary.

---

README.rst

The integration testing example in the readme was wrong regarding browser login:
We have greed to pass the browser to `self.login` and not use `browser.login` in #3053.

Update integration testing example in readme.

---

docs/HISTORY.txt
opengever/ogds/base/ou_selector.py
opengever/ogds/base/tests/test_ou_selector.py

Otherwise the fixes in #3151 has no effect for users with an existing cookie, because the current orgunit cookie has a validity of 30 days.

Rename current orgunit cookie, to invalidate existing cookies.

---

docs/HISTORY.txt
opengever/ogds/base/sync/ldap_util.py

With #2985 the new property `lookup_groups_base` is now respected
during OGDS group synchronisation. But the current implementation
failed when group_recurse is enabled but the property `lookup_groups_base` is not set. This PR fixes the issue (see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3611/).

Fixed OGDS group sync, when lookup_groups_base is not defined.

---

opengever/dossier/tests/test_activate.py
opengever/dossier/tests/test_adapters.py
opengever/dossier/tests/test_archiver.py
opengever/dossier/tests/test_base.py
opengever/dossier/tests/test_businesscasedossier.py
opengever/dossier/tests/test_catalog.py
opengever/dossier/tests/test_copy_dossier.py
opengever/dossier/tests/test_deactivate.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py
opengever/testing/tests/test_fixtures.py
opengever/testing/tests/test_integration_test_case.py

I've started rewriting the `opengever.dossier` tests with integration testing.
Part of #3024
I'd like to have this PR merged as soon as possible because we need the fixture for basing other tests on.
**Enhance the integration test case base class:**
- catalog helpers
- workflow state helpers
- property for accesing all dossier tasks
- support for generic-setup-profile based feature flags; add filing number feature
- `IntegrationTestCase.clock` decorator
**Fixture enhancements**
- an empty dossier, which can be used for setting up a specific testing scenario
- a "secretariat user", who can archive / unarchive dossiers
- new subdossiers
- tasks and subtasks
- documents in main dossiers, subdossier and task
- proposal
- use UTC timezone as base for everything, since we should always use …

Integration tests for opengever.dossier

---

docs/HISTORY.txt
opengever/task/browser/overview.py
opengever/task/tests/test_overview.py

Converts web intelligent text to html for line breaks and clickable links.
URLs embedded at the end of sentences remain an issue.
Resolves: #3054
See also: https://github.com/plone/plone.intelligenttext/issues/4

Improve linebreak display in tasks

---

docs/HISTORY.txt
opengever/bundle/sections/progress.py

Also includes current memory consumption (RSS) in the output whenever import progress is logged.

Bundle import: Display current memory usage (RSS) in progress logger.

---

opengever/core/tests/test_relations.py

Because the zc.relation cataog persists provided interfaces, the removed interfaces has been cleaned up manually from the zc.relation catalog. This test should help to not forget the manual  cleanup, when removing an interface.
See #3165 for more informations.

Add test to detect interface removals without cleaning up the relation catalog

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/tests/test_agendaitem.py
sources.cfg

~⚠️ _requires https://github.com/4teamwork/plonetheme.teamraum/pull/564_~
ℹ️ _part of #2829_ 
Update the meeting view so that the proposal document is listed and can directly be edited.
Changes:
- Show proposal document right beneath proposal; the tooltip allows for fast checkout and edit.
- Make proposal title text bold, because it is the important part of the proposal.
- Prefix attachments with a "Attachments"-label; this was not clear enough.
- Move Attachment-Toggle from a separate "Documents" column to the left side (into the number column), because a toggle should be at the left side from a UX viewpoint and because the documents column did consume too much space.
- These changes are feature-flagged with the word-changes-feature.

Meeting word: add proposal document to meeting view

---

docs/HISTORY.txt
opengever/meeting/browser/proposalforms.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_proposal.py

Add a option for checking out and external-editing the proposal document
of newly created proposals. The option is enabled by default.
As discussed in #2829
Not sure why there is a CSS bug; I'm using a regular z3cform checkbox widget as it is used in other places. Probably needs to be fixed in the theme.

SPV word: checkout proposal document after creating proposal.

---

docs/HISTORY.txt
opengever/bundle/sections/constructor.py
opengever/bundle/sections/fileloader.py
opengever/bundle/sections/post_processing.py
opengever/bundle/tests/assets/business_rule_violations.oggbundle/documents.json
opengever/bundle/tests/test_business_rule_violations.py
opengever/bundle/tests/test_section_constructor.py
opengever/bundle/tests/test_section_fileloader.py

Avoid keeping references to the constructed objects in hope that this will reduce the memory footprint of large migrations.
Also fixes an issue where failures to construct objects because of disallowed subobject type could not be logged properly.
Recommendation: Review commit by commit.

Bundle import: Don't unnecessarily keep references to persistent objects

---

docs/HISTORY.txt
opengever/dossier/base.py
opengever/dossier/tests/test_base.py
opengever/dossier/tests/test_retention_expiration.py

This PR refactors the function: `earliest_possible_end_date`.
Beside an overall code-refactoring, the following changes where made on code-optimizations:
**Objects of dossiers**
Objects of Dossier-brains are not necessary because the start and end-date are in the catalog metadata
**Convert datetime objects into date objects if necessary**
All dates are already date-objects. Otherwise, there is something wrong in consistency
**Check if dossier start-date is available or not**
We filter out None-values and get the max-date. There is no need to do this check anymore.
**Sort end-dates**
Thats not necessary because the max-function does not require a sorted list.
closes #3107

Refactor the function: earliest_possible_end_date.

---

docs/HISTORY.txt
opengever/base/browser/resources/tooltip.js
opengever/document/widgets/tooltip.py

Closes https://github.com/4teamwork/opengever.core/issues/2825
The tooltip may call the content with a logged out user. This leads
to an unwanted rendering of the whole login page in the tooltip.
So add a response header to make sure the response is a true tooltip response
and redirect the user to the login page with a simple reload.

Handle unknown asynchronous tooltip response.

---

docs/HISTORY.txt
opengever/advancedsearch/advanced_search.py
opengever/advancedsearch/configure.zcml

Use ZCML instead of grok for registration (part of #3205).

Ungrok opengever.advancedsearch.

---

opengever/meeting/proposal.py

When updating the repository folder title in the SQL row of a proposal, the title must be saved as unicode.
Fixes the same issue as in #3143, but when updating the model.

Fix encoding error when updating repository folder title on proposal.

---

docs/HISTORY.txt
opengever/base/browser/exposator.py

JQuery expose uses a default z-Index of 9998 (http://jquerytools.github.io/documentation/toolbox/expose.html). The ``ftw.showroom`` renders its overlay with a z-index of 8000.
The solution for the problem is to set the z-index of the expose lower than the z-index of the ``ftw.showroom``
closes #3208

Fix showroom overlay within an activated exposator.

---

docs/HISTORY.txt
opengever/core/profiles/default/rolemap.xml
opengever/core/tests/test_folder_contents.py
opengever/core/upgrades/20170724104729_disallow_reordering_on_root__only_managers_are_whitelistet/rolemap.xml
opengever/core/upgrades/20170724104729_disallow_reordering_on_root__only_managers_are_whitelistet/upgrade.py

Fixes #3159
Before other roles like `Contributor`, 'Editor' and `Reviewer` were able to reorder items on the plone root. 
This is now no longer possible. The folder_contents View on the Plone root is only accessable with the `Manager` role.

Only the Manager can access the folder_contents on the plone root.

---

docs/HISTORY.txt
opengever/meeting/proposal.py

Fix another encoding error when syncing a proposal with the SQL record.
@phgross I wanted to fix this one too in #3200, but amended the wrong commit 🙈

Fix encoding error when syncing proposals with SQL.

---

docs/HISTORY.txt
opengever/dossier/archive.py
opengever/dossier/tests/test_archiver.py

Since #2972 the dossier resolver is an named adapter, and should be
gotten with the `get_resolver`. But the use of the DossierResolver in
the ArchiveForm has not been updated and failed therefore. This PR
fixes this issue and also add tests for the ArchiveForm.

Fix ArchiveForm, when resolving a dossier.

---

docs/HISTORY.txt
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20170803115957_remove_properties_action_on_personal_overview/actions.xml
opengever/core/upgrades/20170803115957_remove_properties_action_on_personal_overview/upgrade.py

This PR removes the "Properties"-action on the personal overview.
closes #3173

Remove "Properties"-action on personal overview.

---

docs/HISTORY.txt
opengever/meeting/tabs/membershiplisting.py
opengever/tabbedview/sqlsource.py
opengever/tabbedview/tests/test_sqlsource.py

This PR allows to sort by sqlalchemy columns and activates sorting on memberships-listing.
closes #3161

Fix sorting by sqlalchemy column

---

README.rst
bin/.gitignore
bin/remove-test-cache
opengever/core/cached_testing.py
opengever/core/testing.py
setup.py
versions.cfg

When developing ``opengever.core``, a developer often runs single test module,
with ``bin/test -m opengever.dossier.tests.test_activate`` for instance. This will set up a complete fixture each time. In order to speed up the feedback loop when developing, we try to cache the database after setting up the fixture.
This will speed up the test runs, but it also makes the result inaccurate: if the cachekeys do not detect a relevant change, we may not realize that something breaks.
Because the results are not accurate and this is an experiment, the feature is considered experimental and therefore disabled by default.
You can enable the feature by setting an environment variable:
```sh
GEVER_CACHE_TEST_DB=true bin/test -m  opengever.dossier.tests.test_activate
```
You can manually remove / …

Cache integration testing setup

---

docs/HISTORY.txt
opengever/base/browser/search.py
opengever/base/tests/test_search.py

The filter_query, which is customized by GEVER to handle some query parameters separate, has been refactored in the plone release. The previous method `filter_query` has been renamed to `_filter_query` and the method `filter_query` is now a wrapper of the `_filter_query`
method. Therefore the fix is only a rename of our customized `filter_query` method (see https://github.com/plone/plone.app.search/pull/18).
I've also checked, if the customization is still necessary and it is (date range queries, subject queries, empty SearchableText handling)
Closes #3220

Fixed bug in search when sorting on relevance.

---

opengever/dossier/tests/test_deactivate.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_word.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

~~🚧 _includes #3198: Cache integration testing setup_~~
~~🚧 _includes #3212: Fix encoding error when syncing proposals with SQL._~~
- Rewrite test_proposal with integration testing and fixtures.
- Extract word proposal into test_proposal_word.py, rewrite as integration tests with fixture.
- Extend fixture with meeting proposals and committes, as needed for the tests.
- Add helper methods to integration base class, as needed.

Rewrite meeting proposal tests as integration tests.

---

docs/HISTORY.txt
opengever/base/restricted_vocab.py

Pass `context` (received in `__call__`) to methods that require it instead of setting `self.context`. 
The `RestrictedVocabularyFactory` is instantiated and [kept as a module global](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/behaviors/classification.py#L147-L151). Than means setting `self.context` did keep a reference to a Plone object much longer than necessary, preventing it from being garbage collected.

Fix leaking reference in RestrictedVocabularyFactory

---

docs/HISTORY.txt
opengever/bundle/sections/post_processing.py

The post-processing section (creating initial versions) previously didn't log progress and memory usage. Since memory consumption can be quite high for this section, I'm adding this logging here as well.

Bundle import: Also log progress and RSS during post-processing.

---

opengever/meeting/tests/test_proposal_word.py
opengever/testing/integration_test_case.py

The experience of the last days have shown that it is not wise to let long tests fail.
The main problem is that the duration can vary quite a bit, leaving us with too many flaky tests. While rewriting more and more tests with integration testing a trend to having more flaky tests is becoming apparent.
Those flaky tests are annoying and there is not enough room for fixing the issues: some actions just take that long in GEVER and optimizing those is often out of scope of a specific change.
The idea for starting that in the first place was to motivate a developer, who just writes a tests, to try to make it fast and think about the impact of certain test setups.
But at this point I see no way to achieve that without having constantly flaking tests on the CI server or foreign failing tests …

Remove letting long tests fail.

---

docs/HISTORY.txt
opengever/dossier/browser/tabbed.py
opengever/dossier/templatefolder/configure.zcml
opengever/dossier/templatefolder/tabs.py
opengever/tabbedview/browser/bumblebee_gallery.py

This PR adds the bumblebee-gallery view to the proposaltemplate tab.
⚠️  It also refactors the `list_view_name` method of the `BumblebeeGalleryMixin`.
See #3251 for more information.
closes #3251

Add bumblebee gallery view for proposaltemplate.

---

docs/HISTORY.txt
opengever/meeting/model/meeting.py
opengever/meeting/protocol.py
opengever/meeting/tests/test_meeting_view.py

This PR sorts the meeting participants alphabetically in meeting-view.
Before:
After:
closes #3160

Sort meeting participants alphabetically in meeting-view.

---

docs/HISTORY.txt
opengever/meeting/browser/proposalforms.py
opengever/meeting/tests/test_proposal_template.py
opengever/meeting/tests/test_proposal_word.py
opengever/testing/fixtures.py

This PR fixes an issue when creating proposals from a template where the template has umlauts or other non-ascii chars in its title. The term title of the vocabulary used to enumerate the available was `utf8` but should have been decoded to unicode when read from the catalog.
Fixes #3261.

Fix a unicode error when creating proposals from a template.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/tests/test_agendaitem_word.py

This pull-request improves the behavior and appeareance of the
edit-document button in the meeting view. The button is available per agenda item. When clicked, the proposal document is checked out and opened with office connector.
New behavior of the button:
- ~~The button is available when the agenda item is in the "pending"
state or in the "revision" state.~~
- The button is only visible when the user has the permission to edit the document.
- The button is active as long as I can checkout and edit.
- The button is inactive when the document is checkout out by somebody
else in order to communicate to the user that he could edit the
document if it wouldn't be checked out.

Word meeting: Improve edit-document-button behavior in meeting view.

---

docs/HISTORY.txt
opengever/bumblebee/document.py
opengever/document/browser/actionbuttons.py
opengever/document/document.py
opengever/mail/browser/mail.py
opengever/mail/browser/send_document.py
opengever/mail/mail.py
opengever/mail/tests/test_senddocument.py
opengever/mail/zipexport.py
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api.py

Dieser PR implementiert die `original_message` beim versenden einer E-Mail.
Zudem gibt es zwei commits mit einem Refactoring. Die Implementation für `original_message` wurde bereits mehrfach wiederholt. 
closes #3181

Use original message when sending a mail as an attachement

---

docs/HISTORY.txt
opengever/dossier/base.py
opengever/dossier/tests/test_base.py

This PR fixes an issue in `earliest_possible_end_date` if there are `date` and `datetime` objects to compare.
closes #3238

Fix error in earliest_possible_end_date if there are date and datetime objects to process.

---

docs/HISTORY.txt
opengever/dossier/browser/overview.py
opengever/dossier/tests/test_overview.py
opengever/trash/remover.py
opengever/trash/tests/test_remove_conditions.py

Dieser PR fixt zwei Stellen im GEVER, welche gelöschte Backlinks nicht korrekt berücksichtigen.
Siehe PR #3108, dort wird über die Thematik diskutiert.
Dieser PR löst das Problem, so wie es in der Plone-Dokumentation beschrieben wird, indem nicht mehr existierende Referenzen gefiltert werden.
Die Ursache des Problems ist jedoch, dass gelöschte Backreferenzen nicht aus dem Referenz-Katalog gelöscht werden. Diese Implementation wäre mit mehr Aufwand verbunden und sollte in einem eigenen Issue behandelt werden da dies ein generelles Problem (oder Feature ;-) ) ist.
closes #2706

Fix broken code with removed backreferences.

---

docs/HISTORY.txt
opengever/dossier/handlers.py
opengever/dossier/tests/test_catalog.py

This PR reindexes the `is_subdossier` index after moving the dossier.
closes #3224

Reindex is_subdossier-index after moving the dossier.

---

README.rst
docs/HISTORY.txt
docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/schemas/dossiers.schema.json
opengever/core/upgrades/20170809094247_add_external_reference_index_to_catalog/upgrade.py
opengever/document/indexers.py
opengever/document/tests/test_indexers.py
opengever/dossier/behaviors/dossier.py
opengever/dossier/config.py
opengever/dossier/indexers.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_dossier_byline.py
opengever/dossier/tests/test_indexer.py
opengever/dossier/viewlets/byline.py

Some institutions use an unambiguous reference field to find dossiers.
The composition of this field varies between the institutions using it
and therefore cannot be generated but is furnished by the user.
Overview of the made steps:
-  Zusätzliches TextLine Feld external_reference zum IDossier behavior hinzufügen.
-  Der Wert soll im SearchableText aufgenommen werden.
-  Darstelllung in der Byline falls Wert vorhanden
-  Update API Schema Docs using `bin/instange dump_schemas` and `bin/build-docs-public`
-  Update `README.rst`
-  Ein separater Index `external_reference` wurde hinzugefügt zum indexieren der `IDossier.external_reference` so wie `IDocumentMetadata.foreign_reference`. (Eine Abfrage ist vorerst nur via API oder GET-Parameter möglich. Siehe Screenshot in der Besprechung.)
- …

Add external reference to Dossier and its index

---

docs/HISTORY.txt
opengever/bundle/cfgs/oggbundle.cfg
opengever/bundle/sections/garbage_collect.py
opengever/bundle/sections/post_processing.py
opengever/bundle/transmogrifier.zcml

These changes aim to reduce the memory (RSS) footprint of a bundle import, particularly the high-water-mark.
While I was able to clean up some leaking references in earlier pull requests (x, y), that wasn't enough to significantly bring down max. memory usage.
At some point I discovered that re-setting the Plone site using the `getSite()` hook finally manages to get rid of those leaking references, and allows the Python garbage collector to do its job. In addition, the `cPickleCache` also needs to be garbage collected periodically.
So, in regular intervals the following things need to happen:
- Creating transaction savepoints
- Re-setting the Plone site using setSite()
- Garbage collecting the cPickleCache
- Python garbage collection (optional, doesn't effect high-water-mark)
I can't yet …

Bundle Import: Reduce memory footprint

---

README.rst
opengever/testing/fixtures.py
opengever/testing/tests/test_dump_fixture_structure.py

1) Fix the tree in the fixture documentation, so that it works with real Plone objects as well as SQL wrappers. The problem was that some were prefixed with the Plone site path, others were relative to the Plone site. Since the IntegrationTestCase traverses on the Plone site it is correct to make all paths relative to the Plone site.
2) Let the test fail if the readme was udpated when running the test. This does only fail once and then leave an uncommitted, changed readme behind, which must be committed be the developer. On the CI-server it will fail when a PR changes the fixture but misses the readme update.

Fixture: improve documentation and assert readme updated.

---

opengever/testing/integration_test_case.py
opengever/testing/tests/test_integration_test_case.py

ExtJS is implemented in JavaScript, but ftw.testbrowser does not support JavaScript.
In order to test listing tabs anyway, ExtJS is deactivated for integration tests so that ftw.tabbedview renders a simple table, which is testable with ftw.testbrowser.
ExtJS is also deactivated in functional testing, so this will behave the same.

Disable ExtJS in integration testing.

---

opengever/base/browser/translated_title.py
opengever/contact/browser/configure.zcml
opengever/contact/browser/contact_view.py
opengever/contact/browser/contactfolder_forms.py
opengever/contact/browser/templates/contact_view.pt
opengever/contact/configure.zcml
opengever/contact/contact.py
opengever/contact/contactfolder.py
opengever/contact/handlers.py
opengever/dossier/templatefolder/configure.zcml
opengever/dossier/templatefolder/templatefolder.py
opengever/inbox/browser/configure.zcml
opengever/inbox/browser/inbox_forms.py
opengever/inbox/browser/inboxcontainer_forms.py
opengever/inbox/container.py
opengever/inbox/inbox.py
opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/configure.zcml
opengever/meeting/committeecontainer.py
opengever/repository/browser/configure.zcml
opengever/repository/browser/repositoryfolder_forms.py
opengever/repository/browser/repositoryroot_forms.py
opengever/repository/repositoryfolder.py
opengever/repository/repositoryroot.py

This PR ungroks `opengever.contact`.
Because of dependencies, I had to ungrok all the TranslatedTitle-Forms, too.
related to #3205

Ungrok opengever contact with TranslatedTitle-Forms

---

docs/HISTORY.txt
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/browser/configure.zcml
opengever/tabbedview/tests/test_bumblebee_gallery.py

Remove separate bumblebee fetch-views since they are no longer necessary because we no longer use grok.
see #3205

Remove separate bumblebee fetch-views

---

docs/HISTORY.txt
opengever/task/response_syncer/__init__.py
opengever/task/response_syncer/workflow.py
opengever/task/tests/test_response_syncer.py

This PR fixes an issue where the user is not able to change the workflow-state of a remote task.
It is possible, that the task-successor wants to reassign or close a synced task. This action will end up in an unauthorized error if the successor has no write permission on the remote task.
To fix this issue, we give more access to the user while updating the workflow.
It seems, that this issue have always existed: https://github.com/4teamwork/opengever.core/pull/2828/commits/cd0bd98226bf89083e5428197a00d54774389eed#diff-10e13c62c57ce071c5f962b24d62b024L121
closes #3242

Fix remote wf changes without permission

---

docs/HISTORY.txt
setup.py

The hotfix release has been created from the `2017.4-stable` branch.

Bump next version to 2017.5.0 and cleanup changelog after hotfixrelease

---

README.rst
development.cfg
docs/HISTORY.txt

This PR adds a simple wrapper script to enable cached testing on a per test-run basis. Motivation:
- i always forget the env-variable name and have to spend time figuring it out again 😢 
- i'd like to have access to a script that just remembers the name for me in an auto-completable, quick way
objections/suggestions?

Add bin/test-cached helper script to execute a chached test-run.

---

test-pydocstyle.cfg

Runs only on incoming files and uses our shared config.
Purposefully ignores tests, at least for now.
We could later do a different ruleset for the tests or somesuch.

Add a CI script to run pydocstyle on incoming files

---

bin/.gitignore
bin/git-fork-point
bin/pyflakes-ci
test-pyflakes.cfg

* Split the git fork point finding onto its own script
* Make a `bin/pyflakes-ci` script to be able to write unrestricted-by-buildout-internals bash
* Wrap that script with a trivial `bin/test-jenkins` via `collective.recipe.template`
* Fail per default
* Split up the parametres in a way which can be useful for future QA script code sharing
Closes #3299.

Fix and split up the pyflakes CI run script

---

docs/HISTORY.txt
opengever/advancedsearch/tests/test_search.py
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

The problem was introduced with the OGIP 15 (https://github.com/4teamwork/opengever.core/pull/2852), which turned all vocabularies (IVocabulary) into sources (ISource) to support a new kind of selection widget provided by ftw.keywordwidget.
With this change filtering for disabled OrgUnits went lost.
This PR brings back this feature.
I also slightly refactored the source a little bit, otherwise this change would introduced a lot of duplicated code. 
I also hat to fix a side effect on the advanced search form.
A test-odgs user was not properly configured, since a OrgUnit was missing.
This change basically no longer allows user without an OrgUnit, since it is required to build the query.
Fixes #3273

Filter results from disabled orgunits.

---

docs/HISTORY.txt
opengever/core/upgrades/20170822083925_set_missing_titles_on_private_root/upgrade.py

On my local machine I was only able to reproduce this state by setting manually `title_fr` and `title_de` to a empty string.
Hope I'm not missing anything. 
Closes #2911

Add upgrade step which fixes potential missing titles on opengever.private.root objects

---

docs/HISTORY.txt
opengever/base/viewlets/footer.pt

As discussed in https://4teamwork.slack.com/archives/C060FEYKA/p1502960325000375 we'd like to update the footer link and point it to this repo instead of https://github.com/OneGov/onegov.gever.
What about the link to CI?
It currently points to a view in Jenkins, but that view contains outdated and manually configured dependencies. I propose to:
- remove the link to CI in the footer
- also remove the view, i don't think that we use it anymore since CI-Governor has take over, also the list is fairly outdated
objections (@phabegger, @phgross , @lukasgraf, @jone)?

Point source-code link to 4teamwork/opengever.core.

---

opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
sources.cfg

The goal is to improve the meeting view when the word feature is enabled. This is done step by step. This pull request updates the styling and positioning of the agenda item table and its contents.
- Remove the "number" column and put the number in front of the title. This makes the view more compact.
- Add a tooltip on the meeting item number, telling that this is the meeting item number.
- Increase the font size of the agenda item title and number for better visual orientation.
- Separate headings in the agenda by adding a thick line between the sections.
- Style headings so that they are centered.
- Fix title editing dialog to support new DOM structure (JS).
Part of #2829

Update layout of agenda items in word meeting view.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/tests/test_agendaitem_word.py
sources.cfg

When agenda items are decided, the decision number should be shown in the meeting view, at the right side of the agenda item title.
Part of #2829 
Requires https://github.com/4teamwork/plonetheme.teamraum/pull/575

Word meeting: Show decision number in meeting view.

---

docs/HISTORY.txt
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/setup/sections/navigation.py

Fixes assignment of tree portlets to repo roots upon bundle import.
This was broken in #3196 when the `item['_object']` reference was removed. Also includes test to verify that repo root portlets get assigned properly.
Fixes #3287

Bundle import: Fix tree portlet assignment to repo roots.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting-noword.pt
opengever/meeting/tests/test_excerpt.py

Fix an issue with a css class that was used in two different places for different functionality, introduced in https://github.com/4teamwork/opengever.core/pull/3245. This broke the link to generate excerpts manually.
⚠️  depends on https://github.com/4teamwork/plonetheme.teamraum/pull/576
Closes #3320.

Fix an issue with conflicting css classes breaking a link.

---

docs/HISTORY.txt
opengever/journal/form.py
opengever/journal/tests/test_manual_entry.py

when contact feature is disabled.
Because the implemented feature to add a reference to contacts in the manual entry form only works for the "new contact type", we decided to hide the contact field for installations with a disabled feature flag.

Hide contact field in the manual journal entry form, 

---

docs/HISTORY.txt
opengever/tabbedview/sqlsource.py

Currently all expressions contain a string cast statement, even if the field is already a string column. This is unnecessary and leads to an issue with oracle backends (see traceback below). The new
implementation ads casting only for not stringy fields.
`DatabaseError: (cx_Oracle.DatabaseError) ORA-00906: missing left parenthesis`
Fixes https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3749/

Fix textfilter for sql table listings when using oracle backends.

---

opengever/meeting/browser/periods.py
opengever/meeting/browser/templates/periods.pt
opengever/meeting/tests/test_periods.py

This PR displays the edit period link only when the user is actually allowed to `Modify portal content` in the corresponding committee.
Closes #3319.

No longer display edit period button for unprivileged users.

---

docs/HISTORY.txt
opengever/document/browser/tabbed.py
opengever/document/tests/test_tabbed.py

The former implementation also calls the baseclass checks, but those
are wrong for the drag'n'drop replacing use case. A check for `add
portal content` permission makes no sense.

Fix Drag'n'Drop replacing for documents inside a resolved task.

---

docs/HISTORY.txt
opengever/core/profiles/default/registry.xml
opengever/core/profiles/default/types/ftw.mail.mail.xml
opengever/core/upgrades/20170831112449_remove_mail_tabbedview_fti_actions/upgrade.py
opengever/core/upgrades/20170831171547_add_mail_preview_tab_registry_flag/registry.xml
opengever/core/upgrades/20170831171547_add_mail_preview_tab_registry_flag/upgrade.py
opengever/mail/browser/configure.zcml
opengever/mail/browser/tabbed.py
opengever/mail/interfaces.py
opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/opengever.mail.pot
opengever/mail/tests/test_mail_previewtab.py
opengever/testing/integration_test_case.py

Because the bumblebee-preview and the preview tab, doesn't show the same results in some cases, some customers want to disable the preview `tab`. This is now possible with registry setting. But by default the preview tab is still visible.
Besides that:
- Replaced tabbedview FTI actions with a MailTabbedview
- Convert TestPreviewTab tests to integration tests

Add configuration option to hide the mail preview tab.

---

docs/HISTORY.txt
js_graph.py
opengever/base/browser/helper.py
opengever/base/browser/modelforms.py
opengever/base/browser/resources/breadcrumbs.js
opengever/base/tests/test_pathbar.py
opengever/base/viewlets/pathbar.pt
opengever/base/viewlets/pathbar.py
opengever/base/wrapper.py
opengever/contact/tests/test_participation.py
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20170831103505_install_breadcumbs_javascript/jsregistry.xml
opengever/core/upgrades/20170831103505_install_breadcumbs_javascript/upgrade.py
opengever/meeting/browser/meetings/excerpt.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/protocol.py
opengever/meeting/browser/members.py
opengever/meeting/model/membership.py
opengever/meeting/tests/test_pathbar.py
opengever/meeting/wrapper.py
opengever/private/tests/test_folder.py

This PR replaces the current implementation of the Pathbar viewlet, with our own to provide the following features:
- extend the crumbs with icons
- group the repository in to a dropdown list, to save space
It also no longer uses the breadcrumb view and uses the aq chain to generate the breadcrumb.
⚠️ Needs styling PR (https://github.com/4teamwork/plonetheme.teamraum/pull/573) merge first
Closes #2389

Breadcrumb rework

---

docs/HISTORY.txt
opengever/core/upgrades/20170904162218_replace_is_subdossier_field_index_with_a_boolean_index/upgrade.py
opengever/dossier/config.py

Closes #3345
The upgradestep also reindexes the value for all dossiers, which fixes some dossiers with a potential wrong value because of the bug #3224.

Replace is_subdossier FieldIndex with an BooleanIndex.

---

docs/HISTORY.txt
opengever/core/upgrades/20170905152010_add_document_to_agenda_item/upgrade.py
opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/proposalforms.py
opengever/meeting/command.py
opengever/meeting/committee.py
opengever/meeting/committeecontainer.py
opengever/meeting/exceptions.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/model/proposal.py
opengever/meeting/sources.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_committee_container_word.py
opengever/meeting/tests/test_committee_word.py
opengever/meeting/vocabulary.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

This PR adds support for ad-hoc agenda items for the word-meeting feature. The ad-hoc agenda-items have the same user-interface as proposal base agenda items:
They require an ad-hoc proposal template to be configured on the committee or committee-
container.
When the user creates an ad-hoc agenda item the proposal template is copied into the meeting dossier and the copy is linked to the agenda-item. That file can then be edited the same way as the document of a proposal. Currently when the agenda-item is deleted the document will remain in the meeting dossier.
2do:
- ~~[ ] delete from dossier when agenda-item is deleted?~~

Word-meeting: Create document from configured template for ad-hoc agenda items.

---

docs/HISTORY.txt
opengever/core/upgrades/20170831142434_add_agenda_list_items_to_meetings/upgrade.py
opengever/meeting/browser/meetings/agendaitem_list.py
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting-noword.pt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/command.py
opengever/meeting/exceptions.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/generateddocument.py
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_agendaitem_list.py
opengever/meeting/tests/test_meeting_view_word.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/testing/fixtures.py

* Add a generated document schema relation for agendalist item documents
* Generate documents if they do not exist
* Amend the meeting views for the two-stage workflow
* Link to the download views of generated documents
* Embed generated documents in zip exports of meetings (or generate if none)
Depends on 4teamwork/plonetheme.teamraum#579
Closes #3331.

Generate and store agendalist item documents

---

versions.cfg

Used by the new ftw.zipexport dependency rfc6266 (see #3351).

Add missing pinning of LEPL.

---

opengever/core/upgrades/20170906100343_add_agenda_list_items_to_meetings/upgrade.py

The upgrade has been merged in orphaned state. Schemamigrations currently
can't handle installing orphaned upgrade, so this upgrade was skipped. We
touch the upgrade and add a guard for systems where it has been previously
installed.

Touch orphaned upgrade, add safeguard.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_agendaitem_word.py

This PR adds functionality to return *one* excerpt to the proposer/to the proposal's dossier.
⚠️  Requires styling from https://github.com/4teamwork/plonetheme.teamraum/pull/582.
The excerpt listing of an agenda-item now has a button behind each excerpt to return it:
Returning requires a confirmation:
After returning the excerpt will be copied and linked to the dossier. Edits on the proposal side will be synced to the copy in the dossier.
The returned excerpt is highlighted in the listing:
This PR re-uses existing functionality that was already present for the of auto-generated excerpts. Thus the UI is a bit limited but will most likely be expanded/improved upon in future PRs.
Part of https://github.com/4teamwork/opengever.core/issues/2829.

Add functionality to return an excerpt to the proposer

---

docs/HISTORY.txt
opengever/tabbedview/browser/base_tabs.py
opengever/tabbedview/tests/test_base_tabs.py

During the opengever.tabbedview ungrok work (#3239), the `BaseCatalogListingTab` has been reworked and does no longer inherit from the GeverTabMixin first. Therefore the custom_sort method from `ftw.tabbedview.browser.listing` has been called instead of the GeverTabMixin.custom_sort, which provides custom sorting for `reference`, `sequence`, users etc.
Closes #3356

Fix custom sort for catalog listing tabs.

---

docs/HISTORY.txt
opengever/task/tests/test_response_viewlet.py
opengever/task/viewlets/response.py
opengever/task/viewlets/response_templates/responseview.pt

The responses are now displayed in the same manner than task descriptions (see #3172)
Closes #3363

Format line breaks and links in task responses.

---

docs/HISTORY.txt
opengever/core/upgrades/20170912122143_fix_shared_excerpt_list_reference/upgrade.py
opengever/meeting/proposal.py

This PR fixes an issue with mutable default arguments in combination with a `RelationList`.
When creating a new excerpt for a submitted proposal and setting the excerpt list attribute/field on the submitted proposal the default value from the `ISubmittedProposal` schema was used instead of a new list instance. This happened by using `getattr` which already returns
the schema default. This lead to the default value being shared between multiple instances of submitted proposals.
We attempt to fix this with an upgrade step. Excerpts are stored in the meeting-dossier. We fix shared excerpt lists by creating a new list instance and filtering out the excerpts that come from foreign meeting dossiers should they be present in the excerpt list.
We can't completely fix relations within the same …

Fix shared default value for excerpt lists.

---

docs/HISTORY.txt
opengever/bundle/sections/constructor.py
opengever/bundle/tests/test_section_constructor.py

Currently the construtor section does not ensure the encoding for the title attribute, which must be unicode. This can lead in to broken `zope.i18nmessageid.message.Message` objects in the journal of an object, which raises an `UnicodeDecodeError` (see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3941/) when trying to translate the Message by `zope.i18n.translate`.
Therefore the journal of those object can not be rendered or converted in to a PDF when resolving the Dossier.

OGGBundle: Fix title encoding in constructor section.

---

docs/intern/operations/allgemein.rst
docs/intern/operations/index.rst

Add some internal documentation for commonly used cron-jobs.

Docs intern: Document cronjobs commonly needed for production deployments

---

opengever/testing/fixtures.py

Currently we're populating local variables at __call__ time and this could be done at __init__ time.
Also migrated a print call to use an info logger instead.

Split __init__ and __call__ properly on the integration test fixtures

---

docs/HISTORY.txt
opengever/base/locales/fr/LC_MESSAGES/plone.po

Note: Currently the `plone.po` is not part of the og.base modul in the [translation tool](http://translations.onegovgever.ch), therefore those translations were not displayed in the translation tool.

Add missing french translations.

---

README.rst
docs/HISTORY.txt
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20170920094529_add_edit_action_for_meetings/actions.xml
opengever/core/upgrades/20170920094529_add_edit_action_for_meetings/upgrade.py
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/edit_meeting.py
opengever/meeting/browser/meetings/templates/edit_meeting.pt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/tests/test_meeting_edit.py
opengever/meeting/tests/test_memberships.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

**Background:**
In the older SPV implementation, the meeting details were edited through the "protocol"-view, which included the meeting details form.
But with the word feature we are no longer using the "protocol"-view because the protocol is now written directly in the word files, triggered through the meeting view.
Request: https://github.com/4teamwork/gever/issues/65
**Changes:**
- The meeting details form is extracted from the "protocol"-view into a separate edit form.
- The "edit"-action is moved from the left sidebar to Plone's editbar (`object`-action), because it is the plan to get rid of the sidebar step by step.
**Implementation details:**
- The meeting-type has no `FTI` => the action can only be registred publicly.
- The published meeting wrapper does not allow unsecure access …

SPV word: New edit meeting form.

---

docs/HISTORY.txt
opengever/core/upgrades/20170920143453_add_excerpts_table/upgrade.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/model/__init__.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/excerpt.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_proposal_word.py
opengever/testing/fixtures.py

This PR adds excerpts for ad-hoc agenda items.
Up to now excerpts could only be generated for proposal based agenda-items. We also want excerpts for ad-hoc items. Those excerpts are also stored in the meeting-dossier and referenced from the agenda-item. Since the agenda-items are stored in SQL only, we must (temporarily until the content is moved to plone) add a table to reference excerpts in SQL.
The button to generate excerpts now also appears for ad-hoc agenda items, once they are decided:
Note the absence of the functionality to return an excerpt. This, of course, is not possible since we do not have a proposal. Since the excerpts are stored in the meeting dossier one can further process them as one pleases, with tasks, for example.
Closes #3371.

Excerpts for ad-hoc agenda items.

---

opengever/meeting/tests/test_meeting_zipexport.py

Rewrite meeting zipexport as integration test since we want to move to integration testing and changes are planned in the zipexport.

Testing: rewrite meeting zipexport test as integration test.

---

opengever/meeting/tests/test_meeting_zipexport.py

Because of merging two conflicting pull requests without rebasing the tests broke. One change used a method which the other change was removing.

Fix testing regression.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/tests/test_meeting_zipexport.py

When the word-meeting feature flag is enabled, the ZIP export of a meeting should also contain the proposal documents.
Closes https://github.com/4teamwork/gever/issues/95

SPV word: Add proposal documents to meeting ZIP export.

---

docs/HISTORY.txt
opengever/core/lawgiver.zcml

Lawgiver: Ignore `ftw.usermigration` permission: This is required as preparation for including `ftw.usermigration` in `opengever.core`.
This is done as a separate commit to ease backporting, because in the version that the usermigration stuff will be backported to, lawgiver isn't part of `opengever.core` yet. On the other hand, it's required in `opengever.core:master` so that tests will pass for the usermigration-PR.

Lawgiver: Ignore ftw.usermigration permission:

---

docs/HISTORY.txt
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/tests/test_bumblebee_gallery.py

Content listings should be ordered in a way the user can interpret. Currently we order by the catalog's internal values, such as the rid, which is confusing for users and considered a bug.
It's best to order by modified date by now, in order to show the latest changes, so that users can find recently used documents easily.
In the future we will hopefully implement an ordering menu, where the user can decide how to order. But modified date is a good fix for now.

Fix ordering in bumblebee gallery.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_proposal_listings.py

Decision numbers are counted per period. A period is usually a calendar year. In order to easily distinguish the decisions, we prefix the decision number with the year ("2017 / 35").
Closes https://github.com/4teamwork/gever/issues/56

SPV word: Prefix decision numbers with year.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting-noword.pt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

At any point in the process, the committee responsible must be able to go back so that all documents can be edited.
This is changed in both, the old meeting implementation and the new word implementation.

SPV: Fix dialog text when closing a meeting.

---

docs/HISTORY.txt
opengever/ogds/base/sync/ogds_updater.py

We do this because PostgreSQL is strict about string column lengths, and we simply can't control the information that's being passed to us from an external AD or LDAP.
So if any field value is longer than it's corresponding column's length, it will be truncated to the column length before it gets written to SQL.
Needs backport to `4.15-stable` branch.

OGDS update: Truncate purely descriptive user fields:

---

docs/HISTORY.txt
opengever/base/response.py
opengever/base/tests/test_json_response.py

The JSONResponse component is used for generating standardized JSON responses of read-only (GET) as well as writing (POST) requests.
The responses were not equipped with caching headers (such as cache-control). If a response does not have a cache-control header, some browsers, such as IE 11, may cache the response, at least of GET requests.
This component is primarely used for AJAX requests. We usually want to avoid caching AJAX responses as their content may change over time.
We especially do not want to let the browser be in control of cache invalidation.
Therefore we use no-cache headers on all AJAX responses by default.
Implementation details:
- `Cache-Control: no-store`: Neither browser nor intermediate components are allowed to keep a copy in the cache.
- `Pragma: no-cache`: …

Fix caching problems in JSON responses with IE 11.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/model/generateddocument.py
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_word.py

**Background:**
Users make errors. Therefore a secretary of a committee / meeting should always be able to fix typos and errors in documents.
**Requirement:**
In order to be able to fix problems in documents, a user must be able to reopen an already closed meeting. A new "reopen" workflow transition of the meeting workflow allows to do so.
**Problems:**
When _closing_ a meeting, it overrides the protocol and removes the lock, allowing the user to edit the document.
By adding a "reopen" transition we create the problem that a user may have made changes to the generated protocol, but by reopening and closing again the protocol would have been overwritten.
This is addressed by 
1. not overriding protocols which are no longer locked
2. not removing the lock when reopening the meeting. …

SPV word: let meeting be reopened.

---

docs/intern/index.rst
docs/intern/notizen.rst

Includes a list of releases with missing backports in the `intern.onegovgever.ch` docs.

Document releases with missing backports.

---

docs/HISTORY.txt
opengever/private/folder.py
opengever/private/tests/test_folder.py

The current PrivateFolder implementation assumes that the folder id is exactly the same than the id of the corresponding user. But the portal_membership tool, convert the id (for example `-` gets
replaced with `--`, see https://github.com/plone/Products.PlonePAS/blob/master/src/Products/PlonePAS/tools/membership.py#L318) therefore this assumption is wrong and leads to the following error when trying to create a member area for userid containing dashes:
```
File "/plone.api-1.7-py2.7.egg/plone/api/user.py", line 373, in grant_roles
raise InvalidParameterError('User could not be found')
InvalidParameterError: User could not be found
```
So I've changed the implementation and using `getOwner()` to get the corresponding userid of an private folder.
Needs possibly a backport to 2017.5-stable.

Fix private folder creation for userids containing dashes.

---

opengever/activity/model/watcher.py
opengever/core/upgrades/20170907161431_add_team_model/upgrade.py
opengever/inbox/browser/assign.py
opengever/inbox/forwarding.py
opengever/ogds/base/actor.py
opengever/ogds/base/browser/configure.zcml
opengever/ogds/base/browser/teamdetails.py
opengever/ogds/base/browser/templates/teamdetails.pt
opengever/ogds/base/browser/templates/userdetails.pt
opengever/ogds/base/browser/userdetails.py
opengever/ogds/base/locales/de/LC_MESSAGES/opengever.ogds.base.po
opengever/ogds/base/locales/fr/LC_MESSAGES/opengever.ogds.base.po
opengever/ogds/base/locales/opengever.ogds.base.pot
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_actor_lookup.py
opengever/ogds/base/tests/test_sources.py
opengever/ogds/base/tests/test_team_details.py
opengever/ogds/base/tests/test_userdetails.py
opengever/task/browser/assign.py
opengever/task/browser/delegate/recipients.py
opengever/task/handlers.py
opengever/task/task.py
opengever/task/tests/test_team_tasks.py
opengever/task/util.py
opengever/tasktemplates/sources.py
opengever/tasktemplates/tests/test_sources.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py
sources.cfg

Thats the first part of the OGIP 24 - Teamaufgaben implementiation
- Upgradestep for the new model introduce in opengever.ogds.models (https://github.com/4teamwork/opengever.ogds.models/pull/48) Closes #3410 
- Display team memberships in the user-details view, closes #3412 
- Detailview for teams, closes #3413 
- Add additional option `include_teams` to the AllUsersAndInbox source. Which has been renamed to `AllUsersInboxesAndTeamsSource`.
- Allow to select a team as a task responsible and change the responsible to current user, when a team task gets accepted. Closes #3414 
Currently there is no need for a feature flag, if no team exists none of these changes are visible for a user.
Styling: https://github.com/4teamwork/plonetheme.teamraum/pull/585

Introduce teams as a new task responsible. 

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_proposal_word.py

When generating an excerpt, the user should be able to set a meaningful title, to distinguish the listed excerpts better.
Resolves https://github.com/4teamwork/gever/issues/69

Allow to set excerpt titles

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

... because an "ad hoc" agenda item is simply an agenda item.
Resolves https://github.com/4teamwork/gever/issues/96

Remove "Ad-Hoc"

---

opengever/task/tests/test_team_tasks.py

Assign watchers to a local variable in order to avoid having a "stale association proxy" when the GC collects within the list comprehension.
This should fix this problem:
```python
Error in test test_all_team_members_are_notified_for_a_new_team_task (opengever.task.tests.test_team_tasks.TestTeamTasks)
File "/var/lib/jenkins/zope/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
testMethod()
File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.27.0-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
return func(self, *args, **kwargs)
File "/var/lib/jenkins/jobs/opengever.core/workspace@2/opengever/task/tests/test_team_tasks.py", line 76, in test_all_team_members_are_notified_for_a_new_team_task
[watcher.actorid for watcher in …
```

Fix GC / SQL bug in team tests.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py

When a responsible of a committee creates an agenda item ad hoc, a
document is created to contain the ad hoc item's proposal / decision.
If the ad hoc item is removed, the related document should be trashed.
If the agenda item is created from a proposal (handed in by a proposer),
then the proposal should remain until a related agenda item has been
scheduled.
Therefore removing the related agenda item should keep the document
untrashed.
Resolves https://github.com/4teamwork/gever/issues/76

Trash document of deleted ad hoc agenda items

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/proposal.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_proposal_word.py

The title of the proposal should be the title of the proposal's
document.
Resolves https://github.com/4teamwork/gever/issues/74

Remove the prefix of the proposal document's title

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/resources/meeting.js

Adds a spinner on "schedule text" and "schedule paragraph" buttons in the meeting view in order to give visual feedback to the user that the system is doing something.
In order for this to work we need to use <button>-tags as <input>-tags do not support a :before pseudo class in CSS.

SPV word: Improve visual feedback when scheduling text or paragraph.

---

README.rst
bin/.gitignore
bin/i18n-build
development.cfg
test-i18n-de.cfg

*Problem:*
From other projects I'm used to blindly run `bin/i18n-build`. When I do that in `opengever.core` I have these problems:
- it runs on all packages - I usually work on one package but I forget to add the package name as argument 🙈 
- I try to stop it, but its unstoppable (Ctrl-C just stops one process, the script continues with the next).
*Solution:*
I've changed the script to just exit with a usage when running `bin/i18n-build` without arguments.
In order to actually run all packages, just use the new `--all` option.
We have the same features as before, but now I need to decide what I really want to do 😉 
*Other changes:*
I moved the `i18n-build.in` to `bin/i18n-build` and disabled buildout from doing anything. Template and script were the same, so lets just commit to git where …

bin/i18n-build: add --all option

---

opengever/base/menu.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting.py
opengever/meeting/workflow.py

1) Change the workflow state translation from "geschlossen" to "Abgeschlossen".
2) Protect the reopen transition (closed-held) so that it only appears when the word-meeting feature is enabled.
3) Fix a potential problem in the when gerating the menu items for transitions: the menu requires the "separator" and "class" keys.

Meeting workflow fixes

---

opengever/core/testing.py

We switched from unittest2 to unittest. One difference is that unittest2 has the longMessage set to True be default, but unittest does not. We want long messages, which include a repr of the compared objects, since used to have that and a lot of assertions depend on that.
Before:
```
AssertionError: Object <Proposal at /plone/ordnungssystem/fuhrung/vertrage-und-vereinbarungen/dossier-1/proposal-4> has an incorrect workflow state.
```
After:
```
AssertionError: {'catalog metadata': 'asdf', 'object': 'asdf', 'catalog index': 'asdf'} != {'catalog metadata': 'proposal-state-submitted', 'object': 'proposal-state-submi [truncated]...
- {'catalog index': 'asdf', 'catalog metadata': 'asdf', 'object': 'asdf'}
+ {'catalog index': 'proposal-state-submitted',
+  'catalog metadata': …
```

Testing: use long assertion messages.

---

docs/HISTORY.txt
opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/committeecontainer.py
opengever/meeting/tests/test_committee_container_word.py

The excerpt template is not required when the word feature is enabled.
This also improves some existing tests.
Resolves https://github.com/4teamwork/gever/issues/102

Remove excerpt template from forms when word feature enabled

---

opengever/tabbedview/tests/test_bumblebee_gallery.py
opengever/tabbedview/tests/test_document_listing.py

Fix some flaky tests:
1) Document listing tests (tabbedview): test is rewritten with integration testing and is modified to only assert that one expected item is in the list of documents. In the fixture we actually have many documents, since word-based proposals also contain a document. It is more practical / less brittle here to not assert the complete list but only verify that one document is there.
2) Bumblebee gallery tests: use a ticking creator for moving the time forward so that we dont have two objects created at the same time[1] and thus the ordering is not consistent.
[1] same time means in the same minute, since the catalog's sort-index is minutes based (for better internal tree balancing, I guess).

Fix flaky tests

---

opengever/activity/center.py
opengever/activity/tests/test_notification_center.py

Fixes a flaky bug where the use of get_watchers sometimes threw a "InvalidRequestError: stale association proxy, parent object has gone out of scope"
The reason for this error is that resource.watchers is an association proxy, which is implemented lazy. This leads to situations where the garbage collector removes objects which are parts of lambdas within the association proxy object, because the GC believes there are no references to those objects (refcount is 0).
This means we need to consume the watchers within the same scope we access the watchers attribute. Thus the get_watchers method cannot return a lazy association proxy object but must resolve it first.
This is achieved by putting the watchers into a tuple. This resolves lazyness while making sure that no user of get_watchers …

Fix "stale association proxy" error.

---

docs/HISTORY.txt
opengever/core/upgrades/20171003084150_fix_history_entries/upgrade.py

Fixes proposal history.
The history of an object is stored in IAnnotations.
The type of the entry (ex. submitted) is used to filter the entries in
the proposal history. (See https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/proposalhistory.py#L42)
The key under which the type is stored is called 'history_type'.
Previously the key used was 'name', but changed in 21f89be.
There was no upgrade step (data migration) to change these keys for
existing data.
Before the upgrade:
The upgrade:
After the upgrade:
Resolves #3462

Add upgrade step to fix proposal history

---

docs/HISTORY.txt
opengever/bundle/ldap.py

Bundle import: Fix deactivation of LDAP plugin during import:
The previous approach, where a reference to the persistent plugin registry was kept around and later restored, was causing errors in combination with the recent memory optimizations:
Since we regularly re-set the Plone site and garbage collect the cPickleCache, we might hold on to a reference to a persistent object (the plugin registry) that has become detached from the ZODB connection it was retrieved from.
This lead to POSKey errors in cases where the plugin registry had to be restored by the context manager.
Instead, we now keep a **simple mapping** (without any persistent data structures whatsoever) of the plugins that were enabled (per plugin-type) at the beginning of the import, and re-enable those that got deactivated …

Bundle import: Fix deactivation of LDAP plugin during import

---

docs/HISTORY.txt
opengever/meeting/browser/resources/meeting.js

Some modals (dialogs) exist only in the no-word version.
Trying to close them leads to a javascript error.
Make sure the dialogs are not undefined before trying to close them.
Resolves #3407 
Needs backport to: `2017.5-stable`

Fix removal of agenda items

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_edit.py

Displays "other participants" in the meeting view (if any available).
Adding some "other participants":
Displaying "other participants":
Resolves https://github.com/4teamwork/gever/issues/85

Display other participants

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/zipexport.py

There are two command classes:
`CreateGeneratedDocumentCommand` - used when the word feature is disabled
`MergeDocxProtocolCommand` - used when the word feature is enabled.
This affects the content of the protocol word file when exported in a ZIP.
Resolves: https://github.com/4teamwork/gever/issues/112
We don't have (yet) testing infrastructure for exact comparison of the content of word files. Therefore this change cannot be reliably tested at this point.
When a meeting doesn't yet have a protocol, and I export the ZIP file, the protocol generated in the ZIP should use the new protocol generating mechanism. This can be verified by making sure that the agenda item document / proposal document is merged into the protocol. We didn't do that in the non-word implementation.
Steps in order to …

Use new protocol command if word feature enabled

---

docs/HISTORY.txt
opengever/meeting/browser/proposalforms.py
opengever/meeting/browser/proposaloverview.py
opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/proposal.py
opengever/meeting/proposalhistory.py
opengever/meeting/tests/test_proposal_word.py
opengever/meeting/vocabulary.py

The goal is to make it possible to create successor proposal based on decided proposals.
On one hand it should be visible in the proposals that they depend on each other,
on the other hand it should make it easier for the user to reuse / base on a proposal document.
Closes https://github.com/4teamwork/gever/issues/99
- A `Create successor proposal` button appears on decided proposals (but not on a submitted proposal).
- The idea is that a business case is in one dossier, therefore all its proposal shall be in the same proposals.
- The button leads to the proposal addform, which has prefille defaults:
- The fields are filled with the defaults from the predecessor.
- The predecessor proposal document can be used as template for the successor proposal; a copy is created.
- The excerpt of the …

SPV: Create successor proposals

---

opengever/base/browser/layout.py
opengever/base/tests/test_layout.py

When the meeting and its word implementation is enabled, provide a class "body.feature-word-meeting" so that we can use it in CSS.

Provide a body.feature-word-meeting class.

---

docs/HISTORY.txt
opengever/meeting/browser/proposalforms.py

Lets be consistent with the other GEVER forms.

SPV word: In proposal forms, move the title to the top.

---

docs/HISTORY.txt
opengever/core/upgrade.py
opengever/core/upgrades/20170907161431_add_team_model/upgrade.py
opengever/core/upgrades/20170920143453_add_excerpts_table/upgrade.py
opengever/core/upgrades/20171004145231_add_missing_sequences/upgrade.py

When creating a new table with a sequence in a schema migration, the sequence is not created automatically. We haven't done that up to now.
- This change introduces a helper "ensure_sequence_exists", which safely creates a sequences when it is missing.
- An upgrade step makes sure all currently known sequences exist. The list is created with:
`git grep "Sequence(" | sed -e 's:.*Sequence(.::' -e 's:.).*::' | sort | uniq`
- The last two upgrade steps were updated to ensure the their sequences exist in order to improve the copy/paste experience for future migrations.
⚠️ Please do a careful review as I am no SQL / SQLAlchemy master.
Fixes https://github.com/4teamwork/gever/issues/114

Create missing SQL sequences.

---

docs/HISTORY.txt
opengever/mail/browser/send_document.py

This PR fixes the broken default value due to ungroking the module.
See #3476 for more information.

Fix default_documents_as_links default value for opengever.mail.

---

docs/HISTORY.txt
opengever/core/upgrades/20171004160937_update_relation_catalog_for_proposal_excerpts/upgrade.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal_word.py

The relation from the submitted proposal to the excerpt were not registred properly in the relation catalog.
- Make sure that `addRelations` is called, which registers all relations in the relation catalog.
- Do the same for existing submitted proposals in an upgrade step.
The `excerpts` relation list is only available in submitted proposals.

SPV word: Register excerpt relations properly in the relation catalog.

---

README.rst
docs/HISTORY.txt
opengever/tasktemplates/content/configure.zcml
opengever/tasktemplates/content/tasktemplate.py
opengever/tasktemplates/tests/test_tasktemplate.py
opengever/testing/fixtures.py

Without grokking the subpackage the `plone.directives.form.default_value` decorator is not working. Therefore the creation of a tasktemplate failed with a validation error for a
hidden field (see https://github.com/4teamwork/opengever.ftw/issues/46). We now register the default_value adapter directly without the help of the decorator. (see https://community.plone.org/t/howto-default-value-for-datetime-field-in-plone5-without-using-plone-directives/2014/6 for further information)
Closes https://github.com/4teamwork/opengever.ftw/issues/46
Backport to `2017.5-stable` needed.

Fixed default_value for hidden responsible_client field on tasktemplates

---

docs/HISTORY.txt
docs/public/dev-manual/api/docs_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/scanin.rst
opengever/api/configure.zcml
opengever/api/scanin.py
opengever/api/tests/test_scanin.py
opengever/base/configure.zcml
opengever/base/namedfile.py
setup.py

Provides a new REST API endpoint `@scan-in` for uploading scanned documents.
The uploaded documents are created in the context of the given user either in the inbox or in a private dossier with the title "Scaneingang".
The permission `plone.restapi: Use REST API` is required to access the endpoint. 
The endpoint expects multipart form data containing:
- userid: 
- destination: inbox or private
- org_unit: id or name of the org unit, only needed with destination inbox
- file: file data
Example request:
```
POST /gever/@scan-in HTTP/1.1
Authorization: [AUTH_DATA]
Accept: application/json
Content-Type: multipart/form-data; boundary=------------------------b3e801e2d0fb0cc9
Content-Length: [NUMBER_OF_BYTES_IN_ENTIRE_REQUEST_BODY]
--------------------------b3e801e2d0fb0cc9
Content-Disposition: …
```

Scan to gever

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/meetings/transitions.py
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_word.py
opengever/meeting/tests/test_protocol_word.py
opengever/meeting/workflow.py

**Goal:**
We want to give the user control over the state of the agenda items. It should be a conscious decision to decide each single agenda items.
**Changes:**
- Closing a meeting does no longer automatically decide agenda items.
- Closing a meeting is not allowed when there are undecided agenda items.
**Implementation details:**
- The transition controller endpoint can now also return a JSON error message.
- The frontend is updated to handle JSON error messages for transitions.
- The transition controller does no longer raise `NotFound` when a request is unexpected, but `BadRequest`.
- Transitions can now implement a `get_validation_errors` method.
- Because we've removed content from the confirmation dialog, the dialog is rewritten to be more expressive about what exactly happens and …

SPV word: do not decide agenda items when closing the meeting.

---

docs/HISTORY.txt
opengever/document/document.py
opengever/document/tests/test_document_word.py
opengever/dossier/docprops.py
opengever/meeting/configure.zcml
opengever/meeting/docprops.py
opengever/meeting/tests/test_docproperties.py

When a document belongs to a proposal in any way, meeting docproperties are provided for this document.
Example:
```python
{'ogg.meeting.decision_number': '2016 / 2',
'ogg.meeting.agenda_item_number': '1.',
'ogg.meeting.proposal_title': '\xc3\x84nderungen am Personalreglement',
'ogg.meeting.proposal_state': 'Decided'}
```
**The docproperties are provided for these documents:**
- Proposal documents which are stored within the case dossier.
- Submitted proposal documents which are stored within the committee.
- Excerpt documents which are created in the committed (and stored within the meeting dossier).
- Excerpt documents which were sent back to the proposer and thus stored in the case dossier.
Resolves https://github.com/4teamwork/gever/issues/77

SPV word: provide meeting docproperties in proposal document and excerpt.

---

docs/HISTORY.txt
opengever/officeatwork/configure.zcml

This PR ungroks `opengever.officeatwork`.
related to #3205

Ungrok opengever.officeatwork.

---

docs/HISTORY.txt
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_word.py
opengever/meeting/tests/test_unit_meeting.py

The CommitteeMember should only allow users to access the content for reading and not to shange any things.
Since meetings have no Plone content object yet, we require the user to have the "Modify portal content" on the committee object.
This change removes these components for read-only users:
- Generate / update agenda item and protocol documents.
- Reorder agenda items.
- Change agenda items (edit, decide, remove, etc)
- Add new agenda items or paragraphs.
Closes https://github.com/4teamwork/gever/issues/128
Closes https://github.com/4teamwork/gever/issues/127

SPV: Let CommitteeMember only have read-access on meeting view.

---

docs/HISTORY.txt
opengever/meeting/browser/proposaltransitions.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal_word.py

Executing a proposal transition requires the "Modify protal content" permission, but the transitions were listed for users without this permissions.
With this change we no longer show transitions to users without the "Modify portal content" permission.
This cannot be soled within the workflow implementation because the workflow object has no reference to the Plone object (which knows about security).
It has a reference to the so-called "model"-object, but this object does not know about security and the Plone object may or may not be  resolvable (e.g. multi client setup where proposal and submitted proposal are stored in different admin units).
Closes https://github.com/4teamwork/gever/issues/124

SPV word: Protect proposal transitions to require modify permission.

---

docs/HISTORY.txt
opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/command.py
opengever/meeting/committee.py
opengever/meeting/committeecontainer.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/mergetool.py
opengever/meeting/model/committee.py
opengever/meeting/model/meeting.py
opengever/meeting/sablon.py
opengever/meeting/tests/test_committee.py
opengever/meeting/tests/test_committee_container.py
opengever/meeting/tests/test_committee_container_word.py
opengever/meeting/tests/test_committee_word.py
opengever/meeting/tests/test_protocol_word.py
opengever/testing/fixtures.py

Protocols are usually stored in a physical medium with a signature.
With these changes it is possible to add a template which is appended to the protocol, intended for the signatures.
Resolves https://github.com/4teamwork/gever/issues/103

Add protocol suffix template

---

opengever/meeting/committee.py
opengever/meeting/tests/test_committee_traversal.py

Make sure that a meeting can only be accessed in the correct committee.

SPV: prevent incorrect meeting traversal in committees.

---

docs/HISTORY.txt
opengever/meeting/browser/documents/proposalstab.py
opengever/meeting/tests/test_proposal_listings.py

The proposal tab configuration had these problems:
- Sorting by various columns, such as title, did not work.
- Grouping does not make sense when sorting does not work.
- The default width of columns was not configured well.
- The Proposal-ID column did not help and therefore we want to get rid
of it.
Changes:
- Remove Proposal-ID column.
- Disable sorting and grouping on generated columns.
- Configure sane default widths.
Fixes https://github.com/4teamwork/gever/issues/137, where sorting by title did not work.
Withs are optimized for my 15" display.

SPV: Update and fix proposal tabs.

---

docs/HISTORY.txt
opengever/globalindex/model/query.py
opengever/ogds/base/actor.py
opengever/ogds/base/tests/test_actor_lookup.py
opengever/tabbedview/browser/personal_overview.py
opengever/tabbedview/browser/tasklisting.py
opengever/tabbedview/helper.py
opengever/tabbedview/tests/test_personaloverview.py
opengever/tabbedview/tests/test_tasklisting.py

The MyTask tab in the personal overview now shows also tasks, which are assigned to a team, where the current user is a team member.
Besides that, the `responsible` and `issuer` column in tasklistings is now linked and prefixed with a icon to differ the different actors (user, inbox, team).
Styling in a separate PR: https://github.com/4teamwork/plonetheme.teamraum/pull/590
Closes #3415

 List team-tasks in team member's MyTask tab of the personal overview

---

opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_word.py

Fixes a bug where meetings with paragraphs could not be closed because the paragraph is considered not yet "decided" because of its review state. Paragraphs should be skipped in this check, because it is not possible to decide paragraphs.
ℹ️ No changelog entry because the bug was introduced in a feature in the unreleased master ( #3475). 
Fixes https://github.com/4teamwork/gever/issues/139

SPV word: fix closing meetings with paragraphs.

---

docs/HISTORY.txt
opengever/base/browser/resources/SelectAutocomplete.js
opengever/base/browser/resources/TableRadioWidget.js
opengever/base/schema.py
opengever/base/templates/tableradio_input.pt
opengever/base/widgets.py
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20171012114615_register_table_radio_widget_js/jsregistry.xml
opengever/core/upgrades/20171012114615_register_table_radio_widget_js/upgrade.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/browser/proposalforms.py
opengever/meeting/committee.py
opengever/meeting/configure.zcml
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_committee_word.py
opengever/meeting/tests/test_vocabulary.py
opengever/meeting/vocabulary.py

Resolves https://github.com/4teamwork/gever/issues/80
**Goal:**
The selection of available proposal templates should be configurable for each committee.
**Changes:**
- Add new field `allowed_proposal_templates` to committees, storing the UID of each enabled proposal template. When empty, all templates are allowed.
- Extend the `TableRadioWidget` and its field so that it can be configured to automatically reload (via AJAX) when one ore more defined fields change.
- Rewrite proposal template vocabulary (so that we have a class and make methods) and extend it so that it filters the allowed templates when a commitee is given.
- Configure proposal add form so that it updates the proposal template table whenever the committee is changed.
- Make sure we preveserve successor proposal support. …

SPV word: configure available proposal templates for committee.

---

docs/HISTORY.txt
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_document_link_widget.py
opengever/document/widgets/document_link.pt
opengever/document/widgets/document_link.py

When a user does not have the permission to view a document, the DocumentLinkWidget should not render a link (which will lead to unsufficient privileges), but render a text instead.
This does not affect regular listings, where the users doesnt see such documents anyway, but explicit relations where the user must know that a document exists, but may not have access to the document.

Do not render document link without View permission.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/model/agendaitem.py
opengever/meeting/proposal.py

Always list the excerpts in the meeting view, even when the user has no access to the documents.
This is important in order to let the user know that there are documents.
The user usually has no access because of an incorrect configuration.
Fixes https://github.com/4teamwork/gever/issues/131
Fixes https://github.com/4teamwork/gever/issues/129

SPV word: always show excerpts in meeting view.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_meeting_view_word.py

Reguler committee members should not be able to return excerpts.

SPV word: prevent reader user from returning excerpts.

---

docs/HISTORY.txt
opengever/document/checkout/manager.py
opengever/document/document.py
opengever/document/indexers.py
opengever/document/tests/test_indexers.py

* I've plugged the D'n'D upload reindexing hole
* Only reindex the `checked_out` index

Optimize reindexing for document checkout/checkin cycles

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/agendaitems-word.html

Previously:
Now:
Resolves https://github.com/4teamwork/gever/issues/118

Remove double excerpt entries when word activated

---

docs/HISTORY.txt
opengever/meeting/tabs/meetinglisting.py
opengever/meeting/tests/test_meeting_listings.py

If a user does not have the permission to view the dossier a link to the
dossier is not reasonable.
Therefore when the dossiers are listed, the view permissions are checked
and if the user is missing the permission to view the dossier only the
title of the dossier is rendered.
Resolves https://github.com/4teamwork/gever/issues/125

Remove link to dossier if permission is missing

---

docs/HISTORY.txt
opengever/document/browser/edit.py

This PR accesses the response-variable the default-way instead the grok-way.
Related to #3205

Fix missing response-variable due to ungrok opengever.document.

---

opengever/document/widgets/document_link.pt
opengever/document/widgets/document_link.py

- Remove the "span.removed_document": the markup was wrong, resulting in
a standalone tag and a HTML syntax error. It was fixed by wrapping
the link, which coincidentally was what we wanted.
- Add the "removed_document" as regular class to <a> / <span>.
- Rename the "no-access" class to "no_access" in order to be consistent.
- ⚠️ This requires https://github.com/4teamwork/plonetheme.teamraum/pull/592
**Before:**
**After:**

Change markup for document icons (removed, no access).

---

opengever/meeting/command.py
opengever/meeting/committeecontainer.py
opengever/meeting/exceptions.py
opengever/meeting/tests/test_committee_container_word.py

... also make the paragraph template required for the committee container; resolves https://github.com/4teamwork/opengever.core/issues/3459
... also adapt test to include all required templates in the tests.

Add missing protocol header template error message

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/indexes.py
opengever/bundle/console.py
opengever/bundle/loader.py
opengever/bundle/tests/test_oggbundle_pipeline.py

Adds an indexer that indexes the bundle GUID from `IAnnotations(obj)['guid']`. In a standard GEVER, there will no corresponding index, and this indexer won't be called.
For bundle imports however, a FieldIndex `bundle_guid` will be created, so that the imported items' GUIDs will get indexed for efficent querying (future partial/delta imports, and import report generation). This index probably will be removed again after the migration.

Add indexer for bundle GUIDs and create index upon bundle import

---

docs/HISTORY.txt
opengever/bundle/sections/constructor.py
opengever/bundle/sections/resolveguid.py
opengever/bundle/tests/__init__.py
opengever/bundle/tests/assets/invalid_parent_reference.oggbundle/dossiers.json
opengever/bundle/tests/test_business_rule_violations.py
opengever/bundle/tests/test_invalid_parent_reference.py
opengever/bundle/tests/test_section_constructor.py
opengever/bundle/tests/test_section_resolveguid.py

All reference numbers used in `parent_reference` parent pointers **must exist** according to the Plone catalog, otherwise we **abort early**.
So we build a flat list of reference numbers that exist in the Plone catalog first, and make sure each `parent_reference` pointer we encounter points to a reference number that actually exists.
The **(cached) lookup** for actually turning the reference number into a path happens later, in the `ConstructorSection`, but at that point we can be sure each one is resolvable to a path because we found it in the catalog earlier.
Also includes some cleanup and refactorings.

OGGBundle: Validate parent_reference early for existence

---

README.rst
docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/service.py
opengever/base/tests/test_email_attributes_service.py
opengever/testing/fixtures.py

The action "send as attachment" in the inbox raised a javascript error,
because the service, which is needed to fill the attributes of the email
was not available.
This commit adds a default service which provides an empty set of values for the
resulting email.
Also add inbox fixture and add missing reindex after changing roles.
Resolves #3443

Fix send as attachment

---

docs/HISTORY.txt
docs/public/dev-manual/oggbundle/index.rst
opengever/bundle/report.py
opengever/bundle/sections/constructor.py
opengever/bundle/sections/resolveguid.py
opengever/bundle/tests/__init__.py
opengever/bundle/tests/assets/delta.oggbundle/dossiers.json
opengever/bundle/tests/assets/delta_base.oggbundle/repofolders.json
opengever/bundle/tests/assets/delta_base.oggbundle/reporoots.json
opengever/bundle/tests/test_business_rule_violations.py
opengever/bundle/tests/test_delta_bundle_import.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/bundle/tests/test_section_resolveguid.py

This allows items in bundles to reference a GUID via `parent_guid` that refers to an object that has previously been imported into Plone.
If an object with the same GUID exists both in Plone as a JSON item in the bundle, the one from Plone is used as the parent container for any items that refer to that GUID.
---
The **report logic** had to change slightly to accommodate this change:
In order to generate the report, we now track the acutal constructed GUIDs in `bundle.constructed_guids`. For generating the report, we simply query the catalog for all these GUIDs.

OGGBundle: Support delta imports using GUID:

---

docs/HISTORY.txt
opengever/bundle/loader.py
opengever/bundle/sections/progress.py
opengever/bundle/sections/resolveguid.py
opengever/bundle/tests/__init__.py

Because already existing items still supplied in bundle will be filtered and not constructed again, the actual item count may deviate from the raw number of item in the bundle's JSON
files.
Therefore we list those counts separately, to make the available information more clear.
Example output:
```
2017-10-20 16:08:02 INFO opengever.bundle.loader Raw items in bundle <Bundle opengever/bundle/tests/assets/basic.oggbundle/>
2017-10-20 16:08:02 INFO opengever.bundle.loader ================================================================================
2017-10-20 16:08:02 INFO opengever.bundle.loader documents.json       8
2017-10-20 16:08:02 INFO opengever.bundle.loader repofolders.json     3
2017-10-20 16:08:02 INFO opengever.bundle.loader reporoots.json       1
2017-10-20 16:08:02 INFO …
```

OGGBundle: Fix tracking of item counts (actual vs. raw)

---

docs/HISTORY.txt
opengever/dossier/service.py
opengever/dossier/tests/test_email_attributes_service.py

When a dossier is resolved, the user does not have the permission to
modify its content.
The send as attachment action adds a bcc email address, such that the
document is added to the dossier again.
This should not happen when the dossier is resolved.
Therefore the bcc is removed when the user has no permission to modify
its content.
Resolves #3457

Remove bcc from attributes for resolved dossiers

---

README.rst
docs/HISTORY.txt
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/contentstats/tests/test_content_stats_integration.py
opengever/inbox/browser/tabs.py
opengever/inbox/tests/test_move_items.py
opengever/mail/tests/test_indexers.py
opengever/tabbedview/tests/test_document_listing.py
opengever/testing/fixtures.py

Reenables copy items action for inbox.
It was disabled because a customer wanted it to be disabled.
Now its a sensible action, needed for several customers.
Resolves #3426

Reenable copy items action in inbox

---

docs/HISTORY.txt
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

Currently disabled or no longer assigned users has been invalid. Therefore it was not longer possible to edit a dossier with a not assigned users defined as responsible, because it raised an
NoResultFound exception.
With this PR the source differs between a `base_query` and a `search_query`, so that a disabled or not assigned users ist still valid but not selectable via the search method.
Closes #3078

Fixed handling of disabled or not assigned users in the sources.

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js

The showroom search-view implementation for fetching new objects will use the default
next/previous button urls of the searchform to request new objects based on the current search
params.
If we load only the first next or previous batch-slice, this will work well. But if we
reach the end/beginning of the second batch-slice, it will reuse the same fetch-link as for
the first request, because the search-view itself will not update its buttons after fetching
new objects through the showroom.
To solve this issue, we implement a new class for handling the current request-urls for the
tail/head function of the showroom.
There is a side-issue (not required for this PR!): https://github.com/4teamwork/ftw.showroom/issues/45 - The issue describes a bad behavior where it is possible, that the …

Fix fetch new showroom items in serach-view

---

docs/HISTORY.txt
opengever/bundle/cfgs/oggbundle.cfg
opengever/bundle/console.py
opengever/bundle/sections/commit.py
opengever/bundle/transmogrifier.zcml

OGGBundle: Do intermediate commits every 1000 items by default:
This behavior can be disabled by invoking `bin/instance import`
with the `--no-intermediate-commits` flag.

OGGBundle: Do intermediate commits every 1000 items by default

---

docs/HISTORY.txt
opengever/base/browser/layout.py
opengever/base/tests/test_layout.py
opengever/base/viewlets/byline.pt
opengever/document/contentlisting.py
opengever/document/tests/test_document_link_widget.py
opengever/document/widgets/document_link.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/byline.py
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/edit_meeting.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/participants.py
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/meetings/templates/navigation-word.html
opengever/meeting/browser/resources/meeting.js
opengever/meeting/command.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/meeting.py
opengever/meeting/tests/pages/meeting_view.py
opengever/meeting/tests/test_meeting_byline.py
opengever/meeting/tests/test_meeting_edit.py
opengever/meeting/tests/test_meeting_view_word.py
opengever/meeting/tests/test_participants_view.py
opengever/meeting/tests/test_protocol_word.py
opengever/testing/pages/byline.py

This pull requests contains multiple steps in the redesign process of the meeting view with the word feature enabled.
See current layout screenshot for reference at the bottom.
Belongs to: https://github.com/4teamwork/gever/issues/106
⚠️ Requires https://github.com/4teamwork/plonetheme.teamraum/pull/593
Closes https://github.com/4teamwork/gever/issues/126
Move parts of the metadata to the newly displayed byline:
- Move "agenda items list" and "protocol" to sidebar.
- Call it "Vorprotokoll" until the meeting is closed.
- Meeting number appears when meeting is closed.
- List all participants in the participants tab.
- Allow to select role.
- Allow to "excuse" participants.
- Provide filter because this list can get very long.
- Show additional participants.
- The navigation shows all agenda …

SPV Word: Meeting View Redesign, Part 1

---

README.rst
docs/HISTORY.txt
opengever/core/upgrades/20171017223630_add_respect_max_depth_registry_entry_for_dossiertemplates/registry.xml
opengever/core/upgrades/20171017223630_add_respect_max_depth_registry_entry_for_dossiertemplates/upgrade.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/dossiertemplate/interfaces.py
opengever/dossier/tests/test_dossier_template.py
opengever/testing/fixtures.py

Currently dossiertemplates are not respecting the maximum dossier depth configuration option. The current behavior is the desired one, for most of the customers, but the behavior should be
configurable. Therefore we add an additional registry option `respect_dossier_depth` to the dossiertemplate settings. Which is disabled by default.
See https://basecamp.com/2768704/projects/14549453/todos/326699123 for
more information.

Add dossiertemplates configuration flag `respect_dossier_depth`.

---

docs/HISTORY.txt
opengever/meeting/browser/proposaloverview.py
opengever/meeting/browser/templates/proposaloverview.pt
opengever/meeting/tests/test_proposal_overview.py

When an excerpt was returned, the user sees a link to the excerpt
document in the view of the proposal.
If the user has no permission to view the excerpt document, the link
should not be displayed.
Old:
New (left: with permission - right: without permission):
Resolves https://github.com/4teamwork/gever/issues/132

Remove unpermitted link to excerpt document

---

docs/HISTORY.txt
opengever/ech0147/model.py
opengever/ech0147/tests/test_model.py

- Include mails in eCH-0147 exports.
- Skip documents without a file in eCH-0147 exports (Documents without a file are not supported by the eCH-0147 standard).
Closes #3509

eCH-0147 export: Handling for mails and documents without a file

---

docs/HISTORY.txt
opengever/ogds/base/sync/ldap_util.py

With #2710 we already skip those referral's in the groups import, but same problem happens during user import.
The PR renames also the `filter` parameter to `search_filter`, to avoiding "conflicts".
Closes https://sentry.4teamwork.ch/sentry/onegov-gever/issues/4306/

LDAP sync: skip referral's on each ldap search.

---

opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/tests/test_zipexport.py

The creation of the zip file fails when there is no agenda item list
template.
The export itself should work when there is no agenda item list
template, the agenda item list should not be included in the zip file in
that case.
Since getting the agenda item list template is obfuscated, a try-except
is used to prevent the server error.
Resolves #3338

Fix zip export when agendaitemlisttemplate missing

---

docs/HISTORY.txt
opengever/meeting/tests/test_committee_vocabulary.py
opengever/meeting/vocabulary.py

This vocabulary is used to display the committees in the form to add
proposals.
These committees should be sorted by their title.
Before:
Now:
I split the PR into two commits, the first one contains the test (which fails), the second one contains the changes letting the test pass.
As soon as this PR is approved, the two commits are going to be squashed.
Resolves https://github.com/4teamwork/gever/issues/141

Sort committees in committee vocabulary

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_agendaitem.py

No longer allow the following actions when the meeting has been held:
- schedule paragraphs
- schedule agenda items
- edit agenda item title
- delete agenda items
Fixes #3551.

Prevent editing agenda item list when it should not be allowed.

---

docs/HISTORY.txt
opengever/base/browser/resources/Controller.js
opengever/base/response.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/unscheduled_proposals.py
opengever/meeting/browser/resources/meeting.js
opengever/meeting/exceptions.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_unit_workflow.py
opengever/meeting/tests/test_unscheduled_proposals.py
opengever/meeting/workflow.py

This PR changes the behaviour of the agenda item list view to also display error messages to users when an ajax request failed because the servers state has changed in the meantime. We also trigger a reload of the agenda-item list for some of these cases to display the current state.
Changes include:
- throw exceptions in model instead of `assert` statements
- catch exceptions in controller/view and display messages to users
- also use correct status codes in json responses instead of 200 everywhere
- always display the error messages in a json response instead of just for succeeded responses
Closes #2436.

Display error message to client when state has changed in meantime

---

docs/HISTORY.txt
opengever/core/upgrades/20171029220954_make_task_response_changes_persistent/upgrade.py
opengever/task/adapters.py
opengever/task/tests/test_comment.py
opengever/task/tests/test_response.py

PR provides:
- Fix response change creation for new responses
- An upgradestep which convert existing response changes (`dict`'s) in to persistent objects (`PersistentMapping`'s)
Closes #3419

Make sure response changes are persistent.

---

docs/HISTORY.txt
opengever/dossier/tests/test_dossier_template.py
opengever/dossier/tests/test_overview.py
opengever/testing/fixtures.py

This PR fixes an issue if you try to edit an object created through the `OpengeverContentFixture` with the testbrowser.
The responsible `hugo.boss` does not exist.

Add proper responsible for fixture objects

---

docs/HISTORY.txt
opengever/core/upgrades/20171009113732_add_commitee_roles_to_document_workflow/upgrade.py

If there are no committee containers the upgrade would run with an empty path list and thus not restrict the query at all and update all documents/mails. We should early-abort if there are no commitee containers in the system, i.e. if the first result is empty.
Fixes https://github.com/4teamwork/opengever.sg/issues/209.

Fix upgrade, avoid running for all documents/mails.

---

docs/HISTORY.txt
opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/command.py
opengever/meeting/committee.py
opengever/meeting/committeecontainer.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/model/committee.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_committee_container_word.py
opengever/meeting/tests/test_committee_word.py
opengever/meeting/tests/test_proposal_word.py
opengever/testing/fixtures.py

A sablon template can be defined on committee or committee container
which will be added (if available) to the created excerpts.
If the committee has no templates available, the template of the
committee container is used.
Since the new excerpts do not only contain the content of the agenda
item document, the tests which previously compared the content of the
generated excerpts with the agenda item documents need to be changed.
The import of the MergeDocxExcerptCommand inside the method of the
AgendaItem is required to get rid of circular imports.
Resolves https://github.com/4teamwork/gever/issues/117

Allow adding excerpts headers and suffixes

---

opengever/meeting/browser/meetings/templates/meeting-word.pt

This allows us to not hide the link on ie11 which caused issues with displaying the fa-icon.
⚠️  requires https://github.com/4teamwork/plonetheme.teamraum/pull/596.
now correctly displays the document actions on ie11:
Fixes https://github.com/4teamwork/gever/issues/146.

Fix ie11 action buttons, don't put title into action link.

---

docs/HISTORY.txt
opengever/base/model.py
opengever/tabbedview/sqlsource.py
opengever/tabbedview/tests/test_sqlsource.py

Oracle raises an "ORA-00906: missing left parenthesis" erorr when
casting a integer column to a string and querying it with ilike.
Therefore I add a special handling for oracle backends, which solves
the issue https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3749/
when filtering in task listings like the MyTasks tab.
Not valid Query 
```
SELECT tasks.id, tasks.admin_unit_id [...]
FROM tasks
WHERE tasks.responsible IN ('hugo.boss') AND (lower(CAST(tasks.sequence_number AS VARCHAR)) LIKE lower('%phip%')) ORDER BY created DESC
```
Valid query
```
SELECT tasks.id, tasks.admin_unit_id [...]
FROM tasks
WHERE tasks.responsible IN ('hugo.boss') AND (tasks.sequence_number LIKE lower('%phip%')) ORDER BY created DESC
```

Fix textfilter in sqlsource table listings for oracle backends.

---

docs/HISTORY.txt
opengever/core/releaser.py
setup.cfg

With this PR we automatically update the released version in `versions.cfg` while creating a release with `zest.releaer`.
- We use https://github.com/zestsoftware/zest.releaser `prerelease` hook to pin the to be released gever version in `versions.cfg` at the same time `setup.py` and `HISTORY.txt` are updated, i.e. when creating the `Preparing release [num]` commit.
- We use the `postrelease` hook to remove the pinning again, i.e. when creating the `Back to development: [num++]` commit.
Example commits:
- prerelease:  https://github.com/4teamwork/opengever.core/commit/23977156bbcff405ebcaae15dafcddee616821f5
- postrelease: https://github.com/4teamwork/opengever.core/commit/935299224b379e2a00c4cd5ee1bb56328b94f2a4
⚠️  todo once approved:

Automatically update gever version in versions.cfg.

---

docs/HISTORY.txt
opengever/core/upgrades/20171009113732_add_commitee_roles_to_document_workflow/upgrade.py

This will avoid running the upgrade for every document if we have committee containers in the system.
_This will also need a backport to 2017.6 and another bugfix release._

Fix catalog index name, it is `path`, not `paths`.

---

docs/HISTORY.txt
opengever/api/configure.zcml

This PR ensures that `plone.restapi` directives are loaded before using them. 
Also drops the no longer needed conditional in an adapter definition.

Make sure `plone.rest` directives are loaded when used.

---

opengever/officeconnector/service.py

As the main thing itself got canned, I'm slowly on the side starting to rebase and cherry-pick useful stuff onto master.
* Please pylint
* Reorder the Office Connector endpoint logic to 'fail per default'

officeatwork fallout salvage - OfficeConnector endpoint logic reordering

---

opengever/activity/model/query.py

I'm intending on moving to asserting on unclean stderr from a test batch in the CI runs and this is the last one standing in the way.
https://ci.4teamwork.ch/builds/121918/tasks/187756
Querying on an empty notification role target group spits out (retouched for readability):
```
eggs/SQLAlchemy-1.1.10-py2.7-linux-x86_64.egg/sqlalchemy/sql/default_comparator.py:161: 
SAWarning:
The IN-predicate on "notifications.userid" was invoked with an empty sequence.
This results in a contradiction, which nonetheless can be expensive to evaluate.
Consider alternative strategies for improved performance.
```
This breaks the test assertion (to explicitly test for no one having being notified in case no one has registered). Suggestions?

Squelch an SQLAlchemy stderr bleed from a test

---

docs/HISTORY.txt
opengever/meeting/browser/resources/meeting.js

The code expected an element to be present all the time whereas it is only
there when the word-meeting feature flag has been enabled.

Fix agenda items rendering on non-word meeting.

---

docs/HISTORY.txt
opengever/core/upgrades/20171107141117_sync_meeting_title_to_dossier/upgrade.py
opengever/dossier/tests/test_dossier.py
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/meetingdossier_forms.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting.py
opengever/meeting/tests/test_meeting_dossier.py
opengever/meeting/tests/test_meeting_edit.py
opengever/testing/fixtures.py

Currently meeting and meeting-dossier titles can be edited separately, and also the default title suggestions are different from each other. This is confusing for the users. We want to merge meetings and meeting-dossiers in the near future. One step in that direction is to let meeting-dossiers and meetings always have the same title.
This PR introduces the following changes:
- meeting will (for now) contain the master title
- titles on meeting-dossiers are no longer editable
- when creating a meeting-dossier it will have the same title as the corresponding meeting
- the meeting title is always synced to the meeting dossier when a meeting is edited
Also this PR adds an upgrade step to rename meeting-dossiers.
Closes https://github.com/4teamwork/gever/issues/145.

Keep meeting-dossier and meeting title in sync.

---

docs/HISTORY.txt
opengever/meeting/browser/proposalforms.py
opengever/meeting/tests/test_submitted_proposal_word.py

Before:
And now:
Resolves https://github.com/4teamwork/gever/issues/144

Remove submitted proposal noword fields

---

docs/HISTORY.txt
opengever/dossier/browser/overview.py

Transform seems to be applied twice by mistake. We can just use the `super` implementation instead of overriding it with a faulty one.
See https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/160.

Don't escape description in overview twice for dossier templates.

---

docs/HISTORY.txt
opengever/meeting/browser/committee.py
opengever/meeting/tests/test_committee_overview.py

> Die Links zu den Mitgliedern werden falsch erstellt, sie zeigen auf das Committee (z.B. … fd/sitzungen/committee-1/member-123), sollten aber auf den CommitteeContainer (z.B. …fd/sitzungen/member-123) zeigen.
Resolves https://github.com/4teamwork/gever/issues/152

Fix links from the committee overview to members

---

docs/HISTORY.txt
opengever/activity/dispatcher.py
opengever/activity/model/__init__.py
opengever/activity/model/settings.py
opengever/activity/tests/test_notification_center.py
opengever/core/upgrades/20171108134921_add_notification_settings_table/upgrade.py
opengever/testing/builders/activity.py

Add new model NotificationSetting, which stores the personal notification settings, in the same manner than we have stored the settings for the complete installation. The NotificationDispatchers checks first for a personal setting and uses the notification_defaults as a fallback when deciding if a notification has to be dispatched ... 
The form, where a user can add and edit those personal settings will follow in a separate PR. 
This is a part of OGIP 29

Allow personal notification settings

---

bin/mtest

Current test timings on my laptop with this layer split:
```
0.033%                     policy               02 seconds
0.037%                     sphinx               02 seconds
0.037%            policytemplates               02 seconds
0.144%                    testing               09 seconds
0.144%                        api               09 seconds
0.150%                    ech0147               10 seconds
0.182%               contentstats               12 seconds
0.460%                      debug               30 seconds
0.616%               officeatwork               40 seconds
0.654%                   portlets               43 seconds
0.670%                    sharing               44 seconds
0.691%                 repository               45 seconds
0.727% …
```

Port mtest to multiprocessing and split out layers

---

docs/HISTORY.txt
opengever/document/base.py
opengever/document/browser/overview.py
opengever/document/browser/templates/overview.pt
opengever/document/document.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/meeting/model/meeting.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_overview_meeting_links.py
opengever/meeting/tests/test_proposal_listings.py

The document overview should display links to the meeting or the proposal if there is any proposal / meeting associated to the document displayed.
Also the link should be "disabled" if the user has no view permission.
Resolves https://github.com/4teamwork/gever/issues/100

Add links to meeting and proposal

---

docs/HISTORY.txt
opengever/core/upgrade.py
opengever/core/upgrades/20171115090641_fix_submitted_proposal_title_sync/upgrade.py
opengever/meeting/browser/createsubmittedproposal.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py

The title and other proposal-model attributes should only be synced after
they have been set from the attribute data provided as JSON in the request.
We have not noticed this is a problem so far because the test tests with
attachments which cause an object modified event to be fired later. Same for
the word implementation since creating the word document fires a modified
event, too.
Also contains a critical fix for `SQLUpgradeStep` that ensures statements always are picked up as changes by the zope datamanager.
_Should be backported as a bugfix level release._
Fixes #3607.

Fix syncing the submitted proposal title to sql.

---

docs/HISTORY.txt
docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
opengever/base/schemadump/config.py
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/schemas/dossiers.schema.json
opengever/dossier/behaviors/protect_dossier.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_protect_dossier.py
opengever/ogds/base/sources.py

Add new field dossier_manager to the IProtectDossier behavior to set the dossier-manager manually.
The field "dossier_manager" is not read-only as described in the requirements. A manager or a dossier-manager can change this field. This is required if you need to add i.e. a group instead only a user as a dossier-manager or if the manager wants to change the dossier-manager.

Adds own field for dossier manager

---

bin/mtest

I was under the impression using just the module name will do the same test discovery / filtering dance than using the dotted name. Apparently it is not so. This pull request amends that.

Restore mtest to use dotted names for modules

---

docs/HISTORY.txt
opengever/meeting/model/query.py
opengever/meeting/tests/test_meeting_listings.py

Sorts the list of meetings in the committee tabbed view in the meetings tab.
See also https://github.com/4teamwork/gever/issues/159

Sort meetings in meeting tab of committee

---

docs/HISTORY.txt
opengever/tabbedview/browser/base_tabs.py

Use gever's own generic template (`generic_with_filters.pt`) for all
CatalogListings, which always shows the filterlist, even on empty listings. Closes #2819.

Show filterlist also on empty tabbedview listings.

---

docs/HISTORY.txt
opengever/bumblebee/tests/test_document_event_handling.py
opengever/document/configure.zcml
opengever/document/handlers.py
opengever/dossier/docprops.py
opengever/dossier/tests/__init__.py
opengever/dossier/tests/test_default_doc_property_adapters.py
opengever/dossier/tests/test_doc_property_writer.py
opengever/ogds/base/tests/test_userdetails.py
opengever/tabbedview/tests/test_document_listing.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Update bumblebee checksum when modifying a document's doc-properties.
Fire a modified event when we modify the document. Bumblebee listens to those so we can be sure that the cached document checksum will always be correct after adding doc-properties to a docx file.
This fixes an issue where the bumblebee checksum is not updated after creating/modifying a document and thus the bumblebee preview image or overlay could not be rendered.
As discussed there is no upgrade step here since fixing this would include re-calculating the checksum for every document. We will provide a button with which an `Administrator` and `Manager` can attempt to re-render the bumblebee preview, see https://github.com/4teamwork/opengever.core/issues/3619 for a suggestion.
Fixes …

Update bumblebee checksum when modifying document doc-properties.

---

docs/HISTORY.txt
opengever/core/profiles/default/types/opengever.meeting.sablontemplate.xml
opengever/core/upgrades/20171117151801_fix_redirector_after_salon_creation/types/opengever.meeting.sablontemplate.xml
opengever/core/upgrades/20171117151801_fix_redirector_after_salon_creation/upgrade.py
opengever/tabbedview/browser/configure.zcml
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/tests/test_redirectors.py

Previously: ![sablom bug](https://user-images.githubusercontent.com/194114/32783319-99bbaa84-c94b-11e7-87b7-c9aa4d8702f0.gif)
And now: 
Resolves #3609

Fix redirector after sablon template creation

---

docs/HISTORY.txt
opengever/dossier/behaviors/protect_dossier.py

This PR adds the proper default value for list fields in the IProtectDossier behavior schema.
closes #3624

Add missing default value for dossier protection fields.

---

docs/HISTORY.txt
opengever/document/indexers.py
opengever/document/tests/test_indexers.py
opengever/mail/configure.zcml
opengever/mail/indexer.py
opengever/mail/overrides.zcml
opengever/mail/tests/test_indexers.py
setup.py
versions.cfg

This PR fixes the unicode-issue due to 
- unconfiguring the ftw.mail searchableTextExtender which uses the html_to_text transform
- registering the document searchableTextExtender for IBaseDocument instead the more specific `IDocumentSchema`
- Removing the `OGMail` searchableTextExtender because it's the same implementation like the one of the document.
Before:
After:
Closes #2462

Fix OGMail searchable text extender.

---

docs/schema-dumps/ftw.mail.mail.schema.json
docs/schema-dumps/opengever.document.document.schema.json
docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
opengever/bundle/schemas/documents.schema.json
opengever/bundle/schemas/dossiers.schema.json
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po

I added the new description of the keyword fields in the translations.
I included a line-break to make it more readable.
I also added a french translation.

Add field description for keyword fields

---

docs/HISTORY.txt
opengever/portlets/tree/resources/tree.js

Closes https://github.com/4teamwork/opengever.core/issues/2830

Use localstorage for tracking expanded_uids instead of cookie.

---

docs/HISTORY.txt
opengever/disposition/browser/excel_export.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_excel_export.py

Dossier title seemed to be the most appropriate basis for the report filename.
Should this kind of change be marked in the HISTORY.txt file?

Set excel file name to dossier title when creating a disposition report.

---

opengever/officeconnector/tests/test_templates.py
opengever/testing/integration_test_case.py

* Add a document without a file to the fixtures
* Permanently fix a bumblebee test in regards of incoming data - did I break the test?
* Add the Office Connector features to the fixtures
* Port the Office Connector template tests to integration tests

officeatwork fallout salvage - port OfficeConnector template tests to integration tests

---

opengever/dossier/upgrades/20170328131435_set_task_comment_permission/upgrade.py

With #3642 three workflow and security reindexing upgradesteps has been merged togheter. But the check if a reindex_security is necessary at all has been dropped by mistake. This PR adds this check again (`has_offered_or_archived_dossiers`). See the diff from the previous PR for more details (https://github.com/4teamwork/opengever.core/pull/3642/commits/7aac61cd65d1a8063f49382daea8c80a9f7dffcc).

Improve workflow upgradesteps

---

docs/HISTORY.txt
opengever/inbox/locales/de/LC_MESSAGES/opengever.inbox.po
opengever/inbox/locales/fr/LC_MESSAGES/opengever.inbox.po

Changed in German and French
I also noticed there seems to be confusion between *Auftraggeber* and *Auftragnehmer* in French, both translated by *Mandataire* (see screenshot). I had a quick look and it seems to be wrong in most of GEVER, where *mandataire* (Auftragnehmer) is used to translate *Auftraggeber*, which I would translate by *Mandant*
fixes #3643

Change field description for forwardings responsible field

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

This is more semantically correct.

Rename to "Traktandum abschliessen".

---

opengever/dossier/behaviors/protect_dossier.py
opengever/sharing/tests/test_blocked_local_roles_listing.py

Simply a case of not reindexing when setting the blocked local roles attribute.
Trivial fix on a fresh unreleased feature -> no changelog entry.
Closes #3650

Reindex protected dossiers when blocking local roles

---

docs/HISTORY.txt
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20171121100830_add_ogds_sync_configuration/registry.xml
opengever/core/upgrades/20171121100830_add_ogds_sync_configuration/upgrade.py
opengever/ogds/base/interfaces.py
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py

Add an registry configuration option to define an LDAP attribute name, which should be used when syncing LDAP groups into the OGDS.
This allow us to use the group description as group title on some installations, thats a part of the OGIP 23 changes.

Add group title option to the OGDS Synchronisation.

---

versions.cfg

It is only a test-dependency but since requests is pinned, pinning toolbelt also should avoid running into incompatibility issues later.

Also pin test-depdenency requests_toolbelt.

---

docs/HISTORY.txt
opengever/base/behaviors/lifecycle.py

The date is now visible only for managers.
Should this be done with lawgiver?
Manager:
Other User:

Set cassation_date field permissions to manager

---

docs/HISTORY.txt
opengever/task/tests/test_team_tasks.py
opengever/task/util.py

Make sure `Response` object is already added to the task before changing the workflow state, so event handlers as the `reassign_team_tasks` are able to extend the response changes.
See https://sentry.4teamwork.ch/sentry/onegov-gever/issues/4530/

Fix bug when accepting a multi admin_unit team task.

---

docs/HISTORY.txt
opengever/sharing/browser/admin_list.py
opengever/sharing/tests/test_blocked_local_roles_listing.py

I also changed the naming of the `children` variable which was redefined in a loop over `children`. While that works, it seemed to be a rather unfortunate choice 😄 
solves #3653

Show icons in BlockedLocalRolesList

---

docs/HISTORY.txt
opengever/bumblebee/tests/test_download.py
opengever/bumblebee/tests/test_versions.py
opengever/document/document.py
opengever/document/quick_upload.py
opengever/document/tests/test_bumblebee.py
opengever/document/tests/test_versioner.py
opengever/dossier/docprops.py
opengever/meeting/command.py
opengever/meeting/tests/test_excerpt.py

The doc-property updater did not set the a document's file with the setter as would be the "proper" way to do and as is also expected by changes in https://github.com/4teamwork/opengever.core/pull/3467. Instead it accessed the file's `data` directly, sidestepping lazy version creation. This PR fixes that issue by properly using the file attribute in this case (and also throughout GEVER). We also change the `update_file` method of a document a bit and allow it to re-use unchanged arguments from an already present `file`.
Fixes https://github.com/4teamwork/opengever.core/issues/3641.
Backport needed: [2017.6-stable](https://github.com/4teamwork/opengever.core/tree/2017.6-stable)

Ensure new versions are created when doc-properties change.

---

docs/HISTORY.txt
versions.cfg

Let's use the latest ruby and nokogiri version:
- ruby (2.3.3 -> 2.4.2)
- nokogiri (1.7.2 -> 1.8.1)

Use latest ruby (2.4.2) and nokogiri (1.8.1)

---

docs/HISTORY.txt
opengever/task/browser/accept/main.py
opengever/task/tests/test_team_tasks.py

with option participate. Make sure the SQL task objects gets updated after changing the workflow state, its possible that some of the metadata gets changed or updated when a task gets accepted, for an example when accepting a team task.

Fix bux when accepting a multi admin unit team task

---

opengever/meeting/browser/meetings/templates/meeting-noword.pt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

- Use `abschliessen` instead of `beschliessen` more consistently.
- Shorten description, drop technical details.

Improve wording for meeting buttons/descriptions.

---

docs/HISTORY.txt
opengever/officeconnector/service.py

As discussed, the OC testing overhaul to easier enable testing for this without exploding the ZServer layer runtimes way out of hand will land later.
Closes #3640

 Append a missing context to the OC multiattach error message

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Use `abgeschlossen` instead of `beschlossen` when agenda items are concerned. The term `beschlossen` i.e. decided should only be used when we talk about proposals.
_CL imho not necessary._

Use `abgeschlossen` instead of `beschlossen`.

---

docs/HISTORY.txt
opengever/mail/browser/extract_attachments.py

One of the jpg has `image/jpg` as content type which is not a registered mimetype. I tried to add it as a new mimetype but could not make it work yet.
For now, simply fixing the missing condition will avoid crash and simply give a missing icon in the table, see below. That safeguard should anyway be there.
fixes #3637

Fix bug for unknown mimetypes

---

docs/HISTORY.txt
opengever/dossier/base.py
opengever/dossier/browser/tabbed.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/tests/test_tabbed.py

- Only show subdossier tab on dossiers where the max depth allows to add subdossiers.
- Reworked and renamed the `is_subdossier_addable` method.
- Always show the subdossier tab, when subdossiers exists, even when there not allowed by the max_depth.
Backport needed: 2017.5.x

Show subdossier depending on max dossier depth.

---

docs/HISTORY.txt
opengever/core/upgrades/20171128092302_increase_group_title_length/upgrade.py
sources.cfg

The limit of 50 makes no sense and bring problems with the new group title sync option (see https://github.com/4teamwork/opengever.core/pull/3638).
This PR contains only the schema migration, schema change in https://github.com/4teamwork/opengever.ogds.models/pull/50.

Increase group title length.

---

docs/HISTORY.txt
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py

The group title attribute is configurable by the IOGDSSyncConfiguration group_title_ldap_attribute configuration flag and can be a multivalued attribute.

OGDS sync: handle multivalued group titles.

---

opengever/officeconnector/configure.zcml

Seems I initially forgot to register the locales in ZCML and this caused translations to not work within the endpoint.

Register locales for opengever.officeconnector

---

docs/HISTORY.txt
opengever/document/browser/actionbuttons.py
opengever/document/browser/templates/macros.pt
opengever/document/tests/test_document_tooltip.py
opengever/mail/tests/test_mail_overviewtab.py

not for mails. The opengever.pdfconverter only converts documents not mails.
There already a test for that case, but didn't fail because it tests
the actions with an empty mail.
Needs Backport: `2017.6-stable`

Make sure PDF Preview link is only available for documents,

---

docs/HISTORY.txt
opengever/document/configure.zcml
opengever/document/document.py
opengever/document/forms.py
opengever/document/tests/test_document.py

Backport needed: `2017.6-stable`
Don't display radio buttons to keep or remove a file in the add form, when there are validation errors. It does not make sense there since the document is being created.
The widget is rendered as follows:
Vs. old widget:

 Don't display nochange/remove for file in add-form.

---

docs/HISTORY.txt
opengever/journal/templates/journal_selection.pt
opengever/journal/tests/test_journal_tab.py

Make sure the manual entry add form is called on the current context, so that the entry is added to the right journal.
Backport-needed: `2017.6-stable`

Fix manual journal entry link on documents journal.

---

docs/HISTORY.txt
opengever/task/browser/delegate/utils.py

We need to use `update_reponsible_field_data` to correctly fill responsibles at the moment. This was not the case in this form yet.
Backport-needed: `2017.6-stable`
Tests will follow in a separate PR only for `master`. I've run into issues with local role datatypes in our test fixture.

Correctly handle all responsibles while delegating.

---

test-i18n-de.cfg

Shell defaults and implementation details have varied over time and this is the most portable way to ensure the behaviour we seek.
Closes #3458

Explicitly set globstar for the i18n tripwire script

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/debug.py
opengever/meeting/tests/test_meeting_debug.py

The view offers a zip that contains the following files for a meeting, if available:
- protocol header filled sablon template
- all agenda item documents (ad-hoc or from proposal)
- all paragraph filled sablon templates
- protocol footer filled sablon template
This will help to quickly acquire the documents necessary to debug possible docxcompose issues.

Add debug view to download docxcompose raw files.

---

docs/public/admin-manual/meeting/debugging.rst

Add documentation for view added in https://github.com/4teamwork/opengever.core/pull/3710.

Document debug_docxcompose in docs.

---

opengever/api/tests/test_scanin.py
opengever/dossier/tests/test_protect_dossier.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/task/tests/test_delegate.py
opengever/testing/fixtures.py
opengever/testing/test_case.py

Add tests for https://github.com/4teamwork/opengever.core/pull/3708. This is a separate PR in order to avoid too many changes in the predecessor PR and make back-porting easier.
Also always use a `list` for local roles as this is expected by plone and may trip up `_mergedLocalRoles` when not doing so.
_CL was already provided in https://github.com/4teamwork/opengever.core/pull/3708, an additional one should not be necessary._

Add tests for delegating a task to an inbox.

---

opengever/base/tests/test_reference.py

These were unnecessary inheritances (the only thing they used from the inheritance was the setup). This made us run 61 tests instead of 44.

Fix inheritance in test_reference

---

opengever/dossier/tests/test_dossier_byline.py

Another inheritance that made us run 18 instead of 10 tests.

Fix inheritance in test_dossier_byline

---

opengever/dossier/tests/test_dossier.py

Moved the `TestMeetingFeatureTypes` from `FunctionalTestCase` to `IntegrationTestCase`

Rewrite dossier test to integration layer

---

opengever/dossier/tests/test_dossier.py

Sorry, just realised I forgot to remove the unused imports in https://github.com/4teamwork/opengever.core/pull/3717

Removed unused imports

---

opengever/meeting/tests/test_meeting_dossier_byline.py

We should not import a test class in the current namespace. Otherwise all its tests get executed.
This happened only twice in the gever code, both are fixed now (the other one in https://github.com/4teamwork/opengever.core/pull/3725)

Correct import in test_meeting_dossier_byline.

---

opengever/mail/browser/extract_attachments.py
opengever/mail/browser/templates/extract_attachments.pt
opengever/tabbedview/browser/selection_with_filters.pt
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview-manual.pot
opengever/tabbedview/locales/opengever.tabbedview.pot

Normalize appearance of 'all' and 'none' shortcuts.

---

opengever/dossier/tests/test_dossier_ids.py

Should this kind of test remain a functional test? It does run much faster (20ms instead of 700ms) as IntegrationTest, but will be sensitive to changes in the Fixture.

Changed test_dossier_ids to IntegrationLayer

---

docs/HISTORY.txt
opengever/meeting/tabs/meetinglisting.py

Resolves https://github.com/4teamwork/gever/issues/159

Fix width of dossier and title column in meeting tab

---

opengever/mail/mail.py

We always want to use a NamedBlobFile. No need for the import dance here.
Stumbled upon this while investigating while we still have some `NamedFile` instances. May have been the reason 🤔 . I think it is better if we remove this now.
See also https://github.com/4teamwork/opengever.maintenance/pull/102.

Remove blobfile import dance.

---

opengever/core/testing.py
opengever/document/tests/test_bumblebee.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Port some bumblebee tests to integration tests.
Also provide setup required for bumblebee in the fixture, but make sure to turn it off by default. It  must be enabled with the `features` test class variable or per test with `enable_feature`.

Port bumblebee tests to integration tests.

---

docs/HISTORY.txt
setup.py

- Bump next version to 2017.8.0.
- Clean up changelog after releasing hotfix-relase 2017.7.3. Release has been created from 2017.7-stable release

Version and changelog cleanup after 2017.7.3 hotfix release

---

versions.cfg

because of using production-v2.cfg in ftw-buildouts on our new gever server, we have to pin "plone.recipe.command = 1.1" in versions.cfg.

Pin plone.recipe.command version to 1.1

---

bin/mtest

https://bugs.python.org/issue15373
Stumbled upon that. Apparently we were still not making a proper copy of the environment for the workers. Even though this is now moot for mtest as we run the ZServer layer in its own runner, this is still good practice.

Actually make a copy of os.environ for the workers

---

opengever/document/checkout/manager.py
opengever/document/checkout/revert.py

The redirect cascade upon `Unauthorized` access currently makes `plone.protect` jump in 4 times unnecessarily.
Also cleaned up the checkout manager a bit.

Change faulty content types from unauthorized document revert redirects

---

README.rst
opengever/contentstats/tests/test_content_stats_integration.py
opengever/dossier/tests/test_overview.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_meeting_dossier_overview.py
opengever/tabbedview/tests/test_personaloverview.py
opengever/task/tests/test_team_tasks.py
opengever/testing/fixtures.py

Tests for the `MeetingDossier` overview were not executed anymore since we moved them to `IntegrationTestCase`. Instead we executed the tests twice for the `Dossier` overview. This test inherits from the `dossier.tests.test_overview.TestOverview`, and used to (when still on the `FunctionalLayer`) redefine the `setUp` method to work on a `MeetingDossier` instead of a `Dossier`. This is not so easily done in the `IntegrationLayer` and had not been taken care of.
Several elements were missing in the fixture to allow testing of the `MeetingDossier` overview. To reuse the test of the `Dossier` for the `MeetingDossier` I needed a similar structure in both the `dossier` and `meeting_dossier`. The `OpengeverContentFixture` was modified as follows:
* Add a document `meeting_document` in the …

Correct dossier overview tests

---

opengever/mail/tests/test_extract_attachments.py

Add tests to
* verify that mimetype lookup can handle unknown mimetypes
* verify that `extract_attachments` view can handle attachments with unknown mimetypes
solves #3689

Add test attachment with wrong mimetype

---

docs/HISTORY.txt
opengever/task/browser/accept/newdossier.py

When accepting a multi adminunit task and selecting the store and editing in a newdossier step. The dossier responsible field does not work. The AJAX call to the search endpoint ist not working (404).
The reason is that the typename, which is used by the WizzardWrappedAddForm, is not set in the widget_traversal request, therefore I add an fallback to the default dossier type.
Backport-needed to `2017.6-stable`

Fix dossier responsible widget, in the DossierAddFormView step.

---

opengever/base/skins/opengever.base_scripts/search.py
setup.py

The package `izug.basetheme` is mentioned in two places. Afaik it has been long deprecated now, so this cleanup should be justified.

Remove hints about izug.basetheme.

---

docs/HISTORY.txt
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20171211081352_let_administrators_save_new_versions/rolemap.xml
opengever/core/upgrades/20171211081352_let_administrators_save_new_versions/upgrade.py
opengever/document/tests/test_force_checkin.py

Give administrators the `CMFEditions save new version` permission, which is necessary to checkin a document and creating a new version.
Closes #3756.

Fix force-checkin for administrators.

---

.ci_governor.yml

To ensure that we don't use too many resources on our jenkins, we now have weight based builds. 
So we can make sure we don't block any other builds, and also use the maximum resources without overloading our jenkins.

use weight 5 on jenkins for test-plone-4.3.x.cfg

---

opengever/dossier/tests/test_dossier_workflow.py

I think I would need some input here. All 3 tests tested were testing only negative results, which is not very robust. I added a positive test for `test_deleting_dossier_is_only_allowed_for_managers`. For the two others I could not find any situation where these two workflow transitions appear in the action menu.

Move test_dossier_workflow to IntegrationLayer

---

docs/HISTORY.txt
opengever/journal/handlers.py

Object deletion has been journalized as an object movement which is wrong. 
Besides that it breaks also the removal of the plonesite (closes #3788).

Ignore Object(Will)RemovedEvents in the journal handlers.

---

opengever/task/browser/delegate/metadata.py
opengever/task/tests/test_delegate.py

Since we use the keywordwidget for user selection, prefiling via request does not longer work. But the standard z3c.form wys does now work with the new widget. 🎉 
Closes #3714.
Besides that, I converted the tests to integration tests.

Task delegate form: Prefill issuer with current user

---

opengever/testing/fixtures.py
opengever/testing/helpers.py
opengever/testing/tests/test_fixtures.py

**Goal:**
We want to have predictable intids in the tests, so that we can assert the intids and also oguids (which are based on intids).
**Thoughts:**
We freeze the time and already a use a static UID generator. The fixture is fragmented into groups, frozen to a specific hour and with a certain UID prefix so that we avoid conflicts while still beeing able to keep the values as static as possible.
Since the ID is a ten-digit integer, we cannot prefix it with a string. We've therefore decided to base the intid generation on the current time, which we expect to be already frozen.
**Implementation:**
The generated ID consists of: `100, hour, minute, second, 00`, wherease the ending `00` is used for conflict resolution incrementation, although this should not happen in the fixture when we …

Have predictable intids in the fixture.

---

docs/HISTORY.txt
opengever/meeting/form.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_committee.py
opengever/meeting/vocabulary.py
opengever/testing/fixtures.py

This PR uses the widget to inject initial data instead of the request.
This is a better way of loading data especially since the data is set from a data converter which can also deal with vocabularies that have values that differ from their tokens.

Fix pre-filling committee group id in edit form.

---

docs/HISTORY.txt
opengever/task/browser/delegate/metadata.py
opengever/task/browser/delegate/recipients.py
opengever/task/tests/test_delegate.py

Set missing_value for the `responsible` field in the delegate task form, otherwise the `z3c.form.field.FieldWidgets.extract` those not raise an requiredinput validation error.

Delegate task form: Fix required input validation for the recipients field

---

opengever/dossier/tests/test_documents_tab.py

The `link.click()` makes the first test slow, but it calls the `redirect_to_parent_dossier` view, which I don't think can be tested simply from the URLs.

Change documents_tab test to IntegrationTestCase

---

README.rst
docs/HISTORY.txt
opengever/core/lawgiver.zcml
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/rolemap.xml
opengever/core/profiles/default/types.xml
opengever/core/profiles/default/types/opengever.workspace.workspace.xml
opengever/core/profiles/default/workflows.xml
opengever/core/tests/test_relations.py
opengever/core/upgrades/20171213174551_add_workspace_content_type/rolemap.xml
opengever/core/upgrades/20171213174551_add_workspace_content_type/types.xml
opengever/core/upgrades/20171213174551_add_workspace_content_type/types/opengever.workspace.root.xml
opengever/core/upgrades/20171213174551_add_workspace_content_type/types/opengever.workspace.workspace.xml
opengever/core/upgrades/20171213174551_add_workspace_content_type/upgrade.py
opengever/core/upgrades/20171213174551_add_workspace_content_type/workflows.xml
opengever/dossier/behaviors/dossiernamefromtitle.py
opengever/dossier/sequence.py
opengever/testing/builders/dx.py
opengever/testing/fixtures.py
opengever/workspace/interfaces.py
opengever/workspace/permissions.zcml
opengever/workspace/tests/test_workspace_workspace.py
opengever/workspace/workspace.py
opengever/workspace/workspace_root.py

Adds a new content type `opengever.workspace.workspace`.
Workspaces should have an id with a sequence number -> `workspace-X`. 
However, we can't implement a new sequencer nor a new name-from-title class since workspace already gets the one from dossier. Plone cant decide which one to use if there are two implementations of the same thing provided to the content type. 
Thats why we put some `if`s into the code of dossiers to generate the sequenced id.
closes #3676

Add workspace content type

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/tests/test_meeting_edit.py
opengever/meeting/tests/test_meeting_view_word.py

Because the plone_view's `showEditableBorder` checks for `ModifyPortalContent`, we have to enable the border manually otherwise the zip export action is not available for committee members.
Closes #3828 
Backport-to: `2017.7-stable`

Enable edit border for committee members on meeting view.

---

bin/mtest

Motivation: We're already in a situation where adding new integration tests directly adds to the wallclock runtime. Good work, @njohner, you forced me into this corner again.
* Uses the test discovery output of `bin/test` to discover test classes per test layer
* We're approaching a point where we could take this approach upstream to `zope.testrunner`
* Upstream already splits layers onto processes with the `-j` parametre
* The discovery penalty is about 6s on our CI infrastructure
* Provides clear knobs for tweaking when the reality of layer runtimes changes again
* Removes duplication of output printing in debug and non debug runs
* Improves debug output
* Fixes a rounding bug in `humanize_time()`
* Moves to use async futures returned from the pool
* Polls the futures every 1s for …

Generalize splitting layers in mtest

---

docs/HISTORY.txt
opengever/activity/center.py
opengever/activity/tests/test_notification_viewlet.py
opengever/activity/viewlets/notification.py

Since the the personal settings feature, the badge icon is a separate channel. But the number getter in the viewlet counts all notifications not only the badge notifications wich leads in wrong/confusing unread numbers. This PR fixes #3842.

Fix notification counter, count only badge notifications.

---

docs/HISTORY.txt
opengever/task/tests/test_util.py
opengever/task/util.py

This fixes an issue when completing a task (in-progress to resolved)
the state is not updated in the globalindex.

Trigger SQL task synchronisation when changing task state.

---

docs/HISTORY.txt
opengever/base/browser/list_groupmembers.py
opengever/base/tests/test_list_groupmembers.py

Fix listing members of an empty group

---

README.rst
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/dossier/tests/test_base.py
opengever/dossier/tests/test_dossier.py
opengever/dossier/tests/test_indexer.py
opengever/dossier/tests/test_move_items.py
opengever/mail/tests/test_indexers.py
opengever/meeting/tests/test_meeting_listings.py
opengever/tabbedview/tests/test_personaloverview.py
opengever/task/tests/test_team_tasks.py
opengever/testing/fixtures.py

I've added quite a few elements to the fixture as we needed different elements in different states. We could obviously do without, by changing the state of existing elements instead. This is pretty slow though (around 0.2s or so). I guess in the end this will depend on how many tests use different elements from the fixture.

Move test_move_items to IntegrationLayer.

---

docs/HISTORY.txt
opengever/meeting/committee.py
opengever/meeting/tests/test_committee_roles.py

Viewing and editing the committee are now not coupled to only the group selectable in the committee any more. We should always display all groups since it is valid that users that are not in the group can edit the committee (i.e. when they have the CommitteeResponsible role).
This fixes an issue where the group would always be changed to another one since the `CommitteeResponsible` was not in said group but still able to edit the committee.
Needs backport to `2017.7-stable`.

Display all LDAP groups for the committee.

---

docs/HISTORY.txt
opengever/core/profiles/default/types/opengever.workspace.root.xml
opengever/core/upgrades/20171220185847_configure_tabbedview_for_workspace_root_as_default_view/types/opengever.workspace.root.xml
opengever/core/upgrades/20171220185847_configure_tabbedview_for_workspace_root_as_default_view/upgrade.py
opengever/workspace/browser/configure.zcml
opengever/workspace/browser/tabbed.py
opengever/workspace/browser/tabs.py
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot

This PR bases on #3824, please merge this one first.
Currently we have only one tab... I know this is no useful, but it will be replaces really soon.

Add tabbed_view with one tab listing all workspaces to workspace root

---

docs/HISTORY.txt
opengever/advancedsearch/resources/advanced_search.js

Catch up with changes in https://github.com/4teamwork/ftw.keywordwidget/pull/24.
The function called in `opengever.core` no longer exists. We change widget initialization to the way it is done in `ftw.keywordwidget` now.
Fixes #3859.

Fix broken advanced search js initialization.

---

README.rst
docs/HISTORY.txt
opengever/core/lawgiver.zcml
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/rolemap.xml
opengever/core/profiles/default/types.xml
opengever/core/profiles/default/types/opengever.workspace.folder.xml
opengever/core/profiles/default/workflows.xml
opengever/core/tests/test_relations.py
opengever/core/upgrades/20171220151710_add_workspace_folder_content_type/rolemap.xml
opengever/core/upgrades/20171220151710_add_workspace_folder_content_type/types.xml
opengever/core/upgrades/20171220151710_add_workspace_folder_content_type/types/opengever.workspace.folder.xml
opengever/core/upgrades/20171220151710_add_workspace_folder_content_type/types/opengever.workspace.workspace.xml
opengever/core/upgrades/20171220151710_add_workspace_folder_content_type/upgrade.py
opengever/core/upgrades/20171220151710_add_workspace_folder_content_type/workflows.xml
opengever/testing/builders/dx.py
opengever/testing/fixtures.py
opengever/workspace/behaviors/configure.zcml
opengever/workspace/behaviors/namefromtitle.py
opengever/workspace/configure.zcml
opengever/workspace/interfaces.py
opengever/workspace/permissions.zcml
opengever/workspace/sequence.py
opengever/workspace/tests/test_workspace_folder.py
opengever/workspace/workspace_folder.py

Adds a new content type `WorkspaceFolder` which is only addable inside a Workspace and inside itself.
closes #3677

OGIP 17:  Add workspace folder content type

---

docs/HISTORY.txt
opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py

Closes https://github.com/4teamwork/opengever.core/issues/3732

Display document mimetype icon on livesearch results.

---

docs/HISTORY.txt
opengever/ogds/base/sources.py
opengever/workspace/__init__.py
opengever/workspace/tests/test_workspace_sources.py
opengever/workspace/utils.py

- Only users with a role having the View permission are selectable.
The implementation is basically taken from my.teamraum.com
1. Get all Roles with View permission
2. Walk up the aq_chain and get all userids with having the local roles having the view permission.
3. Extend the sources queries with the collected userids if the Task is added in a Workspace.
I tried to avoid filtering for empty list, since this may have a performance impact.

OGIP 17: Implement AllUsersInboxesAndTeamsSource also for Workspace.

---

opengever/workspace/tests/test_workspace_folder.py

The problem is that two pull requests were merged without rebasing. The combination breaks the test.
- https://github.com/4teamwork/opengever.core/pull/3861
- https://github.com/4teamwork/opengever.core/pull/3823

Disable broken build.

---

docs/HISTORY.txt
opengever/globalindex/handlers/task.py
opengever/repository/tests/test_repositoryfolder_tabs.py

When inserting the task entry in the globalindex, the "created" value was set to the current database time and not the Plone object's created time.
This can lead to a small difference in production and it makes testing harder because it is not predictable.
This change should fix the tests and will make testing easier in the future.
It has a low impact on production. 
We are not reindexing current entries and leave them inconsistent because this would be too expensive and has no known pratical gain other than better consistency.

Task globalindex: set the created time in sql from the Plone object.

---

docs/HISTORY.txt
opengever/base/browser/resources/base.js
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20171227115310_move_base_javascript_after_keywordwidget/jsregistry.xml
opengever/core/upgrades/20171227115310_move_base_javascript_after_keywordwidget/upgrade.py

The auto focus was just limited to textareas and text input elements.
Closes https://github.com/4teamwork/opengever.core/issues/3807

Fix autofocus on forms with keywordwidget.

---

docs/HISTORY.txt
opengever/base/browser/resources/logoutClient.js
opengever/base/browser/resources/logoutWorker.js
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20171221172209_install_logout_shared_worker/jsregistry.xml
opengever/core/upgrades/20171221172209_install_logout_shared_worker/upgrade.py

When a logout is triggered in one gever tab, all other tabs are reloaded
automatically.
This is done through a SharedWorker. All tabs are connected with this
SharedWorker. If one tab sends a logout message to the worker the worker
broadcasts a logout message to all open gever tabs.
According to https://caniuse.com/#feat=sharedworkers this is just
working in Chrome and Firefox.
⚠️ This implementation is not working for cross-site worker invocations. As far as I know the SharedWorkers obey the cross origin security. Maybe a simple CORS header will do the trick.
/cc @Rotonen Thanks for the tip 👍

Implement cross tab logout mechanism.

---

README.rst
opengever/core/cached_testing.py

The new environment variable ``GEVER_CACHE_VERBOSE`` causes a list of modified files to be printed when a testing cache stack's cachekey is considered invalid. This can be useful for debugging the test caching.

Testing cache: add verbosity option for debugging.

---

opengever/core/cached_testing.py

I have noticed that the .pyc-files are sometimes updated after the cachekey was stored. This causes the cachekey to invalidate on the next run too. The .pyc-files are actually not relevant for us: we want the cache to invalidate when the actual code changes.

Exclude .pyc-files from cached-testing cachekeys.

---

docs/HISTORY.txt
opengever/base/reference.py
opengever/base/reference_formatter.py
opengever/private/browser/tabbed.py
opengever/private/dossier.py
opengever/private/quota.py
opengever/private/reference.py
opengever/private/tests/__init__.py
opengever/private/tests/test_delete_action.py
opengever/private/tests/test_reference_number.py
opengever/private/viewlets/quotawarning.py

* Amended the private dossier reference number getter
* Get the current formatter
* If possible, use the current separator
* Default to a space
Did not go for making the prefix configurable per repository root / repository folder. Splitting that onto its own issue to be tackled later down the line.
Closes #3571

 Prefix the reference numbers on private dossiers with a P

---

docs/HISTORY.txt
opengever/meeting/command.py

If no excerpt header template is available, fall back to agenda item`s document as master.
This fixes an issue with headings not taken from the correct file in the merged word documents.
Needs backport to `2017.7`.

Use excerpt header template as master, if available.

---

docs/HISTORY.txt
opengever/core/upgrades/20180109091110_add_index_to_committee_title/upgrade.py
opengever/meeting/model/committee.py

The select statement explained (before adding the index):
```
opengever.kern=# EXPLAIN SELECT committees.id AS committees_id, committees.group_id AS committees_group_id, committees.admin_unit_id AS committees_admin_unit_id, committees.int_id AS committees_int_id, committees.title AS committees_title, committees.physical_path AS committees_physical_path, committees.workflow_state AS committees_workflow_state FROM committees ORDER BY committees.title;
QUERY PLAN                              
---------------------------------------------------------------------
Sort  (cost=11.04..11.11 rows=30 width=2150)
Sort Key: title
->  Seq Scan on committees  (cost=0.00..10.30 rows=30 width=2150)
(3 rows)
```
The select statement explained (after running the upgrade step):
```
opengever.kern=# EXPLAIN …
```

Add index to sort committees by title

---

opengever/examplecontent/profiles/default/registry.xml

Ech0147 has been implemented with in https://github.com/4teamwork/opengever.core/pull/3249 and https://github.com/4teamwork/opengever.core/pull/3669. This PR enables these features by default for our development profile:

Enable ech0147 for our development profile.

---

docs/HISTORY.txt
opengever/ech0147/tests/test_import.py
opengever/ech0147/utils.py

This PR fixes an issue where the `bumblebee_checksum` is not calculated for documents that are imported with the ECH0147 import.
Fixes #3889.

Fix bumblebee preview in ECH0147 import.

---

docs/HISTORY.txt
setup.py

We're close to cutting a release and customers start testing. They should see the next released version.

Set next upcoming release to 2018.1.0.

---

docs/HISTORY.txt
opengever/officeconnector/helpers.py
opengever/officeconnector/testing.py
opengever/officeconnector/tests/test_api_dossier_checkout.py
opengever/officeconnector/tests/test_zopemaster.py
opengever/testing/assets/__init__.py

Just mirroring `plone.restapi` here.
We had cloned the logic from there as we needed to customize it, so the fix did not propagate down to what we're actually doing just by upgrading `plone.restapi`.

 Fix JWT authentication for users from the Zope root acl_users for OC payloads

---

docs/HISTORY.txt
opengever/bumblebee/tests/test_overlay_view.py
opengever/document/browser/actionbuttons.py

Appends the version_id parametre to download links if it is present in the request and that is not the current version.
Closes #3863

Ensure bumblebee overlay view download links point to the correct version

---

docs/HISTORY.txt
opengever/inbox/browser/assign.py
opengever/inbox/forwarding.py
opengever/inbox/tests/test_forwarding.py
opengever/task/browser/assign.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/task.py
opengever/task/tests/test_assign.py

And support teams also when reassigning task/forwardings, but only when the task/forwarding is in an open state, otherwise the User is informed via message.
Closes #3888 
Was a missing part of the OGIP 24 Teamaufgaben

Make teams available on forwardings

---

docs/HISTORY.txt
opengever/base/browser/edit_public_trial.py
opengever/core/profiles/default/types/opengever.workspace.folder.xml
opengever/core/upgrades/20180123112216_change_default_view_of_workspace_folder/types/opengever.workspace.folder.xml
opengever/core/upgrades/20180123112216_change_default_view_of_workspace_folder/upgrade.py
opengever/dossier/base.py
opengever/workspace/browser/configure.zcml
opengever/workspace/browser/tabbed.py
opengever/workspace/tests/test_workspace_workspace.py

- Use tabbedview as default view for WorkspaceFolder
- Fix Dossierstrcucture listing on overview tab
- Fix file detail view for files in workspace
closes #3678

Various improvements for Workspaces

---

opengever/core/upgrades/20180131153203_drop_unused_sequences/upgrade.py

Ran `SELECT c.relname FROM pg_class c WHERE c.relkind = 'S';` on an older client installation and a fresh installation and diffed:
```
--- fresh.txt	2018-01-30 18:41:38.000000000 +0100
+++ <redacted>.txt	2018-01-30 18:41:29.000000000 +0100
@@ -23,9 +23,11 @@
participations_id_seq
periods_id_seq
phonenumber_id_seq
+proposal_history_id_seq
proposal_id_seq
resources_id_seq
submitteddocument_id_seq
+subscriptions_resource_id_seq
task_id_seq
teams_id_seq
urls_id_seq
```
Closes #3477.

Drop unused SQL sequences

---

opengever/base/reference_formatter.py
opengever/core/upgrades/20180131180538_regenerate_and_reindex_reference_numbers_on_private_roots_and_their_contents/upgrade.py
opengever/private/configure.zcml
opengever/private/dossier.py
opengever/private/reference.py
opengever/private/root.py
opengever/private/tests/test_dossier.py
opengever/private/tests/test_folder.py
opengever/private/tests/test_reference_number.py

Nicked the logic from: https://github.com/4teamwork/opengever.core/blob/a3eb6bb6b41d710441664de50bcd003c6f8ae1f7/opengever/dossier/handlers.py#L57-L79
Closes #3897

Regenerate and reindex reference numbers on private dossiers

---

opengever/examplecontent/configure.zcml
opengever/examplecontent/profiles/default-ska/metadata.xml
opengever/examplecontent/profiles/default-ska/unit_creation/admin_units.json
opengever/examplecontent/profiles/default-ska/unit_creation/org_units.json

In development, we have only one admin unit "FD" (=Plone site). In order to test things locally with two admin units, this adds a second admin unit "SKA" with one org unit, allowing for a easier setup.
When using it, make sure to not purge the SQL on setup.

Add SKA admin unit for development.

---

opengever/tabbedview/helper.py

Seems like a trivial copy/paste or carelessness from the initial implementation. It only ever acted as a fallback of the JS having failed to interject.
Closes #3922

Fix malformed version URL on documents

---

opengever/core/upgrade.py

When setting up an admin unit (Plone site), all past schema migrations are tracked as installed by inserting rows into the shared SQL.
Since we did not check whether the row was already added by another admin unit, there were SQL insertion errors when installing the second admin unit.
- Also removed an unused import.
- No changelog since initial implementation is in same release.

Fix multi admin unit setup.

---

opengever/core/cached_testing.py

When running functional tests, the opengever_upgrade_version may be left over because it is not registered in the metadata because of it's special nature (it is created on the fly).
This leads to problems when running integration tests from cache after running functional tests: in this case we have the table in our cache and cannot recreate it because it already exists.
The easiest solution is to just drop the table before loading from cache.

Fix testing cache by dropping opengever_upgrade_version table.

---

docs/HISTORY.txt
opengever/portlets/tree/resources/init_tree.js
opengever/portlets/tree/resources/tree.js

Closes https://github.com/4teamwork/opengever.core/issues/3359
Every time the navigation tree wants to mark an entry with a favorite
tag, it triggers an XHR for getting all favorites entries.
So use promises to keep the loading task of the favorites pending until the data is
retrieved by the ajax call.

Prevent navigation tree from getting favorites multiple times.

---

docs/HISTORY.txt
opengever/document/extra_mimetypes.py
opengever/policy/base/profiles/mimetype/mimetypes.xml
opengever/policy/base/upgrades_mimetypes/20180207161442_add_missing_extensions_to_mimetype_registry/mimetypes.xml
opengever/policy/base/upgrades_mimetypes/20180207161442_add_missing_extensions_to_mimetype_registry/upgrade.py

This PR fixes the various mimetype registries in such a way that they yield results as epxpected by bumblebee, see also https://github.com/4teamwork/ftw.bumblebee/blob/bc7b6f9ad9efe7bffd91a50b7a984797b0018d32/ftw/bumblebee/mimetypes.py#L19-L64.
Bumblebee expects the extension to be set for a mime-type in the plone mimetypes registry:
- Add `bmp` extension to `image/bmp`
- Add `ini` extension to `text/plain`
Also we need to register `ini` with python:
- Treat `ini` as `text/plain`

Fix mimetype registries.

---

docs/HISTORY.txt
opengever/core/upgrades/20180207171348_fix_order_of_select2_styles/cssregistry.xml
opengever/core/upgrades/20180207171348_fix_order_of_select2_styles/upgrade.py

The z-index of the value dropdown has been alredy fixed in this PR https://github.com/4teamwork/plonetheme.teamraum/pull/605, but opengever.core
does not make sure that the ftw.keywordwidget css files are loaded
before the gever.css.
Change includes an upgradestep which fixes the order also for existing deployments.

Fix select2 value dropdowns, which has been hidden by the exposator.

---

docs/HISTORY.txt
opengever/contentstats/providers.py
opengever/contentstats/tests/test_content_stats_integration.py

**Content stats**: Avoid producing empty string key in mimetypes stats (like these for example):
```
{
"": 77,
"application/pdf": 5,
"image/png": 3,
}
```
We need to prevent this because several components in the ELK stack (filebeat, elasticsearch) can't deal with empty JSON keys gracefully, and choke on them.
_(Only last commit contains actual functional changes, the rest is cleanup/tests)._

Content stats: Avoid producing empty string key in mimetypes stats

---

docs/HISTORY.txt
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180208155711_register_etag_value_for_repository_favorites/registry.xml
opengever/core/upgrades/20180208155711_register_etag_value_for_repository_favorites/upgrade.py
opengever/portlets/tree/configure.zcml
opengever/portlets/tree/favorites.py
opengever/portlets/tree/tests/test_favorites.py

Because the favorites cache key is placed in the page the cache for for the favorites request is never updated when the page comes from cache.

Include favorites cache key in page cache key

---

docs/HISTORY.txt
opengever/contentstats/configure.zcml
opengever/contentstats/filters.py
opengever/contentstats/providers.py
opengever/contentstats/tests/test_content_stats_integration.py

**Content stats**: Add custom GEVERPortalTypesProvider that sums up docs and mails:
This provider extends the list of `portal_types` with a new, fake portal_type `_opengever.document.behaviors.IBaseDocument` that contains the sum of regular documents and mails.
This is needed for easier processing down the line in the ELK stack.

Content stats: Add custom GEVERPortalTypesProvider that sums up docs and mails

---

docs/HISTORY.txt
opengever/ogds/base/browser/templates/userdetails.pt
opengever/ogds/base/browser/userdetails.py
opengever/ogds/base/tests/test_userdetails.py

User details view: URLEncode group IDs in links to group members. This for example is necessary to make groups with spaces in their ID work.

User details view: URLEncode group IDs in links to group members

---

sources.cfg

Switch ftw.solr to master branch, since the `tb-reimplementation` branch has been merged now.

Switch ftw.solr to master branch.

---

opengever/core/upgrades/20180131124231_activate_placeful_workflow_for_private_area/upgrade.py

Upgrade fails if there's no private area.

Fix ActivatePlacefulWorkflowForPrivateArea upgrade step

---

docs/HISTORY.txt
opengever/tabbedview/sqlsource.py
opengever/tabbedview/tests/test_sorting.py
opengever/tabbedview/tests/test_sqlsource.py

The tabbed view allows to configure the sorting of tables for each user.
If after a migration the column the user used to sort the data is not available anymore, the server responds with an error.
This prevents sorting by unavailable columns.
Resolves #3468

Sort query only if column exists

---

docs/HISTORY.txt
opengever/portlets/tree/favorites.py
opengever/portlets/tree/tests/test_favorites.py

Fix repository favorites cache key generation for Anonymous users: Anonymous users can't have repository favorites - we therefore short circuit cache key generation, no need to ask the view.
This avoids `Unauthorized` exceptions where we attempted to traverse to the view as Anonymous users, just to ask it for its `ETag` contribution.

Fix repository favorites cache key generation for Anonymous users

---

docs/HISTORY.txt
docs/public/dev-manual/api/examples/example_get_custom_summary.py
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/operations.rst
docs/public/dev-manual/api/searching.rst
docs/public/dev-manual/api/summaries.rst
opengever/api/summary.py
opengever/api/tests/test_summary.py

It's now possible to specify additional fields that should be returned in summaries of GET requests.
The requested fields are given with the url parameter `items.fl`.
Example: `items.fl=filename,filesize,modified`

Restapi items fieldlist

---

opengever/tabbedview/browser/selection_with_filters.pt
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview-manual.pot
opengever/tabbedview/locales/opengever.tabbedview.pot

Add missing ftw.tabbedview domain as we translate the label in that domain for all listings.
Fixed:
Before:
Backref: https://basecamp.com/2768704/projects/12554551/todos/341841512

Add missing translation domain.

---

docs/HISTORY.txt
opengever/activity/mail.py
opengever/activity/templates/notification.pt

The summary contains markup elements which is not displayed well by certain mail clients.
Backref https://basecamp.com/2768704/projects/12554551/todos/341966157.

Use mail subject as title.

---

docs/HISTORY.txt
opengever/activity/browser/settings.py
opengever/activity/tests/test_settings.py
opengever/core/upgrades/20180213141432_migrate_grouped_notification_settings/upgrade.py

There are some different task-transitions which ends in the same review_state, therefore ther are multiple options in the activity settings page for closing a task. Thats confusing for the user, therefore we combine them together and introduce a list of "aliased transitions".

Combine similar transitions to one in the activity settings page.

---

opengever/base/tests/test_search.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180214115035_add_sequence_number_to_solr_pattern/registry.xml
opengever/core/upgrades/20180214115035_add_sequence_number_to_solr_pattern/upgrade.py
solr-conf/managed-schema

Also index sequence number as string because querying an int field with a string value results in an error.

Add sequence number to Solr search pattern

---

MANIFEST.in

I think without this line the conf is skipped. We rely on it in our buildout recipes though.

Make sure solr-conf is in released egg.

---

opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180214153212_enable_mind_manager_with_office_connector/registry.xml
opengever/core/upgrades/20180214153212_enable_mind_manager_with_office_connector/upgrade.py

Mind Manager is supported in Office Connector 1.5.0 and later.

Enable Mind Manager with Office Connector

---

opengever/base/browser/livesearch.py

Solr livesearch: Make sure search terms are passed to advanced search link and also make sure they're URL encoded everywhere they're used in URLs.
The `searchurlparameter` that previously was passed to the advanced search link was set to a dummy value (`1`), and doesn't seem to be needed for anything else. Instead of re-introducing the [cargo-culty processing from the legacy `livesearch_reply`](https://github.com/4teamwork/opengever.core/blob/master/opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py#L82-L87), I used `self.search_terms` from the new view.
I took care of URL encoding the terms (where used in URLs), but potentially there could still be some edge cases with reserved characters in lucene queries that would need to be addressed. I'd suggest we look at …

Solr livesearch: Make sure search terms are passed to advanced search

---

docs/HISTORY.txt
opengever/core/upgrade.py

Creating the tracking table failed for oracle due to a different auto naming schema.

Fix upgrade steps for oracle.

---

bin/mtest
docs/HISTORY.txt

Fix `bin/mtest` output encoding:
The previous implementation attempted to display output by
`print()` -ing unicode text. This will fail (for content with non-ASCII characters) if the output isn't a terminal (e.g. when the output of bin/mtest is piped to another process, redirected using shell I/O
redirection, ...).
*(See https://ci.4teamwork.ch/builds/147573/tasks/232383 for an example where `bin/mtest` failed to render *any* of the test runner output because it contained a single Ç).*
Instead we use the logging module for displaying output, because it handles exactly these output encoding issues properly, depending on what encoding the output stream requires.
---
Related: #3995 *(Flaky test failures related to language selector viewlet*)

Fix bin/mtest output encoding

---

opengever/base/tests/test_anonymous.py
opengever/base/tests/test_navigation.py
opengever/base/tests/test_translated_title.py
opengever/contact/tests/test_contactfolder.py
opengever/disposition/tests/test_excel_export.py
opengever/dossier/tests/test_templatefolder.py
opengever/inbox/tests/test_inbox.py
opengever/inbox/tests/test_inbox_container.py
opengever/meeting/tests/test_committee_container.py

Skip some flaky tests for now - see 4teamwork/opengever.core#3995 (related to language selector viewlet).
(Unfortunately it's more than I previously thought - 10 tests total).

Skip some flaky tests for now

---

docs/HISTORY.txt
opengever/activity/__init__.py
opengever/activity/digest.py

Add some minimal logging for `send_digest` handler, so it's obvious during debugging whether or not digests have been send, and to which addresses.
Example output:
```
2018-02-19 14:45:00 INFO opengever.activity.digest Sending digests...
2018-02-19 14:45:00 INFO opengever.activity.digest   Digest sent for lukas.graf (lukas@example.org)
2018-02-19 14:45:00 INFO opengever.activity.digest   Digest sent for david.erni (deif@example.org)
2018-02-19 14:45:00 INFO opengever.activity.digest Done sending digests.
```

Add some minimal logging for send_digest handler

---

docs/HISTORY.txt
opengever/base/tests/test_search.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180219150514_improve_search_pattern/registry.xml
opengever/core/upgrades/20180219150514_improve_search_pattern/upgrade.py
opengever/document/configure.zcml
opengever/document/indexers.py
opengever/document/tests/test_indexers.py
opengever/tabbedview/catalog_source.py
opengever/tabbedview/tests/test_catalog_source.py
solr-conf/managed-schema

Add new field `metadata` for indexing document metadata as searchable text.
Use `metadata` field in Tabbedview filter and in search/livesearch.
Solr configuration changes:
- Preserve original term in text fields (allows using wilcards in terms that contain non-alphanumeric characters, e.g. _ice-cream_ can be found by querying for _ice-cr*_)
- Prevent splitting of search terms on non-alphanumeric, non-whitespace characters (e.g. do not split 3.9.2 into 3 9 2)

Improve Tabbedview filter in Solr

---

docs/HISTORY.txt
opengever/base/tests/test_solr.py
setup.py

Add files from `solr-conf` to `data_files`: This is needed so that they get placed into the `.egg` during installation.
Including them in `MANIFEST` only ensures these files are included in the source tarball - but for files *outside* of Python packages, these need to be explicitely listed in `data_files` in order for them to be copied *into the egg* during buildout time.
---
Also: The [documentation for `data_files`](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files) **lies**: Those files get placed relative to the `.egg` root, not `sys.prefix` (at least that's what I'm seeing in a local test).

Add files from solr-conf to data_files

---

docs/HISTORY.txt
opengever/ech0147/utils.py

This fixes an issue with bumblebee preview not being rendered correctly upon ECH0147 import.
It fixes a previous fix in https://github.com/4teamwork/opengever.core/pull/3891 which made sure checksums are calculated upon import, but does not take the storing mechanism into account. Storing checksums in bumblebee (with the `BumblebeeTriggerStoring` view) calls a view which then stores the documents in bumblebee, once the transaction has been commited. For this to succeed we need to fire the modified event when the document id is final, i.e. after it has been moved.
The issues was not discovered previously as we seem to have tested with documents that were already stored in bumblebee.

Fix bumblebee, fire modified once document is renamed.

---

docs/HISTORY.txt
opengever/base/browser/resources/generateToc.js

https://github.com/4teamwork/opengever.core/issues/3936
IE11 and Edge do not support `blob` as repsonse type for XHR requests.
So use `arraybuffer` and build the blob manually.

Fix toc download on IE11 and Edge

---

docs/HISTORY.txt
opengever/core/upgrades/20180131153203_drop_unused_sequences/upgrade.py

Disable "Drop unused sequences" upgrade step because it failed on TEST: We're disabling this upgrade step because it failed when deploying on TEST, indicating that at least the `subscriptions_resource_id_seq` sequence was still being used.
```
2018-02-19T18:35:04 ERROR ftw.upgrade FAILED
File "ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/jsonapi/plonesite.py", line 158, in _install_upgrades
executioner.install_upgrades_by_api_ids(*api_ids)
File "ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", line 57, in install_upgrades_by_api_ids
return self.install(data)
File "ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", line 43, in install
self._upgrade_profile(profileid, upgradeids)
File "ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", …
```

Disable "Drop unused sequences" upgrade step because it failed on TEST:

---

docs/HISTORY.txt
opengever/activity/__init__.py
opengever/activity/digest.py

Digest: Set request language based on site wide preferred language so that the i18n and l10n 
machinery down the line can pick it up automatically with as little manual guidance from us as
possible.
Fixes date formatting mentioned in https://basecamp.com/2768704/projects/12554551/todos/342457420

Digest: Set request language based on site wide preferred language

---

docs/HISTORY.txt

Didn't remove duplicates as that will leave 2017.7 releases empty. Not sure what to do in such cases 🤔 so i prefer the duplication.

Also add CL entries from the 2017.6 release.

---

docs/HISTORY.txt
opengever/meeting/browser/resources/meeting.js

The code seems to have been refactored so that renameAgendaItemDialog is now a function which wraps the overlay. The definition check needs to be moved closer to the overlay.
Fixes #4024.

Fix deleting agenda items for non-word agenda items.

---

docs/HISTORY.txt
opengever/activity/browser/views.py
opengever/base/browser/navigation.py
opengever/dossier/browser/navigation.py
opengever/meeting/browser/meetings/agendaitem_list.py
opengever/meeting/browser/toc.py
opengever/portlets/tree/favorites.py
opengever/workspace/participation/browser/manage_participants.py

Removes all uses of `response.enableHTTPCompression()` in `opengever/*` code.
This is because the ZPublisher implementation of gzipping responses is buggy (prone to **double compression**), and therefore shouldn't be used at all (HTTP compression should be done at the Apache / Nginx frontend level anyway, instead of at the application level).
---
ZPublisher's implementation is buggy because multiple calls to `HTTPResponse.setBody()` may lead to double compression. The only way double compression is usually prevented is because the [`newlen < startlen` condition in HTTPRequest.setBody() evaluates to `False`.](https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/HTTPResponse.py#L538-L568)
Gzipping data twice usually increases its size. Except when it doesn't, then ZPublisher …

Remove all uses of enableHTTPCompression in GEVER

---

opengever/dossier/archive.py
opengever/dossier/configure.zcml
opengever/dossier/move_items.py
opengever/mail/browser/configure.zcml
opengever/mail/browser/send_document.py
opengever/task/browser/assign.py
opengever/task/browser/complete.py
opengever/task/browser/configure.zcml
opengever/task/configure.zcml
opengever/task/task.py

`provideAdapter` should never be used on module level because:
1. it cannot be isolated in tests
2. it is not consistent: all other adapters are registered in ZCML.
Fixes #3928

Use ZCML instead of provideAdapter.

---

docs/HISTORY.txt
opengever/meeting/model/meeting.py

This makes checks for presence in `sablon` templates easier, as the variable can then be used in an `<<if>>` to check for presence.
With empty strings we currently have the problem that they are always considered truthy, see https://github.com/senny/sablon#conditionals. Thus we don't have an option to build an `<<if>>` in `sablon` that only evaluates to `true` for non-empty strings without either introducing new dependencies (like `activesupport`) or modifications to sablon itself. Fixing it in gever is easier.

Return `None` when no meeting date is available.

---

README.rst
opengever/base/tests/test_wizard_storage.py
opengever/core/testing.py
opengever/document/tests/test_indexers.py
opengever/dossier/tests/test_archiver.py
opengever/dossier/tests/test_participation.py
opengever/mail/tests/test_validators.py
opengever/meeting/tests/test_unit_proposalhistory.py
opengever/tabbedview/tests/test_containing_documents_tab.py
opengever/task/tests/test_unit_related_documents.py
opengever/task/tests/test_validators.py

Fixes #3876.
Unit tests (=tests without a layer) do not have isolation. So all global things registered in those tests, such as adapters, utilites, the site hook or other globals, are not isolated (!). We've had quite a lot of tests which blindly changed global things without any isolation.
I've cleaned it up a bit:
1. rename `ANNOTATION_LAYER` to `COMPONENT_UNIT_TESTING`: the layer can be used for all tests which test components (e.g. adapters, annotations) or rely on components beeing available.
2. let candidates I found use the `COMPONENT_UNIT_TESTING`.
@4teamwork/gever be advised: when writing unit tests, you must be 100% sure that your test and all things your tests use do not use any adapters or other components or will in the future. The unit test must not ever write to globals …

Cleanup component unit tests and mock tests and rename ANNOTATION_LAYER.

---

docs/HISTORY.txt
opengever/activity/tests/test_hooks.py
opengever/activity/tests/test_settings.py
opengever/core/upgrades/20180226163757_fix_notficationdefaults_badge_roles/upgrade.py

With d9b0adfe9cc693d732b60ff8e8bc96eaa9ec53ce the badge icon has been reworked to a separate channel, but the profilehook which adds the notification defaults on a new setuped GEVER, was not correctly reworked.
For already existing GEVER deployments the change contains an upgradestep which fixes the wrongly badge setting  of notification_defaults.
Closes #3981

Fix NotificationDefault hook.

---

opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po

In French translations:
* Correct a typo
* Change "appendices" in two more cases (generally replace by "pièces jointes", but in one case here simply by "documents additionnels" which made more sense in that context, as it is a confirmation of an action that was termed"Soumettre des documents additionnels")
resolves https://extranet.4teamwork.ch/support/edk/tracker-support-gever-edk/83
Other instances of this translation had been corrected in
https://github.com/4teamwork/opengever.core/pull/3811

Correct French translations

---

test-plone-4.3.x.cfg

Observations piled up enough to take a small diversion:
1) We can save time by explicitly resetting buildout parts to the relevant ones for the main build
2) We should use `test-command-no-coverage` to fully adhere to the intentions of our buildouts
3) We should run the builds with the debug flag for better user feedback (and recorded timing data)
4) We should explicitly set the parallelity to match the build weight config

Trivialities of `bin/mtest`

---

bin/mtest

I've made mtest more usable for local development. It now splits the tests across processes independent of preconfigured layer split lists and accepts --layer and -m arguments. It also now runs heaviest-by-classcount layer batches first.
For running on a single module, for example `bin/test -j3 -m opengever.document` is still faster, but when running on multiple modules, for example `bin/mtest -d -j3 -m opengever.core -m opengever.base -m opengever.repository -m opengever.dossier -m opengever.document -m opengever.mail` mtest ends up quicker. This has to do with mtest incurring layer setup costs when splitting within a layer and `bin/test` not splitting within a layer, but merely running layers in parallel.

Generalize mtest more

---

docs/HISTORY.txt
opengever/api/configure.zcml
opengever/api/move.py
opengever/api/tests/test_move.py

Customize `@move` endpoint and comment out delete permission checks.

Do not check for delete permission in `@move` endpoint

---

docs/HISTORY.txt
docs/public/dev-manual/api/config.rst
docs/public/dev-manual/api/docs_changelog.rst
docs/public/dev-manual/api/index.rst
opengever/api/config.py
opengever/api/configure.zcml
opengever/api/tests/test_config.py

Provides a new endpoint for querying configuration settings that may be needed in clients.
Currently it returns:
- maximum subdossier depth
- maximum repository depth
- activated and disabled features
Example Response:
```json
{
"@id": "http://localhost:8080/fd/@config",
"features": {
"activity": true,
"bumblebee": false,
"contacts": false,
"dossier_templates": true,
"meetings": true,
"officatwork": true,
"solr": true,
"workspace": false
},
"maximum_repository_depth": 3,
"maximum_subdossier_depth": 1
}
```

Add REST API endpoint for querying configuration settings

---

docs/HISTORY.txt
opengever/core/upgrades/20180226144641_add_missing_forwarding_added_notification_default/upgrade.py

With the commit 064ca0f8284c633bf0e7925f4d0125b9aa055604 the missing `forwarding-added` notification-default has been added retroactively, but the changed upgradestep was already installed on some installations, which leads now to an error on the notification-settings page (see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/4732) because of the missing entry for the kind `forwarding-added`.
This PR makes sure that the entry exists.
⚠️ Only merge after https://github.com/4teamwork/opengever.core/pull/4019 has been merged.

Make sure notification-default for the forwarding-added kind exists.

---

docs/HISTORY.txt
opengever/api/configure.zcml
opengever/api/document.py
opengever/api/dossier.py
opengever/api/tests/test_serializer.py
opengever/base/default_values.py
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/dossier/behaviors/dossier.py
opengever/dossier/browser/forms.py
opengever/dossier/widget.py

- Customize serializer for dossiers and documents to return the correct reference number.
- Make reference_number a read-only field to prevent setting it through the REST API.
Having the reference number as a field in the schema is highly questionable for me.
I'm keeping it in the edit form for now as removing it, is out of scope of this PR.
Having it in the schema seems to confuse people as various tests show that try to set/get the value of the reference number field.
Further the document schema doesn't contain the reference number field.

Fix restapi reference number

---

docs/HISTORY.txt
opengever/core/upgrades/20180306101228_fix_relation_catalog_references/upgrade.py

We have detected that in rare cases there seems to be a reference from one of the relation catalogs `BTrees` to a previously removed class. 
- the class was removed in https://github.com/4teamwork/opengever.core/pull/2949
- the relation catalog was cleaned up in https://github.com/4teamwork/opengever.core/pull/3165
However there was still a reference according to `gc. get_referrers` from one of the `BTrees` in the `ICatalog` relation catalog utility. This resulted in a `PicklingError` when attempting to create new relations anywhere in the system, see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/5485/. We have not found the reference though as neither keys nor values of the `BTree` contained the object. Also by investigating attributes of the `BTrees` and its `Buckets` no …

Detect and fix broken references to ICreatorAware in the relation catalog.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/agendaitems-noword.html
opengever/meeting/browser/meetings/templates/agendaitems-word.html
opengever/meeting/browser/meetings/templates/meeting-noword.pt
opengever/meeting/browser/meetings/templates/meeting-word.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

For actions on `AgendaItem` we now distinguish paragraphs, regular items and proposals.
Actions are named accordingly in the menus.
Clicking an action shows an overlay for confirmation. I made the text generic here but show the title of the item that will be deleted. If specific text (meaning either "Zwischentitel" or "Traktandum") is needed, I can make a new overlay instead.
**Action menu for paragraph**
**Action menu for agenda item**
**Overlay for confirming item removal**
resolves #4016

Change action names for meeting agenda items

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_agendaitem.py

Listing is now alphabetical:
**now**
**before**
resolves #4028

Order agenda item attachements alphabetically

---

docs/HISTORY.txt
opengever/dossier/browser/overview.py
opengever/dossier/tests/test_overview.py

Sort the related dossiers alphabetically in the dossier overview.
**now**
**before**
resolves #3825

Sort related dossiers alphabetically

---

docs/HISTORY.txt
opengever/sharing/browser/sharing.pt
opengever/sharing/browser/sharing.py
opengever/sharing/browser/sharing_tab.pt
opengever/sharing/tests/test_sharing_integration.py

Make sure to URL encode links to the `list_groupmember` view in **sharing views**:
This ensures members for groups with **spaces in their ID** can also be listed in the overlay. This is a follow up to PR #3961 which fixed this issue for the user details view, but not the sharing pages.

Make sure to URL encode links to the list_groupmember view in sharing views:

---

docs/HISTORY.txt
opengever/dossier/handlers.py
opengever/meeting/tests/test_proposal.py

Seems there was already something similar in place for tasks.
Closes #3234

Always manually sync proposals for dossier reference number prefixes

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_helper.py

Closes https://github.com/4teamwork/opengever.core/issues/3908
⚠️ depends on https://github.com/4teamwork/plonetheme.teamraum/pull/619

Implement related document icon.

---

docs/HISTORY.txt
opengever/core/upgrades/20180306101228_fix_relation_catalog_references/upgrade.py

Disable this upgrade step until we figure out what exactly is going
on in issue #4074 - right now it seems that pickling a persistent
object (just to check whether it's in an ok state) might be a bad
idea and not be side-effect free.
Until we're sure this isn't harmful, we disable this upgrade step.
See #4074 for a more detailed explanation.

Temporarily disable upgrade step to fix broken references until we're sure it's safe

---

bin/mtest

We're having too many transient failures due to the mysterious potentially layer teardown related recursion depth issues.
https://ci.4teamwork.ch/builds/150747/tasks/238262

Disable flunking tests on an unclean stderr

---

base-plone-4.3.x.cfg
development.cfg
test-plone-4.3.x.cfg

This time without destroying `development.cfg`. A basically free ~40s CI job runtime gain.

Reorder buildouts to minimize CI test run buildout time

---

docs/HISTORY.txt
opengever/document/checkout/checkout.py
opengever/document/tests/test_checkout.py

Added a `reauth=1` querystrhing parametre to the checkout redirector to skip the checkout when used only for the reauth.
Closes https://github.com/4teamwork/opengever.core/issues/3941

Avoid checking out the document via the redirector on an OC reauth.

---

opengever/document/browser/actionbuttons.py
opengever/document/browser/templates/macros.pt
opengever/document/checkout/checkin.py
opengever/document/checkout/manager.py
opengever/document/tests/test_checkout.py
opengever/document/tests/test_force_checkin.py

- verify that both checkin views (with and without comment) remove the locks:
- yes, both actions call the `checkin` method of the `CheckinCheckoutManager`
- verify that this behavior is tested.
- Behavior is tested for checkin without comment
- Added a test to check that force checkin by another user 
- make sure that forcing checkin (checking in documents checked out by other users) is based on the `opengever.document: Force Checkin` permission
- There are two permissions that allow force checkin:
- `Force Checkin`
- `Manage portal`
- I also added a test that `Force Checkin` gives the permission. Note that with just this permission, the checkin will raise an `Unauthorized` probably because the user cannot save the file (the file gets checked in though and the lock cleared). So this is a …

Allow force checkin for users with `Manage portal` permissions

---

docs/HISTORY.txt
opengever/base/browser/gever_state.py
opengever/base/interfaces.py
opengever/base/tests/test_gever_state.py
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20180221144648_update_properties_action_available_expression/actions.xml
opengever/core/upgrades/20180221144648_update_properties_action_available_expression/upgrade.py
opengever/disposition/browser/configure.zcml
opengever/disposition/browser/overview.py
opengever/disposition/browser/resources/disposition.js
opengever/disposition/browser/templates/overview.pt
opengever/disposition/browser/views.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_overview.py
opengever/disposition/tests/test_views.py

The transfer_number is now shown on the disposition overview and directly editable for users, which has the `edit transfer number` permission.  The transfer_number update is made via a simple AJAX call on a specific endpoint. Closes #2811.
Additionally I've fixed also an issue with the `available-expression` on the properties action.
The added tests are still Functional tests, the conversion to integration is a bigger work and will follow in a separate PR.
with edit transfer number permission:
without permission:
Styling: https://github.com/4teamwork/plonetheme.teamraum/pull/617

Improve input position for the transfer number

---

opengever/document/checkout/checkin.py
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/tests/test_checkout.py

Buttons get defined on the class level, so conditionally changing the button label is not a good idea. Instead we now have 2 buttons that are displayed conditionally.
I also added the French translation of the button label.
**Before, once the label was changed to "checking anyway", it could remain in that state even if the document is not locked anymore**
**Now  we get the correct labels**
**And the french translation**
resolves https://extranet.4teamwork.ch/support/edk/tracker-support-gever-edk/102

Fix force checkin button

---

docs/HISTORY.txt
opengever/core/upgrades/20180319170439_cleanup_i_creator_leftovers/upgrade.py

Upgrade step to remove references to the `ICreatorAware` interface in the index.
This was tested locally by reverting the commits removing the interface, setting up a new gever with content and then reapplying the commits and corresponding upgrade steps. This upgrade step could then be applied and tested.
resolves #4048

Upgrade to cleanup leftovers from ICreatorAware

---

docs/HISTORY.txt
opengever/contact/browser/configure.zcml
opengever/contact/browser/contact_forms.py
opengever/contact/contactfolder.py
opengever/contact/tests/test_contact.py

`IContactSettings.is_feature_enabled` is enabled, one should not be able to add contacts.
* implement `allowedContentTypes` to only allow `contact` when the feature is disabled
* Make the add form unavailable when the feature is enabled.
**With the feature enabled, contact is not in the add menu anymore**
**Unauthorized is raised when directly accessing the add form**
**When the feature is disabled, contacts can be added**
resolves #4086

Only allow to add contacts when `IContactSettings.is_feature_enabled` is disabled

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/handlers.py
opengever/private/tests/test_workflows.py

This is to deal with the fact that Plone doesn't automatically update object security when an **object gets moved out of a location where a placeful workflow applies**.
This fixes users not having view permissions on documents that got moved out of the private area of a user.
I used `ftw.upgrade.helpers.update_security_for()` do the job of actually taking care of updating the object security as needed.
Therefore, questions for @jone 😉 :
- Is this a good idea? (is that function considered a part of the public API?)
- This function delegates to [`obj.reindexObjectSecurity()`](https://github.com/zopefoundation/Products.CMFCore/blob/2.2.10/Products/CMFCore/CMFCatalogAware.py#L93-L120), which is recursive. Do you see an issue with that (performace wise)? Currently, in the `private area`, users …

Update object security when moving objects

---

docs/HISTORY.txt
opengever/document/checkout/checkin.py
opengever/document/checkout/manager.py
opengever/document/tests/test_checkout.py
opengever/document/tests/test_force_checkin.py

* Do not check-in locked documents when the multi-checkin action is called. 
* Display a message for each document that could not be checked-in
* Addition of a `force` argument to methods of the checkin controller to make the use of force checkin more deliberate and clear.
Apart from the main bug fixed, another one was also fixed and tests improved:
* Correct a bug for checkin without comment. When doing a checkin without comment on a document that could not be checked-in, one would be redirected to the checkin with comment. This was intended for locked documents, but would also happen for documents that could not be checked in for other reasons (for example not checked out)
* Improved existing multi-checkin tests by better using the fixture (remove unnecessary document creation) …

Disallow checkin-anyway for multi-checkin action

---

README.rst
docs/HISTORY.txt
opengever/api/tests/test_serializer.py
opengever/api/tests/test_summary.py
opengever/base/browser/resources/TableRadioWidget.js
opengever/base/schema.py
opengever/base/templates/tableradio_input.pt
opengever/base/tests/test_contentlisting.py
opengever/base/tests/test_widget.py
opengever/base/tests/views/z3cforms.py
opengever/base/widgets.py
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/core/testing.py
opengever/document/tests/test_bumblebee.py
opengever/dossier/dossiertemplate/form.py
opengever/dossier/templatefolder/form.py
opengever/dossier/tests/__init__.py
opengever/dossier/tests/test_documents_tab.py
opengever/dossier/tests/test_dossier_template.py
opengever/dossier/tests/test_templatefolder.py
opengever/mail/tests/test_indexers.py
opengever/meeting/browser/proposalforms.py
opengever/meeting/tests/test_zipexport.py
opengever/private/tests/test_reference_number.py
opengever/repository/tests/test_repositoryfolder_tabs.py
opengever/tabbedview/tests/test_document_listing.py
opengever/testing/fixtures.py
opengever/testing/tests/test_fixtures.py

* Ported the template form tests to integration tests where sensible and currently possible
* Implemented a template-side JS filter field for `TableChoice`
* The JS filter is active for:
- Document templates
- Dossier templates
- Proposals
Theming PR: https://github.com/4teamwork/plonetheme.teamraum/pull/622
The filter is also visible for proposals and dossier-templates:
Closes https://github.com/4teamwork/opengever.core/issues/3189

JavaScript filter field for choosing templates

---

docs/HISTORY.txt
opengever/core/upgrades/20180328132504_fix_d_d_upload_for_template_folders/upgrade.py
opengever/dossier/templatefolder/interfaces.py
opengever/dossier/tests/test_templatefolder.py

This PR fixes an issue where the upload box would not be rendered for template folders. 
The template folder did no longer provide the `ITabbedviewUploadable` interface, which is required (also for containers that is uploaded into).
In https://github.com/4teamwork/opengever.core/pull/3081 the inheritance of template folders has changed. I suspect that this removed the upload functionality.
Fixes #4114.

Fix displaying quickupload uploadbox for template folders.

---

docs/HISTORY.txt
docs/public/user-manual/dokumente/anschauen.rst
docs/public/user-manual/dokumente/bearbeiten.rst
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/tabbedview/helper.py
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview-manual.pot
opengever/tabbedview/locales/opengever.tabbedview.pot

* Couldn't find where the label  from `opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po` is used.
* Should we update the screenshots in the docs for that?
resolves #4051

Change checkout and edit button label

---

docs/HISTORY.txt
opengever/api/tests/test_content_creation.py
opengever/bumblebee/document.py

The event handler in `opengever.bumblebee` that does so on `ObjectModified` events
relies on `doc.digitally_available` being up-to-date. This was not the case because both event handlers are registered for the same event type, and we can't control the order in which these event handlers are executed.
We therefore must make sure to update `doc.digitally_available` before checking against it.

Make sure bumblebee checksum gets calculated for docs created via REST API

---

docs/HISTORY.txt
opengever/base/browser/resources/logoutClient.js
opengever/base/browser/resources/logoutWorker.js

Reload the page with the actual URL instead of a simple location reload.
This should trigger the reload with the correct URL eg. portal logout
URL.
Backport needed: `2018.2-stable`

Fix logout worker when using SSO

---

docs/HISTORY.txt
opengever/meeting/browser/resources/datetimepicker.js

With the new ftw.datepicker version 1.3.0 the xdsoft widget has been
updated (see https://github.com/4teamwork/ftw.datepicker/pull/16) and
now the API has been changed which lead in to JS failures when adding a new meeting. Closes #4143 
Backport Needed: `2018.2-stable`

Fix datetime picker when adding a new meeting.

---

docs/HISTORY.txt
setup.py

after bugfix release 2018.2.1 has been released via `2018.2-stable` branch.

Cleanup history and bump version for next release to 2018.3.0

---

docs/HISTORY.txt
docs/public/dev-manual/api/favorite.rst
docs/public/dev-manual/api/index.rst
opengever/api/configure.zcml
opengever/api/favorites.py
opengever/api/repository_favorites.py
opengever/api/tests/test_favorites.py
opengever/api/tests/test_repository_favorites.py
opengever/base/favorite.py
opengever/base/model/favorite.py

Based on #4128 .
This PR adds the favorite API endpoints which are used for the new favorite-feature  (OGIP 32):
- @favorites (GET, POST, PATCH and DELETE)
- @repository-favorites (GET)
For further information see documentation https://github.com/4teamwork/opengever.core/blob/6636677a4dbe0b5b5ab09f737fae4ce97f2fe05b/docs/public/dev-manual/api/favorite.rst
**Permission and protection:**
- the GET service requires`zope2.View` all other services requires the `setOwnProperties` permission.
- All services are protected with an additional check `userid == api.user.get_current()`, which avoid that a user can manipulate favorites of an other user.

Favorites API endpoints

---

docs/HISTORY.txt
opengever/base/browser/resolveoguid.py
opengever/base/tests/test_resolve_oguid.py

The view supports now traversal based oguids and other views.
GET paramater: `/fd/resolve_oguid?fd:123`
Traversal based paramater: `/fd/resolve_oguid/fd:123`
Specific view: `/fd/resolve_oguid/fd:123/tooltip`
Closes #4101

Enhance resolve_oguid view, to support other views.

---

opengever/base/configure.zcml
opengever/base/handlers.py
opengever/base/tests/test_favorite.py

- Remove favorites when an objects gets trashed or deleted.
- Update favorite title when the object title gets changed, unless the title is personalized.
Closes #4109

Update favorites when content changes

---

docs/HISTORY.txt
opengever/activity/mailer.py
opengever/activity/templates/notification.pt
opengever/activity/tests/test_mail.py
opengever/testing/integration_test_case.py

* Breaks the activity details out per paragraphs on notify mails with multi line details
As far as I can tell these are not printed on digests.
Closes https://github.com/4teamwork/opengever.core/issues/3365

 Break activity details out per paragraph

---

opengever/policytemplates/policy_template/opengever.+package.name+/versions.cfg.bob

Extends in our policy templates should include `versions.cfg` from a tag on github instead of the no longer used KGS url.
_CL entry not necessary i'd say._

Update extends in policy templates.

---

opengever/policytemplates/policy_template/opengever.+package.name+/setup.py.bob

Otherwise policies won't include necessary test dependency and thus tests will fail for new generated policies.
_CL entry not necessary i'd say._

Add opengever.core[tests] to tests_requires.

---

docs/HISTORY.txt
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

I gave up writing the tests as integration test cases. I anyway had to build new dossiers and documents, as the `self.dossier` from the `fixture` cannot be resolved (there are documents in it and it contains subdocuments, moreover we would first have to set proper states for all the tasks and such).
resolves #4138

Delete shadowed documents when resolving a dossier

---

docs/HISTORY.txt
opengever/contact/permissions.zcml
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20180417143819_create_new_team_add_and_edit_permissions/rolemap.xml
opengever/core/upgrades/20180417143819_create_new_team_add_and_edit_permissions/upgrade.py
opengever/ogds/base/browser/configure.zcml
opengever/ogds/base/browser/teamdetails.py
opengever/ogds/base/tests/test_team_forms.py

* Defined new roles
* Amended rolemap + added a migration for it
* Amended view registrations
* Amended team details view logic on edit link visibility
* Amended tests
* Ignored in lawgiver as teams are site-global
Closes #4054

Grant team add and edit permissions to site admins

---

docs/HISTORY.txt
opengever/dossier/profiles/filing/types/opengever.dossier.businesscasedossier.xml

Currently the translation for "Businesscase Dossier" in the factory menu is broken after installing the filing profile, because the i18n domain has changed since the profile-merge.

Fix i18n domain in the types xml of the filing profile.

---

docs/HISTORY.txt
opengever/ogds/base/sync/ldap_util.py
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/ldaphelpers.py

Starting with 2.4.21, `python-ldap` now doesn't raise `ldap.NO_SUCH_OBJECT` anymore if case of empty search results, but instead returns an empty list.
See https://github.com/python-ldap/python-ldap/blob/28f5251fd534fd50d333b522c857a2b0aaa56787/CHANGES#L543-L544

OGDS sync: Fix handling of missing user after updating python-ldap:

---

docs/HISTORY.txt
opengever/base/browser/jsvariables.py
opengever/base/tests/test_jsvariables.py
opengever/bumblebee/__init__.py
opengever/bumblebee/browser/resources/bumblebee.js
opengever/bumblebee/interfaces.py
opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/registry.xml
opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/upgrade.py
opengever/examplecontent/profiles/default/registry.xml
opengever/testing/integration_test_case.py

Add a feature-flag to enable/disable bumblebee auto-refresh. This allows us to avoid 404s in the browser console when the backend's `notifications` endpoint is not available.

Add bumblebee auto-refresh feature flag.

---

docs/HISTORY.txt
opengever/base/browser/search.py
opengever/base/tests/test_search.py

ftw.solr expects an exact match when filtering on 'path' index, so we have to use `path_parent` for the "search only in this are"- use case.
The livesearch is already handling this, no change needed (see
https://github.com/4teamwork/opengever.core/blob/master/opengever/base/browser/livesearch.py#L59).
Closes #4069.

Fix path filterd Solr searches.

---

docs/HISTORY.txt
opengever/api/config.py
opengever/api/tests/test_config.py
opengever/base/browser/configure.zcml
opengever/base/browser/jsvariables.py
opengever/base/browser/search.pt
opengever/base/tests/test_jsvariables.py
opengever/bumblebee/__init__.py
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/preview_listing.py
opengever/bumblebee/browser/resources/bumblebee-cable.js
opengever/bumblebee/browser/resources/bumblebee.js
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/browser/templates/previews.pt
opengever/bumblebee/interfaces.py
opengever/bumblebee/tests/test_preview_listing.py
opengever/core/profiles/default/jsregistry.xml
opengever/core/tests/test_view_security.py
opengever/core/upgrades/20180202111739_register_bumblebee_cable_js/jsregistry.xml
opengever/core/upgrades/20180202111739_register_bumblebee_cable_js/upgrade.py
opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/registry.xml
opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/upgrade.py
opengever/document/browser/overview.py
opengever/document/browser/templates/overview.pt
opengever/document/widgets/tooltip.pt
opengever/document/widgets/tooltip.py
opengever/examplecontent/profiles/default/registry.xml
opengever/testing/integration_test_case.py

See https://github.com/4teamwork/opengever.core/issues/4052
As bumblebee has the capability to send a notification to a client
using WebSockets when a document has finished, we can now profit from
that, embedding the client library [bumblebee-cable.js](https://github.com/4teamwork/bumblebee-cable.js).
When a user accesses a GEVER page, he'll first get the thumbnail. If bumblebee finished converting the document, the preview container (either image or iframe) will automatically refresh.
This feature has **low** impact, when the webserver of GEVER, or the webserver of Bumblebee is not able to handle WebSocket requests, this won't raise any error in the javascript part. 
The initial loading of the images is not changed. It's still an `img` or `iframe` tag. The reloading is done through …

Implement bumblebee's auto refresh functionality

---

docs/HISTORY.txt
opengever/core/upgrade.py
opengever/core/upgrades/20180424145246_fix_date_for_transported_objects/upgrade.py

Adds an upgradestep which fixes dates for transported objects (closes #4156). See #4155 for more information.
The upgradestep is skipped on a single admin_unit deployment, because the transporter is only used in multi admin_unit communication and potentially long running.

Fix dates for transported objects.

---

docs/HISTORY.txt
opengever/base/tests/test_favorite_action.py
opengever/base/viewlets/favorite_action.py

The self.published value, first parameter of an etag adapter, differs between a
webdav requests than a regular request. On a webdav request self.published is directly the context itself, therefore we have to handle it separately:

Fix favorite etag adapter for webdav requests.

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_helper.py

Currently the helper failed with an `AttributeError: get_css_class` when passing in a task objects. So adding a favorite for a task was not possible.

Fix get_css_class helper for task objects.

---

docs/HISTORY.txt
opengever/core/profiles/default/actions.xml
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20180403175143_add_confirmation_to_cancel_checkout/actions.xml
opengever/core/upgrades/20180403175143_add_confirmation_to_cancel_checkout/jsregistry.xml
opengever/core/upgrades/20180403175143_add_confirmation_to_cancel_checkout/upgrade.py
opengever/document/browser/actionbuttons.py
opengever/document/browser/templates/macros.pt
opengever/document/checkout/cancel.py
opengever/document/checkout/configure.zcml
opengever/document/checkout/templates/cancelconfirmation.pt
opengever/document/checkout/templates/cancelconfirmationform.pt
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/static/cancel_checkout_confirmation.js
opengever/document/tests/test_cancel.py

Request a confirmation to cancel the checkout of a document.
When cancelling the checkout of a single document from the document actions, a popup window asks for confirmation. When using the table actions from the `TabbedView`, the confirmation is handled by a form (see snapshots below).
I also checked that it still works for `proposaltemplate`.
**pop up for cancelling checkout of a single document**
**form for cancelling checkout of multiple documents. The form lists the files that were selected for checkout cancel**
**Messages after cancelling checkout, here of three documents, with one of them that wasn't checked out, so the cancel failed for that one**
resolves #4119

Request confirmation before cancelling a document checkout

---

opengever/meeting/browser/sablontemplate.py

The `html:*` fields only make sense when the word meeting feature is disabled, otherwise the fields have been replaced by the word-file and are no longer available.
_This is currently important as we're about to create many new templates. Merge ASAP for a process speedup. 💛!_

Respect feature flag when filling sample data.

---

docs/HISTORY.txt
docs/public/admin-manual/meeting/debugging.rst
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_meeting_debug.py

I needed this to debug an issue for a customer. It puts the filled out header and suffix sablon templates to generate an excerpt into a zip, together with the document containing the proposal.
So `+quick tests` `+quick documentation` `=` benefit for the near future.

Add debug view for docxcompose agenda items.

---

docs/HISTORY.txt
opengever/inbox/browser/configure.zcml
opengever/inbox/browser/tabs.py
opengever/inbox/tests/test_inbox_bumblebee_gallery.py

When documents are redirected, they're stored in a subdossier. If the
depth is not set, the bumblebee gallery will display all objects of
subdossiers.
To prevent displaying redirected inbox documents, the depth is set to 1.
Resolves #4191

Fix bumblebee inbox documents gallery preview

---

docs/HISTORY.txt
opengever/oneoffixx/browser/configure.zcml
opengever/oneoffixx/browser/connect_xml.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt
opengever/oneoffixx/tests/test_connect_xml.py

* `TemplateId` and `LanguageLcid` elements are only added to the XML if they are present in the annotation. That's what I understood @buchi wanted? If you'd rather have a different behaviour, maybe empty tags or simply no XML at all when this information is missing, let me know.
* A template can be available in different languages, so the in the template metadata, that field is a list. In the XML there can be only one. Current choice is `2055`, i.e. *German Switzerland* if that language is in the list, otherwise the first language from the list.
Here is an example of xml generated by the view:
```
<oneoffixxconnectbatch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.oneoffixx.com/OneOffixxConnectBatch/1">
<settings>
<add key="KeepConnector">true</add>
<add …
```

Add view returning oneoffixx xml

---

README.rst
docs/HISTORY.txt
opengever/base/contentlisting.py
opengever/base/overrides.zcml
opengever/dossier/tests/test_templatefolder.py
opengever/private/tests/test_deactivate_action.py
opengever/private/tests/test_delete_action.py
opengever/private/tests/test_dossier.py
opengever/private/tests/test_folder.py
opengever/private/tests/test_quota.py
opengever/private/tests/test_reference_number.py
opengever/private/tests/test_root.py
opengever/private/tests/test_viewlets_quotawarning.py
opengever/private/tests/test_workflows.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Currently API requests on a private dossiers raises an `TypeError: 'str' object is not callable`. Because of an incorrect handling in the `plone.app.contentlisting` the adapted IContentListing-object looses the acquisition context which leads then to problems when getting the owner on in the title accessor of a PrivateFolder.
I fixed the issue by overriding the `RealContentListingObject` adapter. I'll add also an PR to the `plone.app.contentlisting` package, but that needs some more time and a general test-example. Closes #4166.
Besides that I've converted all opengever.private tests to integration tests. closes #3903 .

Fix API get request on private dossiers.

---

opengever/meeting/model/meeting.py

This reverts commit c2ff55c4e956595aacae75db617f231bb58362ee.
Accidently pushed a temp commit (tried to run the tests on CI) but with the new magit default you push to origin/master.
(Yes the 🐷 already got its 5 CHF)

Revert "tmp id add"

---

docs/HISTORY.txt
opengever/dossier/tests/test_templatefolder.py
opengever/examplecontent/profiles/default/registry.xml
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing_integration.py

With b1e2d59 a new configuration option `group_title_ldap_attribute` has been introduced, which sets the group title during the ogds syncrhonisation. We show now the title if exists in the Sharing view instead of only the id.
Because our LDAP stack does not support mapping additional attributes, we fetch the title information from ogds groups.
Closes #3864.

Show group title in the sharing view

---

docs/HISTORY.txt
opengever/base/handlers.py

This fixes the currently broken plonesite removal. Closes #4256

Skip plonesite removals in ObjectRemovedEvent handler

---

docs/HISTORY.txt
opengever/document/document.py
opengever/locking/tests/test_force_unlock.py
opengever/officeconnector/configure.zcml
opengever/officeconnector/helpers.py
opengever/officeconnector/service.py
opengever/officeconnector/testing.py
opengever/officeconnector/tests/test_api_dossier_checkout.py
opengever/officeconnector/tests/test_api_dossier_disabled.py
opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
opengever/officeconnector/tests/test_zopemaster.py

Add the service to create a JWT for the `oneoffixx` action for office connector.
resolves #4136

Add service to create OC JWT URLs

---

opengever/officeconnector/configure.zcml
opengever/officeconnector/helpers.py
opengever/officeconnector/service.py
opengever/officeconnector/testing.py
opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
opengever/oneoffixx/browser/form.py
opengever/oneoffixx/command.py

Add service to generate payload for the officeconnector oneoffixx action. The payload contains the necessary information to retrieve the connect XML (`connect-xml` key)
resolves #4137

Add service to generate payload for officeconnector oneoffixx action

---

docs/HISTORY.txt
opengever/api/tests/test_config.py
opengever/base/interfaces.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20180503150336_enable_favorites_feature_by_default/registry.xml
opengever/core/upgrades/20180503150336_enable_favorites_feature_by_default/upgrade.py

Feature soll bei allen Kunden standardmässig aktiviert sein.

Enable favorites feature by default.

---

opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po

For documents we used "Metadaten bearbeiten" to edit the metadata but "Eigenschaften" to view them. Clients proposed that we standardise the terms. Finally we only change the "Eigenschaften" to "Metadaten anzeigen". That makes it very clear for documents.
For other types, we still use "Bearbeiten" to edit the object, and now "metadaten anzeigen" to view the properties.
**Preview for a meetingdossier**
**Preview for a document**
resolves #4050

Change translation of properties

---

docs/HISTORY.txt
opengever/tabbedview/sqlsource.py
opengever/tabbedview/tests/test_sqlsource.py

In https://github.com/4teamwork/opengever.core/pull/3851 we introduced a check to only sort by columns that exist. This is too strict and filters out sorting by special sqlalchemy constructs, e.g. a `column_property`.
This PR loosens the checks and allows to sort by anything that comes out of the `sqlalchemy_sort_indexes` mapping.
Fixes #4195.

Fix sorting of memberships by fullname.

---

opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob

While removing the obsolete "opengever.portlets.tree.enable_favorites" registry entry, an "endif" was forgotten which broke the policy template.
https://github.com/4teamwork/opengever.core/commit/e99eb74aca16fd256fdcfa06ae0ccd9b2b4c3bfa#diff-29f5e91b71244d611e5d4131d17d94bb
Resolves #4273

Fix policy template

---

opengever/base/browser/resources/Favorites.js
opengever/portlets/tree/resources/tree.js

This PR fixes three issues:
1.
`withCache` will be always `true` if you set it explicitly to `false`.
```node
> false || true
true
```
2. Requesting a cached resource without a caching parameter will not set Caching-Headers (https://github.com/4teamwork/opengever.core/blob/master/opengever/api/repository_favorites.py#L31), means, if a browser is requesting the resource without a `cache_key` parameter, the request should never be cached. This works fine for all browsers instead IE11. It is caching this request anyway. Setting a timestamp as a cachekey for requests without caching will solve this issue.
Before:
After:
3. Adding sync from the tree-portelt to the context-title favorite-marker
Before:
After:

Favorites: Fixes issues in state-sycing

---

opengever/examplecontent/profiles/default/registry.xml

We don't want this enabled for dev by default (for now) as it results in console error messages when bumblebee is not running in dev (which is usually the case).
_As just discussed before lunch._

Don't enable auto refresh in example content.

---

docs/HISTORY.txt
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py
opengever/testing/builders/dx.py
opengever/testing/integration_test_case.py

Set the document date of journal pdfs to their to dossiers end-date, if the dossier has an end-date. This prevents the dossier from entering an invalid state with a document date outside the dossiers start-end range.
This also fixes the tests by calling the browser-view to resolve the dossier as that view recursively resolves the dossiers whereas just calling the transition will behave differently.
Also port `TestResolvingDossiers` and `TestResolveJobs` from functional to an integration test case.
Closes #4270.

Set document date of generated journal pdfs to dossier end-date.

---

README.rst

Directives need a newline to be reconized correctly.

Add missing newline before .. code:: directive.

---

docs/HISTORY.txt
opengever/disposition/disposition.py
opengever/disposition/tests/test_activities.py

Currently the archivist group members has been fetched via group's `getGroupMemberIds` but those does not respect nested groups and lead to incomplete dispositions watchers list.
The watchers list is not permission-critical, therefore the ogds is the right place to query the group members.

Fetch archivist group members from ogds.

---

docs/HISTORY.txt
opengever/base/browser/resources/favorites_app.js
opengever/base/browser/resources/favorites_menu_app.js

IE 11 ignores `Cache-Control` headers on AJAX GET calls, therefore we need to extend the fetch url with a timestamp parameter.
This solves different IE 11 issues with the new favorites feature.

Make sure IE 11 does not cache favorites fetch requets.

---

README.rst

Otherwise it will break in the near future when the next version is released. 
Assuming that https://github.com/4teamwork/ftw.solr/pull/118 will be merged soon.

Point download link to archive.apache.org.

---

docs/HISTORY.txt
opengever/task/activities.py
opengever/task/task.py
opengever/task/tests/test_activities.py

Refactoring the complete mail template, using the same default-template as the digest mail, will be handled in a separate PR.
Closes #4242

Show responsible and issuer to notification mail for TaskAdded activities.

---

docs/HISTORY.txt
opengever/dossier/templatefolder/configure.zcml
opengever/dossier/templatefolder/tabs.py
opengever/dossier/tests/test_templatefolder.py

The document listing of a templatefolder only shows documents directly inside the folder, but the gallery view showed recursive all documents.
Closes #4191

Fix content displayed in the templatefolder's gallery view.

---

docs/HISTORY.txt
opengever/meeting/command.py
opengever/meeting/committeecontainer.py
opengever/meeting/exceptions.py

This PR no longer requires the paragraph template for committees and their containers. It also removes the Exception that was raised in such a case.
It may not be required by customers, which is a valid state but uncommon. The system should not forbid it though as there is no reason to do so.

No longer require paragraph template.

---

docs/HISTORY.txt
opengever/activity/mailer.py
opengever/activity/tests/test_mail.py

The with #4152 introduced "splitlines" could not handle empty activity descriptions.
Closes #4307

Fix NotificationMailer for TaskReassigned activities.

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_helper.py

This introduces a new CSS class to mark documents that are checked out by the **current user**:
| State | Example CSS Classes |
| --- | --- |
| Not checked out | `icon-docx` |
| Checked out by current user | `icon-docx is-checked-out-by-current-user` |
| Checked out by someone else | `icon-docx is-checked-out` |
This depends on 4teamwork/plonetheme.teamraum#635 for styling.

Distinguish icons for docs checked out by current user vs. someone else.

---

docs/HISTORY.txt
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/base/skins/opengever.base_scripts/insufficient_privileges.pt

Closes #4305 
Use neutral of `Fachapplikationsverantwortlichen` on all error pages.

Customize insufficient privileges error page.

---

docs/HISTORY.txt
opengever/core/upgrades/20180517160709_change_physical_path_column_type/upgrade.py
opengever/globalindex/model/task.py
opengever/meeting/model/committee.py
opengever/meeting/model/proposal.py

This PR fixes issue where the physical_path value could be too long. I'm fixing it for all the `physical_paths` we store in the relational database.
After a brief discussion with @Rotonen and @lukasgraf we decided against adding an index for now.
_The `existing_...` params would not be necessary for postgres but i find they are helping in documenting what we're doing._
Fixes #4235.
Needs backport to: `2018.1-stable` and `2018.2-stable`

Fix too long physical_path value issue.

---

docs/HISTORY.txt

#4318 has been backported to 2018.1 and 2018.2.

Update changelog after hotfix releases via stable branches.

---

docs/HISTORY.txt
opengever/core/upgrades/20180427103952_migrate_favorites/upgrade.py

Repositoryfolder can be removed by administrators or managers.

Fix favorites-migration: skip no longer existing repo-favorites.

---

docs/intern/kurzreferenzen/feedbackforum-prozess.rst
docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
docs/public/dev-manual/api/schemas/opengever.document.document.inc
docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
docs/public/user-manual/dokumente/metadatenpflegen.rst
docs/public/user-manual/dossiers/dossiervorlagen.rst
docs/public/user-manual/dossiers/eroeffnen.rst
docs/schema-dumps/ftw.mail.mail.schema.json
docs/schema-dumps/opengever.document.document.schema.json
docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
opengever/bundle/schemas/documents.schema.json
opengever/bundle/schemas/dossiers.schema.json
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po

Here's the search for the "worte" string:
Here's the search for the "worte" string in the docs:
As you can see, there's no further occurrence of "Schlagworte".
Resolves #3830

Rename "Schlagworte" zu "Schlagwörter"

---

docs/HISTORY.txt
opengever/base/redirector.py

See https://github.com/4teamwork/opengever.core/issues/4147
The `reload` event is fired after the tabbedview has been loaded. So open the oc url after this event happened.

Fix stuck tabbedview spinner on firefox

---

docs/HISTORY.txt
opengever/api/scanin.py
opengever/api/tests/test_scanin.py

* Move error returns to destination discovery
* Duck type the destination for error handling
* Use a fall-through default 404 on the destination discovery
Closes #4202

Improve error handling on the @scan-in API endpoint

---

docs/HISTORY.txt
opengever/contact/browser/organization_listing.py
opengever/contact/browser/person_listing.py
opengever/contact/tests/test_organization_listing.py
opengever/meeting/browser/committeecontainertabs.py

The filter now correctly display "Alle" instead of "all":
Resolves #4342

Fix the label for the translation

---

docs/HISTORY.txt
opengever/core/upgrades/20180524145042_reset_task_templates_listing_cache/upgrade.py
opengever/tasktemplates/browser/tasktemplates.py
opengever/tasktemplates/browser/trigger.py
opengever/tasktemplates/tests/test_trigger.py
opengever/tasktemplates/vocabularies.py

We allow ordering of `TaskTemplate` in `TaskTemplateFolder` in a `TaskTemplateFolder` with a drag and drop column in the `TaskTemplates` listing view.
This order is then used for selection of tasks in the `add-tasktemplate` action, and selected actions are created in the same order they appear in the `TaskTemplateFolder`.
**Task template with tasks ordered test2; test3; test1**
**Task selection step, same order**
**Responsible selection step**
**Tasks created in the order given in the template. Can be ordered by *Laufnummer* to retrieve that order**
**Subtasks in the main task are also ordered as in the template**
resolves #4171

Make `TaskTemplate` sortable.

---

docs/HISTORY.txt
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/task/locales/de/LC_MESSAGES/opengever.task.po

My impression is that in french it should still be ok with "annulé", though maybe I just don't understand the difference in German well enough to propose something better in French...

Rename task state cancelled in German from storniert to abgebrochen

---

docs/HISTORY.txt
opengever/inbox/tests/test_transition_actions.py
opengever/task/configure.zcml
opengever/task/handlers.py
opengever/task/tests/test_transition_actions.py

* Ported some task transition action tests to integration tests where trivial
* Reset task responsible to issuer upon task rejection
* Also remove the activity subscription of the previous responsible
Closes #4177

OGIP 26: Reset responsible to issuer on task rejection

---

docs/HISTORY.txt
opengever/document/base.py
opengever/document/tests/test_document.py

As the mimetype registry is a persistent mapping of persistent mappings, I brought the logic into `document/base.py` where I recurse into a second round of case insensitive checking on dict-comprehension-lowercased mappings if we've had a miss on the normal lookup.
Testing the insensitivity both ways.
Closes #4281

Make document mimetype lookups case insensitive

---

docs/HISTORY.txt
opengever/trash/locales/de/LC_MESSAGES/opengever.trash.po
opengever/trash/locales/fr/LC_MESSAGES/opengever.trash.po
opengever/trash/locales/opengever.trash.pot
opengever/trash/remover.py
opengever/trash/tests/test_remove_conditions.py
opengever/trash/tests/test_trash.py
opengever/trash/trash.py

`removed` documents could be reactivated (untrashed), leading to documents that are in the state `document-state-removed` but not in the trash.
Moreover, `removed` documents could be removed again, leading to an error.
We now test whether a document is in the state `document-state-removed` before removing it, otherwise raising an error message:
Reactivation of documents in the state `document-state-removed` is now forbidding, also raising an error message.
resolves #4233

Do not allow reactivation of deleted document

---

opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

Assuming:
```
- Dossier
|
+- Subdossier
|  |
|  +- Subsubdossier
|  |  |
|  |  +- Document''
|  |
|  +- Document'
|
+- Document
```
If a user tries to resolve `Subdossier`, an error will occurr, since a
Subsubdossier is available and `Document'` is not supplied.
This change fixes the issue.
Resolves #4260

Fix resolving subdossiers if parent has documents

---

docs/HISTORY.txt
opengever/contact/tests/test_contactfolder.py
opengever/core/profiles/default/types/opengever.contact.contactfolder.xml
opengever/core/upgrades/20180531144505_amend_team_add_action_permission/types/opengever.contact.contactfolder.xml
opengever/core/upgrades/20180531144505_amend_team_add_action_permission/upgrade.py

@phgross 
There is also a backport branch based on top of the 2018.3.1 tag:
https://github.com/4teamwork/opengever.core/tree/jo-4054-2018.3.2-backport
Closes #4054

Team add portal action permissions: Administrators to add

---

docs/HISTORY.txt
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_template.py
opengever/meeting/tests/test_proposalhistory.py

Once figured out, a simple content source portal type whitelist amendment did the trick.

 Allow attaching documents of sibling proposals to proposals

---

docs/HISTORY.txt
docs/public/admin-manual/meeting/mergefields.rst
opengever/meeting/protocol.py
opengever/meeting/tests/test_protocol_json_data.py

In order to display the protocol generation data, the date needs to be passed inside the data.
This adds a formatted `today`.
Resolves #4216

Add today in the right format to the sablon data

---

docs/HISTORY.txt
opengever/document/behaviors/metadata.py

> Will man ein Platzhalter Dokument in einem Dossier ablegen, um z.B. ein Dokument aus einem anderen Dossier zu referenzieren, so muss die Option in Papierform aufbewahrt angewählt werden, dies ist im Falle eines Platzhalter-Objekt falsch. Die Validierung des Feldes in Papierform aufbewahrt müsste so angepasst werden, das nicht nur das Feld Datei sondern auch die verwandten Dokumente überprüft werden.
The changes from line 117 to 121 are due to the qa-test: See https://ci.4teamwork.ch/builds/166324/tasks/263812
Resolves #4371

Implement new validation of preserved as paper

---

opengever/core/testing.py

This is to aid with debugging failing / flaky tests that only leave a `"error while rendering <viewletname>"` behind in the markup as their only piece of evidence.
Like [this one](https://ci.4teamwork.ch/builds/166128/tasks/263455) for example:
```
ftw.testbrowser dump: /tmp/ftw.testbrowser-MwIM1J.html
Error in test test_prefill_from_advanced_search_omits_searchable_text_keywords (opengever.base.tests.test_search.TestOpengeverSearch)
NoElementFound: Empty result set: <ftw.browser.core.Browser instance>.css('#searchGadget') did not match any nodes.
```
Even if you manage to get your hands on `/tmp/ftw.testbrowser-MwIM1J.html`, all it contains regarding this failure is `error while rendering plone.searchbox`.
`plone.app.viewletmanager` would actually [log a helpful, detailed …

Tests: Whitelist ERROR level messages from plone.app.viewletmanager:

---

docs/HISTORY.txt
plonetheme/teamraum/resources/css/main.css

Previously:
With the right z-index (>200):
Resolves: #4357

Display flyup menues over selected list items

---

docs/HISTORY.txt
opengever/base/source.py
opengever/dossier/tests/test_move_items.py

The reference widget does sort its entries by the plone standard: `getObjectPositionInParent`
This can be overriden by defining a `navigation_tree_query['sort_on']`. 
The new index is 'searchable_title' (if a `navigation_tree_query` is provided but no `sort_on` key-value is present)
Before:
After:
Resolves #4286

Sort entries of the reference widget

---

docs/HISTORY.txt
opengever/meeting/browser/documents/proposalstab.py
opengever/meeting/tests/test_proposal_listings.py

The `translated_state` could not handle state translations containing
umlauts (see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/7224/ for more information).
@bierik @deiferni not sure which one of you need to fill the 🐷

Fix unicode error on proposal listings

---

.ci_governor.yml
bin/mtest
opengever/bundle/report.py
opengever/document/tests/test_document.py
opengever/ech0147/tests/test_export.py
opengever/ech0147/tests/test_import.py
test-plone-4.3.x-functional.cfg
test-plone-4.3.x-integration.cfg
test-plone-4.3.x.cfg

I've been slowly fiddling with parallelising the buildout.coredev CI builds and this process has led into some usability improvements for mtest. I've now backported some of these and also gone and fiddled a bit with the layer split and execution order stuff, as the power-of-two zipper-unweaving techniques from buildout.coredev does not work well for opengever.core.
* STDERR gets printed as a FYI, but will not get logged as an error or trip the build up
* Cleaned up STDERR as the two current things were deprecation warning related trivialities
* Nonzero returns will get logged as errors and trip the build up
* Improved printing logic - the debug mode is not necessary anymore
* Splitting strategies are now based on actual test class assertion counts
* Reintroduced split mapping - …

Backport usability changes of mtest from buildout.coredev

---

opengever/core/testing.py
test-plone-4.3.x-functional.cfg
test-plone-4.3.x.cfg

Renaming the layer was simpler than I anticipated.
This way we do not need to manually muck around with the layers every time something is killed or added - only if something is provenly too slow (or now quick enough).

Rename the zserver test layer so we can have a catch-all job

---

docs/HISTORY.txt
opengever/globalindex/model/query.py
opengever/task/browser/transitioncontroller.py
opengever/task/tests/test_task_checker.py

1. Anton created a successor task for Berta
2. Anton delegated the task to Carlos
```
FD                   RK
1.
Task (Anton) +-----> Successor Task (Berta)
+
| 2.
| 
v
Delegated Task (Carlos)
```
When Berta tries to resolve the task, the status of the subtask delegated to Carlos should be checked as well.
Therefore the check on Berta's side should get all the subtasks from
Berta's and Anton's task.
Resolves #4230 
Closes #4351

Fix resolving tasks if original task was delegated

---

docs/HISTORY.txt
opengever/document/vdexvocabs/document_types.vdex
opengever/dossier/vdexvocabs/container_types.vdex
opengever/dossier/vdexvocabs/participation_roles.vdex
opengever/dossier/vdexvocabs/type_prefixes.vdex
opengever/journal/vdexvocabs/manual_journal_entry_categories.vdex
opengever/task/vdexvocabs/bidirectional_by_reference.vdex
opengever/task/vdexvocabs/unidirectional_by_reference.vdex
opengever/task/vdexvocabs/unidirectional_by_value.vdex

PHVS waren die ersten Kunden, bei denen die GEVER auf Französisch umgesetzt wurde, dann wurde `fr` gewählt:
https://github.com/4teamwork/opengever.phvs/blob/061cd37332c56a88f301b20a00e03a24835cbd72/opengever/phvs/profiles/default/portal_languages.xml#L4
Generell wird aber `fr-ch` verwendet (z.b. demo):
https://github.com/4teamwork/opengever.demo/blob/7678109ab712861d73b42d2ac2a29b3eae1aed37/opengever/demo/profiles/default/portal_languages.xml#L5
Daher die doppelten Einträge (analog de, de-ch)
See also #4403

Duplicate fr translations to fr-ch in vdex files

---

docs/HISTORY.txt
opengever/repository/configure.zcml
opengever/repository/indexers.py
opengever/repository/tests/test_indexer.py

Deeply nested repository folder titles are bloated with padded zeroes.
```
(Pdb) self.context.Title
'1.1.1.5.1.1. Dienstzweig Abfallbewirtschaftung und Deponie (AD)'
from Products.CMFPlone.CatalogTool import sortable_title
(Pdb) sortable_title(self.context)()
'0001.0001.0001.0005.0001.00...ponie (ad)'
```
By registering a custom index for the repository folder, we can determine how the length of the sortable title varies.
The default `sortable_title` is barely reusable:
https://github.com/plone/Products.CMFPlone/blob/2df112f3a281f2799da4e37cc169809940db8a2f/Products/CMFPlone/CatalogTool.py#L183-L203
therefore a custom filter was implemented using the same logic.
Resolves #4398

Add sortable_title indexer for repository folders

---

docs/HISTORY.txt
opengever/base/default_values.py
opengever/base/tests/test_default_values_for_types.py

The `get_persisted_value_for_field()` helper function previously wasn't able to fetch persisted values for fields that were implemented as properties. This change adds support for also correctly looking up those values.
If we're dealing with attribute storage and a field's value can't be found in the instance dict, we need to check for a property in the class dict as a last resort before raising an `AttributeError`.

Add support for properties to get_persisted_value_for_field() helper

---

opengever/meeting/tests/test_unscheduled_proposals.py

Port test case from functional to integration tests.
Part of https://github.com/4teamwork/opengever.core/issues/4399.
_Follow up of https://github.com/4teamwork/opengever.core/pull/4397. No separate CL entry necessary IMO._

Port unscheduled_proposals tests to integration.

---

opengever/examplecontent/meeting.py

The five meeting dossiers in our example content didn't have a value for the required `responsible` field yet.
This flared up when checking the [script to check for non-persisted fields](https://github.com/4teamwork/opengever.maintenance/pull/134) against a recent local development instance.
*(No changelog because it's an internal change only)*

Examplecontent: Make sure meeting dossiers have a responsible.

---

opengever/meeting/tests/test_committee_container.py
opengever/meeting/tests/test_committee_container_tabs.py
opengever/meeting/tests/test_committee_container_word.py

Update naming, drop duplicated tests and split nicely into files as appropriate.
Part of https://github.com/4teamwork/opengever.core/issues/4399.
_Follow up of https://github.com/4teamwork/opengever.core/pull/4397. No separate CL entry necessary IMO._

Refactor committee container tests.

---

opengever/core/profiles/default/jsregistry.xml

This PR adds a missing file to the js registry.
The JS file is responsible to make various dropdowns searchable, for example when adding proposals: 
With its absence no JS errors are causes, but usability of the affected forms suffers.
In https://github.com/4teamwork/opengever.core/pull/4397 i have extracted some functionality into its own javascript file and added that file in an upgrade-step in https://github.com/4teamwork/opengever.core/pull/4397/files#diff-733441fdefe984bffebb71c8be1b9ef5R43. Unfortunately the file was not added to the default profile's `jsregistry.xml`. Sorry about that 🙈.

Add missing proposal.js that was only added in upgrade.

---

opengever/meeting/tests/test_agendaitem_list.py

Somehow `document.generated` date made its way back into the dict. Instead of omitting it we could also just freeze the date while generating the list.

Freezing the date might be a good idea.

---

docs/HISTORY.txt
opengever/base/reporter.py
opengever/base/tests/test_reporter.py
opengever/core/profiles/default/types/opengever.repository.repositoryroot.xml
opengever/core/upgrades/20180604222451_add_excel_export_action_to_repository_roots_for_administrators/types/opengever.repository.repositoryroot.xml
opengever/core/upgrades/20180604222451_add_excel_export_action_to_repository_roots_for_administrators/upgrade.py
opengever/repository/browser/configure.zcml
opengever/repository/browser/excel_export.py
opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/opengever.repository.pot
opengever/repository/mixin.py
opengever/repository/repositoryfolder.py
opengever/repository/repositoryroot.py
opengever/repository/tests/test_excel_export.py

* Can reimport the exported output
* Adds an action on the repository root
* Extends necessary missing functionality to the excel reporter
Closes #4221

Export repository roots as reimportable excel files

---

docs/HISTORY.txt
opengever/base/default_values.py
opengever/base/monkey/patches/default_values.py
opengever/base/tests/test_default_values_for_types.py

Ensure default values get set by patching DX [`DefaultAddForm.create()`](https://github.com/plone/plone.dexterity/blob/2.2.8/plone/dexterity/browser/add.py#L47-L70):
Object construction in DX `DefaultAddForm.create()` previously wasn't covered by our default value patches. That means that there were still some cases where default or missing values weren't properly persisted on objects for content created via Z3C forms.
These cases are:
- Fields where the current user doesn't have write permission
(these get [filtered out completely in `p.autoform.utils.processFields()`](https://github.com/plone/plone.autoform/blob/1.6.2/plone/autoform/utils.py#L189-L217))
- Fields that are omitted from the form
- Fields whose widgets are in `DISPLAY_MODE` even in AddForms.
In addition, I updated the …

Ensure default values get set by patching DX DefaultAddForm.create

---

docs/HISTORY.txt
opengever/base/default_values.py
opengever/base/monkey/patches/default_values.py
opengever/base/tests/test_default_values_for_types.py
opengever/meeting/proposal.py

This fixes an edge case for `title` or `description` fields with default values :
When a `title` or `description` field has a default(factory), there is one more pathological case where defaults weren't persisted correctly up until now:
The [constructor in `Products.CMFCore.PortalFolder.PortalFolderBase`](https://github.com/zopefoundation/Products.CMFCore/blob/ba14b57c0b3486a7bf5b60341ad97ead096b8f53/Products/CMFCore/PortalFolder.py#L71-L74) sets title and description specificially to the empty string if no **actual** field value was provided.
This then fools our own [`set_default_values()`](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/default_values.py#L266-L310) which is called later: Because there already is a value persisted on the object for those fields, it …

Fix default value persistence edge case for title and description fields.

---

README.rst
opengever/api/tests/test_serializer.py
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/document/tests/test_bumblebee.py
opengever/dossier/docprops.py
opengever/dossier/tests/__init__.py
opengever/dossier/tests/test_default_doc_property_adapters.py
opengever/dossier/tests/test_documents_tab.py
opengever/dossier/tests/test_overview.py
opengever/dossier/tests/test_templatefolder.py
opengever/mail/tests/test_indexers.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt
opengever/private/tests/test_reference_number.py
opengever/testing/fixtures.py

properties from the `Dossier` were missing in the docproperties of documents inside `Task` and `Proposal` because we were getting the dossier with `aq_parent` instead of using `get_parent_dossier`.
I also added tests to make sure such documents contain the expected docproperties.
resolves #4410

Include Dossier Doc-Properties for Documents inside Proposals and Tasks

---

docs/HISTORY.txt
opengever/base/tests/test_default_values_for_types.py
opengever/private/folder.py

Make sure members folders (private roots) get persisted default values.
*(Discovered by running the script that checks for default value persistence)*

Make sure members folders (private roots) get persisted default values.

---

docs/HISTORY.txt
opengever/task/handlers.py
opengever/task/tests/test_sequential_task_process.py

When a `Task` from a sequential task template gets closed or skipped, its successor is opened.
resolves #4459

Open successor task when predecessor is skipped or closed.

---

docs/HISTORY.txt
opengever/task/browser/transitioncontroller.py
opengever/task/tests/test_transitioncontroller.py

Disallow reopen task in resolved dossier

---

docs/HISTORY.txt
opengever/base/command.py
opengever/base/tests/test_command.py
opengever/core/upgrades/20180619143343_make_sure_excerpt_document_title_is_unicode/upgrade.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_agendaitem_proposal.py

The title entered in the create excerpt dialog was never decoded to unicode and stored as utf8. Thus displaying the title failed in various places.
This PR fixes:
- the form now correctly stores unicode
- also add a safeguard to command to convert title of newly created objects
- versions of affected documents
- messages in the journal that still contained the utf8-title, inspired by https://github.com/4teamwork/opengever.maintenance/pull/90
The upgrade-step only updates documents affected by the bug fixed here, i.e. all the different excerpts.
Fixes #4452.

Make sure excerpt document title is unicode.

---

docs/HISTORY.txt
opengever/api/mail.py
opengever/api/tests/test_mail.py

Currently mail titles gets resetted to subject, when trying to update a mail via REST-API PATCH requests. It now only syncs the title from subject if a message object is part of the
parameters.
This fix makes it also possible to create a mail with a different title than the subject.
Closes #4456
Backport needed to: `2018.3-stable`

Fix updating mail title via API.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_meeting_zipexport.py

`document.file` is not available in `OGMail`
Use `document.get_file()`, which is available on documents and mails.
@lukasgraf: I will squash the commits together after review.
I left the commit where I remove the test unsquashed to remind why the test didn't work as expected.
Resolves #4453 
Backport needed to: `2018.3-stable`

Meeting zip export shall hande mails

---

docs/HISTORY.txt
opengever/base/tests/test_default_values_for_types.py
opengever/core/upgrades/20180620155146_rename_proposal_column_creator_to_issuer/upgrade.py
opengever/core/upgrades/20180620155221_migrate_proposal_creator_to_issuer/upgrade.py
opengever/meeting/browser/documents/proposalstab.py
opengever/meeting/browser/proposalforms.py
opengever/meeting/browser/resources/proposal.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/proposal.py
opengever/meeting/model/query.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_listings.py
opengever/meeting/tests/test_submitted_proposal.py
opengever/tabbedview/browser/personal_overview.py
opengever/testing/builders/dx.py
opengever/testing/builders/sql.py
opengever/testing/fixtures.py

closes #4412 
- Add attribute `issuer` to the proposal type
- migrate `creator` to `issuer`
See issue #4412 for more details about.

Add the new issuer field to a proposal

---

docs/HISTORY.txt
opengever/activity/__init__.py
opengever/activity/browser/settings.py
opengever/activity/hooks.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/roles.py
opengever/core/upgrades/20180620155648_add_meeting_notification_settings/upgrade.py

This PR adds the required roles to setup the proposal notification properly.
I had to already update the activity-settings to fix the tests. This means, the newly introduced activities and its roles are already listed within the personal-settings overview.
Closes #4413

Add proposal notification roles

---

docs/HISTORY.txt

Released from `2018.3-stable` branch.

Cleanup changelog after 2018.3 hotfixes.

---

opengever/meeting/browser/templates/macros.pt

Follow up for https://github.com/4teamwork/opengever.core/pull/4397.
Closes #4470.
_separate CL entry not necessary IMO_

Drop no longer used meeting macros.

---

Gemfile
Gemfile.lock

* Bumped the expected ruby version
* Bumped the expected bundler version
* Updated sass
* Updated rb-kqueue
* Verified it produces no output delta vs. the previous sass version

Match the plonetheme.teamraum inherited ruby stack to match the sablon one

---

docs/HISTORY.txt
opengever/task/handlers.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/response_description.py
opengever/task/tests/test_response_descriptions.py

In response message, we indicate the new task responsible when the task is rejected.
resolves #4460

Indicate responsible change when task is rejected.

---

docs/HISTORY.txt
opengever/document/browser/versions_tab.py

Comments are truncated when they are too long.
A simple way to solve this without breaking the UI is to put the comment
as well in the title attribute of the DOM element containing the
truncated text.
This is already solved in the Journal tab.
The tooltip helper just strips all html tags from the text, probably to
prevent XSS.
I also removed the sortable option on the comment (shall I put this into its own commit or shall I keep the sort option?)
Resolves #4323

Put comments as well in the title attribute

---

docs/HISTORY.txt
opengever/tasktemplates/browser/trigger.py
opengever/tasktemplates/tests/test_trigger.py

The problem is in how the string representing the user is treated in the forms used to choose a task responsible (`SelectResponsiblesWizardStep`). When representing a user it has the form `orgunit:user_id` and for the inbox `inbox:orgunit`.
This is fixed here with conditionals, as it is in several other places in the code. In the future, this should all be delegated to the actor. 
resolves #4458

Fix bug when triggering a tasktemplatefolder with inbox as responsible.

---

docs/HISTORY.txt
opengever/core/upgrades/20180517160709_change_physical_path_column_type/upgrade.py

Changing a VARCHAR2 column to CLOB, as it has been done by the former implementation of the `ChangePhysicalPathColumnType` migration, does not work on oracle and raises an
`DatabaseError: (cx_Oracle.DatabaseError) ORA-22858: invalid 
alteration of datatype` exception (see
https://stackoverflow.com/questions/13402510/oracle-changing-varchar2-column-to-clob).
Therefore I add a special handling for oracle backends: create a new column and move the data from the old column to the new column.
This needs to be backported to `2018.3-stable`.

Fix physical_path schema migration for oracle backends.

---

opengever/core/upgrades/20180517160709_change_physical_path_column_type/upgrade.py

Altering an oracle column to nullable-allowed where nullable was already allowed, is not possible and ends in an Oracle Exception (`ORA-01451: column to be modified to NULL cannot be
modified to NULL`), therefore I add an additional check and only handle non-nullable columns.
I've tested the upgradestep on oracle, works now 😅 
Needs backport: `2018.3-stable`

Fixup for #4506 (oracle fix).

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/opengever.bumblebee.pot
opengever/bumblebee/tests/test_overlay_view.py
opengever/document/tests/test_versioner.py
opengever/document/versioner.py

* Uses the versioner to pull in the metadata history
* Uses the lazy history proxy to fetch the correct comment for the document version in question
Closes https://github.com/4teamwork/opengever.core/issues/4381

Display the checkin comment on bumblebee overlays

---

opengever/base/monkey/patches/default_values.py

I'm pretty sure this is fine.
https://github.com/plone/plone.registry/blob/d77dec32cb25d604cc48ac6c8ab92a5a10af26e9/plone/registry/interfaces.py#L185-L190
Closes https://github.com/4teamwork/opengever.core/issues/4340

Whitelist registry records proxies for non-persistency

---

docs/HISTORY.txt
opengever/base/browser/paste.py
opengever/base/tests/test_copy_paste.py

We're potentially mucking with DC metadata assumptions here:
https://github.com/zopefoundation/Products.CMFCore/blob/e235f04aea5678f56693fdbaca152da0685e8fc7/Products/CMFCore/interfaces/_content.py#L235-L248
Closes #4386

Ensure creator gets set to the paster upon pasting content

---

docs/HISTORY.txt
opengever/document/browser/versions_tab.py
opengever/document/tests/test_versions_tab.py
opengever/journal/tab.py
opengever/journal/tests/test_journal_tab.py
opengever/tabbedview/helper.py
opengever/testing/helpers.py

Fixes unicode issue with `tooltip_helper` for versions tab comments that contain non-ASCII characters:
The tooltip_helper is currently used by two tabs, version and journal tabs. They don't both pass it the same type of value, one uses unicode and the other bytestrings. The `tooltip_helper` therefore needs to be able to accept both, work with unicode internally, and finally return a bytestring.

Fix unicode error in versions tab comments.

---

docs/HISTORY.txt
opengever/task/browser/overview.py
opengever/task/viewlets/response.py

Fix a bug with modern emojis while rendering task responses. The source of the
problem was not calling `getData` on a transform  which will return a stream
instead of the result.
Testing seems a bit difficult at the moment as our tooling does not seem to
support these characters either 😂.
But, task-responses are now rendered correctly, even if they contain emojis:

Fix a bug with modern emojis in task responses.

---

docs/HISTORY.txt
opengever/bumblebee/tests/test_overlay_view.py
opengever/document/browser/actionbuttons.py
opengever/document/browser/templates/macros.pt
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_overview.py

When document is already checked-out we now show an `Edit` button instead of `Checkout and edit`. 
**Normal 'checkout and edit' of a file**
**Once checked-out, we now show an `Edit` button**
**For a file that cannot be edit in office connector (unsupported file type), we show an `checkout` button**
**If the file is already checked-out and is of unsupported type, we don't show any button (before we showed the checkout button here, but that does not make sense)**
resolves #1812

Improve "checkout and edit" buttons

---

opengever/base/tests/test_default_values_for_types.py
opengever/core/tests/test_relations.py
opengever/document/tests/test_document.py
opengever/locking/tests/test_lockable.py
opengever/meeting/tests/test_committee_container_tabs.py
opengever/meeting/tests/test_committee_roles.py
opengever/meeting/tests/test_committee_tabs.py
opengever/meeting/tests/test_members.py
opengever/meeting/tests/test_memberships.py
opengever/meeting/tests/test_periods.py
opengever/meeting/tests/test_protocol_json_data.py
opengever/meeting/tests/test_submit_additional_documents.py
opengever/meeting/tests/test_toc.py
opengever/meeting/tests/test_unit_agenda_item.py
opengever/testing/builders/dx.py
opengever/testing/fixtures.py

This PR fixes a viewlet rendering error that appeared during toc tests. The test fixture contained two active periods, which is an invalid state.

Fix viewlet rendering error in toc tests.

---

docs/HISTORY.txt
docs/public/admin-manual/meeting/mergefields.rst

Remove the unsupported fields from the documentation.
These fields are part of the old SPV version and can therefore be removed.
All customers of the old SPV were migrated to the new version.
Resolves #4530

Remove deprecated sablon fields from documentation

---

opengever/locking/info.py
opengever/locking/templates/info.pt
opengever/locking/tests/test_lockable.py

Lock info is visible now even if the lock belongs to the current user.
Only managers will see the unlock button though.
**User see own lock**
**managers can unlock**
resolves #4454

Make lock info visible even when it can be safely unlocked.

---

docs/HISTORY.txt
opengever/base/browser/configure.zcml
opengever/base/browser/is_delete_available.py
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20180629085145_restrict_delete_action_availability/actions.xml
opengever/core/upgrades/20180629085145_restrict_delete_action_availability/upgrade.py
opengever/dossier/tests/test_dossier_workflow.py
opengever/repository/tests/test_deletion.py
opengever/tasktemplates/tests/test_tasktemplate.py

Since #3598, a delete action button was available everywhere for managers, and on third level of the repository it was available for admins even when the node was not empty, or twice when the node was empty. This was an unintended side effect of making the delete action available for the private folder, it became instead available everywhere where a user had delete rights on the parent. As we also have our own delete action for repos, this could lead to two available buttons.
The tests did not catch this error because we were testing on a branch repository folder, where the administrator does not have delete rights on the parent. Testing on a leaf made the error apparent.
I added a new view used to control where the delete button should be available and improved the tests for deleting …

Restrict availability of Delete action button

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Build missing french translations for opengever.meeting.
The translations should have been builded through the PR: #4490

Build missing french translations for opengever.meeting

---

docs/HISTORY.txt
opengever/tasktemplates/browser/tasktemplates.py
opengever/tasktemplates/browser/templates/view.pt
opengever/tasktemplates/content/tasktemplate.py
opengever/tasktemplates/tests/test_tasktemplate.py

When the text contains line breaks and similar, they were not displayed in the detail view.
Resolves #4526

Format task template comments

---

docs/HISTORY.txt
opengever/latex/opentaskreport.py
opengever/latex/tests/test_opentaskreport.py

This is a follow up to #4529 - the condition for checking admin-unit local tasks *(local side of inter-admin-unit task-pairs)* in the open task report was wrong.

Open task report: Fix condition to report admin-unit local tasks only

---

docs/HISTORY.txt
opengever/meeting/command.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

The message displayed when regenerating the agendaitem list was wrongly saying that the protocol has been regenerated.

Correct info message when agendaitem list is regenerated.

---

opengever/officeconnector/tests/test_api_dossier_attach.py
opengever/officeconnector/tests/test_api_dossier_checkout.py
opengever/officeconnector/tests/test_api_dossier_disabled.py
opengever/officeconnector/tests/test_templates.py

In an effort to make use of newly added elements in the fixture we update the OfficeConnector tests.
Using the inactive and archive dossiers from the fixture instead of setting the workflow state in the office connector tests made for an easy speedup (from 1:50 to 1:15 on my machine).
This is part of issue #3857

Speedup OfficeConnector tests by better using the fixture

---

docs/HISTORY.txt
opengever/document/tests/test_versions_tab.py
opengever/tabbedview/helper.py
opengever/tabbedview/tests/test_helpers.py

The `comment` in the `sys_metadata` section of version metadata may be `None` as well as empty string. This fixes the `tooltip_helper` so it also deals with this case, and adds regression tests for both the helper as well as the higher level use case of the version tab.
First I changed `Versioner.create_version()` in a way where it never sets `None` as a comment - but I think that's misleading:
1) There's no upgrade step that fixes existing version metadata, so `None` can still appear -> nothing gained
2) That's just the way CMFEditions works, we have to expect `None` in this kind of metadata.  
Fixes #4515

Fix issue where empty version comments caused version tab to fail

---

docs/HISTORY.txt
opengever/meeting/proposal.py
opengever/meeting/tests/test_activites.py

This PR improves the tests of proposal activities.
It tests the badge-notifications for the notification-settings for each activity.
This is a follow-up pr of https://github.com/4teamwork/opengever.core/pull/4548

Improve proposal activity tests

---

docs/intern/kurzreferenzen/ubersetzungen.rst
docs/intern/meta.rst
sphinx.cfg

The docs are now on seth.4teamwork.ch instead of theta.4teamwork.ch
Due the use of personal users, every user who updates the documentation must customize their .ssh/config configuration.
Please add the following in your local ~/.ssh/config
```
Host seth.4teamwork.ch
User <user>
```

Migrating docs and translation to other server

---

bin/enable-lfs
sphinx.cfg

When attempting to build docs using on of the `bin/docs-build-<project>` scripts, this will now **print a warning and abort if `git-lfs` support hasn't been enabled** for the current repo *(because that would result in a build with missing images)*.
On CI (Jenkins) this check is skipped, because we explicitely don't want to enable LFS on Jenkins, and the missing images otherwise don't negatively affect the docs build.
*(No changelog entry because internal change)*

Docs: Check whether git-lfs is enabled before building.

---

opengever/api/tests/test_content_creation.py
opengever/base/tests/test_default_values_for_types.py

- Rewrite API content creation tests as integration tests
- Rewrite default value tests as integration tests
- Use documents with files in default value tests because this is our most important and common use case

Rewrite API tests as integration tests

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/tests/test_agendaitem.py

Fix unicode error on edit an agendaitem.
The title and description are already in unicode. See https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/browser/meetings/agendaitem.py#L333. So it's not possible to re-decode it.
Before:
After:
closes #4582

Fix unicode error on edit an agendaitem.

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_favorite.py
opengever/base/tests/test_helper.py
opengever/document/configure.zcml
opengever/document/handlers.py

Updates the favorite-icon for checked-out documents:
Favorites for user who checked-out the document:
---------------------------------------------------
Favorites for user marked a checkedout document as a favorite:
---------------------------------------------------
@lukasgraf ❓ to get the different icon-classes (see method `_update_favorites_icon_class`, we have to lookup the icon for the current user and for all the other users (as already mentioned by @jone within the issue itself). I see three different approaches to reach the same result:
1. Manually manipulating the css-class (this is what I've implemented) 
We get the css-class for the current user and remove the unnecessary part of class for other users.
=> I've chosen this solution because it was fast to implement and i have …

Update favorite-icon after checking-out or checking-in a document.

---

opengever/base/browser/edit_public_trial.py
opengever/base/tests/test_utils.py
opengever/document/browser/archival_file_form.py
opengever/document/tests/test_archival_file_form.py
opengever/dossier/utils.py

We make use of the new elements in the fixture to port the archival file form tests to the integration layer. This is part of issue #3857.
Note that:
1. There was a harmless bug in the `can_access_archival_file_form` function. While iterating over the `DOSSIER_STATES_OPEN` to check whether the user has `Modify portal content` rights on any of these states, we would return whether the user has these rights on the first of the states in the list.
2. The test `test_parent_of_content_needs_to_be_a_dossier` did not actually test what was advertised in the title, instead the second part
```
with self.assertRaises(AssertionError):
can_access_archival_file_form(user, self.document.aq_parent)
``` 
actually tests that the form cannot be accessed for an object that is not `documentish`. This is …

Port archival file form tests to integration layer

---

opengever/core/upgrades/20180716102547_reset_task_templates_listing_cache/upgrade.py
opengever/tasktemplates/browser/tasktemplates.py

Fix the upgrade step to set the sorting on the `draggable` column and also make sure that it is set to `draggable` column per default.
I did not add a CL entry here, as this fixes a change that is not released yet and has a CL entry.
resolves #4596

Make sure to sort tasktemplates on the draggable column.

---

docs/HISTORY.txt
opengever/locking/info.py
opengever/locking/templates/info.pt

We now show hide the unlock button when editing the document metadata.
I decided to leave the info that the document is locked when editing the metadata, as I think it is relevant for the user to know that while he is editing the metadata, the document is locked. Obviously we can also remove that info, if you think this is irrelevant/confusing for the user.
I also updated the changelog, as I had forgotten to add an entry in #4539 
resolves #4598

Hide unlock button in the DocumentEditForm.

---

docs/HISTORY.txt
docs/public/dev-manual/api/config.rst
opengever/api/config.py
opengever/api/configure.zcml
opengever/api/tests/test_config.py
opengever/base/casauth.py
opengever/base/configuration.py
opengever/base/subscribers.py
opengever/base/tests/test_casauth.py
opengever/base/tests/test_configuration_adapter.py

Enhancements needed for new UI:
- Makes `@config` endpoint accessible for anonymous on every context
- Return CAS server URL
- Return root URL

Gever-UI Config Enhancements

---

opengever/latex/dossierjournal.py
opengever/latex/tasklisting.py

Just stumbled on some copy/paste fails in some docstrings in the `opengever.latex` module

Fix docstrings in opengever.latex

---

docs/HISTORY.txt
opengever/meeting/configure.zcml
opengever/meeting/handlers.py
opengever/meeting/tests/test_proposal.py

There is an issue with `ftw.mail.mail` attachments as the event handler was only registered for documents, and not for mails. Thus rows in the `submitteddocuments` table were not removed correctly which led to an `IntegrityError` for a duplicate key value upon re-submitting.
Fixes #4565.

 Fix re-submitting previously rejected proposals.

---

docs/HISTORY.txt
opengever/meeting/browser/documents/submit.py
opengever/meeting/browser/submitdocuments.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

There are several views for submitting additional documents.
One is used to submit additional documents and for updating these documents.
This view got a dynamic label, such that the label matches the action (update submitted documents or submit new documents).
Resolves #4584

Improve view for additional submitted documents

---

docs/HISTORY.txt
opengever/base/security.py
opengever/base/tests/test_security.py
opengever/document/browser/versions_tab.py
opengever/document/tests/test_versioner.py
opengever/document/tests/test_versions_tab.py
opengever/document/versioner.py

With the **deferred creation of the initial version** (introduced in #3467), the initial version will only be created once a second version is actually created. That may happen in the security context of a different user that initially created the document.
Because CMFEditions always sets the ID of the currently logged in user as `sys_metadata['principal']`, this leads to incorrect authorship attribution for this case.
We therefore create the initial version with a security context that assumes the user ID of the document's initial creator to make sure the 'principal' in the initial version's authorship metadata is correct.
I also changed the version tab so it always lists the document's original creator for version 0 - irrespective of whether that's an actual initial version (case …

Create initial version with the original document creator as the principal

---

opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob

Theta is dead!
We use agyptian gods now to host our GEVER SaaS customers.
...and these want us to extends other buildout configurations!
Also them gods want us to use a different database name, because dashes
prevent the databases to be removed automatically and such and such.

Update the policy template for new servers

---

docs/HISTORY.txt
opengever/base/browser/configure.zcml
opengever/base/browser/manage_role_assignments.py
opengever/base/tests/test_role_assignments.py

Because the ZMI's manage_access view, is no longer the alone source of
truth, I added a management view which returns all the existing
assignments for the current context. The view is only accessible for managers.

Add role assignments management view.

---

docs/HISTORY.txt
opengever/inbox/browser/tabs.py
opengever/inbox/tests/test_tabs.py

It's not possible to add a proposal to an inbox, therefore the create proposal action does not make sense.
I also convert the inbox tab tests to integration tests.
Closes #4646

Hide create proposal action on inboxes document listing tab.

---

docs/public/user-manual/benachrichtigung.rst
docs/public/user-manual/img/media/img-benachrichtigungs-einstellungen-5.png
docs/public/user-manual/spv/antrag-erfassen.rst
docs/public/user-manual/spv/antrag-traktandieren.rst
docs/public/user-manual/spv/antrags-benachrichtigungen.rst
docs/public/user-manual/spv/index.rst

@phgross  ein Printscreen mit dem Feld "Antragssteller" fehlt noch. Möchte diesen dann auf spv.onegovgever machen, damit es zu den restlichen Screens passt.

Doku Anpassungen durch OGIP 36

---

docs/HISTORY.txt
opengever/task/browser/assign.py
opengever/task/browser/forms.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/task.py

This is not necessary any mode, since the `responsible_client` field is now purely internal and is [always hidden](https://github.com/4teamwork/opengever.core/blob/871272d901bcce701e4bce01180f392bcdf82a35/opengever/task/task.py#L135). Also the description for the `responsible` field should be the same for both single and multi org unit deployments, so the translations can be homogenized.

Task forms: Drop unnecessary distinction between single/multi org unit setups

---

opengever/locking/info.py

Not sure why but when editing an E-mail, the view attribute of the lockinfo viewlet is the form wrapper (`Products.Five.metaclass.MyFormWrapper`) and not the form itself. Hence it does not provide the `IEditForm` interface and we first need to get the form instance in that case.
I'd be happy with a cleaner solution though...
fixes #4662

Do not show lockinfo in mail edit form.

---

docs/HISTORY.txt
opengever/document/static/officeconnector.js

Office connector uses the window location as base url for the dossier, but this does not work when called from a url with the trailing view name. Instead we can use the `href` attribute of the `base` tag.
This works as is, we do not need to fix #4672 first as the base url is already correct for folderish objects.
resolves #4665

Fix officeconnector issue with urls including view name

---

docs/HISTORY.txt
opengever/base/tests/test_default_values_for_types.py
opengever/dossier/behaviors/protect_dossier.py
opengever/dossier/browser/forms.py
opengever/dossier/tests/test_protect_dossier.py

The `dossier_manager` must not be a schema default, because otherwise the current user gets set as a default in situations other than user-created content via forms (programmatic content creation via OGGbundle import, REST API, etc...).
This changes the `dossier_manager` to be **just a form level default** instead of a schema level default.
*@phgross As discussed, I will refactor the form widget prefilling by introducing a common helper method to easily access `z3c.form` group widgets (in a later PR).* 
Fixes #4653

Only prefill dossier_manager as a form level default (instead of schema level)

---

docs/HISTORY.txt
opengever/tasktemplates/browser/trigger.py
opengever/tasktemplates/tests/test_trigger.py

For users who triggers an tasktemplatefolder, it's easier to understand if the interactive users are already resolved to real users. Closes #4651 
Note: Because the `TaskTemplateFolderTrigger` functionality will also be used by an API endpoint, the resolving interactive users is done there too.

Resolve interactive users already on the select-responsibles step.

---

docs/HISTORY.txt
opengever/base/clipboard.py
opengever/base/configure.zcml
opengever/base/tests/test_copy_paste.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180806174312_add_clipboard_e_tag/registry.xml
opengever/core/upgrades/20180806174312_add_clipboard_e_tag/upgrade.py

to make sure that the paste action occurrence is not cached. Closes #4647.

Add eTag adapter for the clipboard

---

docs/HISTORY.txt
opengever/dossier/behaviors/protect_dossier.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_protect_dossier.py

We require that the dossier manager field is set when `reading` or `reading_writing` protection is set.
An exception is raised if this is not the case:
resolves #4673

Make sure dossier manager field is set when protecting a dossier.

---

opengever/task/tests/test_transition_actions.py

This test fails all the time in a flaky way, but only on Jenkins.

Tests: Skip flaky task transition test for now.

---

docs/HISTORY.txt
opengever/base/browser/layout.py
opengever/base/tests/test_layout.py

We fix the base URL for contentish objects, which was incorrectly set to the request URL, hence including the view name.
This is for issue #4672, fixing the problem for the 2018.4 release, but the issue should not be closed as we will implement a better solution for 2018.5.
In the meantime, this resolves #4671

Fix base URL tag for contentish objects.

---

docs/HISTORY.txt
opengever/core/profiles/default/portal_placeful_workflow.xml
opengever/core/profiles/default/portal_placeful_workflow/opengever_inbox_policy.xml
opengever/core/profiles/default/workflows.xml
opengever/core/profiles/default/workflows/opengever_inbox_document_workflow/definition.xml
opengever/core/profiles/default/workflows/opengever_inbox_workflow/definition.xml
opengever/core/upgrades/20180726095934_add_placeful_workflow_for_inbox_area/portal_placeful_workflow.xml
opengever/core/upgrades/20180726095934_add_placeful_workflow_for_inbox_area/portal_placeful_workflow/opengever_inbox_policy.xml
opengever/core/upgrades/20180726095934_add_placeful_workflow_for_inbox_area/upgrade.py
opengever/core/upgrades/20180726095934_add_placeful_workflow_for_inbox_area/workflows.xml
opengever/core/upgrades/20180726095934_add_placeful_workflow_for_inbox_area/workflows/opengever_inbox_document_workflow/definition.xml
opengever/core/upgrades/20180726095934_add_placeful_workflow_for_inbox_area/workflows/opengever_inbox_workflow/definition.xml
opengever/document/browser/overview.py
opengever/document/tests/test_overview.py
opengever/inbox/tests/test_workflow.py
opengever/setup/profiles/default_content/content_creation/01_default_content.json
opengever/testing/fixtures.py

Currently inbox inbox group users are wrongly able to edit the inbox. Because those users should still be able to edit documents inside the inbox, we introduce a separate workflow for inbox_documents and adjust the inbox workflow:
- Add a separate placeful workflow policy `opengever_inbox_workflow` enabled on inboxes and inbox-containers and below.
- Separate inbox_document workflow which no longer acquires the permissions `Modify portal_content`, `Request review`, `opengever.document: Cancel`, `opengever.document: Checkin` and `opengever.document: Checkout`
- Revoke `Modify_portal_content` for `Editors` and `Administrators on inboxes`
- Upgradestep which enables the placeful_workflow policy for all inboxes or inbox-container and below.
Currently inbox users are not been able to …

Add placeful workflow policy for inboxes

---

versions.cfg

Used by the newer version of plone.restapi.

Add version pinning for plone.schema.

---

docs/HISTORY.txt
opengever/api/sharing.py
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

With the plone.restapi version dump, I dropped the order of available roles. Because the user is used to the current role order, we want to lock this.

Lock oder of avaialbe roles in sharing endpoint.

---

docs/HISTORY.txt
opengever/base/browser/resources/prepoverlay.js
opengever/ogds/base/browser/configure.zcml
opengever/ogds/base/browser/templates/userdetails.pt
opengever/ogds/base/browser/templates/userdetails_table.pt
opengever/ogds/base/browser/userdetails.py
opengever/ogds/base/tests/test_userdetails.py
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

Extract user details table in to a separate template and add a plain view, which can be displayed in a overlay. So we can show the user details in a overlay in the sharing view, in the same manner we display the group details.
I've also adjust the prepOverlay JS to not stack overlays when clicking on a overlay-link inside an overlay.

Sharing views: Show userdetails also in an overlay. 

---

docs/HISTORY.txt
opengever/sharing/browser/resources/sharing.js
opengever/sharing/browser/templates/sharing.html
opengever/sharing/browser/templates/sharing.pt

- No longer use arrow functions and Object.values, there are not supported by IE 11.
- Drop sharing.js from the sharing template. The sharing.js is included globally (registered in the js registry), so no need to include them in the template.
- Show assignments_info button (?) only on rows with automatic roles

Sharing view improvements and IE 11 fixes

---

README.rst
docs/HISTORY.txt
opengever/api/tests/test_mail.py
opengever/api/tests/test_serializer.py
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/tests/test_overlay_adapter_document.py
opengever/bumblebee/tests/test_overlay_adapter_document_version.py
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/dossier/tests/test_overview.py
opengever/dossier/tests/test_templatefolder.py
opengever/ech0147/tests/test_model.py
opengever/mail/tests/test_indexers.py
opengever/officeconnector/tests/test_api_dossier_attach.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt
opengever/private/tests/test_reference_number.py
opengever/testing/fixtures.py

* Added an empty document into the fixtures
* Ported the bumblebee overlay tests to integration tests
* Fixed the bumblebee document overlay date getter to allow for `None`
Closes #4723

Fix the bumblebee document overlay date getter to allow for `None`

---

docs/HISTORY.txt
opengever/api/tests/test_config.py
opengever/base/browser/config.py
opengever/base/browser/configure.zcml
opengever/base/configuration.py
opengever/base/interfaces.py
opengever/base/tests/test_configuration_adapter.py
opengever/base/tests/test_get_setting_view.py
opengever/base/tests/test_gever_ui_action.py
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180809152739_add_gever_ui_action/actions.xml
opengever/core/upgrades/20180809152739_add_gever_ui_action/registry.xml
opengever/core/upgrades/20180809152739_add_gever_ui_action/upgrade.py
opengever/testing/integration_test_case.py

We add an action to switch to the new GEVER UI. The action is controlled by two registry settings:
1. boolean to activate the feature (disabled by default)
2. a URI to control the basepath used to redirect to the new UI.
We also introduce a new view to retrieve registry settings (from a traversal to the view followed by the setting name for example `get_setting/gever_ui_enabled`)
resolves #4688

Add action to switch to new UI

---

docs/HISTORY.txt
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/response_description.py
opengever/task/tests/test_response_descriptions.py

With #4502 the automated responsible change when rejecting a task is now also visible in the response. But that leads to confusing response description for older tasks, where the responsible change took not place. Like 
> Abgelehnt durch ${old_responsible}. Aufgabe an Auftragnehmer ${new_responsible} zugewiesen.
Therefore I re add the former message for task where no responsible change has been made.

Fix Reject response description for old tasks

---

docs/HISTORY.txt
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/default_values.py
opengever/base/tests/test_default_values_for_types.py
opengever/testing/helpers.py

Make sure widgets properly return persisted missing values for optional fields with default values:
In `z3c.form.widget.Widget.update` there is a [misguided check](https://github.com/zopefoundation/z3c.form/blob/3.2.11/src/z3c/form/widget.py#L114) that falls back to using a **default value** if a fields actual value is **equal to missing value**.
This leads to a bug where for fields that are
1) optional (not required)
2) have a default of some sort (field.default or field.defaultFactory)
3) have a legitimate missing value persisted
4) have a MV that is different from the default
an incorrect value is returned by the widget (the default value instead of the legitimate missing value).
This will result in display views that render an object and use the widget's display mode for that to …

Make sure widgets properly return persisted missing values

---

docs/HISTORY.txt
opengever/api/tests/test_summary.py
opengever/task/task.py

It does not make sense to mark a `text` field   as a primary field.
This solves an issue (closes #4745) where API GET request on dossiers had raised an AttributeError when the dossier contained tasks and the summary fieldlist contained the `filesize` or `filename` attribute.

Mark tasks text field no longer as the primary field.

---

opengever/core/upgrades/20180813122830_fix_contenttype_for_ms_publisher_files/upgrade.py
opengever/document/extra_mimetypes.py

Including an upgradestep which fix the contenttype for existing MS Publisher documents.
Note: Changelog entry not necessary, feature already mentioned in the changelog.

Register MS publisher mimetype to python mimetypes registry.

---

docs/HISTORY.txt
opengever/base/hooks.py
opengever/core/upgrades/20180813172307_exclude_precondition_failed_from_error_log/upgrade.py

`PreconditionFailed` errors should be managed client side and can therefore be ignored on the GEVER side.
resolves #4730

Exclude PreconditionFailed from Error log.

---

docs/HISTORY.txt
opengever/base/protect.py
opengever/base/sentry.py

Filter list of registered objects so only **offending** objects are logged in sentry - whitelisted (safe) objects get removed from the list.
This should make it much easier to determine the culprit (object unexpectedly being written to) from the Sentry event.
The extra data attribute in Sentry was renamed from `_registered_object` to `filtered_registered_objects` to be able to distinguish what the semantics of the reported data in a Sentry event are (filtered or not):
---
Also, this changes the **log level** of CSRF events to `warning`:
Closes #4676

CSRF logging: Filter list of registered objects

---

docs/HISTORY.txt
opengever/base/browser/configure.zcml
opengever/base/browser/ploneview.py
opengever/base/tests/test_ploneview.py
opengever/core/tests/test_view_security.py

to respect also workflow transitions.
This solves an issue, where the contentmenu was wrongly not visible, in some cases where the user is able to trigger a transition, but does not have Modify oder Add portal content permission. For example an administrator is allowed to reactivate a inactive dossier, but did not see the menu. Closes #4621

Overwrite showEditableBorder from ploneview

---

opengever/sharing/browser/resources/sharing.js

Some cleanup work for the recently introduced new sharing form.
Closes #4737.

Sharing Vue app: remove the unnecessary reactive properties.

---

docs/HISTORY.txt
opengever/inbox/browser/refuse.py
opengever/task/browser/assign.py
opengever/task/browser/forms.py
opengever/task/deadline_modifier.py
opengever/task/tests/test_assign.py
opengever/task/tests/test_deadline_modification.py
opengever/task/tests/test_forms.py
opengever/task/util.py

This solves or at least temper an existing performance-issue when reassign a task inside a large dossier (see #4683) or other task transition/actions. The following transitions could be optimized:
- Reassign a task / forwarding via transition
- Reassign a task via Editform
- Deadline modification
- Refusing a task

Avoid ObjectModifiedEvents gets fired multiple timeson task transitions

---

docs/HISTORY.txt
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_zipexport.py

Extend meeting zip-export with sort_order and gever_id, used by grimlock to ensure the sort oder and clean updates of existing meetings.

Extend meeting zip-export with sort_order and gever_id.

---

docs/HISTORY.txt
opengever/meeting/proposal.py
opengever/meeting/proposalhistory.py
opengever/meeting/tests/test_proposalhistory.py

Do not try to sync proposalhistory entries on not sumitted propsoal, because there is no "other side".
Closes #4795

Fix issue when commenting on a not submitted proposal

---

docs/HISTORY.txt
opengever/activity/browser/resources/settings.js

`Object.values` is not supported on IE. See https://stackoverflow.com/questions/42830257/alternative-version-for-object-values

Fix IE bug on the notification settings page.

---

docs/HISTORY.txt
opengever/core/upgrades/20180619143343_make_sure_excerpt_document_title_is_unicode/upgrade.py

The use of CMFEditions' [`CopyModifyMergeRepositoryTool.getHistory()`](https://github.com/plone/Products.CMFEditions/blob/2.2.23/Products/CMFEditions/CopyModifyMergeRepositoryTool.py#L497-L506) causes massive amounts of savepoints (one per version history retrieve).
When this is done for lots of documents, this leads to thousands of savepoints being created and rolled back to in the same transaction.
This has the side effect of creating just as many nested SQLAlchemy transactions.
When the SQLAlchemy connection then is used in a subsequent upgrade step, the attempt to fetch the outermost connection in `sqlalchemy.orm.session.connection_for_bind()` then fails, because it's [recursive](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/orm/session.py#L398) and exceeds Python's …

Make upgrade step 20180619143343 deferrable:

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_agendaitem_adhoc.py
opengever/meeting/tests/test_meeting_zipexport.py

Ad-hoc `AgendaItem` filename was prefixed with "Ad hoc agenda item". It is now simply set to the title of the `AgendaItem`, as entered by the user.
resolves #4409

Set ad-hoc AgendaItem filename to title.

---

docs/HISTORY.txt
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20180720162842_add_task_pdf_enabled_dossier_resolve_property/registry.xml
opengever/core/upgrades/20180720162842_add_task_pdf_enabled_dossier_resolve_property/upgrade.py
opengever/document/document.py
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/interfaces.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py
opengever/latex/configure.zcml
opengever/latex/dossierdetails.py
opengever/latex/dossierjournal.py
opengever/latex/dossiertasks.py
opengever/latex/listing.py
opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/opengever.latex.pot
opengever/latex/templates/dossiertasks.tex
opengever/latex/tests/test_dossierjournal.py
opengever/latex/tests/test_dossiertasks.py
opengever/testing/integration_test_case.py

We add a new feature to create a document of the tasks of a dossier when it gets resolved.
The document is a pdf containing a list of the tasks. For each task we show the metadata followed by a table presenting its history.
This feature is controlled by a configuration entry `tasks_pdf_enabled` in `IDossierResolveProperties` and is deactivated by default.
Finally we introduce an interface to mark the generated document to allow updating it instead of generating a new one when the dossier is reactivated and then closed again. We also adapt the journal pdf to follow that same behaviour.
Here an example of a generated pdf:
[Aufgabenliste des Dossier grege, 25.07.2018 10 05 (8).pdf](https://github.com/4teamwork/opengever.core/files/2228165/Aufgabenliste.des.Dossier.grege.25.07.2018.10.05.8.pdf …

Add feature to generate a pdf listing the tasks when resolving a dossier.

---

docs/HISTORY.txt
opengever/task/handlers.py
opengever/task/tests/test_sequential_task_process.py

Unidirectional by reference tasks (`Zur Kenntnisnahme`) can directly been closed from the open state. This transition wasn't handled by the open_next_task handler, which opens the next planned state from the sequential process.
Should be backported to: `2018.4-stable`

Fix handling of unidirectional by ref tasks in a sequential process.

---

docs/HISTORY.txt
opengever/latex/listing.py

SubDossiersLaTeXListing inherits from DossiersLaTeXListing by removing two columns, but the column widths were not recalculated afterwards, so that the table would not span the whole textwidth.
We add a new method to reset the column width so that the table spans the whole `textwidth`. The tables are now all the same width:
resolves #4623

Correct table width for SubDossiersLaTeXListing.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_meeting_zipexport.py

* Use the localized title string for the agenda item folders within the zip export
* Localize the relevant tests as well
Closes #4528

Simplify agenda item titles for folder names for meeting zip exports

---

docs/HISTORY.txt
opengever/document/base.py
opengever/document/document.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/quick_upload.py
opengever/meeting/tests/test_proposal.py

For proposal documents:
* Disallow non-.docx uploads via metadata edits
* Disallow file removals via metadata edits
* Disallow replacing the file with a non-.docx file via D&D
Should also take care of the API and OC upload routes as per the schema field validation.
Closes #4333

Prevent breaking proposal documents with file replacements

---

docs/HISTORY.txt
opengever/meeting/tests/test_proposal.py
opengever/meeting/vocabulary.py

I also considered translating each language to the user-native language, as `zope.i18n` does have all the mappings to achieve this, but as this only happens in multilingual organisations, always grabbing the language-native title, as specified int he ticket, should be fine.
Closes #4335

Display native language of each language on proposal edit forms

---

docs/HISTORY.txt
opengever/document/checkout/manager.py
opengever/document/tests/test_checkout.py

Document date should not be set by the system anymore, but only by the user. The modification date is already available in the `modified` attribute.
resolves #4560

Do not set document date during checkin or cancel.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/navigation.html

This should be back-ported to 2018.4.
resolves #4814

Fix double escaping of agendaitem title in meeting overview.

---

docs/HISTORY.txt
opengever/core/upgrades/20180619143343_make_sure_excerpt_document_title_is_unicode/upgrade.py

In 34b711962664 excerpts are now also sorted by title. Unfortunately that code is used in an upgrade (which was introduced before aforementioned change) which attempts to fix encoding issues in the title.
With this PR we copy model code into the upgrade, but without sorting as order is not relevant.

Fix an encoding issue by not using model code.

---

docs/HISTORY.txt
plonetheme/teamraum/resources/index.html

Currently the the logo column uses more than 35% of the total width, which is much more than needed by the logos. This fixes #4818 an UI Issue on small screens.
Before:
After:
Works also for installations with a right logo:
Needs backport to: `2018.4-stable`

Scale down size for logo wrapper, to have more space for personal menues

---

docs/HISTORY.txt
opengever/base/browser/livesearch.py
opengever/base/tests/test_search.py

* Fixed result limits for SOLR livesearch
* Fixed paths for global scoped SOLR livesearch 'show more' links
/cc @phgross we'll backport this as well?
Closes #4838
Backport to `2018.4-stable` needed

Fix global scoped "show more" links for SOLR livesearch

---

docs/HISTORY.txt
opengever/dossier/tests/test_templatefolder.py
opengever/ech0147/tests/test_model.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/templates/agendaitems.html
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_agendaitem_proposal.py
opengever/meeting/tests/test_docproperties.py
opengever/meeting/tests/test_meeting.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposalhistory.py
opengever/meeting/tests/test_protocol.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt
opengever/private/tests/test_reference_number.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

When an agendaitem is decided, the proposal should not be set to decided yet, as the decision has not been communicated yet (excerpt returned). We now only set the proposal to decided when the excerpt has been generated and returned.
Closing a meeting now requires that not only all agendaitems are decided, but also that the excerpts have been generated and returned for the agentaitems with proposals.
resolves #4331

Decide proposal only when excerpt is returned

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_agendaitem_proposal.py

* The info message when scheduling a paragraph was wrongfully saying "Paragraph erfolgreich hinzugefügt" instead of "Zwischentitel erfolgreich hinzugefügt"
* When deciding an agendaitem with a proposal, the info message was wrongfully saying that the protocol excerpt was generated and sent back. I propose to change that to "not yet generated and sent back", as we will enforce that the user generates and sends back all excerpts before closing a meeting.
resolves #4771

Correct info messages in meetings

---

docs/HISTORY.txt
opengever/dossier/command.py
opengever/dossier/tests/test_command.py

Creating a dossier from a dossiertemplate would fail when there was a document without a file in the dossiertemplate.
resolves #4828

Fix bug with document without file in a dossiertemplate.

---

docs/HISTORY.txt
opengever/document/quick_upload.py
opengever/meeting/tests/test_proposal_template.py

* It does not seem to be possible to remove a file from a proposal template
* The form upload check was already in place
* Added a check to the file quickuploads for checking if the context is a proposal template
Closes #4642

Prevent replacing files on proposal templates with non-.docx files via quickupload

---

docs/HISTORY.txt
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180907161827_extend_officeconnector_editable_file_types/registry.xml
opengever/core/upgrades/20180907161827_extend_officeconnector_editable_file_types/upgrade.py

See https://github.com/4teamwork/OfficeConnector/pull/296

Register bmp as editable by officeconnector type.

---

docs/HISTORY.txt
opengever/dossier/templatefolder/form.py
opengever/dossier/tests/test_templatefolder.py

When creating a document from a template, `document` templates  inside a `dossiertemplate` should not be in the list of templates to choose from.
Documents can be inside the main `templatefolder`, but also in sub-`templatefolder`, `dossiertemplate`, subfolders in `dossiertemplate`, etc.
In the end we want as templates all `document` that are nor contained in a `templatefolder`. This would need to be recursively checked (as they can have dossiers as direct `parent_folder`). It is easier to get all documents that are directly contained in a `templatefolder`, which should be equivalent. This requires several catalog searches, and a custom sorting.
resolves #4657 
Also resolves https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/76

Fix bug in document template list.

---

docs/HISTORY.txt
opengever/core/upgrades/20180911140637_fix_contenttype_for_ms_publisher_files/upgrade.py
opengever/document/extra_mimetypes.py

This fixes the icon for wmf files (introduced by 94f1ba126651d7ea8f428675e6126ae6075f4fbc).
Instead of writing a new upgradestep, i touched an existing one which does the same for MS Publisher files, to avoid doubled run time.

Add missing mimetype for wmf files.

---

docs/HISTORY.txt
opengever/base/handlers.py
opengever/bundle/console.py
opengever/core/upgrades/20180912160954_reindex_checked_out_and_allowed_roles_and_users_on_solr/upgrade.py
opengever/document/checkout/manager.py
opengever/setup/overrides.zcml
opengever/setup/sections/reindexobject.py
opengever/usermigration/creator.py

Because using `catalog_tool.reindexObject` updates Portal Catalog only, but it doesn't in Solr.
This leads to an inconsistent Solr index and confusing search results for the user. 
Discussed to day with buchi, if ftw.solr should also handle `catalog.reindexObject` calls: 
He is of opinion  that  catalog's `reindexObject`, is an internal API which only updates the portal_catalog, it also skip other catalogs (UID ...) and therefore should not do anything with solr. This makes sense.
The PR contains an upgradestep which reindexes checked_out and allowedRolesAndUsers on solr. Because those could be affected by the reindexing problem. The upgradestep is marked as deferrable, because its not urgent.
I also overwrite the `plone.app.transmogrifiert` ReindexObject section, to include a manual SOLR …

No longer use catalog.reindexObject.

---

docs/HISTORY.txt
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

Urlencode the `groupid` parameter when creating the list-groupmembers overlay link. This fixes an issue with groups where the id contains spaces. (Fixes #4873)

Fix groubmembers overlay for groupids with spaces.

---

docs/HISTORY.txt
opengever/activity/tests/test_handlers.py
opengever/inbox/forwarding.py
opengever/inbox/tests/test_activities.py
opengever/inbox/tests/test_inbox_assign.py
opengever/ogds/base/sources.py
opengever/task/browser/accept/utils.py
opengever/task/browser/forms.py
opengever/task/configure.zcml
opengever/task/handlers.py
opengever/task/tests/test_activities.py
opengever/task/tests/test_api_support.py
opengever/task/tests/test_comment_response.py

With the latest plone.restapi update, there was nothing big to support adding tasks via API:
- Remove unnecessary split ups of `ddd:ddd` tokens. There was never the case.
- Fix activity and watcher registration, by moving the activity recording from the form in to an event handler.
Example request body:
``` js
{
"@type": "opengever.task.task",
"title": "Anfrage prüfen auf Vollständigkeit",
"task_type": "correction",
"text": "Könntest du bitte die Anfrage (siehe Anhang) prüfen und gegebenenfalls ergänzen",
"responsible": "peter.muster",
"issuer": "hans.peter",
"responsible_client": "afi"
}
```

Support adding task via REST API

---

docs/HISTORY.txt
opengever/activity/center.py
opengever/activity/model/query.py
opengever/globalindex/model/query.py

**Activities**
Do not use `is_(True)` for sqlalchemy filter statements, because this leads to an `ORA-00908: missing NULL keyword` exception on oracle backends. So i use filter(== true()) instead.
- https://stackoverflow.com/questions/15143827/missing-null-keyword-error-when-trying-to-avoid-duplicates
- https://stackoverflow.com/questions/18998010/flake8-complains-on-boolean-comparison-in-filter-clause for more information.
**Task**
With #4318 the physical_path column has been switched from a string to a text column. On oracle backends this leads to errors when filtering on physicalpath (`DatabaseError: (cx_Oracle.DatabaseError) ORA-00932: inconsistent datatypes: expected - got CLOB`).
Therefore I implemented a fallback for oracle backends, which first cast to string before filtering.
- …

Fix task and activity queries for oracle backends

---

docs/HISTORY.txt
opengever/core/upgrades/20180919125535_reindex_issuer_for_proposals/upgrade.py

In 4teamwork/opengever.core#4442 a new issuer field was introduced on Proposals. This field is now picked up for the issuer indexes and metadata - but existing proposals hasn't been reindex.
Closes #4855

Reindex issuer of all proposals.

---

docs/public-fr/_static/img/img-triage-1.png
docs/public-fr/_static/img/img-triage-2.png
docs/public-fr/_static/img/img-triage-3.png
docs/public-fr/_static/img/img-triage-4.png
docs/public-fr/_static/img/img-triage-5.png
docs/public-fr/_static/img/img-triage-6.png
docs/public-fr/chapitre9-triage.rst
docs/public-fr/index.rst

Gemäss Aufgabe im Basecamp habe ich in der Französischen Dokumentation das Kapitel *Aussonderung auf französisch hinzugefügt. *Le triage
https://basecamp.com/2768704/projects/13482340/todos/365053299
Bitte um überprüfung, danke

Docs: Aussonderung FR hinzugefügt

---

docs/HISTORY.txt
solr-conf/managed-schema

Fixes:
https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/341

Split search terms at non-alphanumeric characters

---

README.rst
docs/HISTORY.txt
opengever/base/browser/is_delete_available.py
opengever/meeting/tests/test_meeting_template.py
opengever/testing/fixtures.py

As the newly introduced deletability block is a bit of a handful, I've introduced an easy to cleanup mixin for flagging things as deletable for now.
Closes #4848

Make paragraph templates deletable again

---

versions.cfg

We were previously on `4.4.4`.
Rationales / changes:
* We can now do this as we're not running anything in a way which depends on clean layer teardowns
* /cc @jone
* We still cannot do sequential runs of the full stack or certain modules
* `4.4.5` sorts sequential runs to reuse layer setups better, which flares this up further
* `4.4.8` improves the use of multiple test filters - knocks a full minute of wallclock time off all `bin/mtest` runs
* `4.4.9` parallelises `bin/test -j` runs starting from the first layer by introducing an implicit `.EmptyLayer` to run first
* `4.5.0` using `-x` will actually stop the whole test run when the first error is encountered, instead of just stopping the current layer
* `4.8.0` and `4.8.1` bleed through more categories of deprecation warnings, which can …

Bump zope.testrunner to 4.8.1.

---

bin/mtest

The meeting layer tests do not stick out runtime-wise like a sore thumb anymore thanks to @deiferni, so we can stop splitting them within-layer and not duplicate the layer setup in mtest.

Unsplit the meeting layer in mtest

---

docs/HISTORY.txt
opengever/dossier/templatefolder/templatefolder.py
opengever/dossier/tests/test_templatefolder.py

This works for the action, as well for the API
Closes #4905 
Backport to: `2018.4-stable`

Only allow adding meeting templates, when meeting feature is enabled.

---

opengever/meeting/tests/test_meeting_template.py

My bad, must have misread the test having been green when merging https://github.com/4teamwork/opengever.core/pull/4912

Enable the meeting feature for meeting template tests

---

README.rst
opengever/api/tests/test_mail.py
opengever/api/tests/test_serializer.py
opengever/base/tests/test_contentlisting.py
opengever/base/tests/test_copy_paste.py
opengever/base/tests/test_default_values_for_types.py
opengever/base/tests/test_object_touched_handling.py
opengever/base/tests/test_object_touched_triggering.py
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/bumblebee/tests/test_overlay_view.py
opengever/mail/tests/test_mail_previewtab.py
opengever/meeting/tests/test_proposal.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Ended up here from https://github.com/4teamwork/opengever.core/pull/4829
* Make everything use explicit `self.mail_eml`
* Add a test for preventing object double registrations
Closes https://github.com/4teamwork/opengever.core/issues/4911

Prevent double registrations in the fixtures

---

opengever/meeting/browser/protocol.py

Fix a querystring field separator in docx merging

---

docs/HISTORY.txt
solr-conf/solrconfig.xml

Makes sure that the metadata of a document gets indexed if an error occurs
during text extraction with Tika, e.g. because of an encrypted document.
It seems that the behavior has changed in newer Solr versions. With previous versions the metadata got indexed even though a Tika exception occured. With Solr 7.3.1 the document gets not indexed at all if Tika exception aren't ignored.

Ignore Tika exceptions during indexing in Solr

---

opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/opengever.base.pot
opengever/base/locales/plone.pot
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po

according to the feedback in https://extranet.4teamwork.ch/support/ph-vs/tracker/513.
Backport to 2018.4-stable

Fix some french translations

---

docs/HISTORY.txt
opengever/document/browser/versions_tab.py
opengever/document/tests/test_versions_tab.py
opengever/tabbedview/helper.py

Since 2017.6 (PR #3467) the initial version of a document is only created when really used. Which leads to a not working bumblebee overlay link, when the initial version does not exist yet. Closes #4917
I add a special handling to the `InitialVersionDataProxy`, which uses the working copy to fetch the document.
Backport to `2018.4.-stable`

 Fix bumblebee overlay link for not yet created initial version.

---

docs/HISTORY.txt
opengever/meeting/tests/test_toc.py
opengever/meeting/toc/alphabetical.py

We do not want paragraphs (intertitles) included in the table of contents (alphabetical or repository based).
I also updated the tests to make sure the intertitles are excluded from the tocs.
resolves #4907 
Sidenote: `description` of the agendaitems is not in the generated json, but as @deiferni pointed out, there is probably no one out there who wants the descriptions in the Toc. So I left it as is for now.

Do not include paragraphs in AlphabeticalToc.

---

setup.py

This was done already but has been lost due to a bugfix release made from `master` afterwards.

Set setup.py version to 2018.5.0.dev0.

---

docs/HISTORY.txt
opengever/activity/base.py
opengever/activity/browser/settings.py
opengever/activity/center.py
opengever/activity/hooks.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/roles.py
opengever/core/upgrades/20181001113227_change_task_reminder_notification_setting_role/upgrade.py
opengever/globalindex/model/reminder_settings.py
opengever/task/activities.py
opengever/task/reminder/reminder.py
opengever/task/tests/test_activities.py
opengever/task/tests/test_reminder.py

Dieser PR implementiert das Objekt `TaskReminder`.
Das Objekt ist verantwortlich für alles, was mit Reminders gemacht wird.
Das ist:
- Hinzufügen eines Reminders für ein Objekt
- Entfernen eines Reminders für ein Objekt
- Aktuellen Reminder für das Ploneobjekt abholen
- Aktuellen Reminder für das SQL Objekt abholen
- Activities und Notifications für Objekte erstellen
- remind_day von allen gesetzten Reminders eines Objektes aktualisieren
issuer: #4205 
based on: https://github.com/4teamwork/opengever.core/pull/4620

Add TaskReminder to handle reminders in annotations and sql.

---

opengever/task/browser/assign.py
opengever/task/response_syncer/workflow.py
opengever/task/tests/test_assign.py
opengever/task/tests/test_response_syncer.py

Dieser PR entfernt die gesetzte Erinnerung für den alten Verantwortlichen nach dem `neu zuweisen`.
issuer: #4205

Remove reminder for old responsible

---

docs/intern/operations/allgemein.rst
opengever/task/browser/assign.py
opengever/task/deadline_modifier.py
opengever/task/reminder/__init__.py
opengever/task/reminder/cronjobs.py
opengever/task/reminder/reminder.py
opengever/task/response_syncer/workflow.py
setup.py

Dieser PR fügt den zopectrl-Befehl `generate_remind_notifications` hinzu zum Erstellen der Erinnerungen über einen Cronjob.
issuer: #4205

Add cronjob script

---

docs/HISTORY.txt
opengever/meeting/browser/committeetabs.py
opengever/meeting/tabs/membershiplisting.py
opengever/meeting/tests/test_membershiplisting.py

* Added filter for displaying only active memberships in the listing
* Added tests for the membership listing
* Clean up `Memberships` class
for the cleanup, I moved some code from `Memberships` to the parent class `MembershipListingTab`. This is more consistent with how the other ListingTabs are defined. I also removed some superfluous code:
```
enabled_actions = []
major_actions = []
```
are the defaults in `BaseListingTab`, so can be removed.  `get_member_link` was defined twice, but the definition in `MembershipListingTab` seemed to be unused.
resolves #4244

Add filters (active and all) to membership listing.

---

docs/HISTORY.txt
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/reminder.rst
opengever/api/configure.zcml
opengever/api/reminder.py
opengever/api/tests/test_reminder.py

Dieser PR fügt die Task-Reminder Endpoints zu hinzufügen und löschen von Task-Reminders hinzu: `@reminder`.
Issuer: #4205 
Based on: #4736

Task-Reminder Restapi-Endpoints to add and delete reminders

---

docs/HISTORY.txt
opengever/task/activities.py
opengever/task/tests/test_reminder.py

Reminder-Benachrichtigungen werden nicht mehr erstellt, wenn eine Aufgabe erledigt ist.
Issuer: #4205 
Based on: #4930

No reminder if task is finished

---

docs/HISTORY.txt
opengever/task/__init__.py
opengever/task/tests/test_localroles.py

The transition from in-progress to closed, was not handled when introduced the role revoking on task finish (see #4656).

Revoke temporary roles also when closing direct-execution tasks.

---

docs/HISTORY.txt
opengever/document/base.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/configure.zcml
opengever/meeting/handlers.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/query.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_excerpt.py
opengever/trash/browser/trash.py
opengever/trash/locales/de/LC_MESSAGES/opengever.trash.po
opengever/trash/locales/fr/LC_MESSAGES/opengever.trash.po
opengever/trash/locales/opengever.trash.pot
opengever/trash/remover.py
opengever/trash/trash.py

Trashing and/or removing protocol excerpts was not handled properly. Here we add the following features:
* Hide trashed excerpts from the meeting view
* when an excerpt is removed from trash, cleanup relations to proposal/agendaitem:
* If the excerpt is from an ad-hoc agendaitem, remove its relation to the agendaitem from the sql database
* If the excerpt is from an agendaitem with a proposal, remove the relation from the submitted proposal
* Forbid to trash an excerpt if it has been returned to the proposal.
resolves #4486

Trash/remove Protocol Excerpts

---

docs/HISTORY.txt
opengever/document/browser/actionbuttons.py
opengever/document/browser/templates/macros.pt
opengever/document/document.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/static/officeconnector.js
opengever/oneoffixx/tests/test_oneoffixx.py

Split off from https://github.com/4teamwork/opengever.core/pull/4282
In case anything goes wrong, this is enabling us to let users retry, and for development and trying things out, this is undispensable.

Allow users to retry creating a file from a Oneoffixx template

---

opengever/base/tests/test_get_setting_view.py

When playing around with how to build the per instance configurability of Oneoffixx, I ended up noticing a fetch collision for the API endpoints for feature flags and settings. Asserting on no collisions sidesteps the issue.

Test no settings or features share a name

---

docs/HISTORY.txt
opengever/base/helper.py
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/meeting/browser/meetings/meeting.py

The `TableRadioWidget` automatically adds the NullObject if the field is not required. A label is added for this element in the default columns, but for custom columns this element will not have a title. We add a helper that can be used as transform to handle this in a custom title column.
It seems likely that we will have the same issue in other `TableRadioWidget`. So I put the transform in `opengever.base` with a generic translation for the Null label.
resolves #4849

Display title for NullObject in meeting template selection.

---

docs/HISTORY.txt
plonetheme/teamraum/resources/rules.xml

The favorite-action is rendered by the below-content-title viewlet, but we actually want it on the same line as the title. This viewlet is rendered as a block in the default template, below the title. We use diazo here to move it outside of that viewlet and just after the document title.
This seems to fix the problem in all the mentioned cases:
**Dossier "view metadata"**
**Paragraph template view**
And it did not break any of the other views, for example:
**Normal document with title spannign more than one line**
resolves #4747

Move the favorite action just after the documentFirstHeading.

---

opengever/tabbedview/tests/test_sqlsource.py

This gets us some 300 tests further along a sequential test run.

Do not leak setting the sql dialect to Oracle in the Memory DB layer

---

docs/HISTORY.txt
opengever/api/dossier.py
opengever/api/tests/test_serializer.py

Instead of user identifier, we return the fullname of the dossier responsible in a REST API dossier GET.
We could also return the label with principal: `fullname  (identifier)`
resolves #4820

return fullname of responsible in dossier GET.

---

README.rst
docs/HISTORY.txt
opengever/base/browser/pasting_allowed.py
opengever/base/monkey/patches/paste_permission.py
opengever/base/tests/test_copy_paste.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/dossier/tests/test_templatefolder.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt
opengever/sharing/tests/test_blocked_local_roles_listing.py
opengever/tabbedview/tests/test_dossier_listing.py
opengever/tabbedview/tests/test_personaloverview.py
opengever/testing/fixtures.py

* Amend the fixtures to have suitable data types
* Prevent pasting without `Copy or Move` on the target container as otherwise the freshly created object cannot be renamed
Closes #4589

Prevent pasting without `Copy or Move` on the target container

---

docs/HISTORY.txt
opengever/bundle/sections/fileloader.py
opengever/bundle/tests/assets/basic.oggbundle/documents.json
opengever/bundle/tests/test_bundle_loader.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/bundle/tests/test_section_bundlesource.py
opengever/bundle/tests/test_section_fileloader.py

This fixes an `UnicodeDecodeError` with UNC filepaths containing non-ASCII characters that wasn't previously covered by tests.
Fixes #4670

OGGBundle: Fix encoding issue with UNC filepaths containing non-ASCII characters

---

docs/HISTORY.txt
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

The sharing view's `update_inheritance` contains a fallback wich re adds the current local roles, if the current user would lock him out. Those currently did not used the RoleAssignmentManager and therefore raised a `ValueError`. It now uses the `RoleAssignmentManager` which closes #4963
Additionally we decided to skip the `inheritance fallback` for administrators and managers, because the access for those users is ensured by the global roles. So we can avoid local_roles assigned to a specific users, which we say should not be used usually.

Fix sharing form local_roles inheritance fallback.

---

docs/HISTORY.txt
opengever/examplecontent/configure.zcml

The `geveradmin` user is member of the `gever_admins` groups, so we now have at least one Administrator in the example content users.
resolves #4387

Map gever_admins to the administrator_group in example content.

---

docs/HISTORY.txt
opengever/api/tests/test_repository.py
opengever/repository/reference.py

Huh, this adapter has been broken since August 2010 as far as I can tell?
https://github.com/4teamwork/opengever.core/blame/dd62ab3f037fff23feb25ebb933a404012c64661/opengever/repository/reference.py#L18
Closes #4967

Fix a typo in the code of repository root reference number adapter

---

docs/HISTORY.txt
opengever/base/browser/pasting_allowed.py
opengever/base/tests/test_pasting_allowed.py

Fixture setup failures took me down a few wrong paths, but this was rather simple in the end.
We already had filtering of what can be pasted into a template folder.
https://github.com/4teamwork/opengever.core/blob/810674f4186126b85d4d1e8d32d7d91ee4841aae/opengever/dossier/templatefolder/templatefolder.py#L41-L56
So we just needed to allow pasting into a template folder.
Closes #4776

Allow pasting documents and templates into a template folder

---

docs/HISTORY.txt
opengever/base/role_assignments.py
opengever/sharing/browser/resources/sharing.js
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

- **Fix removal of all role assignments**: Currently the removal of all local roleassignments has been skipped by mistake in the sharing endpoint. We fix that, by making sure that all
RoleAssignments are cleared, when no assignments exists.
- Do not show search results multiple times.

Sharing form fixes

---

opengever/base/tests/test_utils.py
opengever/tasktemplates/tests/test_functional_helper.py

Addressed the few deprecation warnings in our `UnitTests` layer to make the early test run cleaner.

Fix zope.testrunner.layer.UnitTests deprecation warnings

---

docs/HISTORY.txt
opengever/activity/dispatcher.py
opengever/task/activities.py
opengever/task/tests/test_reminder.py

The default dispatcher implementation requires watchers to run the dispatch-section. We don't have watchers for taskreminders (no one is watching a resource for a reminder, the activity and it's notifications are generated directly through a script), but the[ dispatcher requires it](https://github.com/4teamwork/opengever.core/blob/master/opengever/activity/dispatcher.py#L55).
That's why we dispatch the required notifications directly within the TaskReminderActivity.
fixes: #4984

Fix dispatching notifications while recording a TaskReminderActivity.

---

docs/HISTORY.txt
opengever/task/response.py

Before:
-------
After:
-------
fixes: #4983

Prefill task-reminder select field on task response form.

---

opengever/api/configure.zcml
opengever/api/listing.py
opengever/api/summary.py
opengever/api/tests/test_listing.py
opengever/base/contentlisting.py
opengever/base/helpers.py
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/uuidindex.py

The listing endpoint currently supports two "modes" a `dossier` and a `document` listing, and knows the following parameters:
- `name`: mode  (`dossier` or `document`)
- `start`: starting point for the listing
- `rows`: number of items wich should be returned
- `sort_on`: sort index, default sorting is modified
- `sort_order`:  ascending or descending, default is descending
- `search`: filter text
- `columns`: list of columns which should be returned. Currently supported are ['reference', 'creator', 'containing_dossier', 'document_date', 'receipt_date', 'end', 'title', 'document_author', 'responsible', 'filename', 'start', 'filesize', 'review_state', 'type', 'thumbnail', 'description', 'checked_out', 'mimetype', 'reference_number', 'created', 'containing_subdossier', 'modified', …

Add @listing API endpoint 

---

docs/HISTORY.txt
opengever/bumblebee/__init__.py
opengever/dossier/tests/test_templatefolder.py

I'm still a bit surprised that the tooltip would show the link for the preview, with attributes pointing to the bumblebee data, for content that is not bumblebeeable. Showroom does not find that information as it looks in the listing tab, for a hidden link with the `showroom-item` attribute...
resolves #4826

Fix bug with document preview for sablon and proposal templates.

---

docs/HISTORY.txt
opengever/activity/browser/configure.zcml
opengever/activity/browser/notification_mail_macros.py
opengever/activity/browser/templates/notification_mail_macros.pt
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/mail.py
opengever/activity/templates/digest.pt
opengever/activity/templates/notification.pt
opengever/activity/tests/test_digest.py
opengever/activity/tests/test_mail.py

Dieser PR verwendet für die Standard-Benachrichtigung per E-Mail das selbe Template wie für die Tageszusammenfassung.
Tageszusammenfassung:
--------------------------
Standard-Benachrichtigung vorher:
--------------------------
Standard-Benachrichtigung nachher:
--------------------------
fixes #4523

Use the same template for default notifiaction email like the daily-digest template.

---

docs/HISTORY.txt
opengever/base/browser/resources/tooltip.js

Closes https://github.com/4teamwork/opengever.core/issues/4809
On one hand the mouseover event somehow breaks the click event on touch devices such as the iPad.
On the other hand a mouseover event is not possible on touch devices anyway. So just initialize the qtip tooltips on non touch devices.

Remove document tooltip on touch devices

---

docs/HISTORY.txt
opengever/ogds/base/browser/team_forms.py
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

Dieser PR lässt den Benutzer beim Hinzufügen eines Teams nur noch Orgunits der aktuellen AdminUnit auswählen.
Zudem wird eine neue Vocabulary-Source für die Gruppen verwendet. Neu werden die Black-White-List prefixes welche im ISharingConfiguration konfiguriert werden bei der Gruppenauswahl miteinbezogen.

Adjust team queries

---

plonetheme/teamraum/testing.py
plonetheme/teamraum/tests/test_customstyles.py
plonetheme/teamraum/tests/test_logo.py
plonetheme/teamraum/tests/test_personal_bar.py
plonetheme/teamraum/tests/test_responsive_tinymce.py
plonetheme/teamraum/tests/test_searchbox.py

Reduces the unnecessary background noise in our tests by a lot.
Closes #4725

Actually port plonetheme.teamraum tests to opengever.core testing

---

docs/HISTORY.txt
opengever/meeting/browser/sablontemplate.py
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_agendaitem_list.py
opengever/meeting/tests/test_unit_agenda_item.py

The description is passed on to sablon which no longer treats the input as html which needs to be converted to word. So html-escapes will be treated literally which is wrong.
Fixes #5012.

Don't html-escape description for JSON data.

---

opengever/core/upgrade.py
opengever/setup/deploy.py

This suppresses an sqlalchemy deprecation warning. I've set up new gever (with the purge sql option enabled) to test it works. All code paths that are modified are taken when setting up a new gever with `@@gever-add-deployment`.

Use MetaData.reflect instead of reflect parmeter.

---

docs/HISTORY.txt
opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py
opengever/advancedsearch/tests/test_livesearch_reply.py
opengever/base/browser/livesearch.py

Fix it for solr and for the skins folder livesearch. The title was not escaped at all which lead to markup not being rendered correctly in some cases.
Fixes https://github.com/4teamwork/opengever.core/issues/5016.

Fix rendering issue in livesearch reply view.

---

docs/HISTORY.txt
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20181031131112_define_modernizr_js_position/jsregistry.xml
opengever/core/upgrades/20181031131112_define_modernizr_js_position/upgrade.py

Register modernizr.js as one of the top JS.
Fixes the current js-issue on dev.onegovgever.ch.

Fix JS ordering issue: define modernizr.js position.

---

docs/HISTORY.txt
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/zipexport.py

For certain special characters normalization for the actual file names and for the JSON-file with metadata were different. We make sure to use the same normalization in all cases.
Fixes #5023.

Fix normalizing filename for zip export.

---

docs/public/admin-manual/meeting/mergefields.rst

Remove wrong divider symbols in the mergefields docu.

---

docs/HISTORY.txt
opengever/base/browser/resources/generateToc.js
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/agendaitem_list.py
opengever/meeting/browser/protocol.py
opengever/meeting/browser/resources/meeting.js
opengever/meeting/browser/sablontemplate.py
opengever/meeting/browser/toc.py
opengever/meeting/command.py
opengever/meeting/exceptions.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/meeting.py
opengever/meeting/sablon.py
opengever/meeting/sablontemplate.py
opengever/meeting/tests/test_toc.py

We introduce a custom exception to handle failures when processing sablon templates.
Some of the sablons are requests issued from JavaScript, which are handled separately.
* We add a custom exception `SablonProcessingFailed` raised when processing fails. This exception adds an error message and reloads the page.
* For requests from JavaScript:
* For agendaitems, we return the error in the JSON response
* For TOC download, the response is not JSON, but an `arraybuffer`. We therefore cannot use the machinery of the `Controller` to handle the error. Instead we simply add an error message in Plone and then reload the page in JavaScript.
* Error handling of the TOC download was already present in the case of missing template, but it was broken. I fixed it as described above.
Here are snapshots …

Custom Sablon Exceptions

---

docs/HISTORY.txt
opengever/core/upgrades/20181022104232_reindex_task_principals_in_globalindex/upgrade.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_query.py
opengever/tabbedview/tests/test_personaloverview.py
opengever/task/task.py
opengever/task/tests/test_principals.py
opengever/testing/integration_test_case.py

With the `TaskPrincipals` we already sync principals allowed to see a Task in to the globalindex. But currently the task queries has not been restricted and therefore a task was always visible, for all accessors of a Dossier and for inbox-users all tasks of a current admin_unit has been visible.
With "OGIP 46 - personal task", we now introduced a possibility to disable the `inbox-user` agency permission and have to restrict the task listings etc. I decided to restrict all TaskQueries, which also solves an [Issue](https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/365) wich allowed including tasks in to pdf_task_listing, where the user was not allowed to access.
During implementation I've also realized that the current implementation of the principals getter was wrong and did …

Restrict TaskQueries according to the task principals.

---

docs/HISTORY.txt
opengever/base/browser/search.pt
opengever/base/browser/search.py
opengever/base/tests/test_search.py

This PR fixes a rendering issue in search view. We fix it for SOLR and for the skins folder search results. The description was inserted as structure which would not render correctly due to missing escaping for catalog results.
SOLR search is configured by the view to return markup with highlighting using `<em>` tags. SOLR is now also configured to already escape its results before inserting those `<em>` tags so that the returned description can be safely inserted in the template using a `tal:structure`. 
For catalog results the view now escapes the description before it is being rendered in the template.
Fixes https://github.com/4teamwork/opengever.ftw/issues/77 https://github.com/4teamwork/opengever.core/issues/5017

Fix rendering issue in search view.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/meetingtemplate.py
opengever/meeting/vocabulary.py

When creating meetings from a template the template content object was stored in the wizard storage. This causes issues as the object retrieved from storage can loose its acquisition context. We switch to only storing the objects UID and then retrieving the object again when it is needed.
Fixes #5031 
The existing test in https://github.com/4teamwork/opengever.core/blob/253524907bcaed57e2b5c46d74b972f8c775dbaa/opengever/meeting/tests/test_meeting_template.py#L66-L123 still works, no need for further testing IMO.

 Fix acquisition issue with meeting templates.

---

docs/HISTORY.txt
opengever/base/touched.py

Drop verbose logging for `ObjectTouched` events. Logging was initially added to aid debugging of potential issues with the "recently touched" feature, but it turns out to be too verbose and leads to spam in the instance logs.

Drop verbose logging for ObjectTouched events.

---

opengever/api/dossier.py
opengever/api/listing.py
opengever/api/livesearch.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_serializer.py
opengever/base/contentlisting.py
opengever/base/helpers.py
opengever/base/tests/test_contentlisting.py

- Handle items without review_state in listings
- Keep value of responsible field in GET and return responsible's fullname as it's own property
- Return responsible and checked_out fullnames separately in listings
- Strip VHM path from path in livesearch
- Include PDF preview URL in listings

Various REST API fixes

---

docs/HISTORY.txt
opengever/core/profiles/default/catalog.xml
opengever/core/upgrades/20181101150743_add_document_filesize__filename_and_file_extension_to_document_metadata/catalog.xml
opengever/core/upgrades/20181101150743_add_document_filesize__filename_and_file_extension_to_document_metadata/upgrade.py
opengever/document/behaviors/metadata.py
opengever/document/config.py
opengever/document/configure.zcml
opengever/document/indexers.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_indexers.py

Did I get the addition of yet-unused metadata bit right here?
The translations on the schema items also probably need some love.
I'm also assuming we want to craft the deferrable upgrade step for rolling out this and the new `changed` timesteamp sometime later when the dust has settled on both.
Closes #4966

Add file related metadata and indices, without yet actually using them

---

docs/HISTORY.txt
opengever/task/browser/related_documents.py
opengever/task/tests/test_related_documents_tab.py

This was simply missed upon initial implementation.
Closes #5006

Fix Officeconnector permission checks for task documents tab actions

---

docs/HISTORY.txt
opengever/api/configure.zcml
opengever/api/document.py
opengever/api/dossier.py
opengever/api/listing.py
opengever/api/repositoryfolder.py
opengever/api/serializer.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_serializer.py

This PR provides the bumblebee-checksum in the `@listing` restapi endpoint and for serialized IBumblebeeable objects.
fixes #5009

Include bumblebee checksum to restapi calls

---

docs/HISTORY.txt
opengever/repository/browser/excel_export.py

Fetching the correct reference number adapter and sorting with the sorter from there.
Building a test case where the catalog query result would be guaranteedly out of order or a weird reference formatter just for the tests would be a bit excessive.
Closes #5061

Sort repository excel exports by reference number

---

docs/HISTORY.txt
opengever/ogds/base/browser/templates/teamdetails.pt
opengever/ogds/base/tests/test_team_details.py

Using `label` we will display the `groupid` if the group does not have a `title`, instead of having an empty field.
resolves #5054

Display group label in teamdetails instead of group title.

---

docs/HISTORY.txt
opengever/core/upgrades/20181109105732_ensure_all_fields_of_e_ch_0147_imported_objects_are_properly_typed/upgrade.py
opengever/dossier/handlers.py
opengever/ech0147/serializer.py
opengever/ech0147/tests/test_import.py
opengever/ech0147/utils.py

Made a custom JSON (de)serializer for eCH-0147  imports as we feed these to the `plone.restapi` JSON deserializer. This way everything is guaranteedly just a string unless it's whitelisted as a date field and we can easily amend any future additions to the field types.
There are also tests for importing data via eCH-0147 and a deferrable upgrade step for going through all of the fields on all of the schemata on all of the non-bundle-imported objects for PyXB data types and casting the strings, ints, booleans, dates and datetimes thereof into their appropriate field types.
Closes #4376

Sanitize eCH-0147 imports via a JSON cycle

---

docs/HISTORY.txt
opengever/meeting/model/agendaitem.py

This will not happen in the long run, but agendaitems that were decided before we introduced that proposals get decided only when the excerpt is returned can be already decided even if the proposal has not been returned. This lead to an error when returning the excerpt and trying to decided an already decided proposal.
We fix this by only closing the proposal if it has not been closed already.
**returning the excerpt of a closed agendaitem could lead to an error**
**With the fix, we can return the excerpt without trying to close the proposal a second time**
resolves #5055

Fix issue when returning an excerpt to an already decided proposal.

---

docs/HISTORY.txt
opengever/latex/dossiertasks.py
opengever/latex/templates/dossiertasks.tex
opengever/latex/tests/test_dossiertasks.py

* Make sure that the text passed is an empty string and not "None", as this gets displayed as such in the PDF. 
* Fix the label shown for the task issuer and task responsible.
It seems I got really confused with what `Auftraggeber` and `Auftragnehmer` were. Sorry about that!
I think we do not need to handle the case of `None` for the other fields as they are all mandatory.
**Here a snapshot of the PDF. The task has no description, myself as issuer and Lukas as responsible**
resolves #5065

Fix data in Task PDF when resolving a dossier.

---

docs/HISTORY.txt
opengever/document/forms.py

By adding the context class to the button we can re-use existing css.
Fixes #5069.

Make save as pdf button colored green.

---

docs/HISTORY.txt
opengever/activity/browser/resources/settings.js
opengever/activity/browser/settings.py
opengever/activity/browser/templates/settings.pt

Conditionally show proposal notification settings.
The settings should only be visible when the meeting feature is enabled. If the feature is disabled the tab is omitted from the form as follows:
The changes in this PR lead to the tab order changing slightly. The proposals tab will move by one tab, to the right of the notifications tab. I did not address this issue as i do not expect this to be a breaking change for our users (the form is most certainly not used on a daily basis).
Fixes #5066.
_The form is rendered in javascript only, so unfortunately i cannot test this automatically._

Conditionally show proposal notification settings.

---

docs/HISTORY.txt
opengever/core/upgrades/20181109105732_ensure_all_fields_of_e_ch_0147_imported_objects_are_properly_typed/upgrade.py
opengever/dossier/handlers.py
opengever/ech0147/serializer.py
opengever/ech0147/tests/test_import.py
opengever/ech0147/utils.py

Round two:
* Ensure `temporary_former_reference_number` is unicode
* Sanitize the eCH-0147 imports via a json cycle
* Add an upgrade step to sanitize all existing data
Closes #4376

Sanitize eCH-0147 imported documents and dossiers

---

docs/HISTORY.txt
opengever/document/behaviors/related_docs.py
opengever/document/tests/test_forms.py
opengever/meeting/browser/proposalforms.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py
opengever/task/task.py
opengever/task/tests/test_forms.py
opengever/tasktemplates/browser/trigger.py
opengever/tasktemplates/tests/test_trigger.py

As we use a new enough `ZCatalog`, we can append a not query of the `review_state` to the path queries.
Put this PR to 2018.5 milestone as this is essentially an Oneoffixx thing.
Closes #3385

Exclude shadow documents from being relatable

---

docs/HISTORY.txt
opengever/bumblebee/browser/callback.py
opengever/bumblebee/tests/test_callback.py
opengever/document/browser/save_pdf_document_under.py
opengever/document/tests/test_save_pdf_under.py

After discussing with @jone and @deiferni, we should use the `opaque_id` of `bumblebee` instead of a get parameter for the verification token in the `SavePDFUnder` views.

Use opaque_id instead of get parameter in SavePDFDocumentUnder.

---

opengever/core/testing.py

If we want to preserve unique testrunner matchability for our main integration test layers, do we do it this way, or do we rename the bulk one as `integration:base` or equivalent?

Rename the theme integration test layer to preserve unique matchability

---

opengever/bumblebee/browser/callback.py
opengever/bumblebee/tests/test_callback.py
opengever/document/browser/save_pdf_document_under.py
opengever/document/tests/test_save_pdf_under.py

The ReceiveDocumentPDF callback view is called from bumblebee hence by an anonymous user. Because of that the preview is not generated by bumblebee as the anonymous user does not have view permissions on the document.

Login as document owner in the ReceiveDocumentPDF callback.

---

opengever/base/role_assignments.py
opengever/task/tests/test_localroles.py

The performance improvement recently introduced by #5079, had a bug on
revoking roles on distinct parent. I've fixed it and improved the
according test.
Needs backport

Fix revoke local roles performance improvement

---

docs/HISTORY.txt
opengever/base/browser/templates/macros.pt

Because the status message is defined in a `metal` macro, it seems that we need to pass the translation domain in each translated tag.
This led to message type not being translated in various forms, notably when adding a document from a template, but also when adding a proposal, a task, and probably any add form in which an error could be raised.
**Before the status message type was not translated**
**Now the translation works correctly, shown here for adding a document from a template, or adding a proposal**
resolves #5064

Translate status message type in forms.

---

opengever/examplecontent/meeting.py

A committee always requires a period, we seem to have omitted that for the evil committee sample content.
Fixes #5094.

Add period to evil committee.

---

docs/HISTORY.txt
opengever/dossier/resolve.py

This should have a positive performance impact when resolving a subdossier as we will not have to check whether all tasks and documents are in a subdossier (`and` condition will evaluate from left to right until it hits its first `False`).

Reorder conditions in dossier resolve.

---

docs/HISTORY.txt
opengever/base/browser/resources/base.js

but only focus instead. 
The fix (#3837) for the send document form still works but also closes #5067.

Do not open keywordwidget when autofocusing the first form field,

---

opengever/latex/dossiertasks.py
opengever/latex/listing.py
opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/opengever.latex.pot
opengever/latex/templates/listing.pt
opengever/latex/tests/test_dossiertasks.py

We improve the format of the task listing PDF:
* We add the possibility to set the text alignment in the `LaTexListing`. `Column`s now have a new `alignment` attribute.
* To avoid stretching of text and hyphenation, we set the first three columns (date, creator and transition) to left-aligned. The last column, `description`, is justified.
* For the creator we now show the full label (full name and userid)
* In the title of the document, we quote the dossier title.
**Old formatting**
**New formatting**
This should not change the formatting of other listings, as we use `justified` as default, which seems to be the default when no alignment is specified. The generated latex probably depends on the browser used though, as we go through HTML, and then from HTML to Latex.

Improve task listing formatting.

---

opengever/base/browser/resources/task_reminder_selector.js

Reorganised around
* Only fires after we know we have a tabbedview
* Only fires after we know the reminder selector is there
Closes #5109

Fix the task reminder Vue app to also work without the reminder element in the markup

---

opengever/base/browser/resources/tooltip.js

This reverts commit cb637206b1ed6b8c1ef266ba91e958fdd335c1cd.
The with #5000 introduced solution, leads to problem on hybrid machines (touchable desktops), where the tooltip is now newer showed up on such machines. In my opinion it's more important that the `tooltip` works on hybrids, than the tabled use case is solved. 
I'll reopen the Issue #4809, so we can look for an other solution ...

Revert "Merge pull request #5000" 

---

docs/HISTORY.txt
opengever/latex/layouts/resources/default_layout.tex

This change allows latex to distribute 3em more of white space on a line when it cannot split it in a satisfying way, this is notably useful as titles often contain long numbers.
According to my tests the current setting should always work for numbers up to 10 digits. For longer numbers we can lines that extend over the margin or sheet. I feel like that is pretty reasonable, though we could obviously crank that up to some larger value, but then there is the risk of obtaining lines typeset with a lot of space.
Another possibility would be to redefine the titles to be `raggedright`, in the case of a section title as in the issue (#5123 ):
```
\titleformat*{\section}{\bf\Large\filright}
```
I think the generic solution should do though.
resolves #5123

Set \emergencystretch to 3em in latex templates.

---

docs/HISTORY.txt
opengever/activity/browser/views.py
opengever/activity/tests/test_views.py
opengever/activity/viewlets/notification.pt

In the same manner we do that for for all switching admin_unit links (tasks etc.) we open notification links for foreign resources in the notification viewlet in a new tab/window.

Open notifications for resources on a foreign admin_unit in a new tab/window.

---

opengever/base/browser/resources/task_reminder_selector.js

`finally` on axios requests, is not fully supported in some browser, therefore i moved the finally
part in to a separate method which is called by `then` and `catch`.

Fix task reminder selector dropdown for MS Edge.

---

README.rst
versions.cfg

We want to define a specific SOLR version, which is tested and should be used for each specific GEVER versions. So I moved the definition in to the versions.cfg. 
It's still possible to change to solr version for a specific deployment, but it's no longer necessary to define the version in each buildout.

 Define solr version in versions.cfg

---

docs/HISTORY.txt
opengever/activity/__init__.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/latex/dossierjournal.py
opengever/latex/dossiertasks.py
opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/opengever.latex.pot
opengever/latex/tests/test_dossierjournal.py
opengever/latex/tests/test_dossiertasks.py

* For both the dossier task PDF and the dossier journal PDF, only the listings were processed by the `ftw.pdfgenerator.html2latex.converter.HTML2LatexConverter`, the other rendered arguments, such as the title of the generated file, were not being processed. This could lead to issues, notably with quotes (Latex uses special opening and closing quotes). This is now corrected.
* I also adapted the title of the dossier journal, to match the one of the dossier task pdf, quoting the dossier title in the title of the PDF.
* There were missing translations for `transition-add-subtask` and `transition-add-document`
* I changed the dateformat for the `deadline` and `completion_date`, not displaying the time anymore, as these are `date` and not `datetime` fields.
**Before we dossier or task titles …

Fix dossier task and journal PDF latex conversion issues

---

docs/HISTORY.txt
opengever/core/upgrades/20181022104232_reindex_task_principals_in_globalindex/upgrade.py

Skip tasks where no representing sql task is stored in the globalindex. This situation should never happen and is something which should be visible in the validation scripts (https://github.com/4teamwork/opengever.maintenance/pull/149), but should not let the
upgrade fail.
So we skip and log a warning instead if a corresponding sql task is missing.

Make ReindexTaskPrincipalsInGlobalindex upgradestep more robust.

---

docs/HISTORY.txt
opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py
opengever/base/browser/livesearch.py
plonetheme/teamraum/resources/css/main.css

* We improve the livesearch result display. We now show one line of the title and one line of the description. Both are truncated if necessary and an ellipsis is added if they are truncated.
* Instead of truncating them in the python code, we now do this in css.
* There was also an issue with solr, where the description would not be displayed. This has now been fixed (we forgot to get the description field in the request to solr).
Here a snapshot on IE.

 Show one line of each of title and description in livesearch result

---

docs/HISTORY.txt
opengever/base/favorite.py
opengever/base/handlers.py
opengever/base/model/favorite.py
opengever/base/tests/test_favorite.py
opengever/base/tests/test_favorite_action.py
opengever/base/tests/test_favorite_menu.py

Favorites only supported objects with titles shorter than 255 characters. This led to errors when trying to edit the title of such an object, or setting it as favorite. We now truncate the title to 255 characters in the favorites.
We could have added a validator in the model to truncate the title automatically when creating or modifying an `opengever.base.model.favorite.Favorite` object. But this would lead to silently truncating the title when a user sets a personalised title. 
Note that there is now some inconsistency in the `FavoriteManager` as the `add` method truncates the title of the object in the favorite, whereas the `update` methods throws an error when the passed title is too long. For now I think this behavior is ok, when the user sets the title for one of his favorites and …

 Fix bug in favorites to support objects with long titles.

---

docs/HISTORY.txt
opengever/core/upgrades/20181101150743_add_document_filesize__filename_and_file_extension_to_document_metadata/upgrade.py
solr-conf/managed-schema

The change from PR #5024 only added catalog indexes, but did not add corresponding indexes to the solr schema. So the upgradestep was useless for deployments with an enabled solr search or even worse it almost removed all solr data because of a curios behave of solr or ftw.solr (I'll investigate this behavior in a separate issue).
So I added the new indexes to the schema and fix the current upgradestep.

Fix file indexes upgradestep for deployments using solr.

---

bin/mtest

Here's a batch of small to medium improvements and usability changes I'm backporting from my efforts of using an mtest variant in `buildout.coredev`.

Backport mtest improvements over from buildout.coredev experimentation

---

docs/HISTORY.txt
opengever/meeting/browser/proposalforms.py
opengever/meeting/tests/test_proposal.py

Simply using the new metadata field does the trick.
Closes #5082

Only display .docx files as possible proposal documents

---

docs/HISTORY.txt
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/localroles.py
opengever/task/response.py
opengever/task/tests/test_response.py

Avoid unauthorized raises, when current user loses the access rights on the dossier during task closing. The Unauthorized has been raised, because we revoked the permission and fetch the subdossiers afterwards, so the getObject on the brain raised the `Unauthorized`. I've fixed this by changing the order, first fetch all subdossiers and than revoke the permission on the main dossier.
Besides that I also implemented a fallback to the add response form, when the current users loses access rights. If that's the case we now redirect to the personal overview and show a corresponding statusmessage.
Backport needed: `2018.5`

Fix task revoking permissions on close/reassign

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/browser/resources/zip_export_app.js
opengever/meeting/tests/test_meeting_zipdemand.py
opengever/meeting/tests/test_meeting_zipexport_callback.py
opengever/meeting/zipexport.py

When callback requests arrive concurrently the they may not correctly see the amount of finished documents, so zip creation was not triggered all the time.
Thus we move triggering creating the zip file to the polling view. The polling view now uses `POST` as it will create content (the Zip).
The polling view should only be called once as the polling interval is quite long. It can also deal with two concurrent zip creations though and also does not create the zip again when a zip is already present.
Needs backport to `2018.5`.

Fix create zip for concurrent callback requests.

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/language.py
opengever/base/tests/test_language_negotiation.py

This extends request language negotiation in a way where we also support browsers sending **simple language codes** in their `Accept-Language` headers (even though we have `use_combined_language_codes` turned on).
We do this by using a hardcoded mapping from simple to combined language codes, which we know to be appropriate because of our customer base.
Fixes #5162

Add support for simple language codes in request language negotiation

---

docs/HISTORY.txt
opengever/base/utils.py
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/tests/test_overlay_view.py
opengever/document/browser/overview.py
opengever/document/tests/test_overview.py
opengever/mail/browser/mail.py
opengever/mail/tests/test_overview.py

Introduced a new row type for the document and mail overviews and used the transform in the Bumblebee overlay.
Closes #5063

Render documentish descriptions as intelligent text

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/handlers.py
opengever/base/tests/test_changed_date.py

This fixes an issue when copy & pasting a dossier containing documents. The reason is, that object which raises the CreatedEvent or CopiedEvent (inherits from the CreatedEvent) aren't acquisition wrapped. This can lead to several issues, as example the copy & paste bug. Closes #5182 
IMHO the ObjectAdded which is fired when the object is added to the context, is the right thing to initialize the changed date.
Needs backport to `2018.5`

Set changed date on ObjectAdded instead of ObjectCreatedEvent.

---

.gitignore

This directory gets created by Sphinx documentation builds, and may appear at any depth.
Fixes the underlying issue for the mess in #5188

gitignore: Make _build match recursively instead of just in the root directory.

---

docs/HISTORY.txt
opengever/base/handlers.py
opengever/core/upgrades/20181219103543_reindex_containing_dossier_or_subdossier_indices/upgrade.py
opengever/dossier/configure.zcml
opengever/dossier/handlers.py
opengever/dossier/indexers.py
opengever/dossier/tests/test_copy_dossier.py
opengever/dossier/tests/test_move_items.py

The `containing_dossier` and `containing_subdossier` indices were not updated when an object was copied or moved. As an `ObjectModifiedEvent` is fired for every object that is moved, i.e. when moving a container an event is fired for every contained object as well, we can simply handle this in an event registered for `IDexterityContent`.
We also move the reindexing of `is_subdossier` to this handler, to have everything at the same place.
The `containing_subdossier` index was updated when an object was modified, event when it's title was not changed, although `containing_dossier` was only updated when the title gets modified. We now update the indexes only when necessary.
This should fix the sorting issues on subdossiers, which seemed to stem from inconsistent data between the metadata and …

Correctly handle containing_dossier, containing_subdossier and is_subdossier indices.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/trash/locales/de/LC_MESSAGES/opengever.trash.po
opengever/trash/locales/fr/LC_MESSAGES/opengever.trash.po

There were some more instances of "zurücksenden" that got forgotten in https://github.com/4teamwork/opengever.core/pull/4768. We fix the remaining translations and also adapt the french translations to "deposer" instead of "classer" as it makes more sense in several of these phrases.
resolves #4332

Change remaining "zurücksenden" to "ablegen".

---

docs/HISTORY.txt

Just as a friendly reminder, the checklist would actually cover that step, too 🙄😝 https://github.com/4teamwork/opengever.core/wiki/Neuer-GEVER-Release.

Update CL after 2018.5.6 release.

---

README.rst
docs/HISTORY.txt
opengever/bundle/sections/constructor.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/disposition/ech0160/model/folder.py
opengever/disposition/tests/test_activities.py
opengever/disposition/tests/test_byline.py
opengever/disposition/tests/test_destruction.py
opengever/disposition/tests/test_disposition.py
opengever/disposition/tests/test_ech0160export.py
opengever/disposition/tests/test_excel_export.py
opengever/disposition/tests/test_history.py
opengever/disposition/tests/test_listing.py
opengever/disposition/tests/test_model.py
opengever/disposition/tests/test_overview.py
opengever/disposition/tests/test_removal_protocol.py
opengever/disposition/tests/test_sippackage.py
opengever/disposition/tests/test_views.py
opengever/disposition/tests/test_workflow.py
opengever/dossier/tests/test_indexer.py
opengever/testing/fixtures.py

* changes to the fixture:
* Added a new user `archivist` to the fixture
* Added 2 offered dossiers and a disposition to the fixture
* Add the clock as attribute of the fixture.
* Create plone user and ogds user with the same timestamp. Before we were moving the clock 2 minutes between these two, but this leads to necessitating 4 minutes per cerated user, which did not allow to add the `archivist` in the same hour as the other users. 
* Ported almost all disposition tests to the integration layer. 
* Fix bug in disposition ech0160 folder model. See below
Not all tests in `TestSIPPackage` could be ported, as we need documents in the disposition dossier, but these cannot be added properly in an integration test, as we never really write the blobs when in this isolation layer. Of course we …

Port disposition tests to integration layer

---

opengever/base/tests/test_reference_prefix.py

Did not realise there was a new integration test in `opengever.base` relying on the dossier count.
My bad.

Fix a new integration test which got merged after a fixture amend merge

---

opengever/base/tests/test_relations.py

the order in the relation catalog can't be controlled therefore we check for existence in all relations, instead of relying on on the order.
The test has been converted to integration tests recently and has been noticed as flaky since.

Fix flaky relation tests

---

docs/HISTORY.txt
opengever/base/browser/resources/tooltip.js

As documented in https://extranet.4teamwork.ch/support/stadt-nidau/tracker-gever/95 it may be possible that the documents overview page reloads when loading a tooltip of a document and the document detail view simultaneously.
So when user clicks on the document link in the overview while the browser awaits the response from the tooltip, the tooltip request is aborted. The javascript code checks the response of the tooltip request, which has been aborted, for a `X-Tooltip-Response` header. But because the request has been canceled the header is not present. As a result the javascript code triggers a reload of the documents overview page because it is treated as an error.
Using a flag setting to true when the user clicks on the documents links solved the problem. The flag is checked before …

Fix loading of document preview with tooltip

---

docs/HISTORY.txt
opengever/document/browser/configure.zcml

Not much else to say. I tested it locally with bumblebee to make sure the save_pdf_under still worked.
resolves #5134

Remove unused get_conversion_status view.

---

docs/HISTORY.txt
opengever/dossier/base.py
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

Invalid end dates for resolved dossiers can happen for several reasons, recently because of the switch from document_date to changed for the calculation of the earliest_possible_end_date. These are always due to software bugs and not user input and should hence be fixed automatically.
We need to be careful because open subdossiers with invalid end dates are due to user input and should still lead to an error message and let the user fix it himself. The approach implemented here works as follows:
* when checking the validity of subdossier end dates (in `ResolveConditions.check_end_dates`), we consider as invalid only dossiers that are not resolved and have an invalid end date. These will prevent dossier resolution and the user will receive an error message
* When resolving the dossier in …

Fix resolved subdossier invalid end dates when resolving main dossier.

---

docs/HISTORY.txt
opengever/document/handlers.py
opengever/document/tests/test_handlers.py

This changes the updating of DocProperties for `*.docx` documents in a way here it doesn't block **moving** or **checkin/checkout** of documents if the DocProperties update fails for some reason.
One reason this can happen is corrupted / invalid Word-Documents: These cause a `BadZipfile` exception that would otherwise kill the entire (possibly long running) move operation, or prevent this document from ever getting checked out again and fixed.
The behavior for **adding new documents** is still the same though - it will fail hard, and therefore prevent that broken documents even make it into GEVER. But for documents that are already in GEVER, we're being more defensive.
So, to summarize, this is how DocProperties update errors for the different document-related events will be handled now: …

Make sure a failure to update DocProperties doesn't prevent checkin/checkout or moving of documents

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/byline.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting_error.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_meeting_byline.py
opengever/meeting/tests/test_meeting_view.py
opengever/tabbedview/helper.py

We add a new view, which is displayed instead of the meeting view when a user has a permission mismatch between the `committee` and the `meeting_dossier`, as several elements of the meeting view are broken in that case. More specifically, when a user has `View` permission on the `committee` but not on the `meeting_dossier` or when a user has `Edit` permission on the `committee` but not on the `meeting_dossier`. The new view informs the user of the situation by displaying an error message (see screenshots below).
Note that I display a link to the `meeting_dossier` in these cases, which means that a user with no view permissions of the `meeting_dossier` will still see it's title and the link to the dossier.
**User has edit on the committee but not on the meeting_dossier**
**User has view on …

 Show error view when user has permission issues on a meeting.

---

docs/HISTORY.txt
opengever/base/tests/test_language_negotiation.py
opengever/core/locales/fr_ch/LC_MESSAGES/plonelocales.po

When localizing dates using `toLocalizedTime`, Plone determines the date format to be used by looking up the desired format ID (e.g. `date_format_short `) in a special translation domain called `plonelocales` in the user's currently negotiated language.
In stock Plone, a `plonelocales` definition only exists for `fr`, but not `fr-ch`. Therefore, for `fr-ch` it falls back to the French locale, which separates dates using slashes, which is incorrect for `French (Switzerland)`.
By supplying a `plonelocales` definition for `fr-ch`, we can control the date formats as needed.

Supply date format locale settings for fr-ch

---

docs/HISTORY.txt
opengever/oneoffixx/browser/form.py

The form previously mistakenly used the message factory from Dossier.
Closes #5244

Use the correct message factory in the Oneoffixx form

---

docs/HISTORY.txt
opengever/base/browser/resources/base.js

On a quick clickaround did not notice any legacy reason why choice fields were not included in the seek of which field to focus on as the first field of the form.
Closes #5245

Add choice fields as possible first form elements for the autofocus seek

---

docs/HISTORY.txt
docs/public/dev-manual/api/favorite.rst
opengever/api/tests/test_favorites.py
opengever/api/tests/test_repository_favorites.py
opengever/base/model/favorite.py

This adds a `portal_type` field to the items in the `@favorite` endpoint's responses. The field indicates the type of the target object referenced by the favorite.
A new response will look like this:
```json
[
{
"@id": "http://localhost:8080/fd/@favorites/peter.mueller/3",
"favorite_id": 3,
"icon_class": "icon-dokument_word",
"oguid": "fd:68398212",
"title": "Richtlinien Gesetzesentwürfe",
"portal_type": "opengever.document.document",
"position": 1,
"target_url": "http://localhost:8080/fd/resolve_oguid/fd:68398212"
}
,
{
"@id": "http://localhost:8080/fd/@favorites/peter.mueller/57",
"favorite_id": 57,
"icon_class": "contenttype-opengever-dossier-businesscasedossier",
"oguid": "fd:68336212",
"title": "Anfragen 2018",
"portal_type": "opengever.dossier.businesscasedossier",
"position": 2, …
```

Include portal_type in @favorites endpoint responses.

---

docs/HISTORY.txt
opengever/meeting/handlers.py
opengever/meeting/tests/test_sablon_template_validation.py

To allow to setup a development GEVER without a functional Sablon installation, we skip template validation during setup in development mode.
Note that after the setup of the example content, the sablon templates are marked as invalid. And without a working installation of sablon, sablon templates cannot be checked-in (they can be checked out).
Fixes #4852

Skip sablon template validation during setup of development system.

---

docs/HISTORY.txt
opengever/base/browser/configure.zcml
opengever/base/browser/list_groupmembers.py
opengever/base/browser/list_teammembers.py
opengever/base/browser/resources/keywordwidget.js
opengever/base/tests/test_list_teammembers.py
opengever/contact/tests/test_team_listing.py
opengever/examplecontent/hooks.py
opengever/examplecontent/teams.py
opengever/examplecontent/tests/test_hooks.py
opengever/meeting/tests/test_committee_roles.py
opengever/ogds/base/tests/test_sources.py
opengever/ogds/base/tests/test_team_forms.py
opengever/task/task.py
opengever/testing/fixtures.py

* Added teams to example content
* Added an empty group and a team for it into the fixtures
* Added a view for the keyword widget to use to fetch team members
* Extended the keyword widget js template to also work with teams
* Used the form on the add task form responsible field
Did I miss some other forms where this new template should now be used for the widget?
Closes #5129

Amend the keywordwidget js template to also list team members

---

docs/HISTORY.txt
opengever/base/browser/resolveoguid.py
opengever/base/tests/test_resolve_oguid.py

This change makes sure that any additional **query string parameters** passed to the `resolve_oguid` view **are preserved**, for internal redirects as well as redirects to remote admin units.
This is to ease frontend development of favorites.

ResolveOGUIDView: Preserve query string.

---

docs/HISTORY.txt
opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py
opengever/advancedsearch/tests/test_livesearch_reply.py
opengever/base/browser/livesearch.py
opengever/base/browser/templates/livesearch.pt
opengever/base/tests/test_search.py
opengever/base/tests/test_solr_livesearch.py
opengever/testing/integration_test_case.py

Livesearch reply with activated solr was overwritten by a browser view, but copying the rendering from the `livesearch_reply.py` from the skins folder, so that no template was used for the view. Instead html was generated from the python code by concatenating strings, making the code hard to read and modify. 
* We refactor the `LiveSearchReplyView` to use a template
* We add tests for the `LiveSearchReplyView` (which was untested until now)
* We correct a small xml bug in the standard `livesearch_reply` (no solr)
* We add a test for when the standard `livesearch_reply` returns no results.
To allow more flexible testing we modify the `IntegrationTestCase.mock_solr` method to also accept a response dictionary as argument instead  of an asset filename. This allows to more easily modify the …

Refactor solr livesearch reply

---

development.cfg
docs/HISTORY.txt
opengever/examplecontent/profiles/default/registry.xml
start_all.cfg

We include solr in `development.cfg`, making it available for local development, but we do not activate it by default. To activate run `bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/activate_solr.py`
To facilitate the starting and stopping of solr and making sure the correct instance of solr is running for a given instance of gever, we provide a script which checks if the port used by solr is already in use and only starts solr and the gever instance if it isn't. When exiting gever, solr will also be stopped.
After installing a fresh GEVER, everything works fine without using solr. But strangely during deployment of the example content, errors of the type
```
2019-01-09 14:03:51 ERROR ftw.solr.connection Update command failed. An exception occured: [Errno 61] …
```

Provide solr for local development.

---

docs/HISTORY.txt
opengever/dossier/tests/test_copy_dossier.py
opengever/task/configure.zcml
opengever/task/handlers.py

When copying a dossier, contained tasks should not be copied with it. This may have previously worked occasionally, but was fraught with issues around IntId generation and syncing to SQL, sometimes preventing dossiers with tasks in them from being copied.
This implementation works [exactly the same as what we already have for proposals](https://github.com/4teamwork/opengever.core/blob/505111c4e850191a8ac75702e989cb228135a490/opengever/meeting/handlers.py#L90-L97).
This means there is an eventhandler on `IObjectCopiedEvent` for *the object itself*, and the object (the task) then *deletes itself*.
The advantage of this implementation is that **copying tasks anywhere will always reliably be prevented**. A possible risk however is if we were to rely on tasks getting copied anywhere, this …

Prevent tasks from being copied

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_traverser.py
opengever/meeting/traverser.py
opengever/meeting/zipexport.py

When a proposal has several attachments with the same title/filename, or if the proposal document has the same title/filename as an attachment, this leads to a naming conflict in the zip file and in the grimlock zip-import. To avoid that, we add a new folder `attachments` for each proposal, and within that folder we prefix the attachments with a number.
Also note that in the first commit I removed an unnecessary check in the `MeetingTraverser`. Indeed in `_get_agenda_item_document` we do not need to check whether the agendaitem has a document, as `AgendaItem.resolve_document` already returns `None` when if the agenda_item does not have a document.
resolves #5192

Avoid naming conflicts in meeting zipexport

---

docs/HISTORY.txt
opengever/document/tests/test_document.py
opengever/mail/configure.zcml
opengever/mail/subscribers.py
opengever/mail/tests/test_mail.py
opengever/mail/tests/test_mail_metadata.py

When editing an E-mail and setting the `document_author` to an existing userid, we now set the `document_author` to the corresponding user `fullname`.
Should we write an upgrade step to correct existing E-mails? Note that upon E-mail creation, the `document_author` is taken from the e-mail sender, and if the E-mail address corresponds to a GEVER user, the `document_author` is set to that user's `fullname`. So my guess is that this issue affects only a few E-mails
As I copied the tests from `test_document.TestDocumentAuthorResolving`, which were functional tests, I ported those to the integration layer. I also ported `test_mail.py` to integration layer, just because I had at first added my new tests in that file and having functional tests in there hurt my eyes.
resolves #5226

Resolve mail author to fullname when it is a userid.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po

As I wrote in the ticket:
This was already modified in a previous release. Currently we have:
**Protokollauszug ablegen (Overlay):**
Der Protokollauszug wird im Ursprungsdossier des Antrags abgelegt. Es können keine weiteren Protokollauszüge abgelegt werden.
Wollen Sie diesen Protokollauszug wirklich im Ursprungsdossier ablegen?
So the difference here is using `Ursprungsdossier` instead of `Antragsdossier`. Should that be corrected? `Antragsdossier` is used in only one place in the whole GEVER for now...
**Sitzung abschliessen (inaktiv):**
I'd leave the part about closing all agendaitems, which is still a condition to close the meeting. I adapted the text accordingly
resolves #5205

Change wording of info for inactive close meeting button.

---

docs/HISTORY.txt
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/exception_formatter.py

Return an empty user-facing traceback for non-manager users.
This is done as `Unauthorized` is explicitly rerisen for PAS plugins and this ends up bypassing the `opengever.base` exception template and falling back to normal exception rendering mechanisms.
Additionally we always display the tracebacks in debug mode or with verbose security enabled.
Adding tests for this one would be quite a chore as one would have to create a new testing layer per combination of ZServer settings and the traversal driver on the testbrowser always follows redirects and the issue we have is on the body of the redirect response. Thus I'm requesting manual validation.
We're hitting this logic (relevant for PAS challenge plugins) in https://github.com/zopefoundation/Zope/commit/7b65910f826130e456c32fd33a0ccec2668 …

Also hide re-risen Unauthorized tracebacks for non-manager users.

---

docs/HISTORY.txt
opengever/meeting/committee.py
opengever/meeting/tests/test_committee_roles.py

The normalizer normalizes to a length of 50 by default. As this is shorter than the maximum length of the groupid column and some customers have a naming schema where the the first 50 chars of a group id might be identical we must allow for longer tokens.
Same maximum length as the groupid column should be safe.

Avoid truncating committee responsible group token while normalizing.

---

Gemfile
Gemfile.lock
README.rst
versions.cfg

While installing gever on my machine today, I stumbled upon the wrong Ruby version in the documentation. Also, I had to activate the correct Ruby version after installing it.
The ruby version in the documentation now matches the one specified in the `Gemfile`.
On a side note: I also had to use `rbenv exec gem install bundler` instead of only `gem install bundler`, but maybe that is only because of my setup and does not need to be documented?

Bump Ruby version to 2.4.5

---

docs/HISTORY.txt
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_traverser.py
opengever/meeting/traverser.py
opengever/meeting/zipexport.py

Documents without files were not properly handled in the meeting zip export. They were only handled in the `ZipExportDocumentCollector` but not in `MeetingJSONSerializer` and `MeetingDocumentZipper`. To make sure documents are handled identically in all three classes, we make a new subclass (`MeetingDocumentWithFileTraverser`) of `MeetingTraverser ` and use it as baseclass for the three classes above. Documents with missing files are now directly skipped in the new traverser.
I also added a missing changelog (forgotten in a PR that is already merged, sorry).
resolves #5281

Handle documents without files in meeting zip export with .
