4teamwork/opengever.core

- docs/HISTORY.txt
- opengever/meeting/model/agendaitem.py
It seems that in https://github.com/4teamwork/opengever.core/pull/5207 we introduced a bug for the display of paragraph agendaitems. Because paragraphs have an `item_number` that is `None`, we need to avoid formatting it in a string, see screenshot below.
> Fix bug in paragraph agendaitem item_number display.

- docs/HISTORY.txt
- opengever/meeting/committee.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_committee.py
We group the fields in the committee edit forms in several tabs, to make it a bit clearer.
The fields come from separate schemas, so that it was not possible (let's say I couldn't find how) to make a fieldset with fields from the different schemas (usually we have one schema inheriting from several, and then it works). But as there is only one set that has fields from the two schemas, leaving those in no fieldset and putting the remaining ones in separate fieldsets did the trick.
Another problem appeared during validation. Somehow the invariant gets called once on the form and then on each group. In the latter case, some of the fields were `None` and the invariant failed. Not sure why that is.
resolves #4800
>  Group fields in Committee edit forms.

- docs/HISTORY.txt
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base.pot
- opengever/base/monkey/patches/cmf_catalog_aware.py
- opengever/base/role_assignments.py
- opengever/base/tests/test_copy_paste.py
During a copy/paste, the behaviour was to clear all local_roles and set the owner to the user making the copy/paste. The desired behavior is to preserve the local roles assignment during a copy/paste operation. 
Local roles can get assigned through different behaviors, and it does not make sense to preserve all of them. For example local roles granted through a task should not be copied, as the copied dossier is not referenced in the task.
We now copy local roles from`SharingRoleAssignment`, `ProtectDossierRoleAssignment`, and `InvitationRoleAssignment` when copying an object. Local roles from other assignment classes are dropped (`TaskRoleAssignment`, `TaskAgencyRoleAssignment` and `CommitteeGroupAssignment`). We still reset the owner to the user doing the copy/paste.
We also add a …
> Copy local roles depending on assignment cause during copy/paste.

- docs/HISTORY.txt
- opengever/base/browser/templates/favorites.pt
- opengever/base/tests/test_js_cache_invalidation.py
- opengever/base/viewlets/favorites_menu.pt
- opengever/base/viewlets/recently_touched_menu.pt
- opengever/document/browser/templates/save_pdf_under.pt
- opengever/meeting/browser/meetings/templates/demand_zip.pt
- opengever/task/browser/templates/overview.pt
- opengever/workspace/participation/browser/templates/participants-view.pt
Provide a query string parameter wherever we include vue apps directly in a template. This will invalidate all those apps, theoretically that would not be necessary now but only when the file changes next time. We do it now anyway so it serves as an example for future uses, also new files we include will then already have the version query parameter when the line is copied from an existing template. Also hopefully hints that the version must be increased manually whenever the javascript file changes. 
We should come up with something better soon, but until then this approach must do.
I have manually verified that the apps affected by this change still work 😓.
Also provide tests that make sure that the query string parameter is updated when the files change and that we do not introduce new …
> Provide poor man's cache invalidation mechanism  for vue apps.

- docs/HISTORY.txt
- opengever/meeting/browser/configure.zcml
- opengever/meeting/browser/templates/periods.pt
- opengever/meeting/browser/toc.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_periods.py
- opengever/meeting/tests/test_toc.py
- opengever/meeting/toc/alphabetical.py
- opengever/meeting/toc/dossier_refnum.py
- opengever/meeting/toc/repository.py
- opengever/meeting/toc/repository_refnum.py
- opengever/meeting/toc/utils.py
We add two new toc types for meeting periods:
* only agendaitems with proposals, ordered by dossier reference number
* only ad hoc agendaitems, ordered by titles
I'm not quite sure whether this is what was wanted here? The proposed solution is only partially satisfactory as it relies on a second entry in the TOC json `toc_adhoc`, which can be used in the sablon template to have a different listing type (without displaying the reference number) for adhoc agendaitem elements. I modified the template accordingly, see below for example TOCs:
**Only agendaitems with proposals, ordered by reference number**
**Only ad hoc agendaitems, ordered by title**
Another solution could be to have two different templates. Or maybe only one new TOC type, with two listings, one for agendaitems with proposal …
> Add new meeting toc options sorted by reference number and only ad hoc agendaitems

- docs/HISTORY.txt
- opengever/activity/center.py
- opengever/activity/error_handling.py
- opengever/activity/mailer.py
- opengever/activity/tests/test_digest.py
- opengever/activity/tests/test_mail.py
Defer sending mails until the end of the transaction, to avoid issues with the `zope.sendmail.delivery.MailDataManager` not having savepoint support.
Immediately when doing a `mailhost.send()`, the mailhost will cause a `MailDataManager` to join the current transaction (one per mail). That's how `zope.sendmail` facilitates transactional mails. That specific `IDataManager` does not have savepoint support however. This causes any code that tries to create a transaction savepoint at a later time in that transaction to fail (this will happen during pasting, or certain meeting workflows).
Sending of mails for notifications is already centralized in `opengever.activity.mailer.Mailer`. We change that code so that it doesn't immediately call `mailhost.send()`, but instead collects the mails to be …
> Notifications: Defer sending mails until the end of the transaction

- docs/HISTORY.txt
- opengever/task/browser/forms.py
- opengever/task/tests/test_private_task.py
Currently the fields `is_private` on a task is hidden in a tasks add-form if the private task feature is not enabled. It is also hidden in the edit form unconditionally.
Only hiding but not omitting the field does not discard browser input. Thus input from the browser was still used even when the feature was not enabled. Under some circumstances (still not entirely sure when and when not) the hidden field is rendered as 'selected' in the markup, thus all tasks are/were created as private even when the feature was not enabled.
This PR fixes two things:
- No longer allow creation of private tasks when the feature is not enabled (form patch only, must be addressed again and fixed properly in https://github.com/4teamwork/opengever.core/pull/5316)
- Don't allow changing privateness in the edit …
> Prevent tasks from being created as private or switched to private when feature is not enabled.

- docs/HISTORY.txt
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_periods.py
- opengever/meeting/tests/test_toc.py
- opengever/meeting/toc/alphabetical.py
Include agenda item or proposal description in JSON provided as input for TOC sablon templates. It is already included in JSON for protocol, agenda item list and excerpt but unfortunately was not added to the TOC.
Closes #5305.
> Include agenda item description in TOC json.

- docs/HISTORY.txt
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/upgrades/20190205162955_make_the_oneoffixx_timeout_configurable_via_the_registry/registry.xml
- opengever/core/upgrades/20190205162955_make_the_oneoffixx_timeout_configurable_via_the_registry/upgrade.py
- opengever/oneoffixx/api_client.py
- opengever/oneoffixx/interfaces.py
It has arisen we want much longer timeouts for the caching and it'd thus be prudent to make the timeouts configurable. For the sake of simplicity both non-eternal caches are now using the same timeout.
Closes #5323
> Make the Oneoffixx timeout configurable via the registry

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/exception_formatter.py
Redo of https://github.com/4teamwork/opengever.core/pull/5269
Return an known-redacted user-facing traceback for non-manager users.
This is done as Unauthorized is explicitly rerisen for PAS plugins and this ends up bypassing the opengever.base exception template and falling back to normal exception rendering mechanisms.
Additionally we always display the tracebacks in tests, debug mode or with verbose security enabled.
Adding tests for this one do not seem possible.
We're hitting this logic (relevant for PAS challenge plugins) in zopefoundation/Zope@7b65910 and monkey patching the exception formatting logic was the least impactful route I found of addressing this.
An alternative would be to try to muck around with the exception hook itself, but that'd be potentially a lot more dangerous. …
> Also hide re-risen Unauthorized tracebacks for non-manager users

- docs/HISTORY.txt
- opengever/tabbedview/catalog_source.py
- opengever/tabbedview/tests/test_catalog_source.py
Solr TabbedView filters: Also **include non-wildcarded terms** in query.
Wildcard queries in Solr only get analyzed with a subset of the query analyzers, not all of them (only multi term aware ones). *(See [this (old) post](https://lucidworks.com/2011/11/29/whats-with-lowercasing-wildcard-multiterm-queries-in-solr/) for an in-depth explanation of the issue, and [this section](https://lucene.apache.org/solr/guide/6_6/analyzers.html#Analyzers-AnalysisforMulti-TermExpansion) in the docs).*
Specifically, this leads to our `WhitespaceTokenizerFactory` not being run against the query, and the query therefore doesn't get tokenized.
---
This can be observed in the difference of how Solr parses the query (note the difference in `parsedquery`):
**Non-Wildcard query**
**Wildcard query**
---
Also …
> Solr TabbedView filters: Also include non-wildcarded terms in query

- docs/HISTORY.txt
- plonetheme/teamraum/importexport.py
- plonetheme/teamraum/tests/test_importexport.py
The upload was broken and ended up in an AttributeError and a cryptic error message gets
displayed in browser.
> Fix logo upload in the theme control-panel.

- docs/intern/kurzreferenzen/feedbackforum-prozess.rst
Habe beim Aufräumen des FF die Tags vereinheitlicht resp. zusammengestrichen, da wir viel zu viele hatten, welche nicht gepflegt wurden. Diese Anpassung habe ich nun auch in der Doku aktualisiert.
> Aktaulisierung interne Informationen zu Feedbackforum

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/command.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_meeting_view.py
- opengever/meeting/tests/test_protocol.py
This PR fixes an unmatched label and missing change-date update.
Fixes #5154
> Fix label and modification date for protocol documents

- README.rst
- docs/HISTORY.txt
- opengever/core/testserver.py
- opengever/testing/fixtures.py
The testserver is useful for testing other projects which use / work
with a GEVER.
Those projects have specific needs: they may need certain content or a specific structure and may not need some parts of GEVER at all.
Thats why we want to be able to inject a custom fixture when starting up the testserver. We need to be able to subclass the default fixture though, so that we can profit from the features in the default fixture.
The custom fixture can be inserted by setting the ``FIXTURE`` environment variable to the path to the fixture python file. The directory of the file needs to be a package, so there needs to be a ``__init__.py``. Since the fixture is stored and maintained in the third party project, it is not part of the python path. The testserver loads the package of the fixture …
> Testserver: add support for custom fixtures.

- docs/HISTORY.txt
- opengever/core/upgrades/20190205142415_fix_broken_mimetypes/mimetypes.xml
- opengever/core/upgrades/20190205142415_fix_broken_mimetypes/upgrade.py
- opengever/policy/base/profiles/mimetype/mimetypes.xml
Dieser PR fügt den fehlenden .xls mimetype-Eintrag wieder hinzu.
Der Eintrag wurde durch diesen PR gelöscht: https://github.com/4teamwork/opengever.core/pull/4494
Grund:
-------
Der [erste definierte Mimetype](https://github.com/collective/collective.mtrsetup/blob/master/collective/mtrsetup/handler.py#L53) wird als ID verwendet. Bei folgender Registrierung:
```xml
<object name="mimetypes_registry" meta_type="MimeTypes Registry">
<mimetype
name="Microsoft Excel Spreadsheet"
extensions="xls"
globs="*.xls"
mimetypes="application/vnd.ms-excel
application/msexcel"
/>
</object>
```
Wird `application/vnd.ms-excel` als ID verwendet. Es wird danach geschaut, ob diese [ID bereits irgendwo definiert wurde](https://github.com/collective/collective.mtrsetup/blob/master/collective/mtrsetup/handler.py#L5 …
> Fix broken mimetypes.

- docs/HISTORY.txt
- opengever/core/upgrades/20181116121240_reindex_new_supported_bumblebee_documents/upgrade.py
This PR calculates the checksum for documents having the newly supported mimetypes and stores the im bubmelbee.
~⚠️ use `ftw.bumblebee` release instead from source~ (Required bumblebee-version have already been pinned by the following commit https://github.com/4teamwork/opengever.core/commit/210cb77804)
> Reindex and store additionally supported bumblebee documents.

- docs/HISTORY.txt
- opengever/base/subscribers.py
Added pessimism to the attribute access.
Closes #5351
> Fix scrubbing the server version out of the HTTP response headers

- opengever/api/tests/test_repository.py
- opengever/portlets/tree/tests/test_treeportlet.py
- opengever/testing/builders/__init__.py
- opengever/testing/builders/dx.py
- opengever/testing/builders/portlets.py
- opengever/testing/fixtures.py
- Register a new portlet builder `tree portlet` for building tree portlets.
- Add a `with_tree_portlet()` option to the `repository_root` builder.
- Setup the tree in the standard fixture with a portlet.
This is very useful when starting the testserver: until now there was no navigation, which was confusing, especially for non-geverists.
> Register and use a tree portlet builder for testing.

- docs/HISTORY.txt
- opengever/api/tests/test_favorites.py
- opengever/base/favorite.py
The functionality which raises the position for the favorites after the one which has been deleted, destruct the order.
Closes #5288
> Fix order issue when deleting a favorite.

- README.rst
The devdocs now contain a LaTeX section and our own fonts.
Ref https://github.com/4teamwork/devdocs.4teamwork.ch/pull/63
> Readme: reference LaTeX devdocs section.

- docs/HISTORY.txt
- opengever/inbox/browser/overview.py
- opengever/inbox/tests/test_overview.py
Not much to say... just a snapshot with a document worthy of storing in a GEVER:
resolves #5350
> Add document tooltip to inbox document listing.

- docs/HISTORY.txt
- opengever/base/configure.zcml
- opengever/base/indexes.py
- opengever/base/model/__init__.py
- opengever/core/upgrades/20190204085532_increase_sortable_title_max_length/upgrade.py
- opengever/document/tests/test_indexers.py
- opengever/dossier/tests/test_indexer.py
- opengever/mail/tests/test_indexers.py
- opengever/repository/configure.zcml
- opengever/repository/indexers.py
- opengever/repository/tests/test_indexer.py
- opengever/testing/tests/test_integration_test_case.py
Add custom `sortable_title` indexer to avoid cropping of content titles. We set the maximal length for the `sortable_title` larger than the maximal allowed content title length, to allow for number padding without cropping long titles.
resolves #4398
> Add custom sortable_title indexer to avoid cropping of content titles.

- docs/HISTORY.txt
- opengever/activity/tests/test_mail.py
- opengever/task/activities.py
Notification mails for task added activity were not displayed correctly if the Description was multiline.
The problem stems from https://github.com/4teamwork/opengever.core/pull/4152/commits/a2b502635b4576d4b9a29d6b99bc49a6ca3e6b19, where we break up the description into html paragraph blocks if it is multiline. Problem is that for task-added activity, the Description is already an html table, leading to overlapping tags in the final html. gmail then tries to fix the html, but doesn't manage it correctly (whereas mail for example succeeded in fixing the markup).
Proposed solution is to treat the linebreaks beforehand for the case of task-added activity.
**task-added activity before this fix**
**task-added activity before this fix**
resolves #5290 and …
> Fix mail for task added activity with multiline comment.

- base-testserver.cfg
- opengever/core/testserver_selftest.py
- test-testserver-selftest.cfg
- versions.cfg
Closes #5331
The port choosing method is switched to using a 0-port so that the OS chooses the port in the testserver.
This is done in order to avoid problems where the jenkins master chooses a port, but the test is run at the slave, on which the port is already used.
The robot server is extended so that it prints out the URLs including the chosen ports for the ZServer and the XMLRPC-server. The selftest script now needs to watch the stdout of the testserver process and wait until the URLs appear
> Reenable testserver selftest on jenkins by fixing port choosing.

- docs/HISTORY.txt
- opengever/dossier/utils.py
When using `while` loops to walk up the parents in the acquisition chain to find a particular object (or stop at the site root), care must be taken to consider the case of **improperly AQ wrapped objects**:
When these functions get passed objects that aren't AQ wrapped (or don't have a full acquisition chain that reaches up to the Plone site), `aq_parent()` will return `None` at some point.
If this isn't accounted for and dealt with by terminating the loop, this kind of a while loop can end in an infinite loop.
*(No tests, because failing tests for this would cause Jenkins jobs to get stuck pretty much by definition)*
> Avoid infinite loops when looking for parent dossiers

- docs/HISTORY.txt
- opengever/dossier/tests/test_copy_dossier.py
- opengever/meeting/handlers.py
- opengever/meeting/tests/test_proposal.py
- opengever/task/handlers.py
When "filtering" objects (currently tasks and proposals) from copied subtrees, we do so by deleting them from the temporary ZEXP that's about to be attached to the destination container.
We need to **suppress deletion events** in order to avoid attempts to uncatalog objects that
- haven't even been cataloged yet and
- dont' have a proper AQ chain because they're part of a subtree
that hasn't been attached to a container yet.
Fixes #5347
> Suppress deletion events when filtering objects from copied subtrees

- docs/HISTORY.txt
- opengever/task/reminder/cronjobs.py
To make sure that (hopefully) everything gets translated correctly down the line, we set the language on the request from the cronjobs generating the reminders.
resolves #5378
> Set request language based on site wide preferred language for task reminders

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/deactivate.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_base.py
- opengever/dossier/tests/test_deactivate.py
The check is not done as a workflow transition guard as that'd make visiting deeply/widely populated dossiers very expensive.
⚠️ Missing translations.
Closes #5153
> Prevent deactivating dossiers with undeactivatable subdossiers

- opengever/dossier/browser/tabbed.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
With https://github.com/4teamwork/opengever.core/pull/5353 I introduced an unnecessary translation for the document templates tab and also broke the french translation for it, when OneOffixx is enabled.
> Remove a now-unneeded layer of Oneoffixx related Localization

- docs/HISTORY.txt
- opengever/base/date_time.py
- opengever/base/tests/test_date_time.py
- opengever/meeting/tests/test_agendaitem_list.py
- opengever/meeting/tests/test_toc.py
- opengever/meeting/utils.py
In #4417 we have introduced custom format strings for dates in sablons. The problem is that these dates are not localized to the user's locale, but to the servers, i.e. english.
To allow for localizations of these dates with a custom format string, we introduce our own date localization method, based upon `i18nl10n.ulocalized_time`. Below an example of a generated agendaitem list with GEVER in french and in german:
Also note that the resulting dates are zero padded.
resolves #4989
> Add date string localization for sablon data.

- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
This PR fixes a typo when returning an excerpt to the dossier of its proposal.
> Fix a typo in info message.

- docs/HISTORY.txt
- opengever/api/scanin.py
- opengever/api/tests/test_scanin.py
- opengever/contact/tests/test_team_listing.py
- opengever/inbox/tests/test_forwarding.py
- opengever/ogds/base/tests/test_actor_lookup.py
- opengever/ogds/base/tests/test_sources.py
- opengever/ogds/base/tests/test_team_details.py
- opengever/task/tests/test_assign.py
- opengever/task/tests/test_overview.py
- opengever/task/tests/test_team_tasks.py
- opengever/testing/fixtures.py
As request objects contain byte strings, scan-in did not work for org units with non-ASCII in their titles.
Closes #5376
>  Fix handling of non-ASCII in the scan-in API endpoint.

- docs/HISTORY.txt
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/resolve.py
- opengever/dossier/resolve_lock.py
- opengever/dossier/tests/test_resolve.py
- opengever/dossier/viewlets/byline.py
Implements a **locking mechanism to prevent concurrent dossier resolution**.
This mechanism is intended to prevent users from simultaneously triggering the `resolve` transition for a dossier (which would result in degraded performance because retries of conflicting transactions).
We do this by issuing a **persistent lock** that gets committed in its own transaction as the very first thing in the resolution process. Further attempts at resolving a dossier are then rejected as long as such a lock exists (and hasn't expired). Once the dossier is resolved successfully, the lock is removed and the removal will be committed again. The lock will **expire after 24h**, and which point it will just be treated as if it wouldn't exist.
In case of an exception, we catch it, abort the transaction, …
> Lock dossier subtree during resolve transition

- docs/HISTORY.txt
- opengever/task/browser/assign.py
- opengever/task/tests/test_assign.py
When reassigning the task, leaving the responsible field empty would lead to an exception. This is now handled. What will happen now is that you stay on the form and get an error message (see screenshot)
resolves #5392
> Handle empty responsible field when assigning task.

- docs/public/index.rst
- docs/public/release-notes/index.rst
Officially **publish release notes**, since they are now being linked to from the https://onegovgever.ch/aktuell redirect.
*(They were already reachable, but not completely integrated into the navigation/TOC)*
> Docs: Officially publish release notes

- docs/HISTORY.txt
- opengever/document/document.py
- opengever/officeconnector/mimetypes.py
Adds the mimetype for XML based Visio `*.vsdx` files (`'application/vnd.ms-visio.drawing'`) to the base list of OC-editable types.
The intent was to do this in #5085, but this type was only added as part of upgrade steps, not to the base profile. Therefore it got omitted when switching to the new three-tier mechanism in #5382.
The macro enabled Visio types, as well as template and stencils, are not added on purpose because those currently won't work with OfficeConnector.
See #5413 for some more background.
---
In addition, this PR factors out the `get_editable_types()` function for cleaner separation of concerns (building the final list vs. determining whether a particular document is editable) and easier use for debugging.
> Add Visio *.vsdx to the base list of OC-editable types

- docs/HISTORY.txt
- opengever/activity/__init__.py
- opengever/dossier/cronjobs.py
- opengever/task/reminder/cronjobs.py
More translations problems for mails generated via cron jobs. We corrected this for task reminders in https://github.com/4teamwork/opengever.core/pull/5379, and now the same fix is applied for dossier overdue activity. We are simply making sure the language is set on the request before generating the E-mails.
This resolves https://basecamp.com/2768704/projects/12554551/todos/380774579
> Set default language for dossier overdue activity.

- docs/HISTORY.txt
- opengever/api/document.py
- opengever/api/listing.py
- opengever/api/tests/test_document.py
- opengever/api/tests/test_listing.py
- opengever/base/contentlisting.py
- opengever/base/tests/test_contentlisting.py
* Added the Bumblebee PDF URL to the document API GET endpoint
* Unified the listing GET endpoint vs. the document GET endpoint
I'm not quite up to documenting the document and listing endpoints at this point. These commits can also be dropped, if the placeholders are undesired.
//cc @jone @sebastianmanger 
Closes #5391
> Make bumblebeeable documents uniform on API endpoints

- docs/HISTORY.txt
- opengever/officeconnector/mimetypes.py
Despite macro files being known problematic, a source of support tickets and something we cannot guarantee to work, they are still widely used by end users.
In hindsight I should have tried to consult the content stats for the MIME type.
Closes https://github.com/4teamwork/opengever.core/issues/5447
> Readd Office macro files into Office Connector editable MIME types

- docs/HISTORY.txt
- opengever/base/viewlets/footer.pt
While working on https://github.com/4teamwork/opengever.core/issues/5187, I realized the footer in GEVER is also outdated. It now points to our new 4teamwork website.
> Adapt footer to new 4teamwork website.

- docs/HISTORY.txt
- opengever/document/extra_mimetypes.py
- opengever/officeconnector/mimetypes.py
We're readding Office Connector editability for Office template formats, as they work on Windows.
Closes https://github.com/4teamwork/opengever.core/issues/5453
> Readd Office template, macro, stencil files into Office Connector editable MIME types

- docs/HISTORY.txt
As the title says, update of the HISTORY after the backport for the 2019.1.2 release.
> Update HISTORY after 2019.1.2 release.

- docs/HISTORY.txt
- opengever/tabbedview/catalog_source.py
The original implementation for excluding the search root in `ftw.table`, introduced in 4teamwork/ftw.table#53, creates one path query for each immediate child. Turns out that performs much worse than expected for containers with lots of immediate children.
Because in GEVER we have a more recent version of `Products.ZCatalog`, and also [monkeypatch the UIDIndex's query options to add support for the 'not' operator](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/monkey/patches/uuidindex.py), we're able to use a more efficient strategy here, and simply exclude the current context using `{'not': uuid}` filter.
Fixes #5487
> Fix performance issue with search root exclusion in tabbed view listings

- docs/HISTORY.txt
- docs/public/user-manual/aufgaben/aufgaben-workflow.rst
- opengever/task/localroles.py
- opengever/task/tests/test_localroles.py
> Make attachments for `direct-execution` tasks editable by the responsible.

- docs/HISTORY.txt
- opengever/task/browser/transitioncontroller.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_transition_actions.py
- opengever/task/tests/test_transitioncontroller.py
The skip transitions should only be available for tasks generated from a tasktemplate.
Note: A special protection for the planned to skipped transition is not necessary, because only tasks part of a task sequence can be in the planned state.
Closes #5438
> Make reject to skip transition only available for tasks part of a sequence.

- docs/HISTORY.txt
- docs/public/admin-manual/meeting/mergefields.rst
- docs/public/release-notes/archiv/release-3.10.rst
- docs/public/release-notes/release-2017.1.rst
- docs/public/release-notes/release-2018.1.rst
- docs/public/release-notes/release-2018.2.rst
- docs/public/release-notes/release-2018.4.rst
- docs/public/user-manual/sitzungs-app/zusammenstellen.rst
- docs/public/user-manual/spv/antrag-erfassen.rst
- docs/public/user-manual/spv/antrags-benachrichtigungen.rst
- docs/public/user-manual/spv/sitzung-vorbereiten.rst
- docs/public/user-manual/spv/sitzungsunterlagen-aufbereiten.rst
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/tests/test_meeting_zipexport.py
We now use `Beilage` in German and `pièce jointe` in French everywhere in the SPV. I left `Anhang` in other places such as mails.
Side effect is that in the zip export we now have `Beilage` instead of `Anhang` as subdodisser for the attachments. I'm not sure whether that is a problem for the meeting app?
resolves #5189
> Standardize french and german translation of "attachments" in meetings.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
Filters can be passed with the `filters` record query parameter.
Example:
`/@listing?name=dossiers&filters.review_state:record:list=dossier-state-active&filters.review_state:record:list=dossier-state-archived&filters.responsible:record=hugo.boss`
> Add support for filters in listing endpoint

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
- opengever/testing/fixtures.py
- Erweitert die vorhandenen @listing-queries mit `workspaces`.
Issuer: https://github.com/4teamwork/gever-ui/issues/15
> Extend listing with workspaces

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/sharing/interfaces.py
We add the `black_list_prefix` and `white_list_prefix` from `ISharingConfiguration` to the config endpoint.
I wonder whether we should group them under `sharing_config` or something like that? Just the names as they are now are not very explicit.
resolves #5423
> Add sharing white and black list prefix to config endpoint/view.

- docs/HISTORY.txt
- opengever/core/upgrades/20190307132714_fix_task_and_journal_pdf_object_provides/upgrade.py
Because the index name was misspelled in the query (`title` instead of `Title`), the initial query returned all documents, leading to many unnecessary objects getting checked. With this fix the query runs as originally intended.
I also verified that the new query does indeed match and find the automatically generated PDF documents that are supposed to be reindexed.
_Needs to be backported to `2019.1.x` (and possibly `2018.5.x`)._
> Fix upgrade step that reindexes object_provides for PDFs so it performs better

- docs/HISTORY.txt
- opengever/base/transition.py
- opengever/task/browser/assign.py
- opengever/task/browser/configure.zcml
- opengever/task/configure.zcml
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/tests/test_api_support.py
- opengever/task/tests/test_assign.py
- opengever/task/tests/test_response_syncer.py
- opengever/task/transition.py
- opengever/testing/integration_test_case.py
Extend the field validator, which makes sure that admin-unit changes are only possible when the task is in the open state. Registering two `SimpleFieldValidators` for the same field, does not worked, therefore I combined the two checks in one validator.
Because we do not use the exact same interface in the form than the transition extender, which is used by API requests, we need to add separate validators for each field of the transition extender interface. 
I also realized that the BaseTransitionExtender did not correctly validates the values (SimpleFieldValidators has not been called in the former implementation), I've fixed that as well.
Closes #5374
> Allow reassigning tasks to other org- and adminunits.

- docs/HISTORY.txt
- opengever/dossier/tests/test_templatefolder.py
- opengever/inbox/tests/test_tabs.py
- opengever/repository/tests/test_repositoryfolder_tabs.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/opengever.tabbedview.pot
- opengever/tabbedview/tests/test_document_listing.py
Added the column to the base Document tab, added translations and amended the tests.
Closes #5478
> Add a file extension column to document listings

- docs/HISTORY.txt
- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/document/browser/tabbed.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/mail/browser/tabbed.py
- opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/opengever.mail.pot
- opengever/trash/tests/test_trash.py
* Adding a portal warning onto the tabbedview of a document or a mail
* Only if the request is a 'simple get'
* Adding a warning to bumblebee overlays for documents and mails
* Added a versioned attribute to the versioned overlay as the adapter loses the context proper
Document overview:
Document overview overlay:
Document version listing overlay of current version:
Document version listing overlay of old version:
Closes #5481
> Display a portal warning on the overview of trashed documents

- docs/HISTORY.txt
- docs/intern/operations/allgemein.rst
- docs/intern/operations/saas.rst
I updated the documentation for the update of SaaS deployments. I also added a reference to a script I wrote, which has not been reviewed yet: https://github.com/4teamwork/opengever-deployments/pull/27
> Update SaaS deployments documentation.

- docs/HISTORY.txt
- docs/public/dev-manual/api/searching.rst
- opengever/api/configure.zcml
- opengever/api/solrsearch.py
- opengever/api/tests/test_solrsearch.py
The endpoint passes the parameter to ftw.solr's SolrSearchUtiliy, so we don't have to care about the security index and preparing the different parameters.
If solr is not enabled the endpoints raises a BadRequest exception.
Closes #5406
> Add solrsearch REST API endpoint.

- opengever/base/tests/test_changed_date.py
Spotted off the shuffle nightlies - overwriting `self.manager` in integration tests.
> Fix a test leak in the 'changed' tests

- README.rst
- docs/HISTORY.txt
- docs/public/dev-manual/api/tasks.rst
- opengever/base/tests/test_role_assignments.py
- opengever/dossier/tests/test_overview.py
- opengever/globalindex/tests/test_query.py
- opengever/globalindex/tests/test_task_sql_syncer.py
- opengever/latex/tests/test_dossierjournal.py
- opengever/meeting/tests/test_meeting_dossier_overview.py
- opengever/meeting/tests/test_proposal.py
- opengever/tabbedview/tests/test_personaloverview.py
- opengever/tabbedview/tests/test_tasklisting.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/task.py
- opengever/task/tests/test_forms.py
- opengever/task/tests/test_localroles.py
- opengever/task/tests/test_private_task.py
- opengever/tasktemplates/tests/test_trigger.py
- opengever/testing/fixtures.py
I added an invariant to the ITask schema, thats imho the only way to have a schema validation, which is also called on api POST/PATCH requests.
Because invariants get an `z3c.form.validator.Data` object passed in, which provides his own getattr with a fallback, fetching the value from the context when the field was not passed in via form/api , I had to check if the is_private value was part of the input-data with the help of the attribute `_Data_data___`. I don't see any other way to check if the field is passed in or if it's already set on the object.
Besides that Joni did some testing and cleanup work, thx ...
Closes #5441
> Prevent creating private task or switching a task to private when feature is disabled.

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
- opengever/base/contentlisting.py
Erweitert die vorhandenen @listing-queries mit `tasks`.
Issuer: https://github.com/4teamwork/gever-ui/issues/18
> Extend listing endpoint with `tasks`

- docs/HISTORY.txt
- docs/public/dev-manual/api/navigation.rst
- opengever/api/navigation.py
- opengever/api/tests/test_navigation.py
Add the following properties to a navigation-item:
- `@type`
- `current`
- `current_tree`
Add the following query-params to the `@navigation` endpoint:
- `include_root`
- `root_interface`
- `content_interfaces` 
Issuer: https://github.com/4teamwork/gever-ui/pull/107
> Extend @navigation endpoint to be more generic

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
Nightlies are failing because of a date shift. This comes from a timezone issue. In the tests for the default values, we freeze with a TZ aware `datetime`, which is correct for looking at `changed` which is TZ aware, but fails for other dates, e.g. the document date, which defaults to `date.today()`.
We now simply use a TZ aware `datetime` for freezing and comparing with `changed` and a TZ naive `date` to check other date defaults.
I did check that this solves the problem when the offset leads to a date shift.
> Fix tests failing due to timezone leading to date shift.

- docs/HISTORY.txt
- opengever/dossier/browser/archival_file_management_view.py
- opengever/dossier/browser/configure.zcml
- opengever/dossier/browser/templates/archival_file_management_view.pt
- opengever/dossier/tests/test_archival_file_management_view.py
We add a management view on the dossier level, which lists all documents and their archival file state.
Documents are sorted by path and the information displayed is:
* the path to the document (link)
* the filetype
* whether the document has an `archival_file`
* The `archival_file_state` of the document
Notice that we are rendering the `plone.belowcontenttitle` viewlets, as this contains the byline listing. This handler also adds the favorite menu, which is a bit less welcome here. I'm not sure how to selectively disable some viewlets? For now, I simply display the dossier title, as `firstHeading`, so that the favorite menu is actually next to the dossier name.
**Example archival file management view**
resolves #5538
> Add archival file management view on dossier level.

- docs/HISTORY.txt
- docs/public/dev-manual/api/documents.rst
- docs/public/dev-manual/api/index.rst
Closes #5279.
Note: this PR does not change anything on the API, its documentation only.
> Add documentation for document endpoints (checkin/out, locking etc.)

- docs/HISTORY.txt
- opengever/api/scanin.py
- opengever/api/tests/test_scanin.py
- opengever/core/upgrades/20190403172610_fix_scaneingang_privatedossiers/upgrade.py
the scan-in endpoint used the `create` helper from plone.restapi to create the private dossier `Scaneingang`, but this helper does not fires the CreatedEvent which leads to object without an UID. In combination with the recently introduced not-query on UIDs those dossiers are no longer listed in the dossier listing. 
I changed now the creation to `createContentInContainer` (the way we use for other in code content creation) and provide an upgradestep which fires (again) the ObjectCreatedEvent and reindex the object.
Closes #5529 
Needs backport to `2019.1-stable`
> Fix creation of scaneingang dossier in the scan-in endpoint.

- docs/HISTORY.txt
- opengever/base/browser/resources/base.js
- opengever/oneoffixx/api_client.py
- opengever/oneoffixx/browser/form.py
- opengever/oneoffixx/tests/test_oneoffixx.py
* Added a fetcher for the per user selected favorites to the api client
* Injecting the favorites, if any, as a template group
* Added a filter to the select field
* Refixed the autofocus JS
A demo of the filter:
We do not currently know of a user on a real backend, which would have selected favorites. Validation should ultimately still wait for this ability to be achieved.
Closes https://github.com/4teamwork/opengever.core/issues/5445
Closes https://github.com/4teamwork/opengever.core/issues/5246
> Support Oneoffixx template favorites

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/extendedpathindex.py
- opengever/base/monkey/patches/uuidindex.py
- opengever/tabbedview/catalog_source.py
Turns out that NOT queries perform very bad for indexes with a lot of unique values.
Thus we patch the ExtendedPathIndex now for root path exclusion.
- Patch ExtendedPathIndex to allow exclusion of root path
- Exclude root path within path query in tabbed view's catalog source and in the REST API's listing endpoint
- Remove no longer needed UUIDIndex patch for NOT support
> Fix root path exclusion performance

- docs/HISTORY.txt
- opengever/base/browser/paste.py
- opengever/document/tests/test_handlers.py
Docproperties get updated several times during a copy/paste operation of a word document, overwriting the blob file each time. Each time the blob file is changed, a reindex operation is queued in solr, which is processed after the transaction ends. When that happens, solr tries to process some blobs that do not exist anymore and fails. We now update the docproperties only once during a copy/paste operation.
I don't think I can write a test for this, as long as we do not have a real solr running for testing purposes. For now I've written a test making sure that my changes did not break the update of the docproperties when copy/pasting a dossier containing a document. I added a comment in the test to also test sorl indexing of the object once we can.
**Here some notes on the analysis of the …
>  Fix solr error during copy/paste of word document.

- docs/HISTORY.txt
- opengever/base/browser/paste.py
This should fix an issue during copy/paste when some catalog entries were duplicated.
Children are now renamed/moved postorder, i.e. children are renamed before their
parents. This is important to avoid race-conditions with the move optimization from ftw.copymovepatches.
- When moving multiple items plone dispatches the move event to children in an event handler. This event handler is registered earlier than the handler from `ftw.copymovepatches`. Thus it is called before the parent item is "moved" in the catalog by `ftw.copymovepatches`.
- The optimization in `ftw.copymovepatches` trips up if one of the children somehow cause their parent to be reindexed while it is moved as the catalog then treats it as a new entry.
- we can fix this behavior in our custom copy/paste handler by moving …
> Fix duplicate catalog entries, rename depth first after copying.

- docs/HISTORY.txt
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/tests/test_dossier_template.py
When adding `businesscasedossier` is disallowed in a leaf repofolder but `add_businesscase_dossier` have been selected, we show the add dossier from template action. This allows for repofolders where dossiers can only be added from templates.
Note that in general when adding `businesscasedossier` is disallowed, we do not show the add dossier from template action.
resolves #5543
> Show dossier from template action also when adding dossier disallowed.

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
The restriction query, which has been introduced with #5007, contained an distinct statement, which lead to problems on oracle backends. Because Oracle does not support DISTINCT with SELECTs that have CLOB type columns. But the task model uses CLOB for the physical_path and text column.
So we need to use a subquery instead, when using an oracle backend. I extend the restrict method, to a oracle specific implementation with subqueries.
Update: Because PostgreSQL optimize the subquery too and a subquery is even faster, we don't need to avoid the subquery and use the same query for PostgreSQL backends too, instead of a specific Oracle query.
Fixes #5565.
> Improve task restriction query, to work also on oracle backends.

- docs/HISTORY.txt
- opengever/api/livesearch.py
- opengever/api/tests/test_livesearch.py
- opengever/base/browser/livesearch.py
- opengever/base/solr.py
Adjustment for solr and non-solr deployments.
Closes #5550.
> Include filename in the livesearch endpoint results.

- docs/HISTORY.txt
- opengever/task/browser/forms.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_private_task.py
- opengever/task/tests/test_revoke_permissions.py
Omit the is_private field instead of only set it to hidden mode, when the feature is disabled. Fixes #5568
> Fix issue on task creation when is_private feature is disabled.

- opengever/testing/builders/sql.py
The OrgUnitBuilder creates Plone Groups and OGDS Groups for each org unit. But the configured group ids in the org unit did not match the automatically generated group ids.
This change makes the group ids consistent by not setting a default argument for the sql object and setting the default when building the groups. This allows us to use the default ids, to override the ids by using a "having" but also to create the groups by hand.
> Testing: make group ids consistent in OrgUnitBuilder.

- docs/HISTORY.txt
- opengever/api/tests/test_listing.py
- opengever/base/tests/test_changed_date.py
- opengever/core/profiles/default/types/opengever.workspace.folder.xml
- opengever/core/profiles/default/types/opengever.workspace.workspace.xml
- opengever/core/tests/test_relations.py
- opengever/core/upgrades/20190418113651_remove_dossier_inheritance_for_workspaces/opengever.workspace.folder.xml
- opengever/core/upgrades/20190418113651_remove_dossier_inheritance_for_workspaces/opengever.workspace.workspace.xml
- opengever/core/upgrades/20190418113651_remove_dossier_inheritance_for_workspaces/upgrade.py
- opengever/testing/fixtures.py
- opengever/workspace/browser/configure.zcml
- opengever/workspace/browser/tabbed.py
- opengever/workspace/browser/tabs.py
- opengever/workspace/interfaces.py
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/tests/test_workspace_folder.py
- opengever/workspace/tests/test_workspace_workspace.py
- opengever/workspace/workspace.py
- opengever/workspace/workspace_folder.py
Dieser PR entfernt die Vererbung des Dossiers auf einen Teamraum.
Durch diesen PR wird ebenfalls das Übersichtstab ersetzt mit einem "Ordner" Tab. Der Grund: Das Übersichtstab ist nicht wirklich sinnvoll (https://github.com/4teamwork/gever-ui/pull/107). Durch die Entfernung der Vererbung müssten wir für einen Arbeitsraum ein neue Overview-View implementieren - entweder durch Refactoring der bestehenden oder eine Kopie mit kleineren Anpassungen.
Um dies zu Verhindern, wird neu nur noch ein Tab mit den Ordnern dargestellt.
Im Frontend werden wir trotzdem alle Möglichkeiten offen haben.
Beispiel mit klassischem UI:
Beispiel mit neuem UI
Durch diesen PR werden folgende PRs überflüssig: https://github.com/4teamwork/opengever.core/pull/5556, https://github.com/4teamwork/opengever.core/pull/5559 …
> Workspaces do no longer inherit from dossiers.

- docs/HISTORY.txt
- opengever/base/handlers.py
- opengever/base/security.py
- opengever/task/localroles.py
When profiling the test runs, I spotted about 20% of the runtime of the module `opengever.task` is spent in `LocalRolesSetter. set_roles_on_distinct_parent()`, for which we already have an optimisation in place for only reindexing the security indices of known-effected children of the distinct parent.
Diving deeper showed half of that time is spent in setting the metadata for those objects, which makes no sense in the context. Looking at the implementation of `.reindexObjectSecurity()` for a `CMFCatalogAware` object from `Products.CMFCore` 2.2.x revealed it does a direct catalog reindex skipping the metadata update, for the object including all of its children.
https://github.com/zopefoundation/Products.CMFCore/blob/2.2/Products/CMFCore/CMFCatalogAware.py#L122-L123
We already have a use …
>  Optimise local roles security reindexing in tasks

- docs/HISTORY.txt
- opengever/document/tests/test_document.py
- opengever/dossier/tests/test_indexer.py
- opengever/dossier/tests/test_templatefolder.py
- opengever/inbox/tests/test_tabs.py
- opengever/repository/tests/test_repositoryfolder_tabs.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/filtered_source.py
- opengever/tabbedview/filters.py
- opengever/tabbedview/tests/test_document_listing.py
- opengever/testing/fixtures.py
- opengever/testing/integration_test_case.py
We add a keywords filter to the document listings, when solr is active. This reuses the implementation of the filter for the dossiers, which breaks the listings if solr is not reachable. I added a commit which handles this by ignoring keywords in that case. This is just a proposal, not sure whether we want the listing to be broken when solr is unavailable.
resolves #5464
> Add keyword filter to document listings

- docs/HISTORY.txt
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
Simply added the setting to the configuration adapter implementation.
Closes #5588
> Include preserved_as_paper_default in the @config endpoint and view

- opengever/nightlyjobs/runner.py
- opengever/nightlyjobs/tests/test_nightly_job_runner.py
psutil's `virtual_memory().percent` is in percent (`0-100`), not a decimal like `0.95`.
(See [`psutil._common.usage_percent()`](https://github.com/giampaolo/psutil/blob/c78a850358af883dcaa63a3f9204f15cc129e518/psutil/_common.py#L268-L277)).
On this occasion, I also verified that [`percent` refers to the percentage of `total - available`](https://github.com/giampaolo/psutil/blob/c78a850358af883dcaa63a3f9204f15cc129e518/psutil/_pslinux.py#L478) (instead of `used`, which would be problematic), which is the behavior we want. (_That isn't explicitly documented in psutil's docs, but is what's to be expected._)
_(No change log entry, since introduced in the same release)_
> Nightly job runner: Fix virtual_memory_percent limit

- opengever/nightlyjobs/runner.py
- opengever/nightlyjobs/tests/test_nightly_job_runner.py
Nightly job runner: Immediately check for time window and system load upon invocation, before even attempting to look up providers and collect jobs. This will result in an unhandled exception every time the runner is invoked outside the time window (from a misconfigured cron job), and allows us to notice these misconfigurations.
(Otherwise a situation with 0 pending jobs would lead to "success", because `NightlyJobRunner.interrupt_if_necessary()` is never called).
For testing purposes I had to introduce an `early_check=True` kwarg to be able to disable this behavior when we want to test for when these conditions happen later, during job execution.
_(No change log entry, since introduced in the same release)_
> Nightly job runner: Immediately check for time window and system load

- docs/HISTORY.txt
- opengever/document/archival_file.py
- opengever/dossier/tests/test_resolve.py
When resolving a dossier, the archival file conversion of documents typically gets triggered multiple times as it is triggered for all contained documents on each dossier (because resolution is recursive), but the main dossier already contains all the documents...
The approach here is to avoid queuing documents several times in the same request, by storing the already queued documents in the annotations on the request and checking if a document is already in the queue before queuing it.
resolves #5596
> Avoid queuing same document conversion more than once in a single request

- docs/HISTORY.txt
- opengever/base/tests/test_personal_bar.py
- opengever/document/tests/test_overview.py
- opengever/meeting/tests/test_proposal_overview.py
- opengever/task/tests/test_actionmenu_viewlet.py
- opengever/webactions/renderer.py
- opengever/webactions/tests/test_webaction_menus.py
- opengever/webactions/tests/test_webactions_menu_items_preparer.py
- opengever/webactions/tests/test_webactions_renderer.py
We add the parameters directly in the `WebActionsSafeDataGetter`, which is used by all `Renderers` and `ItemPreparers`, so that we directly have the parameters passed for all the display locations.
resolves #5586
> Pass context and orgunit as GET parameters to webactions.

- docs/HISTORY.txt
- opengever/task/browser/delegate/utils.py
- opengever/task/tests/test_activities.py
When delegating a task, we fired the activity twice, once manually and once through an event handler (`record_added_activity`). See issue for details.
resolves #5555
> Do not fire task delegating activity twice.

- docs/HISTORY.txt
- opengever/tabbedview/browser/tabs.py
The catalog does not handle sorting on Subjects correctly, so that all items with no Subject will not be returned by the query in that case.
I don't think we can write tests for this.
resolves #5489
> Do not allow sorting on Keywords in dossier and document listings.

- docs/HISTORY.txt
- docs/intern/operations/allgemein.rst
- opengever/base/tests/test_solr.py
- opengever/core/debughelpers.py
- opengever/core/upgrades/20190428144925_add_boolean_index_after_resolve_jobs_pending/upgrade.py
- opengever/document/archival_file.py
- opengever/dossier/config.py
- opengever/dossier/configure.zcml
- opengever/dossier/indexers.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/nightly_after_resolve_job.py
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_resolve.py
- opengever/dossier/viewlets/byline.py
- opengever/nightlyjobs/cronjobs.py
- opengever/nightlyjobs/runner.py
Implement **nightly job to perform jobs after dossier resolution** as part of #5477 (OGIP 55).
The basic mode of operation is like this:
- The `AfterResolveJobs` class tracks (on a flag in the dossier's annotations) whether the `AfterResolveJobs` already have been executed for a particular dossier or not.
- This flag's value is also indexed into a `BooleanIndex`.
- When the nightly job feature flag is enabled, the `AfterResolveJobs` are  **skipped during normal operation**, and the **flag is set** to indicate that they are still pending for that dossier.
- A nightly job is registered that collects all dossiers that have
- `review_state='dossier-state-resolved'`
- `after_resolve_jobs_pending=True`
and then executes the `AfterResolveJobs` for them (which will also set the flag to `False`). …
> Implement nightly job to perform jobs after dossier resolution.

- docs/HISTORY.txt
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/response_description.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_assign.py
- opengever/task/tests/test_response_descriptions.py
When the activity creator is the same as the task responsible we do not need to specify the creator in the reassign activity.
While I was at it, I ported the task reassign activity tests to the integration layer.
resolves #5544
> Adapt task reassign activity message.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/base/configure.zcml
- opengever/base/indexes.py
- opengever/base/tests/test_indexers.py
- opengever/core/profiles/default/catalog.xml
- opengever/core/upgrades/20190418160803_add_has_same_type_children_metadata_column/catalog.xml
- opengever/core/upgrades/20190418160803_add_has_same_type_children_metadata_column/upgrade.py
- solr-conf/managed-schema
* added a new column `has_sametype_children` to the metadata.
* add the `has_sametype_children` to solr.
* add it as a column in the `listing` endpoint
A question that surfaced is whether this is what we really wanted. For example:
* should `has_sametype_children` be `True` for a dossier containing an inactive or trashed dossier?
* should `has_sametype_children` be `True` for a dossier containing a dossier that the current user cannot see?
resolves #5527
> Add has_sametype_children metadata column.

- opengever/nightlyjobs/cronjobs.py
Make sure exceptions during nightly jobs get reported to Sentry.
For that we need to register a [custom excepthook](https://docs.python.org/2/library/sys.html#sys.excepthook) to log unhandled exceptions to Sentry like `ftw.raven` would normally do.
We need to install this one ourselves, because ZPublisher isn't in play during a `bin/instance [zopectl_cmd]` script, so we don't get to piggy-back on `zpublisher_exception_hook_wrapper`.
This isn't perfect: We don't have a context (because no traversal is happening) and we get a URL like `'http://foo'` reported to Sentry, but it should be good enough to at least notice things going wrong.
Example exception in Sentry:
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/23999/
Fixes #5614
> Make sure exceptions during nightly jobs get reported to Sentry.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_protocol.py
This PR display the `changed` date instead the `modified` date for meeting-protocols.
After this change, the meeting-view is using the same implementation as the [document-view](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/browser/overview.py#L367)
Closes #5154
> Display the `changed` date instead the `modified` date for meeting-protocols.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
Filesize and filename are now stored in the catalog.
Because of deferrend reindexing some installations may still miss the values.
Thus we keep the fallback with object lookup.
> Avoid object lookup for filesize and filename

- docs/HISTORY.txt
- opengever/nightlyjobs/cronjobs.py
- opengever/nightlyjobs/runner.py
- opengever/nightlyjobs/tests/test_nightly_job_runner.py
In order to be able to run the nightly jobs outside the time window or when the feature flag is disabled, we add a `force` flag to the `zopectl.command`.
resolves #5613
> Add flag to force execution of nightly jobs.

- opengever/core/testing.py
- opengever/core/tests/base.py
Salvaged from https://github.com/4teamwork/opengever.core/pull/5574
This can still be useful for any scripts which iterate over the modules and rely on the cache, like local fixture amendment test runs or profiling runs.
> Isolate ftw.lawgiver tests onto their own layer

- docs/HISTORY.txt
- opengever/dossier/nightly_after_resolve_job.py
- opengever/dossier/tests/test_resolve.py
- opengever/nightlyjobs/cronjobs.py
- opengever/nightlyjobs/interfaces.py
- opengever/nightlyjobs/runner.py
- opengever/nightlyjobs/testing.py
- opengever/nightlyjobs/tests/test_nightly_job_provider.py
- opengever/nightlyjobs/tests/test_nightly_job_runner.py
Nightly jobs: Log all output to a dedicated self-rotating logfile in `var/log/nightly-jobs.log`.
In order to accomplish that, we set up the logger appropriately in the cronjob wrapper (in other context, a logfile handler would already be present). That properly configured logger then gets passed to the providers by having them adapt a third discriminator, `logging.Logger` (i.e., an instance of the Python stdlib `Logger` class).
>  Nightly jobs: Log all output to a dedicated self-rotating logfile.

- docs/HISTORY.txt
- opengever/task/tests/test_activities.py
Task activity tests that were recently ported to integration layer are now systematically failing on CI. The issue was that the SQL session was not refreshed after updating some activity subscriptions. This is only an issue in the tests, as we are here updating and querying the subscriptions in the same transaction.
>  Fix task activity tests.

- docs/HISTORY.txt
- opengever/core/upgrades/20190409141826_add_document_type_index/upgrade.py
`document_type` is only an index and not in the metadata, but is also indexed in solr. We therefore do not need to update the metadata, but need to explicitly index it in solr.
resolves #5612
> When adding document_type index we do not need to update metadata.

- opengever/core/upgrades/20171026172342_add_new_dossier_manager_role/upgrade.py
- opengever/core/upgrades/20171029220954_make_task_response_changes_persistent/upgrade.py
- opengever/core/upgrades/20171108161558_add_a_boolean_index_for_blocked_local_roles/upgrade.py
- opengever/core/upgrades/20180424145246_fix_date_for_transported_objects/upgrade.py
- opengever/core/upgrades/20180503231632_add_additional_task_state_planed/upgrade.py
- opengever/core/upgrades/20180508155014_add_task_state_skipped/upgrade.py
- opengever/core/upgrades/20180515125607_add_task_transition_in_progress_to_cancelled/upgrade.py
- opengever/core/upgrades/20180604105148_add_proposal_comment_permission/upgrade.py
- opengever/core/upgrades/20180911140637_fix_contenttype_for_ms_publisher_files/upgrade.py
- opengever/core/upgrades/20181019172817_reader_gets_view_on_all_task_states/upgrade.py
- opengever/core/upgrades/20181113161333_fix_content_type_for_open_xml_visio/upgrade.py
- opengever/core/upgrades/20190424164904_add_a_boolean_index_for_blocked_local_roles/upgrade.py
According to the [analysis](https://github.com/4teamwork/opengever.zug/issues/301) we did for the upcoming upgrade in zug, some upgradesteps could be merged or at least marked as deferrable to reduce the upgrade time.
I added my considerations why an optimization is possible in the particular commit message of each commit.
> Upgradestep improvements 2017.7 - 2019.2

- docs/HISTORY.txt
- opengever/core/upgrades/20190506084117_reindex_file_extension_for_mails/upgrade.py
- opengever/document/indexers.py
- opengever/mail/tests/test_indexers.py
The indexer uses the file_extension of the original_message, if exists.
Provides a deferrable upgradestep which reindexes the file_extension for all mails.
Closes #5623.
> Add file_extension indexer for mails.

- docs/HISTORY.txt
- opengever/api/tests/test_search.py
- opengever/base/monkey/patches/filter_trashed_from_catalog.py
- opengever/testing/helpers.py
- opengever/trash/tests/test_catalog.py
- opengever/trash/trash.py
In order to be able to query for recently trashed documents from RIS, we need to make sure that
- **Our automatic `trashed` filter can be overridden**.
So our patch must only inject the filter for non-trashed docs if a query against the `trashed` index isn't already present (by looking at both `REQUEST` and `kw` in the patched `searchResults()`)
- the **modification date is updated and indexed** correctly
With these in place, a query via the REST API like this works:
```http
GET .../dossier-43/@search?portal_type=opengever.document.document&trashed:boolean=True
```
(Because `trashed` in GEVER is a `FieldIndex` and not a `BooleanIndex`, `plone.restapi` can't automatically cast the query arguments. Therefore a [ZPublisher type hint](https://zope.readthedocs.io/en/latest/zdgbook/ObjectPublish …
>  Trash: Update and reindex modification date when trashing documents.

- docs/HISTORY.txt
- opengever/base/indexes.py
The has_children indexer was making a catalog query, which leads to processing the indexing queue in the middle of operations like creating a folderish object. This led to duplicate brains in the catalog. At least that is my best guess as to what the problem was...
I could not reproduce the problem in tests (tried Integration and Functional tests), but I can confirm that I could reproduce the two issues locally and that they do not happen anymore with these changes.
resolves #5635 #5632
> Fix has_children indexer which lead to duplicate brains.

- opengever/base/browser/resources/tooltip.js
☠️ I tested this on chrome, safari, IE11 and on iPad running iOS 12.1. The revert commit: https://github.com/4teamwork/opengever.core/pull/5117 documents that there were issues for so-called hybrid devices. I'm not entirely sure how those devices behave in terms of event order. So this solution may not work for such devices. I had no access to such a machine to test that out. So before merging the pull request these changes should first be tested on a real hybrid device.
Closes https://github.com/4teamwork/opengever.core/issues/4809
Uses a flag which will be set to true when the user touches the screen. So when the mouseover event is triggered after the touchevent, the tooltips are not initialized. On the other hand, when the user does not touch the screen, the touchevent is not fired so …
> Fix preview tooltip for different input types.

- docs/HISTORY.txt
- docs/public-fr/chapitre13-deroulements-standards.rst
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po
Found that we were using a 3rd version `processus standard`. Hope I caught them all...
resolves #5634
> Concistently use "déroulement standard" for tasktemplates in French.

- opengever/core/upgrades/20190507160417_remove_dossier_inheritance_for_workspaces/types/opengever.workspace.folder.xml
- opengever/core/upgrades/20190507160417_remove_dossier_inheritance_for_workspaces/types/opengever.workspace.workspace.xml
- opengever/core/upgrades/20190507160417_remove_dossier_inheritance_for_workspaces/upgrade.py
Dieser PR behebt einen Fehler im Upgradestep von folgendem PR: https://github.com/4teamwork/opengever.core/pull/5578/
1. Die Type-Files waren nicht im `types` Ordner und wurden somit garnicht ausgeführt
2. die Behaviors dürfen nicht gelöscht werden (purge). Dies wäre der Fall gewesen, wenn das Profil korrekt importiert worden wäre
> Fix broken upgradestep introduced in es-5563-remove-dossier-inheritance-for-workspaces

- docs/HISTORY.txt
- opengever/task/browser/complete.py
- opengever/task/util.py
Avoid unnecessary workflow changes syncs, when resolve a multi adminunit task. Because this leads do erorrs or incomplete task completions (not delivered documents etc.)
Unfortunately adding a test which checks for this issues was not possible, because we can not completly test the multi-adminunit communication.
Closes #5651
> Fix resolving of multi-adminunit tasks.

- docs/HISTORY.txt
- opengever/officeconnector/service.py
- opengever/oneoffixx/command.py
- opengever/oneoffixx/tests/test_oneoffixx.py
Seems I actually built all the machinery we needed, but then forgot to to actually plug it in in the end.
Original PR: https://github.com/4teamwork/opengever.core/pull/4282
🐷 will get fed.
> Fix the setting of the content-type for Oneoffixx templates

- docs/HISTORY.txt
- opengever/nightlyjobs/cronjobs.py
This extends our custom exception hook so that any unhandled exception also gets written to `var/log/nightly-jobs.log` (not just reported to Sentry).
> Nightly jobs: Also log exceptions to logfile, not just Sentry.

- docs/public/user-manual/dossiers/bearbeiten.rst
- docs/public/user-manual/img/media/img-dossiers-12.png
- docs/public/user-manual/img/media/img-dossiers-13.png
With #4264 we changed the action translation from `Eigenschaften anzeigen` to `Metadaten anzeigen`.
https://basecamp.com/2768704/projects/14549453/todos/388183457
> Update documentation for the `Metadaten anzeigen` action

- docs/public/user-manual/dokumente/bearbeiten.rst
- docs/public/user-manual/img/media/img-dokumente-7.png
There was an old screenshot used, which showed also the no longer existing `Auschecken / Bearbeiten` acction above the title.
See https://basecamp.com/2768704/projects/14549453/todos/388184388.
> Update Dokument-Metadaten bearbeiten docu screenshot. 

- docs/HISTORY.txt
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/upgrades/20190507133725_add_a_configurable_scope_for_oneoffixx_o_auth2_grant_requests/registry.xml
- opengever/core/upgrades/20190507133725_add_a_configurable_scope_for_oneoffixx_o_auth2_grant_requests/upgrade.py
- opengever/oneoffixx/api_client.py
- opengever/oneoffixx/interfaces.py
- opengever/oneoffixx/tests/test_oneoffixx.py
Extranet issue:
https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/714
As per potential upcoming changes in their API, we've been alerted to make more things configurable at runtime.
> Oneoffixx configurability changes

- docs/HISTORY.txt
- opengever/base/tests/test_favorite.py
- opengever/document/configure.zcml
- opengever/document/handlers.py
- opengever/testing/integration_test_case.py
Since #4581 the document icon of documents marked as favorite gets updated on checkout and checkin. But on checkout-cancel the icon gets not updated, which leads in a wrong inconsistent document icon. This change solves this issue.
> Update favorite-icon after cancel a document checkout.

- docs/HISTORY.txt
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/upgrades/20190515134907_remove_oneoffixx_baseurl_from_the_registry/registry.xml
- opengever/core/upgrades/20190515134907_remove_oneoffixx_baseurl_from_the_registry/upgrade.py
- opengever/core/upgrades/20190515135724_add_new_oneoffixx_configurability_values_to_the_registry/registry.xml
- opengever/core/upgrades/20190515135724_add_new_oneoffixx_configurability_values_to_the_registry/upgrade.py
- opengever/oneoffixx/api_client.py
- opengever/oneoffixx/interfaces.py
- opengever/oneoffixx/tests/test_oneoffixx.py
We discovered we cannot currently handle a path prefix in regards to where the Oneoffixx web service(s) are mounted.
I've split the configuration up a bit with sane defaults. Now the only thing which, normally needs to get configured, is the backend hostname. The second most common thing to configure is the path prefix.
> Split up Oneoffixx configurability

- docs/HISTORY.txt
- opengever/tabbedview/browser/generic_with_bumblebee_viewchooser.pt
- opengever/tabbedview/tests/test_document_listing.py
When selecting a filter (keyword, state) with lead to no results, the filters should still be visible, otherwise deleting the filter is not possible.
se https://basecamp.com/2768704/projects/12554551/todos/388673626.
> Show filters also on no contents page in document listings.

- docs/HISTORY.txt
- opengever/core/upgrades/20190520140249_make_subjects_column_non_sortable/upgrade.py
With #5601 the subject column of dossier listings has been marked as not sortable, but for users which have their own tabbeview setting in the dictstorage, the column was still sortable. Therefore we need to update those dictstorage entries.
> Make subject column non-sortable in storred dictstorage settings.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/tests/test_meeting_view.py
A user with edit permissions on the meeting would not be able to view the meeting if the meeting dossier is closed. This is to avoid problems with buttons in the meeting view that do not work because of lack of edit permissions on the meeting dossier. Nevertheless when the meeting is closed, it should be visible for a user with edit permissions even when the meeting dossier is closed.
When a user with edit permissions goes on a closed meeting with a closed meeting dossier, there is at least one button that will not work, the one to generate the protocol acceptance proposal.
resolves #5680
> Allow viewing closed meeting when meeting dossier is closed.

- docs/HISTORY.txt
- opengever/core/upgrades/20181012203011_make_oneoffixx_textline_configs_optional_so_they_can_be_unset/registry.xml
- opengever/core/upgrades/20190515134907_remove_oneoffixx_baseurl_from_the_registry/registry.xml
- opengever/core/upgrades/20190515134907_remove_oneoffixx_baseurl_from_the_registry/upgrade.py
- opengever/core/upgrades/20190520140249_make_subjects_column_non_sortable/upgrade.py
- Remove outdated and no longer working upgradestep 2019.2. Because the IOneoffixxSettings has been changed and no longer provides an field base_url. Closes #5679.
- Make dictostorage migration, for the subject column more "fail-safe".
> Upgradestep cleanup 2019.2

- docs/HISTORY.txt
- opengever/inbox/forwarding.py
- opengever/task/browser/forms.py
- opengever/task/tests/test_revoke_permissions.py
The recently added revoke_permission fields, wasn't handled in the add and edit forwarding forms, therefore the creation of a forwarding, when the feature flag was disabled, did not worked.
Closes #5685
> Fix revoke_permission field and validation in the fowarding forms.

- docs/HISTORY.txt
- opengever/contact/browser/byline.py
- opengever/contact/browser/configure.zcml
- opengever/ogds/base/tests/test_team_details.py
There is no sensible data which should be displayed in the team 
details view. So we register an hidden byline for teams.
See https://basecamp.com/2768704/projects/14549453/todos/388925855
> Hide byline for the teams

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/tasks.rst
- opengever/api/configure.zcml
- opengever/api/response.py
- opengever/api/task.py
- opengever/api/tests/test_task.py
- opengever/testing/integration_test_case.py
A GET request on a task, now contains the task history in the key `responses`. 
Closes #5676 
See documentation (part of the PR) for further information.
> Extend task API serialization with responses data.

- docs/HISTORY.txt
- opengever/api/transition.py
- opengever/dossier/activate.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_activate.py
In the same spirits as the other PRs for #5432:
* We add the RESTAPI endpoint to properly handle the activate dossier transition.
* I refactored the tests of the dossier activate transition to allow for easier code reuse and have the same tests for the transition via browser or via RESTAPI.
This is part of https://github.com/4teamwork/opengever.core/issues/5432
> Correctly handle dossier activation through RESTAPI

- docs/HISTORY.txt
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core-manual.pot
- opengever/core/locales/opengever.core.pot
- opengever/trash/locales/de/LC_MESSAGES/opengever.trash.po
- opengever/trash/locales/fr/LC_MESSAGES/opengever.trash.po
- opengever/trash/remover.py
- opengever/trash/tests/test_remove_conditions.py
We improve the error message when a document cannot be deleted because it is reference by another item. Instead of only listing the titles of the items that reference the document, we also show their portal type.
I translated the portal types for documents, tasks and proposals. Is there any other portal type that can reference a document?
**Example for a document with a task, a proposal and a document referencing it**
resolves #5592
> Improve error message when trying to delete a referenced document.

- docs/HISTORY.txt
- opengever/api/transition.py
- opengever/dossier/deactivate.py
- opengever/dossier/exceptions.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_deactivate.py
- opengever/dossier/tests/test_resolve.py
We add the RESTAPI endpoint to properly handle the deactivate dossier transition. As for dossier resolution, the transition is handled by custom transition handler. We do not need to use a `TransitionExtender` here, as there are no jobs that need to be executed after transition to the inactive state.
I refactored the tests of the dossier deactivate transition to allow for easier code reuse and have the same tests for the transition via browser or via RESTAPI.
I also added a test that trying to resolve a dossier non-recursively through the RESTAPI is not allowed. It seemed that this was not tested, or at least I did not find a test for it. 
This is part of https://github.com/4teamwork/opengever.core/issues/5432
> Correctly handle dossier deactivation through RESTAPI

- docs/HISTORY.txt
- opengever/api/transition.py
- opengever/dossier/reactivate.py
- opengever/dossier/tests/test_reactivate.py
We add the RESTAPI endpoint to properly handle the reactivate dossier transition. As for dossier resolution, the transition is handled by custom transition handler. We do not need to use a `TransitionExtender` here, as there are no jobs that need to be executed after the transition to the active state.
I refactored the tests of the dossier reactivate transition to allow for easier code reuse and have the same tests for the transition via browser or via RESTAPI. I also ported them to the `IntegrationTestCase`
Note: reactivating a dossier that is inactive does not throw an error, but that was already that way before... I made an issue for this https://github.com/4teamwork/opengever.core/issues/5638
This is part of https://github.com/4teamwork/opengever.core/issues/5432
> Correctly handle dossier reactivation through RESTAPI

- docs/HISTORY.txt
- opengever/core/upgrades/20180912145057_add_a_registry_setting_for_oneoffixx_baseurl/registry.xml
- opengever/core/upgrades/20180912145057_add_a_registry_setting_for_oneoffixx_baseurl/upgrade.py
The field has been removed lately, thus adding it will fail.
We have already cleaned up similar problems in https://github.com/4teamwork/opengever.core/pull/5683.
The issue was introduced with https://github.com/4teamwork/opengever.core/pull/5666 when the field was introduced.
Needs backport to `2019.2.x`.
> Drop no longer working oneoffixx upgrade.

- docs/HISTORY.txt
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/reactivate.py
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_reactivate.py
- opengever/dossier/tests/test_resolve.py
Because when resolving a dossier we skip inactive dossiers and when reactivating a dossier we skip all dossiers in states different from resolved, it was possible to resolve an inactive dossier and reactivate an active or an inactive dossier (while this would basically do nothing). We now prevent this by making sure that the transition can be executed on the main dossier.
resolves #5638
> Only allow dossier transitions that are possible on the main dossier

- solr-conf/managed-schema
This reverts commit 0c12bfda739d4c79240dc1a22e749a24866ba182.
The change has negative side effects to other searches, for example on short query strings containing `-` like `m-039` or something similar. See https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/612#rb49671ef for a further description.
> Revert "Split search terms at non-alphanumeric characters" #4895

- docs/HISTORY.txt
- opengever/api/tests/test_dossier_workflow.py
- opengever/api/transition.py
- opengever/dossier/tests/test_activate.py
- opengever/dossier/tests/test_reactivate.py
- opengever/dossier/tests/test_resolve.py
Certain dossiers transitions should not be allowed through the RESTAPI, as they are handled by a specific process in GEVER. This is the case of all the transitions linked to the offer/archive process.
We now reply to such requests with a 400 `BadRequest`.
This is part of and closes #5432
> Forbid transitions linked to dossier offer process through RESTAPI.

- docs/HISTORY.txt
- docs/public/admin-manual/aussonderung.rst
- opengever/sharing/browser/admin_list.py
- opengever/sharing/tests/test_blocked_local_roles_listing.py
Testing is a bit weak I guess. There was a test which was probably flaky because we were not sorting the list of blocked local roles. Modifying the reference number of an object and checking that the order is updated would be better, but did not find a simple way of doing this and it did not quite seem worth investing more time in this.
resolves #5670
> Sort BlockedLocalRolesList on reference number.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/meeting.py
- opengever/meeting/model/query.py
- opengever/meeting/tests/test_period_query.py
We were displaying the year of the current period as prefix to the agendaitem decision numbers. Instead we now the title of the period matching the date of the meeting as prefix. 
This is a bit better, but ultimately we should make sure that each meeting gets assigned to a given period as soon as the decision numbers and meeting numbers are generated (when the meeting is held), as these depend on the period. This will be tackled separately though (see https://github.com/4teamwork/opengever.core/issues/5200)
I also modified the displayed meeting number, as this should also depend on the period (and until now we simply displayed the year of the meeting...).
**meeting display if there is a period matching the committee and date of the meeting**
**meeting display if there is no period …
> Prefix agendaitem decision numbers and meeting number by correct period title

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
So the listing endpoint supports now filtering on file_extension and document_type. Closes https://github.com/4teamwork/gever-ui/issues/159.
> Extend listing endpoint fields with file_extension and document_type.

- docs/HISTORY.txt
- opengever/task/response_syncer/deadline.py
- opengever/task/tests/test_deadline_modification.py
Skip forwarding predecessors. Forwarding predecessors are already closed and stored in the yearfolder, and should not longer be changed.
Fixes #5710
Needs backport to `2019.2`
> Do not sync deadline modifications to forwarding predecessors.

- docs/HISTORY.txt
- opengever/sharing/browser/resources/sharing.js
- opengever/sharing/browser/sharing.py
- opengever/sharing/browser/templates/sharing.html
- opengever/sharing/tests/test_sharing.py
_Harvest: `[3.2.2.1] OneGov GEVER` - `CR 2019.3 SG`_
If the `group_title_ldap_attribute` is configured, we also search that field. This makes sense because thats the value which is visible and displayed as group title. See https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/762
Besides that I also added a spinner, similar to the save button, which is shown when searching for a principal,  to give the user feedback when the search request takes some time.
> Support searching on group description in sharing form.

- docs/HISTORY.txt
- opengever/tabbedview/browser/generic_with_bumblebee_viewchooser.pt
- opengever/tabbedview/browser/generic_with_filters.pt
- opengever/tabbedview/browser/selection_with_filters.pt
- opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/opengever.tabbedview.pot
The label of the keyword-filter has not been implemented as a translatable label, and also another name was used for it (`Schlagworte` instead of `Schlagwörter`).
Before:
After:
See https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/163
> Translate keyword-filter label.

- bin/mtest
When the name of a test class TC1 is contained in the name of another test class TC2 from the same python file, the tests for TC1 are potentially run more than once by mtest (as TC1 is also matched when we try to run the test TC2). As matching of the search patterns is done on strings of the form 'testname (test.class.qualified.name)', we can do exact matching if we include the parenthesis in our search patterns.
> Avoid certain test classes being run multiple times.

- .github/pull_request_template.md
We would like to make the existing pull-request checklist more visible. In our opinion the best way to do this at the moment is by creating a pull-request template for github.
We move the existing pull request checklist from the wiki (currently at https://github.com/4teamwork/opengever.core/wiki/Prozess:-PullRequest-Review-Checkliste, will be removed once merged) and enrich it with https://basecamp.com/2768704/projects/9430593/todos/320310258. I've chosen the `.github` folder as that seems to be the convention adopted by other projects, e.g. https://github.com/4teamwork/ris.
I have compressed the list a bit, so we can start with something "simple". If there is an important point i forgot please let me know.
> Add pull request/review checklist.

- docs/intern/operations/allgemein.rst
The nightly cron jobs need to run with the zope user's environment variables. Because these are not normally sourced in a crontab, we prefix the nightly job command with `bash -l -c` in order to run them in a login shell, which will load the environment variables.
This is of particular importantance for the nightly jobs for at least two reasons:
- When triggering archival PDF generation via bumblebee, the `http_proxy` and `no_proxy` environment variables must be set correctly, otherwise requests may fail (with 502 notresolvable / BadStatusLine errors).
- We're attempting to log errors from the nightly jobs to  Sentry. For that to work, the `RAVEN_DSN` env variable needs to be set properly.
> Docs: Update nightly cron jobs example

- docs/HISTORY.txt
- opengever/api/document.py
- opengever/api/tests/test_document.py
- opengever/document/base.py
- opengever/document/indexers.py
Currently the `file_extension` is only accessible on the `@listing` endpoint. So we don't get the information when creating a document. So an additional fetch would be necessary. Closes #5718.
> Include file_extension in API representation of documents.

- docs/HISTORY.txt
- opengever/activity/tests/test_mail.py
- opengever/activity/tests/test_plone_center.py
- opengever/advancedsearch/tests/test_search.py
- opengever/base/tests/test_indexers.py
- opengever/inbox/tests/test_activities.py
- opengever/inbox/tests/test_workflow.py
- opengever/latex/tests/test_dossiertasks.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_assign.py
- opengever/task/tests/test_assign_to_dossier.py
- opengever/task/tests/test_delegate.py
- opengever/task/tests/test_forms.py
- opengever/task/tests/test_localroles.py
- opengever/task/tests/test_private_task.py
- opengever/task/tests/test_redirector.py
- opengever/task/tests/test_response_descriptions.py
- opengever/task/tests/test_revoke_permissions.py
- opengever/task/tests/test_sequential_task_process.py
- opengever/tasktemplates/tests/test_tasktemplate.py
- opengever/tasktemplates/tests/test_trigger.py
- opengever/testing/__init__.py
- opengever/testing/testbrowser_responsible_user_widget.py
The convolution around the `AsyncKeywordWidget`, task template wizards and the registration-at-module-init-time magic of the `ftw.testbrowser` widgets threw me off for a bit.
This PR adds easier handling for the most common use case for the responsible fields, users. It can later be further amended to handle teams and inboxes.
Closes #5330
> Add an ftw.tesbrowser widget for filling responsible(s) in the tests

- docs/HISTORY.txt
- opengever/api/livesearch.py
Only strip Virtual Host Monster path if we are actually using the plone.restapi
SearchHandler.
> Fix livesearch endpoint when using Solr

- docs/HISTORY.txt
- opengever/ogds/base/sync/ogds_updater.py
Fix encoding issue in `OGDSUpdater`'s error logging.
When logging errors about a referenced user not being found in LDAP, the error logging blew up with an encoding error when a user with non-ASCII character in its DN was logged, because a UTF-8 bytestring was formatted into a unicode message.
This changes all the format strings to use the `repr()` of the respective values to avoid such errors in the future.
(Discovered via https://extranet.4teamwork.ch/betrieb/tracker/880)
Sentry Issue: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/30789/
> Fix encoding issue in OGDSUpdater's error logging.

- docs/HISTORY.txt
- opengever/dossier/archive.py
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_archiver.py
The archive form relied on the `DossierResolveView` already **validating dossier resolution preconditions**, and presenting error messages to the user. Because that wasn't the case any more after the refactoring of the whole dossier resolution process, the archive form was broken when preconditions weren't fulfilled.
This change fixes this by:
- Refactoring the dossier resolution code so that:
- Raising the appropriate exceptions is done in a single method on the resolver, `raise_on_failed_preconditions()` 
- Constructing and displaying error messages for classic views, including redirecting to the appropriate context, is done in a mixin class. That way it can be reused in the archive form.
- Handling violated preconditions in both
- The `DossierResolveView`, before even redirecting to …
> Fix validation of resolve preconditions in archive form

- docs/HISTORY.txt
- docs/public/_static/custom.css
- docs/public/dev-manual/api/content_types.rst
- docs/public/dev-manual/api/schemas/opengever.task.task.inc
- docs/schema-dumps/opengever.task.task.schema.json
- opengever/base/schemadump/config.py
- opengever/base/schemadump/field.py
- opengever/base/schemadump/tests/test_schemadumps.py
As currently published to https://docs.onegovgever.ch/dev-manual/api/content_types/#aufgabe
I had to implement a workaround of the `task_type`s vocabulary in the schema dumper: The [`getTaskTypeVocabulary()`](https://github.com/4teamwork/opengever.core/blob/master/opengever/task/util.py#L66-L79) function incorrectly wraps the underlying VDEX vocabulary, so the reference to the VDEX gets completely destroyed and we can't determine any more whether term order is significant or not, leading to flaky tests (if not addressed).
> Docs: Add tasks to documented content types

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/overrides.zcml
This ensures that it will be loaded with the currently pinned version of `plone.restapi` (which doesn't have it's own `ChoiceFieldDeserializer` yet) and will also not cause conflicting configurations with `plone.restapi:master`, which now [does have a `ChoiceFieldDeserializer`](https://github.com/plone/plone.restapi/blob/25446902caaec5b7e930f8c0d8bc198e5ddf7ed3/src/plone/restapi/deserializer/dxfields.py#L117-L130).
That way we make sure that GEVER tests against `plone.restapi` are green again and don't shadow problems that might be introduced in the upcoming restapi sprint.
> Register ChoiceFieldDeserializer using overrides instead of configure ZCML

- opengever/document/tests/test_checkout.py
- opengever/dossier/tests/test_overview.py
- opengever/meeting/tests/test_committee.py
- opengever/officeconnector/tests/test_api_mail_attach.py
So, I started hunting for quick wins in test speeds based on the output of three log files:
[2019-06-13-functionaltestperf.log](https://github.com/4teamwork/opengever.core/files/3290314/2019-06-13-functionaltestperf.log)
[2019-06-13-integrationtestperf.log](https://github.com/4teamwork/opengever.core/files/3290315/2019-06-13-integrationtestperf.log)
[2019-06-13-othertestperf.log](https://github.com/4teamwork/opengever.core/files/3290316/2019-06-13-othertestperf.log)
I quickly hit a wall as to some event ordering issue in the test server self test:
https://ci.4teamwork.ch/builds/249683/tasks/409536
The best guess is that the SQLite DB Engine gets initialized before ZCML is registered. We have an event for forcibly enabling save points for integration testing. …
> Minor cleanups for cleaner test output / linter in tests

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/participation.rst
- opengever/api/configure.zcml
- opengever/api/participation.py
- opengever/api/tests/test_participation.py
- opengever/api/tests/test_vocabularies.py
- opengever/workspace/configure.zcml
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/participation/__init__.py
- opengever/workspace/participation/browser/manage_participants.py
- opengever/workspace/participation/browser/participants_view.py
- opengever/workspace/permissions.zcml
- opengever/workspace/tests/test_vocabularies.py
- opengever/workspace/tests/test_workspace_manage_participants.py
- opengever/workspace/vocabularies.py
Dieser PR implementiert die REST-API für Beteiligungen.
Die alte API besteht weiterhin. Die neue API verwendet hauptsächlich die alte Implementation.
closes #5589
> Teamraum Beteiligungen - REST-Endpoints

- docs/HISTORY.txt
Dieser PR schiebt den Changelog-Eintrag von PR #5599 an die richtige Stelle.
Ich habe nach einem Rebase vergessen, das Changelog zu kontrollieren. In der Zwischenzeit gab es bereits neue Releases.
related to #5589
> Move changelog entry to the proper position

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/participation.py
- opengever/api/tests/test_participation.py
- opengever/api/tests/test_workspace.py
- opengever/api/workspace.py
- opengever/workspace/participation/browser/my_invitations.py
- opengever/workspace/tests/test_my_invitations.py
Das GEVER-UI benötigt einen Endpoint zum Anzeigen von Teamraum-Einladungen sowie zum Annehmen und Ablehnen von Einladungen.
Dieser PR implementiert die entsprechenden Endpoints.
Issuer: https://github.com/4teamwork/gever-ui/issues/21
> REST-API: Handle workspace invitations

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
We allow range queries on the deadline in the listing endpoint. This is necessary for the new frontend.
resolves #5743
> Allow range queries on deadline in listing endpoint.

- opengever/activity/__init__.py
- opengever/activity/browser/settings.py
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
The notification settings view was not working for zopemaster (see https://github.com/4teamwork/opengever.core/pull/5730), which gets fixed with this PR. Users with no entry in the ogds, like zopemaster, are now handled separately. Default configurations are shown for them and an error message is displayed if they try to save a personal configuration.
**notification settings view for zopemaster after trying to save a config change. An error message is displayed and default values are shown for the configurations**
closes #5762 
*I did not translate the error message, which is only meant for zopemaster*
*No changelog, as there is already a CL entry for these settings in the same release*
> Fix notification settings view for zopemaster.

- docs/HISTORY.txt
- versions.cfg
In order to get rid of installing ruby dependencies via buildout and to get rid of https://raw.githubusercontent.com/4teamwork/gever-buildouts/master/ruby-gems.cfg we'd like to switch to the sablon and nokogiri versions provided in http://rpm.4teamwork.ch/el7/x86_64/sablon-0.3.1-1.el7.x86_64.rpm as a first step.
- I have locally validated that our example files still can be generated from sablon and that they still look the same.
- I have validated the same thing with a wider set of examples from production.
> Bump sablon and nokogiri to RPM versions.

- docs/HISTORY.txt
- solr-conf/solrconfig.xml
- versions.cfg
Update Solr and ftw.solr to latest versions.
ftw.solr now performs soft commits to allow near real time (NRT) searching.
This make documents available for search almost immediately after being indexed.
E.g. after uploading, documents are now visible immediately in listings in the new frontend.
Apart from that, Solr 8.1.1 comes with various bug fixes and improvements. See https://lucene.apache.org/solr/8_1_1/changes/Changes.html
Other changes:
- Tike exceptions are now properly ignored (e.g. with encrypted documents)
- Increased auto commit max time to 60s.
> Solr update

- docs/HISTORY.txt
- opengever/base/handlers.py
If an object has been copy & pasted, we need to reindex some fields. The `IObjectCopiedEvent` is too early to do that though, because at that point the object doesn't have a full AQ chain yet. We therefore just mark the object during `IObjectCopiedEvent`, and do the reindexing later during `IObjectAddedEvent`.
This fixes copy & pasting in Solr-enabled deployments.
Fixes #5765
> Avoid reindexing 'created' during IObjectCopiedEvent

- docs/HISTORY.txt
- opengever/core/upgrades/20190628142921_add_index_for_task_principal/upgrade.py
- opengever/globalindex/model/task.py
This fixes performance Issues on task listings when using an oracle backed for the OGDS DB (closes 4teamwork/opengever.zug#313). Because of the NLS_SORT and NLS_COMP settings we use for oracle backends (see https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/events.py#L6-L11), we need to make sure that oracles indexes supports linguistic sort.
Upgradestep: The PR provides a  schema migration which adds the index if it's not existing yet.
_--> War leider nicht möglich. Stellt aber m.E. keine Problem dar._
> Add linguistic index on task principal column for oracle backends.

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
For the new GEVER UI we need the possibility to optionally query for facet available values on the listing endpoint. 
resolves #5738
> Add optional facet values and counts search to listing endpoint

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
This also excludes the searchroot from **Solr results** for the `@listing` endpoint _(like we already do for Catalog results)_.
It filters the search context by adding a `-UID: <uid>` filter query to the Solr query. For contexts that don't have an UID (like the Plone site root), this filter query is omitted. This shouldn't be an issue however, because the Plone site itself is not indexed in Solr.
Fixes #5757
> @listing endpoint: Exclude searchroot from Solr results.

- docs/HISTORY.txt
- opengever/core/upgrades/20190628142921_add_index_for_task_principal/upgrade.py
The `self._has_index()` method that was used before is one that only exists on the `IdempotentOperations` class, which we don't currently use for Oracle. So this upgrade step (introduced in #5767) didn't quite work yet when executed on Oracle.
For this specific upgrade step, we therefore test for index presence directly using a simple SQL query.
_(Tested (by hand) on Oracle)_
_(bestehende angepasst)_
> Fix upgrade step that adds linguistic index for task principal

- docs/HISTORY.txt
- opengever/base/monkey/patches/exception_formatter.py
If the plone site does not exist, e.g. for errors that happen while we install the plone site in the first place, displaying the exception would fail with `CannotGetPortalError`.
We change the permission check to use the zope application and retrieve the application from the request. Gracefully hide the trace in case of a missing request or if the app cannot be retrieved (which should not happen).
Fixes #5758.
There don't seem to be any automated test for this. I have manually tested that formatting still works as desired by stopping postgres on a running site and when attempting to setup a new site.
> Dont require plone site in exception formatter.

- docs/public/dev-manual/api/searching.rst
The widget somehow made its way to the middle of the page where it disrupts the page/docs. Move it to the bottom again.
> Display disqus widget at bottom of page.

- docs/HISTORY.txt
- opengever/task/browser/forms.py
- opengever/task/browser/overview.py
- opengever/task/browser/templates/overview.pt
- opengever/task/handlers.py
- opengever/task/task.py
- opengever/task/tests/test_overview.py
- opengever/task/tests/test_sequential_task_process.py
A subtask of a sequential task should not be handled as a sequential task rather than as a simple subsubtask. Because a subsubtask is not part of the sequential order, but is more a splitting of a specific task of the sequential process. When resolving a subsubtask  it should no start the next task of the sequential process neither should be subsubtasks displayed as a sequence.
This PR corrects the misbehaviour during the creation as well as during the representation of such subsubtasks within task sequences. Closes #5821 
_Ja, Weiterleitungen sind davon aber nicht betroffen, da bei Standardabläufen ausschliesslich Aufgaben erstellt werden._
> Fix creation and handling for subtasks of sequential tasks.

- base-plone-4.3.x.cfg
- base-testserver.cfg
- docs/HISTORY.txt
- opengever/testing/patch.py
- opengever/testing/tests/test_collective_indexing_active.py
We need to enable `collective.indexing` during tests in order to create Solr tests (because `ftw.solr` integrates itself by providing an `IIndexQueueProcessor`).
So we need `collective.indexing`'s pluggable `IndexQueueProcessor` mechanism, but we don't want the unpredictable behavior of reindexes that are deferred until the end of the transaction during tests (or the queue getting flushed at arbitrary points).
We therefore patch the `IndexQueue`'s operation methods so that they always immediately process the queue after being called.
Closes #5801
**Note**:
I checked for any negative effects on test runtime - wallclock time for tests on CI stayed exactly the same.
> Enable c.indexing during tests, but patch it to not defer operations:

- docs/HISTORY.txt
- opengever/base/browser/gever_state.py
- opengever/base/tests/test_gever_state.py
Currently the properties action is shown for teams. This is incorrect as teams don't implement properties view. Therefore we disable the action.
Fixes #5827.
> Disable properties action for teams.

- docs/HISTORY.txt
- opengever/bundle/console.py
- opengever/setup/sections/reindexobject.py
Disable collective.indexing during bundle import if Solr is disabled.
Also remove confusing `--skip-solr` option
The option only disables Solr in the reindex section.
But there are other places
(e.g. `opengever.base.security.reindex_object_security_without_children`)
where Solr is still called explicitly.
To avoid Solr indexing, it should be disabled in the registry.
Btw, the option is misnamed. If the option is provided, `skip_solr` has a
value of `False`.?! If the option is omitted, the value is `True`.
> Bundle import disable collective indexing

- bin/qa
- docs/HISTORY.txt
At some point we had a (opengever-core-) custom linter config. Apparently we don't anymore, and the `bin/qa` script doesn't properly handle this:
The variable with files that will be checked (`$unexcluded_changed_files`) only ever gets set in the `if` clause that handles possible excludes from a linter config. If no linter config is present, that variable stays empty all the time and the script claims `Found nothing to complain about. Well done!`.
Fixes #5778
> Fix QA tests

- docs/HISTORY.txt
- opengever/api/tests/test_listing.py
- opengever/core/profiles/default/types/opengever.workspace.todo.xml
- opengever/core/upgrades/20190719100928_add_numbering_and_naming_behaviors_to_to_dos/types/opengever.workspace.todo.xml
- opengever/core/upgrades/20190719100928_add_numbering_and_naming_behaviors_to_to_dos/upgrade.py
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
- opengever/workspace/behaviors/configure.zcml
- opengever/workspace/behaviors/namefromtitle.py
- opengever/workspace/configure.zcml
- opengever/workspace/participation/browser/manage_participants.py
- opengever/workspace/sequence.py
- opengever/workspace/subscribers.py
- opengever/workspace/tests/test_todo.py
- opengever/workspace/tests/test_todolist.py
- opengever/workspace/tests/test_workspace_manage_participants.py
- opengever/workspace/tests/test_workspace_sources.py
- opengever/workspace/todo.py
In this PR we:
* Add the standard naming and numbering behavior to `ToDo`s
* Add a hard limit of the number of `ToDo`s allowed in a single workspace
* Add two new ogds sources: `PotentialWorkspaceMembersSource` and `ActualWorkspaceMembersSource` and use them respectively for the users that can be invited into the workspace and users that can be set as responsibles on a `ToDo`
* Remove special handling of workspaces in `AllUsersInboxesAndTeamsSource`, which is not needed anymore as it was only used for tasks in workspaces, which are now not allowed anymore (see https://github.com/4teamwork/opengever.core/pull/5808).
I also improved some tests of other ogds sources, added tests for the `ToDo`'s API and a few other small fixes.
Overall the ogds sources seem more complex than necessary, have …
> Backend for todos

- docs/HISTORY.txt
- docs/public/dev-manual/api/notifications.rst
- opengever/activity/model/notification.py
- opengever/api/tests/test_notifications.py
This includes `actor_id` and `actor_label` in the responses of the `@notifications` endpoint.
Since the ID is already included in the `actor_id` field, the label is rendered with `principal=False`, so it will contain `Lastname Firstname` instead of `Lastname Firstname (user.id)`.
Closes #5834
> Include actor_id and actor_label in @notifications endpoint responses.

- opengever/examplecontent/profiles/municipality_content/opengever_content/01_initial_dossiers.json
Part of https://github.com/4teamwork/opengever.core/issues/5167.
This quality of live PR adds initial content for disposition so that we can easily create disposable content for local development. It creates a dossier with one document which has its retention period expired and which is already in closed state. It should pop up when you add a new disposition on your repository.
_I have opted to not create the disposition itself yet, however that could be amended in a later PR if deemed useful._
> Add a disposable dossier to the initial content.

- docs/HISTORY.txt
- opengever/disposition/browser/configure.zcml
- opengever/disposition/browser/ech0160.py
- opengever/disposition/browser/overview.py
- opengever/disposition/disposition.py
- opengever/disposition/handlers.py
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- opengever/disposition/tests/test_disposition.py
- opengever/disposition/tests/test_ech0160export.py
- opengever/disposition/tests/test_overview.py
This is the first part of the work we do for #5167, a short summary of the changes this PR does.
- **Rework SIP Package generation and download.** Store SIP package as a blob locally instead of re generating them for each download. This solves time and ressources and makes it possible to provide customer specific scripts and SIP package handling. 
- **Switch SIP download button to the download view.** The export view stays still available, but is no longer available trough the UI, can be useful for debugging purposes.
- Instead of a manual trigger, generate and store the SIP Package automatically, when disposing a disposition.
- Remove local copy of the SIP package after closing a disposition.
>  Rework SIP Package generation and download

- docs/HISTORY.txt
- opengever/activity/dispatcher.py
- opengever/base/request.py
- opengever/base/sentry.py
- opengever/nightlyjobs/cronjobs.py
Two small Quality of Life improvements for nightly jobs:
- Don't require `ftw.raven` when running nightly jobs locally.
- Add short `-f` option as alias for `--force`.
#5302  Checkliste
> Nightly Jobs: Minor Quality of Life improvements

- docs/HISTORY.txt
- opengever/base/__init__.py
- opengever/base/security.py
- opengever/base/source.py
- opengever/contact/utils.py
- opengever/ogds/base/actor.py
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_actor_lookup.py
- opengever/tabbedview/browser/base_tabs.py
- opengever/tabbedview/filters.py
The profile_url fetches the contact folder which is not possible for a foreign user (is not permitted to see the contactfolder). Therefore I introduced a `elevate_privileges` keyword to get the contact_folder url even if the user is not allowed to access it.
In my opinion it's the right solution and part of an access as a foreign user, that some links are not accessible and answer with an unauthorized message.
Fixes #5843 
In addition to the actual change, I moved the `is_solr_feature_enabled` flag where it belongs to.
> Fix team actor profile_url for foreign users

- opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
This PR updates policy templates so that they are created according to our newest feature set. We always want to enable solr. Tika can be dropped as with solr it is not used.
> Use solr per default in policy templates.

- README.rst
- opengever/base/tests/test_reference_prefix.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/disposition/tests/test_byline.py
- opengever/disposition/tests/test_disposition.py
- opengever/disposition/tests/test_excel_export.py
- opengever/disposition/tests/test_history.py
- opengever/disposition/tests/test_listing.py
- opengever/disposition/tests/test_overview.py
- opengever/testing/fixtures.py
This adds a disposition to the fixture which is in state `disposition-state-disposed` and has a SIP package, ready to be delivered.
This is necessary because transports (which will be implemented as part of #5167) need to access the underlying blob on the filesystem. The blob will only have a stable filesystem location once it's committed though. Because in our `IntegrationTestCase` we only emulate `transaction.commit()`, but never actually do a hard commit, this requires the blob to have already been created as part of the fixture to be actually committed and accessible.
> Testing: Add disposition with SIP to fixture.

- opengever/api/tests/test_actions.py
- opengever/document/browser/actionbuttons.py
with https://github.com/4teamwork/opengever.core/pull/5847 we added fileactions as a new category of `portal_actions`. The availability checks for these actions relied on a view which delegates the checks to an adapter of `IFileActions`. We did not handle the case of `portal_type`s for which no such adapter is registered. This is now handled correctly.
**Implementation details**
The `FileActionAvailabilityMixin` was implementing all the methods of the `IFileActions` interface and delegating them to the `IFileActions` adapter. Instead we now overwrite the `__getattr__` method in this mixing and delegate to `IFileActions` adapter when the attribute is a method defined by that interface. In all other cases we raise the `AttributeError` so that normal treatment of attribute search can follow …
>  Fix availability checks for fileactions for non documentish types.

- docs/HISTORY.txt
- docs/public/admin-manual/aussonderung.rst
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20190730111610_add_i_filesystem_transport_settings_registry_record/registry.xml
- opengever/core/upgrades/20190730111610_add_i_filesystem_transport_settings_registry_record/upgrade.py
- opengever/disposition/browser/ech0160.py
- opengever/disposition/browser/overview.py
- opengever/disposition/browser/templates/overview.pt
- opengever/disposition/configure.zcml
- opengever/disposition/delivery.py
- opengever/disposition/disposition.py
- opengever/disposition/handlers.py
- opengever/disposition/interfaces.py
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- opengever/disposition/nightly_jobs.py
- opengever/disposition/permissions.zcml
- opengever/disposition/testing.py
- opengever/disposition/tests/test_delivery.py
- opengever/disposition/tests/test_disposition.py
- opengever/disposition/tests/test_nightly_jobs.py
- opengever/testing/helpers.py
Implements SIP delivery via filesystem.
This addresses part of #5167 _(addressing the FTPS usecase will be solved by mounting an FTPS connection using CurlFtpFS, and using filesystem delivery to drop the SIP on that mounted share)_.
- A new `ISIPTransport` adapter is introduced. These adapters are meant to implement specific transport mechanisms.
- For now, a `FilesystemTransport` is provided (disabled by default), which copies the SIP to a configured destination directory
- Upon disposing a disposition, a new class `DeliveryScheduler` will schedule the SIP for delivery with all enabled transports.
- Delivery status is tracked (by the `DeliveryScheduler` per transport, in annotations on the disposition
- A nightly job is provided that collects all dispositions that are eligble for …
> Implement SIP delivery via filesystem

- docs/HISTORY.txt
- opengever/base/configure.zcml
- opengever/base/transport.py
- opengever/task/browser/accept/utils.py
- opengever/task/reminder/reminder.py
- opengever/task/tests/test_accept.py
- opengever/task/tests/test_reminder.py
The movement is split up in to two parts - a creation of the reminder(s) as part of the successor task creation via Transporter's new ResponsibleTaskRemindersDataCollector and the removal on the predecessor side when accepting the predecessor task.
Closes #5783 (the reason why we move the reminders of responsibles from the predecessor to the successors is described in the issue).
-> Die Reminders funktionieren zurzeit nicht, bzw. können gar nicht funktionieren da Weiterleitungen keine Deadline definiert habe, ich eröffne hierzu ein separaten Issue.
> Move task reminders of responsibles to the successor, when accepting a multi admin unit task.

- docs/HISTORY.txt
- opengever/core/upgrades/20190814122549_fix_permission_for_existing_workspaces/upgrade.py
Update workflow security for `opengever_workspace` workflow to fix permission on existing workspaces.
Durch den PR #5829 wurde der bestehende `opengever_workspace` Workflow mit einer neuen Berechtigung `opengever.workspace.UpdateContentOrder` erweitert. Die Workflow-Security wurde jedoch nicht aktualisiert. Bestehende Arbeitsräume funktionieren somit nicht mit der neuen Berechtigung.
Dieser PR aktualisiert lediglich die Workflow-Security von bestehenden Arbeitsräumen.
Wie kann der Fehler reproduziert werden?
Ein WorkspaceMember kann bei einem bestehenden Arbeitsraum keine ToDo Listen verschieben weil ihm die Berechtigung `opengever.workspace.UpdateContentOrder` auf dem Arbeitsraum fehlt.
> Update workflow security for opengever_workspace workflow

- docs/HISTORY.txt
- opengever/ogds/base/sources.py
- opengever/workspace/tests/test_workspace_sources.py
The userid is not necessary in all the teamraum sources and leads to display issues in the frontend.
I noticed it while implementing the detail view #5852 .
> Remove userid from the users fullname in all teamraum sources.

- docs/HISTORY.txt
- opengever/api/participation.py
- opengever/api/tests/test_participation.py
The new plone.restapi sends a dict having a token and a title for vocabularie values like the users. The frontend is using this new format as well. We have to update the participation implementation to use it as well to fix an issue where it was no longer possible to add participants.
Related frontend PR: https://github.com/4teamwork/gever-ui/pull/396
> Fix workspace participation restapi.

- docs/HISTORY.txt
- opengever/workspace/tests/test_workspace_workspace.py
- opengever/workspace/workspace.py
This PR fixes a broken permission check for the `WorkspacePatch`-API endpoint. 
@all4manu FYI
Fixes an issue introduced in https://github.com/4teamwork/opengever.core/pull/5829
> Fix an issue where it was no longer possible to modify a workspace

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- docs/public/user-manual/dossiers/bearbeiten.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/upgrades/20190821114305_add_use_changed_for_end_date_registry_field/registry.xml
- opengever/core/upgrades/20190821114305_add_use_changed_for_end_date_registry_field/upgrade.py
- opengever/dossier/base.py
- opengever/dossier/interfaces.py
- opengever/dossier/tests/test_archiver.py
- opengever/dossier/tests/test_base.py
- opengever/testing/integration_test_case.py
The newly introduced use of the `changed` date of documents in the calculation of the `earliest_possible_end_date` of a dossier (https://github.com/4teamwork/opengever.core/pull/4806) does not seem to cover all use cases. Indeed some users will modify document metadata, or add some documents while cleaning up a dossier just prior to closing it. The end date will in that case not reflect the what they consider to be the end date of the dossier. To accommodate these use cases, we introduce a new configuration setting allowing to restore the behaviour we had before, i.e. use the `document_date` in the calculation of the `earliest_possible_end_date`.
For https://github.com/4teamwork/opengever.zug/issues/319
> Add config to switch between changed and document_date for dossier end date calculation

- opengever/testing/builders/dx.py
Der failing Test in RIS war unabhängig von diesen Änderungen.
Ich habe mit diesen Änderungen alle Backend-Tapes neu aufzeichnen lassen (https://github.com/4teamwork/ris/pull/1615) ohne dass sich etwas an den Tapes geändert hätte (*zur Sicherheit könnte man noch alle frontend-Tapes neu aufzeichnen lassen, das dauerte mir aber zu lange ...*).
> Reindex object without changing modified date.

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
- opengever/core/upgrades/20190821181500_copy_proposal_language_from_model_to_plone_content/upgrade.py
- opengever/core/upgrades/20190821181535_copy_proposal_committee_from_model_to_plone_content/upgrade.py
- opengever/dossier/tests/test_deactivate.py
- opengever/dossier/tests/test_resolve.py
- opengever/meeting/browser/proposalforms.py
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_committee_vocabulary.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_vocabularies.py
- opengever/meeting/vocabulary.py
- opengever/testing/builders/dx.py
With https://github.com/4teamwork/opengever.core/issues/5799 we would like to provide API support for proposals. To do so we must in a first step make sure all data is stored on plone content objects as primary data source and only synced to SQL later. This PR provides only a first, small step towards API support. It adds all proposal fields that were in SQL only to the proposal plone content type. It provides upgrades that store data that were only in SQL on the plone content objects.
The following fields are moved:
- `language`, a string representing the selected lanugage
- `committee_oguid`, to store a reference to the committee. i have chosen to store the oguid in plone as that is on the abstraction level of plone content objects. unfortunuately we cannot use plones references as the …
> Move remaining proposal model schema fields to proposal plone content type.

- docs/HISTORY.txt
- opengever/disposition/ech0160/model/document.py
- opengever/disposition/ech0160/model/file.py
- opengever/disposition/ech0160/model/folder.py
- opengever/disposition/tests/test_model.py
- opengever/disposition/tests/test_sippackage.py
Up to now, only the archival file would be included in the SIP package during eCH-0160 export if an archival file is present. We now always export the original file and also the archival file when one is present.
I checked that there is no problem with the numbering. We are basically simply adding another `File`, these get numbered automatically, so there cannot be any naming conflict.
For issue https://github.com/4teamwork/opengever.core/issues/5809
> Include original files in ech0160 SIP export.

- docs/HISTORY.txt
- docs/public/dev-manual/api/recently_touched.rst
- opengever/api/recently_touched.py
- opengever/api/tests/test_recently_touched.py
To allow to easily display an icon and a hint whether a document is checked out or not in the recently touched menu of the new UI, we add the `filename` and `checked_out` fields to the `recently-touched` endpoint.
Note that we have a discrepancy between the `last_touched` date for recently touched vs checked out documents. In one case it's timezone aware and in the other it's not. See comment in the tests.
This is for https://github.com/4teamwork/opengever.core/issues/5760
> Add filename and checked_out fields to the recently-touched endpoint.

- docs/HISTORY.txt
- opengever/sharing/browser/sharing.py
- opengever/sharing/browser/templates/sharing.html
- opengever/sharing/tests/test_sharing.py
When a user or a group gets deleted from the LDAP, it is not deleted from the `ogds` but set to `inactive`, as it might still be used somewhere in the Gever instance. For example a user that gets deleted might still be set as responsible on a given dossier or so. 
There was a bug in the `sharing` view not handling such an inactive group properly. The problem was that we get the local roles with the `acl_users` tool (https://github.com/plone/plone.app.workflow/blob/master/plone/app/workflow/browser/sharing.py#L231), which will wrongly assign the type `user` to inactive groups (deleted from the LDAP), as it will not find them (https://github.com/plone/Products.PlonePAS/blob/master/src/Products/PlonePAS/pas.py#L276-L282). This leads to the detailed view url pointing to an inexistant user …
> Correctly handle inactive groups in the sharing view.

- docs/HISTORY.txt
- opengever/api/tests/test_copy_paste.py
- opengever/base/browser/copy_items.py
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base.pot
- opengever/base/monkey/patches/verify_object_paste.py
- opengever/base/tests/test_copy_paste.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20190823113658_do_not_show_copy_action_for_checked_out_documents/actions.xml
- opengever/core/upgrades/20190823113658_do_not_show_copy_action_for_checked_out_documents/upgrade.py
- opengever/document/tests/test_copy_document.py
- opengever/document/tests/test_menu.py
- opengever/document/tests/test_overview.py
We prevent copy / pasting documents that are checked out, because the state of such documents is not well defined (we might be copying a working copy of another user), and the pasted object will be in the checked-out state.
We try to handle the case gracefully whenever possible:
* Disable copy action for checked-out documents. (action not shown in the actions menu)
* Forbid copy pasting of checked-out documents from the TabbedView listings (objects will not land in the clipboard and an error message is displayed)
Other cases (rest api, or `plone.api.content.copy` for example) are handled in the `_verifyObjectPaste` that we have already monkey patched. I first tried to handle these cases with an event handler, but there on the `lifecycleevent`s we don't have access to the object being …
> Prevent copy / paste of checked out documents

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
- opengever/meeting/browser/createsubmittedproposal.py
- opengever/meeting/browser/proposalforms.py
- opengever/meeting/configure.zcml
- opengever/meeting/docprops.py
- opengever/meeting/handlers.py
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/proposal.py
- opengever/meeting/proposal.py
- opengever/meeting/proposalsqlsyncer.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_toc.py
- opengever/testing/builders/dx.py
This PR is part of https://github.com/4teamwork/opengever.core/issues/5799. we move functionality that creates SQL records and syncs to SQL out of add and edit forms and use event handlers instead. In order to be able to easily create proposals via api endpoint and make sure the corresponding SQL records are created and synced automatically via event handler. This further decouples SQL from plone objects. Functionality and knowledge about what to sync from proposals and submitted proposals is also moved to the SQL model. The following things are addressed in this PR:
- Forms for proposals are no longer inheriting from `ModelProxyEditForm`
- Creating/Updating proposal record is now done via event handler
- Some care has to be taken when creating submitted proposals, we make sure that the …
> Drop custom model forms for proposals and create proposal model via event handler.

- docs/HISTORY.txt
- opengever/base/browser/search.pt
- opengever/base/browser/search.py
- opengever/base/tests/test_search.py
When searching for a term with special character, the url for the `advanced search` button was not url-encoded, which would raise a 400 on IE. We now properly encode the url.
For https://github.com/4teamwork/opengever.core/issues/5859, support issue https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20437/
> Handle special characters in link to advanced search.

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/development.py
This PR patches a tuple of exceptions that should be re-raised in `BaseOrderedViewletManager` so that all exceptions are re-raised. The patch is only applied for local development, i.e. when the env variable `IS_DEVELOPMENT_MODE` is enabled.
With the patch active rendering of a page is aborted when a viewlet or viewlet manager fails to render. Without this patch a placeholder markup snippet is rendered indicating rendering errors, e.g. `error while rendering plone.failing.viewlet`. That snippet will then be cached happily by `plone.app.caching` and can remain in place even after the error has been fixed. After spending way too much time attempting to debug a "failing" viewlet i'd prefer to have this patch for local development.
> Always raise viewlet(-manager) rendering errors in dev mode.

- docs/HISTORY.txt
- opengever/document/browser/overview.py
- opengever/document/tests/test_overview.py
Die `WebIntelligentFieldRow` rendert den Value `None` als String. Mit diesem PR wird ein `None` Value nicht mehr gerendert.
Related Issue: #5785 
> Do no longer render `None` value in document description.

- docs/HISTORY.txt
- docs/public/user-manual/benachrichtigung.rst
- opengever/activity/__init__.py
- opengever/activity/base.py
- opengever/activity/browser/resources/settings.js
- opengever/activity/browser/settings.py
- opengever/activity/browser/templates/settings.pt
- opengever/activity/hooks.py
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
- opengever/activity/model/subscription.py
- opengever/activity/roles.py
- opengever/base/response.py
- opengever/core/upgrades/20190829091825_add_workspace_activity_setting/upgrade.py
- opengever/disposition/handlers.py
- opengever/workspace/activities.py
- opengever/workspace/configure.zcml
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/participation/browser/manage_participants.py
- opengever/workspace/participation/browser/my_invitations.py
- opengever/workspace/subscribers.py
- opengever/workspace/tests/test_activities.py
- opengever/workspace/todo.py
We integrate `ToDo`s in the notification system. For that we:
* Add new activity settings for workspaces for `TODO_RESPONSIBLE_ROLE` and `WORKSPACE_MEMBER_ROLE`
* Add activities for assigning, closing, reopening and commenting a todo.
* Automatically update watchers on the `ToDo`s outside from the activities, in prevision of the view listing all objects that user is watching:
* Add all workspace users as watchers to a newly created ToDo.
* Add new workspace participant as watcher on all ToDos.
For https://github.com/4teamwork/opengever.core/issues/5796
> Integrate ToDos in GEVER-Notification-System

- docs/public/dev-manual/oggbundle/index.rst
- setup.py
This avoids an auto-completion clash with buildout and starts to establish a
`create-` prefix convention for commands that create things.
Closes #5930.
> Rename bundle-factory to create-bundle.

- opengever/webactions/tests/test_webactions_storage.py
Currently `DeprecationWarning: BaseException.message has been deprecated as of  Python 2.6.` bleeds through all of our test output when this module is tested. By not accessing the attribute but the exceptions string representation we can use the non-deprecated implementation while maintaining functionality
> Get rid of BaseException.message deprecation.

- docs/HISTORY.txt
- opengever/task/browser/modify_deadline.py
- opengever/task/configure.zcml
- opengever/task/tests/test_api_support.py
- opengever/task/transition.py
Validate task deadline modification through the rest-api if the user uses the same deadline as already set on the task.
Issuer: #5814 
> Validate task deadline modification through the rest-api

- docs/HISTORY.txt
- docs/public/dev-manual/api/recently_touched.rst
- opengever/api/tests/test_recently_touched.py
- opengever/base/tests/test_object_touched_handling.py
- opengever/base/touched.py
- opengever/core/upgrades/20190920114010_migrate_dates_in_recently_touched_menu/upgrade.py
Also use timezone aware datetimes for the recently touched log, so both datetimes returned by the `recently-touched` endpoint are timezone aware datetimes.
The change contains a migration for the existing recently-touched log, which migrates the naive datetimes.
for #5887
> Harmonize datetimes in recently-touched endpoint.

- docs/HISTORY.txt
- docs/public/dev-manual/api/content_types.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/proposals.rst
- docs/public/dev-manual/api/schemas/opengever.meeting.proposal.inc
- docs/schema-dumps/opengever.meeting.proposal.schema.json
- opengever/api/add.py
- opengever/api/configure.zcml
- opengever/api/tests/test_content_creation.py
- opengever/base/schemadump/config.py
- opengever/meeting/browser/proposalforms.py
- opengever/meeting/utils.py
- opengever/meeting/vocabulary.py
This PR supersedes https://github.com/4teamwork/opengever.core/pull/5924.
The Add form for proposals contained some logic and specific steps needed for the creation of a `Proposal`, such as the creation of a `Document` (the proposal document). Because of that, creation of a `Proposal` through the REST-API was not possible (or rather broken).
In this PR we make it possible to create proposals through the REST-API. For that we:
* Copy and refactor  `plone.restapi.services.content.add.FolderPost`, splitting it into several methods to allow to hook into it in a subclass. This should allow us to move that code into `plone.restapi` later on.
* Overwrite `FolderPost` (with `GeverFolderPost`) to handle special cases like `proposal` creation in gever
* `GeverFolderPost` allows to extract and …
> Handle creation of new proposals over the REST-API.

- docs/HISTORY.txt
- opengever/core/solr_testing.py
- solr-conf/solrconfig.xml
- versions.cfg
We've decided to not yet bump the solr version to an 8.x major version yet as we have discovered that a major upgrade needs a full reindex. Instead we're going to ship scripts to ease migration to 8.x with the next gever release, see https://github.com/4teamwork/opengever.core/pull/5933.
See https://github.com/4teamwork/opengever.core/issues/5863 for full background and next steps we're planning to take.
- ⚠️ before deploying this PR locally and on our RED deployment(s) we must manually run a `bin/instance solr reindex`, or for local development create a fresh deployment. You will get a `SolrCore 'development' is not available due to init failure: Error opening new searcher.` error after the downgrade, so we need to manually clear the core and make sure it is rebuilt.
the older solr can …
> Downgrade solr to 7.3.1.

- docs/HISTORY.txt
- opengever/core/upgrades/20191001090415_fix_paragraph_template_ordering_object_id_type/upgrade.py
- opengever/meeting/browser/meetingtemplate.py
- opengever/meeting/tests/test_meeting_template.py
Fixes https://github.com/4teamwork/opengever.core/issues/5957. With this PR we make sure that plone object ids are always stored as ascii when using the `OFS.interfaces.IOrderedContainer` interface. We also migrate existing incorrect ids to ascii.
This issue currently blocks https://github.com/4teamwork/opengever.core/issues/5863 from moving forward as a solr reindex is not possible for agenda item templates/meeting templates.
>  Make sure agenda item template ids are ascii.

- docs/HISTORY.txt
- docs/public/dev-manual/oggbundle/index.rst
- opengever/bundle/factory.py
- opengever/bundle/loader.py
- opengever/bundle/sections/fileloader.py
- opengever/bundle/tests/test_section_fileloader.py
Currently the bundle import of GEVER had no support for importing *.msg mails. With this changes it now also support the import of those mails, similar than GEVER does when uploading them via dnd (quickupload):
- Converting the *.msg to an *.eml with `msgconvert` and stores it as `message`
- Stores the `*.msg` as original_mesasge
For https://github.com/4teamwork/opengever.koeniz/issues/78
> Support the bundle-import of mails in the msg format.

- docs/HISTORY.txt
- opengever/task/activities.py
- opengever/task/tests/test_activities.py
There was a problem in the watcher handling when reassing a task to
the same user but a different org_unit. It tried to remove the watcher
for the former responsible, but thats also the new one, so now change necessary.
For #5963 
> Fix reassigning a task to the same user but a different org unit.

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/recently_touched.rst
- opengever/api/recently_touched.py
- opengever/api/tests/test_recently_touched.py
- opengever/base/viewlets/recently_touched_menu.html
So we support also the `metadata_fields` parameter which allows to
fetch additional metadata. For #5976 
Implementation details:
- The summary representation is extended with the information `icon_class` and `last_touched` which are not supported by the summary and used for the existing UI
- Breaking change: The attributes `filename` and `checked_out` are no longer part of the default representation. But with the `metadata_fields` parameter still accessible.
> Use plone.restapi summary serialization in the recently-touched endpoint.

- docs/public/dev-manual/api/tasks.rst
- opengever/api/response.py
- opengever/api/task.py
- opengever/api/tests/test_task.py
- opengever/task/comment_response.py
Dieser PR:
- Erweitert die REST-API Dokumentation mit dem `@responses` Endpoint für Tasks
- Verwendet den `CommentResponseHandler` beim Hinzufügen von Kommentaren über den `@responses` Endpoint. Damit wird sichergestellt, dass speziellen Attribute wie z.B. der `transition_type` korrekt für das alte UI gesetzt werden und die Kommentare korrekt synchronsiert werden.
Issuer: #5813
> Fix task responses

- docs/HISTORY.txt
- docs/public/dev-manual/api/tasks.rst
- opengever/task/transition.py
Text field was missing in the `ModifyDeadlineTransitionExtender`. There were also some errors in the documentation that I corrected.
> Allow text field in task deadline modification through API.

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
This PR updates the listing-endpoint to support `issuer` as a filter parameter.
Issuer: https://github.com/4teamwork/gever-ui/pull/532
> Make `issuer` filterable in the @lising endpoint.

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/browser/zipexport.py
- opengever/base/tests/test_zipexport.py
- opengever/base/utils.py
- opengever/document/browser/report.py
- opengever/document/tests/test_reporter.py
- opengever/dossier/browser/report.py
- opengever/dossier/tests/test_reporter.py
- opengever/latex/tests/test_latex_utils.py
- opengever/latex/utils.py
- opengever/testing/integration_test_case.py
This adds support for pseudo-relative paths for these four views that take `paths:list` parameters:
- `zip_selected` (Als Zip-Datei exportieren, Documents Tab)
- `document_report` (Auswahl exportieren, Documents Tab)
- `dossier_report` (Auswahl exportieren, Dossiers Tab)
- `pdf-dossier-listing` (Auswahl drucken, Dossiers Tab)
Pseudo-relative in this context means paths that don't start with the Plone site (so are relative to it), but still have a trailing slash).
This is required for these views because the new gever-ui sends paths that aren't prefixed with the Plone site.
Addresses #5974
> Add support for relative paths for views that take paths:list parameter

- opengever/api/document.py
- opengever/api/tests/test_document.py
- opengever/document/base.py
- opengever/document/contentlisting.py
- opengever/document/tests/test_base.py
For #5905 
We also wondered during the Scrum meeting if it would make sense to namespace the additional attributes or use the `metadata_fields` behavior. I decided against it for the following reasons:
- The document representation already contains "ready-only" metadata which is not part of a schema on the top level
- Non schema keys are ignored by the restapi on Patch and Post requests
- `metadata_fields` is currently not supported for the representation of a context
> Provide additional attributes in the API representation of documents and mails

- docs/HISTORY.txt
- opengever/api/mail.py
- opengever/api/tests/test_deserializer.py
When uploading mails through drag&drop in the new `gever-ui`, we use the `tus-upload` endpoint. 
**Problem:**
This endpoint was not working for E-mails, the reason being that the deserialized the `message` field in our custom `DeserializeMailFromJson`, to check whether we need to move the message to the `original_message` field, and then deserialize the field again (standard deserialization to fill the value into the object). Problem is that deserialization of the field consumes the file in the `tus-upload`, so the second deserialization was failing. 
**Solution:**
We invert the order, first we deserialize the field to write the data to the object, then, if necessary, we move that file to the `original_message` field.
For https://github.com/4teamwork/gever-ui/issues/539
> Fix mail deserialization for mails uploaded through tus-upload.

- docs/HISTORY.txt
- docs/public/dev-manual/api/favorite.rst
- docs/public/dev-manual/api/listings.rst
- opengever/api/favorites.py
- opengever/api/listing.py
- opengever/api/tests/test_favorites.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_repository_favorites.py
- opengever/base/model/favorite.py
The oguid parameter is still supported. In addition the `listing` endpoint now also supports the UID as a column.
Used for https://github.com/4teamwork/gever-ui/issues/490
> Allow adding favorites by UID parameter via favorites endpoint.

- docs/HISTORY.txt
- opengever/activity/browser/resolve.py
- opengever/activity/tests/test_resolve.py
- opengever/base/browser/resolveoguid.py
- opengever/document/tests/test_copy_document.py
- opengever/dossier/tests/test_move_items.py
Use functionality from the base class (the resolveoguid class), so there is no need to test any possible case, because it's already done in the TestResolveOGUIDView class.
Closes #5773
> Preserve query string in the resolve notification view.

- docs/HISTORY.txt
- opengever/api/tests/test_config.py
- opengever/base/browser/resources/base.js
- opengever/base/configuration.py
- opengever/base/interfaces.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/base/tests/test_gever_ui_action.py
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20180809152739_add_gever_ui_action/actions.xml
- opengever/core/upgrades/20191028103858_add_ui_switcher/actions.xml
- opengever/core/upgrades/20191028103858_add_ui_switcher/registry.xml
- opengever/core/upgrades/20191028103858_add_ui_switcher/upgrade.py
Issue: https://github.com/4teamwork/gever-ui/issues/487
Dieser PR fügt eine User-Action zum wechseln auf das neue UI hinzu.
> UI switcher

- docs/HISTORY.txt
- docs/public/dev-manual/api/reminder.rst
- opengever/api/tests/test_reminder.py
- opengever/api/tests/test_vocabularies.py
- opengever/task/reminder/configure.zcml
- opengever/task/reminder/model.py
- opengever/task/reminder/vocabulary.py
- opengever/task/response.py
- opengever/task/tests/test_reminder.py
- opengever/task/tests/test_reminder_model.py
- opengever/task/tests/test_reminder_storage.py
Also return the option_title in the reminder API serialization, so we can display the translated title in the frontend.
for #5971 
> Moved reminder options vocabulary to globaly registered vocabulary.

- opengever/webactions/storage.py
In some test cases, a unicode string is returned which raises an error when patching webactions with valid data due to invalid, but generated unicode data for the owner field.
This is a quick, but not complete fix so that the RIS team can finish implementing changes. Changelog entry, tests and more may follow depending on how the GEVER team decieds to approach this issue.
Relates to  #6011 (but does not close it).
> Cast the userid to bytestring so that validation to ASCIILine passes

- docs/HISTORY.txt
- opengever/api/dossier.py
- opengever/api/tests/test_serializer.py
This PR extends the dossier serializer with `is_subdossier`.
This is required for the frontend-pr: https://github.com/4teamwork/gever-ui/pull/650
Issuer: https://github.com/4teamwork/gever-ui/issues/515
> Extend dossier serializer with `is_subdossier`.

- opengever/webactions/storage.py
Reverts 4teamwork/opengever.core#6012.
As discussed, adding a workaround for this issue to the `ris` branch turned out to be an incorrect, even detrimental approach: Until the issue is fixed in `master`, tests are *supposed* to fail, since it also can't work in production.
> Revert "Cast the userid to bytestring so that validation to ASCIILine passes"

- docs/HISTORY.txt
- opengever/api/add.py
- opengever/api/configure.zcml
- opengever/api/task.py
- opengever/api/tests/test_task.py
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
Currently the api for task creation/editing only supports a single value for the `responsible_client` and `responsible` field. But the `schema´ or `querysources` endpoint returnes a combined value for the users containing `responsible_client` and `responsible`. This difference leads to bad situation where we would need to split the values in the frontend or need to use a separate endpoint to fetch the responsible values.
I was also thinking about adding a different endpoint or moving the ":" splitting to the frontend, but I think thats the cleanest way. I see the following advantages:
- The value exposed by the schema endpoint is valid and can be used for a POST or PATCH request. The default implementation on the frontend side works also for tasks.
- The special handling for combined …
>  Support combined notation for task responsible

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/plone_restapi.py
- opengever/core/upgrades/20191031155315_fix_todo_and_todolist_ordering_object_id_type/upgrade.py
- opengever/meeting/browser/meetingtemplate.py
- opengever/workspace/tests/test_todolist.py
This PR fixes an issue where ids of reordered content are converted to unicode on python 2. We now convert input ids when necessary and make sure the ordering stored on a container contains only bytestring object ids.
When changing object ordering via PATCH request we used to incorrectly store ids of reordered resources as unicode instead of a bytestring. This lead to mixed types being stored in the ordering annotations and subsequently mixed types being returned when calling `objectIds` of a container.
Affected content types are todo and todolist (or their possible content types respectively).
We also discovered that with newer versions of `OFS.ObjectManager` non-ascii ids are allowed. Thus we switch agenda item template id input validation to also use the `utf-8` encoding.
See …
> Fix an issue with ids not being stored as bytestring when reordering.

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/action_info.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20191104145517_add_trash_document_and_untrash_document_file_actions/actions.xml
- opengever/core/upgrades/20191104145517_add_trash_document_and_untrash_document_file_actions/upgrade.py
- opengever/document/fileactions.py
- opengever/document/interfaces.py
- opengever/trash/trash.py
Add `trash_document` and `untrash_document` file_actions.
Because [`ActionInfo._checkPermissions()`](https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/ActionInformation.py#L262-L281) only checks permissions on the actual context for action categories that start with `object`,`workflow` or `document`, our permissions for our own `file_actions` category were always checked against the Plone site root. Because so far we only used `View` to protect those actions, this seemed to sort of work. But when using permissions like `"opengever.trash: Trash content"` this failure now surfaces.
🐒I therefore patched `_checkPermissions()` to also consider our `file_actions` category a context based one. IMHO this is even preferrable to renaming the action category, because we …
> Add trash_document and untrash_document file_actions

- docs/HISTORY.txt
- opengever/api/tests/test_document.py
- opengever/document/document.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
Because we still wont an detailed error message (including the mail-in address) directly placed by the field, I duplicate the check from the simplefieldvalitor and register it also as a schema invariant. Simplefieldvalidator are z3c form bsed validation and therefore not called by plone.restapi.
An migration/upgradestep is not necessary, I doublechecked our gever installation, there were only 2 which i migrated manually (delete and recreate). Other productive deployment should not be affected by this.
For #5988
Checked by:
```
from opengever.maintenance import dm
dm()
from plone import api
cat = api.portal.get_tool('portal_catalog')
MAIL_EXTENSIONS = ['.eml', '.msg', '.p7m']
wrong = []
for brain in docs:
doc = brain.getObject()
if doc.get_file() and doc.get_file_extension() in …
```
> Disallow mail upload as documents via API.

- docs/HISTORY.txt
- opengever/dossier/tests/__init__.py
- opengever/meeting/docprops.py
- opengever/meeting/tests/test_docproperties.py
Proposal doc-properties were incorrectly collected as an utf-8 encoded bytestring instead of an unicode-string by using the accessor methods `Title` and `Description` respectively. 
Fixes #5955 
⚠️ based on https://github.com/4teamwork/opengever.core/pull/6037 as doc-properties are refactored there. Needs a final rebase.
> Fix encoding issue in proposal doc-properties.

- opengever/ogds/models/tests/base.py
- setup.py
We are at least on python2.7 on all deployments, so unittest2 and unittest are equal.
_I just stumbled upon this by chance but as unittest2 is no longer necessary we can just as well get rid of the import, no CL necessary IMO._
> Drop unittest2 in favor of unittest.

- docs/HISTORY.txt
- opengever/contentstats/providers.py
- opengever/contentstats/tests/test_content_stats_integration.py
We extend the `GEVERContentStatsProvider` with a count of the main dossiers.
For https://github.com/4teamwork/opengever.core/issues/6043
> Add main dossier count to contentstats.

- docs/HISTORY.txt
- opengever/document/versioner.py
- opengever/journal/handlers.py
- opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/opengever.journal.pot
- opengever/journal/tests/test_document_journalization.py
Newer OfficeConnector versions upload the modified file each time it gets saved. As these file modifications get journalised, this clogs up the journal with uninformative entries. With this change, we no longer journalise file modifications. Instead, document checkin/checkout entries serve as markers to who modified a document and when (although a checkout/checkin cycle with no modifications cannot be distinguished in the journal from one with modifications, but document versions would allow to track changes if necessary).
For https://github.com/4teamwork/opengever.core/issues/6003
> No longer add journal entry for document file modifications.

- docs/HISTORY.txt
- opengever/api/listing.py
Fixes yet another Unicode error in `@listing`.
Because that entire code is a mess and deals with a mix of bytestrings and unicode in different places, it's out of scope of this PR to fix all those encoding issues that are most likely still lurking here. Instead, I left a comment that (and how) this should be fixed once this endpoint is refactored as part of #5901. 
Addresses #5975
> Fix unicode error in @listing endpoint filters.

- docs/HISTORY.txt
- opengever/task/tests/test_localroles.py
- opengever/task/transition.py
When rejecting a task the responsible gets changed to the tasks issuer, but the local permissions sets has not been revoked (#5984) this PR fixes that.
> Revoke permissions for former responsible, when task gets rejected.

- docs/HISTORY.txt
- opengever/api/document.py
- opengever/api/tests/test_document.py
Our serializer for documents had not respect the `version` parameter, as the default plone.restapi serializer does.
For #6049
> Fix document serialization for older document versions.

- docs/HISTORY.txt
- opengever/task/browser/complete.py
- opengever/task/tests/test_resolve.py
Since the TaskReponse rebuild, accessing the response container by
indexing is no longer supported.
I also added a minimal test for the whole mutli-adminunit completion, so we should noticed similar problems in the future. 
For #6062.
> Fixes is already done check in multi admin unit tasks completion.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/history.py
- opengever/api/tests/test_history.py
- opengever/document/checkout/manager.py
- opengever/document/tests/test_checkout.py
In this PR we overwrite the `@history` PATCH endpoint for documents to correctly revert documents to older versions. Indeed in GEVER we have customised the reverting to older versions for documents, to avoid reverting the metadata (we only revert the file data), but the API was doing the standard Plone revert.
For https://github.com/4teamwork/opengever.core/issues/6008
> Fix @history patch endpoint to correctly revert to older document version.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
The fallback to the default sorting index in the `listing` endpoint was broken. This PR fixes that bug and adds tests that sorting parameters get set properly.
For https://sentry.4teamwork.ch/sentry/onegov-gever/issues/35027/
> Fix fallback to default sorting index in listing endpoint.

- docs/HISTORY.txt
- opengever/task/browser/complete.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/response_description.py
- opengever/task/tests/test_resolve.py
Display returned documents in the task-resolved history entry.
When resolving a multi admin unit task, the user has the possibility to return some documents, those are now displayed in the task history. Both ways referenced or contained documents are handled and combined if necessary.
For #6065
> Task completion history

- docs/public/release-notes/index.rst
- docs/public/release-notes/release-2019.4.rst
The release notes do not contain the API changes, as they are meant to be for actual GEVER users, not for technical Users of the API.
> Add release notes for the 2019.4 release.

- docs/HISTORY.txt
- versions.cfg
This adds a version pin for the initial version of `ftw.monitor`.
This is so we have a version pin in place going forward (for the next release), even though for currently rolling it out without being tied to a release we've already added a temporary one in 4teamwork/gever-buildouts#31
> Pin ftw.monitor = 1.0.0 for next release.

- docs/HISTORY.txt
- opengever/task/browser/delegate/recipients.py
- opengever/task/tests/test_delegate.py
> Allow teams as task responsible when delegating a task

- docs/HISTORY.txt
- opengever/api/tests/test_summary.py
- opengever/document/contentlisting.py
The original RealContentListingObject drops the acquistion information, when accessing the value. This lead to problems when calling getOwner in the Title accessor for example. This has been already fixed for OpengeverRealContentListingObject but not for the document one.
For #6057 
> Fix contentlisting and API summary for documents inside tasks.

- docs/HISTORY.txt
- docs/public/dev-manual/api/searching.rst
- opengever/api/listing.py
- opengever/api/solrsearch.py
- opengever/api/tests/test_solrsearch.py
The `solrsearch` endpoint returned the facets directly as received from solr, without any of cleanup done in the `SolrResponse` and in the `@listing` endpoint, i.e. in the form:
```
"facet_counts": {
"facet_fields": {
"document_type": [
"contract",
1,
"request",
1
]
},
"facet_heatmaps": {},
"facet_intervals": {},
"facet_queries": {},
"facet_ranges": {}
}
```
This is hard to use in the frontend and labels for the facets are missing, which poses challenges for the translations in the frontend.
In this PR, we fix the `facet_counts` in the response to match that of `@listing` endpoint:
- We use the facets from `SolrResponse`, which is a dictionary of facets and counts (instead of the list with every second element being a facet or a count)
- We add the labels to the facets for certain fields, …
> Also return facet labels in solrsearch endpoint.

- docs/HISTORY.txt
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/core/locales/fr/LC_MESSAGES/ftw.lawgiver.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/plone.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- Added the French translations for release 2019.4.
- Update translation for disposition archive action
This is for https://github.com/4teamwork/opengever.core/issues/6080
> Update French translations for release 2019.4

- docs/HISTORY.txt
- opengever/officeconnector/service.py
- opengever/oneoffixx/api_client.py
- opengever/oneoffixx/browser/form.py
- opengever/oneoffixx/locales/de/LC_MESSAGES/opengever.oneoffixx.po
- opengever/oneoffixx/locales/fr/LC_MESSAGES/opengever.oneoffixx.po
- opengever/oneoffixx/locales/opengever.oneoffixx.pot
- opengever/oneoffixx/tests/test_oneoffixx.py
- opengever/testing/fixtures.py
There are several changes made by oneoffixx in their last OneOffix update:
- TenantInfo returns a list of datasources, the primary is marked
with the `isPrimary` flag
- The parameter `orgId` is now required when quering template groups or templates.
- Favorites does return now directly a list of templates
In Addition to the changes made necessary by the API changes, I also fixed a "typo" in the oc_checkout view, which does not correspond to the shadow_document creation.  
> Update oneoffixx integration with the latest oneoffixx api changes

- docs/HISTORY.txt
- opengever/api/journal.py
When calling the history endpoint, it currently sorted the persistent list - which raises CSRF Warnings.
Used for https://github.com/4teamwork/gever-ui/issues/659
_Link zum Issue: `closes` oder `fixes` keyword verwenden._
Definition of Done: https://gever.4teamwork.ch/ordnungssystem/3/2/2/allgemeines/dossier-3644/document-30943
> Do not manipulate the persistent journal list on @history get.

- docs/HISTORY.txt
- opengever/oneoffixx/api_client.py
With the latest change, we adjust the handling to extract the templatelibrary id. But with this change, we mistakenly only adjusted the happy case, but not the case when the first requests is answered with an 401, because of a no longer valid token.
Fixes https://sentry.4teamwork.ch/sentry/onegov-gever/issues/52318/
> Fix authorization handling when fetching the template_group_id.

- docs/HISTORY.txt
- opengever/base/browser/resources/tooltip.js
We fix a styling issue in the documents tab, where after opening the bumblebee tooltip, the highlighting of the corresponding row does not get removed when the tooltip is closed again.
It also happens that the highlighted row is in front of other open menus (search menu for example), but I think that is fine, as long as the highlighting is not left behind...
**With open search and tooltip, the row color and text is above the search menu.**
**Once the tooltip is closed, the color is removed and does not overlap the search menu anymore**
For https://github.com/4teamwork/opengever.core/issues/5898
> Fix styling bug in tabbedview after showing bumblebee tooltip.

- docs/HISTORY.txt
- opengever/activity/browser/resources/settings.js
- opengever/activity/browser/settings.py
- opengever/activity/browser/templates/settings.pt
Workspaces notifications settings should only be visible when the feature is activated.
For https://github.com/4teamwork/opengever.core/issues/6084
> Only show workspace notification tab when feature is activated.

- docs/HISTORY.txt
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_submitted_proposal.py
Fix setting the description of an agenda-item when it has a proposal.
Apparently this code-branch was not tested 😢. This PR fixes an attribute-error when attempting to set the description of an agenda-item that is attached to a proposal.
Fixes #6090.
> Fix setting agenda item description.

- docs/HISTORY.txt
- opengever/task/activities.py
- opengever/task/tests/test_api_support.py
- opengever/task/transition.py
- opengever/task/util.py
With the 2019.4 release it's now possible to reassign a task to the same user but different org_unit (`responsible_client`). But the response representation was wrong, because the responsible change was not tracked correctly.
No upgradestep/migration needed, because it is only possible since 2019.4.x
> Fix response text for responsible changes to the same user.

- docs/HISTORY.txt
- opengever/journal/handlers.py
- opengever/officeconnector/tests/test_api_dossier_checkout.py
We do no longer write journal entries when saving a checked out file (as this made an entry for each save of the file see https://github.com/4teamwork/opengever.core/pull/6054). But the check to skip the journal entry did not work when using the REST-API payloads for OC. This is fixed in this PR.
For https://github.com/4teamwork/opengever.core/issues/5735
> Skip document modified journal entry when saving file with OC RESTAPI.

- docs/HISTORY.txt
- opengever/core/testserver.py
This is needed so that virtual hosting URLs work with the testserver, which is required for the upcoming `gever-ui` E2E tests.
> Register virtual host monster on site setup for testserver

- docs/HISTORY.txt
- opengever/task/task.py
- opengever/task/tests/test_sequential_task_process.py
The current implementation has not added the IFromSequentialTasktemplate to additionally added sequential tasks, which lead to an incorrect tasktemplate_predecessor indexing. Which meant they weren't started automatically, when closing the previous task.
No need imho for an upgradestep, the problem in the production was solved by manually opening or skipping the task.
> Fix automatic start of additionally added sequential tasks.

- docs/HISTORY.txt
- opengever/oneoffixx/browser/form.py
- opengever/oneoffixx/locales/de/LC_MESSAGES/opengever.oneoffixx.po
- opengever/oneoffixx/locales/fr/LC_MESSAGES/opengever.oneoffixx.po
- opengever/oneoffixx/locales/opengever.oneoffixx.pot
- opengever/oneoffixx/tests/test_oneoffixx.py
Do not completely hide the exceptions, it still logs the error to sentry.
See https://basecamp.com/2768704/projects/12554551/todos/404990430#comment_735363271
> Catch oneoffixx api calls failures and show statusmessage instead.

- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default_content/opengever_content/03_committees.json.bob
Follow-up of https://github.com/4teamwork/opengever.core/pull/6089, also make sure that correct meeting roles are used in policy templates.
> Fix meeting permissions in policy template.

- docs/HISTORY.txt
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20191128155237_allow_sharing_action_on_workspaces/actions.xml
- opengever/core/upgrades/20191128155237_allow_sharing_action_on_workspaces/upgrade.py
- opengever/sharing/browser/configure.zcml
- opengever/sharing/browser/sharing.py
- opengever/sharing/tests/test_sharing.py
For the new frontend we need the `@sharing` action and view to work on `workspace`s and `workspace_folder`s. In this PR we:
- Allow the sharing action on workspaces.
- Restrict available users (for `GET`) on `workspace`s and `workspace_folder`s to users with local roles in the `workspace`, except for admins and managers.
For https://github.com/4teamwork/opengever.core/issues/6041
> Allow sharing view and action on workspaces

- docs/HISTORY.txt
- opengever/base/browser/resources/tooltip.js
https://github.com/4teamwork/opengever.core/pull/6092 only partially fixed the issue, but the fix did not work when leaving from the tooltip overlay instead of from the document. In that case the target from the event is not the row in the table, but the tooltip itself, and the selector to remove the `bumblebee-tooltip-active` class did not work.
There is no good way to find the correct row in the table starting from the tooltip, so I had to resort selecting directly form the `body`
For https://github.com/4teamwork/opengever.core/issues/5898
> Correct styling bug fix in tabbedview after showing bumblebee tooltip.

- docs/HISTORY.txt
- opengever/base/overrides.zcml
- opengever/base/warmup.py
Add custom `IWarmupPerformer` to also warm up GEVER's `trashed` index.
This extends the standard indexes (`allowedRolesAndUsers` and `object_provides`) that are [warmed up by `ftw.monitor`](https://github.com/4teamwork/ftw.monitor/blob/master/ftw/monitor/warmup.py#L50-L53) with our GEVER-specific `trashed` index.
With this we will warm up the same indexes that were determined as a good trade-off between effectiveness and warmup-time and [got used in the monitor prototype](https://github.com/4teamwork/opengever.maintenance/blob/24908aae0b3784b25dde06b95bbbf488452ebedd/opengever/maintenance/browser/warmup.py#L27-L31).
> Add custom IWarmupPerformer to also warm up GEVER's trashed index.

- opengever/examplecontent/meeting.py
Fix creating example content periods, they are now a plone content type and should be created inside their parent with `within`.
Closes #6112.
> Correctly create periods in committees.

- docs/intern/kurzreferenzen/ogip.rst
We do no longer track the state of an OGIP in the basecamp list, but in the opportunity instead.
> Adjust OGIP process description

- docs/HISTORY.txt
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_solrsearch.py
Now that we have solr tests running, we add tests for the `@solrsearch` and `@listing` endpoints.
These are extracted from https://github.com/4teamwork/opengever.core/pull/6086
For https://github.com/4teamwork/opengever.core/issues/5901
> Add tests for solrsearch and listing endpoints.

- docs/HISTORY.txt
- opengever/api/globalindex.py
- opengever/api/listing.py
- opengever/api/solr_query_service.py
- opengever/api/solrsearch.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_search.py
- opengever/api/tests/test_solrsearch.py
- opengever/base/contentlisting.py
- opengever/base/tests/test_utils.py
- opengever/base/utils.py
With this PR we refactor the listing and search endpoints. The two endpoints mainly have the same functionality but were each doing things differently, not sharing any code. 
Refactoring led to:
- The two endpoints share a baseclass 
- They return similar responses (see also https://github.com/4teamwork/opengever.core/pull/6071). 
- Batching is still done differently in the two endpoints (one uses `rows` and `start`, the other `b_size` and `start_b`), as this would be a breaking change...
- The field, index, accessor mapping was rewritten using classes for fields, which also know things like casting a value to a label, etc. This leads to fewer conditions strewn around in the code.
- Fields now know if they need to request other fields (for example `preview_url` needs the …
> Refactor Solr search and listing endpoints

- docs/HISTORY.txt
- opengever/core/upgrades/20181120131154_add_office_connector_tus_upload_settings/registry.xml
- opengever/core/upgrades/20181120131154_add_office_connector_tus_upload_settings/upgrade.py
- opengever/core/upgrades/20191115105256_remove_oc_rest_api_feature_flag/registry.xml
- opengever/core/upgrades/20191115105256_remove_oc_rest_api_feature_flag/upgrade.py
- opengever/locking/tests/test_force_unlock.py
- opengever/officeconnector/browser/settings.py
- opengever/officeconnector/helpers.py
- opengever/officeconnector/interfaces.py
- opengever/officeconnector/service.py
- opengever/officeconnector/testing.py
- opengever/officeconnector/tests/test_api_dossier_checkout.py
- opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
- opengever/officeconnector/tests/test_api_task_checkout.py
- opengever/officeconnector/tests/test_feature.py
- opengever/officeconnector/tests/test_zopemaster.py
- opengever/testing/integration_test_case.py
In this PR we remove support for non-API based OfficeConnector actions (checkout, upload, checkin, lock and unlock). This makes API-based OfficeConnector the one and only default.
For https://github.com/4teamwork/opengever.core/issues/5848
Introduced in GEVER in https://github.com/4teamwork/opengever.core/pull/5126
Introduced in OC in https://github.com/4teamwork/OfficeConnector/pull/307
> Always use API for OfficeConnector.

- docs/HISTORY.txt
- opengever/api/tests/test_webactions.py
- opengever/core/upgrades/20191211081852_make_webaction_owners_and_groups_unicode/upgrade.py
- opengever/testing/builders/webactions.py
- opengever/webactions/schema.py
- opengever/webactions/storage.py
- opengever/webactions/tests/test_webactions_provider.py
- opengever/webactions/tests/test_webactions_storage.py
For some webactions, `owner` was set to a unicode string, which then does not pass validation when patching the webaction. We were not validating that field when adding a webaction as it is generated in the backend and not user input. I now:
- Added validation of all the fields when creating a new webaction
- Cast the `userid` to correct type before setting it to the `owner` field of the webaction
- Switch `owner` and `groups` field to unicode
- Update existing webactions to make sure correct type is being used
I switch to unicode as some userids and groups can be unicode
For https://github.com/4teamwork/opengever.core/issues/6011
> Make sure that owner has correct type in webactions.

- .github/pull_request_template.md
We've decide the DoD shall be moved. It is now at https://github.com/4teamwork/opengever.core/wiki/Definition-of-Done and the link in the PR description should be updated accordingly.
> Update link to DoD from GEVER to github wiki.

- opengever/core/upgrades/20191216161532_remove_old_workspace_invitations/upgrade.py
Part of https://github.com/4teamwork/opengever.core/issues/5911. We changed the data-format of invitations. Older invitations are no longer valid. Thus we delete them.
Should be merged with https://github.com/4teamwork/opengever.core/pull/6123. Didn't add a CL as it is already covered there and part of the same set of changes.
> Add upgrade to drop old-style workspace invitations.

- docs/HISTORY.txt
- opengever/task/tests/test_assign.py
- opengever/task/transition.py
Issuer: https://github.com/4teamwork/opengever.sg/issues/372
This PR fixes an issue where it was not possible to reassign a task to a new inbox group. It was only possible through the edit or add form.
Before:
After:
> Fix to reassign a task to a new inbox group.

- docs/HISTORY.txt
- opengever/api/invitations.py
- opengever/api/participations.py
- opengever/api/tests/test_invitation.py
- opengever/api/tests/test_participation.py
- opengever/workspace/participation/__init__.py
- opengever/workspace/tests/test_workspace_manage_participants.py
With this PR we adapt the response format used in the `@invitations` and `@participations` endpoint for the new UI. Some tests which can no longer work are removed. Functionality that can be removed is double checked with issues attached to the epic https://github.com/4teamwork/opengever.core/issues/6141.
Closes https://github.com/4teamwork/opengever.core/issues/6168.
> Adapt response format for invitations and participations for new UI.

- versions.cfg
Add version pin for the previously unpinned `itsdangerous`. This is a new dependency that was introduced in #6161.
> Add version pin for itsdangerous.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/invitations.py
- opengever/api/tests/test_invitation.py
- opengever/api/tests/test_participation.py
- opengever/core/profiles/default/types/opengever.workspace.workspace.xml
- opengever/core/upgrades/20191230160531_add__add_invitation__action_to_workspace/types/opengever.workspace.workspace.xml
- opengever/core/upgrades/20191230160531_add__add_invitation__action_to_workspace/upgrade.py
- opengever/workspace/tests/test_workspace_workspace.py
~~based on `deif-6163-add-responsible-to-workspace` and https://github.com/4teamwork/opengever.core/pull/6177~~
This PR adds an action to add invitations to workspaces. We also drop `PATCH`-ing invitations as unwanted/incorrect invitations can be deleted and re-added.
Part of https://github.com/4teamwork/opengever.core/issues/6141, closes https://github.com/4teamwork/opengever.core/issues/6164.
> Add action to add invitations to workspaces.

- docs/HISTORY.txt
- opengever/api/configure.zcml
Since we use the `CMFEditions.RevertToPreviousVersions` permission, we need to explicitly load the `permissions.zcml` in order to not be dependent on ZCML load order.
(This turned out to be an issue in ZG from the `2019.5-stable` branch, where the ZCML load order seems to turn out differently).
> Include permissions.zcml of Products.CMFEditions:

- opengever/testing/fixtures.py
- opengever/workspace/participation/browser/manage_participants.py
- opengever/workspace/participation/browser/my_invitations.py
- opengever/workspace/tests/test_my_invitations.py
~~based on `deif-6164-actions-for-invitations` and https://github.com/4teamwork/opengever.core/pull/6178~~
This PR adapts the kind of role-assignment that we modify in the @participations endpoint. We now expect a normal sharing role assignment. The invitation role assignment is no longer used at the moment. The role assignment can be modified by the users which makes it equivalent to a sharing role assignment. Also for workspace folders only sharing role assignments will be used. Having to manage both sharing and invitation role assignments seems complicated for now. We may re-activate the invitation role assignments eventually in the near future, so they are not dropped from the code-base yet. Doing so has been added to https://github.com/4teamwork/opengever.core/issues/6176 however. …
> Modify/delete correct role assignment in @participation endpoints.

- docs/HISTORY.txt
- docs/public/dev-manual/api/workspace/index.rst
- docs/public/dev-manual/api/workspace/role_inheritance.rst
- opengever/api/configure.zcml
- opengever/api/role_inheritance.py
- opengever/api/tests/test_role_inheritance.py
- opengever/base/role_assignments.py
- opengever/workspace/base.py
- opengever/workspace/workspace.py
- opengever/workspace/workspace_folder.py
This PR implements the a `@role_inheritance` `POST` and `GET` service endpoint for workspace folders as specified in https://github.com/4teamwork/opengever.core/issues/6167.
- The `GET` service endpoint allows a user who can `View` to query if role inheritance on context is blocked
- The `POST` endpoint allows a workspace admin to set if inheritance on context is blocked or not. When blocking the parents local role assignments are copied, when unblocking the current folders assignments are removed.
_Creating a draft, but could be merged separately as it  fully implements the `@role_inheritance` endpoint as specified in https://github.com/4teamwork/opengever.core/issues/6167. Checkboxes ticked off accordingly. Didn't get to work on this today unfortunately, so not 100% finsihed._
> Workspace folder participation, implement @role_inheritance views.

- docs/HISTORY.txt
- solr-conf/solrconfig.xml
Allows to run Solr in a master/slave replication setup.
Replication is disabled by default. It can be enabled using the Solr Config API by setting the `solr.replication.masterUrl` and `solr.replication.enable` properties on the slave.
Example:
```
curl -X POST \
-H 'Content-type:application/json' \
-d '{"set-user-property": {"solr.replication.masterUrl": "http://solr-master:8983/solr/core1/replication"}}' \
http://solr-slave:8983/api/cores/core1/config
curl -X POST \
-H 'Content-type:application/json' \
-d '{"set-user-property": {"solr.replication.enable": "true"}}' \
http://solr-slave:8983/api/cores/core1/config
```
> Configure Solr replication handler

- docs/HISTORY.txt
- docs/public/dev-manual/api/workspace/participation.rst
- docs/public/dev-manual/api/workspace/role_inheritance.rst
- opengever/api/configure.zcml
- opengever/api/participations.py
- opengever/api/role_inheritance.py
- opengever/api/tests/test_invitation.py
- opengever/api/tests/test_participation.py
- opengever/api/tests/test_role_inheritance.py
- opengever/api/tests/test_vocabularies.py
- opengever/workspace/base.py
- opengever/workspace/configure.zcml
- opengever/workspace/participation/browser/manage_participants.py
- opengever/workspace/tests/test_vocabularies.py
- opengever/workspace/vocabularies.py
Issuer: #6167 
Dieser PR ist ein Follow UP von https://github.com/4teamwork/opengever.core/pull/6190.
Der PR implementiert:
> Workspace folder participation

- docs/HISTORY.txt
- opengever/core/testing.py
- opengever/core/testserver.py
Instead of waiting for solr to have restored a backup when setting up the
testlayer, properly tear it down by waiting for solr to be finished restoring.
A symptom of this issue was, that solr logged:
"Restore in progress. Cannot run multiple restore operationsfor the same core":
See https://ci.4teamwork.ch/builds/302050/tasks/496604
This needs to be backported to 2019.4.x, 2019.5.x and 2019.6.x as we test against these versions in RIS.
> Await solr to be restored when tearing down test layers

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20200110182808_add_new_task_from_document_file_action/actions.xml
- opengever/core/upgrades/20200110182808_add_new_task_from_document_file_action/upgrade.py
- opengever/document/fileactions.py
- opengever/document/interfaces.py
This adds the `new_task_from_document` backend action required for 4teamwork/gever-ui#837.
The action will be shown for **documents** and **mails**, whenever the parent context is a dossier and the user is allowed to add a new task to the parent (i.e. has the `opengever.task: Add task` on the parent).
> Add new_document_from_task file_action.

- docs/HISTORY.txt
- opengever/core/upgrades/20200122154137_fix_missing_related_proposal_documents/upgrade.py
- opengever/meeting/proposal.py
Zusätzlich eingereichte Dokumente für einen Antrag verschwinden nach einem Reload im Antrag und erscheinen später wieder
Zope stellt mehrere Threads pro Instanz zur Verfügung. Jeder Thread wiederum hat Zugriff auf ein Pool von ZODB-Verbindungen. 
Wenn wir nun einen Antrag mit einem Dokument als Beilage erstellen, einreichen und anschließend ein zusätzliches Dokument einreichen, erhalten wir für den gleichen Thread verschiedene Objekte der `relatedItems`. Einmal mit nur einem Dokument und einmal mit zwei Dokumenten:
Das bedeutet, je nachdem, welche DB-Verbindung der Thread verwendet, wird ihm die aktuelle Version oder eine veraltete Version des Objektes zurückgegeben. Dies wiederum bedeutet, dass die Änderungen am Objekt nicht in die DB gespeichert werden. Das können wir überprüfen, indem …
> Fix volatile related proposal documents.

- docs/HISTORY.txt
- solr-conf/managed-schema
Adds `filing_no` field to Solr schema.
Tested:
- Installations without the `IFilingNumber` behavior don't index anything into Solr, and search / sorting still works
- Sorting by filing number works for deployments with the activated behavior
Reindexing of the `filing_no` field in Solr for deployments that actually need it can be done as follows:
`http://localhost:8080/plone/@@solr-maintenance/reindex?idxs:list=filing_no`
Addresses #6203
> Add 'filing_no' field to Solr schema.

- docs/HISTORY.txt
- opengever/core/upgrades/20200124171823_correct_public_trial_statement_type/upgrade.py
On some older objects public_trial_statement is saved as unicode on the object which will lead to errors if it contains non ASCII characters. We did not determine in which commit this was fixed and even then we would still need to find out for each deployment when that fix was introduced. Nevertheless we only fix objects older than 2016 as this seems to be a problem only for Zug, and it seems the issue was fixed there mid 2015.
for https://github.com/4teamwork/opengever.core/issues/6204
> Add upgrade step to correct public_trial_statement type.

- docs/HISTORY.txt
- opengever/core/profiles/default/jsregistry.xml
- opengever/core/upgrades/20200128082842_define_overlayhelper_order_in_js_registry/jsregistry.xml
- opengever/core/upgrades/20200128082842_define_overlayhelper_order_in_js_registry/upgrade.py
https://github.com/4teamwork/opengever.core/pull/6202 made an ordering issue in the `jsregistry.xml` surface. Indeed not all installations seem to have `plone.app.jquerytools.overlayhelpers.js` positioned before `opengever.base/prepoverlay.js`, but functions from `overlayhelpers.js` are used in `prepoverlay.js`. Here we correct that ordering issue by ensuring the jquerytools are loaded early, placing them and the things they depend on at the top of the registry.
> Fix JS ordering issue: define overlayhelpers.js position.

- docs/HISTORY.txt
Update changelog in prevision of 2020.0.rc1 release. It seems we forgot to update the CL when making the 2019.6 releases.
> Update CL with 2019.6 releases.

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/sharing.rst
- opengever/api/sharing.py
For https://github.com/4teamwork/gever-ui/issues/864
> Add documentation for sharing endpoint.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_solrsearch.py
- opengever/core/testserver_selftest.py
`solrsearch` failed when we requested the snippets, because `ftw.solr` relies on `UID` being on the `SolrDocument` to extract the snippets from the response. We therefore always need to have the `UID` in the list of requested fields when we request snippets. Here we simply always require the `UID`.
For https://github.com/4teamwork/opengever.core/issues/6184
> Always request UID from solr as it is needed for snippets.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_resolve.py
This is for https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/908
It seems that checking the preconditions for resolving a dossier can be very slow. After inspecting the code I found:
- A bug in the recursion in `ResolveConditions.check_end_dates`, which led to visiting certain objects several times and hence calculating the `earliest_possible_enddate` several times per object in the main dossier.
- A bug in `ResolveConditions.is_all_checked_in`, which only checked documents in the main dossier and within to a depth of 2.
I corrected these two bugs and optimised `DossierContainer.has_valid_enddate` to only calculate `earliest_possible_end_date` when necessary, which is probably almost never in most cases.
This should speed up the precondition calculation quite a bit and I also …
> Speed up validation of dossier resolution preconditions.

- docs/HISTORY.txt
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20200129170738_add_move_proposal_items_action/actions.xml
- opengever/core/upgrades/20200129170738_add_move_proposal_items_action/upgrade.py
- opengever/meeting/browser/configure.zcml
- opengever/meeting/browser/documents/proposalstab.py
- opengever/meeting/browser/move_proposal_items.py
- opengever/meeting/configure.zcml
- opengever/meeting/exceptions.py
- opengever/meeting/handlers.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_move_proposal.py
- opengever/meeting/tests/test_move_proposal_items.py
- opengever/meeting/tests/test_proposal_listings.py
Issuer #6014 
Dieser PR implementiert eine Tabbedview-Action zum Verschieben von Anträgen.
Anträge können nur innerhalb ihres Hauptdossiers verschoben werden.
ℹ️ Die bereits vorhandene View "move_items" kann leider nicht verwendet werden. Siehe https://github.com/4teamwork/opengever.core/issues/6211 für mehr Informationen.
⚠️ Abgrenzung: Es ist momentan nicht möglich, einen Antrag zurück in das Hauptdossier zu verschieben. Das Problem wird hier weiterbehandelt: Siehe https://github.com/4teamwork/opengever.core/issues/6224
❓Verhindert die o.g. Abgrenzung das Schliessen dieses PBIs?
> Allow to move proposals

- docs/HISTORY.txt
- docs/intern/kurzreferenzen/index.rst
- docs/intern/kurzreferenzen/teamraum.rst
- opengever/testing/builders/__init__.py
- opengever/testing/builders/workspaceclient.py
- opengever/workspaceclient/__init__.py
- opengever/workspaceclient/exceptions.py
- opengever/workspaceclient/keys.py
- opengever/workspaceclient/session.py
- opengever/workspaceclient/tests/__init__.py
- opengever/workspaceclient/tests/test_keys.py
- opengever/workspaceclient/tests/test_session.py
Issuer #6205 
Dieser PR implementiert den Auth-Flow gem. #6205 
Mit dieser Anpassung wird opengever.core zum Client gegenüber Serviceapplikationen. Diese Anforderung wird momentan für den Teamraum benötigt. Der Teamraum wird neu als Serviceapplikation als eigenständiges Deployment installiert. GEVER muss sich nun am Teamraum authentisieren können und entsprechende Abfragen absetzen können.
Der PR implementiert die Möglichkeit, das generierte Claim-Set mit dem Private-Key von [ftw.tokenauth](https://github.com/4teamwork/ftw.tokenauth) in GEVER zu speichern und für eine bestimmte URL zu verwenden.
⚠️ Dieser PR implementiert das Key-Handling und die Authentisierung mit [ftw.tokenauth](https://github.com/4teamwork/ftw.tokenauth). Die Teamraum-Integration wird nicht durch diesen PR …
> Implement authentication flow

- docs/HISTORY.txt
- opengever/tabbedview/catalog_source.py
- opengever/tabbedview/tests/test_catalog_source.py
In the InboxDocuments tab, the depth is set to 1 to avoid listing documents in forwardings. This depth restriction was not handled when the query is sent to solr (i.e. when documents are filtered), leading to more documents being displayed when applying a filter.
For https://basecamp.com/2768704/projects/14549453/todos/410114932
> Handle path depth when filtering a table.

- development.cfg
- docs/HISTORY.txt
- docs/intern/kurzreferenzen/teamraum.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20200204154822_add_workspace_client_settings/registry.xml
- opengever/core/upgrades/20200204154822_add_workspace_client_settings/upgrade.py
- opengever/testing/integration_test_case.py
- opengever/workspaceclient/__init__.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/exceptions.py
- opengever/workspaceclient/interfaces.py
- opengever/workspaceclient/session.py
- opengever/workspaceclient/tests/__init__.py
- opengever/workspaceclient/tests/test_client.py
- opengever/workspaceclient/tests/test_keys.py
- opengever/workspaceclient/tests/test_session.py
Issuer #6153 
Dieser PR implementiert den `WorkspaceClient`.
Die Klasse wird für Requests auf einen Teamraum verwendet.
Eine Instanz des Objektes stellt automatisch ein authentisiertes Session-Objekt für den in den Umgebungsvariablen konfigurierten Teamraum zur Verfügung.
Requests werden dabei relativ zum Teamraum gesendet.
```python
client = WorksapceClient()
client.request.get('folder-1')
```
> Add WorkspaceClient to access the connected workspace

- docs/HISTORY.txt
- opengever/api/navigation.py
This is a fix for the devteamraum installation, I think we need to discuss these issues further. I created an issue to decide how to correctly handle teamraum installations (https://github.com/4teamwork/opengever.core/issues/6234)
In a gever installation we always assume that we are actually running a Gever, but it can now also be a Teamraum instead. As such we default the navigation to look for the repository root and display the repository folders. This default does not make sense in the case of a Teamraum installation and leads to an error if there is not repository.
This PR is a simple fix, but we should have some sort of concept of how we want to go about supporting Teamraum installations...
For https://github.com/4teamwork/opengever.core/issues/6181
> Handle deployments with no repository in navigation endpoint.

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/browser/configure.zcml
- opengever/base/browser/folder_buttons_availability.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20200205102852_add_new_task_from_documents_action/actions.xml
- opengever/core/upgrades/20200205102852_add_new_task_from_documents_action/upgrade.py
- opengever/dossier/templatefolder/tabs.py
- opengever/inbox/browser/tabs.py
- opengever/repository/browser/tabs.py
We only return `create_task` in the `@actions` endpoint on dossiers and tasks. Before the action was available everywhere where the user has the `Add task` permission and it was then specifically disabled on some different content_types in the tabs. We now only return the action when it actually should be displayed so that the frontend can rely on the presence of the action in the `@actions` endpoint.
Note that we decided to not display the `new_task_from_document` action  (in the new UI) on documents inside tasks, although the `create_task` action is available on the document listing inside tasks.
> Only return create_task in actions endpoint on dossiers and tasks.

- docs/HISTORY.txt
- opengever/activity/mailer.py
- opengever/workspace/participation/browser/my_invitations.py
- opengever/workspace/participation/invitation_mailer.py
- A workspace installation should have only a single `orgunit`, so that we can find out to which group to assign a user accepting an invitation. The check we were doing for this was wrong as it looked for all org_units, not restricting the search to the `admin_unit` of the workspaces installation. 
- Also change mail header for invitations
For https://github.com/4teamwork/opengever.core/issues/6181
> Fix check for allowed number of orgunits in a workspaces installation.

- docs/HISTORY.txt
- opengever/api/serializer.py
- opengever/core/profiles/default/types/opengever.dossier.businesscasedossier.xml
- opengever/core/tests/test_relations.py
- opengever/core/upgrades/20200206162838_add_linked_workspaces_behavior/types/opengever.dossier.businesscasedossier.xml
- opengever/core/upgrades/20200206162838_add_linked_workspaces_behavior/upgrade.py
- opengever/workspaceclient/__init__.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/configure.zcml
- opengever/workspaceclient/interfaces.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/storage.py
- opengever/workspaceclient/tests/__init__.py
- opengever/workspaceclient/tests/test_client.py
- opengever/workspaceclient/tests/test_linked_workspaces.py
- opengever/workspaceclient/tests/test_serializer.py
- opengever/workspaceclient/tests/test_storage.py
Issuer #6154 
Dieser PR
- implementiert den Store für verknüpfte Arbeitsräume
- implementiert ein Behavior, welches das Auflisten von verknüpften Arbeitsräumen zur Verfügung stellt
- registriert das Behavior für Dossiers
- benutzt den Behavior-Adapter im Item-Serializer wenn das Workspace-Client Feature aktiviert ist und das Objekt das Behavior zur Verfügung stellt
> Linked workspace store with serializer extender

- opengever/workspaceclient/session.py
Wir müssen den `Accept` header explizit setzten bei der Token-Abfrage für den `WorkspaceClient`. Sonst wird in einer Live-Umgebung zum Teil kein JSON zurückgegeben.
Related to #6154
> Add missing header to obtain access token on remote system

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob
We enable solr for every new deployment, so it makes sense to configure this default. 
> Enable the solr flag in the policytemplate.

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default_content/opengever_content/01-initial-structure.json.bob
Realised this issue when creating a new bilingual policy. I took the translations from opengever.demo.
> Add french titles for initial content in the policytemplate.

- docs/HISTORY.txt
- opengever/core/lawgiver.zcml
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20200203174321_add_permission_and_role_to_use_workspace_client/rolemap.xml
- opengever/core/upgrades/20200203174321_add_permission_and_role_to_use_workspace_client/upgrade.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/configure.zcml
- opengever/workspaceclient/permissions.zcml
- opengever/workspaceclient/tests/__init__.py
- opengever/workspaceclient/tests/test_client.py
We add a new role and permission to allow the use of the `WorkspaceClient`. This permission should also be used for API endpoints.
For https://github.com/4teamwork/opengever.core/issues/6192
> Add permission and role to use the Workspace Client.

- docs/HISTORY.txt
- opengever/examplecontent/configure.zcml
- opengever/setup/deploy.py
The reader_group was assigned to the `Member` role which seems incorrect.
Seems like we only configured this for one customer so far, but only retroactively in the policy after a TTW change, see https://github.com/4teamwork/opengever.koeniz/pull/65.
I also add a fake reader group to our dev deployments that make sure the code path to set the group is executed once in a while.
> Assign correct role Reader to reader_group.

- docs/HISTORY.txt
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20200217113801_allow_administrators_to_add_new_keywords/rolemap.xml
- opengever/core/upgrades/20200217113801_allow_administrators_to_add_new_keywords/upgrade.py
Administrators did not have the permission to add new keywords, which can lead to situations where an administrator can add a new dossier, or edit a dossier, but cannot add a keyword on the dossier.
For https://extranet.4teamwork.ch/support/gemeinde-muri-guemligen/tracker/5/
> Allow Administrators to add new keywords.

- docs/HISTORY.txt
- docs/public/dev-manual/api/linked_workspaces.rst
- opengever/api/configure.zcml
- opengever/api/linked_workspaces.py
- opengever/api/tests/test_actions.py
- opengever/api/tests/test_linked_workspaces.py
- opengever/base/browser/folder_buttons_availability.py
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20200218164654_add_copy_documents_to_workspace_action/actions.xml
- opengever/core/upgrades/20200218164654_add_copy_documents_to_workspace_action/upgrade.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/exceptions.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/permissions.zcml
- opengever/workspaceclient/session.py
- opengever/workspaceclient/storage.py
- opengever/workspaceclient/tests/__init__.py
- opengever/workspaceclient/tests/test_client.py
- opengever/workspaceclient/tests/test_linked_workspaces.py
- opengever/workspaceclient/tests/test_storage.py
This PR impements the `@copy-document-to-workspace` endpoint according to the specs in https://github.com/4teamwork/opengever.core/issues/6197#issuecomment-586218068 .
> Implement @copy-document-to-workspace endpoint

- docs/HISTORY.txt
- opengever/activity/browser/templates/notification_mail_macros.pt
- opengever/activity/templates/notification.pt
- opengever/activity/tests/test_digest.py
- opengever/activity/tests/test_mail.py
- opengever/api/tests/test_notifications.py
- opengever/globalindex/model/task.py
- opengever/task/activities.py
- opengever/task/browser/delegate/utils.py
- opengever/task/handlers.py
- opengever/task/task.py
- opengever/task/tests/test_activities.py
- opengever/task/transition.py
- opengever/tasktemplates/browser/form.py
- opengever/tasktemplates/tasktemplatefolder.py
To give more context to the users we add the dossier title in task activities. 
As we want to add the information about the dossier only for certain types of activities, adding a new column in the `Activity` model that would be empty for most activities did not seem to make too much sense, especially that then `Notification` serialization would also need to support cases with or without that field and so on. 
Instead we simply add the dossier title in the `title` field for the task activities in the form `[dossier title] task title`. Adding it in the title will make it visible in the badges, notification mails and digests.
The tabular view (`mynotifications` tab) also displays the notification title, so there too, the dossier name will now appear for task activities.
While I was at it I …
> Add dossier title to task activity titles.

- opengever/api/tests/test_linked_workspaces.py
On of the tests for the `@copy-document-to-workspace` was flaky. Should be fixed now...
> Fix flaky test for the copy-document-to-workspace endpoint.

- docs/HISTORY.txt
- rewrite_rule_smoketests/README.md
- rewrite_rule_smoketests/assertions.py
- rewrite_rule_smoketests/auth.py
- rewrite_rule_smoketests/colors.py
- rewrite_rule_smoketests/config.py
- rewrite_rule_smoketests/config_entities.py
- rewrite_rule_smoketests/registry.py
- rewrite_rule_smoketests/runner.py
- rewrite_rule_smoketests/smoketests.py
Implements some basic smoke test for our rewrite rules and VHost configurations.
Run
```bash
bin/zopepy rewrite_rule_smoketests/smoketests.py
```
to execute the smoke tests. Some tests will require credentials, and will therefore be skipped.
In order to provide those credentials (one pair per cluster), run
```bash
bin/zopepy rewrite_rule_smoketests/smoketests.py --prompt-credentials
```
The credentials (username and password) will then be used to log into the cluster's corresponding portal, get a session, and store those session cookies to `~/.opengever/rewrite_rule_smoketests/`.
The password itself will never be stored.
Addresses #6259
> Add smoke tests for rewrite rules and VHost configs.

- opengever/core/solr_testing.py
When the testserver is installed with a buildout located outside of opengever.core, the bin-scripts (e.g. solr) are not located within the opengever.core checkout or egg directory.
With the new BUILDOUT_DIR environment variable a caller (such as e2e UI tests) can configure the correct buildout dir so that the testserver has access to the scripts.
This change is needed in order to fix the e2e ui tests. I cannot explain why it was not failing up to now; maybe some left overs on the CI server (although this should not be possible since workspaces are wiped).
> Testserver: introduce BUILDOUT_DIR environment variable.

- docs/HISTORY.txt
- opengever/api/tests/test_config.py
- opengever/api/tests/test_user_settings.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/ogds/models/user_settings.py
- opengever/testing/builders/sql.py
- opengever/testing/fixtures.py
- opengever/testing/tests/test_fixtures.py
It seems we have a isolation issue for the SQL db in the `gever-ui` tests. As a result, the tours will get opened in the tests, until one tests closes the tour, which will then leak into the following tests. 
To make it easier for the frontend we set the `seen_tours` attribute to `[*]` for all users in the fixture except one, so that tours will not open in any tests in the frontend. We keep one user with the default settings, i.e. no settings.
For https://github.com/4teamwork/gever-ui/issues/781
> Set seen_tours for all users in test fixture.

- docs/HISTORY.txt
- opengever/setup/deploy.py
- opengever/setup/meta.py
Issuer #6258 
This PR extends the opengever deployment directive with workspace roles.
This lets us define the groups for a specific role in the deployment configuration:
```xml
<opengever:registerDeployment
title="OneGov GEVER"
...
workspace_creator_group="tr_creators"
workspace_user_group="tr_users"
/>
```
> Extend the opengever deployment directive with workspace roles.

- docs/public/release-notes/index.rst
- docs/public/release-notes/release-2020.1.rst
- Display link to release information in public docs
- Also quickly mention OggBundle changes for filesystem migration in changelog
> Link Release 2020.1 in CL.

- rewrite_rule_smoketests/config.py
This PR registers demo.teamraum.ch as a new Cluster for rewrite rule tests.
> Register demo.teamraum.ch to rewrite rule tests

- rewrite_rule_smoketests/smoketests.py
We had a regression in our rewrite rules where POST requests (from Bumblebee) got answered with the `index.html` for the new frontend.
This adds a failing test to ensure this doesn't happen.
The current plan to fix this is to change the RewriteRules in a way that the `index.html` _never_ gets served in response to any request with a method other than `GET`.
_(No changelog entry, since it's a testing only change)._
> Smoketests: Test that POST requests never get answered with index.html.

- rewrite_rule_smoketests/config.py
Since [`dev.onegovgever.ch` has been switched to serve the classic UI by default](https://git.4teamwork.ch/misc/puppet/commit/88923ee96c0bb3daf1e7907e234ecb96a51a4733) (instead of the new UI like before), the smoketests, which are currently failing because of that, need to be updated accordingly.
> Smoketest: Switch dev.onegovgever.ch to classic UI default.

- docs/HISTORY.txt
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/configure.zcml.bob
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/workspaces_content/metadata.xml
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/workspaces_content/opengever_content/01-initial-structure.json
This PR extends the policytemplates with:
- Question to activate the `gever-ui` in the backend (enables the switch to new UI action link in the user-menu)
- Question about the workspaces deployment (will create a new profile to install a teamraum deployment)
- Updates the template to use the single thread setup: https://github.com/4teamwork/opengever.hatchery/pull/53
This PR helps creating new teamraum deployments with `bin/create-policy`
related to #6258
> Extends policytemplates

- rewrite_rule_smoketests/config.py
This change adds configs for `demo.ogg` and `sales.ogg` to the rewrite rule smoketests.
These are two SaaS deployments, one on `ipet` and the other on `sia`, respectively. Current smoketests are passing for these.
> Smoketests: Add demo.ogg and sales.ogg (SaaS deployments).

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/templatefolder.rst
- opengever/api/configure.zcml
- opengever/api/templatefolder.py
- opengever/api/tests/test_templatefolder.py
- opengever/api/tests/test_vocabularies.py
- opengever/dossier/templatefolder/configure.zcml
- opengever/dossier/templatefolder/vocabulary.py
- opengever/dossier/tests/test_documenttemplates_vocabulary.py
This PR adds an api endpoint `@document-from-template` to create documents based on a document template. It also adds a vocabulary `opengever.dossier.DocumentTemplatesVocabulary` that contains the available templates.
The endpoint is very simple and mirrors the functionality currently available in the old UI. It just allows the user to select a template and a title for the document which will be created as a copy of the template.
I have made the following disputable decisions while implementing:
- the vocabulary namespace is `opengever.dossier` as the dossier might in the future restrict the templates that are available. currently it does not though, so we migth also choose `opengever.templatefolder...` as namespace for the vocabulary. If you think so please speak up.
- currently the …
> Add API endpoint to create document from template.

- opengever/wopi/browser/wopi.py
- opengever/wopi/lock.py
- opengever/wopi/tests/test_lock.py
This change fixes some **lock token mismatches** on `PutFile` operations we were seeing because the MS WOPI client sometimes sends incomplete / partial tokens.
I addressed this by moving comparison of the lock tokens to a small helper function that does an exact string comparison in `strict` mode (which is the default), and a more loose comparison otherwise.
We've so far only seen this behavior for the `PutFile` operation, and in these two specific variants:
- The client token is a substring of the server token
- The client token looks like JSON, and contains a subset of the key/value
pairs present in the server token (with keys in the same order).
The **validator tests using docker** pass against this change. _(And they did indeed fail when rejecting any token, or accepting any token)._ …
> WOPI: Fix lock token mismatches on PutFile:

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/browser/folder_buttons_availability.py
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20200310081410_add_list_workspaces_action/actions.xml
- opengever/core/upgrades/20200310081410_add_list_workspaces_action/upgrade.py
- opengever/core/upgrades/20200311140946_move_copy_documents_from_workspace_to_folder_actions/actions.xml
- opengever/core/upgrades/20200311140946_move_copy_documents_from_workspace_to_folder_actions/upgrade.py
The new frontend needs to know when to show the workspace listing block, i.e. when the user has the permission to use the workspace client. Here we:
- Add a new marker action for listing linked workspaces
- Adapt the `copy_documents_to_workspace` and `copy_documents_from_workspace` actions to only show up when the user has the correct permissions.
- Create new action category for UI actions on folders, similarly as was done for `file_actions`.
While `copy_documents_to_workspace` is a `folder_button` on its own right because it is executed for a selection of documents (and is hence in that action category), `list_workspaces` is simply an action available on dossiers. `copy_documents_from_workspace` also belongs into the `folder_actions` as it is not executed on a selection of documents on …
> Add list workspaces action for new frontend.

- docs/HISTORY.txt
- docs/intern/kurzreferenzen/index.rst
- docs/intern/kurzreferenzen/multi-app-setup.rst
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
This PR extends the `@config` endpoint with an `apps_url` attribute.
This URL is required for the GEVER-UI to fetch a list of Applications for the `AppSwitcher` compoment. See https://github.com/4teamwork/gever-ui/pull/1005
Issuer: https://github.com/4teamwork/gever-ui/issues/834
> Extend the @config endpoint with an `apps_url` attribute.

- opengever/api/configure.zcml
- opengever/api/listing.py
We have established the convention that api service classes should be postfixed with the http verb of the request they are handling. It has always annoyed me a bit that @listing with `Listing` does not follow that convention, as it is really useful for example when searching for the class in the editor via globals. so here is the rename to `ListingGet`  to calm down my nerves a bit :).
> Rename Listing to ListingGet to follow naming conventions.

- docs/HISTORY.txt
- opengever/document/checkout/manager.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_checkout.py
- opengever/wopi/browser/edit.py
- opengever/wopi/browser/wopi.py
This introduces the concept of **collaborative checkouts** and applies it to the **OfficeOnline** (WOPI) integration.
> ℹ️  This branch is currently deployed to https://lab.onegovgever.ch/ for easier review 
With this change,
- Documents may be checked in collaborators other than the user that initially checked out the document (_addresses #6229_)
- Collaborators are written to version and journal comment on checkin (_addresses #6230_)
**Caveat**
- The version and journal comments get written as a fixed-language string (in the site's default language at the time of checkin).
> OfficeOnline: Use collaborative checkout / checkins

- rewrite_rule_smoketests/config.py
- rewrite_rule_smoketests/config_entities.py
- rewrite_rule_smoketests/smoketests.py
We want to activate the new frontend for `cloud.onegovgever.ch`. I activated solr and the new UI, but it doesn't work. We probably have a problem with the rewrite rules. So we add `cloud.onegovgever.ch` to the smoketests. This is a bit of a special case, as it is a single unit installation but we have the plone site ID in the URL. I had to add support for that in the smoketests config.
> Add cloud.onegovgever.ch to smoketests.

- docs/schema-dumps/ftw.mail.mail.schema.json
- docs/schema-dumps/opengever.document.document.schema.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
- opengever/bundle/schemas/documents.schema.json
- opengever/bundle/schemas/dossiers.schema.json
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- plonetheme/teamraum/resources/css/gever/partials/_form.scss
As discussed in https://github.com/4teamwork/gever-ui/issues/976 the gever-ui is not able to format form hints using HTML. So change the </br> to a \n. To make the newline character visible in the opengever.core use `white-space: pre-wrap;`. See the `pre-wrap` specification in https://tympanus.net/codrops/css_reference/white-space/.
> Uses newline character to break text for helptext in forms

- docs/HISTORY.txt
- opengever/base/casauth.py
- opengever/base/tests/test_casauth.py
- opengever/base/tests/test_logout.py
- opengever/setup/casauth.py
- opengever/setup/profiles.zcml
- opengever/setup/profiles/casauth_ianus_portal/actions.xml
- opengever/setup/profiles/casauth_ianus_portal/metadata.xml
The new Ianus-Portal provides a differen CAS-Auth URL than the old portal. In the PR: https://github.com/4teamwork/opengever.core/pull/6296 I already tried to permanently use the new url. But that was declined because we still use the old portal for several new deployments.
The URL is part of the plugin and will be set during a profile-hook. If we want to use the new cas-url, we would have to manually adjust it after installation or have to create a new fake-profile in the deployment repositories which will be installed after the `casauth` profile to get an additional hook to reset the URL.
This PR adds a brand new profile `casauth_ianus_portal` which already sets the URL to the new endpoint. We can now just use this new profile instead the old `casauth` to get a deployment with the …
> Add a new profile to setup a cas auth plugin for the new portal

- docs/HISTORY.txt
- opengever/api/schema/querysources.py
- opengever/api/tests/test_vocabularies.py
The query will be used for arbitrary queries containing non-ascii characters. We have to properly sanitize and convert the input query string parameter to unicode for app-internal handling.
@bierik stumbled upon this in https://github.com/4teamwork/gever-ui/issues/839, ironically while improving error handling.
> Fix encoding issue in query-source `query` param.

- docs/HISTORY.txt
- opengever/api/document.py
- opengever/api/tests/test_document.py
This PR extends the document serialization with the `checked_out_fullname` property.
Issuer: https://github.com/4teamwork/gever-ui/issues/982
> Extend the document serialization with `checked_out_fullname`.

- docs/HISTORY.txt
- opengever/api/document.py
- opengever/api/tests/test_document.py
- opengever/document/checkout/templates/checkedoutviewlet.pt
- opengever/document/checkout/viewlets.py
- opengever/document/document.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_checkout_viewlet.py
- opengever/mail/mail.py
- opengever/testing/integration_test_case.py
This displays a different "currently checked out" message for documents that are collaboratively checked out, meaning they're being edited in OfficeOnline.
> ℹ️  **Note**: This branch is deployed on https://lab.onegovgever.ch/ for easier review
---
---
I also added the `is_collaborative_checkout` additional metadata to the API `GET` response for documents, so the frontend can do the same distinction for that message. This could possibly already be used in 4teamwork/gever-ui#982
Part of #6319 
Nein - soll es nicht.
> OfficeOnline: Show specific message for collaborative checkouts.

- docs/HISTORY.txt
- opengever/activity/mailer.py
- opengever/activity/tests/test_mail.py
- opengever/workspace/tests/test_invitation.py
An activity mail should always be sent by the system itself and not under the users email address. It is possible that the user is registered by with a different email address than the portal domain. This will end up in spam issues.
Issuer: #6258  (https://github.com/4teamwork/opengever.core/issues/6258#issuecomment-600501160)
> Do no longer send activity mails from the current user.

- docs/HISTORY.txt
- docs/public/dev-manual/api/globalindex.rst
- opengever/api/globalindex.py
- opengever/api/tests/test_globalindex.py
We update the `@globalindex` endpoint to also return the url to the tasks in the `@id` attribute.
This is needed so that the new frontend can link the tasks in the listing.
For https://github.com/4teamwork/gever-ui/issues/962
> Also return @id in globalindex endpoint.

- docs/HISTORY.txt
- opengever/inbox/tests/test_forwarding.py
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
With https://github.com/4teamwork/opengever.core/pull/6318 we introduced the `hidden` attribute for `OrgUnit`s and `AdminUnit`s and dissalowed selecting users from hidden `OrgUnit`s as responisble for tasks and forwardings. Here we also disallow choosing the inbox of a hidden `OrgUnit` as responsible for a forwarding.
For https://github.com/4teamwork/opengever.core/issues/6129
> Disallow choosing inbox of hidden OrgUnit as responsible in forwardings.

- docs/HISTORY.txt
- opengever/activity/tests/test_mail.py
- opengever/api/tests/test_notifications.py
- opengever/task/activities.py
- opengever/task/tests/test_activities.py
With https://github.com/4teamwork/opengever.core/pull/6270 we added the dossier title in task activities. Here we change the format used to display the dossier titles in these activities, using "dossier title - task title" instead of "[dossier title] - task title"
For https://github.com/4teamwork/opengever.sg/issues/424
> Change container title format in task activities.

- docs/HISTORY.txt
- opengever/document/browser/actionbuttons.py
- opengever/document/browser/templates/macros.pt
- opengever/document/document.py
- opengever/document/fileactions.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_document_tooltip.py
- opengever/document/tests/test_overview.py
This adds the `Edit in Office Online` file action button in the classic UI as well.
> ℹ️  **Note**: This branch is deployed on https://lab.onegovgever.ch/ for easier review ℹ️
It will be shown on:
---
---
---
(Addresses 4teamwork/opengever.sg#421)
This also fixes **action availability**, so that Office Online editing and Office Connector editing flows are mutually exclusive (addresses #6319): When a document is being edited using Office Online, the regular checkout and edit actions are disabled:
---
> Add 'Edit in Office Online' file action button in classic UI.

- docs/intern/kurzreferenzen/appswitcher.rst
- docs/intern/kurzreferenzen/index.rst
- docs/intern/kurzreferenzen/multi-app-setup.rst
- docs/intern/operations/allgemein.rst
- docs/intern/wopi/index.rst
Dieser PR enthält die Dokumentation für das einrichten des neuen App-Switchers.
Follow-Up PR von: https://github.com/4teamwork/gever-ui/issues/834
> Add documentation to configure the app-switcher

- opengever/core/upgrades/20170601103050_add_hidden_flag_to_admin_and_org_units/upgrade.py
The current admin unit is fetched every time the metadata of an object is updated, because of the reference number indexer. This will lead to failing upgrade steps if we do not update the admin_units table first. So we predate this upgrade step to just before the oldest upgrade that has not been executed on all client installations yet.
> Backdate AddHiddenFlagToAdminAndOrgUnit upgrade step.

- docs/HISTORY.txt
- docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
- docs/public/dev-manual/api/schemas/opengever.document.document.inc
- docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
- opengever/api/docsbuilder/schemadocs.py
We need to use newline chars instead of `<br>` in schema  descriptions for new lines because the new UI does not render html  tags in field descriptions.
Unfortunately, using a new-line char will unindent the description block and will raise a sphinx build warning which will cause a test failure.
We remove the newline chars in the description fields completely to fix the layout in the build documentation and to fix the tests.
Issuer: #6340
> Fix documentation build by removing newline chars in description fields.

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/listing_stats.rst
- docs/public/dev-manual/api/listings.rst
- opengever/api/configure.zcml
- opengever/api/listing_stats.py
- opengever/api/tests/test_listing_stats.py
- opengever/api/tests/test_repository.py
Dieser PR fügt den neuen Endpoint `@listing-stats` hinzu. Er gibt für jedes [Listing](https://github.com/4teamwork/opengever.core/blob/master/opengever/api/listing.py#L53) die gesamte Anzahl der Elemente zurück:
Issuer: https://github.com/4teamwork/gever-ui/issues/973
> Add @listing-stats API endpoint to get listing statistics

- docs/HISTORY.txt
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20200401120441_fix_solr_complex_search_pattern/registry.xml
- opengever/core/upgrades/20200401120441_fix_solr_complex_search_pattern/upgrade.py
We used the string formatting argument `title`, but solr passes the argument as `phrase` in https://github.com/4teamwork/ftw.solr/blob/8354f7658a9e301854d671e3d478923509fa55fe/ftw/solr/query.py#L74. This lead to an error when users applied complex search patterns.
The argument has been renamed in https://github.com/4teamwork/ftw.solr/commit/ac91691ef147d9a594a9e19b454654af948e736e but it seems we never updated the configuration in GEVER.
Fixes https://github.com/4teamwork/opengever.core/issues/5937.
> Fix solr complex search pattern configuration.

- .github/pull_request_template.md
Update the PR checklist as discussed in a meeting, the checklist now has an optional and mandatory part as suggested by @elioschmutz. The mandatory part must be left in place and checked off, from the optional part we only keep the relevant items.
Changes:
- split checklist into optional and non-optional parts.
- add/improve description a bit.
- update DoD link to jira.
- amend issue linking, mandatory jira link/backlink.
I have also replaced the DoD in our wiki at https://github.com/4teamwork/opengever.core/wiki/Definition-of-Done and put a link to the new DoD in jira.
_I have not yet translated the checklist but we might wan't to do that eventually._
> Amend PR checklist, optional and mandatory part, link jira issue (if available).

- docs/HISTORY.txt
- opengever/base/service.py
- opengever/base/tests/test_api.py
- opengever/document/static/officeconnector.js
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api_dossier_checkout.py
This prevents documents that are currently being edited in Office Online from being opened (and edited) with OfficeConnector _when the user clicks the "Check out and edit" action in a **stale tab** that hasn't been updated_.
> ℹ️ This branch is deployed on https://lab.onegovgever.ch/ for easier review ℹ️ 
The **steps to reproduce** this issue are:
- Open two tabs for the same document (one that's not checked out yet)
- Start editing the document in Office Online in Tab 1
- Switch to Tab 2, and click the "Check out and edit" action
---
Before this fix, Office Connector was opened, and allowed to to make local changes that could never be saved. With this fix, this is prevented (**classic UI**):
- OC won't launch
- Instead a page refresh will be triggered
-  and then the user will then see …
> Prevent documents being edited in Office Online from getting opened in OfficeConnector.

- docs/HISTORY.txt
- opengever/api/config.py
- opengever/api/tests/test_config.py
- opengever/base/ip_range.py
- opengever/base/tests/test_ip_range_validation.py
- opengever/core/upgrades/20200402115723_add_oc_disallowed_ip_range_setting/registry.xml
- opengever/core/upgrades/20200402115723_add_oc_disallowed_ip_range_setting/upgrade.py
- opengever/document/document.py
- opengever/document/fileactions.py
- opengever/document/interfaces.py
- opengever/document/tests/test_fileactions.py
- opengever/dossier/templatefolder/form.py
- opengever/officeconnector/helpers.py
- opengever/officeconnector/interfaces.py
In this PR we add functionality to hide buttons that would triggere Office Connector when the User is on an EMM environment. 
Implementation:
- For this we add a configuration for ip ranges which are blacklisted for OfficeConnector actions. 
- When the client IP address is in the blacklisted ranges:
- we do not display the OC actions (checkout and edit, edit...)
- The `@actions` endpoint also does not return the OC actions
- We omit the `edit_after_creation` field when 
For https://github.com/4teamwork/opengever.sg/issues/404
> Hide OC actions when user is in EMM environment

- docs/HISTORY.txt
- opengever/activity/mailer.py
- opengever/activity/tests/test_mail.py
- opengever/workspace/tests/test_invitation.py
- setup.py
Revert "Merge pull request #6334 from 4teamwork/es-6285-fix-activiy-mails-in-spam-folder"
This reverts commit a992c60c336efa602bb61fcb9a04120a2e7c5c3f, reversing
changes made to 9c0796ea1c2b0dc31ef52e812ade6bdc391eeb53.
This change is necessary for now as issues with mail dispatching surfaced during a release.
Also we broke the use-case of users getting mail auto-replies, e.g. when the assignee of a task is absent.
Reverted PR: https://github.com/4teamwork/opengever.core/pull/6334
Origin of reverted change: https://github.com/4teamwork/opengever.core/issues/6258#issuecomment-600501160
_Alles muss gemacht/angehakt werden._
> Revert: Do no longer send activity mails from the current user.

- docs/HISTORY.txt
- opengever/dossier/command.py
- opengever/dossier/tests/test_command.py
The CreateDocumentFromTemplateCommand changes the docproperties just after creating the object. This seems to break the indexing of the blob in solr.
I added a test to make sure docproperties still get updated upon document creation from template.
I also tested by hand that the document still gets indexed properly in solr (with up to date docproperties). While doing this I noticed that a document with docporperties gets added 7 times in the solr indexing queue (6 after this change).
For https://github.com/4teamwork/opengever.core/issues/6371
> Fix CreateDocumentFromTemplateCommand.

- docs/HISTORY.txt
- opengever/meeting/tests/test_meeting_zipexport.py
- opengever/meeting/zipexport.py
Exporting a meeting to a zip file will generate a `meeting.json`-file which contains properties with links to the generated documents and agenda items. The` agenda_item_list` document have been included in the zip-file but have not been linked in the `meeting.json`.
This commit extends the `meeting.json` whith the `agenda_item_list` document.
Issuer: https://4teamwork.atlassian.net/browse/GEVER-149
_Alles muss gemacht/angehakt werden._
> Extend the `meeting.json` with a `agenda_item_list` property

- README.rst
The section in the README describing how to set up a local Solr for development purposes is outdated and following it will result in a configuration conflict:
```
raise ConfigurationConflictError(conflicts)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/Users/mbaechtold/Developer/github.com/4teamwork/opengever.core/parts/instance/etc/site.zcml", line 19.2-19.64
ConfigurationConflictError: Conflicting configuration actions
For: ('utility', <InterfaceClass ftw.solr.interfaces.ISolrConnectionConfig>, '')
File "/Users/mbaechtold/Developer/github.com/4teamwork/opengever.core/parts/instance/etc/package-includes/999-additional-overrides.zcml", line 19.4-21.41
<solr:connection host="localhost"
port="8983"
base="/solr/plone"/>
File …
```
> Improve the documentation.

- docs/HISTORY.txt
- opengever/task/helper.py
The `task_type_helper` is a helper function for listings to return the task type title based on a task_type. The used vocabulary is a vdex vocabulary and provides language specific task type titles. The function is decorated with a ram-cache but only with the task_type as a cache-key. That means, if the user changes the language, the cache key is still valid and the returned value will be in the old language.
To fix this problem, we have to make the cache key language dependent.
ℹ️ I don't know why we should remove the function or the cache-decorator (see code). 
ℹ️ This PR fixes both listings, in the old and in the new UI.
Jira: https://4teamwork.atlassian.net/browse/GEVER-99
_Nur Zutreffendes soll angehakt stehengelassen werden._
> Fix `task_type_helper` to respect the current language for the ram-cache.

- docs/HISTORY.txt
- docs/public/dev-manual/api/tasks.rst
- opengever/api/configure.zcml
- opengever/api/task.py
- opengever/api/tests/test_task.py
The response of a GET request of a task now includes the information about the containing dossier of the task. This is achieved by using a custom serializer for the task.
Belongs to the Jira task https://4teamwork.atlassian.net/browse/GEVER-245
> Task GET API: Also include info about containing dossier.

- docs/HISTORY.txt
- opengever/base/configure.zcml
- opengever/base/indexes.py
- opengever/base/tests/test_indexers.py
- opengever/core/profiles/default/catalog.xml
- opengever/core/upgrades/20200429114820_add_is_subdossier_to_catalog_metadata/catalog.xml
- opengever/core/upgrades/20200429114820_add_is_subdossier_to_catalog_metadata/upgrade.py
- opengever/document/tests/test_copy_document.py
- opengever/dossier/configure.zcml
- opengever/dossier/dossiertemplate/configure.zcml
- opengever/dossier/dossiertemplate/indexers.py
- opengever/dossier/indexers.py
- opengever/dossier/tests/test_catalog.py
- opengever/dossier/tests/test_indexer.py
- opengever/dossier/tests/test_move_items.py
It is already an index, but unfortunately not in metadata. We need it for some still catalog based api listings, namely when displaying item summaries for a parent in e.g. a `GET` request on the parent.
I've noticed that documents and other objects within dossiers seem to index the parents value via acquisition. I've disabled that behavior and registered one generic indexer which does return `None` and specific indexers for content types where we should access the `is_subdossier` method on the object.
I have only added an upgrade step for dossiers (and templatedossiers) as those are the only types where the new metadata field is truly relevant. This is a trade-off leaning towards upgrade-step performance.
it will slightly change the indexers behavior:
- the index will contain `False` for …
> Add is_subdossier to catalog metadata.

- opengever/api/task.py
- opengever/api/tests/test_task.py
- opengever/task/task.py
On the detail view of a task (in the new GEVER UI), the  linked dossier must be the main dossier, not the parent of the task. This is mainly relevant for tasks in subdossiers.
This is a follow-up of https://github.com/4teamwork/opengever.core/pull/6387 and belongs to https://4teamwork.atlassian.net/browse/GEVER-246.
> Return main dossier instead of containing dossier.

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/watchers.rst
- opengever/activity/center.py
- opengever/api/configure.zcml
- opengever/api/tests/test_watchers.py
- opengever/api/watchers.py
It should be possible to observe tasks as a watcher in order to stay informed.
This PR provides the API support for watchers. 
With the `@watcher` endpoint, it is possible to query all watchers of a task and their roles and add new watchers with the role `regula_watcher`. In addition, a user can delete his role as `regular_watcher` of a task.
Jira: https://4teamwork.atlassian.net/browse/GEVER-22
> Add @watchers API endpoint

- docs/HISTORY.txt
Update history with 2020.2.4 bugfix release. 
Update history in `master` with the `2020.2.4` bugfix release made for https://4teamwork.atlassian.net/browse/GEVER-279.
> Update history with 2020.2.4 bugfix release. 

- opengever/activity/browser/settings.py
This is a follow-up pr of #6397 
Due to a refactoring, the labels of the general tab in the notification settings have not been displayed correctly.
This PR fixes the issue.
Before:
After:
> Fix labels of notification user settings

- opengever/tabbedview/catalog_source.py
This is a follow-up for what we discussed in https://github.com/4teamwork/opengever.core/pull/6382#discussion_r416655539. We want to catch issues early so we temporarily add explicit logging to sentry to be aware when this happens. Quickly discussed this with @buchi and he's now fine with temporarily adding explicit sentry logging until we manage to get messages from `logging` into sentry with https://4teamwork.atlassian.net/browse/GEVER-233. 
Motivation:
- we want to see when this issue happens in production early, especially now after we have our new solr listings
- if we just `log`, even with `error` level we won't be aware of the error in production as only exceptions are logged to sentry with our current sentry integration
- we have already adopted the strategy of explicit logging in …
> Add explicit sentry logging for unknown sort_on.

- docs/HISTORY.txt
- opengever/meeting/browser/proposalforms.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_vocabularies.py
- opengever/meeting/vocabulary.py
The proposal templates weren't filtered anymore by the selected committee. This should by repaired in this PR.
In commit 31b96c4ea3b395224d1307b5c11dccfb3898898e the field 'committee' was renamed to 'committee_oguid'. This had the consequence that a select field was renamed what caused that form.widgets.proposal_template wasn't updated anymore when changing the value in the select box.
Also the vocabulary filtered not correctly also due the switch to oguid.
Jira Issue -> https://4teamwork.atlassian.net/browse/GEVER-268
> Show proposal template corresponding to the committee.

- opengever/base/handlers.py
A new event handler was introduced for repositoryfolders which uses the IIntID utility (see https://github.com/4teamwork/opengever.core/pull/6386). This will fail when deleting the plone site root as the utility might get deleted before the repositoryfolders.
For https://4teamwork.atlassian.net/browse/GEVER-327 and https://4teamwork.atlassian.net/browse/GEVER-247
> Fix plone site deletion issue.

- docs/HISTORY.txt
Update History after backport of ftw.solr bump to 2020.2.5.
> Fix changelog after backport to 2020.2.5.

- docs/HISTORY.txt
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/catalog_source.py
In https://github.com/4teamwork/opengever.core/pull/6382 and https://github.com/4teamwork/opengever.core/pull/6404 we have introduced explicit logging for potential issues in solr listing. We now have already found some cases where we need special handling/fixes. This PR addresses the following issues
- Pop sorting parameters from solr query to avoid attempting to handle them as schema fields
- No longer sort by `sortable_author` in solr as no such field exists, instead `document_author` should be used
Furthermore we should also log to sentry when we encounter unknown fields as more issues may appear.
For https://4teamwork.atlassian.net/browse/GEVER-328
> Drop sorting by sortable_author for solr and avoid handling sorting parameters as fields.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/tests/test_config.py
- opengever/base/tests/test_utils.py
- opengever/base/utils.py
- opengever/sharing/browser/sharing.py
- opengever/tabbedview/browser/personal_overview.py
- opengever/task/browser/transitioncontroller.py
This new information is used by the the GEVER UI in order to determine if it should display the menu item "Verwaltung" in the navigation drawer. 
The chosen solution has been discussed with @all4manu and @deiferni prior to its implementation and was deemed as a "good-is-good-enough" solution. All other options we discussed (dedicated endpoint @navigationdrawer, enhancement of @navigation or @actions endpoints) were deemed bloated, "unnatural" or violated the YAGNI principle.
This pull requests belongs to [GEVER-297](https://4teamwork.atlassian.net/browse/GEVER-297), a sub task of the Jira issue [GEVER-36](https://4teamwork.atlassian.net/browse/GEVER-36).
> Add "is_admin_menu_visible" to the @config API endpoint.

- docs/HISTORY.txt
- opengever/api/solrsearch.py
- opengever/api/tests/test_solrsearch.py
Jira: https://4teamwork.atlassian.net/browse/GEVER-285
The `@solrsearch` endpoint sorts the results by its `score`. That the most relevant search result is at the top, we have to sort by `desc` instead `asc`:
> score desc | Sorts in descending order from the highest score to the lowest score [Solr Documentation](https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html#CommonQueryParameters-ThesortParameter )
> Fix @solrsearch endpoint default sort order

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/solr_query_service.py
- opengever/api/solrsearch.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_solrsearch.py
Jira: https://4teamwork.atlassian.net/browse/GEVER-290
This PR:
- Added a feature for the `@solrsearch` endpoint to provide the same facets like the `@listing` endpoint. This means, a facet can now be requested by entering the exact solr index name like `Creator` or a self defined `ListingField`-Name like `creator` (https://github.com/4teamwork/opengever.core/blob/master/opengever/api/solr_query_service.py#L200).
- Fixes an issue where facet values have not been tranformed if requesting a facet based on a `ListingField` (i.e.: `/@listing?name=documents&columns=title&facets=creator`)
> Fix an issue where solr facet labels have not been transformed correctly

- docs/HISTORY.txt
- opengever/api/invitations.py
- opengever/api/tests/test_invitation.py
- opengever/api/tests/test_validation.py
- opengever/api/validation.py
Jira: https://4teamwork.atlassian.net/browse/GEVER-357
The `@invitation` endpoint is currently hard-validating the json-body and will raise an error if there is an unknown attribute. That's not the same behavior like the default plone restapi for adding resources.
This PR refactors the endpoint to extract all relevant attributes from the body.
**Side-Info**
The frontend provides a generic add form which uses a predefined schema for a type. Since an invitation is a kind of type in the frontend, it also sends the `@type` property to the server for adding a new invitation.
This will raise an error on the backend because `@type` is not part of the `IWorkspaceInvitationSchema`:
`BadRequest: [(u'@type', UnknownField(u'@type'))]`
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/67036/
Of …
> Skip unknown attributes in POST @invitation endpoint.

- docs/HISTORY.txt
- opengever/activity/tests/test_listing.py
- opengever/activity/tests/test_mail.py
- opengever/activity/tests/test_notification_viewlet.py
- opengever/activity/tests/test_resolve.py
- opengever/activity/tests/test_views.py
- opengever/api/tests/test_watchers.py
- opengever/disposition/tests/test_activities.py
- opengever/meeting/tests/test_activites.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_forms.py
- opengever/task/tests/test_team_tasks.py
- opengever/task/tests/test_transition_actions.py
- opengever/testing/fixtures.py
- opengever/workspace/tests/test_activities.py
Since the `activity` feature is not enabled when creating tasks (and forwardings) in the `OpengeverContentFixture`, no subscriptions, resources and watchers are created in the database for the tasks.
Currently it is not possible to enable the feature, so the required content is now created manually for each task.
Now subscriptions, resources and watchers for tasks no longer need to be created first in each test
Jira: https://4teamwork.atlassian.net/browse/GEVER-32
> Add watchers, resources and subscriptions to tasks and forwarding in fixtures

- docs/HISTORY.txt
- opengever/tasktemplates/tasktemplatefolder.py
- opengever/tasktemplates/tests/test_activities.py
If new tasks were created with the task templates and the standard process was not triggered, no watchers were created in the database for the main task. 
The `IDuringTaskTemplateFolderTriggering` inteface prevents a `TaskAddedActivity` from being triggered when creating tasks from task templates. Therefore no watchers are created.
Now a `TaskAddedActivity` is also triggered for the main task, so the watchers are also created.
Jira: https://4teamwork.atlassian.net/browse/GEVER-32
> Fix activity bug when creating tasks with tasktemplates.

- docs/HISTORY.txt
- opengever/repository/repositoryfolder.py
The previous implementation was not performing well for repository folders containing lots of folders, because `contentItems` is not lazy. It should only be used for small number of items (see https://docs.plone.org/develop/plone/content/listing.html).
Furthermore, the exit condition has been improved due to the fact that a a repository folder cannot contain other repository folders and items of other content types at the same time.
Belongs to the Jira issue [GEVER-375](https://4teamwork.atlassian.net/browse/GEVER-375) (which contains the proposed solution and a flame graph).
> Improve performance while determining leaf node state.

- docs/HISTORY.txt
- opengever/repository/deleter.py
`listFolderContents` honors the currently logged-in user roles, so the computed value might be misleading. Furthermore it is slow for large folders (see https://docs.plone.org/develop/plone/content/listing.html#getting-folder-objects-filtered).
Belongs to [GEVER-373](https://4teamwork.atlassian.net/browse/GEVER-373) (which contains the proposed solution and a flame graph).
> Improve performance while determining repositoryfolder emptiness.

- docs/HISTORY.txt
- docs/public/dev-manual/api/watchers.rst
- opengever/activity/sources.py
- opengever/activity/tests/test_sources.py
- opengever/api/configure.zcml
- opengever/api/tests/test_watchers.py
- opengever/api/watchers.py
Jira: https://4teamwork.atlassian.net/browse/GEVER-320
This PR implements the `@possible-watchers` endpoint.
The Endpoint returns users without a watcher-role on the current context. The results are sorted by last and first name. The current user will be returned on the first position if he is part of the result-set.
> Implement @possible-watchers endpoint

- docs/HISTORY.txt
- opengever/dossier/browser/navigation.py
- opengever/dossier/browser/overview.py
- opengever/dossier/browser/templates/overview.pt
- opengever/dossier/resources/init_tree.js
- opengever/dossier/tests/test_navigation.py
We can remove the server-side checks because when the checks are positive (which are called twice by the way), the data needs to be fetched anyway. So instead we simply try to get the data and render the empty message when there is no data to be displayed.
Belongs to [GEVER-388](https://4teamwork.atlassian.net/browse/GEVER-388)
> Improve performance of the subdossier tree.

- docs/HISTORY.txt
- opengever/base/source.py
- opengever/base/tests/test_source_binder.py
This PR fixes a bug which allowed to move documents from a businesscasedossier to a private dossier, which is almost equivalent to deleting the document. 
Private dossiers were not selectable when using the selection widget with navigation, but were selectable when using searching for them using a query. The issue was that the `RepositoryPathSourceBinder` restricts the navigation to the current repository but not the query.
**Note for reviewer: I first pushed failing tests to better show that the second commit actually fixes the issue**
For https://4teamwork.atlassian.net/browse/GEVER-337
> Test that RepositoryPathSourceBinder is limited to current repository.

- opengever/base/tests/test_solr.py
- opengever/core/hooks.py
- opengever/core/upgrades/20200518084137_cleanup_catalog_indexes_and_metadata/upgrade.py
- opengever/document/tests/test_copy_document.py
- opengever/dossier/tests/test_move_items.py
This also introduces a profile hook which removes unneeded catalog indexes and metadata when a fresh GEVER is installed.
> Remove catalog indexes and metadata of "plone.app.discussion".

- opengever/api/tests/test_watchers.py
- opengever/api/watchers.py
The `@watchers` endpoint will fail for watchers that aren't users (for example system users, inactive ogds-users...). Activities use Actors most everywhere and the watcher endpoints should do the same. This PR avoids `@watchers` to fail for such users, but this is not a definitive fix, as for example `@id` will not be correct for watchers that are not users and the `fullname` attribute does not really make sense for actors and should be renamed. I opened an issue to have a closer look at the watchers, but basically `Actor`s should be used most everywhere and should know the URL with which a given actor can be accessed over the API (https://4teamwork.atlassian.net/browse/GEVER-406). Moreover the Frontend will need to deal with actors as well.
Sentry: …
> Fix issue in watchers endpoint with inactive ogds-users.

- docs/HISTORY.txt
- docs/public/dev-manual/api/allowed_roles_and_principals.rst
- opengever/api/tests/test_allowed_roles_and_principals.py
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20200515162243_assign_permission_to_service_key_user_role/rolemap.xml
- opengever/core/upgrades/20200515162243_assign_permission_to_service_key_user_role/upgrade.py
Among various possible solutions, this was deemed the most appropriate one (as discussed extensively between Lukas, Elio and Martin). The creation of an additional role was considered "overkill". The chosen role seems the most appropriate at the moment.
Belongs to the Jira issue [GEVER-339](https://4teamwork.atlassian.net/browse/GEVER-339)
> Assign permission to role "ServiceKeyUser".

- base-plone-4.3.x.cfg
Currently setuptools is unpinned in tests which results in picking an
incompatible version that no longer supports Python 2.7.
Installation itself currently does not fail, but some eggs (e.g.
zope.interface) are not installed correctly and tests fail because of
that. This does not manifest when using shared eggs and the affected
eggs were installed with an older setuptools before.
By extending from test-versions-plone-4.cfg we include our known
version constraints for Plone 4.3/Python2.7.
> Add version constraints for tests with Plone 4.3

- docs/HISTORY.txt
- opengever/document/widgets/document_link.py
Doing a permission check for catalog brains is needless as catalog
searches are security aware anyway.
This improves the performance of the documents tab.
Jira: https://4teamwork.atlassian.net/browse/GEVER-374
> Avoid object lookup in DocumentLinkWidget for catalog brains

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/browser/contenttree.py
- opengever/base/browser/resources/contenttree.js
- opengever/base/browser/templates/fragment.pt
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base.pot
- opengever/base/tests/test_contenttree.py
- opengever/core/profiles/default/jsregistry.xml
- opengever/core/tests/test_view_security.py
- opengever/core/upgrades/20200525170008_handle_large_contenttrees/jsregistry.xml
- opengever/core/upgrades/20200525170008_handle_large_contenttrees/upgrade.py
No longer load all children but limit the maximum number to 100 when browsing related items using the content tree widget. Provide a "load more" link to load the next batch.
This fixes performance issues when having items with a large amount of children.
https://4teamwork.atlassian.net/browse/GEVER-374
> Improve contenttree widget in handling a large amount of items

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/users.rst
- opengever/api/configure.zcml
- opengever/api/serializer.py
- opengever/api/team.py
- opengever/api/tests/test_ogdsuser.py
- opengever/api/tests/test_team.py
- opengever/api/tests/test_teamlisting.py
There are naming conventions for the REST API that state that the plural should be used for endpoint names.
https://plonerestapi.readthedocs.io/en/latest/conventions.html#singluar-vs-plural
Therefore the endpoint `@team` is renamed to `@teams`.
Jira: https://4teamwork.atlassian.net/browse/GEVER-418
> Rename @team API endpoint to @teams.

- docs/HISTORY.txt
- opengever/document/widgets/document_link.py
Related to #6458
Doing a permission check for Solr documents is needless as Solr searches are security aware anyway.
This improves the performance of the documents tab.
Jira: https://4teamwork.atlassian.net/browse/GEVER-374
> Avoid object lookup in DocumentLinkWidget for Solr documents

- docs/HISTORY.txt
- opengever/activity/hooks.py
- opengever/core/upgrades/20200430153116_merge_notification_settings/upgrade.py
The `MergeNotificationSettings` relies on the main notification configuration which leads to issues when upgrading multiple upgradesteps changing the notification defaults.
This PR uses a static configuration for the `MergeNotificationSettings` upgradestep` to fix this issue.
I manually updated the dev.onegovgever.ch ogds with:
```sql
update notification_defaults set digest_notification_roles='["workspace_member_role"]' where id=173;
update notification_defaults set digest_notification_roles='["workspace_member_role"]' where id=174;
```
to add the missing digest configuration.
> Fix MergeNotificationSettings upgradestep to use a fixed configuration

- development-multi-admin.cfg
Because we override the `zcml-additional` variable in the `development-multi-admin.cfg` we have to manually include the solr-configuration to get a working solr-config.
How to reproduce:
Run a multi-admin unit instance with the `development-multi-admin.cfg` and try to activate solr.
> Fix missing solr config for multi-admin setup

- opengever/base/tests/test_source_binder.py
`RepositoryPathSourceBinder` requires Solr, so it makes no sense to test it against the catalog. The test even fails because we removed the index "SearchableText" in a previous commit.
> Remove test.

- docs/HISTORY.txt
- opengever/base/role_assignments.py
- opengever/usermigration/__init__.py
- opengever/usermigration/localroles.py
- opengever/usermigration/tests/test_localroles.py
Wit this PR we customize the local roles migrator from `ftw.usermigration` as implemented in https://github.com/4teamwork/ftw.usermigration/blob/9fc23a52dc6e3c95b10e89e6c2d043663cd650dd/ftw/usermigration/localroles.py#L26-L47.
We only allow setting local roles via `RoleAssignmentManager` as of https://github.com/4teamwork/opengever.core/pull/4551 and no longer allow setting them directly via the management methods of plone/zope. The package `ftw.usermigration` was using these methods, however. This lead to an error when attempting to migrate.
With this PR we adapt the local role migration to migrate all local roles set via `RoleAssignmentManager`. This includes roles assigned via sharing, but also includes automatic roles assigned by the systems. As far as i could see they are not …
> Implement custom gever localroles migrator.

- docs/HISTORY.txt
- docs/public/dev-manual/api/extract_attachments.rst
- docs/public/dev-manual/api/index.rst
- docs/public/user-manual/dokumente/ablegen.rst
- opengever/api/configure.zcml
- opengever/api/mail.py
- opengever/api/tests/test_document.py
- opengever/api/tests/test_mail.py
- opengever/api/tests/test_move.py
- opengever/journal/configure.zcml
- opengever/journal/handlers.py
- opengever/mail/browser/extract_attachments.py
- opengever/mail/browser/templates/extract_attachments.pt
- opengever/mail/configure.zcml
- opengever/mail/events.py
- opengever/mail/exceptions.py
- opengever/mail/interfaces.py
- opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/opengever.mail.pot
- opengever/mail/mail.py
- opengever/mail/subscribers.py
- opengever/mail/tests/test_extract_attachments.py
- opengever/mail/tests/test_mail.py
- opengever/mail/tests/test_ogmail.py
- opengever/mail/tests/test_subscribers.py
In order to be able to work with Mails in the GEVER-UI we needed several changes in the backend:
- return the attachments in the GET of `Mail`s, to allow representing attachments in the detailview
- A new endpoint `extract-attachments` to extract the attachments of an `Mail` as a separate document
There are also some new requirements for `Mail`s, that will allow a more modern representation of mails in GEVER:
- Each attachment should only be extracted once
- For each attachment the `Mail` should store a link to the extracted document
- deleting of attachments from the `Mail` itself should not be allowed anymore (mail messages should be immutable)
This allows to represent each attachment as either a link to the extracted document or as a link to extracting the attachment.
On the technical …
> Add attachments in mail serializer.

- docs/HISTORY.txt
- docs/public/dev-manual/api/webactions.rst
- opengever/webactions/exceptions.py
- opengever/webactions/renderer.py
- opengever/webactions/storage.py
- opengever/webactions/tests/test_webactions_renderer.py
- opengever/webactions/tests/test_webactions_storage.py
This pull request adds support for placeholder in the target urls of the webactions. The placeholders will be replaced with their actual value when the target url is rendered in GEVER.
Until now, the two query params `context` and `orgunit` were appended to the target url unconditionally. This feature is kept, but the creators of the webaction may chose to request more data (`uid`, `intid` and `path`).
Belongs to Jira issue [GEVER-147](https://4teamwork.atlassian.net/browse/GEVER-147).
> Support placeholders in the target url of the webactions.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/tests/test_config.py
Right now, the Bumblebee preview does not work in the new GEVER UI, if two GEVER are deployed under the same domain because it fetches the Bumblebee cookie only when no cookie is present. The cookie it got from the first deployment is not respected by the second deployment causing the preview to fail (a "missing" image is rendered instead).
See the Jira issue for a detailed explanation of the problem.
⚠️ Requires https://github.com/4teamwork/gever-ui/pull/1116
Belongs to Jira Issue [GEVER-427](https://4teamwork.atlassian.net/browse/GEVER-427)
> Add "bumblebee_app_id" to the @config API endpoint.

- docs/HISTORY.txt
- opengever/dossier/browser/configure.zcml
- opengever/dossier/browser/navigation.py
- opengever/dossier/browser/overview.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_navigation.py
- opengever/dossier/tests/test_overview.py
Use Solr for dossier overview. This includes getting documents and the dossier navigation.
Jira: https://4teamwork.atlassian.net/browse/GEVER-374
> Use Solr for dossier overview

- docs/HISTORY.txt
- opengever/ogds/base/sync/ogds_updater.py
The logger should be as early as possible.
If the script fails somewhere we should know which group is affected.
This PR does not fix broken (recursive) groups but it makes debugging much easier.
Jira: https://4teamwork.atlassian.net/browse/GEVER-479
> Move the ogds groups import logger more up in the script.

- docs/HISTORY.txt
- docs/public/dev-manual/api/templatefolder.rst
- opengever/api/configure.zcml
- opengever/api/tests/test_templatefolder.py
As requested in the Jira issue, the user must be able to create documents (from templates) within tasks too. So we need to register the API endpoint for the content type "Task" too.
Belongs to Jira issue https://4teamwork.atlassian.net/browse/GEVER-435
> Enable API endpoint @document-from-template for tasks.

- docs/HISTORY.txt
- docs/public/user-manual/aufgaben/erstellen.rst
- docs/schema-dumps/opengever.task.task.schema.json
- opengever/activity/center.py
- opengever/activity/handlers.py
- opengever/activity/tests/test_notification_center.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/inbox/forwarding.py
- opengever/inbox/tests/test_activities.py
- opengever/inbox/tests/test_forwarding.py
- opengever/ogds/base/sources.py
- opengever/task/activities.py
- opengever/task/browser/forms.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/task.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_forms.py
- opengever/task/tests/test_task.py
We add a new `informed_principals` field to the `TaskAddForm`, listing principals that will receive a notification for the newly created `Task`. This allows avoiding having to create separate `Task`s just to inform certain users about a new `Task`.
This is implemented by temporarily adding watchers to the `Task` before creation and removing them directly after, so that they just get informed of the creation itself. As they get added in the `WATCHER_ROLE` we need to avoid generating a `WatcherAddedActivity`. Note that we refactor the generation of the `WatcherAddedActivity` a bit, as I found it a bit confusing that they such an activity only gets generated when I add the watcher through the `PloneNotificationCenter` but not if I used the `NotificationCenter`. 
We also only show the field …
> Allow notifying users and groups when creating a new task.

- docs/HISTORY.txt
- docs/public/dev-manual/api/tasks.rst
- opengever/api/configure.zcml
- opengever/api/tests/test_task.py
- opengever/api/transition.py
This PR updates the `@workflow` endpoint for tasks to allow the use of a combined responsible value.
The ``@querysource`` of the responsible Field returns combined token values:
```json
{
"@id": "task-4/@querysources/opengever.task.task/responsible?query=L",
"items": [
{
"title": "DEIFS_LAUTE_GRUPPE (Steuerverwaltung)",
"token": "team:427"
},
{
"title": "rk_leitung (Amt für Informatik)",
"token": "team:420"
}
]
}
```
We want to directly reuse this tokens to reassign a new task.
Jira: https://4teamwork.atlassian.net/browse/GEVER-71
> Support combined notation for task responsible in workflow transitions.

- docs/HISTORY.txt
- opengever/base/quickupload.py
- opengever/mail/mail.py
- opengever/mail/tests/test_ogmail.py
- opengever/mail/utils.py
- opengever/testing/assets/mail_with_one_p7m_attachment.eml
When extracting p7m attachments for mails they were created as a document by mistake. This PR makes sure we use the same special handling when extracting p7ms as during D&D upload and during mail-in unwrapping. We make sure the extracted part is correctly created as another mail and not as a a document.
https://4teamwork.atlassian.net/browse/GEVER-467
> Fix p7m attachment extraction from mails.

- docs/public/dev-manual/api/tasks.rst
This PR fixes a type on the `tasks.rst` of the `dev-manual` introduced in #6484
> Fix typos in the dev-manual of tasks.rst

- docs/HISTORY.txt
- opengever/activity/mailer.py
- opengever/activity/tests/test_mail.py
- opengever/base/interfaces.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20200609102902_add_iog_mail_settings_registry_record/registry.xml
- opengever/core/upgrades/20200609102902_add_iog_mail_settings_registry_record/upgrade.py
- opengever/workspace/tests/test_invitation.py
- Don't send mails with `From:` addresses other than our own
- Instead set a `Reply-To:` header containing the human actor's address
- Make this new behavior the default, but configurable
This avoids sending activity mails with `From:` addresses of OGDS users, which would effectively be spoofing, and instead uses the Plone site's sender address as configured in the mail settings.
In addition, a `Reply-To:` header with the user's address is set instead for mails that are triggered based on the action of a human actor (in the hope that out-of-office replies will be sent there, still reaching the human actor).
In contrast to what's been outlined in the story / done before in #6334, I chose to still use the **user's full name** in the `From:` header (just like GitHub does for example), and …
> Don't send mails with From-Addresses other than our own, and set Reply-To header

- docs/HISTORY.txt
I have decide to also move the ftw.mail bump to 2.6.2 as it is included
in the 2.7.0 bump.
for https://4teamwork.atlassian.net/browse/GEVER-59
> Update changelog after 2020.2.6 hotfix release.

- docs/HISTORY.txt
- opengever/activity/model/watcher.py
- opengever/activity/notification_settings.py
- opengever/activity/tests/test_hooks.py
- opengever/activity/tests/test_model.py
- opengever/activity/tests/test_notification_center.py
- opengever/activity/tests/test_settings.py
- opengever/activity/tests/test_watcher.py
- opengever/core/upgrades/20200608170947_add_watcher_role_to_task_added_mail_notification_settings/upgrade.py
- opengever/ogds/base/actor.py
- opengever/ogds/base/browser/userdetails.py
- opengever/ogds/base/tests/test_actor.py
- opengever/ogds/base/utils.py
- opengever/sharing/browser/sharing.py
- opengever/task/handlers.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/task.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_response_viewlet.py
- opengever/task/viewlets/response.py
This is a followup PR to https://github.com/4teamwork/opengever.core/pull/6475. In this PR we fix a bug and add some polish according to feedback from the PO.
**Bugfix:**
- We fix a bug with groups selected in the `informed_principals` field. Groups were not handled correctly in the activities. Specifically we had to:
- Add `OGDSGroupActor` class.
- Make sure that `Watcher.get_user_ids` returns the representatives for a group, so that all representatives of the group get notified when a task is added
**Polish:**
- Reorder fields in task add form.
- Show informed principals in task added history.
- Add watcher role to task added mail notification settings, so that by default users get notified by mail of a task creation when they are in the `informed_principals`. For this upgrade, we only …
> Fix and polish new info at feature.

- docs/HISTORY.txt
- docs/schema-dumps/_opengever.ogds.models.user.User.schema.json
- opengever/api/tests/test_ogdsuser.py
- opengever/core/upgrades/20200610151807_drop_import_stamp_column_from_user_model/upgrade.py
- opengever/ogds/base/sync/ogds_updater.py
- opengever/ogds/base/tests/test_ogds_updater.py
- opengever/ogds/models/group.py
- opengever/ogds/models/tests/test_user.py
- opengever/ogds/models/user.py
This is a followup PR to #6477 
Currently the last_login field is overwritten with None every time the LDAP is synchronized, because the field is not mapped to LDAP.
This has been corrected by the OGDSUpdater no longer synchronizing all fields of the user models, but only those that are in a set (column_names_to_sync). The same applies to the group model.
Furthermore the column import_stamp of the user model was deleted, because it is not used anymore.
Jira: https://4teamwork.atlassian.net/browse/GEVER-39
> Define a set of columns that get synchronized in user and group model and remove import_stamp

- docs/HISTORY.txt
- opengever/base/sentry.py
Explicitly log to sentry for two `ftw.solr` modules we want to monitor well at the moment.
The package `ftw.solr` currently only logs potentially critical issues in https://github.com/4teamwork/ftw.solr/blob/6f1db34678b4271e3b2640b85e4f11b6c8795fa3/ftw/solr/connection.py and https://github.com/4teamwork/ftw.solr/blob/6f1db34678b4271e3b2640b85e4f11b6c8795fa3/ftw/solr/handlers.py. With our currenty sentry integration only exceptions end up in sentry.
With this PR we add a very simple log-handler and specifically register it for the two modules. It also logs the messages (for certain levels) to sentry. Some examples:
- https://sentry.4teamwork.ch/sentry/onegov-gever/issues/68017
- https://sentry.4teamwork.ch/sentry/onegov-gever/issues/67593
- …
> Add minimalistic log handler for sentry.

- docs/public/dev-manual/api/listing_stats.rst
- opengever/api/listing_stats.py
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_listing_stats.py
In the new frontend, we use the `listing-stats` endpoint to show the total number of items in the different tabs, without having to query the corresponding listing. But there are several places where we have hidden filters, for example:
- only show dossiers for current responsible on the dashboard
- only show `opengever.document.document` in template folder and not all `BaseDocument`
- only count main dossiers and tasks in the respective tabs... 
So to get be able to display the correct total item counts in such situations, we add support for pivot queries in the `listing-stats` endpoint. This allows to define queries as request parameter for which statistics will be calculated for each pivot. I also added support for `depth`, which we will need to get the correct counts for main dossiers …
> Add support for pivot queries in listing-stats endpoint.

- docs/HISTORY.txt
- docs/public/dev-manual/api/searching.rst
- opengever/api/listing.py
- opengever/api/listing_stats.py
- opengever/api/solr_query_service.py
- opengever/api/solrsearch.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_solrsearch.py
For the new Widget to choose objects from a tree like structure (https://4teamwork.atlassian.net/browse/GEVER-472) we need to be able to search for subdossiers directly contained in given dossier (we want to load items only one level at a time when the user actually clicks a given container). The `solrsearch` endpoint did not handle the `depth` parameter, and hence did not allow for any convenient way to search inside a given container. Moreover the `solrsearch` did not take into account the `context` on which it was called, but always search on the root, except if the `path` filter was specified. The new behavior is:
- search recursively when `depth` is not specified
- search on context when `path` filter is not specified
- search in given `path` when `path` filter is specified
**This is …
> Handle depth filter in solrsearch endpoint.

- docs/HISTORY.txt
- opengever/core/solr_testing.py
In case 'SOLR_PORT' is already set in env it can't be overwritten by the configured port and in order to fix this setdefault() is replaced.
**Background**
For some reason I have defined a Solr port as env variable global. This had the consequence that my Solr did not work in the tests. In an exhausting debugging session we found out that "setdefault" was used to set the correct port. But here the value is only set if the value is not yet available. This had the consequence that a completely wrong port was used.
Was solved as part of https://4teamwork.atlassian.net/browse/GEVER-462.
> Always use configured solr port

- docs/HISTORY.txt
- docs/public/dev-manual/api/assigned_users.rst
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/notifications.rst
- docs/public/dev-manual/api/tasks.rst
- opengever/activity/center.py
- opengever/activity/tests/test_notification_center.py
- opengever/api/assigned_users.py
- opengever/api/configure.zcml
- opengever/api/permissions.zcml
- opengever/api/tests/test_assigned_users.py
- opengever/api/tests/test_transfer_task.py
- opengever/api/transfer.py
- opengever/core/lawgiver.zcml
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20200605095549_assign_transfer_permission/rolemap.xml
- opengever/core/upgrades/20200605095549_assign_transfer_permission/upgrade.py
- opengever/task/activities.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/response_description.py
- opengever/task/tests/test_activities.py
The possibility should be created to transfer all tasks of one user to another. This means all tasks where the user is the responsible and/or the issuer.
This required some backend work:
- The new endpoint `@assigned-users` provides a vocabulary of all users of the current admin unit. The frontend needs this list to get all possible users to which the task could be transferred.
- To transfer a task, the new endpoint `@transfer-task` is required. The endpoint is protected by a new permission `opengever.api.TransferAssignment`, which allows only administrators and managers to use the endpoint.
- A new header `X-GEVER-SuppressNotifications` is introduced, with which it is possible to suppress the triggering of a notification.
Currently, only local tasks can be transferred, not cross-client …
> Add new endpoints @assigned-users and @transfer-task

- docs/HISTORY.txt
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
Quering `ContactsSource` and `UsersContactsInboxesSource` failed for contacts without an E-mail. There are two corresponding sentry issues:
- https://sentry.4teamwork.ch/sentry/onegov-gever/issues/67485
- https://sentry.4teamwork.ch/sentry/onegov-gever/issues/67921
For https://4teamwork.atlassian.net/browse/GEVER-367
> Fix contact query sources for contacts without an E-mail

- docs/HISTORY.txt
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
We want to be able to filter for all checked out documents. For this we must be able to make a query of this type: `http://localhost:8080/fd/@listing?name=documents&facets:list=checked_out&filters.-checked_out:record=`
Therefore the following two things had to be implemented:
- Ability to filter for empty strings
- Possibility to negate a filter query
Jira: https://4teamwork.atlassian.net/browse/GEVER-41
> Allow filtering for all checked out documents.

- docs/HISTORY.txt
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
Due an error in the GEVER api the task types in the listing endpoint weren't translated. This is fixed in this commit.
Jira Issue: https://4teamwork.atlassian.net/browse/GEVER-462
> Translate task types in GEVER api.

- docs/HISTORY.txt
- opengever/core/upgrades/20200616143838_customize_invitation_group_dn/registry.xml
- opengever/core/upgrades/20200616143838_customize_invitation_group_dn/upgrade.py
- opengever/workspace/interfaces.py
- opengever/workspace/participation/browser/my_invitations.py
- opengever/workspace/tests/test_my_invitations.py
By default invited users are added to the org unit's users group. This group includes all users that have access to the site. However often invited users need to be put into a dedicated group. This PR allows configuring a dedicated group in the registry. If not configured, it falls back to the org unit's users group.
Jira: https://4teamwork.atlassian.net/browse/GEVER-79
> Allow customizing group dn for invitations

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/trigger_task_template.rst
- opengever/api/configure.zcml
- opengever/api/task.py
- opengever/api/templatefolder.py
- opengever/api/tests/test_templatefolder.py
- opengever/tasktemplates/tasktemplatefolder.py
The endpoint `@trigger-task-template` allows the user to create tasks from task-templates. The tasks are created in a dossier.
The main goal of this PR is to expose triggering task templates via API so we can re-implement the classic UI wizard in the new ui. We won't implement it as a wizard though so all data can be passed to the endpoint at once.
Challenges i had:
- `plone.restapi` does not help me validate arbitrary schema based input, as far as i could see i have to do some manual validation. if someone has a better idea about how this should be done please let me know.
- i had to split the schema in two, one part is "automatically" validated via `get_validation_errors`, the other part is only used for its sources and for manual validation.
- the vocabulary returning selectable …
> Add API endpoint `@trigger-task-template` to create tasks in a dossier from a template.

- docs/HISTORY.txt
- docs/public/dev-manual/api/favorite.rst
- opengever/api/favorites.py
- opengever/api/tests/test_favorites.py
- opengever/api/tests/test_repository_favorites.py
- opengever/base/model/favorite.py
This PR implements a `resolve` query parameter for the `@favorites` endpoint which will return already resolved favorites if possible.
We need resolved favorites for the new content selector. Navigation and selection of favorite items is not fully provided without this changes.
⚠️ In the spec we defined to only return resolved favorites if we use the `resolve` parameter. But this seems to be wrong and not useful. I introduced a new property on the serialized favorite instead to indicate if the current favorite is resolved or not. The frontend can then filter for resolved favorites if necessary.
Jira: https://4teamwork.atlassian.net/browse/GEVER-473
> Extend the @favorites endpoint to let it return already resolved favorites.

- opengever/api/tests/test_templatefolder.py
The test helper to get vocabulary items introduced in https://github.com/4teamwork/opengever.core/pull/6514 relied on vocabulary order. The order seems arbitrary and thus the test became flaky. I have adapted the test helper to filter by a criteria (title in this case) instead of relying on order to get specific items.
This should hopefully fix the flaky tests.
https://4teamwork.atlassian.net/browse/GEVER-101
_sorry about that 😞_ 
> Fix flaky test that relied on arbitrary order.

- .github/pull_request_template.md
Following the discussion in https://4teamwork.slack.com/archives/C062G6FGT/p1592497331009400?thread_ts=1592466050.000300&cid=C062G6FGT, `api-change` label is not enough to track breaking changes made to the API. I propose to add a new checkbox in the PR checklist, so that we at least inform the SM.
I also took the liberty to clean the PR checklist up a bit, so that it does not become longer than it already is...
> Update PR template to include API breaking changes.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/proposal.py
- opengever/api/tests/test_proposal.py
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/model/meeting.py
- opengever/meeting/model/proposal.py
- opengever/meeting/proposal.py
In this PR we add some additional data in the GET of proposals and proposal responses. `Proposal`s indeed include important data depending on their status which is not part of their Schema (the meeting it is scheduled in, the excerpt and the decision number). Similarly additional data is required to represent certain `ProposalResponse`s correctly, which is not in the response schema (titles and urls of meeting and successor proposal).
For https://4teamwork.atlassian.net/browse/GEVER-313
> Add additional data in GET of Proposals and ProposalResponses

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
To decide in the frontend which folderActions are available for documents, you have to know if the documents are in the trash or not. Therefore the listing endpoint must provide this information.
Jira: https://4teamwork.atlassian.net/browse/GEVER-45
> Allow trashed as field in @listing endpoint.

- docs/HISTORY.txt
- opengever/core/upgrades/20200508163417_populate_filename_column_in_favorites/upgrade.py
**Background**
This upgrade step attempts to poplate the filename SQL column for favorites, which is limited to 105 characters. If an object (specifically mails) is encountered that for some reason still has a longer filename indexed in the catalog, this upgrade step will fail.
**Fix**
This change makes it more robust by truncating any filename to the max length before attempting to write it to SQL.
**Jira** (related to): https://4teamwork.atlassian.net/browse/GEVER-477
❗ Needs to be backported to `2020.3.x`
> Make "populate_filename_column_in_favorites" UpgradeStep more robust:

- docs/HISTORY.txt
- docs/public/dev-manual/api/listing_stats.rst
- docs/public/dev-manual/api/operations.rst
- opengever/api/configure.zcml
- opengever/api/dossier.py
- opengever/api/tests/test_dossier.py
- opengever/api/tests/test_repository.py
This API expansion enables us to fetch the data of the main dossier of any given object.
This is required for an enhancement of the new content selector widget in GEVER UI. See https://4teamwork.atlassian.net/browse/GEVER-555 where @elioschmutz, @deiferni any myself discussed possible solutions.
> Add API expansion "main-dossier".

- docs/HISTORY.txt
- opengever/base/tests/test_command.py
- opengever/bumblebee/tests/test_document_adapter.py
- opengever/bundle/tests/test_section_fileloader.py
- opengever/core/upgrades/20200507073857_update_filename_of_mails_with_file_extension_msg/upgrade.py
- opengever/ech0147/tests/test_model.py
- opengever/mail/mail.py
- opengever/mail/tests/test_mail_download_copy.py
- opengever/mail/tests/test_ogmail.py
- opengever/mail/tests/test_senddocument.py
- opengever/mail/tests/test_zip_export.py
- opengever/officeconnector/tests/test_api_mail_attach.py
When an e-mail with the file extension "msg" is uploaded, two blob files are created, one with the original file, one that has been converted to "eml".
If the file name of an email has been changed, only the file name of the converted message has been changed, but not the file name of the original message. 
However, when the email is added as a favorite, the filename of the original message is written to the database.
This can cause errors because the filename of the original message was not truncated.
Now the filename of the original message is also truncated when the filename of an email changes, this solves the problem.
Jira: https://4teamwork.atlassian.net/browse/GEVER-477
_Everything has to be …
> Also normalise filename of original_message when present.

- docs/HISTORY.txt
- opengever/document/browser/versions_tab.py
Until now, a searchbox was rendered on the document versions tabbed view. As far as we could find out, the searchbox never had any effect on the results shown in table.
The listing of the document versions is lazy and we do not see an easy way to implement the filtering of the versions by a searchable text and keeping this lazyness at the same time.
According to the product owner, we may simply disable the searchbox on the version tab (see screenshot).
There is no test because the searchbox is removed by JavaScript.
Belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-584
> Disable the searchbox for document versions.

- docs/HISTORY.txt
- opengever/core/upgrades/20200623100315_index_task_template_deadline_as_period/upgrade.py
- opengever/tasktemplates/browser/tasktemplates.py
- opengever/tasktemplates/configure.zcml
- opengever/tasktemplates/indexers.py
- opengever/tasktemplates/tests/test_tasktemplate.py
- solr-conf/managed-schema
Since we switched the tabular listing view to Solr, the deadline of task templates was no longer shown. There is already a Solr field called `deadline`, which is a `pdate`. But the deadline of the task templates is an integer. So we store the value in a Solr field called `period` and render it in the tabular listing.
Belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-561
The screenshot depicts the affected column in the table listing of task templates.
> Fix deadline of task templates no longer shown in tabular listing.

- docs/HISTORY.txt
- opengever/tabbedview/catalog_source.py
- opengever/tasktemplates/browser/configure.zcml
- opengever/tasktemplates/browser/tasktemplates.py
- opengever/tasktemplates/tests/test_tasktemplatefolder.py
Until now, reordering the task templates within a task template folder looked to the user like it was not working. Although the items can be ordered with drag'n'drop, the ordering was lost after a browser refresh. 
This was due to the fact that Solr does not have an index for `getObjPositionInParent`. We can fix this by sorting the items by their position in the parent, just like Plone would do.
Belongs to Jira issue https://4teamwork.atlassian.net/browse/GEVER-565
> Fix sort order within task template folder.

- docs/HISTORY.txt
- docs/public/dev-manual/api/trigger_task_template.rst
- opengever/api/templatefolder.py
- opengever/api/tests/test_templatefolder.py
We also want to support interactive responsibles for the tasks created via `@trigger_task_template`. Not only should the existing defaults from a task-template be used, we also want to support to replace a concrete default value with an interactive one.
For https://4teamwork.atlassian.net/browse/GEVER-101.
> Also support interactive responsibles when triggering a task template.

- docs/HISTORY.txt
- opengever/api/tests/test_summary_serializer.py
- opengever/base/contentlisting.py
- opengever/document/contentlisting.py
The summary serializer should support the same metadata, whether the object being summarised is a brain or a real object, so that `items` and `related_items` get serialized in the same way. `OpengeverRealContentListingObject` should therefore support the same `metadata_fields` as the `OpengeverCatalogContentListingObject`. As a first step here, we add support for some essential fields, notably `filename` which is essential for correctly representing documents in a relation field (e.g. `relatedItems`) in the frontend, notably documents linked to a subtask, the excerpt or linked documents in a `Proposal`.
For https://4teamwork.atlassian.net/browse/GEVER-313
- API change:
> Add support for several metadata_fields for real content listing objects 

- docs/HISTORY.txt
- opengever/task/task.py
- opengever/task/tests/test_sequential_task_process.py
When resolving a subtask of a sequential `TaskTemplate`, the next`Task` is opened. The problem is that there is no guarantee that the current user has any permissions on that next `Task`, especially for cross-client `Task`s. We therefore need to use `elevated_privileges` to trigger that transition.
For https://4teamwork.atlassian.net/browse/GEVER-583
This should also solve https://sentry.4teamwork.ch/sentry/onegov-gever/issues/9715/
> Fix permission issue with tasktemplates.

- docs/HISTORY.txt
- opengever/base/browser/resources/contenttree.js
In https://github.com/4teamwork/opengever.core/pull/6461/ we introduced a modified version of the javascript for the contenttree widget, to optimise its use with large amounts of items. This change introduced some ES6 syntax which is not supported by IE. This breaks gever on IE.
For https://4teamwork.atlassian.net/browse/GEVER-621
> Fix contenttree.js: IE cannot parse ES6 syntax.

- docs/HISTORY.txt
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/response_description.py
- opengever/task/tests/test_sequential_task_process.py
- plonetheme/teamraum/resources/css/gever/gever.css
Subtasks generated from a task template change their state from "planned" to "open", when the previous subtask is completed.
The resulting item in the response history of the subtask was missing a proper icon and a message.
Belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-607
> Improve response history for opened subtasks.

- docs/HISTORY.txt
- opengever/base/model/favorite.py
- opengever/core/upgrades/20200501143003_populate_additional_metadata_of_favorites/upgrade.py
When for some reason workflow state cannot be retrieved we still want to be able to create the favorite. Thus make the code a bit more robust for this non-critical information.
Also fix an upgrade that would attempt to write `Missing.Value` from the catalog into an sql column which won't work due to missing serializers.
- ✅   i have manually verified that favorites can now be added
- ✅   i have run an upgrade from https://github.com/4teamwork/opengever.core/commit/91a89d17b (the commit before https://github.com/4teamwork/opengever.core/commit/04fcdf52cae62e3ccacfa6c0ff3b3d5a4d9c9ebf was merged to https://github.com/4teamwork/opengever.core/tree/deif/617-fix-favorites-workflow-state to make sure the upgrade would now pass and doesn't break other things
Sample sentry message from my local …
> Robustify adding favorites with invalid workflows.

- docs/HISTORY.txt
- opengever/document/base.py
- opengever/document/browser/overview.py
- opengever/document/browser/templates/overview.pt
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_document_word.py
- opengever/meeting/tests/test_excerpt.py
- opengever/trash/trash.py
Add separate conditions to display the link from a document to its proposal, submitted proposal and meeting (if any). The visibility of these items can be different depending on how gever is setup. We now check separately if the user can view the proposal or the submitted proposal. In both cases we display link to the proposal/submitted porposal and the meeting.
I have added displaying a link to the submitted proposal, so this is not strictly a bugfix. I think it may be the best approach and help the user to navigate to all the different content that is generated automatically. The following cases are displayed differently _(sorry about screenshot alignment)_:
- User can only see meeting, not case dossier
- User can see case dossier and meeting
- User can only see case dossier (meeting is …
> Separate conditions for links from document to proposal/submitted proposal/meeting.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/tests/test_config.py
- opengever/private/__init__.py
- opengever/private/tests/test_folder.py
Expose the path to the user's private folder in the `@config` API endpoint. This serves as a feature flag for the GEVER UI too.
The reason for this addition is the fact, that the GEVER UI does not get the path to the private folder right in every case. Especially when the user id is an e-mail address, the id of the private folder is normalized (see the tests for an example).
Belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-611
- API change:
> Enhance "@config" with "private_folder_url".

- docs/HISTORY.txt
- opengever/core/solr_testing.py
The command `bin/testserver` did not succeed due to a `503` during the initial connection (which empties the index) from the testserver to Solr:
```
ftw.testing PATCHING: Products.CMFQuickInstallerTool.events.handleProfileImportedEvent with noop
ftw.testing PATCHING: Products.CMFQuickInstallerTool.events.handleBeforeProfileImportEvent with noop
11:12:33 [ wait ] Starting Zope 2 server
{u'error': {u'msg': u'SolrCore is loading', u'code': 503, u'metadata': [u'error-class', u'org.apache.solr.common.SolrException', u'root-error-class', u'org.apache.solr.common.SolrException']}}
File "./bin/testserver", line 434, in <module>
sys.exit(plone.app.robotframework.server.server())
File "/Users/sebastianmanger/Code/opengever/eggs/plone.app.robotframework-1.2.3-py2.7. …
```
> Expect the solr service not to be running upon the first request

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/configure.zcml.bob
The administrator group was missing from the [configuration of opengever.quarten](https://github.com/4teamwork/opengever.quarten/blob/3034b0e00aeada143497cfed2664b1e7411e7f5a/opengever/quarten/configure.zcml#L57-L71) so our product owner though it would be a good idea to add it to our policy template.
Belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-538
> Add question for `administrator_group` to the policy template.

- opengever/base/browser/resources/base.js
- opengever/base/browser/resources/teaser.js
This is a followup PR to #6536 
A tour can only be set as seen if the user is an ogds user. This was not considered before.
In addition, the UI-switch reloaded the window before the tour could be set as seen. This has now been corrected.
Jiira: https://4teamwork.atlassian.net/browse/GEVER-552
> Fix teaser.

- opengever/base/tests/test_teaser.py
- opengever/base/viewlets/teaser.pt
- opengever/base/viewlets/teaser.py
This is a followup PR to #6536
The frontend teaser is now only showed if the GEVER-UI feature is enabled.
Jira: https://4teamwork.atlassian.net/browse/GEVER-552
> Only show new frontend teaser if gever ui is enabled.

- docs/HISTORY.txt
- opengever/activity/browser/configure.zcml
- opengever/activity/browser/notification_mail_macros.py
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/participation/invitation_mailer.py
- opengever/workspace/participation/templates/invitation_mail.pt
We improve the design of the workspace invitation e-mail by reusing the macro defined for the activity notifications. Furthermore, the content of the e-mail has been changed as requested in https://4teamwork.atlassian.net/browse/GEVER-536
> Improve workspace invitation e-mail.

- docs/HISTORY.txt
- opengever/base/browser/resources/contenttree.js
Loading more items did not work for top level items. E.g. when selecting related items in a task and if there are more than 100 items. The problem was that top level items do not have a parent and the previous implementation simply appended the additionally loaded items to the parents children.
JIRA: https://4teamwork.atlassian.net/browse/GEVER-655
> Fix loading of more items in contenttree widget

- opengever/activity/browser/templates/notification_mail_macros.pt
- opengever/workspace/participation/templates/invitation_mail.pt
As requested by the product owner. 
This is a follow-up of https://github.com/4teamwork/opengever.core/pull/6542 and belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-536
The changelog is not modified because it has already been updated in https://4teamwork.atlassian.net/browse/GEVER-536
> Remove footer in workspace invitation e-mail.

- docs/HISTORY.txt
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
Filtering by `document_author` was not working in the new frontend when the author name contained a space. We fix this here by escaping spaces in filters when creating the solr query in the `listing` endpoint. We do not fix this in `ftw.solr` as the `escape` function defined there is used for the search query, for which spaces do not need to be escaped. Instead we implement our own escaping function specifically for filter queries.
For https://4teamwork.atlassian.net/browse/GEVER-649
- API change:
- If breaking:
> Fix filtering on values containing spaces in listing endpoint.

- docs/HISTORY.txt
- opengever/core/upgrades/20200508163000_update_filename_of_mails_with_file_extension_msg/upgrade.py
Filename column has to be added to favorites before fixing mail filenames, i.e. https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20200508162410_add_filename_column_to_favorites/upgrade.py should be executed before https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20200507073857_update_filename_of_mails_with_file_extension_msg/upgrade.py which should itself be executed (although this is not mandatory) before https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20200508163417_populate_filename_column_in_favorites/upgrade.py
For https://4teamwork.atlassian.net/browse/GEVER-168
- Upgrade steps (changes in …
> Fix update mail filename upgrade step.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/interfaces.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20200703163603_add_user_snap_key_to_registry/registry.xml
- opengever/core/upgrades/20200703163603_add_user_snap_key_to_registry/upgrade.py
For the integration of Usersnap in the frontend, we add a registry entry with the API key. This also gets returned in the `@config` endpoint and will serve as feature flag (usersnap is shown when the API key is defined).
I took the opportunity to update the API documentation with many of the missing features and configs returned by the `@config` endpoint.
For https://4teamwork.atlassian.net/browse/GEVER-516
- API change:
- If breaking: It's non breaking!
> Add UserSnap API key to registry.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
This PR exposes the currently logged in users e-mail address in the ``@config`` endpiont.
We need this information for the usersnap plugin.
⚠️ I would like to have the serialized user object here instead of defining each attribute. But this would end in an api change which I wanted to avoid. I opened an enabler to handle this refactoring: https://4teamwork.atlassian.net/browse/GEVER-698
Jira: https://4teamwork.atlassian.net/browse/GEVER-516
- API change:
> Expose the current logged in users email address in the @config endpoint

- docs/HISTORY.txt
- docs/public/dev-manual/api/authentication/index.rst
- docs/public/dev-manual/api/authentication/jwt.rst
- docs/public/dev-manual/api/authentication/logout.rst
- opengever/api/configure.zcml
- opengever/api/logout.py
- opengever/api/tests/test_logout.py
We add an API endpoint to log out the current user by expiring his cookies (__ac and deployment specific cookie, e.g. __ac_fd). This is necessary because logout in the frontend should also log the user out of the backend.
I'm actually really not sure this is the right approach. It works, but maybe that should be the job of the portal or something?
I haven't added the documentation yet, as I'm more and more doubtful that this is a good solution.
For https://4teamwork.atlassian.net/browse/GEVER-558
PR in the frontend: https://github.com/4teamwork/gever-ui/pull/1186
- API change:
> Add API endpoint to logout current user.

- docs/HISTORY.txt
- opengever/activity/digest.py
- opengever/activity/mail.py
- opengever/activity/model/activity.py
- opengever/activity/model/notification.py
- opengever/api/tests/test_notifications.py
Activities are stored in multiple languages and can therefore be translated. The `@notifications` endpoint nevertheless did not returned the translated activities, so that the new frontend would always display the notifications in German. This is fixed with this PR.
I also removed some code duplication, defining a `serialize` method directly on the `Activity`, also allowing to deal with the translations in one central place.
For https://4teamwork.atlassian.net/browse/GEVER-668
- API change:
- If breaking:
> Translate activities in @notifications endpoint.

- docs/HISTORY.txt
- opengever/base/interfaces.py
- opengever/base/tests/test_teaser.py
- opengever/base/viewlets/teaser.pt
- opengever/base/viewlets/teaser.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20200710080249_add_teaser_settings/registry.xml
- opengever/core/upgrades/20200710080249_add_teaser_settings/upgrade.py
We want to be able to hide the teasers for certain customers. I've added `ITeasersSettings` with a flag to completely hide the teasers and a list of specific teasers to hide.
This is a follow-up PR for https://github.com/4teamwork/opengever.core/pull/6536, https://github.com/4teamwork/opengever.core/pull/6541 and https://github.com/4teamwork/opengever.core/pull/6543
For https://4teamwork.atlassian.net/browse/GEVER-552
> Add TeasersSettings to registry to allow hiding teasers.

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/role_assignment_reports.rst
- opengever/api/configure.zcml
- opengever/api/permissions.zcml
- opengever/api/role_assignment_reports.py
- opengever/api/tests/test_allowed_roles_and_principals.py
- opengever/api/tests/test_role_assignment_reports.py
- opengever/base/configure.zcml
- opengever/base/interfaces.py
- opengever/base/nightly_role_assignment_reports.py
- opengever/base/storage.py
- opengever/base/tests/test_copy_paste.py
- opengever/base/tests/test_nightly_role_assignment_reports.py
- opengever/base/tests/test_storage.py
- opengever/core/lawgiver.zcml
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20200702172053_assign_role_assignment_reports_permission/rolemap.xml
- opengever/core/upgrades/20200702172053_assign_role_assignment_reports_permission/upgrade.py
- opengever/dossier/tests/test_protect_dossier.py
- opengever/repository/tests/test_excel_export.py
- opengever/testing/fixtures.py
An administrator wants to know what local roles a user or group has.
This PR makes it possible to create role assignment reports.
With the API endpoint `@role-assignment-reports` a report can be created. This is stored in the `RoleAsssignmentReportsStorage` with the status "in progress".
In a nightly job, all local roles of a Principal are collected and the report is completed with them. The report then has the status "ready".
Jira: https://4teamwork.atlassian.net/browse/GEVER-33
- API change:
> Add @role-assignment-reports endpoint to list, add and delete role assignment reports.

- opengever/core/profiles/default/jsregistry.xml
This is a follow-up to In https://github.com/4teamwork/opengever.core/pull/6536
`teaser.js` got inserted at the beginning of the registry instead of just before `opengever.base.js`. This led to new deployments and the testserver being broken. The insertion did not work as expected because `teaser.js` got inserted before `opengever.base.js`, then the `insert-before` dose not find the position of the element it should insert before and defaults to beginning of the registry: https://github.com/plone/Products.ResourceRegistries/blob/master/Products/ResourceRegistries/tools/BaseRegistry.py#L842-L844
Simply making sure `opengever.base.js` appears before `teaser.js` in opengever/core/profiles/default/jsregistry.xml is therefore enough.
For https://4teamwork.atlassian.net/browse/GEVER-552 …
> Fix javascript ordering.

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
Date filters in the `@listing` endpoint did not handle wildcards. We now correctly handle wildcards in these filters.
Note that we have also changed the error handling. The status before was that:
- If no range was provided the code would simply fail with `UnboundLocalError` (https://sentry.4teamwork.ch/sentry/onegov-gever/?query=is%3Aunresolved+UnboundLocalError%3A+local+variable+%27date_from%27+referenced+before+assignment)
- if parsing failed, it would be silently ignored and return no results.
Now when parsing fails it will return an appropriate `Bad Request` error
Not sure whether we should consider that braking. It feels more like fixing a bug to me.
For https://4teamwork.atlassian.net/browse/GEVER-624
- API change:
- If breaking:
> Handle wildcard in date filters in listing endpoint.

- docs/HISTORY.txt
- opengever/setup/sections/reference.py
When setting up a repository, the system incorrectly checked whether the title of an item already exists instead of checking whether the normalized title already exists.
Jira: https://4teamwork.atlassian.net/browse/GEVER-460
> Fix id normalization when setting up a repository.

- docs/HISTORY.txt
- opengever/api/navigation.py
- opengever/api/tests/test_navigation.py
The `@navigation` endpoint should allow to specify a list of interfaces used to query for the contents to display (`content interfaces`). The current implementation only handled the case of a single interface. We now extend the endpoint to correctly handle  multiple `content_interfaces`.
This will allow to also display the `WorkspaceFolder`s in the navigation for workspaces in the the new UI.
For: https://4teamwork.atlassian.net/browse/GEVER-532
- API change:
> Handle multiple content interfaces in @navigation endpoint.

- docs/HISTORY.txt
- opengever/api/solrsearch.py
- opengever/api/tests/test_solrsearch.py
Since https://github.com/4teamwork/opengever.core/pull/6499, errors when querying solr will be logged to sentry.
This notably happens for invalid queries that solr cannot parse. While it would be better to avoid actually sending invalid queries to solr, it is complex and would first need us to establish what is the behaviour we expect and what type of user queries we want to support. This will be done in a further step (https://4teamwork.atlassian.net/browse/GEVER-752)
For now, when the search fails on the solr side, we need to at least raise an error in the solrsearch endpoint, so that
the gever-ui can handle such errors. This changes the behaviour of when a query becomes invalid in the `LiveSearch`. Before it would suddenly show no results when a query becomes invalid (try typing "test …
> Handle errors in solrsearch endpoint.

- docs/HISTORY.txt
- opengever/api/scanin.py
- opengever/base/monkey/patches/default_values.py
- opengever/base/tests/test_command.py
- opengever/bundle/sections/constructor.py
- opengever/document/forms.py
- opengever/document/tests/test_save_pdf_under.py
We fix `createContentInContainer` to respect behaviors. This has been fixed in `plone.dexterity` in version 2.2.0 (https://github.com/plone/plone.dexterity/pull/17) but never made its way into our `MonkeyPatch` (see https://github.com/plone/plone.dexterity/pull/17). Note that it was fixed several times in `plone.dexterity`, but never quite correctly. The current implementation (https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/utils.py#L133-L150) is still fragile, relying on `getattr` to decide whether a certain field is part of a given schema. This has two problems:
- This does not really test whether the field is part of a given behavior, but only whether the field exist in the storage of that behavior (so it could be part of another behavior using the same schema)
- …
> Fix createContentInContainer to respect behaviors.

- docs/HISTORY.txt
- opengever/api/navigation.py
- opengever/api/tests/test_navigation.py
When getting a context over the API, the @id of the navigation endpoint should always be returned, even if no root is found with the default root_interface. Otherwise it would require to always specify the root_interface for every get on every context for a Teamraum deployment.
It did also not make sense to go to the trouble of finding the root when we are not expanding the `navigation`. If the user then makes a request on the `@navigation` endpoint, we will search for the root at that moment anyway. I think it's actually a rather unexpected behavior that in a GET of a context, for example a dossier, we get back the the URL to get the navigation of the root, i.e. the repository root.
For https://4teamwork.atlassian.net/browse/GEVER-532 …
> Always return @id in navigation endpoint when not expanding.

- docs/HISTORY.txt
- opengever/api/tests/test_workflow.py
- opengever/api/transition.py
Fix executing workflow transitions via @workflow service when the executing user has no permission in target state on the context for which the transition is executed.
This is done by accessing `review_history` with elevated privileges, if necessary.
There is an issue in the `WorkflowTransition` service when the user performs a transition into a state where his access is revoked. The service will raise a `WorkflowException` when attempting to access `review_history` while rendering the response. This will prevent the transition from being executed.
We work around this issue when we catch a `WorkflowException` and attempt to read the history with elevated privileges.
For https://4teamwork.atlassian.net/browse/GEVER-755.
I am of the opinion that this is a `plone.restapi` issue, as the issue …
> Fix @workflow when no permissions in target state.

- docs/HISTORY.txt
- opengever/core/upgrades/20200720171931_add_additional_wopi_settings/registry.xml
- opengever/core/upgrades/20200720171931_add_additional_wopi_settings/upgrade.py
- opengever/wopi/browser/edit.py
- opengever/wopi/browser/wopi.py
- opengever/wopi/interfaces.py
- opengever/wopi/tests/test_edit.py
- opengever/wopi/tests/test_wopi.py
Adds additional functionality which is required to support integration with Office 365:
- SHA256 checksum in CheckFileInfo operation
- Business user flow
- Custom WOPI base URL
The business user flow can be activated in the registry and is enabled by default. If enabled, the user has to sign in with his Office 365 account to be able to edit documents. This is required for commercial uses.
The WOPI base URL can be configured in the registry. This allows to expose the WOPI API on a different URL, e.g. https://wopi.onegovgever.ch/lab instead of https://lab.onegovgever.ch/, which enables us to use a single WOPI domain for all SaaS customers.
The Office user interface language is no longer hardcoded. The parameter is now omitted and thus the language is chosen based on the browser language. …
> WOPI enhancements

- docs/HISTORY.txt
- opengever/core/upgrades/20200730094255_fix_docs_only_partially_indexed_in_solr/upgrade.py
With this PR we provide a fix for documents that are only partially indexed in solr.
We think affected documents may have been not indexed in solr at all due to a bug with date serialization in `ftw.solr`. The bug was only fixed in https://github.com/4teamwork/ftw.solr/pull/158.
Subsequent edits of the document by users via plone or reindex operations during upgrades would have partially indexed or restored the document in solr, but only some of the fields as we use atomic updates.
We've seen that all affected documents do not have the created date set as we never manually reindex it, as it never changes. Thus apply a heuristic to detect broken solr documents. We assume that broken documents do not have the field 'created' set to a value in solr.
I have decided against writing better …
> Fix docs only partially indexed in solr.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- docs/public/dev-manual/api/globalindex.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/notifications.rst
- docs/public/dev-manual/api/resolve_oguid.rst
- opengever/activity/browser/resolve.py
- opengever/activity/model/notification.py
- opengever/api/configure.zcml
- opengever/api/globalindex.py
- opengever/api/resolve_oguid.py
- opengever/api/tests/test_config.py
- opengever/api/tests/test_globalindex.py
- opengever/api/tests/test_notifications.py
- opengever/api/tests/test_resolve_oguid.py
- opengever/base/configuration.py
- opengever/base/exceptions.py
- opengever/base/oguid.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/globalindex/model/task.py
- opengever/tabbedview/browser/tasklisting.py
With this PR we add the endpoint `@resolve-oguid` which allows to get the a serialized object via oguid. Then endpoint will proxy the change to another remote internally, if necessary.
It also includes the following other changes:
- add `oguid` to `@notifications` and `@globalindex` endpoint
- amend `@globalindex` endpoint with the following changes
- Support search queries
- translate `task_type`
- add correct batching information
- add issuer_fullname
- extend `@config` with admin-unit and org-unit
I have verified that the api-change does not have an impact in https://4teamwork.slack.com/archives/C3RUACNN7/p1595930231095400.
For https://4teamwork.atlassian.net/browse/GEVER-439.
_Only …
> Add @resolve-oguid endpoint, amend @notifications and @globalindex.

- docs/HISTORY.txt
- opengever/usermigration/dossier.py
- opengever/usermigration/tests/test_dossier_migrator.py
`responsible` is part of the searchable text, so the `SearchableText` of dossiers should get updated during a user migration.
I decided not to write an upgrade step here, as I don't know how to identify the dossiers that are concerned by this. Reindexing the `SearchableText` of all dossiers seems a bit of an overkill?
For https://4teamwork.atlassian.net/browse/GEVER-819
> Also reindex searchable text of dossier when migrating responsible user.

- docs/HISTORY.txt
- opengever/advancedsearch/tests/test_search.py
- opengever/core/upgrades/20200805094934_reindex_searchable_text_to_include_filing_no/upgrade.py
- opengever/dossier/archive.py
- opengever/dossier/filing/advanced_search.py
- opengever/dossier/tests/test_indexer.py
The `SearchableText` was not reindexed when the `filing_no` is set by the `Archiver`, although the  `filing_no`  is part of the `SearchableText`. Apart from this correction, I also realised that the advanced search did not work for filing numbers, as this referenced the `searchable_filing_number` field, which is not indexed in solr. I therefore now use the `filing_no` in the advanced search form instead.
The upgrade step reindexing the `SearchableText` will find dossiers only for deployments having this behavior (i.e. only Zug), as we query for the `IFilingNumberMarker` interface.
For https://4teamwork.atlassian.net/browse/GEVER-802
> Reindex SearchableText when filing_no is set.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/inbox.py
- opengever/api/tests/test_serializer.py
- opengever/inbox/browser/overview.py
- opengever/testing/fixtures.py
With this PR we:
- Add the mail-in address to the inbox serializer. 
- Add the inbox_id to the inbox serializer. 
- We also clean-up the query for inbox documents which still used an outdated filter `isWorkingCopy` which is not used in gever anymore (https://github.com/4teamwork/opengever.core/commit/1e7c8a1140247d2c65919925d9e715362ff92c50)
For https://4teamwork.atlassian.net/browse/GEVER-463
- API change:
- If breaking:
> Add mail-in address to inbox serializer.

- opengever/api/tests/test_task.py
- opengever/api/tests/test_vocabularies.py
- opengever/task/browser/delegate/configure.zcml
- opengever/task/browser/delegate/vocabulary.py
- opengever/task/tests/test_delegate.py
We introduce a vocabulary factory for the `attachable_documents_vocabulary` source binder, so that it can be accessed over the REST-API.
For https://4teamwork.atlassian.net/browse/GEVER-430
- API change:
- If breaking:
> Add vocabulary for attachable documents when delegating a task.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/tests/test_config.py
- opengever/inbox/utils.py
Deployments having multiple org-units will have multiple inboxes within an inbox container. The user will be redirected automatically to the currently active inbox depending on his active org-unit.
To be able to implement this functionality in the new ui, we need the url to the current inbox.
This PR extends the `@config` endpoint with the `inbox_folder_url`.
Jira: https://4teamwork.atlassian.net/browse/GEVER-490
- API change:
- If breaking:
> Extend the @config endpoint with the inbox_folder_url.

- docs/HISTORY.txt
This PR fixes the history after a new release.
Belongs the the following PR: https://github.com/4teamwork/opengever.core/pull/6583
> Fix history after release

- docs/HISTORY.txt
- opengever/base/casauth.py
- opengever/base/interfaces.py
- opengever/base/tests/test_casauth.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20200818160702_add_portal_settings_registry/registry.xml
- opengever/core/upgrades/20200818160702_add_portal_settings_registry/upgrade.py
This PR adds a new registry entry to define the portal_url.
By default, the portal url refers to `[admin-unit-url]/portal`(i.e. https://mygever.com/portal). In rare cases where the portal is not running under the same domain like the gever, we have to define it separately.
In Jira, there is a suggestion to reuse the cas-auth url from the auth-plugin to guess the portal url. This could have been one possible solution. But guessing will lead once again into problems in the future. So I introduced a new setting to override the default `portal_url`.
Currently, the `portal_url` will be exposed in the @config endpoint and will be used to generate the invitation url for teamraum invitations.
Jira: https://4teamwork.atlassian.net/browse/GEVER-860
_Everything has to be done/checked. Checked but …
> Make the portal_url configurable through the portal_registry.

- README.rst
- docs/HISTORY.txt
- opengever/api/tests/test_config.py
- opengever/api/tests/test_scanin.py
- opengever/api/tests/test_serializer.py
- opengever/api/tests/test_task.py
- opengever/api/tests/test_watchers.py
- opengever/examplecontent/configure.zcml
- opengever/examplecontent/profiles/default_content/content_creation/01_default_content.json
- opengever/examplecontent/profiles/default_content/content_creation/02_inboxes.json
- opengever/examplecontent/profiles/default_content/metadata.xml
- opengever/officeconnector/tests/test_api_forwarding_attach.py
- opengever/testing/fixtures.py
- opengever/usermigration/tests/test_localroles.py
This PR updates the example content profile and the testing fixture to add separate inboxes for each org-unit within an inbox container.
This is the expected setup for a multi-orgunit setup.
Jira: https://4teamwork.atlassian.net/browse/GEVER-490
> Add missing inboxes for multi orgunit setups in the examplecontent fd profile and testing fixture

- opengever/testing/fixtures.py
Follow-Up PR for #6584 
This PR fixes broken local roles for the `inbox_rk` object in the testing fixture.
> Fix inbox_rk local roles in testing fixtures

- docs/HISTORY.txt
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
If a query was submitted with an excluding filter (e.g. -keywords=bla), the correct ListingField was not found until now, because only the field name "keywords" is known. 
Therefore fields with mapping are now duplicated and the field name and index are preceded by a minus sign, so that the fields can also be used as exclusion filters.
Jira: https://4teamwork.atlassian.net/browse/GEVER-699
> Fix filtering with exclusion filters if the field has a mapping.

- docs/HISTORY.txt
- docs/public/dev-manual/api/accept_remote_task.rst
- docs/public/dev-manual/api/complete_successor_task.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/remote_workflow.rst
- opengever/api/accept_remote_task.py
- opengever/api/complete_successor_task.py
- opengever/api/configure.zcml
- opengever/api/remote_task_base.py
- opengever/api/remote_workflow.py
- opengever/api/tests/test_accept_remote_task.py
- opengever/api/tests/test_complete_successor_task.py
- opengever/api/tests/test_remote_workflow.py
- opengever/base/exceptions.py
- opengever/base/oguid.py
- opengever/base/tests/test_oguid.py
- opengever/task/browser/complete.py
- opengever/task/browser/complete_utils.py
This change introduces three new endpoints:
- `POST @remote-workflow` on the Plone site root
- `POST @accept-remote-task` on dossiers
- `POST @complete-successor-task` on tasks
These are endpoints required in the backend to facilitate the process of accepting inter-admin-unit tasks, and finally resolving them, via the new frontend.
The underlying idea is that the frontend should need to know as little as possible about the detailed mechanics of inter-admin-unit processes, remote requests, and authenticating to non-local admin units.
These endpoints therefore proxy or internally dispatch (via server-to-server requests) the necessary actions, allowing the frontend to perform all actions from a single, current admin unit.
Using these endpoints, the processes of accepting and completing …
> Add API endpoints for accepting and completing remote tasks

- docs/HISTORY.txt
- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/sections/constructor.py
- opengever/bundle/sections/reindex_containers.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/bundle/transmogrifier.zcml
- opengever/core/upgrades/20200817143709_reindex_container_modified_during_bundle_import/upgrade.py
In the oggbundle import pipeline, object reindexing is deactivated to avoid objects being reindexed several times during the import.
Every object is indexed just once in the pipeline, but containers into wich objects are added were not reindex afterwards, leading to a discrepency in the modified date on the object and in the catalog. This in turn leads to problems with solr diff / sync.
We also add an upgrade step, which identifies the concerned objects by their symptom of having a different modified date in the catalog than on the object, and hence in solr...
For https://4teamwork.atlassian.net/browse/GEVER-190
> Reindex modified containers after bundle import.

- docs/HISTORY.txt
- docs/schema-dumps/ftw.mail.mail.schema.json
- docs/schema-dumps/opengever.document.document.schema.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
- docs/schema-dumps/opengever.repository.repositoryfolder.schema.json
- opengever/base/behaviors/classification.py
- opengever/base/default_values.py
- opengever/base/monkey/patches/default_values.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/base/utils.py
- opengever/bundle/schemas/documents.schema.json
- opengever/bundle/schemas/dossiers.schema.json
- opengever/bundle/schemas/repofolders.schema.json
- opengever/core/upgrades/20200825130823_fix_description_type_for_dossier_templates/upgrade.py
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/mail/tests/test_mail_classification.py
- opengever/repository/repositoryfolder.py
With this PR we fix our default_value patches not correctly detecting the difference between `''` and `u''` in some cases. The issue has surfaced due to the change introduced in https://github.com/4teamwork/opengever.core/pull/6563/ where we set values via their field during `createContentInContainer`. This will perform a type-check and fail if the type is not correct.
The issue appeared in production when creating a dossier from a templatedossiers with a sub-template dossiers with only the description default value. See https://sentry.4teamwork.ch/sentry/onegov-gever/issues/68884/ for corresponding sentry issue. See https://4teamwork.atlassian.net/browse/GEVER-895 for steps to reproduce.
**To tackle the issue i have:**
- added type checks to our default value tests
- fixed where the …
> Fix empty bytestring overriding unicode in some cases. Fix existing content.

- docs/HISTORY.txt
- opengever/base/contentlisting.py
- opengever/base/tests/test_contentlisting.py
Some meeting content like proposals have a custom workflow implementation that's layered on top of the Plone workflow.
For these, we need to use `obj.get_state()` to access the real workflow state that's in play, and translate that.
Jira: https://4teamwork.atlassian.net/browse/GEVER-808
> Fix translated review state for meeting content

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/role_assignment_reports.rst
- opengever/base/nightly_role_assignment_reports.py
In this PR, the owner role is filtered out of the role assignment reports and "Rollenzuweisungsbericht" is renamed to "Berechtigungsreport" in the API documentation.
Jira: https://4teamwork.atlassian.net/browse/GEVER-547
> Filter out owner role

- docs/HISTORY.txt
- opengever/api/proxy_base.py
- opengever/api/remote_workflow.py
- opengever/api/resolve_oguid.py
- opengever/api/tests/test_remote_workflow.py
- opengever/api/tests/test_resolve_oguid.py
This brings the format of error responses for the `@resolve-oguid` endpoint in the line with the response format used in the other parts of the REST API:
Return `400 Bad Request` with a JSON body including error details, instead of returning `400` with a custom status line reason text.
In addition, this allowed to also homogenize some details about how the two proxying endpoints `@resolve-oguid` and `@remote-workflow` behave, and factor out their commonalities into a base class.  
Follow up to: https://github.com/4teamwork/opengever.core/pull/6595
Jira: https://4teamwork.atlassian.net/browse/GEVER-270
- API change:
- If breaking:
*(deemed unnecessary, will coordinate with frontend guys directly)*
> Bring @resolve-oguid error responses in line with REST API style

- docs/public/dev-manual/api/dossiers.rst
- docs/public/dev-manual/api/index.rst
- opengever/api/configure.zcml
- opengever/api/tests/test_transfer_dossier.py
- opengever/api/transfer.py
This PR implements the `@transfer-dossier` endpoint.
This endpoint provides the functionality to transfer the responsible of a user to another user. With the option: `include_subdossiers`, all subdossiers of the specified user will also be transfered.
Jira: https://4teamwork.atlassian.net/browse/PHX-14
- API change:
- If breaking:
> Add @transfer-dossier Endpoint

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/menu.py
- opengever/core/profiles/default/types/opengever.document.document.xml
- opengever/core/upgrades/20200827131106_provide_action_to_create_forwarding_on_document/types/opengever.document.document.xml
- opengever/core/upgrades/20200827131106_provide_action_to_create_forwarding_on_document/upgrade.py
With this PR we provide an action `create_forwarding` for documents in inboxes. This helps the UI to create forwardings not only from listing but from the overview of a single document.
- The action will only appear in inboxes as only they manage the `opengever.inbox: Add Forwarding` permission.
- The action is only exposed via rest-API but not in the classic ui as that would require a custom JS-Integration and is out of scope for this issue.
Jira: https://4teamwork.atlassian.net/browse/PHX-10
> Provide create_forwarding action in API for documents in inboxes.

- docs/HISTORY.txt
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
- docs/public/dev-manual/api/schemas/opengever.document.document.inc
- docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
- docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc
- docs/public/dev-manual/api/vocabularies.rst
- opengever/api/schema/querysources.py
- opengever/api/tests/test_vocabularies.py
- opengever/testing/integration_test_case.py
With this PR we allow the `@querysources` API endpoint to be queried by a `token` parameter in addition to the existing `query` parameter. The token can be used to retrieve the representation of one already known token. It will return an empty list if no such token exists.
- I have added some very basic docs for our customizations to vocabularies and sources as specified in https://plonerestapi.readthedocs.io/en/latest/vocabularies.html
- I mostly used the description i found in https://github.com/4teamwork/opengever.core/issues/5973 and https://github.com/4teamwork/opengever.core/issues/5968 for this
- I have amended tests so they also cover the possible error-states (no or too many query string parameters provided)
- I have also update the schema docs. this is a leftover of …
> Allow to query by token in @querysources API endpoint.

- docs/HISTORY.txt
- opengever/api/tests/test_vocabularies.py
- opengever/ogds/base/sources.py
With this PR we fix escaping special characters when building solr literal queries. This lead to query strings like `Eingangskorb:Blabla` failing and thus the whole request not returning any e.g. issuers for a task in autocomplete.
Jira: https://4teamwork.atlassian.net/browse/PHX-10
> Escape solr queries when building literal queries.

- docs/HISTORY.txt
- opengever/base/txnutils.py
- opengever/dossier/resolve_lock.py
- opengever/task/browser/assign.py
This solves an edge case which can lead to a deadlock when reassigning inter-admin-unit tasks. If the new responsible doesn't have an entry in the `watchers` SQL table yet, both the predecessor and successor sides would try to add it for the first time, and therefore **deadlock on the to-be-inserted row for the new watcher**.
This is prevented by creating the new watcher (if required) at the very beginning of this process, immediately committing the transaction, and starting a new one.
For a more detailed description of the problem, please see the Jira issue linked below.
Testing the effect of this change unfortunately is near impossible - it's not enough to fake a sort-of-inter-admin-unit scenario, because actual HTTP requests, across multiple real Zope instances were responsible for …
> Prevent deadlock when reassigning inter-admin-unit tasks

- docs/HISTORY.txt
- opengever/api/tests/test_vocabularies.py
- opengever/latex/tests/test_dossiercover.py
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
This PR adds an additional fallback for the `AllUsersInboxesAndTeamsSource` when attempting to figure out the currently selected orgunit. For requests from the UI via API we don't have the form prefilling that is used to get the current orgunit for the forwarding add-form. Instead we must consider the cookie value for the orgunit currently selected.
The current mechanism only considers request form parameters https://github.com/4teamwork/opengever.core/blob/2f2f92f4dc4576ffe254195a79e94d59c440dd82/opengever/ogds/base/sources.py#L301-L318, but the cookie, which is always provided by the UI, is not considered. I have added the fallback last to avoid it from shadowing the edit form, when the value must be retrieved from `context`.
I have also fixed a related issue that popped up in some …
> Consider cookie when figuring out current orgunit in AllUsersInboxesAndTeamsSource.

- docs/HISTORY.txt
- opengever/document/browser/redirect_to_parent_dossier.py
- opengever/dossier/browser/redirect_to_maindossier.py
- opengever/dossier/tests/test_redirect_to_maindossier.py
- opengever/task/browser/redirector.py
- opengever/task/tests/test_redirector.py
This PR preserves the query string for the `redirect_to_parent_dossier` and `redirect_to_main_dossier` view.
The GEVER-UI needs to redirect to parent contents. The business-logic should come from the backend. Because we need this paths in listings, we would have to index all the possible paths in the solr catalog and return it when needed. We can't do/don't want to do this.
Instead, we can just use the redirect views on a context to get the new parent context. Because the GEVER-UI adds a lot of query parameters to get all required information form the backend, we have to preserve the query string on redirection.
Jira: https://4teamwork.atlassian.net/browse/PHX-1
_Only applicable should be …
> Pass query string to location url on maindossier and parentdossier redirect

- docs/HISTORY.txt
- opengever/api/tests/test_forwarding.py
- opengever/api/tests/test_globalindex.py
- opengever/api/tests/test_task.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/core/upgrades/20200901163834_set_task_type_for_forwarding_on_objects/upgrade.py
- opengever/globalindex/browser/report.py
- opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
- opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
- opengever/globalindex/locales/opengever.globalindex.pot
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_sql_task.py
- opengever/globalindex/tests/test_task_css_class.py
- opengever/inbox/__init__.py
- opengever/inbox/forwarding.py
- opengever/inbox/locales/de/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/locales/fr/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/locales/opengever.inbox.pot
- opengever/task/browser/accept/main.py
- opengever/task/helper.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
With this PR we fix multiple related issues with `opengever.inbox.forwarding` when creating and reading via API:
- forwarding no longer requires a `task_type` to be provided, and will no longer ignore the `task_type` provided via `POST`
- as `task_type` is now a proper field for forwardings we get rid of the property, we also provide a migration to set the `task_type` on existing content to ensure all objects are in the same state
- forwarding `task_type` representation in GET is fixed to be consistent with GET of a task, the task_type is now an object, also providing the translation
- forwarding `task_type` in `@globalindex` is now also translated
I have also amended missing test for forwarding defaults (where possible) and have amended default tests for creating a task via API.
I have …
> Fix forwarding requiring task_type in API, fix forwarding task_type translations

- docs/HISTORY.txt
- docs/public/dev-manual/api/globalindex.rst
- opengever/api/globalindex.py
- opengever/api/tests/test_globalindex.py
With this PR we add the `@type` attribute to items we return. We use the existing `task_type` column to figure out the portal type ss we don't store an e.g. `portal_type` in the tasks table. The `task_type` is distinct and we can use it to figure out the portal type. This helps the UI as it might display forwardings and tasks differently when retrieved from the `@globalindex` API service endpoint.
Jira: https://4teamwork.atlassian.net/browse/PHX-10
- API change:
> Add @type to @globalindex items.

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/workspace/actual_workspace_members.rst
- docs/public/dev-manual/api/workspace/index.rst
- docs/public/dev-manual/api/workspace/share_content.rst
- opengever/activity/mailer.py
- opengever/api/actual_workspace_members.py
- opengever/api/configure.zcml
- opengever/api/share_content.py
- opengever/api/tests/test_actual_workspace_members.py
- opengever/api/tests/test_share_content.py
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20200827160546_add_share_content_action/actions.xml
- opengever/core/upgrades/20200827160546_add_share_content_action/upgrade.py
- opengever/workspace/browser/configure.zcml
- opengever/workspace/browser/is_within_workspace.py
- opengever/workspace/content_sharing_mail.pt
- opengever/workspace/content_sharing_mailer.py
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/tests/test_content_sharing_mail.py
With this PR it becomes possible to share workspace content with other members.
- The `@actual-workspace-members` endpoint provides a vocabulary with all members of a workspace. This allows the frontend to select with whom a content can be shared.
- With the `@share-content endpoint`, an e-mail can be sent to the selected members.
- The e-mail is created and sent using the `ContentSharingMailer`.
- A new action `share_content` is provided on workspace content and workspaces.
Jira: https://4teamwork.atlassian.net/browse/GEVER-697
> Add new endpoints @actual-workspace-members and @share-content endpoint

- docs/HISTORY.txt
- opengever/api/tests/test_transfer_task.py
- opengever/api/transfer.py
- opengever/task/response_syncer/configure.zcml
- opengever/task/response_syncer/issuer_change.py
- opengever/testing/test_case.py
This adds support for also transferring inter-admin-unit tasks using the `@transfer-tasks` endpoint.
For changing the `responsible`, the existing "reassign task" mechanism, which involves an actual workflow transition, is reused. For changing the `issuer`, that mechanism is emulated, and supported by a new `IssuerChangeResponseSyncerSender` that syncs the change to the remote side (without triggering an actual WF transition though, because there is none).
The situation for forwardings doesn't really change with the support for inter-admin-unit tasks, because forwardings can never be in a state where the predecessor forwarding is still open - therefore, no syncing of changes is required. 
Jira: https://4teamwork.atlassian.net/browse/GEVER-541
- API change:
_(Not needed, checked)_
- New …
> Add support for transferring inter-admin-unit tasks.

- docs/HISTORY.txt
- opengever/base/model/favorite.py
- opengever/base/tests/test_favorite.py
If an attempt is made to resolve a favorite that does not exist, an exception is raised. This exception has not been handled so far. Now the favorite is returned unresolved.
Jira: https://4teamwork.atlassian.net/browse/GEVER-868
> Fix resolving favorites that don't exist.

- docs/HISTORY.txt
- docs/public/dev-manual/api/tasks.rst
- opengever/api/configure.zcml
- opengever/api/globalindex.py
- opengever/api/task.py
- opengever/api/tests/test_task_predecessor.py
- opengever/api/tests/test_task_successor.py
- opengever/globalindex/model/task.py
With this PR we add `@predecessor` and  @`successors` expansion to tasks. This helps the UI to display predecessors/successors for inter-admin-unit tasks.
I've seen that currenlty the `@globalindex` endpoint had implemented its own serialization, bypassing the `ISerializeToJson` and `ISerializeToJsonSummary` adapters introduced by `plone.restapi`. With this PR i have refactored the existing functionality to provide such adapters.
Decisions/thoughts:
- After some back and forth i've decided to put all functionality into `opengever.api.task` but of course that can be changed.
- After some more back and forth i've decided to nest the tasks as `items` and `item` respectively. This could be changed to the explicit `successors` and `predecessors` but i did not like the repetition.
- Task …
> Add task `@predecessor` and  @`successors` expansion.

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/browser/folder_buttons_availability.py
Don't display actions to transfer documents from and to a teamraum when the dossier is not open or when the user does not have permissions to modify the dossier or add content to the dossier.
Jira: https://4teamwork.atlassian.net/browse/GEVER-953
> Don't show workspace actions for non-open dossiers or when the user can only view.

- docs/HISTORY.txt
- docs/schema-dumps/ftw.mail.mail.schema.json
- docs/schema-dumps/opengever.document.document.schema.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
- docs/schema-dumps/opengever.repository.repositoryfolder.schema.json
- opengever/base/behaviors/classification.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/bundle/schemas/documents.schema.json
- opengever/bundle/schemas/dossiers.schema.json
- opengever/bundle/schemas/repofolders.schema.json
- opengever/mail/tests/test_mail_classification.py
In this PR we revert part of the changes introduced in https://github.com/4teamwork/opengever.core/pull/6601, namely we remove the `missing_value` for the `public_trial_statement` field. This led to issues when submitting proposals, for which the `public_trial_statement` had a value of `None` (on the proposal document), which was now invalid.
For some unknown reason, the `public_trial_statement` default/missing value does not always get persisted on the object anymore, so that we had to manually fix the default values tests. After discussion with @deiferni and @lukasgraf we deemed this as acceptable for now.
For https://4teamwork.atlassian.net/browse/GEVER-959
This should fix the following sentry issues:
- https://sentry.4teamwork.ch/sentry/onegov-gever/issues/69172
- …
> Revert adding missing value for public_trial_statement.

- docs/HISTORY.txt
- opengever/base/browser/resolveoguid.py
- opengever/base/tests/test_resolve_oguid.py
- setup.py
In the `resolve_oguid` view we constructed invalid urls when trying to resolve an OGUID on a remote client with query string parameters. This typically happened when the portal appends a ticket to the url (see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/13998/), so that the view was called with an URL of the type `.../adminunit/@@resolve_oguid/remote-adminunit:intid?ticket=myticket`. In that case it would redirect to `.../remote-adminunit/@@resolve_oguid?oguid=remote-adminunit:intid?ticket=myticket`. The second query string separator `?` is interpreted as literal question mark and the view tries to resolve the oguid `remote-adminunit:intid?ticket=myticket`.
For https://4teamwork.atlassian.net/browse/GEVER-888
_Everything has to be done/checked. Checked but not present means the …
> Correctly handle query strings for oguid on remote admin units in ResolveOGUIDView.

- opengever/core/profiles/default/portal_placeful_workflow/opengever_workspace_policy.xml
- opengever/core/upgrades/20200827114625_update_workspace_workflow/upgrade.py
I've previously renamed the id to be consistent with other policies but missed some occurrences.
This has broken the upgrade step.
JIRA: https://4teamwork.atlassian.net/browse/GEVER-82
> Fix id of workflow policy for workspaces

- opengever/core/lawgiver.zcml
- opengever/core/profiles/default/workflows/opengever_workspace/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_document/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_folder/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_todo/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_todolist/definition.xml
- opengever/core/upgrades/20200909192905_update_workspace_workflow/workflows/opengever_workspace/definition.xml
- opengever/core/upgrades/20200909192905_update_workspace_workflow/workflows/opengever_workspace_document/definition.xml
- opengever/core/upgrades/20200909192905_update_workspace_workflow/workflows/opengever_workspace_folder/definition.xml
- opengever/core/upgrades/20200909192905_update_workspace_workflow/workflows/opengever_workspace_todo/definition.xml
- opengever/core/upgrades/20200909192905_update_workspace_workflow/workflows/opengever_workspace_todolist/definition.xml
Fixes ZMI access to the Properties tab.
By default the "Manage properties" permission is assigned to the "edit" action group.
As we do not manage the "edit" action group in workspace workflows we have to inherit the "Manage properties" permission.
Jira: https://4teamwork.atlassian.net/browse/GEVER-82
> Do not manage the "Manage properties" permission

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/globalindex.py
- opengever/api/ogdslistingbase.py
- opengever/api/ogdsuserlisting.py
- opengever/api/teamlisting.py
- opengever/api/tests/test_globalindex.py
- opengever/api/tests/test_ogds_listing_base.py
- opengever/api/tests/test_ogdsuserlisting.py
- opengever/api/tests/test_teamlisting.py
When sorting according to a non-unique column, response of ogds listings could contain duplicate items and other items could be missing. This is because the sort order of successive queries is not guaranteed to be identical (except when specifically sorting on a key with a unique value for each item).
With this PR we fix this issue by always having a secondary sort by a unique key for the `OGDSUserListingGet`, `TeamListingGet` and in `GlobalIndexGet`. We also refactor the global index endpoint to use the same base class as the other two OGDS listings.
For https://4teamwork.atlassian.net/browse/GEVER-968
API changes are non breaking, except that the ordering of tasks will now be different …
> Fix ogds listing endpoints for undefined sort orders.

- docs/HISTORY.txt
- opengever/core/upgrades/20200910171300_fix_populate_filename_column_in_favorites/upgrade.py
**Analysis**
The `PopulateFilenameColumnInFavorites` already underwent several iterations of fixes, unfortunately all of them were flawed.
- the upgrade was introduced in https://github.com/4teamwork/opengever.core/commit/c139e6fda08a5a06b3c0c07606397e3b7bab6d9b
- then patched in https://github.com/4teamwork/opengever.core/commit/b4101303c8c38dc9230b3c8fe80c8ef2e2d5ce88
- and https://github.com/4teamwork/opengever.core/commit/0e7d08693f2a29e11a3a5a0477d60db0bcb2e26b
The last fix unfortunately introduced another issue where `filename` would be skipped (set to `u''` default) when already unicode due to a missing `return` in https://github.com/4teamwork/opengever.core/commit/0e7d08693f2a29e11a3a5a0477d60db0bcb2e26b#diff-46eb5b96923b2d90aaff51c8c66fc964R23-R25. None of the fixes `touch`-ed …
> Fix jinxed favorite filename upgrade step.

- docs/HISTORY.txt
- docs/public/dev-manual/api/navigation.rst
- opengever/api/navigation.py
- opengever/api/tests/test_navigation.py
This PR includes the `is_subdossier` and `review_state` attribute into the nodes of the `@navigation` endpoint.
This information is required for displaying the correct UI-Icons in the frontend.
Jira: https://4teamwork.atlassian.net/browse/PHX-19
- API change:
- If breaking:
> Include is_subdossier and review_state in @navigation endpoint nodes.

- docs/HISTORY.txt
- docs/public/dev-manual/api/documents.rst
- opengever/api/configure.zcml
- opengever/api/tests/test_tus.py
- opengever/api/tus.py
- opengever/document/checkout/manager.py
- opengever/officeconnector/testing.py
- opengever/officeconnector/tests/test_api_dossier_checkout.py
- opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
- opengever/officeconnector/tests/test_api_task_checkout.py
- opengever/officeconnector/tests/test_zopemaster.py
Customize `@tus-replace` endpoint to perform additional checks before replacing a file:
- The document must be checked out by the current user
- If locked, the lock token must be provided in the request
- If it's a proposal, the file must have a .docx extension
The main difference with the implementation in `quick_upload.py` is, that you must be able to upload a file if it's locked by you, because Office Connector always locks the file.
However the current Office Connector release (1.10.0) does not yet send the lock token when replacing a file. :-(
The check for the correct lock token would break uploading files with the current OC release.
As we need some time to ensure a wide rollout of an OC release with lock token support, the lock check is currently disabled. There's a test verifying …
> Fix tus replace

- opengever/api/navigation.py
- opengever/api/tests/test_navigation.py
This fixes serialization of possible `Missing.Value`s in the `@navigation` endpoint by running its `node` dict through plone.restapi's `json_compatible` helper function.
Jira: https://4teamwork.atlassian.net/browse/GEVER-1023
_Not needed, bug is being fixed in same release as it was introduced_ (#6632)
> Fix handling of Missing.Value in `@navigation` endpoint.

- docs/HISTORY.txt
- opengever/core/lawgiver.zcml
- opengever/core/profiles/default/workflows/opengever_workspace/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace/specification.txt
- opengever/core/profiles/default/workflows/opengever_workspace_document/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_document/specification.txt
- opengever/core/profiles/default/workflows/opengever_workspace_folder/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_folder/specification.txt
- opengever/core/profiles/default/workflows/opengever_workspace_todo/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_todo/specification.txt
- opengever/core/profiles/default/workflows/opengever_workspace_todolist/definition.xml
- opengever/core/profiles/default/workflows/opengever_workspace_todolist/specification.txt
- opengever/core/upgrades/20200917122158_update_workspace_workflows/upgrade.py
- opengever/core/upgrades/20200917122158_update_workspace_workflows/workflows/opengever_workspace/definition.xml
- opengever/core/upgrades/20200917122158_update_workspace_workflows/workflows/opengever_workspace_document/definition.xml
- opengever/core/upgrades/20200917122158_update_workspace_workflows/workflows/opengever_workspace_folder/definition.xml
- opengever/core/upgrades/20200917122158_update_workspace_workflows/workflows/opengever_workspace_root/definition.xml
- opengever/core/upgrades/20200917122158_update_workspace_workflows/workflows/opengever_workspace_todo/definition.xml
- opengever/core/upgrades/20200917122158_update_workspace_workflows/workflows/opengever_workspace_todolist/definition.xml
- opengever/workspace/tests/test_deactivate_workspace.py
- opengever/workspace/tests/test_workspace_workspace.py
With this PR we achieve that local roles can no longer be changed in deactivated workspaces. This also means that no new members can be invited.
Jira: https://4teamwork.atlassian.net/browse/GEVER-1017
> Do not manage security in deactivated workspaces

- docs/HISTORY.txt
- opengever/base/service.py
- opengever/base/tests/test_api.py
Fix the `status` service endpoint when it is used for mails. Also port existing functional tests to separate integration test-cases and attempt to improve readability of test-cases and in case of failures.
Jira: https://4teamwork.atlassian.net/browse/GEVER-1048
> Fix `status` API endpoint for mails.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/deactivate.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_base.py
- opengever/dossier/tests/test_deactivate.py
- opengever/dossier/tests/test_resolve.py
- opengever/workspaceclient/linked_workspaces.py
With this PR a dossier can no longer be resolved or deactivated if it is linked to an active workspace.
To have access to the WorkspaceClient you need the permission `opengever.workspaceclient: Use Workspace Client`. I have achieved this with the `elevated_privileges` context manager. Maybe there is a better way to do this?
Jira: https://4teamwork.atlassian.net/browse/CA-995
> Don't resolve or deactivate a dossier if it is linked to an active workspace

- docs/HISTORY.txt
- opengever/api/solr_query_service.py
- opengever/api/tests/test_vocabularies.py
- opengever/base/vocabulary.py
- opengever/contact/browser/participation_forms.py
- opengever/document/behaviors/metadata.py
- opengever/dossier/archive.py
- opengever/dossier/behaviors/dossier.py
- opengever/dossier/behaviors/participation.py
- opengever/task/util.py
ℹ️ TO THE REVIEWWER ℹ️ 
This PR is kind of changing the current api because it now handles elephantvocabularies properly. I'm not sure, if this change have to be mentioned as breaking api change or not. It was broken before, but it behaves differently now...
---------
[ElephantVocabularies](https://github.com/collective/collective.elephantvocabulary) are wrapper vocabularies around zope.schema vocabularies to restrict vocabulary entries.
The vocabulary factory for the schema field ([example schema field in gever](https://github.com/4teamwork/opengever.core/blob/485762035774a90c8a76ecda5c6be44901749092/opengever/document/behaviors/metadata.py#L117)) is created by the [`wrap_vocabulary`](https://github.com/collective/collective.elephantvocabulary/blob/master/collective/elephantvocabulary/__i …
> Provides the IVocabularyTokenized interface for elephant vocabularies.

- docs/HISTORY.txt
- docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
- docs/public/dev-manual/api/schemas/opengever.document.document.inc
- docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
- docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc
- docs/public/dev-manual/api/users.rst
- docs/schema-dumps/_opengever.ogds.models.group.Group.schema.json
- opengever/api/configure.zcml
- opengever/api/group.py
- opengever/api/permissions.zcml
- opengever/api/tests/test_group.py
- opengever/api/tests/test_ogdsgroups.py
- opengever/base/exceptions.py
- opengever/base/utils.py
- opengever/core/lawgiver.zcml
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20200909150915_add_is_local_column_for_groups/upgrade.py
- opengever/core/upgrades/20200909162246_add_manage_groups_permission/rolemap.xml
- opengever/core/upgrades/20200909162246_add_manage_groups_permission/upgrade.py
- opengever/core/upgrades/20200921135157_manage_groups_with_source_groups_plugin/upgrade.py
- opengever/examplecontent/profiles/4teamwork-ldap/ldap_plugin.xml
- opengever/ogds/base/sync/ogds_updater.py
- opengever/ogds/base/tests/test_ogds_updater.py
- opengever/ogds/models/group.py
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/ldap/ldap_plugin.xml.bob
- opengever/setup/deploy.py
- opengever/testing/fixtures.py
For Teamraum deployments we want to allow administrators to manage groups so that groups can be used to give access to workspaces. Plone already has a `@groups` endpoint, but we needed to extend it to support our OGDS as well as allow Administrators to use the endpoint. For that we:
- Overwrite the `@groups` POST, PATCH and DELETE endpoints
- Customize the endpoints to be allowed for Administrators
- Customize the endpoints to handle the OGDS
- Restrict the endpoints to handle workspace roles
- Restrict the endpoints to only manage local groups (source groups)
- Modify the `sync_ogds` to avoid overwriting the source groups managed by the `@groups` endpoint
Another difficulty that arose in that groups are enumerated and managed over the plugins, so we need to make sure that our deployments …
> Overwrite @groups endpoint to handle the OGDS

- .github/pull_request_template.md
PR template: Add note to notify `#delivery` channel on breaking API changes.
As requested by @stefanhaenni
> PR template: Add note to notify #delivery on breaking API changes.

- opengever/api/group.py
- opengever/api/tests/test_group.py
This is a follow-up PR for #6631
This PR fixes an issue where the group title have not been synchronized with the ogds-group when creating a new group with the `@groups` endpoint.
Jira: https://4teamwork.atlassian.net/browse/CA-530
- API change:
- If breaking:
> Also sync the group title with the ogds-group when adding a new group

- docs/HISTORY.txt
- opengever/latex/dossiercover.py
- opengever/latex/dossierdetails.py
- opengever/latex/layouts/default.py
- opengever/latex/layouts/resources/default_layout.tex
- opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
- opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
- opengever/latex/locales/opengever.latex.pot
- opengever/latex/templates/dossiercover.tex
- opengever/latex/templates/dossierdetails.tex
- opengever/latex/tests/test_default_layout.py
- opengever/latex/tests/test_landscape_layout.py
A French translation isn't available when exporting the dossier cover, therefore it is added.
Example files:
[dossiercover.pdf](https://github.com/4teamwork/opengever.core/files/5274165/dossiercover.pdf)
[dossierdetails.pdf](https://github.com/4teamwork/opengever.core/files/5274166/dossierdetails.pdf)
Jira: https://4teamwork.atlassian.net/browse/GEVER-832
- API change:
- If breaking:
> Add missing translations for dossier export.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/repositoryfolder.py
- opengever/api/tests/test_repository_folder.py
- opengever/repository/behaviors/referenceprefix.py
When creating repository folders via API so far the `reference_number_prefix` was not validated. Theoretically users could have chosen duplicate prefixes. This PR adds validation when creating repository folders via API.
I've decided to implement validation in the deserializer as it has all the information necessary.
- It knows whether we are adding or editing
- It has all the data, context and parent can be accessed easily
Unfortunately an invariant cannot be used as it does not know whether we are adding or editing. Also the add form does provide different data during add than the rest api. In the form context is unavailable while adding, while in the rest API the object to be validated is already created and passed as as context.
We also we leave validation via …
> Prevent setting invalid reference prefix number via API.

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/dossier_participations.rst
- docs/public/dev-manual/api/index.rst
- opengever/api/configure.zcml
- opengever/api/dossier_participations.py
- opengever/api/tests/test_dossier_participations.py
- opengever/core/upgrades/20200925090651_migrate_participations/upgrade.py
- opengever/dossier/behaviors/participation.py
- opengever/dossier/browser/forms.py
- opengever/dossier/events.py
- opengever/dossier/interfaces.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_participation.py
- opengever/journal/configure.zcml
- opengever/journal/handlers.py
- opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/opengever.journal.pot
In this PR some changes are implemented:
- CRUD endpoints are implemented for dossier participations
- Previously it was possible to have several participations per participant. This is now prevented by not being able to create a participation for a user if the user already has a participation on the dossier.
- Since it is possible that multiple participations exist for users, all participations had to be migrated.
- Since participations can now be modified via the API endpoint, a journal entry must be created for the modification of a participation.
About the upgrade step: maybe it should be deferrable, because it goes over all dossiers. Also, the endpoints will not be used as long as the frontend part is not implemented. Probably it would make sense to use the same upgrade step in the …
> Add @participations endpoints for dossiers

- docs/HISTORY.txt
- opengever/document/handlers.py
- opengever/document/tests/test_handlers.py
No longer prevent adding documents with doc-property update issues. There are currently problems with python-docx when it attempts to parse bookmark references, which seem to be valid in word but will cause an error when the document is parsed. It will fail with the following traceback:
```
File "/Users/deif/Files/workspaces/opengever.core/opengever/document/handlers.py", line 60, in _update_docproperties
DocPropertyWriter(document).update()
File "/Users/deif/Files/workspaces/opengever.core/opengever/document/docprops.py", line 95, in update
if self.update_doc_properties(only_existing=True):
File "/Users/deif/Files/workspaces/opengever.core/opengever/document/docprops.py", line 118, in update_doc_properties
return self.write_properties(only_existing, self.get_properties())
File …
```
> Don't prevent adding document with docprop issues.

- docs/HISTORY.txt
- opengever/core/upgrades/20200930131957_add_cadwork_mime_types/mimetypes.xml
- opengever/core/upgrades/20200930131957_add_cadwork_mime_types/upgrade.py
- opengever/officeconnector/mimetypes.py
- opengever/policy/base/profiles/mimetype/mimetypes.xml
Register mimetypes for Cadwork in mimetypes registry and add them to the editable types of Office Connector.
These are not official IANA mimetypes.
JIRA: https://4teamwork.atlassian.net/browse/CA-974
> Add Cadwork mimetypes

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/tests/test_group.py
The `POST`, `PATCH` and `DELETE` verbs vor the `@groups` endpoint are already using the `opengever.api.ManageGroups` permission. We also need this permission for the `GET` verb to make sure, an administrator can manage groups properly.
The default permission assiged by the `plone.restapi` is `cmf.ManagePortal`
Issuer: https://4teamwork.atlassian.net/browse/NE-83
- API change:
- If breaking:
> Makes the GET @groups endpoint available with the `opengever.api.ManageGroups` permission.

- docs/HISTORY.txt
- docs/public/dev-manual/api/workspace/participation.rst
- opengever/api/configure.zcml
- opengever/api/participations.py
- opengever/api/tests/test_participation.py
- opengever/base/role_assignments.py
- opengever/base/tests/test_role_assignments.py
- opengever/ogds/base/actor.py
- opengever/workspace/participation/__init__.py
- opengever/workspace/participation/browser/manage_participants.py
Currently, it's only possible to let users participating on a teamraum. 
This PR extends the participation management in a teamraum to also manage groups.
Jira: https://4teamwork.atlassian.net/browse/NE-71
- API change:
- If breaking:
> Manage groups in teamraum

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_solrsearch.py
- opengever/base/tests/test_solr.py
- opengever/core/upgrades/20201006142950_reindex_external_reference_in_solr/upgrade.py
- solr-conf/managed-schema
With this PR we add a field `external_reference` also to Solr. The field can have two sources, it can come from documents or dossiers.
The field `IDocumentMetadata.foreign_reference` is also indexed into the index external_reference:
https://github.com/4teamwork/opengever.core/blob/fe821de8281b88dd16276158d4d7ec7029c59a96/opengever/document/indexers.py#L119-L123
We include it here to reindex consistently and the same way as the field is indexed in the catalog. This will lead to somewhat inconsistent naming of `foreign_reference` v.s. `external_reference`.
I've quickly discussed it with @lukasgraf and we'e decided to leave it as is for now, with the following way out:
- should `foreign_reference` be used, we can reindex documents with a `foreign_reference` into an additional Solr field, …
> Add external_reference field to solr, reindex objects with values.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/core/upgrades/20201009110640_add_phvs_special_fields_to_solr/upgrade.py
- solr-conf/managed-schema
As listings have been switched to always using solr, we now need the PHVS specific fields to be indexed in solr in order to be able to display them in the listings. We therefore add the fields to the solr `managed-schema`. The upgrade step will only reindex object on the PHVS deployment as it queries for the interface supporting the PHVS specific fields.
I have tested this locally with the PHVS policy for the listings in the classic UI and made sure that indexing also works properly when modifying the fields (edit form in the classic and new UI).
For https://4teamwork.atlassian.net/browse/CA-950
> Add and index PHVS specific fields in solr.

- opengever/api/tests/test_dossier.py
The correct parameter name is "expand" and not "expansion" for requiring expansions over the REST-API. Tests were not failing because the main-dossier expansion gets expanded by default.
This is not for any jira issue, and I think does not deserve a changelog entry.
> Correct main-dossier expansion tests.

- docs/HISTORY.txt
- opengever/api/tests/test_dossier.py
- opengever/dossier/utils.py
This PR extends the `get_main_dossier` utility function to also provide it for dossiertemplates.
Jira: https://4teamwork.atlassian.net/browse/NE-57
- API change:
- If breaking:
> Also provide main_dossier for dossiertemplates

- docs/HISTORY.txt
- docs/public/dev-manual/api/content_types.rst
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/dossier_from_template.rst
- docs/public/dev-manual/api/index.rst
- opengever/api/configure.zcml
- opengever/api/templatefolder.py
- opengever/api/tests/test_templatefolder.py
- opengever/api/tests/test_vocabularies.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20201008174028_add_folder_factories_to_portal_actions/actions.xml
- opengever/core/upgrades/20201008174028_add_folder_factories_to_portal_actions/upgrade.py
- opengever/dossier/dossiertemplate/__init__.py
- opengever/dossier/dossiertemplate/configure.zcml
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/tests/test_dossier_template.py
- Add `folder_factories` to `portal_actions`. This way the folder_factories appear by default when the @actions endpoint is requested and we don't have to define, which categories are needed. With this information we can then find out where the dossiers, documents and tasks can be created from template.
- Implement `opengever.dossier.DossierTemplatesVocabulary`.
- Move some functions to a helper class to make them reusable. I'm not sure if it's pythonic to have a mixin class or if I copied that from frontend development. 🤔
- Add `@dossier-from-template` endpoint. The endpoint inherits from the class used to create content using POST requests to create the dossier. The remaining content is then created using the methods I moved to the mixin helper class.
Jira: …
> Add @dossier-from-template endpoint

- docs/HISTORY.txt
- opengever/api/tests/test_group.py
- opengever/base/utils.py
- opengever/core/upgrades/20201012191434_activate_groups_plugin_for_source_groups/upgrade.py
- opengever/setup/deploy.py
Activates the `IGroupsPlugin` for `source_groups`. The groups plugins determines the groups to which a user belongs. This is mandatory to make permission lookups through groups possible. Since an admin can manage local groups, we need to activate this plugin for the source_groups.
The implementation is leaned on: https://github.com/4teamwork/opengever.core/pull/6631
Jira: https://4teamwork.atlassian.net/browse/NE-71
- API change:
- If breaking:
> Activate the groups plugin for source_groups.

- README.rst
- opengever/core/testserver.py
Currently, the `bin/testserver` will fail on startup if a solr is already running. So it's not possible to run a local dev environment in addition with a running testserver.
A running solr is blocking all of its cores. Thus, running two solr servers on different ports with the same configuration is not possible. The first running server is blocking the core of the second one. This happens if you try to run the testserver with an `opengever.core` checkout where you already started a solr server manually. This is normally the case while developing.
You can tell the testserver to reuse the already running solr instead of starting an own server. To do this, set the ``SOLR_PORT`` to the running solr and the ``TESTSERVER_REUSE_RUNNING_SOLR`` to the same port.
This will tell the testserver to …
> Reuse already running solr instance if available

- docs/HISTORY.txt
- docs/public/dev-manual/api/dossier_participations.rst
- opengever/api/configure.zcml
- opengever/api/dossier_participations.py
- opengever/api/tests/test_dossier_participations.py
In this PR a new API endpoint `@possible-participants` is implemented. The endpoint is used to decide for which users/contacts/mailboxes participations can be added.
Jira: https://4teamwork.atlassian.net/browse/NE-90
- API change:
> Add @possible-participants endpoint.

- opengever/policytemplates/policy_template/opengever.+package.name+/bootstrap.py
Since the bootstrap.py has been updated, it should also be updated in the policy template.
It was already updated in August, so there are no major changes.
Jira: https://4teamwork.atlassian.net/browse/NE-113
> Update bootstrap.py in policy template.

- docs/HISTORY.txt
- opengever/readonly/bumblebee.py
- opengever/readonly/configure.zcml
- opengever/readonly/tests/test_bumblebee_readonly_support.py
Create and persist the user's bumblebee salt during login, if one doesn't exist yet.
This will make sure it's available when needed, and doesn't have to be calculated and persisted as part of an ad-hoc write-on-read. Since several writes already happen during login _(when the connection is in read-write mode)_, and the login request is whitelisted by `plone.protect` itself, this shouldn't have any adverse effects.
By doing this we can ensure that users that have already logged in at least once have their salt ready, and will be able to see Bumblebee previews in read-only mode.
_(On a login during read-only mode this needs to be suppressed - the whole idea is that we won't have to generate any salts while in read-only mode)_
> Create and persist Bumblebee user salt on login.

- docs/HISTORY.txt
- docs/schema-dumps/opengever.workspace.workspace.schema.json
- opengever/api/tests/test_workspace.py
- opengever/base/schemadump/config.py
- opengever/base/schemadump/schema.py
- opengever/bundle/schemas/workspaces.schema.json
- opengever/core/upgrades/20201015155432_add_videoconferencing_ur_ls_to_workspaces/registry.xml
- opengever/core/upgrades/20201015155432_add_videoconferencing_ur_ls_to_workspaces/upgrade.py
- opengever/core/upgrades/20201015171147_add_default_videoconferencing_ur_ls_to_workspace_objects/upgrade.py
- opengever/workspace/interfaces.py
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/tests/test_workspace_workspace.py
- opengever/workspace/workspace.py
With this PR we add a simple field to display a link to some videoconferencing provider on a workspace. 
- By default we provide auto-generated URLs for Jitsi, but this can be overriden by the user
- If no link is desired the field can be left empty
- If another solution or URL is desired (e.g. for Self-Hosted Jitsi, the base-url can be adapted via registry)
- Fields are left untranslated in the classical UI as we're only providing the new UI
_I'll leave this open as a draft for @njohner to take over. The UI part is missing but required for this to function well and not break. There is a POC which needs some 💛 &nbsp; in https://github.com/4teamwork/gever-ui/tree/deif/1009-jitsi-poc_
Jira: https://4teamwork.atlassian.net/browse/CA-1009 …
> Add simple videoconferencing URL field to workspaces.

- docs/HISTORY.txt
- opengever/journal/handlers.py
- opengever/readonly/tests/test_file_download.py
Don't create journal entry when downloading file copy in readonly mode (original documents or PDF previews from bumblebee).
This is to **prevent the write-on-read** that would otherwise happen during journaling of the file download in readonly mode.
> Don't create journal entry when downloading file copy in readonly mode.

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_listing_stats.py
- opengever/base/contentlisting.py
This PR:
- adds a new listing to list all contents within a context
- adds a new listing-field `creator_fullname`
We need to list contents of a workspaces. Currently `contents` are workspace folders, documents and mails. A generic `folder_contents` listing lets the frontend decide, which types should appear in the `contents` tab.
Jira: https://4teamwork.atlassian.net/browse/NE-124
- API change:
- If breaking:
> Extend the @listing endpoint to list `folder_contents`

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
This PR implements a new query parameter for the `@listing` endpoint: `sort_first`.
This parameter can be used to order the listing results into two groups. We use this in combination with the `folder_contents` listing to order folderish contents first.
The function query executes in an average time of 200ms on a system with about one million contents. The tested query was:
`if(or(termfreq(portal_type, 'opengever.dossier.businesscasedossier'), termfreq(portal_type, 'opengever.document.document')),1, 0) desc` 
Jira: https://4teamwork.atlassian.net/browse/NE-124
- API change:
- If breaking:
- Upgrade steps (changes in …
> Implement sort group for the `@listing` endpoint

- docs/HISTORY.txt
- opengever/readonly/__init__.py
This might for example happen when a request hits the Zope application root instead of the Plone site.
Returning `False` in this case is incorrect, strictly speaking, but the only safe choice to fall back to (in the sense that in writable production mode, the system must _never_ be considered readonly by accident).
But since 
- the result of this flag has no discernable effect on the Zope App Root
- the worst that could happen as a consequence of False-Negative answers to `is_in_readonly_mode()` is that actions that won't work are shown
this should be fine.
> Make is_in_readonly_mode() more robust when getSite() hook returns None

- docs/HISTORY.txt
- opengever/base/browser/templates/error.pt
When debugging user-specific login related writes-on-read, it's desirable to have the **culprit traceback** shown for users other than managers - otherwise, these writes-on-read get quite tricky to hunt down.
Thefore I remove the `is_manager` restriction for write-on-read culprit tracebacks.
I don't really consider this a security risk in terms of information disclosure:
This functionality (_write-on-read tracing_) has to be enabled deliberately by developers, times out, and could only ever be seen by end users during a short period of time, under very specific circumstances (when RO mode is active).
> Show culprit traceback on ReadOnlyError page to all users, not just managers

- docs/HISTORY.txt
- opengever/base/quickupload.py
- opengever/base/tests/test_quickupload.py
c.quickupload correctly determines the mimetype from Plone's mimetypes registry. However our quick upload adapter doesn't pass the mimetype to the `CreateDocumentCommand`. Because of this plone.namedfile determines the mimetype using Python's mimetypes module, which doesn't work for custom mimetypes.
JIRA: https://4teamwork.atlassian.net/browse/CA-1143
> Fix mimetype for quickupload with custom mimetypes

- docs/HISTORY.txt
- opengever/base/browser/errors.py
Custom error page: Also log `ReadOnlyError` culprit traceback (if one is available) to error log in `var/log/instance?-log`.
This makes debugging easier in situations where the error page contents aren't easily viewable in the browser, like for AJAX requests.
> Custom error page: Also log ReadOnlyError culprit traceback

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/readonly.py
- opengever/readonly/tests/test_login_during_readonly.py
Avoid `ftw.casauth` write-on-read (last login times) during login:
Patch `CASAuthenticationPlugin.set_login_times()` to avoid the write-on-read during login when attempting to set login times.
This is the same issue that's already being patched for the `MembershipTool`, but `ftw.casauth` contains its own copy of `setLoginTimes()` and therefore needs to be patched separately.
> Avoid ftw.casauth write-on-read (last login times) during login

- docs/HISTORY.txt
- opengever/api/tests/test_listing.py
- opengever/dossier/indexers.py
It seems that I messed up the label order for the `participations` field in the API endpoint. We were returning `role label|participant label` instead of `participant label|role label`.
For https://4teamwork.atlassian.net/browse/CA-17
- API change: Documentation is still ok, and it's not a breaking change as such as it's just the returned labels that change
- If breaking:
> Fix order of labels for participations field in the listing endpoint.

- docs/HISTORY.txt
- opengever/workspaceclient/__init__.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/locales/de/LC_MESSAGES/opengever.workspaceclient.po
- opengever/workspaceclient/locales/fr/LC_MESSAGES/opengever.workspaceclient.po
- opengever/workspaceclient/locales/opengever.workspaceclient.pot
- opengever/workspaceclient/tests/__init__.py
- opengever/workspaceclient/tests/test_linked_workspaces.py
We add journal entries in the dossier for the following actions:
- Creation of a new linked workspace
- Copy of a document to a linked workspace
- Copy of a document from a linked workspace
This is to guarantee traceability.
I wonder whether we should also add a journal entry on the document itself when it is being copied over to a workspace. 
This is for:
- https://4teamwork.atlassian.net/browse/CA-927
- https://4teamwork.atlassian.net/browse/CA-928
- https://4teamwork.atlassian.net/browse/CA-929
> Journalize creation of linked workspace and copying documents to and from it.

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
This PR adds the application type to the @config endpoint. This allows the frontend to decide which app should be loaded independently from the portal.
Jira: https://4teamwork.atlassian.net/browse/NE-97
- API change:
> Extend @config endpoint with application type.

- opengever/workspaceclient/configure.zcml
Seems I forgot to register the new `locales` directory introduced in https://github.com/4teamwork/opengever.core/pull/6701 for the new journal entries for workspace client actions (create from a dossier, copy document back and forth between dossier and workspace).
For
- https://4teamwork.atlassian.net/browse/CA-927
- https://4teamwork.atlassian.net/browse/CA-928
- https://4teamwork.atlassian.net/browse/CA-929
> Register new translations directory in opengever.workspaceclient.

- docs/HISTORY.txt
- opengever/readonly/cli.py
- opengever/readonly/tests/data/filestorage-ro-zope.conf
- opengever/readonly/tests/data/filestorage-rw-zope.conf
- opengever/readonly/tests/data/relstorage-ro-zope.conf
- opengever/readonly/tests/data/relstorage-rw-zope.conf
- opengever/readonly/tests/data/zeoclient-ro-zope.conf
- opengever/readonly/tests/data/zeoclient-rw-zope.conf
- opengever/readonly/tests/test_cli.py
- setup.py
This script allows to enable or disable the read-only mode of all instances in a GEVER deployment without running buildout.
It adds an environment variable `GEVER_READ_ONLY_MODE=true` and sets the ZODB connection to read-only in the `zope.conf` file.
By default all instances except for `instance0` are toggled. If an instance is in read-write mode it's set to read-only and vice versa.
With the command line options `-r` and `-w` it's possible to enable or disable the read-only mode regardless of the current state (see also `bin/toggle-readonly --help`)
After toggling the affected instances needs to be restarted.
JIRA: https://4teamwork.atlassian.net/browse/CA-211
> Add script to toggle read-only mode in zope.conf

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
The bumblebee notifications url is necessary for the gever-ui to open a websocket connection to bumblebee in order to receive updates about newly created previews. With those updates, the gever-ui is able to reload the document's preview images as soon as the preview is available in bumblebee.
See https://4teamwork.atlassian.net/browse/NE-80
- API change:
- If breaking:
> Expose bumblebee notifications url in the config endpoint

- opengever/readonly/__init__.py
During a local setup the connection can be `None` at some point. A setup would fail with the following trace:
```
Module opengever.setup.browser.admin, line 132, in __call__
Module opengever.setup.browser.admin, line 176, in install_with_ajax_stream
Module opengever.setup.browser.admin, line 147, in _install
Module opengever.setup.deploy, line 61, in create
Module opengever.setup.deploy, line 149, in sync_ogds
Module opengever.ogds.base.sync.ogds_updater, line 77, in sync_ogds
Module opengever.ogds.base.sync.import_stamp, line 38, in set_remote_import_stamp
Module opengever.ogds.base.sync.import_stamp, line 29, in …
```
> Handle when connection is None in readonly.

- docs/HISTORY.txt
- docs/public/dev-manual/api/dossier_from_template.rst
- opengever/dossier/dossiertemplate/form.py
When creating a dossier from a template we need access to the template in the frontend. Since the IntId cannot be resolved by an endpoint, the Oguid is now set as token in the DossierTemplatesVocabulary, because we can resolve the Oguid with the @resolve-oguid endpoint.
Discussed with @deiferni 
Since the vocabulary was only accessible via API since the last release, I do not consider it necessary to notify the channel and the Scrum Master. 
Jira: https://4teamwork.atlassian.net/browse/NE-43
- API change:
- If breaking:
> Use oguid instead of intId as token in DossierTemplatesVocabulary

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_query.py
- opengever/globalindex/tests/test_reporter.py
- opengever/globalindex/utils.py
Pre-discussed with @deiferni : https://4teamwork.slack.com/archives/C01BHEGBVU1/p1603707985016500
Jira: https://4teamwork.atlassian.net/browse/NE-56
----- 
The `@@task_report` view is a folder-action which should also work for the gever-ui.
Currently, the view wants a list of `task_ids` which should be included in the report. Unfortunately, we don't have `task_ids` in the `@listing` endpoint of the frontend. Including it would mean, that we have to index the `task_ids` in solr and expose it int the `@listing` endpoint. This was not desired. Thus, we need another way to lookup the tasks.
Because the tasks in a default listing are always within the current admin unit, we can do a task lookup by the resource-id (`@id`)
This PR extends the `@@task_report` view with a new parameter: `tasks`. …
> @@task_report-view supports task lookup by the ressource-id through the `tasks` parameter.

- docs/HISTORY.txt
- opengever/core/upgrades/20201028100049_ensure_solr_only_indices_dropped_from_catalog/upgrade.py
- opengever/document/config.py
- opengever/document/tests/test_catalog.py
- opengever/document/tests/test_copy_document.py
- opengever/dossier/tests/test_move_items.py
We seem to have different indexes still around for different deployments regarding the catalog indices `document_author`, `SearchableText` and `total_comments`. The following states exist:
- Neither `document_author` nor `SearchableText`:
This happened when solr was activated with the `activate_solr.py` script
from `opengever.maintenance` https://github.com/4teamwork/opengever.maintenance/blob/a05f10627dd8729db13128d7a767d98d7696b508/opengever/maintenance/scripts/activate_solr.py. It deleted the `document_author` index which was still present in `opengever.core`.
- Only `document_author`:
This is the state for all new deployments where `activate_solr.py` has not been run as the `document_author` index was still present in `opengever.core`.
- Indices `document_author`, `SearchableText` and …
> Ensure remaining indices are dropped from catalog.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/browser/sablontemplate.py
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_agendaitem.py
Jira: https://4teamwork.atlassian.net/browse/NE-108
A user should be able to order agena-item attachments in the new UI. This is already possible through the restapi with unsubmitted proposals. While submitting the proposal, the related documents gets sorted by the title. The old ui meeting view which displays submitted proposals will now show the attachments ordered by title as well.
By removing the ordering, we get the documents in the order as they where created. And this is the user defined order, exactly what we want to display. 
This PR no longer orders the agenda-item attachments by name but by the position in the relationItem field instead:
_Only applicable should be left and …
> Agenda-item attachments are now ordered based on the position in the relationField.

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/tests/test_listing.py
In https://4teamwork.atlassian.net/browse/NE-173, the user reported an issue, where not all facets are listed in the dossier listing.
This is becuase the default facet limit is 100 in solr 8.4: https://lucene.apache.org/solr/guide/8_4/faceting.html#field-value-faceting-parameters.
So, remove the limit of the Subject facets by including f.Subject.facet.limit=-1 in the solr query.
> Remove limit for Subject facet

- docs/HISTORY.txt
- docs/public/dev-manual/api/dossier_from_template.rst
- opengever/dossier/dossiertemplate/form.py
This PR is a follow-u pr of #6709 
We want to use the vocabulary in combination with a selection-widget which is based on solr.
Because we don't indexed the OGUID in solr, we're not able to intersect vocabulary items and solr items.
This PR now uses the `UID` instead which is already indexed in solr.
Jira: https://4teamwork.atlassian.net/browse/NE-43
Prediscussed with @njohner: https://4teamwork.atlassian.net/browse/NE-43?focusedCommentId=19007
> While we might want to try to uniformly return OGUIDs everywhere in the future, this is not a realistic option right now. Indexing the OGUID would also be very expensive, as it is not in the catalog, it would require an upgrade step that wakes all the objects from the catalog…
> So for now I advised that we go with the UID. If we ever decide to …
> Use UID instead of oguid as token in DossierTemplatesVocabulary.

- docs/HISTORY.txt
- docs/public/dev-manual/api/webactions.rst
- opengever/api/actions.py
- opengever/api/configure.zcml
- opengever/api/tests/test_actions.py
- opengever/webactions/interfaces.py
- opengever/webactions/provider.py
- opengever/webactions/tests/test_webactions_provider.py
Currently, webactions are only manageable. To be able to display registered webactions in the UI, we have to expose registered webactions somewhere. We decided to integrate them into the `@actions` endpoint in a new category `webactions`.
This PR overrides the `@actions` endpoint for GEVER and extends the result with `webactions`. If there are no webactions available, it will return an empty list for the `webactions`-category.
Because a webaction consist of many attributes we don't want to expose to the end-user, we white-list the desired attributes for the serialized `webactions` in the `@actions` endpiont.
Pre-Discussion: https://4teamwork.slack.com/archives/C01BHEGBVU1/p1603815306027700
Jira: https://4teamwork.atlassian.net/browse/NE-65
_Everything has to be done/checked. Checked but …
> Webactions integration in @actions endpoint

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/debug/__init__.py
- opengever/debug/browser/manage_write_on_read_tracing.py
- opengever/debug/patches/modified_out_of_sync.py
- opengever/debug/stacktrace.py
- opengever/debug/write_on_read_tracing.py
With this PR we add patches that help to hunt down the very rarely occurring out of sync modified of catalog v.s. content objects. We suspect there is a missing reindex when the attribute is set. I have not managed to figure it out locally, so best strategy IMO would be to enable the patches on our dev system and wait.
The patches are inactive by default and should only be activated on a non-production system for the moment. They are designed in such a way that they can be activated for a deployment via buildout configuration in the `instance` section:
```
[instance]
environment-vars +=
GEVER_DEBUG_MODIFIED_OUF_OF_SYNC True
```
We want to activate them on dev for now and as the issue occurs very rarely activation has to be persistent across instance restarts.
- Write on read tracing has …
> Add debug patches to hunt for out of sync modified (catalog v.s. objects).

- docs/HISTORY.txt
- opengever/api/participations.py
- opengever/api/tests/test_participation.py
- opengever/ogds/base/actor.py
`@participations` endpoint was failing for participations with a `participant_id` that could not be resolved to an actor. This is because the `represents` from the `NullActor` was broken. It now returns `None`, as it probably was intended to, which also has to be handled in the `@participations` endpoint.
With this PR we fix this issue, but we should probably remove the `represents` from the `Actor` and simply return an actor in this `@participations` endpoint. This endpoint was forgotten in https://github.com/4teamwork/opengever.core/pull/6713. I will either make a PR for this adaptation or open a new story.
For https://4teamwork.atlassian.net/browse/CA-1185
> Fix the Workspace `@participations` endpoint for NullActors

- docs/public/dev-manual/api/workspace/participation.rst
- opengever/api/participations.py
- opengever/api/tests/test_participation.py
The workspace `@participations` endpoint got forgotten in https://github.com/4teamwork/opengever.core/pull/6713. We now also return the `participant_actor` in that endpoint, so that in the long run we can remove the custom serialized `participant` from the response.
For  https://4teamwork.atlassian.net/browse/CA-406
- API change:
- If breaking:
> Return participant_actor in workspace participations endpoint.

- docs/HISTORY.txt
- opengever/base/behaviors/base.py
- opengever/base/tests/test_base_behavior.py
Jira: https://4teamwork.atlassian.net/browse/NE-247
This PR quick-fixes an issue where it is not possible to create content with an empty bytestring as the description. Currently, every plone content created through the `plone.restapi` without a description will have an empty bytestring instead an empty unicode string as the default value. 
Setting the description directly is possible. That's what the `plone.restapi` does. But setting it though the behavior will fail due to a guard in the `IBaseBehavior`. When creating a dossier form a dossier-template, the main dossier will be created through the `restapi` which works fine. But the subdossiers are created with the `createContentInContainer` method which will then raise an error.
The story https://4teamwork.atlassian.net/browse/CA-918 …
> Convert bytestring values for IOpengeverBase.description field to unicode instead of raising an error.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/tests/test_resolve.py
This fixes resolving subdossiers when the Teamraum Connect feature is enabled.
Subdossiers are not supposed to have linked workspaces (only main dossiers may). But because the `ILinkedWorkspace` adapter [deliberately raises a `ComponentLookupError`](https://github.com/4teamwork/opengever.core/blob/master/opengever/workspaceclient/linked_workspaces.py#L83-L84) when instantiated for a dossier, which would otherwise be adaptable just fine, that lead to a failure when checking dossier resolution preconditions.
This is a quick fix in order to still get it in before we cut the release. Overall, I would really question the approach of raising `ComponentLookupError` there instead of just returning empty lists etc.. But for now I fixed it in the most local way possible, in order to not destabilize …
> Fix resolving subdossiers when Teamraum Connect feature is enabled.

- opengever/api/actions.py
- opengever/api/tests/test_actions.py
- opengever/webactions/provider.py
- opengever/webactions/renderer.py
- opengever/webactions/tests/test_webactions_provider.py
This PR now uses the `WebActionsSafeDataGetter` instead directly the `IWebActionsProvider` adapter to lookup webactions in the `@actions` endpoint. This ensures, that the webaction target urls are interpolated properly and the fields are sanitized.
Currently, not flattened webactions from the `IWebActionsProvider` where filtered through: `_filter_action_data`. But not flattened. That's why we use `_filter_action_data` for flattened webactions now to get the same response for each type of representation. We have to whitelist the `display` attribute within the `IWebActionsProvider`. We need the `display` attribute in the serialized webactions for the `@actions` endpoint.
Jira: https://4teamwork.atlassian.net/browse/NE-65
_Everything has to be done/checked. Checked but not present means the …
> Interpolate target_url for webactions exposed in the @actions endpoint

- README.rst
- development.cfg
- docker-compose.yml
- docs/HISTORY.txt
- opengever/base/tests/test_msg_transform.py
- opengever/base/transforms/msg2mime.py
- opengever/core/testing.py
- opengever/latex/builder.py
- opengever/latex/overrides.zcml
- opengever/latex/tests/test_builder.py
- opengever/meeting/sablon.py
- opengever/meeting/tests/test_unit_sablon.py
- opengever/testing/docker.py
Adds support for using web-based services instead of locally installed executables for `msgconvert`, `sablon` and `pdflatex`.
This is a first step towards running `opengever.core` with Docker and turning into a service oriented architecture.
The services are provided as Docker images on [Docker Hub](https://hub.docker.com/search?q=4teamwork&type=image&sort=updated_at&order=desc):
- [msgconvert](https://hub.docker.com/r/4teamwork/msgconvert)
- [pdflatex](https://hub.docker.com/r/4teamwork/pdflatex)
- [sablon](https://hub.docker.com/r/4teamwork/sablon)
To use a specific service, its service URL has to be defined in an environment variable. It not defined, it falls back to use the executable. For local development the service URLs are defines as follows:
``` …
```
> Docker services

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/base/colorization.py
- opengever/base/tests/test_gever_colorization.py
- opengever/base/viewlets/colorization.py
The color should be displayed in new UI later, so it is necessary to display it in the endpoint.
https://4teamwork.atlassian.net/browse/CA-1147
- API change:
- If breaking:
> Add GEVER_COLORIZATION to the config endpoint

- development.cfg
For local development, third party executables such as sablon are disabled and since require a web service.
In order for the testserver to work locally, the locations of those services have to be configured, otherwise the testserver tries to look for missing executables.
> Fix testserver setup for local development

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/configure.zcml
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20201103154342_add_disposition_setting_to_allow_non_expired_dossiers_for_selection/registry.xml
- opengever/core/upgrades/20201103154342_add_disposition_setting_to_allow_non_expired_dossiers_for_selection/upgrade.py
- opengever/disposition/interfaces.py
- opengever/disposition/tests/test_disposition.py
- opengever/disposition/validators.py
- opengever/testing/integration_test_case.py
With this PR we add a new new flag we allow to optionally disable the restriction to only add expired dossiers to a disposition. All closed dossiers will be allowed for selection disregarding any retention period setting.
- Add flag to disregard retention period, not enabled by default
- Expose flag in `@config`
- Partially related: follow naming conventions for REST-Api, `Config`->`ConfigGet`
Jira: https://4teamwork.atlassian.net/browse/CA-884
> Add flag to disregard retention period when creating a disposition.

- docs/HISTORY.txt
- opengever/activity/browser/templates/notification_mail_macros.pt
The URL in the comment seems to have caused some mail servers to bounce the message as the domain seems to be in a blacklist. Also the blog post that was linked does no longer exists.
Jira: https://4teamwork.atlassian.net/browse/CA-1209
> Drop URL to blacklisted hosts in notifications.

- docs/HISTORY.txt
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/.mrbob.ini
With this PR we make another baby-step towards improving the policy generator a bit.
We add new defaults that can be guessed from previous input for the following questions:
- bumblebee app id
- ogds db name
- administrator group
We also switch question order, and ask for admin unit id first to generate defaults from the technical admin unit identifier instead from of from the user visible abbreviation. The questions for which defaults are generated are also asking for technical identifier, so that IMO makes more sense.
Jira: https://4teamwork.atlassian.net/browse/CA-1107
> Improve policy generator dynamic defaults.

- docs/HISTORY.txt
- opengever/contact/browser/contacts_tab.py
- opengever/contact/tests/test_contact_tab_helpers.py
We fix an encoding issue that arose due to inconsistent handling of unicode vs bytestrings.
Items passed to the helper methods can be anything from a brain to a solr-document and those do not gurantee unicode strings. Thus we consider these methods to be at the application boundary and make sure we work with unicode internally.
We also refactore the two nearly identical methods and merge them into one method with two shallow wrapper methods setting correct parameters.
Jira: https://4teamwork.atlassian.net/browse/CA-1208
> Fix an encoding error on the local contacts tab.

- docs/HISTORY.txt
- docs/public/dev-manual/api/docs_changelog.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/notification_settings.rst
- opengever/activity/notification_settings.py
- opengever/api/configure.zcml
- opengever/api/notification_settings.py
- opengever/api/tests/test_notification_settings.py
This PR implements an API endpoint for notification settings so that the notification settings can also be offered in the new front end.
A GET request to @notification-settings returns all notification settings (default and personal).
The settings are divided into two groups, `activities` and `general`.
With a PATCH request a notification setting can be edited as well as reset to the default.
Discussed with @lukasgraf 
Jira: https://4teamwork.atlassian.net/browse/NE-99
- API change:
> Add @notification-settings endpoint

- docs/HISTORY.txt
- opengever/dossier/templatefolder/form.py
- opengever/dossier/tests/test_templatefolder.py
Jira: https://4teamwork.atlassian.net/browse/NE-164
We want to use the vocabulary in combination with a selection-widget which is based on solr.
Because we don't indexed the OGUID in solr, we're not able to intersect vocabulary items and solr items.
This PR now uses the UID instead which is already indexed in solr.
Implemented according to https://github.com/4teamwork/opengever.core/pull/6716 where we already changed the vocabulary-token for the `DossierTemplateVocabulary`.
- API change:
- If breaking:
> Use UID instead of intId as token in DocumentTemplatesVocabulary

- docs/HISTORY.txt
- opengever/api/add.py
- opengever/api/configure.zcml
- opengever/api/tests/test_linked_workspaces.py
- opengever/api/workspace.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/tests/test_client.py
This change introduces a dedicated `@upload-document-copy` endpoint for copying documents to Teamraum. 
In order to prepare for also storing metadata about linked documents, the existing use of TUS upload is replaced by a dedicated endpoint on workspaces that accepts everything needed to create a document copy in one single request.
The implementation using TUS was already using three spin-off requests to the remote system during a running transaction:
- Preparation of TUS upload
- TUS upload of the blob
- A PATCH to set metadata
This would have had to be extended by a fourth one to set link metadata for linking the document copy to the GEVER document. Therefore the TUS upload approach had to be abandoned by a more purpose-built endpoint.
Tests for this are problematic: Because some tests …
> Use a dedicated endpoint to upload document copy to workspace

- development-multi-admin.cfg
- docs/HISTORY.txt
- opengever/core/upgrades/20201111125010_add_admin_unit_to_member/upgrade.py
- opengever/examplecontent/meeting.py
- opengever/meeting/committeecontainer.py
- opengever/meeting/model/member.py
- opengever/meeting/model/query.py
- opengever/meeting/tabs/memberlisting.py
- opengever/meeting/tests/test_committee_query.py
- opengever/meeting/tests/test_members.py
- opengever/meeting/tests/test_memberships.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_vocabularies.py
- opengever/meeting/vocabulary.py
- opengever/testing/builders/sql.py
- opengever/testing/fixtures.py
With this PR we enable support for `opengever.meeting` in a cluster with multiple admin-units. No cross admin-unit communication is supported yet. But multiple separate deployments can now have `opengever.meeting` activated individually in the same cluster.
We make sure that:
- only local committees are selectable, where appropriate
- make sure that members are linked to an admin-unit, and only local members are displayed on each admin-unit
Notes/thoughts about the upgrade to add admin-unit to members:
-  We apply a graceful strategy in case we find a deployment in invalid state. Instead of failing hard and blocking a potential upgrade path we migrate using a placeholder and notify that manual cleanup is needed. We don't expect any deployments in such state as it is currently not …
> Add simple support for meetings in a multi-admin-unit cluster.

- docs/HISTORY.txt
- opengever/ogds/base/sync/ldap_util.py
- opengever/ogds/base/sync/ogds_updater.py
- opengever/ogds/base/tests/test_ogds_updater.py
- opengever/ogds/models/group.py
- opengever/ogds/models/user.py
The current implementation always modifies all users and groups regardless if there are any changes.
As this is done in a single transaction, this results in a table lock of the users and groups tables.
If a user tries to login during an OGDS sync, his last login date gets updated but this update has to wait until the lock caused by the OGDS sync is released.
At the end of the OGDS sync a timestamp gets written to each admin unit. If the admin unit is blocked by pending user logins, this results in a deadlock. The deadlock is resolved after a proxy timeout. However the admin unit is not available until the OGDS sync finishes. With multiple admin units involved, this results in an outage of 5 minutes (proxy timeout) per admin unit.
The new approach no longer modifies every user and group …
> Optimize OGDS Sync

- docs/HISTORY.txt
- docs/public/dev-manual/api/linked_workspaces.rst
- opengever/api/add.py
- opengever/api/document.py
- opengever/api/tests/test_document.py
- opengever/api/tests/test_linked_workspaces.py
- opengever/api/workspace.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/configure.zcml
- opengever/workspaceclient/interfaces.py
- opengever/workspaceclient/linked_documents.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/tests/test_client.py
- opengever/workspaceclient/tests/test_linked_documents.py
This links GEVER documents and their copies in Teamraum when they are copied using Teamraum Connect. 
_(This is motivated by later using these links to transfer back copied documents from Teamraum to GEVER as a new version of the original document)._
These links are internally stored in annotations on the documents on both sides, and are serialized in a document GET like so:
**On a GEVER document** (links to multiple TR documents possible):
```json
{
"teamraum_connect_links": {
"gever_document": null,
"workspace_documents": [
{
"UID": "a8519078dc2a4b39bca2ab530b817376",
"UID": "a7ea5e0fb1544a4bb513820210589d55",
}
]
},
"...": "..."
}
```
**On a Teamraum document**:
```json
{
"teamraum_connect_links": {
"gever_document": {
"UID": "cafde44103ae4c73b683321bed7bd054"
},
"workspace_documents": …
```
> Link documents copied via Teamraum Connect

- docs/HISTORY.txt
- opengever/api/linked_workspaces.py
- opengever/api/tests/test_linked_workspaces.py
- opengever/workspaceclient/exceptions.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/tests/test_linked_workspaces.py
This will prevent checked out documents from being copied _to_ a Teamraum, or _copied back_ from Teamraum to GEVER.
The individual requests for the respective documents will be answered with 400 Bad Request, and the document will therefore be flagged as "failed" in the document operation queue  (bottom right) by the frontend.
Jira: https://4teamwork.atlassian.net/browse/CA-1218
> Prevent checked out documents from being copied to or from a teamraum

- docs/HISTORY.txt
- opengever/api/listing_stats.py
- opengever/api/tests/test_listing_stats.py
In order for the frontend to show how many documents are in the trash, it must be possible to query this. Therefore, the default filter "trashed:false" must no longer be used in @listing-stats endpoint.
Jira: https://4teamwork.atlassian.net/browse/NE-60
- API change:
- If breaking:
> No longer exclude trashed documents in @listing-stats endpoint

- docs/HISTORY.txt
- opengever/api/listing.py
- opengever/api/solr_query_service.py
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/opengever.base.pot
- opengever/base/locales/plone.pot
For the search in the frontend there is a new tab for proposals. It should be possible to filter by review state and issuer. 
Therefore the following things have to be changed:
- For Issuer the actor label must be provided
- The review states of proposals must be translated
Jira: https://4teamwork.atlassian.net/browse/NE-211
> Translate proposal review state and tranform issuer label

- docs/HISTORY.txt
- opengever/api/tests/test_linked_workspaces.py
- opengever/workspaceclient/linked_documents.py
- opengever/workspaceclient/tests/test_linked_documents.py
Before this fix, the following could happen:
- A property like `storage.linked_workspace_documents` was accessed on an uninitialized storage, as part of a display operation
- This lead to a regular, non-persisted dict being added to annotations because of the use of `setdefault`
- That dict then got committed as part of the transaction
- Subsequent write operations on the storage then picked up that non-persistent dict to add to it. Those changes then would never be persisted.
The fix therefore makes sure that `storage._link_storage(persistent=False)` never *stores* the empty, non-persistent dict, but instead just _returns_ it.
Jira: https://4teamwork.atlassian.net/browse/CA-1220
> Fix persistence bug in linked documents storage

- docs/HISTORY.txt
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/tests/test_linked_workspaces.py
This is a follow-up to https://github.com/4teamwork/opengever.core/pull/6742. As it had already been reviewed twice, I did not want to add more functionality in that PR, and it also makes it clearer how we decided to treat mails with regard to locking them when copying them to a Workspace. 
I decided to simply ingnore the `lock=True` argument when copying a Mail to a workspace, as it does not make sense to lock an E-mail, which anyway can't be updated when copying the Mail back from the workspace. Raising an Error is not an option IMO, as this is a FolderButton, so the user can select a mix of documents and mails to copy to the Workspace and selects the `lock` flag for all items being copied. It would not make sense to fail for the E-mails just because the user clicked the `lock` …
> Ignore locking mail when making a copy via Teamraum Connect.

- docs/HISTORY.txt
- solr-conf/sync-solr.js
The Processor did not work for atomic commits. This PR fixes the bug.
We want to pop the first element and keep the rest, so shift is the correct method to use here.
Issue: https://4teamwork.atlassian.net/browse/CA-1214
- API change:
- If breaking:
> Fix ScriptUpdateProcessor

- README.rst
We've decided to use an unclamimed identifier for this new thing which makes sure certain fields from a GEVER Solr are also available in a RIS Solr.
- Solr sync is already taken by the (command-line) tool to make sure GEVER and Solr are in sync.
- Replication is already taken for certain deployment styles where Solr/GEVER instances are distributed across multiple servers.
So, `update chain` it is.
> Consistently use name solr update chain.

- docs/HISTORY.txt
- opengever/api/participations.py
- opengever/core/upgrades/20201127160828_correct_to_do_watchers/upgrade.py
- opengever/workspace/activities.py
- opengever/workspace/participation/browser/my_invitations.py
- opengever/workspace/tests/test_activities.py
With https://github.com/4teamwork/opengever.core/pull/5917 we included ToDos in the Gever notification system so that workspace participants get notified about modifications on ToDos. There was a bug in the implementation, so that the new participant would get added to all ToDos instead (https://github.com/4teamwork/opengever.core/blob/d42390cc1380477d774fd1b32b2e75bc72beb808/opengever/workspace/activities.py#L44), also the ones he had no permission to see when he accepted the invitation over the browser view which uses `elevated_privileges` (https://github.com/4teamwork/opengever.core/blob/4a84462c2872b06db0595ed34ac7908cd1682e40/opengever/workspace/participation/browser/my_invitations.py#L222).
The good news is that there was a second error in the implementation so that the newly added …
> fix todo watchers

- docs/HISTORY.txt
- docs/public/dev-manual/api/linked_workspaces.rst
- opengever/api/linked_workspaces.py
- opengever/api/tests/test_linked_workspaces.py
- opengever/testing/test_case.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/locales/de/LC_MESSAGES/opengever.workspaceclient.po
- opengever/workspaceclient/locales/fr/LC_MESSAGES/opengever.workspaceclient.po
- opengever/workspaceclient/locales/opengever.workspaceclient.pot
- opengever/workspaceclient/tests/test_linked_workspaces.py
This adds support for transferring documents from teamraum back to GEVER **as a new version**.
The `@copy-document-from-workspace` endpoint accepts a new flag `as_new_version` (default: False), which will retrieve the document as a new version of the linked document, if possible. If not possible (e.g. if the document wasn't linked, doesn't have a file or is a mail), it will pick to create a _copy_ instead though). The endpoint will return the creation mode it picked as a property `teamraum_connect_retrieval_mode`(`copy` or `version`) in the serialized object in the response.
When retrieving a document as a new version, the original document will be **unlocked** (if locked). When retrieving as a copy, it **won't**.
Jira: https://4teamwork.atlassian.net/browse/CA-1222
- API change:
- New …
> Support transferring documents from workspace back to GEVER as new version.

- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
This PR extends the policy generator with adds a question to add a Usersnap API key to the policy.
Adding a key will automatically enable usersnap on the deployment.
> Add a usersnap-api key question to the policy-generator

- docs/HISTORY.txt
- opengever/core/upgrades/20201127160828_correct_to_do_watchers/upgrade.py
The upgrade step fixing the subscriptions on ToDos was not restricted to the current admin_unit. While it did work correctly because it would end up skipping subscriptions from other admin units, it would also log an unnecessary warning.
For https://4teamwork.atlassian.net/browse/CA-1297
> Only fix subscription on current admin unit.

- README.rst
The setup of a multi-admin deployment for development didn't work with the new frontend. Setting the `cas_url` to empty string will avoid that the frontend tries to login over CAS. 
Note that the frontend will only work for the `fd` admin_unit, because the `rk` is not included in the default apps that the frontend will use for local development.
> Update Readme for setting up a multi-admin deplyoment for development.

- docs/HISTORY.txt
- solr-conf/sync-solr.js
This additional field is required so that PDF documents can be displayed in RIS. The documents are synchronized to the RIS-Solr since PR https://github.com/4teamwork/opengever.core/pull/6576
> Synchronize bumblebee checksum to RIS

- docs/HISTORY.txt
- opengever/inbox/tests/test_zipexport.py
- opengever/task/configure.zcml
- opengever/task/tests/test_overview.py
- opengever/task/tests/test_zipexport.py
- opengever/task/ziprepresentation.py
We don't export tasks that don't contain any documents to prevent creation of empty folders for such tasks.
Aborting for empty tasks has been implemented as a catalog query for documents. This has proven to be the easiest way to hook into existing functionality of [ftw.zipexport](https://github.com/4teamwork/ftw.zipexport/ ) without breaking/changing the whole zipexport behavior.
Jira: https://4teamwork.atlassian.net/browse/CA-1167
> Implement specific task zip representation, no longer export empty tasks.

- docs/HISTORY.txt
- opengever/api/task.py
- opengever/api/tests/test_task.py
- opengever/testing/builders/dx.py
In the frontend we want to show whether a "Standardablauf" is sequential or parallel. Therefore I added the field `sequence_type` to the task serializer.
Jira: https://4teamwork.atlassian.net/browse/NE-314
> Add sequence_type to task serializer

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/activity/browser/settings.py
- opengever/api/notification_settings.py
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20201203113604_add_to_do_feature_flag/registry.xml
- opengever/core/upgrades/20201203113604_add_to_do_feature_flag/upgrade.py
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
- opengever/testing/integration_test_case.py
- opengever/workspace/__init__.py
- opengever/workspace/interfaces.py
- opengever/workspace/tests/test_todo.py
- opengever/workspace/tests/test_workspace_workspace.py
- opengever/workspace/workspace.py
This PR adds a feature flag for todos. This allows us to enable and disable ToDos and ToDo lists. By default, this feature is enabled so that no additional update steps are required in the policies.
With the policy generator the feature can be enabled and disabled.
Jira: https://4teamwork.atlassian.net/browse/NE-163
- API change:
> Add feature flag for todos.

- docs/HISTORY.txt
- opengever/advancedsearch/tests/test_search.py
- opengever/core/upgrades/20200805094934_reindex_searchable_text_to_include_filing_no/upgrade.py
- opengever/dossier/archive.py
- opengever/dossier/filing/advanced_search.py
This is a backport of #6578 to `2019.6-stable`.
I had to drop the new test from this fix when backporting, because the test requires the `SolrIntegrationTestCase`, which wasn't around yet in `2019.6`.
Tests against this branch are still failing though, because the boostrap invocation on Jenkins with `--setuptools-version` would require an updated `bootstrap.py` (and possibly newer versions of `setuptools` and `zc.buildout`), which we don't want to bump for this branch as part of a backport.
I tested the fix locally - I was able to reproduce the issue, the fix + upgrade step worked and fixed it 👍 
Runtime for the upgrade step (as tested locally) is around `8 reindexed dossiers / s`.
Jira: https://4teamwork.atlassian.net/browse/CA-1247
> Backport filing number search fix (#6578)

- docs/HISTORY.txt
- opengever/base/browser/resources/TableRadioWidget.js
Instead of using browser location we use the form action to re-render specific widgets. The browser location does not always expose the add form name, for example when opened via POST from a tabbed view action.
The form action however always points to the correct form and is more reliable.
This fixes a bug with only rendering allowed proposal templates for the chosen committee on a proposal add form, when the form was opened with the "add proposal" action on a document tab in the classic ui.
Jira: https://4teamwork.atlassian.net/browse/CA-1234
> Use form action URL to re-render specific widget.

- docs/HISTORY.txt
- opengever/tabbedview/catalog_source.py
- opengever/tabbedview/tests/test_dossier_listing.py
Until now, the keyword filter did not find dossiers when filtering for keywords containing spaces.
To filter for a keyword that consists of several words, the keyword must be enclosed in quotation marks.
Jira: https://4teamwork.atlassian.net/browse/NE-365
> Fix keyword filter for keywords that contain spaces

- docs/HISTORY.txt
- docs/public/dev-manual/api/content_types.rst
- docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc
- docs/public/dev-manual/api/schemas/opengever.repository.repositoryroot.inc
- docs/public/dev-manual/api/schemas/opengever.workspace.root.inc
- docs/schema-dumps/opengever.repository.repositoryfolder.schema.json
- docs/schema-dumps/opengever.repository.repositoryroot.schema.json
- docs/schema-dumps/opengever.workspace.root.schema.json
- opengever/api/serializer.py
- opengever/api/tests/test_contactfolder.py
- opengever/api/tests/test_repository.py
- opengever/api/tests/test_schema.py
- opengever/api/tests/test_translated_title.py
- opengever/base/behaviors/translated_title.py
- opengever/base/browser/translated_title.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/jsonschema_for_portal_type.py
- opengever/base/schemadump/config.py
- opengever/base/tests/test_translated_title.py
- opengever/bundle/schemas/repofolders.schema.json
- opengever/bundle/schemas/reporoots.schema.json
- opengever/bundle/schemas/workspaceroots.schema.json
With this PR we change the API behavior with translated title fields to appear dynamically according to deployments currently active languages. The following changes are made:
- The fields `title_de` and `title_fr` will only appear in the `@schema` and `@types` endpoints if their corresponding lanugage has been set to active on the plone site.
- The fields `title_de` and `title_fr` will also only be serialized if their corresponding language is active.
- Deserialization (`POST`ing or `PATCH`ing via API) will be a bit more permissive and also accept inactive language fields.
I have attempted to implement the changes in a generic and, if possible, non-intrusive way.
Unfortunately schema serialization in `plone.restapi` [has been implemented in a …
> Only expose translated title fields for active languages in schema and serialization via API.

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/document/browser/download.py
- opengever/document/fileactions.py
- opengever/document/tests/test_download.py
Jira: https://4teamwork.atlassian.net/browse/NE-49
Currently, if another user has checked out a document, the `download_copy` and `attach_to_mail` actions were not shown.
With this PR, the actions will be shown even if the document is checked out by another user. But it have to have at least one version.
If the user who checked out the document downloads the document, the current working copy will be downloaded.
If another user download the document, the latest version will be downloaded.
By default, a newly created document does not have any version. If a user checks out this document and working on it will directly modify the document. That's the reason why we don't provide the download (or attach to mail) action to another user, if there does not exist any version yet.
_Only applicable …
> Allow downloading and sending a document checked out by another user

- docs/HISTORY.txt
- opengever/base/configure.zcml
- opengever/base/handlers.py
- opengever/base/tests/test_favorite.py
- opengever/core/upgrades/20201207113732_clean_up_favorites_for_trashed_and_deleted_objects/upgrade.py
When trashing or deleting an object, the corresponding favorites get deleted by an event handler. This did not work because the session did not get marked as changed and hence the changes were not persisted in the SQL DB. 
Moreover the favorites deletion failed for objects contained in the deleted object: the OGUID of the object removed could not be resolved anymore because its intid had already been removed from the catalog. We fix this by registering the handler earlier (on `ObjectWillBeRemovedEvent` instead of `ObjectRemovedEvent`).
We also add an upgrade step to fix potentially broken favorites for trashed and deleted objects.
For https://4teamwork.atlassian.net/browse/CA-1186
- …
> Fix deletion of favorites when object is removed or trashed.

- docs/HISTORY.txt
- docs/public/dev-manual/api/inbox.rst
- docs/public/dev-manual/api/index.rst
- opengever/api/configure.zcml
- opengever/api/forwarding.py
- opengever/api/tests/test_assign_to_dossier.py
- opengever/base/transition.py
- opengever/inbox/tests/test_api_support.py
- opengever/inbox/transition.py
This PR introduces a new endpoint `@assign-to-dossier` for forwardings.
A forwarding can be assigned to a dossier through the workflow transition: `forwarding-transition-assign-to-dossier`.
Executing this transition will perform several steps:
- creating a new task
- linking the newly created task with the forwarding
- moving the forwarding into the years-folder of the inbox
Just calling the transition through the `@worflow` endpoint would be possible but comes with some disadvantages. The `@workflow` endpoint is a generic endpoint for performing workflow transitions on an object. The UI would not know anything about the newly created task nor about the moved forwarding.
The `@assign-to-dossier` endpoint takes care of it and will return the newly created task as the response.
The old UI …
> Add @assign-to-dossier endpoint for forwardings

- docs/HISTORY.txt
- docs/public/dev-manual/api/tasks.rst
- opengever/api/configure.zcml
- opengever/api/task.py
- opengever/api/tests/test_task.py
Jira: https://4teamwork.atlassian.net/browse/NE-338
This PR extends the task POST endpoint to also respect the `positions` parameter if adding a task to a sequential task.
This was already implemented in the current Add form: https://github.com/4teamwork/opengever.core/blob/master/opengever/task/browser/forms.py#L111, but was forgotten for the API.
- API change:
- If breaking:
> Adding a subtask to a sequential task through the restapi respects the `position` parameter.

- docs/HISTORY.txt
- docs/public/dev-manual/api/listings.rst
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
- opengever/testing/fixtures.py
In order to display the `public_trial` in a document listing, it must be allowed in the listing endpoint.
Jira: https://4teamwork.atlassian.net/browse/NE-147
- API change:
> Add public_trial field to listing endpoint.

- docs/HISTORY.txt
- opengever/ogds/base/__init__.py
- opengever/ogds/base/browser/configure.zcml
- opengever/ogds/base/browser/ldapcontrolpanel.py
- opengever/ogds/base/browser/templates/ldapcontrolpanel.pt
- opengever/ogds/base/sync/ogds_updater.py
- opengever/ogds/base/tests/test_ogds_updater.py
OGDS sync for local groups is needed for teamraum to reflect changes that can be done in various places (e.g. ZMI or import of groups) in OGDS.
By default sync of local groups is only enabled for installations with enabled workspace feature.
It can be executed on any site using the control panel.
JIRA: https://4teamwork.atlassian.net/browse/CA-1332
> Implement OGDS sync for local groups

- opengever/api/tests/test_actions.py
- opengever/document/browser/download.py
- opengever/document/fileactions.py
- opengever/document/tests/test_download.py
Jira: https://4teamwork.atlassian.net/browse/NE-49
This is a follow-up PR of https://github.com/4teamwork/opengever.core/pull/6755
I assumed, that the first version will be created as soon as the user is checking in a document the first time.
But that's not right. There is a file-setter on the document model which is creating an initial version 0 if the file-field is updated the first time. Means, if a user creates a new document, there will be no version at all. If the user checks out the document and saves it with some changes without checking it in, an initial version 0 will be created by the file-setter: https://github.com/4teamwork/opengever.core/blob/master/opengever/document/document.py#L263
I handled the version 0 like there is no version.
This PR updates the implementation of the …
> Download checked out document also respect the init version 0

- opengever/api/forwarding.py
- opengever/api/tests/test_assign_to_dossier.py
Creating a task requires a `responsible` and a `responsible_client`. From the vocabularies, we receive combined values for the responsible field like `fd:username`. Instead of separating this values in the frontend and sending it in separate attributes to the server, we deserialize combined values in the backend and separate it properly: https://github.com/4teamwork/opengever.core/blob/master/opengever/api/task.py#L105
The newly introduced endpoint `@assing-to-dossier` in https://github.com/4teamwork/opengever.core/pull/6767  does not implement this special deserialization of the responsible field.
This PR extends the endpoint to also provide combined values for task responsibles.
Jira: https://4teamwork.atlassian.net/browse/NE-73 …
> @assign-to-dossier endpoint deserializes combined values for the responsible

- docs/HISTORY.txt
- opengever/ech0147/tests/test_import.py
- opengever/ech0147/utils.py
contentType was of type `pyxb.binding.datatypes.token` before, which is not JSON serializable.
https://sentry.4teamwork.ch/organizations/sentry/issues/65198/?project=17
I've not added an upgrade step to fix existing documents because it requires to check all documents which is costly and eCH0147 import is rarely used.
I've fixed the affected system with the following script:
```python
from pyxb.binding.datatypes import token
import transaction
site = app.digs
docs = site.portal_catalog.unrestrictedSearchResults(portal_type='opengever.document.document')
for doc in docs:
obj = doc.getObject()
if obj.file:
if type(obj.file.contentType) == token:
obj.file.contentType = str(obj.file.contentType)
print "Fixed contenType for %s" % doc.getPath()
transaction.commit()
```
JIRA: …
> Fix type of file contentType on eCH0147 import

- docs/HISTORY.txt
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
The `invitation_group_dn` was not part of the policy templates for teamraum deployments. It might be unnecessary for certain setups where the LDAP itself adds newly created users to the correct group (as in SG), but IMO, I'd rather have that in the template and delete it from the created policy when necessary. In general this needs to be set for invitations to work correctly.
For https://4teamwork.atlassian.net/browse/CA-12
> Add invitation_group_dn to teamraum policy template.

- docs/HISTORY.txt
- docs/public/dev-manual/api/globalindex.rst
- opengever/api/globalindex.py
- opengever/api/ogdslistingbase.py
- opengever/api/tests/test_globalindex.py
This provides faceting for OGDS based listings in the same way as Solr based listings do.
Facets can be requested on the `@globalindex` endpoint for a predefined set of columns (issuer, responsible, review_state, task_type).
Required for filtering pending task: https://github.com/4teamwork/gever-ui/pull/1469
Jira: https://4teamwork.atlassian.net/browse/CA-1200
- API change:
> Implement faceting for globalindex endpoint

- docs/HISTORY.txt
- docs/public/dev-manual/api/documents.rst
- opengever/api/configure.zcml
- opengever/api/lock.py
- opengever/api/tests/test_actions.py
- opengever/api/tests/test_lock.py
- opengever/api/tests/test_repository.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20201214150706_add_unlock_action/actions.xml
- opengever/core/upgrades/20201214150706_add_unlock_action/upgrade.py
- opengever/document/fileactions.py
- opengever/document/interfaces.py
- opengever/locking/tests/test_locks.py
Since it was only possible to remove a `STEALABLE LOCK` as creator with the @unlock endpoint until now, the endpoint had to be overwritten. Now a `lock_type` can be specified to determine which lock should be removed. Furthermore all users can remove the `copied_to_workspace` lock, not only the creator.
Furthermore, a lock expansion was added, so that it can be determined in the frontend with which `lock_type` an object is locked, in order to be able to remove this lock afterwards.
Additionally, an `unlock` file action was added to decide when a user can unlock a document.
Refined with @njohner 
Jira: https://4teamwork.atlassian.net/browse/NE-340
_Only applicable should be left and …
> Add lock expansion, override unlock endpoint and add unlock file action

- docs/HISTORY.txt
- opengever/meeting/model/meeting.py
- opengever/meeting/tests/test_meeting.py
Meeting overview did not support Period titles containing unicode characters.
For https://4teamwork.atlassian.net/browse/CA-1359
Sentry: https://sentry.4teamwork.ch/organizations/sentry/issues/70360
> Fix unicode error in meeting overview.

- docs/HISTORY.txt
- opengever/tabbedview/browser/tabs.py
The subject column is not sortable because its values are unordered lists of keywords. As it is not sortable, grouping cannot function correctly either. Currently grouping actually led to an Error, but it anyway does not make sense to allow it.
I did not add a test as this is just a configuration of the table.
For https://4teamwork.atlassian.net/browse/CA-1348 and https://4teamwork.atlassian.net/browse/CA-1349
> Do not allow to group on Subject column.

- docs/HISTORY.txt
- opengever/examplecontent/profiles/default_content/content_creation/01_default_content.json
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/workspaces_content/opengever_content/01-initial-structure.json
- opengever/setup/profiles/default_content/content_creation/01_default_content.json
The workspace root must have the `opengever_workspace_policy` placeful workflow policy .
There's an upgrade step that enables it for existing installations, but currently it's not activated in default content for new setups.
https://4teamwork.atlassian.net/browse/CA-1358
> Setup placeful workflow for workspace root in default content

- docs/HISTORY.txt
- docs/public/dev-manual/api/config.rst
- opengever/api/tests/test_config.py
- opengever/base/configuration.py
- opengever/base/tests/test_configuration_adapter.py
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20201216155007_add_workspace_meeting_feature_flag/registry.xml
- opengever/core/upgrades/20201216155007_add_workspace_meeting_feature_flag/upgrade.py
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
- opengever/testing/integration_test_case.py
- opengever/workspace/__init__.py
- opengever/workspace/interfaces.py
- opengever/workspace/tests/test_workspace_meeting.py
- opengever/workspace/tests/test_workspace_workspace.py
- opengever/workspace/workspace.py
This PR adds a feature flag for workspace meetings. This allows us to enable and disable WorkspaceMeetings. By default, this feature is enabled so that no additional update steps are required in the policies.
With the policy generator the feature can be enabled and disabled.
Jira: https://4teamwork.atlassian.net/browse/NE-290
- API change:
> Add feature flag for workspace meetings.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/tests/test_dossier_participations.py
Participations should not be able to be modified if a dossier cannot be modified.
Jira: https://4teamwork.atlassian.net/browse/NE-219
> Protect dossier participations endpoints with modify permission.

- docs/HISTORY.txt
- opengever/document/fileactions.py
- opengever/document/tests/test_fileactions.py
- opengever/wopi/browser/edit.py
- opengever/wopi/tests/test_edit.py
Until now, a document was editable with Office Online even if it was locked. The office_online_edit action was also available. This is no longer the case with this pr.
Jira: https://4teamwork.atlassian.net/browse/NE-446
> Prevent attempts to edit locked documents in Office Online.

- docs/HISTORY.txt
- opengever/base/configure.zcml
- opengever/base/handlers.py
- opengever/base/indexes.py
- opengever/base/ordering.py
- opengever/base/overrides.zcml
- opengever/base/tests/test_contents_reordered_handling.py
- opengever/base/tests/test_indexers.py
- opengever/base/tests/test_solr.py
- opengever/core/upgrades/20201230152803_add_and_index_get_obj_position_in_parent_solr_field/upgrade.py
- opengever/tasktemplates/browser/tasktemplates.py
- opengever/tasktemplates/tests/test_tasktemplatefolder.py
- solr-conf/managed-schema
Jira: https://4teamwork.atlassian.net/browse/NE-283
Currently, we don't provide a solr-index for the position of an object within its parent for manually sorted content. This leads to workarounds i.e. for ordering tasktemplates (https://github.com/4teamwork/opengever.core/blob/master/opengever/tasktemplates/browser/tasktemplates.py#L72) or performance issues i.e. for displaying todos and todolists (https://github.com/4teamwork/gever-ui/blob/master/src/components/workspace/ToDoTab.vue#L144).
This PR implements the index `getObjPositionInParent` for solr. The indexer itself will only index the position for some whitelisted types which are `Todos`, `TodoLists` and `Tasktemplates`.
If the `ReorderedEvent` is triggered on an object, all its children will be reindexed. Even here, we do this …
> Implement solr indexer getObjPositionInParent for tasktemplates, todos and todolists

- docs/HISTORY.txt
- opengever/dossier/configure.zcml
- opengever/dossier/handlers.py
- opengever/dossier/tests/test_touched.py
We do not want to update the touched date of the children of an object that is moved. This is both wrong and leads to errors in the indexing, probably because `IObjectMovedEvent` gets dispatched to all children and in the touched handler we propagate the update of touched to all parents...
For https://4teamwork.atlassian.net/browse/CA-1395
> Do not update touched date of children when moving an object.

- docs/HISTORY.txt
- opengever/propertysheets/__init__.py
- opengever/propertysheets/configure.zcml
- opengever/propertysheets/definition.py
- opengever/propertysheets/exceptions.py
- opengever/propertysheets/schemapolicy.py
- opengever/propertysheets/storage.py
- opengever/propertysheets/tests/test_definition.py
- opengever/propertysheets/tests/test_storage.py
With this PR we implement the storage for "property sheets" in plone-site annotations and a property sheet definition helper class. Property sheets hold a custom schema definition with custom fields, and optional assignments by which they can be queried.
The initial implementation is written in a basic and simple way, so that initially it will only be usable by a `Manager`. 
Incremental edits for schemas are not yet supported, e.g. field removal or reordering. We reuse `plone.schemaeditor` functionality to provide schema editing, so these features can be amended later should they be desired.
The following features will be added as of this PR:
- Functionality to define property sheets and their schemas 
- For the schemas only a subset of all potential fields is currently supported, namely: …
> Add property sheet schema storage.

- docs/HISTORY.txt
- opengever/base/__init__.py
- opengever/base/language.py
- opengever/examplecontent/profiles/default/portal_languages.xml
These is the minimal set of changes to **enable picking English as a UI language** (in the classic UI):
- Add it as a supported language in the portal language too (makes it available for selection)
- Set its `native` name (required to provide the display title used in the [personal bar viewlet](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/viewlets/personal_bar.py#L37))
- Add it to `SIMPLE_TO_COMBINED_MAPPING` (required for robust HTTP language negotiation)
> Add 'en-us' as supported language in example content.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/propertysheets.rst
- opengever/api/tests/test_vocabularies.py
- opengever/propertysheets/api/configure.zcml
- opengever/propertysheets/api/delete.py
- opengever/propertysheets/api/get.py
- opengever/propertysheets/api/post.py
- opengever/propertysheets/assignment.py
- opengever/propertysheets/configure.zcml
- opengever/propertysheets/definition.py
- opengever/propertysheets/schema.py
- opengever/propertysheets/storage.py
- opengever/propertysheets/tests/test_assignment.py
- opengever/propertysheets/tests/test_definition.py
- opengever/propertysheets/tests/test_schema.py
- opengever/propertysheets/tests/test_schema_definition_delete.py
- opengever/propertysheets/tests/test_schema_definition_get.py
- opengever/propertysheets/tests/test_schema_definition_post.py
- opengever/propertysheets/tests/test_storage.py
With this PR we add REST-API endpoints to make use of the property sheet storage that was added in https://github.com/4teamwork/opengever.core/pull/6795.
The initial implementation only allows `POST` and `DELETE` for a `Manager`. `GET` is available for anyone with the `View` permission. Incremental edits for schemas are not yet supported, e.g. field removal or reordering.
Property sheets support being represented as JSON Schema as of this Pull-Request. The schema of a single sheet can be retrieved, including the schemas in the `@schema` endpoints for existing types will follow in future Pull-Request when we implement property sheet/custom field support for certain content-types.
We add a new service endpoints `@propertysheets` which is available on the plone-site only. It can be used to …
> Add REST-API endpoints for property sheet schema storage.

- opengever/activity/locales/en/LC_MESSAGES/opengever.activity.po
- opengever/activity/tests/test_plone_center.py
- opengever/api/tests/test_notification_settings.py
Clean up English og.activity translations.
The purpose of this is to clean up existing English translations, and fill in missing ones with the following aspects in mind:
- Some very specific modules (SPV, Disposition, ...) with lots of domain specific terminology will have to be looked at more closely at a later point, and translations would need to be changed (if necessary) as a whole, in context, and based on some research.
For these I will fix obvious, glaring mistakes, but otherwise won't substantially change any core terms.
- I'll leave some `MARKER`s for things that strike me as odd, need to be double checked again later, or otherwise might need revisiting in order to not forget them, but be able to quickly make a decision and move on.
- Title case vs sentence case: It's a [whole …
> Clean up English og.activity translations.

- docs/HISTORY.txt
- opengever/meeting/tests/test_meeting_zipexport.py
- opengever/meeting/zipexport.py
Grimlock wants the agenda item list document under the `documents` key and in a list and not as it is now under the `agenda_item_list` key (see @fguyer 's comment: https://4teamwork.atlassian.net/browse/CA-149?focusedCommentId=14380). This key is already in use in Grimlock for zips generated by RIS, but it's a new key in Gever, so displaying it should work in Grimlock without needing any changes.
Note that Grimlock expects items in the `documents` section to have a `title`, so we also need to add the title of the agenda item list in the Zip file.
Note that I tested the export and import in Grimlock with the new format.
For https://4teamwork.atlassian.net/browse/CA-1401
> Change key for agenda item list document to "documents" in zip export.

- opengever/base/tests/test_default_values_for_types.py
- opengever/contact/locales/en/LC_MESSAGES/opengever.contact.po
- opengever/contact/tests/test_byline.py
- opengever/contact/tests/test_contact.py
- opengever/contact/tests/test_contactfolder.py
- opengever/contact/tests/test_mail_addresses_view.py
- opengever/contact/tests/test_organization_listing.py
- opengever/contact/tests/test_participation.py
- opengever/contact/tests/test_person.py
- opengever/contact/tests/test_person_listing.py
- opengever/contact/tests/test_team_listing.py
Clean up English `og.contact` translations.
The unusual plural form `Persons` (instead of "People") is used (at least) for a tab title that sits right next to `Organizations`.
https://www.grammarly.com/blog/persons-people-peoples/ says:
> [...] nowadays, the plural persons is only considered correct in legal contexts and, occasionally, *when deliberately referring to humans individually rather than collectively*.
I think that applies here - we're not referring to a crowd _(of people)_, but individual person records.
For overall comments on the process, please see PR #6806
> Clean up English og.contact translations.

- opengever/locking/locales/en/LC_MESSAGES/opengever.locking.po
Clean up English `og.locking` translations.
> Clean up English og.locking translations.

- opengever/api/tests/test_listing.py
- opengever/base/tests/test_ploneform_macros.py
- opengever/base/tests/test_relations.py
- opengever/disposition/tests/test_excel_export.py
- opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/tests/test_activate.py
- opengever/dossier/tests/test_archiver.py
- opengever/dossier/tests/test_base.py
- opengever/dossier/tests/test_deactivate.py
- opengever/dossier/tests/test_dossier.py
- opengever/dossier/tests/test_dossier_byline.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_move_items.py
- opengever/dossier/tests/test_overview.py
- opengever/dossier/tests/test_participation.py
- opengever/dossier/tests/test_protect_dossier.py
- opengever/dossier/tests/test_reactivate.py
- opengever/dossier/tests/test_redirect_to_maindossier.py
- opengever/dossier/tests/test_reporter.py
- opengever/dossier/tests/test_resolve.py
- opengever/dossier/tests/test_templatefolder.py
- opengever/dossier/tests/test_validators.py
- opengever/meeting/tests/test_move_proposal_items.py
- opengever/oneoffixx/tests/test_oneoffixx.py
- opengever/private/tests/test_dossier.py
- opengever/sharing/tests/test_blocked_local_roles_listing.py
Clean up English `og.dossier` translations.
There's a few messages in `opengever.dossier.po` around resolving and (re)activating dossiers that are quite clunky, but are used in **REST API responses** (error messages for workflow transitions). Found that out the hard way (already changed them, got weird test failures 😭 ).
I aborted those changes and left them untouched, and instead added a cautionary marker. We certainly don't want to push breaking API changes when it's "just" translations that are supposed to be updated.
The second commit is purely casing changes. From "magic eight ball casing" to "sentence casing". Should make it a bit easier to review having those separately.
> Clean up English og.dossier translations.

- opengever/globalindex/locales/en/LC_MESSAGES/opengever.globalindex.po
- opengever/globalindex/tests/test_reporter.py
Clean up English `og.globalindex` translations.
> Clean up English og.globalindex translations.

- opengever/portlets/tree/locales/en/LC_MESSAGES/opengever.portlets.tree.po
Clean up English `og.portlets.tree` translations.
> Clean up English og.portlets.tree translations.

- opengever/webactions/locales/en/LC_MESSAGES/opengever.webactions.po
- opengever/webactions/tests/test_manage_webactions_view.py
Clean up English `og.webactions` translations.
> Clean up English og.webactions translations.

- opengever/inbox/locales/en/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/tests/test_inbox_container.py
Clean up English `og.inbox` translations.
> Clean up English `og.inbox` translations.

- docs/HISTORY.txt
- opengever/base/source.py
- opengever/core/tests/test_relations.py
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/tests/test_todo.py
- opengever/workspace/todo.py
ToDo now has a `relatedItems` field that can be used to refer to existing documents in the workspace.
Jira: https://4teamwork.atlassian.net/browse/NE-61
> Add relatedItems field to todo

- opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
Clean up English `og.workspace` translations.
> Clean up English og.workspace translations.

- opengever/locking/tests/test_locks.py
- opengever/private/tests/test_dossier.py
- opengever/trash/locales/en/LC_MESSAGES/opengever.trash.po
- opengever/trash/tests/test_remove.py
- opengever/trash/tests/test_remove_conditions.py
- opengever/trash/tests/test_trash.py
Clean up English `og.trash` translations.
> Clean up English og.trash translations.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/propertysheets.rst
- opengever/base/schemadump/config.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/core/profiles/default/types/ftw.mail.mail.xml
- opengever/core/profiles/default/types/opengever.document.document.xml
- opengever/core/upgrades/20210113175519_enable_custom_properties_for_documents_mails/types/ftw.mail.mail.xml
- opengever/core/upgrades/20210113175519_enable_custom_properties_for_documents_mails/types/opengever.document.document.xml
- opengever/core/upgrades/20210113175519_enable_custom_properties_for_documents_mails/upgrade.py
- opengever/document/behaviors/customproperties.py
- opengever/document/configure.zcml
- opengever/propertysheets/annotation.py
- opengever/propertysheets/assignment.py
- opengever/propertysheets/definition.py
- opengever/propertysheets/exceptions.py
- opengever/propertysheets/field.py
- opengever/propertysheets/storage.py
- opengever/propertysheets/tests/test_annotation.py
- opengever/propertysheets/tests/test_assignment.py
- opengever/propertysheets/tests/test_definition.py
- opengever/propertysheets/tests/test_definition_validate.py
- opengever/propertysheets/tests/test_document_custom_properties.py
- opengever/propertysheets/tests/test_field.py
- opengever/propertysheets/tests/test_mail_custom_properties.py
- opengever/propertysheets/tests/test_schema_definition_delete.py
- opengever/propertysheets/tests/test_schema_definition_get.py
- opengever/propertysheets/tests/test_schema_definition_post.py
- opengever/testing/builders/__init__.py
- opengever/testing/builders/propertysheets.py
With this PR we introduce a `Behavior` enabling custom properties for content. We activate the behavior for document and mail content types. It is based on functionality introduced in earlier Pull-Requests https://github.com/4teamwork/opengever.core/pull/6795 and https://github.com/4teamwork/opengever.core/pull/6800.
Jira: https://4teamwork.atlassian.net/browse/CA-1284
With this PR the following concepts/terms are introduced:
- `Assignment Slot`: A content type defines assignment slots. A property sheet can be assigned to such an assignment slot. Currently there is one slot for each document type. If a document type is selected and a sheet is registered for its slot, the sheets schema is enforced/validated.
- `Custom Property`: The actual data stored on content and validated against the …
> Activate custom properties for documents/mails in API (de-)serialization.

- opengever/latex/locales/en/LC_MESSAGES/opengever.latex.po
- opengever/latex/tests/test_listing.py
Clean up English `og.latex` translations.
> Clean up English og.latex translations.

- opengever/api/tests/test_linked_workspaces.py
- opengever/workspaceclient/locales/en/LC_MESSAGES/opengever.workspaceclient.po
- opengever/workspaceclient/tests/test_linked_workspaces.py
Clean up English `og.workspaceclient` translations.
> Clean up English og.workspaceclient translations.

- opengever/repository/locales/en/LC_MESSAGES/opengever.repository.po
- opengever/repository/tests/test_deletion.py
- opengever/repository/tests/test_reference_behavior.py
- opengever/repository/tests/test_reference_prefix_manager.py
- opengever/repository/tests/test_repositoryfolder.py
- opengever/repository/tests/test_repositoryfolder_tabs.py
- opengever/repository/tests/test_subscribers.py
Clean up English `og.repository` translations.
I left some translations untouched because they're used in Excel export/import.
> Clean up English og.repository translations.

- opengever/ech0147/locales/en/LC_MESSAGES/opengever.ech0147.po
- opengever/ech0147/tests/test_import.py
Clean up English `og.ech0147` translations.
> Clean up English og.ech0147 translations.

- docs/HISTORY.txt
- opengever/tabbedview/browser/bumblebee_gallery.py
- opengever/tabbedview/tests/test_bumblebee_gallery.py
We need to configure the current page in the table source as Solr only fetches the requested batch. Before with portal catalog we were able to access all results.
JIRA: https://4teamwork.atlassian.net/browse/CA-1160
> Fix loading next batch in gallery view

- opengever/api/solr_query_service.py
This is required to no longer expose all users by facets like creator or responsible.
> Fix: do no longer expose facet values for zero-count values.

- opengever/workspace/browser/configure.zcml
- opengever/workspace/browser/registration.py
- opengever/workspace/tests/test_self_registration.py
Add view to handle self registration.
Creates the user in OGDS and redirects to the next URL provided in the query string or to the site root.
> OGDS self registration

- docs/HISTORY.txt
- opengever/meeting/model/query.py
- opengever/meeting/tests/test_committee.py
With this PR we fix deactivating committees with canceled meetings inside.
The query used in the guard to detect if the committee can be deactivated did not consider canceled meetings.
Jira: https://4teamwork.atlassian.net/browse/CA-1397
> Fix deactivating committees with canceled meeting.

- docs/HISTORY.txt
- opengever/base/tests/test_translated_title.py
- opengever/private/browser/configure.zcml
- opengever/private/tests/test_root.py
- opengever/workspace/browser/configure.zcml
- opengever/workspace/browser/forms.py
- opengever/workspace/tests/test_workspace_root.py
Some of the tests for the translated titles were not testing anything. Indeed they were asserting equality between empty lists, probably since we started using combined language codes like 'de-ch'.
We also improve the tests by really checking that translated title fields are only shown for the active languages both in the Add and the Edit forms. This led to discovery that both `WorkspaceRoot` and `PrivateRoot` were not handling the translated fields correctly. I therefore also fix this with this PR.
For https://4teamwork.atlassian.net/browse/CA-1040
> Respect active languages languages in WorkspaceRoot and PrivateRoot forms.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/tasks.rst
- opengever/api/tasktree.py
- opengever/api/tests/test_tasktree.py
- opengever/base/indexes.py
- opengever/base/tests/test_indexers.py
- opengever/core/upgrades/20210119134941_index_get_obj_position_in_parent_solr_field_for_tasks/upgrade.py
- opengever/task/task.py
In the new frontend, it should be possible to create new subtasks in a sequential process between the subtasks. Therefore, each subtask must know whether new subtasks can be added to the main task.
- To decide whether a subtask can be added at the end, the field `is_task_addable_in_main_task` is required.
- To decide whether a subtask can be added before another subtask, the field `is_task_addable_before` is required.
- Until now, the @tasktree endpoint returned the task sorted by creation date. Since this means that those created later do not appear in the correct position for sequential tasks, they are now sorted according to getObjPositionInParent for sequential tasks. This first had to be indexed.
Jira: https://4teamwork.atlassian.net/browse/NE-315
_Everything has to be done/checked. …
> Add is_task_addable_in_main_task and is_task_addable_before attributes to @tasktree endpoint, sort on getObjPositionInParent

- docs/HISTORY.txt
- opengever/activity/tests/test_mail.py
- opengever/task/activities.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/en/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/tests/test_activities.py
We add the list of informed principals to the description of the `TaskAddedActivity`.
I also decided to align the labels to the top of the cells, which makes it much more readable IMHO. 
The screenshot below shows the E-mail for a created Task with a long title, description and several informed principals:
For https://4teamwork.atlassian.net/browse/CA-1227
> List informed principals in TaskAddedActivity description.

- opengever/api/tests/test_vocabularies.py
- opengever/workspace/configure.zcml
- opengever/workspace/tests/test_workspace_meeting.py
- opengever/workspace/utils.py
- opengever/workspace/vocabularies.py
- opengever/workspace/workspace_meeting.py
Because we do not expect a lot of workspace users, we use a vocabulary instead of a query-source for the possible meeting participants.
This allows us to instantly display all possible users in a list in the frontend for selecting participants.
> Use a vocabulary for an instant users-list in the frontend for workspace meetings

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/notifications.rst
- opengever/api/configure.zcml
- opengever/api/notifications.py
- opengever/api/tests/test_notifications.py
We want to be able to mark all notifications as read in the new frontend. For this purpose, the POST method for the @notifications endpoint is implemented. Specified by @deiferni 
Jira: https://4teamwork.atlassian.net/browse/NE-185
- API change:
> Implement POST @notifications endpoint to mark notifications as read.

- docs/HISTORY.txt
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
This splits usersnap settings into separate settings for whether it's enabled at all (boolean, default `True`) and the API key, and prefills the default for the API key from a JSON dotfile on the local machine if present.
The dotfile is looked for in `~/.opengever/policytemplate.json` and expected to have a structure as follows:
```json
{
"usersnap_api_keys": {
"gever": "87....",
"teamraum": "fe...."
}
}
```
Jira: https://4teamwork.atlassian.net/browse/CA-1245
> Enable Usersnap by default in SaaS policy template

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/notifications.rst
- opengever/activity/center.py
- opengever/api/notifications.py
- opengever/api/tests/test_notifications.py
In the new frontend, all notifications returned by the @notifications endpoint are displayed as badge notifications. This meant that notifications that were not badge notifications were also displayed.
With the changes in this PR, the @notifications endpoint only returns badge notifications.
It would also have been possible to introduce an is_badge field and filter by it in the frontend, but I think the chosen method is better, as it gives the backend control over which notifications are displayed in the frontend.
Jira: https://4teamwork.atlassian.net/browse/NE-378
- API change:
- If breaking:
> Return only badge notifications in @notifications endpoint.

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/browser/folder_buttons_availability.py
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20210126165317_update_create_proposal_action/actions.xml
- opengever/core/upgrades/20210126165317_update_create_proposal_action/upgrade.py
- opengever/repository/tests/test_repositoryfolder_tabs.py
Until now, the `create_proposal` action has appeared on various contents. But the action should only appear on dossiers.
Jira: https://4teamwork.atlassian.net/browse/NE-313
> Only show create_proposal action on dossiers.

- opengever/workspace/browser/meeting_pdf.py
The JSONField does not provide a default value. So there is potentially a `None` value coming from context.agenda_items if the field have not been initialized yet. We have to take care of this.
> Fix meeting pdf generation if there are no agenda_items.

- docs/HISTORY.txt
- opengever/base/tests/test_indexers.py
- opengever/base/tests/test_solr.py
- opengever/core/upgrades/20210128112320_index_is_folderish_solr_index/upgrade.py
- solr-conf/managed-schema
This PR adds the plone `is_folderish` index to the solr.
Jira: https://4teamwork.atlassian.net/browse/NE-281
We reuse the already existing indexer from plone which checks the `isPrincipiaFolderish`, as well as the `INonStructuralFolder` to decide if a content is folderish or not.
See https://github.com/plone/Products.CMFPlone/blob/4.3.18/Products/CMFPlone/CatalogTool.py#L235 for more information about the plone implementation.
⌛ Estimated Time to reindex:
- 80'000: 2 min
- 1'000'000: 25 min
- API change:
- If breaking:
- Change in schema …
> Add a new solr-index 'is_folderish'.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/listings.rst
- opengever/api/dossier.py
- opengever/api/listing.py
- opengever/api/repositoryfolder.py
- opengever/api/solr_query_service.py
- opengever/api/tests/test_dossier.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_serializer.py
- opengever/core/upgrades/20210128083955_index_blocked_local_roles_in_solr_for_repository_folders_and_dossiers/upgrade.py
- solr-conf/managed-schema
- Index the field `blocked_local_roles` for dossiers and repofolders in Solr. Indexers for the types already exist, as the index is also in the catalog
- Allow `blocked_local_roles` field in `@listing` endpoint
- Add `blocked_local_roles` to dossier and repofolder serialization
- Allow to filter for a boolean term with `filters.<name>:record:boolean`, until now, such a query threw an exception
Jira: https://4teamwork.atlassian.net/browse/NE-275
- API change:
> Add blocked_local_roles field in serialization of dossiers and repofolders, index field in solr

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- opengever/api/linked_workspaces.py
- opengever/api/tests/test_actions.py
- opengever/api/tests/test_linked_workspaces.py
- opengever/base/browser/folder_buttons_availability.py
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/en/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20210129083214_add_link_to_workspace_action/actions.xml
- opengever/core/upgrades/20210129083214_add_link_to_workspace_action/upgrade.py
- opengever/workspaceclient/tests/__init__.py
Until now, it was decided in the frontend when a dossier could be linked to a workspace. This also made it possible to link a dossier to a workspace when the dossier was already closed. Now there is an action.
Jira: https://4teamwork.atlassian.net/browse/NE-522
- API change:
- If breaking:
> Add link_to_workspace folder action, protect @create-linked-workspaces and @link-to-workspace endpoints

- docs/HISTORY.txt
- docs/public/dev-manual/api/propertysheets.rst
- opengever/document/behaviors/customproperties.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/en/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/mail/browser/default_view.py
- opengever/mail/browser/edit.py
- opengever/propertysheets/api/post.py
- opengever/propertysheets/configure.zcml
- opengever/propertysheets/definition.py
- opengever/propertysheets/field.py
- opengever/propertysheets/form.py
- opengever/propertysheets/locales/de/LC_MESSAGES/opengever.propertysheets.po
- opengever/propertysheets/locales/en/LC_MESSAGES/opengever.propertysheets.po
- opengever/propertysheets/locales/fr/LC_MESSAGES/opengever.propertysheets.po
- opengever/propertysheets/locales/opengever.propertysheets.pot
- opengever/propertysheets/storage.py
- opengever/propertysheets/templates/propertysheet.pt
- opengever/propertysheets/templates/propertysheet_display.pt
- opengever/propertysheets/tests/test_document_default_view.py
- opengever/propertysheets/tests/test_document_forms.py
- opengever/propertysheets/tests/test_mail_default_view.py
- opengever/propertysheets/tests/test_mail_forms.py
- opengever/propertysheets/tests/test_schema_definition_post.py
- opengever/propertysheets/tests/test_storage.py
- opengever/propertysheets/tests/test_widget.py
- opengever/propertysheets/widgets.py
With this PR we add support for custom properties in the classic UI. Custom properties have previously been enabled for mails and documents via API in https://github.com/4teamwork/opengever.core/pull/6823, but so far they were not visible in any way in the classic UI. The properties are shown/rendered as follows:
- when no property sheets are defined, no custom property forms/fieldsets are show
- when propety sheets are available in the plone site but none is active based on the current value of `document_type`, the fieldsets are rendered empty <img width="730" alt="Screenshot 2021-01-28 at 10 53 39" src="https://user-images.githubusercontent.com/736583/106120802-1d816380-6157-11eb-85ea-0de9fb6a839d.png">
- when property sheets are available and there is an active sheet, fields are …
> Implement support for custom properties in the classic UI.

- docs/HISTORY.txt
- solr-conf/sync-solr.js
This is required so that RIS can do subsequent API request to a path.
RIS provides a "global search" where users can search in the RIS metadata and GEVER documents. The search is handled by the "RIS-Solr", and documents are synced into this Solr by GEVER with the update chain (#6576).
We must now display the `history` of the documents that are on display in the search result - so an API request to GEVER based on the information available in the Solr index must be made.
Together with @deiferni we evaluated several options and simply passing the path to the RIS solr seemed the least painful one (rejected alternatives: store the oguid, add an api view to resolve an element by the UID). RIS knows the GEVER base URL, and the `path` attribute is already stored for RIS-elements in the solr.
> Synchronize the path to the RIS-Solr

- opengever/propertysheets/annotation.py
- opengever/propertysheets/tests/test_annotation.py
- opengever/propertysheets/tests/test_transporter.py
- opengever/propertysheets/tests/test_widget.py
- opengever/propertysheets/widgets.py
Fix prefilling values of an old property sheet when it becomes active again and loads previously stored values. Improve tests so they cover two possibilities of partial and complete property sheets.
Jira: https://4teamwork.atlassian.net/browse/CA-1284
> Fix prefilling widgets when active sheet changes.

- versions.cfg
The package six is pinned to 1.11.0 by plone pinnings, ftw.builder however requires at least 1.12.0. I have double-checked the six changelog and have not found anything preventing us from going to the most recent release.
Without this change policy tests against current master fail with the following version constraint error:
```
Version and requirements information containing six:
[versions] constraint on six: 1.11.0
Requirement of zope.testrunner==4.8.1: six
Requirement of ftw.builder: six>=1.12.0
Requirement of z3c.form: six
Requirement of requests_mock: six
Requirement of sqlalchemy-i18n: six>=1.4.1
Requirement of plone.protect>=3.0.15: six
Requirement of plone.api>=1.4.11: six
Requirement of mr.bob: six>=1.2.0
Requirement of docxcompose>=1.0.0a17: six
Requirement of cryptography: …
```
> Bump six to most recent version.

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/session.py
- opengever/base/tests/test_session_cookie.py
This is best practice in terms of security.
With `SameSite=Lax` the cookie is only sent if the user is navigating to the site (following a link or submitting a form with GET method). The cookie is not sent when loading images, AJAX requests, Iframes and forms with POST method.
See also:
https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/501907630/Sicherheitsrichtlinien+f+r+Webanwendungen#4.-Restriktive-Cookies
> Set SameSite=Lax flag for session authentication cookie

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/documents.rst
- opengever/api/configure.zcml
- opengever/api/save_document_as_pdf.py
- opengever/api/tests/test_save_document_as_pdf.py
- opengever/document/browser/save_pdf_document_under.py
- opengever/document/forms.py
- opengever/document/tests/test_save_pdf_under.py
- Only allow to save a document as pdf if document isn't checked out.  Until now, checked-out documents could also be saved as PDFs.This resulted in the fact that when saving a document, the last version of the document was saved as pdf, but when checking whether the document could be converted, the working copy was used. This could lead to errors.
- New endpoint `@save-document-as-pdf`. In order to be able to offer this function in the new frontend, a new endpoint is needed. For this, some functionalities had to be moved to the global scope in order to reuse them in the endpoint.
Jira: https://4teamwork.atlassian.net/browse/NE-352
_Only applicable should be left and …
> New API endpoint @save-document-as-pdf

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/propertysheets.rst
- opengever/propertysheets/configure.zcml
- opengever/propertysheets/definition.py
- opengever/propertysheets/deserializer.py
- opengever/propertysheets/serializer.py
- opengever/propertysheets/tests/test_definition.py
- opengever/propertysheets/tests/test_deserializer.py
- opengever/propertysheets/tests/test_document_custom_properties.py
- opengever/propertysheets/tests/test_field.py
- opengever/propertysheets/tests/test_mail_forms.py
- opengever/propertysheets/tests/test_schema.py
- opengever/propertysheets/tests/test_schema_definition_post.py
- opengever/propertysheets/tests/test_serializer.py
- opengever/propertysheets/tests/test_widget.py
This PR fixes some issues that surfaced due to `Choice` fields not being initialized correctly and thus skipping validation.
- Choice fields have a special condition in their validate method, skipping validation during field initialization https://github.com/zopefoundation/zope.schema/blob/bdc8935158e287549e671ee14a6f17174b9c6aa7/src/zope/schema/_field.py#L486-L488
- Our version of `plone.supermodel` has a bug which never unsets the value https://github.com/plone/plone.supermodel/blob/20812f8162ac549bad6898047c53f8dc8e3d1780/plone/supermodel/exportimport.py#L164, this is only fixed in https://github.com/plone/plone.supermodel/pull/12
We also change how `Choice` field values are represented in the API. Choice fields should be serialized and deserialized consistently with vocabulary based …
> Fix custom property choice field (de-)serialization.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/tests/test_config.py
The `@config`-Endpint exposes an attribute called `is_admin_menu_visible` which was introduced for the GEVER-UI to indicate, if the management-area in the frontend should be visible or not. Since the introduction of this attribute, the frontend has changed and is now providing a management-area for every gever user, not only for admins. The frontend decides depending on attributes value, which cards should be shown in the management area. In addition, it protects special management routes with the value of this attribute.
In general, the frontend just needs to know if the current user is an admin or not. So we rename this attribute in the `@config` endpoint to make it semantically correct.
Slack-Discussion: https://4teamwork.slack.com/archives/C01BHEGBVU1/p1613382646011400?thread_ts=161338 …
> Rename the attribute 'is_admin_menu_visible' from the @config endpoint to 'is_admin'.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/config.rst
- opengever/api/config.py
- opengever/api/tests/test_config.py
This PR introduces a new `@config` attribute: `is_inbox_user` which is required for the frontend to decide if inbox specific dashboard cards should be visible for the current user or not.
The condition for the `is_inbox_user` is taken from the old implementation: https://github.com/4teamwork/opengever.core/blob/ffe96663f855bcf81f7359b8817827f4bf9918a1/opengever/tabbedview/browser/personal_overview.py#L140
I think it makes no sense to refactor the old implementation to a reusable function. So I just reimplemented the required part directly in the `@config` endpoint. The decision who can see the tabs/cards is made in the frontend based on the newly `is_inbox_user` and `is_admin`(https://github.com/4teamwork/opengever.core/pull/6898)
Slack-Discussion: …
> Add 'is_inbox_user' attribute to the @config endpoint

- docs/HISTORY.txt
- opengever/document/browser/overview.py
- opengever/document/tests/test_overview.py
The document overview for documents that are inside an inbox got broken, because the [code for the `show_edit_archival_file_link()`](https://github.com/4teamwork/opengever.core/blob/ad3f7ac1452cc21ae266a5c08100055b149c3f83/opengever/document/browser/overview.py#L352-L361) doesn't deal with the fact that `get_parent_dossier()` might return `None`.
This case is never an issue for regular users because they lack the necessary permissions and the previous condition already terminates the method, but for managers it broke the overview for documents in inboxes.
Fixes https://sentry.4teamwork.ch/organizations/sentry/issues/71907/
> Fix inbox document overview for managers 

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
For some reason we were setting the APPS_ENDPOINT_URL only for teamraum deployments. I think all new deployments will have the Gever-UI and need the APPS_ENDPOINT_URL to be set.
Moreover we now setup new deployments (on new servers) with several tools installed as services, notably sablon, msgconvert and pdflatex. I've now added a question that will set the URLs for these services correctly in sich cases.
For https://4teamwork.atlassian.net/browse/CA-984
> Update policy templates

- opengever/base/configure.zcml
It seems this was added accidentally. In general we don't want to allow any cross origin requests.
> Remove CORS policy

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/configure.zcml.bob
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/ldap/ldap_plugin.xml.bob
As we now always use ianus for new deployments, there is no reason to use the `casauth` policy of the old portal in the policy templates. Also Authentication and resetting credentials should not happen over the ldap plugin. Authentication anyway gets deactivated during setup (https://github.com/4teamwork/opengever.core/blob/master/opengever/setup/deploy.py#L138-L141)
For https://4teamwork.atlassian.net/browse/CA-984
> Adapt policy templates for ianus portal.

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/copy_.py
- opengever/api/tests/test_copy_paste.py
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/en/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base-manual.pot
- opengever/base/locales/opengever.base.pot
Does basically the same as in `PasteClipboardView`:
- Renames the id of copied objects
- Prepends the title of the top level object with "Copy of" if it was copied to the same location
- Sets the creator to the user making the copy
- Makes sure that Doc Properties are updated only after renaming
The current implementation of renaming an object is highly inefficient as it removes the object from the container and adds it again, which triggers a lot of events. This is what the Plone default implementation does. This could be optimized if necessary.
There's an upgrade step that renames the id of objects that have a wrong one. This is done only for documents and dossiers as these are currently the only types that can be copied using the new frontend. It does not work for closed dossiers. …
> Rename object and set creator after copying with REST API

- docs/public/release-notes/index.rst
Adds a pointer to new documentation to the release notes section.
_(French docs don't contain the release notes section)_
See [Slack conversation](https://4teamwork.slack.com/archives/C060FEYKA/p1614003424000900).
(No changelog or Jira issue)
> Docs: Add pointer to new documentation.

- docs/HISTORY.txt
- opengever/base/utils.py
- opengever/mail/subscribers.py
- When refusing a submitted proposal, it gets deleted (https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/proposal.py#L411-L412)
- Because an E-mail is deleted, we end up in the `mail_deleted` handler which tries to remove the `IExtractedFromMail` interface from the extracted document.
- This fails because the extracted document is trashed and hence `uuidToObject` returns None because the document is trashed
We simply fix this by using an unrestricted version of `uuidToObject`. 
I did not add tests, because I think the whole scenario is very convoluted and should actually not happen. I actually think it's wrong that attachments from E-mails in a submitted proposal get extracted into the meeting dossier. I've created a follow-up story for that …
> Fix rejecting submitted proposal containing mail with extracted trashed attachment.

- docs/HISTORY.txt
- opengever/activity/error_handling.py
- opengever/activity/mail.py
- opengever/activity/tests/test_plone_center.py
A user might have some notifications enabled for the "E-Mail" channel, but not have an email address tied to their account / OGDS user.
Before this change, this resulted in the actor that triggered the notification getting an unhelpful warning message saying that one or more notifications could not be dispatched (because an attempt was made to have the Mailhost send an email with a recipient of `None`).
This PR changes this behavior so that this case is silently ignored (except for a warning that gets logged).
In addition, exceptions that happen during notification dispatching will now be logged to Sentry.
Follow-Up Story: [CA-1829](https://4teamwork.atlassian.net/browse/CA-1829) _(Benachrichtigungseinstellungen: Channels ausgrauen falls keine E-Mail Adresse hinterlegt)_
Jira: …
> No longer show warning about failed notification deliveries if recipient user doesn't have an email address

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/menu.py
- opengever/core/profiles/default/types/opengever.meeting.proposal.xml
- opengever/core/upgrades/20210218094100_add_create_task_from_proposal_action/types/opengever.meeting.proposal.xml
- opengever/core/upgrades/20210218094100_add_create_task_from_proposal_action/upgrade.py
With this PR we provide an action create_task_from_proposal for proposals. This helps the new frontend to create tasks from the overview of a proposal.
The action is not shown in the classic UI as the "Create task" function already exists there.
Jira: https://4teamwork.atlassian.net/browse/NE-684
- API change:
> Add create_task_from_proposal action

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- opengever/api/document.py
- opengever/api/tests/test_document.py
This PR adds the `creator` to the document serializer.
We need this for the frontend to be able to properly display the creator of the initial version.
Jira: https://4teamwork.atlassian.net/browse/CA-1812
- API change:
- If breaking:
> Add creator to the document serializer

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
This PR fixes the CL after backporting commits to release 2020.4.1
> Fix changelog after backporting

- docs/HISTORY.txt
- opengever/base/behaviors/changed.py
- opengever/dossier/base.py
- opengever/dossier/tests/test_dossier_helpers.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/catalog_source.py
- opengever/tabbedview/helper.py
- opengever/tabbedview/tests/test_catalog_source.py
The changed date has now been indexed on all deployments and the conditionals protecting against states where it had been introduced but not set yet are no longer needed.
Note that I had to delete two tests, that were actually testing some of the conditionals that were only introduced temporarily as a safeguard for missing changed dates.
For https://4teamwork.atlassian.net/browse/CA-1667
> Cleanup conditionals protecting for changed date not set yet.

- opengever/core/testserver.py
For testing language switcher in UI @all4manu would like to have a second language which is always enabled. This seems to work with all existing tests in the backend.
Jira: https://4teamwork.atlassian.net/browse/HG-995
> Add second language to the testservers by default.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/searching.rst
- opengever/api/solrsearch.py
- opengever/api/tests/test_solrsearch.py
Needed by the gever-ui, for displaying the breadcrumbs for each searchresult in the search results page. 
Because we do not have the information currently in SOLR and an indexing would lead to bad updating problems (changing the title of the repositoryfolder), we decide to use the real object for the generation, but introduce a flag and do not add the breadcrumbs by default. So it's only used in the detailed search results page, similar as we do in the classic ui. Discussed with buchi.
i was not sure how to implement the flag, that were my thoughts:
* Why not using the `expansion` functionality: The results is added to each result item not as a main key to the response.
* Why not handling the breadcrumbs as a requested field: the generation leads to longer requests, this would not be …
> Extend solrsearch endpoint, with breadcrumbs information option.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/documents_from_template.rst
- docs/public/dev-manual/api/index.rst
- opengever/docugate/service.py
- opengever/docugate/tests/test_service.py
- opengever/officeconnector/helpers.py
- opengever/oneoffixx/browser/form.py
- opengever/oneoffixx/configure.zcml
- opengever/oneoffixx/service.py
- opengever/oneoffixx/templates.py
- opengever/oneoffixx/tests/__init__.py
- opengever/oneoffixx/tests/test_oneoffixx.py
- opengever/oneoffixx/tests/test_service.py
This PR implements the following endpoints:
- POST @document_from_oneoffixx endpoint to create a document form a oneoffixx template
- GET @oneoffixx-templates endpoint to get all  oneoffixx groups, templates and favorites
Jira: https://4teamwork.atlassian.net/browse/CA-1388
ℹ️ because I don't know the exactly oneoffixx-api behavior and I can't test it properly due to a missing test-env, I had to make assumptions for the rest-api by reading the existing tests and the current implementation for the old UI. 
- API change:
- If breaking:
- Change in …
> Implement OneOffixx REST-Endpoints

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/sharing.rst
- opengever/api/configure.zcml
- opengever/api/local_roles.py
- opengever/api/sharing.py
- opengever/api/tests/test_local_roles.py
- opengever/sharing/browser/resources/sharing.js
- opengever/sharing/tests/test_sharing.py
The default local-roles serializer returns all current local roles by default. If we pass a search-param, it will return all available entries which could possibly be added to the local roles. This result set can contain a lot of entries:
Currently, such a response will break the UI.
So this PR customizes the local-roles serializer to return a batched result-set if searching for entries but returns an unbatched result-set if just requesting the current local roles.
ℹ️ The default batch-size is at 25 which should solve the issue. We do not implement batching in the frontend-sharing-tab, but just display the available entries.
Jira: https://4teamwork.atlassian.net/browse/CA-1831
_Only …
> The @sharing endpoint returns a batched result set if using the search param.

- .github/pull_request_template.md
As discussed in the sprint review, when a PR leaves a state behind that will require further improvements, for example because it leads to some technical debt, does not cover some edge cases, or is simply an incomplete implementation of a feature that we know will lead to support requests, complaints, confusion further down the line, we want to make sure to create follow-up stories to sort these out.
This is added as a reminder in the PR template.
Moreover I propose to simplify the checklist a bit, make it a single checklist with a mandatory and optional part.
> Update PR template with creation of follow-up stories

- docs/HISTORY.txt
- opengever/core/profiles/default/rolemap.xml
- opengever/core/upgrades/20210304141056_allow_authenticated_users_to_use_the_api/rolemap.xml
- opengever/core/upgrades/20210304141056_allow_authenticated_users_to_use_the_api/upgrade.py
This PR solves the problem that if a user in the new frontend, i.e. via API, wants to access a foreign task in a foreign admin unit.
With the current implementation, the task responsible is allowed to access the task on the foreign admin_unit, but not to use the API on PloneSite root level, wich leads in Unauthorized Exceptions when using the new frontend and clicking on a foreign task.
https://4teamwork.atlassian.net/browse/CA-1859
- Upgrade steps (changes in profile)
> Allow any authenticated users to use the REST API.

- docs/HISTORY.txt
- opengever/document/forms.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/en/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_forms.py
When validation fails when a new file is uploaded over the `NamedFileWidget`, it will then behave as if it already had a value set, but this will not work correctly upon resubmission of the form because the file was not stored server side.
This problem is addressed in newer version of the widget, but it comes with its own set of problems, so [we gave up that path](https://github.com/4teamwork/opengever.core/pull/6910).
Here we propose another fix for the document add form. We reset the value of `NamedFileWidget` in the `DocumentAddForm` when validation fails. This is not ideal, but at least the widget does correctly show that currently no file will be uploaded if the form is submitted again. This covers the most likely scenario when using custom
property sheets in the classic UI.
This …
> Reset value of NamedFileWidget in DocumentAddForm when validation fails.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/deactivate.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_base.py
- opengever/dossier/tests/test_deactivate.py
- opengever/dossier/tests/test_resolve.py
This PR is a follow-up PR of: https://github.com/4teamwork/opengever.core/pull/6642
It should not be possible to resolve/deactivate a dossier if there are active linked workspaces. It's possible, that the current user does not see some linked workspaces because he does not have the `View` permission on it. So the check in https://github.com/4teamwork/opengever.core/pull/6642 will not detect such workspaces.
The `elevated_privileges` is only for the GEVER-instance and has no effect on the teamraum instance. So even if we run it with elevated privileges, the request to the teamraum is made with the currently logged in user and the permissions on the source instance, so the teamraum. It just makes sure, that the current user can access the `WorkspaceClient`.
We could refactor this, but …
> Don't resolve or deactivate a dossier if it has linked workspaces without view permission.

- docs/HISTORY.txt
- opengever/api/transition.py
- opengever/task/tests/test_api_support.py
The RelationChoice validator from the plone.restapi, make changes on the passed in data, so its necessary to pass in a deepcopy. Otherwise we pass in a list of objects instead of paths to the `doActionFor` call, which leads to an error in restapi's deserializer.
https://4teamwork.atlassian.net/browse/CA-1693
> Fix support in TransitionExtender for RelationChoice fields.

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/task/__init__.py
- opengever/task/browser/forms.py
- opengever/task/browser/templates/overview.pt
- opengever/task/configure.zcml
- opengever/task/handlers.py
- opengever/task/task.py
- opengever/task/tests/test_api_support.py
- opengever/task/tests/test_overview.py
- opengever/task/tests/test_sequential_task_process.py
This PR provides some fixes for the sequential task process feature:
- Fixed automatic start of a next task inside a sequential task process.
- Only show "add task to process" link, if next task is not yet started.
- Fix adding sequential task process on first position.
This ensures that only one task is open in a process.
For https://4teamwork.atlassian.net/browse/CA-1429
> Sequential task fixes

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/browser/folder_buttons_availability.py
In the new frontend, the `trash` action is visible in the documents tab on repository folder level. Because the documents listing shows all documents, even the the ones in resolved / inactive dossiers, the action can fail for certain documents. This failure is not handled by the frontend.
Here we implement the same approach as in the classic UI, i.e. we simply [do not show the action at the repository level](https://github.com/4teamwork/opengever.core/blob/master/opengever/repository/browser/tabs.py#L8-L12). I think this makes sense, I don't really see a use case for trashing documents from different main dossiers at the same time.
For https://4teamwork.atlassian.net/browse/CA-1828
_Everything has to be …
> Filter out trash and untrash folder buttons in @actions endpoint on repofolders.

- docs/HISTORY.txt
- opengever/api/tests/test_actions.py
- opengever/base/browser/folder_buttons_availability.py
- opengever/core/profiles/default/actions.xml
`folder_delete` action is available in new frontend for administrators on the repository folder level, but it isn't actually allowed to delete any objects. In the classic UI this action is not enabled on the documents tab of the repository folder. We do the same here and filter it out. 
This was not a requirement of any story, but stumbled upon it while looking at https://4teamwork.atlassian.net/browse/CA-1828
> Filter out folder_delete folder button in @actions on repofolders.

- docs/HISTORY.txt
- plonetheme/teamraum/resources/css/main.css
Since the latest chrome version (89.*) the upload box was displayed incorrectly - behind the title area, so that no upload was possible anymore.
See <img width="1353" alt="Bildschirmfoto 2021-03-05 um 15 37 14" src="https://user-images.githubusercontent.com/485755/110129969-cf502780-7dc8-11eb-8395-50ccaee97d43.png">
The `float:left` statement, seems not necessary, no side effects detected. Also discussed it with Kevin, who implemented the styling 5 years ago.
https://4teamwork.atlassian.net/browse/CA-1857
> Fix tabbedview's upload container position for latest chrome versions.

- docs/HISTORY.txt
- opengever/api/globalindex.py
- opengever/api/tests/test_globalindex.py
When filtering by responsible using the `@globalindex` endpoint, also return tasks assigned to a team the responsible belongs to. Ensures the same behavior we have in the classic UI.
JIRA: https://4teamwork.atlassian.net/browse/CA-1454
> Include team tasks in globalindex

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/.gitignore
We use python virtual environments on CentOS 8. For this we need to ignore a few more files and folders, otherwise deployments will get marked as dirty.
For https://4teamwork.atlassian.net/browse/CA-1792
> Update .gitignore of policytemplates for deployment on CentOS 8.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- opengever/api/document.py
- opengever/api/tests/test_actions.py
- opengever/api/tests/test_document.py
- opengever/api/tests/test_mail.py
- opengever/document/base.py
- opengever/document/fileactions.py
- opengever/document/tests/test_base.py
The action `new_task_from_document` should now also be available for documents within tasks.
To determine in the frontend where the new task should be created, the field `containing_subdossier_url` must also be serialised for documents.
Jira: https://4teamwork.atlassian.net/browse/NE-677
- API change:
> Allow to create tasks from document within task

- docs/HISTORY.txt
- opengever/api/configure.zcml
- opengever/api/history.py
- opengever/api/tests/test_history.py
- opengever/document/checkout/manager.py
- opengever/document/tests/test_checkout.py
- opengever/document/tests/test_copy_document.py
- opengever/document/tests/test_versioner.py
- opengever/trash/tests/test_trash.py
In case the document was checked-out and in without having ever been modified, the initial version will be missing and needs to be created, as it will not be created by the file setter. In all other scenarios the initial version should already exist.
I don't see any way we could identify concerned documents and recreate the initial version though. It's also not that important, as the missing version has the same file as the first version. It also seems that we have wrong creators[ for the initial version of older documents](https://github.com/4teamwork/opengever.core/pull/4632), so we overwrite the `@history` endpoint to return the correct creator for the initial versions. This also ensures that the same creators are displayed in the new frontend as in the classic UI [without having to …
> Create initial version upon document checkin.

- docs/HISTORY.txt
- opengever/workspace/configure.zcml
- opengever/workspace/indexers.py
- opengever/workspace/subscribers.py
- opengever/workspace/tests/test_workspace_meeting_agenda_item.py
- opengever/workspace/workspace_meeting_agenda_item.py
As we do not want to display `WorkspaceMeetingAgendaItem`s as separate objects (no detail view), but we want their content to be searchable, we need to add their content to the `SearchableText` of the `WorkspaceMeeting`. For this:
- We define a `SearchableTextExtender`
- We add event handlers to reindex the `WorkspaceMeeting` when an `WorkspaceMeetingAgendaItem` is added or modified.
For https://4teamwork.atlassian.net/browse/CA-1734
> Index agenda items in the workspace meeting searchable text.

- docs/HISTORY.txt
- opengever/api/solrsearch.py
- opengever/api/tests/test_solrsearch.py
- opengever/base/browser/search.py
- opengever/base/tests/test_indexers.py
- opengever/base/tests/test_search.py
- opengever/core/profiles/default/propertiestool.xml
- opengever/core/upgrades/20210315115831_remove_workspace_agendaitem_from_search/propertiestool.xml
- opengever/core/upgrades/20210315115831_remove_workspace_agendaitem_from_search/upgrade.py
- opengever/workspace/tests/test_workspace_meeting_agenda_item.py
`WorkspaceMeetingAgendaItem` are only meant to be represented on the the `WorkspaceMeeting` and should therefore not be findable in searches. Instead their content gets indexed in the `SearchableText` of the `WorkspaceMeeting`. So here we make sure that they get filtered out of the different search views and endpoints.
The `@solrsearch` endpoint is implemented in such a way that by default it filters out the blacklisted portal_types (notably `WorkspaceMeetingAgendaItem`), but if a `portal_type` filter is specified, it will be respected, so that it is possible to search for `WorkspaceMeetingAgendaItem`.
As `WorkspaceMeetingAgendaItem` get introduced in this version, this is not an API change and I did not adapt the documentation. I don't think that we need to describe in the documentation …
> Remove workspace meeting agendaitem from search

- docs/schema-dumps/opengever.workspace.meetingagendaitem.schema.json
- opengever/workspace/workspace_meeting_agenda_item.py
Jira: https://4teamwork.atlassian.net/browse/CA-1734
This PR fixes a wrong i18n domain for the workspace agenda item schema. There is no need to update the translations because all the translation strings are already translated. The `opengever.document` translations have not been update in the meantime, thus, there is also no need to rebuild them.
A changelog is not required because it's a fix of a feature introduced in this PR: #6925 
- API change:
- If breaking:
> Change wrong i18n domain for workspace agenda item schema

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/listings.rst
- opengever/api/listing.py
This whitelists the `id` for the `@listing` endpoint. The ID is required to for manual ordering in the task template listing.
Currently, we extract the `id` from the `@id` attribute. With this PR this is no longer necessary. That's part of a small refactoring.
Jira: https://4teamwork.atlassian.net/browse/CA-1737
- API change:
- If breaking:
> Add id field to the @listing endpoint.

- opengever/setup/creation/configure.zcml
- opengever/setup/overrides.zcml
- opengever/setup/tests/test_inflator_config_overwrite.py
Redeclaring it in `configure.zcml` may result in a `ConfigurationConflictError` depending on the order the packages are
loaded.
I'm not sure why, but sometimes I get a different order of the package paths included in the instance script. Seems to happen particularly after running buildout for the first time. Running buildout again usually "fixes" the order.
We also had the issue with deployments on a server, so it seems not to depend on the local dev environment.
E.g. if the grokcore packages are added first to the path then it probably doesn't work:
```
sys.path[0:0] = [
'/apps/eggs/grokcore.annotation-1.3-py2.7.egg',
'/apps/eggs/grokcore.site-1.6.1-py2.7.egg',
'/apps/eggs/grokcore.viewlet-1.11-py2.7.egg',
'/apps/eggs/grokcore.component-2.5.1-py2.7.egg', …
```
> Properly override inflator import step

- docs/HISTORY.txt
- opengever/setup/deploy.py
With [this PR](https://github.com/4teamwork/opengever.core/pull/6903), we removed LDAP from the Authentication plugins in the policy templates, as it anyway gets deactivated during setup. Problem is that the deployment script fails while trying to deactivate the plugin.
For https://4teamwork.atlassian.net/browse/CA-1801
> Deployment no longer fails if ldap is not in authentication plugins.

- docs/HISTORY.txt
- docs/public/dev-manual/api/propertysheets.rst
- opengever/document/behaviors/customproperties.py
- opengever/propertysheets/assignment.py
- opengever/propertysheets/field.py
- opengever/propertysheets/tests/fixture.py
- opengever/propertysheets/tests/test_annotation.py
- opengever/propertysheets/tests/test_assignment.py
- opengever/propertysheets/tests/test_field.py
- opengever/propertysheets/tests/test_field_schema_provider.py
- opengever/propertysheets/tests/test_widget.py
- opengever/propertysheets/widgets.py
Introduce customproperties default slots which is enabled for every document. So it's possible to add custom fields which are available regardless of which document type is selected.
First part of https://4teamwork.atlassian.net/browse/CA-1493 - Dossier Support will follow in a separate PR
- API change:
> Extend document propertysheets with a default slot.

- development.cfg
- docker-compose.yml
- docs/HISTORY.txt
- opengever/core/docker_testing.py
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/en/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/testing.py
- opengever/core/upgrades/20210319175529_add_meeting_minutes_pdf_action/actions.xml
- opengever/core/upgrades/20210319175529_add_meeting_minutes_pdf_action/upgrade.py
- opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
- opengever/workspace/browser/configure.zcml
- opengever/workspace/browser/meeting_pdf.py
- opengever/workspace/browser/templates/meeting_minutes.pt
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/tests/test_meeting_minutes.py
Provides the functionality to create a PDF with the meeting minutes from a workspace meeting.
Uses WeasyPrint for PDF generation from HTML, which is integrated as dockerized a web service.
The reason for not using the already available PDFLaTeX, is its poor support for handling HTML tables.
JIRA: https://4teamwork.atlassian.net/browse/CA-1743
> Meeting minutes pdf

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/trigger_task_template.rst
- opengever/api/templatefolder.py
- opengever/api/tests/test_templatefolder.py
- opengever/tasktemplates/tasktemplatefolder.py
Allow overriding task and subtask title and text (description) fields in the `@trigger-task-template` endpoint, so that users can set these attributes in a batch add form in the new UI.
We extend the existing `@trigger-task-template` endpoint so that new, optional attributes can be provided. 
This will provide more convenience in the new UI. The functionality is available in the classic UI, but only when editing the content after creation.
Corresponding UI PR: https://github.com/4teamwork/gever-ui/pull/1673
Jira: https://4teamwork.atlassian.net/browse/HG-1041
- API change:
> Allow overriding task and subtask title and text in `@trigger-task-template` endpoint.

- docs/HISTORY.txt
- opengever/officeconnector/service.py
Make it work with shadow documents that don't have a content type stored in annotations. This is the case for Docugate as we don't know yet the content type.
JIRA: https://4teamwork.atlassian.net/browse/CA-1411
> Fix oc_checkout endpoint

- docs/HISTORY.txt
- docs/public/dev-manual/api/propertysheets.rst
- docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
- opengever/api/schema/adapters.py
- opengever/api/tests/test_vocabularies.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/bundle/schemas/dossiers.schema.json
- opengever/core/profiles/default/registry.xml
- opengever/core/profiles/default/types/opengever.dossier.businesscasedossier.xml
- opengever/core/profiles/default/types/opengever.meeting.meetingdossier.xml
- opengever/core/upgrades/20210322222234_add_dossier_types_configuration_setting/registry.xml
- opengever/core/upgrades/20210322222234_add_dossier_types_configuration_setting/upgrade.py
- opengever/core/upgrades/20210323080047_enable_custom_properties_for_dossiers/types/opengever.dossier.businesscasedossier.xml
- opengever/core/upgrades/20210323080047_enable_custom_properties_for_dossiers/types/opengever.meeting.meetingdossier.xml
- opengever/core/upgrades/20210323080047_enable_custom_properties_for_dossiers/upgrade.py
- opengever/dossier/behaviors.zcml
- opengever/dossier/behaviors/customproperties.py
- opengever/dossier/behaviors/dossier.py
- opengever/dossier/browser/forms.py
- opengever/dossier/interfaces.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_dossier_types.py
- opengever/dossier/vdexvocabs/dossier_types.vdex
- opengever/propertysheets/assignment.py
- opengever/propertysheets/tests/test_assignment.py
- opengever/propertysheets/tests/test_dossier_custom_properties.py
This PR introduces a customproperty field for dossier, including a new field `dossier_type`, similar to the `document_type` field for documents and mails. I made the following decisions:
- For the dossier_type values I introduced new vdexvocabulary, which can be customized by a GEVER policy. By default there is only one value, which is also hidden by the registry entry.                                                                                                                                                                 
- If there are no values for the field available, the field is hidden in the add and edit forms.
- The customproperty field provides a default slot and slots for each dossier_type.
I also had to fix the vocabulary_url for unnamed vocabularies in the @schema …
> Introduce a new field dossier_type and customproperty slots for dossiers.

- docs/HISTORY.txt
- docs/schema-dumps/opengever.workspace.meeting.schema.json
- opengever/api/tests/test_vocabularies.py
- opengever/workspace/browser/meeting_pdf.py
- opengever/workspace/browser/templates/meeting_minutes.pt
- opengever/workspace/configure.zcml
- opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
- opengever/workspace/locales/opengever.workspace.pot
- opengever/workspace/tests/test_vocabularies.py
- opengever/workspace/tests/test_workspace_meeting.py
- opengever/workspace/utils.py
- opengever/workspace/vocabularies.py
- opengever/workspace/workspace_meeting.py
This PR provides a new field `attendees` for a workspace meeting.
Jira: https://4teamwork.atlassian.net/browse/CA-1740
- API change:
- If breaking:
> Meeting participants

- docs/HISTORY.txt
- opengever/activity/notification_settings.py
- opengever/activity/tests/test_notification_center.py
- opengever/task/tests/test_activities.py
With this change we now dispatch notifications for documents added to tasks (controlled via the `task commented` notification settings group).
This activity was previously unmapped in the configuration, and therefore produced errors during notification settings lookup, as well as not being dispatched.
The notification settings group "task commented" is not a perfect fit, but the least bad of the available ones, and we don't want to undo the simplification by introducing yet another group.
In addition, errors during notification lookup are now handled more specifically, by raising an intermediate `UnmappedActivityKind` exception that ends up in Sentry together with a sensible traceback (instead of [producing an `AttributeError`](https://sentry.4teamwork.ch/organizations/sentry/issues/71995/ …
> Dispatch notification for documents added to tasks.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- opengever/task/tests/test_api_support.py
- opengever/task/transition.py
It should now be possible to notify additional principals when delegating a task, just like when creating a task.
Jira: https://4teamwork.atlassian.net/browse/NE-671
- API change:
> When delegating tasks via API, informed_principals can be set.

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/testing/fixtures.py
- opengever/testing/profiles/testing/registry.xml
Add the new dossier_type field to dossier templates. 
The PR also enables the dossier_type `businesscase` in our testsetup, this allows the gever-ui to tests dossier_type specific customproperties.
https://4teamwork.atlassian.net/browse/CA-1292
> Add dossier_type field for dossier templates.

- docs/HISTORY.txt
- opengever/propertysheets/configure.zcml
- opengever/propertysheets/solr.py
- opengever/propertysheets/tests/test_solr.py
- solr-conf/managed-schema
This allows filtering and sorting by custom properties in Solr. However there's no UI integration so far.
Properties are indexed using the corresponding Solr type (string, int, boolean) in dynamic fields.
Text (multiline) properties are not indexed as it doesn't make sense to filter/sort on multiline text.
Only properties of the active and the default assignment are indexed.
The name patterns for dynamic fields are:
- `*_custom_field_string`
- `*_custom_field_int`
- `*_custom_field_boolean`
E.g. a custom property with id `supplier` and type `TextLine` would be indexed in the dynamic field `supplier_custom_field_string`. The assignment is not part of the Solr field name, which could potentially lead to conflicts in case of having the same id in the default and the active assignment. …
> Index custom properties in Solr as dynamic fields

- docs/HISTORY.txt
- opengever/core/upgrades/20210401195218_fix_task_template_responsibles/upgrade.py
Jira: https://4teamwork.atlassian.net/browse/CA-1997
This PR fixes an issue where it is possible, that the responsible of a tasktemplate is `interactive_actor:None`. 
This bug was introduced in the PR: https://github.com/4teamwork/opengever.core/pull/6804 (v2021.3.0.) by the upgradestep: https://github.com/4teamwork/opengever.core/pull/6804/files#diff-5ab0af610f807e6e371deb6d77e40033f44c2a9abdb3c1cf88d8c4aeaabb3c46
Before v2021.3.0, if you removed a tasktemplate responsible, the `responsible_client` have not been removed. But the upgradestep in https://github.com/4teamwork/opengever.core/pull/6804/files#diff-5ab0af610f807e6e371deb6d77e40033f44c2a9abdb3c1cf88d8c4aeaabb3c46 assumed, that it is: https://github.com/4teamwork/opengever.core/pull/6804/files#diff-5ab0af610f807e6e371deb6d77e40033f …
> Fix broken task template responsibles

- docs/HISTORY.txt
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_agendaitem_adhoc.py
- opengever/meeting/tests/test_agendaitem_list.py
For ad-hoc proposals, the `dossier_reference_number` mergefield contains now the reference_number of the meeting dossier instead of None.
https://4teamwork.atlassian.net/browse/CA-1374
The dossier_reference_number is fetched on the fly. Since the IntId Catalog and Acquisition are used for this, I consider this procedure as not performance critical and have decieded do not persist the file number in the SQL model.
Documentation needs no update, the `dossier_reference_number` is already documented.
> Provide dossier_reference_number mergefield value also for ad-hoc proposals 

- docs/HISTORY.txt
- opengever/mail/subscribers.py
Plone site deletion fails when attachments have been extracted to new documents. This is because of event handlers on the `IObjectRemovedEvent` which fail due to deletion order. I did not dig too deeply, but it seems that the behaviors can get deleted before the objects, so that adapting the document to `IRelatedDocuments` in `extracted_attachment_deleted` will fail.
I also skip a second event handler (`mail_deleted`), although I did not see any failure due to this one, but it might happen, so it's safer to also check for plone site deletion there.
For https://4teamwork.atlassian.net/browse/CA-1947
> Fix plone site deletion by skipping certain event handlers.

- docs/HISTORY.txt
- opengever/task/tests/test_activities.py
- opengever/task/transition.py
This PR properly handles watchers for team tasks accepted by a user.
With this change, if a user accepts a task assigned to a group, the group will be removed as a watcher of the resource and the user will be added. 
Jira: https://4teamwork.atlassian.net/browse/CA-1953
- API change:
- If breaking:
> Properly reset the responsible watcher if a user accepts a task assigned to a team.

- docs/HISTORY.txt
- opengever/core/upgrades/20210409160907_index_attendees_in_solr/upgrade.py
- opengever/workspace/configure.zcml
- opengever/workspace/indexers.py
- solr-conf/managed-schema
With this PR, attendees for workspace meetings are indexed in Solr. This is necessary to display a meetings card on the teamraum dashboard.
Based on: https://github.com/4teamwork/opengever.core/pull/6858
Jira: [NE-678]
- API change:
[NE-678]: https://4teamwork.atlassian.net/browse/NE-678
> Add attendees solr index for workspace meetings.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/datetimepicker.js
This PR removes the daterange restriction in the spv meeting end date.
Jira:https://4teamwork.atlassian.net/browse/CA-1459
Because the JS code in the old ui is hard to maintain and legacy anyway, we just remove this restriction.
- API change:
- If breaking:
> Remove daterange restriction in spv meeting end date.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- opengever/api/configure.zcml
- opengever/api/field_deserializers.py
- opengever/api/tests/test_deserializer.py
Because the Python `strftime` methods can't represent dates earlier than 1900, we reject them in the API by using custom field serializers.
I didn't override the `PersistentDatetimeFieldDeserializer` that we also have (in the same file), because that only gets used for system-generated timestamps, like entries in task or proposal histories. These should never get set to anything earlier than 1900 ;-) 
Jira: https://4teamwork.atlassian.net/browse/CA-1882
- API change:
- If breaking:
> API: Reject years before 1900 for date and datetime fields.

- docs/HISTORY.txt
- opengever/task/response_syncer/workflow.py
- opengever/task/tests/test_response_syncer.py
Add `task-transition-in-progress-tested-and-closed` transition to synced transitions, to make sure closing a multi admin unit direct-execution tasks, is synced correctly to the predecessor.
https://4teamwork.atlassian.net/browse/CA-2047
> Fix in-progress to close transition (API), for multi adminunit tasks.

- docs/HISTORY.txt
- docs/public/dev-manual/api/api_changelog.rst
- opengever/api/task.py
- opengever/api/tests/test_task.py
The frontend needs to know whether a task is a cross client task so that it can present the correct options for the workflow transitions.
For https://4teamwork.atlassian.net/browse/CA-2064
- API change:
- If breaking:
> Add is_remote_task to task serialization.

- changes/6977.other
- docs/public/dev-manual/api/api_changelog.rst
- opengever/api/task.py
- opengever/api/tests/test_task.py
The frontend also needs to find out the URL of the admin unit of the responsible for a given task. We thought of fetching this from the portal, but we cannot rely on the URLs being configured correctly on the portal. Instead we now also add that URL to the task serialization.
For https://4teamwork.atlassian.net/browse/CA-2064
- API change:
- If breaking:
> Add responsible_admin_unit_url to task serialization.

- changes/6975.other
- opengever/document/browser/templates/macros.pt
Microsoft has removed the close action from Word and has announced to do the same for Excel and PowerPoint in the future. The user now needs to close the tab to finish editing. Thus we open Office Online in a new tab.
JIRA: https://4teamwork.atlassian.net/browse/CA-1940
> Open Office Online in new tab

- changes/CA-2110.bugfix
- opengever/api/tests/test_history.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/content_history_viewlet.py
With this PR we prevent an exception in the `@history` endpoint for users who only have the `Reader` role on context they access.
We need to workaround the following problem:
- plone.restapi relies on history viewlet https://github.com/plone/plone.restapi/blob/d78a8411d1166ee785ee71292a540f39fc2cf44c/src/plone/restapi/services/history/get.py#L42 and iterates over its result https://github.com/plone/plone.restapi/blob/d78a8411d1166ee785ee71292a540f39fc2cf44c/src/plone/restapi/services/history/get.py#L54 
- however full history returns `None` when the history can't be retrieved or is empty https://github.com/plone/plone.app.layout/blob/0ba390844d7c4f7dc88fe1688e80876eea58be66/plone/app/layout/viewlets/content.py#L481 
- which is the case when there are no versions and user can’t access …
> Fix `@history` endpoint when no history exists.

- changes/1912.feature
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/index.rst
- docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
- docs/public/dev-manual/api/schemas/opengever.workspace.meeting.inc
- docs/public/dev-manual/api/versions.rst
- opengever/api/configure.zcml
- opengever/api/history.py
- opengever/api/tests/test_history.py
- opengever/document/browser/versions_tab.py
We add a new `@versions` endpoint to retrieve the list of versions of a document. This endpoint is basically a copy of the `@history` endpoint with a few modifications:
- It only returns versioning entries (whereas the `@history` endpoint also returns workflow modification entries).
- It is batched
- It always returns the initial version, even when it has not been created now. Because we delay the creation of the initial version in Gever to avoid wasting storage space, we make sure to return the correct information for the initial version in the @versions endpoint even when it wasn't created yet.
- Use the creator as the actor of the initial version in `@versions.` This is necessary because certain initial versions in Gever have the wrong actor. This was already [corrected in the …
> Add new @versions endpoint

- changes/CA-1753.other
- opengever/policytemplates/hooks.py
- opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
* Apps endpoint URL question should not be ignored for GEVER deployments
* check enable_workspace_meeting_feature should only be used for teamraum policies.
> Fix policy generator for GEVER policies

- changes/CA-1732.other
- opengever/meeting/tests/test_meeting_json_serializer.py
- opengever/meeting/tests/test_meeting_zipdemand.py
- opengever/meeting/tests/test_meeting_zipexport.py
- opengever/meeting/zipexport.py
- opengever/private/tests/test_dossier.py
- opengever/testing/integration_test_case.py
Grimlock does no longer support uploading documents which are not a PDF, but Users nevertheless sometimes upload the ZIP with original files to Grimlock.
Instead of adding validation to Grimlock which may be expensive, we no longer add the `meetings.json` metadata file to the zip of originals. This will prevent such ZIPs being processed by Grimlock. This JSON file is only used for Grimlock import, but as the import for originals is no longer possible it does not make sense to include the metadata in the zip.
I had to move the tests around a bit:
- An exhaustive functional test which asserts the whole structure of the `meetings.json` file in the downloaded zip, i moved it to the PDF ZIP oriented tests
- I dropped some of the tests which only test  a subset of aforementioned test
- Also I …
> No longer export meeting.json in meeting zip export of original files.

- changes/CA-2012.bugfix
- opengever/sharing/browser/sharing.py
- opengever/sharing/tests/test_sharing.py
Currently when searching for a group, via the @sharing endpoint and the search_terms contains umlaut, the search for the additional group_title attribute (`description`) failed silently with a UnicodeWarning. Because combining the attribute and the search_term raised an UnicodeDecodeError.
Fixes https://4teamwork.atlassian.net/browse/CA-2012
> Fix searching for group descriptions with umlauts in search terms.

- changes/CA-2063.other
- opengever/base/browser/resources/base.js
Remove path limitation in the geverui cookie, because the decision which UI the user wants to use, should be for the all admin units. Accepting multi admin unit tasks with different UI selected, leads to not found errors (see https://4teamwork.atlassian.net/browse/CA-2063).
Not sure if there is a possibility to migrate or update existing settings.
> Switch GEVER-UI setting to an overall admin_unit setting.

- changes/CA-1724.other
- opengever/core/locales/de/LC_MESSAGES/opengever.core.po
- opengever/core/locales/en/LC_MESSAGES/opengever.core.po
- opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
- opengever/core/locales/opengever.core.pot
- opengever/core/profiles/default/actions.xml
- opengever/core/upgrades/20210426170717_add_reopen_meeting_action/actions.xml
- opengever/core/upgrades/20210426170717_add_reopen_meeting_action/upgrade.py
- opengever/meeting/browser/meetings/configure.zcml
- opengever/meeting/browser/meetings/reopen.py
- opengever/meeting/browser/meetings/templates/reopen_meeting.pt
- opengever/meeting/model/query.py
- opengever/meeting/reopen.py
- opengever/meeting/tests/test_meeting_reopen.py
- opengever/meeting/tests/test_meeting_view.py
With this PR we add functionality to automatically reopen meetings. So far this was unsupported and had to be done manually via debug shell.
At the moment the action is only visible for a `Manager` as we want to test it out ourself before enabling it for customers.
A simple view will open which shows a summary of actions to be performed or reasons why they can't be performed at the moment.
I have translated only the action but not the view, as the view will only be used by us at the moment.
Jira: https://4teamwork.atlassian.net/browse/CA-1724
> Allow meetings to be reopened by a Manager.

- opengever/base/browser/resources/base.js
otherwise the path specific cookie wins over the `/` cookie and the new ui is still shown.
https://4teamwork.atlassian.net/browse/CA-2063
_Changelog entry already exists._
> Fix UI toggler, remove the adminunit specific cookie.

- changes/CA-1871.other
- opengever/document/archival_file.py
- opengever/dossier/base.py
- opengever/dossier/nightly_after_resolve_job.py
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_base.py
- opengever/dossier/tests/test_resolve.py
To avoid swamping bumblebee with PDF conversion jobs when executing the `NightlyAfterResolveJobs`, we add a limit to the number of conversion jobs triggered by a deployment in one night.
Note that the `AfterResolveJobs.trigger_pdf_conversion` method was not very smart as it submitted conversion jobs for all documents in the dossier being resolved, but as dossier resolution is recursive, this happens for every subdossier too. We had already introduced a mechanism to at least [avoid sending several jobs for the same document in a single request](https://github.com/4teamwork/opengever.core/pull/5600), but this is not sufficient. Indeed it would still queue conversion jobs for documents from a previously resolved subdossier (which was not resolved in the same request). Also this will not work …
> Improve archival file conversion job management when resolving dossiers.

- changes/CA-1224.bugfix
- opengever/bundle/console.py
Since #6968 its no longer be possible to import a bundle without a configuration file.
> Bundle import: Skip configuration import if not exists.

- changes/CA-1276.bugfix
- opengever/dossier/configure.zcml
- opengever/dossier/handlers.py
- opengever/workspaceclient/client.py
- opengever/workspaceclient/linked_workspaces.py
- opengever/workspaceclient/storage.py
- opengever/workspaceclient/tests/test_linked_workspaces.py
Workspace links are only allowed on main dossiers, but with moving a dossier into a subdossier it was possible to make a main dossier with linked workspaces to a subdossier. This PR fixes this issue, by automatically move the workspace link to the main_dossier. For https://4teamwork.atlassian.net/browse/CA-1276
There is a small possibility, where a move ist not possible, because the user is not allowed to update the linked workspaces. In that case it raises an Exception. Which is currently not handled with a specific error message in the frontend (I added a not to https://4teamwork.atlassian.net/browse/CA-396, because we need to define the right format for such messages first).
_Only …
> Move workspace links, when moving a dossier with linked workspace in to a dossier.

- changes/CA-2173.bugfix
- opengever/meeting/browser/meetings/debug.py
It is not mandatory to define a template for paragraphs, therefore we need to handle the situation where the template is not defined, as is already done in the view generating the protocol (https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/command.py#L333-L336).
> Handle no template for paragraphs in DebugDocxCompose view.

- changes/CA-2129.other
- opengever/base/behaviors/configure.zcml
- opengever/base/behaviors/lifecycle.py
- opengever/base/tests/test_lifecycle.py
According to https://4teamwork.atlassian.net/browse/CA-2129 the value restriction on the `archival_value` field, is "fachlich" incorrect and no longer desired.
The PR replaces the RestrictedVocabulary with a SimpleVocabulary, with this changes also the value_propagation for no longer valid values is redundant.
> Remove value restriction for the archival_value field.

- changes/CA-1840.other
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/workspace/participation.rst
- opengever/api/tests/test_participation.py
- opengever/workspace/participation/browser/manage_participants.py
With this PR we prevent that a site-admin or manager is able to remove the last `WorkspaceAdmin` role assignment for a workspace or a workspace folder.
This currently solves the backend side, but does not really render a nice error message in the frontend. This can be solved separately, though.
Jira: https://4teamwork.atlassian.net/browse/CA-1840
- API change:
> Don't allow removing last workspace admin role.

- changes/CA-1494.feature
- docs/public/dev-manual/api/api_changelog.rst
- docs/public/dev-manual/api/listings.rst
- opengever/api/configure.zcml
- opengever/api/listing.py
- opengever/api/listing_custom_fields.py
- opengever/api/solr_query_service.py
- opengever/api/tests/test_listing.py
- opengever/api/tests/test_listing_custom_fields.py
- opengever/propertysheets/definition.py
- opengever/propertysheets/solr.py
- opengever/propertysheets/tests/test_definition.py
We add support to query the `@listing` endpoint with custom properties/dynamic fields. Available custom columns by listing are provided globally in a `@listing-custom-fields` endpoint.
The custom fields are provided in a global endpoint on the plone site, so that the UI can request these mostly static information once, and then retrieve it from from global application state rather than querying the available fields every time before a listing is requested from the backend.
The `@listing-custom-fields` endpoint returns all available fields based on currently registered property sheets. It takes care of associating property sheets to available listing names and merges fields from different property sheets with the same name and type while building the list.
The `@listing` endpoint now …
> Allow querying by custom properties in `@listing` endpoint.

- opengever/propertysheets/definition.py
- opengever/propertysheets/tests/test_definition.py
- opengever/propertysheets/tests/test_schema_definition_post.py
With this PR we explicitly prevent that users add non string choice values to a choice field in a property sheet definition.
This would not have been prevented before indirectly due to a call to `encode` on all values. Nevertheless we add explicit handling to disallow non string values in choice fields and raise an exception with a more explicit message.
Amends https://github.com/4teamwork/opengever.core/pull/7000, i have not added a separate CL entry.
Jira: https://4teamwork.atlassian.net/browse/CA-1494
- ~~[ ] Changelog entry~~
> Properly handle non string choices in property sheet definition.

- changes/CA-1494.other
- opengever/propertysheets/assignment.py
- opengever/propertysheets/storage.py
- opengever/propertysheets/tests/test_field.py
- opengever/propertysheets/tests/test_storage.py
- opengever/testing/builders/propertysheets.py
We now enforce unique fields names within certain subsets of slots.
This has become necessary as our Solr dynamic field implementation of https://github.com/4teamwork/opengever.core/pull/6959 potentially shares field names between different property sheets. To prevent undefined behavior when a sheet for the default slot and a sheet for a type specific slot define the same field, we don't allow this to happen in the first place.
We also don't allow the same property sheet to be assigned to the default slot and a type specific slot at the same time.
The implementation here is a bit more strict that would be necessary as same name but different type would currently result in different Solr dynamic field names. I think it is a reasonable and future proof restrictions, and users can just …
> Prevent creation of property sheets with conflicting fields.
