changes/CA-2212.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/upload_structure.rst
opengever/api/configure.zcml
opengever/api/tests/test_upload_structure.py
opengever/api/upload_structure.py

We add an endpoint @upload-structure to help prepare a dossier upload into Gever. The endpoint will check whether the proposed upload is possible and reply with information about the structure that would need to be created in Gever, including 
which containers should be created and the `portal_type`s that should be used.
The endpoint checks whether the user is allowed to create content in the given context and whether the objects (container, documents and mails) that would need to be created for that upload are allowed in the current context, including whether the maximal subdossier depth would be exceeded.
For https://4teamwork.atlassian.net/browse/CA-2212
_Only applicable should be left …

Add @upload-structure endpoint

---

changes/CA-1641.feature
docs/public/dev-manual/api/close_remote_task.rst
docs/public/dev-manual/api/index.rst
opengever/api/close_remote_task.py
opengever/api/configure.zcml
opengever/api/serializer.py
opengever/api/tests/test_close_remote_task.py
opengever/api/tests/test_serializer.py
opengever/api/tests/test_summary_serializer.py
opengever/task/browser/close.py

Adds an additional API endpoint `close-remote-task` which allows to close a remote task and copy documents (related or contained) to a dossier of the current admin_unit.
https://4teamwork.atlassian.net/browse/CA-1641
- API change:

Add close-remote-task endpoint 

---

changes/CA-2117.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/globalindex.rst
opengever/api/task.py
opengever/api/tests/test_globalindex.py

On the dashboard in the new frontend, the @globalindex endpoint is used for listing tasks. Since the table listing can also display the values "Subdossier", "Status" and "Laufzeitnummer", these values must also be available via the @globalindex endpoint.
Jira: https://4teamwork.atlassian.net/browse/CA-2117 and https://4teamwork.atlassian.net/browse/CA-2230
- API change:

Include containing_subdossier, review_state_label and sequence_number in task model serialization

---

changes/CA-2222.bugfix
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/extract_attachments.rst
opengever/api/tests/test_mail.py
opengever/document/base.py
opengever/mail/mail.py

Until now, extracting attachments from mail in a workspace did not work because no parent was found where the attachment could be saved.
Jira: https://4teamwork.atlassian.net/browse/CA-2222
- API change:

Attachment extraction now also works for mails in a workspace.

---

changes/CA-2215.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/upload_structure.rst
opengever/api/configure.zcml
opengever/api/tests/test_upload_structure.py
opengever/api/upload_structure.py

With this PR we add possible duplicate identification in the `@upload-structure` endpoint. Note that the implementation has the following shortcomings:
1. For now the control is limited to files and we are not checking for folder names. 
2. Also note that it only partially works for mails, as the during upload the filename is modified to match the Subject of the E-mail, so that subsequently uploading the same E-mail will not identify it as a possible duplicate. This is not easily solved as during the control we do not have the actual files, only the filenames, so that we cannot analyse mails to check their subjects. Note that the current implementation in the gever-ui was not handling this issue either.
For https://4teamwork.atlassian.net/browse/CA-2215
_Everything has to be done/checked. …

Add duplicate control in @upload-structure endpoint.

---

changes/CA-1180.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/linked_workspaces.rst
opengever/api/linked_workspaces.py
opengever/api/tests/test_linked_workspaces.py
opengever/workspaceclient/linked_workspaces.py

In the new frontend, a warning should be displayed on the dossier overview if the dossier is linked to workspaces to which the user does not have access. Therefore, it must be known whether such workspaces exist.
Jira: https://4teamwork.atlassian.net/browse/CA-1180
- API change:

Add workspaces_without_view_permission attribute to @linked-workspaces endpoint

---

changes/CA-1970.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/dossier.py
opengever/api/serializer.py
opengever/api/tests/test_document.py
opengever/api/tests/test_dossier.py

This PR adds an additional key to the dossier and documents api serialization which lists summaries of all backreferences. It uses plone.restapis default summary serializer for the backreferences.
This is used for display backreferences in the new UI, see https://4teamwork.atlassian.net/browse/CA-1970
- API change:

Include backreference list to dossier and documents api serialization.

---

changes/CA-1358.bugfix
opengever/api/tests/test_linked_workspaces.py
opengever/api/tests/test_scanin.py
opengever/base/placeful_workflow.py
opengever/bundle/tests/test_teamraum_oggbundle_pipeline.py
opengever/examplecontent/profiles/default_content/content_creation/01_default_content.json
opengever/inbox/configure.zcml
opengever/inbox/subscribers.py
opengever/inbox/tests/test_inbox.py
opengever/inbox/tests/test_inbox_container.py
opengever/inbox/upgrades/20170502101718_ensure_portlet_configuration_for_inboxes_and_inboxcontainers/upgrade.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default_content/opengever_content/01-initial-structure.json.bob
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/workspaces_content/opengever_content/01-initial-structure.json
opengever/private/configure.zcml
opengever/private/subscribers.py
opengever/private/tests/test_root.py
opengever/private/upgrades/20170502101306_ensure_portlet_configuration/upgrade.py
opengever/setup/cfgs/gever_content.cfg
opengever/setup/profiles/default_content/content_creation/01_default_content.json
opengever/setup/tests/test_default_content.py
opengever/testing/fixtures.py
opengever/testing/tests/test_fixtures.py
opengever/usermigration/tests/test_private_folders_migrator.py
opengever/workspace/configure.zcml
opengever/workspace/subscribers.py
opengever/workspace/tests/test_workspace_root.py
opengever/workspaceclient/tests/test_linked_workspaces.py

With this PR we make sure that placeful workflow policies are assigned automatically for the following content types:
- workspace root
- inbox
- private root
Until now placeful workflow policy assignment relied on having a correct initial content json file. This covers most of the ways that content is created in production but would not have been future-proof when:
- creating the content manually as `Manager`
- importing content via bundle (Policyless or normal bundle)
We change the approach and make sure the application is always in control of correct content type configuration. To achieve so we move placeful workflow policy assignment into an event handler.
We also drop the `placefulworkflowupdater` section from the import pipeline. So content imported with that pipeline from a …

Automatically assign placeful workflow policies when workspace root, private root and inbox are created.

---

changes/CA-1119.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/config.py
opengever/api/tests/test_config.py

For GEVER deployments with multiple repositories, the gever-ui needs to know which is the primary one. Therefore I added the `primary_repository` to the `@config` endpoint.  For https://4teamwork.atlassian.net/browse/CA-1119
In the refinement part of the story it was described that the navigation endpoint should be extended. This would be much more difficult for the UI and above all it would mean that a catalog query for repositoryroots would have to be performed for every route change. Therefore I decided to extend the config endpoint instead.
- API change:

Add primary_repository URL to the @config endpoint.

---

changes/CA-2176.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py

In order to filter correctly in solr, terms containing spaces must be surrounded by quotation marks.
Jira: https://4teamwork.atlassian.net/browse/CA-2176
- API change:

Fix filtering on values containing spaces in @listing endpoint.

---

opengever/api/config.py

Handle sites without a repository root in the config endpoint. This fixes the currently failing UI tests.
_Changelog entry - not necessary_

Fix @config endpoint for sites without a repository root.

---

changes/CA-2220.bugfix
opengever/api/configure.zcml
opengever/api/relationfield.py
opengever/api/tests/test_relationfield.py

plone.restapi's RelationChoiceFieldDeserializer uses restrictedTraverse to fetch relations given by URL or path. But this only works if every single path element is accesssible by the current user. Therefore I customized the Relation deseralizer and fetch the element in the same manner the ZCatalog does - fetch the parent unrestricted and the object itself restricted.
See https://4teamwork.atlassian.net/browse/CA-2220

Fix a problem in relation deserializer when not all path elements are accessible.

---

changes/CA-2306.bugfix
opengever/api/close_remote_task.py
opengever/api/tests/test_close_remote_task.py

This PR fixes an issue where it was not possible to close a remote task without copying documents to a local dossier.
Jira: https://4teamwork.atlassian.net/browse/CA-2306
Follow-Up of: https://github.com/4teamwork/opengever.core/pull/7003
- API change:
- If breaking:

Fix closing remote task without copying any documents to a dossier

---

changes/CA-1994.feature
opengever/api/tests/test_actions.py
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20210525150331_add_move_item_action_for_tasks/actions.xml
opengever/core/upgrades/20210525150331_add_move_item_action_for_tasks/upgrade.py
opengever/dossier/configure.zcml
opengever/dossier/tests/test_move_items.py

For the new frontend, the move_item action should also be available for tasks.
Jira: https://4teamwork.atlassian.net/browse/CA-1994

Add move_item action for tasks.

---

changes/CA-2088.feature
docs/schema-dumps/opengever.repository.repositoryroot.schema.json
opengever/api/tests/test_repository.py
opengever/base/reference_formatter.py
opengever/base/tests/test_default_values_for_types.py
opengever/base/tests/test_reference.py
opengever/bundle/schemas/reporoots.schema.json
opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/en/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/opengever.repository.pot
opengever/repository/reference.py
opengever/repository/repositoryroot.py

This change is necessary in order to have the possibility of having unique reference numbers even when using two repository roots. 
If the field `reference_number_addendum` is changed, `reference` and `sortable_reference` must be reindexed in Solr.
Jira: https://4teamwork.atlassian.net/browse/CA-2088

Add reference_number_addendum field to repository root and use it in reference number

---

changes/CA-1588.other
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py

The `path_parent` field query of the `@solrsearch` endpoint properly resolves paths relative to the virtual host url and joins multiple `path_parent` field queries with an OR operator.
Jira: https://4teamwork.atlassian.net/browse/CA-1588
This change is required because a frontend does not know anything about the physical path of an object which is required to do solr-path queries.
the path indexes of an object is always the physical path:
But a frontend does not know anything about it. I.e.
the url http://www.example.com/examplecontent can point to the same physical path like the url http://localhost:8080/fd/examplecontent =>
http://www.example.com/examplecontent => `/plone/examplecontent`
http://localhost:8080/plone/examplecontent => `/plone/examplecontent`
But we can only extract the …

Properly resolves path_parent field queries for the @solrsearch endpoint if they are relative to the virtual root

---

changes/CA-2060.bugfix
opengever/api/batch.py
opengever/api/dossier_participations.py
opengever/api/ogdslistingbase.py
opengever/api/serializer.py

When sorting according to a non-unique column, response of SQLHypermediaBatches could contain duplicate items and other items could be missing. This is because the sort order of successive queries is not guaranteed to be identical (except when specifically sorting on a key with a unique value for each item).
This issue has been fixed with #6624 for ogds listings but not for all cases we use the SQLHypermediaBatches, therefore i moved the additional sorting on unique key to the SQLHyperMediaBatch itself.
Closes https://4teamwork.atlassian.net/browse/CA-2060

Fix SQLHypermediaBatch for undefined sort orders.

---

changes/CA-2253.bugfix
opengever/task/__init__.py
opengever/task/tests/test_task_checker.py

Otherwise it's not possible to close a sequential_task process, where some task have been skipped.
Close https://4teamwork.atlassian.net/browse/CA-2253

Add skip state to the list of finished task states.

---

changes/CA-2262.bugfix
opengever/core/upgrades/20210519102848_fix_inbox_workflow_policy_assignment/upgrade.py

With this upgrade step we make sure that placeful workflows for inboxes
are assigned in a consistent way across all deployments.
We ensure that:
- every inbox has document and mail placeful workflows assigned
- inbox containers no longer have placeful workflows
Assigning placeful workflows to inboxes is now also done automatically
by the system when an inbox is created as of https://github.com/4teamwork/opengever.core/pull/7012. This PR should ensure consistent state for the future.
Jira: https://4teamwork.atlassian.net/browse/CA-2262

Unify inbox placeful workflow assignment.

---

opengever/mail/browser/inbound.py
opengever/virusscan/testing.py
opengever/virusscan/tests/test_virusscan_validator.py

Of course in https://github.com/4teamwork/opengever.core/pull/7019 I broke the only feature I couldn't really test locally 😓 ...
For https://4teamwork.atlassian.net/browse/CA-1504

Fix inbound mail.

---

changes/CA-2330.bugfix
opengever/api/tests/test_linked_workspaces.py
opengever/workspaceclient/linked_workspaces.py

Jira: https://4teamwork.atlassian.net/browse/CA-2330
This PR fixes an issue where it was not possible to copy a teamraum document back to gever if the target-dossier was classified with a higher classification than the teamraum document.
The fix will increase the classification level of the teamraum document to dossier classification if it does not meet the requirements.
SIde-info: The classification has nothing to do with permissions on the object itself. It's just an informative attribute.
- API change:
- If breaking:
- New …

Fix copy workspace document into a higher classified gever dossier.

---

changes/CA-2075a.other
opengever/api/configure.zcml
opengever/api/login.py
opengever/api/tests/test_login.py
opengever/core/testserver.py

Allows us to authenticate with a cookie instead of a JWT.
We use the @login endpoint only for local development and testing. In production we use ftw.casauth for login.
JIRA: https://4teamwork.atlassian.net/browse/CA-2075

Allow cookie based authentication when using @login endpoint

---

changes/CA-2343.bugfix
opengever/base/handlers.py
opengever/globalindex/handlers/task.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_task_sql_syncer.py

When moving a dossier with a task_process it is not guaranteed that the objects are moved in the tasktemplate order, so it can happen, that the predecessor does not yet exists. Because the intid stays the same after move, its safe to just don't update the predecessor.
Fixes https://4teamwork.atlassian.net/browse/CA-2343

Fixed moving dossier with a tasktemplate process.

---

changes/CA-2089.feature
opengever/base/source.py
opengever/base/tests/test_source_binder.py

Jira: https://4teamwork.atlassian.net/browse/CA-2089
This PR extends the `RepositorySourcePathBinder` to allow moving contents between an old and a new repository-root if the user is within an old repository root.
The implementation differs to the main refinement in the following case:
I have not implemented the registry entry. It behaves like in the frontend: if the user tries to move an object within an old repository root, he is allowed to move it to the new one but not vice versa.
- API change:
- If breaking:
- …

Allow to move dossiers from an old repository root to a new one.

---

changes/CA-2090.other
opengever/core/upgrades/20200429114820_add_is_subdossier_to_catalog_metadata/upgrade.py
opengever/core/upgrades/20201008152233_add_and_index_participations_solr_field/upgrade.py
opengever/core/upgrades/20210128083955_index_blocked_local_roles_in_solr_for_repository_folders_and_dossiers/upgrade.py

I analysed the upgradestep from `2019.6.5` to `master` and optimized two upgradesteps by merging them together to avoid multiple reindexObject specially the catalog metadata updating part, during the the GEVER ZG Release (https://4teamwork.atlassian.net/browse/CA-2090).
Auszug der Analyse:
```
20200427154326@opengever.core:default DEFERRABLE  Always use solr for table source.                                       |  Upgrade: alle Kontakt und alle abgeschlossenen Dossiers -> OK
20200429114820@opengever.core:default DEFERRABLE  Add is_subdossier to catalog metadata.                                  |  Upgrade: alle Dossiers -> Wurde kurzgeschlossen
20200508163000@opengever.core:default ORPHAN      Update filename of mails with file extension msg.                       |  Upgrade: alle *.msg …
```

Upgradestep optimization for ZG Release

---

changes/CA-2246.bugfix
opengever/wopi/browser/edit.py
opengever/wopi/tests/test_edit.py

Resolves https://4teamwork.atlassian.net/browse/CA-2246
I tested it briefly in St. Gallen, works as desired - the Office Online UI is translated correctly.

Add language code parameter to office online edit link.

---

changes/CA-2095.bugfix
opengever/core/upgrades/20210611084449_fix_mail_review_history/upgrade.py

In earlier years of GEVER the opengever_mail_workflow had used `state` instead of `review_state` as state_variable. This leads to an KeyError in plone.restapis WorklowInfo service (see https://sentry.4teamwork.ch/organizations/sentry/issues/69441). This PR adds an upgradestep which fixe the workflow_history for those mails.
https://4teamwork.atlassian.net/browse/CA-2095
The bug has been introduced with 0820123893dd8a4abf85aa3ac3cea78793035be9 and fixed with 3cf26ce1edf9bb665d0df6719d95b9aad32d3d53 so we add additional two years to make sure that the fix has been installed in production.

Cleanup mail workflow_history for mail created before 2016.

---

opengever/ogds/base/locales/fr/LC_MESSAGES/opengever.ogds.base.po
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

Changes in AllUsersInboxesAndTeamsSource
- Users are now additionally sorted by OrgUnit title
- Teams are sorted by team title
- Inboxes are sorted by OrgUnit title
Jira: https://4teamwork.atlassian.net/browse/CA-1989

Change sorting of search results of AllUsersInboxesAndTeamsSource

---

changes/CA-2375.other
opengever/core/upgrades/20210611103928_disable_mail_unwrapping/registry.xml
opengever/core/upgrades/20210611103928_disable_mail_unwrapping/upgrade.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

Unwrapping of inbound mails is rather confusing, notably when there are several attachments to an inbound mail, any of which being an E-mail, it will save that attachment into Gever instead of the whole E-mail. As this behavior is not necessary anymore we simply deactivate it for all deployments.
For https://4teamwork.atlassian.net/browse/CA-2375

Disable unwrapping of inbound mails.

---

changes/CA-2016.feature
opengever/usermigration/base.py
opengever/usermigration/checked_out_docs.py
opengever/usermigration/configure.zcml
opengever/usermigration/creator.py
opengever/usermigration/dictstorage.py
opengever/usermigration/dossier.py
opengever/usermigration/migrations.py
opengever/usermigration/ogds.py
opengever/usermigration/ogds_references.py
opengever/usermigration/plone_tasks.py
opengever/usermigration/private_folders.py
opengever/usermigration/proposals.py
opengever/usermigration/recently_touched.py
opengever/usermigration/task_templates.py
opengever/usermigration/tests/test_creator_migrator.py
opengever/usermigration/tests/test_dictstorage_migrator.py
opengever/usermigration/tests/test_dossier_migrator.py
opengever/usermigration/tests/test_migration.py
opengever/usermigration/tests/test_ogds_references_migrator.py
opengever/usermigration/tests/test_plone_tasks_migrator.py
opengever/usermigration/tests/test_proposals_migrator.py
opengever/usermigration/tests/test_recently_touched_migrator.py
opengever/usermigration/tests/test_task_template_migrator.py

This PR adds support for additional usermigrations using `ftw.usermigration` pre migration hooks.
The following migrations are added:
- `UserSettings` `userid`
- `NotificationSetting` `userid`
- `Favorite` `userid`
- Recently touched objects in Plone site annotations
- Task reminders stored in tasks and ogds
- `TaskTemplate` `responsible`
- `Meeting` `secretary`
- `Proposal` and `SubmittedProposal` `issuer`
We also improve by:
- Adding a base class for all migrations
- Adding a base migration class for plone content object attribute migrations
- Running a migration against the test fixture (currently for one user only)
- Yank out an unused `strict` argument. Pre-migration hooks are called with just mapping and mode https://github.com/4teamwork/ftw.usermigration/blob/9fc23a52dc6e3c95b10e89e …

Implement additional usermigrations.

---

changes/CA-1695.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/searching.rst
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py

Add support to return simple statistics for numeric, string and date fields as specified in the solr documentation at
https://solr.apache.org/guide/8_8/the-stats-component.html.
As with the facet endpoint the query is passed more or less directly to solr. To receive the stats component in the response to solrsearch both enabling it with `stats=true` and passing all the the desired fields by repeating the `stats.field<fieldname>` parameter is necessary.
We take care to not return any statistics for the blacklisted fields.
Jira: https://4teamwork.atlassian.net/browse/CA-1695
- API change:

Support solr stats component in `@solrsearch`.

---

changes/CA-2406.bugfix
opengever/core/upgrades/20210615143823_reindex_customproperties_for_dossier/upgrade.py
opengever/dossier/behaviors/customproperties.py
opengever/dossier/tests/test_indexer.py
opengever/propertysheets/field.py
opengever/propertysheets/tests/test_solr.py

The customproperty field tried to access the dossier_type field directly on the dossier object. But this is not possible because it is part of the IDossier behavior, wich uses AnnotationStorage. So I introduced an additional parameter attribute_interface for the customproperty field.
Fixes https://4teamwork.atlassian.net/browse/CA-2406
- Upgrade steps:

Fix solr indexing of customproperties assigned to a specific dossier_type

---

changes/CA-2417.bugfix
opengever/latex/builder.py
opengever/latex/tests/test_builder.py

Fix two bugs with the `pdflatex` service when sending additional files:
- Instead of the file content we would just send the path to the file
- We would not send the filename, leading to every file be prefixed with `.file` upon save. This broke references to the file.
I have opted to read the file myself before passing it to requests to be in control of closing the file once it is read. Requests does not take care of this and reading the files in a context manager guarantees that we are in control of closing. I am expecting the files to be relatively small (logos for headers and footers, for example).
Jira: https://4teamwork.atlassian.net/browse/CA-2417

Fix sending additional files to pdflatex service.

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/en/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po

The pre-increment lead to some confusion and users assigning the wrong numbers. This is only used internally by managers so instead of changing how we calculate the numbers i'm hoping that a better description may prevent future errors.
_IMO no CL entry necessary, will amend if the reviewer is of different opinion._
- ~~Changelog entry~~
- ~~Link to issue (Jira or GitHub) and backlink in issue (Jira)~~

Clarify sequence number descriptions for periods.

---

opengever/trash/tests/test_trash.py
opengever/trash/trash.py

Follow-up of https://github.com/4teamwork/opengever.core/pull/7045. We forbid to trashed already trashed objects, but that check should not happen recursively. Indeed it should be allowed to trash a document in a folder, and later decide to trash that folder too. We fix this with this PR.
For https://4teamwork.atlassian.net/browse/CA-981

Fix trashing of workspace folders containing trashed objects

---

changes/CA-438.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/configure.zcml
opengever/api/task.py
opengever/api/tests/test_task.py

By registering a specific PATCH service for tasks, which raises if the is_private changes.
Fixes https://4teamwork.atlassian.net/browse/CA-438

Prevent changing the is_private field of existing tasks via API.

---

changes/CA-2247.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/add.py
opengever/api/configure.zcml
opengever/api/tests/test_document.py
opengever/api/tests/test_tus.py
opengever/api/tus.py
opengever/quota/browser/error.py

Fixes https://4teamwork.atlassian.net/browse/CA-2247, different from what is described in the JIRA issue, I also corrected the TUS upload, because that is the one that is used in the gever-ui.
- API change:

Improve error handling when quota limit gets exceeded on API requests.

---

opengever/dossier/resolve.py
opengever/dossier/tests/test_archiver.py
opengever/testing/services.py
opengever/testing/tests.zcml

This PR:
- introduces a new rest-api testing view to install the filing-number profile in e2e tests
- fixes an issue where it was no longer possible to resolve a dossier with subdossiers
Jira: https://4teamwork.atlassian.net/browse/CA-2090
- API change:
- If breaking:

Dossier resolving with filing-number follow-up for e2e tests

---

changes/CA-2394.bugfix
opengever/api/configure.zcml
opengever/api/tests/test_users.py
opengever/api/users.py

Jira: https://4teamwork.atlassian.net/browse/CA-2394
This PR extends the `@users/<userid>` endpoint to handle profile image deletion.
I did not document it in the api-doc since this is the way how it should work by default.
- API change:
- If breaking:

Fix removing a profile-image with a PATCH request to the `@users/<userid>` endpiont.

---

changes/CA-2476.other
opengever/oneoffixx/utils.py

Currently OneOffixx Funktionsvorlagen gets filtered out by our own templatetype-whitelist, but these are also desired.
See https://4teamwork.atlassian.net/browse/CA-2476

Add oneoffix "Funktionsvorlagen" to the whitelisted template types.

---

changes/CA-2424.bugfix
changes/CA-2450.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/move.py
opengever/api/tests/test_move.py
opengever/base/adapters.py
opengever/base/configure.zcml
opengever/base/interfaces.py
opengever/document/configure.zcml
opengever/document/move.py
opengever/dossier/move_items.py
opengever/dossier/templatefolder/utils.py
opengever/dossier/tests/test_move_items.py
opengever/inbox/utils.py
opengever/private/utils.py
opengever/repository/utils.py

Until now, documents could be moved via API even though they were in a task, for example. This is now restricted.
Jira: https://4teamwork.atlassian.net/browse/CA-2424 and https://4teamwork.atlassian.net/browse/CA-2450
- API change:
- If breaking:

Restrict document move via API

---

changes/CA-2462.other
docs/public/dev-manual/api/config.rst
opengever/activity/browser/settings.py
opengever/activity/handlers.py
opengever/api/notification_settings.py
opengever/api/tests/test_config.py
opengever/api/tests/test_notification_settings.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20210629072407_remove_document_watcher_feature_flag/registry.xml
opengever/core/upgrades/20210629072407_remove_document_watcher_feature_flag/upgrade.py
opengever/document/__init__.py
opengever/document/handlers.py
opengever/document/interfaces.py
opengever/document/tests/test_activities.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
opengever/testing/integration_test_case.py

Document watcher feature flag is no longer needed.
Jira: https://4teamwork.atlassian.net/browse/CA-2462
- API change:

Remove document watchers feature flag.

---

opengever/core/upgrades/20200501143003_populate_additional_metadata_of_favorites/upgrade.py
opengever/core/upgrades/20200730094255_fix_docs_only_partially_indexed_in_solr/upgrade.py
opengever/core/upgrades/20200817143709_reindex_container_modified_during_bundle_import/upgrade.py

A not very smart upgrade step, triggering the processing of the indexing queue for every object reindexed, has already been copied twice. To avoid copying it again in the future, I've added a comment in these upgrade steps.
For https://4teamwork.atlassian.net/browse/CA-2091

Add comment in inefficient upgrade steps.

---

changes/CA-2336.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/trigger_task_template.rst
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py
opengever/tasktemplates/tasktemplatefolder.py

Allow overriding task and subtask deadline field in the @trigger-task-template endpoint, so that users can set this attribute in a batch add form in the new UI.
Jira: https://4teamwork.atlassian.net/browse/CA-2336
- API change:

Allow overriding task and subtask deadline in @trigger-task-template endpoint

---

changes/CA-2492.bugfix
opengever/contact/sources.py
opengever/contact/tests/test_sources.py

Jira: https://4teamwork.atlassian.net/browse/CA-2492
The `ContactSource` object is used by the `@participation` endpoint if the `contact` feature is enabled. Currently, the source requires an id to lookup in a kind of an actor id with `type:id`. But it's not an actor because there are completely custom types used for the source.
In the frontend, 1. we can't use actors since the api does not return actor-ids consistently and 2. using actors would not work, because the contact source does only need a kind of an actor, not an actor 🙈 .
So to go straight, this PR just assumes that we want to lookup an `ogds_user` if there is no given actor prefix. …

ContactsSource fallbacks to `ogds_user` type if no type is explicitly given.

---

changes/CA-2338-2.feature
opengever/api/tests/test_vocabularies.py
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20210705111629_allow_authenticated_users_to_access_vocabularies_via_api/rolemap.xml
opengever/core/upgrades/20210705111629_allow_authenticated_users_to_access_vocabularies_via_api/upgrade.py

With PR #5580 the vocabulary endpoint was made accessible for all Members. But for requests on a foreign admin_unit, the user only has the `Authenticated` Role but still need to access vocabularies, for example the `SupportedContentLanguages` vocabulary. 
Opening the endpoint for AuthenticatedUsers is not problematic, because all critical information (users, groups etc.) are visible for the whole client group anyway or their contents are only visible for users with access rights anyway (see #5449 for more information). Furthermore a test ensures that no new vocabularies with sensitive data are made accessible.
For https://4teamwork.atlassian.net/browse/CA-2338

Allow authenticated users to access vocabularies via API.

---

changes/CA-2338.feature
opengever/api/config.py
opengever/api/configure.zcml
opengever/api/serializer.py
opengever/api/tests/test_config.py

Used to display current app information in the gever-ui (see https://4teamwork.atlassian.net/browse/CA-2338).
Currently org_units are not really accessible directly via REST, so the `@id` in the endpoint ist not really an URL - but I think thats not a problem for now.

Include information about the current admin_unit in the config endpoint.

---

changes/CA-2364.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/navigation.rst
opengever/api/navigation.py
opengever/api/tests/test_navigation.py

In the new UI it should be possible to display only the active dossiers in the dossier structure. However, the current dossier should also be displayed in the dossier structure if it has an inactive review state but only the active dossiers are displayed. This is ensured with the include_context parameter.
Jira: https://4teamwork.atlassian.net/browse/CA-2364
- API change:

Add review_state and include_context parameter to @navigation endpoint.

---

changes/CA-2553.bugfix
opengever/dossier/tests/test_documents_tab.py
opengever/tabbedview/browser/base_tabs.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/catalog_source.py
opengever/tabbedview/tests/test_dossier_listing.py

The provided fix just fixes the issue for tabbedview/table based listings in the classical UI.
It works around the fact that the Solr based source does not always have all contents loaded to apply batching but uses Solr side batching. This breaks an assumption in the catalog based "select all" functionality which seems to expect an unbatched list of all brains being available.
As a workaround we tell the source that we want all results. The query will be optimized and will only query for the `path` field. I have tested it locally on a dossier with 20k documents. Returning the selected paths to the frontend seems performant enough so that i can bump the hard-coded maximum to 100k.
Jira: https://4teamwork.atlassian.net/browse/CA-2553 …

Fix selecting all items for Solr based listings.

---

changes/CA-2528.feature
opengever/mail/browser/download.py
opengever/mail/tests/test_mail_download.py
opengever/mail/tests/test_mail_download_copy.py

The view decides independently whether original message or eml file is returned and does no longer require a fieldname as additional url paramenter. This allows the frontend to just call a view and not handle the businesslogic by them self.
For https://4teamwork.atlassian.net/browse/CA-2528 

Provide field unspecific mail download view

---

opengever/core/upgrades/20210609085047_add_document_watcher_feature_flag/upgrade.py

Follow up for https://github.com/4teamwork/opengever.core/pull/7067
Since the feature flag has been removed again, this upgrade step no longer works because the field no longer exists on the IDocumentSettings interface.

Fix upgrade step.

---

changes/CA-2036.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/proposals.rst
opengever/api/configure.zcml
opengever/api/proposal.py
opengever/api/task.py
opengever/api/tests/test_proposal.py
opengever/meeting/browser/submitdocuments.py
opengever/meeting/command.py

We add a new `@submit-additional-documents` endpoint.
The endpoint takes as input parameter a list of document UIDs. This avoids the whole problem with dealing with absolute urls and should not be a problem for the frontend, which also has the UIDs from the content selector.
I was a bit more indecisive regarding the response. Because depending on whether a given document was already submitted or not, the document will either be copied to the submitted proposal, updated with a new version or nothing will be done, I deemed it necessary to include the performed action for each document in the response. The response is there fore a list of dictionaries. For each document it returns its URL and the performed action:
```
[{"source" : url, "action": "copied"}]
``` 
The URL is under the "source" …

Add new @submit-additional-documents endpoint.

---

changes/HG-1488.other
opengever/setup/serviceuser.py
opengever/setup/tests/test_serviceuser.py
setup.py

Currently creating a service user involves some manual steps to be done through a web interface. With this PR we add a script to easily create a service user and merge the following separate steps into one command to be called on the command line:
- create a user in plone with a random password
- assign the user to some predefined roles
- create a service key (`ftw.tokenauth`) and store it in a `*.json` file
The command
```bin/instance create_service_user workspace.app --roles Member WorkspaceAdmin Impersonator --service-key-title "teamraum connect"```
will automatically create a user `workspace.app` and also create a corresponding key. They key will be written to a json file in `$CLIENTHOME` (`.var/instance/workspace.app.json`) on a dev machine. They key will be available for the new …

Add script to create service users

---

changes/CA-1213.other
opengever/policytemplates/policy_template/opengever.+package.name+/setup.py.bob

I'm currently removing all the tika dependencies from our saas policies, so the policytemplate should not create new ones 😉 
Part of CA-1213
_Removing and uninstalling tika will follow in a separate PR_

Remove ftw.tika dependency from the policytemplate.

---

changes/CA-2019-1.feature
changes/CA-2019-2.feature
docs/public/dev-manual/api/accept_remote_forwarding.rst
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
opengever/api/accept_remote_forwarding.py
opengever/api/accept_remote_task.py
opengever/api/close_remote_task.py
opengever/api/configure.zcml
opengever/api/remote_task_base.py
opengever/api/tests/test_accept_remote_forwarding.py
opengever/api/transition.py
opengever/inbox/browser/refuse.py
opengever/inbox/configure.zcml
opengever/inbox/tests/test_api_support.py
opengever/inbox/transition.py

- Add `@accept-remote-forwarding` endpoint to accept cross client forwardings
- Move refuse transition functionalities to a transition extender for `forwarding-transition-refuse` transition, this way we can refuse forwardings via API
- Add transition_response to POST `@workflow` endpoint, so that we can return the url of the forwarding that will be created when a forwarding is refused. This allows redirecting to the new forwarding after the transition in the new front end.
For [CA-2019]
- API change:
[CA-2019]: https://4teamwork.atlassian.net/browse/CA-2019

Enable cross-client transitions via API for forwardings.

---

changes/CA-2472.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_trash.py
opengever/api/trash.py

Since the error message `The document has been returned as excerpt` was not caught, a `204 No content` was returned in this case.
Now an error message is always returned in case of an error.
For [CA-2472]
- API change:
- If breaking:
[CA-2472]: https://4teamwork.atlassian.net/browse/CA-2472

Always return error message in @trash endpoint if content is not trashable

---

changes/CA-2627.bugfix
opengever/inbox/configure.zcml
opengever/inbox/tests/test_accept.py
opengever/inbox/tests/test_activities.py
opengever/inbox/tests/test_transition_extender.py
opengever/task/browser/accept/utils.py
opengever/task/browser/store.py
opengever/task/tests/test_transition_extender.py

The transition extender was not registered for that transition so user input text was discarded.
I have also added a quick test for all task and forwarding transitions to make sure we have extenders registered correctly for all other transitions. Luckily this seems to be the case (or not required for one task transition).
For https://4teamwork.atlassian.net/browse/CA-2627
The text is now persisted ans shows up as expected:

Fix storing text when accepting a forwarding.

---

changes/CA-CA-1885.other
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

Use correct defaults for groups assignments for Teamraum deployments and make `invitaiton_group_dn` non-mandatory, is this typically should not be set for on-premise deployments where the `invitaiton_group_dn` is different for TEST and PROD deployments. It will anyway correctly default to the users group, i.e. `tr_users` in Gever (see https://github.com/4teamwork/opengever.core/blob/master/opengever/workspace/participation/browser/my_invitations.py#L93-L117).
For [CA-1885]
[CA-1885]: https://4teamwork.atlassian.net/browse/CA-1885

Improve policy templates for Teamraum deployments.

---

changes/CA-2623.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/tests/test_history.py

The initial version is created lazily so documents that have not been touched in any way after adding do not have an initial version. We handle this case by returning the document itself as the initial version.
For https://4teamwork.atlassian.net/browse/CA-2623
- API change:

Fix retrieving lazy initial version for documents.

---

changes/CA-2362.feature
opengever/base/browser/configure.zcml
opengever/base/browser/role_assignment_excel_report.py
opengever/base/reporter.py
opengever/base/tests/test_role_assignment_excel_report.py

For [CA-2362](https://4teamwork.atlassian.net/browse/CA-2362)
Uses the already existing XLSReporter. Because the role-assignment report ist not a real object, I did not register a portal_action, instead the action is defined in the frontend.

Add excel role assignment-report generation and download view.

---

changes/CA-2623-1.bugfix
opengever/base/viewlets/download.py
opengever/document/tests/test_download.py
opengever/virusscan/tests/test_virusscan_validator.py

The initial version is created lazily so documents that have not been touched in any way after adding do not have an initial version. We handle this case by retrieving the file version from the document itself.
I've seen that input validation in the view has not been done so nicely and could result in 500 range server side errors. I have amended to turn them into 400 client side errors where possible.
This is a follow-up for https://github.com/4teamwork/opengever.core/pull/7097 which only fixes one part of the issue.
For https://4teamwork.atlassian.net/browse/CA-2623

Fix download lazy initial version for documents.

---

changes/CA-1822.bugfix
opengever/document/base.py
opengever/mail/mail.py
opengever/mail/tests/test_extract_attachments.py

Mail attachments for mails inside a submitted proposal got extracted into the proposal dossier, which does not make sense. Instead we extract the attachments into the submitted proposal.
For [CA-1822]
[CA-1822]: https://4teamwork.atlassian.net/browse/CA-1822

Extract attachments from mail inside submitted proposal into parent.

---

docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/linked_workspaces.rst
opengever/api/configure.zcml
opengever/api/linked_workspaces.py
opengever/api/tests/test_actions.py
opengever/base/browser/folder_buttons_availability.py
opengever/base/tests/test_solr.py
opengever/core/hooks.py
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/en/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/profiles/default/catalog.xml
opengever/core/upgrades/20210728095648_add_unlink_workspace_action/actions.xml
opengever/core/upgrades/20210728095648_add_unlink_workspace_action/upgrade.py
opengever/core/upgrades/20210730105957_add_gever_doc_uid_catalog_index/catalog.xml
opengever/core/upgrades/20210730105957_add_gever_doc_uid_catalog_index/upgrade.py
opengever/document/tests/test_copy_document.py
opengever/dossier/tests/test_move_items.py
opengever/workspaceclient/client.py
opengever/workspaceclient/config.py
opengever/workspaceclient/configure.zcml
opengever/workspaceclient/hooks.py
opengever/workspaceclient/indexers.py
opengever/workspaceclient/linked_documents.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_client.py
opengever/workspaceclient/tests/test_linked_documents.py
opengever/workspaceclient/tests/test_linked_workspaces.py

I made the following decisions:
- Becuase the "gever-workspace-link" ist not really traversable, I decided against a `DELETE` endpoint and implemented a `@unlink-workspace` POST endpoint.
- We don't remove the linked document, so if a workspcae gets unlinked and linked again, the linked documents can be copied as new version to the GEVER dossier. But existing locks will always be unlocked, when unlinking a workspace.
- Because a GEVER dossier can have multiple linked workspaces, we need to know which documents belongs to which workspace, to make sure only those document-locks get unlocked. Therefore I added a new catalog index and metadata `gever_doc_uid` on the workspace side, which stores the UID of the linked gever document. This allows GEVER with a request on the workspace an a query …

Add API endpoint to unlink a workspace from a dossier.

---

changes/CA-2108.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/configure.zcml
opengever/api/repositoryfolder.py
opengever/api/tests/test_delete.py
opengever/dossier/handlers.py
opengever/repository/configure.zcml
opengever/repository/handlers.py
opengever/repository/subscribers.py

We enable deletion of empty repository folder over the REST-API.
For [CA-2108]
- API change:
- If breaking:
[CA-2108]: https://4teamwork.atlassian.net/browse/CA-2108

Allow deleting repository folders over the REST-API.

---

opengever/api/configure.zcml
opengever/api/linked_workspaces.py
opengever/api/tests/test_list_linked_documents_from_workspace.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_linked_workspaces.py

Follow up for PR #7102  Make API endpoint `@list-linked-gever-documents-uids` accessible for all with view permission. GEVER Users does not have the role `WorkspaceClientUser` on the teamraum side in a regular GEVER <-> temraum setup, but only in the development setup. Also the endpoint queries the UIDs now unrestricted to make sure every linked documents gets unlocked.
If the gever user does not have permission on all linked gever documents, the method raises an `BadRequest`, so unlinking is not possible for this user.
For [CA-2392]
- Changelog already added in the previous commit.
[CA-2392]: https://4teamwork.atlassian.net/browse/CA-2392

Fix permission issue when unlinking a workspace.

---

changes/CA-2468.bugfix
opengever/base/handlers.py
opengever/base/tests/test_favorite.py
opengever/core/upgrades/20210806151730_fix_favorite_positions/upgrade.py

When an object is deleted or trashed, the associated favorites get deleted. This led to the position of the favorites for the concerned users to not be a gapless sequence from 0 to n, which in turn breaks reordering of the favorites.
This is fixed here by ensuring that favorite positions get updated when an object is trashed or deleted. We also add an upgrade step to fix broken `Favorite.position` sequences.
Note that I made the upgrade step a `SchemaMigration` so that it only happens once.
For [CA-2468]
[CA-2468]: https://4teamwork.atlassian.net/browse/CA-2468

Fix update of favorites when trashing / deleting an object.

---

changes/CA-2683.bugfix
opengever/core/upgrades/20210809142703_sync_task_reminders/upgrade.py
opengever/task/reminder/reminder.py
opengever/task/task.py
opengever/task/tests/test_reminder.py

Setting a reminder over the accept form was not working correctly, because the reminder was set after the changes to the task were synced (which happens on the `IObjectModifiedEvent`: https://github.com/4teamwork/opengever.core/blob/master/opengever/globalindex/handlers/configure.zcml#L9-L13). This could lead to the notification not being generated if the task wasn't modified, and hence synced again, before the reminder day...
Because this might be an issue in other situations as well, we sync the reminders synchronously every time a reminder is set.
For [CA-2683]
[CA-2683]: https://4teamwork.atlassian.net/browse/CA-2683

Fix setting reminder over accept form.

---

changes/CA-2649.bugfix
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py
opengever/base/behaviors/translated_title.py
opengever/base/tests/test_translated_title.py

We fix returning the translated title in the `listing` and `solrsearch` endpoints. The check that we were making to decide whether to return a translated title was never passing, as `OGSolrContentListingObject` does not support `providedBy`.
For [CA-2649]
[CA-2649]: https://4teamwork.atlassian.net/browse/CA-2649

Fix returning translated title in solrsearch and listing endpoints.

---

changes/CA-2708.bugfix
opengever/activity/browser/templates/notification_mail_macros.pt
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20210812105425_remove_view_atat_prefix_for_personal_preferences_for_new_ui_compatibility/actions.xml
opengever/core/upgrades/20210812105425_remove_view_atat_prefix_for_personal_preferences_for_new_ui_compatibility/upgrade.py

With this PR we drop the `@@` prefix from links to the personal preferences browser view in two places:
- From the link in notification mails
- From the action url displayed in the personal navigation menu
Dropping the prefix will prevent the URL being handled by rewrite rules redirecting requests to the backend regardless of the cookie enabling/disabling the new UI. It is intended to work in combination with https://github.com/4teamwork/gever-ui/pull/1887 and fix/improve URL handling to notification settings in the following cases:
- Links from the mail should work on both the classical and new UI (for GEVER) and for the new UI (for temaraum)
- Handling works when changing the UI from classical to new (We've decided against special handling for the inverted case as this switch is not …

Remove `@@` prefix from links to personal preferences browser view.

---

changes/CA-2543_1.feature
changes/CA-2543_2.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/proposals.rst
opengever/api/document.py
opengever/api/proposal.py
opengever/api/tests/test_document.py
opengever/api/tests/test_proposal.py

In the metadata overview of proposals and documents in the new frontend, some metadata concerning the SPV is still missing. In order to display them, some additional fields are needed.
For [CA-2543]
- API change:
[CA-2543]: https://4teamwork.atlassian.net/browse/CA-2543

Include SPV metadata in document and proposal serialization

---

changes/CA-2235.other
opengever/activity/browser/resolve.py
opengever/activity/model/notification.py
opengever/activity/tests/test_resolve.py

Change the current behavior to always redirect to notification resource in `@@resolve_oguid` if user has permission to view the resource, even for foreign notifications. The  previous behavior was to return an error if the notification was not visible for the current user. The change adds more convenience in case the link to the notification is
shared between users unintentionally (e.g by forwarding a mail).
For https://4teamwork.atlassian.net/browse/CA-2235

Redirect to notification resource while resolving.

---

changes/CA-2688.bugfix
opengever/base/handlers.py
opengever/base/tests/test_favorite.py

Fix updating document title in favorites when document title is changed via API request. The api seems to choose a different interface here (IMO the correct one) and our changed detection heuristic did not pick it up correctly.
I am also adding a separate test for dossier favorite titles which can also change. This should cover the two most important use-cases. Task titles can't really change and repo favorites are handled differently anyway.
For https://4teamwork.atlassian.net/browse/CA-2688

Fix updating document title in favorites with API.

---

changes/CA-2350.other
opengever/core/upgrades/20210205084521_add_sortable_reference_number_index/upgrade.py
opengever/core/upgrades/20210601180416_update_reindex_reference_and_sortable_reference_index/upgrade.py

Merging the older upgrade step reindexing sortable_reference with a newer one is counterproductive. Indeed this leads to indexing all sortable_reference numbers in solr a second time for deployments that are on a version between 2021.4 and 2021.12. Indeed the upgrade adding the `sortable_reference` index was included in 2021.4 ( https://github.com/4teamwork/opengever.core/pull/6732) and the upgrade steps were merged in 2021.12 (https://github.com/4teamwork/opengever.core/pull/7029). This is notably the case for SG...
For [CA-2350]
[CA-2350]: https://4teamwork.atlassian.net/browse/CA-2350

Revert merge of upgrade reindexing reference and sortable_reference.

---

changes/CA-2267.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/listing.py
opengever/api/tests/test_listing.py
opengever/document/approvals.py
opengever/document/checkout/manager.py
opengever/document/configure.zcml
opengever/document/indexers.py
opengever/document/tests/test_approvals.py
opengever/document/tests/test_indexers.py
opengever/document/versioner.py
opengever/tabbedview/tests/test_personaloverview.py
opengever/task/tests/test_principals.py
opengever/testing/fixtures.py
solr-conf/managed-schema

This adds
- a method `ApprovalList.get_approval_state()` to determine the current `approval_state` of a document based on the contents of the approval lists in annotations
- plus the corresponding **Solr index** `approval_state`
- and the **indexer** on the Plone side.
Currently I only made sure the `approval_state` index is _updated_ in Solr when a document gets **reverted**. But we maybe should also fix the approval lists when a document gets reverted to a version that has previously been approved, similar to what is being done when a document is copied. 
⚠️ So right now, reverting to a document version that has previously been approved will not retain that approval state, and the document will therefore be "approved in an older version".  
For …

Add Solr field approval_state plus corresponding indexer and logic 

---

changes/CA-2096.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/reference_numbers.rst
opengever/api/configure.zcml
opengever/api/reference_numbers.py
opengever/api/tests/test_reference_numbers.py
opengever/base/adapters.py
opengever/base/exceptions.py
opengever/repository/browser/referenceprefix_manager.py

Add new @reference-numbers `GET` and `DELETE` endpoints for administrators. The `GET` returns a list of all reserved positions on a given context, while the `DELETE` endpoint allows to liberate an inactive position (position that was previously in use but is not used any longer).
For [CA-2096]
- API change:
- If breaking:
[CA-2096]: https://4teamwork.atlassian.net/browse/CA-2096

Add new @reference-numbers endpoint.

---

opengever/core/upgrades/20210810115730_reindex_missing_changed_date/upgrade.py

💦 💦 I misspelled the `unrestricted_search` method and apparently did not test the upgrade again after implementing that method in `ftw.solr`... 💦 💦 
For [CA-1335]
[CA-1335]: https://4teamwork.atlassian.net/browse/CA-1335

Fix failing upgrade step.

---

changes/CA-2132.other
opengever/bumblebee/tests/test_revive_bumblebee_preview.py
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20210818101411_allow_reader_to_revive_bumblebee_previews/rolemap.xml
opengever/core/upgrades/20210818101411_allow_reader_to_revive_bumblebee_previews/upgrade.py

Allow users with the `Reader` role to revive bumblebee previews. Previously this was limited to admins and managers but there is not really a reason to do so.
Tests are done with the regular user though as reader must be set up for each test case. Testing with the regular user covers the common use case better and is thus IMO preferrable.
For [CA-2132](https://4teamwork.atlassian.net/browse/CA-2132)

Allow Reader to revive bumblebee previews.

---

changes/CA-2670.bugfix
opengever/api/tests/test_actions.py
opengever/base/browser/folder_buttons_availability.py

For [CA-2670]
With https://github.com/4teamwork/gever-ui/pull/1894 the frontend is always calling the endpoints on the main dossier.
[CA-2670]: https://4teamwork.atlassian.net/browse/CA-2670

Show copy document to workspace action also in subdossiers.

---

changes/CA-2269.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/tasks.rst
opengever/api/tests/test_forwarding.py
opengever/api/tests/test_task.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/en/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/sources.py
opengever/task/task_response.py
opengever/task/tests/test_api_support.py
opengever/task/tests/test_sources.py
opengever/task/transition.py
opengever/task/util.py

This allows to supply an additional transition parameter `approved_documents` with UIDs of documents that should be approved when executing the `@workflow` transition `task-transition-in-progress-resolved` for a task with task_type `approval`.
Example:
```http
POST /dossier-20/task-5/@workflow/task-transition-in-progress-resolved
{
"text": "Ich genehmige diese Dokumente",
"approved_documents": [
"7dce9cda657f41d883b72c66ce718034"
]
}
```
Any approved documents will be referenced from the TaskResponse that is generated when resolving the task. The response serialization then includes these approved documents:
_(Responses can be accessed via `task-5/@responses/<response_id>` or as part of the regular task `GET`, like in this example)._ 
```json
{
"...": "...",
"responses": [
{"...": "..."}, …
```

API: Allow for approving documents when resolving a task.

---

changes/CA-1923_1.feature
changes/CA-1923_2.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/workspace/actual_workspace_members.rst
docs/public/dev-manual/api/workspace/share_content.rst
opengever/api/actual_workspace_members.py
opengever/api/share_content.py
opengever/api/tests/test_actual_workspace_members.py
opengever/api/tests/test_config.py
opengever/api/tests/test_invitation.py
opengever/api/tests/test_share_content.py
opengever/base/tests/test_configuration_adapter.py
opengever/ogds/base/sources.py
opengever/sharing/tests/test_sharing.py
opengever/testing/fixtures.py
opengever/workspace/tests/test_workspace_sources.py
opengever/workspace/utils.py
opengever/workspace/vocabularies.py

- The `ActualWorkspaceMembersSource` is extended so that the users of groups are also included
- With the parameter `include_groups` groups can now be included in the `@actual-workspace-members` endpoint
-  The `@share-content` endpoint can now handle groups
For [CA-1923]
- API change:
- If breaking:
[CA-1923]: https://4teamwork.atlassian.net/browse/CA-1923

Add support for groups in @share-content endpoint.

---

changes/CA-2401_2.other
opengever/api/dossier.py
opengever/api/tests/test_dossier.py

This PR exposes the `is_protected` in the dossier serializer which is required for the new UI.
For [CA-2401]
- API change:
- If breaking:
[CA-2401]: https://4teamwork.atlassian.net/browse/CA-2401

Expose `is_protected` in the dossier serializer.

---

changes/CA-2401.other
opengever/api/tests/test_actions.py
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20210819233605_add_protect_dossier_action/actions.xml
opengever/core/upgrades/20210819233605_add_protect_dossier_action/upgrade.py
opengever/dossier/tests/test_dossier_workflow.py

This PR adds a new object-button action `protect_dosser` which is required for the new UI to decide if the current user is allowed to protect the dossier.
For [CA-2401]
- API change:
- If breaking:
[CA-2401]: https://4teamwork.atlassian.net/browse/CA-2401

Add new object-button action `protect_dossier`

---

changes/CA-2767.other
docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc
docs/schema-dumps/opengever.repository.repositoryfolder.schema.json
opengever/bundle/schemas/repofolders.schema.json
opengever/repository/behaviors/referenceprefix.py
opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/en/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/opengever.repository.pot
opengever/repository/tests/test_reference_behavior.py
opengever/repository/tests/test_subscribers.py

This renames the label for the `reference_number_prefix` field (previously labelled `Reference prefix`) to 
- `Repository number` (English)
- `Ordnungspositionsnummer` (German)
- `Numéro de classement` (French)
The internal name of the field in technical contexts (code base, API, ...) is left untouched.
Since the frontend fetches the field labels from the schema, this will result in the field label changing in **user facing** contexts, like the add view for a new repository folder:
For [CA-2767](https://4teamwork.atlassian.net/browse/CA-2767)
- API change:

Rename label for "Reference prefix" to "Repository number" (en, de, fr)

---

changes/CA-371.bugfix
opengever/api/configure.zcml
opengever/api/serializer.py
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/relation_fields.py
opengever/core/upgrades/20210819081602_clean_up_relation_catalog/upgrade.py
opengever/document/document.py
opengever/document/tests/test_behaviors.py
opengever/document/tests/test_document.py
opengever/dossier/browser/overview.py

We fix the handling of relations when deleting an object. There were 2 main issues:
- The `z3c.relationfield` only handles fields stored on the object, while we store our relations in the annotations
- When the `to_object` of a relation is deleted, the relation remains in the catalog, but is marked as broken. We did not handle that case anywhere (API, overviews, etc).
I fixed the event handlers, so that relations get deleted from the catalog when the `from_object` is deleted. 
I also fixed the serializer, so that broken relations are not serialized to the frontend, so that we don't have to handle that case everywhere in the frontend (before they got serialized as `None`, so for a relation list `[None]`). 
I also added handling of broken relations for documents (and all derived types), as …

Fix handling of relations when an object is deleted.

---

HISTORY.rst

Every time I do a backport I'm annoyed with our lack of convention concerning backports. I think there is only one way of doing this correctly, which is having dupplicate entries and consider every PATCH version to not be included in the following MAJOR and MINOR versions. This is the only way to reflect the reality of how we work, i.e. with diverging branches for PATCH versions...
For [CA-2690]
[CA-2690]: https://4teamwork.atlassian.net/browse/CA-2690

Clarify changelog conventions for backports.

---

opengever/api/complete_successor_task.py
opengever/api/tests/test_complete_successor_task.py
opengever/task/browser/complete_utils.py

The approval of a document with a task is now also supported for the `@complete-successor-task` endpoint, which solves an issue when resolving a multi adminunit task for approval.
The endpoint does not sync or copy the approval to the predecessor site, but it handles a stores the approval on the successor site.
For [CA-2269]
[CA-2269]: https://4teamwork.atlassian.net/browse/CA-2269

Fix resolving of multi adminunit tasks for approval.

---

changes/CA-1629.feature
docs/public/dev-manual/api/actors.rst
docs/public/dev-manual/api/api_changelog.rst
opengever/api/actors.py
opengever/api/tests/test_actors.py
opengever/inbox/utils.py
opengever/ogds/base/actor.py

Include the following properties in the `@actors` endpoint:
- `@type`
- `active`
- `portrait_url`
- `representatives`
- `respresents`
This allows us to use a generic Actor component in the frontend which resolves additional information using the `@actors` endpoint for displaying actors (users, groups, inboxes, teams, ...).
JIRA: https://4teamwork.atlassian.net/browse/CA-1629
- API change:

Extend actors endpoint

---

changes/CA-2757.other
opengever/base/behaviors/configure.zcml
opengever/base/behaviors/lifecycle.py
opengever/base/tests/test_lifecycle.py

The value restriction on the custody_period field is no longer desired.
The PR replaces the RestrictedVocabulary with a SimpleVocabulary, with this changes also the value_propagation for no longer valid values is redundant.
For [CA-2757]
[CA-2757]: https://4teamwork.atlassian.net/browse/CA-2757

Remove value restriction for the custody_period field.

---

changes/CA-2777.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/users.rst
opengever/api/configure.zcml
opengever/api/reactivate_local_group.py
opengever/api/tests/test_reactivate_local_group.py

Until now, local groups can only be deactivated, but not reactivated. With the endpoint @reactivate-local-group they can now also be reactivated.
For [CA-2777]
- API change:
[CA-2777]: https://4teamwork.atlassian.net/browse/CA-2777

Add @reactivate-local-group endpoint.

---

changes/CA-1957.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/propertysheets.rst
opengever/api/tests/test_listing_custom_fields.py
opengever/base/monkey/patches/default_values.py
opengever/document/indexers.py
opengever/document/tests/test_indexers.py
opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py
opengever/propertysheets/definition.py
opengever/propertysheets/serializer.py
opengever/propertysheets/tests/test_document_custom_properties.py
opengever/propertysheets/tests/test_dossier_custom_properties.py
opengever/propertysheets/tests/test_mail_custom_properties.py
opengever/propertysheets/tests/test_schema_definition_post.py
opengever/propertysheets/tests/test_serializer.py
opengever/propertysheets/tests/test_solr.py
opengever/propertysheets/tests/test_widget.py
opengever/testing/fixtures.py
solr-conf/managed-schema

Adds new customfield type `multiple_choice`, which allows to select multiple values from a list of strings.
For [CA-1957]
- API change:
[CA-1957]: https://4teamwork.atlassian.net/browse/CA-1957

Support multiple choice custom fields.

---

changes/CA-2370.bugfix
opengever/document/fileactions.py
opengever/document/tests/test_fileactions.py

Since the edit_office_online action used the lock token to determine if a document was checked out collaboratively, the action was no longer available when the lock was removed.
For [CA-2370]
[CA-2370]: https://4teamwork.atlassian.net/browse/CA-2370

Allow editing of a document with Office Online even if the document is not locked

---

changes/CA-2774.bugfix
opengever/dossier/behaviors/protect_dossier.py
opengever/dossier/tests/test_protect_dossier.py

Since it is not possible to authorize users through the `reading` and `reading_and_writing` fields if no dossier manager is set, it is not necessary to check if a dossier manager is set when making a change, as this prevents dossier protection from being removed if all fields are cleared at the same time.
For [CA-2774]
[CA-2774]: https://4teamwork.atlassian.net/browse/CA-2774

Update local roles when dossier protection is revoked.

---

README.rst
opengever/base/nightly_role_assignment_reports.py
opengever/core/tests/test_upgrade.py
opengever/core/upgrade.py
opengever/core/upgrades/20210205084521_add_sortable_reference_number_index/upgrade.py
opengever/disposition/nightly_jobs.py
opengever/dossier/nightly_after_resolve_job.py
opengever/nightlyjobs/configure.zcml
opengever/nightlyjobs/interfaces.py
opengever/nightlyjobs/maintenance_jobs.py
opengever/nightlyjobs/provider.py
opengever/nightlyjobs/runner.py
opengever/nightlyjobs/tests/test_maintenance_jobs.py
opengever/nightlyjobs/tests/test_nightly_job_provider.py

With this PR we add a new nightly job provider for maintenance jobs. The implementation is meant to keep as much flexibility as possible, allowing to basically run any function in a nightly maintenance job. I also tried to make the queues efficient, using BTrees and only storing the strict minimum in the queues.
I also added a helper context manager that allows to easily use the nightly maintenance jobs for upgrades reindexing objects in the catalog or in solr.
For [CA-2366]
[CA-2366]: https://4teamwork.atlassian.net/browse/CA-2366

Add support for nightly maintenance jobs

---

changes/CA-2156-1.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/tests/test_document.py

Bring API validation in line with classic ui validation for proposal documents. We fix the following two potential issues:
- Prevent users from replacing a proposal document with a non-docx document.
- Prevent users from removing the file from a proposal document.
_This still leaves a potential loophole as we don't inspect file data. This is consistent with behavior in the classical UI and also i'm not sure if want to do so and can do so reliably._
For [CA-2156](https://4teamwork.atlassian.net/browse/CA-2156)
- API change:

Prevent non-docx and empty files in a PATCH request to a proposal document.

---

opengever/api/tests/test_listing_custom_fields.py
opengever/testing/fixtures.py

This PR extends the testing fixture with a custom prop having a default value.
For [CA-2482]
[CA-2482]: https://4teamwork.atlassian.net/browse/CA-2482

Extend the testing fixture with a custom prop having a default value.

---

changes/CA-2485.bugfix
opengever/core/upgrades/20210819081602_clean_up_relation_catalog/upgrade.py

This upgrade iterated and modified the relation catalog at the same time. This will lead to a RuntimeError as the bucket being iteratedchanged size.
To prevent the issue we defer unindexing broken relations to afteriterating the relation catalog.
✅  &nbsp;tested and confirmed working on a test-run system.
For [CA-2485](https://4teamwork.atlassian.net/browse/CA-2485)

Fix changing bucket being iterated in size during relation catalog cleanup.

---

changes/CA-2352.bugfix
opengever/core/upgrades/20210806084458_fix_sharing_permissions/upgrade.py

Avoid workflow update for all documents.
During the SG testrun I realized that the upgrade step `FixSharingPermissions`, which intends to update only the inbox and private documents, updates the workflow for all documents. Which would make the upgrade step unnecessarily longer. 
The reason is how the ftw.upgrades `WorkflowSecurityUpdater` works. It fetches the types for the given workflows (https://github.com/4teamwork/ftw.upgrade/blob/master/ftw/upgrade/workflow.py#L179) and queries all those types. Because we use a placeful workflow for inbox_documents and private_documents, the type `opengever.document.document` is queried and we update all documents.
I have therefore rewritten the upgrade step so that we update the inbox and private documents manually.
For [CA-2352]
_Everything has to …

Fixed FixSharingPermissions upgradestep.

---

changes/CA-2152.bugfix
opengever/mail/mail.py
opengever/mail/tests/test_mail_metadata.py

When extracting `document_author` from mails and setting it on D&Duploaded mails we did bypass input validation of the form fields. We change how the from header is handled by adding manual sanitation of
extracted values. The field is relatively permissive and only disallows newlines and carriage returns. We also strip the value before attempting to lookup an actor so that we could also handle leading/trailing whitespace should it make its way into the header somehow.
For [CA-2152](https://4teamwork.atlassian.net/browse/CA-2152)

Sanitize extracted document_author from mails.

---

opengever/api/tests/test_tus.py
opengever/api/tus.py
opengever/base/quickupload.py
opengever/base/tests/test_quickupload.py
opengever/mail/create.py
opengever/mail/mail.py
opengever/mail/tests/test_extract_attachments.py
opengever/mail/tests/test_inbound.py
opengever/propertysheets/creation_defaults.py
opengever/propertysheets/tests/test_creation_defaults.py

This initializes custom properties with default values for
- Documents and mails **uploaded with TUS**
- Documents and mails **uploaded via QuickUpload**
- Mails received via **inbound mail**
- Documents **extracted from mail attachments**
For [CA-2482](https://4teamwork.atlassian.net/browse/CA-2482)

Initialize custom properties with default values on non-interactive document creations

---

opengever/core/upgrades/20210908103657_remove_newlines_from_mail_document_authors/upgrade.py

Follow up for https://github.com/4teamwork/opengever.core/pull/7158 to add an upgrade that also fixes affected content in production. In contrary to my initial assumptions this seems to have happened occasionally and we prefer to have correct data in production 😉 .
- The upgrade applies the same replacements as is done by input sanitation in https://github.com/4teamwork/opengever.core/blob/73a17fb6fd9838a758f97622d96d8665269fbd38/opengever/mail/mail.py#L420
- Would also convert any non-unicode `document_authors` should they exist
For [CA-2152](https://4teamwork.atlassian.net/browse/CA-2152)

Add upgrade to fix mail authors with newlines.

---

changes/CA-2850.bugfix
opengever/wopi/browser/wopi.py
opengever/wopi/tests/test_wopi.py

This way we can make sure that even in teamraum deployments the label in the office online breadcrumb makes sense. In addition, the client title is also visible for MulitAdminUnit sites in this way.
The BreadcrumbBrandName is visible in office onlines Breadcrumb:
For [CA-2850]
[CA-2850]: https://4teamwork.atlassian.net/browse/CA-2850

Use plone site title as WOPI BreadcrumbBrandName.

---

changes/CA-2339.other
changes/CA-2339a.feature
changes/CA-2339b.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/tests/test_document.py
opengever/api/tests/test_mail.py
opengever/base/service.py
opengever/base/tests/test_api.py
opengever/document/checkout/manager.py
opengever/document/document.py
opengever/document/tests/test_cancel.py
opengever/document/tests/test_checkout.py
opengever/mail/mail.py

Include additional infos in document serialization and status endpoint:
- file modification time
- checkout collaborators
- lock time and timeout
This info will be displayed in the document status bar.
Allow checkin of collaborative checkouts for all collaborators if the document is not locked (lock has expired).
Usually Office Online renews the lock regularly. It happens that Office Online does not unlock the document correctly, e.g. if the user closes the Office Online tab while not being connected to the internet. In this case the lock expires and the collaborators should be able to checkin the document.
For [CA-2339](https://4teamwork.atlassian.net/browse/CA-2339)
- API change:

Allow checkin for collaborative checkout if it's not locked

---

changes/CA-2751.bugfix
opengever/api/ogdsuser.py
opengever/api/serializer.py
opengever/api/tests/test_ogdsuser.py
opengever/api/tests/test_ogdsuserlisting.py
opengever/ogds/models/tests/test_user.py
opengever/ogds/models/user.py

It seems IMAG has one user with a unicode userid. We fix the `ogds-users` and `ogds-user-listing` endpoints so that they support non-ascii userids.
For [CA-2751]
- API change:
[CA-2751]: https://4teamwork.atlassian.net/browse/CA-2751

Add support for unicode userids in ogds-users and ogds-user-listing endpoints.

---

changes/CA-2156-2.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/complete_successor_task.py
opengever/api/tests/test_complete_successor_task.py
opengever/task/validators.py

Prevent transferring documents checked out by different users when completing successor tasks in `@complete-successor-task`. This makes the behavior consistent with validation in the classic UI where such documents are not allowed.
Error handling is unfortunately very basic for the new UI but we have other issues that block having something better right now.
For [CA-2156](https://4teamwork.atlassian.net/browse/CA-2156)
- API change:

Prevent transferring working copies in remote task.

---

opengever/api/tests/test_tus.py

Continue temporary disable lock check in tus-replace because office-connector still does not proivde this feature.
See https://github.com/4teamwork/opengever.core/pull/6636 for more information.

Continue temporary disable lock check in tus-replace

---

changes/CA-2482.bugfix
opengever/propertysheets/widgets.py

The `++widget++` traversal for autocomplete searches in the `responsible` field cause the entire form to be updated. When the form contained custom properties widgets, these got updated as well. This caused issues when the custom property widgets did not contain valid values yet at this point.
We therefore skip updating custom properties widgets on `++widget++` traversal requests to avoid this.
I tried to write a test for this, but I was unable to create a test that actually *failed* first.
For [CA-2482](https://4teamwork.atlassian.net/browse/CA-2482)

Fix ++widget++ traversal when form contains custom properties

---

changes/CA-1269.feature
docs/schema-dumps/opengever.repository.repositoryfolder.schema.json
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/schemas/repofolders.schema.json
opengever/core/profiles/default/types/opengever.repository.repositoryfolder.xml
opengever/core/upgrades/20210913180533_add_responsible_org_unit_field_to_repository_folders/types/opengever.repository.repositoryfolder.xml
opengever/core/upgrades/20210913180533_add_responsible_org_unit_field_to_repository_folders/upgrade.py

This was a customisation for AI, but as we are trying to get rid of customisations and that it generally makes sense for multi-OrgUnit deployments to have the `responsible_org_unit` field on repository folders, we have decided to add this to `opengever.core` instead and remove AI's customization.
For [CA-1269]
[CA-1269]: https://4teamwork.atlassian.net/browse/CA-1269

Add responsible_org_unit field to repository folders.

---

changes/CA-2482-2.bugfix
opengever/propertysheets/schema.py
opengever/propertysheets/tests/test_schema.py

Custom properties don't have support for controlling the vocabularies on `Choice` fields yet. Their vocabularies therefore get autogenerated. During that autogeneration, the `token` is always made 7-bit ASCII when it's derived from `values`.
For values that contain non-ASCII characters, this is achieved using `unicode_escape(value)`. That therefore leads to `token`s that are different from `values` (for these terms).
Because the REST API never should expose vocabulary _values_, the client is expected to pass the `token` in its requests. But that means any Field `default`s also need to be translated to the respective `token` before serializing the schema.
For [CA-2482](https://4teamwork.atlassian.net/browse/CA-2482)
- API change:

Transform default *value* to *token* in custom property schemas.

---

docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/propertysheets.rst
opengever/propertysheets/default_from_member.py
opengever/propertysheets/tests/test_default_from_member.py

This adds a new parameter `allow_unmapped` (default: `False`) to the `default_from_member` options for propertysheet definitions.
This will therefore change the default behavior of `default_from_member`: Unless `allow_unmapped` is set to `True`, unmapped values are not returned as defaults, but the `fallback` is used instead.
With `allow_unmapped == True`, unmapped values are returned 1:1.
The reason for this is to add an additional level of robustness, where unexpected (i.e. unmapped) values don't result in invalid defaults being produced.
For [CA-2288](https://4teamwork.atlassian.net/browse/CA-2288)
- API change:
- If breaking:

Propertysheets: Add allow_unmapped parameter to default_from_member options.

---

changes/CA-2896.bugfix
opengever/api/tests/test_actors.py
opengever/ogds/base/actor.py

The `@teams` endpoint expects the team id in the URL and not the actor identifier which includes a `team:` prefix.
For [CA-2896](https://4teamwork.atlassian.net/browse/CA-2896)

Fix actor represents URL for teams

---

changes/CA-1130.other
opengever/workspace/participation/browser/my_invitations.py
opengever/workspace/tests/test_my_invitations.py

Until now, an error was thrown when an invitation link was opened that referred to an already accepted invitation.
Now you will be redirected directly to the workspace the invitation was for or, if the user is not logged in, to the login form.
For [CA-1130]
[CA-1130]: https://4teamwork.atlassian.net/browse/CA-1130

Redirect to workspace if the invitation link refers to an already accepted invitation

---

changes/CA-2904.bugfix
opengever/core/profiles/default/types/opengever.meeting.proposal.xml
opengever/core/profiles/default/types/opengever.meeting.submittedproposal.xml
opengever/core/upgrades/20210917151047_remove_immediate_view_for_proposals/types/opengever.meeting.proposal.xml
opengever/core/upgrades/20210917151047_remove_immediate_view_for_proposals/types/opengever.meeting.submittedproposal.xml
opengever/core/upgrades/20210917151047_remove_immediate_view_for_proposals/upgrade.py

Fixes protocol approval proposal creation, when the new UI is enabled and after proposal creation it redirects to the new UI.
The regular URL of a proposal, works also for the new UI, but the `tabbed_view` addition does not. The change has no impact for the old UI.
For [CA-2904]
[CA-2904]: https://4teamwork.atlassian.net/browse/CA-2904

Remove immediate_view for proposals

---

changes/CA-1207.bugfix
opengever/api/tests/test_move.py
opengever/dossier/base.py
opengever/dossier/configure.zcml
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/move_items.py
opengever/dossier/tests/test_move_items.py

Moving a dossier over the API did not validate the dossier depth. Also note that in the classic UI we only checked whether we can add a dossier in the target, we did not check whether the dossier we are adding itself contains subdossiers and if that would respect the dossier depth. This is now also fixed.
For [CA-1207]
- API change:
- If breaking:
[CA-1207]: https://4teamwork.atlassian.net/browse/CA-1207

Respect maximum dossier depth when moving a dossier.

---

changes/CA-2925.bugfix
opengever/api/tests/test_actors.py
opengever/ogds/base/actor.py

The `is_active` property was missing for the SystemActor. Fixes https://sentry.4teamwork.ch/organizations/sentry/issues/77235.
For [CA-2925]
[CA-2925]: https://4teamwork.atlassian.net/browse/CA-2925

Fix actors endpoint for the SystemActor.

---

changes/CA-2852.bugfix
opengever/api/batch.py
opengever/api/tests/test_globalindex.py

The current implementation of SQLHyperMediaBatch passed in the SQLAlchemy query in to the Batch mechanism, this lead to several unnecessary SQL queries and performance Issue on deployments with a large amount of tasks (`@globalindex` endpoint).
I switched the implementation of the `SQLHyperMedia`, so that the query is only called when initializing the HyperMediaBatch and make sure that the query.count() is also only called once.
On local measurements with 50K tasks, the @globalindex endpoint could be reduced from approx. 5s to approx. 500ms.
For [CA-2852]
[CA-2852]: https://4teamwork.atlassian.net/browse/CA-2852

Make performance improvements for API endpoints using SQLHypermediaBatch.

---

changes/CA-1269_2.other
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

New deployments should all have nightly jobs enabled.
For [CA-1269]
[CA-1269]: https://4teamwork.atlassian.net/browse/CA-1269

Enable nightly jobs by default.

---

changes/CA-1346-2.other
changes/CA-1346.other
opengever/nightlyjobs/runner.py
opengever/nightlyjobs/tests/test_nightly_job_runner.py
opengever/ogds/base/sync/import_stamp.py
opengever/ogds/base/tests/test_ogds_updater.py

- Track nightly job runs with a timestamp on the Plone site
- Such a timestamp already exists for OGDS sync
- Add helper functions that determine, based on those timestamps, whether these jobs have been executed in the last 24h:
- `nightly_run_within_24h()`
- `ogds_sync_within_24h()`
- Add helper functions provide the underlying information:
- `get_ogds_sync_stamp()`
- `get_nightly_run_timestamp()`
- `get_job_counts()`
The nightly jobs timestamp will not so much track *success*, but any *attempt* to run the jobs (that could be successful). So it gets updated whenever the runner is invoked by the cron job and:
- we're not outside the time window
- nightly jobs are not disabled via registry
- system load at the start doesn't lead to an immediate abort
For …

Track nightly jobs and OGDS sync runs with timestamps 

---

changes/CA-2907.other
opengever/core/testserver.py
opengever/core/testserver_selftest.py

Isolation for the sqlite in e2e tests:
Related frontend PR: https://github.com/4teamwork/gever-ui/pull/1948
https://user-images.githubusercontent.com/557005/133816226-d5adde95-084f-4b82-a0a5-4eb182cfa447.mov
https://user-images.githubusercontent.com/557005/133815502-3e2cb4bd-2182-4d49-93ea-8f71bc178965.mov

Implement sqlite isolation for e2e tests.

---

changes/CA-2936.bugfix
opengever/api/document.py
opengever/api/serializer.py
opengever/api/tests/test_document.py

This change makes sure that **on documents**, non-documentish types are also filtered from the `back_references_...` property returned by the REST API, similarly to what already is [being done in the classic UI with `related_items(documents_only=True)`](https://github.com/4teamwork/opengever.core/blob/f7d69a99f17fcf38f94de2cd7f3a8c6c972142f8/opengever/document/browser/overview.py#L269-L282).
For [CA-2936](https://4teamwork.atlassian.net/browse/CA-2936)

Filter non-documentish types for IRelatedDocuments.relatedItems backrefs

---

changes/CA-2947.bugfix
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py

We have again and again the case that the notation of the userid is changed in the AD/LDAP, this leads then to a `StaleDataError` during the OGDS synchronisation. Therefore such "duplicated" users are now ignored and skipped.
We already did the similar fix in the old implementation of the OGDS sync (see #1054)
Fixes [CA-2947]
[CA-2947]: https://4teamwork.atlassian.net/browse/CA-2947

Skip duplicate users with different capitalization during LDAP-OGDS sync

---

changes/CA-2771.feature
opengever/api/tests/test_schema.py
opengever/base/behaviors/classification.py
opengever/base/behaviors/lifecycle.py
opengever/base/behaviors/utils.py
opengever/base/monkey/patches/readonly.py
opengever/base/permissions.zcml
opengever/base/tests/test_classification.py
opengever/base/tests/test_lifecycle.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20210920163320_add_permission_to_edit_classification_and_lifecycle_fields/rolemap.xml
opengever/core/upgrades/20210920163320_add_permission_to_edit_classification_and_lifecycle_fields/upgrade.py
opengever/dossier/browser/forms.py
opengever/dossier/dossiertemplate/form.py
opengever/repository/browser/repositoryfolder_forms.py

This is necessary so that we can restrict who can edit these fields for St. Gallen. https://github.com/4teamwork/opengever.sg/pull/501
For [CA-2771]
[CA-2771]: https://4teamwork.atlassian.net/browse/CA-2771

Add permission to protect lifecycle and classification fields.

---

README.rst
base-testserver.cfg
bin/testserverctl
opengever/core/testserver.py
opengever/core/testserver_selftest.py
opengever/core/testserver_zope2server.py
setup.py

**The goal is to make the testserver more sturdy, so that it does not break when doing unexpected things such as making HTTP requests while doing isolation (teardown/setup) between tests.**
- _⚠️ currently merging into #7182; rebase needed ⚠️_
- superseding #7189 
- part of: https://4teamwork.atlassian.net/browse/CA-749
Until now, the testserver was built expecting that the client is well-behaved, does not make any HTTP requests while doing isolation and waits until the testserver is ready again. But fact is that our JavaScript-based frontend is not that well-behaved. It does not wait (long enough) until the setup is finished or may send requests after tear down is initialized.
Making HTTP requests when the testserver is not ready can cause problems such as:
- `KeyError: 'test-stack-4'` …

Make testserver more sturdy

---

changes/CA-2971.other
opengever/docugate/tests/test_service.py
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api_dossier_attach.py
opengever/officeconnector/tests/test_api_dossier_checkout.py
opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
opengever/officeconnector/tests/test_api_forwarding_attach.py
opengever/officeconnector/tests/test_api_mail_attach.py
opengever/officeconnector/tests/test_api_task_checkout.py
opengever/officeconnector/tests/test_zopemaster.py

In Office Connector we want to notify the user if his checked out local copy of a document is older than the current version on the server. For this we need to get the current version.
This situation can occur if the document is not checked-in by Office Connector because of a problem and then manually checked-in by the user.  If meanwhile another user creates a new version and the first user wants to continue working on the current version, OC still uses his local copy.
For [CA-2971]
[CA-2971]: https://4teamwork.atlassian.net/browse/CA-2971

Include document version in Office Connector metadata

---

changes/CA-960.bugfix
opengever/base/model/favorite.py
opengever/base/tests/test_favorite.py

As the filename column has a length limit we must enforce it by truncating too long data. This adds another layer of sanitation to the already existing id normalizer. The normalizer seems to be a bit lenient when it comes to file extensions potentially allowing very long file extensions. We add strict sanitation for such cases to prevent errors while writing to the database.
For [CA-960](https://4teamwork.atlassian.net/browse/CA-960)

Truncate filenames when updating favorites.

---

opengever/core/testserver_zope2server.py

This fixes a minor issue discovered by @jone and me while trying to find out why the E2E tests in RIS were no longer working when testing against the latest `master` of `opengever.core` (9e90421705221866cae63ae4b03a526b0961f662).

Fix testserver

---

changes/CA-3000.bugfix
opengever/document/configure.zcml
opengever/document/handlers.py
opengever/document/tests/test_activities.py

The `IObjectRevertedToVersion` event gets notified in the [revert_to_version method](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L365-L366), which is also called when [cancelling a checkout](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L263-L264). This led to an `DocumenVersionCreatedActivity` being created although no new version of the document was actually created.
For [CA-3000]
[CA-3000]: https://4teamwork.atlassian.net/browse/CA-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not create DocumenVersionCreatedActivity when cancelling checkout.

---

changes/CA-3001.bugfix
opengever/api/actors.py
opengever/api/tests/test_actors.py

`serialize_actor_id_to_json_summary()` is also called from the sharing endpoint.  From there, actor ids can have non-ascii characters.
https://sentry.4teamwork.ch/organizations/sentry/issues/78180
For [CA-3001]
[CA-3001]: https://4teamwork.atlassian.net/browse/CA-3001

Fix handling of unicode actor ids

---

changes/CA-2773.bugfix
opengever/mail/mail.py
opengever/mail/tests/__init__.py
opengever/mail/tests/mail_with_ad_from.txt
opengever/mail/tests/test_mail_metadata.py

The ad information inside `<` `>` leads to very long and confusing document_authors, so we strip them, if it's not an email.
For [CA-2773]
[CA-2773]: https://4teamwork.atlassian.net/browse/CA-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Strip outlooks AD information in mails document_author extraction.

---

changes/CA-2674.other
opengever/officeconnector/mimetypes.py

Sometimes the mimetype of onenote documents is `application/msonenote` instead of `application/onenote`. This should be Editable by OC.
Note that I've added it manually for Fribourg in the `IOfficeConnectorSettings.officeconnector_editable_types_extra`.
For [CA-2674]
[CA-2674]: https://4teamwork.atlassian.net/browse/CA-2674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add application/msonenote to OC editable types.

---

changes/CA-3038.feature
opengever/core/upgrades/20211018134101_add_invitation_mail_content_setting/registry.xml
opengever/core/upgrades/20211018134101_add_invitation_mail_content_setting/upgrade.py
opengever/workspace/interfaces.py
opengever/workspace/participation/invitation_mailer.py
opengever/workspace/tests/test_invitation.py

This PR adds an additional registry entry, to customize the invitation mail content. 
The setting is empty by default, therefore the default mail content (which also provides translations) is used. The customization flag does not support translations.
The mail content is customized only in exceptional cases, therefore the flag is not set in the policy generator.
For [CA-3038]
[CA-3038]: https://4teamwork.atlassian.net/browse/CA-3038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make workspace invitation mail content customizable.

---

opengever/tasktemplates/content/templatefoldersschema.py
opengever/tasktemplates/locales/de/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/en/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/opengever.tasktemplates.pot

This helps for the understanding of the new field. follow up of #7220 
For [CA-3081]
[CA-3081]: https://4teamwork.atlassian.net/browse/CA-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add help text for the new tasktemplatefolders `text` field.

---

changes/CA-2844.feature
opengever/globalindex/browser/report.py
opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/en/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/opengever.globalindex.pot
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_reporter.py
opengever/globalindex/utils.py
opengever/latex/tasklisting.py
opengever/latex/templates/tasklisting.tex
opengever/latex/tests/test_listing.py

This PR introduces a new parameter `include_subtasks` to include subtasks in task reports. The parameter is only used in the new frontend, because in the listings of the classic frontend, unlike the listings of the new frontend, subtasks are displayed.
I decided to sort the subtasks by path so that subsubtasks appear below the correct subtask. This has the consequence that for sequential tasks the order is not necessarily correct. But since determining the correct order for sequential tasks would require retrieving the Plone task, I chose not to include this.
For [CA-2844]
[CA-2844]: https://4teamwork.atlassian.net/browse/CA-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

Allow to include subtasks in task reports

---

opengever/api/complete_successor_task.py
opengever/api/task.py
opengever/api/tests/test_complete_successor_task.py
opengever/api/tests/test_task.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_sql_task.py
opengever/task/browser/complete.py
opengever/task/browser/complete_utils.py
opengever/task/transition.py

The recently introduced flag `pass_documents_to_next_task` had only worked for tasks inside an adminunit. This PR extends the functionality to also work if one part of a sequential task process is cross adminunit.
Besides that I added the helpers `has_sequential_successor` and `has_remote_predecessor` two the task serialization, to help display the correct transition fields in the gever-ui.
For [CA-1978]
[CA-1978]: https://4teamwork.atlassian.net/browse/CA-1978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make pass_documents flag also work for multi adminunit tasks.

---

changes/CA-3113.bugfix
opengever/core/upgrades/20211028173917_fix_committee_meeting_end_date/upgrade.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/protocol.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/en/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_meeting.py
opengever/meeting/tests/test_meeting_edit.py

Since the end date is validated in the meetings app, this repeatedly led to import errors. Therefore, the end date is now also validated in Gever.
The end date can now no longer be before the start date. For meetings that have an invalid end date set, the end date is set to None.
For [CA-3113]
[CA-3113]: https://4teamwork.atlassian.net/browse/CA-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add validation of the end date for meetings

---

changes/CA-3125.bugfix
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py

Some deployments had errors in OGDS sync because they have group titles that contain non-ascii chars.
For [CA-3125]
[CA-3125]: https://4teamwork.atlassian.net/browse/CA-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix UnicodeEncodeError in ogds sync.

---

changes/CA-3131.other
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po

I decided to only change the description but not the title of the field. Adding reactivate in the title does not make sense IMO, as it's not the only status change the user will be allowed to make.
For [CA-3131]
[CA-3131]: https://4teamwork.atlassian.net/browse/CA-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify description of read/write access for dossier protection.

---

changes/CA-3117.bugfix
opengever/api/copy_.py
opengever/api/tests/test_copy_paste.py
opengever/base/browser/paste.py

Copied documents need to get stored in bumblebee once all their parents have been renamed, as otherwise the url in the storing job will be outdated by the time the job gets processed. This only matters for documents with docproperties which will modify the file, i.e. the document's checksum will not already be stored in bumblebee.
For [CA-3117]
[CA-3117]: https://4teamwork.atlassian.net/browse/CA-3117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix storing documents in bumblebee during copy/paste

---

opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po

There was a typo and the PO wants "reactivate" instead of "activate" for the activate transition. No changelog entry as there is already one from https://github.com/4teamwork/opengever.core/pull/7231.
For [CA-3131]
[CA-3131]: https://4teamwork.atlassian.net/browse/CA-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Small correction to description of read/write access for dossier protection.

---

changes/CA-3150.bugfix
docs/schema-dumps/opengever.workspace.meeting.schema.json
opengever/api/configure.zcml
opengever/api/field_deserializers.py
opengever/api/tests/test_deserializer.py
opengever/base/schemadump/config.py
opengever/core/upgrades/20211105142527_make_workspace_meetings_timezone_aware/upgrade.py
opengever/testing/fixtures.py
opengever/workspace/workspace_meeting.py

Start and end dates for `WorkspaceMeeting`s are sent as UTC from the frontend, but were stored as timezone naive on the objects. This leads to localization of the datetime when generating the PDF for the meeting to show the UTC start and end times. I chose to save the fields as localized datetimes on the objects instead.
Note that `UTCDatetime` fields are already stored as timezone aware in the classic UI, so would probably have been broken without the deserializer. As they were used only for meetings, which are not implemented in the new UI, this problem was not noticed before.
The upgrade step uses somewhat of a hack. By reindexing the full object we change the modified date, so that when checking whether the metadata has changed, we never reach the comparison with previous value for …

Make workspace meeting start and end timezone aware.

---

changes/CA-1815.feature
opengever/officeconnector/helpers.py
opengever/officeconnector/tests/test_api_dossier_attach.py

⚠️  Requires new OfficeConnector version.
The flags are used to tell the OfficeConnector which things are not needed in the mail. The interpretation of the flags is done in the OfficeConnector.
For [CA-1815]
[CA-1815]: https://4teamwork.atlassian.net/browse/CA-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add flags to office connector url for attach action.

---

changes/CA-408.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_language.py
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/language_tool.py

by patching the language tool and add the `PATCH` request method to the supported ones.
this fix two issues: 
- translate error messages also in PATCH requests
- translate vocabulary values etc. when `return=representation` header is sent
For [CA-408]
- API change:
[CA-408]: https://4teamwork.atlassian.net/browse/CA-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make sure preferred language is also used for API PATCH requests,

---

changes/CA-1679-4.other
opengever/workspace/configure.zcml
opengever/workspace/subscribers.py
opengever/workspace/tests/test_todo.py

This reverts commit 5c25a0be584a23c73d79dadca3d42d954180272a.
Since we improved the performance for todo listings, we do no longer need a hard limit.
For [CA-1679]
- API change:
- If breaking:
[CA-1679]: https://4teamwork.atlassian.net/browse/CA-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "Add hard limit for number of ToDos in a single workspace."

---

changes/CA-3085.bugfix
opengever/inbox/forwarding.py

Somehow this fixes an issue where creating a forwarding leads to the documents being moved into the forwarding appearing twice in the catalog: once with the old path and once with the new. It seems to have something to do with reindexing and event order, but I wasn't really able to pin it down.
I could not reproduce the issue in a test, probably because the issue is linked to collective indexing.
For [CA-3085]
[CA-3085]: https://4teamwork.atlassian.net/browse/CA-3085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update local roles after moving document when creating forwarding.

---

changes/CA-2606_2.feature
opengever/api/tests/test_dossier_participations.py
opengever/dossier/configure.zcml
opengever/dossier/participations.py
opengever/dossier/tests/test_participation.py
opengever/kub/client.py
opengever/kub/sources.py
opengever/kub/testing.py
opengever/kub/tests/test_kub_client.py
opengever/kub/tests/test_kub_contact_source.py
opengever/ogds/base/actor.py
opengever/ogds/base/tests/test_actor.py

With this PR we add support for KuB participations.
For the tests I used real responses from a KUB deployment with data from a fixture (see https://github.com/4teamwork/kub/pull/49), so that we can easily update the responses if KuB were to change.
For [CA-2606]

Add support for KuB participations

---

changes/CA-1212.other
opengever/core/profiles/default/metadata.xml
opengever/core/upgrades/20211119083157_uninstall_ftw_tika/upgrade.py

The package dependency is still necessary and will removed later, when the profile is uninstalled everywhere (see CA-1158 ).
For [CA-1212]
[CA-1212]: https://4teamwork.atlassian.net/browse/CA-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove ftw.tika dependency and uninstall tika profile.

---

opengever/core/upgrades/20211119083157_uninstall_ftw_tika/upgrade.py

When deploying #7249 on dev, I realized a problem with the uninstall profile in tika. 
It seems that in some cases the tika product is still installed but the profile is no longer installed. This makes is hard to uninstall the product. Therefore we reinstall the profile and uninstall the product afterwards.
For [CA-1212]
[CA-1212]: https://4teamwork.atlassian.net/browse/CA-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix tika uninstall upgradestep.

---

changes/CA-3230.bugfix
opengever/api/tests/test_proposal.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_protocol_json_data.py
opengever/meeting/tests/test_traverser.py
opengever/meeting/traverser.py

With this PR we fix a bug where documents added to a submitted proposal would not get included in the meeting Zip file. I also decided to include such documents in the `ProtocolData`.
For [CA-3230]
[CA-3230]: https://4teamwork.atlassian.net/browse/CA-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include documents manually added to submitted proposal in meeting Zip and protocol data.

---

opengever/kub/testing.py

We switched the approach for creating the testing fixture in KuB (https://github.com/4teamwork/kub/pull/49) to use `baker` instead of a json dump. This lead to creation and modification dates changes (I'm now using freezing on the KuB side).
For [CA-2606]

Update KuB testing fixture.

---

changes/CA-3132.bugfix
opengever/policytemplates/cli.py

It seems that the create-policy command was broken when improving the test-server. The changes (https://github.com/4teamwork/opengever.core/commit/d7730d5f04a4c0cd348afd51ca03f70b7d5794a8#diff-2ecaec2b2900eb97131d5ac85d4c1ffa016b109208a4bbb8378075d79de9ce06L14) lead to an unrecognised argument being passed to the command. We simply fix this by removing the argument before calling mrbob.
For [CA-3132]
[CA-3132]: https://4teamwork.atlassian.net/browse/CA-3132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix create-policy command.

---

changes/CA-3066.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/reminder.py
opengever/api/tests/test_reminder.py

I would not consider that a breaking API change...
For [CA-3066]
- API change:
- If breaking:
[CA-3066]: https://4teamwork.atlassian.net/browse/CA-3066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

@reminders does not raise anymore when no reminder is set.

---

docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dispositions.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/schemas/opengever.workspace.meeting.inc
opengever/api/configure.zcml
opengever/api/disposition.py
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/tests/test_disposition.py
opengever/disposition/browser/overview.py
opengever/disposition/disposition.py

- Add an additional key `dossier_details`, which contains a summary of all contained dossiers, grouped by repository and separated in two lists `active_dossiers` and `inactive_dossiers`
- Add a separate `@appraisal` PATCH endpoint
For [CA-2116]
- API change:
[CA-2116]: https://4teamwork.atlassian.net/browse/CA-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend API Support for dispositions

---

changes/CA-2116.bugfix
opengever/repository/constrains.py
opengever/repository/tests/test_repositoryfolder.py

Make dispositions always addable, it doesn't matter if the repositoryfolder is a leaf or a branch folder.
For [CA-2116]
[CA-2116]: https://4teamwork.atlassian.net/browse/CA-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix repositoryfolder addable types constraints

---

changes/CA-1929.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/add.py
opengever/api/tests/test_document.py
opengever/api/tests/test_tus.py
opengever/api/tus.py

We now also have the translated message in the error response. The status code of the response has changed from 507 to 403.
For [CA-1929]
- API change:
- If breaking:
[CA-1929]: https://4teamwork.atlassian.net/browse/CA-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use Gever API error handling for ForbiddenByQuota errors.

---

changes/CA-3193.bugfix
changes/CA-3193.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/complete_successor_task.rst
opengever/api/complete_successor_task.py
opengever/api/relationfield.py
opengever/api/tests/test_complete_successor_task.py
opengever/api/tests/test_relationfield.py
opengever/base/oguid.py
opengever/base/tests/test_oguid.py

Extends the `documents` payload parameter of the `@complete-successor-task` endpoint to also accept URLs.
We do this by reusing the already existing method `relationfield_value_to_object` which provides resolving a value to an object by multiple ways, also by URL.
By using this method, we change the behavior of resolving paths. Currently, the endpoint expects physical paths for the `documents` parameter. But physical paths are for internal use only. It now supports relative paths which is the correct way of resolving objects paths provided by a client. [breaking change]
For [CA-3193]
- API change:
- If breaking:
- Further …

Improve complete successor task endpoint when using urls or relative paths as document references

---

HISTORY.rst

According to https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/168166594/GEVER+Releases+erstellen#Patchlevel-Release-erstellen we always update the `master` CL with backport releases. It seems we did not do so for any if the `2021.23.X` so far so i'm including all of them now.
For [CA-2746](https://4teamwork.atlassian.net/browse/CA-2746)

Update CL with recent backport releases.

---

changes/CA-2606_3.feature
opengever/contact/browser/participation_add_view.py
opengever/contact/browser/tabbed.py
opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/en/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/opengever.contact.pot
opengever/contact/tests/test_participation.py
opengever/contact/tests/test_tabbed.py
opengever/dossier/browser/forms.py
opengever/dossier/tests/test_tabbed.py

Or rather, inform the user that we do not handle KuB participations in the classic UI...
For [CA-2606]

Handle KuB contacts and participations in classic UI

---

changes/CA-2606_4.feature
opengever/api/tests/test_listing.py
opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py

Add support for KuB participations in the `@listing` endpoint.
For [CA-3260], [CA-2606], maybe [CA-3098] ...
[CA-3098]: https://4teamwork.atlassian.net/browse/CA-3098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-3260]: https://4teamwork.atlassian.net/browse/CA-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support KuB participations in listing endpoint.

---

opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py

This is to handle 2 situations:
- There are participations on a dossier that are not of the type of the currently activated contact feature (for example on dev.onegovgever.ch/rk, I activated KuB but there are plone participations that were not migrated)
- There are participations for a contact that does not exist anymore (currently contacts can be deleted in KuB).
Both these cases should not really happen in production as I understand it because:
- There will be some sort of migration when switching to KuB contacts (https://4teamwork.atlassian.net/browse/CA-2605)
- KuB plans on implementing deactivation of contacts instead of deletion.
But still, we can't afford that the whole dossier listing fails because of an unknown participant ID.
For [CA-2606]
[CA-2606]: …

Support invalid participation IDs in listing endpoint.

---

changes/CA-3277.bugfix
opengever/activity/digest.py
opengever/activity/mail.py
opengever/activity/mailer.py
opengever/activity/tests/test_mail.py
opengever/workspace/content_sharing_mailer.py
opengever/workspace/participation/invitation_mailer.py

Pass in from and to mail adresses when sending mails to avoid problems for users with long fullname or mail addresses.
possibly needs backport to 2021.22.x 
For [CA-3277]
[CA-3277]: https://4teamwork.atlassian.net/browse/CA-3277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix sending notification mails from or to users with long mail addresses.

---

changes/CA-2274.bugfix
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/globalindex.rst
opengever/api/task.py
opengever/api/tests/test_globalindex.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_sql_task.py

In task listings, we now use `is_completed` to display whether a task is completed. For this to work for task listings that use the `@globalindex` endpoint, the attribute must be present in the SQL task serialization.
For [CA-3284]
- API change:
[CA-3284]: https://4teamwork.atlassian.net/browse/CA-3284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CA-3284 Include is_completed in sql task serialization.

---

changes/CA-2646.other
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/en/LC_MESSAGES/opengever.activity.po
opengever/api/tests/test_disposition.py
opengever/disposition/locales/en/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/tests/test_activities.py
opengever/disposition/tests/test_disposition.py
opengever/disposition/tests/test_ech0160export.py
opengever/disposition/tests/test_excel_export.py
opengever/disposition/tests/test_history.py
opengever/disposition/tests/test_listing.py
opengever/disposition/tests/test_overview.py

For some reason in english we used `disposition` to translate both `Angebot` and `Aussonderung`. 
I've now consistently used `Offer` for `Angebot`, and `disposal` for `Aussonderung`.
Actually I might find it better to use `Disposal offer`, `Offre de triage` and `Aussonderungsangebot` instead of simply `Offer`, etc. I did not want to change everything now...
For [CA-2646]
[CA-2646]: https://4teamwork.atlassian.net/browse/CA-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve translations of the disposition module.

---

changes/CA-1742.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/documents.rst
opengever/api/configure.zcml
opengever/api/tests/test_xhr_upload.py
opengever/api/xhr.py

This PR adds a new endpoint `@xhr-upload` to upload documents with a `multipart/form-data` xhr request
This endpoint was introduced beside of the already existing `@tus-upload` endpoint. It's because be don't have access to the response of an uploaded document if using tus.
For [CA-1742]
- API change:
- If breaking:
[CA-1742]: https://4teamwork.atlassian.net/browse/CA-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add @xhr-upload endpoint to upload documents with a multipart/form-data xhr request

---

changes/CA-3296.bugfix
opengever/api/tests/test_upload_structure.py
opengever/api/upload_structure.py

Fix file upload into subdossiers which exceed the current max dossier depth. 
Needs backport to `2021.22.x`
For [CA-3296]
[CA-3296]: https://4teamwork.atlassian.net/browse/CA-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Skip dossier_depth check if only files are uploaded.

---

changes/CA-2115.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py

This is needed to add a filter for expired dossiers in the new frontend.
For [CA-2115]
- API change:
[CA-2115]: https://4teamwork.atlassian.net/browse/CA-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Expose retention_expiration column in @listing endpoint.

---

changes/CA-3249.other
opengever/workspace/browser/templates/meeting_minutes.pt

With this PR we try to improve the layout and style of the Teamraum meeting PDFs. The main changes are that we allow tables to get split over several pages and we add borders to the tables. I include 2 PDFs showing the difference between the old style and the new style:
[old_style.pdf](https://github.com/4teamwork/opengever.core/files/7649764/old_style.pdf)
[new_style.pdf](https://github.com/4teamwork/opengever.core/files/7649765/new_style.pdf)
Note that the output PDF does not respect the column widths set by the user. This is because the `wdith` attribute is only presentational hint. `weasyprint` does have a parameter that should force respecting these attributes (https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#cmdoption-p), which I tried and did not help. 🤷 
For …

Improve teamraum meeting PDF style.

---

changes/CA-2606_5.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/users.rst
opengever/api/configure.zcml
opengever/api/kub.py
opengever/api/linked_workspaces.py
opengever/api/solrsearch.py
opengever/api/tests/test_kub.py
opengever/api/utils.py
opengever/kub/client.py
opengever/kub/testing.py
opengever/ogds/base/actor.py

This endpoint basically proxies requests to the KuB service. This allows the frontend to resolve KuB entities without communicating directly with KuB.
Note that we currently need to parse the ID of the KuB contact to then request it from the correct endpoint from the KuB service. This will not be necessary anymore once KuB offers a `@resolve` endpoint (see https://4teamwork.atlassian.net/browse/HG-1995). Once we have that new endpoint we could also use it in the `KuBContactsSource` where we currently still use the `search` endpoint to resolve a given ID (because the other endpoints do not return the `text` and `TypeId` fields, which we use in the source as value and token respectively).
For [CA-2606]
- API change:
- If breaking:
[CA-2606]: …

Add @kub endpoint allowing to resolve KuB entities by their ID.

---

changes/CA-3272-2.bugfix
changes/CA-3272.bugfix
opengever/api/tests/test_task_from_template.py
opengever/task/browser/overview.py
opengever/task/task.py
opengever/task/tests/test_delegate.py
opengever/task/tests/test_task.py
opengever/task/transition.py

This PR fixes an issue where we have a conflict between a method called `documents` on a task (introduced in https://github.com/4teamwork/opengever.core/pull/7217) and a property callled `documents`.
Since the property wins over a method, we have had an issue when rendering the `task/browser/overview.py` because it expects a function under `documents`.
The main issue is when delegating tasks. The transition-extender passes `documents` coming from the `transition_params` further to the dexterity's [createContent](https://github.com/plone/plone.dexterity/blob/2.2.8/plone/dexterity/utils.py#L150) method which will then add a property `documents` to the created content, even if it's not defined in a schema-definition.
Since the refactoring of …

Fix task documents method/property collision

---

changes/CA-2118.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/configure.zcml
opengever/api/disposition.py
opengever/api/tests/test_disposition.py
opengever/core/upgrades/20211203182308_migrate_disposition_history/upgrade.py
opengever/disposition/activities.py
opengever/disposition/browser/overview.py
opengever/disposition/configure.zcml
opengever/disposition/disposition.py
opengever/disposition/handlers.py
opengever/disposition/history.py
opengever/disposition/interfaces.py
opengever/disposition/response.py
opengever/disposition/tests/test_history.py
opengever/disposition/tests/test_listing.py

To be able to reuse the existing response extension and `@response` endpoint,  I transformed the existing HistoryStorage to a regular IResponsesContainer. Including a migration for existing disposition objects. The upgradestep deferrable, but the migration shouldn't take long time, because there aren't any disposition objects in production yet.
For [CA-2118]
- API change:
[CA-2118]: https://4teamwork.atlassian.net/browse/CA-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add API Support for the disposition history.

---

changes/CA-2119.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/disposition.py
opengever/api/tests/test_disposition.py
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/en/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20211207105652_add_disposition_actions/actions.xml
opengever/core/upgrades/20211207105652_add_disposition_actions/upgrade.py
opengever/disposition/browser/overview.py
opengever/disposition/browser/templates/overview.pt
opengever/disposition/disposition.py
opengever/disposition/tests/test_actions.py

Necessary to show the actions in the gever-ui, but have the condition if the action is available still in the backend.
The PR also extends the disposition serialization with the `sip_delivery_status` key.
For [CA-2119]
- API change:
[CA-2119]: https://4teamwork.atlassian.net/browse/CA-2119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Register disposition actions as ui-context-actions

---

HISTORY.rst

Hotfix have been released from  `2021.22-stable`

Update changelog after hotfix release.

---

changes/CA-3319.bugfix
opengever/meeting/model/meeting.py
opengever/meeting/reopen.py
opengever/meeting/tests/test_meeting_reopen.py

The check whether there are newer already closed meetings was broken, because it filters on meeting numbers but did not restrict the check to meetings from the same period, although meeting numbering is per Period.
For [CA-3319]
[CA-3319]: https://4teamwork.atlassian.net/browse/CA-3319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix meeting reopen action

---

changes/CA-2274.feature
docs/public/dev-manual/api/actors.rst
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/out_of_office.rst
docs/public/dev-manual/api/substitutes.rst
docs/public/dev-manual/api/users.rst
docs/schema-dumps/_opengever.ogds.models.user.User.schema.json
opengever/api/actors.py
opengever/api/configure.zcml
opengever/api/out_of_office.py
opengever/api/substitutes.py
opengever/api/tests/test_actors.py
opengever/api/tests/test_ogdsuser.py
opengever/api/tests/test_out_of_office.py
opengever/api/tests/test_substitutes.py
opengever/base/model/__init__.py
opengever/core/upgrades/20211202155051_add_substitutes/upgrade.py
opengever/ogds/base/actor.py
opengever/ogds/base/locales/de/LC_MESSAGES/opengever.ogds.base.po
opengever/ogds/base/locales/en/LC_MESSAGES/opengever.ogds.base.po
opengever/ogds/base/locales/fr/LC_MESSAGES/opengever.ogds.base.po
opengever/ogds/base/locales/opengever.ogds.base.pot
opengever/ogds/base/substitute.py
opengever/ogds/base/tests/test_ogds_updater.py
opengever/ogds/models/substitute.py
opengever/ogds/models/user.py
opengever/testing/builders/sql.py

With `@my-substitutes` we can list, add and delete substitutes of the current user.
With the `@substitutes` endpoint we can list the substitutes of any user.
With the `@out-of-office` endpoint, we can show and edit the absence settings of the current user.
The `@actors` endpoint indicates whether an actor is absent.
For [CA-2274]
- API change:
[CA-2274]: https://4teamwork.atlassian.net/browse/CA-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add @my-substitutes, @substitutes and @out-of-office API endpoints

---

changes/CA-2452.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/templatefolder.rst
opengever/api/kub.py
opengever/api/schema/globalsources.py
opengever/api/templatefolder.py
opengever/api/tests/test_config.py
opengever/api/tests/test_globalsources.py
opengever/api/tests/test_templatefolder.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/contact/sources.py
opengever/dossier/indexers.py
opengever/dossier/templatefolder/form.py
opengever/dossier/tests/test_templatefolder.py
opengever/kub/docprops.py
opengever/kub/entity.py
opengever/kub/testing.py
opengever/kub/tests/test_docprops.py
opengever/kub/tests/test_kub_entity.py
opengever/ogds/base/actor.py
opengever/ogds/base/tests/test_actor.py

We add support for using KuB contacts as recipients when creating a document from a template. The data of that recipient is then passed as docproperties when creating the document.  Note that we are using the same docproperties with the same keys as were used with SQL contacts. This should allow existing templates to still work after a switch to KuB. Also note that KuB currently does not return a `primaryEmail` and `primaryUrl`, but that should change in the near future.
Note that we do not support KuB contacts in the classic-UI and therefore display an error message when a user tries to create a document from a template with the KuB feature active. This will not prevent creation from a document
from a template, but it does not allow to select a recipient either.
The config endpoint now …

Handle KuB feature when creating a document from template.

---

changes/CA-2612.feature
opengever/disposition/ech0160/model/additional_data.py
opengever/disposition/ech0160/model/document.py
opengever/disposition/ech0160/model/dossier.py
opengever/disposition/tests/test_model.py
opengever/propertysheets/utils.py

The custom properties are included in the `zusatzDaten` attribute.
For [CA-2612]
[CA-2612]: https://4teamwork.atlassian.net/browse/CA-2612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include custom properties in the eCH-0160 export.

---

changes/CA-3315.bugfix
opengever/api/document.py
opengever/api/tests/test_document.py

This PR fixes an issue where the `file_extension` of the serialized document have not respected the currently requested version.
For [CA-3315]
- API change:
- If breaking:
[CA-3315]: https://4teamwork.atlassian.net/browse/CA-3315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Document serializer respects the file_extension of the currently requested version

---

opengever/kub/docprops.py

We were using the description and text of the person for the contact docproperties of a membership, when the membership itself also has a description and should have a text (not implemented yet in KuB).
For [CA-2452]
[CA-2452]: https://4teamwork.atlassian.net/browse/CA-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

For memberships use its own description and text as contact docprops.

---

opengever/disposition/ech0160/model/additional_data.py
opengever/disposition/tests/test_model.py

Small fix for #7295.
For [CA-2612]
[CA-2612]: https://4teamwork.atlassian.net/browse/CA-2612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle int field customproperties when extending for ech0160 export.

---

changes/CA-1675.bugfix
opengever/api/group.py
opengever/api/tests/test_group.py

There were several problems with the endpoint:
- Not all users could be deleted from the OGDS group
- If the payload did not contain the title and description, the title and description were set to None
- A description was set for the ogds_group, although we don't have a column for the description in the SQL database for groups
For [CA-1675]
[CA-1675]: https://4teamwork.atlassian.net/browse/CA-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix @groups patch endpoint.

---

changes/CA-3323.bugfix
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_linked_workspaces.py

Sometimes the document on the Gever side cannot be found, for example because it has been trashed, or maybe moved to a dossier where the current user does not have access. In such cases, when copying a document back from a workspace as a new version, we will instead create a new document.
For [CA-3323]
[CA-3323]: https://4teamwork.atlassian.net/browse/CA-3323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix copy document from workspace as new version when gever document is trashed.

---

changes/CA-3350.feature
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py
opengever/dossier/tests/test_participation.py
opengever/kub/sources.py
opengever/kub/tests/test_kub_contact_source.py

For both dossier participations and recipients ogds users should be available when KuB feature is enabled. This was already the case for SQL contacts and needs to also be supported with KuB contacts.
Note that when creating a document from template, after selecting a recipient from the OGDS, you could select an address, phone number, url and mail address when using SQL contacts. This is not possible anymore, as we have decided not to implement that form in the new UI, and instead use default address, phone number, URL and mail for KuB contacts. For OGDS users there is no default for these fields, so I simply chose to take the first on of each...
For [CA-3350]
_Everything has to be done/checked. Checked …

Extend KuBContactSource with ogds users.

---

changes/CA-3358.bugfix
opengever/task/response_syncer/__init__.py
opengever/task/response_syncer/deadline.py
opengever/task/tests/test_response_syncer.py

When the same user was modifying the deadline of a task twice in a row with the same (or no) comment, the second modification would not get synced to its predecessors and successors. This behaviour is fixed here.
For [CA-3358]
[CA-3358]: https://4teamwork.atlassian.net/browse/CA-3358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix task syncing when deadline is modified twice by same user.

---

changes/CA-2851.feature
opengever/api/deserializer.py
opengever/api/tests/test_deserializer.py
opengever/api/tus.py
opengever/base/monkey/patches/default_values.py
opengever/base/quickupload.py
opengever/base/tests/test_command.py
opengever/base/tests/test_default_values_for_types.py
opengever/base/tests/test_transport.py
opengever/base/transport.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/ech0147/tests/test_import.py
opengever/mail/create.py
opengever/mail/mail.py
opengever/propertysheets/creation_defaults.py
opengever/propertysheets/tests/test_dossier_custom_properties.py

This PR makes sure that custom properties are initialized correctly with default values, if they're provide one. 
The following content creation are handled:
_already ensured, implemented_
- content creation via form (old and new UI)
- mail creation via Inbound Mail
- document creation via Drag&Drop TUS upload (neues UI)
- document creation via Drag&Drop QuickUpload (old UI)
- document creation Dokument via Mail-Attachment extraction (old and new UI)
_newly ensured_
- content creation via API
- dossier creation via Drag&Drop folder upload
- content creation via OGGBundle import
- content creation via `Transporter` (used in multi adminunit communication)
- document creation from template (old and new UI)
- dossier creation from template (old and new UI)
The concerns about dynamic defaults …

Make sure customproperty default values are initalized, when content is created.

---

changes/CA-1686.feature
docs/public/dev-manual/api/api_changelog.rst
docs/schema-dumps/opengever.workspace.workspace.schema.json
opengever/api/tests/test_linked_workspaces.py
opengever/api/tests/test_workspace.py
opengever/api/workspace.py
opengever/base/schemadump/config.py
opengever/bundle/schemas/workspaces.schema.json
opengever/core/upgrades/20211216155313_initialize_workspaces_responsible_field/upgrade.py
opengever/workspace/configure.zcml
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/subscribers.py
opengever/workspace/tests/test_workspace_workspace.py
opengever/workspace/workspace.py

Instead of reusing plones `Creator` and serialize it as the workspace responsible, the workspace schema contains now simple choice field. This allows to make sure only workspace members are selectable and the responsible is editable by the edit form. Only workspace admins are allowed to edit workspace metadata, the same applies to the responsible field
For [CA-1686]
- API change:
- If breaking:
[CA-1686]: https://4teamwork.atlassian.net/browse/CA-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a new field `responsible`

---

changes/CA-2613.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/searching.rst
opengever/api/solr_query_service.py
opengever/api/tests/test_solrsearch.py

Custom property fields can now be faceted as well using the `@solrsearch` endpoint (except ones of type `text`).
The names for the Solr fields of custom properties, and in which listings they should appear, can be retrieved using the existing `@listing-custom-fields` endpoint.
For [CA-2613](https://4teamwork.atlassian.net/browse/CA-2613)
- API change:

Add support for custom property facets to `@solrsearch` endpoint

---

README.rst
changes/CA-2953.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
docs/public/dev-manual/api/propertysheets.rst
docs/public/dev-manual/api/schemas/opengever.workspace.workspace.inc
opengever/api/config.py
opengever/api/tests/test_assigned_users.py
opengever/api/tests/test_config.py
opengever/api/tests/test_dossier_participations.py
opengever/api/tests/test_local_roles.py
opengever/api/tests/test_ogdsuserlisting.py
opengever/api/tests/test_serializer.py
opengever/api/tests/test_users.py
opengever/api/tests/test_watchers.py
opengever/base/monkey/patches/readonly.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20211220121109_add_property_sheets_manager_role/rolemap.xml
opengever/core/upgrades/20211220121109_add_property_sheets_manager_role/upgrade.py
opengever/propertysheets/api/configure.zcml
opengever/propertysheets/configure.zcml
opengever/propertysheets/permissions.zcml
opengever/propertysheets/tests/test_schema_definition_post.py
opengever/sharing/tests/test_sharing.py
opengever/testing/fixtures.py

This introduces a new permission `opengever.propertysheets: Manage PropertySheets` that is used to protect `POST` and `DELETE` to the `@propertysheets` endpoint. This permission is assigned to the `Manager` and a new `PropertySheetsManager` role.
Therefore, the `PropertySheetsManager` role can be assigned to a group of users that should be able to manage propertysheets (setting dynamic defaults is still only allowed for the `Manager` role though).
The `@config` endpoint also includes a new key `is_propertysheets_manager` to indicate whether the user is allowed to manage property sheets _(and the respective functionality should be displayed in the frontend)_.
For [CA-2953](https://4teamwork.atlassian.net/browse/CA-2953)
_Everything has to be done/checked. Checked but not present means the …

Introduce PropertySheetsManager role and custom permission 

---

changes/CA-3339.bugfix
versions.cfg

Currently there's no official Solr distribution that contains the latest security fixes for Log4j. Thus we use our own for now.
For [CA-3339](https://4teamwork.atlassian.net/browse/CA-3339)

Use custom Solr distribution containing Log4j 2.17.0

---

changes/CA-3044-2.feature
changes/CA-3044.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/searching.rst
opengever/api/configure.zcml
opengever/api/solr_query_service.py
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py
opengever/api/tests/test_utils.py
opengever/api/utils.py

This PR extends the `@solrsearch` endpoint with a new `fq`: `url` (or you can also use `@id` as an alias).
This allows us to directly filter objects by its `@id`. 
Since queries can be very long and an url is limited by the client, server or proxy, we now allow `POST` requests against the `@solrsearch` endpoint. This allows us to use the request-body instead the query-string to pass arguments.
The `POST` endpoint is an alias for the `GET` endpoint. So it behaves exactly the same with exactly the same feature-set. The only difference is, that we pass JSON with the `POST` endpoint.
Here is a practical example of how to use the `POST` endpoint in combination with the `@id` filter:
**Request**
```http
POST /plone/@solrsearch HTTP/1.1
Content-Type: application/json
Accept: application/json
{ …
```

Implement @solrsearch filtering by @id through a POST request

---

changes/CA-2794.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
docs/public/dev-manual/api/propertysheets.rst
opengever/api/tests/test_listing_custom_fields.py
opengever/document/tests/test_indexers.py
opengever/propertysheets/annotation.py
opengever/propertysheets/definition.py
opengever/propertysheets/solr.py
opengever/propertysheets/tests/test_definition.py
opengever/propertysheets/tests/test_solr.py
opengever/testing/fixtures.py
solr-conf/managed-schema

Two general adjustments were necessary for correct display and indexing:
- The `@listing-custom-fields` endpoint contains now also the widget information
- Don't use `json_compatible` and ftw.solr `to_iso8601` instead when passing in date values to the solr index handler 
For [CA-2794]
- API change:
- If breaking:
- (not necessary IMHO) #delivery channel notified about breaking change
- _(not necessary IMHO)_ Scrum master is informed 
[CA-2794]: https://4teamwork.atlassian.net/browse/CA-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new customfield type date.

---

changes/CA-2791-2.feature
changes/CA-2791.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/listing.py
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py
opengever/core/upgrades/20211221135724_add_dossier_type_index/upgrade.py
opengever/dossier/configure.zcml
opengever/dossier/dossiertemplate/configure.zcml
opengever/dossier/dossiertemplate/indexers.py
opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py
solr-conf/managed-schema

This PR adds a new solr index `dossier_type` according to the `document_type` index.
The `dossier_type` is also added as a `ListingFiled` for the `@listing` endpoint.
For [CA-2791]
- API change:
- If breaking:
[CA-2791]: https://4teamwork.atlassian.net/browse/CA-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add dossier type index

---

opengever/wopi/browser/wopi.py
opengever/wopi/tests/test_wopi.py

The `Creator` for documents imported via OGGBundle may not be set (`Creator()` returns empty string).
This fix makes `OwnerId` fall back to `getOwner().getId()` in such a case, in order to make OfficeOnline happy.
For [CA-3318](https://4teamwork.atlassian.net/browse/CA-3318)

WOPI check_file_info(): Fall back to document owner if creator isn't set.

---

changes/CA-2792.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py

Since in the new UI the document type should be available as a column in the table, the document type must be translated.
For [CA-2792]
- API change:
[CA-2792]: https://4teamwork.atlassian.net/browse/CA-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Expose document_type_label column in @listing endpoint

---

changes/CA-2791-3.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/testserver.py
opengever/dossier/vocabularies.py

This PR adds a new `feature` to the `@config` endpoint called: `multiple_dossier_types`
It also patches the available dossier-types for the testserver. This allows us to write better e2e tests with dossier-types.
Changing the dossier-types for the whole dev-deployment seems to be a big deal since we would change the default for production as well.
For [CA-2791]
- API change:
- If breaking:
[CA-2791]: https://4teamwork.atlassian.net/browse/CA-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

Add a new feature to the '@config' endpiont: 'multiple_dossier_types'

---

changes/CA-3389.bugfix
opengever/api/tests/test_save_document_as_pdf.py
opengever/document/document.py

Workspace documents have their own workflow, which has only a single state. This breaks save PDF under, as the function sets the document to shadow state and then transitions it back to active state when the PDF has been posted back by bumblebee. This transition did not exist and led to the function failing.
For [CA-3389]
[CA-3389]: https://4teamwork.atlassian.net/browse/CA-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix save PDF under for workspace documents.

---

changes/CA-2598.feature
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20211223165356_add_i_inbound_mail_settings_registry_record/registry.xml
opengever/core/upgrades/20211223165356_add_i_inbound_mail_settings_registry_record/upgrade.py
opengever/mail/browser/inbound.py
opengever/mail/interfaces.py
opengever/mail/tests/test_inbound.py

This adds a new registry setting `IInboundMailSettings.sender_aliases` of type dict that can be used to alias sender addresses for incoming mails to a GEVER user. Mails coming from those senders will then be created with the respective user instead of getting rejected as unknown sender.
The lookup for an alias in the `email address -> userid` mapping is **case-insensitive** (because users might easily have a irregular casing configured in their MUA). The lookup of a user based on the `userid` however is **case-sensitive** (`getUserById()`) - but since we control that aspect, this shouldn't be an issue. 
The regular user lookup via sender email address has precedence - if the sender address can be resolved to a user, any potential entries in alias table will be ignored.
The PR to configure …

Inbound mail: Add support for sender address aliases

---

changes/CA-3437.bugfix
opengever/document/fileactions.py
opengever/document/tests/test_fileactions.py

Trashed documents should not be editable in office online.
For [CA-3437]
[CA-3437]: https://4teamwork.atlassian.net/browse/CA-3437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disallow edit with office online for trashed documents.

---

changes/CA-3382.bugfix
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_linked_workspaces.py

Copying a document with a related document to a workspace will fail, as the related item does not exist on the teamraum deployment (and we pass the serialized object, which will lead to errors on the other side). So as this does anyway not make sense, we simply drop that field before copying the document to the workspace.
For [CA-3382]
[CA-3382]: https://4teamwork.atlassian.net/browse/CA-3382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Drop related items when copying document to workspace.

---

changes/CA-2791-4.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py

Exposes the `dossier_type_label` column in the `@listing` endpoint according to https://github.com/4teamwork/opengever.core/pull/7316 which does the same with the `document_type_label`.
For [CA-2791]
- API change:
- If breaking:
[CA-2791]: https://4teamwork.atlassian.net/browse/CA-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Expose dossier_type_label column in @listing endpoint.

---

changes/CA-2989.other
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/configure.zcml.bob
opengever/setup/deploy.py
opengever/setup/meta.py

We do not need a specific workspace administrator group, instead we give the Administrator role to the `tr_administrators` group (which will be the default for teamraum deployments).
For [CA-2989]
[CA-2989]: https://4teamwork.atlassian.net/browse/CA-2989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Drop workspace administrator group from policy templates and setup.

---

changes/CA-3455.bugfix
opengever/meeting/command.py

It seems the condition introduced in https://github.com/4teamwork/opengever.core/commit/cf5c7401c926e2247963dd9622d30ce9688a4416 was wrong. When creating a proposal excerpt we skip merging only if both the head and suffix templates are missing. Otherwise we need to merge with the agendaitem file.
This cannot be easily tested, hence no test...
For [CA-3455]
[CA-3455]: https://4teamwork.atlassian.net/browse/CA-3455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Correctly handle missing excerpt suffix template when creating excerpt.

---

README.rst
changes/testserver-docker.feature
docker-compose.yml
docker/testserver/Dockerfile
docker/testserver/README.md
docker/testserver/bin/testserver
docker/testserver/docker-entrypoint.sh
docker/testserver/requirements-testserver.txt
opengever/core/solr_testing.py
opengever/core/testserver.py

The goal is to be able to run the testserver in docker, so that:
1. it can be easily used for testing other components (e.g. RIS)
2. devs who are developing services using GEVER can run the testserver locally without having to run buildout.
This pull request makes it possible to run the testserver with docker-compose. It is not yet very optimized and the build process is not automated.
- The testserver is integrated in the `docker-compose.yml`, so that it can be easily run with docker compose and shares the services (such as sablon).
- The testserver has to be changed so that it supports the case that solr is running on a different host than `localhost`, so that the solr container can be accessed over the docker compose network.
- The Dockerfile of the testserver currently needs to …

Docker for testserver

---

changes/CA-3476.bugfix
opengever/dossier/move_items.py
opengever/dossier/tests/test_move_items.py

Trying to move a proposal document was not handled correctly anymore in the classic UI and led to an error.
For [CA-3476]
[CA-3476]: https://4teamwork.atlassian.net/browse/CA-3476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Correctly handle error when trying to move proposal document.

---

README.rst
changes/CA-2755.other
opengever/api/not_reported_exceptions.py
opengever/api/trash.py
opengever/api/tus.py
opengever/api/upload_structure.py
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/maybe_report_exception.py
opengever/base/monkey/patches/verify_object_paste.py
opengever/document/move.py
opengever/dossier/move_items.py
opengever/workspace/participation/browser/manage_participants.py

I did not like the idea of excluding errors using the `RAVEN_DISABLE_EXCEPTIONS` environment variable from `ftw.raven`, notably because it only allows to exclude whole classes of exceptions and because it is not easily visible in the code. Also this did not seem like a very future proof solution for when we move away from ftw.raven. 
Instead I chose to not report to sentry all exceptions inheriting from a newly introduced `NotReportedException` class. This allows to specifically disregard certain exceptions in sentry, while still returning the correct error codes and types over the API.
I went over all sentry issues and checked which ones should be disregarded. For a few of them, notably validation errors which are all handled generically …

Exclude exceptions that happen in normal usage from sentry.

---

changes/CA-2954-1.feature
changes/CA-2954-2.feature
changes/CA-2954-3.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/propertysheets.rst
opengever/api/schema/schema.py
opengever/api/tests/test_schema.py
opengever/propertysheets/api/configure.zcml
opengever/propertysheets/api/definition_serializer.py
opengever/propertysheets/api/get.py
opengever/propertysheets/api/post.py
opengever/propertysheets/schema.py
opengever/propertysheets/tests/test_definition_serializer.py
opengever/propertysheets/tests/test_schema_definition_get.py
opengever/propertysheets/tests/test_schema_definition_post.py

Use the same custom format that POST requests accept as input for GET responses (and the POST response upon successful creation).
This format, unlike the serialization to a JSON schema, is much more compact, and more importantly, **information-preserving**. For example:
In propertysheet definitions, we distinguish between `texline` and `multiple_choice` (of textline) fields on the field type level. In JSON schema, these both get serialized to a field with a `type` of `string`, but the second has a vocabulary.
Also, by using the same JSON format for serialization and deserialization with the `@propertysheets` endpoint, it will finally follow the behavior that any response it gives, will
- result in the creation of a equivalent sheet if POSTed
- not result in a meaningful modification if …

`@propertysheets` GET: Return same format as POST, instead of JSON schema

---

changes/CA-2954-4.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/propertysheets.rst
opengever/propertysheets/api/base.py
opengever/propertysheets/api/configure.zcml
opengever/propertysheets/api/get.py
opengever/propertysheets/api/patch.py
opengever/propertysheets/api/post.py
opengever/propertysheets/tests/test_api_error_formatting.py
opengever/propertysheets/tests/test_schema_definition_get.py
opengever/propertysheets/tests/test_schema_definition_patch.py
opengever/propertysheets/tests/test_schema_definition_post.py

This implements PATCH support for the `@propertysheets` endpoint.
PATCH semantics only apply to the topmost level (assignments and fields) - if either of those keys is omitted, it will be preserved as-is. Omitting a field from the list of fields however will **delete** it. The field list as a whole therefore needs to be modified by the caller, and always be sent in its entirety.
Dynamic defaults also need some special handling for PATCH:
We also allow non-Managers to PATCH propertysheets that contain dynamic defaults (which otherwise may only be set by managers), if those dynamic defaults already existed before and don't get modified by the PATCH request.
This is necessary to allow regular PropertySheetsManagers to allow saving the form with modifications to other things that don't …

Add PATCH support for `@propertysheets` endpoint

---

README.rst
changes/CA-3290.feature
opengever/nightlyjobs/browser/configure.zcml
opengever/nightlyjobs/browser/nightly_jobs_stats.py
opengever/nightlyjobs/configure.zcml
opengever/nightlyjobs/cronjobs.py
opengever/nightlyjobs/tests/test_nightly_jobs_stats.py
setup.py

The BrowserView is accessible only for managers.
For [CA-3290]
[CA-3290]: https://4teamwork.atlassian.net/browse/CA-3290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add browser view and zopectl command to show nightly jobs stats.

---

changes/CA-3499.other
opengever/api/tests/test_actual_workspace_members.py
opengever/api/tests/test_workspace.py
opengever/base/tests/test_response.py
opengever/ogds/base/sources.py
opengever/workspace/tests/test_workspace_sources.py
opengever/workspace/tests/test_workspace_workspace.py

Otherwise, users with the same name cannot be distinguished.
For [CA-3499]
- API change:
- If breaking:
[CA-3499]: https://4teamwork.atlassian.net/browse/CA-3499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Return fullname and userid as term title in ActualWorkspaceMemberSource.

---

changes/CA-2954-5.other
docs/public/dev-manual/api/api_changelog.rst
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/en/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/base/schema.py
opengever/propertysheets/api/base.py
opengever/propertysheets/api/configure.zcml
opengever/propertysheets/api/error_serialization.py
opengever/propertysheets/api/patch.py
opengever/propertysheets/api/post.py
opengever/propertysheets/exceptions.py
opengever/propertysheets/locales/de/LC_MESSAGES/opengever.propertysheets.po
opengever/propertysheets/locales/en/LC_MESSAGES/opengever.propertysheets.po
opengever/propertysheets/locales/fr/LC_MESSAGES/opengever.propertysheets.po
opengever/propertysheets/locales/opengever.propertysheets.pot
opengever/propertysheets/metaschema.py
opengever/propertysheets/tests/test_api_error_formatting.py
opengever/propertysheets/tests/test_propertysheet_metaschema.py
opengever/propertysheets/tests/test_schema_definition_patch.py
opengever/propertysheets/tests/test_schema_definition_post.py

This overhauls the error handling in the `@propertysheets` APIs in a way that the client-side errors get serialized in a way where they contain a deliberately crafted `translated_message`.
We do this to enable the frontend to just display this one message at the top of the form, without any further processing of the response or highlighting of the offending widget.
The message must therefore contain enough context so that the user can identify where the error is, and what he needs to change to fix it.
This generated `translated_message` is a multi-line string (three, sometimes four lines), where each line gets progressively more specific / local.
Example:
```
The form contains errors:
Field 3 ('location'):
Parameter 'title': Value is too long
(Max: 128 characters, Actual length: 135 …
```

Serialize `@propertysheet` errors in a frontend-friendly way

---

changes/testserver-auto-isolate.feature
opengever/core/testserver_zope2server.py

The testserver now automatically runs the initial isolation setup on startup before starting the XMLRPC server.
That means that users and tests no longer have to run a `zodb_setup` or `isolation` after starting up.
This makes the usage easier and more convenient when the app is doing requests on startup before the first test.
The testserver prints the line `Setting up isolation (zodb_setup).` when it is doing the isolation on startup; making it easier for devs to figure out whether their installed version is doing that already.
For [HG-2189]
- API change:
- If …

Testserver: auto-isolate on startup.

---

opengever/testing/fixtures.py

This PR uses static uids for the workspace testing fixtures. It seems that we've forgotten it while adding the fixtures.
We need this change to make frontend testing fixtures static.

Use static fixtures for workspace fixtures

---

changes/CA-3543.bugfix
opengever/disposition/ech0160/model/dossier.py
opengever/disposition/tests/test_model.py

Currently the documents inside a proposal or a task, are not included in the eCH-0160 SIP export. This PR fixes that.
For [CA-3543]
[CA-3543]: https://4teamwork.atlassian.net/browse/CA-3543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ech0160 export: include documents inside tasks and proposals.

---

changes/CA-2174.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/searching.rst
opengever/api/solr_query_service.py
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py
opengever/core/testserver_selftest.py

This PR changes the `path_parent` filter query.
Since the physical path of an object is only for internal use, we have to change the `path_parent` filter query to accept relativ paths.
For [CA-2174]
- API change:
- If breaking:
[CA-2174]: https://4teamwork.atlassian.net/browse/CA-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use relative paths for the @solrsearch path_parent filter query.

---

changes/CA-1938.feature
opengever/api/tests/test_actors.py
opengever/base/casauth.py
opengever/base/interfaces.py
opengever/base/tests/test_casauth.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20220126084051_add_actor_settings_registry/registry.xml
opengever/core/upgrades/20220126084051_add_actor_settings_registry/upgrade.py
opengever/ogds/base/actor.py

This PR implements an  `IActorSettings` registry interface with a `user_avatar_image_source_type` property.
This allows us to configure the portrait_url lookup between the three modes:
- plone only
- portal only
- plone with fallback to portal
The `@actors` endpoint respects this setting and returns the expected portrait url.
For [CA-1938]
- API change:
- If breaking:
[CA-1938]: https://4teamwork.atlassian.net/browse/CA-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

Actor portrait_url from different sources

---

changes/CA-3289.other
opengever/core/tests/test_upgrade.py
opengever/core/upgrade.py
opengever/core/upgrades/20210205084521_add_sortable_reference_number_index/upgrade.py
opengever/core/upgrades/20211102201059_reindex_is_completed_for_tasks_and_todos/upgrade.py
opengever/core/upgrades/20211221135724_add_dossier_type_index/upgrade.py
opengever/core/upgrades/20220118173918_migrate_nightly_indexer_maintenance_jobs/upgrade.py
opengever/core/upgrades/20220118175855_migrate_default_value_persister_maintenance_jobs/upgrade.py
opengever/nightlyjobs/maintenance_jobs.py

With this PR we modify the `NightlyIndexer` and `DefaultValuePersister` to store UIDs instead of IntIDs in their queues. This allows to iterate over brains instead of objects in the upgrade steps (although the only upgrade currently using `DefaultValuePersister` still needs to fetch the objects to decide whether a given objects needs persisting or not).
As storing the UIDs in the queue is less memory efficient than storing the IntIDs, we have left `NightlyWorkflowSecurityUpdater` untouched, i.e. it still stores IntIDs in its queue, as it is anyway necessary to get the objects during the upgrade step to check for placeful workflows.
I also had to write a migration for maintenance jobs from `NightlyIndexer` and `DefaultValuePersister` that might still be in queues but with IntIDs instead of …

Improve upgrade memory usage

---

changes/CA-3551.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/schema/globalsources.py
opengever/api/tests/test_globalsources.py
opengever/ogds/base/sources.py

The name `all_users_and_groups` actually already lets the API user assume that inactive users will also be found.
This allows administrators to create a permission_report also for inactive users which are no longer assigned to a org_unit.
For [CA-3551]
- API change:
[CA-3551]: https://4teamwork.atlassian.net/browse/CA-3551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include inactive users in the all_users_and_groups source.

---

changes/CA-3506-1.bugfix
changes/CA-3506-2.bugfix
changes/CA-3506-3.bugfix
changes/CA-3506.bugfix
opengever/api/tests/test_tus.py
opengever/base/tests/test_quickupload.py
opengever/base/transport.py
opengever/base/utils.py
opengever/mail/tests/test_extract_attachments.py
opengever/mail/tests/test_inbound.py
opengever/propertysheets/annotation.py
opengever/propertysheets/api/base.py
opengever/propertysheets/testing.py
opengever/propertysheets/tests/test_creation_defaults.py
opengever/propertysheets/tests/test_definition.py
opengever/propertysheets/tests/test_document_custom_properties.py
opengever/propertysheets/tests/test_dossier_custom_properties.py
opengever/propertysheets/tests/test_mail_custom_properties.py
opengever/propertysheets/tests/test_schema.py
opengever/propertysheets/tests/test_schema_definition_post.py
opengever/propertysheets/tests/test_serializer.py
opengever/propertysheets/tests/test_transporter.py
opengever/propertysheets/tests/test_widget.py
opengever/propertysheets/widgets.py

This fixes several issues found when adding more tests for the propertysheets `date` field type:
No longer pass returned properties through `json_compatible()` when reading them from annotations storage, e.g. with a read access to `IDocumentCustomProperties(doc).custom_properties`.
This was originally done to make the task transporter happy, but that doesn't really work, and caused issues with date fields:
- It didn't _really_ work for the transporter, because `json_compatible()` may be a no-op for Python fields that have a direct equivalent in JSON, but actually performs a serialization for types like dates that don't. Those would then need to be deserialized on the other side. But since `json_compatible()` is a one way "serialization" only, a proper serialization/deserialization would …

Fix propertysheets `date` field serialization and default

---

opengever/propertysheets/api/base.py
opengever/propertysheets/tests/test_schema_definition_post.py

Because the new frontend apprently omits empty fields on **add**, but sends them with `null` on **edit**, the static `default` for a propertysheet field may receive `None`, instead of a string.
`strptime` then raises a `TypeError` instead of a `ValueError` which also needs to be handled.
For [CA-3506](https://4teamwork.atlassian.net/browse/CA-3506)

Propertysheets: Make sure preprocessing of static defaults doesn't choke on non-string types.

---

changes/CA-3631.bugfix
opengever/activity/mailer.py
opengever/activity/tests/test_mail.py
opengever/api/tests/test_share_content.py

With https://github.com/4teamwork/opengever.core/pull/7270 I broke the content-sharing for multiple recipients. Because we pass in now the `mail_to` manually we need to make sure its a list and not a comma separated string.
For [CA-3631]
[CA-3631]: https://4teamwork.atlassian.net/browse/CA-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix content-sharing for multiple recipients.

---

changes/CA-3631.bugfix
opengever/activity/mailer.py
opengever/api/tests/test_share_content.py

The previous fix #7356 only worked for To recipients but the cc recipients are still ignored.
For [CA-3631]
[CA-3631]: https://4teamwork.atlassian.net/browse/CA-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix content-sharing for cc recipients.

---

opengever/propertysheets/locales/fr/LC_MESSAGES/opengever.propertysheets.po

This fixes an error that prevents us from building the docker images `ogcore` and its dependant `testserver`.
I've run `bin/i18n-build opengever.propertysheets` after changing the file to make sure it remains stable. Apparently it prefers to have the newlines as provided in this PR.
The build error in detail:
```
=> ERROR [build-stage 11/18] RUN find /app/opengever -name "*.po" | xargs -I@ sh -c 'msgfmt @ -o "$(dirname @)/$(basename @ .po)".mo' &&     find /app/plonetheme -name "*.po" | xargs -I@ sh -c 'msgfmt @ -o "$(dirname @)/$(basename @ .po)".mo'                                                                                                                  0.8s
------
> [build-stage 11/18] RUN find /app/opengever -name "*.po" | xargs -I@ sh -c 'msgfmt @ -o "$(dirname @)/$(basename @ …
```

Fix missing msgstr in propertysheet po file.

---

changes/GH-6894.change
opengever/base/configure.zcml
opengever/base/subscribers.py
opengever/base/tests/test_security_headers.py
opengever/wopi/browser/edit.py
opengever/wopi/tests/test_edit.py

Setting these headers is best practice in terms of security.
Only load scripts and stylesheets with the correct content type:
```
X-Content-Type-Options: nosniff
```
Enable browser protection for reflected XSS attacks:
```
X-XSS-Protection: 1; mode=block
```
Only send referrer on requests to the same origin
```
Referrer-Policy: same-origin
```
For HTML resources we only allow resources from the same origin, but we have to allow eval and inline js/css. Images are allowed from the same origin and from data urls. We disallow plugins and framing.
```
Content-Security-Policy: default-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data:; object-src 'none'; frame-ancestors 'none'
```
For other resources we disallow the loading of any resources and disable framing.
``` …
```

Set security related HTTP headers

---

changes/CA-3574.bugfix
opengever/workspace/subscribers.py

We suppress creation of activities in the `todo_review_state_changed()` handler if it gets called during an upgrade to avoid failing upgrade steps.
This is because the creation of activities will emit SQL statements (queries, as well as inserts) which are likely to fail:
They will use the current models SQL (for Activities, Notifications, Users, ...) as present in the already updated code, but may run against an SQL database that hasn't had its schema fully upgraded yet.
(There may be later upgrade steps pending that would upgrade it and bring it in line with the schema on the Python models).
This has specifically been a problem with the upgrade [`20211105114219_add_completed_state_for_todos`](https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20211105114219_ad …

Suppress creation of todo completion activities during upgrades:

---

changes/CA-3336.feature
changes/CA-3491.feature
opengever/latex/configure.zcml
opengever/latex/dossierdetails.py
opengever/latex/listing.py
opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/en/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/opengever.latex.pot
opengever/latex/templates/dossierdetails.tex
opengever/latex/tests/test_dossierdetails.py
opengever/latex/tests/test_listing.py

The custom fields are only displayed if a value is set.
For [CA-3491] and [CA-3336] 
[CA-3491]: https://4teamwork.atlassian.net/browse/CA-3491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-3336]: https://4teamwork.atlassian.net/browse/CA-3336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add comments and custom fields to dossier details pdf

---

changes/CA-3625.other
opengever/base/handlers.py

If a new object is added or an existing one is renamed, there's no need to update the security or perform any of the other index updates in this event handler. Further if an object is copied, the security is now updated only once. It was updated twice before, because the object is renamed after beeing added to the container.
This speeds up object creation and copying of objects significantly. E.g. bundle import time is reduced by approximately 30%.
For [CA-3625](https://4teamwork.atlassian.net/browse/CA-3625)

Avoid unnecessary security updates

---

changes/CA-3625.change
opengever/base/warmup.py

Loading the most important catalog indexes into memory doesn't work well for larger sites. It takes several minutes and fills up a lot of memory. We try another approach by calling REST API endpoints that are always called by the frontend on a new page load. At least for read access and when using the new frontend this approach seems to be superior.
Test with ogg1m, new approach:
Warmup duration: `24s`
Memory consumption after warmup: `500 MB`
First Page Load after warmup (Dashboard of new frontend): `7.5s`
Test with ogg1m, old approach:
Warmup duration: `5m 13s`
Memory consumption after warmup: `3.4 GB`
First Page Load after warmup (Dashboard of new frontend): `9.7s`
Test Köniz (very slow disk system), new approach:
Warmup duration: `56s`
Memory consumption after warmup: `400 MB`
First …

Optimize warmup for large sites

---

changes/CA-3673.bugfix
opengever/dossier/browser/participants.py
opengever/latex/dossierdetails.py
opengever/latex/tests/test_dossierdetails.py
opengever/usermigration/tests/test_creator_migrator.py

With this PR we fix the `dossierdetails` view for dossiers containing SQL participations.
For [CA-3673]
[CA-3673]: https://4teamwork.atlassian.net/browse/CA-3673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dossierdetails for dossier with SQL participations.

---

opengever/base/subscribers.py
opengever/base/tests/test_security_headers.py

For responses without a body it doesn't make sense to set the securtiy headers. Also fixes setting the wrong CSP for 304 responses, which breaks the classic frontend if HTTP caching is enabled.
Fix for: https://github.com/4teamwork/opengever.core/pull/6894

Do not set security header for responses without content type

---

changes/CA-3324.other
opengever/api/navigation.py
opengever/api/tests/test_navigation.py

Switch `@navigation` endpoint to Solr queries.
This is in preparation for later adding the `dossier_type`, which is only indexed in Solr. Also, building the navigation by querying Solr instead of the ZCatalog should be noticably faster.
For [CA-3324](https://4teamwork.atlassian.net/browse/CA-3324)

Switch `@navigation` endpoint to Solr queries.

---

changes/CA-3324-1.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/vocabularies.rst
opengever/api/configure.zcml
opengever/api/raw_dossier_types.py
opengever/dossier/tests/test_dossier_types.py
opengever/dossier/vdexvocabs/dossier_types.vdex
opengever/testing/assets/dossier_types.vdex

This endpoint returns the raw contents of the `dossier_types` VDEX vocabulary.
They are returned
- in **inherent order** (even though orderSignificant may be False)
- **unfiltered** (hidden terms are included)
This is needed in order for the frontend to be able to map dossier types to colors in a deterministic way that is stable over time.
Because dossier types are mapped to a fixed-length color palette, and types that have already been mapped to a color once MUST keep that color, we need to provide the frontend with a list of dossier types where historical terms keep their position, and new terms only ever are appended at the end.
This endpoint facilitates this, together with the following rules for editing the `dossier_types.vdex` file:
- New terms must only be **appended at the end**
- …

Add `@raw-dossier-types` endpoint:

---

changes/CA-2878.bugfix
opengever/base/acquisition.py
opengever/base/tests/test_classification.py

When acquiring default values, the [`acquire_field_value()`](https://github.com/4teamwork/opengever.core/blob/cfa50aed2f6acc85fe81bf6c7e1bcd11be0d15b0/opengever/base/acquisition.py#L10-L51) function may encounter objects in the chain that do claim to provide the field, but are missing the actual attribute because it never got persisted properly.
Because we now [use `get_persisted_value_for_field()`](https://github.com/4teamwork/opengever.core/blob/cfa50aed2f6acc85fe81bf6c7e1bcd11be0d15b0/opengever/base/acquisition.py#L43) to fetch the field value, we need to account for the `AttributeError` it [may raise](https://github.com/4teamwork/opengever.core/blob/cfa50aed2f6acc85fe81bf6c7e1bcd11be0d15b0/opengever/base/default_values.py#L112) (unlike the `field.get()` that was used before).
For …

Default value acquisition: Skip intermediate objects missing attribute.

---

changes/CA-3677.bugfix
opengever/document/tests/test_checkout.py
opengever/document/tests/test_indexers.py
opengever/document/versioner.py

When a new version is saved, the file's type may have changed (e.g. from .pdf to .docx), and the filename therefore is updated, and needs to be reindexed.
In particular this was the case in a situation where a PDF was reverted (which creates a new version) to a version that was a Word-Document. In this case the filename in Solr was outdated, because unlike the catalog, metadata in Solr doesn't get updated unless the index is explicitly listed.
❗ FYI: I decided to not add an upgrade step for this issue. I couldn't easily find a way to recognize just the documents that exhibit this specific problem, which would mean reindexing `filename` for all documents. And that is just not justified IMHO for a problem this rare and minor. Also, the situation is self-healing, in the sense that the …

Reindex 'filename' when creating a new document version:

---

changes/CA-2878-1.bugfix
opengever/core/upgrade.py

If an object has been deleted for example, it's intid or UID won't resolve any more, resulting in `None`, and we must not attempt to run `update_security_for(None)`, because that will result in an `AttributeError` (via `ftw.upgrade`).
This blocked nightly jobs (only on `02-digs-test`) when updating SG test. I've made these changes in the source checkout of `opengever.core` and ran nightly jobs again, and then they all ran through successfully.
Sentry: https://sentry.4teamwork.ch/organizations/sentry/issues/82311
❗ Needs backport to `2022.4-stable`.
For [CA-2878](https://4teamwork.atlassian.net/browse/CA-2878)
- Bug fixed:

NightlyWorkflowSecurityUpdater: Gracefully skip objs that can't be resolved

---

changes/CA-3324-5.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20220224162815_add_i_dossier_type_is_dossier_type_colors_feature_enabled_registry_record/registry.xml
opengever/core/upgrades/20220224162815_add_i_dossier_type_is_dossier_type_colors_feature_enabled_registry_record/upgrade.py
opengever/dossier/interfaces.py

`@config`: Add 'dossier_type_colors' feature flag, and the corresponding registry entry.
For [CA-3324](https://4teamwork.atlassian.net/browse/CA-3324)
- API change:

`@config`: Add 'dossier_type_colors' feature flag.

---

changes/CA-3329.feature
docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
opengever/base/schemadump/config.py
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/schemas/dossiers.schema.json
opengever/dossier/behaviors/dossier.py
opengever/dossier/dossiertemplate/behaviors.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_checklist.py
opengever/dossier/tests/test_dossier_template.py

With the checklist field, we can map processes in the new UI.
For [CA-3329]
[CA-3329]: https://4teamwork.atlassian.net/browse/CA-3329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add checklist field to dossier and dossiertemplate

---

changes/CA-3732.bugfix
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api_mail_attach.py

This PR fixes an issue where the `BCC` address was not set in the mail-client if sending a document within a teamraum over email.
https://user-images.githubusercontent.com/557005/155532647-43b05b35-b5e7-40ac-b6cf-7cf5fb345ba8.mov
https://user-images.githubusercontent.com/557005/155532338-514ff255-00ca-4f1f-9293-36598a0c036e.mov
For [CA-3732]
- API change:
- If breaking:
- Bug fixed:
[CA-3732]: https://4teamwork.atlassian.net/browse/CA-3732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

Fix BCC address if sending documents over email in teamraum

---

changes/CA-3324-1.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
docs/public/dev-manual/api/white_labeling_settings.rst
opengever/api/tests/test_white_labeling_settings.py
opengever/api/white_labeling_settings.py
opengever/base/interfaces.py
opengever/core/upgrades/20220228151905_add_dossier_type_colors_whitelabeling_setting/registry.xml
opengever/core/upgrades/20220228151905_add_dossier_type_colors_whitelabeling_setting/upgrade.py
opengever/setup/creation/setuphandler.py
opengever/testing/profiles/testing/white_labeling/settings.json

The setting is needed to display dosing types with different colors in the new frontend
For [CA-3324]
- API change:
[CA-3324]: https://4teamwork.atlassian.net/browse/CA-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add dossier_type_colors whitelabeling setting.

---

changes/HG-2215.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/reference_number.rst
opengever/api/configure.zcml
opengever/api/reference_number.py
opengever/api/tests/test_reference_number.py
opengever/api/tests/test_repository.py

Provide an expandable view `@reference-number` that returns the formatted reference number, a sortable reference number and the unformatted reference number parts.
This helps client applications that need to use the raw reference number or parts of the raw reference.
I did not find an interface for which to register a single service. Instead i found that the `IReferenceNumber` adapter is registered for `ISiteRoot` and `IDexterityContent`. Thus the new service and adapter
mirror the adapter registrations of `IReferenceNumber`. The same service and adapter are registered twice for different interfaces.
This can be used in a client application when raw reference numbers or sortable reference numbers are needed.
For [HG-2215](https://4teamwork.atlassian.net/browse/HG-2215)
_Everything has to …

Provide `@reference-number` expansion and view

---

changes/CA-3771.bugfix
opengever/core/tests/test_upgrade.py
opengever/core/upgrade.py

This PR fixes an issue where upgradesteps are failing when using the `IntIdMaintenanceJobContextManagerMixin` and the queued object has currently no intid.
For [CA-3771]
- API change:
- If breaking:
- Bug fixed:
[CA-3771]: https://4teamwork.atlassian.net/browse/CA-3771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix IntIdMaintenanceJobContextManagerMixin obj_to_key if there is no registered intid.

---

changes/CA-3820.bugfix
changes/CA-3820a.bugfix
opengever/oneoffixx/templates.py
opengever/oneoffixx/utils.py

Filter OneOffixx favorites to only include white listed templates. This fixes a KeyError if the user has favorites of not white listed templates.
```
2022-01-26T10:11:19 ERROR Zope.SiteErrorLog 1643188279.660.546125934712 https://gever.sg.ch/kapo/ordnungssystem/fuehrung-und-koordination/operative-fuehrung/aufbauorganisation/fuehrung-hauptabteilungen-leitungsstellen-abteilungen-gruppen/kriminalpolizei-kripo/administration-fuehrung-kripo/dossier-55851/@oneoffixx-templates
Module plone.rest.service, line 23, in __call__
Module plone.restapi.services, line 21, in render
Module opengever.oneoffixx.service, line 86, in reply …
```

Fix OneOffixx favorites

---

changes/CA-3786.bugfix
opengever/nightlyjobs/runner.py
opengever/nightlyjobs/tests/test_nightly_job_runner.py

Until now, all nightly jobs were aborted when an unexpected error occurred. Now it continues with the next job.
For [CA-3786]
[CA-3786]: https://4teamwork.atlassian.net/browse/CA-3786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle errors in nightly jobs.

---

changes/CA-3822.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/role_assignment_reports.py
opengever/api/tests/test_role_assignment_reports.py

In the frontend, a source is used to select the `principalid`, which prefixes the group ID with `group:`  Therefore, such group ID were classified as "unknown principal".
For [CA-3822]
- API change:
[CA-3822]: https://4teamwork.atlassian.net/browse/CA-3822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle group prefix in principalid in @role-assignment-reports endpoint

---

changes/CA-3711.bugfix
opengever/api/tests/test_linked_workspaces.py
opengever/workspaceclient/linked_workspaces.py

This was not possible because the @search endpoint is batched.
For [CA-3711]
[CA-3711]: https://4teamwork.atlassian.net/browse/CA-3711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow all documents of a linked workspace to be copied to a dossier.

---

changes/CA-3329.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20220311082313_add_dossier_checklist_feature_flag/registry.xml
opengever/core/upgrades/20220311082313_add_dossier_checklist_feature_flag/upgrade.py
opengever/dossier/__init__.py
opengever/dossier/browser/forms.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/interfaces.py
opengever/dossier/tests/test_checklist.py
opengever/dossier/tests/test_dossier_template.py
opengever/testing/integration_test_case.py

A feature flag is needed so that the checklist feature can be sold.
For [CA-3329]
- API change:
[CA-3329]: https://4teamwork.atlassian.net/browse/CA-3329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add dossier checklist feature flag

---

changes/CA-3587.feature
changes/CA-3587.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/linked_workspaces.rst
docs/public/dev-manual/api/workspace/participation.rst
opengever/api/configure.zcml
opengever/api/linked_workspaces.py
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/participations.py
opengever/api/tests/test_linked_workspaces.py
opengever/api/tests/test_participation.py
opengever/workspaceclient/linked_workspaces.py

With this PR we add a new endpoint `@add-participations-on-workspace` allowing to set participations on a linked workspace from the Gever dossier.
To avoid having to do multiple requests to the teamraum deployment and to simplify error handling we enable setting a list of participants in the `@participations` endpoint, so that we have a single request from Gever to Teamraum and setting the participations either works for all participants or None.
I'm not sure whether I should add translations of the error messages. These errors should actually not happen in the new UI.
For [CA-3587]
- API change:
- If breaking:
[CA-3587]: https://4teamwork.atlassian.net/browse/CA-3587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new @linked-workspace-participations endpoint.

---

changes/CA-3682.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dashboard.rst
docs/public/dev-manual/api/index.rst
opengever/api/configure.zcml
opengever/api/dashboard.py
opengever/api/tests/test_dashboard.py
opengever/base/interfaces.py
opengever/core/upgrades/20220224150211_add_dashboard_cards_configuration/registry.xml
opengever/core/upgrades/20220224150211_add_dashboard_cards_configuration/upgrade.py

The new configuration options, allows us to add a customer specific dossier Card, which only lists dossiers of a specific type for example. The current dashboard-settings can be fetched by the `@dashboard-settings` endpoint.
For [CA-3682]
- API change:
[CA-3682]: https://4teamwork.atlassian.net/browse/CA-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add configuration option for gever-ui dashboard cards.

---

opengever/base/interfaces.py

This PR updates the DEFAULT_DASHBOARD_CARDS with the responsibleToggleFilters for the `DashboardCard`.
This is required since we no longer provide the `myDossiersOnly` property in the frontend for more flexibility in configuring the cards.
For [CA-3682]
This is a follow-up PR for https://github.com/4teamwork/gever-ui/pull/2189
- API change:
- If breaking:
- Bug fixed:
[CA-3682]: https://4teamwork.atlassian.net/browse/CA-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

Update DEFAULT_DASHBOARD_CARDS with the responsibleToggleFilters

---

changes/CA-3592.other
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20220315151115_add_access_all_users_and_groups_permission/rolemap.xml
opengever/core/upgrades/20220315151115_add_access_all_users_and_groups_permission/upgrade.py
opengever/readonly/tests/test_all_roles_and_permissions_mapped.py
opengever/workspace/permissions.zcml

This PR adds a new permission `opengever.workspace: Access all users and groups`.
This permission is used to protect internal users and groups from external users.
For [CA-3592]
- API change:
- If breaking:
- Bug fixed:
[CA-3592]: https://4teamwork.atlassian.net/browse/CA-3592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a new global permission "opengever.workspace: Access all users and groups"

---

changes/CA-3274-1.feature
changes/CA-3274-2.bugfix
changes/CA-3274.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/external_activities.rst
opengever/activity/dispatcher.py
opengever/activity/tests/test_plone_center.py
opengever/api/external_activities.py
opengever/api/permissions.zcml
opengever/api/tests/test_external_activities.py
opengever/base/monkey/patches/readonly.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20220316122716_add_global_privileged_notification_dispatcher_role/rolemap.xml
opengever/core/upgrades/20220316122716_add_global_privileged_notification_dispatcher_role/upgrade.py

This adds support for the `notification_recipients` parameter on `@external-activities` to also accept group IDs, resolve them to their members, and dispatch notification to those users.
For this, sending notifications to users _other than yourself_ had to be allowed in that endpoint for users with the necessary privileges. The new permission `opengever.api: Notify Arbitrary Users` allows this (assigned to the new `PrivilegedNotificationDispatcher` role).
In addition, I improved the error handling in that endpoint. Most problems should only cause soft errors, that are reported in an `{'errors': [...]}` list in the response, but still with status `201 Created`.
For [CA-3274](https://4teamwork.atlassian.net/browse/CA-3274)
- API change:

Accept groups in `notification_recipients` for `@external-activities` endpoint 

---

changes/CA-3809.other
opengever/api/errors.py
opengever/api/tests/test_language.py
opengever/api/transition.py
opengever/task/tests/test_api_support.py

For some reason we were serialising `Bad Requests` into a dictionary when executing transitions over the API. Instead now, we do nothing special so that the `Bad Request` actually gets raised and handled by our `GeverErrorHandling`, which will also take care of translating the error if possible.
This also helps the Gever-UI, so that it's automatic error handling will correctly display the returned error. With this change, an error is at least displayed when reassigning an open Task to a Team, although the error is simply displayed as a message and not in the form under the corresponding field (see screenshot). The frontend currently does not have error handling for field validation errors.
For [CA-3809] …

Improve error handling for workflow transitions over the API

---

opengever/task/response_description.py

By reusing the revise response description, the state icon is displayed correctly in the classic UI.
Small fix for the new transition introduced in #7400 for the classic ui.
For [CA-3579]
[CA-3579]: https://4teamwork.atlassian.net/browse/CA-3579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Register description for the new closed-in-progress transition.

---

changes/CA-3890.other
opengever/bumblebee/tests/test_revive_bumblebee_preview.py
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20220323170920_allow_to_revive_bumblebee_previews_in_teamraum/rolemap.xml
opengever/core/upgrades/20220323170920_allow_to_revive_bumblebee_previews_in_teamraum/upgrade.py

In https://github.com/4teamwork/opengever.core/pull/7127 we allowed normal users to revive bumblebee previews in Gever, but forgot that in teamraum deployments nobody is `Reader`... This is confusing as the action appears for broken previews in the new frontend but basically does nothing.
For [CA-3890]
[CA-3890]: https://4teamwork.atlassian.net/browse/CA-3890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow normal users to revive bumblebee previews in Teamraum.

---

changes/CA-3707.feature
docs/schema-dumps/ftw.mail.mail.schema.json
docs/schema-dumps/opengever.document.document.schema.json
docs/schema-dumps/opengever.workspace.workspace.schema.json
opengever/api/linked_workspaces.py
opengever/api/tests/test_linked_workspaces.py
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/schemas/documents.schema.json
opengever/bundle/schemas/workspaces.schema.json
opengever/document/behaviors/metadata.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/workspace.py
opengever/workspaceclient/client.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_client.py
opengever/workspaceclient/tests/test_linked_workspaces.py

We add a field `gever_url` to workspaces and documents. If a workspace is linked to a dossier, `gever_url` refers to the linked dossier. If a workspace document is linked to GEVER document, `gever_url` refers to the linked GEVER document.
For [CA-3707]
[CA-3707]: https://4teamwork.atlassian.net/browse/CA-3707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add gever_url field to workspaces, documents and mails

---

changes/CA-3917.bugfix
opengever/repository/browser/configure.zcml
opengever/repository/tests/test_repository_workflow.py

I don't want to point fingers at anyone, but it seems [someone introduced a new permission to allow Administrators to export the repository as Excel, but used it only for the action and not for the corresponding view.](https://github.com/4teamwork/opengever.core/pull/4659) It still worked for Administrators because they did also have the `AddRepositoryFolder` permission, but now it did not work anymore for `LimitedAdmin`
For [CA-3917]
[CA-3917]: https://4teamwork.atlassian.net/browse/CA-3917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow Administrator and LimitedAdmin to export repository as excel.

---

changes/CA-3597-1.feature
changes/CA-3597-2.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_actions.py
opengever/api/tests/test_config.py
opengever/base/browser/folder_buttons_availability.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/en/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20220324143655_add_workspace_creation_and_linking_flags/actions.xml
opengever/core/upgrades/20220324143655_add_workspace_creation_and_linking_flags/registry.xml
opengever/core/upgrades/20220324143655_add_workspace_creation_and_linking_flags/upgrade.py
opengever/workspace/interfaces.py
opengever/workspaceclient/__init__.py
opengever/workspaceclient/interfaces.py
opengever/workspaceclient/tests/__init__.py

These are configuration options requested by a customer to allow workspace to be created by GEVER only.
The feature flag to restrict workspace creation is only used in the new frontend, we do not restrict anything in the backend.
For [CA-3597]
- API change:
[CA-3597]: https://4teamwork.atlassian.net/browse/CA-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add feature flags to disable link actions and restrict workspace creation

---

README.rst
changes/CA-3883.other
opengever/api/tests/test_dossier_participations.py
opengever/api/tests/test_globalsources.py
opengever/api/tests/test_local_roles.py
opengever/api/tests/test_ogdsuserlisting.py
opengever/api/tests/test_serializer.py
opengever/api/tests/test_users.py
opengever/sharing/tests/test_sharing.py
opengever/testing/fixtures.py

This is to allow testing vocabularies in the Gever-UI (see https://github.com/4teamwork/gever-ui/pull/2199).
For [CA-3883]
[CA-3883]: https://4teamwork.atlassian.net/browse/CA-3883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add inactive user to fixture.

---

opengever/api/breadcrumbs.py
opengever/api/tasktemplatefolder.py
opengever/api/tests/test_breadcrumbs.py

So that the frontend can avoid showing the review state of sub-TaskTemplateFolders in the breadcrumbs.
For [CA-3586]
[CA-3586]: https://4teamwork.atlassian.net/browse/CA-3586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add is_subtasktemplatefolder to breadcrumbs.

---

changes/CA-3880.bugfix
opengever/repository/subscribers.py
opengever/repository/tests/test_subscribers.py

It's not guaranteed that the user which changes the reference_prefix on a repositoryfolder, are allowed to access all content inside this folder, even if its a Administrator, for example if a document is in the removed-state. Therefore we need to reindex the objects with elevated_privileges.
For [CA-3880]
[CA-3880]: https://4teamwork.atlassian.net/browse/CA-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix reference_prefixes update mechanism for removed documents.

---

changes/CA-3716.other
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/ldap/ldap_plugin.xml.bob

Am I the only one who always ends up with two `ou=` in a row after creating a policy? IMO the response to the question "LDAP ou name" will be something starting with `ou=`, e.g. `ou=MyClientID,ou=OneGovGEVER,dc=4teamwork,dc=ch`, so we do not need the `ou=` in the ldap plugin template.
For [CA-3716]
[CA-3716]: https://4teamwork.atlassian.net/browse/CA-3716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid ending up with ou=ou=... in the ldap plugin.

---

changes/CA-3573.feature
opengever/api/tests/test_forwarding.py
opengever/api/tests/test_task.py
opengever/task/activities.py
opengever/task/configure.zcml
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/en/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/response_description.py
opengever/task/task_response.py
opengever/task/tests/test_task.py
opengever/task/tests/test_task_from_template.py
opengever/task/transition.py
opengever/task/util.py

Journal entries are created only for newly closed or canceled tasks.
For [CA-3573]
[CA-3573]: https://4teamwork.atlassian.net/browse/CA-3573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 Add response to parent task when subtask is closed or cancelled

---

opengever/tasktemplates/browser/trigger.py
opengever/tasktemplates/locales/de/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/en/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/opengever.tasktemplates.pot
opengever/tasktemplates/tests/test_trigger.py
opengever/tasktemplates/tests/test_vocabularies.py
opengever/tasktemplates/vocabularies.py

In this PR we:
- Prevent selection of sub-TaskTemplateFolders for triggering in the classic UI. Note that the vocabulary now needs to get the objects, making it inefficient. We could base it on solr instead, but I don't really expect this to be an issue...
- Prevent triggering nested TaskTemplateFolders in the classic UI. When a TaskTemplateFolder containing sub-TaskTemplateFolders is selected for triggering, an error message is shown and the user has to select again.
For [CA-3725]

Prevent triggering nested TaskTemplateFolders in the classic UI

---

changes/CA-3725.change
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/trigger_task_template.rst
opengever/api/configure.zcml
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py

This PR introduces a new endpoint `@task-template-structure` to fetch the full structure of a task-template folder. This allows us to easely render a nested form in the frontend without doing lots of requests or manually building a tree in the frontend.
For [CA-3725]
- API change:
- If breaking:
- Bug fixed:

Add @task-template-structure endpoint

---

changes/CA-3865.bugfix
opengever/api/tests/test_participation.py
opengever/workspace/participation/browser/manage_participants.py

without a corresponding OGDS user. Usually a leftover of a migration
For [CA-3865] 
Needs backport to LTS release `2022.4.x`
- Bug fixed:
[CA-3865]: https://4teamwork.atlassian.net/browse/CA-3865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix deleting workspace participations of inactive users,

---

opengever/api/configure.zcml
opengever/api/tests/test_templatefolder.py

This is a follow-up PR for #7413 
Everyone with view permission should be able to read the task template structure.
This PR fixes an issue For [CA-3725]
- API change:
- If breaking:
- Bug fixed:

Allow regular users to read task template structures

---

docs/public/dev-manual/api/trigger_task_template.rst
opengever/api/configure.zcml
opengever/api/templatefolder.py

This is a follow-up PR for https://github.com/4teamwork/opengever.core/pull/7413
- This PR fixes a copy&paste failure in the dev-manual which ended in a wrong `@id`.
- Renames a  badly named class for the @task-template-structure endpoint 
For [CA-3725]
- API change:
- If breaking:
- Bug fixed:

Rename badly named class for the @task-template-structure endpoint

---

changes/CA-3725.feature
opengever/api/add.py
opengever/api/configure.zcml
opengever/api/process.py
opengever/api/tests/test_process.py
opengever/meeting/vocabulary.py
opengever/tasktemplates/tasktemplatefolder.py

In this PR we implement a new endpoint `@process` which allows to create task sequences. This endpoint is a substitute for the `@trigger-task-template`, but allowing more flexibility. It notably supports nested task sequences and the created process does not need to come from a `TaskTemplateFolder`. The old functionality and endpoint is kept for now, so that we do not have an API change. A few notable points:
- The `@process` can now validate the data of subtasks directly using the `ITask` schema, as we do not have half the data coming from the corresponding `TaskTemplate` which forced us to validate everything by hand before.
- All fields from `ITask` are now supported for the subtasks
- Validation, deadline calculation, data preprocessing and process creation are now all recursive and …

Add @process endpoint supporting nested task sequences.

---

docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/process.rst
docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
docs/public/dev-manual/api/schemas/opengever.document.document.inc
docs/public/dev-manual/api/schemas/opengever.workspace.workspace.inc
docs/public/dev-manual/api/trigger_task_template.rst

Add missing documentation for the `@process` endpoint. This is a follow-up for https://github.com/4teamwork/opengever.core/pull/7416
For [CA-3725]
- API change:
- If breaking:

Add documentation for @process endpoint

---

opengever/api/process.py

`relatedItems` is not necessary in the `ITaskContainer` schema, as the related items are set after validation from the `related_documents` of the process.
For [CA-3725]

Remove unnecessary field from ITaskContainer.

---

changes/CA-3725-2.feature
changes/CA-3725-3.feature
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py
opengever/tasktemplates/content/tasktemplate.py
opengever/tasktemplates/tests/test_tasktemplate.py
opengever/testing/fixtures.py

This PR extends the `@task-template-structure` endpoint with the following:
- serialized tasktemplates includes the `is_private` with a static value of `False`. This attribute is required if creating a task through the `@process` endpoint
- serialized tasktemplates replaces the relative deadline with the absolute deadline. The relative deadline is only relevant if manipulating the template itself, but if we use it to create a `@process`, we need the absolute one
I did not touch the `TaskTemplate` serializer itself because both attributes are only relevant for the `@task-template-structure` endpoint. We do not want to change the template itself since this is used in the add/edit form of the template.
For [CA-3725]
_Everything has to be done/checked. Checked but not present means the author …

Extend @task-template-structure endpoint with useful attributes

---

changes/CA-3831.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_tus.py
opengever/api/tus.py

At the moment it is not possible to upload a document later via @tus-upload for a document that exists only in paper form.
For [CA-3831]
- API change:
[CA-3831]: https://4teamwork.atlassian.net/browse/CA-3831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow uploading a file with @tus-upload endpoint if the document has no file yet

---

changes/CA-3725-6.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/tasks.rst
opengever/api/tasktree.py
opengever/api/tests/test_tasktree.py

This PR updates the `@tasktree` endpoint to properly handle nested tasks.
The previous implementation expected to have the main-task as the context and only one nesting level. This is no longer the case since we provide multi-nesting for by using the `@process` endpoint.
This PR removes the main-task specific attribute `is_task_addable_in_main_task` and adds two attributes: `is_task_addable` and `is_task_addable_before` in a consistent way for each item within the task-tree.
For [CA-3725]
- API change:
- If breaking:
- Bug fixed:
- …

`@tasktree` endpoint properly handles nested tasks

---

changes/CA-4023.bugfix
opengever/task/task.py
opengever/task/tests/test_task_from_template.py

The automatic closing of the main task is a comfort function, should never cause problems when closing a subtask.
For [CA-4023] and https://sentry.4teamwork.ch/organizations/sentry/issues/79537
- Bug fixed:
[CA-4023]: https://4teamwork.atlassian.net/browse/CA-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make closing of main task more fail safe.

---

changes/CA-3909.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/tus_upload.py

This patches [`TUSUpload.cleanup()`](https://github.com/plone/plone.restapi/blob/6.14.0/src/plone/restapi/services/content/tus.py#L372-L377) so that file system data for TUS uploads doesn't get cleaned up immediately during a running transaction, but instead is done in an **afterCommmitHook**, and only if the transaction was successful.
This prevents the following bug that otherwise can occur:
- A file is uploaded in the 2nd stage of a TUS upload using `@tus-upload`
- The blob is added to the ZODB and file system data is cleaned up
- But a write conflict happens when trying to commit the transaction
- Changes to the ZODB are rolled back
- But not the changes on the file system
- The request is retried as part of the conflict resolution
- On the 2nd request, the `@tus-upload` will not find …

TUS upload: Only clean up file system data after successful commit:

---

changes/CA-3911.other
opengever/meeting/browser/meetings/templates/demand_zip.pt
opengever/meeting/browser/resources/zip_export_app.js

This prevents support requests.
For [CA-3911]
[CA-3911]: https://4teamwork.atlassian.net/browse/CA-3911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Increase meeting zip export poll timeout to 5 minutes

---

changes/CA-3577-1.feature
changes/CA-3577-2.feature
changes/CA-3577.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/task.py
opengever/api/tests/test_task.py
opengever/api/tests/test_transfer_task.py
opengever/inbox/tests/test_api_support.py
opengever/inbox/tests/test_workflow.py
opengever/inbox/transition.py
opengever/task/browser/assign.py
opengever/task/browser/forms.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/en/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/localroles.py
opengever/task/task.py
opengever/task/tests/test_assign.py
opengever/task/tests/test_forms.py
opengever/task/tests/test_localroles.py
opengever/task/tests/test_team_tasks.py
opengever/task/transition.py

This allows former responsibles to follow up on what is happening with the task.
For [CA-3577]
- API change:
- If breaking:
[CA-3577]: https://4teamwork.atlassian.net/browse/CA-3577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revoke roles from former task responsibles only when task is completed

---

changes/CA-4021.other
opengever/api/tests/test_copy_paste.py
opengever/base/monkey/patches/verify_object_paste.py

So that the error can be displayed correctly in the frontend.
See also https://github.com/4teamwork/gever-ui/pull/2230
For [CA-4021]
[CA-4021]: https://4teamwork.atlassian.net/browse/CA-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Translate error message when trying to copy a checked-out document.

---

opengever/core/upgrade.py
opengever/core/upgrades/20220421180133_reindex_dossier_comments/upgrade.py
opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py

With the rebuild of the dossier comments from a simple field to a response container, the dossier comments has been dropped from the searchableText by mistake. This PR re adds the dossier comments to the searchableText and provides a nightly upgradestep to reindex dossiers with a comment.
For [CA-3970]
[CA-3970]: https://4teamwork.atlassian.net/browse/CA-3970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Re add dossier comments to the searchable text.

---

changes/CA-4114.bugfix
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_linked_workspaces.py

using `document.content_type` can lead to wrong contentType, because it calls `Format` on the `CMFDefault/DublinCore`, which returns `text/plain` for mails (see CA-4114 for more details).
For [CA-4114]
[CA-4114]: https://4teamwork.atlassian.net/browse/CA-4114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix contentType problem when copying mails with teamraum connect.

---

changes/CA-4069.feature
opengever/base/transport.py
opengever/task/tests/test_transporter.py
opengever/task/transporter.py

When closing a cross-client "information" task, documents can be copied to a dossier on the responsible client. In such cases, we also copied over the "creator" and "created" to the copied document. This is not consistent with normal copy of a document and is a bit confusing as in the journal it says that the document was added by the current user, whereas the creator is still the creator of the original document.
No upgrade step to fix existing such documents. Also I corrected this only for copying documents when closing a task and not generally in the transporter, as I think in most cases it makes sense to copy the Creator and creation date.
For [CA-4096]
[CA-4096]: https://4teamwork.atlassian.net/browse/CA-4096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

Do not copy creator and creation date when transporting task documents.

---

changes/CA-4108.feature
opengever/api/task.py
opengever/api/tests/test_forwarding.py
opengever/api/tests/test_task.py

We need the creator to display him in the task responses (see https://github.com/4teamwork/gever-ui/pull/2242).
For [CA-4069]
[CA-4069]: https://4teamwork.atlassian.net/browse/CA-4069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Return creator in task serialization.

---

changes/CA-4108.bugfix
opengever/api/tests/test_tus.py
opengever/api/tus.py
opengever/core/upgrades/20220428110823_correct_content_type_for_cadwork/upgrade.py

The content type is passed by the frontend to the `tus-upload` endpoint, but this content type comes from the browser or from uppy. This is therefore out of our control and does not work correctly for all content types that we support, notably for Cadwork files. We now set the content type in the backend, using the mimetypes registry, ensuring that content type is at least set correctly for all types supported by OfficeConnector. 
For [CA-4108]
[CA-4108]: https://4teamwork.atlassian.net/browse/CA-4108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set content type correctly in tus upload

---

opengever/document/move.py

Return statement was accidentally removed in commit dd219d53ae4d696f621f78a7bc620271c85dc5e9. The return statement is not really necessary, it's just for performance.
For [CA-3292]
[CA-3292]: https://4teamwork.atlassian.net/browse/CA-3292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Readd accidentally removed return movability checker.

---

changes/CA-3929.other
opengever/api/tests/test_linked_workspaces.py

The test to copy a document from the second batch from a workspace does not make sense, as there is no such thing as a document from the second batch (the search is not sorted). So this test was flaky and I don't see any way to make a meaningful test for this. See https://ci.4teamwork.ch/builds/498333/tasks/936230
For [CA-3929]
[CA-3929]: https://4teamwork.atlassian.net/browse/CA-3929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove flaky test.

---

changes/CA-2808.feature
opengever/api/tests/test_move.py
opengever/dossier/actions.py
opengever/dossier/configure.zcml
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/move_items.py
opengever/dossier/tests/test_actions.py
opengever/dossier/tests/test_move_items.py
opengever/tasktemplates/actions.py
opengever/tasktemplates/configure.zcml
opengever/tasktemplates/locales/de/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/en/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/opengever.tasktemplates.pot
opengever/tasktemplates/move.py
opengever/tasktemplates/tests/test_actions.py
opengever/tasktemplates/tests/test_move.py

This PR enables the `move_item` context action for dossiertemplates and tasktemplatefolders and the `move_items` folder action for dossiertemplate listings. Furthermore I have implemented a MovabilityChecker for both types
For [CA-2808]
[CA-2808]: https://4teamwork.atlassian.net/browse/CA-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow to move dossiertemplates and tasktemplatefolders

---

changes/CA-4164.bugfix
opengever/api/accessible_workspaces.py
opengever/api/tests/test_accessible_workspaces.py

When a user is deleted from the LDAP, set inactive in the OGDS, it does not have a member data anymore, which leads to raising an error in the @accessible-workspaces endpoint. This is fixed here by checking whether the user is in the OGDS instead, and then adding groups and the users'roles only if he has memberdata.
For [CA-4164]
- Bug fixed:
[CA-4164]: https://4teamwork.atlassian.net/browse/CA-4164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle inactive users in the @accessible-workspaces endpoint.

---

changes/CA-4138.bugfix
opengever/api/move.py
opengever/api/tests/test_move.py

Use our own `get_obj_by_path` in the `@move` endpoint to fix a traversal bug, when not all path elements are accessible.
For [CA-4138]
[CA-4138]: https://4teamwork.atlassian.net/browse/CA-4138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix moving an object with the api where not all path elements are accessible.

---

changes/CA-4179.bugfix
opengever/activity/sources.py

The possible watchers query didn't work for Zug
See also https://sentry.4teamwork.ch/organizations/sentry/issues/75726/events/8c822c0cd82945fab82bd17c9252ee56/?project=17
For [CA-4179]
[CA-4179]: https://4teamwork.atlassian.net/browse/CA-4179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix possible watchers query to work for Oracle databases as well

---

changes/CA-2609-2.feature
changes/CA-2609.feature
opengever/api/listing.py
opengever/api/solr_query_service.py
opengever/api/solrsearch.py
opengever/base/browser/reporting_view.py
opengever/base/solr/__init__.py
opengever/document/browser/report.py
opengever/document/tests/test_reporter.py
opengever/dossier/browser/report.py
opengever/dossier/handlers.py
opengever/dossier/tests/test_reporter.py

This PR changes the report-view:
- it can now export more than 1000 objects. We do no longer define a limit
- it is now possible to choose selected items by passing a listing-name and the corresponding filter/sorting params instead of explicitly define them by paths
- no longer sort the results locally when using paths. Use term-boosting to directly sort the results in solr instead: https://solr.apache.org/guide/6_6/the-standard-query-parser.html since we use a generator for the selected_items.
For [CA-2609]
- API change:
- If breaking:
- Bug fixed:
- New …

Excel mass export for documents and dossiers

---

changes/CA-3958.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/interfaces.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20220510174043_remove_user_snap_settings/registry.xml
opengever/core/upgrades/20220510174043_remove_user_snap_settings/upgrade.py
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

I had to leave the interface, as the upgrade step would otherwise fail.
For [CA-3958]
- API change:
- If breaking:
[CA-3958]: https://4teamwork.atlassian.net/browse/CA-3958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove usersnap settings.

---

changes/CA-3839.feature
opengever/core/upgrades/20220512150235_add_only_attach_original_if_conversion_is_missing_flag/registry.xml
opengever/core/upgrades/20220512150235_add_only_attach_original_if_conversion_is_missing_flag/upgrade.py
opengever/disposition/__init__.py
opengever/disposition/ech0160/model/folder.py
opengever/disposition/interfaces.py
opengever/disposition/tests/test_model.py

For [CA-3839]
[CA-3839]: https://4teamwork.atlassian.net/browse/CA-3839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add disposition setting: only attach original if conversion missing.

---

opengever/base/solr/fields.py

Looking up the custom property fields is expensive.
Here the flamegraph of an export of 10k documents
When performing mass-selection actions, i.e. excel export, we run into massive performance issues:
We can export ~100 documents per second without caching.
**Export of 10k Documents without caching**
After the caching, we can export ~1500 documents per second:
**Export of 10k Documents with caching**
For [CA-2609]
- API change:
- If breaking:
- Bug fixed:
[CA-2609]: …

Cache get_custom_property_solr_field in SolrFieldMapper to boost mass selection actions

---

docs/public/dev-manual/api/api_changelog.rst
opengever/api/configure.zcml
opengever/api/ogdssync.py
opengever/api/tests/test_ogdssync.py
opengever/base/monkey/patches/readonly.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20220518085545_add_new_sync_ogds_permission/rolemap.xml
opengever/core/upgrades/20220518085545_add_new_sync_ogds_permission/upgrade.py
opengever/ogds/base/configure.zcml
opengever/ogds/base/permissions.zcml
opengever/ogds/base/sync/ogds_updater.py

The endpoint is protected with a separate permission, assigned only to the roles administrator and manager.
For [CA-4103]
- only profile changes
- API change:
[CA-4103]: https://4teamwork.atlassian.net/browse/CA-4103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new API enpoint @sync-ogds to start the OGDS sync manually.

---

changes/CA-4245.bugfix
opengever/base/role_assignments.py
opengever/dossier/behaviors/protect_dossier.py
opengever/dossier/tests/test_protect_dossier.py

Currently when a dossier, with tasks, gets protected, all temporary role assignments for tasks are deleted. This should not be the case, because task role assignments are should not be touched by dossiers protect functionality otherwise its not guaranteed that the responsible is able to access the task.
For [CA-4245]
[CA-4245]: https://4teamwork.atlassian.net/browse/CA-4245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

No longer clear task permissions when protecting a dossier.

---

changes/CA-4271.bugfix
opengever/mail/browser/inbound.py
opengever/mail/tests/test_inbound.py
opengever/workspace/participation/storage.py
opengever/workspace/tests/test_participation_storage.py

Currently when sending a mail to a dossier (mail-in) or inviting a user to a workspace. The search for the user by email address was not exact. This leads to problems when having two users with similar email-adresses like `meier@example.com` and `bergmeier@example.com`. The `exact_match` solves this issue, case insensitivity still works.
For [CA-4271]
[CA-4271]: https://4teamwork.atlassian.net/browse/CA-4271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix search by mailaddress in workspace invitations and mail-in.

---

changes/CA-3754.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/ogdsuserlisting.py
opengever/api/tests/test_actors.py
opengever/api/tests/test_ogdsgroups.py
opengever/api/tests/test_ogdsuserlisting.py
opengever/base/browser/list_groupmembers.py
opengever/ogds/models/group.py

Group member representation in the gever-ui was unsatisfactory. To improve this we wanted 
1. group representatives to be sorted
2. to show a real user listing in the group detail view.
I therefore sorted the user in the ogds Group model and implemented a new `groupid` filter for the `@ogds-user-listing` endpoint. 
For [CA-3754]
- API change:
- If breaking:
[CA-3754]: https://4teamwork.atlassian.net/browse/CA-3754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Sort group representatives by lastname and allow filtering ogds-user-listing by group membership.

---

changes/CA-4296.bugfix
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

This PR properly orders groups from the `AllGroupsSource` by `title` and `groupid`
For [CA-4296]
- API change:
- If breaking:
- Bug fixed:
[CA-4296]: https://4teamwork.atlassian.net/browse/CA-4296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Order AllGroupsSource groups by title.

---

README.rst
base-plone-4.3.x.cfg
development.cfg
docker-compose.yml
docker/solr/Dockerfile
docker/solr/create_and_update_cores.sh
opengever/core/cached_testing.py
opengever/core/solr_testing.py
opengever/core/testing.py
test-functional-solr.cfg
test-solr.cfg
test-testserver-selftest.cfg

Run Solr with Docker instead of installing it with Buildout.
This has several advantages:
- The required services for development can be started with one command `docker-compose up -d`.
- No locally installed JDK required.
- Better isolation. Solr for development does not interfere with Solr for running tests.
The Solr image has been extended to support the creation of multiple cores on startup.
Further the configuration of each core is updated on container startup. Before this change, the configuration of a core was never updated even if there were changes added to the image.
For [CA-XXXX]

Solr with docker

---

changes/CA-4037.feature
opengever/base/schemadump/schema.py
opengever/bundle/cfgs/oggbundle.cfg
opengever/bundle/schemas/dossiers.schema.json
opengever/bundle/sections/participations.py
opengever/bundle/tests/assets/basic.oggbundle/dossiers.json
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/bundle/transmogrifier.zcml
opengever/dossier/participations.py

This adds support for an additional key `_participations` in the dossier bundle import which allows to import dossier participations. The participant ids and roles are not validated, this gives us more flexibility during migrations. Moreover, GEVER can handle Ids that no longer exist or are incorrect. 
For [CA-4037]
[CA-4037]: https://4teamwork.atlassian.net/browse/CA-4037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support importing dossier participations in bundle import.

---

opengever/core/testserver.py

Since https://github.com/4teamwork/opengever.core/pull/7427 we run Solr with Docker.
Because of that, blobs always have to be uploaded to Solr. But the testserver did not upload blobs if the Solr hostname was localhost.

Always upload blobs to Solr from testserver

---

changes/CA-4012.bugfix
changes/CA-4012.feature
opengever/propertysheets/definition.py
opengever/propertysheets/deserializer.py
opengever/propertysheets/helpers.py
opengever/propertysheets/interfaces.py
opengever/propertysheets/serializer.py
opengever/propertysheets/tests/test_deserializer.py
opengever/propertysheets/tests/test_field.py
opengever/propertysheets/tests/test_serializer.py

With this PR we modify the behaviour of choice and multiple choice fields for custom properties, ensuring that the current value for such a field remains valid if the list of valid choices is modified. Both serialization and deserialization of the `PropertySheetField` now supports the current value of the field as valid. Moreover I fixed an issue leading to multiple choice fields never being validated.
For [CA-4012]
[CA-4012]: https://4teamwork.atlassian.net/browse/CA-4012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow current value in single or multiple choice fields for custom properties.

---

changes/CA-4154.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/schemas/opengever.workspace.meeting.inc
docs/public/dev-manual/api/workspace/attendees_presence_states.rst
docs/public/dev-manual/api/workspace/index.rst
docs/schema-dumps/opengever.workspace.meeting.schema.json
opengever/api/attendees_presence_states.py
opengever/api/configure.zcml
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/tests/test_attendees_presence_states.py
opengever/api/workspace_meeting.py
opengever/base/schemadump/config.py
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt
opengever/workspace/configure.zcml
opengever/workspace/interfaces.py
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/tests/test_workspace_meeting.py
opengever/workspace/workspace_meeting.py

Some additional fields are needed for workspace meetings. The fields are also included in the PDF protocol.
For [CA-4154]
- API change:
[CA-4154]: https://4teamwork.atlassian.net/browse/CA-4154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add chair, secretary and attendees presence state to workspace meeting

---

docs/public/dev-manual/oggbundle/index.rst
opengever/base/schemadump/config.py
opengever/base/schemadump/schema.py
opengever/bundle/loader.py
opengever/bundle/report.py
opengever/bundle/schemas/ogds_users.schema.json
opengever/bundle/sections/constructor.py
opengever/bundle/sections/resolveguid.py
opengever/bundle/tests/assets/basic.oggbundle/ogds_users.json
opengever/bundle/tests/helpers.py
opengever/bundle/tests/test_bundle_loader.py
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/bundle/tests/test_section_bundlesource.py
opengever/bundle/tests/test_teamraum_oggbundle_pipeline.py
opengever/bundle/tests/test_teamraum_oggbundle_rootless_pipeline.py

With this PR the bunde import now also provide the possibility to import SQL objects, currently only OGDS Users are supported. But I implemented a generic way, so that support for other SQL Objects could be easily added.
Used for [CA-4038], where the goal is to import old, inactive users into the ogds.
[CA-4038]: https://4teamwork.atlassian.net/browse/CA-4038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support importing OGDS Users in a bundle import

---

changes/CA-4299.feature
opengever/api/tests/test_journal.py
opengever/journal/entry.py
opengever/journal/tests/test_journal_tab.py

This provides the ability to format journal entry comments.
For [CA-4299]
[CA-4299]: https://4teamwork.atlassian.net/browse/CA-4299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow saving journal entry comments as HTML structure

---

changes/CA-4039.feature
docs/public/dev-manual/oggbundle/index.rst
opengever/base/schemadump/schema.py
opengever/bundle/cfgs/oggbundle.cfg
opengever/bundle/schemas/documents.schema.json
opengever/bundle/schemas/dossiers.schema.json
opengever/bundle/schemas/repofolders.schema.json
opengever/bundle/schemas/reporoots.schema.json
opengever/bundle/schemas/workspacefolders.schema.json
opengever/bundle/schemas/workspaceroots.schema.json
opengever/bundle/schemas/workspaces.schema.json
opengever/bundle/sections/constructor.py
opengever/bundle/sections/creator.py
opengever/bundle/sections/manual_journal_entries.py
opengever/bundle/tests/assets/basic.oggbundle/documents.json
opengever/bundle/tests/assets/basic.oggbundle/dossiers.json
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/bundle/tests/test_section_constructor.py
opengever/bundle/transmogrifier.zcml
opengever/journal/__init__.py
opengever/journal/handlers.py
opengever/journal/interfaces.py

The original goal of the story was to be able to define the creator of journal entries during a bundle import. We decided to extend this, so that the creator can also be set. It would be confusing if the listing under creator would say something different than in the journal.
For [CA-4039]
[CA-4039]: https://4teamwork.atlassian.net/browse/CA-4039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add possibility to bundle import to set obj creator and actor for journal entries 

---

changes/CA-4132.feature
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20220624115904_enable_zip_export_for_workspace_and_workspacefolders/registry.xml
opengever/core/upgrades/20220624115904_enable_zip_export_for_workspace_and_workspacefolders/upgrade.py
opengever/workspace/actions.py
opengever/workspace/configure.zcml
opengever/workspace/tests/test_actions.py
opengever/workspace/tests/test_zipexport.py

workspace-meetings, todos and todolists are excluded from the zip.
For [CA-4132]
-  only profile change
[CA-4132]: https://4teamwork.atlassian.net/browse/CA-4132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enabled zipexport for workspaces and workspacefolders.

---

changes/CA-4301.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/journal.rst
opengever/api/journal.py
opengever/api/tests/test_journal.py
opengever/journal/entry.py

This PR extends the `@journal` to make it searchable and filterable.
For [CA-4301]
- API change:
- If breaking:
- Bug fixed:
[CA-4301]: https://4teamwork.atlassian.net/browse/CA-4301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

The @journal endpoint can now be filtered and searched.

---

changes/CA-4382.other
opengever/dossier/reactivate.py

`get_subdossiers` is recursive by default, returning all subdossier at any depth. So as we recursively execute `_recursive_reactivate`, we want to limit the subdossiers in the loop to `depth=1`.
I've tested locally for a pretty deep dossier structure containing a total of 176 dossiers and a 8 levels of subdossiers. In that case, most of the time was spent getting the subdossiers and iterating over them (see flamegraph), and reactivation took 363 seconds. When limiting depth to 1, it took 39 seconds, and without sorting it took 38 seconds. 
Of course improvement largely depends on the nesting depth, but can probably be even more drastic in some real cases. Indeed I started looking into this because I could not understand why the customer could not reopen the dossier (see jira story) …

Drastically improve performance of reactivation for highly nested dossiers.

---

changes/CA-4364.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/kub.py
opengever/api/tests/test_kub.py
opengever/core/upgrades/20220704143500_add_additional_ui_attributes_setting/registry.xml
opengever/core/upgrades/20220704143500_add_additional_ui_attributes_setting/upgrade.py
opengever/kub/interfaces.py

This is necessary to display customer-specific additional attributes in the kub info card in the UI.
For [CA-4363]
- API change:
[CA-4363]: https://4teamwork.atlassian.net/browse/CA-4363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CA-4363 Add additional_ui_attributes to registry

---

solr-conf/managed-schema

Because stemming is not applied to wildcard queries, they do not work as expected. E.g. the term "Verträge" is indexed as "vertrag" because of normalization and stemming. Searching for "verträge*" will not match, because no stemming is applied to a wildcard query. To work around this, we also index the unstemmed token. Further queries matching the exact term should get a better score.
For [CA-4241](https://4teamwork.atlassian.net/browse/CA-4241)

Preserve original token when stemming

---

changes/CA-4363.other
opengever/kub/client.py
opengever/kub/tests/test_kub_client.py

Otherwise, the KuB attributes are not translated in the correct language.
For [CA-4363]
[CA-4363]: https://4teamwork.atlassian.net/browse/CA-4363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set Accept-Language header when requesting KuB

---

changes/CA-4298-2.other
changes/CA-4298-3.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/journal.rst
opengever/api/journal.py
opengever/api/tests/test_journal.py

This PR refactors hand harmonizes the `@journal` endpoint:
- We now use the `IFieldDeserializer` for every `IManualJournalEntry`-field, not only for the documents. This allows us to send the `category` as it comes from the `vocabulary`: `{ "token": "information" }`.
- The `POST` method expects a `comment` attribute, but the `GET` returns a `comments` attribute for each journal entry. The naming is now harmonized and will always be `comment`.
For [CA-4298]
- API change:
- If breaking:
- Bug fixed: …

Journal api refactoring

---

changes/CA-4151.other
opengever/core/upgrades/20220707162158_enable_all_languages_for_teamraum/portal_languages.xml
opengever/core/upgrades/20220707162158_enable_all_languages_for_teamraum/upgrade.py
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/portal_languages.xml

We update the policy templates to enable all languages by default for Teamraum policies.
There is also an upgrade step to enable the languages for all Teamraum deployments. We try to maintain the default language.
For [CA-4151]
[CA-4151]: https://4teamwork.atlassian.net/browse/CA-4151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable all languages by default for Teamraum policies.

---

changes/CA-4298-3.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/journal.rst
opengever/api/journal.py
opengever/api/tests/test_journal.py

Add `category` attribute for serialized @journal entry items.
This information is required to properly display the currently selected category if we want to display an edit form in the frontend.
For [CA-4298]
- API change:
- If breaking:
- Bug fixed:
[CA-4298]: https://4teamwork.atlassian.net/browse/CA-4298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `category` attribute for serialized @journal entry items

---

opengever/document/activities.py
opengever/document/checkout/manager.py
opengever/document/events.py
opengever/document/handlers.py
opengever/document/interfaces.py
opengever/journal/tests/test_integration.py

The comment is already stored on the corresponding event (`ObjectCheckedInEvent`), so we can avoid retrieving the latest version of the document in the activity by simply getting the comment from the event. This is more efficient and fixes issues with testing, as retrieving a version makes a transaction savepoint which is not supported by the testserver.
So to be clear, this fixes the failing gever-ui tests...
For [CA-4235]
[CA-4235]: https://4teamwork.atlassian.net/browse/CA-4235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Retrieve comment from event for DocumenVersionCreatedActivity.

---

changes/CA-4449.bugfix
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py

Since these groups cannot be authorised in GEVER anyway, we do not need to synchronise them.
For [CA-4449]
[CA-4449]: https://4teamwork.atlassian.net/browse/CA-4449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

No longer sync groups with names containing non-ascii characters into the OGDS

---

changes/CA-1039-1.other
changes/CA-1039-2.other
opengever/api/group.py
opengever/api/serializer.py
opengever/api/tests/test_group.py

The previous implementation performed terribly with a large amount of group members (e.g. 10'000 members).
We now avoid fetching the user object for each group member which greatly improves the performance.
Further we also allow to recreate deleted local groups.
For [CA-1039](https://4teamwork.atlassian.net/browse/CA-1039)

Optimize groups API

---

changes/CA-4240.other
opengever/bundle/sections/resolveguid.py

If the site already contains a large amount of items the resolve GUID section can take several hours. By using sets for containment checks, this is reduced to a few seconds.
For [CA-4240](https://4teamwork.atlassian.net/browse/CA-4240)

Optimize resolve GUID section in bundle import

---

changes/CA-3978.bugfix
opengever/api/tests/test_dossier_participations.py
opengever/api/tests/test_listing.py
opengever/contact/tests/test_participation.py
opengever/dossier/tests/test_indexer.py
opengever/dossier/tests/test_participation.py
opengever/kub/client.py
opengever/kub/sources.py
opengever/kub/testing.py
opengever/kub/tests/test_kub_contact_source.py
opengever/latex/tests/test_dossierdetails.py

With the current implementation, we had some serious performance issues, when accessing a large dossier listing with thousands of KuB-participations. Because the participation facet has led to thousands of separate kub-reqest (one separate request for each participations).
We solve the issue by using a separated, newly introduced KuB endpoint called `labels` (needs https://github.com/4teamwork/kub/pull/130), which returns the label for all contacts (people, organization and memberships) and create a mapping of those. This mapping will be cached for one hour.
For [CA-3978]
Needs  backport to LTS `2022.4` and `2022.11`
[CA-3978]: https://4teamwork.atlassian.net/browse/CA-3978?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

Improve perfomance in KuB contact source.

---

changes/CA-4413.bugfix
opengever/latex/listing.py
opengever/latex/tests/test_listing.py

Before:
After:
For [CA-4413]
[CA-4413]: https://4teamwork.atlassian.net/browse/CA-4413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix column width in latex subdossier listings.

---

changes/CA-3514.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/linked_workspaces.rst
opengever/api/linked_workspaces.py
opengever/api/tests/test_linked_workspaces.py
opengever/workspace/__init__.py
opengever/workspaceclient/client.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/locales/de/LC_MESSAGES/opengever.workspaceclient.po
opengever/workspaceclient/locales/en/LC_MESSAGES/opengever.workspaceclient.po
opengever/workspaceclient/locales/fr/LC_MESSAGES/opengever.workspaceclient.po
opengever/workspaceclient/locales/opengever.workspaceclient.pot

One can now unlink a workspace and deactivate it at the same time.
For [CA-3514]
- API change:
[CA-3514]: https://4teamwork.atlassian.net/browse/CA-3514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add parameter to deactivate the workspace in the @unlink-workspace endpoint

---

changes/CA-4489.bugfix
opengever/kub/docprops.py
opengever/kub/tests/test_docprops.py

KuB distinguishes between Swiss zip code and foreign zip code. Therefore the DocPropertyProvider must be able to handle both.
For [CA-4489]
[CA-4489]: https://4teamwork.atlassian.net/browse/CA-4489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support foreign zip codes in document properties

---

changes/CA-4429.feature
docs/public-fr/admin-manual/proprietedocs/list.rst
docs/public/admin-manual/docproperties/list.rst
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/templatefolder.rst
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py
opengever/document/docprops.py
opengever/dossier/command.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/templatefolder/configure.zcml
opengever/dossier/templatefolder/form.py
opengever/dossier/tests/test_templatefolder.py

With this PR we add support for defining a sender when creating a document from a template. This will add the corresponding docproperties to the created document. We of course also add support for defining a sender in the API.
For [CA-4429]
- API change:
[CA-4429]: https://4teamwork.atlassian.net/browse/CA-4429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sender docproperties when creating document from template.

---

changes/CA-3644.other
opengever/api/recently_touched.py
opengever/api/tests/test_recently_touched.py

This switches the implementation of the `@recently-touched` endpoint to Solr instead of ZCatalog, in order to optimize performance.
The API remains unchanged.
For [CA-3644](https://4teamwork.atlassian.net/browse/CA-3644)

Switch `@recently-touched` endpoint to Solr.

---

changes/CA-4537.bugfix
opengever/base/solr/fields.py
opengever/document/tests/test_reporter.py

Currently it is not possible to assign multiple propertysheets to one slot, therefore we need to duplicate the field configuration in some cases. This has led to errors in the Excel report.
The current assertion can be ignored, if multiple fields are defined with the same name but are equal.
For [CA-4537]
[CA-4537]: https://4teamwork.atlassian.net/browse/CA-4537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix excel export if multiple custom fields with same name exits.

---

opengever/workspace/tests/test_meeting_minutes.py

Fixes [this test failure](https://ci.4teamwork.ch/builds/516472/tasks/984579) that appeared after the `4teamwork/weasyprint` docker image was updated.
```
Failure in test test_meeting_minutes_pdf_view_returns_a_pdf (opengever.workspace.tests.test_meeting_minutes.TestMeetingMinutes)
File "/usr/local/python/2.7.16/lib/python2.7/unittest/case.py", line 329, in run
testMethod()
File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.30.1-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
return func(self, *args, **kwargs)
File "/var/lib/jenkins/workspace/opengever.core-weight-6/opengever/workspace/tests/test_meeting_minutes.py", line 18, in test_meeting_minutes_pdf_view_returns_a_pdf
self.assertEqual(browser.contents[:8], '%PDF-1.5')
File …
```

Fix meeting minutes test after WeasyPrint image was updated to 56.1.

---

base-testserver.cfg

Removing rubygems from testserver will require running the GEVER shared docker services on the Jenkins nodes. For now, we therefore just re-add the rubygems to the testserver buildout in order to not break the testserver and local development buildout.
⚠️ Tests for this will fail until #7537 is merged
For [CA-485](https://4teamwork.atlassian.net/browse/CA-485)

Temporarily re-add rubygems to testserver buildout:

---

development.cfg

With the recent changes to buildout for the removal of the ruby-gems it appears that the buildout bug that drops parts (beyond a certain level of extends) has struck again and drops the 'development-parts' and others.
We therefore explicitly add them to `parts` in the dev buildout.
⚠️ There might still be some more parts that are dropped, I might add those in a later PR. These are the most important ones for now, in order to fix the local development buildout.
For [CA-485](https://4teamwork.atlassian.net/browse/CA-485)

Explicitly add some parts in dev buildout:

---

changes/CA-485.other
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob

Policytemplate: Always configure ALL shared service URLs:
For SaaS-Servers, we've decided that all GEVER shared services (Sablon, PDFLatex, MSGConvert and WeasyPrint) will *always* be deployed on all servers (teamraum-servers as well as GEVER-servers).
Therefore we simplify the buildouts by always configuring all service URLs, irrespective of whether they're actually needed or not.
In addition, we remove the `parts -= gems` hack from the policytemplate, since it's not necessary anymore.
For [CA-485](https://4teamwork.atlassian.net/browse/CA-485)

Policytemplate: Always configure ALL shared service URLs in SaaS buildouts

---

development.cfg

Add `chamelon-cache` to parts in order to fix dev-buildout. This is another part that got dropped by the buildout bug (follow up to #7539).
For [CA-485](https://4teamwork.atlassian.net/browse/CA-485)

Add chamelon-cache to parts in order to fix dev-buildout.

---

base-testserver.cfg
setup.py

This is a "fun" one.
The `bin/testserver` script was generated **twice** during buildout.
One was incomplete and broken, but until now got overwritten with the second, correct one. But the recent changes to the development buildout somehow changed the order in which these parts get built, and now the correct one gets 
overwritten by the broken one.
The correct script is produced by the [testserver] section in base-testserver.cfg. It contains the necessary additional egg `plone.app.robotframework`, as well as required initialization code.
The incorrect script was generated as part of the regular [instance] section, because it has a `testserver` console_scripts entry point. However, that entry point doesn't define either the additional dependency or the required init code. That entry point …

Fix testserver console_script generation

---

changes/CA-4530.other
opengever/api/deserializer.py
opengever/api/tests/test_deserializer.py
opengever/propertysheets/creation_defaults.py
opengever/propertysheets/tests/test_document_custom_properties.py
opengever/propertysheets/utils.py

With this PR we fix an issue where custom properties defaults were saved on objects even if that object did not have the corresponding slot as active (i.e. is not of the corresponding document or dossier type). As these properties are not displayed, it is "unimportant", but it's unnecessary and makes things unnecessarily difficult when we want to modify a given propertysheet, as its default values are stored everywhere...
For [CA-4530]
[CA-4530]: https://4teamwork.atlassian.net/browse/CA-4530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Only save custom properties defaults of active and default slots.

---

opengever/api/recently_touched.py
opengever/api/tests/test_recently_touched.py

The switch of `@recently-touched` to solr has led to errors being thrown in solr when the the user does not have any recently touched item. While the endpoint correctly returns an empty list, as `ftw.solr` swallows all solr errors, it leads to a lot of junk in the output of e2e tests (e.g. search for "Solr response error. " in https://ci.4teamwork.ch/builds/518375/tasks/989597).
Note that the tests also pass without the current change to the endpoint (as I said, solr errors are swallowed in `ftw.solr`), but I think it's still a good idea to test the endpoint for empty recently touched list.
For [CA-3644]
[CA-3644]: https://4teamwork.atlassian.net/browse/CA-3644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle empty recently touched log in @recently-touched endpoint.

---

changes/CA-4529.other
opengever/api/tests/test_participation.py
opengever/workspace/participation/__init__.py
opengever/workspace/participation/browser/manage_participants.py
opengever/workspace/tests/test_workspace_manage_participants.py

Since it checks if the user has the permission "Sharing page: Delegate WorkspaceAdmin role", it is only possible for administrators to modify/delete their own participations.
For [CA-4529]
[CA-4529]: https://4teamwork.atlassian.net/browse/CA-4529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow admins and workspace admins to modify and delete their own workspace participations

---

changes/CA-3912.other
opengever/meeting/proposal.py

For the migration of Meetings to RIS, we copy or move all documents from the meetings into the meeting dossier (see https://github.com/4teamwork/opengever.maintenance/pull/336). This leads to failure to display proposals, and is fixed here. We simply check for deactivated meetings feature as this is a clear sign of having migrated the meetings to RIS.
For [CA-3912]
[CA-3912]: https://4teamwork.atlassian.net/browse/CA-3912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Proposal handles proposal document moved to dossier.

---

changes/CA-4605.bugfix
opengever/api/tests/test_deserializer.py
opengever/propertysheets/helpers.py

This PR fixes an issue where it is not possible to change a custom property value if the previous value contained an umlaut.
Example dossier: https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-2258
https://user-images.githubusercontent.com/557005/186158574-89d8380f-9e10-439e-b81b-b815b9f9691e.mov
For [CA-4605]
- Bug fixed:
[CA-4605]: https://4teamwork.atlassian.net/browse/CA-4605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix updating a custom property value when the previous value contained an umlaut

---

changes/CA-3276.bugfix
opengever/disposition/nightly_jobs.py
opengever/disposition/tests/test_nightly_jobs.py

Nightly jobs have not run on dev.onegovgever.ch/fd (see https://dev.onegovgever.ch/fd/@@health-check?extended=1) in the last month because of nightly jobs referencing deleted objects. We fix it here for the dossier journal PDF nightly jobs.
Sentry: 
- https://sentry.4teamwork.ch/organizations/sentry/issues/88595
- https://sentry.4teamwork.ch/organizations/sentry/issues/88464
- https://sentry.4teamwork.ch/organizations/sentry/issues/88465 (maybe)
For [CA-3276]
- Bug fixed:
[CA-3276]: https://4teamwork.atlassian.net/browse/CA-3276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle deleted dossiers in NightlyDossierJournalPDF.

---

changes/CA-3912.other
opengever/meeting/handlers.py
opengever/meeting/interfaces.py

Handle meeting dossiers containing proposals during meeting migration. For this we need to allow moving the proposals, as we replace the meeting dossier with a normal dossier, effectively moving the proposal.
I did not add a test, as this is not used in Gever, only in the migration of the meetings.
For [CA-3912]
[CA-3912]: https://4teamwork.atlassian.net/browse/CA-3912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow moving proposals outside main dossier during meeting migration.

---

changes/CA-3912.other
opengever/base/tests/test_navigation.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/committeecontainer.py
opengever/meeting/model/meeting.py
opengever/meeting/reopen.py
opengever/meeting/tests/test_committee.py
opengever/meeting/tests/test_meeting.py
opengever/meeting/tests/test_meeting_reopen.py
opengever/meeting/utils.py

It was never really planed that the meeting feature would get deactivated, so things are not ideal when there is a committecontainer and meetings with the feature deactivated. We make a few changes here to better handle that situation:
- Disallow reopening meetings when the meeting feature is disabled
- Hide the committeecontainer from the navigation when the feature is disabled.
For [CA-3912]
[CA-3912]: https://4teamwork.atlassian.net/browse/CA-3912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for deactivating the meeting feature

---

changes/CA-4594.other
docs/public/dev-manual/api/journal.rst
opengever/api/tests/test_journal.py
opengever/api/tests/test_journal_manager.py
opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/en/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/journal/tests/test_manual_entry.py

"Manual entry" is removed from the title. We need to keep the translation, otherwise older journal entries would be missing the translation.
For [CA-4594]
[CA-4594]: https://4teamwork.atlassian.net/browse/CA-4594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust journal entry title of manual entries

---

base-testserver.cfg
changes/CA-4595.other
opengever/base/tests/test_configuration_adapter.py
opengever/testing/fixtures.py

This PR is properly configuring the test environment to make it possible to write workspace client related e2e tests.
We do not really setup a teamraum-env. We just add the necessary roles and configuration to simulate the existence of a teamraum deployment. This allows us to use forms and actions in the ui which are related to the workspace-client feature.
We'll not do real requests to the `TEAMRAUM_URL` but we need to configure it that the backend "thinks" we've configured a teamraum. In e2e-tests, we'll mock the requests to the teamraum-backend.
For [CA-4595]
- API change:
- If breaking:
- Bug fixed:
- …

Setup test environment for workspace client e2e tests

---

changes/CA-4595.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/linked_workspaces.rst
opengever/api/configure.zcml
opengever/api/linked_workspaces.py
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/tests/test_linked_workspaces.py
opengever/workspaceclient/linked_workspaces.py

This PR adds a new endpoint `@linked-workspace-invitations` which allows to invite users to a linked workspace from GEVER.
This allows us to directly invite users on workspace creation within GEVER.
For [CA-4595]
- API change:
[CA-4595]: https://4teamwork.atlassian.net/browse/CA-4595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement new endopint @linked-workspace-invitations to invite users from gever to a workspace

---

opengever/api/tests/test_tus.py

Defer TUS lock test by another month.
We probably can enable the behavior now, but until we have time to properly check this, we just defer the test by another month for now.

Defer TUS lock test by another month.

---

changes/CA-4675.feature
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/participation/invitation_mailer.py
opengever/workspace/participation/templates/invitation_mail.pt

This PR updates the workspace invitation email template by adding anchor-tags for links.
This will fix an issue in some mail clients where the urls are not automatically recognized as links. In addition, we're able to add a label to the links which makes it much more user friendly.
⚠️ in some mail clients, i.e. office365 online, the links are not even rendered as links. This is a functionality of the mail clients that they'll be clickable.
For [CA-4675]
- API change:
- If breaking:
- Bug fixed:
[CA-4675]: …

Use a-tags for the workspace invitation email template to properly render links in mail-clients

---

changes/CA-4678.bugfix
changes/CA-4678.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dossier_participations.rst
opengever/api/dossier_participations.py
opengever/api/tests/test_dossier_participations.py
opengever/ogds/base/actor.py
opengever/ogds/base/tests/test_actor.py

Participants are now sorted by `participant_title` in the `@participations` endpoint.
During the implementation I noticed that the endpoint with KuB participations is extremely slow. Therefore I optimized the KuBActor so that KuB is only requested when necessary.
A request of the endpoint with 5 KuB participations took more than 1.5 seconds. Now the request is about a factor of 45 faster.
For [CA-4678]
- API change:
[CA-4678]: https://4teamwork.atlassian.net/browse/CA-4678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Sort dossier participations by label in @participations endpoint

---

changes/CA-4684.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/configure.zcml
opengever/api/serializer.py
opengever/api/tests/test_serializer.py

Currently, in the new frontend, the folder id is displayed as the heading in the private folder. This is a little bit unpleasant, because the id was normalized. It would be better to display the label of the user.
For [CA-4684]
- API change:
[CA-4684]: https://4teamwork.atlassian.net/browse/CA-4684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include title in private folder serialization

---

changes/CA-4701.bugfix
opengever/locking/tests/test_force_unlock.py
opengever/officeconnector/helpers.py
opengever/officeconnector/testing.py
opengever/officeconnector/tests/test_api_dossier_attach.py
opengever/officeconnector/tests/test_api_dossier_checkout.py
opengever/officeconnector/tests/test_api_dossier_disabled.py
opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
opengever/officeconnector/tests/test_api_forwarding_attach.py
opengever/officeconnector/tests/test_api_forwarding_checkout.py
opengever/officeconnector/tests/test_api_forwarding_disabled.py
opengever/officeconnector/tests/test_api_mail_attach.py
opengever/officeconnector/tests/test_api_task_checkout.py
opengever/officeconnector/tests/test_zopemaster.py

For external users the previous implementation did not work, because the documents were fetched with `api.content.get`. `api.content.get` does a `restrictedTraverse` in the background, this did not work for external users, because they sometimes had access only to one repo folder.
Since only the document UIDs are needed anyway, I switched the query to Solr.
For [CA-4701]
[CA-4701]: https://4teamwork.atlassian.net/browse/CA-4701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use solr to parse documente uids for office connector url

---

changes/CA-4710.bugfix
opengever/base/transport.py
opengever/task/tests/test_transporter.py

Each client has its own preserved_as_paper default, therefore it shouldn't be copied to the other client
For [CA-4710]
Maybe need backport to version currently used by opengever.zug.
[CA-4710]: https://4teamwork.atlassian.net/browse/CA-4710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use client own preserved_as_paper default when transporting documents.

---

changes/CA-4721.bugfix
opengever/core/upgrades/20220917130346_remove_inactive_group_memberships/upgrade.py
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py

So far, the group memberships have not been removed. This resulted in groups being displayed for users that no longer existed.
For [CA-4721]
[CA-4721]: https://4teamwork.atlassian.net/browse/CA-4721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove group memberships in ogds sync when ldap group is deactivated

---

README.rst
changes/CA-4543.feature
opengever/core/testing.py
opengever/core/upgrades/20220914101403_add_case_insensitive_sql_indexes_for_user_and_group_i_ds/upgrade.py
opengever/core/upgrades/20220914151051_add_case_insensitive_sql_index_for_groups_users_userid/upgrade.py
opengever/ogds/auth/__init__.py
opengever/ogds/auth/configure.zcml
opengever/ogds/auth/plugin.py
opengever/ogds/auth/testing.py
opengever/ogds/auth/tests/test_plugin.py
opengever/ogds/auth/www/addPlugin.zpt
opengever/ogds/auth/www/config.zpt
opengever/ogds/models/group.py
opengever/ogds/models/user.py

This adds an implementation for an OGDS PAS plugin that aims to eventually replace the functionally we currently use from the LDAP/AD plugins of `P.LDAPMultiPlugins`.
It implements the following interfaces:
- `IUserEnumerationPlugin`
- `IGroupEnumerationPlugin`
- `IGroupsPlugin`
- `IPropertiesPlugin`
Results are cached, and SQL queries on hot paths (like `enumerateUsers('current.user')`) are backed by SQL indexes on the appropriate columns.
All lookups that this plugin does (by user ID or group ID) are case-insensitive.
**Notes:**
- `IGroupIntrospection` is not supported yet. In user-facing usage, I coulnd't find a case where this is needed. The groups tab in the "Groups and Users" Plone control panel seems to need it however, so that's currently broken when this Plugin is installed. I …

Implement OGDS auth plugin

---

changes/CA-4679.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/dossier_participations.py
opengever/api/tests/test_dossier_participations.py

Because a participant can only have one participation on an object, participants that already have a participation on a dossier should not get returned by the `@possible-participations` endpoint.
For [CA-4679]
[CA-4679]: https://4teamwork.atlassian.net/browse/CA-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Filter out current participants in @possible-participations.

---

changes/CA-4662.other
opengever/api/tests/test_move.py
opengever/dossier/base.py
opengever/dossier/tests/test_base.py
opengever/dossier/tests/test_move_items.py

Don't enforce max dossier depth if a structure of same nesting level as the new one already exists.
For example: If a dossier already contains a subdossier with a sub-sub-dossier that already exceeds the max depth by 2, then it will be allowed to create more content on that level that exceeds the depth by up to 2 levels (but not more).
**Note:**
I tried to switch `Dossier.get_subdossiers()` to Solr instead of ZCatalog queries, because it is now (often) used when viewing a dossier, and having to determine whether to show subdossiers as addable or not.
However, I had to abort that attempt because `get_subdossiers()` is used in so many places, that ~80 tests failed, and among those 13 `Functional` test cases, which would not easily be converted to `SolrIntegrationTestCases` in the scope of …

Make max dossier depth restriction less strict

---

changes/CA-4734-2.other
changes/CA-4734.other
docs/schema-dumps/_opengever.ogds.models.user.User.schema.json
opengever/api/tests/test_ogdsuser.py
opengever/bundle/schemas/ogds_users.schema.json
opengever/core/upgrades/20220926163919_add_users_object_sid_sql_column/upgrade.py
opengever/ogds/auth/plugin.py
opengever/ogds/auth/tests/test_plugin.py
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/sync/sid2str.py
opengever/ogds/base/tests/test_ogds_updater.py
opengever/ogds/base/tests/test_sid2str.py
opengever/ogds/models/user.py

Once the OGDS auth plugin is used and the  ActiveDirectoryMultiPlugin is removed, we need to keep the `objectSid` in OGDS for the OneOffixx integration to still work and expose it in the member properties via the OGDS auth plugin.
For [CA-4734](https://4teamwork.atlassian.net/browse/CA-4734)

Add object_sid column to OGDS users

---

changes/CA-4734-3.other
changes/CA-4734-4.other
changes/CA-4734-5.bugfix
docs/schema-dumps/_opengever.ogds.models.user.User.schema.json
opengever/api/tests/test_ogdsuser.py
opengever/bundle/schemas/ogds_users.schema.json
opengever/core/upgrades/20220927162859_add_users_display_name_sql_column/upgrade.py
opengever/ogds/auth/plugin.py
opengever/ogds/auth/tests/test_plugin.py
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py
opengever/ogds/models/user.py

The LDAP/AD attributes `displayName` or `cn` are sometimes mapped to the `fullname` property. This is especially the case for customers that actively manage the display names of their users, e.g. to also contain the user's department or their role.
If it exists, we store it in OGDS in the `display_name` column. This is therefore a customer-controlled display name, and different from the fullname we build in the `User.fullname()` method by concatenating first and last name.
With that display ending up in the `fullname` property, Plone will use it e.g. when searching for users in the sharing tab, or to display it in the personal tools menu.
Also contains a bugfix for accessing SQLAlchemy RowProxy results.
For [CA-4734](https://4teamwork.atlassian.net/browse/CA-4734)
- …

Add `display_name` column to OGDS user model

---

changes/CA-4666.feature
opengever/activity/notification_settings.py
opengever/task/browser/transitioncontroller.py
opengever/task/tests/test_transitioncontroller.py

The transition already existed but only for task templates. The transition is not available for cross-client tasks that are processed in  in a dossier on the responsible tenant.
For [CA-4666]
[CA-4666]: https://4teamwork.atlassian.net/browse/CA-4666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow cancellation of tasks in progress

---

changes/CA-4734-6.other
docs/schema-dumps/_opengever.ogds.models.user.User.schema.json
opengever/api/tests/test_ogdsuser.py
opengever/bundle/schemas/ogds_users.schema.json
opengever/core/upgrades/20220928114307_add_users_organization_sql_column/upgrade.py
opengever/ogds/models/user.py

This column is intended to track a user's organization in a simpler way than the existing directorate and department columns.
In order to be populated, it will need to be mapped in the LDAP schema to an AD/LDAP attribute first, with a public_name of 'organization'. Then it will be synced to OGDS.
For [CA-4734](https://4teamwork.atlassian.net/browse/CA-4734)

Add `organization` column to OGDS user model:

---

changes/CA-4774.bugfix
opengever/dossier/base.py
opengever/dossier/tests/test_dossier_helpers.py

When determining the end date for dossiers, the time zone was not taken into account. If a document was last modified on 10.10.22 at 00:15, therefore then the date 09.10. came out, because the modified datetime is stored as utc, and from this the date was generated. Now, when converting the datetime to a date, the local time zone is respected.
For [CA-4774]
[CA-4774]: https://4teamwork.atlassian.net/browse/CA-4774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Consider time zone when determining the end date of a dossier

---

changes/CA-4703.feature
opengever/base/docprops.py
opengever/base/tests/test_base_docprops_provider.py
opengever/kub/docprops.py
opengever/kub/testing.py
opengever/kub/tests/test_docprops.py

Include KuB organization phone number in membership docproperties:
When serializing a KuB membership to DocProperties, this will also include the organization's phone number in `ogg.[scope].organization.phone.number` (where [scope] may currently be `sender` or `recipient`).
A side effect of this is that when serializing an `organization` entity, its phone number is now exposed twice in DocProperties: Once in `ogg.[scope].organization.phone.number` and once in `ogg.[scope.]phone.number`.
This is because the phone number is once included by the `KuBPhoneNumberDocPropertyProvider` at the upper, generic level (that exposes common properties in an entity type agnostic way), and once more by the `KuBOrganizationDocPropertyProvider` under `ogg.[scope].organization.phone.number`, to be able to …

 Include KuB organization phone number in membership docproperties.

---

changes/CA-4663.other
opengever/activity/__init__.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/en/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot

It seems that when we modified the activity settings we stopped using the `ACTIVITY_TRANSLATIONS` in the `NotificationSettingsView` (see https://github.com/4teamwork/opengever.core/pull/6397), but did not remove the translations that were not used anymore.
For [CA-4663]
[CA-4663]: https://4teamwork.atlassian.net/browse/CA-4663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clean-up activity translations.

---

changes/CA-4802.other
opengever/kub/client.py
opengever/kub/tests/test_kub_client.py

With the `If-Modified-Since` header the labels are only returned if something has changed since the given date, otherwise a response with status code 304 is returned.
Since, if there have been no changes, the request is very fast, we therefore no longer have to cache the labels for an hour. Since with some requests (`@actors`endpoint) the label mapping is queried several times, I still cache the mapping for 5 seconds so that KuB is requested only once.
For [CA-4802]
[CA-4802]: https://4teamwork.atlassian.net/browse/CA-4802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

No longer cache kub label mapping for an hour, use If-Modified-Since header instead

---

changes/CA-4772.bugfix
opengever/document/events.py
opengever/journal/handlers.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_linked_workspaces.py

When copying documents as a new version from the workspace, no events were fired. Therefore, among other things, the "changed" field was not updated
For [CA-4772]
[CA-4772]: https://4teamwork.atlassian.net/browse/CA-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update changed field and mark document as recently touched when copying documents as new version from workspace

---

changes/CA-4897.other
opengever/workspace/participation/templates/invitation_mail.pt

In some email clients, e.g. office365 online, the links are not displayed as links if the a tag is not used. Therefore, it must be possible to use the a tag in custom_invitation_mail_content.
For [CA-4897]
[CA-4897]: https://4teamwork.atlassian.net/browse/CA-4897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

No longer escape custom_invitation_mail_content in teamraum invitation mail

---

changes/CA-3220.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
opengever/api/config.py
opengever/api/tests/test_config.py

This PR extends the `@config` endpoint with the `template_folder_url` property.
We need this property to exclude template folder contents from the search.
For [CA-3220]
- API change:
- If breaking:
- Bug fixed:
[CA-3220]: https://4teamwork.atlassian.net/browse/CA-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add template_folder_url to the @config endpoint

---

changes/CA-3220-2.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/searching.rst
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py

This PR extends the `@solrsearch` endpoint with the possiblity to exclude path-parents by url.
We need this to exclude the template folder area from search queries in the frontend.
For [CA-3220]
- API change:
- If breaking:
- Bug fixed:
[CA-3220]: https://4teamwork.atlassian.net/browse/CA-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow to exclude paths by url in solrsearch

---

bin/mtest
changes/CA-4726-1.other
changes/CA-4726.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/linked_workspaces.rst
opengever/api/configure.zcml
opengever/api/linked_workspaces.py
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/tests/test_linked_workspaces.py
opengever/api/workspace.py
opengever/base/listing_actions.py
opengever/core/testing.py
opengever/dossier/actions.py
opengever/dossier/configure.zcml
opengever/dossier/tests/test_actions.py
opengever/testing/test_case.py
opengever/workspaceclient/client.py
opengever/workspaceclient/exceptions.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/__init__.py
test-functional-solr.cfg
test-functional-zserver-solr.cfg
test-solr.cfg

This adds backend support for copying (sub)dossiers to teamraum by:
- adding a new `@prepare-copy-dossier-to-workspace` endpoint that will create the respective folder structure on the teamraum side
- allowing the `@copy-document-to-workspace` endpoint to also take teamraum folders as targets
The frontend will then call the `@prepare-copy-dossier-to-workspace` first (with `validate_only=True`) to validate preconditions (main dossier linked to workspace, no checked out documents), and display any errors to the user. It will then call it a second time to have it create an empty folder structure on the teamraum that mirrors the subdossier structure. The endpoint will then return a list of all documents that need to be copied by the frontend, and the teamraum folders they should be copied to. …

Add backend support to copy subdossiers to teamraum

---

changes/CA-4943.bugfix
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dossier_participations.rst
opengever/api/dossier_participations.py
opengever/api/tests/test_dossier_participations.py

This PR extends the `available_roles` items of the `@participations` endpoint with an `active` flag for each available role.
The flag will be set to `false` if the registry entry: `opengever.dossier.interfaces.IDossierParticipants.roles` is used and the given role is not listed in the list of roles.
This flag is required for the ui to know if a specific role is selectable or not. Just remove these roles is not possible because we need the inactive items for the `title` lookup for already existing entries.
For [CA-4943]
- API change:
- If breaking:
- Bug fixed:
- Further improvements …

Return an active-flag for available roles in in the `@participations endpoint.

---

changes/CA-3864.other
opengever/document/configure.zcml
opengever/document/document.py
opengever/document/handlers.py
opengever/document/tests/test_handlers.py
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api_dossier_checkout.py
opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
opengever/officeconnector/tests/test_api_task_checkout.py
opengever/officeconnector/tests/test_zopemaster.py

Track if a document has pending changes and include this info in the checkout metadata for Office Connector.
We want to know if a document was modified since the last checkout and if there are changes that haven't been checked in yet. Unfortunately we can not determine this directly as Word documents are always modified on checkout and checkin because of DocProperties updates. Even if this is not the case, it's hard to determine if a document was really modified. We would have to diff the file contents of the current working copy with the last version. Therefore we add a marker when a new document version gets uploaded.
Requires a new Office Connector version (>1.16.0) to get the feature working, but older versions still work as before.
See: …

OfficeConnector cancel checkout

---

changes/CA-4925.bugfix
opengever/api/tests/test_tus.py
opengever/workspace/participation/storage.py

The same problem as in #7552 , but unfortunately it was solved only for incoming mails. See also: https://github.com/4teamwork/opengever.core/pull/7552#issue-1349663726
For the lock check I created an issue: https://4teamwork.atlassian.net/browse/CA-4982
For [CA-4925]
⚠️ Needs backport to 2022.15.x ⚠️
[CA-4925]: https://4teamwork.atlassian.net/browse/CA-4925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix user lookup by email for workspace invitation mail

---

changes/CA-4846.bugfix
opengever/workspace/participation/browser/my_invitations.py
opengever/workspace/tests/test_my_invitations.py

No longer redirect to the login page and redirect to the portal page instead. Because only the portal page, redirects to external authentication service, like secure-connect.
For [CA-4846]
Needs backporting to the SG Prod Release 
[CA-4846]: https://4teamwork.atlassian.net/browse/CA-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix workspace invitations portal redirects.

---

changes/CA-3864-1.bugfix
changes/CA-3864-2.bugfix
opengever/disposition/ech0160/sippackage.py
opengever/disposition/tests/test_sippackage.py

According to comments in the code, this is what's supposed to be used in this field, instead of the current user's name.
This also fixes a unicode error when disposing a disposition on a deployment where the admin unit title contains non-ASCII characters.
For [CA-4889](https://4teamwork.atlassian.net/browse/CA-4889)

Use disposition creator's fullname in eCH0160 'ablieferndeStelle' field

---

changes/CA-4945.bugfix
opengever/task/__init__.py
opengever/task/browser/transitioncontroller.py
opengever/task/task.py
opengever/task/tests/test_task_from_template.py

In a nested task structure that contains a sequential subprocess, it was possible to manually start a subtask inside such a subprocess even though the containing parent task was still in the planned state.
This lead to an invalid task structure, causing the logic that is supposed start the next task when a task is closed to trip up, because it doesn't expect the next task to be already in progress.
Sentry: https://sentry.4teamwork.ch/organizations/sentry/issues/98191/
For [CA-4945](https://4teamwork.atlassian.net/browse/CA-4945)
Bug fixed:

Sequential tasks: Only allow subtasks to be started when parent is in progress

---

changes/CA-4982.other
opengever/api/tests/test_tus.py
opengever/api/tus.py

For [CA-4982]
[CA-4982]: https://4teamwork.atlassian.net/browse/CA-4982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Re-enable forbidding tus-replace when document is locked by another user.

---

changes/CA-4900.feature
opengever/officeconnector/browser/configure.zcml
opengever/officeconnector/browser/oc_checkout_redirect.py
opengever/officeconnector/tests/test_oc_checkout_redirect.py

This view allows 3rd party applications to produce links that should directly trigger a checkout using OfficeConnector on a GEVER document.
In case a necessary precondition is not satisfied (e.g., document is already checked out by someone else), the view just redirects to the regular document view, which should give the user some indication as to why the checkout didn't work.
> **Note**: This registers a browser view with the same same as the [existing `oc_checkout` REST API endpoint](https://github.com/4teamwork/opengever.core/blob/d7ee0559ca3989fba3a55ded972f623acb585adc/opengever/officeconnector/configure.zcml#L70-L77).
> This technically isn't a problem, because one is a REST service and the other a Browser View (`plone.rest` can distingiush those via content negotiation), one is on …

Add `@@oc_checkout` view that redirects to oc: checkout URL

---

opengever/officeconnector/tests/test_oc_checkout_redirect.py

Also perform JWT signature validation during frozen time, otherwise we'll get `ExpiredSignatureError: Signature has expired` after some time.
For [CA-4900](https://4teamwork.atlassian.net/browse/CA-4900)

Fix TestOCCheckoutRedirect tests

---

changes/CA-4834.bugfix
opengever/ogds/base/sync/ogds_updater.py
opengever/ogds/base/tests/test_ogds_updater.py
opengever/ogds/models/user.py

This makes the OGDS synchronisation case inensitive with regard to the user ID.
Therefore, when a user ID changes case in LDAP/AP, it will still be matched to the existing OGDS user (with original capitalization for its user ID) when updating user properties and group memberships.
For [CA-4834](https://4teamwork.atlassian.net/browse/CA-4834)

Make OGDS sync case insensitive

---

changes/CA-5006.bugfix
opengever/core/upgrades/20221125151226_store_task_related_items_in_annotations/upgrade.py
opengever/task/localroles.py
opengever/task/tests/test_localroles.py

Local roles are added on documents that are related to a task. When closing that task, the local roles are revoked on the current list of related items, but if some objects were removed from the list of related items at some point, the local roles on these documents would never get revoked.
For newly added related items, the local roles were correctly updated in an event handler. To revoke the local roles on related items that get removed, we need to find out which objects were removed from the list of related items. This information is not accessible in the event handler, so we had to store the list of related items in the annotations on each task, allowing us to compare it with the `relatedItems` field on the task and revoking the local roles accordingly.
For [CA-5006] …

Revoke roles when objects are removed from a task's related items.

---

opengever/core/locales/de/LC_MESSAGES/plone.po
opengever/core/locales/en/LC_MESSAGES/plone.po
opengever/core/locales/fr/LC_MESSAGES/plone.po
opengever/core/locales/plone.pot

Seems I forgot to add the `TaskResponsible` in the `plone.pot` file. This does not have any impact, except of course when running `i18n-build` for the next time...
For [CA-4395]
[CA-4395]: https://4teamwork.atlassian.net/browse/CA-4395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix TaskResponsible role translation.

---

changes/CA-5038-1.other
changes/CA-5038.other
opengever/core/tests/test_upgrade.py
opengever/core/upgrade.py
opengever/core/upgrades/20220914101403_add_case_insensitive_sql_indexes_for_user_and_group_i_ds/upgrade.py
opengever/core/upgrades/20220914151051_add_case_insensitive_sql_index_for_groups_users_userid/upgrade.py
opengever/core/upgrades/20221013095934_add_index_for_predecessor_id/upgrade.py
opengever/ogds/base/upgrades/to4004.py
opengever/ogds/base/upgrades/to4006.py

This introduces a new helper method `.create_index_if_not_exists()` on the `SchemaMigration` class that will only emit a `CREATE INDEX` statement if the index by that name doesn't exist yet, and makes the (recent) upgrade steps that add new indexes use it.
This makes those upgrade steps idempotent, so that they won't fail if executed a second time.
In addition, I removed the `IdempotentOperations` class and some other special handling for MySQL, which we dropped support for years ago.
For [CA-5038](https://4teamwork.atlassian.net/browse/CA-5038)

Fix upgrade steps that add new indexes

---

opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

Place TaskResponsible role as last. It's the least important role, so it does not have to be that proeminent.
For [CA-4395]
[CA-4395]: https://4teamwork.atlassian.net/browse/CA-4395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify order of roles in sharing tab.

---

changes/CA-5093.bugfix
opengever/api/tests/test_tus.py
opengever/api/tus.py

With https://github.com/4teamwork/opengever.core/commit/51ed9dd4c66f1031525c571c2953a5c41aeba1a3 the lock check was enabled in the @tus-upload endpoint.
But the check does not work properly, so I have to disable it again. I have created a bug to address the problem:
https://4teamwork.atlassian.net/browse/CA-5107
For [CA-5093]
[CA-5093]: https://4teamwork.atlassian.net/browse/CA-5093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disable lock check in @tus-upload endpoint again

---

changes/CA-5090.bugfix
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20221208084514_allow_users_with_document_view_permission_to_revive_bumblebee_preview/rolemap.xml
opengever/core/upgrades/20221208084514_allow_users_with_document_view_permission_to_revive_bumblebee_preview/upgrade.py
opengever/document/actions.py
opengever/document/tests/test_actions.py

Since the permission check was wrong, it was only possible for users with global roles (i.e. administrators) to revive the preview. 
Furthermore, the permission should be available to all roles that have View Permission. A TaskResponsible does not necessarily have to be a Reader.
Only the first commit needs to be backported.
For [CA-5090]
[CA-5090]: https://4teamwork.atlassian.net/browse/CA-5090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix permission check for revive_bumblebee_preview action

---

changes/CA-5045.feature
opengever/document/document.py
opengever/document/tests/test_document_workflow.py
opengever/task/task.py
opengever/task/transition.py

Preventing reopening only makes sense if the task is in an approval process. Otherwise any document referenced by a pending task which gets closed by accident cannot be reopened.
For [CA-5045]
[CA-5045]: https://4teamwork.atlassian.net/browse/CA-5045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Only prevent reopening a document if the referencing task is for approval.

---

base-testserver.cfg
test-testserver-selftest.cfg

This should also fix the issue for local buildouts and gever-ui E2E tests.

Pin selenium in base-testserver.cfg instead of test-testserver-selftest.cfg

---

changes/CA-2605.other
opengever/contact/interfaces.py
opengever/journal/handlers.py

Contact migration will also migrate the dossier participations, i.e. add new participations and delete the old ones, which generates journal entries. To avoid this we add a marker interface that will be provided during contact migration and skip creation of journal entries during migration.
For [CA-2605]
[CA-2605]: https://4teamwork.atlassian.net/browse/CA-2605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid creating journal entries during contact migration.

---

opengever/base/addressblock/addressblock.py
opengever/base/addressblock/tests/test_address_formatting.py

Addressblock formatting: Filter any `None` values or empty strings before joining lines.
This may be needed when certain attributes required for a complete address are missing. This will result in incomplete addresses being produced, but that's still preferable to having the "Create document from template" action fail (or any other context, where that DocProperty is generated).
For [CA-5079](https://4teamwork.atlassian.net/browse/CA-5079)

Addressblock formatting: Filter any None values before joining lines.

---

opengever/debug/patches/modified_out_of_sync.py

When deleting the `ContactFolder` this patch gave rise to an error on `01-dev.onegovgever.ch-fd`
For [CA-2605]
[CA-2605]: https://4teamwork.atlassian.net/browse/CA-2605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix debug patch checking for out of sync modification date.

---

opengever/base/addressblock/docprops.py
opengever/base/addressblock/extraction.py
opengever/base/addressblock/tests/test_extraction.py
opengever/kub/docprops.py
opengever/kub/entity.py
opengever/ogds/base/docprops.py

This fixes address block data extraction for KuB entities without a `primaryAddress`, and also makes the address block docproperties more robust in general. 
For [CA-5079](https://4teamwork.atlassian.net/browse/CA-5079)

Make address block docproperties more robust

---

changes/CA-5037-2.feature
changes/CA-5037.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
docs/public/dev-manual/api/config_checks.rst
docs/public/dev-manual/api/index.rst
opengever/api/config.py
opengever/api/config_checks.py
opengever/api/configure.zcml
opengever/api/tests/test_config.py
opengever/api/tests/test_config_checks.py
opengever/base/browser/errors.py
opengever/base/config_checks/checks.py
opengever/base/config_checks/configure.zcml
opengever/base/config_checks/manager.py
opengever/base/configure.zcml
opengever/base/interfaces.py
opengever/base/tests/test_config_checks.py
opengever/base/tests/test_utils.py
opengever/base/utils.py
opengever/base/viewlets/config_check.pt
opengever/base/viewlets/config_check.py
opengever/base/viewlets/configure.zcml
opengever/core/testserver.py
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/periods.py

Thsi PR implements the `ConfigCheckManager` and integrates the results of the config checks in a config-check viewlet for the old UI and provides the check results over a new api endpoint: `@config-checks`.
The checks are only available for managers.
For [CA-5037]
- API change:
- If breaking:
- Bug fixed:
[CA-5037]: https://4teamwork.atlassian.net/browse/CA-5037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Config checks

---

opengever/base/config_checks/checks.py
opengever/base/config_checks/configure.zcml
opengever/base/tests/test_config_checks.py

This is a follow-up PR for #7651 and changes the "ldap order check" config-check by using the `IProperties` plugin instead the `IAuthentication` plugin.
@tinagerber thanks for your input!
For [CA-5037]
- API change:
- If breaking:
- Bug fixed:
[CA-5037]: https://4teamwork.atlassian.net/browse/CA-5037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use the IPropertiesPlugin for the ldap config check

---

changes/CA-5036.bugfix
opengever/core/upgrades/20230109145141_fix_order_of_i_properties_plugin_pas_plugins/upgrade.py

Add upgrade step that fixes order of IPropertiesPlugin PAS plugins by ensuring the `ldap` plugin is always at the top.
For [CA-5036](https://4teamwork.atlassian.net/browse/CA-5036)
[CA-5036]: https://4teamwork.atlassian.net/browse/CA-5036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add upgrade step that fixes order of IPropertiesPlugin PAS plugins.

---

changes/CA-5103.bugfix
opengever/base/subscribers.py
opengever/base/tests/test_anonymous.py

This disallows access to member portraits via `<portal>/portal_memberdata/portraits/<userid>` for anonymous users.
The `portraits` attribute on `MemberDataTool` instance at `portal_memberdata` is a [direct instance of a BTreeFolder2](https://github.com/plone/Products.PlonePAS/blob/9ec4a950ff47057254a1f206f55f44fb9b7a72fc/src/Products/PlonePAS/tools/memberdata.py#L40) that can be traversed to.
Because of that, it's challenging to add additional permission checks to the `MemberDataTool`, especially because even Anonymous users have the `View` permission on the Plone site root anyway.
Therefore I disallowed access to member portraits on the traversal level, in our already existing `IPubAfterTraversal` hook.
For [CA-5103](https://4teamwork.atlassian.net/browse/CA-5103)
[CA-5103]: …

Disallow anonymous access to member portraits.

---

opengever/base/configure.zcml
opengever/workspace/tests/test_workspace_touched.py

This is a follow-up PR for #7655 
The workspace touched date needs to update if the review-state of todos have been changed.
For [CA-4875]
- API change:
- If breaking:
- Bug fixed:
[CA-4875]: https://4teamwork.atlassian.net/browse/CA-4875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Touch workspace if todo review state changed

---

changes/CA-5239.other
opengever/api/tests/test_scanin.py
opengever/base/subscribers.py

This PR adds the `WWW-Authenticate` response header for unauthorized requests to the `@scan-in` endpoint.
Two notes to the reviewer:
1. The header could be added automatically by the `IChallengePlugin` of the PAS by plone by default. The `HTTPBasicAuthHelper` Plugin would already add the header. But we never reach this code even if the plugin is activated. We do not use the `challenge`-method of the `IChallengePlugins`s at this point .
2. The response object would provide a `addHeader`: `response.addHeader('WWW-Authenticate', 'Basic')`. But this is not compatible with the testbrowser of `ftw.testbrowser` which provides its own `TestResponse` object. I implemented a direct key assignment for the header. Otherwise we'd need to ship a new version of `ftw.testbrowser` to make it compatible in …

Provides a "WWW-Authenticate" response header for unauthorized requests to the @scan-in endpoint.

---

opengever/api/tests/test_tus.py

Tests: Defer failing lock token test once more.

Tests: Defer failing lock token test once more.

---

changes/CA-5103.bugfix
opengever/base/subscribers.py

The previous condition worked locally, but did not work in virtual hosting scenarios where the path contains an additional 'virtual_hosting' step.
Follow-up for [CA-5103](https://4teamwork.atlassian.net/browse/CA-5103)
[CA-5103]: https://4teamwork.atlassian.net/browse/CA-5103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix check to prevent anonymous users from viewing member portraits:

---

opengever/workspace/tests/test_deleter.py

Workspace deleter tests did not have the workspace feature activated when they were written (https://github.com/4teamwork/opengever.core/commit/7cfedb5beceeef8ff66283a6b91438e5f26dac79) so that we were actually testing against the wrong permission. We therefore had to use manager permissions to delete objects, when in fact workspace members are allowed to delete documents. So we switch here to testing with a workspace member.
There is no related issue for this, I just stumbled across this error while working on https://github.com/4teamwork/opengever.core/pull/7668

Improve workspace deleter tests.

---

changes/CA-5228.feature
opengever/core/upgrades/20230209144650_add_resolver_custom_precondition_registry_fields/registry.xml
opengever/core/upgrades/20230209144650_add_resolver_custom_precondition_registry_fields/upgrade.py
opengever/dossier/base.py
opengever/dossier/interfaces.py
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

We introduce 2 registry records allowing to define an additional dossier resolution rule and the related error thrown when the rule is broken. The rule is a TALES expression. In order to make custom properties available in the custom resolve condition, I had to add custom properties as a property on the dossier.
For [CA-5228]
[CA-5228]: https://4teamwork.atlassian.net/browse/CA-5228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow to define a custom dossier resolution precondition.

---

changes/CA-5274.bugfix
opengever/core/upgrades/20230208123453_reindex_mail_reference_numbers/upgrade.py
opengever/document/configure.zcml
opengever/document/handlers.py
opengever/dossier/tests/test_move_items.py

It seems we had only registered an event handler to reindex the reference number of moved documents but not for mails.
For [CA-5274]
[CA-5274]: https://4teamwork.atlassian.net/browse/CA-5274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reindex the reference number of mails during move operations.

---

changes/CA-5312.bugfix
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/tests/test_meeting_minutes.py

Agendaitem in workspace meetings can reference documents, which can be deleted, so that the reference ends up being broken. With this PR we now handle broken references by simply skipping them.
For [CA-5312]
[CA-5312]: https://4teamwork.atlassian.net/browse/CA-5312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle broken references when generating the meeting minutes PDF.

---

changes/CA-5229.feature
opengever/core/upgrades/20230214171647_add_resolver_custom_after_transition_hook_registry_field/registry.xml
opengever/core/upgrades/20230214171647_add_resolver_custom_after_transition_hook_registry_field/upgrade.py
opengever/dossier/base.py
opengever/dossier/interfaces.py
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py
opengever/propertysheets/solr.py
opengever/propertysheets/tests/test_solr.py
opengever/propertysheets/utils.py

SPDAG want to track the first resolution date on their dossiers. To avoid adding a new metadata field which will only be used by them but pollute all other deployments, we are adding the tools necessary to implement the desired behaviour with custom-fields. We are therefore introducing a registry entry `resolver_custom_after_transition_hook` allowing to define a TALES expression that will be executed in a post transition hook when resolving a dossier.
The actual field, upgrade step and Tales expressions that allow to define the desired behaviour for SPDAG are [defined in their policy](https://github.com/4teamwork/opengever.spdag/pull/30).
For [CA-5229](https://4teamwork.atlassian.net/browse/CA-5229) …

Allow to define a custom dossier resolution after transition hook.

---

changes/CA-5355.bugfix
opengever/core/upgrades/20230109145141_fix_order_of_i_properties_plugin_pas_plugins/upgrade.py

This upgrade step assumed that there's always an `ldap` plugin in GEVER deployments. This is not the case anymore however for policyless deployments, so it broke upgrades on those.
For [CA-5355](https://4teamwork.atlassian.net/browse/CA-5355)
[CA-5355]: https://4teamwork.atlassian.net/browse/CA-5355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix LDAP properties plugin upgrade step to work in deployments without LDAP.

---

changes/CA-5229.other
opengever/dossier/interfaces.py

These interfaces are not needed anymore, since the upgrade step cleaning the leftovers has itself been deleted from gever long ago.
For [CA-5229]
[CA-5229]: https://4teamwork.atlassian.net/browse/CA-5229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove deprecated journal and task pdf marker interfaces.

---

changes/CA-5160.bugfix
opengever/api/tasktree.py
opengever/api/tests/test_tasktree.py

Subtasks in sequential tasks are ordered according to position in parent while they are ordered according to creation date in parallel tasks. For nested tasktemplates, with a mixture of parallel and sequential processes, the ordering was broken as it was determined once and for all on the main task. This is fixed here by determining the sort order for subtasks at each nesting level.
For [CA-5160]
[CA-5160]: https://4teamwork.atlassian.net/browse/CA-5160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ordering of subtasks in @tasktree for nested task processes.

---

changes/CA-5277.bugfix
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/participation/browser/my_invitations.py
opengever/workspace/participation/browser/templates/invalid_invitation.pt
opengever/workspace/tests/test_my_invitations.py

If an invitation is accepted which has been withdrawn/deleted in the meantime, a general error message appears. This is confusing for the user and leads to support requests.
A specific error message is now displayed:
A simple redirect and showing a status message is not possible, because the @@invitations-view is called directly on the gever backend.
For [CA-5277]
[CA-5277]: https://4teamwork.atlassian.net/browse/CA-5277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show specific error page when invitations are no longer valid.

---

changes/CA-4097.bugfix
opengever/api/save_minutes_as_pdf.py

The document titles of the generated documents have not been translated properly due to a missing parameter.
For [CA-4097]
- API change:
- If breaking:
- Bug fixed:
[CA-4097]: https://4teamwork.atlassian.net/browse/CA-4097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix translating the title for pdfs created by the @save-minutes-as-pdf API endpoint.

---

.github/workflows/docker-image.yml

The GitHub actions cache supports scopes. By using scopes for different images in the builder step, the caches are more efficient and this should speed up image building.

GitHub Actions: use scoped cache in builder.

---

changes/OGDS-SYNC.bugfix
opengever/ogds/base/sync/ogds_updater.py

OGDS sync was logging that it had added all group members of a group when a single member was added or removed. This clutters the logs and makes it pretty confusing, as if tons of new users had been added.

Fix OGDS sync logging of modified group memberships.

---

changes/CA-5251.feature
docs/public/user-manual/standardablaeufe.rst
opengever/api/tests/test_listing.py
opengever/api/tests/test_process.py
opengever/api/tests/test_templatefolder.py
opengever/base/tests/test_default_values_for_types.py
opengever/base/tests/test_utils.py
opengever/base/utils.py
opengever/latex/tests/test_dossiertasks.py
opengever/task/task.py
opengever/task/tests/test_activities.py
opengever/task/tests/test_task.py
opengever/tasktemplates/browser/tasktemplates.py
opengever/tasktemplates/content/tasktemplate.py
opengever/tasktemplates/locales/de/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/en/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/locales/opengever.tasktemplates.pot
opengever/tasktemplates/tasktemplatefolder.py
opengever/tasktemplates/tests/test_tasktemplate.py
opengever/tasktemplates/tests/test_trigger.py

We can configure a relative deadline for tasks and tasktemplates in days.
This PR changes the behavior of the absolute deadline calculation by skipping weekends.
Before this change, a deadline offset of 5 on monday would return the saturday, with this change, it returns the next monday.
For [CA-5251]
- API change:
- If breaking:
- Bug fixed:
[CA-5251]: https://4teamwork.atlassian.net/browse/CA-5251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude weekends on task deadline calculation

---

changes/CA-5506.bugfix
opengever/base/browser/folder_buttons_availability.py
opengever/dossier/tests/test_actions.py
opengever/dossier/tests/test_dossier_deleter.py

This PR fixes an issue where it was not possible to remove empty subdossiers if the main dossier was linked to a workspace.
For [CA-5506]
- API change:
- If breaking:
- Bug fixed:
[CA-5506]: https://4teamwork.atlassian.net/browse/CA-5506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Empty subdossiers can be deleted even if the main dossier is linked with a workspace

---

changes/CA-5508.other
opengever/base/browser/folder_buttons_availability.py
opengever/workspaceclient/client.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_client.py
opengever/workspaceclient/tests/test_linked_workspaces.py

This PR improves the following points:
- We do no longer validate the configuration if initializing the `WorkspaceClient`. We do it if we really need a session to make requests to the remote system. This makes debugging much easier and it allows us to use non remote system related methods for the `WorkspaceClient` or the `LinkedWorkspaces`. 
- We do no longer use the workspace client to determine if a dossier is linked to a workspace but the `LinkedWorkspacesStorage` instead. This makes it possible to check if there are linked workspaces even if we do not have access to the remote system
For [CA-5508]
- …

Improve workspace client

---

changes/CA-5446.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/globalindex.rst
opengever/api/globalindex.py
opengever/api/tests/test_globalindex.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_query.py

This PR implements an additional option called `duplicate_strategy` for the `@globalindex` endpoint.
This options allows us to change the behavior of which task should be returned for successor/predecessor task pairs.
We need this, because we sometimes need to change this behavior depending on the purpose of the request.
One use case is i.e. to get all tasks which I issued. In that case, I usually want the `predecessor_task` strategy which would always return the main task if there is also a predecessor task.
Providing this feature allows us to fix an issue in the frontend where the user does not see his tasks if requesting the `@globalindex` endpoint from a third admin unit.
For [CA-5446] …

Add duplicate-strategies to the @globalindex endpoint.

---

changes/CA-5545.feature
changes/CA-5546.bugfix
opengever/api/tests/test_templatefolder.py
opengever/base/addressblock/addressblock.py
opengever/base/addressblock/extraction.py
opengever/base/addressblock/tests/test_address_formatting.py
opengever/base/addressblock/tests/test_extraction.py
opengever/kub/tests/test_docprops.py

For [CA-5545] and [CA-5546]
[CA-5545]: https://4teamwork.atlassian.net/browse/CA-5545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-5546]: https://4teamwork.atlassian.net/browse/CA-5546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle extra address lines and use correct address for memberships in address block

---

changes/CA-5516.bugfix
opengever/ogds/base/sync/ogds_updater.py

Re-registering a file hander every time the ogds sync is called works fine when it is run as a zope control command, but when it is called over the API, i.e. on a running instance, we should only register the file handler once.
For [CA-5516]
[CA-5516]: https://4teamwork.atlassian.net/browse/CA-5516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make sure to register @ogds-sync file logger only once.

---

changes/CA-5248.bugfix
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_task_sql_syncer.py

Tasks were broken when in a dossier or subdossier with a title longer than 512 characters, as the corresponding column in the task model was limited to 512 characters. With this PR we truncate the dossier and subdossier titles to the maximal allowed length when syncing a task. 
For [CA-5248]
[CA-5248]: https://4teamwork.atlassian.net/browse/CA-5248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle long dossier and subdossier titles in task sync.

---

changes/CA-5570.bugfix
opengever/document/document.py
opengever/document/tests/test_document_workflow.py

Reopen a finalized document is only possible, if there are no pending approval tasks. Therefore the finalization of a document should only be possible if there is not already referenced by pending approval tasks. Otherwise this leads to issues like [CA-5570]
[CA-5570]: https://4teamwork.atlassian.net/browse/CA-5570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prevent finalization if document is referenced by a pending approval task

---

changes/CA-5546.bugfix
opengever/workspace/participation/browser/my_invitations.py
opengever/workspace/tests/test_my_invitations.py

No longer redirect to the login page and redirect to the portal page instead. Because only the portal page, redirects to external authentication service, like secure-connect.
In addition to #7610 we also need adjust the portal redirect for already accepted invitations.
For [CA-5170]
[CA-5170]: https://4teamwork.atlassian.net/browse/CA-5170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix workspace invitation redirects for already accepted invitations.

---

changes/CA-5158.feature
opengever/api/configure.zcml
opengever/api/listing.py
opengever/api/solr_query_service.py
opengever/api/solrsearch.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_solrsearch.py
opengever/api/upload_structure.py
opengever/core/solr_testing.py
opengever/core/upgrades/20230323120723_reindex_metadata_field/upgrade.py
opengever/officeconnector/tests/test_api_dossier_attach.py
opengever/officeconnector/tests/test_api_mail_attach.py
solr-conf/managed-schema
solr-conf/solrconfig.xml

The behavior of the livesearch in Gever is currently pretty confusing, as only searches for full tokens will lead to results. This typically leads to having 0 results after typing a few characters, but results will appear again later, once a word is complete.
We propose here to fix this by specifically adding wildcards to the terms of the query and doing some tokenization as it will not happen for wildcard queries.
I also switch the default operator the `AND`, IMO this is the expected behavior, getting fewer results when searching for more terms (this is also what google does). I had to set the `q.op` parameter and not the `mm`, as this otherwise prevents from using operators in the queries.
I've also added boosting of recently `changed` objects, which got lost when we switched to the …

Add @solrlivesearch endpoint and improve solr configuration. 

---

changes/CA-5229.other
opengever/dossier/tests/test_resolve.py
opengever/propertysheets/utils.py

Setting date values to a custom property is not possible when using the `resolver_custom_after_transition_hook` of the `IDossierResolveProperties` because it is not allowed to use pythons `datetime.date()` function in restricted python. We can only use `DateTime.utcdatetime()`. Therefore, we need to cast the datetime value to a date if the underlying schema field is of type Date.
⚠️ Requires a backport to `2023.5.x`
For [CA-5229]
- API change:
- If breaking:
- Bug fixed:
[CA-5229]: …

Cast datetime values to date objects for customproperty date fields.

---

opengever/task/task.py

`datetime.today().date()` does not always return the same date as `date.today()`. We now consistently use date.today() for all deadline calculations.
I could have fixed the tests, but we already calculate the deadline for tasktemplates using `date.today()`, so decided to make it consistent instead.
This should fix the failing nightly build tests, see https://ci.4teamwork.ch/builds/555422/tasks/1097389

Fix flaky test for task deadline default values.

---

changes/CA-5629.bugfix
opengever/disposition/browser/excel_export.py
opengever/disposition/tests/test_excel_export.py

Excel does not allow some characters in their sheet title, so we need to escape them.
For [CA-5629], solves https://sentry.4teamwork.ch/organizations/sentry/issues/105601/?project=17&query=is%3Aunresolved+valueerror&statsPeriod=14d
- Bug fixed:
[CA-5629]: https://4teamwork.atlassian.net/browse/CA-5629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Escape invalid characters in the sheet title of disposition exports.

---

changes/CA-5477.bugfix
opengever/api/solr_query_service.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_solrsearch.py

With commit https://github.com/4teamwork/opengever.core/pull/7683/commits/fbb504ae641cc8aaac129780ffa48bd3a96ef99a, I broke handling of trailing wildcards, this leads to queries for listings where the query is simply `*` to query solr with `**`. For some reason such queries are much slower. With this PR we fix handling of trailing wildcards to avoid this issue.
For [CA-5477]
[CA-5477]: https://4teamwork.atlassian.net/browse/CA-5477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix handling of trailing wildcard in query preprocessing.

---

changes/CA-5635.bugfix
opengever/dossier/docprops.py
opengever/dossier/tests/test_default_doc_property_adapters.py

In some case, custom_properties of the type `multiple_choice` provide a value from type `list` and not `set`. The current implementation does not handle this case, which leads in an `Unsupported type <type 'list'>` exception when creating or updating docprops for a document.
For [CA-5635]
- Bug fixed:
[CA-5635]: https://4teamwork.atlassian.net/browse/CA-5635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix docproperty collector for custom_properties with a list as value.

---

changes/CA-5630.bugfix
opengever/disposition/browser/removal_protocol.py

Starting with the earliest entry and ends with the latest, makes more sense.
I have waived a test. We currently have no way to parse back the latex table, so it would be too time-consuming.
For [CA-5630]
[CA-5630]: https://4teamwork.atlassian.net/browse/CA-5630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change history order in the disposition removal protocol.

---

changes/CA-5584-2.other
changes/CA-5584.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/navigation.py
opengever/api/tests/test_navigation.py
opengever/api/tests/test_workspace.py
opengever/dossier/utils.py

This PR:
- extends the `@navigation` endpoint by always excluding trashed items. Currently, we do not have any use case where we need or want to display trashed navigation items
- register a `workspace` as a main-dossier.
For [CA-5584]
- API change:
- If breaking:
- Bug fixed:
[CA-5584]: https://4teamwork.atlassian.net/browse/CA-5584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Workspace navigation

---

pyproject.toml
towncrier.rst

This configures towncrier to add the Jira issue number when generating the changelog from the news fragements.
The issue number is the part of the news fragment filename left to the extension, e.g. `CA-4567` from `CA-4567.bugfix`.
It will (should) produce a HISTORY.rst that looks like this in its raw form:
```rst
2023.6.0 (2023-04-10)
---------------------
New features:
- Add @solrlivesearch endpoint and improve solr configuration. [njohner][CA-3456]
- Use Bcc when sharing content in Teamraum with all participants. [njohner][CA-4567]
- Handle extra address lines in address block. [njohner][CA-1234]
```
and is rendered like this:
---
---
I decided not to actually link the Jira issue, because this would significantly clutter the raw RST. 
[CA-3456]: …

Towncrier: Add Jira issue when generating changelog.

---

changes/CA-5562.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/tests/test_document.py
opengever/testing/test_case.py
opengever/workspaceclient/linked_documents.py
opengever/workspaceclient/tests/__init__.py

This is needed for displaying the links to the workspace documents on the GEVER side.
For [CA-5562]
- API change:
[CA-5562]: https://4teamwork.atlassian.net/browse/CA-5562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add workspace document urls in document serialization.

---

changes/CA-5400.bugfix
opengever/activity/model/activity.py
opengever/activity/sources.py
opengever/activity/tests/test_notification_center.py
opengever/api/tests/test_external_activities.py
opengever/api/tests/test_watchers.py
opengever/api/watchers.py

Inactive users are no longer displayed as observers and are also no longer available for selection.
For [CA-5400]
[CA-5400]: https://4teamwork.atlassian.net/browse/CA-5400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hide and skip inactive users in the @watchers endpoints.

---

changes/CA-5363.bugfix
opengever/task/browser/complete.py
opengever/task/response_syncer/workflow.py
opengever/task/task.py
opengever/task/tests/test_response_syncer.py

In some cases there is a mismatch between successor/predecessor pairs, which leads to a WorkflowException when trying to sync the workflow transition to the remote site, via remote_request. This cases needs to be fixed manually via debug mode.
To prevent this support effort, we try to fix this review_state mismatch automatically, when a workflow transition sync fails.
For [CA-5363]
[CA-5363]: https://4teamwork.atlassian.net/browse/CA-5363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle review_state mismatch between successor/predecessor pairs gracefully

---

changes/CA-5726.other
opengever/core/upgrades/20230504163300_reindex_not_properly_indexed_files/upgrade.py

This PR reindexes files which may be not properly indexed.
The index is out of sync for files, mainly the filename index. Because we do not really know all the indexes which could be out of sync, we'll just reindex the full object.
The reason why these files where not properly indexed is not yet fully clear. It could have happened when introducing the `filename` index
Since most of the files are properly indexed, we do not use a nightly job for this upgradestep.
Slack-Reference: https://4teamwork.slack.com/archives/C01BHEGBVU1/p1683206204789769
For [CA-5726]
- …

Reindex maybe not properly indexed files

---

opengever/ech0147/utils.py

This PR adds a comment to give a pointer of a special pyxb implementation when importing an ech0147 zip file.
For [CA-5751]
- API change:
- If breaking:
- Bug fixed:
[CA-5751]: https://4teamwork.atlassian.net/browse/CA-5751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a comment for the ech0147 import function

---

changes/CA-5556.other
opengever/core/upgrades/20221115154555_add_task_responsible_role/upgrade.py
opengever/core/upgrades/20230105124325_update_workflows/upgrade.py

When modifying the workflow of workspace documents, we should avoid reindexing the security for all Gever documents...
We modify two upgrade steps here to create the list of workflows to reindex depending on whether the deployment is a Gever or a Teamraum.
One upgrade step is in Gever version 2022.24.0, the other in 2023.1.0 so we do not need to backport this for SG, but only for the LTS release (for on Prem update).
For [CA-5556]
[CA-5556]: https://4teamwork.atlassian.net/browse/CA-5556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Speed-up upgrade step reindexing workspace documents'workflow.

---

changes/CA-5850.bugfix
opengever/disposition/ech0160/model/repository.py

https://github.com/4teamwork/opengever.core/assets/557005/5056dc3f-371f-4326-ad9c-6b52c573f34a
https://github.com/4teamwork/opengever.core/assets/557005/8b7d3372-dd15-47aa-abf9-1940434e3ef1
For [CA-5850]
- API change:
- If breaking:
- Bug fixed:
[CA-5850]: https://4teamwork.atlassian.net/browse/CA-5850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ech0160 when submitting disposition if there are umlauts in a repository title.

---

changes/CA-5766a.other
opengever/ogds/auth/plugin.py
opengever/ogds/auth/tests/test_plugin.py

`IGroupIntrospection` is needed to allow setting permissions for OGDS groups in the sharing view. Also makes OGDS groups show up in the Plone control panel.
The methods aren't cached currently, as we expect they are used rarley. Caching could be easily done though.
`getGroups()` is implemented in a naive way and could be optimized to not query each group separately, but we are not expecting to use it.
For [CA-5766](https://4teamwork.atlassian.net/browse/CA-5766)
[CA-5766]: https://4teamwork.atlassian.net/browse/CA-5766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement IGroupIntrospection for OGDS auth plugin

---

changes/CA-5831.bugfix
opengever/api/users.py

The problem was a security check in deletePersonalPortrait method. With the current implementation the userid was "normalized" twice. And the safeId ist not the same as the current user id, which led to Unauthorized raised.
The safeId inside our own API endpoint is unnecessary and can be removed, MembershipTools implementation already takes care of that.
I was not able to provide a specific test for the mail situation in reasonable time
For [CA-5831]
- Bug fixed:
[CA-5831]: https://4teamwork.atlassian.net/browse/CA-5831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix portrait removal for users with mail address as userid.

---

changes/CA-5463.feature
opengever/api/tests/test_solrsearch.py
opengever/base/utils.py
opengever/core/upgrades/20230524173623_add_related_items_solr_index/upgrade.py
opengever/document/configure.zcml
opengever/document/indexers.py
opengever/document/tests/test_indexers.py
opengever/dossier/tests/test_copy_dossier.py
opengever/mail/tests/test_extract_attachments.py
opengever/meeting/tests/test_proposal.py
opengever/task/configure.zcml
opengever/task/indexers.py
opengever/task/tests/test_indexer.py
opengever/testing/helpers.py
solr-conf/managed-schema

With this PR we index related items for documents and tasks in Solr. This can be used for example to display contained and related documents of a task (see test `test_get_related_and_contained_documents`).
Tests are failing because we would need to build and use a new image of solr to include the changes in solr configuration.
For [CA-5463]
[CA-5463]: https://4teamwork.atlassian.net/browse/CA-5463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Index related items for documents and tasks

---

changes/CA-5463.other
opengever/core/docker_testing.py
opengever/core/solr_testing.py
opengever/dossier/tests/test_move_items.py

We always want to test against the latest versions of the services and especially of `ogsolr`.
For [CA-5463]
[CA-5463]: https://4teamwork.atlassian.net/browse/CA-5463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Always pull latest docker images for testing.

---

changes/CA-5702.other
opengever/nightlyjobs/maintenance_jobs.py
opengever/nightlyjobs/runner.py

Nightly job execution spams the logs with way too much trash. We try to improve this here by logging only every 5000 jobs of the same type, but also by indicating total number of executed and remaining jobs. We also log when we switch to a new job type. Finally we avoid logging that we are processing the task queue for every job, although there never is anything to process...
For [CA-5702]
[CA-5702]: https://4teamwork.atlassian.net/browse/CA-5702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve logging for maintenance jobs.

---

changes/CA-5898.bugfix
opengever/core/upgrade.py
opengever/core/upgrades/20230608115956_reindex_french_and_german_content_in_solr/upgrade.py
solr-conf/managed-schema

Make text analysation accent insensitive by adding the asciifoldingfilterfactory which normalize non-asccii characters.
Provides an upgradestep which reindex content detected as french or english content overnight.
For [CA-5764](https://4teamwork.atlassian.net/browse/CA-5764)
Needs backport to LTS 2023.6.x
[CA-5895]: https://4teamwork.atlassian.net/browse/CA-5895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-5764]: https://4teamwork.atlassian.net/browse/CA-5764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve search behavior for english and french content.

---

changes/CA-4519-2.feature
changes/CA-4519-3.feature
changes/CA-4519-3.other
changes/CA-4519.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/configure.zcml
opengever/api/listing.py
opengever/api/listing_stats.py
opengever/api/solr_query_service.py
opengever/api/tests/test_listing_stats.py
opengever/api/tests/test_templatefolder.py
opengever/base/tests/test_default_values_for_types.py
opengever/core/tests/test_relations.py
opengever/dossier/dossiertemplate/behaviors.py
opengever/dossier/dossiertemplate/configure.zcml
opengever/dossier/dossiertemplate/form.py
opengever/dossier/dossiertemplate/indexers.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_dossier_template.py

This PR extends the dossier template schema with a `related_documents` field. It allows document templates as references which will be created as new documents when adding a new dossier from a dossier template.
For [CA-4519]
- API change:
- If breaking:
- Bug fixed:
[CA-4517]: https://4teamwork.atlassian.net/browse/CA-4517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-4519]: https://4teamwork.atlassian.net/browse/CA-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

Dossier templates can reference document templates.

---

changes/CA-5001.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_tus.py
opengever/api/tus.py

This PR extends the `@tus-upload` endpoint to allow a `document_date` within the `Upload-Metadata`-header to directly set a custom document date.
For [CA-5001]
- API change:
- If breaking:
- Bug fixed:
[CA-5001]: https://4teamwork.atlassian.net/browse/CA-5001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

@tus-upload can directly set a custom document_date.

---

changes/CA-5921.other
changes/CA-5921_2.other
opengever/api/navigation.py
opengever/api/recently_touched.py
opengever/api/tasktree.py
opengever/api/tests/test_navigation.py
opengever/api/tests/test_tasktree.py
opengever/api/transfer.py
opengever/base/solr/__init__.py
opengever/ogds/base/sources.py
opengever/tabbedview/catalog_source.py
opengever/task/browser/related_documents.py
opengever/task/tests/test_related_documents_tab.py

For the `@recently-touched` endpoint, I tested locally with a large Excel file (the one causing issues in SG), and request time went from 41seconds to 50ms.
We also set the `fl` parameters for all solr searches made in opengever.core, except the ones where we set `rows=0`, as it doesn't make any performance difference in such queries (typically facet queries).
I have also made changes to `ftw.solr` to log warnings when we query solr without specifying `fl`.
For [CA-5921]
[CA-5921]: https://4teamwork.atlassian.net/browse/CA-5921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Massively improve performance of @recently-touched endpoint.

---

changes/CA-4911.bugfix
opengever/propertysheets/default_from_member.py
opengever/propertysheets/tests/test_default_from_member.py

During the os migration on a customer system we recognized, that the logs contains a lot of warnings like `WARNING opengever.propertysheets Failed to retrieve property language from member Anonymous User for request <HTTPRequest, URL=xy>: Got: TypeError("getProperty() got an unexpected keyword argument 'default'",)`
The reason is that some calls are done anonymously, we just return the fallback in this case.
For [CA-4911]
[CA-4911]: https://4teamwork.atlassian.net/browse/CA-4911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix member default for propertysheet fields.

---

changes/CA-5929.feature
opengever/document/actions.py
opengever/document/tests/test_actions.py

Note that I can't rely on the `Copy or Move` permission which is inherited from somewhere for everyone. Modifying that permission would not work either as we typically want a user to have the `Copy or Move` on contexts he can see, while here we want to couple showing the "copy_items" action with the user being member on the context, i.e. having some sort of "Edit" permission.
For [CA-5929]
[CA-5929]: https://4teamwork.atlassian.net/browse/CA-5929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hide copy, move and edit items actions for workspace guests on document listings.

---

changes/CA-5939.other
opengever/activity/center.py
opengever/activity/tests/test_notification_center.py
opengever/api/notifications.py
opengever/api/tests/test_notifications.py

We now avoid getting all the users notifications from the OGDS DB, instead only getting the batch we actually want.
This should dramatically increase the performance of the `@notifications` endpoint for users with a large number of notifications (there is a user in SG with 150'000 notifications). Note that slow requests on the OGDS will block all other users from all tenants, so this is a critical fix which we will backport to our LTS and to the SG release.
For a user with 70'000 notifications, performance improvement was from 2s to 300ms.
For [CA-5939]
[CA-5939]: https://4teamwork.atlassian.net/browse/CA-5939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve performance of @notifications endpoint.

---

changes/CA-5959.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/activity/center.py
opengever/activity/tests/test_notification_center.py
opengever/api/tests/test_notifications.py

This ensures that the frontend always displays the first unread notifications and that it always knows if there are unread notifications.
For [CA-5959]
[CA-5959]: https://4teamwork.atlassian.net/browse/CA-5959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Notification views in frontend by sorting unread notifications first in @notifications endpoint.

---

changes/CA-5543-2.feature
changes/CA-5543-3.feature
changes/CA-5543.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/system_information.rst
opengever/api/configure.zcml
opengever/api/system_information.py
opengever/api/tests/test_system_information.py

This PR introduces a new endpoint `@system-information`:
- `dossier_participation_roles`
- `property_sheets`
ℹ️ why not using the already existing `@config` endpoint which already provides some info about the system?
Because the `@config`-endpoint is the main entry endpoint for the `gever-ui` and should be as fast as possible. The endpoint should only provide information which is required to let the ui properly run. The `@system-information`-endpoint is used for a dedicated information-view in the UI. This endpoint can return expensive data because it will not be called often. It should provide the information in a way that the frontend can easily display the data.
For [CA-5543]
_Only …

System information endpoint

---

changes/CA-4999.feature
opengever/api/tests/test_document.py
opengever/core/upgrades/20230623124442_add_upload_mimetype_blacklist/registry.xml
opengever/core/upgrades/20230623124442_add_upload_mimetype_blacklist/upgrade.py
opengever/document/document.py
opengever/document/interfaces.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot

This PR adds an upload mimetype blacklist.
https://github.com/4teamwork/opengever.core/assets/557005/735759fa-3aaa-4f45-aea6-e0d725454694
For [CA-4999]
- API change:
- If breaking:
- Bug fixed:
[CA-4999]: https://4teamwork.atlassian.net/browse/CA-4999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow to configure an upload mimetype blacklist

---

changes/CA-1971.feature
docs/schema-dumps/opengever.workspace.workspace.schema.json
opengever/bundle/schemas/workspaces.schema.json
opengever/core/upgrades/20230622101030_initialize_footer_meeting_template_settings/upgrade.py
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/tests/test_meeting_minutes.py
opengever/workspace/tests/test_workspace_workspace.py
opengever/workspace/workspace.py

This PR introduces the possibility to configure the header and footer of the meeting minutes PDF for a workspace. The configuration provides a left, center and right block for the header and footer area, where the user can add text, use dynamic content like page_number, number_of_pages, print_date or even include the customers logo or a specific workspace logo.
The configuration is stored in two separate JSON fields. Those fields are initialized with the current configuration, so nothing changes for existing workspaces. 
The UI Implementation will look like this:
For [CA-1971]
[CA-1971]: https://4teamwork.atlassian.net/browse/CA-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

Introduce configuration options for workspace meeting minutes PDF 

---

changes/CA-5949.bugfix
opengever/repository/subscribers.py
opengever/repository/tests/test_subscribers.py

Repositoryfolder contains the complete prefix number, so we need to reindex all title indexes for sub-repositoryfolders.
IMHO no need for an upgradestep, the users reindex the object, by manually edit each sub position.
For [CA-5949]
[CA-5949]: https://4teamwork.atlassian.net/browse/CA-5949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix title updating of sub repositoryfolder when prefix changes.

---

changes/CA-5857.other
opengever/disposition/ech0160/sippackage.py
opengever/disposition/tests/test_ech0160export.py
opengever/disposition/tests/test_sippackage.py

I gave up using the creation date of the disposition instead of the delivery date of the SIP package, as this folder name format is part of the eCH 160 standard (see https://www.ech.ch/sites/default/files/dosvers/hauptdokument/STAN_d_DEF_2022-05-11_eCH-0160_V1.2.0_ArchivischeAblieferungsschnittstelle.pdf page 30 or excerpt below). Instead I simply added the dispositions sequence number, making the folder names unique and avoiding name conflicts. This change is also in line with the eCH 160 standard as the last part of the folder name can be freely chosen.
For [CA-5857]
[CA-5857]: https://4teamwork.atlassian.net/browse/CA-5857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add disposition sequence number to SIP folder name.

---

changes/CA-6037.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_schema.py
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/restapi_utils.py

Currently the @schema endpoint only returns information for the add or the edit form. This leads to the problem, that the lifecycle informations (ILifeCycle) are not visible for users, which does not have the `EditLifecycleAndClassification` permission. 
To fix this issue I introduced a display mode, similar than plone.dexterity already those for the DefaultView, that mode can be used by the gever-ui for the MetaDataPanel.
For [CA-6037]
- API change:
[CA-6037]: https://4teamwork.atlassian.net/browse/CA-6037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce display mode in the @schema endpoint.

---

opengever/core/upgrade.py
opengever/core/upgrades/20220917130346_remove_inactive_group_memberships/upgrade.py

This PR provides two oracle specific fixes for deployment which uses oracle db.  
For [CA-5783] 
Backport to `2023.8-stable` needed
[CA-5783]: https://4teamwork.atlassian.net/browse/CA-5783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix schema migration for ogds oracle backend.

---

changes/CA-6061.bugfix
opengever/dossier/actions.py
opengever/dossier/tests/test_actions.py

Dispositions cannot be created in dossiers, so the action should not be available on subdossier listings.
For [CA-6061]
[CA-6061]: https://4teamwork.atlassian.net/browse/CA-6061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not display create_disposition action on subdossier listings.

---

changes/CA-6039.other
opengever/api/tests/test_config.py
opengever/base/interfaces.py
opengever/base/tests/test_configuration_adapter.py
opengever/base/tests/test_gever_ui_action.py
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

Enable GEVER UI registry feature by default.
Even though the classic UI still has many fans 😜 , there won't be any deployments any more where we don't also deploy the GEVER UI. Any this feature flag only controls the switcher action anyway. We therefore make it true by default, and we can kill the feature flag soon with https://4teamwork.atlassian.net/browse/CA-6036
I also removed the question from the policytemplate:
Since the flag is now enabled by default, we don't need the explicit registry entry any more. Disabling it is still possible, but should be so rare that it's not supported by the policytemplate any more.
For [CA-6039](https://4teamwork.atlassian.net/browse/CA-6039)
[CA-6039]: https://4teamwork.atlassian.net/browse/CA-6039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

Enable GEVER UI registry feature by default.

---

changes/CA-5766.other
opengever/ogds/base/sync/import_stamp.py
opengever/ogds/base/tests/test_ogds_updater.py

The new OGDS sync service only sets it in OGDS.
This is used for the extended healthcheck.
Should fix extended health check for test.onegovgever.ch and lab.onegovgever.ch
For [CA-5766](https://4teamwork.atlassian.net/browse/CA-5766)
[CA-5766]: https://4teamwork.atlassian.net/browse/CA-5766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Read OGDS sync timestamp from OGDS instead of ZODB

---

changes/CA-5991.bugfix
opengever/api/copy_.py
opengever/api/tests/test_copy_paste.py
opengever/base/browser/paste.py
opengever/base/tests/test_copy_paste.py

Proposal excerpts, which get deposited and locked in the dossier from which the proposal originated, prevented copy/pasting the dossier. Copy/pasting of only the excerpt actually already worked, and there is no reason to prevent copying the dossier. We therefore fix this by removing the locked on the copy of the excerpt before renaming happens (which is what was raising an error before this change).
For [CA-5991]
[CA-5991]: https://4teamwork.atlassian.net/browse/CA-5991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow copying dossiers containing locked excerpt documents.

---

changes/CA-6039-1.bugfix
opengever/setup/browser/adddeployment.pt

Policyless deployments: Fix link to bundle import view.
For [CA-6039](https://4teamwork.atlassian.net/browse/CA-6039)
[CA-6039]: https://4teamwork.atlassian.net/browse/CA-6039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Policyless deployments: Fix link to bundle import view.

---

changes/CA-6104.feature
opengever/api/linked_workspaces.py
opengever/api/tests/test_linked_workspaces.py

We need to cover the case where a user has permissions on a subdossier but not on the main dossier. The gever-ui would until now call the `@linked-workspaces` on the main dossier, leading to an error. Instead we now allow calling that endpoint on subdossiers, but it will return the workspaces linked to the main dossier. As workspaces can only be linked to main dossiers, this is fine.
For [CA-6104]
[CA-6104]: https://4teamwork.atlassian.net/browse/CA-6104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Getting @linked-workspaces on subdossier returns workspaces linked to main dossier

---

changes/CA-6128.bugfix
opengever/api/configure.zcml
opengever/api/mail.py
opengever/api/tests/test_mail.py
opengever/mail/browser/extract_attachments.py
opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/en/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/opengever.mail.pot
opengever/mail/mail.py
opengever/mail/tests/test_extract_attachments.py

Extraction worked in the classic UI but not over the API because we checked the permission to add documents on the context instead of on the extraction target.
Test failures seem unrelated, probably due to the new solr  container that was pushed to the `latest` tag.
For [CA-6128]
[CA-6128]: https://4teamwork.atlassian.net/browse/CA-6128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix extraction of attachments from mails in closed tasks.

---

changes/CA-6128.other
opengever/document/configure.zcml
opengever/document/tests/test_actions.py
opengever/mail/actions.py
opengever/mail/configure.zcml
opengever/mail/tests/test_actions.py

Currently the action to extract attachments from an E-mail always appears, whether it's possible to do so or not. We therefore introduce a context action that the frontend can use to only display the action when necessary.
For [CA-6128]
[CA-6128]: https://4teamwork.atlassian.net/browse/CA-6128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add extract_attachments context action for mails.

---

changes/CA-6136.bugfix
opengever/api/tests/test_solrsearch.py
solr-conf/managed-schema
solr-conf/solrconfig.xml

Currently two strings combined with an underscore are not indexed separately as it was in former versions of GEVER.
I also added the reference field  to the searched fields, this improves the search results, when searching with a specific
reference-number.
For [CA-6136]
[CA-6136]: https://4teamwork.atlassian.net/browse/CA-6136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add WordDelimiterGraphFilterFactory to all text indexers.

---

changes/CA-6021.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/task.py
opengever/api/tests/test_task.py
opengever/task/task.py

This flag is used to decide correctly if the AcceptTaskAlert should be displayed in the UI or not.
For [CA-6021]
- API change:
[CA-6021]: https://4teamwork.atlassian.net/browse/CA-6021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add is_current_user_responsible flag to task api serialization.

---

changes/CA-6168.bugfix
opengever/disposition/disposition.py
opengever/disposition/ech0160/sippackage.py
opengever/disposition/tests/test_sippackage.py

Currently the SIP package include also dossiers with a negative appraisal, which should not be exported and imported in to a DLZA. This PR fixes this issue.
For [CA-6168]
[CA-6168]: https://4teamwork.atlassian.net/browse/CA-6168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include only dossiers with positive appraisal in the SIP package.

---

changes/CA-5563.feature
docker/core/etc/site.zcml
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/listing.py
opengever/api/serializer.py
opengever/api/tests/test_favorites.py
opengever/api/tests/test_linked_workspaces.py
opengever/api/tests/test_serializer.py
opengever/api/tests/test_summary_serializer.py
opengever/base/handlers.py
opengever/base/model/favorite.py
opengever/core/upgrades/20230911131841_reindex_is_locked_by_copy_to_workspace/upgrade.py
opengever/document/base.py
opengever/document/configure.zcml
opengever/document/indexers.py
opengever/dossier/tests/test_move_items.py
opengever/locking/lockable.py
opengever/locking/overrides.zcml
opengever/locking/tests/test_locks.py
opengever/testing/integration_test_case.py
solr-conf/managed-schema

This PR adds a new solr index `is_locked_by_copy_to_workspace` and provides it in listings.
This allows us to mark such contents in listings in the UI as locked.
We can't just reindex the object in the `@lock`/`@unlock` endpoints because it is also possible to unlock the content through the old ui. In addition, there is a function in the `ILocking` behavior which unlocks all locks. So we have to override the `TTWLockable` object to implement the reindex in the source of locking.
For [CA-5563]
- API change:
- If breaking:
- Bug fixed:
- …

Add new solr index `is_locked_by_copy_to_workspace` and provide it in serializations. 

---

changes/CA-5099.feature
opengever/api/tests/test_response.py
opengever/base/response.py
opengever/base/tests/test_response.py
opengever/workspace/configure.zcml
opengever/workspace/subscribers.py
opengever/workspace/tests/test_todo.py

This PR adds response objects for created, closed and reopened todos.
For [CA-5099]
- API change:
- If breaking:
- Bug fixed:
[CA-5099]: https://4teamwork.atlassian.net/browse/CA-5099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add todo responses for created, closed and reopened todos

---

opengever/disposition/tests/test_destruction.py
opengever/mail/exceptions.py
opengever/mail/subscribers.py

There are two event handlers that can fail when deleting a dossier containing documents extracted from an E-mail: depending on the order of the object deletion, either the source E-mail will not be found, or the extracted document is not found.
For [CA-6195]
[CA-6195]: https://4teamwork.atlassian.net/browse/CA-6195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix deletion of dossiers containing attachments extracted from mails.

---

changes/CA-6141.bugfix
opengever/disposition/browser/removal_protocol.py
opengever/disposition/tests/test_removal_protocol.py

Fix UnicodeError in removal protocol download.
`View.convert_plain()` from ftw.pdfgenerator always returns a bytestring, even when passed unicode.
Sentry: https://sentry.4teamwork.ch/organizations/sentry/issues/105603/
For [CA-6141](https://4teamwork.atlassian.net/browse/CA-6141)
[CA-6141]: https://4teamwork.atlassian.net/browse/CA-6141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disposition: Fix UnicodeError in removal protocol download.

---

changes/CA-6039.feature
opengever/bundle/cfgs/oggbundle.cfg
opengever/bundle/console.py
opengever/bundle/importer.py
opengever/bundle/sections/map_principal_names_to_ids.py
opengever/bundle/tests/test_section_map_principal_names_to_ids.py
opengever/bundle/transmogrifier.zcml

For principal names that appear in local roles (the `_permissions` property in bundle items), **map their names to ids** based on OGDS users / groups.
This is required to support new-style deployments with OGDS auth plugin and user/group names and ids that are distinct from each other (as opposed to legacy style deployments where they are identical).
**Notes:**
- This mapping will be applied during every bundle import, regardless of whether the deployment is new-style or legacy. On legacy deployments it will just not have any effects, since `name == id`
- Lookups by username/groupname are case-insensitive
- If a princpal name in local roles matches both a user and a group, the group is preferred
- Since we are doing case insensitive lookups, we require that usernames / groupnames in OGDS …

Bundle import: Map principal names to ids in local roles

---

changes/CA-6167.feature
opengever/api/disposition.py
opengever/api/tests/test_disposition.py
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/en/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/base/role_assignments.py
opengever/base/tests/test_copy_paste.py
opengever/base/tests/test_role_assignments.py
opengever/core/upgrades/20230922085455_add_new_attributes_to_dispositions/upgrade.py
opengever/disposition/__init__.py
opengever/disposition/activities.py
opengever/disposition/configure.zcml
opengever/disposition/disposition.py
opengever/disposition/handlers.py
opengever/disposition/nightly_jobs.py
opengever/disposition/tests/test_activities.py
opengever/disposition/tests/test_disposition.py
opengever/disposition/tests/test_nightly_jobs.py
opengever/nightlyjobs/tests/test_nightly_job_runner.py
opengever/nightlyjobs/tests/test_nightly_jobs_stats.py

With this PR we make sure that archivists have the needed permissions to inspect the dossiers of an offer.
- Because this requires reindexing of all the objects inside the offer, we set the permissions in a nightly job. 
- We also provide `has_dossiers_with_pending_permissions_changes` in the serialisation of the disposition so that a warning can be shown when permissions are not up to date yet. 
- To avoid that the archivists receive an E-mail for a newly created disposition that they can't evaluate yet because they don't have the permissions on the dossier, we delay creation of the activity to after updating the permissions on all offered dossiers.
For [CA-6167]
[CA-6167]: …

Grant view permissions to archivists on offered dossiers

---

changes/CA-6217.bugfix
opengever/latex/dossierdetails.py
opengever/latex/tests/test_dossierdetails.py

It seems that in some cases custom properties with multiple values return a list and not a set. [A similar issue was already fixed for docproperties](https://github.com/4teamwork/opengever.core/pull/7710).
This might need to be backported for Zug.
This fixes https://sentry.4teamwork.ch/organizations/sentry/issues/98136
For [CA-6217]
- Bug fixed:
[CA-6217]: https://4teamwork.atlassian.net/browse/CA-6217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dossier details for dossier with custom property with a list as value

---

changes/CA-6250.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/listing.py

Whitelists the `location` field in the `@listing` endpoint.
This is required for workspace meeting listings.
For [CA-6250]
- API change:
- If breaking:
- Bug fixed:
[CA-6253]: https://4teamwork.atlassian.net/browse/CA-6253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-6250]: https://4teamwork.atlassian.net/browse/CA-6250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Whitelist the location field for the @listing endpoint.

---

changes/CA-6262.bugfix
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api_mail_attach.py

Attaching documents to an Email from different parents was broken with https://github.com/4teamwork/opengever.core/pull/7762. This change is only included in the two last releases 2023.12 and 2023.13, which are releases used only for SaaS, so we do not need to backport this.
For [CA-6262]
[CA-6262]: https://4teamwork.atlassian.net/browse/CA-6262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix attaching documents from different parents to mails.

---

changes/CA-6215.bugfix
opengever/api/tests/test_upload_structure.py
opengever/api/upload_structure.py
opengever/dossier/base.py
opengever/dossier/utils.py
opengever/private/folder.py
opengever/repository/repositoryfolder.py

We can set a global allowed dossier depth in the registry. Adding a subdossier deeper than the configured limit is not possible. Beside of this global limit, we also have a local limit which can be higher than the actual global limit. Usually, this will happen if the user creates a dossier from a template. dossier templates can be deeper nested than the global limit. 
Such dossiers will automatically expand the allowed limit to the existing subdossier-depth. Means, the user can always create siblings, even if the depth is higher than the global limit.
Currently, we do not respect this local depth when uploading a folder structure. The `@upload-structure` endpoint only checks for the global limit.
This PR fixes this issue and uses the same mechanism for checking the allowed depth in the …

Respect local dossier depth when uploading a dossier structure.

---

changes/CA-6219.other
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

I did not change the default on the `IDossierResolveProperties` interface, as this might affect existing deployments. Instead we simply set the lenient resolver in the policy templates by default.
For [CA-6219]
[CA-6219]: https://4teamwork.atlassian.net/browse/CA-6219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use lenient dossier resolver by default for newly created policies.

---

changes/CA-6264.other
opengever/api/solr_query_service.py
opengever/api/tests/test_solrsearch.py

Splitting terms in solr livesearch query preprocessing is not necessary anymore since we are not using the `StandardTokenizer` anymore.
This change is not necessary to fix the specific case described in the Story, but it still improves results and simplifies the preprocessing.
For [CA-6264]
[CA-6264]: https://4teamwork.atlassian.net/browse/CA-6264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove unnecessary term splitting solr livesearch preprocessing.

---

opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

with https://github.com/4teamwork/opengever.core/pull/7789/commits/3f0cce71eb3f96f2a4a6fd4f0f97654c87be1ade, `Role Manager` was added to lawgiver, which has as side-effect that it appears in the sharing view of diverse portal types, where it is not desired. This is fixed here, which, at least on the tested object types, recovers the roles displayed before that change in the sharing view.
For [CA-6155]
[CA-6155]: https://4teamwork.atlassian.net/browse/CA-6155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove role manager from sharing view of other contexts than dossier.

---

opengever/api/schema/adapters.py
opengever/api/tests/test_schema.py
opengever/dossier/handlers.py

Two things were broken in the new feature implemented in https://github.com/4teamwork/opengever.core/pull/7789:
- Permission check for editing the responsible field was not correct
- The event handler setting the local roles for the responsible broke the sharing view. I'm not sure why that was not picked up by any tests, as there are tests of the sharing view. Might be an event order issue?
For [CA-6155]
[CA-6155]: https://4teamwork.atlassian.net/browse/CA-6155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes for feature giving local roles to dossier responsibles.

---

changes/CA-6285.other
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/templates/demand_zip.pt
opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/en/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_zipexport.py
opengever/meeting/zipexport.py

This will fix the Zip export if any documents cannot be converted. It will basically mark the documents that still have status converting as skipped, which will lead to attaching the original document instead of the PDF to the zip file.
For [CA-6285]
[CA-6285]: https://4teamwork.atlassian.net/browse/CA-6285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add method marking unconverted documents as skipped in meeting Zip.

---

changes/CA-6281.feature
opengever/disposition/disposition.py
opengever/disposition/ech0160/sippackage.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/en/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_disposition.py
opengever/disposition/tests/test_sippackage.py

Our default for the `AktebnbildnerName` in the SIP package only makes sense for deployments where we have one AdminUnit per Service, but not for deployments like Fribourg. That Metadata should indeed contain the name of the service which was responsible for the set of documents and therefore needs to be overwritable.
For [CA-6281]
[CA-6281]: https://4teamwork.atlassian.net/browse/CA-6281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add transferring office field to dispositions to overwrite the AktenbildnerName.

---

changes/CA-6253.bugfix
opengever/document/versioner.py
opengever/dossier/command.py
opengever/dossier/tests/test_command.py

By avoiding the creation of the initial version before writing the docproperty values, we fix an issue when creating a document from template. Currently when a document gets created from template, the docproperty values are not written to the initial version of a document, but only in the working copy. This leads to a wrong document, when closing the document without doing any change after generation. Because with the recently changed office connector behavior, this cancels the checkout and drops the changes in the working copy.
For [CA-6253]
[CA-6317]: https://4teamwork.atlassian.net/browse/CA-6317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CA-6253]: https://4teamwork.atlassian.net/browse/CA-6253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

Fix docproperty writing when creating a doc from template.

---

changes/CA-5815.feature
opengever/api/tests/test_actions.py
opengever/base/context_actions.py
opengever/bumblebee/tests/test_overlay_view.py
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20231006164401_add_view_document_action/actions.xml
opengever/core/upgrades/20231006164401_add_view_document_action/upgrade.py
opengever/document/actions.py
opengever/document/browser/actionbuttons.py
opengever/document/browser/templates/macros.pt
opengever/document/fileactions.py
opengever/document/interfaces.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_actions.py
opengever/document/tests/test_document_tooltip.py
opengever/document/tests/test_overview.py
opengever/locking/tests/test_locks.py
opengever/mail/actions.py
opengever/mail/tests/test_actions.py
opengever/mail/tests/test_mail_overviewtab.py
opengever/officeconnector/configure.zcml
opengever/officeconnector/service.py

Provides a new action `oc_view` for opening documents in read-only mode with Office Connector and the associated application.
The action is always displayed if the document has a file representation unless the document is checked-out by the user himself.
Office Connector > 1.18.1 (https://github.com/4teamwork/OfficeConnector/pull/403) is required for the action to work. With older versions the action is ignored.
For [CA-5815](https://4teamwork.atlassian.net/browse/CA-5815)
- API change:
- If breaking:
- Bug fixed:
- Change in schema …

Add support for viewing documents with Office Connector

---

changes/CA-6272.other
opengever/base/viewlets/download.py
opengever/document/tests/test_download.py
opengever/virusscan/tests/test_virusscan_validator.py

Speedup is hard to measure, locally for an 84MB file it decreased from ~12 seconds to something like 200ms. On Kapo there is a 600MB file that takes 2 hours when downloading a version and a few seconds when downloading the document itself.
For [CA-6272]
[CA-6272]: https://4teamwork.atlassian.net/browse/CA-6272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Massively speed up download of file version.

---

changes/CA-6355-2.bugfix
changes/CA-6355.bugfix
opengever/api/tests/test_process.py
opengever/task/task.py
opengever/task/tests/test_task_from_template.py
opengever/tasktemplates/tasktemplatefolder.py

This PR fixes two issues with deeply nested tasks from tasktemplates.
Having a deeply nested tasktemplate with sequential and parallel tasks, task states have not been set properly in deeper nesting levels:
## After
When closing a task in a task sequence, the next task should open. If the next task is a parallel task container, the subtasks have not been properly opened.
https://github.com/4teamwork/opengever.core/assets/557005/ab798bbd-db79-4294-9eb7-a4a66da0d3cc
https://github.com/4teamwork/opengever.core/assets/557005/0496d208-e668-49aa-bebd-3b2e8738f5ee
For [CA-6355]
- API change:
- If breaking:
- Bug …

Fix deeply nested task templates

---

changes/CA-5703.other
opengever/virusscan/testing.py

Base64 encode a literal occurence of EICAR Test-File:
This is to avoid triggering an HTTPS proxy on an on prem installation that performs virus scans.
For [CA-5703](https://4teamwork.atlassian.net/browse/CA-5703)
[CA-5703]: https://4teamwork.atlassian.net/browse/CA-5703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Base64 encode a literal occurence of EICAR Test-File:

---

changes/CA-6440.bugfix
opengever/dossier/base.py
opengever/dossier/tests/test_base.py
opengever/dossier/tests/test_dossier.py
opengever/dossier/tests/test_move_items.py

Allow max depth violations, if the main dossier already contains subdossiers which exceed the max dossier depth.  Regardless of whether it is the current sub-branch or not.
For [CA-6440]
Backport to 2023.14 necessary. 
[CA-6440]: https://4teamwork.atlassian.net/browse/CA-6440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make max dossier depth restriction less strict.

---

changes/CA-5703-1.other
opengever/api/tests/test_document.py
opengever/core/upgrades/20231127105110_add_i_document_settings_upload_filetypes_blacklist_registry_record/registry.xml
opengever/core/upgrades/20231127105110_add_i_document_settings_upload_filetypes_blacklist_registry_record/upgrade.py
opengever/core/upgrades/20231127113003_remove_i_document_settings_upload_mimetype_blacklist_registry_record/registry.xml
opengever/core/upgrades/20231127113003_remove_i_document_settings_upload_mimetype_blacklist_registry_record/upgrade.py
opengever/document/document.py
opengever/document/interfaces.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot

Blacklist uploaded file formats based on extension instead of mimetype.
Blacklisting file formats by mimetypes doesn't work well because many file formats resolve to the MIME type `text/plain`, unless we specifically add them to our registry.
For [CA-5703](https://4teamwork.atlassian.net/browse/CA-5703)
[CA-5703]: https://4teamwork.atlassian.net/browse/CA-5703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Blacklist uploaded file formats based on extension instead of mimetype.

---

changes/CA-6464.bugfix
opengever/api/accessible_workspaces.py

Fix Unicode error in `@accessible-workspaces` endpoint.
For [CA-6464](https://4teamwork.atlassian.net/browse/CA-6464)
Follow-Up story: https://4teamwork.atlassian.net/browse/CA-6473
[CA-6464]: https://4teamwork.atlassian.net/browse/CA-6464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Unicode error in `@accessible-workspaces` endpoint.

---

opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Prepare testing for using a username different from userid.
- Use `username` for logging in during test, instead of `userid`
- Make sure username gets set correctly for Plone users
- Base email on username

Prepare testing for using a username different from userid

---

README.rst
opengever/api/tests/test_ogdsuserlisting.py
opengever/ogds/auth/tests/test_plugin.py
opengever/testing/fixtures.py

Tests: Use different userid for fixture user `limited_admin`

Tests: Use different userid for fixture user limited_admin

---

README.rst
opengever/api/tests/test_external_activities.py
opengever/testing/fixtures.py

Tests: Use different userid for fixture user `member_admin`

Tests: Use different userid for fixture user member_admin

---

README.rst
opengever/api/tests/test_disposition.py
opengever/testing/fixtures.py

Tests: Use different userid for fixture user `records_manager`

Tests: Use different userid for fixture user records_manager

---

README.rst
opengever/api/tests/test_serializer.py
opengever/testing/fixtures.py

Tests: Use different userid for fixture user `service_user`

Tests: Use different userid for fixture user service_user

---

README.rst
opengever/activity/tests/test_sources.py
opengever/api/tests/test_watchers.py
opengever/dossier/tests/test_protect_dossier.py
opengever/testing/fixtures.py
opengever/testing/tests/test_fixtures.py

Tests: Use different userid for fixture user `dossier_manager`
Corresponding test fixes in gever-ui: https://github.com/4teamwork/gever-ui/pull/2630

Tests: Use different userid for fixture user dossier_manager

---

changes/CA-6237.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_dossier.py
opengever/base/tests/test_default_values_for_types.py
opengever/ogds/base/sources.py
opengever/testing/integration_test_case.py

With the recently introduced separation between userid and username, certain API endpoints now expect the userid to be specified. Since external applications such as the RIS have no knowledge of the GEVER internal userid, they must be adapted so that they can also handle the username.  This PR introduces this support for the dossier responsible field.
For [CA-6237]
- API change:

Also support usernames for the responsible field in dossier API.

---

README.rst
opengever/api/tests/test_webactions.py
opengever/testing/fixtures.py
opengever/webactions/tests/test_manage_webactions_view.py
opengever/webactions/tests/test_webactions_provider.py

Tests: Use different userid for fixture user `webaction_manager`
Corresponding test fixes in gever-ui: https://github.com/4teamwork/gever-ui/pull/2634

Tests: Use different userid for fixture user webaction_manager

---

README.rst
opengever/base/tests/test_default_values_for_types.py
opengever/testing/fixtures.py

Tests: Use different userid for fixture user `meeting_user`
Corresponding test fixes in gever-ui: https://github.com/4teamwork/gever-ui/issues/2636

Tests: Use different userid for fixture user meeting_user

---

changes/CA-6302.feature
opengever/core/upgrades/20231120152734_add_disposition_setting_attach_csv_reports/registry.xml
opengever/core/upgrades/20231120152734_add_disposition_setting_attach_csv_reports/upgrade.py
opengever/disposition/ech0160/model/document.py
opengever/disposition/ech0160/model/dossier.py
opengever/disposition/ech0160/model/file.py
opengever/disposition/ech0160/model/folder.py
opengever/disposition/ech0160/sippackage.py
opengever/disposition/interfaces.py
opengever/disposition/reports.py
opengever/disposition/tests/test_sippackage.py

LTAs from certain customers cannot automatically process the metadata.xml of the SIP package. In this case, we therefore extend the SIP package with additional csv exports. A list of all dossiers (`dossiers.csv`), a list of all files (`items.csv`) and a list with the custom fields for each dossier type.
This feature is disabled per default. The column names are based on the ech0160 spec and are therefore in german.
For [CA-6302]
[CA-6302]: https://4teamwork.atlassian.net/browse/CA-6302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend dispositon SIP package with csv exports.

---

changes/CA-6237-4.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/ogdsuser.py
opengever/api/tests/test_ogdsuser.py
opengever/ogds/base/browser/templates/userdetails_table.pt
opengever/ogds/base/browser/userdetails.py
opengever/ogds/base/tests/test_userdetails.py
opengever/ogds/models/service.py

The @user-details endpoint and the user-details view can now be called also with username as request-parameter, not just userid.
Besides that, the userdetails view uses now the group.label() in the group listing.
For [CA-6237]
- API change:

Add username fallback for @ogds-users endpoint and user-details view.

---

changes/CA-6237-2.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_task.py
opengever/base/tests/test_default_values_for_types.py
opengever/ogds/base/sources.py

Same as I already did for dossiers (#7831), we need also for task creation and modification.
With the recently introduced separation between userid and username, certain API endpoints now expect the userid to be specified. Since external applications such as the RIS have no knowledge of the GEVER internal userid, they must be adapted so that they can also handle the username.
For [CA-6237]
- API change:

Also support usernames for the responsible and issuer field in tasks API.

---

changes/CA-6354.bugfix
opengever/task/__init__.py
opengever/task/tests/test_localroles.py

This PR extends the list of `FINAL_TRANSITIONS` with forwarding transitions. This fixes an issue where temporary assigned inbox permissions have not been revoked after the forwarding have been closed.
For [CA-6354]
- API change:
- If breaking:
- Bug fixed:
[CA-6354]: https://4teamwork.atlassian.net/browse/CA-6354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Properly revoke temporary inbox permissions when working with forwardings.

---

changes/CA-6499.bugfix
opengever/api/tests/test_templatefolder.py
opengever/dossier/command.py
opengever/dossier/dossiertemplate/form.py
opengever/dossier/tests/test_command.py

This PR fixes an issue introduced in: https://github.com/4teamwork/opengever.core/commit/e576c233f
If the feature `grant_role_manager_to_responsible` is activated and the user creates a new dossier from template containing subdossiers, the local-roles of the subdossiers will be broken.
It's because the local-roles from the feature will be set based on the current responsible, after the new subdossier have been created. But at this time, the responsible is not yet set. The responsible of the subdossier will be set after the creation process in a separate assignment statement. 
```
(Pdb) self.context.get_local_roles()
((None, ('Role Manager',)),))
```
This PR fixes the issue by extending the `CreateDossierFromTemplateCommand` with `kwargs` will then be passed to the create command as …

Fixes the sharing tab for subdossiers created by a dossier from template

---

opengever/api/tests/test_templatefolder.py

In the meantime the id of the regular_user has changed and therefore the test is failing.

Fix recently introduced templatefolder test.

---

changes/CA-6418.other
docker/httpd/README.md
docker/httpd/httpd-foreground

Generating an Apache config file for multi-tenant setups out of environment variables is difficult.
Instead we allow to skip config file generation to allow bind mounting a config file.
For [CA-6418](https://4teamwork.atlassian.net/browse/CA-6418)
[CA-6418]: https://4teamwork.atlassian.net/browse/CA-6418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add option to skip generation of httpd.conf

---

changes/CA-6237-1.other
changes/CA-6237-3.other

Seems they got lost during rebasing...

Add missing changelog entries from #7817

---

changes/CA-6354.bugfix
opengever/task/__init__.py
opengever/task/tests/test_localroles.py

This PR  reverts commit 870684d4391b802dde8100dacfdf34cad06902a4 from the PR: #7818 
The change introduced an issue, where the "@assign-to-dossier" endpoint is broken.
The user loses the necessary permissions after the forwarding has been closed. We then create the successor-task in a after transition hook wich will fail.
We'll fix it in an upcoming PR.
For [CA-6354]
- API change:
- If breaking:
- Bug fixed:
[CA-6354]: https://4teamwork.atlassian.net/browse/CA-6354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

Revert "Properly revoke temporary inbox permissions when working with forwardings."

---

changes/CA-6542.bugfix
opengever/base/browser/reporting_view.py
opengever/document/browser/report.py
opengever/document/tests/test_reporter.py
opengever/dossier/browser/report.py
opengever/dossier/tests/test_reporter.py
opengever/meeting/browser/report.py
opengever/meeting/tests/test_reporter.py

The current implementation which sorts using the supplied path sorting, was massively inperformant and led to Solr crashes. Instead we fetch the the current sorting of the listing and use this.
This drops the sorting support for the classic UI, as discussed at the daily that is not really a problem.
For [CA-6524]
[CA-6524]: https://4teamwork.atlassian.net/browse/CA-6524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve reporting view performance for path based queries.

---

changes/CA-5913.other
opengever/base/service.py
opengever/base/tests/test_api.py

Include the `bumblebee_checksum` in the document status. This allows us to reload the document preview on the frontend if the checksum has been changed.
For [CA-5913]
- API change:
- If breaking:
- Bug fixed:
[CA-5913]: https://4teamwork.atlassian.net/browse/CA-5913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include bumblebee_checksum in document status.

---

changes/CA-6490.feature
changes/CA-6490.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/schema/globalsources.py
opengever/api/tests/test_globalsources.py
opengever/base/addressblock/tests/test_extraction.py
opengever/contact/sources.py
opengever/kub/client.py
opengever/kub/sources.py
opengever/kub/testing.py
opengever/kub/tests/test_kub_client.py
opengever/kub/tests/test_kub_contact_source.py

This PR adds a new `@globalsource` called `all_contacts` wich will return all active and inactive contacts.
We use this source to display a performant participation filter in the frontend.
⚠️ Requires KUB >= `2023.18.0` (https://github.com/4teamwork/kub/pull/279)
ℹ️ tested on spd ag test deployment.
For [CA-6490]
- API change:
- If breaking:
- Bug fixed:
[HG-4270]: https://4teamwork.atlassian.net/browse/HG-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Add `all_contacts` global source

---

changes/CA-6237-6.other
opengever/ogds/models/service.py
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

With the recently introduced differentiation of userid/usernames and group/groupnames the sharing API should support also setting local roles by the username and groupname. So that the API behaves in the same way as before.
For [CA-6237]

Support usernames and groupnames in the sharing API.

---

changes/CA-6354.bugfix
opengever/api/tests/test_assign_to_dossier.py
opengever/inbox/transition.py
opengever/task/__init__.py
opengever/task/tests/test_localroles.py

This PR extends the list of `FINAL_TRANSITIONS` with forwarding transitions. This fixes an issue where temporary assigned inbox permissions have not been revoked after the forwarding have been closed.
⚠️ adding the `forwarding-transition-assign-to-dossier` transition to the `FINAL_TRANSITIONS` will not work. We need access to the forwarding documents in the after transition hook for the successor task.
I first tried to refactor out the successor-task creation and move it to the `@assign-to-dossier` endpoint. This was already quite hard since we have the whole schema extraction and validation in the `TransitionExtextender` class. I also needed to refactor the old UI:
- https://github.com/4teamwork/opengever.core/blob/master/opengever/task/browser/accept/newdossier.py#L281
- …

Forwarding permissions fix

---

changes/CA-6493.bugfix
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py

This PR fixes an issue where localroles of dossier tempaltes have only been overtaken from subdossiers, but not for the main dossier.
The `CreateDossierFromTemplateCommand` already respect local roles and role inheritance: https://github.com/4teamwork/opengever.core/blob/376083ec4bdff0b69652c0681547750e4d6e150c/opengever/dossier/command.py#L114 but the command will only be used for subdossiers.
This fix updates the api-endpoint to also respect the local roles and role inheritance on the main dossier itself.
For [CA-6493]
- API change:
- If breaking:
- Bug fixed:
- Further improvements …

Properly set predefined dossier template local roles on dossiers creating by templates

---

opengever/api/tests/test_templatefolder.py

These tests were executed against an old base of `master`, where the fixture user's user ID was not renamed from `kathi.barfuss` to `regular_user` yet.
That's why the PR on GitHub passed at one point, but once merged into the current master where the rename already happened, they fail.

Fix tests on master

---

development.cfg
sources.cfg

- No longer extend from `4teamwork-psc.cfg`. Also removes `isotoma.buildout.basicauth` extension which is no longer needed.
- Add `find-links` for each package as Gitlab's simple index consists of subpages that aren't processed by setuptools.

Fix find-links for Gitlab packages

---

changes/HG-4035.feature
opengever/base/handlers.py
opengever/base/indexes.py
opengever/base/tests/test_contents_reordered_handling.py
opengever/base/tests/test_indexers.py
opengever/document/handlers.py
opengever/dossier/tests/test_move_items.py

With this PR we enable indexing the ordering of documents/mails. These changes make sure that the `getObjPositionInParent` is indexed in Solr for newly added and reordered documents/mails.
These changes are motivated by the following requirements in RI(S)PV:
- The customers want to define an order for documents of an agenda item (a current SPV feature)
- The customers want to define an order for documents of a meeting
See  [HG-4035](https://4teamwork.atlassian.net/browse/HG-4035) for more details.
An agenda item in RIS corresponds to a dossier in GEVER. RIS unfortunately does not have knowledge of all documents of an agenda item as this information is figured out on the fly via GEVER. Thus after some discussion with @phgross a while ago and @buchi some days ago we decided to try to use …

Make documents/mails in dossiers orderable by API clients

---

changes/CA-6450.bugfix
opengever/task/task.py
opengever/task/tests/test_task_from_template.py
opengever/task/transition.py

Nested task templates: Also pass docs to subtasks that get started:
This will make sure that if a sequential task is started because it is the next one in line, and the user selected `pass_documents_to_next_task`, the documents will be passed (i.e. set as relatedItems) not just to that next task, but also to any subtasks that get started if the next task happens to be a task template.
So in short:
If the user selects `pass_documents_to_next_task`, the documents will always be passed to exactly the same tasks that automatically get started.
For [CA-6450](https://4teamwork.atlassian.net/browse/CA-6450)
[CA-6450]: https://4teamwork.atlassian.net/browse/CA-6450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Nested task templates: Also pass docs to subtasks that get started

---

changes/CA-6605.bugfix
opengever/trash/tests/test_trash.py
opengever/trash/trash.py

The current implementation recursively checks if all contained items of a workspace folder can be trashed.
This obviously gets slower, the more items a workspace folder contains and is already unusable if it contains just a few items.
Now, we only check if the workspace folder itself can be trashed and do the check for contained items while performing the trash operation.
For [CA-6605](https://4teamwork.atlassian.net/browse/CA-6605)
[CA-6605]: https://4teamwork.atlassian.net/browse/CA-6605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix performance when checking if a workspace folder can be trashed

---

changes/GH-7875.bugfix
docker/core/etc/site.zcml

Fix Docker image: remove ZCML include of ftw.tika in Docker image

---

changes/CA-6552.bugfix
opengever/api/tests/test_listing.py
opengever/api/tests/test_solrsearch.py
opengever/base/handlers.py
opengever/core/upgrade.py
opengever/core/upgrades/20240119135606_touch_modified_timestamp_for_objects_where_changed_is_newer/upgrade.py

Also update `modified` when updating `changed` timestamp:
We rely on `modified` in `solr-sync` to determine which items are out of sync (present on both sides, but with potential difference in metadata contents). However, `modified` gets updated not nearly as consistently as we thought: For example, triggering a workflow transition will not update `modified`.
Therefore, we always update `modified` when we update the higher-level `changed` timestamp. This way, we should at least catch the most important user facing changes to objects.
This includes an upgrade-step which will touch `modified` for all items in the catalog where `changed` is newer than `modified`. It will defer the reindexing of `modified` (and all metadata) to a nightly job, and will only reindex `modified` in ZCatalog, but …

Also update `modified` when updating `changed` 

---

changes/CA-6152.feature
docs/public/dev-manual/api/api_changelog.rst
docs/schema-dumps/opengever.workspace.meetingagendaitem.schema.json
opengever/base/schemadump/config.py
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/tests/test_workspace_meeting_agenda_item.py
opengever/workspace/workspace_meeting_agenda_item.py

This PR adds a new field for workspace agenda items: `related_todo_list`
It allows us to display todos within a workspace agenda item.
For [CA-6152]
- API change:
- If breaking:
- Bug fixed:
[CA-6152]: https://4teamwork.atlassian.net/browse/CA-6152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add related todo list field to workspace agenda items.

---

changes/CA-6649.bugfix
opengever/api/tests/test_globalsources.py
opengever/kub/client.py
opengever/kub/testing.py

This PR fixes an issue introduced in: https://github.com/4teamwork/opengever.core/pull/7863
Search by umlauts was no longer possible.
Sentry: https://sentry.4teamwork.ch/organizations/sentry/issues/123946/?project=17&query=release%3A2024.1.0&referrer=release-issue-stream
For [CA-6649]
- API change:
- If breaking:
- Bug fixed:
[CA-6649]: https://4teamwork.atlassian.net/browse/CA-6649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix unicode error in kub search

---

changes/CA-6577.other
opengever/base/browser/reporting_view.py

Reporting view: Use filter query to filter by paths:
Compared to regular queries, a filter query should be chacheable in Solr and result in lower memory usage.
For [CA-6577](https://4teamwork.atlassian.net/browse/CA-6577)
[CA-6577]: https://4teamwork.atlassian.net/browse/CA-6577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reporting view: Use filter query to filter by paths

---

changes/CA-6237a.other
development.cfg
docker-compose.yml
opengever/examplecontent/profiles/default-ska/unit_creation/org_units.json
opengever/examplecontent/profiles/default/unit_creation/org_units.json
opengever/ogds/base/sync/ogds_updater.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/units/unit_creation/org_units.json.bob
opengever/setup/creation/orgunit.py

If an ogds-sync url is configured, the service is used for syncing instead of the built-in syncer.
Configure url for local development.
Fixes initial setup of local development as the ogds-sync service is also used for setup.
ogds-sync >= 2024.1.0 is required.
Use legacy ogds-sync profile for development. As long as we use the ldap plugin for development, we have to stick with the legacy sync (username=userid).

Use ogds-sync service for syncing users and groups

---

changes/CA-6592.feature
opengever/api/tests/test_vocabularies.py
opengever/ogds/base/configure.zcml
opengever/ogds/base/vocabularies.py
opengever/ogds/models/service.py

This PR adds a new global vocabulary: `opengever.ogds.base.all_other_admin_units`
The vocabulary lists all enabled, visible admin unit excluding the current. We use this vocabulary for the `dossier-transfer`-Feature.
For [CA-6592]
- API change:
- If breaking:
- Bug fixed:
[CA-6592]: https://4teamwork.atlassian.net/browse/CA-6592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new vocabulary: opengever.ogds.base.all_other_admin_units

---

docker-compose.yml

Remove default network from compose file:
This network leads to `"Pool overlaps with other one on this address space"` when working with several GEVER checkouts locally, because the network is left over unless the deployments are always stopped with `docker-compose down`.
And it was only intended to prevent docker from allocating huge network blocks, which can be prevented by by adding something like this to the docker daemon cfg:
```
"default-address-pools": [
{
"base": "172.17.0.0/12",
"size": 24
}
],
```

Remove default network from compose file:

---

changes/HG-4035-1.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/tests/test_document.py
opengever/api/tests/test_mail.py

With this PR we enable serializing`getObjPositionInParent` for documents/mails in REST API responses. It is a follow-up for https://github.com/4teamwork/opengever.core/pull/7869 which enabled indexing in Solr.
These changes are motivated by the following requirements in RI(S)PV:
- After creating content in GEVER we would like to know the position of the new object directly from the `POST` response
- Without this change we would have to make a 2nd request to fetch the object position
I've chosen to re-use the default plone indexer for serialization. IMO this is fine but i can of course use the adapter that is used by the indexer directly if that is preferred.
_Dear reviewer(s) please have a good and thorough look here, I feel very rusty with this codebase and errors are very likely!_ …

Add getObjPositionInParent to serialization for documents/mails

---

changes/CA-6592-2.feature
opengever/api/tests/test_vocabularies.py
opengever/ogds/base/configure.zcml
opengever/ogds/base/vocabularies.py

Follow-Up for #7886 
We'll use the `opengever.ogds.base.all_admin_units` vocabulary for e2e testing.
For [CA-6592]
- API change:
- If breaking:
- Bug fixed:
[CA-6592]: https://4teamwork.atlassian.net/browse/CA-6592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new vocabulary: opengever.ogds.base.all_admin_units

---

changes/CA-6552.bugfix
opengever/core/upgrades/20240119135606_touch_modified_timestamp_for_objects_where_changed_is_newer/upgrade.py

Fix upgrade step that touches modified timestamp.
Avoids the upgrade step failing when there's `DateTime`s in the catalog's `modified` that are naive, instead of (as usual) TZ aware (as discovered on ftw GEVER).
For [CA-6552](https://4teamwork.atlassian.net/browse/CA-6552)
[CA-6552]: https://4teamwork.atlassian.net/browse/CA-6552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix upgrade step that touches modified timestamp.

---

changes/GH-7889.other
docker/core/Dockerfile
docker/core/docker-entrypoint.sh
docker/core/entrypoint.d/create_zope_conf.py
docker/core/etc/site.zcml
docker/core/requirements-core.txt
opengever/core/tests/test_versions.py

The previous base image was based on Alpine 3.14 which is EOL.
The new base image comes with various improvements described in https://github.com/4teamwork/plone-docker/pull/1
PostgreSQL 15.5 (libpq) and OpenLDAP 2.6.5 (libldap) provided by Alpine 3.18 are newer versions than officially supported by psycopg2 2.8.6 and python-ldap 2.4.45 but seem to work so far.
Bump cryptography to version 3.3.2 to include fix for CVE-2020-36242. We do not bump it in buildout `versions.cfg` because it requires OpenSSL 1.1 which is not available on CentOS 7.

Use Plone 4.3 image based on Alpine 3.18

---

changes/CA-6435.bugfix
opengever/bundle/sections/map_principal_names_to_ids.py
opengever/bundle/tests/test_section_map_principal_names_to_ids.py

The `map-principal-names-to-ids` section was called after the `map-local-roles` section. This can't work because `map-local-roles` transforms `_permissions` data to `_ac_local_roles`.
For [CA-6435](https://4teamwork.atlassian.net/browse/CA-6435)
[CA-6435]: https://4teamwork.atlassian.net/browse/CA-6435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix mapping of names to principal ids in bundle import

---

changes/CA-6482.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/workspace/todos.rst
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/tests/test_todo.py
opengever/workspace/todo.py

With this PR, we add a new text field for external references to the todo's of the teamroom. 
The aim of the change is to be able to provide links to external resources in the UI.
This leads to an extension of the attributes of the todo schema with a text field with the name external_reference.
For [CA-6482]
- API change:
[CA-6482]: https://4teamwork.atlassian.net/browse/CA-6482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new field external_reference to teamroom todo 

---

changes/CA-6496.other
opengever/bumblebee/service.py
opengever/bumblebee/tests/test_document_adapter.py

This PR extends the check for convertibility to PDF. If a file does not have a file extension, it will not be allowed for conversion via Bumblebee. 
Without this check, the file is sent for conversion but not processed and remains in the pickup folder. This must be avoided.
For [CA-6496]
[CA-6496]: https://4teamwork.atlassian.net/browse/CA-6496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend is_convertable in bumblebee service

---

changes/CA-6292.other
opengever/officeconnector/mimetypes.py

ODS documents can be opened with OpenOffice, which is supported by OfficeConnector.
For [CA-6292]
[CA-6292]: https://4teamwork.atlassian.net/browse/CA-6292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ODS to document types editable with OfficeConnector.

---

changes/CA-5855.feature
opengever/api/dossier.py
opengever/api/tests/test_dossier.py

In this PR we extend the context of the dossier with the information about the discrepancy between the completion of the dossier and its planned dependent processing steps in order to be able to inform the user about this in the UI. 
For [CA-5855]
[CA-5855]: https://4teamwork.atlassian.net/browse/CA-5855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add info about upcoming nightly processing

---

changes/CA-6435.bugfix
docker/core/Dockerfile
opengever/ogds/base/sync/ogds_updater.py

Create symlink and use real path for the rotating file handler in order to get the correct base directory when rotating log.
For [CA-6435](https://4teamwork.atlassian.net/browse/CA-6435)
[CA-6435]: https://4teamwork.atlassian.net/browse/CA-6435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix OGDS sync log in Docker container

---

changes/CA-6435.other
docker/core/docker-entrypoint.sh
docker/core/entrypoint.d/create_package_includes.py

This allows us to use existing policies with Docker and easier customization by bind mounting a package into the container instead of single files.
To include a package, it needs to be bind mounted into the container and the environment variable `ZCML_PACKAGE_INCLUDES` needs to be set to the package name. Multiple package names can be specified separated by a space.
Example snippet from opengever.dockerexample:
```
services:
ogcore:
volumes:
- ./opengever/dockerexample:/app/opengever/dockerexample:ro
environment:
- ZCML_PACKAGE_INCLUDES=opengever.dockerexample.fd
```
For [CA-6435](https://4teamwork.atlassian.net/browse/CA-6435)
[CA-6435]: https://4teamwork.atlassian.net/browse/CA-6435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for ZCML package includes in Docker container

---

changes/CA-6451.bugfix
opengever/dossier/base.py
opengever/dossier/tests/test_base.py

Don't let rejected tasks prevent the dossier from being closed.
Until this change, rejected (sub) tasks prevented the dossier from being closed, even though the main task containing the subtask could be closed. This inconsistency was because
- the [check for closing a task](https://github.com/4teamwork/opengever.core/blob/5a7decc9af7f06caab1a89a6a6091fe8fae87d51/opengever/task/browser/transitioncontroller.py#L730) uses [FINSHED_TASK_STATES](https://github.com/4teamwork/opengever.core/blob/5a7decc9af7f06caab1a89a6a6091fe8fae87d51/opengever/task/__init__.py#L23-L27) to make sure all tasks are "finished"
- whereas the [check for resolving a dossier](https://github.com/4teamwork/opengever.core/blob/5a7decc9af7f06caab1a89a6a6091fe8fae87d51/opengever/dossier/base.py#L317-L322) uses …

Don't let rejected tasks prevent the dossier from being closed.

---

changes/CA-5855.bugfix
opengever/dossier/reactivate.py
opengever/dossier/tests/test_reactivate.py

This PR handles the processing of the pending job flag when a dossier is reopened/reactivated
For [CA-5855]
[CA-5855]: https://4teamwork.atlassian.net/browse/CA-5855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle pending jobs flag when reactivate dossier

---

docker/solr/Dockerfile
versions.cfg

Includes fixes for CVE-2023-50291, CVE-2023-50292, CVE-2023-50298, CVE-2023-50386 and CVE-2022-39135.
For [CA-XXXX]

Bump Solr to version 8.11.3

---

changes/CA-6435a.bugfix
changes/CA-6435b.bugfix
changes/CA-6435c.other
changes/CA-6435d.other
docker/core/Dockerfile
opengever/bundle/console.py
opengever/setup/serviceuser.py

- Fix argument parsing of `create_service_user` command
- Fix argument parsing of `import` command
- Change log location of `migration.log`
- Make `/app/var/log` and `/app/var/instance` writeable inside Docker container
For [CA-6435](https://4teamwork.atlassian.net/browse/CA-6435)
[CA-6435]: https://4teamwork.atlassian.net/browse/CA-6435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix console scripts when run with Docker

---

changes/CA-6417.feature
docs/public/dev-manual/api/api_changelog.rst
docs/schema-dumps/opengever.workspace.workspace.schema.json
opengever/api/document.py
opengever/api/tests/test_document.py
opengever/bundle/schemas/workspaces.schema.json
opengever/document/actions.py
opengever/document/fileactions.py
opengever/document/tests/test_actions.py
opengever/mail/actions.py
opengever/workspace/actions.py
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/tests/test_actions.py
opengever/workspace/utils.py
opengever/workspace/workspace.py

This PR adds the option of restricting the action options for guests to the workspace. 
The aim of this is to ensure that guests can only view documents in the team room at this time and to make it as difficult as possible for them to print or download content. These restrictions relate primarily to the new UI.
For [CA-6417]
- API change:
[CA-6417]: https://4teamwork.atlassian.net/browse/CA-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ability to restrict workspace mails and documents actions for guests 

---

changes/CA-6790.other
solr-conf/data-config.xml

Use a cursor for pagination instead of paging.
It turns out Solr is very inefficient when using deep paging. This has the effect that reindexing using a data import handler gets slower and slower the more documents have been processed. By using a cursor, the reindexing speed remains the same independant of the retrieved page. See also: https://solr.apache.org/guide/8_11/pagination-of-results.html#performance-problems-with-deep-paging
Comparison reindexing 2.2 M documents:
Using cursors:
Indexing completed. Added/Updated: 2249657 documents. Deleted 0 documents. (Duration: 6h 13m 50s)
Requests: 0 , Fetched: 2,249,657 100/s, Skipped: 0 , Processed: 2,249,657 100/s
Started: about 7 hours ago
Using paging (aborted after 12h):
Indexing since 12:3:9.704
Requests: 0 , Fetched: 1,486,650 34/s, …

Improve performance of Solr reindexing using DIH

---

docker-compose.yml

In ogds-sync 2024.2.0 the OpenLDAP profile was renamed and a new profile was added for new style mapping.
It's now easy to switch between legacy and new style mapping by removing or adding the Legacy suffix.

Use OpenLDAPLegacy profile as default for ogds-sync

---

changes/CA-6417.other
opengever/document/actions.py
opengever/document/tests/test_actions.py
opengever/mail/tests/test_actions.py
opengever/workspace/actions.py
opengever/workspace/tests/test_actions.py

Follow-up PR of: Add ability to restrict workspace mails and documents actions for guests #7909
For [CA-6417]
[CA-6417]: https://4teamwork.atlassian.net/browse/CA-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend the restriction of possible actions by guests

---

changes/CA-6863.other
changes/CA-6863a.other
opengever/setup/zopectl.py
setup.py

Allows easy setup and upgrades mainly when run with Docker, but also works with Buildout deployments.
The `setup` command creates a new Plone site (GEVER deployment).
It can be run with `docker compose run --rm ogcore setup` or `bin/instance setup`.
An optional OGG bundle can be provided which is imported automatically:
`docker compose run --rm -v ./example.oggbundle:/oggbundle ogcore setup`
The following optional arguments are supported:
```
--deployment DEPLOYMENT
Name of the deployment profile (default: Policyless Deployment)
--user USER           Name of the user used for creating the deployment (default: zopemaster)
--purge-ogds          Purge OGDS before creating new deployment
--purge-solr          Purge Solr before creating new deployment
--purge-site          Purge Plone site …
```

Setup and update commands

---

changes/CA-1852.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/config.py
opengever/api/tests/test_config.py
opengever/base/configure.zcml
opengever/base/systemmessages/api.zcml
opengever/base/systemmessages/api/base.py
opengever/base/systemmessages/api/delete.py
opengever/base/systemmessages/api/get.py
opengever/base/systemmessages/api/patch.py
opengever/base/systemmessages/api/post.py
opengever/base/systemmessages/api/schemas.py
opengever/base/systemmessages/api/serializers.py
opengever/base/systemmessages/configure.zcml
opengever/base/systemmessages/models.py
opengever/base/systemmessages/tests/test_api_delete.py
opengever/base/systemmessages/tests/test_api_get.py
opengever/base/systemmessages/tests/test_api_post.py
opengever/base/systemmessages/tests/test_builder.py
opengever/base/systemmessages/tests/test_model.py
opengever/base/systemmessages/tests/test_patch.py
opengever/base/systemmessages/tests/test_serializer.py
opengever/base/tests/test_database_table_declarations.py
opengever/core/upgrades/20240321115949_add_system_messages_sql_table/upgrade.py
opengever/testing/builders/sql.py

Provide widely System Message `CRUD `operations. Only the `manager `has access to the endpoints. The endpoints are defined as follows:
**GET**: This will fetch a list of all system messages or a single record when calling the URL with a system message `id `parameter. The endpoint will also deal with filtering. We can filter by `active`, which will return all active messages, or by `admin_unit_only`, which will return only messages to the `authenticated `user.
**POST**: Create a new System message.
**PATCH**: Update a record based on the record `id` parameter.
**DELETE**: Remove a record based on the record `id` parameter..
Additionally, we provide an additional data with the key `system_messages `on the` @config` endpoint.
For [CA-1852](https://4teamwork.atlassian.net/browse/CA-1852) …

Provide System Messages implemenation

---

changes/CA-6417a.other
changes/CA-6417b.other
changes/CA-6417c.other
opengever/base/browser/configure.zcml
opengever/base/browser/errors.py
opengever/base/browser/zipexport.py
opengever/document/browser/download.py
opengever/document/tests/test_download.py
opengever/workspace/tests/test_zipexport.py

Hiding download actions is not sufficient, as documents still can be downloaded by URL-guessing.
Protects download and zip export.
I've also disabled rendering of the error page for `BadRequest` and `Forbidden` errors.
The error page makes look these errors like server-side errors. Further it's quite expensive to render and doesn't provide any useful information for these type of errors. A plain text error message is now displayed instead.
For [CA-6417](https://4teamwork.atlassian.net/browse/CA-6417)
[CA-6417]: https://4teamwork.atlassian.net/browse/CA-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disallow download in restricted workspaces for guests

---

docker/testserver/bin/testserver
docker/testserver/docker-entrypoint.sh

This changed when upgraded base image to Alpine 3.18.

Fix path of python interpreter

---

changes/CA-6163.bugfix
opengever/api/globalindex.py

We used to pass an ISO formatted date string to SQLAlchemy when constructing the BETWEEN clause. Apparently this datetime string format is not appropriate for Oracle, and it complains with
```
ORA-01861: literal does not match format string
```
Parsing the date strings submitted by the frontend into Python dates and passing those instead lets SQLAlchemy format them correctly for Oracle.
For [CA-6163](https://4teamwork.atlassian.net/browse/CA-6163)
[CA-6163]: https://4teamwork.atlassian.net/browse/CA-6163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix OGDS listing date filters to also work on Oracle:

---

changes/CA-6237.bugfix
opengever/wopi/browser/wopi.py
opengever/wopi/tests/test_edit.py
opengever/wopi/tests/test_validation.py
opengever/wopi/tests/test_wopi.py

Fixes Office Online support with setups where userid and username are not equal.

Fix lookup of user in WOPI operations

---

changes/CA-6417.other
changes/CA-6417a.other
changes/CA-6417c.other
opengever/api/copy_.py
opengever/api/save_document_as_pdf.py
opengever/api/tests/test_copy_paste.py
opengever/api/tests/test_mail.py
opengever/api/tests/test_save_document_as_pdf.py
opengever/bumblebee/browser/open_pdf.py
opengever/document/actions.py
opengever/document/tests/test_actions.py
opengever/mail/browser/attachment.py
opengever/mail/tests/test_actions.py
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api_dossier_attach.py

This is a follow-up PR for #7909 
The PR disables some more ui-actions and protects endpoints for guests within a restricted workspace.
For [TI-16]
[TI-16]: https://4teamwork.atlassian.net/browse/TI-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Restricted workspaces

---

opengever/document/actions.py
opengever/document/tests/test_actions.py

This PR removes the `Download as pdf` action for guests within a restricted workspace.
This is a follow-up PR for #7931 
We had tests for this case, but unfortunately, the tested document was nod a bumblebeeable document, thus the action was disabled by default in the tests. I split up this PR into two commits to make it clear what happens.
For [CA-6417]

Remove save document as pdf action for guests in restricted workspaces

---

changes/TI-5a.other
opengever/dossiertransfer/api/base.py
opengever/dossiertransfer/tests/test_api_get.py

Allow Manager to list or fetch any dossier transfer.
This is to ease development as well as debugging / support later in production.
For [TI-5](https://4teamwork.atlassian.net/browse/TI-5)
[TI-5]: https://4teamwork.atlassian.net/browse/TI-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow Manager to list or fetch any dossier transfer.

---

changes/TI-71.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py

The ris base url is used in the gever-ui to open the ris to create proposals.
For [TI-71]
- API change:
[TI-71]: https://4teamwork.atlassian.net/browse/TI-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ris base url to config endpoint

---

changes/CA-6591.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dossier_transfers.rst
opengever/api/document.py
opengever/base/subscribers.py
opengever/dossiertransfer/api/base.py
opengever/dossiertransfer/api/get.py
opengever/dossiertransfer/api/post.py
opengever/dossiertransfer/api/serializers.py
opengever/dossiertransfer/model.py
opengever/dossiertransfer/tests/test_api_get.py
opengever/dossiertransfer/tests/test_token.py
opengever/dossiertransfer/token.py
opengever/testing/builders/sql.py

This adds a "full content serialization" mode to the `GET /@dossier-transfers/<id>` endpoint.
The `@perform-dossier-transfer` endpoint will use this (in a server-to-server request) to retrieve all the actual content data when performing a transfer.
When invoked with the `?full_content=1` query string parameter, the endpoint also adds serialization of the transfer contents to its response:
```http
GET /@dossier-transfers/42?full_content=1`
```
```json
{
"@id": "http://localhost:8080/fd/@dossier-transfers/42",
"@type": "virtual.ogds.dossiertransfer",
"...": "...",
"content": {
"dossiers": ["..."],
"documents": ["..."],
"contacts": {"..."}
},
}
```
In this mode,
- **Anonymous** requests are accepted, as long as the contain a **valid JWT token** that matches the respective transfer
- The JWT …

Add full content serialization mode for GET /@dossier-transfers

---

changes/TI-89.other
opengever/api/templatefolder.py
opengever/api/tests/test_templatefolder.py
opengever/dossier/command.py
opengever/dossier/tests/test_command.py

Ensure that document keywords are added to documents generated from the template.
For [TI-89](https://4teamwork.atlassian.net/browse/TI-89)
- API change:
- If breaking:
- Bug fixed:
[TI-89]: https://4teamwork.atlassian.net/browse/TI-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include document keywords for documents created from the template

---

changes/TI-161.feature
docker-compose.yml
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dossier_transfers.rst
opengever/dossiertransfer/api.zcml
opengever/dossiertransfer/api/perform.py
opengever/dossiertransfer/api/schemas.py
opengever/dossiertransfer/tests/test_api_perform.py
opengever/kub/client.py

Performs a dossier transfer at the given repository folder:
- First all documents are fetched and stored in a temporary directory.
- Then all contacts referenced in participations are created if they don't exist yet
- At last the dossier, its subdossiers and documents are created
Checking for existing contacts is done by comparing the `third_party_id`.
If the source doesn't have a `third_party_id`, its id is used instead.
If the creation of dossiers or documents fails, newly created contacts are kept, as they are created externaly in KuB.
For [TI-161](https://4teamwork.atlassian.net/browse/TI-161)
- API change:
[TI-161]: https://4teamwork.atlassian.net/browse/TI-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dossier transfer create content

---

opengever/dossiertransfer/api/perform.py
opengever/dossiertransfer/tests/test_api_perform.py

Creating content with unknown custom properties results in a validation error. Therefore we need to strip those before creating the content.
For [TI-161](https://4teamwork.atlassian.net/browse/TI-161)
[TI-161]: https://4teamwork.atlassian.net/browse/TI-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Strip unknown custom properties

---

changes/TI-131.other
opengever/repository/browser/excel_export.py
opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/en/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/opengever.repository.pot
opengever/repository/tests/test_excel_export.py

Improves the repository root Excel export feature by adding the folder UID and relative path to each entry
For [TI-131](https://4teamwork.atlassian.net/browse/TI-131)
**before**:
**After**:
- API change:
- If breaking:
- Bug fixed:
[TI-131]: https://4teamwork.atlassian.net/browse/TI-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve Repository Root Excel Export

---

opengever/dossiertransfer/api/perform.py
opengever/dossiertransfer/tests/test_api_perform.py

Two more fixes:
- Assignment slots can have no definition
- The `custom_properties` property may have a value of `None`
For [TI-161](https://4teamwork.atlassian.net/browse/TI-161)
[TI-161]: https://4teamwork.atlassian.net/browse/TI-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix handling of custom properties

---

changes/TI-144.other
opengever/activity/tests/test_mail.py
opengever/api/tests/test_notifications.py
opengever/task/activities.py
opengever/task/tests/test_activities.py

Provide the full title instead of a cropped title in task activities.
**Before**:
`u'Vertr\xe4ge mit der kantonalen... - Vertragsentwurf \xdcberpr\xfcfen'`
**After**:
`u'Vertr\xe4ge mit der kantonalen Finanzverwaltung - Vertragsentwurf \xdcberpr\xfcfen'`
**UI App notification**:
For [TI-144](https://4teamwork.atlassian.net/browse/TI-144)
[TI-144]: https://4teamwork.atlassian.net/browse/TI-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove cropped title from task activity

---

changes/TI-317.other
opengever/api/system_information.py
opengever/api/tests/test_system_information.py

Provide Docproperty information in `@system-information` view
For [TI-317](https://4teamwork.atlassian.net/browse/TI-317)
[TI-317]: https://4teamwork.atlassian.net/browse/TI-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Inhance system information view with Docproperties

---

opengever/core/upgrades/20240125083502_add_dossier_transfers_sql_table/upgrade.py
opengever/dossiertransfer/api/get.py
opengever/dossiertransfer/api/perform.py
opengever/dossiertransfer/api/serializers.py
opengever/dossiertransfer/tests/test_api_get.py
opengever/dossiertransfer/tests/test_api_perform.py
opengever/kub/client.py

This PR adds some fixes for the dossier transfer:
- Properly handle ogds users as dossier participants when performing a dossier transfer
- Fix transfering emails
- Fix upgradestep
- Fix creation of people with memberships and/or username (remove it)
- Fix creation of organizations
- Add contact-guessing for people and organizations
For [TI-349]
[TI-349]: https://4teamwork.atlassian.net/browse/TI-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix some dossier transfer issues

---

changes/TI-88.other
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/interfaces.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20240524081835_add_setting_to_disable_classic_ui/registry.xml
opengever/core/upgrades/20240524081835_add_setting_to_disable_classic_ui/upgrade.py

This PR adds a feature-flag to disable the classic UI.
It is a marker flag only. So nothing will happen on the backend to prevent access to the classic UI.
The flag will be used by the UI to decide if a link to toggle the UI should be visible or not.
For [TI-88]
[TI-88]: https://4teamwork.atlassian.net/browse/TI-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add feature-flag to disable the classic ui

---

changes/TI-116.other
opengever/workspace/tests/test_vocabularies.py
opengever/workspace/vocabularies.py

Enhance the Workspace member vocabulary so we can get any meeting participants even if they are not part of the workspace any more.
For [TI-116](https://4teamwork.atlassian.net/browse/TI-116)
**Before:**
**After:**
[TI-116]: https://4teamwork.atlassian.net/browse/TI-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add cutom workspace vocb to get users from AllUsers source

---

changes/TI-482.other
opengever/base/systemmessages/api.zcml
opengever/base/systemmessages/configure.zcml
opengever/base/systemmessages/permissions.zcml
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20240531101009_update_system_messages_permissions/rolemap.xml
opengever/core/upgrades/20240531101009_update_system_messages_permissions/upgrade.py
opengever/readonly/tests/test_all_roles_and_permissions_mapped.py

Define new permission `opengever.systemmessages.ManageSystemmessages` to manage System Messages.
The permission is limited to the following roles: `(Manager, Administrator, LimitedAdmin)`
For [TI-482](https://4teamwork.atlassian.net/browse/TI-482)
[TI-482]: https://4teamwork.atlassian.net/browse/TI-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add systemmessages permissions

---

changes/TI-456.bugfix
opengever/oneoffixx/command.py
opengever/oneoffixx/service.py

Before Office Connector no longer needs a filename and we support all kind of templates, we support at least word templates. The Office Connector change will be implemented with https://4teamwork.atlassian.net/browse/TI-455
This change can be reverted, as soon the OC is updated and rolled out.
Needs backport to 2024.8.x
For [TI-456]
[TI-456]: https://4teamwork.atlassian.net/browse/TI-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Temporarily pass a dummy filename to oneoffixx

---

changes/TI-485-2.bugfix
changes/TI-485.bugfix
opengever/task/handlers.py
opengever/task/task.py
opengever/task/tests/test_task_from_template.py

This PR fixes some issues related to nested tasks for task templates:
**Skipped subtasks**
closing a predecessor task was not possible if there where skipped task in the tasks to open
**Properly start and close parent tasks within nested task template structure**
When now starting to work on a subtask, all parent tasks will be set in progress. This ensures in a later step, that the full parent structure will be closed if the last subtask gets closed:
https://github.com/4teamwork/opengever.core/assets/557005/60cd68ca-a53d-4208-8282-d3373ffd223a
For [TI-485]
[TI-485]: https://4teamwork.atlassian.net/browse/TI-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …

Fix nested task templates

---

changes/TI-85.other
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po

Improve French translation for canceling a dossier with open tasks
For [TI-85](https://4teamwork.atlassian.net/browse/TI-85)
[TI-85]: https://4teamwork.atlassian.net/browse/TI-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update French translation for canceling a dossier with open tasks

---

changes/TI-328.other
opengever/api/tests/test_invitation.py
opengever/workspace/participation/__init__.py

Handel invitation sent by inactive workspace users
For [TI-328](https://4teamwork.atlassian.net/browse/TI-328)
[TI-328]: https://4teamwork.atlassian.net/browse/TI-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handel inactive user invitation

---

changes/TI-472.other
opengever/ris/actions.py
opengever/ris/configure.zcml
opengever/ris/tests/test_actions.py

Add ris proposal context action to create tasks, because Köniz wants to create tasks for the proposal in GEVER.
For [TI-472]
[TI-472]: https://4teamwork.atlassian.net/browse/TI-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ris proposal context action to create tasks

---

changes/TI-506.bugfix
opengever/base/context_actions.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20240610143303_add_workspace_export_participants_permission/rolemap.xml
opengever/core/upgrades/20240610143303_add_workspace_export_participants_permission/upgrade.py
opengever/readonly/tests/test_all_roles_and_permissions_mapped.py
opengever/workspace/actions.py
opengever/workspace/configure.zcml
opengever/workspace/permissions.zcml
opengever/workspace/report.py
opengever/workspace/tests/test_actions.py

- Fix workspace admin permission when export workspace users.
For [TI-506](https://4teamwork.atlassian.net/browse/TI-506)
[TI-506]: https://4teamwork.atlassian.net/browse/TI-506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix access for workspace admin on export users

---

changes/TI-399.other
opengever/api/participations.py
opengever/api/tests/test_linked_workspaces.py
opengever/api/tests/test_participation.py
opengever/ogds/base/actor.py
opengever/workspaceclient/client.py
opengever/workspaceclient/linked_workspaces.py

Links workspaces by username instead of userid and adds participations by user/groupname instead of user/groupid.
This is required for setups with user/groupid not beeing equal to user/groupname, because user/groupids are different per OGDS.
For [TI-399](https://4teamwork.atlassian.net/browse/TI-399)
[TI-399]: https://4teamwork.atlassian.net/browse/TI-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Link workspaces by username/groupname

---

changes/TI-402.other
opengever/api/schema/querysources.py
opengever/ogds/base/sources.py

This PR improves the `AllUsersInboxesAndTeamsSource` query source when using the REST-API.
Querysources are not batched. If we search for a user or team, we'll query all terms from the DB. Then we iterate over all terms and doing an actor-lookup for each term. This causes a hue performance lost.
We can't really change the API because the old UI still relies on it. We also don't want to completely refactor the ogds-sources and implement batching because it would be too complicated and time consumption. As a quick-fix, we implement a raw-query which will not resolve terms but return the raw values. We can then resolve each value when required.
Performance-Stats: with 2000 query result:
Without this fix: `3500ms`
With this fix:        `200ms`
For [TI-402]
[TI-402]: …

Improve performance when searching for a responsible in tasks and forwardings

---

changes/TI-293.other
solr-conf/managed-schema

This helps to speed up queries of alphanummeric terms, for example "B57.0.346" or similar.
For [TI-293]
[TI-293]: https://4teamwork.atlassian.net/browse/TI-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Solr conf: use WordDelimiterGraph only on indexing

---

changes/TI-56.other
opengever/workspace/participation/templates/invitation_mail.pt

We remove this link since it is already present a second time at the bottom of the mail. It was leading to confusion.
For [TI-56]
[TI-56]: https://4teamwork.atlassian.net/browse/TI-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove Link to Platform

---

changes/TI-472.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/ris/actions.py
opengever/ris/tests/test_actions.py

Deactivate the edit ui-action for ris proposals
For [TI-472]
- API change:
[TI-472]: https://4teamwork.atlassian.net/browse/TI-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Deactivate the edit ui-action for ris proposals

---

changes/TI-366.bugfix
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/test_linked_workspaces.py

When changing the mimetype of a linked workspace document in teamraum an then retrieve it in gever by creating a new version of a gever-document, the new version will be broken. 
We also have to set the mimetype of the document do be in sync with the blob data.
For [TI-366]
[TI-366]: https://4teamwork.atlassian.net/browse/TI-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Respect new file mimetype when retrieve a file from teamraum as a new version

---

opengever/policytemplates/policy_template/opengever.+package.name+/compose-+base.server_name+-+base.deployment_number+-+base.domain+.yml.bob

The gever-ui port ist now ***80 instead of 34, this PR updates the policytemplate accordingly.

Adjust default port for gever-ui in policytemplates

---

changes/TI-362.other
opengever/api/tests/test_vocabularies.py
opengever/disposition/configure.zcml
opengever/disposition/disposition.py
opengever/disposition/events.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/en/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_events.py
opengever/disposition/vocabularies.py

The PR Introducing 
- `responsible` field on `Disposition `object with limited selectable to the Archivist role.
- Event handler assigns `responsible` on `Finalize Evaluation`  transition to the current user if no responsible was set.
For [TI-362](https://4teamwork.atlassian.net/browse/TI-362)
[TI-362]: https://4teamwork.atlassian.net/browse/TI-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhance Disposition with new field responsible

---

changes/TI-528.bugfix
opengever/api/tests/test_disposition.py
opengever/disposition/disposition.py
opengever/disposition/tests/test_ech0160export.py
opengever/disposition/tests/test_sippackage.py

So the SIP package name is unique, not only the sip folder name as introduced in #7754.
For [TI-528]
[TI-528]: https://4teamwork.atlassian.net/browse/TI-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce sequence number in the SIP name.

---

changes/TI-407-2.other
changes/TI-407.bugfix
changes/TI-407.feature
changes/TI-407.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/watchers.rst
opengever/activity/sources.py
opengever/activity/tests/test_sources.py
opengever/api/tests/test_watchers.py
opengever/api/watchers.py
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

Currently, only users are allowed as watchers for resources.
This PR extends the `@possible-watchers` and `@watchers` endpoint to allow groups and teams as watchers beside of users.
For [TI-407]
- API change:
- If breaking:
[TI-407]: https://4teamwork.atlassian.net/browse/TI-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement group and teams watchers

---

changes/TI-407-2.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/watchers.rst
opengever/activity/sources.py
opengever/activity/tests/test_sources.py
opengever/api/tests/test_watchers.py

Currently, the `@possible-watchers` endpoint returns all possible watchers without the watchers which are currently watching the context. 
This filter makes it complicated and expensive to calculate in the backend and could easily be handled in the frontend if an actor is already watching a specific resource. 
This PR removes these filters and will always return all actors with are possible to watch a context.
This PR implements the review-feedback of: https://github.com/4teamwork/opengever.core/pull/7986#discussion_r1665428959
For [TI-407]
- API change:
- If breaking:
[TI-407]: https://4teamwork.atlassian.net/browse/TI-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

Remove @possible-watchers already existing watchers filter

---

changes/TI-670.other
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/report.py

Include the workspace title in the participation Excel file when downloading it.
For [TI-670](https://4teamwork.atlassian.net/browse/TI-670)
[TI-670]: https://4teamwork.atlassian.net/browse/TI-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include workspace title in participant export file name

---

changes/TI-458.bugfix
opengever/api/tests/test_tus.py
opengever/api/tus.py

Fix Update document date on Drag & Drop from Outlook Mail.
For [TI-458](https://4teamwork.atlassian.net/browse/TI-458)
**Before:**
**After:**
[TI-458]: https://4teamwork.atlassian.net/browse/TI-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Document date after drag and drop from E-Mail

---

changes/TI-669.other
opengever/globalindex/browser/report.py
opengever/workspace/report.py
opengever/workspace/tests/test_workspace_participation_reporter.py

This PR enhances the workspace participant Excel export feature by including users who are part of groups with permissions in the workspace. Previously, the export only listed users directly authorized in the workspace. With this update, the export will:
- Resolve group members and include users from these groups in the export.
- Ensure that no duplicated users in the export.
For [TI-669](https://4teamwork.atlassian.net/browse/TI-669)
[TI-669]: https://4teamwork.atlassian.net/browse/TI-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include group users in Teamraum participant Excel export

---

changes/GH-7995.bugfix
docker/core/requirements-core.txt

Building the Docker image is currently broken.

Fix Redis requirement for Docker image

---

opengever/workspace/tests/test_workspace_participation_reporter.py

This PR fixes a flaky test due to different sort orders between test-runs.
See test-result of: https://github.com/4teamwork/opengever.core/pull/7993/checks?check_run_id=27514045718
Follow-Up for https://github.com/4teamwork/opengever.core/pull/7992/
For [TI-669]
[TI-669]: https://4teamwork.atlassian.net/browse/TI-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix flaky test due to different sort orders

---

changes/TI-706.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dossier_transfers.rst
opengever/dossiertransfer/api/get.py
opengever/dossiertransfer/tests/test_api_get.py

This PR adds the summary serialized brain of the `root` dossier if requesting dossier-transfers through the `@dossier-transfer` endpoint or directly requesting a transfer with `@dossier-transfer/1`.
The root-dossier will only be serialized if:
1. the root is stored on the current admin-unit
2. the user has permission to view the dossier
**Why don't we add the `root_item` to the dossier-transfer serializer?**
The reason is performance. A dossier-transfer is stored in the ogds. The serializer would need to know if the source dossier is stored on the current admin unit and would need to do a catalog query to lookup the dossier. We'd need to do this for every dossier transfer.
For [TI-706] …

Add serialized source dossier to dossier transfer if possible

---

changes/TI-296.other
opengever/api/sharing.py
opengever/sharing/tests/test_sharing.py

Update the `Sharing `endpoint with the following points :
1. In the sharing tab, inactive users and groups are displayed only for managers.
2. In edit mode, inactive users and groups are always displayed
For [TI-296](https://4teamwork.atlassian.net/browse/TI-296)
[TI-296]: https://4teamwork.atlassian.net/browse/TI-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude inactive users and groups for non-managers in Sharing tab

---

changes/TI-777.bugfix
opengever/repository/browser/tabbed.py
opengever/repository/tests/test_repositoryfolder_tabs.py

Add logic to the Proposals tab, enabling it to display when either the `proposal `feature or any of the `spv` features `(RIS or Meeting)` are activated.
For [TI-777](https://4teamwork.atlassian.net/browse/TI-777)
[TI-777]: https://4teamwork.atlassian.net/browse/TI-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update tabbed logic for proposals to include old and new SPV

---

changes/GH-8003.bugfix
opengever/bundle/console.py

Was broken in release 2024.6.0

Fix migration.log handler

---

changes/TI-596.other
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po

Missing French Translation was added for limiting dossier depth:
Before:
After:
For [TI-596]
[TI-596]: https://4teamwork.atlassian.net/browse/TI-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

French translation during File Metadata edit fixed

---

changes/TI-672.other
opengever/workspace/actions.py
opengever/workspace/tests/test_actions.py

The PR provides an Excel export feature for workspacefolder `participations` via `context action`.
For [TI-672](https://4teamwork.atlassian.net/browse/TI-672)
Related FrontEnd PR [FR PR](https://github.com/4teamwork/gever-ui/pull/2782)
[TI-672]: https://4teamwork.atlassian.net/browse/TI-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide context action to export workspacefolder participations

---

changes/OPS-97.bugfix
opengever/bundle/config/importer.py

This fixes "AttributeError: can't set attribute" during policyless setup:
```
File "<string>", line 1, in <module>
File "/app/opengever/setup/zopectl.py", line 116, in setup
import_bundle(deployment.site, options.bundle_path)
File "/app/opengever/setup/zopectl.py", line 179, in import_bundle
importer.run()
File "/app/opengever/bundle/config/importer.py", line 34, in run
self.update_casauth_settings()
File "/app/opengever/bundle/config/importer.py", line 82, in update_casauth_settings
self.portal.acl_users.cas_auth.cas_server_url = cas_server_url
AttributeError: can't set attribute
```
When the distinction between an internal CAS server URL and the regular CAS server URL was introduced in 4teamwork/ftw.casauth#23, `cas_plugin.cas_server_url` was made into …

Fix setting CAS server URL on setup

---

changes/TI-691.other
opengever/core/upgrades/20240814102603_add_kub_doc_property_additional_fields/registry.xml
opengever/core/upgrades/20240814102603_add_kub_doc_property_additional_fields/upgrade.py
opengever/dossiertransfer/tests/test_api_get.py
opengever/kub/docprops.py
opengever/kub/interfaces.py
opengever/kub/testing.py
opengever/kub/tests/test_docprops.py

This PR introduces :
- Added configurable DocProperties
- Introduced a new registry property to define which KuB fields are available as DocProperties 
- Updated the DocProperties Crawlers to respect the new configuration without causing errors if a field is unavailable.
For [TI-691](https://4teamwork.atlassian.net/browse/TI-691)
**Default (Before):**
**With Custom Doc Props (After)**
[TI-691]: https://4teamwork.atlassian.net/browse/TI-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add customFields support in IKUBSettings to include them in Docprops

---

changes/TI-918.other
docs/schema-dumps/opengever.workspace.meeting.schema.json
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/tests/test_workspace_meeting.py
opengever/workspace/workspace_meeting.py

The PR
- Provided a new field `guests` on the `IWorkspaceMeetingSchema` which allow the users to add `guests` to a meeting.
- Add the guest field to the generated protokoll pdf. 
For [TI-918](https://4teamwork.atlassian.net/browse/TI-918)
[TI-918]: https://4teamwork.atlassian.net/browse/TI-918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide new field guests on Meeting

---

changes/TI-922.other
opengever/ogds/base/sources.py
opengever/workspace/tests/test_vocabularies.py
opengever/workspace/tests/test_workspace_sources.py
opengever/workspace/vocabularies.py

This PR:
- Refactored vocabulary handling to return 'not found' for invalid  users and exceptions. 
- Added tests to ensure correct term management and error handling.
For [TI-922](https://4teamwork.atlassian.net/browse/TI-922)
[TI-922]: https://4teamwork.atlassian.net/browse/TI-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve workspace users vocabulary to properly handle no longer available users for restricted workspaces

---

changes/TI-917.others
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot

This PR implements adding the todos that agenda items have in teamroom to the pdf-export.
For [TI-917]
[TI-917]: https://4teamwork.atlassian.net/browse/TI-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add todos related to agenda items to the pdf export in teamroom

---

changes/TI-658.other
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20240718141302_add_sign_feature_flag/registry.xml
opengever/core/upgrades/20240718141302_add_sign_feature_flag/upgrade.py
opengever/sign/interfaces.py
opengever/sign/tests/test_feature_flag.py
opengever/sign/utils.py
opengever/testing/integration_test_case.py

This PR adds the feature flag for the sign-service.
For [TI-658]
[TI-658]: https://4teamwork.atlassian.net/browse/TI-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sign feature flag.

---

changes/TI-479.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/tests/test_listing.py
opengever/base/configure.zcml
opengever/base/handlers.py
opengever/base/solr/fields.py
opengever/core/upgrades/20240821165540_add_dossier_review_state_index/upgrade.py
opengever/dossier/configure.zcml
opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py
opengever/dossier/tests/test_move_items.py

This PR implements the `dossier_review_state` index. The index provide the state of the current dossier or the closest parent dossier for other content types.
The use case for this index is to filter by contents within a dossier of a specific state. I.e. all documents within an inactive dossier.
ℹ️ there is no need to recreate the solr docker image. The `dossier_review_state` is already defined within the solr-schema: https://github.com/4teamwork/opengever.core/blob/master/solr-conf/managed-schema#L144 but is not in use. I just reused this field for the new indexer.
For [TI-479]
[TI-479]: https://4teamwork.atlassian.net/browse/TI-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add dossier_review_state solr index.

---

changes/TI-1009.bugfix
docker/core/etc/site.zcml
opengever/base/monkey/configure.zcml

Load monkey patches as early as possible
Because of not using `z3c.autoinclude` with Docker, the order of loading ZCML is different. It turns out that applying the patch for `handleDynamicTypeCopiedEvent` after registering the event handler doesn't work and breaks copying documents.
For [TI-1009](https://4teamwork.atlassian.net/browse/TI-1009)
[TI-1009]: https://4teamwork.atlassian.net/browse/TI-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix copying documents when deployed with Docker

---

changes/TI-309.other
opengever/latex/listing.py
opengever/latex/tests/test_listing.py

Adjust the widths of the columns in the Subdossiers section for the pdf generation to ensure that dates have enough space.
The extra 1% added to the 2 date columns was removed from the "responsible" column. 
For [TI-309]
[TI-309]: https://4teamwork.atlassian.net/browse/TI-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust column widths to allow space for dates.

---

changes/GH-8025.other
opengever/base/colorization.py

Allows us to disable colorization without removing the env variable which is more convenient for Docker Compose deployments.

Disable colorization if env variable has an empty value

---

changes/TI-114.other
opengever/task/localroles.py
opengever/task/tests/test_localroles.py

The PR:
1. Grant Reader Access on the Task: Provide `Reader `access to informed_principals for viewing the task details.
2. Grant Reader Access on Related Items: Allow `Reader `access for informed_principals on all related items for viewing purposes.
3. Grant TaskResponsible Access on Related Items: Allow `TaskResponsible` access for informed_principals on dossier
4. Revoke Permissions When Task is Closed: Automatically revoke all permissions for informed_principals once the task is closed.
For [TI-114](https://4teamwork.atlassian.net/browse/TI-114)
[TI-114]: https://4teamwork.atlassian.net/browse/TI-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

Enhance local roles with task informed principals reader roles

---

changes/TI-1046.bugfix
opengever/workspace/__init__.py

The term 'opengever.ogds.base.all_admin_units' wasn't in the whitelisted vocabularies for teamraum and therefore was always deemed to be invisible. Therefore creating System Messages worked in Gever, but not in Teamraum. The whitelisted Vocab was updated and problem was fixed:
Before:
After:
For [TI-1046]
[TI-1046]: https://4teamwork.atlassian.net/browse/TI-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add all_admin_units to whitelisted teamraum vocab

---

changes/GH-8030.other
docker/core/entrypoint.d/create_zope_conf.py

We log requests with ftw.structlog which provides all the information from the Z2 log and more.

Disable Z2 access log in Docker deployments

---

changes/TI-658-2.other
opengever/base/context_actions.py
opengever/base/tests/test_utils.py
opengever/base/utils.py
opengever/document/actions.py
opengever/document/tests/test_actions.py

This PR reverts the sign actions introduced in #7998 according to the comment in https://4teamwork.atlassian.net/browse/TI-659?focusedCommentId=46734
Reason: we'll implement the feature by the workflow, not by actions.
For [TI-659]
[TI-659]: https://4teamwork.atlassian.net/browse/TI-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert sign action

---

changes/TI-992.bugfix
opengever/api/configure.zcml
opengever/api/response.py
opengever/api/task.py
opengever/api/tests/test_response.py

We have two response implementations. A `Response` and a `TaskResponse`. The `TaskResponse` is used for tasks only and provides some additional attributes.
When removing a task comment, we currently use a default `Response` object instead a `TaskResponse`. We have several code parts where we check for attributes which are only available on the `TaskResponse`. For example: https://github.com/4teamwork/opengever.core/blob/2fa9dbf08e4ff5eb621186788c398c59382a4c29/opengever/task/browser/close.py#L311 . This will not work for `Reponses` and will raise an error.
This PR fixes this issue by using the `TaskResponse` for deleted comments as we do it already for every other response on tasks.
Providing an upgrade step seems not to be necessary since it is a rare edge-case. The last committed …

Use TaskResponses if removing a task comment

---

changes/TI-1036.other
opengever/api/tests/test_participation.py
opengever/workspace/participation/browser/my_invitations.py

This pull request addresses a recurring AttributeError encountered by users in Teamraum when handling invitations. The error was traced to an issue where a non-existent inviter was being referenced, leading to a failure in the invitation process.
For [TI-1036](https://4teamwork.atlassian.net/browse/TI-1036)
**Before:**
**After:**
[TI-1036]: https://4teamwork.atlassian.net/browse/TI-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Resolve invitation error when user dose not exists any more

---

changes/TI-953.bugfix
opengever/document/browser/download.py
opengever/document/tests/test_download.py

When trying to dowload certain files and giving them a name with special characters there was an error on prod.
This was caused by the filename string getting converted into a byte string, which gever then tries to encode with UTF-8, which doesn't work.
With the fix it is checked that the filename is infact unicode and can be encoded before doing so.
To reproduce this add a file to gever. Now try to download said file by adding `/@@download/file/blä.docx` or another name with ä, ö or ü in it to the trailing part of the URL of the file. Without the change this should lead to an error.
For [TI-953]
[TI-953]: https://4teamwork.atlassian.net/browse/TI-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix error with file downloads

---

changes/TI-1086.other
opengever/workspace/report.py
opengever/workspace/tests/test_workspace_participation_reporter.py

This PR:
Updates the` teamraum participation` export to ensure that only active `users `and `group users` are included in the Excel export. Previously, some` deleted / Inactive` users were still being listed (status '`FALSCH`'). With this change, inactive or deleted users will no longer be part of the export.
For [TI-1086](https://4teamwork.atlassian.net/browse/TI-1086)
**Before:**
**After:**
[TI-1086]: https://4teamwork.atlassian.net/browse/TI-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude inactive users from teamraum participation excel export

---

changes/TI-1024.bugfix
opengever/ogds/base/sync/ogds_updater.py

This PR fixes an issue where syncing the ogds is no longer possible due to a unicode error in the logger:
Sentry: https://sentry.4teamwork.ch/organizations/sentry/issues/135578/?project=17&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=2
A skipped user will be logged. If its userid contains an umlaut, it will fail.
For [TI-1024]
[TI-1024]: https://4teamwork.atlassian.net/browse/TI-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix unicode error when logging skipped users in ogds-updater

---

changes/TI-659.feature
development.cfg
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/documents_sign.rst
docs/public/dev-manual/api/index.rst
opengever/api/configure.zcml
opengever/api/sign.py
opengever/api/tests/test_sign.py
opengever/api/transition.py
opengever/base/subscribers.py
opengever/core/testing.py
opengever/document/configure.zcml
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_document_workflow.py
opengever/document/transition.py
opengever/sign/client.py
opengever/sign/sign.py
opengever/sign/storage.py
opengever/sign/tests/test_client.py
opengever/sign/tests/test_sign.py
opengever/sign/tests/test_storage.py
opengever/sign/tests/test_token.py
opengever/sign/token.py

This PR implements the signing feature.
The feature extends the newly introduced sign-transitions from #8034 with additional transition extenders which are responsible for starting the sign-process and uploading a new, signed document version.
The signing-flow looks as follow:
ℹ️ the coral-parts are implemented by this PR.
For [TI-659]
- API change:
- If breaking:
- Bug fixed:
[TI-659]: https://4teamwork.atlassian.net/browse/TI-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

Implement the sign-feature

---

changes/TI-1210.bugfix
opengever/api/solr_query_service.py
opengever/base/solr/fields.py
opengever/base/tests/test_solr_listing_fields.py

Solr may still return facet values for values that are not in the index any more, even after restarting Solr. So we may encounter facet values that refer to non-existent objects, like renamed OrgUnits.
In case of a missing facet label, logging will look like this:
```python
2024-09-19 13:58:56 ERROR opengever.base.solr Failed to transform value u'inbox:doesntexist' for field 'responsible':
2024-09-19 13:58:56 ERROR opengever.base.solr OrgUnit new for identifier inbox:doesntexist is missing.
File "/opengever/base/solr/fields.py", line 308, in index_value_to_label
transformed = self.transform(value)
File "/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/volatile.py", line 71, in replacement
cached_value = cache[key] = fun(*args, **kwargs)
File …
```

Make determining Solr facet labels more robust:

---

changes/TI-1221.bugfix
opengever/activity/sources.py
opengever/activity/tests/test_sources.py
opengever/ogds/base/sources.py
opengever/workspace/tests/test_workspace_sources.py

The PR #7986 extended the possible watchers from users only to watching users, groups and teams. This works fine for gever but not for teamraum.
The group source is not whitelisted in teamraum and teams do not exist in teamraum.
The PR fixes the issue by:
- Whitelist and protect the groups source for teamraum deployments
- only use the users and groups source for teamraum deployments and add the teams-source only for gever deployments.
For [TI-1221]
[TI-1221]: https://4teamwork.atlassian.net/browse/TI-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix possible watchers in teamraum

---

changes/TI-1222.feature
opengever/activity/sources.py
opengever/activity/tests/test_sources.py
opengever/base/interfaces.py
opengever/core/upgrades/20240919110844_add_possible_watchers_groups_white_list_setting/registry.xml
opengever/core/upgrades/20240919110844_add_possible_watchers_groups_white_list_setting/upgrade.py
opengever/ogds/base/sources.py

This PR adds a new global configuration option to filter possible group watcher by a regex.
For [TI-1222]
[TI-1222]: https://4teamwork.atlassian.net/browse/TI-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add configuration option to filter possible group watchers

---

changes/TI-948.other
docker/core/Dockerfile
opengever/bundle/console.py

Currently if there are any changes in the Vdexvocabs the bundle importer validates against a wrong JSON Schema. We added a new flag `--rebuild-schemas` which makes a new dump of the current schemas. To make it work on docker containers, we granted the plone user permission to write inside the schemas directory. 
Example command: `bin/instance import opengever/bundle/tests/assets/basic.oggbundle --rebuild-schemas`
For [TI-948](https://4teamwork.atlassian.net/browse/TI-948)
[TI-948]: https://4teamwork.atlassian.net/browse/TI-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add option to dump current schemas to bundle loader

---

changes/TI-942.other
opengever/disposition/browser/removal_protocol.py
opengever/disposition/disposition.py
opengever/disposition/tests/test_disposition.py

A user can create disposition by selecting dossiers in the dossier listing.
As soon as the disposition is created, each dossier will be turned into a new review state called: "offered". A user is now able to edit the disposition and remove dossiers which will trigger another workflow transition on dossiers to release them again.
A dossier which is already part of a disposition cannot be added to another disposition.
Currently, we have the following restrictions:
- a disposition cannot be removed
- a disposition requires at least one dossier
This is bad for the following situation: A user creates a disposition "Disposition A" with "Dossier A" and realized that it was a bad selection. There is already an existing disposition "Disposition B". There is no option to `abort` this process. The …

Allow to close a disposition without any dossiers

---

sphinx.cfg

Decommission Centos 7 Server seth.4teamwork.ch and use web06p.4teamwork.ch for future publishing of onegovgever docs.

Change docs publishing server

---

changes/TI-675.bugfix
opengever/document/browser/download.py

Until now we prevented downloading documents with no versions that are checked out by another user. This doesn't make sense as this is only the case when the document hasn't been modified yet. As soon as the document is modified, the initial version is created and used for downloads.
For [TI-675](https://4teamwork.atlassian.net/browse/TI-675)
[TI-675]: https://4teamwork.atlassian.net/browse/TI-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow downloading checked-out documents with no modifications

---

changes/GH-8056.bugfix
opengever/setup/zopectl.py

Set log level for root logger instead of "opengever.setup" logger only. This way we also get the logs from ftw.upgrade at INFO level.

Fix logging in upgrade command

---

changes/TI-1300.bugfix
opengever/api/tests/test_process.py
opengever/task/__init__.py
opengever/task/handlers.py
opengever/task/task.py
opengever/task/tests/test_task_from_template.py
opengever/tasktemplates/tasktemplatefolder.py

This PR fixes the initial state of tasks created from a task template.
To make it clear what really changes through this PR, the first  commit provides a bunch of missing tests of the current implementation which will then be updated with the bugfix.
Here is an example of what changes through this PR: If I start a process with the following structure:
- Parallel Task
- Task 1
- Task 2
- Sequential Task
- Task 3
- Task 4
The tasks where started in the following states:
- Parallel Task (in Progress)
- Task 1 (open)
- Task 2 (open)
- Sequential Task (planned)
- Task 3 (planned)
- Task 4 (planned)
With the fix, it would create tasks in the following states:
- Parallel Task (in Progress)
- Task 1 (open)
- Task 2 (open)
- Sequential Task (in Progress)
- Task 3 (open)
- Task 4 (planned)
For …

Fixes nested tasktemplates on the first level

---

changes/GH-8058.other
docker/core/Dockerfile
docker/core/cron/crontab
docker/core/docker-entrypoint.sh
docker/core/entrypoint.d/create_crontab.py

Create cron jobs in Docker deployments within a time window.
Cron jobs are now started within a time window to avoid starting them at the same time for each deployment.
By default the deployment number is used to spread the cron jobs equaly in 12 slots. This can be customized by setting the `CRON_START_SLOT` and `CRON_MAX_START_SLOTS` environment variables explicitly.
The time window is defined by start and end time and is currently not configurable.

Cron time window

---

changes/TI-1116.other
opengever/setup/sections/local_roles.py

This is required when using a non-legacy profile with ogds-sync (group names and ids are not equal).
For [TI-1116](https://4teamwork.atlassian.net/browse/TI-1116)
[TI-1116]: https://4teamwork.atlassian.net/browse/TI-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support setting local roles by groupname when importing repositories from Excel

---

changes/GH-7921.other
docker-compose.yml
docker/mta/Dockerfile
docker/mta/conf/aliases.jinja
docker/mta/conf/main.cf.jinja
docker/mta/conf/sni.jinja
docker/mta/conf/virtual.jinja
docker/mta/configure-postfix.py
docker/mta/docker-entrypoint.sh
docker/mta/mta2plone.py
opengever/base/monkey/patches/__init__.py
opengever/base/monkey/patches/mailhost.py

Provide MTA container for handling mail. Handles incoming and outgoing mail with Postfix.
This is meant for setups where we deploy only containers and replaces the functionality provided by Postfix installed on the host.
Additionaly the mail host can now be configured through the follwing environment variables:
```
- SMTP_HOST
- SMTP_PORT
- SMTP_USER
- SMTP_PASSWORD
- SMTP_FORCE_TLS
- SMTP_NO_TLS
```

Docker MTA

---

changes/TI-932.bugfix
opengever/workspace/participation/browser/my_invitations.py

An OGDS sync is required after a new user has been created by the invitation process when using the OGDS auth plugin.
The OGDS sync is triggered after the user created a new account and gets redirected back to the `@@my-invitations` endpoint and before the regular authentication flow is triggered.
The sync could be optimized by just syncing the new user, but for now syncing all users seems to be fast enough.
For [TI-932](https://4teamwork.atlassian.net/browse/TI-932)
[TI-932]: https://4teamwork.atlassian.net/browse/TI-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix login for newly registered teamraum users when using OGDS authentication

---

changes/TI-1263.other
opengever/api/copy_.py
opengever/api/tests/test_copy_paste.py

**Current situation :** 
When copying a dossier that is already linked to a workspace causes the target dossier to remain connected to that workspace. This should not happen.
**This PR :**
With the changes made in this PR, the copied dossier will not be connected to any workspace, even if the source dossier is linked to one.
For [TI-1263](https://4teamwork.atlassian.net/browse/TI-1263)
[TI-1263]: https://4teamwork.atlassian.net/browse/TI-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove the linked teamraum from target dossier after copy

---

changes/TI-1103.other
opengever/base/solr/fields.py

Excel Export for faceted Search was implemented in https://github.com/4teamwork/gever-ui/pull/2809.
It was noticed that header "Dossier ID" didn't exist in fields, and therefore wouldn't be included in the excel export. To fix this, this field was added to solr fields.py.
9 solr tests don't pass due to the problem mentioned by Buchi in the daily
For [TI-1103]
[TI-1103]: https://4teamwork.atlassian.net/browse/TI-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new solr Field "ID"

---

opengever/api/tests/test_livesearch.py
opengever/api/tests/test_solrsearch.py

Required due to https://github.com/4teamwork/opengever.core/pull/7958
Didn't get noticed because no new ogsolr image was built, which is used in tests.
The regular `@solrsearch` endpoint is mainly affected by the changes, but it's no longer used in the UI, so we just remove the assertions as fixing it would reintroduce the performance problems. Currently we are only using the `@solrlivesearch` endpoint.

Fix Solr tests

---

docker/core/Dockerfile
docker/core/packages/openssl1.1-compat/APKBUILD
docker/core/packages/openssl1.1-compat/man-section.patch
docker/core/packages/openssl1.1-compat/ppc64.patch

Update to latest Alpine version (3.20)
Base images `4teamwork/plone` and `4teamwork/python` are already updated.
Alpine 3.20 no longer provides openssl 1.1, therefore we have to build it ourselves.
It's no longer necessary to uninstall openssl 1.1 for building psycopg2 as we put the 1.1 headers in a different location 😉 .

Use Alpine 3.20 as base image

---

HISTORY.rst

Release `2024.15.0` was a brown bag release that was made without the `zestreleaser.towncrier` plugin. Therefore  HISTORY.rst got messed up by zest.releaser, since it processed it in the traditional style.
Updated [docs](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/35652746/Python+Paket+releasen+mit+zest.releaser) with instructions to also install `zestreleaser.towncrier`.
For [TI-1422](https://4teamwork.atlassian.net/browse/TI-1422)
[TI-1422]: https://4teamwork.atlassian.net/browse/TI-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix HISTORY.rst

---

setup.cfg

Prevent `zest.releaser` from building wheels.
Since version `8.0.0a2` zest.releaser will always build wheels, which we don't want for `opengever.core`. 
For [TI-1447](https://4teamwork.atlassian.net/browse/TI-1447)
[TI-1447]: https://4teamwork.atlassian.net/browse/TI-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prevent zest.releaser from building wheels.

---

changes/GH-8075.bugfix
opengever/meeting/sablon.py

Leaving it open can lead to: `ValueError: Can't commit with opened blobs.`

Close template file after processing with Sablon

---

changes/GH-8076.bugfix
docker/core/Dockerfile

Cryptography was accidentally linked against OpenSSL 3.

Fix broken build of cryptography in Docker image

---

changes/GH-8077.bugfix
opengever/core/profiles/default/jsregistry.xml

With #8036 the order of the resources was changed so that the cooked javascript was broken.

Fix broken JS registry for new installs

---

opengever/api/tests/test_listing.py
opengever/api/tests/test_solrsearch.py
opengever/base/tests/test_search.py
opengever/base/tests/test_solr_livesearch.py
opengever/base/tests/test_source_binder.py
opengever/tabbedview/tests/test_catalog_source.py
opengever/tabbedview/tests/test_filters.py
opengever/testing/integration_test_case.py

The `mock_solr`-method of `opengever/testing/integration_test_case.py` is not isolated at all. If used once, the solr connection is mocked for every upcoming test.
We have another solr-mock implementation within the disposition builder introduced in https://github.com/4teamwork/opengever.core/pull/7939 (https://github.com/4teamwork/opengever.core/pull/7939/commits/b38f4d82779b33fe19e68f5ba39af55294651ca3) which checks for an already running solr and mocks the response if there is no solr connection yet. 
Until now, there was no test using the `mock_solr` method before the disposition activity-tests which relies on these mocked results: https://github.com/4teamwork/opengever.core/blob/master/opengever/disposition/tests/test_activities.py#L36
Under some circumstances, the execution order …

Fix isolation issue with tests using a mocked solr.

---

changes/TI-1345.bugfix
opengever/dossiertransfer/api/perform.py
opengever/dossiertransfer/tests/test_api_perform.py

This PR fixes an issue where it is not possible to transfer a dossier if the target admin unit does not provide the same dossier or document types.
We fix the issue by removing the not existing type before deserializing it. Means, we loose this information on the target admin unit. This is the desired behavior.
For [TI-1345]
[TI-1345]: https://4teamwork.atlassian.net/browse/TI-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dossier transfer if the target admin unit does not provide the same dossier_types or document_types.

---

changes/TI-1472.other
opengever/dossier/browser/report.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_reporter.py

**This PR**:
Adds the dossier creator to the dossier report if the creator column is sent from the front end
For [TI-1472](https://4teamwork.atlassian.net/browse/TI-1472)
- API change:
- If breaking:
- Bug fixed:
[TI-1472]: https://4teamwork.atlassian.net/browse/TI-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Dossier creator column to dossier report

---

changes/TI-661.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/document.py
opengever/api/tests/test_serializer.py
opengever/api/transition.py
opengever/core/testserver.py
opengever/document/tests/test_document_workflow.py
opengever/document/transition.py
opengever/sign/client.py
opengever/sign/pending_signer.py
opengever/sign/pending_signing_job.py
opengever/sign/sign.py
opengever/sign/storage.py
opengever/sign/tests/test_client.py
opengever/sign/tests/test_pending_signer.py
opengever/sign/tests/test_pending_signing_job.py
opengever/sign/tests/test_sign.py
opengever/sign/tests/test_storage.py
opengever/sign/tests/test_utils.py
opengever/sign/utils.py

This PR makes the pending signing state available for the frontend.
The current implementation has some issues when working with different versions and trying to make it visible to the UI. If we revise a signed document or revert to an old version, we'd loose the information about the signed documents and signers.
Currently, we provide `sign_metadata` which is in fact the `pending_signing_job` state. It gives us information about a pending signing process like the job-id, redirect url and the signers. this could also contain the current state of signers, i.e. who has aborted or not yet signed the document.
But there should be another state, the `signatures`-state itself. This should give us a finalized info about which version is signed by which users. So as soon as the signing-process is …

Serialize pending signing job for documents

---

changes/TI-661-2.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/documents_sign.rst
opengever/api/document.py
opengever/api/tests/test_serializer.py
opengever/sign/pending_signer.py
opengever/sign/pending_signing_job.py
opengever/sign/sign.py
opengever/sign/signatory.py
opengever/sign/signed_version.py
opengever/sign/storage.py
opengever/sign/tests/test_pending_signer.py
opengever/sign/tests/test_pending_signing_job.py
opengever/sign/tests/test_sign.py
opengever/sign/tests/test_signatory.py
opengever/sign/tests/test_signed_version.py
opengever/sign/tests/test_storage.py

This PR is a follow-up PR of #8050 
Currently, we only track pending signing jobs on a document. As soon as the document sign process is completed, we do not have any information about the signatories or which versions has been signed.
This PR adds a storage for `signature items` and provides it through the api.
A new signature item will be created and persisted as soon as the signing process will be completed (all the requested signatories have been signed the document). 
In a pending signing job, we're just working with email addresses and will provide actor-ids on the fly when serializing it. This is what we want because the underlying actor could still change. As soon as the signature job is completed, we need to make sure, that the underlying actor does no longer change. We do this …

Implement and serialize signatures

---

changes/TI-1471.other
opengever/api/tests/test_ui_actions.py
opengever/base/browser/reporting_view.py
opengever/base/listing_actions.py
opengever/document/browser/report.py
opengever/dossier/actions.py
opengever/dossier/tests/test_actions.py
opengever/dossier/tests/test_reporter.py

**This PR:**
Implements a new action to export dossiers with subdossiers. We use the same endpoint, `dossier_report`, and its related class `DossierReporter`. 
The export is controlled via a parameter flag, `include_children`. If the flag is set to true, the subdossiers will be included in the export; otherwise, only the selected dossiers will be exported.
For [TI-1471](https://4teamwork.atlassian.net/browse/TI-1471)
[TI-1471]: https://4teamwork.atlassian.net/browse/TI-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide dossier Excel export including subdossier

---

changes/GH-8081.other
changes/GH-8081a.other
changes/GH-8081b.other
opengever/bundle/sections/map_principal_names_to_ids.py
opengever/bundle/tests/test_section_map_principal_names_to_ids.py
opengever/examplecontent/meeting.py
opengever/examplecontent/workspaces.py
opengever/ogds/models/group.py
opengever/setup/cfgs/gever_content.cfg
opengever/setup/deploy.py
opengever/setup/sections/local_roles.py
opengever/setup/zopectl.py
opengever/testing/builders/dx.py

Fix various issues when creating content in a policy:
- Sync OGDS as early as possible on new site setup
- Map responsible name to id when creating dossiers with a policy
- Map responsible name to id when creating dossiers with dossier builder
- Map group names to ids when assigning global roles in deployment setup
- Install OGDS auth plugin when there's no LDAP profile

Fix username userid issues

---

changes/TI-1476.other
opengever/base/reporter.py
opengever/globalindex/browser/configure.zcml
opengever/globalindex/browser/report.py
opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/en/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/opengever.globalindex.pot
opengever/globalindex/tests/test_reporter.py

**This PR:**
Implement a new endpoint `groups-membership-report` to export all groups and their related users in an Excel table.
The endpoint is accessible only for admin users
For [TI-1476](https://4teamwork.atlassian.net/browse/TI-1476)
- API change:
- If breaking:
- Bug fixed:
[TI-1476]: https://4teamwork.atlassian.net/browse/TI-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide Excel Export for groups membership

---

changes/TI-1477.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/role_assignment_reports.py
opengever/api/tests/test_role_assignment_reports.py

**This PR** 
Updates the returned values from the `RoleAssignmentReportsGet` endpoint with additional data, including `reference_number `and `review_state`. This data will be used in the frontend to add new columns to the `RoleAssignmentReport `table.
For [TI-1477](https://4teamwork.atlassian.net/browse/TI-1477)
[TI-1477]: https://4teamwork.atlassian.net/browse/TI-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhance RoleAssignmentReportsGet endpoint with new values

---

opengever/base/browser/reporting_view.py

**This PR:**
Follow-Up: Add Hierarchical Path Filtering and Sorting for Include-Children Feature
The hierarchy of the exported Excel file was disorganized. When exporting dossiers with subdossiers, the subdossiers were not listed under their main positions, which was not ideal for users. With these changes, we now have a proper hierarchy in the exported Excel table.
For [TI-1471](https://4teamwork.atlassian.net/browse/TI-1471)
[TI-1471]: https://4teamwork.atlassian.net/browse/TI-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix sort order for children dossier when exporting dossiers including subdossiers

---

changes/TI-1540.other
opengever/base/role_assignments.py
opengever/base/tests/test_database_table_declarations.py
opengever/core/upgrade.py
opengever/core/upgrades/20241114093420_add_local_roles_lookup_sql_table/upgrade.py
opengever/core/upgrades/20241114094418_reindex_local_roles_lookup_table/upgrade.py
opengever/sharing/local_roles_lookup/manager.py
opengever/sharing/local_roles_lookup/model.py
opengever/sharing/tests/test_local_roles_lookup_manager.py

This PR introduces a local roles tracking table which can be used to do ad-hoc reports about modified local-roles for users or objects.
The table stores all managed roles of each principal for each object having managed custom local roles.
For [TI-1540]
[TI-1540]: https://4teamwork.atlassian.net/browse/TI-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce a lookup table for objects having modified local roles.

---

changes/TI-1541.other
opengever/sharing/local_roles_lookup/reporter.py
opengever/sharing/tests/test_role_assignment_reporter.py

This PR implements the `RoleAssignmentReporter` which is able to return a dict of objects having changed local roles.
The reporter creates a dict providing a list of objects, ordered by their paths, that define custom local roles.
Each item in the list contains:
- a serialized Solr item representing the object.
- a dictionary mapping each defined local role to a list of principals assigned that role.
The report can be filtered by a specific `principal_id`, with an option to include or exclude assigned groups for the given principal. Additionally, the report can be limited to a specific branch.
For [TI-1541]
[TI-1541]: https://4teamwork.atlassian.net/browse/TI-1541?atlOrigin=eyJpIjoiNWRkNTlj …

Implement RoleAssignmentReporter

---

changes/TI-1541-2.other
opengever/sharing/local_roles_lookup/reporter.py
opengever/sharing/tests/test_role_assignment_reporter.py

This is a follow-up PR of #8088 
It extends the `RoleAssignmentReporter` to allow creating reports of multiple principals instead only of one principal.
In addition, the PR fixes an issue in testing where I used `assertItemsEqual` instead `assertEqual`. Using `assertItemsEqual` for nested dicts will not properly deep assert the values. It will lead to false positives.
For [TI-1541]
[TI-1541]: https://4teamwork.atlassian.net/browse/TI-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow multiple principals when creating role assignment reports

---

opengever/sharing/local_roles_lookup/manager.py

This is a follow-up PR of https://github.com/4teamwork/opengever.core/pull/8086
It's possible that we get `None` principals in `local_roles`:
```
>>> obj.__ac_local_roles__
{'principal1': ['Owner'], None: ['Role Manager'], 'principal2': ['Owner']}
```
Here is an example object: https://4teamwork.slack.com/archives/C06US2QSCD8/p1732699211158489
We fix the lookup table update function to skip those principals.
For [TI-1540]
[TI-1540]: https://4teamwork.atlassian.net/browse/TI-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make reindex local roles lookup table more failsafe

---

changes/TI-1546.feature
changes/TI-1546.other
opengever/core/locales/de/LC_MESSAGES/plone.po
opengever/core/locales/en/LC_MESSAGES/plone.po
opengever/core/locales/fr/LC_MESSAGES/plone.po
opengever/core/locales/plone.pot
opengever/sharing/local_roles_lookup/exporter.py
opengever/sharing/tests/test_role_assignment_excel_export.py
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/participation/__init__.py

This PR improves the role assignment excel export by:
- translating the `portal_type` and the `role` values
- using the auto-filter feature for the table
the Report was introduced in #8091 
For [TI-1546]
[TI-1546]: https://4teamwork.atlassian.net/browse/TI-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Role assignment excel export improvements

---

changes/TI-1539.other
opengever/api/listing.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_listing_custom_fields.py
opengever/base/tests/test_default_values_for_types.py
opengever/testing/fixtures.py

**This PR:** 
Provide the Custom fileds on the `ListingGet` endpoint based on the listing name `dossiers` or `documents`.
It also update the test fixture schema so we add  more custom fields to the dossier schema.
Currently, the `@listing-endpoint` does not support filtering by custom fields of type `date` because the field mapper lacks knowledge of these fields. This PR addresses the issue by updating the `field mapper` to handle `date custom fields` for filtering.
For [TI-1539](https://4teamwork.atlassian.net/browse/TI-1539)
- API change:
- If breaking:
- Bug fixed:
- Further …

Extend listing endpoint to filter by custom field type (date)

---

changes/TI-1735.other
opengever/activity/sources.py
opengever/activity/tests/test_sources.py
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py

We introduced group and teams watchers in a previous PR: #7986  which allows the user to select a group or a team as a watcher. Currently, all teams within the OGDS are queried which is not the desired behavior. Each team is assigned to a specific Org-Unit. The watchers-source should respect this setting to only list teams of the current users org unit.
So this PR updates the sources to only list those teams instead of all teams across all admin units.
For [TI-1735]
[TI-1735]: https://4teamwork.atlassian.net/browse/TI-1735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Restrict team watchers source to the current org unit

---

changes/TI-1494.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/documents_sign.rst
opengever/api/tests/test_serializer.py
opengever/api/transition.py
opengever/document/tests/test_document_workflow.py
opengever/document/transition.py
opengever/sign/client.py
opengever/sign/pending_editor.py
opengever/sign/pending_signing_job.py
opengever/sign/sign.py
opengever/sign/tests/test_client.py
opengever/sign/tests/test_pending_editors.py
opengever/sign/tests/test_pending_signing_job.py
opengever/sign/tests/test_sign.py

This PR implements non signers sign requests.
With this PR it will be possible to pass `editors` which will later be able to manage signatories directly in the `skribble` UI.
We mainly address the Skribble feature: Create a signature request without initial signers: https://api-doc.skribble.com/#b6100136-63b3-4fd6-a703-3a0848a89c04
See for the ogsign implementation: https://github.com/4teamwork/ogsign/pull/12
For [TI-1494]
[TI-1494]: https://4teamwork.atlassian.net/browse/TI-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement non signers sign request

---

changes/TI-1494-2.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/documents_sign.rst
opengever/api/configure.zcml
opengever/api/sign.py
opengever/api/tests/test_sign.py
opengever/base/subscribers.py
opengever/sign/client.py
opengever/sign/pending_editor.py
opengever/sign/pending_signer.py
opengever/sign/pending_signing_job.py
opengever/sign/sign.py
opengever/sign/tests/test_client.py
opengever/sign/tests/test_pending_editors.py
opengever/sign/tests/test_pending_signer.py
opengever/sign/tests/test_pending_signing_job.py
opengever/sign/tests/test_sign.py

This PR introduces the `@update-pending-signing-job` endpoint and provides the `update_url` to the `sign` service which will use it to sync editors and signers from skribble to gever.
See related `ogsign`-PR: https://github.com/4teamwork/ogsign/pull/13 for the implementation there.
The PR adressses the `PATCH /<update_url>` section of this chart:
```
┌───────┐                          ┌────────┐                    ┌───────────┐
│       │ POST /signing-jobs/      │        │                    │           │
│       ├─────────────────────────►│        │                    │           │
│       │                          │        │ POST /convert      │           │
│       │                          │        ├───────────────────►│           │
│       │                          │ …
```

Pending job sync

---

changes/TI-1737.other
opengever/dossier/participations.py

Inactive users in kub shouldn't be able to be found in the "possible participants" search in Gever Dossiers. 
To correct this behaviour, the "only_active" in the KubClient was set to True and the behavior of "is_active" in KuB was corrected in the following PR: https://github.com/4teamwork/kub/pull/356
Before: (Pascal Reiss is an inactive user in KuB):
After:
For [TI-1737]
[TI-1737]: https://4teamwork.atlassian.net/browse/TI-1737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set is_active filter to true for possible participants

---

base-plone-4.3.x.cfg
base-testserver.cfg
bin/mtest
development.cfg

- explicitly use Python 2.7 in `bin/mtest` script.
- use Docker services for Sablon, PDFLaTeX and msgconvert in all tests.

Fix tests on new CI server

---

changes/TI-1570.other
opengever/base/addressblock/addressblock.py
opengever/base/addressblock/interfaces.py
opengever/base/addressblock/tests/test_address_formatting.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20250114101908_add_hide_salutation_feature_flag/registry.xml
opengever/core/upgrades/20250114101908_add_hide_salutation_feature_flag/upgrade.py

**This PR:**
Adds functionality to control the visibility of the salutation in address blocks based on a feature flag. The `hide_salutation` setting from the registry determines whether the salutation should be included in the formatted address. If the flag is enabled, the salutation is hidden; otherwise, it is shown as part of the address block.
For [TI-1570](https://4teamwork.atlassian.net/browse/TI-1570)
- API change:
- If breaking:
- Bug fixed:
[TI-1570]: …

Implement salutation visibility based on the hide_salutation flag

---

changes/TI-1796.other
opengever/workspaceclient/linked_workspaces.py

Since copying from workspace to dossier doesnt copy the related document, the 'relatedItems' field can be removed from the request.
For [TI-1796]
[TI-1796]: https://4teamwork.atlassian.net/browse/TI-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove relatedItems from request

---

changes/TI-1747.other
opengever/meeting/tabs/meetinglisting.py

**This PR:**
The meeting `title` is now also searchable. The current searchable column in the meeting list view is only the meeting `location`.
Users can now search using the meeting `title` along with the `location`
For [TI-1747](https://4teamwork.atlassian.net/browse/TI-1747)
_**Search by meeting title**_
Before :
https://github.com/user-attachments/assets/555364ba-5a29-4d39-8809-b71fec0e6fb2
After:
https://github.com/user-attachments/assets/b9651653-e717-428e-82a3-b87e9faeb672
-----
- API change:
- If breaking:
- Bug fixed:
- Change …

Enable searching by meeting title in  meeting listing view

---

changes/TI-1331.other
opengever/api/tests/test_complete_successor_task.py
opengever/api/tests/test_task_from_template.py
opengever/task/handlers.py
opengever/task/tests/test_task_from_template.py

**This PR:**
If we have a standard process for tasks, the current situation is that once a task is marked as erledigt, the next task will open automatically. This behavior is not ideal. With our new implementation, the next task will only open if the previous task is closed.
For [TI-1331](https://4teamwork.atlassian.net/browse/TI-1331)
- API change:
- If breaking:
- Bug fixed:
[TI-1331]: https://4teamwork.atlassian.net/browse/TI-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …

Implement auto-open of next task after closing the previous one

---

changes/TI-1333.other
docs/public/dev-manual/api/api_changelog.rst
docs/schema-dumps/opengever.task.task.schema.json
opengever/activity/tests/test_mail.py
opengever/api/forwarding.py
opengever/api/process.py
opengever/api/tests/test_task.py
opengever/api/tests/test_templatefolder.py
opengever/core/upgrades/20250113110216_update_task_text_field_to_rich_text/upgrade.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_task_sql_syncer.py
opengever/task/activities.py
opengever/task/task.py
opengever/task/tests/test_indexer.py
opengever/task/tests/test_task.py

**This PR:**
Changes `Task`  text field from a TextField to a RichTextField.
For [TI-1333](https://4teamwork.atlassian.net/browse/TI-1333)
**The UI related PR**=> [Provide WysiwgyEditor field for task](https://github.com/4teamwork/gever-ui/pull/2837) 
- API change:
[TI-1333]: https://4teamwork.atlassian.net/browse/TI-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change the task text field from Text field to RichText

---

changes/TI-1336-2.other
changes/TI-1336.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/workflow.rst
opengever/api/configure.zcml
opengever/api/tests/test_ui_actions.py
opengever/api/tests/test_workflow_bulk_transition.py
opengever/api/workflow_bulk_transitions.py
opengever/base/listing_actions.py
opengever/document/actions.py
opengever/document/tests/test_actions.py
opengever/dossier/actions.py
opengever/dossier/tests/test_actions.py
opengever/workflow/bulk_transition_information.py
opengever/workflow/tests/test_bulk_transition_information.py

This PR introduces the change_items_state UI action, allowing the rendering of a form for bulk workflow transitions.
Additionally, it implements a new endpoint, @workflow-bulk-transition-information, which provides transition details for the workflow associated with a given object. This information enables the UI to display available transition actions.
For [TI-1336]
- API change:
[TI-1336]: https://4teamwork.atlassian.net/browse/TI-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement actions and endpoints for bulk transitions

---

opengever/base/tests/test_transport.py
opengever/base/transport.py

This is a follow-up of #8105 
This PR fixes an issue where extracting task metadata for task transportation from one admin unit to another is no longer possible due the implementation of #8105 
Traceback:
```
2025-01-23T13:57:18 ERROR Zope.SiteErrorLog 1737637038.740.535046553442 https://dev.onegovgever.ch/fd/ordnungssystem/raumplanung-bau-und-verkehr/mobilitaet/velo-und-fussverkehr/dossier-3135/task-2917/@@transporter-extract-object-json
Module opengever.base.transport, line 147, in __call__
Module json, line 244, in dumps
Module json.encoder, line 207, in encode
Module json.encoder, line 270, in iterencode
Module …
```

Properly extract RichTextValue in object transportation

---

opengever/base/tests/test_transport.py
opengever/base/transport.py

Follow-Up of #8114 and #8105 
This PR properly unpacks rich text values after task transportation from one admin unit to another.
For [TI-1333]
[TI-1333]: https://4teamwork.atlassian.net/browse/TI-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fx task transportation unpack

---

.github/workflows/docker-image.yml

Improve building of Docker image:
- Use our self-hosted action runner which should be faster
- Use newer versions of Docker actions
- Allow running the action manually
- Build image for `master` branch with tag `edge` which can be used for deployment on dev systems.
- Only build ARM image for releases (tags) to have faster builds for `master` branch.
- Only build `lastest` tag if it's on the `master` branch. Should avoid overwriting `latest` with backport releases.

Use self-hosted action runner

---

changes/TI-1333.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_process.py
opengever/api/tests/test_tasktemplate.py
opengever/core/upgrades/20250127123059_update_task_template_text_field_to_rich_text/upgrade.py
opengever/tasktemplates/content/tasktemplate.py

This PR:
Change `task template` text field from `Text` to RichText Field.  
For [TI-1333](https://4teamwork.atlassian.net/browse/TI-1333)
related to the FE PR: https://github.com/4teamwork/gever-ui/pull/2844
- API change:
- If breaking:
- Bug fixed:
[TI-1333]: https://4teamwork.atlassian.net/browse/TI-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change the task template text field to RichtextField

---

changes/GH-8122.bugfix
docker/core/Dockerfile
docker/core/patches/p_a_theming_transform.py

Since upgrading the Docker base image to Alpine 3.20 (ogcore 2024.15.0 and later) the HTML parser used in plone.app.theming doesn't detect the correct encoding when parsing a response. As we always use UTF-8, we set the encoding manually.
Not sure what causes the error, it seems only to happen with newer Alpine versions.
The behavior can be reproduced with the following snippet, which should return 'UTF-8', but returns 'ISO-8859-1':
```python
>>> from lxml.html import HTMLParser
>>> parser = HTMLParser()
>>> parser.feed(b'<div><h2>Schlagw\xc3\xb6rter</h2></div>')
>>> parser.close().getroottree().docinfo.encoding
'ISO-8859-1'
```

Fix encoding issues in classic UI

---

changes/TI-1895.feature
changes/TI-1895.other
docs/public/dev-manual/api/listings.rst
opengever/api/listing_custom_fields.py
opengever/api/tests/test_listing_custom_fields.py
opengever/propertysheets/assignment.py
opengever/propertysheets/definition.py
opengever/propertysheets/tests/test_propertysheet_metaschema.py

**This PR:**
- Provides a new slot in the ListingCustomFieldsGet endpoint for folder_contents.
- Excludes dossier assignment from the property sheet when the workspace is active."
For [TI-1895](https://4teamwork.atlassian.net/browse/TI-1895)
- API change:
- If breaking:
- Bug fixed:
[TI-1895]: https://4teamwork.atlassian.net/browse/TI-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add folder_contents listing in the @listing-custom-fields endpoint

---

changes/TI-1333.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_process.py
opengever/api/tests/test_tasktemplate.py
opengever/core/upgrades/20250131155145_update_task_template_text_field_to_rich_text/upgrade.py
opengever/tasktemplates/content/tasktemplate.py

Reapply changes from PR [#8177](https://github.com/4teamwork/opengever.core/pull/8117) with fixes for E2E tests.
This PR reapplies the changes originally introduced in PR #8117, which were reverted  to fix broken E2E tests. The following adjustments have been made:
- Touched the upgrade step: `bin/upgrade touch opengever/core/upgrades/20250127123059_update_task_template_text_field_to_rich_text`.
This PR is linked to the Frontend PR: https://github.com/4teamwork/gever-ui/pull/2844 and should be merged only after all tests (backend and frontend) are green and approved.
Reference: PR [#8177](https://github.com/4teamwork/opengever.core/pull/8117)

Reapplying changes from PR #8117 causes E2E test failures

---

opengever/sign/pending_editor.py
opengever/sign/pending_signature.py
opengever/sign/pending_signing_job.py
opengever/sign/sign.py
opengever/sign/signatory.py
opengever/sign/signed_version.py
opengever/sign/storage.py
opengever/sign/tests/test_pending_editors.py
opengever/sign/tests/test_pending_signatures.py
opengever/sign/tests/test_pending_signing_job.py
opengever/sign/tests/test_sign.py
opengever/sign/tests/test_signatory.py
opengever/sign/tests/test_signed_version.py
opengever/sign/tests/test_storage.py

This PR refactors the sign module to no longer use persistent objects when dealing with signature data. See https://github.com/4teamwork/opengever.core/pull/8120#discussion_r1950529343 for more information.
To store the values, we now use json strings and we deserialize it back to objects when loading it from the annotations.
This should make future development easier and less error prone. 
For [TI-1495]
[TI-1495]: https://4teamwork.atlassian.net/browse/TI-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove persistent objects in sign module

---

changes/TI-1931.other
opengever/sign/client.py

This PR fixes an issue where gever is not properly raising http errors when communicating with ogsign.
For [TI-1931]
[TI-1931]: https://4teamwork.atlassian.net/browse/TI-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Properly raise http errors when communicating with ogsign

---

changes/TI-2078.bugfix
opengever/workspace/utils.py

Currently the username is returned. With this fix the userid will be returned which matters when using a non-legacy OGDS sync profile.
See also:
https://github.com/plone/Products.PlonePAS/blob/5.1.1/src/Products/PlonePAS/pas.py#L283
For [TI-2078](https://4teamwork.atlassian.net/browse/TI-2078)
[TI-2078]: https://4teamwork.atlassian.net/browse/TI-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix getting context member ids in workspace

---

changes/TI-2089.feature
opengever/dossier/browser/report.py
opengever/repository/browser/excel_export.py

This PR links the repository-folder path and the dossier titles of the corresponding exports.
For [TI-2089]
[TI-2089]: https://4teamwork.atlassian.net/browse/TI-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Link title/path of dossiers and repository folders exported as excel.

---

changes/TI-2113.other
opengever/latex/dossiertasks.py
opengever/latex/listing.py
opengever/latex/tests/test_dossiertasks.py

After providing the RichText field for the task, we encountered an issue with the `pdf-dossier-tasks` endpoint returning a `500 `error when accessing the description directly via `task.text`, which will no longer work with the rich text. We should be able to get the text (description) via `task.text.output`.
Since the `task history` also uses the same field `RichText`, we have an issue where, if the user has, for example, tables or other HTML tags in the history, the PDF is not displaying as expected—some fields get wrapped or disappear. After some debugging with @buchi , we fixed this problem by stripping the HTML from the history and displaying it as plain text.
For [TI-2113](https://4teamwork.atlassian.net/browse/TI-2113)
**After:** …

Fix pdf-dossier-tasks endpoint

---

opengever/core/testserver.py

Currently using the ogtestserver container fails after some time because there is no option to configure the redis_url of an already existing container. With this change we can use the testserver docker setup in ris as we used to before.

Fix for redis in testserver

---

changes/TI-1931-2.other
opengever/sign/client.py
opengever/sign/tests/test_client.py

Currently, the sign client implementation uses the current url to generate the callback urls of the sign service.
This only works if the sign service has access to this url. In case of local development or advanced production deployments, we need a static url which is available for the sign-service.
Currently, we have this issue in development. The sign service runs within a docker container but the gever backend is not. The `ogsign` service can't access gever by `localhost`. The URL should point to the host ip address:
``` 
SIGN_SERVICE_GEVER_URL http://172.16.0.1:8080/fd
```  
For [TI-1931]
[TI-1931]: https://4teamwork.atlassian.net/browse/TI-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

Sign service uses SIGN_SERVICE_GEVER_URL environment variable to construct the callback links.

---

changes/TI-1931-3.other
opengever/sign/client.py
opengever/sign/tests/test_client.py
opengever/sign/tests/test_sign.py

Multiple gever installations of the same gever admin unit network usually point to the same bumblebee server but uses a different app_id for each admin unit. Currently, `ogsign` configured its own bumblebee which makes it impossible to use one ogsign service for multiple gever admin units with different bumblebee apps.
Since ogsign-Version: `v2025.2.0`, we need to pass the bumblebee related configuration as part of the signing job creation. `ogsign` will then use these information to do the bumblebee requests.
This PR passes the the required bumblebee specific information to the ogsign service when creating the job.
This feature requres `ogsign >= 2025.2.0`. 
Related `ogsign`-PR: https://github.com/4teamwork/ogsign/pull/17
For [TI-1931] …

Provides bumblebee connection information to the ogsign service to enable multiple bumblebee apps.

---

opengever/core/testserver.py
opengever/sign/client.py
opengever/sign/sign.py

This PR makes the sign service client configurable. This allows us to use the `NullSignServiceClient` in e2e testing.
For [TI-1931]
[TI-1931]: https://4teamwork.atlassian.net/browse/TI-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make sign service client configurable

---

changes/TI-1363.bugfix
opengever/base/solr/fields.py
opengever/document/tests/test_reporter.py

This PR addresses an issue where custom fields with the same ID but different titles would raise an error when trying to export a list of such objects (excel-export) or by just fetching the `@listing` of such objects.
The fix removes the title from the equality comparison, allowing custom fields with the same ID to have different titles without causing errors. As a result, if multiple matches are found, the first match will be returned, and its title will be used in listings and exports.
The provided solution is a quick-fix. A more comprehensive solution would require a deeper refactoring. It should not be possible to have such fields in general. Means, there should be a field definition which can be assigned to slots. Currently, we add a field definition for each slot.
For [TI-1363] …

Fix error caused by differing titles in custom fields with the same ID

---

changes/GH-8142.other
docker/core/entrypoint.d/create_zope_conf.py

Allows us to run GEVER/teamraum in read-only mode.

Add support for read-only mode with Docker

---

changes/TI-2109.bugfix
opengever/task/browser/delegate/metadata.py
opengever/task/transition.py

Due to making the "Beschreibung" field in tasks into a RichText field, the backend schema for tasks was changed to accept Richtext. The RichTextDeserializer doesnt cannot deserialize null values which leads to 500 Error.
For [TI-2109]
[TI-2109]: https://4teamwork.atlassian.net/browse/TI-2109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow 'text' in MetaDataSchema to be None

---

changes/TI-2272.feature
opengever/api/actors.py
opengever/base/solr/fields.py
opengever/core/upgrades/20250327125737_reindex_committee_title_url/upgrade.py
opengever/meeting/configure.zcml
opengever/ogds/base/actor.py
opengever/ogds/base/tests/test_actor.py
opengever/ris/configure.zcml
opengever/ris/indexers.py
opengever/testing/builders/dx.py
solr-conf/managed-schema

Although the Header in the Proposal Listing was marked as "Committee"/"Gremium", what was actually displayed was the responsible field. Changes have been made to display the actual "committee". For the new actor-type "riscommittee" which is in the new SPV, the details and info was modified to show no-members and correct link in the SPV.
Before:
After:
For [TI-2272](https://4teamwork.atlassian.net/browse/TI-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[TI-2272]: https://4teamwork.atlassian.net/browse/TI-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show committee instead of responsible in Proposal Listing

---

opengever/core/upgrades/20250324140844_migrate_grant_role_manager_to_responsible_to_grant_dossier_manager_to_responsible_feature/upgrade.py

This is a follow-up PR of #8141 and fixes an issue in the upgradestep where we try to check the permission of the current dossier responsible. Every dossier should have a responsible. But it seems, that we have dossier without any responsible, maybe creaded manually by code.
For [TI-2137]
[TI-2137]: https://4teamwork.atlassian.net/browse/TI-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix upgradestep for grant dossier manager to responsible if there is no responsible

---

changes/TI-2135.other
opengever/api/tests/test_transfer_dossier.py
opengever/api/tests/test_ui_actions.py
opengever/api/transfer.py
opengever/base/context_actions.py
opengever/base/listing_actions.py
opengever/dossier/actions.py
opengever/dossier/tests/test_actions.py

This PR:
Provides a context and listing action to change the responsibility for the dossier and its related sub-dossiers.
For [TI-2135](https://4teamwork.atlassian.net/browse/TI-2135)
[TI-2135]: https://4teamwork.atlassian.net/browse/TI-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide actions to change dossier and sub-dossiers responsible

---

changes/TI-2137.other
opengever/core/upgrades/20250324140844_migrate_grant_role_manager_to_responsible_to_grant_dossier_manager_to_responsible_feature/upgrade.py

This is a follow-up PR of #8141 and fixes an issue in the upgradestep where we try to check the permission of the current dossier responsible.
There are users where the userid is not the username. `has_permission` will not find users by the username. This will fail for such users. We have to first get the user and the pass the user object to make it more failsafe.
For [TI-2137]
[TI-2137]: https://4teamwork.atlassian.net/browse/TI-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix upgradestep for grant dossier manager to responsible

---

changes/TI-2471.other
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/en/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/plone.pot

In the Status facet of the extended Search, the translations for document-state-shadow, document-state-draft, and others weren't properly translated.
This PR translates these in the backend using the already existing translation from the frontend.
For [TI-2471]
[TI-2471]: https://4teamwork.atlassian.net/browse/TI-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update document state translations

---

changes/TI-2438.bugfix
solr-conf/sync-solr.js

Previously, if a word document had a "}" character, it wouldn't be properly indexed. This issue has been fixed with this PR.
For [TI-2438]
[TI-2438]: https://4teamwork.atlassian.net/browse/TI-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make Solr Sync more robust

---

changes/TI-2422.bugfix
opengever/task/__init__.py
opengever/task/tests/test_localroles.py

This PR fixes an issue where temporary dossier permissions were not revoked if a task was cancelled while in the "in progress" state. The 'task-transition-in-progress-cancelled' transition is now treated as a final state, which ensures the proper cleanup of temporary permissions associated with the task.
For [TI-2422]
[TI-2422]: https://4teamwork.atlassian.net/browse/TI-2422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix revocation of temporary dossier permissions when a task is cancelled from the "in progress" state.

---

changes/TI-2432.bugfix
opengever/task/browser/transitioncontroller.py
opengever/task/tests/test_transitioncontroller.py

This fix reapplies a dropped commit (https://github.com/4teamwork/opengever.core/compare/7aea2c6d6078de117d4a0b8795deee737dd91d7b..def5b0cd054d76190c6bb5a274f74c79c6e198a0) which was inteded to merge when the cancel-feature has been implemented. 
According to the story specs: https://4teamwork.atlassian.net/browse/CA-4666, this should have never been possible.
Here is the original PR: https://github.com/4teamwork/opengever.core/pull/7575 which implemented the abort-feature.
For [TI-2432]
[TI-2432]: https://4teamwork.atlassian.net/browse/TI-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disallow to cancel tasks which are synced between multiple admin units.

---

changes/TI-1935.feature
changes/TI-1935.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/watchers.rst
opengever/api/permissions.zcml
opengever/api/tests/test_watchers.py
opengever/api/watchers.py
opengever/base/monkey/patches/readonly.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20250605111905_add_remove_any_watcher_permission/rolemap.xml
opengever/core/upgrades/20250605111905_add_remove_any_watcher_permission/upgrade.py

An admin, limited admin, or manager can now remove any watcher from an object via the @watchers endpoint. Previously, it was only possible to remove yourself, groups, or teams associated with the current user.
Since determining whether a specific watcher can be removed has become more complex, this PR introduces a new property in the @watchers response. This property indicates whether the current user is allowed to remove each watcher. The frontend can now rely on this property to determine whether to display a delete icon.
For [TI-1935]
- API change:
[TI-1935]: https://4teamwork.atlassian.net/browse/TI-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

Allow admins to delete any watcher

---

changes/TI-1935-2.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/watchers.rst
opengever/activity/sources.py
opengever/activity/tests/test_sources.py
opengever/api/tests/test_watchers.py

This PR restricts the `@possible-watchers` source by removing every possible watcher user which does not have at least view permission on the context. 
I overtook some of the implementation of the `VisibleUsersAndGroupsFilter` (https://github.com/4teamwork/opengever.core/blob/master/opengever/base/visible_users_and_groups_filter.py) to build the query.
For [TI-1935]
- API change:
[TI-1935]: https://4teamwork.atlassian.net/browse/TI-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Restrict possible watchers source

---

changes/TI-2442.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/listing.py
opengever/api/tests/test_listing.py
opengever/base/solr/fields.py
opengever/core/upgrades/20250613143257_add_document_version_count_index/upgrade.py
opengever/document/configure.zcml
opengever/document/indexers.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document-manual.pot
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_indexers.py
opengever/document/versioner.py
opengever/dossier/tests/test_move_items.py
solr-conf/managed-schema.xml

This PR:
- Indexes the document_version_count field in Solr.
- Include the field in the `@listing`
For [TI-2442](https://4teamwork.atlassian.net/browse/TI-2442)
[TI-2442]: https://4teamwork.atlassian.net/browse/TI-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add document version count to listing and index it

---

changes/TI-2673.bugfix
opengever/sharing/local_roles_lookup/exporter.py
opengever/sharing/tests/test_role_assignment_excel_export.py

This PR resolves an issue where exporting the role assignment report filtered by group results in an empty excel sheet.
For [TI-2673]
[TI-2673]: https://4teamwork.atlassian.net/browse/TI-2673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Properly resolve principals in the role assignment excel export

---

changes/TI-2730.feature
changes/TI-2730.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/listings.rst
opengever/api/tests/test_listing.py
opengever/base/configure.zcml
opengever/base/indexes.py
opengever/base/solr/fields.py
opengever/base/tests/test_indexers.py
opengever/core/upgrades/20250707134458_add_archival_value_index/upgrade.py
opengever/dossier/tests/test_move_items.py
solr-conf/managed-schema.xml

This PR adds a new solr index `archival_value`.
The `archival_value` is also added as a `ListingFiled` for the `@listing`-endpoint.
For [TI-2730]
[TI-2730]: https://4teamwork.atlassian.net/browse/TI-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add archival_value index

---

changes/TI-2854.bugfix
opengever/task/reminder/cronjobs.py
opengever/task/tests/test_reminder.py

Currently the `create_reminder_notifications` cronjob creates reminders for all admin units. In multi-tenant setups this is not what we want, as we have to make sure the cron job is only executed once for all tenants. With this change, reminders are only created for tasks of the current tenant (admin unit) and we can run the same cronjob for each tenant.
Fixes creating/sending multiple reminder notifications in multi-tenant setups.
For [TI-2854](https://4teamwork.atlassian.net/browse/TI-2854)
- API change:
- If breaking:
- Bug fixed:
- …

Only create task reminders for tasks in current admin unit

---

changes/TI-1604.bugfix
opengever/dossier/browser/report.py

Archival value column title and values were not properly translated in the Dossier Export. This problem is now fixed with this PR.
Before:
After:
For [TI-1608]
[TI-1608]: https://4teamwork.atlassian.net/browse/TI-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dossier report translations for archival_value column

---

changes/TI-3142.bugfix
opengever/document/indexers.py
opengever/document/tests/test_indexers.py

GEVER provides a feature to store a document as a PDF directly into a dossier:
This action sends a request to `bumblebee` to generate a PDF representation of the current document. Once ready, bumblebee uploads the PDF back to GEVER using a callback URL: [save_pdf_under_callback](https://github.com/4teamwork/opengever.core/blob/f43d66f955a23884e8998bd9b86f9eecc86fcb37/opengever/bumblebee/browser/configure.zcml#L62)
This callback is called anonymously by bumblebee. After storing the PDF, we trigger an `ObjectModifiedEvent` to reindex the document metadata.
**Why This Fails in Production**
In tests, this works fine due to the patching of `collective.indexing`:
- [Patch to immediately process the indexing queue](https://github.com/4teamwork/opengever.core/blob/master/opengever/testing/patch.py …

Fix PDF save callback issue with document_version_count Index

---

changes/TI-3167.other
opengever/api/tests/test_solrsearch.py
opengever/base/solr/contentlisting.py

This PR properly removes dangerous html tags from the solr listing document snippets.
We can't just search and replace reserved html characters and convert them into html entities (i.e. replacing < to &gt;) because the `snippets` includes text highlighting which is made with html.
We use the plone internal `safe_html` portal transform to fix it. This will remove dangerous tags which is what we want here.
For [TI-3167]
[TI-3167]: https://4teamwork.atlassian.net/browse/TI-3167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Escape html for solr listing document snippets.
