- versions.cfg
`zope.testrunner` `4.4.5` has changed the testing layer ordering which causes test isolation problems with `PloneTestCase` layers which are not isolating properly.
Therefore we pin down `zope.testrunner` for now. Eventually we will need to investigate further why were having layer isolation issues in our tests.
@deiferni
> Pin down zope.testrunner in tests to avoid layer isolation issues.

- opengever/dossier/tests/test_dossier.py
Otherwise this leads to disabled tabs (e.g. proposals) being present. This also helps fixing tests for the `opengever.zug` package.
> Check action condition while getting tabs for tests comparisons.

- docs/HISTORY.txt
- opengever/setup/browser/admin.py
- versions.cfg
This fixes an issue while developing policies locally for customers that are still on the 4.0 release.
Also backport https://github.com/4teamwork/opengever.core/pull/722 to fix failing tests.
> Make sure that an admin-unit is created before it is queried.

- docs/HISTORY.txt
- opengever/setup/sections/xlssource.py
- Raise `KeyError` if a value can't be found in the translation mapping for fields with a vocabulary, instead of just setting the translated value anyway.
- Add some more alternate spellings for the `archival_value` mapping.
Needs to be backported to `4.0-stable` and `4.1-stable`.
> Fix handling of mapped vocabulary terms in XlsSource

- versions.cfg
Backport PR #722 to [`4.1-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.1-stable)
> Backport "Pin down zope.testrunner in tests to avoid layer isolation issues." to 4.1-stable

- docs/HISTORY.txt
- opengever/base/browser/pasting_allowed.py
- opengever/base/tests/test_paste_items.py
Only show the "Paste" action in the menu if all objects in clipboard are of a type that is allowed to be added to the target container. Fixes #648 and #612.
Since this check is being done pretty much on every single request, it's rather performance critical.
I therefore inlined some code from `OFS.CopySupport` because the previous `cb_dataValid()` does nothing else than trying to decode the clipboard. So if we were to call that, and then decode the clipboard again to get to the clipboard objects' types we would do it twice.
> Only show "Paste" action if objects in clipboard are in allowed addable types of target container.

- docs/HISTORY.txt
- opengever/advancedsearch/advanced_search.py
- opengever/advancedsearch/tests/test_search.py
- opengever/base/browser/search.py
Allow filtering by min or max value instead of just by date ranges when
querying for dates. This allows a major simplification and eliminates several
code smells.
Fixes #671.
> Rewrite search/advanced search, especially date querying.

- docs/HISTORY.txt
- opengever/base/browser/pasting_allowed.py
- opengever/dossier/tests/test_move_items.py
This view is called on *every request*, and the checks may fail with a `KeyError` if an object is first copied, and then the same object is moved. Therefore we wrap all the checks in a `try..except` because this view must never fail.
> Wrap checks in is_pasting_allowed in a try..except for safety.

- docs/HISTORY.txt
- opengever/ogds/base/sort_helpers.py
- opengever/ogds/base/tests/test_sort_helpers.py
> Prevent early return or returning None by fixing indentation.

- docs/HISTORY.txt
- opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py
Disable `plonetheme.teamraum` `livesearch.js` to avoid doubled javascript action. This fixes the bug #681.
Additionally I've dropped the not used icon `<img>` tag. Because the livesearch use the sprite icon.
> Livesearch: Dropped not used icon <img> tag.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/browser/proposaloverview.py
- opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
- opengever/meeting/command.py
- opengever/meeting/container.py
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4210.py
Creates history entries for the following proposal-related actions:
- creating a proposal
- submitting a proposal
- scheduling a proposal
- removing a proposal from schedule
- submit documents/additional documents
- update submitted documents
It looks like this:
Note that the history should contain addtitional information for some actions and that icons are missing. These todos are tracked in #728.
> Show proposal history on proposal overview.

- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/model/proposalhistory.py
Depends on 4teamwork/plonetheme.teamraum#277
Wrap submit input with span for displaying icon next to the button.
Change proposal history class for using new icon from plonetheme.teamraum.
> Use meeting icons from plonetheme.teamraum.

- docs/HISTORY.txt
- opengever/meeting/browser/committeecontainertabs.py
- opengever/meeting/browser/committeetabs.py
- opengever/meeting/browser/meetings/preprotocol.py
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/templates/no_selection.pt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/profiles/default/types/opengever.meeting.proposal.xml
- opengever/meeting/proposal.py
- opengever/meeting/tabs/proposallisting.py
- opengever/meeting/tabs/submittedproposallisting.py
- opengever/meeting/tests/test_committee_container.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_proposal_listings.py
- Disable selection links for listings without checkbox column.
- Extend proposal listing columns, with the new columns (state, comittee, proposed action)
- Added tests for the Proposal and the SumittedProposalListing
Additionally I made the `proposed_action` field also available in the proposal add- and edit-form
> Meeting listings improvements

- opengever/meeting/command.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4213.py
:warning: *please merge after #774, i need to rebase and adapt at least one test for changes introduced there*
Currently the proposal history is very basic and does not display valuable information. This PR adds the following information to the proposal history:
- For document related entries display the document name and document version
- For meeting related entries display the meeting title
> Display more details in proposal history.

- opengever/meeting/browser/meetings/preprotocol.py
- opengever/meeting/form.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_members.py
- opengever/meeting/tests/test_memberships.py
- opengever/meeting/tests/test_preprotocol.py
Currently when creating/editing sql-model driven objects no confirmation messages are shown. This PR adds these messages.
> Show portal messages when creating/editing content.

- docs/HISTORY.txt
- opengever/base/redirector.py
- opengever/base/tests/test_redirector.py
Accessing sessions causes the transaction to be a write, which is not very nice.
Required for #754
> Rewrite Redirector adapter to use cookies instead of sessions.

- README.rst
- development.cfg
- docs/HISTORY.txt
This change switches to **PostgreSQL** as the default DB for local development.
If required, the OGDS DB configuration can be switched back to MySQL by uncommenting the following lines in `development.cfg`:
```ini
ogds-dsn = ${buildout:ogds-dsn-mysql}
ogds-db-driver = MySQL-python
```
Other than installing and setting up PostgreSQL [as documented in the README](https://github.com/4teamwork/opengever.core/blob/1d2c7d1c3f0c497ac922d9f2eaaa0aba5551e97c/README.rst#sql-database) no other action is required.
> Switch to PostgreSQL for local development.

- docs/HISTORY.txt
- opengever/task/successor.py
- opengever/task/tests/test_successor.py
When accepting multiclient tasks, the `issuing_org_unit` of the successors is
wrongly be set to the current_org_unit instead of keeping the issuing_org_unit
from the predecessor. Therefore we reset the `issuing_org_unit` when setting the
predecessor with the SuccessorTaskController.
> Automatically set predecessor's issuing_org_unit on successor.

- docs/HISTORY.txt
- opengever/dossier/behaviors/participation.py
This fixes an issue with ie10 and ie11 where no selection could be made and
improves usability.
The new widget looks like this:
Before it looked like so:
> Use checkbox widget to select participations roles.

- docs/HISTORY.txt
- opengever/task/browser/overview.py
- opengever/task/tests/test_overview.py
The `_format_date` did not format the given date, but format the tasks deadline.
> Fixed date_of_completion display in task overview.

- test-plone-4.2.x.cfg
Because the newest version of ftw.recipe.translations pins down `six` to <= `1.2.0`.
Because we don't need the `lovely.buildouthttp` for testing the package I've dropped the including.
In production buildouts we should use the `isotoma` plugin instead of `lovely.buildouthttp`.
@lukasgraf
> Remove lovely.buildouthttp from test-plone-4.2.x.cfg.

- docs/HISTORY.txt
- opengever/base/tests/test_pathbar.py
- opengever/meeting/browser/committeetabs.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/meeting.py
- opengever/meeting/model/query.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/tabs/meetinglisting.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_committee_container.py
- opengever/meeting/tests/test_committee_overview.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_meeting_query.py
- opengever/meeting/tests/test_preprotocol.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/tests/test_unit_meeting.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4214.py
- opengever/testing/__init__.py
- opengever/testing/testbrowser_datetime_widget.py
Because Oracle has no Time data type, we change the Date column `date`  and the two time fields (`start_time` and `end_time`) into two DateTime columns `start` and `end`.
> Replaced three date/time fields in favour of two datetime fields.

- docs/HISTORY.txt
- opengever/core/upgrade.py
- opengever/meeting/model/submitteddocument.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4215.py
Because of oracle's limitation to 30 chars (ORA-00972) we have to use shorter names for our UniqueConstraints.
> Rename UniqueConstraints names of the SubmittedDocument table.

- docs/HISTORY.txt
- opengever/core/upgrade.py
- setup.py
If the tracking table is created for the first time, it's not visible in `metadata` until the transaction has been committed.
Therefore we need to have a method that tries to fetch an existing tracking table and return it, or if it doesn't exist yet, creates it and then returns the created table.
Returning the table created by op.create_table requires `alembic >= 0.7.0`.
> SchemaMigration: Fix tracking table creation for DBs supporting transactional DDL

- docs/HISTORY.txt
- opengever/core/tests/test_upgrade.py
- opengever/core/upgrade.py
- opengever/meeting/handlers.py
- opengever/meeting/upgrades/to4200.py
- opengever/meeting/upgrades/to4203.py
- opengever/meeting/upgrades/to4208.py
- opengever/meeting/upgrades/to4214.py
Use `IdempotentOperations` only for MySQL, i.e. when no transactional DDL is available. Don't use `IdempotentOperations` any more when transactional DDL is available (e.g. for oracle and postgres). Improve `IdempotentOperations` - always update metadata when performing database changes.
*Note, currently not all `IdempotentOperations` methods are overwritten to be idempotent. This should be done on demand - we want to drop MySQL support sooner or later.*
Furthermore fix some existing migrations to work with MySQL and PostgreSQL (and Oracle). Don't use metadata tables for data migrations any more but create local table definitions using [sqlalchemy expressions](http://docs.sqlalchemy.org/en/latest/core/selectable.html).
> Improve/fix schema migrations, support transactional and non-transactional DBMS.

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_sql_task.py
Added `task-state-resolved` to the overdue independent states, because already resolved tasks should not be flaged as overdue.
> Do not show resolved tasks as overdue.

- docs/HISTORY.txt
- opengever/setup/deploy.py
This avoids problems when returning from a branch ahead of master which defines more tables. It also drops the upgrade-version tracking table.
> Drop all SQL-tables during dev-setup.

- docs/HISTORY.txt
- opengever/usermigration/ogds.py
- opengever/usermigration/tests/test_ogds_migrator.py
Add `OGDSMigrator` that migrates `users_group` and `inbox group` for `OrgUnits` in OGDS SQL tables (to be used with `ftw.usermigration`).
Needs to be [backported to all `4.x-stable` branches](https://github.com/4teamwork/opengever.core/issues/804).
> Add OGDSMigrator that migrates users and inbox groups in OGDS SQL tables

- docs/HISTORY.txt
- opengever/usermigration/dictstorage.py
- opengever/usermigration/tests/test_dictstorage_migrator.py
Add `DictstorageMigrator` that migrates user IDs in dictstorage keys in SQL (to be used with `ftw.usermigration`).
The approach is the following:
The migrator will replace the first occurence of the old user ID *from the right* if the key ends with 
`-olduserid`.
This approach will fail in the unlikely case that there exists a user ID that is a substring of another user ID with a dash (and that second user also has dictstorage entries).
For example: We have two users `user42` and `other-user42`, and `user42` gets mapped to `newuser42`. The keys of the second user will then be replaced with the possibly invalid user ID `other-newuser42`.
Needs to be [backported to all `4.x-stable` branches](https://github.com/4teamwork/opengever.core/issues/804).
> Add DictstorageMigrator that migrates user IDs in dictstorage keys (in SQL)

- docs/HISTORY.txt
- opengever/usermigration/dictstorage.py
- opengever/usermigration/tests/test_dictstorage_migrator.py
Backport PR #819 to [`4.0-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.0-stable).
> Backport "Add DictstorageMigrator that migrates user IDs in dictstorage keys (in SQL)" to 4.0-stable

- docs/HISTORY.txt
- opengever/usermigration/dictstorage.py
- opengever/usermigration/tests/test_dictstorage_migrator.py
Backport PR #819 to [`4.1-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.1-stable).
> Backport "Add DictstorageMigrator that migrates user IDs in dictstorage keys (in SQL)" to 4.1-stable

- docs/HISTORY.txt
- opengever/usermigration/dictstorage.py
- opengever/usermigration/tests/test_dictstorage_migrator.py
Backport PR #819 to [`4.2-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.2-stable).
> Backport "Add DictstorageMigrator that migrates user IDs in dictstorage keys (in SQL)" to 4.2-stable

- docs/HISTORY.txt
- opengever/usermigration/dictstorage.py
- opengever/usermigration/tests/test_dictstorage_migrator.py
Backport PR #819 to [`4.3-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.3-stable).
> Backport "Add DictstorageMigrator that migrates user IDs in dictstorage keys (in SQL)" to 4.3-stable

- docs/HISTORY.txt
- opengever/usermigration/dossier.py
- opengever/usermigration/ogds.py
- opengever/usermigration/tests/test_dossier_migrator.py
Implement migrating participants in `DossierMigrator`.
Participations are stored as persistent `Participation` objects in the dossier's annotations. The `Participation` objects have a `contact` attribute that contains a string with a user ID of an OGDS user (or a contact, not relevant for this case).
I also sneaked in a commit that adds the `strict` keyword argument previously missing from the `OGDSMigrator`.
Needs to be [backported to all `4.x-stable` branches](https://github.com/4teamwork/opengever.core/issues/804).
> Implement migrating participants in DossierMigrator.

- docs/HISTORY.txt
- opengever/base/tests/test_selector.py
- opengever/base/viewlets/configure.zcml
- opengever/base/viewlets/language_selector.pt
- opengever/base/viewlets/selector.py
- opengever/examplecontent/profiles/default/metadata.xml
- opengever/examplecontent/profiles/default/portal_languages.xml
- opengever/examplecontent/upgrades/configure.zcml
- opengever/examplecontent/upgrades/profiles/4300/portal_languages.xml
The styling is implemented in the https://github.com/4teamwork/plonetheme.teamraum/pull/286 PR.
Additionally I've added french to the supported languages in the examplecontent profile  to make sure that the language selector is activated during development.
> Customize Language Selector viewlet to display it as a menu.

- opengever/activity/mail.py
- opengever/activity/mail_templates/notification.pt
- Make sure that links in the activity summary are displayed correctly.
- Make sure that the activity kind is translated also in the mails. (The final implementation should configure a default language for each watcher. But for the moment (prototype) it's ok like that).
> Notification mail fixes (translations and html structure)

- docs/HISTORY.txt
- opengever/mail/mail.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/profiles/default/workflows.xml
- opengever/meeting/profiles/default/workflows/opengever_submitted_proposal_workflow/definition.xml
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/profiles/4300/workflows.xml
- opengever/meeting/upgrades/profiles/4300/workflows/opengever_submitted_proposal_workflow/definition.xml
- opengever/meeting/upgrades/to4300.py
- Add missing workflow for `SubmittedProposal`, allow adding `ftw.mail.mail`
- Add initial version to mails, allow tracking as `SubmittedDocument`
> Fix submitting mails with proposals

- docs/HISTORY.txt
- opengever/core/upgrade.py
The type parameter is now named type_ (see http://alembic.readthedocs.org/en/rel_0_6/ops.html#alembic.operations.Operations.drop_constraint.params.type_).
> Made DeactivatedFKConstraint compatible with newer alembic versions.

- docs/HISTORY.txt
- opengever/base/browser/resources/opengever.css
The css fonts adjustments in https://github.com/4teamwork/plonetheme.teamraum/pull/284, broke up the icons in the treeportlet. This PR in collaboration with https://github.com/4teamwork/plonetheme.teamraum/pull/288, fix this.
@lukasgraf please have a look ... 
--- 
I don't like to splitting up the theming stuff in to two separate packages, but this should be a separate discussion/change.
> Fix icon for the treeporlet favorite functionality.

- README.rst
Document installation of `bundler`, which is necessary for local development, in our README.
> Document `bundler` installation in README.

- docs/HISTORY.txt
- opengever/base/protect.py
Fixes #838.
The problem was caused by ftw.footer's FooterViewlet creating
portlet-assignments that are stored in annotations. This causes a write for the
first request on context.
> CSRF: always allow object annotations to be written.

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/browser/confirm.pt
- opengever/base/browser/resources/opengever.css
- opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/opengever.base.pot
Customize the CSRF confirmation page `@@confirm-action` and add German translations.
- Fix the template: Use `fill-slot` instead of `define-slot` to fill title and description slots properly
- Make the messages in the template translatable
- Hide byline via CSS
- Provide German translations
@phgross
> Customize CSRF confirmation page and add German translations.

- docs/HISTORY.txt
- opengever/core/upgrade.py
- opengever/globalindex/upgrades/to4003.py
- opengever/meeting/upgrades/to4216.py
I've adjusted some of our existing SchemaMigration because of problems I've run into while updating a GEVER installation from release `2.7.x` to `3.3`.
@lukasgraf please have a look.
> Made different SchemaMigration Upgradesteps more robust.

- opengever/meeting/committee.py
- opengever/meeting/committeecontainer.py
- opengever/meeting/sources.py
- opengever/meeting/tests/test_committee.py
- opengever/meeting/tests/test_excerpt.py
- opengever/meeting/tests/test_preprotocol.py
- opengever/meeting/tests/test_protocol.py
Make sablon templates configurable per `Committee`. This configuration is optional. The templates defined on a `CommitteeContainer` will still be mandatory and act as fallback.
> Allow configuring sablon templates per committee.

- docs/HISTORY.txt
- opengever/base/behaviors/utils.py
- opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
- opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
- opengever/base/locales/ftw.tabbedview.pot
- opengever/base/profiles/default/metadata.xml
- opengever/base/profiles/default/propertiestool.xml
- opengever/base/tests/test_paste_items.py
- opengever/base/upgrades/configure.zcml
- opengever/base/upgrades/profiles/4300/propertiestool.xml
- opengever/base/viewlets/download.py
- opengever/core/testing.py
- opengever/dossier/menu.py
- opengever/dossier/profiles/default/metadata.xml
- opengever/dossier/profiles/default/types/opengever.dossier.templatedossier.xml
- opengever/dossier/templatedossier/tabs.py
- opengever/dossier/tests/test_templatedossier.py
- opengever/dossier/upgrades/configure.zcml
- opengever/dossier/upgrades/to4301.py
- opengever/meeting/browser/meetings/excerpt.py
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/sablontemplate.py
- opengever/meeting/tests/test_download_sablon_template.py
- opengever/repository/tests/test_deletion.py
- opengever/tabbedview/browser/tabs.py
- Display a separate tab for sablon templates on template-dossiers. Also make sablon templates visible in Trash.
- Drop our implementation of `PrimaryFieldInfo`, i has been implemented in `plone.dextertity` in the meantime.
Also fix #864, #839, #868 and #866.
> Add sablon template tab and some bugfixes

- docs/HISTORY.txt
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/tests/test_dossier_listing.py
Inheriting from the Dossier tab instead of inherit from the BaseDossiersTab
class, includes the default dossier statefilter.
Fixes #720.
Feature flag is not necessary in my opinion: The idea was given the thumbs up (https://feedback.onegovgever.ch/t/abgeschlossene-subdossier-ausblenden-filterbar-machen/75)
> Activate statefilter for subdossier listings.

- docs/HISTORY.txt
- opengever/base/browser/navigation.py
- opengever/base/tests/test_navigation.py
- opengever/base/utils.py
This allows us to display language dependent content in the Treeportlet. As we do for some customers.
@lukasgraf please have a look
> Treeportlet: extend caching parameters with current language code.

- docs/HISTORY.txt
- opengever/base/protect.py
On current `master` the first request after installing `ftw.footer` results in a redirect loop on most views, including the Plone site root.
This is because the context portlet assignments in the context's annotations gets modified (not the annotations themselves, those are already whitelisted). Because the respective viewlet also gets rendered on the `@@confirm-action` view, this causes the transaction to be modified on the `@@confirm-action` view, which triggers another confirmation, etc.. The results is is a redirect loop that the browser eventually needs to detect and cancel.
This PR addresses three things:
- It fixes the current **trigger** for the problem, which are **context portlet assignments**. Those are now whitelisted globally for writes.
- It **rolls back the transaction** …
> Fix redirect loops when transaction is modified on @@confirm-action view

- docs/HISTORY.txt
- opengever/document/browser/overview.py
- opengever/document/browser/overview_templates/overview.pt
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_overview.py
- opengever/meeting/browser/documents/submit.py
- opengever/meeting/model/proposal.py
- opengever/meeting/tests/test_submit_additional_documents.py
- opengever/testing/test_case.py
Also display a link to directly update the document in its proposal when it is
outdated.
> Display submitted-to proposals (and document version) on document overview.

- docs/HISTORY.txt
- opengever/base/subscribers.py
We have to initialize the annotations on every object. To avoid CSRF protection messages on first access of newly created objects, which haven't accessed the annotations during the creation process.
Because the PortletAssignments, for example `ftw.footer` portlets, are written to the objects annotations.
So if the annotations haven't been already accessed, the `AttributeAnnotations` mixin will create the `__annotations__` attribute on the object. This means that not the annotations are marked as changed but rather the object itself. And the we can't whitelist the object itself.
@deiferni @jone @lukasgraf
> Initialize annotations during object creation, to avoid CSRF messages on first object access.

- opengever/policy/base/profiles/default/metadata.xml
- opengever/policy/base/upgrades/configure.zcml
- opengever/policy/base/upgrades/to4300.py
This change is a follow up of #883.
Installing the `ftw.footer` although the package is already installed is not a problem.
@lukasgraf as discussed
> Added upgradestep which installs the `ftw.footer` profile.

- docs/HISTORY.txt
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
- opengever/activity/mail_templates/notification.pt
- opengever/activity/viewlets/notification.pt
- opengever/task/activities.py
- Added missing translations.
- Make sure the `tasktype` in the activity description is translated.
> Fixed and update opengever.activity translations

- docs/HISTORY.txt
- opengever/activity/browser/configure.zcml
- opengever/activity/browser/views.py
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
- opengever/activity/tests/test_notification_viewlet.py
- opengever/activity/tests/test_views.py
- opengever/activity/viewlets/notification.pt
- opengever/activity/viewlets/notification.py
- opengever/tabbedview/browser/personal_overview.py
- opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/opengever.tabbedview.pot
- opengever/tabbedview/tests/test_personaloverview.py
Move MyNotifications listing to the PersonalOverview:
NotificationViewlet: Display message when no unread notitifications exists:
@lukasgraf / @deiferni please have a look ... 
---
Styling will follow in a separate PR in plonetheme.teamraum
> Notification overview and viewlet improvements.

- opengever/base/browser/configure.zcml
- opengever/base/overrides.zcml
- opengever/base/tests/test_ploneform_macros.py
Currently the `ploneform-macros` view is overwritten to fix a bug with displaying status messages. Unfortunately the overwrite does not work reliably. This PR moves the overwrite to `overrides.zcml` to make sure it works correctly.
> Fix overwriting ploneform-macros

- opengever/examplecontent/hooks.py
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_protocol_json_data.py
This PR fixes missing agendaitem titles in sablon templates for agendaitems that are attached to a protocol.
It also fixes an issue with initial meeting content where an invalid template was created from non-unicode text.
*I think a changelog entry is not not necessary since recently introduced additions are fixed*
> Fix missing agendaitem title in sablon templates.

- docs/HISTORY.txt
- opengever/ogds/base/browser/userdetails_templates/userdetails.pt
According changes in https://github.com/4teamwork/plonetheme.teamraum/pull/302
@lukasgraf please have a look.
> Fixed userdetails icons for group listings.

- docs/HISTORY.txt
- opengever/activity/model/__init__.py
- opengever/base/model.py
- opengever/base/tests/test_database_table_declarations.py
- opengever/core/upgrade.py
- opengever/globalindex/model/__init__.py
- opengever/meeting/model/__init__.py
- opengever/meeting/upgrades/to4216.py
- opengever/meeting/upgrades/to4302.py
- opengever/policy/base/upgrades/to4200.py
- opengever/policy/base/upgrades/to4201.py
This PR addresses the following migration issues:
- Fix opengever.policy.base upgrades, limit created tables to installed package.
- Add idempotent MySQL implementations for creating/dropping indices and dropping tables.
- Drop unnecessary/broken statements from migrations.
- Drop a temporary table after the migration is finished.
> Fix upgrades for PostgreSQL/MySQL

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/browser/resources/meeting.js
- opengever/meeting/browser/resources/protocol.js
- opengever/meeting/browser/resources/sticky_heading.js
- opengever/meeting/model/agendaitem.py
- opengever/meeting/profiles/default/jsregistry.xml
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/tests/test_excerpt.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/profiles/4306/jsregistry.xml
Implement scrollspy upon sticky headings. Scrollspy provides the ability
to switch between anchors in a huge protocol so the user wont lose the
focus.
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/303
> Protocol visual improvements.

- opengever/meeting/browser/resources/protocol.js
- opengever/meeting/browser/resources/sticky_heading.js
The offset of the sticky headings are calculated once at startup based
on the DOM elements. When the content is getting higher, the position is
no longer valid because the offset is still referring to the
relative positioned elements. So a clone of each heading is being generated. When scrolling,
just the clone is being positioned relative. The offset is calculated
based on the static positioned original heading which has the correct
offset in the DOM.
> Use clones for headings.

- docs/HISTORY.txt
- opengever/testing/helpers.py
- opengever/trash/tests/test_trash.py
- opengever/trash/trash.py
Fixes #511.
Additionally I've completely reworked the trash tests, using `ftw.builder` and `ftw.testbrowser`.
> Redirect back to documents tab instead of trash tab, after trashing documents.

- opengever/setup/browser/admin.py
Deployment/LDAP-Profile titles can contain non-ascii characters. Currently they are not installable, this PR fixes that issue.
> Fix opengever setup for non-ascii characters.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/handlers.py
- opengever/dossier/tests/test_base.py
- opengever/dossier/utils.py
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_task_sql_syncer.py
- opengever/inbox/inbox.py
- opengever/inbox/tests/test_inbox.py
- opengever/task/task.py
- opengever/task/tests/test_task.py
- Make sure that task's `reference_number` is updated in sql after moving the container: Because we can't control the order of event handlers, we have to sync all containing tasks manually, if the reference number of the dossier or subdossier has changed.
- Reworked task's `get_dossier_sequence_number` method: Drop magic implementation using the catalog and replaced it with a simple implementation which uses acquisition to get the containing dossier and the `ISequenceNumber` adapter to get the number.
Fixes #802 
@lukasgraf please have a look ..
> Fixed sql task synchronisation when task gets moved.

- docs/HISTORY.txt
- opengever/activity/__init__.py
- opengever/meeting/__init__.py
Calling the feature_flag methods (`is_activity_feature_enabled` etc.) should not fail if the corresponding registry entry is missing and only return False instead.
Fixes #909 
> Made featureflags (activity, meeting) more robust.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/menu.py
- opengever/dossier/profiles/default/metadata.xml
- opengever/dossier/profiles/default/types/opengever.dossier.templatedossier.xml
- opengever/dossier/templatedossier/__init__.py
- opengever/dossier/templatedossier/templatedossier.py
- opengever/dossier/tests/test_dossier.py
- opengever/dossier/upgrades/configure.zcml
- opengever/dossier/upgrades/profiles/4303/types/opengever.dossier.templatedossier.xml
- opengever/dossier/upgrades/to4303.py
Currently meeting types only get filtered in the add menu, but they are still in the allowedContentTypes and can be added through url-guessing. This PR changes this behaviour and allows or restricts meeting content in dossiers based on whether the meeting feature is enabled.
Closes #907.
> Restrict allowed dossier meeting content in ConstrainTypesDecider.

- opengever/activity/center.py
- opengever/base/tests/test_download_viewlet.py
- opengever/document/tests/test_download.py
- opengever/document/tests/test_forms.py
- opengever/document/tests/test_overview.py
- opengever/document/tests/test_title_filename_syncer.py
- opengever/inbox/tests/test_activities.py
- opengever/mail/tests/test_senddocument.py
- opengever/meeting/tests/test_download_sablon_template.py
- opengever/meeting/tests/test_meeting_view.py
- opengever/task/browser/accept/utils.py
- opengever/task/handlers.py
- opengever/task/tests/test_activities.py
- opengever/task/tests/test_indexer.py
- opengever/task/tests/test_statesyncer.py
- opengever/task/tests/test_task.py
- opengever/task/tests/test_workflow.py
- opengever/task/util.py
- opengever/testing/builders/dx.py
Das Benachrichtigungssystem soll auch Predecessor/Successor Paare richtig behandeln. Das heisst das die Benutzer jeweils auf die Richtige Seite des Paares landen. Grundsätzlich gilt: Der Auftraggeber wird auf den Predecessor, der Auftragnehmer auf den Successor verlinkt.
Damit wir nicht für alle Aktivitäten, eine spezielle Behandlung für AdminUnit übergreifende Aufgaben implementieren müssen, werden nur die die Watchers von Predecessor/Successor Paare entsprechend angepasst.
**AdminUnit übergreifende Aufgaben:**
* Der Auftraggeber überwacht nach wie vor den Predecessor.
* Der Auftragnehmer überwacht neu nur noch den Successor.
**Weiterleitung einem Dossier zuweisen:**
* Der Auftraggeber und Auftragnehmer überwachen die neu erstellte Aufgabe
* Die Watchers der Weiterleitung werden nicht …
> Implement notification handling for predecessor/successor pairs

- docs/HISTORY.txt
- opengever/ogds/base/Extensions/plugins.py
- opengever/ogds/base/tests/test_plugin.py
Remote Requests werden nur für intern (zwischen zwei GEVER Mandanten) für die mandantenübergreifende Zusammenarbeit verwendet. Solche Requests werden über unser PAS Plugin authentisiert, CSRF Protection ist deshalb für solche Requests nicht notwendig. Fixes #924.
> Disable CSRF protection for remote requests.

- docs/HISTORY.txt
- opengever/tabbedview/browser/tabs.py
Aufgaben sollten nicht kopiert werden können.
@lukasgraf bitte reviewen.
> Disable copy action in task listings.

- opengever/dossier/handlers.py
With the change of #913 we broke up the Plonesite removing, because the ObjectRemovedEvent inherit from the ObjectMovedEvent. This PR fix this problem.
@lukasgraf
> Ignore IObjectRemovedEvents in saveReferenceNumberPrefix handler.

- docs/HISTORY.txt
- opengever/activity/model/activity.py
- opengever/activity/model/notification.py
- opengever/activity/model/resource.py
- opengever/activity/model/settings.py
- opengever/activity/model/watcher.py
- opengever/activity/profiles/default/metadata.xml
- opengever/activity/upgrades/configure.zcml
- opengever/activity/upgrades/to4303.py
Add explicit Sequence to enable of auto-incrementing for oracle. Also make
server-side tables/sequences consistent with other model definitions for
Postgres.
Closes #927.
> Unify definition of auto-incrementing SQL columns.

- docs/HISTORY.txt
- opengever/meeting/upgrades/to4200.py
- opengever/meeting/upgrades/to4203.py
- opengever/meeting/upgrades/to4208.py
- opengever/meeting/upgrades/to4214.py
- opengever/meeting/upgrades/to4215.py
- opengever/policy/base/upgrades/to4201.py
Eine Upgrade auf einer Testinstallation mit Oracle als OGDS DB hat noch einige Probleme bei  Schemamigrationen aufgezeigt. 
Die meisten Probleme traten aufgrund von Oracle Eigenheiten auf:
* Oracle unterstützt Time als datatype nicht.
* Namen von Indexes sind auf 30 Zeichen limitiert
* Unnötige Semicolons in Queries entfernt.
Zudem hat sich auch gezeigt das die Reihenfolge im Acitvity Installation Upgradestep angepasst werden muss, da der Profilehook bereits die Activity Tables benötigt.
@lukasgraf @deiferni bitte reviewn.
> Meeting SchemaMigrations: Made upgrades Oracle compatible.

- opengever/activity/model/activity.py
- opengever/activity/model/resource.py
- opengever/activity/model/watcher.py
- opengever/activity/profiles/default/metadata.xml
- opengever/activity/upgrades/configure.zcml
- opengever/activity/upgrades/to4304.py
- opengever/contact/contact.py
- opengever/globalindex/model/__init__.py
- opengever/globalindex/model/task.py
- opengever/globalindex/profiles/default/metadata.xml
- opengever/globalindex/upgrades/configure.zcml
- opengever/globalindex/upgrades/to4301.py
- opengever/meeting/browser/members.py
- opengever/meeting/model/committee.py
- opengever/meeting/model/generateddocument.py
- opengever/meeting/model/meeting.py
- opengever/meeting/model/member.py
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/model/submitteddocument.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4308.py
- opengever/ogds/base/interfaces.py
- opengever/ogds/base/profiles/default/metadata.xml
- opengever/ogds/base/upgrades/configure.zcml
- opengever/ogds/base/upgrades/to4301.py
- opengever/repository/behaviors/responsibleorg.py
- opengever/setup/meta.py
This PR harmonizes column lengths for SQL models within SQL as well as with Plone models by extracting lengths for common column types into constants.
PR https://github.com/4teamwork/opengever.ogds.models/pull/30 needs to be merged first.
(Changelog will be added once review is complete to avoid rebase hell)
Fixes #893.
> Harmonize SQL column lengths

- docs/HISTORY.txt
- opengever/tabbedview/browser/sqltablelisting.py
This allows SQLAlchemy to properly quote column identifiers depending on the dialect (see #957).
While this fixes the immediate problem regarding ordering in table listings, we still should avoid using reserved keywords as identifiers, therefore I'm still leaving #957 open.
> SqlTableSource: Wrap `sort_on` in a ColumnClause when extending query with ordering

- sources.cfg
- versions.cfg
- Update development-packages after finalizing release 3.3.	
- Use newly created develop kgs in the test buildout (see https://github.com/4teamwork/kgs/pull/74 for more information).
@lukasgraf 
:warning: https://github.com/4teamwork/kgs/pull/74 has to be merged first
> Finalize Release 3.3

- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob
This is done automatically by deploy.py and thus an unnecessary duplication.
> Don't configure current_unit_id in policy templates.

- docs/HISTORY.txt
- opengever/base/tests/test_navigation.py
- opengever/dossier/base.py
- opengever/dossier/browser/configure.zcml
- opengever/dossier/browser/navigation.py
- opengever/dossier/browser/overview.py
- opengever/dossier/browser/overview_templates/overview.pt
- opengever/dossier/configure.zcml
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/resources/init_tree.js
- opengever/dossier/tests/test_dossier.py
- opengever/dossier/tests/test_navigation.py
- opengever/dossier/tests/test_overview.py
- opengever/testing/test_case.py
Stiles are provided in a separate PR, see: https://github.com/4teamwork/plonetheme.teamraum/pull/308
Display a nested dossier-navigation on the dossier overview page. Display the navigation starting at the current dossier's root dossier. Don't display the navigation when no subdossiers are available.
> Display dossier-navigation on dossier overview.

- docs/HISTORY.txt
- opengever/base/__init__.py
- opengever/base/tests/test_selector.py
- opengever/examplecontent/profiles/default/portal_languages.xml
Plone does not display translated languages for combine language codes. This PR configures them globally on module level.
We want to move the language selector to another place anyway, so this should be only a temporary configuration.
> Configure visible language codes in language selector viewlet.

- docs/HISTORY.txt
- opengever/activity/model/notification.py
- opengever/activity/profiles/default/metadata.xml
- opengever/activity/upgrades/configure.zcml
- opengever/activity/upgrades/to4400.py
Tested migration *master -> deif-fix-activity-typo* and confirmed working an MySQL, PostgreSQL and Oracle.
Fixes #969
> Fix a typo in an opengever.activity models column name.

- scripts/mirror-to-onegov-gever.sh
This script can be called from a cron-job in order to mirror the `opengever.core` repo to https://github.com/OneGov/onegov.gever
@phgross
> Add script to mirror opengever.core to onegov.gever repo.

- docs/HISTORY.txt
- opengever/base/browser/boxes_view.py
- opengever/base/browser/gever_macros.py
- opengever/base/browser/templates/gever-macros.pt
- opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/opengever.base.pot
- opengever/base/tests/test_unit_boxes_view.py
- opengever/dossier/browser/overview.py
- opengever/dossier/browser/overview_templates/overview.pt
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier-manual.pot
- opengever/dossier/locales/opengever.dossier.pot
- opengever/inbox/browser/overview.py
- opengever/inbox/browser/overview_templates/overview.pt
- opengever/inbox/locales/de/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/locales/fr/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/locales/opengever.inbox.pot
- opengever/inbox/tests/test_overview.py
Dieser PR behebt ein Problem beim rendern der Übersicht des Eingangskorbes. Ursache des Problems waren Änderungen an der Dossier-Übersicht von der die Inbox-Übersicht erbt. Dabei ist Verbesserungspotential augefallen, die ersten Probleme wurden mit folgenden vorsichtigen Änderungen angegangen:
* Tests zu ftw.testbrowser tests umgeschrieben damit die View tatsächlich gerendert wird.
* Views entkoppelt, die Inhaltstypen erben nicht voneinander, die Views sollten das daher auch nicht tun.
* Gemeinsames in ein macro und in eine Mixin Klasse ausgelagert
* Macro so angepasst, dass gewisse schon bestehende Kunden-Anpassungen einfacher eingebaut werden können (Support für Widgets)
Fixes #981.
> Inbox-Übersicht render-Probleme beheben.

- opengever/inbox/tests/test_overview.py
Mit den Änderungen von #991 wird nun auch die Sortierung (`modified) der Dokumenten Box geprüft, diese kann aber nur sichergestellt werden, wenn das ModificationDate manuell gesetzt wird.
@lukasgraf
> Korrektur Inbox tests: Manuelles setzen des Modification Dates.

- docs/HISTORY.txt
- opengever/task/interfaces.py
- opengever/task/profiles/default/metadata.xml
- opengever/task/task.py
- opengever/task/tests/test_task.py
- opengever/task/upgrades/configure.zcml
- opengever/task/upgrades/profiles/4500/registry.xml
Die Frist ist neu über die Registry konfigurierbar, standardmässig wird immer noch der `heutige Tag + 5 Tage` vorgeschlagen.
Closes #721
@deiferni
> Aufgaben Frist konfigurierbar implementiert.

- docs/HISTORY.txt
- opengever/meeting/browser/committeetabs.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/meeting.py
- opengever/meeting/tabs/meetinglisting.py
- opengever/meeting/tests/test_committee_tabs.py
- Default Sortierung korrigiert (fixes #986)
- Keine Sortierung mehr bei Uhrzeit Spalten
- Umbenennen  der Spalten Titel
@lukas
> Meeting Auflistung: start/end Spalten überarbeitet.

- docs/HISTORY.txt
- opengever/inbox/forwarding.py
- opengever/inbox/tests/test_forwarding.py
> Leeres fieldset `Erweitert` für Forwardig nicht mehr darstellen.

- docs/HISTORY.txt
- opengever/base/monkeypatch.py
This adds a monkey patch for [`ZServer.medusa.http_server.compute_timezone_for_log`](https://github.com/zopefoundation/Zope/blob/2.13/src/ZServer/medusa/http_server.py#L772-L787) (and the module global [`http_server.tz_for_log`](https://github.com/zopefoundation/Zope/blob/2.13/src/ZServer/medusa/http_server.py#L790) where the computation result of that function is saved) in order to fix a DST bug in timezone calculation for Z2 logs.
The original function [tries to use `if time.daylight:`](https://github.com/zopefoundation/Zope/blob/2.13/src/ZServer/medusa/http_server.py#L773) to determine whether it is daylight savings time is currently obeserved or not. However, [`time.daylight`](https://docs.python.org/2/library/time.html#time.daylight) only says whether a a DST timezone is **defined** …
> Monkey patch http_server.compute_timezone_for_log in order to fix DST bug

- opengever/base/browser/templates/gever-macros.pt
- opengever/dossier/tests/test_dossier.py
- Die Macro-expression sollte `exists:` brauchen da man nur auf die Existenz überprüfen will
- Zwei Methoden entfernen, die nicht mehr gebraucht werden
*changelog sollte nicht nötig sein*
> Macro-Expression verbessern & Cleanup

- docs/HISTORY.txt
- opengever/task/browser/modify_deadline.py
- opengever/task/browser/transitioncontroller.py
- opengever/task/deadline_modifier.py
- opengever/task/task.py
- opengever/task/tests/test_actionmenu_viewlet.py
- opengever/task/tests/test_deadline_modification.py
Neu können nun auch Mitglieder der Eingangskorb-Gruppe des Auftraggeber Mandanten, stellvertretend die Frist ändern. 
Zudem wird nun auch die Aktion `Frist ändern` korrekt im Stellvertreter DropDown dargestellt, falls die Aktion nur Aufgrund Stellvertreter-Berechtigung möglich ist.
Closes #996.
> Fristverlängerung auch für Stellvertreter erlauben.

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/task/browser/accept/utils.py
- opengever/task/exceptions.py
- opengever/task/tests/test_accept.py
- opengever/task/tests/test_assign_to_dossier.py
Dieser PR führt eine zusätzliche Überprüfung beim Ändern des Taks/Forwarding status ein. Dabei wird überprüft, dass sich Task/Forwarding in einem validen Anfangszustand befinden.
Fixes #943.
> Doppeltes akzeptieren/zuweisen von Tasks verhindern.

- docs/HISTORY.txt
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/plone.pot
- opengever/task/activities.py
- opengever/task/browser/delegate/utils.py
- opengever/task/deadline_modifier.py
- opengever/task/handlers.py
- opengever/task/tests/test_activities.py
Dieser PR verhindert, dass die folgenden Aktivitäten doppelt registriert/dargestellt werden:
- Neu zuweisen
- Unteraufgaben hinzufügen (Plone action-menu)
- Delegieren tasks (Workflow)
- Frist ändern
Fixes #1007
> Verhindern, dass Aktivitäten doppelt registriert werden.

- docs/HISTORY.txt
- opengever/task/tests/test_task.py
This test makes sure that the VDEX vocabulary backed task types are correctly translated.
@phgross
> Add regression test for task type translations.

- docs/HISTORY.txt
- sources.cfg
- versions.cfg
This PR updates the version pinnings for `opengever.core` dependencies and uses packages from source that don't have a required release out yet.
Requires https://github.com/4teamwork/opengever.ogds.models/pull/31 to be merged first.
> Update versions of opengever.core dependencies

- docs/HISTORY.txt
- opengever/base/monkeypatch.py
- opengever/document/browser/templates/file.pt
- opengever/document/tests/test_forms.py
- opengever/document/widgets/no_download_display.pt
- opengever/document/widgets/no_download_input.pt
- opengever/mail/browser/templates/file.pt
Remove `plone.formwidget.namedfile monkeypatch` and perform necessary changes for using `1.0.11` (bumped in https://github.com/4teamwork/kgs/commit/55e74b878b7a0e40dd7ce357390b28d12c021005)  which includes the fix from plone/plone.formwidget.namedfile#9
(`widget/file/file_size` now includes the `KB` suffix, which requires a few changes to our overridden templates. Also, an empty file is now reported as having a size of `1 KB` as opposed to `0 KB` before).
> Remove p.formwidget.namedfile monkeypatch

- docs/HISTORY.txt
- opengever/document/__init__.py
- opengever/policy/base/profiles/default/metadata.xml
- opengever/policy/base/profiles/mimetype/metadata.xml
- opengever/policy/base/profiles/mimetype/mimetypes.xml
- opengever/policy/base/upgrades/configure.zcml
- opengever/policy/base/upgrades/to4503.py
This PR adds the **macro enabled office MIME types** (according to [Office 2007 File Format MIME Types](http://blogs.msdn.com/b/vsofficedeveloper/archive/2008/05/08/office-2007-open-xml-mime-types.aspx)) to the mimetypes registry.
- Initializes `opengever.policy.base:mimetype` profile version (was previously missing a `metadata.xml`)
- Adds new macro enabled types to MTR
- Includes upgrade step that reindexes `getIcon` metadata for all (potentially) affected documents
> Add macro enabled office mimetypes to MTR

- sources.cfg
`collective.vdexvocabulary` was used from source in @d9f88a4064 but has now been released as `0.2.1`  (and pinned in https://github.com/4teamwork/kgs/commit/add1b442eea0ab2907268596b1fa630458414c1a), so we can remove it from development packages again.
> Remove c.vdexvocabulary from dev-packages after releasing 0.2.1.

- docs/HISTORY.txt
- opengever/document/base.py
- opengever/document/browser/redirect_to_parent_dossier.py
- opengever/document/document.py
- opengever/document/tests/test_document.py
- opengever/dossier/tests/test_documents_tab.py
- opengever/inbox/inbox.py
- opengever/mail/mail.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/helper.py
Wir haben uns entschieden das Problem mit einer Redirect-View zu lösen.
Dieser PR führt zudem eine gemeinsame Superklasse für `Document` und `Mail` ein.
Closes #510
> Subdossier aus Documents-Tab verlinken

- docs/HISTORY.txt
- opengever/repository/repositoryfolder.py
Dieser PR ersetzt das Widget für das Feld *Erlaubte Spezialdossiers* einer Ordnungsposition. Das default-widget ist relativ hässlich und schlecht bedienbar. Neu schaut das so aus:
Zum Vergleich das alte Widget:
Closes #954.
> Feld erlaubte Spezialdossiers mit Checkbox Widget darstellen.

- docs/HISTORY.txt
- opengever/dossier/templatedossier/form.py
- opengever/dossier/tests/test_templatedossier.py
- opengever/tabbedview/helper.py
Dieser PR entfernt den Link zur Vorlage auf der `document_with_template` View.
Closes #739.
> Templates nicht mehr verlinken.

- docs/HISTORY.txt
- opengever/dossier/templatedossier/form.py
- opengever/dossier/tests/test_templatedossier.py
Dieser PR stellt sicher, dass die Vorlagen auf der `document_with_template ` View alphabetisch aufsteigend sortiert werden. 
Closes #745.
> Vorlagen bei der Vorlagenauswahl alphabetisch sortieren.

- docs/HISTORY.txt
- opengever/activity/center.py
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
- opengever/activity/tests/test_plone_center.py
Anstatt bei einem Fehler während dem Erstellen einer Aktivität bzw. Benachrichtigung den Request abzubrechen, wird neu der Fehler abgefangen und der Benutzer stattdessen mit einer Warnung informiert:
Der Error wird aber trotzdem geloggt, so dass wir via Errbit darüber informiert werden.
Closes #1001.
> Fehlerbehandlung des Benachrichtungssystems verbessert

- docs/HISTORY.txt
- opengever/meeting/command.py
Der Message Typ war fälschlicherweise `warn` anstatt `warning`.
Closes #938 
@deiferni
> Message typ (warning) korrigiert, beim Einreichen von bereits eingereichten Dokument-versionen

- docs/HISTORY.txt
- opengever/mail/mail.py
- opengever/mail/tests/__init__.py
- opengever/mail/tests/test_generate_mail_id.py
- opengever/mail/tests/test_indexers.py
- opengever/mail/tests/test_mail_byline.py
- opengever/mail/tests/test_mail_classification.py
- opengever/mail/tests/test_mail_download_copy.py
- opengever/mail/tests/test_mail_metadata.py
- opengever/mail/tests/test_mail_overviewtab.py
- opengever/mail/tests/test_mail_previewtab.py
- opengever/mail/tests/test_ogmail.py
- opengever/testing/builders/dx.py
Dieser PR verhindert, dass Mail-Metadaten beim Kopieren automatisch überschrieben werden.
Fixes #922.
> Author eines Mails nur überschreiben, wenn noch nicht gesetzt.

- docs/HISTORY.txt
- opengever/base/subscribers.py
- opengever/base/tests/test_relations.py
- opengever/dossier/browser/overview.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_overview.py
Neu werden alle Referenzen, sowohl ausgehende wie auch einkommende, in einer separaten Box in der Dossier Übersicht dargestellt. Closes #841 
----
Während der Entwicklung bin ich noch auf eine [Bug im plone.app.relationfield](https://github.com/plone/plone.app.relationfield/pull/12) gestossen. Da ich nicht mit einem Backport seitens von Plone rechne, habe ich den Bug mit einem separaten Event Handler im `opengever.base` korrigiert. Wie verzichten vorerst auf einen Upgradestep, welche bestehende Referenzen reindexieren würde, falls troztdem notwendig, kann das einfach zu einem späteren Zeitpunkt nachgeholt werden.
> Dossier Referenzen in der Dossier-Übersicht darstellen

- opengever/base/browser/templates/gever-macros.pt
Closes #790 .
Kein Changelog Eintrag da nur "Cleanup".
> Remove obsolete span tag in boxes view macro, for brain listings.

- docs/HISTORY.txt
- opengever/base/browser/resources/base.js
- opengever/base/profiles/default/jsregistry.xml
- opengever/base/profiles/default/metadata.xml
- opengever/base/upgrades/configure.zcml
- opengever/base/upgrades/profiles/4500/jsregistry.xml
- opengever/base/upgrades/profiles/4501/jsregistry.xml
Closes #961 .
Wie besprochen habe ich ein generelles Javascript registriert (`base.js`), dies ermöglicht uns kleine Scripts, gesammelt in einem File in der JSRegistry zu registrieren.
Zusätzlich habe ich auch gleich den `compression type` von bereits existierenden Javascripts korrigiert, diese hatten fälschlicherweise `save` anstatt `safe` hinterlegt.
> Autofocus automatisch auf's erste Feld legen.

- README.rst
- development.cfg
- docs/HISTORY.txt
- opengever/mail/mail.py
- opengever/mail/profiles/default/metadata.xml
- opengever/mail/tests/test_mail_download_copy.py
- opengever/mail/tests/test_mail_overviewtab.py
- opengever/mail/tests/test_message_filename_initialized.py
- opengever/mail/tests/test_ogmail.py
- opengever/mail/tests/test_senddocument.py
- opengever/mail/tests/test_subscribers.py
- opengever/mail/upgrades/configure.zcml
- opengever/mail/upgrades/to4500.py
- opengever/testing/builders/dx.py
Dieser PR ändert das Verhalten des Mail-Filenames. Bisher war das Verhalten folgendermassen:
- Beim Mail-In wurde hardcoded der Filename `message.eml` vergeben.
- Beim QuickUpload wurde der Dateiname übernommen.
Neu wird der filename immer automatisch aus dem Titel abgeleitet und gesetzt. Er entspricht der normalisierten Form des Titels:
```
Subject: Die Bürgschaft
Filename: die-burgschaft.eml
```
Damit wird auch automatisch der Titel des Mails als Dateiname beim Zipexport verwendet.
Closes #534.
> Mail-Titel als Dateiname verwenden.

- docs/HISTORY.txt
- opengever/document/browser/overview.py
- opengever/document/tests/test_overview.py
Ich habe die Überprüfung `show_modfiy_public_trial_link` in der Dokumenten Overview korrigiert. Sie ging fälschlicherweise davon aus, dass das Parent eines Dokuments immer ein Dossier ist. Deshalb wurde für Aufgaben fälschlicherweise kein Öffentlichkeitsstatus Formular dargestellt.
Fixes #965.
> Öffentlichkeitsstatus Formular auch bei Dokumenten innerhalb von Aufgaben darstellen

- docs/HISTORY.txt
- opengever/document/checkout/cancel.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_cancel.py
Wenn fälschlicherweise Mails für die Aktion `Wiederrufen` selektiert werden, so stellt neu die CancelDocument View eine entsprechende Fehlermeldung dar. (Fixes #530)
Zudem habe ich für die View noch Tests geschrieben und die Plone API konsequent verwendet.
> Korrektur ComponentLookupError in der CancelDocument View

- docs/HISTORY.txt
- opengever/debug/protect.py
This PR introduces a context manager `TraceObjectRegistrations` that will intercept and log all calls to the [`register()` method](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/Connection.py#L973-L991) on `ZODB.Connection.Connection` or any of its subclasses.
This will indicate a change to a persistent object, and can therefore be used to track down what code exactly causes an unexpected DB write in situations where a `plone.protect` confirmation page appears for a legitimate action.
The context manager works by [registering a trace function](https://docs.python.org/2/library/sys.html#sys.settrace) that traces all calls to `register()`. Once a call is intercepted, a message indicating this and the corresponding stack trace are displayed. Because there is no need to use a …
> Add debug helpers to assist in debugging plone.protect issues.

- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
Muss auf den Release 3.3.x backportet werden.
> Fehlende franz. Übersetzung für Checkin ohne Kommentar hinzugefügt

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/task/tests/test_overview.py
Beim Darstellen der Aufgabenübersicht wurde ein UnicodeEncoderError geraised, wenn das übersetzte Status Label Non-Ascii Zeichen enthielt, z.B. `Fermé`
Korrektur von https://errbit.4teamwork.ch/apps/524030763838182915000312/problems/55923f5a6d61742183c00100.
@lukasgraf
> Fixed UnicodeEncodeError in state_label getter of tasks.

- docs/HISTORY.txt
Der Release `4.4.2` wurde als Bugfix Release vom `4.4-stable` Branch released (siehe https://github.com/4teamwork/opengever.core/commit/306f0ad5998cae5445f88e4223f407d60d256858)
@lukasgraf
> Changelog cleanup after releasing 4.4.2 Release.

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob
`registry.xml` contained a reference to `setup.setup.reference_prefix_starting_point` (`setup` twice).
> Fix invalid variable name in policy template.

- docs/HISTORY.txt
- opengever/ogds/base/sync/ogds_updater.py
Make sure OGDS sync doesn't fail on user- or group IDs that are too long.
Simply skip them and log a warning.
Fixes #1053 
@phgross
> Make sure OGDS sync doesn't fail on user- or group IDs that are too long

- docs/HISTORY.txt
- opengever/document/checkout/manager.py
- opengever/document/tests/test_checkout.py
Neu wird das Dokumentdatum bei jedem erstellen einer Version aktualisiert. Fixes #964 
Beim Checkin: Wird das aktuelle Datum gesetzt. 
Beim Zurücksetzen auf eine Version: Wird das Datum der bestimmten Version verwendet.
- Ein Upgradestep wird nicht implementiert, da vom Kunden nicht gewünscht.
- Hab gleich auch die Tests fürs Reverten und Checkin ein wenig optimiert.
@lukasgraf please have a look
> Dokumentdatum aktualisieren beim erstellen einer neuen Version (checkin/reverting)

- docs/HISTORY.txt
- opengever/ogds/base/sync/ogds_updater.py
With this PR we enforce **uniqueness of user and group IDs** on application side.
If for example a user exists in LDAP twice, with two slightly different spellings of the supposedly unique user ID (casing, trailing whitespace), then a `UNIQUE` constraint in `SQL` may or may not consider those spellings equal, depending on the backend.
If it *doesn't* consider them equal, and allows the `INSERT` of the second user, then this leads to problems when using a case insensitive collation on the session: A `WHERE userid='john'` clause in an `UPDATE` statement will both match `'john'` and `'JOHN'`, and the update would therefore change both users even though it should only affect the one identified by the primary key value. SQLAlchemy detects this and raises
```
StaleDataError: UPDATE statement on …
```
> OGDSUpdater: Enforce uniqueness of user and group IDs on application side.

- docs/HISTORY.txt
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
- opengever/activity/mail.py
- opengever/activity/templates/notification.pt
- opengever/activity/tests/test_mail.py
- opengever/task/activities.py
* Der Betreff enthält neu den Aufgaben Titel prefixed mit `GEVER Aufgabe`.
* Die Tabellen Darstellung bei den Details wurde verbessert
* Wurde keine Aufgaben-Beschreibung angegeben so erscheint nun ein `-` anstatt `None`
Fixes #1000.
@lukasgraf
> Darstellung und Inhalt des Benachrichtigungsmail überarbeitet

- docs/HISTORY.txt
- opengever/repository/subscribers.py
- opengever/repository/tests/test_subscribers.py
Dieser PR fügt ein Eventhandler hinzu, welcher überprüft ob der `Aktenzeichen Prefix` Wert verändert wurde. Falls das Präfix geändert wurde, wird die `reference_number` auch bei allen enthaltenen Objekte reindexiert. Fixes #115.
Wie im Issue bereits beschrieben, die Problematik von lang dauernden Requests, z.B. bei Anpassungen an Ordnungspositionen mit viel Inhalt, wird vorerst "ignoriert". 
@lukasgraf
> Aktenzeichen reindexieren von enthaltenen Objekten wenn der Referencenumber prefix ändert.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/meeting.js
Vorher:
Nachher:
Fixes #941 
@lukasgraf @deiferni Bitte reviewen oder wollen wir das autosize plugin für alle Textfelder in Formularen verwenden?
> Autosizing textareas im Add und Edit Formular von Anträgen

- docs/HISTORY.txt
- opengever/base/utils.py
- opengever/tabbedview/helper.py
This is required because this cache key is used to cache generated URLs, which are dependent on the hostname that is used to access the system (might be `localhost` + SSH tunnel).
Fixes #1068
> Make `author_cache_key` also discriminate on hostname

- docs/HISTORY.txt
- opengever/activity/model/activity.py
- opengever/activity/upgrades/to4501.py
Dieser PR behebt ein potentielles Problem mit den activity upgrades. Es wurden versehentlich Modell-Definitionen aus dem Modell importiert, anstatt wie für Upgrade-Steps korrekt, dupliziert.
Konkret geht es um übersetzte Activities. Die Mapper zum Übersetzen werden teilweise von einem 3rdParty Produkt (https://github.com/kvesteri/sqlalchemy-i18n) generiert. Für den Upgrade-Step wurde die generierte Tabelle aus DB analysiert und als upgrade umgesetzt.
Weiteres:
- Entfernung Parameter Column-Name weil unnötig (Konsistent mit anderen Modelldefinitionen)
- PEP8
> Activity Upgrade-Step flicken

- docs/HISTORY.txt
- opengever/base/marmoset_patch.py
- opengever/base/monkeypatch.py
- opengever/policy/base/profiles/default/metadata.xml
- opengever/policy/base/upgrades/configure.zcml
- opengever/policy/base/upgrades/to4504.py
Dieser PR deaktiviert einen Plone upgrade-step, der den Suchtext für alle Inhalte neu rechnet.
Grund für das Plone Upgrade ist ein neuer I18N Case normalizer. Da damit der ganze Searchable-Text neu gerechnet wird müssen wir dieses Upgrade aus Zeitgründen später einspielen können. Dazu wird der Plone Upgrade Step mit einer null-methode gepatched. Wir registrieren einen separaten upgradestep in `opengever.policy.base`, der das Upgrade nachholt.
> Potentiell teuren Plone upgrade-step verzögern.

- docs/HISTORY.txt
- opengever/ogds/base/sync/ogds_updater.py
`userid`, `user_dn`, `groupid` and `group_dn` are converted to unicode (as soon as possible).
Therefore all message strings used in logging also need to be unicode.
> OGDS Updater: Fix some unicode errors while logging.

- docs/HISTORY.txt
- opengever/core/upgrade.py
- opengever/ogds/base/events.py
Make sure we always get unicode from SQLAlchemy for columns values by setting the `coerce_to_unicode` parameter for the cx_Oracle dialect. Necessary for `SQLAlchemy >= 0.9.2`
See http://docs.sqlalchemy.org/en/latest/dialects/oracle.html#unicode)
> Set `coerce_to_unicode` for the CX Oracle dialect to always get unicode from SA

- docs/HISTORY.txt
- opengever/base/profiles/default/metadata.xml
- opengever/base/upgrades/configure.zcml
- opengever/base/upgrades/to4502.py
The upgradestep removes no longer existing interfaces from zc.relations catalog's interfaces_flattened mapping, to avoid pickling erros (fixes #1091).
@lukasgraf
> Added upgradestep wich cleanup zc.relation catalogs interface mapping.

- docs/HISTORY.txt
- opengever/base/tests/test_utils.py
- opengever/base/utils.py
- opengever/dossier/tests/test_documents_tab.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/helper.py
- opengever/tabbedview/tests/test_document_helper.py
Die Spalten `document_author` und `containing_subdossier` können Zeichen enthalten, die in HTML escaped werden müssen. Dieser PR führt eine wiederverwendbare Funktion `escape_html` in `og.base.utils` ein, ersetzt alle bisherigen Verwendungen von `cgi.escape`, und escaped sowohl den `document_author` wie auch den Link-Text im `containing_subdossier`.
Fixes #1096
> DocumentsTab: Make sure author and subdossier title are HTML escaped

- docs/HISTORY.txt
- opengever/document/widgets/no_download_display.pt
- opengever/document/widgets/no_download_input.pt
- opengever/mail/browser/configure.zcml
- opengever/mail/browser/default_view.py
- opengever/mail/browser/edit.py
Dieser PR stellt sicher, dass auch das Mail `message` Feld die gleichen custom widget templates benutzt wie das Document `file` Feld. Die templates stellen sicher, dass die `message` nur über die overwiew heruntergeladen werden kann, so wird dies auch journalisiert.
Desweiteren wird neu im widget ein MIME-Type icon neben dem Dateinamen angezeigt.
Closes #1095.
> Fehlendes Icon im Mail FileWidget

- opengever/dossier/filing/advanced_search.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
The field was wrongly translated with the advancedsearch domain, but the file is inside the opengever.dossier subpackage. I've changed the domain.
Fixes #1101 
@lukasgraf
> Added missing translation for the filingnumber search field.

- sources.cfg
Adds `ftw.mail` to development packages in order to get the fix from 4teamwork/ftw.mail#32
> Add ftw.mail to development packages.

- docs/HISTORY.txt
- opengever/document/browser/overview.py
- opengever/document/browser/overview_templates/overview.pt
- opengever/document/browser/templates/submitted_with.pt
- opengever/mail/browser/mail.py
Dieser PR verschiebt meeting Elemente in eine eigene Box, so dass der Inahltsbereich für Dokumente nicht mehr halbiert wird.
Closes #1103.
> Dokumentansicht: Inhaltsbereich zur Hälfte limitiert

- opengever/base/upgrades/to4502.py
Mit dem im Commit 647eddb eingeführten Upgradestep, werden nicht mehr existierende Interfaces im `zc.relation Catalog` persistent gespeicherte Interfaces entfernt, dies aber nur aus dem `_name_TO_mapping`. 
Während dem Testen auf dem roten System, hat sich aber gezeigt das noch eine weitere Korrektur notwendig ist: Für die Korrektur von existierenden Relations muss aber zusätzlich auch das `_reltoken_name_TO_objtokenset` mapping korrigiert werden.
Mit dieser Anpassung sollte nun auch das Verschieben und Kopieren von migrierten Objekten (Plone 4.2 -> 4.3) funktionieren.
> RelationCatalog Cleanup Upgradestep Korrektur 

- docs/HISTORY.txt
- opengever/mail/profiles/default/metadata.xml
- opengever/mail/upgrades/configure.zcml
- opengever/mail/upgrades/to4501.py
Fixes the `document_author` and  `title` fields on the mail objects.
The upgrade-step tries to fix a possibly incorrectly decoded value in a field by
- Checking whether it looks like a raw, undecoded header
- Checking whether it is exactly the same as the corresponding raw header
value (which means is hasn't been edited by a user)
- If both of the above are true, re-decode it by fetching it from the
original message again using `get_header`
- If the new value is different, update it on the object, reindex the
necessary indexes, and sync the filename to the title again if needed.
> Add upgrade-step to fix 'document_author' and 'title' for mails with incorrectly decoded header values.

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_sql_task.py
- opengever/task/browser/overview.py
- opengever/task/tests/test_overview.py
Also allow to specify if long or medium format should be used.
Closes #1110.
> Use datetime formatter to display deadline label.

- docs/HISTORY.txt
- opengever/usermigration/creator.py
- opengever/usermigration/tests/test_creator_migrator.py
Adds a `CreatorMigrator` that migrates creators for Dexterity objects - to be used with `ftw.usermigration`.
> Add CreatorMigrator that migrates creators for Dexterity objects.

- sources.cfg
Die Packages sind nun released und müssen nicht mehr ausgecheckt werden.
`collective.js.timeago` ist leider noch nicht released worden.
> Cleanup development-packages after releasing GEVER 3.4.

- docs/HISTORY.txt
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
Neu wird beim Erstellen eines Antrags der Dossiertitel als defaultvalue für den Antragstitel verwendet.
Closes #1075.
> Dossier-Titel als defaultvalue für Antragstitel verwenden. 

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/model/meeting.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_unit_meeting.py
Dieser PR entfernt Einschränkungen beim Bearbeiten und erlaubt edits auch noch während dem Durchführen einer Sitzung.
Closes #1072.
> Traktanden müssen während dem Durchführen der Sitzung editierbar bleiben. 

- docs/HISTORY.txt
- opengever/document/base.py
- opengever/document/document.py
- opengever/mail/mail.py
- opengever/mail/profiles/default/metadata.xml
- opengever/mail/tests/test_ogmail.py
- opengever/mail/upgrades/configure.zcml
- opengever/mail/upgrades/to4600.py
Closes #1037.
Also a migration is needed to:
- initialize ftw.mail caches (headers, attachments)
- rename title attribute from `title` to `_title` to avoid shadowing by properties
> Let OGMail inherit from ftw.mail.mail.Mail.

- docs/HISTORY.txt
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
Fixes #1120.
Needs to be backported to `4.5-stable`.
> Advanced search: Fix translation for filing no help text.

- opengever/mail/browser/templates/file.pt
- sources.cfg
Kleine Anpassung an der Struktur des Mail "file-widgets", um die Darstellung des Mail-Icons zu verbessern. Siehe https://github.com/4teamwork/plonetheme.teamraum/pull/329
@lukasgraf 
----
Benötigt einen Backport nach `4.5-stable`
> Verbesserung und Vereinheitlichung des Mail Icons.

- docs/HISTORY.txt
- opengever/tasktemplates/browser/form.py
- opengever/tasktemplates/locales/de/LC_MESSAGES/opengever.tasktemplates.po
- opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po
- opengever/tasktemplates/locales/opengever.tasktemplates.pot
- opengever/tasktemplates/tests/test_form.py
Redirects back to dossier and shows statusmessage if no active tasktemplatefolders are registered.
Fixes #1119 
@lukasgraf
> Tasktemplate form: add redirect when no tasktemplatefolder exists.

- docs/HISTORY.txt
- opengever/dossier/browser/overview.py
- opengever/dossier/tests/test_overview.py
- opengever/globalindex/model/query.py
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_query.py
- opengever/tabbedview/browser/tasklisting.py
Dieser PR passt die Dossier Übersicht an so, dass nur noch pendente Aufgaben in der Auflistung gelistet werden.
Needs backporting to [4.5-stable](https://github.com/4teamwork/opengever.core/tree/4.5-stable).
Closes #1127
> Dossier-Übersicht: abgeschlossene Aufgaben nicht mehr anzeigen

- docs/HISTORY.txt
- opengever/sharing/browser/configure.zcml
The view wich is called per ajax when searching for a principal, is registered as a separate view, therefore we need to overwrite them as well. Fixes #1122 
----
Wie besprochen müssten die `opengever.sharing` Tests komplett überarbeitet werden, da dies aber den Rahmen dieses Bugfixes sprengen würde, enthält der PR kein Test.
> Fixed gever customization of sharing view, for updateSharingInfo.

- docs/HISTORY.txt
- opengever/tabbedview/helper.py
- opengever/tabbedview/tests/test_document_helper.py
This PR adds the authentication token to the edit_direct link, which fixes #1139.
Need backport: `4.5-stable`
> Made Document's tooltip edit_direct link CSRF safe

- docs/HISTORY.txt
- opengever/latex/layouts/default.py
- opengever/latex/layouts/landscape.py
Make better use of the full a4 landscape paper width:
Fixes #1125.
> Use correct geometry setup for landscape pdfs.

- docs/HISTORY.txt
- opengever/policy/base/profiles/default/jsregistry.xml
- opengever/policy/base/profiles/default/metadata.xml
- opengever/policy/base/upgrades/configure.zcml
- opengever/policy/base/upgrades/profiles/4505/jsregistry.xml
Because of several problems in particularly with `invariants`, we decided to disable the inline validation for now.
Fixes #1137 
> Disable inline validation.

- docs/HISTORY.txt
- opengever/activity/tests/test_listing.py
- opengever/latex/opentaskreport.py
- opengever/latex/tests/test_opentaskreport.py
- opengever/tabbedview/browser/personal_overview.py
Dieser PR behebt ein Problem mit der Pendenzenliste Action und stellt sicher, dass die Action immer angezeigt wird, wenn der Benutzer in der Inbox Gruppe ist.
Desweiteren wird die View, die das PDF zurückgibt auch mit einem Check, der diese Rechte überprüft, geschützt.
Fixes #1128.
> Pendenzenliste Action darstellen, wenn nötig.

- docs/HISTORY.txt
- opengever/inbox/configure.zcml
- opengever/inbox/forwarding.py
- opengever/inbox/tests/test_forwarding.py
Analog zur add-view.
Closes #1124.
> No longer display an empty tab 'additional' on the forwarding edit page.

- docs/HISTORY.txt
- opengever/dossier/profiles/default/metadata.xml
- opengever/dossier/reference.py
- opengever/dossier/tests/test_upgrades.py
- opengever/dossier/upgrades/configure.zcml
- opengever/dossier/upgrades/to4502.py
Die Referenznummer für das Vorlagendossier macht eigentlich keinen Sinn. Zudem gibts es Probleme mit nicht vollständig generierten Referenznummern. Dieser PR nutzt die Gelegenheit um die Referenznummern für Vorlagendossiers zu entfernen. Stattdessen wir neu der Titel des Vorlagendossiers als Referenznummer angezeigt.
Fixes #1136.
> Anstatt Referenznummern für Vorlagendossiers Dossier-Titel darstellen.

- docs/HISTORY.txt
- opengever/base/monkeypatch.py
- opengever/document/browser/templates/file.pt
- opengever/document/tests/test_forms.py
- opengever/document/widgets/no_download_display.pt
- opengever/document/widgets/no_download_input.pt
- opengever/mail/browser/templates/file.pt
We reverted pinning of plone.formwidget.namedfile to plone default, 1.0.7 since
there are problems with the newer version, see #1153.
This PR reverts the changes introduced in https://github.com/4teamwork/opengever.core/pull/1016.
Now we need to make sure that mime-types sent by the browser are ignored since
they are unrelibale. Instead we want to let the server guess the uploaded
file's mimetype.
Closes #1153.
Needs backport to 4.5-stable.
This PR replaces #1157.
> Monkey patch a fix from plone.formwidget.namedfile 1.0.11.

- docs/HISTORY.txt
- opengever/base/monkeypatch.py
- sources.cfg
so it sets `message.contentType` to `unicode`, not `str` (see 4teamwork/ftw.mail#33).
Needs backport to `4.5-stable`
> Fix ftw.mail.inbound.createMailInContainer monkey patch

- docs/HISTORY.txt
- opengever/activity/browser/__init__.py
- opengever/activity/tests/test_listing.py
- opengever/activity/tests/test_mail.py
- opengever/activity/tests/test_notification_viewlet.py
- opengever/activity/tests/test_resolve.py
- opengever/examplecontent/profiles/default/unit_creation/admin_units.json
> Use an admin-unit's public url to generate urls to resolve notifications.

- docs/HISTORY.txt
- opengever/activity/browser/listing.py
- opengever/activity/model/activity.py
- opengever/activity/tests/test_listing.py
- opengever/globalindex/model/task.py
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/meeting.py
- opengever/meeting/model/proposal.py
- sources.cfg
Use the `UnicodeCoercingText` TypeDecorator introduced in 4teamwork/opengever.ogds.models#33 for all `Text` columns.
This makes sure we always get `unicode` back from `Text` columns, even with Oracle as the backend.
Fixes #1154.
Depends on `opengever.ogds.models >= 2.3.1` (hence the failing tests).
> Use `UnicodeCoercingText` TypeDecorator for all `Text` columns

- docs/HISTORY.txt
- opengever/base/browser/pasting_allowed.py
- opengever/dossier/tests/test_move_items.py
> Don't show paste action for closed dossiers.

- docs/HISTORY.txt
- opengever/tabbedview/browser/personal_overview.py
- opengever/tabbedview/tests/test_personaloverview.py
Wrongly the `My notification` tab only gets added for users wich are allowed to watch additional tabs (inbox_group users).
> Display notification tab also for regular users.

- docs/HISTORY.txt
- opengever/tasktemplates/browser/form.py
- opengever/tasktemplates/tests/test_form.py
The TaskTemplateFolders checks if there any active TaskTemplateFolders, but the review_state had a typo in the catalog query and also in the test.
> Fixed lookup for active TaskTemplateFolders.

- docs/HISTORY.txt
- opengever/dossier/tests/test_overview.py
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_task_link.py
- opengever/mail/browser/extract_attachments.py
- opengever/meeting/model/committee.py
- opengever/meeting/model/meeting.py
- opengever/meeting/model/member.py
- opengever/meeting/model/proposal.py
- opengever/ogds/base/actor.py
- opengever/tabbedview/helper.py
- opengever/task/browser/overview.py
This PR improves performance for task overviews by:
- No longer inheriting from `DisplayForm`, this skips unnecessary widget preparations. Our data is from an SQL-source.
- No longer use plone transforms to `text/x-html-safe`, they are slow and not really required here since we build short markup fragments. Instead just use `escape_html`.
> Improve performance for task overviews

- docs/HISTORY.txt
- opengever/base/menu.py
- opengever/dossier/menu.py
- opengever/dossier/tests/test_dossier.py
Die im commit c721c6610e0a3df3661c75ff835125af2a7753f7 implementierte `FilterPostFactoryMenu` Sortierung hat für das Dossier Menü nicht korrekt funktioniert, da die Subdossier Aktion erst nach dem Super call umbenannt wurde.
Ich habe deshalb eine zusätzliche Funktion `rename` implementiert.
@lukasgraf 
Note: Diese Anpassung muss auch für alle `opengever.zug` Spezial Dossier's gemacht werden.
> Korrektur der Sortierung im dossier FactoryMenu

- docs/HISTORY.txt
- opengever/activity/browser/listing.py
- opengever/activity/center.py
- opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
- opengever/activity/locales/opengever.activity.pot
- opengever/activity/tests/test_listing.py
- opengever/activity/tests/test_notification_center.py
- opengever/activity/tests/test_notification_viewlet.py
- opengever/activity/viewlets/notification.pt
- opengever/inbox/activities.py
- opengever/inbox/locales/de/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/locales/fr/LC_MESSAGES/opengever.inbox.po
- opengever/inbox/locales/opengever.inbox.pot
"Meine Benachrichtigungen"
- Sortierung in der "Meine Benachrichtigungen" für alle Spalten bis auf "created" deaktiviert.
- Label anstatt Kind darstellen verwenden
Benachrichtungs viewlet:
- Benachrichtigungen werden nun chronologisch, das neuste zuoberst aufgelistet.
- Tooltip beim "Als gelesen markieren" Link
- Struktur für einfacheres Styling angepasst (siehe https://github.com/4teamwork/plonetheme.teamraum/pull/348)
Übersetzung für `ForwardingAdded` Activity hinzugefügt.
> Verbesserungen Benachrichtigungssystem

- docs/HISTORY.txt
- opengever/activity/tests/test_notification_viewlet.py
- opengever/activity/viewlets/notification.pt
- opengever/activity/viewlets/notification.py
Das Notification Viewlet hat aktuell nur die 10 neusten Einträge dargestellt. Diese Limitierung macht aber bei der aktuellen Darstellung schlicht keinen Sinn. 
Deshalb werden neu alle Notifications dargestellt, und das Notification Viewlet ist stattdessen scrollable.
Styling: im separater PR im `plonetheme.teamraum`
> Drop limitation of notifications and make notification viewlet scrollable instead.

- docs/HISTORY.txt
- opengever/activity/templates/notification.pt
- opengever/activity/tests/test_mail.py
- opengever/task/activities.py
- opengever/task/tests/test_activities.py
Fixes #1178 .
Zu einem habe ich die HTML Struktur korrigiert und anderseits das Styling in ein separates Style Tag im Header verschoben.
> Fix layout and styling in notification mail also for microsoft outlook.

- docs/HISTORY.txt
- opengever/activity/mail.py
- opengever/activity/tests/test_mail.py
- opengever/mail/browser/send_document.py
- opengever/mail/tests/test_utils.py
- opengever/mail/utils.py
Bisher wurden in GEVER beim Senden von Mails die `From:` Header falsch codiert.
Angenommen, der Header soll `Lükäs Graf <l.graf@4teamwork.ch>` sein. Wenn man diesen einfach an `Header()` übergibt, wird der komplette String in ein sog. `encoded-word` gepackt:
```
From: =?utf-8?q?Graf_L=C3=BCk=C3=A4s_=3Cl=2Egraf=404teamwork=2Ech=3E?=
```
Laut [RFC2047](http://tools.ietf.org/html/rfc2047#section-5) darf aber die eigentliche E-Mail Adresse nicht encoded werden:
> An `'encoded-word'` MUST NOT appear in any portion of an `'addr-spec'`.
Outlook verschluckt sich daran und stellt den Header nachher so dar:
Dieser PR führt darum eine Utility-Funktion `make_addr_header` ein, welcher der Fullname und die Adresse separat übergeben werden, und die das richtige encoding übernimmt, so dass dann ein …
> Make sure to create an RFC2047 compliant From: or To: header when sending mails

- docs/HISTORY.txt
- opengever/activity/templates/notification.pt
Das Label `Details:` wird nur noch angezeigt wenn es auch wirklich eine Beschreibung gibt.
@deiferni 
> Notification mail: hide "display" label for activities without a description.

- opengever/core/testing.py
- opengever/core/tests/test_autocomplete_widget.py
- opengever/core/tests/tests.zcml
- opengever/core/tests/views/configure.zcml
- opengever/core/tests/views/z3cform.py
Fix autocomplete widget tests by using our own layer instead of importing from `ftw.testbrowser`.
`ftw.testbrowser.testing` now imports from `plone.app.contenttypes` which we neither have or want). So we just define a form and view in `opengever.core.tests` to the our autocomplete widget against.
> Fix autocomplete widget tests by using our own layer

- bin/mtest
This PR fixes a critical issue with `bin/mtest` not detecting packages with three namespace levels.
This means that `opengever/ogds/base` tests were not executed by our CI system. Thus tests for this PR will fail, wich is OK and expected. The failing tests will be fixed in separate Pull Requests.
> Fix bin/mtest only matching packages two levels deep.

- opengever/ogds/base/tests/test_actor_lookup.py
As mentioned in https://github.com/4teamwork/opengever.core/pull/1183 `opengever.ogds.base` were not executed by CI and contain failing tests. This PR addresses this issue.
> Fix tests for opengever.ogds.base.

- docs/HISTORY.txt
- opengever/base/adapters.py
Any empty `PersistentMapping` is also falsy, therefore the previous check re-initialized an empty mapping again and again.
> ReferenceNumberPrefixAdpater: Fix conditions for lazily initialising PersistentMappings in annotations.

- docs/HISTORY.txt
- opengever/mail/upgrades/to4500.py
- opengever/mail/upgrades/to4501.py
Make upgradesteps `UpgradeMailMessageFilename` and `FixMailsWithIncorrectlyDecodedHeaderValues` more defensive to avoid trouble douring upgrades caused by mails with a wrong class (ftw.mail.mail.Mail instead of OGMail).
Backport-needed: `4.5-stable`
> Make mail upgradesteps (to4500, to4501) more defensive.

- docs/HISTORY.txt
- opengever/task/browser/accept/inbox.py
Fixes #1190.
Ein Benutzer der eine AdminUnit-übergreifende Weiterleitung mit der Option `... im Eingangskorb von Amt für ??? ablegen. ` akzeptiert. Wird direkt auf die `CreateSuccesorForwardingView` auf der Auftragnehmer AdminUnit redirected, anschliessend wird die Weiterleitung im eigenen Eingangskorb abgelegt. Deshalb ist die `CreateSuccesorForwardingView` immer ein Schreibzugriff.
> Disable csrf protection for CreateSuccesorForwardingView.

- docs/HISTORY.txt
The 4.5.2 release was released from the `4.5-stable` release.
> Cleanup changelog after bugfix release 4.5.2.

- docs/HISTORY.txt
- opengever/debug/browser/trigger_csrf.py
- opengever/debug/browser/trigger_csrf_templates/triggercsrf.pt
- opengever/debug/configure.zcml
Adds a debug view `@@trigger-csrf` (on Plone Site, with `ManagePortal` permission) that triggers a `plone.protect` confirmation dialog.
> Add debug view to trigger a plone.protect confirmation dialog.

- docs/HISTORY.txt
- opengever/base/protect.py
This change introduces detailed **logging for CSRF incidents** (cases where the user is shown the `@@confirm-action` dialog).
- Logging enabled by default, but can be disabled by setting the `CSRF_LOG_ENABLED` environment variable to something falsy.
- Logs are automatically rotated and retained for 7 days by default. This age can be configured via the `CSRF_LOG_MAX_AGE` environment variable (in minutes).
There will be one log file created per incident, and the log filename will contain the timestamp and the user name.
For now, the following information is dumped:
- Original **URL** that caused the CSRF protection to fire
- The **`HTTP_REFERER`**, if present
- The **username** of the user that issued the request
- The contents of **`_registered_objects`** (which equals the persistent …
> Add detailed logging for CSRF incidents.

- docs/HISTORY.txt
- opengever/task/task.py
- opengever/task/tests/test_task.py
This prevents an ugly error being displayed.
Closes https://github.com/4teamwork/opengever.zug/issues/206
> Validate task title length.

- docs/HISTORY.txt
- opengever/latex/opentaskreport.py
- opengever/latex/tests/test_opentaskreport.py
Fixes https://github.com/4teamwork/opengever.zug/issues/205 (inkl. genauere Beschreibung der Problematik)
> Hide foreign part of predecessor/successor pairs in the opentaskreport.

- opengever/latex/tests/test_opentaskreport.py
This PR fixes an issue with tests introduced in https://github.com/4teamwork/opengever.core/pull/1203.
> Fix taskreport tests, add deadline to fixture.

- docs/HISTORY.txt
- opengever/latex/templates/opentaskreport.tex
This PR replaces longtable to with supertabular to fix an issue with tables
breaking pages too late.
Closes https://github.com/4teamwork/opengever.zug/issues/204.
fixed page break:
previous implementation, broken page breaks:
> Use supertabular* to render multi-page tables.

- docs/HISTORY.txt
- opengever/debug/browser/manage_csrf_tracing.py
- opengever/debug/browser/manage_csrf_tracing_templates/managecsrftracing.pt
The `@@manage-csrf-tracing` view allows to enable **CSRF tracing**, which will monkey patch the method for object registration on the ZODB connection in order to **save a stack trace** at the point a persistent object has been registered (i.e. changed for the first time in a transaction).
Activating CSRF tracing will patch two methods: [`register()` on the ZODB connection](https://github.com/zopefoundation/ZODB/blob/e76c5b0234fff2ce773b875e024a32ba1e07800b/src/ZODB/Connection.py#L973-L991) and `_build_csrf_report()` on our own `OGProtectTransform`. The patch to `register()` will save a formatted stack trace to a module global every time a persistent object is modified for the first time in a transaction. This will then allow the patched `_build_csrf_report()` to include that stored stack …
> CSRF: Add view to enable and disable CSRF tracing monkey patches.

- docs/HISTORY.txt
- opengever/locking/lockable.py
- opengever/locking/tests/test_lockable.py
This avoids integrity-errors during database flushes when locking the
same object for which expired locks are cleaned.
Fixes #1212.
> Remove expired locks before creating new locks.

- docs/HISTORY.txt
- opengever/document/browser/versions_tab.py
- opengever/document/checkout/manager.py
- opengever/document/tests/test_checkout.py
This PR no longer allows reverts while a document is checked out. This avoids nasty race-conditions where theoretically users could overwrite their files and lose content.
Also disable links to revert as follows:
Closes #1204.
> No longer allow reverting document versions while documents are checked out.

- docs/HISTORY.txt
- opengever/base/protect.py
This PR improves csrf logs by also logging registered object oids.
> Also log object oids in csrf logs.

- docs/HISTORY.txt
- opengever/globalindex/handlers/task.py
The logging should help to detect problems with incorrectly synched or not even registered tasks.
@lukasgraf 
Needs-Backport: `4.5-stable`
> Add logging to the task SQL synchronisation.

- docs/HISTORY.txt
- opengever/policy/base/upgrades/to4504.py
Our deferred version of the upgrade step removed the `catalog.manage_clearIndex([index_id])` [that the `plone.app.upgrade` upgrade step does](https://github.com/plone/plone.app.upgrade/blob/741f9e5996f12dff31189a0abed917b22769056a/plone/app/upgrade/v43/alphas.py#L65).
This leads to cases where the Plone Lexicon used by the `ZCTextIndexes` isn't rebuilt correctly.
Needs-Backport: `4.5-stable`
> Fix Upgrade-Step that updates lexicon: Affected indexes need to be cleared first

- docs/HISTORY.txt
- opengever/inbox/tests/test_activities.py
- opengever/inbox/tests/test_inbox_assign.py
- opengever/task/activities.py
Fixes https://github.com/4teamwork/opengever.zug/issues/200. 
With the PR #1011 the problem of doubled recorded activities gets fixed for tasks, this PR fix the Problem also for forwarding activities wich gets recorded twice.
> Fix duplicate activity recordings when a forwarding gets reassigned.

- docs/HISTORY.txt
- opengever/task/response_description.py
- opengever/task/tests/test_response_descriptions.py
This makes the use of the ResponseDescriptions (`ResponseViewlet` etc.) more robust.
Although reponses without any transition information should not exists, it's the better option to add this fallback than remove any task history (responses).
Fixes https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/55ed2ad06d61743a31120000
Needs-backport: `4.5-stable`
> Added NullResponseDescription fallback for responses without a transition.

- opengever/debug/browser/manage_csrf_tracing.py
I mistakenly used the same name `timeout` for both the **actual** timeout to be set (when submitting the form via `POST`) and the **suggested** timeout (query string parameter when first calling the view, just influencing the form default).
Because the query string parameter stays in the URL, they both get submitted when the form is `POST`ed, leading to Zope parsing them as a list and
```pytb
Module opengever.debug.browser.manage_csrf_tracing, line 183, in __call__
TypeError: int() argument must be a string or a number, not 'list'
```
With this change, the view should then obviously be invoked as …
> CSRF tracing: Fix parameter name collision between actual and suggested timeout

- docs/HISTORY.txt
- opengever/base/behaviors/lifecycle.py
- opengever/base/tests/test_lifecycle.py
The `retention_period` flag was ignored by the RetentionPeriodValidator, this PR fixes #1175.
Because the super class `IntLowerEqualThanParentValidator` is only used by the RetentionPeriodValidator I've dropped the super class, so I can include the is_restricted check directly in the validator.
The complete functionality should be reworked and simplified, but that's not a bugfix thing :wink: 
Needs Backport: `4.5-stable`
> Let RetentionPeriodValidator respect the is_restricted flag now

- docs/HISTORY.txt
- opengever/base/overrides.zcml
- opengever/base/protect.py
- opengever/base/sequence.py
- opengever/base/tests/test_protect.py
With this PR initialising annotations in a GET request no longer displays a CSRF confirmation page.
Closes https://github.com/4teamwork/opengever.zug/issues/203.
> Make annotation initialisation plone.protect aware.

- docs/HISTORY.txt
- opengever/globalindex/handlers/task.py
So it's possible to ensure, that the plone object which was used for the synchronisation (see https://github.com/4teamwork/opengever.core/blob/master/opengever/globalindex/handlers/task.py#L82) was up-to-date.
@deiferni
> Extend logging of task SQL synchronisation, with tasks modification date.

- opengever/base/pathfinder.py
- opengever/base/protect.py
- opengever/base/utils.py
- opengever/ogds/base/sync/ogds_updater.py
- opengever/policytemplates/cli.py
There was an error with cyclic imports during policy creation. This PR fixes that issue by moving a class to its own module from which it can be imported separately.
It also changes the `create_client` script to always pass remaining arguments to the template engine (mr.bob).
> Fix creating policies from template

- docs/HISTORY.txt
- opengever/ogds/base/Extensions/plugins.py
Our [PAS plugin for authenticating internal requests](https://github.com/4teamwork/opengever.core/blob/46cac2fc9a9d1ff0ee7a17d6646f825d7d4ab9be/opengever/ogds/base/Extensions/plugins.py#L28-L41) often causes a `KeyError` because the extracted credentials usually don't contain `id` for normal requests.
These errors are rarely seen because PAS usually swallows them silently, but they still should be avoided.
> Prevent a silently ignored key error in our PAS IAuthenticationPlugin for internal requests.

- docs/HISTORY.txt
- opengever/document/browser/versions_tab.py
VersionsTab: Use `getHistoryMetadata()` instead of `getHistory()` to avoid fetching the actual versioned objects and hence improve performance.
Iterating over the `LazyHistory` returned by `getHistory()` will cause a `retrieve()` for every version iterated over, causing the entire versioned object to be constructed, and therefore results in poor performance.
This change instead uses `getHistoryMetadata()`, which returns a [`ShadowHistory`](https://github.com/plone/Products.CMFEditions/blob/16391ecc2b4905cd286e448143b259f985e451f4/Products/CMFEditions/ZVCStorageTool.py#L784-L947) instance. The APIs for using `LazyHistory` and `ShadowHistory` are entirely different (`ShadowHistory` doesn't support iteration), that's why it's not just a method call that needed to be changed.
IMHO needs a …
> VersionsTab: Use getHistoryMetadata() instead of getHistory() for better performance

- docs/HISTORY.txt
- opengever/base/viewlets/pathbar.py
- opengever/meeting/meeting_wrapper.py
- opengever/meeting/tests/test_pathbar.py
In https://github.com/4teamwork/opengever.core/pull/1174 wrapper objects were introduced. Currently they are also displayed in the pathbar (the wrappers acquisition-parent, to be precise). This PR adds a marker interface to hide the wrapper object.
Closes #1240.
> No longer show wrapper objects in pathbar.

- docs/HISTORY.txt
- opengever/base/viewlets/contentviews.py
- opengever/base/viewlets/pathbar.py
- opengever/locking/tests/test_lockable.py
- opengever/meeting/browser/committeetabs.py
- opengever/meeting/browser/configure.zcml
- opengever/meeting/browser/members.py
- opengever/meeting/browser/memberships.py
- opengever/meeting/committee.py
- opengever/meeting/committeecontainer.py
- opengever/meeting/interfaces.py
- opengever/meeting/model/member.py
- opengever/meeting/model/membership.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_committee_overview.py
- opengever/meeting/tests/test_locking.py
- opengever/meeting/tests/test_members.py
- opengever/meeting/tests/test_memberships.py
- opengever/meeting/wrapper.py
This PR removes `publishTraverse` hacks to lookup objects for `Member` and `Membership`. Instead a wrapper-object as first defined for `Meeting` is used.
Closes #1255.
*This PR introduces some temporary changes necessary while refactoring (green tests), i'd suggest to have a look ad the full diff only to avoid confusion*
> Remove publishTraverse hacks in favour of wrapper objects.

- docs/HISTORY.txt
- opengever/activity/browser/resolve.py
- opengever/activity/center.py
- opengever/activity/mail.py
- opengever/activity/model/activity.py
- opengever/activity/model/notification.py
- opengever/activity/model/resource.py
- opengever/activity/model/subscription.py
- opengever/activity/model/watcher.py
- opengever/activity/profiles/default/metadata.xml
- opengever/activity/tests/test_listing.py
- opengever/activity/tests/test_mail.py
- opengever/activity/tests/test_model.py
- opengever/activity/tests/test_notification_center.py
- opengever/activity/tests/test_notification_viewlet.py
- opengever/activity/tests/test_plone_center.py
- opengever/activity/tests/test_resolve.py
- opengever/activity/tests/test_views.py
- opengever/activity/tests/test_watcher.py
- opengever/activity/upgrades/configure.zcml
- opengever/activity/upgrades/to4505.py
- opengever/activity/upgrades/to4506.py
- opengever/inbox/tests/test_activities.py
- opengever/task/tests/test_activities.py
- opengever/testing/builders/activity.py
With the current implementation, the notification center has registered every single user of a inbox_group, when a task was assigned or issued by a inbox. This lead to following problems:
- A user has been notified twice in some cases.
- A user, which is no longer be part of the inbox_group, is still notified about this task, even if the user has no permissions.
...
Therefore we replaced the direct  relation between `Notification` and `Watcher` and create a Watcher for each actor instead. This means that now Watchers with the actor_id `inbox:fd` exist. 
With the described changes, the notification_center must have the ability to fetch all representatives for an actor. 
Right now the watcher model, has therefore a separate get_representatives method, which differs between users and inbox …
> Register actor as watcher instead of every single user

- docs/HISTORY.txt
- opengever/document/profiles/default/metadata.xml
- opengever/document/upgrades/configure.zcml
- opengever/document/upgrades/to4600.py
Index and column in catalog.xml has already been removed in an upgrade to
2602 - but not the actual metadata column in the catalog.
*For most customers this update is not critical and can be done eventually, in critical cases an update will be executed manually.*
> Remove leftover related_items catalog metadata.

- docs/HISTORY.txt
- opengever/activity/browser/resources/notifications.js
- opengever/base/profiles/default/jsregistry.xml
- opengever/base/upgrades/profiles/4504/jsregistry.xml
When deploying on the DEV system I found some issues on the reworked notification dropdown.
- Fix javascript for sites with disabled activity feature.
- Added missing javascript registration in the default profile of `opengever.base`
The PR #1268 only adds the handlebar.js to the upgrade profile. So newly created GEVER sites will fail with javascript errors.
- Fixed compression type for the handlebars.js, we already use the minified javascript, so no compression is needed anymore.
@lukasgraf 
Needs-backport: `4.5-stable`
> Notification dropdown fixes

- docs/HISTORY.txt
- opengever/globalindex/model/query.py
- opengever/globalindex/tests/test_query.py
If a two dossier exist inside the same repository folder, on with the id `dossier-22` and the other with the id `dossier-222`. The task from the Dossier-222 are wrongly listed in the task listing of Dossier-22.
This change will fix that issue.
@lukasgraf 
I would say it makes sense to backport this fix to the `4.5-stable` ...
> Fixed issue in Tasks `by_container` query, with similar dossier-ids.

- opengever/activity/profiles/default/jsregistry.xml
The handlebars was moved to opengever.base, but I've not cleanely removed the javascript registration entry from the activity jsregistry.xml.
@lukasgraf
> Removed wrong and outdated handlebars.js registration from the activity jsregistry.

- docs/HISTORY.txt
- opengever/task/browser/accept/utils.py
- opengever/task/exceptions.py
- opengever/task/tests/test_accept.py
- opengever/task/tests/test_assign_to_dossier.py
Because this checks, introduced by #1006, breaks the ConflictError handling for multi adminunit requests and functionalities. See #1251 for more information.
> Revert review_state check when accepting or assigning a tasks/forwarding

- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/plone.pot
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/tests/test_overview.py
- opengever/meeting/browser/documents/submit.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/tests/test_submit_additional_documents.py
This just updates the translations but leaves actions and views untouched (that's why some translation ids could not be changed yet). They should be renamed later™ though, see #1276.
Closes #1076
> Consistently name attachments of propoals.

- docs/HISTORY.txt
- opengever/testing/builders/sql.py
Corresponds to https://github.com/4teamwork/opengever.ogds.models/pull/36.
*This PR is required to fix master tests after the `opengever.ogds.models` PR has been merged.*
> Move plone-group creation in OrgUnitBuilder to opengever.core.

- docs/HISTORY.txt
- opengever/activity/model/subscription.py
- opengever/task/activities.py
- opengever/task/tests/test_activities.py
Make sure only the new responsible gets notified by mail, when a task gets reassigned.
To make sure that the old responsible is notified via batch icon, but not via mail, we change the role to `old_responsible` before record the activity, after notification creation, we remove the watcher definitely.
Theoretical it would also be possible to change the configuration, in a way that the old responsible gets also be notified by mail.
@lukasgraf please have a look.
Needs-Backport: `4.5-stable`
> Reassign: Make sure only the new responsible gets notified by mail.

- docs/HISTORY.txt
- opengever/advancedsearch/tests/test_search.py
- opengever/base/subscribers.py
- opengever/base/tests/test_anonymous.py
anonymous.
Löst das Problem, dass diverse Views auf dem Portal Root anonym zugänglich sind und so keine Challenge für eine Authentisierung ausgelöst wird.
Konkretes Beispiel: `@@accept_choose_dossier?oguid=ska-arch:732703461` führt zu einen 404 wenn der Benutzer nicht angemeldet ist.
Bei anonymen Zugriff wird jetzt bei sämtlichen Views auf dem Portal Root ein Unauthorized geraised, ausser bei den explizit aufgeführten Ausnahmen. Diese beinhalten im Wesentlichen das Login Formular und die Password-Zurücksetzen-Funktion.
@phgross , @lukasgraf Bitte insbesondere prüfen, ob die Liste mit den erlaubten Views aus euer Sicht vollständig ist. Seht ihr andere Probleme, die sich mit diesem Ansatz ergeben könnten?
> Add subscriber that disallows access to views on the portal root for

- opengever/base/subscribers.py
With the change made in #1278 the `zauth` view was no longer accessible on the site Root for an anonymous. Therefore I've added the `zauth` view to the `ALLOWED_VIEWS `.
@buchi or @lukasgraf please have a look.
Need-Backport: `4.5-stable`
> Allow accessing the ftw.zopemaster view `zauth` as anonymous.

- docs/HISTORY.txt
- opengever/meeting/browser/committeeforms.py
- opengever/meeting/committee.py
- opengever/meeting/committeeroles.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/profiles/default/rolemap.xml
- opengever/meeting/tests/test_committee.py
- opengever/meeting/tests/test_committee_roles.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/profiles/4611/rolemap.xml
- opengever/meeting/upgrades/profiles/4611/workflows/opengever_committee_workflow/definition.xml
- opengever/meeting/upgrades/to4611.py
This PR refactors meeting-permissions and adds an own role for commitee-group-members. This replaces the previous behavior where existing roles `Reader`, `Editor` and `Contributor` were managed.
Closes #950.
*When upgrading from current master (with https://github.com/4teamwork/opengever.core/pull/1263) to this PR the permissions for your dev-committees with non-zopemaster users will be broken. This is a development issue only and not addressed in this PR.*
> Refactor meeting-permissions, add own role for commitee-group-members.

- docs/HISTORY.txt
- opengever/examplecontent/profiles/default/portlets.xml
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/portlets.xml
Fixed #1290.
An upgradestep is not necessary, because all productive deployments has their own footer configuration in the policy.
@deiferni
> Adjust footer links (Release-Informationen, Quellcode).

- docs/HISTORY.txt
- opengever/locking/lock.py
- opengever/meeting/browser/protocol.py
- opengever/meeting/command.py
- opengever/meeting/tests/test_protocol.py
This PR lock protocol documents while a meeting is not closed to avoid that users get confused when editing the protocol document and the protocol through the web in parallel.
It takes a rather minimalistic approach with `plone.locking`. This has the advantage that we don't have to take further action on the document side (info message, disable actions like external editor, ...).
*The info message might need some customizing in the future though, i.e. show why the document is locked.*
Closes #1061.
> Lock protocol documents while a meeting is not closed.

- docs/HISTORY.txt
- opengever/task/browser/accept/utils.py
The problem is only obvious, when a task is assigned to a inbox. Then all inbox members, except the one who accept the task and creates the successor, are notified twice. 
Note: unfortunately writing a test for this two AdminUnit Request problem, is not simple possible.
> Eliminate duplicate notification when creating a successor after a task has been accepted.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/meeting.pt
Fixes https://github.com/4teamwork/opengever.core/issues/1314
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/370
> Extend meeting metadata with date.

- opengever/meeting/browser/resources/agendaitems.js
Fixes https://github.com/4teamwork/opengever.core/issues/1299
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/371
> Agendaitem table row width is not equal width original while dragging.

- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/profiles/4615/workflows/opengever_committeecontainer_workflow/definition.xml
- opengever/meeting/upgrades/to4615.py
Closes #1293.
*Changelog entry not necessary, it is already covered by other unreleased entries.*
*reviewer note: contains an intentional upgrade-step gap, so that https://github.com/4teamwork/opengever.core/pull/1286 can be merged first*
> Activate add-permissions for Contributor in committeecontainer workflow.

- docs/HISTORY.txt
- opengever/base/viewlets/pathbar.py
- opengever/meeting/browser/meetings/configure.zcml
- opengever/meeting/browser/meetings/excerpt.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/members.py
- opengever/meeting/form.py
- opengever/meeting/tests/test_locking.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_protocol.py
This PR
- drops meeting edit form, and merges it with protocol-editing
- refactors the protocol edit form and changes super classes to make more sense for our use-case (we edit a model, there is no proxy object)
Closes #1300.
Styling will be fixed with #1312.
> Refactor meeting/protocol editing, drop duplicate forms.

- docs/HISTORY.txt
- opengever/task/form.py
- opengever/task/task.py
- opengever/task/tests/test_forms.py
In some situation it's also possible to reassign a task, by changing the responsible in the edit form.  So this way of reassigning a task should also create a response and record an activity. 
> Make sure reassign a task over the edit form, creates a response and record an activity.

- .gitattributes
This reverts commit 28762239692c74cf3b30fdfe0cecbe6e1843e288.
In our experience this merge-strategy did not prove itself in production. It cannot always
reliably resolve conflicts without causing invalid files with missing whitespace or dropping
contributors.
> Revert "Change merge strategy(union) for the changelog."

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/meeting.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/tests/test_close.py
- opengever/meeting/tests/test_excerpt.py
- opengever/meeting/tests/test_locking.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/tests/test_unit_meeting.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4616.py
The state `held` lost its relevance and is now equivalent to `pending`.
Closes #900
> Simplify meeting workflow, drop state held.

- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/browser/resources/Scrollspy.js
- opengever/meeting/browser/resources/protocol.js
- opengever/meeting/tests/test_protocol.py
Fixes #1317 
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/374
When the protocol navigation is longer than the viewport it's unable to
see the entries below the end of the browser window. So make the
navigation scrolling automatically.
> Protocolnavigation is not usable with too many entries.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/resources/agendaitems.js
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/meeting.py
Add a js-modal dialog that requires confirmation before a meeting is closed.
Closes #1316.
> Add confirm-dialog when closing meetings.

- docs/HISTORY.txt
- opengever/base/subscribers.py
Whitelists the `mail-inbound` view which needs to be accessed anonymously by the `mta2plone.py` script.
Needs backport to `4.5-stable`
@phgross
>  Extend whitelist for anonymous access on siteroot.

- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/resources/agendaitems.js
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
Fixes https://github.com/4teamwork/opengever.core/issues/1306
Split paragraphs and text in two seperate input fields.
> Two buttons and one input for adding paragraphs and text is not useful.

- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/tests/test_protocol.py
Fixes https://github.com/4teamwork/opengever.core/issues/1342
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/383
> Restructure headings of protocol view for styling reasons.

- opengever/examplecontent/hooks.py
- opengever/setup/hooks.py
I'd like to include this in policies, similar to `assign_default_navigation_portlet`.
> Refactor blocking portlet inheritance, for easier inclusion in policies.

- docs/HISTORY.txt
- opengever/document/base.py
- opengever/document/tests/test_document.py
- opengever/meeting/command.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/profiles/default/types/opengever.meeting.proposal.xml
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_close.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/profiles/4617/types/opengever.meeting.proposal.xml
The excerpt related to a proposal will be stored in the proposal's dossier instead the proposal. It is already displayed on the proposal overview over a reference that is maintained from `Proposal.excerpt_document`.
Closes #1233.
> No longer allow adding content to proposals.

- docs/HISTORY.txt
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/plone.pot
- opengever/examplecontent/hooks.py
- opengever/meeting/browser/committee.py
- opengever/meeting/browser/committeeforms.py
- opengever/meeting/browser/periods.py
- opengever/meeting/container.py
- opengever/meeting/form.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/__init__.py
- opengever/meeting/model/period.py
- opengever/meeting/model/query.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/profiles/default/types/opengever.meeting.committee.xml
- opengever/meeting/tests/test_committee.py
- opengever/meeting/tests/test_committee_overview.py
- opengever/meeting/tests/test_period.py
- opengever/meeting/tests/test_period_query.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/profiles/4619/types/opengever.meeting.committee.xml
- opengever/meeting/upgrades/to4618.py
- opengever/testing/builders/dx.py
- opengever/testing/builders/sql.py
A period represents a timespan similar to a fiscal year.
- Display the current period on committee overview.
- Add a wizard to close the current and create its successor.
- Add a wizard that creates an initial period upon committee creation.
Addresses the first part of #1065.
> Add periods to committees

- opengever/meeting/model/meeting.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4620.py
Required by #1359.
*The column cannot be updated with onupdate since changes usually occur elsewehere, i.e. in an agenda item.*
> Add last modified column to meeting.

- opengever/meeting/browser/resources/agendaitems.js
Because of https://github.com/4teamwork/opengever.core/pull/1369 the
controller no longer has the event as the first argument. So use the
target object from the callback to get the href from the modal.
> Closing a meeting throws error on javascript.

- opengever/base/subscribers.py
- opengever/document/checkout/handlers.py
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/command.py
This PR fixes an issue with untranslated `portal_repository` comments. This issue affects all comments not only some meeting comments as stated in #1375.
When storing translated `Messages` in the `portal_repository` they are not translated automatically but need to be translated manually with `translate`.
Closes #1375.
> Translate portal_repository comments.

- docs/HISTORY.txt
- opengever/activity/upgrades/to4505.py
On deployments with a MySQL OGDS backend the `ReplaceNotificationsWatcherRelation` Upgradestep has raised the following MySQL error:
```
Module opengever.core.upgrade, line 100, in drop_column
Module alembic.operations, line 650, in drop_column
Module alembic.ddl.impl, line 179, in drop_column
Module alembic.ddl.impl, line 122, in _exec
Module sqlalchemy.engine.base, line 914, in execute
Module sqlalchemy.sql.ddl, line 68, in _execute_on_connection
Module sqlalchemy.engine.base, line 968, in _execute_ddl
Module sqlalchemy.engine.base, line 1146, in _execute_context
Module sqlalchemy.engine.base, line 1341, in _handle_dbapi_exception
Module sqlalchemy.util.compat, line 199, in raise_from_cause
Module sqlalchemy.engine.base, line 1139, in _execute_context
Module sqlalchemy.engine.default, …
```
> Fixes activity upgradestep 4505 for MySQL.

- docs/HISTORY.txt
The release `4.5.8` was relased from the `4.5-stable` branch.
> Cleanup changelog after Bugfix Release 4.5.8.

- opengever/meeting/browser/resources/protocol.js
Fix for https://github.com/4teamwork/opengever.core/pull/1378
Probably because of a rebase issue the saveProtocol method is defined
twice.
> Saving protocol does not work.

- opengever/meeting/browser/resources/protocol.js
- Protocol gets saved when clicking cancel.
- Set event handler to save button instead of form.
- Discard localstorage saved protocol when hitting cancel.
> Save protocol only when clicking on save button.

- docs/HISTORY.txt
- opengever/meeting/browser/sablontemplate.py
- opengever/meeting/tests/test_protocol_json_data.py
- opengever/meeting/tests/test_sablon_template.py
This view aims to simplify modifying templates by providing a method to debug them without the need to setup additional content.
Closes #1385.
> Add meeting-data debug view for sablon templates.

- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/protocol.py
- opengever/meeting/command.py
- opengever/meeting/tests/test_protocol.py
Dieser PR vereinfacht das aktualisieren eines Protokolls. Anstatt dem Benutzer die Wahl zu bieten entweder das bestehende Dokument zu aktualisieren oder ein neues zu erstellen wird immer das schon bestehende Protokoll aktualisiert. Das Formular entfällt deshalb.
Closes #1374.
> Formular Protokoll aktualisieren entfernen

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/resources/meeting.js
- opengever/meeting/browser/templates/macros.pt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/meeting.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_decide.py
- opengever/meeting/tests/test_hold.py
- opengever/meeting/tests/test_unit_agenda_item.py
- opengever/meeting/tests/test_unit_meeting.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4624.py
- opengever/meeting/workflow.py
Wie in #1356 bereits beschrieben, müssen AgendaItems einzeln abgeschlossen werden können.
Dieser PR fügt diese Funktionalität hinzu.
Dazugehöriger PR: https://github.com/4teamwork/plonetheme.teamraum/pull/397
Wird ein Traktandum beschlossen, so wird automatisch auch die Sitzung in den Status `beschlossen` versetzt. Im Status `beschlossen` kann zwar das Protokoll noch bearbeitet werden, die Traktandenliste ist aber fix (löschen, verschieben ist nicht mehr möglich) da die Sitzungs- und Beschlussnummern bereits vergeben sind.
Noch nicht Teil des PR sind folgende Wünsche/Anpassungen:
- Aktualisieren eines Entscheids/Protokollauszug
- Die Funktionalität für den Status `Communicated`
Stylings in separatem PR in `plonetheme.teamraum` umgesetzt.
@deiferni
> Separates beschliessen eines AgendaItems 

- opengever/base/casauth.py
- opengever/base/tests/test_casauth.py
Strip trailing slashes in admin_unit's public_url, when putting together the CAS portal URL.
@deiferni
> Avoid duplicated slashes when generating the CAS portal URL.

- docs/HISTORY.txt
- opengever/base/security.py
- opengever/base/tests/test_security.py
- opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
- opengever/meeting/browser/proposaltransitions.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4625.py
This PR adds a workflow transition to reject a proposal and revert it to pending state. It is possible to enter an optional comment indicating why the proposal was rejected.
This PR also contains an improved way to elevate a current user's privileges, it is now possible to retain the username and avoid `specialusers.system`.
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/399.
Closes #1371.
> Allow rejecting proposals from a committee.

- opengever/meeting/model/period.py
The default form auto-naming is [tablename]-[column_name]-seq.
Closes #1409.
> Fix sequence name.

- opengever/meeting/model/proposal.py
- opengever/meeting/tests/test_proposal.py
The problem was caused by not removing all references to submitted_document from the proposal history entries. The submitted documents are deleted when rejecting the proposal because the `SubmittedProposal` proxy object is removed upon reject.
Fixes #1433.
> Fix an issue where proposals could not be rejected.

- opengever/meeting/browser/sablontemplate.py
- opengever/meeting/protocol.py
- opengever/meeting/tests/test_protocol_json_data.py
Adjustments on the template aren't necessary, because the committee.name is already used in the template.
Fixes #1422
@deiferni
> Extend protocol json data with the committee name.

- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
Consistently use "Kommission" instead of "Kommittee".
Closes #1416.
> Fix german translations for committee.

- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base.pot
- opengever/base/validators.py
- opengever/meeting/committee.py
- opengever/meeting/tests/test_committee.py
- opengever/task/browser/accept/newdossier.py
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
When linking committees to a repository folder it is essential that a leaf
repository folder is selected. Otherwise it cannot contain dossiers for the
committee's meeting.
Fixes #1415.
> Validate that leaf repository folder is selected for committee.

- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/tests/test_agendaitem.py
Fixes #1430 
Extend agenda item with `has_document` method to determine if any documents or excerpts are attached.
> Agendaitem is not expandable if only an excerpt is attached.

- opengever/meeting/protocol.py
- opengever/meeting/tests/test_protocol_json_data.py
Right now its possible to remove a membership, but the meeting stores a list of members not of memberships, therefore it needs a fallback when no membership is found.
Fixes #1425
> Add fallback for members without any committee membership when generating ProtocolData.

- opengever/meeting/browser/resources/protocol.js
Prevent the default event, when clicking on the save link in the protocol view.
Because the save method is redirecting manually back to the meeting view, after saving the changes via AJAX requests, we prevent the default link event. Fixes #1420.
@deiferni
> Fix save link in meetings protocol view.

- opengever/base/browser/navtree.py
Don't render duplicate icon in contenttree widget.
Closes #1443.
> Disable rendering of sablon template icons in navtree.

- opengever/meeting/browser/resources/Scrollspy.js
- opengever/meeting/browser/resources/protocol.js
Because of https://github.com/4teamwork/opengever.core/pull/1449 the `moveToCaret` function was not moved correctly to `Srollspy.js`.
> Moving caret to end does not work.

- opengever/base/monkeypatch.py
Monkey patch the regex used to replace relative paths in url() statements with absolute paths in the portal_css tool. This has been fixed as of release 3.0.3 of Products.ResourceRegistries which is only available for Plone 5.
See https://github.com/plone/Products.ResourceRegistries/commit/4f9094919bc1c50404e74c748b067a3563e640aa
Fixes #1434.
> Monkey patch the regex used to replace relative paths in url() statements.

- opengever/advancedsearch/advanced_search.py
- opengever/base/browser/templates/macros.pt
- opengever/meeting/browser/meetings/protocol.py
Fixes https://github.com/4teamwork/opengever.core/issues/1454
Implement enable_unload_protection configurable for each form. Will be fixed in plone.app.z3cform@0.7.6 -> https://pypi.python.org/pypi/plone.app.z3cform#id12
Disable unload_protection for protocol.
Disable unload protection for advanced search instead of overriding render method.
> Disable unload protection for protocol.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/committee.py
- opengever/meeting/model/committee.py
- opengever/meeting/model/meeting.py
- opengever/meeting/tests/test_meeting.py
This is done for convenience, usually most of the active members of a meeting do participate.
Closes #1424.
> Set all active members of a committee as meeting participants by default.

- opengever/activity/browser/resources/notifications.js
- opengever/activity/viewlets/notification.pt
With the PR #1378 the order in the jsregistry gets modified, so that plone's dropdown.js is now called earlier than our notification.js. This means that the notification dropdown menu does not work (don't drop down when clicking on the bell image).
The real problem is that the `toggleMenuHandler` in plone's `dropdown.js` return false instead of just prevent the default link event.
So to resolve this issue, we removed the actionMenuHeader class from the notification viewlet template.
> Addded js workaroud to fix notification dropdown menu.

- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/tests/test_meeting.py
Also improve close meeting tests a bit by asserting that the info message is displayed..
Closes  #1461.
> Only show edit button when meeting is editable.

- docs/HISTORY.txt
- opengever/activity/configure.zcml
- opengever/base/configure.zcml
- opengever/contact/configure.zcml
- opengever/document/profiles.zcml
- opengever/dossier/profiles.zcml
- opengever/examplecontent/configure.zcml
- opengever/inbox/configure.zcml
- opengever/mail/configure.zcml
- opengever/ogds/base/configure.zcml
- opengever/setup/profiles.zcml
- opengever/tabbedview/configure.zcml
- opengever/task/profiles.zcml
- opengever/trash/profiles.zcml
As documented in https://github.com/4teamwork/ftw.profilehook#usage we should always include ftw.profilehook in our zcml files.
This helps fixing an issue with failing opengever.maintenance tests.
> Include ftw.profilehook, when required.

- docs/HISTORY.txt
- opengever/base/behaviors/translated_title.py
- opengever/base/tests/test_translated_title.py
This PR allows `None` values to be set for translated attributes.
This happens when content is created during setup with transmogrifier. It
inserts default-values (`None` in this case) for some fields.
Closes #1471.
> Fix an issue with setting-up translated content with transmogrifiers schemaupdater.

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/browser/gever_state.py
- opengever/base/casauth.py
- opengever/base/interfaces.py
- opengever/base/tests/test_casauth.py
- opengever/base/tests/test_gever_state.py
- opengever/document/browser/logout_overlay.py
- opengever/document/tests/test_logout_overlay.py
- opengever/setup/casauth.py
- opengever/setup/configure.zcml
- opengever/setup/profiles/casauth/metadata.xml
- opengever/setup/upgrades/casauth_profiles/4600/actions.xml
- opengever/setup/upgrades/configure.zcml
This PR introduces separate concepts for
- the base URL for the **GEVER cluster**
- the **CAS server** URL
- the **GEVER portal** URL
---
The **CAS server URL** is only constructed once (during setup) and used to configure the `ftw.casauth` PAS plugin. After that, the CAS server URL will always be retrieved from that plugin's property (for example to build the link for single-logout).
The **GEVER portal URL** however is constructed dynamically.
Both those URLs happen to be the same in our current setups, but they're always built using the **base URL of the GEVER cluster** as a base.
The GEVER cluster's base URL is determined through a heuristic: If the admin unit's `public_url` ends with the admin unit's ID, we're probably dealing with a multi-admin-unit setup, so we strip the admin unit …
> Fix CAS server and GEVER portal URLs

- docs/HISTORY.txt
- opengever/task/statesyncer.py
- opengever/task/tests/test_assign.py
When reassigning a multi AdminUnit task, the response on the foreign side, was not completly synchronised. The responsible attribute in the response changes was wrong. This PR fixes this problem.
Before:
After:
@lukasgraf or @deiferni
> Fixed missing `responsible` parameters in synced responses.

- docs/HISTORY.txt
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/meeting.py
- opengever/meeting/tests/test_unit_meeting.py
Paragraphs don't need decision numbers. They are not displayed anywhere but lead to gaps in the visible decision numbers for the other agenda items.
Fixes #1469.
> Don't generate decision numbers for paragraphs.

- docs/HISTORY.txt
- opengever/meeting/model/agendaitem.py
The problem currently only surfaces in the generated excerpt word documents. I did not see a way to add  tests for those :disappointed:. 
Fixes #1468.
> Make sure that decision numbers are available when rendering excerpts.

- docs/HISTORY.txt
- opengever/meeting/browser/sablontemplate.py
- opengever/meeting/tests/test_committee_overview.py
- opengever/meeting/tests/test_members.py
- opengever/meeting/tests/test_pathbar.py
- opengever/meeting/tests/test_protocol_json_data.py
- opengever/meeting/wrapper.py
- opengever/testing/builders/sql.py
Also introduce umlauts to the default member fixture created by the builder to avoid such errors in the future.
Fixes #1488.
> Fix an encoding issue while editing memberships.

- docs/HISTORY.txt
- opengever/meeting/model/meeting.py
- opengever/meeting/model/query.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/tests/test_unit_membership_query.py
- opengever/meeting/vocabulary.py
Use the meeting's date to find active memberships at the time when the
meeting takes place to edit the meetings participants instead of the current
date.
Fixes #1482.
> Don't use current date when editing meeting participants.

- docs/HISTORY.txt
- opengever/base/monkeypatch.py
Patch for Products.CMFEditions.historyidhandlertool.HistoryIdHandlerTool.register
The default "register" method uses the Products.CMFUid IUniqueIdGenerator utility for generating the history ID. This utility uses the auto-increment strategy, which generates a lot of conflicts.
In order to reduce the conflicts when generating the history id, we switch to the uuid4 implementation, generating a random number instead and thus not writing to the same place
--
The problem is when multiple users upload documents at the same time. The format of the used ID is not really relevant. Therefore no migration of existing objects is required; the old objects just use a smaller integer as ID.
> Reduce conflict errors by using uuid4 in CMFEditions.

- docs/HISTORY.txt
- opengever/contact/upgrades/to4600.py
- opengever/contact/upgrades/to4601.py
- opengever/dossier/upgrades/to4600.py
- opengever/inbox/upgrades/to4600.py
- opengever/meeting/upgrades/to4627.py
- opengever/repository/upgrades/to4601.py
- opengever/repository/upgrades/to4602.py
MySQL implicitly commits savepoints as soon as a DDL statement is emitted (similar to Oracle).
That means we can't reliably use savepoints in upgrade paths that contain upgrades involving DDL.
@deiferni
> Don't create savepoints in 46xx upgrade steps

- docs/HISTORY.txt
- opengever/meeting/upgrades/to4600.py
This fixes the migration when run with MySQL.
Tested and working with MySQL, PostreSQL and Oracle.
Fixes #1514.
> Drop foreign key constraint before dropping column.

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/ldap/ldap_plugin.xml.bob
This PR catches up with recent changes in our LDAP structure and corrects the path used in LDAP templates.
It also fixes an error in a template where a variable was not substituted correctly.
> Use new SAAS customer path in ldap template.

- docs/HISTORY.txt
- opengever/base/tests/test_widget.py
- opengever/base/widgets.py
- opengever/base/widgets.zcml
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_protocol.py
This PR prevents vulerability to XSS by transforming trix input to safe_html using a plone transform on:
- The protocol page (where input fields are rendered manually)
- For the trix widget using a `DataConverter`
Closes #1529.
> Transform trix input to safe_html to prevent XSS vulerability.

- docs/HISTORY.txt
- opengever/meeting/tabs/meetinglisting.py
- opengever/meeting/tests/test_committee_tabs.py
Fixes https://github.com/4teamwork/opengever.core/issues/1456
As requested in https://github.com/4teamwork/opengever.core/issues/1456
display an additional column for the meeting state similar to the
proposals overview.
> Display state column in meeting overview tab of committee.

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/.mrbob.ini
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/configure.zcml.bob
Erweiterung für Policytemplate:
- casauth-Plugin kann optional hinzugefügt werden.
closes #1544
> Update policy templates to include casauth plugin

- docs/HISTORY.txt
- opengever/examplecontent/profiles/default/portlets.xml
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/portlets.xml
Old one points to http://feedback.onegov.ch, new one should point to https://feedback.onegovgever.ch/ instead. Fixes #1553
> Update link to feedback forum in example content and policy template footers.

- docs/HISTORY.txt
- opengever/base/profiles/default/metadata.xml
- opengever/base/sequence.py
- opengever/base/upgrades/configure.zcml
- opengever/base/upgrades/to4609.py
- opengever/setup/browser/admin.py
- opengever/setup/interfaces.py
:construction: DON'T MERGE YET - SEE DISCUSSION :construction: 
Refactor sequence number generation in order to reduce conflicts
in content creation requests and to ensure uniqueness.
The old Increaser approach hat various flaws, such as it did not make
sure that the number is unique and it did not really help regarding
conflicts.
The new approach moves the incrementation of the sequence number to a
separate transaction which is commited before the number is returned and
thus uniqueness is assured.
By handling the conflict errors while generating the number we reduce
conflict errors in the main content creation transaction.
The Increaser-objects needs to be migrated to normal integers so that
conflicts arise and we can handle them by retrying.
Up to 10 retries are made before the conflict …
> Refactor sequence number generation.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/browser/resources/Scrollspy.js
- opengever/meeting/tests/test_protocol.py
Fixes https://github.com/4teamwork/opengever.core/issues/1548
> Exclude non visible fields from the scrollspy navigation.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/browser/resources/protocol.js
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_protocol.py
Prevent that the protocol form can overwrite a newer version of the protocol.
If concurrent modifications occur we don't offer conflict resolution as of yet but leave the submitted form open to allow the user to take manual action.
Closes #1563.
*This problem should only occur in rare cases when users leave tabs open that contain unsaved changes or modify the same content in several tabs at the same time.*
> Prevent protocol overwrites.

- docs/HISTORY.txt
- opengever/dossier/profiles/default/metadata.xml
- opengever/dossier/upgrades/configure.zcml
- opengever/dossier/upgrades/profiles/4601/catalog.xml
It seems that the "reference_number" metadata in the catalog is no longer in use.
It usually seems to be Missing.Value.
:scissors: :sunglasses: 
Closes #1570
> Remove "reference_number" from catalog metadata.

- docs/HISTORY.txt
- opengever/base/adapters.py
- opengever/base/tests/test_reference_prefix.py
- opengever/dossier/tests/test_move_items.py
When moving an object back to a previous  parent, the previous reference number is recycled.
Solves these problems:
- When moving an object and selecting the current parent, which means that the object is not moved in fact, we now no longer change the reference number.
- When moving an object back to a container where it was before and already had a reference number, the reference number is now automatically recycled (unless explicitly set through the API).
Fixes #1521
> Recycle reference numbers.

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
Vorher:
-----------
Nachher:
-------------
closes #1538
> Change translation for label_publish_in

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
Folgende Übersetzungen wurden angepasst:
closes #1537
> Translate "Standort" to "Sitzungsort" for Meetings.

- docs/HISTORY.txt
- opengever/meeting/profiles/default/metadata.xml
- opengever/meeting/profiles/default/types/opengever.meeting.sablontemplate.xml
- opengever/meeting/upgrades/configure.zcml
- opengever/meeting/upgrades/to4631.py
> Display versions tab for sablon templates.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_protocol.py
Fixes #1564.
Remain on the form after a the error occurred, when the other user unlocks the protocol without modifications, it can be saved again by the current user.
Also, cleanup changelog.
> Prevent saving the protocol when it is locked by another user.

- docs/HISTORY.txt
- opengever/base/profiles/default/metadata.xml
- opengever/base/upgrades/configure.zcml
- opengever/base/upgrades/to4610.py
This is an upgrade step that basically applies the changes from #1554 to all deployments (if needed).
While the original change affects `opengever.examplecontent` and the policy template (in order not to set up new sites containing the wrong link), this upgrade step is in `opengever.base` and will be run for **all deployments**.
It's written in a way that should specifically fix the feedback forum URL if it occurs in an `ftw.footer` portlet, regardless of how that portlet was added.
> Add upgrade-step to update feedback link in footer (if necessary).

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tabs/proposallisting.py
- opengever/meeting/tabs/submittedproposallisting.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_proposal_listings.py
- opengever/tabbedview/profiles/default/metadata.xml
- opengever/tabbedview/upgrades/configure.zcml
- opengever/tabbedview/upgrades/to4600.py
- opengever/testing/builders/sql.py
Die Spalten `Ausgangslage` und `Antrag` können Markup Text enthalten.
Eine Tabelle mit Markup kann nicht schön dargestellt werden. Zudem sind es zu viele Infos für den Benuzer.
- Deshalb wurden die o.g. Spalten aus den Auflistungen entfernt.
Zwei neue Spalten kamen dazu:
- Die `Laufnummer` ist hilfreich für das wiederfinden eines Antrags und wird deshalb neu in den Auflistungen dargestellt.
- Die `Sitzung` beinhaltet ein Link zur Sitzung in welcher der Antrag traktandiert wurde. Dieser Link ist sehr hilfreich zum schnellen auffinden der jeweiligen Sitzung.
Before:
----------
After:
--------
see #1542
> Spalten in Antragsauflistungen überarbeitet

- docs/HISTORY.txt
- opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
Das zweispaltige Layout brauch zu viel Platz für Dokumente und stellt zu wenig Platz für die Tabelle dar.
Es wird nicht erwartet, dass die Benutzer viele Dokumente hochladen.
Deshalb werden die Dokumente neu in der Tabelle angezeigt und das Layout auf ein einspaltiges Layout reduziert.
Die Tabelle hat nun bei bedarf die ganze Seitenbreite zur Verfügung.
Before:
----------
After:
-------
closes #1542
> Antragsansicht überarbeitet: Zweispaltiges Layout in einspaltiges Layout geändert.

- docs/HISTORY.txt
- opengever/base/locales/fr/LC_MESSAGES/plone.po
Die französische Übersetzung für "In bearbeitung" (En modifiaction) im Dossier-Tab stimmt nicht mit dem eCH-0039 Standard überein.
Dieser PR übersetzt die französische Übersetzung gem. eCH-0039 Standard.
closes #1513
> Adjust french translation 'En modification' to eCH-0039-standard 'En cours de traitement'

- docs/HISTORY.txt
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
Die Antragsansicht hat neue Attribute erhalten:
Folgende Attribute wurden für Anträge und gesendete Anträge hinzugefügt:
- Veröffentlichung in
- Zu eröffnen an
- Kopie z.K.
Folgende Attribute wurden nur für gesendete Anträge hinzugefügt:
- Erwägung
- Diskussion
closes #1582
> Neue Attribute für die Antrags-Ansicht hinzugefügt.

- docs/HISTORY.txt
- opengever/meeting/model/proposal.py
- opengever/meeting/proposal.py
- opengever/meeting/tabs/proposallisting.py
- opengever/meeting/tests/test_proposal.py
In den Antrags-Eigenschaften wird nun ein Link zum jeweiligen Meeting angezeigt: 
closes #1568
> Link von Antrag nach Meeting hinzugefügt

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/proposal.py
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
Link vom eingereichten Antrag zum Dossier hinzugefügt.
Dieser Link funktioniert nur, wenn sich der Antrag und das Dossier auf der gleichen AdminUnit befinden.
Sollten sich die AdminUnit unterscheiden, wird anstatt der Link ein statischer Text angezeigt mit "Dossier nicht verfügbar".
closes #1355
> Link vom eingereichten Antrag zum Dossier

- docs/HISTORY.txt
- opengever/meeting/command.py
- opengever/meeting/model/proposal.py
- opengever/meeting/tests/test_close.py
- opengever/meeting/tests/test_excerpt.py
- opengever/meeting/tests/test_protocol.py
Aktuell ist der Titel eines Protokollauszugs 
> Protokollauszug-[Sitzungstitel, Sitzungsdatum].
Neu weist der Titel folgendes Format auf:
> [Titel Antrag] - [Sitzungstitel, Sitzungsdatum].
closes #1569
> Ändert den Titel des Protokollauszugs

- development.cfg
- docs/HISTORY.txt
- setup.py
- sources.cfg
- test-plone-4.3.x.cfg
This is the first step for integrating [`plone.restapi`](https://github.com/plone/plone.restapi) into `opengever.core`.
This introduces an `[api]` extra for `opengever.core`, and uses it for tests and development.
For now, both `plone.rest` and `plone.restapi` will be used from source:
- plone.restapi doesn't have a release yet
- plone.rest is still changing heavily, we want to stay current for now
> Introduce [api] extra to pull in plone.restapi and use it for tests and development

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/unscheduled_proposals.py
- opengever/meeting/tests/test_unscheduled_proposals.py
Fügt einen Link von nicht traktandierten eingereichten Anträgen der Sitzungsübersicht zu dem jeweiligen eingereichten Auftrag.
closes #1362
> Add link in meetingoverview from unscheduled proposals to their corresponding submitted proposals.

- docs/HISTORY.txt
- opengever/core/upgrade.py
- opengever/meeting/upgrades/to4603.py
- opengever/meeting/upgrades/to4633.py
Don't load proposal model in upgrade steps but use sqlalchemy expression api for database access. This ensures that migrations also run in the future, when the model changes.
Also add a separate base-class for sql-based migrations that need to run once per plone site/admin-unit and not only once per cluster.
Fixes #1605
> Fixes an issue with broken db-migrations.

- docs/HISTORY.txt
- opengever/base/reference.py
This avoids an infinite loop in `BasicReferenceNumber.get_parent_numbers()` if the context is not acquisition wrapped: The loop also needs to be terminated when `aq_parent(obj)` returns `None`, which is the case for unwrapped objects.
@deiferni
> Avoid infinite loop in BasicReferenceNumber.get_parent_numbers()

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/tests/test_unit_agenda_item.py
Bisher konnte ein beschlossenes Traktandum weiterhin in der Protokollansicht bearbeitet werden.
Dieser PR verhindert das weitere Bearbeiten eines Traktandums nachdem dieses beschlossen wurde. Anstatt des Editors wird das Feld als Text angezeigt. Leere Felder werden mit einem Defaultwert '-' angezeigt.
closes #1594
> Beschlossene Traktanden dürfen nicht mehr bearbeitet werden können.

- docs/HISTORY.txt
- opengever/examplecontent/hooks.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/resources/meeting.js
- opengever/meeting/model/meeting.py
- opengever/meeting/tests/test_close.py
- opengever/meeting/tests/test_committee_tabs.py
- opengever/meeting/tests/test_excerpt.py
- opengever/meeting/tests/test_locking.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_meeting_dossier_overview.py
- opengever/meeting/tests/test_meeting_view.py
- opengever/meeting/tests/test_pathbar.py
- opengever/meeting/tests/test_proposal_listings.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/upgrades/20160218114243_add_title_column_to_meeting/upgrade.py
- opengever/testing/builders/sql.py
Der User kann den Sitzungstitel nun manuell setzten.
Der Titel wir standardmässig mit folgendem Format ausgefüllt: [Kommisionstitel], [Datum]
Solange der Benutzer den Titel nicht verändert, wird dieser mit dem Startdatum synchronisiert.
Änder also der Benutzer das Startdatum, wird das Datum im Titel automatisch aktualisiert.
Der Titel kann auch nachträglich über die Protokollverwaltung geändert werden.
closes #1360
> Editierbarer Titel für Sitzungsobjekte hinzugefügt.

- docs/HISTORY.txt
- opengever/base/behaviors/utils.py
- opengever/base/utils.py
Avoid infinite loops in `find_parent_dossier()` and `set_default_with_acquisition()` if context is not acquisition wrapped.
@deiferni
> Avoid some more infinite loops for non-acquisition wrapped contexts

- docs/HISTORY.txt
- opengever/base/browser/resources/trix-custom.js
- opengever/base/profiles/default/jsregistry.xml
- opengever/base/upgrades/20160229120650_add_trix_customizations/jsregistry.xml
- opengever/base/upgrades/20160229120650_add_trix_customizations/upgrade.py
Add trix customizations to prevent accepting unsupported content.
We don't support links, quotes, code-blocks and file uploads of any kind.
Fixes #1625.
> Add trix configuration to prevent adding unsupported content.

- docs/HISTORY.txt
- opengever/base/browser/resources/base.js
- opengever/base/subscribers.py
- sources.cfg
This is a follow-up for #1278 to also prevent access when context does not provide `IPloneSiteRoot` but `IBrowserView` as is the case for e.g. a `TabbedView`. Fixes #1608.
It also contains a custom event handler for an event that is added in https://github.com/4teamwork/ftw.tabbedview/pull/51. It issues a page reload which then causes a redirect to the login form when we receive requests from the gever portal.
See also https://github.com/4teamwork/ftw.tabbedview/pull/51
> Prevent anonymous access to browser views on plone site.

- docs/HISTORY.txt
- opengever/mail/browser/send_document.py
- opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/opengever.mail.pot
- opengever/mail/tests/test_senddocument.py
Dieser PR verhindert, dass der Benutzer bei einem Mailversand die E-Mail als Dokument ablegen kann wenn das Dossier bereits geschlossen ist.
Wenn das Dossier geschlossen ist, wird die Checkbox im Formular auf `hidden` gesetzt, damit der Benutzer diese nicht mehr sieht.
Die Kopie wird schlussendlich nur erstellt, wenn das Dossier im Status 'aktiv' ist.
Ansicht bei aktivem Dossier:
Ansicht bei inaktivem Dossier:
closes #1235
> Dokumentversand: Kopie ablegen bei geschlossenen Dossiers ist nicht mehr möglich.

- docs/HISTORY.txt
- opengever/meeting/browser/proposaloverview.py
- opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/tests/test_submit_additional_documents.py
Abgelaufene Dokumente können im Auftrag aktualisiert werden.
SubittedProposals werden wie bisher angezeigt.
closes #936
> Abgelaufene Dokumente können im Auftrag aktualisiert werden.

- docs/HISTORY.txt
- opengever/locking/configure.zcml
- opengever/locking/info.py
- opengever/locking/locales/de/LC_MESSAGES/opengever.locking.po
- opengever/locking/locales/fr/LC_MESSAGES/opengever.locking.po
- opengever/locking/locales/opengever.locking.pot
- opengever/locking/lock.py
- opengever/locking/templates/meeting_lock.pt
- opengever/meeting/tests/test_protocol.py
Die Meldung von gesperrten Protokollen wurde verbessert.
closes #1617
> Meldung gesperrte Protokolle wurde verbessert.

- docs/HISTORY.txt
- opengever/base/skins/opengever.base_scripts/require_login.py
- opengever/base/tests/test_require_login.py
Add fix as documented on the plone documentation:
http://docs.plone.org/develop/plone/sessions/login.html#hyperlinks-to-authenticated-plone-content-in-microsoft-office
The fix hacks around MS office's behavior to resolve links prior to opening a browser. This lead to an "insufficient privileges" page being displayed if the user was already logged in. The fix attempts to traverse to the came_from url that is available to the require_login script, and if the url is traversable redirects to that location.
Manually tested on **Windows 10**:
**OSX**:
Fixes #1200.
> Overwrite require_login script to avoid problems with links from MS office.

- docs/HISTORY.txt
- opengever/base/transport.py
- opengever/meeting/browser/excerpt.py
- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/protocol.py
- opengever/meeting/browser/resources/meeting.js
- opengever/meeting/command.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/agendaitem.py
- opengever/meeting/model/meeting.py
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/tests/test_unit_agenda_item.py
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/416
Traktanden können überarbeitet werden solange die Sitzung nicht abgeschlossen wurde.
Wieder eröffnen:
Wieder eröffnen entsperrt den Text in der Protokollmaske.
Überarbeiten:
Überarbeiten sperrt den text in der Protokollmaske, die Protokollauszüge des Antrags werden neu generiert.
Closes #1356.
> Allow revision for decided agenda-items.

- docs/HISTORY.txt
- opengever/base/browser/resources/Controller.js
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/meetings/templates/protocol.pt
- opengever/meeting/browser/resources/protocol.js
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_protocol.py
Fixes https://github.com/4teamwork/opengever.core/issues/1579 
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/414
Im not happy about https://github.com/4teamwork/opengever.core/compare/kb_corrupt_changes?expand=1#diff-0df47629165198501befb1dd4d1fc069R20 maybe we should implement this in an other way.
> Show hint for corrupt protocol changes.

- docs/HISTORY.txt
- opengever/base/redirector.py
Make sure `IRedirector` JS redirects aren't unconditionally trigged when the user is on the @@confirm-action view.
Fixes #1236
> Don't trigger IRedirector JS redirects on @@confirm-action

- docs/HISTORY.txt
- opengever/base/reference_formatter.py
- opengever/base/tests/test_reference.py
Add a reference number formatter which omits the client id but behaves the same as `grouped_by_three` otherwise.
This is done minimally invasive without touching existing code, at the cost of some duplication.
> Add no_client_id_grouped_by_three reference number formatter.

- docs/HISTORY.txt
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/rolemap.xml
SaaS customers should always be able to do so.
> Activate "remove GEVER content" by default for new policies.

- docs/HISTORY.txt
- opengever/base/reference_formatter.py
- opengever/base/tests/test_reference.py
Because it has no leading `client_id`, the `no_client_id_grouped_by_three` formatter also needs its own sorting logic.
The `sorter()` method is an exact copy of the one from its superclass, minus the [line that tries to split by client ID](https://github.com/4teamwork/opengever.core/blob/f0d1e0ef7f5667fe70c47d7b8cf08c857063c272/opengever/base/reference_formatter.py#L126).
Only verified via tests, haven't actually tested this on a real site yet.
Also see: https://github.com/4teamwork/opengever.core/issues/1561 (We should probably use a `sortable_reference` index instead of sorting on demand).
> Implement sorter for 'no_client_id_grouped_by_three' reference number formatter

- docs/HISTORY.txt
- opengever/base/browser/resources/datetimepicker.js
- opengever/meeting/browser/resources/datetimepicker.js
- opengever/meeting/browser/resources/protocol.js
Since the update to 2.3.8 of bootstrap-datetimepicker the bug here
smalot/bootstrap-datetimepicker#122 is fixed.
So we dont need the workarround applying the timezone manually.
Making a UTC date extending a datestring with `UTC` does not work on IE.
So the backend received invalid date and the protocol could not be saved.
> Fix protocol saving on IE.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/datetimepicker.js
Depends on https://github.com/4teamwork/opengever.core/pull/1642
When the user wants to edit a protocol the datetimepicker always
sets a new date instead of taking the existing date from the server.
So check if the datefileds are prefilled before inserting a new date.
A new date should only get inserted when creating a new meeting.
> Take existing date from server to feed the datetimepicker.

- docs/HISTORY.txt
- opengever/base/tests/test_utils.py
- opengever/base/utils.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/sablontemplate.py
- opengever/meeting/model/member.py
- opengever/meeting/protocol.py
- opengever/meeting/tests/test_meeting.py
- opengever/meeting/tests/test_meeting_view.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/tests/test_protocol_json_data.py
- opengever/meeting/vocabulary.py
Emailadressen werden nun zusätzlich zum Namen an folgenden Orten angezeigt:
Sitzung
----------
Protokoll bearbeiten
---------------------------
Protokoll
------------
> Email-Adressen von Teilnehmern werden in Meetings angezeigt.

- docs/api/_static/custom.css
- docs/api/basics.rst
- docs/api/conf.py
- docs/api/content_types.rst
- docs/api/index.rst
- docs/api/operations.rst
- sphinx.cfg
Adds two more chapters to the API docs:
- **Basics** - describes how the overall interaction with the API happens
- **Operations** - Describes what HTTP Methods are mapped to which operation
@deiferni
> API docs: Add `basics` and `operations` chapters.

- docs/HISTORY.txt
- opengever/tabbedview/browser/personal_overview.py
- sources.cfg
- use optimized method in `AdminUnit` to determine if a user is assigned to it
- memoize `user_is_allowed_to_view` per request as it's called multiple times in some views.
> Optimize `user_is_allowed_to_view()`.

- docs/HISTORY.txt
- opengever/meeting/protocol.py
- opengever/meeting/tests/test_protocol_json_data.py
With this PR excerpts genrated with sablon start with page number 1.
Closes #1641.
> No longer set start-page for documents generated as protocol excerpts.

- docs/HISTORY.txt
- opengever/meeting/committee.py
- opengever/meeting/tests/test_committee_roles.py
- sources.cfg
Bisher wurde jeweils alle Gruppen zum Auswählen angezeigt.
Neu werden nur noch Gruppen angezeigt, in denen der Benutzer selbst ein Mitglied ist.
closes #1512
> Filtert die Gruppen beim Hinzufügen eines Gremiums

- docs/HISTORY.txt
- opengever/base/brain.py
- opengever/base/tests/test_translated_title.py
Das Problem tritt auf wenn ein Repositoryfolder mit Umlauten und ein Dossier mit Umlauten existieren und beide Objekte im Resultat vorhanden sind.
Das Problem liegt im ``TranslatedTitleBrain`` Catalog-Brain:
https://github.com/4teamwork/opengever.core/blob/master/opengever/base/brain.py#L16
Die Funktion muss UTF-8 zurück geben da per default die Titel-Funktion UTF-8 zurück gibt.
> Fix broken TranslatedTitleBrain - return utf-8 instead of unicode

- README.rst
- sphinx.cfg
- Make build script accept format argument (default: `html`)
- Add script to publish docs
- Update `README` to document how to build API docs
@deiferni
> Update and document build scripts for API docs

- docs/api/conf.py
Switch to the sidebar templates shipped with the Alabaster theme, so we get a global TOC in the navigation that stays stable and doesn't cause the reader to lose context.
> API docs: Improve navigation

- docs/api/conf.py
- sphinx.cfg
Enables Google Analytics for `docs.onegovgever.ch`.
> API docs: Enable Google Analytics

- docs/HISTORY.txt
- opengever/meeting/browser/members.py
- opengever/meeting/tests/test_members.py
Instead of the MemberDetailview it redirects now to the members listing tab, after adding a Member.
Fixes #1685 
@deiferni please have a look
> Redirect to the members listing tab after adding a new member

- docs/api/conf.py
- sphinx.cfg
Switch to Google Analytics config using Alabaster theme (builtin) instead of using the `sphinxcontrib.googleanalytics` extension. This simplifies the whole integration.
> API docs: Switch to Google Analytics config using Alabaster theme (builtin)

- docs/HISTORY.txt
- opengever/setup/sections/xlssource.py
For each open file MS office creates a temp file in the same directory. The temp file's filename starts with a tilde, but ends with the same file extension as the original file (`.xlsx`). Currently our import section attempts to parse these files which leads to an error.
This PR changes the behavior of the excel import section to also skip MS office temp files.
Tested and confirmed running with: 
```bash
foo.bar               ordnungssystem.xlsx   ~$ordnungssystem.xlsx ~blub.xlsx
```
> No longer attempt to parse temporary excel files while creating repos.

- docs/HISTORY.txt
- opengever/meeting/browser/configure.zcml
- opengever/meeting/browser/context.py
- opengever/meeting/interfaces.py
- opengever/meeting/tests/test_meeting_view.py
- opengever/meeting/tests/test_members.py
- opengever/meeting/tests/test_memberships.py
- opengever/meeting/wrapper.py
Customize the `object_title` method on the `plone_context_state` view for WrapperObjects, to make sure that the site title contains the Wrapper title instead of the parents id. Fixes #1691.
> Fixes sitetitle for wrapper objects.

- docs/HISTORY.txt
- opengever/core/testing.py
- opengever/policy/base/profiles/default/portal_languages.xml
- opengever/policy/base/upgrades/20160412172450_language_tool__enable_request_content_negotiation/portal_languages.xml
- opengever/policy/base/upgrades/20160412172450_language_tool__enable_request_content_negotiation/upgrade.py
This enables request content negotiation in the `portal_language` tool.
Later we will need this to be able to control the current language in API requests via the `Accept-Language` header.
Tested:
- Fresh setup
- Upgrade step
- Language switcher still works
> Language Tool: Enable request content negotiation.

- docs/api/_static/custom.css
- docs/api/conf.py
- opengever/sphinx/gevertheme/static/gevertheme.css
- opengever/sphinx/gevertheme/static/typography.css
- opengever/sphinx/gevertheme/theme.conf
This introduces a dedicated Sphinx theme for GEVER, located in `opengever/sphinx/gevertheme`.
This theme inherits from the default `alabaster` theme, but contains CSS that overrides styles to look the way we want them to look. For now, this is limited to a `typography.css` that changes the font to a webfont without serifs (Open Sans).
> Sphinx docs: Add a dedicated Sphinx theme for GEVER.

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
This PR fixes the german translations for from/to column labels. Fixes #1659.
> Fix wrong from/to column labels in meeting overviews.

- docs/HISTORY.txt
- opengever/base/reference_formatter.py
- opengever/setup/sections/reference.py
Currently we cannot import repositories formatted with the recently introduced `no_client_id_grouped_by_three` reference number formatter. This PR addresses that issue and adds support for that formatter.
Closes #1661
> Let a formatter know if he is grouped_by_three.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
Rename button to create paragraphs in meetings to "insert". This helps clarifying the difference between agenda-items and paragraphs.
Closes #1660.
Note that currently this breaks button alignment. I don't mind but it might be an issue?
> Rename button to create paragraphs to "insert".

- sphinx-standalone.cfg
- sphinx.cfg
Add buildout that allows to build a standalone Sphinx docs development environment (without `opengever.core`, Plone, etc.)
> Docs: Add standalone Sphinx docs buildout

- docs/intern/kurzreferenzen/administration.rst
Diverse Schreibfehler korrigiert, gemäss Anleitung von @lukasgraf (https://intern.onegovgever.ch/meta/) vorgegangen
> Diverse Typos korrigiert.

- docs/api/_static/custom.css
- docs/api/_static/custom.js
- docs/api/basics.rst
- docs/api/docs_changelog.rst
- docs/api/examples/example_get.py
- docs/api/examples/example_patch.py
- docs/api/examples/example_post.py
- docs/api/examples/example_session.py
- docs/api/examples/index.rst
- docs/api/index.rst
- docs/api/operations.rst
Add some code examples in Python for the basic operations. As currently published on https://docs.onegovgever.ch/operations/
*(The CSS and JS for collapsibles will eventually go into a separate package `opengever.sphinx` as part of the theme, but I haven't gotten around to creating that package/repo just yet.)*
@deiferni
> API Docs: Add some code examples (Python)

- docs/HISTORY.txt
- opengever/dossier/behaviors/dossier.py
- opengever/dossier/tests/test_base.py
This ensures this default is also respected when programmatically creating content (REST API, `plone.api`, `ftw.builder`, `transmogrifier`, ...).
See: http://docs.plone.org/4/en/external/plone.app.dexterity/docs/advanced/defaults.html#defaults
@phgross
> Make default value for IDossier.start a defaultFactory instead of a form level default

- opengever/bumblebee/overrides.zcml
- opengever/bumblebee/service.py
- opengever/document/profiles/default/types/opengever.document.document.xml
- opengever/document/tests/test_bumblebee.py
- opengever/document/upgrades/20160418132407_add_bumblebee_support_for_documents/types/opengever.document.document.xml
- opengever/document/upgrades/20160418132407_add_bumblebee_support_for_documents/upgrade.py
- sources.cfg
Dieser PR bringt folgende Neuerungen:
- das IBumblebeeable behavior wird dem Typ `opengever.document.document` hinzugefügt
- Der Bumblebeeservice zum hinzufügen von Jobs wird mit einem Feature-Flag-Check erweitert
closes #1680
> GEVER-Inhaltstypen IBumblebeeable machen

- development.cfg
Currently we ignore inherited `instance-eggs`.
> Extend instance eggs in development.cfg to include hotfixes.

- docs/HISTORY.txt
- opengever/base/brain.py
TranslatedTitleBrain: Also use `Missing.Value` as indicator that a brain has no translated title, and should therefore return the regular title.
Objects that existed before the TranslatedTitle behavior was activated will have `Missing.Value` indexed for `title_de` and `title_fr` metadata. The existing check for `None` will therefore fail for those objects.
> TranslatedTitleBrain: Also use Missing.Value as indicator to use regular title

- opengever/disposition/browser/configure.zcml
- opengever/disposition/browser/ech0160_export.py
- opengever/disposition/browser/overview.py
- opengever/disposition/browser/overview_templates/overview.pt
- opengever/disposition/profiles/default/actions.xml
- opengever/disposition/tests/test_overview.py
This PR adds the `SIP Download` action, which generates a SIP (eCH-160) Export of the selected dossiers (only dossiers with a truly appraisal).
Additionally if moved the `Export Appraisal list` action also to the action button group.
> Added SIP Download action

- opengever/dossier/base.py
- opengever/tabbedview/tests/test_dossier_listing.py
This fix an issue that archived dossiers are wrongly be listed in the dossier listing when the expired filter is active. Furthermore also the check show_modfiy_public_trial_link Dossier base class should exclude the archived state.
> Removed the archived state from the DOSSIER_STATES_CLOSED list.

- docs/HISTORY.txt
- opengever/policy/base/upgrades/20160418153139_enable_zipexport_for_plonesite__personal_overview_/registry.xml
- opengever/policy/base/upgrades/20160418153139_enable_zipexport_for_plonesite__personal_overview_/upgrade.py
Currently only the export action is shown but then results in a 404.
This PR closes #1682 by allowing access to the zip-exports on the plone-site.
> Enable zip-export for personal overview.

- docs/HISTORY.txt
- opengever/base/tests/test_transport.py
- opengever/base/transport.py
- opengever/meeting/browser/createsubmittedproposal.py
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/command.py
- opengever/meeting/model/proposal.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_submit_additional_documents.py
In the following situations GEVER currently fails with a `Unauthorized` Exception or similar problems:
- A user without any permission on the `Committee A` tries to submit an additional document to a proposal from  `Committee A`
- A user without any permission on the `Committee A` tries to update a submitted document from a proposal assigned to `Committee A`
- A User without any permission on the `Committee A` tries to submit a proposal to the `Committee A`
- A User without any permission on the proposal dossier decide the corresponding agendaitem of this proposal.
To avoid permission problems, we create and update the proposals/documents with elevated privileges.
Fixes #1266 
@deiferni
> Copying proposal and meeting documents with elevated privileges.

- opengever/disposition/browser/overview_templates/overview.pt
- opengever/disposition/disposition.py
- opengever/disposition/handlers.py
- opengever/disposition/tests/test_destruction.py
- opengever/disposition/tests/test_overview.py
Additional informations:
- Before the dossier destruction the most important information of each dossier is saved in a Persistentlist in the annotations of the disposition object.
- The removal of the dossiers itself is done with elevated_privileges.
Furthermore the disposition overview handles closed disposition specially:
- Dossiers aren't linked
- Additional metadata of each dossier is not displayed.
- Data is fetched from the `get_destroyed_dossiers` storage (Annotations)
Not implemented yet:
- Separate permission `Destroy GEVER Dossiers` and a check.
- Separate Removal options.
> Implement dossier destruction when closing a disposition.

- opengever/core/configure.zcml
- opengever/core/layout.py
- opengever/core/tests/test_layout.py
- opengever/document/browser/layout.py
- opengever/meeting/browser/layout.py
- opengever/task/layout.py
Dieser PR fügt eine GEVER Base Layout-Policy hinzu.
Die GEVER-Policy fügt eine CSS Klasse in den Body wenn das Bumblebeefeature aktiviert ist.
Diese Änderung wird v.a. für https://github.com/4teamwork/plonetheme.teamraum/pull/421 benötigt.
closes #1761
> Add gever layout policy to add feature-bumblebee body class if bumblebeefeature is enabled

- docs/HISTORY.txt
- opengever/dossier/templatedossier/form.py
- opengever/dossier/tests/test_templatedossier.py
Traceback:
```
Module opengever.dossier.templatedossier.form, line 67, in __call__
Module opengever.dossier.templatedossier.form, line 104, in render_form
AttributeError: request
```
@lukasgraf please have a 👀
> Fix bug in redirect when no templatedossier is found.

- opengever/document/behaviors/metadata.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_document.py
- opengever/journal/handlers.py
But display it in a separate fieldset.
This changes allow the user to add archive file for documents, which the automatic conversion couldn't create a PDF-A.
> No longer omit the documents archival file

- bin/mtest
Remove `*.py[co]` files to avoid race conditions with parallel workers stepping on each other's toes when trying to clean up stale bytecode.
Setting `PYTHONDONTWRITEBYTECODE` is not enough, because running buildout also already precompiles bytecode for some eggs.
@phgross
> bin/mtest: Remove bytecode before spawning parallel workers.

- docs/HISTORY.txt
- opengever/dossier/browser/navigation.py
- opengever/dossier/tests/test_navigation.py
See https://feedback.onegovgever.ch/t/auflistung-von-abgeschlossenen-subdossiers/148.
This was requested by many of our customers. It improves
navigating a dossier with many sub-dossier.
Closes #1705.
> Only show active sub-dossiers in dossier navigation.

- opengever/disposition/browser/overview.py
- opengever/disposition/browser/overview_templates/overview.pt
- opengever/disposition/disposition.py
- opengever/disposition/handlers.py
- opengever/disposition/history.py
- opengever/disposition/interfaces.py
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- opengever/disposition/tests/test_history.py
The disposition history, which journalizes every status change and object edit, is displayed in the same manner as the progress view on tasks or proposals.
> Added an automatic history for disposition objects.

- opengever/base/browser/search.pt
- opengever/base/browser/search.py
- opengever/base/tests/test_search.py
- sources.cfg
Add bumblebee preview images to search results, when the feature is enabled and an image has been generated.
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/423.
> Display search preview when bumblebee is enabled.

- opengever/disposition/browser/overview.py
- opengever/disposition/browser/overview_templates/overview.pt
- opengever/disposition/tests/test_overview.py
- Don't display empty parentheses, when no archival_value annotation is empty.
- Split up transition and other actions.
- Replace appraisal buttons with simple icon links.
- Display a readonly state wizard.
> Rework disposition overview

- opengever/dossier/base.py
- opengever/dossier/handlers.py
- opengever/dossier/interfaces.py
- opengever/dossier/profiles/default/registry.xml
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_resolve.py
- opengever/dossier/upgrades/20160512161209_add_dossier_resolve_properties/registry.xml
- opengever/dossier/upgrades/20160512161209_add_dossier_resolve_properties/upgrade.py
- opengever/latex/dossierjournal.py
- opengever/latex/listing.py
- opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
- opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
- opengever/latex/locales/opengever.latex.pot
- opengever/latex/templates/dossierjournal.tex
- opengever/latex/tests/test_dossierjournal.py
- opengever/latex/tests/test_listing.py
When a dossier gets resolved the following jobs are be done now:
- Purge the trash of the dossier (final deletion of all trashed documents)
- A PDF representation of the dossiers journal will be generated and filed as a regular document in the dossier.
[dossier-50.pdf](https://github.com/4teamwork/opengever.core/files/261842/dossier-50.pdf)
Both actions are configurable in the portal registry, but are enabled by default.
> Run "cleanup jobs" when resolving a dossier.

- development.cfg
The secret cannot be preconfigured and must be
added to a configuration file by each developer.
```
environment-vars +=
BUMBLEBEE_SECRET thesecret
```
Closes #1809.
> Configure bumblebee for local development.

- docs/HISTORY.txt
- opengever/bumblebee/__init__.py
- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/browser/overlay_templates/bumblebeeoverlayview.pt
- opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
- opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
- opengever/bumblebee/locales/opengever.bumblebee.pot
- opengever/bumblebee/tests/test_overlay.py
Dieser PR fügt einen neuen Link "Dokument als PDF öffnen" im overlay hinzu.
Der Dateiname des PDFs ist der alte Dateinamen mit der Endung ".pdf"
closes #1799
> Link "Dokument als PDF öffnen" im Overlay hinzugefügt

- docs/HISTORY.txt
- opengever/api/tests/test_summary.py
Fix tests for `GeverJSONSummarySerializer`: The `member` attribute has been renamed to `items` in plone/plone.restapi#107.
@deiferni
> Fix tests for GeverJSONSummarySerializer

- docs/HISTORY.txt
- opengever/bumblebee/browser/resources/bumblebee.js
- opengever/tabbedview/browser/bumblebee_gallery.pt
- opengever/tabbedview/browser/bumblebee_gallery.py
- opengever/tabbedview/tests/test_bumblebee_gallery.py
*Duplikat von https://github.com/4teamwork/opengever.core/pull/1815, weil Elio im Moment ein Bot ist 😠*
Dieser PR fügt ein Batching für die Galerieansicht hinzu.
Standardmässig werden 24 Dokumente vorgeladen.
Wird auf den Knopf "Mehr anzeigen" geklickt wird, oder wenn mit dem Showroom ans Ende des Batchs navigiert wird, werden neue Elemente nachgeladen.
closes #1791
> Add batching for the bumblebee gallery-view.

- bin/mtest
Have `bin/mtest` allocate a unique `ZSERVER_PORT` for each worker based on `PORT[1-8]` (see 4teamwork/ci_governor#71) provided by Jenkins Port Allocator plugin.
This is necessary so that we don't have workers trying to start ZServers on conflicting ports once #1826 ist merged to `master`.
@deiferni
> Have bin/mtest allocate a unique ZSERVER_PORT for each worker

- docs/HISTORY.txt
- opengever/base/subscribers.py
- opengever/bumblebee/service.py
- opengever/bumblebee/tests/test_overlay.py
- opengever/bumblebee/tests/test_utils.py
- sources.cfg
With https://github.com/4teamwork/ftw.bumblebee/pull/75 ftw.bumblebee switched to the Bumblebee API v3, therefore we need to updated the `GeverBumblebeeService` as well.
@elioschmutz @deiferni
> Update GeverBumblebeeService for the new ftw.bumblebee version.

- opengever/api/tests/test_summary.py
With [commit `bf146b` in `plone.restapi`](https://github.com/plone/plone.restapi/commit/bf146b04197acd8addfdd9fe5673f54d5473872c) the behavior for listing folder contents was changed. It now uses catalog queries instead of `obj.objectValues()`. This means that our repositoryfolders' titles will be fetched from the brains, not the objects any more.
That in turn means that we'll have the title prefixed with the reference number in listings, because the pure title isn't available on brains in opengever. (`brain.Title`, `brain.title_de` and `brain.title_fr` are all prefixed).
So `1. Repositoryfolder Title` instead of `Repositoryfolder Title`. We agreed this can be considered correct behavior, so this PR updates the tests accordingly.
> Fix GeverJSONSummarySerializer tests:

- docs/HISTORY.txt
- opengever/base/protect.py
- opengever/base/sentry.py
This change will cause every CSRF incident to be logged to Sentry, if possible.
It's implemented in a way that should not affect deployments that don't have `ftw.raven` and/or `sentry` installed. The CSRF incident will still be logged to a rotating file, but in a simplified way (no referrers to registered objects, cropped object representations).
A new function `log_msg_to_sentry()` is introduced in `opengever.base.sentry`, which can be used to directly log a message (and optionally some data) to Sentry, without having to have an actual exception. This function is written in a way that it should be safe to use it anywhere - it should never fail, even if `ftw.raven` or `sentry` aren't available, or some error happens during logging.
The CSRF Sentry events use a custom `fingerprint` that …
> Log CSRF incidents to Sentry (if possible)

- docs/HISTORY.txt
- opengever/base/behaviors/classification.py
- opengever/base/behaviors/lifecycle.py
- opengever/base/behaviors/utils.py
- opengever/document/behaviors/metadata.py
- opengever/document/tests/test_document.py
- opengever/dossier/archive.py
- opengever/dossier/browser/filing_maintenance.py
- opengever/dossier/tests/test_archive.py
- opengever/mail/tests/test_mail_metadata.py
- opengever/mail/upgrades/to3401.py
- opengever/repository/behaviors/referenceprefix.py
- opengever/task/task.py
Decouple default values for fields from any forms (as much as possible). This is necessary groundwork for later changes that will make sure that default values also get set during programmatic content creation.
This usually means turning something like
```python
@form.default_value(field=ISchema['fieldname'])
def fieldname_default(data):
context = data.context
```
into something like
```python
def fieldname_default(context):
class ISchema(form.Schema):
fieldname = schema.Choice(
defaultFactory=fieldname_default,
)
```
Default factories are now being used for the following fields:
- `Document.preserved_as_paper`
- `ArchiveForm.filing_prefix`
- `ArchiveForm.filing_year`
- `ArchiveForm.dossier_enddate`
- `FilingNumberCountersForm.counters`
- `IReferenceNumberPrefix.reference_number_prefix`
- …
> Decouple default values for fields from any forms

- docs/HISTORY.txt
- opengever/document/browser/configure.zcml
- opengever/document/browser/tabbed.py
- opengever/document/checkout/manager.py
- opengever/document/document.py
- opengever/document/interfaces.py
- opengever/document/quick_upload.py
- opengever/document/tests/test_checkout.py
- opengever/document/tests/test_quickupload.py
- opengever/document/tests/test_tabbed.py
Drag'n' drop is only available when document is checked_out by the current user and no webdav lock (ExternalEditor/OfficeConnector) exists. For more information see #1562. 
Closes #1562
> Enables to replace a document per Drag'n'Drop

- docs/HISTORY.txt
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/proposal.py
- opengever/meeting/model/proposalhistory.py
- opengever/meeting/model/query.py
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_proposal_listings.py
- opengever/meeting/tests/test_proposalhistory.py
- opengever/meeting/tests/test_unit_proposal.py
- opengever/tabbedview/browser/selection_with_filters.pt
- opengever/tabbedview/browser/tabs.py
- opengever/testing/builders/dx.py
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/431 for styling
This PR makes proposals cancellable.
- Add model workflow to cancel/reactivate proposals.
- Add a statefilter for  the proposals tab in a dossier to only display active proposals.
Closes #1804.
> Make proposals cancellable.

- docs/HISTORY.txt
- opengever/tabbedview/browser/bumblebee_gallery.py
- opengever/tabbedview/tests/test_bumblebee_gallery.py
Durch diesen PR wird in der Galerieansicht keine eigene Batch-Size mehr verwendet.
Neu wird das globale tabbedview-pagesize attribut verwendet.
Somit hat die Galerieansicht die gleiche Batch-Size wie die Listenansicht.
closes #1860
> Use global pagesize parameter for batchsize in gallery-view

- opengever/meeting/model/proposal.py
- opengever/meeting/tests/test_proposal.py
Fixes #1861.
Fixes an unreleased error that was introduced recently with https://github.com/4teamwork/opengever.core/pull/1849, no changelog entry should be necessary.
> Use correct message type when submitting proposals.

- docs/HISTORY.txt
- opengever/base/browser/templates/gever-macros.pt
- opengever/bumblebee/browser/resources/bumblebee.js
- opengever/dossier/browser/overview.py
- opengever/dossier/tests/test_overview.py
Dokumente im Übersichts-Tab werden nun auch im Overlay geöffnet.
closes #1833
> Add bumblebeeoverlay for documents on the overview tab.

- docs/HISTORY.txt
- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/browser/overlay_templates/bumblebeeoverlayview.pt
- Omit diazo
- use `nocall:` in `tal:condition` to avoid rendering the whole dossier overview 😞 
This improves the overlay rendering time from ~600ms to ~75ms
Fixes #1837.
> Boost bumblebee overlay rendering performance 

- docs/HISTORY.txt
- opengever/document/upgrades/20160601180404_reindex_object_provides_after_adding_i_bumblebeeable_interface/upgrade.py
This makes sure that object_provides is up to date.
Closes #1870.
> Reindex documents after adding ftw.bumblebee.interfaces.IBumblebeeable.

- docs/HISTORY.txt
- opengever/bumblebee/browser/resources/bumblebee.js
Suchresultate wurden nach dem Sortieren oder erneutem Suchen in der Search-View nicht mehr als Showroom-Items initialisiert.
Dieser PR behebt diese Probleme.
> Initialize the showroom correctly for dynamically loaded items in the search-view.

- docs/HISTORY.txt
- opengever/dossier/configure.zcml
- opengever/dossier/tabbedviewstatestorage.py
- opengever/dossier/tests/test_tabbedviewstatestorage.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/interfaces.py
Dieser PR fixt das problem, dass Tablestates für das Dokumenttab nicht mehr persistiert wurden.
closes #1850
> Sortierreihenfolge wird im Dokumenttab wieder persistiert.

- docs/HISTORY.txt
- opengever/bumblebee/browser/resources/bumblebee.js
Zeigt in der Listenansicht die korrekte Anzahl von Dokumenten im Shorwoomoverlay an.
closes #1835
> Show correct total document size in the showroom overlay if opening files from the list-view

- opengever/document/upgrades/20160601180404_reindex_object_provides_after_adding_i_bumblebeeable_interface/upgrade.py
The existing upgradestep, which was introduced with #1877, also updates the metadata. This is unnecessary because there is only a index `object_provides` but not a metadata.
@deiferni
> Fixed ReindexObjectProvidesAfterAddingIBumblebeeableInterface upgradestep

- docs/HISTORY.txt
- opengever/meeting/model/proposal.py
- opengever/meeting/model/query.py
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_proposal_listings.py
- opengever/meeting/upgrades/20160606154939_add_creator_column_to_proposal_model/upgrade.py
- opengever/tabbedview/browser/personal_overview.py
- opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/opengever.tabbedview.pot
- opengever/tabbedview/tests/test_personaloverview.py
- opengever/testing/builders/sql.py
The new tab lists all proposals created by the current user (closes #1496) and is only available when the meeting feature is active.
@deiferni
> Added new tab "My Proposals" to the personal overview

- docs/HISTORY.txt
- opengever/bumblebee/service.py
- opengever/document/tests/test_bumblebee.py
This no longer updates the preview pdf and thumbnails for checked
out documents and prevents that other users can see the working copy.
Closes #1844.
See also https://github.com/4teamwork/ftw.bumblebee/pull/88
> Prevent updating bumblebee checksum for checked out documents.

- docs/HISTORY.txt
- opengever/tabbedview/sqlsource.py
- opengever/tabbedview/tests/test_sqlsource.py
When using PostgreSQL as OGDS and GlobalIndex Database the tabbedview textfilter has not worked because the sequence_number column is part of the listings searchable_columns. The LIKE operator does not work for Integer columns on PostgresSql, therefore we had to extend the query with a Cast.
Fixes #1884.
@deiferni I've found a better way to fix that issue ... 😄 
Note: Sadly all the tests has no value on working on PostgreSQL, because we use SQLite on the testsetup. 😏
> Fixed textfiltering for task listings on PostgreSQL.

- docs/HISTORY.txt
- opengever/bumblebee/browser/resources/bumblebee.js
Fixes https://github.com/4teamwork/opengever.core/issues/1906
`NodeList` is not iterable so the `forEach` does not work here.
Convert the `NodeList` to an iterable Array to have the `forEach`.
> Fix document overview.

- docs/HISTORY.txt
- opengever/base/browser/resources/prepoverlay.js
- opengever/document/browser/download.py
- opengever/document/browser/templates/file.pt
- opengever/document/widgets/no_download_input.pt
Change background color of download confirmation dialog to partial transparent black.
The rest of the overlays keep their color (partially transparent white).
> 	Change background color of download confirmation dialog to partial transparent black.

- docs/HISTORY.txt
- opengever/base/viewlets/byline.pt
- opengever/base/viewlets/byline.py
- opengever/repository/tests/test_repositoryfolder_byline.py
- opengever/repository/viewlets/byline.py
It only displays one line of the description (crop it when its to long), but the complete description is available as a tooltip text.
Fixes #1706.
@deiferni please have a look
> Display repositoryfolder description above the byline.

- docs/HISTORY.txt
- opengever/core/testing.py
- opengever/document/configure.zcml
- opengever/document/tests/test_bumblebee.py
Register bumblebee event handler to also listen to checkin and revert events which don't fire an object-modified event.
Fixes #1914.
> Update bumblebee documents after checkin and revert.

- docs/HISTORY.txt
- opengever/bumblebee/__init__.py
- opengever/bumblebee/tests/test_utils.py
Being bumblebeeable is a decision which is made on a per content-type basis. Plone content-types are marked as bumblebeeable by providing a marker interface. There is no metadata for object_provides on a brain (only an index)  so we do a portal_type check instead.
Fixes #1905.
> Fix bumblebeeability check for documents that are not digitally available.

- docs/HISTORY.txt
- opengever/locking/info.py
- opengever/locking/locales/de/LC_MESSAGES/opengever.locking.po
- opengever/locking/locales/fr/LC_MESSAGES/opengever.locking.po
- opengever/locking/locales/opengever.locking.pot
- opengever/locking/lock.py
- opengever/locking/templates/submitted_document_lock_template.pt
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/command.py
- opengever/meeting/model/submitteddocument.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_submit_additional_documents.py
This prevents that the document-copy is edited and gets out of  sync with its master document. Also a custom lock message is displayed for such documents.
Closes #1421.
> Permanently lock submitted documents after proposal submission.

- docs/HISTORY.txt
- opengever/document/indexers.py
Adapt object to behavior interface before accessing the `public_trial` attribute.
Not 100% sure yet why the old version of the indexer ever worked, but my suspicion it's due to a combination of acquisition and dexterity's `__getattr__` fallback, that lead to the value being acquired from a parent or a default value generator.
@phgross  
Fixes #1918
> Fix public_trial indexer

- opengever/base/behaviors/classification.py
This reverts commit 42462ffc32309dea09f46e8e417c452b9db27355.
Changing the default for `public_trial` from a form-level default to a `defaultFactory` has broken attribute access. (See #1918). Revert the change until we figure out why.
@phgross
> Revert "Use defaultFactory for IClassification public_trial instead of form level defaults."

- docs/HISTORY.txt
- opengever/dossier/tabbedviewstatestorage.py
- opengever/dossier/tests/test_tabbedviewstatestorage.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/interfaces.py
- opengever/tabbedview/tests/test_bumblebee_gallery.py
This PR will fix error from sentry: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/673/
```bash
AttributeError: 'DocumentsProxy' object has no attribute 'select_all'
File "ZPublisher/Publish.py", line 138, in publish
request, bind=1)
File "ZPublisher/mapply.py", line 77, in mapply
if debug is not None: return debug(object,args,context)
File "ZPublisher/Publish.py", line 48, in call_object
result=apply(object,args) # Type s<cr> to step into published object.
File "home/zope/eggs/ftw.tabbedview-3.5.0-py2.7.egg/ftw/tabbedview/browser/tabbed.py", line 216, in select_all
return self.tab.select_all()
```
How to reproduce the issue:
Behavior with the PR-Fix:
closes #1852
> Fix select all

- docs/HISTORY.txt
- docs/intern/kurzreferenzen/administration.rst
- opengever/meeting/browser/meetings/configure.zcml
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/model/generateddocument.py
- opengever/meeting/tests/test_protocol.py
Only download the existing protocol without regenerate or update the protocol document (with sablon).
Fixes #1515.
@deiferni 
The existing `DownloadGeneratedProtocol` view is still registered and available, but only for testing/debugging purpose, it's not available in the UI.
> Simplify protocol download button in meeting view.

- docs/HISTORY.txt
- opengever/base/tests/test_transport.py
- opengever/base/transport.py
- opengever/document/tests/test_bumblebee.py
- opengever/document/tests/test_checkout.py
- opengever/document/tests/test_versions_tab.py
- opengever/locking/info.py
- opengever/locking/locales/de/LC_MESSAGES/opengever.locking.po
- opengever/locking/locales/fr/LC_MESSAGES/opengever.locking.po
- opengever/locking/locales/opengever.locking.pot
- opengever/locking/lock.py
- opengever/locking/templates/excerpt_document_lock_template.pt
- opengever/meeting/browser/excerpt.py
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/command.py
- opengever/meeting/handlers.py
- opengever/meeting/model/proposal.py
- opengever/meeting/tests/test_agendaitem.py
- opengever/meeting/tests/test_excerpt.py
- opengever/meeting/upgrades/20160615142602_manage_checkin_checkout_permissions_in_submitted_proposal/upgrade.py
- opengever/meeting/upgrades/20160615142602_manage_checkin_checkout_permissions_in_submitted_proposal/workflows/opengever_submitted_proposal_workflow/definition.xml
- opengever/testing/helpers.py
This PR locks excerpts in the dossiers and sync updates to the excerpt in a meeting/submitted proposal to the excerpt copy in the dossier.
Also fixes an issue where documents could not be checked out once inside a submitted proposal.
Closes #1803.
> Lock excerpt copies in the dossiers indefinitely

- docs/HISTORY.txt
- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/bumblebee/interfaces.py
- opengever/bumblebee/tests/test_overlay_adapter_document.py
Dieser PR fügt das Lock-Info Viewlet sowie das Checkout-Info-Viewlet dem Bumblebee-Overlay hinzu.
> Add lock-info and checkout-info viewlets to bumblebee-overlay.

- docs/HISTORY.txt
- opengever/base/behaviors/utils.py
Getting default with AQ: Change lookup order so that we first try to properly adapt the context to the schema interface with `field.get(ISchema(obj))`, and only if that fails, try a simple `field.get(obj)`.
Previously this was reversed, and lead to `field.get(obj)` returning bogus values with the `DexterityContent.__getattr__` from `plone.dexterity == 2.3.0`.
> Getting default with AQ: Change lookup order so adapting context to schema interface is tried first

- docs/HISTORY.txt
- opengever/api/tests/test_content_creation.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/default_values.py
- opengever/mail/tests/test_mail_classification.py
This change monkey patches `DexterityContent.__getattr__` to correctly fall back to defaults from behavior schemas (part of a larger effort to fix default value persistence, see #1778)
**Rationale**: The implementation in `plone.dexterity` 2.1.x grabs *marker interfaces* from `SCHEMA_CACHE.subtypes()` for behaviors that have them, instead of their *schema interfaces*:
```python
(Pdb) pp SCHEMA_CACHE.subtypes('opengever.document.document')
(<InterfaceClass collective.dexteritytextindexer.behavior.IDexterityTextIndexer>,
<InterfaceClass ftw.journal.interfaces.IAnnotationsJournalizable>,
<InterfaceClass opengever.base.behaviors.creator.ICreatorAware>,
<InterfaceClass ftw.tabbedview.interfaces.ITabbedView>,
<InterfaceClass opengever.base.behaviors.classification.IClassificationMarker>,  # …
```
> Patch DexterityContent.__getattr__ to correctly fall back to defaults from behavior schemas

- docs/HISTORY.txt
- opengever/base/behaviors/classification.py
This changes the default value generation for the `public_trial` field back to a `defaultFactory`, which should now work after the fix from #1952.
@phgross
> Use defaultFactory for IClassification public_trial instead of form level defaults.

- docs/HISTORY.txt
- opengever/tabbedview/browser/tooltip_source.py
With the bumblebee integration all document listings, gets wrapped in to a proxy view. Therefore the tooltip condition has to be changed to the proxy identifier as well.
@deiferni
> Fixed icon tooltip in document listings.

- docs/HISTORY.txt
- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/tests/test_overlay_adapter_mail.py
- opengever/bumblebee/tests/test_overlay_view.py
Bumblebee supports now mail conversion. Fixes #1946.
@elioschmutz or @deiferni please have a 👀
> No longer hide Download PDF link in the bumblebee overlay for mails.

- docs/HISTORY.txt
- opengever/tabbedview/browser/bumblebee_gallery.py
- opengever/tabbedview/tests/test_bumblebee_gallery.py
The request name was wrong `SearchableText` instead of `searchable_text`. See https://github.com/4teamwork/ftw.tabbedview/blob/00c72c97507b68e1a9a86bc9068a92036feb2358/ftw/tabbedview/browser/listing.py#L171 for more information.
Fixes #1948 .
@elioschmutz or @deiferni please have a 👀
> Fixed textfilter in the documents gallery view.

- docs/HISTORY.txt
- opengever/base/sentry.py
- opengever/base/transforms/trix2sablon.py
We currently need full string length for errors reported by the
trix2sablon conversion.
> Don't truncate strings in sentry extra data.

- docs/HISTORY.txt
- opengever/base/tests/test_trix2sablon.py
- opengever/base/transforms/trix2sablon.py
Trix always renders breaks as simple `<br>`, thus we change the server-side transform to render the same markup.
> Use non self-closing br tags in trix transform.

- docs/HISTORY.txt
- opengever/bumblebee/browser/resources/bumblebee.js
Fixes #1872 by implementing a special handling for extjs listing tabs in the `tail` and `head` methods, which loads and extend the next or previous batch to the showroom queue.
⚠️  Uses https://github.com/4teamwork/ftw.showroom/pull/29
@deiferni or @bierik please have a 👀
> Fixed bumblebee overlay browse functionality for the document extjs listings

- docs/HISTORY.txt
- opengever/setup/browser/adddeployment.pt
- opengever/setup/locales/de/LC_MESSAGES/opengever.setup.po
- opengever/setup/locales/fr/LC_MESSAGES/opengever.setup.po
- opengever/setup/locales/opengever.setup.pot
Remove i18n markup for strings in opengever.setup: we're never going to translate those.
> Remove i18n markup for strings in opengever.setup:

- docs/HISTORY.txt
- scripts/weblate/create-components-json.py
This script is used to automate the component import into Weblate, where each `opengever.*` package (with translations) corresponds to one Weblate component.
*(Tests skipped with `[ci skip]`, this script isn't covered by tests)*
**Example usage:**
```bash
python create-component-import-json.py https://4teamworkTranslator:[access-token]@github.com/4teamwork/opengever.core.git
```
**Output:**
Two files, `main_component.json` and `components.json`.
**These can then be imported into Weblate like so:**
```bash
PROJ="<your_project_slug>" && python manage.py import_json --project ${PROJ} main_component.json && python manage.py import_json --project ${PROJ} --main-component opengever-activity components.json
```
(Where `<your_project_slug>` is something like `onegov-gever`)
> Add helper script to generate JSON files for component import into Weblate.

- docs/HISTORY.txt
- opengever/base/brain.py
- opengever/base/tests/test_navigation.py
- opengever/base/tests/test_translated_title.py
Decide with the help of the brains portal_type if the brain should use the language specific title or not.
Because `object_provides` is only a index but not a metadata, we have to check the portal_types FTI if the object supports TranslatedTitle or not. 
To avoid performance Issues the `support_translatedtitle` check is cached.
@lukasgraf as discussed.
> Adjust decision in TranslatedTitleBrain when the the language specific title should be used.

- docs/HISTORY.txt
- opengever/bumblebee/__init__.py
- opengever/bumblebee/browser/configure.zcml
- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/browser/resources/bumblebee.js
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/bumblebee/interfaces.py
- opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
- opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
- opengever/bumblebee/locales/opengever.bumblebee.pot
- opengever/bumblebee/tests/test_overlay_adapter_document.py
- opengever/bumblebee/tests/test_overlay_adapter_document_version.py
- opengever/bumblebee/tests/test_overlay_view.py
- opengever/document/browser/versions_tab.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_versions_tab.py
- opengever/tabbedview/helper.py
- opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/opengever.tabbedview.pot
This PR add the bumblebee-previews for the document-versions:
closes #1670
> Add previews on versions tab

- docs/HISTORY.txt
- opengever/base/upgrades/to4502.py
Problems detected while upgrading to newest GEVER Release on the PHVS Testsystem.
See http://do3.cc/blog/2012/09/264/debugging-zcrelations---broken-btrees/ for more information.
@lukasgraf as discussed
> Add BTree consistency check and correction to the CleanupRelationsCatalog upgradestep.

- scripts/bumblebee_installation.py
- sources.cfg
This PR will add a script in `./scripts` to index and store bumblebee-objects after installing `ftw.bumblebee` on a GEVER platform.
To see how it works, pls see the intro-help message of the script.
closes #1832
> Add bumblebee installation script

- docs/HISTORY.txt
- opengever/base/protect.py
Fixes CSRF false positives on Portlet contexts like `vorlagen` or `ìnbox` when visiting them for the first time after site setup.
Fixes https://sentry.4teamwork.ch/sentry/onegov-gever/issues/806/
@phgross
> CSRF: Whitelist context portlet assignment annotations.

- docs/HISTORY.txt
- opengever/base/subscribers.py
The `@@health-check` view (from `opengever.maintenance`) needs to be accessible for Anonymous.
@phgross
> Whitelist '@@health-check' view on site root.

- docs/HISTORY.txt
- opengever/meeting/browser/protocol.py
- opengever/meeting/command.py
- opengever/meeting/exceptions.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_protocol.py
Lock the meeting row with `SELECT FOR UPDATE` while the protocol is being generated and check if the protocol is already present before generating the document from its template. This prevents multiple threads from generating a protocol twice for the same meeting.
Fixes #1992.
> Don't allow protocols for a meeting to be generated twice.

- docs/HISTORY.txt
- opengever/bumblebee/document.py
- opengever/bumblebee/tests/test_document_adapter.py
- opengever/document/tests/test_bumblebee.py
This has not happened anyway so far due to a side-effect of another statement. This change makes it explicit and adds tests, though.
Closes #1976.
> Don't store documents that are not digitally available in bumblebee.

- opengever/base/default_values.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/default_values.py
- opengever/base/tests/test_default_values.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/core/testing.py
- opengever/document/behaviors/related_docs.py
- opengever/document/tests/test_document.py
- opengever/dossier/behaviors/dossier.py
- opengever/mail/browser/send_document.py
- opengever/task/response.py
- opengever/testing/configure.zcml
- opengever/testing/patch.py
- opengever/testing/profiles/testing/types.xml
- opengever/testing/profiles/testing/types/Dummy.xml
- opengever/testing/tests.zcml
- opengever/testing/types.py
This addresses several issues described in #1778:
These changes make sure that
- default values are actually persisted when adding content **TTW with `z3c.form`**
- default values are set when using **`createContentInContainer`**
- default values are set when using **`invokeFactory`**
(Will add / clean up changelog once merged into `master`
> Make sure Dexterity default values are persisted

- docs/HISTORY.txt
- opengever/task/interfaces.py
- opengever/task/response.py
- opengever/task/tests/test_task.py
The view must not be called without the transition parameter. There still _are/might be_ some old Response that contain no transition though, so we cannot make the field required safely on the Schema level.
As discussed earlier today we don't want to show a statusmessage but fail hard in case some of our code still calls the view without the now required parameter.
Also cleanup some unused code.
Closes #1991.
> Make transition required for the addresponse view.

- docs/HISTORY.txt
- opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/plone.pot
Display a hint in livesearch results view when the query could not be processed.
Styles are added in https://github.com/4teamwork/plonetheme.teamraum/pull/441.
Fixes #649.
> Display parse errors in livesearch.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/Scrollspy.js
The `:root` selector is not working for IE. It also behaves
strange on chrome with same version but on diffrent devices.
> Fix scrollspy auto scrolling.

- docs/HISTORY.txt
- opengever/contact/models/__init__.py
- opengever/contact/models/organization.py
- opengever/contact/models/person.py
- opengever/contact/tests/test_person_view.py
- opengever/contact/upgrades/20160707112745_remove_duplicated_description_columns/upgrade.py
- opengever/contact/upgrades/20160707113401_remove_duplicated_contact_type_column/upgrade.py
The column `description` and `contact_type` are already defined on the BaseClass `Contact` and therefore unnecessary on the `Organization` or `Person` model. 
This fixes the SA Warning, when starting up the instance:
```
/home/zope/eggs/SQLAlchemy-1.0.5-py2.7-linux-x86_64.egg/sqlalchemy/orm/mapper.py:1648: SAWarning: Implicitly combining column contacts.contact_type with column organizations.contact_type under attribute 'contact_type'.  Please configure one or more attributes for these same-named columns explicitly.
util.warn(msg)
/home/zope/eggs/SQLAlchemy-1.0.5-py2.7-linux-x86_64.egg/sqlalchemy/orm/mapper.py:1648: SAWarning: Implicitly combining column contacts.description with column organizations.description under attribute 'description'.  Please configure one or more attributes for …
```
> Drop duplicated description and contact_type columns on Organization and Person model.

- opengever/contact/tests/test_org_role.py
- opengever/contact/tests/test_organization.py
- opengever/contact/tests/test_person_unit.py
- opengever/testing/builders/sql.py
> Consequently use builders to create contact sql objects in tests.

- docs/HISTORY.txt
- opengever/base/pdfconverter.py
- opengever/document/browser/overview.py
- opengever/document/browser/versions_tab.py
- opengever/document/tests/test_document_link_widget.py
- opengever/document/tests/test_versions_tab.py
- opengever/document/widgets/document_link.py
- opengever/tabbedview/helper.py
- sources.cfg
When both bumblebee and pdfconverter are installed, bumblebee should take precdence.
Depends on https://github.com/4teamwork/opengever.pdfconverter/pull/15.
Closes #2020.
> Let bumblebee take precedence over pdfconverter.

- docs/HISTORY.txt
- opengever/base/reporter.py
- opengever/base/tests/test_reporter.py
- opengever/dossier/browser/report.py
- opengever/globalindex/browser/report.py
- opengever/globalindex/tests/test_task_link.py
- opengever/tasktemplates/tests/test_trigger.py
- opengever/testing/helpers.py
This is required by openpyxl and gets rid of warnings while boot the instances.
Closes https://github.com/4teamwork/opengever.core/issues/1753.
> Bump lxml to version 3.3.1.0

- docs/HISTORY.txt
- opengever/tabbedview/helper.py
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/445.
Remove newlines in generated markup to avoid additional whitespace before
title.
Closes https://github.com/4teamwork/opengever.core/issues/2022.
> Show pdf icon for preview link in document versions tab.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/committee.py
- opengever/meeting/proposal.py
- opengever/meeting/upgrades/20160719150641_fix_beadcrumbs_for_committees_and_their_content/upgrade.py
Return utf-8 instead of unicode, as required by plone.
Closes https://github.com/4teamwork/opengever.core/issues/2009.
> Fix Title for Commitee and Proposal.

- opengever/examplecontent/profiles/default/registry.xml
Most of our customers will enable bumblebee, so we should, too while developing.
> Always enable bumblebee for development by default.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/meeting.js
Dieser PR fix den Sticky-Heading.
Durch ein Refactoring wurde der Klassennamen geändert. Für mehr infos #2051 
closes #2051
> Fix sticky heading

- docs/HISTORY.txt
- opengever/document/widgets/document_link.pt
Otherwise the hidden-link gets duplicated and this leads to a wrong document-number and a buggy scrolling between the different documents (fixes #2059).
@bierik
> Move showroom hidden-link outside the tooltip-trigger div.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/tests/test_agendaitem.py
This issue closes the agenda-item cross-manipulation security leck.
For more information see issue #2031
closes #2031
> Fix security-issue to cross-delete and update agendaitems.

- docs/HISTORY.txt
- opengever/ogds/base/events.py
- opengever/tabbedview/sqlsource.py
- opengever/tabbedview/tests/test_sqlsource.py
The filterbox should be an easy and fast possibility to limit the entries of a listing, therefore it should work case insensitive.
Note: the filterbox on catalog listings already works case insensitive.
--- 
Additionally in enable case_sensitive_like on sql lite connections.
This makes sure that all like queries in tests are case sensitive. So our test DB (SQLLite) works in the same manner than our production DBs (Oracle/PostgreSQL).
@lukasgraf
> Make tabbedview filter on sqltables listings case insensitive.

- docs/HISTORY.txt
- opengever/document/tests/test_document_tooltip.py
- opengever/document/widgets/tooltip.py
Change the condition if the download_copy is shown in the tooltip, to the digitally_available flag. So the link is shown for documents and mails as long as they contain a file.
Closed #2045 
@lukasgraf
> Display download_copy link also for mails.

- docs/HISTORY.txt
- opengever/contact/__init__.py
- opengever/contact/browser/configure.zcml
- opengever/contact/browser/organization_listing.py
- opengever/contact/browser/person_listing.py
- opengever/contact/browser/tabbed.py
- opengever/contact/browser/templates/organization.pt
- opengever/contact/browser/templates/person.pt
- opengever/contact/interfaces.py
- opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/opengever.contact.pot
- opengever/contact/profiles/default/registry.xml
- opengever/contact/profiles/default/types/opengever.contact.contactfolder.xml
- opengever/contact/tests/test_organization_listing.py
- opengever/contact/tests/test_person_listing.py
- opengever/contact/tests/test_tabbed.py
- opengever/contact/upgrades/20160722145337_add_feature_flag/registry.xml
- opengever/contact/upgrades/20160722145337_add_feature_flag/upgrade.py
- opengever/contact/upgrades/20160722150430_remove_tabbedview_actions_on_contacfolder_fti/upgrade.py
- opengever/examplecontent/profiles/default/registry.xml
The new tabs are only visible when the temporary feature flag for the contact modul is enabled (currently only for development-packages).
Beside the new tabs, this PR replaces the FTI tabbedview actions, with a specific TabbedView for contactfolders.
@lukasgraf
> Add new listing tabs `Persons` and `Organizations` to the contactfolder tabbedview.

- opengever/base/acquisition.py
- opengever/base/behaviors/classification.py
- opengever/base/behaviors/lifecycle.py
- opengever/base/tests/test_default_values_for_types.py
This rewrites the last remaining field defaults (that *shouldn't* be form defaults) as `defaultFactories`. Those are `IClassification` and `LifeCycle` fields that use fancy restricted vocabularies that had to undergo a major refactoring first (#2047).
@phgross
> Rewrite form defaults for IClassification and ILifeCycle fields to defaultFactories

- docs/HISTORY.txt
- opengever/base/browser/resources/tooltip.js
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/bumblebee/tests/test_overlay_view.py
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/tests/test_document_tooltip.py
- opengever/document/widgets/tooltip.pt
- Link dossier title in bumblebee overlay, closes #2072 
- Link breadcrumbs in document tooltip, closes #2069  
- Add label below the thumbnail link, closes #2068
- Improve tooltip position (closes #2071 ):
The tooltip is now always positioned on the vertical center of the mouse, usually on the right side. If    there is not enough space, its positioned on the left side of the mouse.
Overlay:
Tooltip:
@lukasgraf
> Bumblebee overlay and tooltip improvments

- docs/HISTORY.txt
- opengever/setup/deploy.py
In production, authentication will always be performed by CAS portal, and it should not be possible to authenticate against LDAP with Plone directly (e.g. via `/login_form`).
This is necessary so we can enforce the requirement for the second factor in 2FA via the CAS Portal.
⚠️  **Note** ⚠️ 
This means that it will be impossible to authenticate via LDAP *without the CAS Portal* for any deployment that isn't a local development setup (extending from `development.cfg`). *Every* GEVER deployment needs a CAS Portal from now on.
@phgross
> Deactivate 'Authentication' capability for LDAP plugin during setup for production deployments

- opengever/api/tests/test_content_creation.py
- opengever/base/tests/test_default_values_for_types.py
This is a series of restructurings ad cleanups for the default value tests. These will eventually be needed in order to implement setting missing values.
@phgross
> Restructure default value tests

- docs/api/basics.rst
- docs/api/batching.rst
- docs/api/docs_changelog.rst
- docs/api/examples/batching.json
- docs/api/examples/workflow_get.json
- docs/api/examples/workflow_post.json
- docs/api/index.rst
- docs/api/operations.rst
- docs/api/schemas/ftw.mail.mail.inc
- docs/api/schemas/opengever.document.document.inc
- docs/api/serialization.rst
- docs/api/workflow.rst
- docs/schema-dumps/ftw.mail.mail.json
- docs/schema-dumps/opengever.document.document.json
Updates the API docs to catch up with some recent changes / new features for `plone.restapi`:
- Update schema dumps.
- Add chapter 'Worfklow'
- Add minimal docs for ``review_state``
- Add chapter "Paginierung".
- Add chapter about serialization.
- Rename attribute ``member`` to ``items``.
> Update API documentation

- opengever/base/default_values.py
- opengever/base/tests/test_default_values_for_types.py
This changes content creation so that in addition to setting default values, we also set missing values for fields that don't have a default.
This should simply result in **all fields** being set to a value
- provided value
- default value
- missing value
when creating objects with any method:
- through the web 
- `createContentInContainer`
- `invokeFactory`
- `plone.api.content.create`
- `plone.restapi`
- `ftw.builder`
- `transmogrify.dexterity`.
@phgross
> Also set missing values if no default can be found

- docs/HISTORY.txt
- opengever/base/browser/search.pt
- opengever/base/contentlisting.py
- opengever/base/templates/simple_link.pt
- opengever/base/tests/test_contentlisting.py
- opengever/base/tests/test_search.py
- Change document link to document overview.
- Display document tooltip on document links.
Closes #2074 
---
I've tried to move the document thumbnail to the left side of the searchresult listing, but the result was not satisfying, the listing looked very restless (unruhig). Therefore I propose to let the thumbnail on the right side of the listing and wait for feedbacks and reactions from the SaaS Trial:
@lukasgraf please have a look
> Improve bumblebee integration in search results page.

- docs/HISTORY.txt
- opengever/meeting/handlers.py
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
This PR fixes an issue when moving a dossier with proposals. The proposals will no longer disappear from the dossiers proposals tab after the move.
Fixes  #2081.
> Keep proposal physical_path in sync when moving dossiers.

- docs/HISTORY.txt
- opengever/base/templates/simple_link.pt
- opengever/base/tests/test_contentlisting.py
This happens when the title of a object contains non-ascii characters.
Closes #2089.
@deiferni
> Fix UnicodeDecodeError in contentlisting render_link method.

- docs/HISTORY.txt
- opengever/bumblebee/profiles/default/cssregistry.xml
- opengever/bumblebee/upgrades/20160818143144_fix_showroom_css_order/cssregistry.xml
- opengever/bumblebee/upgrades/20160818143144_fix_showroom_css_order/upgrade.py
In some cases the ftw.showroom styling gets loaded after the GEVER styles. This causes the showroom styles defined in GEVER not to apply.
The upgrade step moves the showroom styles before the GEVER styles.
> Fix showroom CSS loading order

- docs/HISTORY.txt
- opengever/base/archeologist.py
- opengever/base/tests/test_archeologist.py
- scripts/bumblebee_installation.py
Fix existing reindex script to actually commit the changes (Follow-up of https://github.com/4teamwork/opengever.core/pull/1980).
Add feature to calculate bumblebee checksums for archived documents:
Adds an `Archeologist` which can excavate old archived versions of objects. It returns a direct reference to the archived object by bypassing all the other layers of abstraction. For more details please see `Archeologist`'s docstring.
The script was also tested manually by:
- creating a random amount of versions for ~1000 documents on our dev-server
- generating checksums for these versions
- validating that checksums were present for all versions
> Fix/update script for bumblebee activation.

- docs/HISTORY.txt
- opengever/document/browser/overview_templates/overview.pt
Closes https://github.com/4teamwork/opengever.core/issues/2115
To make the `scanForBrokenImages` function working the target
element must have the `bumblebee-thumbnail` class.
> [bumblebee] Fix bumblebee fallback image on document overview.

- docs/HISTORY.txt
- opengever/contact/browser/templates/organization.pt
- opengever/contact/browser/templates/person.pt
- opengever/contact/tests/test_organization_view.py
- opengever/contact/tests/test_person_view.py
Styling adjustment in plonetheme.teamraum: https://github.com/4teamwork/plonetheme.teamraum/pull/458
@lukasgraf or @deiferni
>  Display contacts URLs in the person and organization detail views.

- docs/HISTORY.txt
- opengever/base/browser/search.pt
- opengever/base/tests/test_search.py
Multiple showroom items get initialized for the same document.
So use a showroom reference for the preview image.
> [showroom] Fix document overview on searchpage

- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/opengever.base.pot
- opengever/base/locales/plone.pot
- opengever/base/menu.py
- opengever/contact/browser/templates/participations.pt
- opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/opengever.contact.pot
- opengever/contact/tests/test_participation.py
- opengever/contact/tests/test_participation_tab.py
- opengever/dossier/profiles/default/types/opengever.dossier.businesscasedossier.xml
- opengever/dossier/tests/test_dossier.py
- opengever/dossier/upgrades/20160829090234_rename_add_participant_action/upgrade.py
- opengever/meeting/profiles/default/types/opengever.meeting.meetingdossier.xml
- opengever/meeting/tests/test_meeting_dossier.py
- Shows `no participation` label when no participation exists.
- Rename `Add Participant` contentmenu action.
@deiferni
> Show no participation label in participation listing and fix contentmenu action.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/protocol.js
When the trix content grows, the pin item position is not
going to be updated. So trigger a refresh on `trix-change`
> Fix wrong pin position when trix content has been changed

- docs/HISTORY.txt
- opengever/contact/browser/configure.zcml
- opengever/contact/browser/organization.py
- opengever/contact/browser/participations.py
- opengever/contact/browser/person.py
- opengever/contact/browser/resources/contact.js
- opengever/contact/browser/templates/latest_participations.pt
- opengever/contact/browser/templates/organization.pt
- opengever/contact/browser/templates/person.pt
- opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/opengever.contact.pot
- opengever/contact/models/participation.py
- opengever/contact/tests/test_participation.py
Closes #2108 
To avoid performance issues, by fetching all dossiers over the IntId utility, the listing is implemented asynchronous and limited to 50 items. Listing all participations ist possible with a "show all" link.
@deiferni
> Add latest participation listing on contact detail views

- docs/HISTORY.txt
- opengever/contact/browser/byline.py
- opengever/contact/browser/configure.zcml
- opengever/contact/browser/layout.py
- opengever/contact/browser/organization_listing.py
- opengever/contact/browser/person_listing.py
- opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/opengever.contact.pot
- opengever/contact/models/archivedcontact.py
- opengever/contact/models/contact.py
- opengever/contact/tests/test_byline.py
- opengever/contact/tests/test_layout.py
- opengever/contact/tests/test_organization_listing.py
- opengever/contact/tests/test_organization_unit.py
- opengever/contact/tests/test_organization_view.py
- opengever/contact/tests/test_person_listing.py
- opengever/contact/tests/test_person_unit.py
- opengever/contact/tests/test_person_view.py
- opengever/contact/upgrades/20160831071153_add_is_active_column_to_contact/upgrade.py
- opengever/tabbedview/base_tabs.py
- opengever/tabbedview/browser/selection_with_filters.pt
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/browser/tasklisting.py
PR contains:
- Statefilter for contact listings
- Separte column `Active` in the contact listings
- A specific byline for organizations and persons
- An icon addition on the watermark icon for inactive contacts.
Closes #1930 
The styles are in a separate PR  in `plonetheme.teamraum`: https://github.com/4teamwork/plonetheme.teamraum/pull/460
@deiferni
> Add active/inactive flag for contacts.

- docs/HISTORY.txt
- opengever/base/browser/search.pt
- opengever/base/tests/test_search.py
The thumbnail uses now the hidden-link for the showroom reference, therefore we have to use the same identifieres, when rendering the thumbnail.
Fixes #2138 
> Fixed showroom identifier of preview thumbnails in search template.

- docs/HISTORY.txt
- opengever/base/default_values.py
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/default_values.py
- sources.cfg
Patch transmogrify.dexterity's schema updater so it correctly sets default values, using our own `determine_default_value` function to determine the default, and `get_persisted_value_for_field` to avoid any `__getattr__` fallbacks.
This fixes, among other things, an `AttributeError` for `privacy_layer` on repositoryfolders for a freshly created GEVER instance.
@phgross
> Patch transmogrify.dexterity's schema updater to set correct default values

- docs/HISTORY.txt
- opengever/base/subscribers.py
These endpoints are protected with `zope.Public` and need to be accessed anonymously.
Additionally, `request.steps[-1]` needs to be used to access the endpoint name so it gets translated from the internal service ID (`POST_application_json_@endpoint`) to just `@endpoint` ([see `plone.rest`](https://github.com/plone/plone.rest/blob/f711777060cdad4b1fa247af59cf8b4997218916/src/plone/rest/negotiation.py#L45)).
> Whitelist @login, @logout and @login-renew API endpoints for anonymous access on site root.

- opengever/base/subscribers.py
Fixes a mistake introduced in #2146:
`req.steps[-1]` doesn't normalize `@@view` to `view`, so depending on how a view was called in the URL, the whitelisted entries don't match any more.
So we revert back to using `req['PUBLISHED'].__name__` and instead prefix the `plone.rest` endpoints using `POST_application_json_@...`
@phgross
> Fix whitelisting of anonymous views on site root

- opengever/contact/browser/organization_listing.py
- opengever/contact/tests/test_organization_listing.py
This fixes the issue, that the statefilters are not displayed on the organization listings.
@deiferni 
Changelog entry is not necessary, it's just a fix for #2134
> Organization listing: removed unnecessary selection template customization.

- docs/HISTORY.txt
- opengever/contact/browser/mail.py
- opengever/contact/contactfolder.py
- opengever/contact/models/contact.py
- opengever/contact/models/org_role.py
- opengever/contact/models/organization.py
- opengever/contact/models/person.py
- opengever/contact/tests/test_mail_addresses_view.py
- opengever/contact/tests/test_organization.py
- opengever/contact/tests/test_organization_listing.py
- opengever/contact/tests/test_person.py
- opengever/contact/tests/test_person_listing.py
- opengever/journal/configure.zcml
- opengever/journal/entry.py
- opengever/journal/form.py
- opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/opengever.journal.pot
- opengever/journal/no_selection_amount.pt
- opengever/journal/tab.py
- opengever/journal/templates/journal_references.pt
- opengever/journal/templates/journal_selection.pt
- opengever/journal/tests/test_journal_tab.py
- opengever/journal/tests/test_manual_entry.py
- opengever/journal/vdexvocabs/manual_journal_entry_categories.vdex
See [Todo](https://basecamp.com/2768704/projects/12330648/todos/271609550) for more details
Besides the new functionality to add a journal entry manually, this PR fixes #2144 and changes the wrapper id for contact objects, it uses now `contact-{id}` instead of `person-{id}` or `organization-{id}`.
The styling adjustments are in separate [PR in plonetheme.teamraum](https://github.com/4teamwork/plonetheme.teamraum/pull/464).
> Add manual journal entry form

- opengever/journal/entry.py
It stores now the messagefactory object instead of the translated string as title of a manual journal entry.
Changelog not necessary just a small fix for #2161.
> Make sure title of a manual journal entry is stored language independent

- docs/HISTORY.txt
- opengever/contact/browser/templates/organization.pt
- opengever/contact/browser/templates/person.pt
- opengever/contact/models/address.py
- opengever/contact/models/archivedaddress.py
- opengever/contact/tests/test_organization_view.py
- opengever/contact/tests/test_person_view.py
- opengever/contact/upgrades/20160921094244_add_country_field_to_addresses/upgrade.py
- opengever/examplecontent/contacts.py
This PR adds an additional field `country` to `Address` and `ArchivedAddress` entities. Such a field is required for addresses outside Switzerland.
Closes #2165.
> Add country field to contact addresses.

- docs/HISTORY.txt
- opengever/contact/models/org_role.py
- opengever/contact/models/organization.py
- opengever/contact/models/person.py
- opengever/contact/models/query.py
- opengever/contact/tests/test_org_role.py
- opengever/contact/tests/test_organization_unit.py
- opengever/contact/tests/test_person_unit.py
- opengever/contact/tests/test_vocabularies.py
- opengever/contact/vocabularies.py
See basecamp discussions 
- https://basecamp.com/2768704/projects/12330648/todos/273237333 and 
- https://basecamp.com/2768704/projects/12330648/todos/266608587.
Needs https://github.com/4teamwork/opengever.ogds.models/pull/42
> Display former_contact_id in the contact selection field and make it searchable.

- docs/HISTORY.txt
- opengever/contact/models/__init__.py
- opengever/contact/models/participation.py
- opengever/contact/ogdsuser.py
- opengever/contact/tests/test_participation.py
- opengever/contact/tests/test_participation_tab.py
- opengever/contact/tests/test_participation_unit.py
- opengever/contact/tests/test_vocabularies.py
- opengever/contact/upgrades/20160921154421_add_ogds_user_participation/upgrade.py
- opengever/contact/vocabularies.py
- opengever/testing/builders/sql.py
This PR enables SQL-participation of users from ogds in dossiers.
Depends on https://github.com/4teamwork/opengever.core/pull/2174.
Currently the ogds is abstracted by a service, we must respect this decision and not add direct relationships to the ogds tables. This may change in the near future though. For now this PR introduces an adapter (the design-pattern, not the plone-thing) for the ogds user that adapts it to `Contact`s interface.
Closes #2164.
> Enable sql-participation for ogds-users in dossiers.

- docs/HISTORY.txt
- opengever/setup/sections/reference.py
When using `opengever.setup` to set up **two or more** repositories, the reference number to path mapping wasn't kept separate for the different repositories.
This lead to items in the XLSX that were missing a parent slipping by. Normally these would be caught and an exception raised:
```
Exception: Parent position for 11.4.1 does not exist!
```
However, Items may arrive in the Transmogrifier pipeline in arbitrary order. So in the case that an invalid repository XLSX contained an item with no parent, it's supposed parent's reference number might have been found in the mapping that was shared over the entire pipeline, because the reference number was already present from a different repository.
**Solution**: Keep track of reference numbers -> paths **per repository root** by keeping a …
> Setup: Keep track of reference number to path mappings per repository root

- docs/HISTORY.txt
- opengever/tasktemplates/configure.zcml
- opengever/tasktemplates/profiles/default/metadata.xml
- opengever/tasktemplates/profiles/default/types/opengever.meeting.meetingdossier.xml
- opengever/tasktemplates/upgrades/20160922173323_enable_task_templates_for_meeting_dossiers/types/opengever.meeting.meetingdossier.xml
- opengever/tasktemplates/upgrades/20160922173323_enable_task_templates_for_meeting_dossiers/upgrade.py
- opengever/tasktemplates/upgrades/configure.zcml
The action to add task-templates is registered in a different profile.
Also configure an upgrade-step directory for the `opengever.tasktemplates` package.
Fixes #1911.
> Enable task-templates for meeting-dossiers.

- docs/HISTORY.txt
- opengever/contact/browser/templates/organization.pt
- opengever/contact/browser/templates/person.pt
- opengever/contact/docprops.py
- opengever/contact/models/org_role.py
- opengever/contact/tests/test_docprops.py
- opengever/contact/tests/test_org_role.py
- opengever/contact/upgrades/20160928163510_add_department_column_to_orgrole/upgrade.py
- opengever/examplecontent/contacts.py
This PR adds a department column/field (TextLine) to orgroles.
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/468.
Closes #2188.
> Add department field to org-role.

- docs/HISTORY.txt
- opengever/contact/browser/person_listing.py
With #2113 an  `organizations` column was added to the person listing.
To avoid fetching the organization data with a separate SQL-query per person, we eager load the Organization data in the base query.
@deiferni
> Improve performance of person listing, using eager loading strategy.

- docs/HISTORY.txt
- docs/schema-dumps/_opengever.contact.models.Address.json
- docs/schema-dumps/_opengever.contact.models.MailAddress.json
- docs/schema-dumps/_opengever.contact.models.OrgRole.json
- docs/schema-dumps/_opengever.contact.models.Organization.json
- docs/schema-dumps/_opengever.contact.models.Person.json
- docs/schema-dumps/_opengever.contact.models.PhoneNumber.json
- docs/schema-dumps/_opengever.contact.models.URL.json
- docs/schema-dumps/_opengever.ogds.models.group.Group.json
- docs/schema-dumps/_opengever.ogds.models.user.User.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.json
- opengever/base/schemadump/config.py
- opengever/base/schemadump/field.py
- opengever/base/schemadump/schema.py
This adds a minimal `SQLSchemaDumper` in order to also dump schemas for our SQL types.
The implementation currently is as minimal as possible, and well need to be built on later, but it already covers **listing available fields** (columns), and whether they're **required** (not nullable) or not.
The primary need for this is to validate SQL query results used for data migration against the structure we expect them to have.
> Implement (basic) SQLSchemaDumper and also dump schemas for common SQL types.

- docs/HISTORY.txt
- opengever/contact/browser/organization.py
- opengever/contact/browser/participations.py
- opengever/contact/browser/templates/organization.pt
- opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
- opengever/contact/locales/opengever.contact.pot
- opengever/contact/models/person.py
- opengever/contact/tests/test_org_role.py
- opengever/contact/tests/test_organization_view.py
- opengever/contact/tests/test_participation.py
- opengever/contact/tests/test_participation_tab.py
- opengever/contact/tests/test_person_unit.py
- opengever/contact/tests/test_person_view.py
- opengever/contact/tests/test_vocabularies.py
- opengever/dossier/tests/test_templatedossier.py
- opengever/journal/tests/test_manual_entry.py
- Change Person label to `Name Surname`: According to the user label, also the person label should use the format `Name Surname` as every where else in GEVER. Closes #2190.
- Sort participations alphabetically on participant's title, closes #2189.
- Sort persons alphabetically on lastname, firstname in the organization detail view.
- Group related persons by active state in the organization detail view closes #2191
> Contact view improvements 

- docs/HISTORY.txt
- docs/schema-dumps/_opengever.contact.models.Address.json
- docs/schema-dumps/_opengever.contact.models.MailAddress.json
- docs/schema-dumps/_opengever.contact.models.OrgRole.json
- docs/schema-dumps/_opengever.contact.models.Organization.json
- docs/schema-dumps/_opengever.contact.models.Person.json
- docs/schema-dumps/_opengever.contact.models.PhoneNumber.json
- docs/schema-dumps/_opengever.contact.models.URL.json
- docs/schema-dumps/_opengever.ogds.models.group.Group.json
- docs/schema-dumps/_opengever.ogds.models.user.User.json
- docs/schema-dumps/ftw.mail.mail.json
- docs/schema-dumps/opengever.contact.contact.json
- docs/schema-dumps/opengever.document.document.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.json
- docs/schema-dumps/opengever.repository.repositoryfolder.json
- docs/schema-dumps/opengever.repository.repositoryroot.json
- opengever/base/schemadump/field.py
Includes `max_length` in the field dumps for string-like fields.
Also maps `SQLAlchemy` column types to corresponding `zope.schema` field types.
> SchemaDumper: Include max_length for stringish field types.

- sources.cfg
It's been [released](https://pypi.python.org/pypi/transmogrify.dexterity) and [pinned](https://github.com/4teamwork/kgs/commit/c6a3ceb601557dc73a792b4f9009e36ca6a5839a) as 1.6.3.
@deiferni
> Remove transmogrify.dexterity from development-packages

- docs/intern/kurzreferenzen/bumblebee.rst
- docs/intern/kurzreferenzen/index.rst
Converts https://github.com/4teamwork/opengever.core/issues/2095 into "proper" documentation.
Closes #2095.
> Add short description on how to activate bumblebee.

- docs/HISTORY.txt
- opengever/bumblebee/browser/configure.zcml
- opengever/bumblebee/browser/download.py
- opengever/bumblebee/tests/test_download.py
Fixes an issue with activating bumblebee when documents are checked out
during the process of activation.
Fixes #2131.
> Override bumblebee download view.

- docs/HISTORY.txt
- opengever/document/base.py
- opengever/document/tests/test_document.py
- opengever/mail/browser/extract_attachments.py
- opengever/mail/mail.py
- opengever/mail/tests/test_ogmail.py
The mail did not return its parent correctly (None instead of the inbox)
thus creation failed.
Fixes #2235.
> Fix extracting attachments for mails in inboxes.

- sources.cfg
It's been [released](https://pypi.python.org/pypi/ftw.casauth) and [pinned](https://github.com/4teamwork/kgs/commit/7f4cfeda804a50709a45a7ac0943720dbcdd4d39) as 1.1.0.
@deiferni
> Remove ftw.casauth from development-packages

- docs/HISTORY.txt
- opengever/base/adapters.py
- opengever/dossier/handlers.py
- opengever/dossier/tests/test_copy_dossier.py
When copy-pasting an existing dossier with sub-dossiers, the sub-dossiers's reference numbers are not assigned correctly. This PR fixes that issue by reseting the reference-number mapping when copying (or more exactly when pasting) a dossier.
Fixes #2092.
> Purge reference number mapping when dossiers are pasted.

- docs/HISTORY.txt
- opengever/base/profiles/default/jsregistry.xml
The prepoverlay js was removed by mistake in the javsascript dependencies cleanup PR (see #2159).
@deiferni 
cc @bierik
> Readd prepoverlay.js

- opengever/base/upgrades/20161018144110_re_register_prepoverlay_js/jsregistry.xml
- opengever/base/upgrades/20161018144110_re_register_prepoverlay_js/upgrade.py
Follow up of #2241
I didn't realize that some deployments are created after the #2159 merge from source, so an upgradestep is necessary.
@deiferni
> Add upgradestep which reregisters the prepoverlay JS.

- docs/HISTORY.txt
- opengever/base/browser/paste.py
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base.pot
- opengever/base/tests/test_copy_paste.py
- opengever/dossier/behaviors/dossier.py
- opengever/dossier/tests/test_dossier.py
- opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
- opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
- opengever/repository/locales/opengever.repository.pot
- opengever/repository/repositoryfolder.py
- opengever/repository/tests/test_repositoryfolder.py
Check allowedContentTypes before pasting objects from clipboard. To avoid pasting dossier in to branch_nodes.
Besides the repository add form shows now a warning message when adding a repositoryfolder to a leafnode, which already contains dossiers.
@deiferni
> Disallow moving/copying dossiers to a branch node.

- docs/HISTORY.txt
- opengever/document/checkout/checkin.py
- opengever/document/tests/test_checkout.py
view without selection documents.
Fixes #2252.
@deiferni
> Show statusmessage and redirect back to document when calling a checkin

- docs/HISTORY.txt
- opengever/base/oguid.py
- opengever/base/tests/test_oguid.py
- opengever/contact/handlers.py
- opengever/contact/models/participation.py
- opengever/contact/tests/test_participation.py
- opengever/contact/tests/test_participation_unit.py
This PR fixes an issue and ensures that participations are copied as well whenever a dossier is copied. 
Closes #2251.
> Copy participations whenever a dossier is copied.

- docs/HISTORY.txt
- opengever/examplecontent/hooks.py
- opengever/meeting/browser/periods.py
- opengever/meeting/model/period.py
- opengever/meeting/tests/test_committee_overview.py
- opengever/meeting/tests/test_period_query.py
- opengever/meeting/tests/test_periods.py
- opengever/meeting/tests/test_unit_meeting.py
- opengever/meeting/upgrades/20161101143905_make_period_dates_required/upgrade.py
- opengever/testing/builders/dx.py
This PR makes start and end date of a Period required. This is required to be able to:
- select meetings based on start/end date to create a table of contents for a period
- make sure that no overlapping periods may exist (would add duplicates to aforementioned TOC)
The data-migration part of this upgrade step will set start/end of a period to span the whole current year. This should be a reasonable default but must be validated by the customer after migration.
Part of #1373.
> Make committee-period dates required.

- docs/HISTORY.txt
- opengever/ogds/base/sync/ldap_util.py
- opengever/ogds/base/sync/ogds_updater.py
- opengever/ogds/base/tests/ldaphelpers.py
This makes sure that the official `_extra_user_filter` property is also respected during OGDS sync, in addition to our custom `user_filter` property.
> LDAPSearch utility: Also consider _extra_user_filter for user_filter expression.

- opengever/base/browser/modelforms.py
- opengever/base/model.py
- opengever/contact/models/contact.py
- opengever/contact/models/participation.py
- opengever/contact/participation.py
- opengever/meeting/browser/configure.zcml
- opengever/meeting/browser/meetings/protocol.py
- opengever/meeting/browser/memberships.py
- opengever/meeting/browser/periods.py
- opengever/meeting/committee.py
- opengever/meeting/committeecontainer.py
- opengever/meeting/interfaces.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/model/membership.py
- opengever/meeting/model/period.py
- opengever/meeting/tabs/periodlisting.py
- opengever/meeting/tests/test_committee.py
- opengever/meeting/tests/test_committee_container.py
- opengever/meeting/tests/test_memberships.py
- opengever/meeting/tests/test_periods.py
- opengever/meeting/tests/test_toc.py
- opengever/meeting/toc/alphabetical.py
- opengever/meeting/wrapper.py
- opengever/testing/builders/dx.py
- sources.cfg
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/477.
This PR prepares forms that are required to generate a TOC or to manage the period.
- Add a field for a toc template on commitee-container and committee
- Make Periods editable
It also contains an attempt to use the form/formsupport base-classes whenever possible.
*The CL entry for all these changes will follow in a later PR (in order to avoid splitting the CL entries too much)*
Part of #1373.
> Prepare forms for TOCs

- docs/HISTORY.txt
- opengever/contact/models/contact.py
- opengever/contact/models/org_role.py
- opengever/contact/ogdsuser.py
- opengever/journal/entry.py
- opengever/journal/form.py
- opengever/journal/tab.py
- opengever/journal/templates/journal_references.pt
- opengever/journal/tests/test_manual_entry.py
As discussed I've added a separate list `users` to the PersistentDict, so that references to users are handled separately.
In the journal tab all references (contacts and users) are listed together under the same title, equal than in the form.
Besides the fix for the users references this PR also fix adding entries without a comment.
@deiferni
> Fixed manual journal entry creation when users are selected as contacts.

- docs/HISTORY.txt
- opengever/base/reporter.py
- opengever/globalindex/browser/report.py
- opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
- opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
- opengever/globalindex/locales/opengever.globalindex.pot
- opengever/globalindex/tests/test_reporter.py
* Add a transform to the reporter to get the org_unit label
* Add the column to the excel export functionality
* Amend the tests
* Amend the locales
* Only the German locale is filled 
* Add a changelog entry
Fixes #2210
> Add a column for the issuing org_unit to the task report .xlsx exports

- docs/HISTORY.txt
- opengever/document/tests/test_document.py
- opengever/dossier/browser/default_view.py
* Changelog entry
* Test cases
* Modify self instead of the ancestor in dossier field exclusions for views
Fixes #2208
> Fix public_trial being hidden on document views after visiting a dossier

- docs/HISTORY.txt
- opengever/base/command.py
- opengever/base/quickupload.py
- opengever/base/tests/test_classification.py
- opengever/testing/builders/qickupload.py
When uploading documents with quickupload, default values were previously set incorrectly, because the `CreateDocumentCommand` attempted to set the default values itself (improperly, as it turns out).
Setting of default values is now handled by centralized patches in `opengever.base`, so this should be dropped. Fixes #2268
> Fix setting of default values for quickuploaded documents

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/tests/test_default_view.py
Because plone.app.dexterity also register a view for `IDexterityItem` and `IDexterityContent` our `OGDefaultView` has to be registered for both detailed interface `IDexterityItem` and `IDexterityContent` instead of using the base inteface `IDexterityContent` (see https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/browser/configure.zcml#L7-L22.
Fixes #2214 
@deiferni
> Register OGDefaultView for all contenttypes, to hide the form helpers in tasks detail view

- opengever/examplecontent/profiles/init/local_role_configuration/01_local_roles.json
Fixes #1904.
*IMO Changelog entry not necessary*
> Add missing local role definition for examplecontent committee container.

- docs/HISTORY.txt
- opengever/base/reporter.py
- opengever/document/browser/report.py
- opengever/document/browser/select_all.pt
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
- opengever/document/profiles/default/actions.xml
- opengever/document/tests/test_reporter.py
- opengever/document/upgrades/20161111090446_add_document_export_actions/actions.xml
- opengever/document/upgrades/20161111090446_add_document_export_actions/upgrade.py
- opengever/dossier/browser/report.py
- opengever/dossier/tests/test_templatedossier.py
- opengever/globalindex/browser/report.py
- opengever/globalindex/model/task.py
- opengever/tabbedview/browser/personal_overview.py
- opengever/tabbedview/browser/tabs.py
- opengever/task/browser/related_documents.py
* Added an export_documents action to portal_actions folder_buttons
* Added the action to relevant views
* Cleaned up the XLSX report generation code where appropriate
* Fixed the MyDocumentsProxy select_all view
* Was not implemented
* The javascript from ftw.tabbedview expects a listing of all documents (export despite pagination)
* Was listing the full site contents without implementing the view
* Localized
* Amended existing tests
* Added a test for the document XLSX export
* Added a changelog entry
Fixes #2209
> Add excel export functionality for documents

- docs/HISTORY.txt
- opengever/dossier/tests/test_dossier_byline.py
- opengever/meeting/configure.zcml
- opengever/meeting/tests/test_meeting_dossier_byline.py
A meeting-dossier should re-use the byline of a businesscase-dossier.
Fixes #1910.
> Use correct dossier byline for meeting dossiers.

- opengever/dossier/handlers.py
- opengever/journal/handlers.py
- opengever/meeting/handlers.py
- opengever/meeting/tests/test_proposal.py
Proposals should not be copied when copying a dossier.
There are many states where this does not make sense at the moment or the desired state after copying is unclear (e.g. already submitted or decided proposals.) Thus we prevent them from being copied for now.
Deleting the proposal right after it had been created had some consequences for the other event handlers, that's why i had to change from acquiring request/catalog to getting it through a global accessor.
Fixes #2282.
> Prevent copying proposals.

- docs/HISTORY.txt
- opengever/core/testing.py
- opengever/dossier/__init__.py
- opengever/dossier/base.py
- opengever/dossier/behaviors.zcml
- opengever/dossier/dossiertemplate/__init__.py
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/dossier/dossiertemplate/dossiertemplate.py
- opengever/dossier/dossiertemplate/interfaces.py
- opengever/dossier/dossiertemplate/menu.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/permissions.zcml
- opengever/dossier/profiles/default/registry.xml
- opengever/dossier/profiles/default/rolemap.xml
- opengever/dossier/profiles/default/types.xml
- opengever/dossier/profiles/default/types/opengever.dossier.dossiertemplate.xml
- opengever/dossier/profiles/default/types/opengever.dossier.templatedossier.xml
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_templatedossier.py
- opengever/dossier/upgrades/20161122103454_add_dossier_templates/registry.xml
- opengever/dossier/upgrades/20161122103454_add_dossier_templates/rolemap.xml
- opengever/dossier/upgrades/20161122103454_add_dossier_templates/types.xml
- opengever/dossier/upgrades/20161122103454_add_dossier_templates/types/opengever.dossier.dossiertemplate.xml
- opengever/dossier/upgrades/20161122103454_add_dossier_templates/types/opengever.dossier.templatedossier.xml
- opengever/dossier/upgrades/20161122103454_add_dossier_templates/upgrade.py
- opengever/testing/builders/dx.py
- sources.cfg
Dieser PR fügt einen neuen Inhaltstyp "Dossiertemplate" hinzu.
Der Inhaltstyp kann nur in einem `templatedossier` hinzugefügt werden.
In einem Dossiertemplate können Dokumente und weitere Dossiertemplates (Subdossier) hinzugefügt werden.
Das Feature kann in der Registry aktiviert bzw. deaktiviert werden.
Die Dossiertempalte-ID wird folgendermassen generiert: `dossietemplate-{squence-number}`
see #2143
> Implementiert Dossiertemplate

- docs/public/api/schemas/ftw.mail.mail.inc
- docs/public/api/schemas/opengever.document.document.inc
- docs/public/api/schemas/opengever.dossier.businesscasedossier.inc
- docs/public/api/schemas/opengever.repository.repositoryfolder.inc
- docs/public/api/schemas/opengever.repository.repositoryroot.inc
- docs/schema-dumps/ftw.mail.mail.schema.json
- docs/schema-dumps/opengever.document.document.schema.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
- docs/schema-dumps/opengever.repository.repositoryfolder.schema.json
- docs/schema-dumps/opengever.repository.repositoryroot.schema.json
- opengever/api/docsbuilder/schemadocs.py
- opengever/base/schemadump/field.py
- opengever/base/schemadump/schema.py
Only set `required` flag in schema dumps if no default value  is present for the given field.
The field may have a `required` flag on a `zope.schema` level, but functionally it's not really required if a default value is defined.
> Only set `required` flag in schema dumps if no default value exists

- docs/HISTORY.txt
- opengever/disposition/disposition.py
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- opengever/disposition/tests/test_disposition.py
- opengever/disposition/tests/test_history.py
- opengever/tabbedview/tests/test_dossier_listing.py
An upgradestep, which migrates the data is not necessary, there exists no productive disposition content.
Besides that change I moved the disposition fields to the common fieldset, to have the same look and feel as all the other content types.
@deiferni or @lukasgraf 
- https://basecamp.com/2768704/projects/12554551/todos/274416348
> Replace reference field with a transfer_number field on disposition schema.

- docs/public/api/schemas/ftw.mail.mail.inc
- docs/public/api/schemas/opengever.document.document.inc
- docs/public/api/schemas/opengever.dossier.businesscasedossier.inc
- docs/schema-dumps/ftw.mail.mail.schema.json
- docs/schema-dumps/opengever.document.document.schema.json
- docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
- opengever/base/schemadump/__init__.py
- setup.py
Unify schema dumping: Have the `bin/instance dump_schemas` zopectl handler dump both regular JSON schemas and OGGBundle JSON schemas.
Also updated the currently existing schema dumps with recent changes.
@phgross
> Unify schema dumping: Have bin/instance dump_schemas dump all schemas

- docs/schema-dumps/oggbundle/documents.schema.json
- docs/schema-dumps/oggbundle/dossiers.schema.json
- docs/schema-dumps/oggbundle/repofolders.schema.json
- docs/schema-dumps/oggbundle/reporoots.schema.json
- opengever/base/schemadump/schema.py
This change brings the JSON schema dump implementation in sync with what was used to produce the schemas in 4teamwork/ubitpoc#2.
(null values also need to be accepted for several fields in order for the data to validate against the schemas).
@deiferni
> OGGBundle schema dumps: Also allow 'null' for fields that aren't required.

- opengever/disposition/configure.zcml
- opengever/disposition/upgrades/configure.zcml
Otherwise ftw.upgrade does not mark the `opengever.disposition` profile as installed, when setting up a new GEVER.
IMO: it's just a fix of #2299 so a changelog entry is not necessary.
@lukasgraf as discussed
> Add missing upgradestep directory for the disposition profile

- docs/HISTORY.txt
- opengever/disposition/browser/excel_export.py
- opengever/disposition/disposition.py
- opengever/disposition/tests/test_disposition.py
- opengever/disposition/tests/test_listing.py
- opengever/testing/builders/dx.py
Default value format: `Disposition {admin unit abbreviation} {localized today's date}`
See https://basecamp.com/2768704/projects/12554551/todos/274416169
> Make disposition title editable, but prefill it with a default value.

- docs/HISTORY.txt
- opengever/dossier/browser/tabbed.py
- opengever/dossier/dossiertemplate/dossiertemplate.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/templatedossier/tabs.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_templatedossier.py
- opengever/testing/builders/dx.py
Dieser PR fügt das Dossiertemplates-Tab der Templatedossier-Tabbedview hinzu.
Wenn das Feature deaktiviert ist, wird das Tab nicht angezeigt.
Die Auflistung zeigt alle Dossiertemplates auf (ohne Subdossiers, gem. Dossier-Listing). Angezeigt werden Titel und Review-State.
see #2143
> fügt Dossiertemplates-Tab zu Templatedossier-Tabbedview hinzu

- docs/HISTORY.txt
- opengever/base/protect.py
- opengever/base/tests/test_protect.py
The current unprotection of the annotations BTree, hasn't worked, when the BTree were splitted into  multiple buckets. This PR resolves this problem.
@deiferni
> Unprotect all buckets of a BTree, when unprotecting a BTree.

- opengever/document/browser/overview.py
1. Test permission on the current context not the portal.
2. Fixed permission identifier.
_IMO: Changelog entry not necessary_
@deiferni
> Fixed permission check in document overview is_archivale_file_visible.

- opengever/core/testing.py
Our test queue was never reset properly, it should be reset after each test.
Fixes #2340.
> Fix a problem in test isolation with the bumblebee queue.

- opengever/setup/sections/jsonsource.py
- opengever/setup/sections/resolveguid.py
- opengever/setup/tests/__init__.py
- opengever/setup/tests/test_section_jsonsource.py
- opengever/setup/tests/test_section_resolveguid.py
- opengever/setup/transmogrifier.zcml
See https://github.com/4teamwork/opengever.core/issues/2306.
This PR adds a transmogrifier section that resolves and validate GUIDs.
It also yields items in an order that guarantees that parents are always positioned before their children. This is achieved by building a temporary tree, then re-yielding the nodes in pre-order.
This section also validates that:
- each item has a guid
- each guid is unique
- parent pointers are valid, should they exist
*CL will follow in a later PR*
> Add guid resolver section for oggbundles.

- docs/HISTORY.txt
- opengever/base/tests/test_contentlisting.py
- opengever/base/tests/test_source_binder.py
- opengever/document/tests/test_contentlisting.py
- opengever/meeting/tests/test_proposal.py
- opengever/meeting/tests/test_proposal_listings.py
- opengever/repository/profiles/default/types/opengever.repository.repositoryroot.xml
- opengever/repository/repositoryroot.py
- opengever/repository/tests/test_repository_root.py
- opengever/repository/upgrades/20161130162544_drop_i_name_from_title_from_repo_roots/types/opengever.repository.repositoryroot.xml
- opengever/repository/upgrades/20161130162544_drop_i_name_from_title_from_repo_roots/upgrade.py
- opengever/task/tests/test_assign_to_dossier.py
- opengever/testing/builders/dx.py
This fixes choosing names from the title in combination with ITranslatedTitle.
Fixes #2350.
> Replace INameFromTitle behavior with adapter for repository roots.

- docs/HISTORY.txt
- opengever/dossier/behaviors.zcml
- opengever/dossier/dossiertemplate/__init__.py
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/dossier/dossiertemplate/dossiertemplate.py
- opengever/dossier/dossiertemplate/menu.py
- opengever/dossier/profiles/default/types/opengever.dossier.dossiertemplate.xml
- opengever/dossier/templatedossier/tabs.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/upgrades/20161130093146_add_i_dossier_behavior_to_dossier_template/types/opengever.dossier.dossiertemplate.xml
- opengever/dossier/upgrades/20161130093146_add_i_dossier_behavior_to_dossier_template/upgrade.py
Dieser PR ersetzt den PR #2319.
Mit diesem PR können Schema-Felder welche über Behaviors dem Typ hinzugefügt werden über eine Whitelist aktiviert werden.
Alle anderen Schema-Felder werden nicht angezeigt.
So ist es möglich, dass ein Schema nicht mehrere Male erfasst werden muss.
> Implement dossier behavior inheritance for dossiertemplates

- docs/HISTORY.txt
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/plone.po
- opengever/base/locales/opengever.base.pot
- opengever/base/locales/plone.pot
- opengever/dossier/configure.zcml
- opengever/dossier/dossiertemplate/configure.zcml
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/upgrades/20161123153724_add_factory_action_to_repository_folder_to_add_dossier_from_template/types/opengever.repository.repositoryfolder.xml
- opengever/dossier/upgrades/20161123153724_add_factory_action_to_repository_folder_to_add_dossier_from_template/upgrade.py
- opengever/repository/profiles/default/types/opengever.repository.repositoryfolder.xml
- opengever/repository/repositoryfolder.py
- opengever/repository/tests/test_repositoryfolder.py
Dieser PR fügt eine neue Action: "Dossier aus Template" dem Repository-Folder hinzu.
Das Icon wurde in diesem PR hinzugefügt: https://github.com/4teamwork/plonetheme.teamraum/pull/484
see #2143
> Fügt "Dossier aus Template"-Action für Repository-Folder hinzu

- opengever/bumblebee/browser/overlay.py
Use unicode string literals in various places when operating with urls and links.
For the fix only one change would be required, but i thought this would be a good time for a smal cleanup operation 😉 .
Fixes #2351.
> Use unicode string literals for urls and links.

- opengever/base/schemadump/__init__.py
- opengever/base/schemadump/field.py
- opengever/base/schemadump/schema.py
- opengever/setup/cfgs/oggbundle.cfg
- opengever/setup/tests/assets/oggbundle/documents.json
- opengever/setup/tests/assets/oggbundle/dossiers.json
- opengever/setup/tests/assets/oggbundle/files/beschluss.pdf
- opengever/setup/tests/assets/oggbundle/files/bewerbung_pesche.docx
- opengever/setup/tests/assets/oggbundle/files/mueller.docx
- opengever/setup/tests/assets/oggbundle/repofolders.json
- opengever/setup/tests/assets/oggbundle/reporoots.json
- opengever/setup/tests/test_oggbundle_pipeline.py
- opengever/setup/transmogrifier.zcml
First implementation of the pipeline to import a bundle. It is based on our already customised `ftw.inflator` pipeline `opengever.setup.content`.
> Add oggbundle pipeline and example data imports.

- docs/HISTORY.txt
- opengever/bundle/console.py
- opengever/setup/sections/jsonsource.py
- setup.py
Adds a zopectl entry point to run OGGBundle import from console via `bin/instance import <path_to_oggbundle>`
@deiferni
> Add entry point to run OGGBundle import from console

- opengever/disposition/browser/removal_protocol.py
- opengever/disposition/disposition.py
- opengever/disposition/handlers.py
- opengever/disposition/history.py
- opengever/disposition/interfaces.py
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- opengever/disposition/tests/test_history.py
- opengever/disposition/tests/test_removal_protocol.py
- Make sure that destroying dossiers doesn't get logged to disposition history as an edited event.
Currently the modified event handler creates a history entry for each dossiers which gets removed, this is unnecessary and wrong. Therefore we mark the request with a marker interface, to ignore ModifiedEvents while destroying dossiers.
- Fixed transition label for the added and edited action.
- Fixed typo in german translations.
- Don't display `None` as transfer number in the removal protocol, if there is no transfer number.
@deiferni  or @lukasgraf
> Disposition history and removal protocol fixes

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
- opengever/dossier/dossiertemplate/configure.zcml
- opengever/dossier/dossiertemplate/dossiertemplate.py
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_dossier_template.py
Dieser PR fügt den Add-Wizard für "Dossier aus Template" hinzu:
ACHTUNG: Dieser PR behandelt nicht das rekursive erstellen von Dossiers und Dokumenten. Es geht hier lediglich um den Wizard und um das initiale Erstellen eines Basisdossiers aufgrund der Template-Attribute.
see #2143
> Dossiertemplates add wizard

- docs/HISTORY.txt
- opengever/meeting/tests/test_toc.py
- opengever/meeting/toc/alphabetical.py
With this PR items of a group are sorted by their full title (case insensitive), with
fallback to repository title and decision number instead of only by their first letter.
Closes #2375.
> Make sure that items of a TOC are sorted as well.

- docs/HISTORY.txt
- opengever/base/upgrades/20161205175814_disable_quickupload_override/propertiestool.xml
- opengever/base/upgrades/20161205175814_disable_quickupload_override/upgrade.py
- sources.cfg
⚠️  depends on https://github.com/collective/collective.quickupload/pull/60
This PR makes sure that configuration is consistent across all our installations.
The override default in collective.quickupload was inconsistent in the
default profile and in the upgrade step.
For a detailed description please see https://github.com/collective/collective.quickupload/pull/60.
Fixes https://github.com/4teamwork/opengever.core/issues/2297.
> Use quickupload from source and ensure consistent configuration.

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/agendaitem.py
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_agendaitem.py
Add server-side validation and client-side maxlength to proposal-based agenda items title field to prevent too long titles being submitted.
Also fix displaying messages client-side.
Fixes #2378.
> Prevent that too long proposal titles can be entered on meeting view.

- docs/HISTORY.txt
- opengever/private/root.py
- opengever/private/tests/test_folder.py
Since the private folder is the only content that is reachable for users
we do not show the parent private root for which they do not have any
permissions.
Closes #2244.
> Hide private root from breadcrumbs.

- opengever/setup/sections/jsonsource.py
JSON source: Open JSON files using codecs module and `'utf-8-sig'` codec in order to handle JSON files that contain an UTF-8 BOM (byte order marker) at the beginning.
@deiferni
> JSON source: Open JSON files using codecs module and 'utf-8-sig' codec

- docs/HISTORY.txt
- opengever/base/command.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/dossier/command.py
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/examplecontent/profiles/default/registry.xml
- opengever/examplecontent/profiles/municipality_content/opengever_content/05_dossiertemplates.json
- opengever/meeting/command.py
Dieser PR erstellt rekursiv Dossiers und Dokumente anhand des Dossiertemplates.
Zusätzlich fügt er zwei Dossiertemplates als Examplecontent hinzu.
see #2143
> Add recursive dossier creation for dossiertemplates

- docs/HISTORY.txt
- opengever/contact/upgrades/20160824101726_add_org_role_participations/upgrade.py
This PR adds the missing length parameter to the  `AddOrgRoleParticipations` upgradestep, which failed on deployments with MySQL Backend.
Traceback:
```
File "/home/zope/eggs/SQLAlchemy-1.0.5-py2.7-linux-x86_64.egg/sqlalchemy/sql/compiler.py", line 2578, in visit_string
return self.visit_VARCHAR(type_, **kw)
File "/home/zope/eggs/SQLAlchemy-1.0.5-py2.7-linux-x86_64.egg/sqlalchemy/dialects/mysql/base.py", line 2306, in visit_VARCHAR
self.dialect.name)
CompileError: VARCHAR requires a length on dialect mysql
```
@deiferni  or @lukasgraf please have a look
> Fixed schemamigration for deployments with MySQL backend

- opengever/journal/tests/test_manual_entry.py
Fix flaky test: Journal entry sort order was fixed in fb18056f, so that journal entries are now sorted in chronological order. In combination with the timestamp used in this test (`09.12.2016 09:40`) and another journal entry (we don't care about) using the non-frozen, dynamic `datetime.today()`, this resulted in the sort order changing today (2016-12-09), and the test started to fail.
@phgross
> Fix flaky test depending on journal entry sort order

- docs/HISTORY.txt
- opengever/tabbedview/browser/personal_overview.py
- opengever/tabbedview/browser/tabs.py
- opengever/tabbedview/tests/test_bumblebee_gallery.py
The current implementation included the current context, which leads to different bugs when calling tabbedview actions. Fixes #2387.
> Fixed select_all selection for ProxyTabbedViews as the document listings.

- docs/schema-dumps/ftw.mail.mail.schema.json
- docs/schema-dumps/oggbundle/documents.schema.json
- docs/schema-dumps/oggbundle/dossiers.schema.json
- docs/schema-dumps/opengever.document.document.schema.json
- opengever/base/schemadump/config.py
- opengever/base/schemadump/schema.py
Completely remove `digitally_available` from all schema dumps. That field is de facto a property and is always set automatically depending on file availability. I think it is reasonable to also drop it from the schema dumps for the documentation.
Also add `sequence_number` to JSON-Schema for dossiers and documents.
Closes #2365
> Completely remove digitally_available, add sequence_number to jsonschema.

- docs/HISTORY.txt
- opengever/inbox/tests/test_accept.py
- opengever/task/browser/accept/utils.py
To avoid tasks with an invalid task_type when canceling the `edit`-form or close the browser after creation, we creates the successor task with a default task type (`For information` - `zur Kenntnisnahme`).
Fixes #2125.
Further details in the [Extranet Issue](https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20191)
> Creates successor-tasks of forwardings with a default task type.

- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/upgrades/configure.zcml.bob
We don't have bin/create-upgrade there, that is `opengever.core` specific. Instead we should use the normal `ftw.upgrade` command.
> Use correct upgrade command description for policies.

- docs/HISTORY.txt
- opengever/base/command.py
- opengever/base/profiles/default/propertiestool.xml
- opengever/dossier/command.py
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/profiles/default/workflows.xml
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/upgrades/20161206181806_do_not_list_dossier_template_in_navigation/propertiestool.xml
- opengever/dossier/upgrades/20161206181806_do_not_list_dossier_template_in_navigation/upgrade.py
- opengever/dossier/upgrades/20161206182239_remove_workflow_for_dossier_templates/upgrade.py
- opengever/dossier/upgrades/20161206182239_remove_workflow_for_dossier_templates/workflows.xml
- opengever/dossier/upgrades/20161207090323_adjust_action_permission_for_dossier_template/types/opengever.repository.repositoryfolder.xml
- opengever/dossier/upgrades/20161207090323_adjust_action_permission_for_dossier_template/upgrade.py
- opengever/meeting/command.py
- opengever/repository/profiles/default/types/opengever.repository.repositoryfolder.xml
Dieser PR macht diverse Anpassungen an Dossiertemplates und behebt kleinere Fehler:
- Löscht eine ungebrauche `skip_defaults_fields` variable aus dem ObjectCreatorCommand-Objekt und seinen Sub-Objekten weil sie nirgends gebrauch wird.
- Zeigt Dossiertemplates nicht mehr in der Navigation an
- Entfernt den Workflow für Dossiertemplates
- Schützt den Dossiertemplate Wizard mit der `opengever.dossier: Add businesscasedossier` permission
see #2143
> Anpassungen für Dossiertemplates

- docs/HISTORY.txt
- opengever/document/base.py
- opengever/document/document.py
- opengever/document/tests/test_document.py
- opengever/mail/mail.py
- opengever/mail/tests/test_message_filename_initialized.py
- opengever/meeting/browser/sablontemplate.py
- opengever/meeting/model/agendaitem.py
- opengever/meeting/tests/test_protocol_json_data.py
This adds a common interface to access the filename to documents and mails.
Fixes #2430.
> Add get_filename method to documents and mails.

- docs/HISTORY.txt
- opengever/base/monkey/patches/__init__.py
- opengever/base/monkey/patches/cmf_catalog_aware.py
- opengever/base/tests/test_patch_catalog_aware.py
Patch the Products.CMFCore.CMFCatalogAware indexObject, reindexObject
and unindexObject methods.
This patch is deactivated by default and can be activated through
the `DeactivateCatalogIndexing` context manager:
```
>>> with DeactivateCatalogIndexing():
...     object.reindexObject  # Does nothing
...     object.unindexObject  # Does nothing
...     object.indexObject  # Does nothing
```
If the patch is activated, it skips the catalog index-methods.
What's the motivation behind this patch?
While creating an object, the object will be reindexed up to 4 times.
This behavior takes a lot of time and is not performance-friendly. Creating
one object through the web might be not a performance issue. But in several
parts of the GEVER-system we're creating a lot of content programatically
(i.e. …
> Patch CMFCatalogAware object to improve performance.

- docs/HISTORY.txt
- opengever/dossier/dossiertemplate/form.py
Dieser PR verwendet den Patch von #2428 um die Performance für die Erstellung von Dossiers anhand von Dossiertemplates zu erhöhen.
Mit diesem Patch wird die Zeit für die Erstellung um bis zu 65% verringert.
Ein Dossier aus einer Dossiervorlage mit 35 Dossiers zu erstellen dauert im Schnitt:
ohne Patch: ~ 20 Sekunden
mit Patch ~ 7 Sekunden
see #2382
see #2143
> Improve dossiertemplate performance

- docs/HISTORY.txt
- opengever/contact/docprops.py
- opengever/contact/models/org_role.py
- opengever/contact/tests/test_docprops.py
- opengever/dossier/templatedossier/form.py
- opengever/dossier/tests/test_templatedossier.py
This PR includes introduces a combined address for person and organization when creating a template based on an org-role.
Also see https://basecamp.com/2768704/projects/12330648/todos/280602489.
Closes #2419.
> Include organization name in org-role addresses.

- docs/HISTORY.txt
- opengever/base/source.py
- opengever/base/tests/test_source_binder.py
- opengever/journal/form.py
- opengever/journal/tests/test_manual_entry.py
- opengever/mail/tests/test_senddocument.py
- opengever/meeting/tests/test_proposal.py
to only documents inside the dossier. Closes #2416 
Besides that I've found and fixed an issue in the DossierPathSourceBinder, which only limits the selectable objects for the selection in the tree widget but not for the selection with the autocomplete field.
> Limit document selection when creating a manual journal entry.

- docs/HISTORY.txt
- docs/public/docproperties/list.rst
- opengever/base/vocabulary.py
- opengever/disposition/ech0160/utils.py
- opengever/dossier/docprops.py
- opengever/dossier/tests/__init__.py
- opengever/dossier/tests/test_default_doc_property_adapters.py
- opengever/dossier/tests/test_doc_property_writer.py
This PR adds a new doc-property `ogg.document.document_type` for documents.
Closes #2426.
> Add doc-property ogg.document.document_type for documents.

- docs/HISTORY.txt
- opengever/base/behaviors/lifecycle.py
- opengever/base/permissions.zcml
- opengever/base/profiles/default/rolemap.xml
- opengever/base/tests/test_lifecycle.py
- opengever/base/tests/test_ploneform_macros.py
- opengever/base/upgrades/20161215174608_add_edit_date_of_submission_permission/rolemap.xml
- opengever/base/upgrades/20161215174608_add_edit_date_of_submission_permission/upgrade.py
- opengever/base/upgrades/20161215175817_add_edit_date_of_cassation_permission/rolemap.xml
- opengever/base/upgrades/20161215175817_add_edit_date_of_cassation_permission/upgrade.py
- opengever/meeting/tests/test_periods.py
- opengever/meeting/tests/test_toc.py
Protect date of cassation and submission with a separate edit permission, which only managers should be allowed to edit those dates. Closes #2422
> Protect date of cassation and submission with a separate edit permission

- docs/HISTORY.txt
- setup.py
local performance measurements. 
**Test-Case: Creating 40 different files incl. tika.**
WITHOUT: 37s
WITH: 21s
**Test-Case: 5 parallel users uploading files with quickupload**
WITHOUT: 2s pro Request
WITH: 3.3s pro Request
**Test-Case: 1 seriell users uploading files with quickupload**
WITHOUT: 1 rps (880ms per Request)
WITH: 1.6 rps (880ms per Request)
> Install collective.indexing

- docs/HISTORY.txt
- opengever/bundle/tests/assets/basic.oggbundle/files/sample.eml
- opengever/setup/sections/fileloader.py
- opengever/setup/tests/test_oggbundle_pipeline.py
- opengever/setup/tests/test_section_constructor.py
- opengever/setup/tests/test_section_fileloader.py
Extends the fileloader in the OGGBundle pipeline to properly deal with `*.eml` mails, and adds some additional tests.
@deiferni
> Extend OGGBundle fileloader to handle mails correctly.

- docs/HISTORY.txt
- opengever/base/reference_formatter.py
- opengever/base/tests/test_reference.py
Make sure reference number sorters also support sorting repofolder-only numbers (i.e., no dossier/document parts).
> Make sure reference number sorters also support sorting repofolder-only numbers

- opengever/base/acquisition.py
Bound field before accessing the default value otherwise the zope.schema field validation will raise an `TypeError: argument of type 'function' is not iterable` when validating the aquired value.
I've found this problem during rewriting the default values to defaultFactories for PHVS specific choice fields.
> Fixed acquired_default_factory for choice fields with a vocabulary.

- sphinx.cfg
This change makes the use of `bin/zopepy` to update schema docs optional (schema docs will only be updated if a `bin/zopepy` is found).
This facilitates the use of `sphinx.cfg` through the `sphinx-standalone.cfg` to have a buildout that is purely intended as an environment to work on documentation. This buildout has minimal dependencies and runs through in just a couple seconds.
The use of this buildout is already documented at https://intern.onegovgever.ch/meta/#arbeiten-an-der-dokumentation
@deiferni
> Facilitate standalone Sphinx buildout, by making schema docs building optional

- opengever/meeting/browser/meetings/configure.zcml
This gets rid of the last `WARNING` during instance bootup 🎉 .
> Drop security declaration for nonexistent method 'schedule'.

- docs/HISTORY.txt
- docs/public/user-manual/aussonderung.rst
- opengever/dossier/base.py
- opengever/dossier/tests/test_retention_expiration.py
- opengever/dossier/upgrades/20161117162220_add_new_index_retention_expiration/upgrade.py
- opengever/dossier/upgrades/20170116224918_update_retention_period_calculation/upgrade.py
The retention period of a dossier should expire at the beginning of the year after the retention period, see https://basecamp.com/2768704/projects/12554551/todos/286197285. This PR changes the calculation and reindex the expiration date for all resolved dossiers. Closes #2425.
Note: This PR also disables the calculation of the retention_expiration date for all resolved dossiers in a earlier upgradestep. This makes sense for all deployments which has not installed the newest GEVER release yet otherwise the expiration date would be calculate twice. For deployments where the retention_expiration is already installed the disabled calculation has no impact.
> Adjust dossiers retention expiration calculation.

- docs/HISTORY.txt
- opengever/base/interfaces.py
- opengever/bundle/tests/assets/basic.oggbundle/dossiers.json
- opengever/bundle/tests/assets/basic.oggbundle/repofolders.json
- opengever/core/debughelpers.py
- opengever/dossier/handlers.py
- opengever/setup/sections/constructor.py
- opengever/setup/tests/test_oggbundle_pipeline.py
OGGBundle constructor: Support setting local reference number part for dossiers (when provided by JSON item).
If (for dossiers) a key `reference_number` is provided, this will be used to prevent automatically issuing the next free reference number (local part), and set the given local part value instead.
I also updated some existing tests so that we test the setting of the local parts (called "reference_prefixes") for repository folders (which already worked) with non-sequential numbers.
TODO (separately): Validate uniqueness of reference number local parts on their respective levels.
@deiferni
> OGGBundle constructor: Support setting local reference number part for dossiers (when provided by JSON item).

- docs/HISTORY.txt
- opengever/bundle/loader.py
⚠️ Builds upon #2481 - merge that one first ⚠️  
Removes any file extension from the title if necessary, so it doesn't end up in the final title.
> OGGBundle loader: Strip extension for title if necessary.

- docs/HISTORY.txt
- opengever/setup/cfgs/oggbundle.cfg
- opengever/setup/sections/navigation.py
Assigns nav tree portlets for repo roots imported via OGGBundle pipeline.
In theory, this affects examplecontent / new site setup in general as well, but *functionally* it shouldn't change anything. The new strategy now is as follows:
- For the Plone Site root, assign a navtree portlet with the first reporoot in the pipeline.
- For the 95% case with exactly one root during setup, that'll be that one
- All other global tabs that inherit that portlet will therefore show the primary root in the navigation
- For all reporoots, portlet inheritance is blocked and they get their own nav tree portlet (obviously with *their* repo root ID configured)
> OGGBundle pipeline: Assign nav tree portlets for imported repo roots.

- opengever/bundle/loader.py
- opengever/bundle/tests/test_bundle_loader.py
- opengever/setup/sections/bundlesource.py
Displays some basic stats (type counts) for items loaded from bundles.
At a later point we'll include counts for objects that have actually been migrated (catalog queries), and those two will hopefully match up 😉 
@deiferni
> OGGBundle loader: Display basic stats when loading bundle

- docs/HISTORY.txt
- opengever/bundle/configure.zcml
- opengever/bundle/sections/map_local_roles.py
- opengever/bundle/tests/assets/basic.oggbundle/dossiers.json
- opengever/bundle/transmogrifier.zcml
- opengever/setup/cfgs/oggbundle.cfg
- opengever/setup/tests/test_oggbundle_pipeline.py
Map local roles from short names used in OGGBundles to actual role names and prepare them in a way so that `collective.blueprint.jsonmigrator` can deal with them.
For example, this section transforms a rolemap from an OGGBundle looking like this
```
'_permissions': {
'block_inheritance': True,
'read': ['regular_users', 'admin_users'],
'reactivate': ['admin_users']
}
```
to this:
```
'block_inheritance': True,
'_ac_local_roles': {'regular_users': ['Reader'],
'admin_users': ['Reader', 'Publisher']},
```
@deiferni - as discussed, implemented as a stand-alone section just to be used for OGGBundles.
> Implement setting of local roles in OGGBundle pipeline.

- opengever/bumblebee/browser/overlay.py
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/document/browser/download.py
- opengever/document/browser/templates/submitted_with.pt
- opengever/document/widgets/tooltip.pt
- opengever/document/widgets/tooltip.py
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_sql_task.py
- opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
- opengever/meeting/tests/test_submit_additional_documents.py
The change on the `plonetheme.teamraum` side:
https://github.com/4teamwork/plonetheme.teamraum/pull/493
All related styling for is now prefixed and contained consistently in the anchor elements.
> Made CSS for outdated and overdue items consistent

- opengever/base/viewlets/footer.pt
This is a follow-up for https://github.com/4teamwork/opengever.core/pull/2454, it updates the link in the footer and points to onegovgever.ch instead of onegov.ch
> Update footer link, point to onegovgever.ch.

- sphinx-standalone.cfg
The `sphinx-standalone.cfg` buildout doesn't inherit the `opengever.core` version pinnings, so `setuptools` and `zc.buildout` need to be pinned separately.
See 4teamwork/ftw-buildouts#68
> Sphinx buildout: Pin setuptools and buildout versions.

- docs/HISTORY.txt
- opengever/dossier/dossiertemplate/tabs.py
- opengever/dossier/tests/test_dossier_template.py
This ensures that documents in both list and gallery views are sorted alphabetically.
This also makes sure an associated, flaky test now consistently passes: https://ci.4teamwork.ch/builds/56559/tasks/80536#bottom
@deiferni @Rotonen
> Fix sorting for documents in template dossier "documents" tab.

- opengever/tabbedview/tests/test_dossier_listing.py
Dossiers are sorted by `modified` by default (which is correct, or at the very least the way it's always been).
Because the modified timestamp as a one-second resolution, it occasionally can happen that sorting by `modified` in tests doesn't exactly equal actual creation order. Therefore we need to not assert on item order in this test.
@deiferni
> Fix flaky test

- docs/HISTORY.txt
- opengever/disposition/browser/ech0160.py
- opengever/disposition/disposition.py
- opengever/disposition/ech0160/sippackage.py
- opengever/disposition/tests/test_ech0160export.py
- opengever/disposition/tests/test_model.py
- opengever/disposition/tests/test_sippackage.py
Replaced the placeholder `myRef` with the transfer number if it exits.
Fix according to the users Testfeedback.
> Fixed SIP package name, include disposition transfer number if exists.

- docs/HISTORY.txt
- opengever/bundle/console.py
- opengever/bundle/ldap.py
Based on code that's already been used/tested in `opengever.bsmigration`.
@deiferni
> Disable LDAP during OGGBundle import to avoid costly LDAP lookups.

- docs/HISTORY.txt
- opengever/base/browser/breadcrumb_by_uid.py
- opengever/base/browser/configure.zcml
- opengever/base/browser/resources/tooltip.js
- opengever/base/contentlisting.py
- opengever/base/indexes.py
- opengever/base/profiles/default/catalog.xml
- opengever/base/tests/test_breadcrum_by_uid.py
- opengever/base/tests/test_breadcrumb_by_uid.py
- opengever/base/upgrades/20161222184858_remove_breadcrumb_titles_from_metadata/catalog.xml
- opengever/base/upgrades/20161222184858_remove_breadcrumb_titles_from_metadata/upgrade.py
- opengever/latex/listing.py
- opengever/tabbedview/helper.py
- opengever/tabbedview/tests/test_dossier_listing.py
This makes indexing (without searchableText 30% faster).
Trade off (reading):
- Get the breadcrumb titles on dossier listings async
- Makes some latex and maintenance script slower.
> Remove breadcrumb_titles index (metadata).

- opengever/disposition/browser/templates/overview.pt
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- Fixed `Don't archive` translation (fixes #2513)
- Translate title of transition actions (fixes #2514)
> Fixed translations on the disposition overview.

- docs/HISTORY.txt
- opengever/officeconnector/configure.zcml
The `<plone:service />` directive is defined by [`plone.rest`'s `meta.zcml`](https://github.com/plone/plone.rest/blob/375c7c8306fd3f68f4ba8a327ee73950286ac453/src/plone/rest/meta.zcml#L5-L9).
Therefore we first need to load the ZCML of `plone.rest` before using this directive. Otherwise we're implicitly relying on a particular load order that might or might not be given.
Fixes this test failure: https://ci.4teamwork.ch/builds/57963/tasks/82506#bottom
@deiferni @Rotonen
> Load ZCML of plone.rest before using plone:service directive.

- opengever/base/viewlets/footer.pt
The footer now shows a version, this PR shortens the label from "GEVER Version" to "Version".
Closes #2527.
> Shorten version label in footer.

- docs/HISTORY.txt
- opengever/contact/browser/participation_add_view.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/profiles/default/actions.xml
This is for the plone base contacts implementation. The link as well as the translation label were broken. This PR fixes those issues.
Closes #2528
> Fix broken link and missing translation for add participation label.

- development.cfg
We should use colors to visually distinguish orphaned upgrade steps. Having an orphaned upgrade step may require action, i.e. touching the upgrade to avoid re-installing an already installed upgrade. This PR includes the  `colors` extra from `ftw.upgrade` for local development.
**no colors:**
**vs. colors:**
> Use ftw.upgrade colors extra for development.

- docs/HISTORY.txt
- opengever/meeting/browser/resources/meeting.js
Closes https://github.com/4teamwork/opengever.core/issues/2437
IE11 does not render newly added agenda points in a new tab before an explicit reload.
This behavior is documented under http://go.microsoft.com/fwlink/?LinkID=291337.
So explicitly refresh the page after the `pageshow` event.
The pageshow event is fired when a session history entry is being traversed to.
This includes back/forward as well as initial page-showing after the onload event.
For some reasons the `persisted` attribute on the event is not set properly:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101518/
So the agenda points are re-rendered on every pageload.
> Fix rendering of new agenda points in IE11.

- docs/HISTORY.txt
- opengever/base/browser/resources/tooltip.js
**Cause**
With the removal of the breadcrumb_title index, the data for the title attribute is now fetched async. 
The event handler is registered on `rollover-breadcrumb`. 
For some reason the boxes on the overview tab may have this class too. Only if [this](https://github.com/4teamwork/opengever.core/blob/033e68ae4de64908e89cd7726cf516f26ec5ce8b/opengever/base/browser/boxes_view.py#L17) mixing is used. 
**Solution**
I cannot say why, nor what's the reason for this. 
But with this change, the event handler is registered more specific and makes sure the `data-uid` attribute is present. 
This avoids an accidentally trigger of the tootlip. 
Fixes #2542
> Make sure the breadcrumb title tooltip only gets loaded if a data-uid attribute is present

- docs/HISTORY.txt
- opengever/meeting/browser/resources/meeting.js
Closes https://github.com/4teamwork/opengever.core/issues/2545
The AgendaItemController is only initialized on a meeting page.
So the update after the `pageshow` event should also just happen
on a meeting page.
Explicitly tested on Chrome and IE11.
> Fix error on agendaItemController update

- docs/HISTORY.txt
- test-docs-intern.cfg
- test-docs-public.cfg
Adds tests for Sphinx docs builds.
Warnings will be interpreted as errors, causing the build to fail.
`public` and `intern` docs will be tested separately. Each of those tests currently takes ~1.5 min to run.
Example build with one failing, one passing:
https://ci.4teamwork.ch/builds/59126/
> Add tests for Sphinx docs builds

- docs/HISTORY.txt
- opengever/base/overrides.zcml
- opengever/base/templates/widget.pt
- opengever/base/tests/test_widget.py
- opengever/base/widgets.py
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_templatedossier.py
Dieser PR implementiert das neue Feld `Titelhilfe` für Dossiertemplates.
closes #2444
> Implementiert ein neues Feld "Titelhilfe" für Dossiertemplates

- docs/HISTORY.txt
- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/console.py
- opengever/bundle/sections/constructor.py
- opengever/bundle/sections/post_processing.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/bundle/transmogrifier.zcml
- opengever/document/checkout/handlers.py
- opengever/document/interfaces.py
- opengever/setup/sections/versioning.py
- Defer the creation of initial versions to the **end of the OGGBundle pipeline** by introducing a dedicated post-processing section
- Make sure the *automatic* creation of initial versions is actually disabled
- Use a **request layer** instead of monkey patching to disable automatic creation of initial versions
- Do **intermediate commits** during creation of initial versions. This addresses
a **performance issue** where the time to write initial versions increases
exponentially with the number of previous initial versions created in the
same transaction.
Explicit commits of the transaction will be logged and indicated in the transaction note. Example how this will look in the ZMI Undo tab:
@deiferni
> Defer creation of initial versions to end of OGGBundle pipeline

- docs/HISTORY.txt
- opengever/mail/browser/send_document.py
- opengever/mail/tests/test_senddocument.py
Fix send_documents view on the inbox.
Allows the functionality to save sent files in the dossier only for IDossierMarker-types.
fixes #2301
> Fix attribute error if send documents

- docs/HISTORY.txt
- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/console.py
- opengever/bundle/loader.py
- opengever/bundle/report.py
- opengever/bundle/sections/bundlesource.py
- opengever/bundle/sections/constructor.py
- opengever/bundle/sections/fileloader.py
- opengever/bundle/sections/map_local_roles.py
- opengever/bundle/sections/post_processing.py
- opengever/bundle/sections/report.py
- opengever/bundle/sections/resolveguid.py
- opengever/bundle/tests/__init__.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/bundle/tests/test_section_bundlesource.py
- opengever/bundle/tests/test_section_constructor.py
- opengever/bundle/tests/test_section_fileloader.py
- opengever/bundle/tests/test_section_resolveguid.py
- opengever/bundle/transmogrifier.zcml
This implements some basic reports for imported objects.
In addition to the summary at the start, right after reading the contents from the bundle, this will also produce reports at the end of the import that are based on what objects actually could be found in **Plone** (i.e. based on catalog queries).
This includes a very short summary of object counts in ASCII, and a much more detailed XLSX report.
@deiferni
> OGGBundle pipeline: Implement basic reports for imported objects

- opengever/bundle/report.py
OGGBundle report: Make getting file size more safe to deal with the case of documents that don't have a file.
@deiferni
> OGGBundle report: Make getting file size more safe

- docs/HISTORY.txt
- opengever/base/locales/de/LC_MESSAGES/plone.po
- opengever/base/menu.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/repository/tests/test_repositoryfolder.py
This PR changes the translation for "Dossier with template"
closes #2560
> Update menu order and rename translation for "Dossier with template"

- docs/HISTORY.txt
- opengever/bundle/sections/report.py
Also **store raw JSON data** for errors and stats.
This makes sure that we have all the raw data tracked during import, in order to
- create more detailed reports after the fact
- have a fail-safe to make sure this data is stored on disk, even if an exception happens during the more complex and error-prone XLSX generation
This also unifies the report structure, by making it a **self-contained, timestamped directory**. A report directly containing all relevant files will be created:
```
var/
import-report-2017-02-15_18-58-43/
main-report.xlsx
errors.json
stats.json
```
*(To be added later: Full log of stderr (`import.log`) and validation report (`validation-report.xlsx`))*
@deiferni
> OGGBundle reports: Also store raw JSON data for errors and stats

- docs/intern/operations/saas.rst
The repository was moved to https://github.com/4teamwork/opengever-buildouts/ so we need to update the links.
> Update link to meta repository, it was renamed to opengever-deployments.

- docs/HISTORY.txt
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/document/widgets/tooltip.pt
- opengever/officeconnector/tests/test_templates.py
* Add tests for template integrity for the various similar subviews.
* Fix the subviews.
Fixes #2581.
> Fix OfficeConnector CSS IDs in templates

- docs/HISTORY.txt
- opengever/base/tests/test_translated_title.py
- opengever/base/upgrades/20170215175054_allow_add_root_content_only_for_manager/rolemap.xml
- opengever/base/upgrades/20170215175054_allow_add_root_content_only_for_manager/types/opengever.meeting.committeecontainer.xml
- opengever/base/upgrades/20170215175054_allow_add_root_content_only_for_manager/upgrade.py
- opengever/dossier/profiles/default/rolemap.xml
- opengever/dossier/tests/test_templatefolder.py
- opengever/inbox/profiles/default/rolemap.xml
- opengever/inbox/tests/test_inbox.py
- opengever/inbox/tests/test_inbox_container.py
- opengever/meeting/permissions.zcml
- opengever/meeting/profiles/default/rolemap.xml
- opengever/meeting/profiles/default/types/opengever.meeting.committeecontainer.xml
- opengever/meeting/tests/test_committee_container.py
- opengever/repository/profiles/default/rolemap.xml
- opengever/repository/tests/test_repository_root.py
This PR removes the permission to add root content for administrators.
GIF as Administartor:
closes #2246
> Allow add root content only for managers.

- docs/HISTORY.txt
- opengever/repository/browser/referenceprefix_manager.py
- opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
- opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
- opengever/repository/locales/opengever.repository.pot
- opengever/repository/tests/test_reference_prefix_manager.py
Fix an error if the user tries to unlock a referencenumber in the referenceprefix manager which is still in use.
The user will see an error status-message instead the full errror-traceback.
closes #2465
> Fix an error if the user tries to unlock a referencenumber

- opengever/dossier/browser/save_comments_entpoint.py
- opengever/dossier/tests/test_dossier_byline.py
This is a fix of a feature introduced with #2582 
There's no changelog entry, since it's a bugfix of a feature in the same release.
> Dossier Note Overlay: Enable CSRF protection by optimizing a test case.

- opengever/base/upgrades/20170221105056_fix_keyword_widget_rolemap_customization/rolemap.xml
- opengever/base/upgrades/20170221105056_fix_keyword_widget_rolemap_customization/upgrade.py
- opengever/policy/base/profiles/default/metadata.xml
`opengever.base:default` does reconfigure the rolemap configuration of `ftw.keywordwidget`.
But because `ftw.keywordwidget` was installed _after_ `opengever.base`, the customization was overwritten with the defaults on a fresh installation.
It did work in test, because the tests do not install GEVER exactly as it is installed in production. (We will prevent such problems with #2588).
It did work when upgrading, because the upgrade step did it in the right order.
The problem by verified by checking the security configuration on the Plone site (manage_access): it is correctly configured when the Contributor-role has the "ftw.keywordwidget: Add new term" permission on the site root.
-----
This change #2539, which is installing the keywordwidget, was not yet released. Therefore I did not add …
> Fix keyword widget installation order.

- opengever/base/tests/test_pasting_allowed.py
- opengever/core/testing.py
- opengever/meeting/tests/test_proposal.py
- opengever/repository/tests/test_deletion.py
Change the test setup so that we install ``opengever.policy.base:default`` rather than its dependencies, so that we include the configuration from the policy profile.
The language is reset to English so that we do not have to change all the tests.
Because a bunch of tests rely on having ``filter_content_types=False`` configured for the ``Plone Site`` FTI, we still keep that for now. This should be awoided for future tests and can be elminiated step by step.
----
This change was initially planned to be part of the profile merge, but it makes sense as a standalone change too.
> testing: install opengever.policy.base:default.

- opengever/task/tests/test_task.py
- opengever/task/upgrades/20170221151551_shorten_task_title_to_256/upgrade.py
Improve a given task title test slightly. 
Closes #1217
> Add upgrade step to shorten task titles to 256 chars. 

- opengever/testing/test_case.py
We are not enalbing the "correct mode", but just switching to HTML mode because the testbrowser does not understand JavaScript.
> testcase: reword ExtJS comment.

- development.cfg
- docs/HISTORY.txt
- opengever/base/browser/modelforms.py
- opengever/inbox/browser/assign.py
- opengever/meeting/browser/documents/submit.py
- opengever/meeting/browser/meetings/excerpt.py
- opengever/meeting/browser/submitdocuments.py
- opengever/meeting/form.py
- opengever/task/browser/assign.py
- opengever/task/browser/delegate/recipients.py
- opengever/task/browser/modify_deadline.py
- opengever/task/response.py
- test-plone-4.3.x.cfg
This **whitelists the prefilling of certain forms via `GET` request.**
This is necessary after the inclusion of [`Products.PloneHotfix20160830`](https://pypi.python.org/pypi/Products.PloneHotfix20160830), which disallows this behavior by default (potential for XSS and reflexive XSS).
Issues / failures happened pretty much where I expected them, and were easy to debug and fix. So even if I missed one here because it wasn't covered by our test suite, it should be trivial to ship a quick fix to address those.
---
This PR also makes sure that the **Hotfixes we use in production are also included in development and test buildouts** - besides this being a good idea anyway, this is needed to actually have the issues with form prefilling surface via failing tests (see [failed build …
>  Allow certain z3c forms to be prefilled via GET requests

- opengever/testing/test_case.py
The helper methods "assertPageContains" and "assertPageContainsNot" assert the complete HTML, which should never be done. They are not used. Therefore we remove them.
> testing: remove assertPageContains[Not].

- docs/HISTORY.txt
- opengever/meeting/browser/meetings/agendaitem_list.py
- opengever/meeting/browser/meetings/configure.zcml
- opengever/meeting/browser/meetings/meeting.py
- opengever/meeting/browser/meetings/templates/meeting.pt
- opengever/meeting/browser/meetings/zipexport.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/meeting/tests/test_meeting_zipexport.py
Minimal requirements are defined in #2183, they are:
And...
Software design decision:
Example structure:
```
normalized-title-of-meeting.zip
├── Agenda items attachments
│   ├── AgendaItem 1
│   │   ├── some_attachment-xyz.pdf
│   │   └── some_attachment.pdf
│   ├── AgendaItem 2
│   │   └── bla.docx
│   └── AgendaItem 3
│       ├── example.doc
│       ├── example2.pdf
│       └── example3.pdf
├── agendaitems-xyc.docx
└── protocol-xyz.docx
```
--> Example ZIP: 
[Gemeindeversammlung- 09.06.2017.zip](https://github.com/4teamwork/opengever.core/files/780259/Gemeindeversammlung-.09.06.2017.zip)
> Implement SPV zip file export

- docs/HISTORY.txt
- opengever/task/task.py
- opengever/task/tests/test_task.py
Hide the 'date of copletion'-field on tasks add-form.
closes #2450
> Hide 'Date of completion'-field on tasks add-form.

- docs/HISTORY.txt
- opengever/dossier/resources/edit_note.js
Removes unnecessary warning-hint after aborting the comments form.
Before:
After:
closes #2616
> Compare strings in the dossier-comments-overlay newline encoding insensitive.

- docs/HISTORY.txt
- opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
- opengever/document/browser/templates/file.pt
- opengever/document/static/officeconnector.js
- opengever/document/widgets/tooltip.pt
- opengever/officeconnector/configure.zcml
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api.py
- opengever/officeconnector/tests/test_templates.py
* New API endpoint behaviour for OfficeConnector URLs to stay under the 500 character limit
* New API endpoints for fetching action instructions per document UUID per OfficeConnector action
* 'OfficeConnector mock testing'
Fixes #2509
> Circumvent an IE11 security feature for OfficeConnector

- docs/HISTORY.txt
- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/console.py
- opengever/bundle/loader.py
- opengever/bundle/report.py
- opengever/bundle/sections/progress.py
- opengever/bundle/sections/report.py
- opengever/bundle/sections/resolveguid.py
- opengever/bundle/transmogrifier.zcml
- XLSX report: Include summary sheet containing **import duration, time of import and bundle name**
- OGGBundle pipeline:  Also write logs to a **dedicated migration log** in the working directory.
- OGGBundle pipeline: Add basic **progress logging**
- OGGBundle import: Add some additional logging to make it quicker to spot common mistakes (log **referring GUID** for 'MissingGUID` errors, and **JSON file name** during load)
@deiferni
> OGGBundle import: Improve logging and reporting

- docs/HISTORY.txt
- opengever/disposition/ech0160/model/folder.py
- opengever/disposition/tests/test_sippackage.py
Skip documents without a file when adding files to the schema during SIP generation, the document  without a file is still registered in the metadata.
Closes #2538
> Fix an error when creating a SIP export of documents without a file.

- docs/public/user-manual/glossary.rst
Zwei Beispiele, wie man TERMDAT als Quelle angeben kann.
> Verlinkungen auf TERMDAT hinzugefuegt (zwei Beispiele).

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/tests/test_constrain_type_decider.py
The `DefaultConstrainTypeDecider` used for dossiers used to have the maximum nesting levels hardcoded.
This change makes it determine these values dynamically from the according registry setting instead.
Also includes a **test that failed against the previous implementation**.
@deiferni
> DefaultConstrainTypeDecider: read max dossier nesting levels from registry

- docs/HISTORY.txt
- opengever/meeting/proposal.py
- opengever/meeting/tests/test_proposal.py
Fix updating the proposals attachements-list after submitting a new document.
Closes #2602
> Fix updating the proposals attachements-list after submitting a new document.

- docs/HISTORY.txt
- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/sections/disabled_indexing.py
- opengever/bundle/transmogrifier.zcml
Have reindexing only happen once per object instead at the end of the
pipeline.
@deiferni
> OGGBundle: Don't reindex during pipeline.

- opengever/dossier/templatefolder/tabs.py
Fixes #2598.
_CL should not be necessary_
> Use correct message factory import for dossier template table columns.

- opengever/officeconnector/tests/test_api.py
This circumvents unicode errors in zope.testbrowser that would happen
when concatenating ascii request body and the unicode request url that
is passed on as referer.
_This fixes the currently broken master ci builds._
> Make sure request url is always ascii.

- docs/HISTORY.txt
- opengever/disposition/disposition.py
- opengever/disposition/tests/test_destruction.py
- opengever/dossier/permissions.zcml
- opengever/dossier/profiles/default/workflows/opengever_dossier_workflow/definition.xml
- opengever/dossier/upgrades/20170301235934_add_new_destroy_dossier_permission/upgrade.py
Only Records Managers and Manager has the `Destroy  Dossier` permission and only on dossiers in the archived state.
Closes #1764
> Protect dossier destruction with a separate permission 'Destroy Dossier'.

- opengever/policy/base/profiles/default/registry.xml
- opengever/policy/base/upgrades/20170302092654_configure_tabbedview_etag_in_caching/registry.xml
- opengever/policy/base/upgrades/20170302092654_configure_tabbedview_etag_in_caching/upgrade.py
The tabbedview's defaulttab needs to be part of the cachekey so that the
cache gets flushed when the default tab is changed.
- https://github.com/4teamwork/ftw.tabbedview/pull/66
- https://github.com/4teamwork/kgs/commit/3a5cf996365b4621753a07625972470ae199f27b
> Caching: enable tabbedview etag value.

- docs/HISTORY.txt
- opengever/disposition/appraisal.py
- opengever/disposition/browser/overview.py
- opengever/disposition/browser/templates/overview.pt
- opengever/disposition/disposition.py
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- opengever/disposition/tests/test_appraisal.py
- opengever/disposition/tests/test_destruction.py
- opengever/disposition/tests/test_overview.py
- opengever/dossier/base.py
- opengever/dossier/deactivate.py
- opengever/dossier/tests/test_base.py
- opengever/dossier/tests/test_deactivate.py
- opengever/dossier/upgrades/20170228172522_set_end_date_for_inactive_dossiers/upgrade.py
- Set end date to current date when deactivating a dossier, including an upgradestep which set the end date for inactive dossiers.
- Pre appraisal: Handle inactive dossier always as not archival worthy.
- Display inactive dossiers in a separate listing on the disposition overview.
> Improve disposal of inactive dossiers

- docs/HISTORY.txt
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api.py
https://github.com/4teamwork/opengever.core/pull/2645
Support that OC-side and also forwards-support the thing that is a quick fix for.
> Scaffold OC payloads for future-proof in regards of direct file uploads via plone.api

- docs/HISTORY.txt
This PR uses the new ftw.keywordwidget version 1.1.2 to fix an ie11 issue.
See https://github.com/4teamwork/ftw.keywordwidget/pull/6 for more information.
Before:
After:
> Update ftw.keywordwidget from 1.1.1 to 1.1.2 to fix an ie11 issue.

- docs/HISTORY.txt
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api.py
* Better readability
* Better reflect what OC actually does
* Also sneak in an usability / user expectation matching improvement to the OC payload
> Cleanup OC API tests

- docs/HISTORY.txt
- opengever/dossier/behaviors/dossier.py
- opengever/dossier/indexers.py
- opengever/dossier/tests/test_indexer.py
- opengever/dossier/upgrades/20170307184059_reindex_searchable_text_for_dossier_templates/upgrade.py
With this PR keywords of dossiers and dossiertemplates are appended to searchable text and thus one can search for dossiers and dossiertemplates based on their keywords.
Fixes #2606.
> Make keywords searchable

- opengever/dossier/tests/test_dossier_template.py
We don't care about order, and this broke/changed with the latest `ftw.keywordwidget` release.
> Fix broken tests on master.

- opengever/mail/upgrades/20170308184726_set_correct_message_content_type_for_drag_drop_uploaded_mails/upgrade.py
Make MSG content type upgrade step more defensive: Some brains in production didn't have the `getContentType` metadata attribute. Those are fishy and deserve no better than to get reindexed.
> Make MSG content type upgrade step more defensive

- docs/HISTORY.txt
- opengever/dossier/indexers.py
Make containing_dossier indexer more defensive in order to account for an odd corner case during upgrades:
During upgrades, the odd case can happen that a mail inside a forwarding inside the inbox wants to have its `containing_dossier` reindexed. This can lead to a situation where we attempt to adapt the `Inbox` to `ITranslatedTitle`, but it doesn't provide this behavior yet because that behavior is going to be actived in the very same upgrade.
Account for this case, and fall back to `inbox.title`, which will contain the original title (in unicode though).
> Make containing_dossier indexer more defensive

- docs/HISTORY.txt
- opengever/ogds/base/sync/ldap_util.py
LDAP util: Skip LDAP referrals that are supposed to be hunted down by client-chasing. We don't support these, and can simply skip them.
> LDAP util: Skip referrals that are supposed to be hunted by client-chasing

- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/sections/post_processing.py
OGGBundle pipeline: Tune savepoint and intermediate commit settings to be more appropriate for medium sized imports.
> OGGBundle pipeline: Tune savepoint and intermediate commit settings

- docs/HISTORY.txt
- opengever/bundle/cfgs/oggbundle.cfg
- opengever/bundle/sections/map_principals.py
- opengever/bundle/transmogrifier.zcml
OGGBundle: Add support to map local role principal names during import based on ingestion settings. This is necessary in order to handle mapping -LS to -GS groups during OSLW import.
> OGGBundle: Add support to map local role principal names during import

- docs/HISTORY.txt
- opengever/mail/browser/extract_attachments.py
- opengever/tabbedview/browser/tasklisting.py
This PR adds missing table-column width.
Before:
After:
closes #2529
> Fix missing table-column width for checkbox rows.

- docs/HISTORY.txt
- opengever/disposition/browser/templates/overview.pt
- opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
- opengever/disposition/locales/opengever.disposition.pot
- Fixed tooltip for the appraisal buttons (closes #2704)
- Removed colon on progress subtitle and improved styling of details section in disposition progress (closes #2680)
- Hide subtitles (active or inactive dossiers) when list is empty (closes #2674)
- Change color of add answer from green to black (closes #2707)
- Use carets instead of plus/minus as collabsible triggers in disposition progress. (closes #2678)
Styling adjustments: https://github.com/4teamwork/plonetheme.teamraum/pull/517
> Disposition overview improvments

- docs/HISTORY.txt
- opengever/base/redirector.py
- opengever/document/checkout/checkout.py
- opengever/officeconnector/helpers.py
- opengever/officeconnector/service.py
* Amend the OfficeConnector `plone.rest` URL services to allow one to init them in ~any `BrowserView`
* Amend the redirector to issue out an OC URL in case of the OC URL checkout feature being enabled
* Amend the JS redirector to handle `oc:foobar` URLs
Considerations:
* Diving deep into portal site_actions would not have squashed #2696
* Not amending the JS redirector trips up the popup blocker on Chrome
* Could avoid the JSON parsing within the redirector, but did not want to break up the service logic
Fixes #2689 
Fixes #2696
> Amend the JS redirector mechanism to support OC URLs

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
- opengever/dossier/behaviors.zcml
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/dossier/dossiertemplate/form.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_restricted_addable_dossiertemplate.py
- opengever/repository/profiles/default/types/opengever.repository.repositoryfolder.xml
- opengever/repository/upgrades/20170306132837_add_i_addable_dossier_templates_to_repositoryfolders/types/opengever.repository.repositoryfolder.xml
- opengever/repository/upgrades/20170306132837_add_i_addable_dossier_templates_to_repositoryfolders/upgrade.py
Adds an additional behavior IAddableDossierTemplates with a RelationList field to repositoryfolders.
If the `addable_dossier_templates` is filled, the selectable templates are restricted otherwise not.
Closes #2625
> Add restriction possibility for dossier templates

- docs/HISTORY.txt
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api.py
* Add the byline email of the parent dossier of a document as a BCC field to OfficeConnector email attach action payloads when said dossier is open.
Implements #2724
> BCC dossier byline when attaching a document to emails via OC if dossier is open

- docs/HISTORY.txt
- opengever/tasktemplates/browser/tasktemplates.py
- opengever/tasktemplates/browser/templatefolders.py
Dieser PR entfernt die nicht mehr benötigte Draggable-Spalte für Tasktemplates.
Siehe #2726 für mehr Informationen
closes #2726
> Remove unused tasktemplate table draggable column.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/browser/overview.py
- opengever/dossier/tests/test_base.py
- opengever/private/tests/test_dossier.py
Hide newest tasks box for private dossiers overview tabbedview view because it's not possible to add tasks in private dossiers.
Before:
After:
closes #2730
> Hide newest tasks box for private dossiers overview tabbedview view.

- opengever/private/tests/__init__.py
- opengever/private/upgrades/20170308172109_install_private_dossier_quota/upgrade.py
- opengever/private/upgrades/20170314200202_fix_private_folder_usage_calculation/upgrade.py
- opengever/quota/sizequota.py
- opengever/quota/tests/test_quota_container.py
Fixes two problems in the quota usage recalculation method:
1. The usage was calculated for all documents on the site, but it should only be calculated for the documents within the quota container.
2. By clearing the usage map before recalculating we make sure that objects, which are no longer there, are no longer counted.
> Fix quota usage recalculation to count correctly.

- opengever/base/browser/templates/gever-macros.pt
- opengever/dossier/browser/overview.py
- opengever/dossier/browser/save_comments_entpoint.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/resources/edit_note.js
- opengever/dossier/tests/test_dossier_byline.py
- opengever/dossier/tests/test_overview.py
- opengever/dossier/utils.py
- opengever/dossier/viewlets/byline.py
- opengever/dossier/viewlets/comment.py
- opengever/dossier/viewlets/configure.zcml
- opengever/dossier/viewlets/templates/note.pt
- opengever/meeting/configure.zcml
- opengever/private/tests/test_dossier.py
Styles in https://github.com/4teamwork/plonetheme.teamraum/pull/518
Display a sticky note icon next to the title and an edit link if there is a comment:
Display an add link in the overview if there is no comment yet:
Follow-up for https://github.com/4teamwork/opengever.core/pull/2695.
> Move "Aktenotiz" out of the byline, add icon next to title and display text in overview

- docs/HISTORY.txt
- opengever/private/browser/tabbed.py
- opengever/private/tests/test_dossier.py
Some document tab columns are not important in the context of private dossiers, therefore we hide them in the default configuration.
Closes #2736
> hide columns from private dossier documents.

- docs/HISTORY.txt
- opengever/dossier/dossiertemplate/behaviors.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/tests/test_dossier_template.py
Fügt die Beschreibung der `predefined_keywords` und `restrcit_keywords` Felder hinzu.
closes #2749
> Add description for predefined_keywords and restrcit_keywords fields

- docs/HISTORY.txt
- opengever/document/archival_file.py
- opengever/document/tests/test_archival_file.py
- opengever/document/upgrades/20170317095333_fix_contentypes_encoding_for_archival_files/upgrade.py
The content type of the archival_file, automatically generated by Bumblebee, was added by with a wrong contenttype encoding (unicode instead of utf-8). This lead to an ValidationError when editing the document.
Closes #2698
> Fixed content type encoding for archival files

- docs/HISTORY.txt
- opengever/dossier/behaviors/dossier.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
Dieser PR fixt die Übersetzung des Common-Tabs:
Vorher: 
Nachher:
see #2402
> Fix tabbs in templatedossier add and edit forms

- development.cfg
The format-xml scripts were removed from default plone development in https://github.com/4teamwork/ftw-buildouts/pull/74 because I hate buildout.
This re-adds the scripts for GEVER.
> Development: re-add format-xml scripts.

- docs/HISTORY.txt
- opengever/base/tests/test_widget.py
- opengever/base/widgets.py
This PR escapes the dynamic_description field for the textfield-widget.
> Escape dossiertemplate title_help field on display.

- docs/HISTORY.txt
- opengever/dossier/indexers.py
- opengever/private/tests/test_dossier.py
Allow private dossiers to be resolved:
They don't have the `ILifeCycle` behavior, and therefore no retention period. Therefore we skip the calculation of the retention_expiration for private dosssiers
in the respective indexer.
> Allow private dossiers to be resolved

- docs/HISTORY.txt
- opengever/mail/browser/extract_attachments.py
Gets rid of a column header that isn't supposed to be shown. Apparently, in a recent version `ftw.tabbedview` falls back to the column ID if the `column_title` is falsy. 
**Before**:
**After**:
> Get rid of unnecessary column label in extract attachments view.

- docs/HISTORY.txt
- opengever/latex/tasklisting.py
Task listing PDF: Use AdminUnit abbreviation instead of title in order to avoid nasty overflows caused by long admin unit titles.
**Before:**
**After:**
> Task listing PDF: Use AdminUnit abbreviation instead of title

- docs/HISTORY.txt
- opengever/dossier/templatefolder/templatefolder.py
- opengever/dossier/tests/test_templatefolder.py
This PR prefills the responsible field with the current logged in user as it is already implemented in a dossier.
closes #2770
> Prefill responsible user for templatefolders.

- opengever/activity/tests/test_listing.py
- opengever/bundle/tests/test_business_rule_violations.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/core/testing.py
- opengever/inbox/tests/test_overview.py
- opengever/meeting/tests/test_agendaitem_list.py
- opengever/meeting/tests/test_members.py
- opengever/meeting/tests/test_protocol.py
- opengever/meeting/tests/test_protocol_json_data.py
- sources.cfg
Change the setup of the sqlite database and the connection to the builder.
These changes make the sql builders actually commit instead of just flushing the session.
The ability to actually commit is important in order to move towards testing with PostgreSQL.
> Testing A1: Refactor sqlite testing setup

- sources.cfg
Switch `opengever.ogds.models` back to master after merging 4teamwork/opengever.ogds.models#45.
> Switch og.ogds.models back to master

- docs/HISTORY.txt
- opengever/base/subscribers.py
- opengever/bundle/sections/post_processing.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/document/subscribers.py
- opengever/document/tests/test_document.py
Currently initial versions are created when:
- any dexterity content is copied/pasted (strangely also for e.g. dossiers that don't have the `IVersionable` behavior)
- mails are loaded from the ogg-bundle pipeline
This PR limits creating initial versions to documents only since afaik that was the way it is intended and exposed in theUI.
Open questions: what happens to data in `portal_repository`. should we attempt to cleanup version data stored there for non-dossiers.
> Don't create initial versions for mails (or other content)

- docs/HISTORY.txt
- opengever/document/browser/overview.py
- opengever/document/document.py
- opengever/document/tests/test_document_tooltip.py
- opengever/document/widgets/tooltip.py
Make sure checkout link on document tooltip is only displayed for editable documents (e.g., not on documents in resolved dossiers).
Done by moving the `is_checkout_and_edit_available()` method to the `Document` class.
> Make sure checkout link on document tooltip is only displayed for editable documents

- docs/HISTORY.txt
- opengever/base/browser/resources/tooltip.js
* Make sure qtip tooltips are removed from the DOM on hide on IE11.
Fixes #2786
> Make sure qtip tooltips are destroyed on hide.

- opengever/bumblebee/browser/overlay.py
> Add missing icon to download copy link for mails.

- docs/HISTORY.txt
- opengever/document/upgrades/20170317095333_fix_contentypes_encoding_for_archival_files/upgrade.py
It may be run when the specified registry record is not available yet.
> Make contenttype fix more robust.

- opengever/core/sqlite_testing.py
- opengever/core/testing.py
*~~Rebase and change target branch when #2745 (`Testing 1: Refactor sqlite testing setup.`) is merged.~~*
In preparation for moving slowly towards PostegreSQL, this change extracts the SQLite setup into a separate layer.
This is already prepared to be set up the same way as PostgreSQL will be.
Because of the order of execution, the `OpengeverFixture` now needs to be initialized with an sql fixture, which allows us to initialize the database after loading some ZCML but before setting up the Plone site.
> Testing A2: extract sqlite testing setup into separate module and layer

- docs/HISTORY.txt
- opengever/meeting/model/meeting.py
- opengever/meeting/model/member.py
- opengever/meeting/tests/test_locking.py
Dieser PR verwendet die `SQLFormSupport`-Klasse (siehe PR: #2012) für alle restlichen SQL-Basierten Typen welche Formulare verwenden.
Gewisse Typen wurden schon früher angepasst (siehe https://github.com/4teamwork/opengever.core/commit/5e21228).
closes #2028
> Use SQLFormSupport class

- opengever/core/testing.py
There is no need to tear down persistent objects as long as the database isolation works.
I would like to remove all teardown code because it will make the move towards PostgreSQL smoother.
> Testing B1: do not tear down, isolate.

- opengever/core/testing.py
The policies base the tests on the `OPENGEVER_FIXTURE`.
Renaming it to `OPENGEVER_FIXTURE_SQLITE` caused policy tests to fail.
For new we just redefine `OPENGEVER_FIXTURE` and use the sqlite version (as there is no other yet).
We may refactor this later.
> Fix policy tests

- docs/HISTORY.txt
- opengever/document/behaviors/metadata.py
- opengever/document/indexers.py
- opengever/document/tests/test_document.py
- opengever/document/tests/test_indexers.py
- opengever/document/upgrades/20170321120536_enable_ftw_keywordwidget_for_document_metadata_behavior/upgrade.py
- opengever/mail/indexer.py
- opengever/mail/tests/test_indexers.py
- opengever/mail/tests/test_mail.py
- opengever/meeting/tests/test_indexers.py
- opengever/meeting/tests/test_sablon_template.py
This PR enables the keywordwidget for the IDocumentMetadata behavior.
It concerns the following portal-types:
- Document
- Mail
- SablonTemplate
close #2600
> Enable keywordswidget for IDocumentMetadata behavior.

- docs/HISTORY.txt
- opengever/tabbedview/browser/users.py
- opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
- opengever/tabbedview/locales/opengever.tabbedview-manual.pot
- opengever/tabbedview/locales/opengever.tabbedview.pot
- opengever/tabbedview/tests/test_user_listing.py
Add an `active` and `all` filter to ogds user listings. `Active` is the default filter, it displays only users that are marked as `active` in ogds.
Closes #2807.
> Add state filters to ogds user listings.

- docs/HISTORY.txt
- opengever/base/command.py
- opengever/base/tests/test_command.py
This PR fixes an UnicodeDecodeError while uploading a .msg file with an umlaut in the filename to a dossier.
closes #2775
> Fix UnicodeDecodeError if uploading a .msg email with an umlaut in the filename to a dossier.

- docs/HISTORY.txt
- opengever/portlets/tree/resources/init_tree.js
- sources.cfg
Closes https://github.com/4teamwork/opengever.core/issues/2722
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/525
The height calculation using javascript on every pageresize is very
expensive and buggy. So use the native CSS `calc` function and relative `vh` unit
to limit the height of the tree portlet.
> Fix max-height of tree portlet.

- docs/HISTORY.txt
- opengever/base/tests/test_default_values_for_types.py
- opengever/meeting/menu.py
- opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
- opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
- opengever/repository/locales/opengever.repository.pot
- opengever/repository/menu.py
- opengever/repository/repositoryfolder.py
- opengever/repository/tests/test_menu.py
Adds a new checkbox on a repository-folder to choose if a user is allowed to add custom businesscase-dossiers or not.
closes #2808
> Adds checkbox on repo-folder to define if a businesscasedossier is allowed to add or not.

- opengever/document/base.py
- opengever/document/document.py
By extracting the icon-by-mimetype functionality from the document FTI class into the BaseDocumentMixin, we make it possible to reuse it in other documentish types.
Because of the inheritance order we still need to define "getIcon" and "icon" at the FTI class.
This change adds new methods to the mail FTI class, but these methods are not used. The getIcon method of the mail FTI is not changed.
> Refactoring: extract icon functionality into document base.

- opengever/meeting/__init__.py
When catching two exceptions, they must be in a tuple, otherwise the second is the variable name holding the exception of the first type.
> fix invalid exception catching in meeting feature.

- opengever/document/upgrades/20170321120536_enable_ftw_keywordwidget_for_document_metadata_behavior/upgrade.py
This PR ensures that keywords are enocded as `utf-8` before being reindexed.
At the Moment `ftw.keywordwidget` stores the keywords as `utf-8`, this seems to be required by `plone.app.vocabularies.Keywords`. Previous document keywords are stored as `unicode`, however. They keywords-vocabulary is global and shared by documents and dossiers. Thus when executing this upgrade step there will be issues with already stored dossier keywords when reindexing as you cannot mix `utf-8` and `unicode` in a `KeywordIndex`.
> Convert existing keywords to utf-8 first before upgrading.

- docs/HISTORY.txt
- opengever/meeting/__init__.py
- opengever/meeting/interfaces.py
- opengever/meeting/upgrades/20170407092308_add_word_implementation_feature_flag/registry.xml
- opengever/meeting/upgrades/20170407092308_add_word_implementation_feature_flag/upgrade.py
Part of #2829
The new feature flag "Word implementation" is used for switching the meeting implemetation to the new Word implementation.
The new word implementation allows to write protocols directly in word.
In order to develop it in parallel it needs to be feature flag.
When enabling the Word implementation feature flag no meeting objects
should exist, otherwise they migth lack a proper migration at this point.
> Meeting: add a "Word implementation" feature flag.

- docs/HISTORY.txt
- opengever/latex/dossiercover.py
- opengever/latex/opentaskreport.py
- opengever/latex/tasklisting.py
Make (all) PDF views customizable by having them dynamically provide their request layers instead of hardcoding them. That way, `self.request_layer` can be overridden in subclasses and the customized view can provide a more specific request layer interface.
> Make (all) PDF views customizable by having them dynamically provide request layers

- docs/HISTORY.txt
- opengever/latex/dossierjournal.py
- opengever/latex/listing.py
- opengever/latex/tests/test_dossierjournal.py
- opengever/latex/tests/test_listing.py
The comment of an `Document Sent` entry contains the attachment links in HTML and the complete mail text which makes no sense to include in the pdf journal listing.
Fixes #2839
Sentry: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/2871
> Skip comment for Document Sent entries in the dossiers journal pdf representation

- docs/HISTORY.txt
- opengever/disposition/browser/configure.zcml
- opengever/disposition/browser/overview.py
- opengever/disposition/browser/templates/overview.pt
- opengever/disposition/profiles/default/types/opengever.disposition.disposition.xml
- opengever/disposition/tests/test_history.py
- opengever/disposition/tests/test_overview.py
- opengever/disposition/upgrades/20170405075741_replace_tabbedview_overview_with_simple_overview_view/types/opengever.disposition.disposition.xml
- opengever/disposition/upgrades/20170405075741_replace_tabbedview_overview_with_simple_overview_view/upgrade.py
The disposition tabbedview has currently only one tab, the "overview" tab. Because there are no other tabs planned, it makes sense to drop the tabbedview and replace it with a simple browserview. The content of the overview is not changed.
Needs styling PR: https://github.com/4teamwork/plonetheme.teamraum/pull/538
Closes #2691
> Replaced disposition tabbedview with a simple browserview.

- docs/HISTORY.txt
- opengever/core/testing.py
- opengever/mail/tests/test_senddocument.py
- opengever/ogds/base/tests/test_ogds_updater.py
- opengever/repository/behaviors/configure.zcml
- opengever/repository/behaviors/referenceprefix.py
- opengever/repository/tests/test_reference_behavior.py
- opengever/sharing/tests/test_sharing_integration.py
- opengever/testing/event_recorder.py
Use the component registry isolation layer as base layer.
This isolates the component registries between tests.
This allows us to just register new components (adapters, utilities, event subscribers) without unregistering them in tear down.
The layer also provides a `load_zcml_string` method, which can be used
for loading a chunk of ZCML in the test:
```python
def test(self):
self.layer['load_zcml_string']('<configure>...</configure>')
```
Layer documentation: https://github.com/4teamwork/ftw.testing#component-registry-isolation-layer
Layer implementation: https://github.com/4teamwork/ftw.testing/blob/fd0f2c4ffe25b9680cffab81a4fa8fc0b01aabcd/ftw/testing/layer.py#L70-L92
Argumentation:
- We can awoid that tests leak components into next tests.
- It makes it easy to run postgres and sqlite …
> Isolate component registry between tests

- opengever/base/upgrades/20170207162749_enable_ftw_keywordwidget_and_index_keywords_of_dossiers/upgrade.py
- opengever/base/upgrades/20170411113233_fix_subject_index__use_unicode_consistently/upgrade.py
- opengever/document/behaviors/metadata.py
- opengever/document/upgrades/20170321120536_enable_ftw_keywordwidget_for_document_metadata_behavior/upgrade.py
- opengever/dossier/behaviors/dossier.py
- sources.cfg
This PR makes sure that keywords use unicode consistenlty.
When switching from `LinesWidget` to `KeywordWidget` we also changed how the values are stored on the field, the first one stored it as `unicode` whereas `ftw.keywordwidget` always persited the field values as `utf-8`. After some discussion we've decided to make `unicode`/`utf-8` terms customizable in `ftw.keywordwidget`, this has been implemented in https://github.com/4teamwork/ftw.keywordwidget/pull/13. That PR also contains a detailed description of our discussion/decisions.
This PR now makes sure that keywords are always stored as unicode, in objects and in the catalog. This purposefully breaks Plone's convention of usually `utf-8` catalog values.
Fixes #2823.
> Make sure keywords are unicode consistently.

- docs/HISTORY.txt
- opengever/base/subscribers.py
Also whitelist 'customlogoright' for unauthenticated access (introduced in 4teamwork/plonetheme.teamraum#535.)
/cc @bierik
> Also whitelist 'customlogoright' for unauthenticated access

- docs/HISTORY.txt
- opengever/bundle/console.py
This change let the request during the bundle import provide the `IOpengeverBaseLayer`.
This is necessary because only the `GeverBumblebeeService` respects the bumblebee feature flag and does not trigger conversion requests, when the flag is disabled. The `GeverBumblebeeService` is a GEVER specific customization registered on the IOpengeverBaseLayer request layer, which is not be provided by default in an zope_ctl script.
> Make sure GEVER customizations works during bundle import

- docs/HISTORY.txt
- opengever/bundle/sections/post_processing.py
This commit was triggered was too early (at the very beginning of the pipeline, because of how Transmogrifier works), and may have been related to sporadic conflict errors, among other things.
> Bundle import: Don't commit "before post-processing"

- opengever/journal/handlers.py
- opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
- opengever/journal/locales/opengever.journal.pot
- opengever/journal/tests/test_attach_journal_entry.py
- opengever/officeconnector/tests/test_api.py
Add a journal entry to a document's dossier whenever attaching a document to a mail. Currently an individual entry will be created for each attached document since they will be downloaded separately (i.e. in separate requests) by OfficeConnector.
Closes #2806.
> Also create journal entries on dossier level when attaching.

- docs/HISTORY.txt
- opengever/task/browser/complete.py
This PR fixes get-prefill after the Products.PloneHotfix20160830 for CompleteSuccessorTaskForm.
closes #2857
> Fixes get-prefill after the Products.PloneHotfix20160830 for CompleteSuccessorTaskForm.

- docs/HISTORY.txt
- opengever/base/interfaces.py
- opengever/base/sequence.py
- opengever/bundle/console.py
OGGBundle import: Don't use separate ZODB connection to issue sequence numbers  in order to avoid conflict errors (when writing to the Plone site root annotations).
I chose to introduce a new request interface `INoSeparateConnectionForSequenceNumbers` to specifically flag this behavior, instead of abusing the `IDuringSetup` one (since OGGBundle import isn't setup, and what happens as a cause of `IDuringSetup could change at any point).
> OGGBundle import: Don't use separate ZODB connection to issue sequence numbers

- docs/HISTORY.txt
- opengever/bundle/ldap.py
Make sure persistent changes that re-enable LDAP are always committed, so we don't end up with a broken plugin registry.
> OGGBundle import: Make sure persistent changes that re-enable LDAP are always committed.

- opengever/base/sequence.py
Fix site setup after introducing `INoSeparateConnectionForSequenceNumbers` request interface:
Request interface needs to be checked with `iface.providedBy()`, not by attempting to adapt the request.
> Fix site setup after introducing INoSeparateConnectionForSequenceNumbers

- docs/HISTORY.txt
- opengever/latex/layouts/default.py
- opengever/latex/templates/dossierdetails.tex
- opengever/latex/tests/test_default_layout.py
Dossierdetails PDF: Fix indentation of dossier metadata table (make it left aligned with heading and the rest of the document).
---
---
[dossierdetails_before.pdf](https://github.com/4teamwork/opengever.core/files/954146/dossierdetails_before.pdf)
[dossierdetails_after.pdf](https://github.com/4teamwork/opengever.core/files/954147/dossierdetails_after.pdf)
> Dossierdetails PDF: Fix indentation of dossier metadata table.

- opengever/testing/builders/dx.py
When the checked out state of a document is switched, the checked_out index must be updated.
But it is not necessary to update all indexes.
> testing builders: make reindexing more efficient.

- docs/HISTORY.txt
- opengever/document/profiles/default/actions.xml
- opengever/document/upgrades/20170424163920_adjust_sort_order_of_actions/actions.xml
- opengever/document/upgrades/20170424163920_adjust_sort_order_of_actions/upgrade.py
- opengever/officeconnector/tests/test_templates.py
> Move the attach to email action to second position, after the copy action

- docs/HISTORY.txt
- opengever/officeconnector/configure.zcml
- opengever/officeconnector/helpers.py
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api.py
Currently attaching mails failed because the attach functionality directly accessed the file with `document.file` but the mail file attribute is named `message`. To solve this issues I consequently used the `get_file`, `has_file` methods  from the `BaseDocumentMixin` and register the services for the IBaseDocument interface.
> Fixed attaching mails via document listing to oc.

- opengever/mail/tests/test_mail_overviewtab.py
If preconditions for the `test_mail_overview_tab` test are different than what we expect them to be, we print this debugging output which should end up in the Jenkins build log:
```
view.is_preview_supported() is unexpectedly False!
is_pdfconverter_enabled(): True
pkg_resources.get_distribution('opengever.pdfconverter'): opengever.pdfconverter 1.5.0 (/Users/lukasgraf/Plone/eggs/opengever.pdfconverter-1.5.0-py2.7.egg)
is_bumblebee_feature_enabled(): False
```
> Tests: Add debugging output to debug flaky tests on Jenkins.

- bin/mtest
The `BufferedPrinter` threads were using 100% CPU in a busy loop situation. Adding a 200ms sleep to each of their business logic brings this down to sensibility and reading from the disk only every 200ms is a touch more sensible in any case.
We could even go as far as to consider bumping this up to multiple seconds, but 200ms preserves local interactivity on a human scale rather nicely for local test runs.
> Reduce mtest CPU use

- docs/HISTORY.txt
- opengever/dossier/browser/tabbed.py
- opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/dossier/locales/opengever.dossier.pot
- opengever/dossier/templatefolder/tabs.py
- opengever/dossier/tests/test_templatefolder.py
- opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
- opengever/meeting/locales/opengever.meeting.pot
- opengever/testing/builders/dx.py
Im Vorlageordner wird ein neues Tab "Antragsvorlagen" hinzugefügt, welches die Antragsvorlagen (#2834) in diesem Vorlageordner anzeigen.
Das Tab verhält sich genau gleich wie das Tab für Sablon-Vorlagen: gewisse Spalten und Aktionen des normalen Dokumente-Tabs stehen werden entfernt.
Dies ist Teil des Auftrags #2829.
> Meeting: Tab für Antragsvorlagen in Vorlageordner

- docs/HISTORY.txt
- opengever/portlets/tree/resources/init_tree.js
> Fix sortorder of repository favorites in the treeportlet.

- docs/HISTORY.txt
- opengever/base/viewlets/colorization.py
This allows to use a different color, than on of the existing schema (red, yellow, green).
For example lab deployment: https://github.com/4teamwork/opengever.demo/blob/master/deployment-theta-17-lab.onegovgever.ch.cfg#L22
> Support simple css colornames in the colorization viewlet.

- docs/HISTORY.txt
- opengever/dossier/dossiertemplate/form.py
- sources.cfg
Issue:
By running the `update` method on the widget, the content of variable `js_config` was converted from a dict to a JSON string. 
This behavior is IMHO bad, since the update method should not change the type of the value.
This was fixed with the latest change in ftw.keywordwidget.
`config_json` now always holds JSON. and `js_config` is always a dict.
This reimplements support for the latest ftw.keywordwidget.
Fixes #2886
> Fix manipulating the tag config of the keywordwidget in the dossier template form

- docs/HISTORY.txt
- opengever/document/forms.py
- opengever/document/tests/test_forms.py
- opengever/dossier/events.py
- opengever/dossier/interfaces.py
- opengever/journal/configure.zcml
- opengever/journal/handlers.py
- opengever/journal/tests/test_attach_journal_entry.py
- opengever/officeconnector/configure.zcml
- opengever/officeconnector/helpers.py
- opengever/officeconnector/service.py
- opengever/officeconnector/tests/test_api.py
* Port OC payload fetches into POSTs to enable less requests per multiattach cycle
* Clump OC document attach dossier journal entries per dossier per event
* Amend the tests
Closes #2873
> Clump OC document attach dossier journal entries per dossier per event

- opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
- opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
- opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
These translations have already been used for message strings in other domains with the exact same ID, and they should be generic enough not to be context dependent.
> i18n: Use some existing translations for message strings that can use the same translation.

- docs/HISTORY.txt
- opengever/dossier/browser/tabbed.py
This PR adds the missing trash-tab in the template-folder:
closes #2881
> Add trash-tab in template folder.

- opengever/meeting/browser/proposalforms.py
I believe the submited propsal edit form should have the content type class `SubmittedProposal`, not `Proposal`.
⚠️ I have no idea if this is on purpose or by accident, nor can I asses the impact of this ching. It just struck me as odd.
> submitted proposal edit form: fix wrong class.

- docs/HISTORY.txt
- opengever/inbox/browser/refuse.py
This PR fixes the issue, where it wasn't possible to refuse a multi-adminunit forwarding.
closes #2877
> Fix refusing a multi-adminunit forwarding.

- docs/HISTORY.txt
- opengever/task/locales/de/LC_MESSAGES/opengever.task.po
- opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
- opengever/task/locales/opengever.task.pot
- opengever/task/task.py
According to https://basecamp.com/2768704/projects/12554551/todos/303789045
French translation intentionally marked as **fuzzy** because message semantics changed, and the french translation needs to be reviewed.
> Improve help text for task responsible selection.

- docs/HISTORY.txt
- opengever/base/skins/opengever.base_scripts/require_login.py
- opengever/base/tests/test_require_login.py
- opengever/base/tests/views/configure.zcml
- opengever/base/tests/views/unauthorized.py
The require_login script was customized in order to support MS Office
probing, which happens without the session (cookies).
The old implementation had issues:
- When the request had a payload, such as a POST request, the payload
did not survive the redirect. When a ++add++ could be rendered but not
posted, this caused the form to reload empty without an error.
- When the unauthorized exception did not happen during traversal but
during publishing a redirect loop was created.
In order to fix this issues I rewrote the require_login script to be
more robust.
- No longer redirect when the request method is not GET.
- When redirecting, add a marker GET parameter for detecting loopbacks
and breaking redirect loops.
- No longer catch all exceptions; catch only the Unauthorized exception.
- …
> Avoid unauthorized redirect loops

- docs/HISTORY.txt
- opengever/base/pdfconverter.py
- opengever/core/testing.py
- opengever/document/tests/test_document_tooltip.py
- opengever/document/tests/test_versions_tab.py
Previously, the `PDFCONVERTER_AVAILABLE` flag was being monkey patched in tests without being reset properly.
In one case, it was being "reset" to `False` in a hardcoded way. This was the default until we added `opengever.pdfconverter` as a test dependency. From that point on, the flag was being reset to an incorrect default value. However, this only started to flare up in tests once we shuffled around their execution order with parallelization improvements to `bin/mtest`.
> Tests: Manage monkey patching of PDFCONVERTER_AVAILABLE through a context manager

- opengever/document/browser/templates/macros.pt
- opengever/document/static/officeconnector.js
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/549
Closes https://github.com/4teamwork/opengever.core/issues/2876
In order to give the user a feedback poll the document state to determine
if the office connector has completely loaded.
> Improve UX for office connector interactions.

- opengever/core/testing.py
Some policy packages setup the OpengeverFixture with additional bases. The OpengeverFixture must therefore support the keyword arguments "bases" and "name" in order to support rebasing the fixture.
> Testing: allow rebasing of OpengeverFixture.

- docs/HISTORY.txt
- setup.py
The use of ftw.treeview has been dropped during the portlet rework in #476, and this change is deployed on every productive deployment. So the ftw.treeview dependency can be dropped completely.
Closes #2452
> Remove no longer used ftw.treeview dependency.

- docs/HISTORY.txt
- opengever/task/response_syncer/workflow.py
- opengever/task/tests/test_response_syncer.py
Workflow changes should never be synced to a forwarding predecessor, because a forwarding predecessor is always closed and stored in a yearfolder. The forwarding has been already ignored by syncing, but the special handling has been removed by mistake during the rework PR #2828.
This fixes an `Forbidden` exception when trying to reassign a task, which has been created while assigning a forwarding to a dossier.
Closes #2912
> Do not sync task workflow changes to forwarding predecessors.

- docs/HISTORY.txt
- opengever/base/configure.zcml
Currently it seems to work only by coincidence, now we make sure that `plone.rest` `service` directive is loaded when it is being used.
> Ensure plone.rest directives are loaded.

- versions.cfg
Remove the ftw.testbrowser from the versions.cfg since it was added to opengever/develop.
https://github.com/4teamwork/kgs/pull/100
Lets only have it pinned once.
> Move ftw.testbrowser pinning to opengever/develop.

- docs/HISTORY.txt
- opengever/mail/browser/mail.py
- opengever/mail/browser/send_document.py
- opengever/mail/browser/templates/attachments.pt
- opengever/mail/browser/templates/previewtab.pt
- opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/opengever.mail.pot
- opengever/mail/tests/test_mail_overviewtab.py
- opengever/mail/tests/test_ogmail.py
- opengever/mail/tests/test_subscribers.py
* Minor cleanups on everything inspected during the process
* Added an extra row with an accompanying template to the mail overview
* Broke out the attachments listing functionality into a mixin
* Amended the tests
Closes #437
> Display attachments on mail overviews

- docs/HISTORY.txt
- opengever/repository/configure.zcml
- opengever/repository/constrains.py
- opengever/repository/repositoryfolder.py
Implement an IConstrainTypes adapter to restrict addable types in repository
folders instead of overwriting the allowedContentTypes method in the content
type. This way the constrains are also checked in API calls (e.g. invokeFactory).
Fixes #2303
> Fix addable types constrain for repository folders for API calls

- docs/HISTORY.txt
- opengever/dossier/indexers.py
- opengever/dossier/tests/test_indexer.py
This will fix some customer policy tests too.
> Fix typo in dossier SearchableTextExtender, which results in a empty SearchableText if IFilingNumber behavior was activated.

- docs/HISTORY.txt
- opengever/repository/constrains.py
`allowedContentTypes()` is called three times per request. Thus it makes sense to cache it.
> Cache addable types constrains for repository folders per request

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/tests/test_base.py
Changing `maximum_dossier_depth` is now implemented in the `DefaultConstrainTypeDecider`. 
The value is used for:
- opengever.dossier.businesscasedossier
- opengever.private.dossier
I slightly change the signature of the  adapter. CONSTRAIN_CONFIGURATION is no longer a `constant`, since it now depends on a configurable value. This may break customer integration of this adapter.
I also had to change the default value of `maximum_dossier_depth` from 1 to 2, since most of the tests depend on 2 levels.
Closes #955
>  Respect `maximum_dossier_depth` registry record in DefaultConstrainTypeDecider

- bin/mtest
Our CI has a suitable python3.4 available.
The output can be tuned later, but for pragmatic reasons I'll fast track this in right now.
The magic is in how to informedly split the modules across workers.
Tests now complete in 12 minutes.
https://ci.4teamwork.ch/builds/83351/tasks/120993
> Port mtest to use concurrent.futures from python3

- docs/HISTORY.txt
- opengever/base/command.py
- opengever/base/quickupload.py
- opengever/base/tests/test_command.py
- opengever/base/tests/test_default_values_for_types.py
- opengever/mail/browser/mail.py
- opengever/mail/create.py
- opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
- opengever/mail/locales/opengever.mail.pot
- opengever/mail/mail.py
- opengever/mail/tests/test_inbound.py
- opengever/mail/tests/test_mail_metadata.py
- opengever/mail/tests/test_mail_overviewtab.py
- opengever/testing/builders/dx.py
With this PR we will keep the original *.msg file after converting it to *.eml upon d&d upload. We will also store the source of a mail (mail-in or d&d-upload). The field is always rendered in display-mode and also shown on the mail-overview, but only for `Manager`:
Closes #1149.
> Keep *.msg file after conversion and store message source for mails

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/browser/paste.py
- opengever/base/locales/de/LC_MESSAGES/opengever.base.po
- opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
- opengever/base/locales/opengever.base.pot
- opengever/base/tests/test_copy_paste.py
We have an `is_pasting_allowed` view that returns whether pasting is allowed. We should also check that one when pasting to prevent url-crafting by the user.
Closes #1159.
> Check is_pasting_allowed view when pasting.

- docs/HISTORY.txt
- opengever/globalindex/model/task.py
- opengever/globalindex/tests/test_task_link.py
Skip access test when the current user has Administrator or Manager role.
Closes #2838
> Always render a task link for administrators or managers.

- docs/HISTORY.txt
- opengever/base/browser/wizard/storage.py
- opengever/meeting/command.py
- opengever/task/browser/accept/utils.py
- opengever/task/browser/complete.py
Inter-Admin-Unit Requests: Extract response body into the local namespace so Sentry can log it as a local in case of failure.
Example Sentry Event:
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3129/events/88432/
(See `response_body` in locals below code, above traceback ("Show more"))
This partly helps with #1541 (still some things left to do though)
> Inter-Admin-Unit Requests: Extract response body into the local namespace

- docs/HISTORY.txt
- opengever/bundle/loader.py
- opengever/bundle/sections/fileloader.py
- opengever/bundle/tests/test_bundle_loader.py
With this fix all items injected into the transmogrifier pipeline contain utf8 encoded byte strings instead of unicode strings. This fixes an issue with unicode strings in local roles (#2927).
It may introduce new issues if something in the ogg bundle pipeline relies on unicode strings. But in general items in the transmogrifier pipeline should always contain byte strings. Various sections will break with unicode strings.
/cc @lukasgraf
> Fix string type in bundle loader

- opengever/core/sqlite_testing.py
Prevent state bleeding between tests by also clearing the dictstorage table. It was created in `create_sql_tables` but never cleared. This led to `DownloadConfirmationHelper` state bleeding between tests.
> Also truncate dictstorage table during tests.

- docs/HISTORY.txt
- opengever/base/security.py
- opengever/base/tests/test_security.py
- opengever/inbox/yearfolder.py
- opengever/task/yearfolderstorer.py
The function `elevated_privileges` supersedes `changed_security` because it retains the current user name instead of using SpecialUsers.system which does not have an username since it corresponds to no real user.
Also tested manually with yearfolders.
Closes #1410.
> Replace changed_security with elevated_privileges.

- docs/HISTORY.txt
- opengever/document/browser/templates/macros.pt
- opengever/document/locales/de/LC_MESSAGES/opengever.document.po
- opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
- opengever/document/locales/opengever.document.pot
Fixes #2951 
Because the action is now part of the document subdirectory, i moved the translation to the og.document domain.
Backport to: 2017.2.x
> Fix translation for the "Open as PDF" action.

- opengever/journal/browser.py
- opengever/journal/form.py
- opengever/journal/tab.py
The actual root cause of #1244 was tackled in the lack of actual understanding of how to build the whole thing properly up from `ftw.table` -> `ftw.tabbedview` -> `opengever.core`. This is doable, but not within the time frame of the sprint now. Our current implementation is a hack which goes against the grain of how one should use these tools.
The actual end result query should eventually end up relying on `plone.batching`.
In the course of mucking around a technique to optimize the slowest part, the deepcopy within the abusely-built-query, was discovered. It turned out pickling and unpickling the objects with cPickle is faster than making a deepcopy. This is a hack, but a valid one at least partially addressing the issue at hand?
I've locally metrified a gain in the journal of a …
> Optimize journal queries

- development.cfg
Follow-up for #2970, make sure that extends order is correct and that variables that are used in a `+=` statement are always defined first.
> Fix extends order, make sure variable used in += are defined first.

- docs/HISTORY.txt
- opengever/dossier/configure.zcml
- opengever/dossier/handlers.py
- opengever/dossier/interfaces.py
- opengever/dossier/resolve.py
- opengever/dossier/tests/test_resolve.py
- opengever/dossier/upgrades/20170519152516_add_resolver_name_to_i_dossier_resolve_properties/registry.xml
- opengever/dossier/upgrades/20170519152516_add_resolver_name_to_i_dossier_resolve_properties/upgrade.py
With this PR the checks when resolving a dossier become customisable. To achieve this goal the dossier-resolver is converted into a named adapter. The name of the adapter to use is read from the registry and used in the adapter lookup. Thus it becomes possible to easily add new adapters, theoretically also on a per customer level, should this be desired. 
We also provide two adapters:
- `strict` the default current behavior which enforces all checks
- `lenient` an implementation which does not enforce that all documents and tasks are to be filed in a subdossier (if the main dossier has subdossiers)
Closes #1871.
> Make rules when resolving a dossier customisable.

- docs/HISTORY.txt
- opengever/base/browser/configure.zcml
- opengever/base/browser/wizard/configure.zcml
- opengever/base/browser/wizard/storage.py
- opengever/base/request.py
- opengever/base/tests/test_safe_call_decorator.py
- opengever/meeting/browser/rejectproposal.py
- opengever/ogds/base/configure.zcml
- opengever/ogds/base/sync/configure.zcml
- opengever/ogds/base/sync/import_stamp.py
- opengever/task/browser/accept/configure.zcml
- opengever/task/browser/accept/utils.py
- opengever/task/browser/close.py
- opengever/task/browser/complete.py
- opengever/task/browser/configure.zcml
- opengever/task/browser/store.py
- opengever/task/configure.zcml
- opengever/task/response_syncer/__init__.py
- opengever/task/transporter.py
The goal is to improve the error handling and debugging ability for requests to other gever sites.
See #1541 for more details.
This PR implements:
- A `safe_call` decorator, which wraps the `__call__` method of an endpoint in a try/except. In case of an exception the traceback is returned as string.
- The safe_call decorator also tries to notify sentry if possible, to not swallow the exception silently.
- On the client site the `dispatch_request` method is now able to  report the traceback of the failed remote call as exception message.
- ConflictError and KeyBoardInterrupt are not catched.
- The parameter to_raise allows you to add more Exceptions, which should not be handled.
**The result:**
If a remote call fails there are 2 entries in sentry. …
> Implement and use a safe_call decorator for all remote endpoints

- docs/HISTORY.txt
- opengever/activity/model/activity.py
- opengever/activity/model/notification.py
- opengever/activity/model/query.py
- opengever/activity/model/resource.py
- opengever/activity/model/settings.py
- opengever/activity/model/subscription.py
- opengever/activity/model/watcher.py
- opengever/contact/models/organization.py
- opengever/contact/models/participation.py
- opengever/contact/models/person.py
- opengever/contact/models/query.py
- opengever/globalindex/model/query.py
- opengever/locking/model/__init__.py
- opengever/locking/model/locks.py
- opengever/locking/model/query.py
This decouples the `Query*` classes a bit from their corresponding model classes. This allows us to avoid possible cyclic imports when writing queries that connect multiple SQL-Models and it allows us to directly access class attributes when writing `filter` query methods.
Closes #1134
> Refactor SQL model classes, put Query* classes into own module.

- README.rst
- development.cfg
- opengever/policytemplates/policy_template/opengever.+package.name+/development.cfg.bob
It is now included by https://github.com/4teamwork/gever-buildouts/blob/master/standard-dev.cfg
> No longer separately include ruby-gems.cfg.

- opengever/core/sqlite_testing.py
- versions.cfg
Backport a fix for a flaky test. Will help to avoid failing tests should another backport be necessary. Not necessary to release separately, though.
Also extend from the correct release version.
> Sanitize 2017.2-stable branch.

- docs/HISTORY.txt
- opengever/base/browser/search.py
- opengever/dossier/browser/overview.py
- opengever/dossier/tests/test_dossier.py
- opengever/dossier/tests/test_dossier_template.py
- opengever/dossier/tests/test_overview.py
In order to make it possible to actually search for keywords containing non ascii characters, it's necessary to pass the `Subject` as unicode.
- The Subject Index only stores unicode values
Currently the default gever listing on the overview tab, shows them as list. 
Not that neat, but consistent. 
Closes #2901
> Link keywords on dossier overview.

- docs/HISTORY.txt
- opengever/dossier/base.py
- opengever/dossier/tests/test_retention_expiration.py
The default values in the interface are:
```
default=[u'5',
u'10',
u'15',
u'20',
u'25'],
``` 
The default value of the field is `5` (as Int)
This means after changing the `retention_period` of a dossier, it was no longer possible to get the `get_retention_expiration_date`. 
This currently may break an upgrade to onegovgever 2017.2.2.
> Fix get_retention_expiration_date on dossier. retention_period may be a unicode.

- docs/HISTORY.txt
- opengever/dossier/browser/overview.py
The Subject needs be url quoted. Don't know why this lead us to a problem in customer integration, but not in gever itself. 
To quote the querystring values is anyway a good practice.
> Fix Subject link on dossier overview.

- development.cfg
- docs/HISTORY.txt
- opengever/activity/upgrades/20170328142858_add_task_commented_notification_setting/upgrade.py
- opengever/core/upgrade.py
This PR fixes an issue when running upgrades on mysql which does not support sequences.
Only increment the sequence manually if the dialect actually supports sequences. The solution has been inspired by https://stackoverflow.com/questions/17196234/how-to-create-postgresqls-sequences-in-alembic.
> Fix upgrade step and make it run on mysql and psql.

- docs/HISTORY.txt
- opengever/bundle/sections/fileloader.py
- opengever/bundle/tests/assets/basic.oggbundle/documents.json
- opengever/bundle/tests/test_bundle_loader.py
- opengever/bundle/tests/test_oggbundle_pipeline.py
- opengever/bundle/tests/test_section_bundlesource.py
- opengever/bundle/tests/test_section_fileloader.py
- opengever/mail/mail.py
- opengever/mail/tests/test_ogmail.py
The fileloader had a special handling for initializing the mail title (use the subject as title) after attaching the message to the object. Those handling hasn't checked for an already existing title.
Fixes #2942
> OGGBundle: Do not initialize the mail title for mails with a title given.

- docs/HISTORY.txt
- opengever/document/static/officeconnector.js
Closes https://github.com/4teamwork/opengever.core/issues/2955
Because the user is able to just edit a checked out document the loader has to behave different.
So first check if the document is already checked out. If so just display the loader 5 seconds
to close the waiting time for opening the office connector.
> Fix checkout behavior of already checked out document.

- docs/HISTORY.txt
- opengever/tasktemplates/browser/tasktemplates_templates/view.pt
Prev.
Now:
This was a regression because of the chameleon rendering.
Closes #2988
> Fix tasktemplate view by adding a missing </table> tag.

- versions.cfg
This is the first baby step taken in eventually bringing the QA tools into developer buildouts with a repo level (and thus also team level) shared config file (all the QA tools already respect setup.cfg by common convention).
Unpinning pyflakes enables me more convenience for local development - I'm currently having a local buildout file and mucking around with the recipes to make editor/IDE linter compatible buildout wrappers for common QA tools. These would down the line live in the shared buildout config snippets and developers can choose to include them in their local buildouts or not - but if anyone uses a QA tool we'd still have a shared config we can tweak and discuss about over time.
> We have no actual need to pin QA tools

- opengever/setup/patches/addzmiopengeverclient.py
With the profile merge it is now displayed incorrectly. This PR removes the hint:
> No longer display update gever warning in zmi.

- docs/HISTORY.txt
- opengever/setup/deploy.py
- opengever/setup/meta.py
Only possibility to configure this so fare is TTW. This PR adds a configuration option to also set the group on a per deployment configuration basis.
> Add api_group deployment configuration option.

- docs/HISTORY.txt
- opengever/core/profiles/default/registry.xml
- opengever/core/upgrades/20170606112029_include_orgunit_selector_e_tag_to_cache_rules/registry.xml
- opengever/core/upgrades/20170606112029_include_orgunit_selector_e_tag_to_cache_rules/upgrade.py
- opengever/ogds/base/tests/test_viewlet_ou_selector.py
- opengever/ogds/base/viewlets/configure.zcml
- opengever/ogds/base/viewlets/ou_selector_viewlet.py
This changes includes the current orgunit id to the plone.app.caching etags, to make sure the site is only served by cache when the current org_unit has not been changed.
> Implement and enable the org unit selector etag adapter.

- docs/HISTORY.txt
- opengever/core/configure.zcml
- opengever/core/hooks.py
- opengever/examplecontent/profiles/default/metadata.xml
- opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/metadata.xml
- opengever/setup/deploy.py
- opengever/setup/meta.py
The profiles
- `opengever.core:default`
- `plonetheme.teamraum:gever`
- `opengever.policy.base:mimetype`
must always be installed in that exact order and are always the first profiles that were listed in a policy's `metadata.xml`. This is an unnecessary duplication, so with this PR we hard-code the to be installed profiles. Also remove the option `base_profile` for the policy directives.
When this PR is merged it is no longer necessary to include the profiles manually in each policy. Also policies will most likely fail if they have incorrect dependencies sine https://github.com/4teamwork/opengever.core/pull/2570 introduced a check to avoid duplicate profile installation.
> Hard-code base profiles to be installed for every deployment.

- bin/mtest
Use `ProcessPoolExecutor` instead of `ThreadPoolExecutor`. It seems to be able to isolate environment variables correctly whereas `ThreadPoolExecutor` seems to have problems.
I have verified that with a modified `bin/test` that just logged the ports in its env, see https://github.com/4teamwork/opengever.core/tree/deif-TMP-debug-ports. After switching to ProcessPoolExecutor duplicate port assignments could not be observed in the log any more, before switching duplicate port assignments could be observed in every run.
> Use ProcessPoolExecutor to execute the batches.

- docs/HISTORY.txt
- opengever/dossier/resources/init_tree.js
- opengever/portlets/tree/resources/tree.js
Closes https://github.com/4teamwork/opengever.core/issues/2967
Render subdossier tree collapsed initially.
> Provide option to initially render the jstree expanded.

- docs/HISTORY.txt
- opengever/inbox/forwarding.py
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
- opengever/task/browser/assign.py
- opengever/task/form.py
- opengever/task/tests/test_assign.py
- opengever/task/tests/test_task.py
**Closes #3010**
- Only users of the current orgunit and the inbox of the current orgunit are selectable.
**Closes #3016**
- The deecopy fails if there are related items, since the payload values are already converted.
> Fix task assign form and creating multiple tasks with relations. 

- docs/HISTORY.txt
- opengever/ogds/base/sources.py
- opengever/ogds/base/tests/test_sources.py
This source is not used directly by opengever.core features but used in different customer special dossiers.
This change allow us to consequently use `ftw.keywordwidget` instead of the `plone.formwidget.autocomplete`.
> Add missing contacts source

- docs/HISTORY.txt
- opengever/document/browser/templates/logout_overlay.pt
The `class` attribute was defined twice in the template, which lead the Chameleon engine to just drop this attribute.
Fixes #2964
> Fix "leave GEVER" on logout overlay.
