4teamwork/opengever.core

docs/HISTORY.txt
opengever/setup/sections/xlssource.py

Backport PR #740 to [`4.1-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.1-stable)

Backport "Fix handling of mapped vocabulary terms in XlsSource" to 4.1-stable

---

docs/HISTORY.txt
opengever/setup/sections/xlssource.py

Backport PR #740 to [`4.0-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.0-stable)

Backport "Fix handling of mapped vocabulary terms in XlsSource" to 4.0-stable

---

docs/HISTORY.txt
opengever/base/browser/resources/opengever.css
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/macros_templates/macros.pt
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/profiles/default/jsregistry.xml
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_unit_meeting.py
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/profiles/4206/jsregistry.xml

Style meeting form.
Add agendaitem sorting implementation.

Meeting form styles. Agendaitem sortable.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/de/LC_MESSAGES/plone.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/plone.po
opengever/meeting/locales/opengever.meeting.pot

Update german translations for opengever.meeting.

---

docs/HISTORY.txt
opengever/base/browser/resources/opengever.css
opengever/meeting/browser/meetings/templates/pre_protocol.pt
opengever/meeting/browser/resources/jquery.autosize.js
opengever/meeting/browser/resources/meeting.js
opengever/meeting/browser/resources/sticky_heading.js
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/profiles/4211/jsregistry.xml

Made styling for protocol view.
Namespaced view with #opengever_meeting_protocol
Add two jquery plugins for autosizing textareas and sticky headings.

Style protocol view.

---

docs/HISTORY.txt
opengever/meeting/browser/committeecontainertabs.py
opengever/meeting/browser/committeetabs.py
opengever/meeting/tabs/committeelisting.py
opengever/meeting/tabs/meetinglisting.py
opengever/meeting/tabs/memberlisting.py
opengever/meeting/tabs/membershiplisting.py
opengever/meeting/tabs/proposallisting.py
opengever/meeting/tabs/submittedproposallisting.py
opengever/tabbedview/browser/tabs.py

:warning: based on #762 
I've used the the already existing `SqlTableSource` for all the meeting listings, this provides filter and sorting functionality.

Fixed filtering and sorting of the meeting listings

---

docs/HISTORY.txt
opengever/meeting/browser/committee.py
opengever/meeting/browser/committee_templates/overview.pt
opengever/meeting/browser/members.py
opengever/meeting/committee.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/query.py
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/profiles/default/types/opengever.meeting.committee.xml
opengever/meeting/service.py
opengever/meeting/tests/test_committee_overview.py
opengever/meeting/tests/test_memberships.py
opengever/meeting/tests/test_preprotocol.py
opengever/meeting/tests/test_service.py
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/to4212.py

Added first version of the overview tab, for the committee Tabbed view.

Added committee overview tab

---

opengever/base/viewlets/contentviews.py
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/proposaloverview.py
opengever/meeting/browser/tabbed.py
opengever/meeting/committee.py
opengever/meeting/form.py
opengever/meeting/model/proposal.py
opengever/meeting/proposal.py
opengever/meeting/tabs/proposallisting.py
opengever/meeting/tabs/submittedproposallisting.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_listings.py
opengever/meeting/tests/test_unit_workflow.py
opengever/meeting/workflow.py

Make sure proposals are only editable as long as considered editable by the model.
Also refactor workflow definition and move it closer to the model.

Respect proposal editable state.

---

docs/HISTORY.txt
opengever/base/browser/resources/opengever.css
opengever/meeting/browser/committeecontainertabs.py
opengever/meeting/browser/committeecontainertabs_templates/committee.pt
opengever/meeting/committee.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/meeting.py
opengever/meeting/model/query.py
opengever/meeting/service.py
opengever/meeting/tests/test_committee_container.py
opengever/meeting/tests/test_meeting_query.py
opengever/meeting/tests/test_service.py
opengever/tabbedview/browser/base.py
sources.cfg

:warning: The PR https://github.com/4teamwork/opengever.ogds.models/pull/26 has to be merged first.
Before:
After:
@deiferni, @lukasgraf  please have a look

Replaced committeelisting tab with a committee overview listing

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/exceptions.py
opengever/usermigration/tests/test_dossier_migrator.py

Add `DossierMigrator` that migrates `responsible` for dossiers (to be used with `ftw.usermigration`).
@phgross

Add DossierMigrator that migrates dossier responsibles 

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/exceptions.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #800 to `4.0-stable` branch.
@phgross

Backport "Add DossierMigrator that migrates dossier responsibles" to 4.0-stable

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/exceptions.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #800 to [`4.1-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.1-stable).
@phgross

Backport "Add DossierMigrator that migrates dossier responsibles" to 4.1-stable

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/exceptions.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #800 to [`4.2-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.2-stable).
@phgross

Backport "Add DossierMigrator that migrates dossier responsibles" to 4.2-stable

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/exceptions.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #800 to [`4.3-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.3-stable).
@phgross

Backport "Add DossierMigrator that migrates dossier responsibles" to 4.3-stable

---

docs/HISTORY.txt
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_ogds_migrator.py

Backport PR #814 to [`4.3-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.3-stable).

Backport "Add OGDSMigrator that migrates users and inbox groups in OGDS SQL tables" to 4.3-stable

---

docs/HISTORY.txt
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_ogds_migrator.py

Backport PR #814 to [`4.2-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.2-stable).

Backport "Add OGDSMigrator that migrates users and inbox groups in OGDS SQL tables" to 4.2-stable

---

docs/HISTORY.txt
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_ogds_migrator.py

Backport PR #814 to [`4.1-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.1-stable).

Backport "Add OGDSMigrator that migrates users and inbox groups in OGDS SQL tables" to 4.1-stable

---

docs/HISTORY.txt
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_ogds_migrator.py

Backport PR #814 to [`4.0-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.0-stable).

Backport "Add OGDSMigrator that migrates users and inbox groups in OGDS SQL tables" to 4.0-stable

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #828 to [`4.3-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.3-stable).

Backport "Implement migrating participants in DossierMigrator" to 4.3-stable 

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #828 to [`4.0-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.0-stable).

Backport "Implement migrating participants in DossierMigrator" to 4.0-stable 

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #828 to [`4.1-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.1-stable).

Backport "Implement migrating participants in DossierMigrator" to 4.1-stable 

---

docs/HISTORY.txt
opengever/usermigration/dossier.py
opengever/usermigration/ogds.py
opengever/usermigration/tests/test_dossier_migrator.py

Backport PR #828 to [`4.2-stable` branch](https://github.com/4teamwork/opengever.core/tree/4.2-stable).

Backport "Implement migrating participants in DossierMigrator" to 4.2-stable 

---

sources.cfg

See https://github.com/4teamwork/ftw.tabbedview/pull/42.
@deiferni please have a look

Add ftw.tabbedview to the development packages to include initial tab fix

---

opengever/inbox/locales/de/LC_MESSAGES/opengever.inbox.po
opengever/inbox/locales/fr/LC_MESSAGES/opengever.inbox.po
opengever/inbox/locales/opengever.inbox.pot

- Type name 
- `current_inbox_not_available` msg

Added missing translations for the inbox container

---

docs/HISTORY.txt
opengever/task/activities.py
opengever/task/tests/test_activities.py

The TaskActivity class had wrongly returned objects creator as activity actor,
instead of the current user.

Fixed actor for all task activities.

---

docs/HISTORY.txt
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/plone.pot
opengever/base/viewlets/searchbox.py

Added translations for the SearchBoxViewlet placeholder.

---

docs/HISTORY.txt
opengever/base/browser/resources/opengever.css
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/layout.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/members.py
opengever/meeting/browser/members_templates/member.pt
opengever/meeting/browser/memberships.py
opengever/meeting/browser/views.py
opengever/meeting/form.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/model/member.py
opengever/meeting/model/membership.py
opengever/meeting/model/proposal.py
opengever/meeting/model/query.py
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/tabs/membershiplisting.py
opengever/meeting/tests/test_meeting.py
opengever/meeting/tests/test_members.py
opengever/meeting/tests/test_memberships.py
opengever/meeting/tests/test_unit_membership.py
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/to4302.py

Display Type Icon also as Watermark or and in listings:
----
Additionally to all the views and I've extend with icons, I extend the Memberview with some additional functionalities:
- Display all Metadata
- Membershiplistings
- Edit functionality 
- Remove functionality 
/cc @deiferni @lukasgraf

Added Icons for all the meeting objects and extend member functionality.

---

docs/HISTORY.txt
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po

@lukasgraf a very small one ...

Fixed french translation for author label.

---

docs/HISTORY.txt
opengever/base/browser/resources/opengever.css
opengever/portlets/tree/resources/init_tree.js

Fixes https://github.com/4teamwork/plonetheme.teamraum/issues/294

Helptext separation

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/excerpt.pt
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_unit_agenda_item.py

Fix displaying agenda-item numbers.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/model/proposal.py
opengever/meeting/model/submitteddocument.py
opengever/meeting/tests/test_excerpt.py
opengever/meeting/tests/test_meeting_view.py
opengever/meeting/tests/test_preprotocol.py
opengever/meeting/tests/test_protocol.py
opengever/testing/builders/sql.py

Made meeting view implementation as described in https://basecamp.com/2768704/projects/7577904/todos/170675783.
Updated builders for generating meeting related documents.
Updated translations for shorter protocol actions.
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/299

Meeting view implementation

---

docs/HISTORY.txt
opengever/dossier/profiles/default/metadata.xml
opengever/dossier/upgrades/configure.zcml
opengever/dossier/upgrades/profiles/4302/workflows/opengever_dossier_workflow/definition.xml
opengever/dossier/upgrades/profiles/4302/workflows/opengever_templatedossier_workflow/definition.xml
opengever/dossier/upgrades/to4302.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposalhistory.py
opengever/meeting/tests/test_submit_additional_documents.py
opengever/task/tests/test_workflow.py

The following permissions are now managed:
- opengever.meeting: Add Proposal
- opengever.meeting: Add Sablon Template
Fixes #773.

Also manage meeting permission in dossier workflow.

---

docs/HISTORY.txt
opengever/task/browser/overview_templates/overview.pt

Fixed wrongly displayed document_actions in task overview.

---

docs/HISTORY.txt
opengever/dossier/deactivate.py
opengever/dossier/tests/test_deactivate.py

Disallow deactivating a dossier which contains not closed tasks.

---

opengever/examplecontent/profiles/default/registry.xml

Set correct reference number starting point for example profiles.

---

opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/resources/Scrollspy.js
opengever/meeting/browser/resources/protocol.js
opengever/meeting/browser/resources/sticky_heading.js
opengever/meeting/profiles/default/jsregistry.xml
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/profiles/4307/jsregistry.xml

This needs https://github.com/4teamwork/plonetheme.teamraum/pull/303
Implementation of scrollspy tree and sticky headings inspector.
This extension works fine with sticky heading.

Implement scrollspy tree inspector.

---

opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/ftw.tabbedview.pot
opengever/base/locales/plone.pot
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/profiles/default/types/opengever.meeting.committee.xml

wurden teilweise wegoptimiert, oder initial nicht erstellt.
*Changelog-Eintrag sollte nicht notwendig sein*
Closes #946.

Add some missing meeting translations.

---

docs/HISTORY.txt
opengever/task/handlers.py
opengever/task/tests/test_response_descriptions.py

Fixes #947 
@lukasgraf or @deiferni

Fixed ResponseDescription when adding mails to a task.

---

docs/HISTORY.txt
opengever/task/browser/overview.py
opengever/task/tests/test_overview.py

Aufgabenübersicht: Verlinkung von Aufgaben vereinfacht.

---

docs/HISTORY.txt
opengever/activity/model/activity.py
opengever/activity/profiles/default/metadata.xml
opengever/activity/upgrades/configure.zcml
opengever/activity/upgrades/to4500.py

Änderungen am Modell + Schemamigration. Getestet auf Postgres, Oracle und MySQL.
Closes #1003.

Activity: Spaltentyp für summary zu Text ändern.

---

opengever/document/browser/redirect_to_parent_dossier.py

Dies ist ein Nachtrag zu #1019, wir haben diese Änderung mündlich diskutiert - sie ging aber leider vor dem merge vergessen.

Assert that redirect view is called with valid precondition.

---

docs/HISTORY.txt
opengever/activity/center.py
opengever/base/browser/pasting_allowed.py
opengever/base/monkeypatch.py
opengever/document/indexers.py
opengever/dossier/archive.py
opengever/mail/browser/attachment.py
opengever/ogds/base/events.py
opengever/ogds/base/sections/activeusers.py

Remove bare excepts and only catch Exception when possible. Also make sure to
always re-raise ConflictError.

Improve exception handling.

---

docs/HISTORY.txt
opengever/base/browser/search.pt
opengever/base/browser/search.py
opengever/base/contentlisting.py
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/base/tests/test_search.py
opengever/dossier/browser/redirect_to_maindossier.py
opengever/dossier/indexers.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_redirect_to_maindossier.py
opengever/dossier/utils.py

Folgende Verbesserungen wurden gemacht:
- Styling Such Formular (siehe Theme PR)
- Kompaktere und übersichtlichere Darstellung der Suchresultate (siehe Theme PR)
- Der Dossier Titel wird neu verlinkt
- Der Dossier Titel ist mit einem Label `Dossier:` prefixed.
Siehe hierzu auch die [Diskussion](https://feedback.onegovgever.ch/t/darstellung-der-suchresultate/124) im Feedback Forum.
@lukasgraf 
Closes #540

Verbesserung der Darstellung von Suchresultaten und der Suchseite

---

docs/HISTORY.txt
opengever/dossier/handlers.py

Additionally I've changed the method names.
@lukasgraf

Fixed path limitation of the catalog query in save_reference_number_prefix subscriber.

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Adjust german translations of the umscheduled proposals box label.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/proposal.py

Show statusmessage after successfully submitting a proposal.

---

docs/HISTORY.txt
opengever/document/browser/overview.py
opengever/document/tests/test_overview.py
opengever/meeting/model/query.py

Only display link to proposal for documents in repositories.

---

opengever/policy/base/upgrades/to4504.py

Die Updates können mitunter sehr lange dauern. Da ist es praktisch und beruhigend wenn man dabei auf ein Log des Fortschritts gucken kann.

Rewrite upgrade to use ftw.upgrade progress logger.

---

docs/HISTORY.txt
opengever/dossier/browser/participants.py
opengever/ogds/base/actor.py
opengever/ogds/base/tests/test_actor_lookup.py

- Anstatt einer separaten Zeile mit dem Icon, wird neu der Actor Link mit einem Icon versehen
- Die "Checkbox-Spalte" hat neu eine feste, schmale Breite
Vorher:
Nachher:
fixes #1093 
@lukasgraf

Verbesserung der Beteiligungen Auflistung

---

docs/HISTORY.txt
opengever/document/browser/download.py
opengever/document/browser/versions_tab.py
opengever/document/tests/test_versions_tab.py

Versionen Tab: Download Links mit Authenticator token versehen.

---

sources.cfg

To include https://github.com/4teamwork/ftw.tabbedview/pull/44

Take ftw.tabbedview from source.

---

docs/HISTORY.txt
opengever/tasktemplates/browser/form.py
opengever/tasktemplates/tests/test_activities.py
opengever/testing/builders/dx.py

Mit diesen Änderungen werden nun auch beim Auslösen eines Standardablaufes Aktivitäten registriert (für die Hauptaufgabe und allen dessen Unteraufgaben).
@lukasgraf

Added tasktemplate activity support

---

docs/HISTORY.txt
opengever/tabbedview/helper.py
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview.pot
opengever/tabbedview/tests/test_document_helper.py

Fixed translation of PDF Preview button in document's tooltip.

---

docs/HISTORY.txt
opengever/activity/center.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/mail.py
opengever/activity/tests/test_listing.py
opengever/activity/tests/test_notification_center.py
opengever/activity/tests/test_plone_center.py
opengever/activity/tests/test_views.py

Exception logging verbessert:
- Der `opengever.activity` logger wird nun verwendet
- Anstatt nur die string representation des Errors wird nun der komplette Traceback ins log geschrieben.
Verbesserung des Error Handling:
- Exceptions beim Dispatchen (Mail Versand) werden separat abgefangen. So wird z.B. sicher gestellt das bei einem Fehler in der Mail Generierung, die komplette Benachrichtigung abgebrochen wird.
@lukasgraf 

Notification dispatch improvements

---

docs/HISTORY.txt

I've released the Bugfix Release `4.5.1` from the `4.5-stable` release. 

Cleanup changelog after bugfix release `4.5.1`.

---

docs/HISTORY.txt

Cleanup changelog after 4.5.3 bugfix release.

---

docs/HISTORY.txt
opengever/document/base.py
opengever/document/tests/test_document.py
opengever/meeting/proposal.py

Fixes [Errbit-error](https://errbit.4teamwork.ch/apps/521f062d38381878b600012c/problems/5608efcb6d617454033b0000), for example  https://gemeinde.onegovgever.ch/ordnungssystem/volkswirtschaft/energie/elektrizitaet/dossier-54/proposal-38/document-248
@deiferni

Fixed get_parent_dossier getter for document inside a proposal.

---

docs/HISTORY.txt
opengever/locking/tests/test_lockable.py
opengever/testing/builders/dx.py

- No longer create `RelationValue` manually, this is now done automatically by ftw.builder see https://github.com/4teamwork/ftw.builder/pull/43
- Catch up with changes in a new ftw.testing release

Fix two issues on current master.

---

.gitattributes

Should cause fewer merge conflicts.

Change merge strategy(union) for the changelog.

---

opengever/base/browser/resources/MessageFactory.js
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/base/profiles/default/jsregistry.xml
opengever/base/profiles/default/metadata.xml
opengever/base/response.py
opengever/base/tests/test_json_response.py
opengever/base/upgrades/configure.zcml
opengever/base/upgrades/profiles/4503/jsregistry.xml
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_meeting_view.py

Agendaitems can now get updated through an inline editbox.
Styles in https://github.com/4teamwork/plonetheme.teamraum/pull/359

Implement updating agenda items.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Include missing items in protocol navigation.

---

opengever/base/browser/resources/MessageFactory.js
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/meetings/configure.zcml
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/meetings/unscheduled_proposals.py
opengever/meeting/browser/resources/agendaitems.js
opengever/meeting/browser/resources/agendsitems.js
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/profiles/default/jsregistry.xml
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_excerpt.py
opengever/meeting/tests/test_meeting_view.py
opengever/meeting/tests/test_proposalhistory.py
opengever/meeting/tests/test_protocol.py
opengever/meeting/tests/test_unit_agenda_item.py
opengever/meeting/tests/test_unscheduled_proposals.py
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/profiles/4612/jsregistry.xml

Fixes https://github.com/4teamwork/opengever.core/issues/1256, https://github.com/4teamwork/opengever.core/issues/900
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/366

Implement clientside processing for meeting view.

---

opengever/meeting/browser/meetings/excerpt.py
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/browser/meetings/protocol.py
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/form.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Fixes https://github.com/4teamwork/opengever.core/issues/1311

Extend icons of meetingview with tooltips.

---

docs/HISTORY.txt
opengever/base/tests/test_pathbar.py
opengever/base/viewlets/contentviews.py
opengever/base/viewlets/pathbar.py
opengever/meeting/browser/members.py
opengever/meeting/form.py
opengever/meeting/model/meeting.py
opengever/meeting/model/member.py
opengever/meeting/model/membership.py
opengever/meeting/tests/test_pathbar.py
opengever/meeting/wrapper.py

Fix member edit link and refactor generating breadcrumbs for models.

---

opengever/meeting/browser/meetings/protocol.py
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/resources/agendaitems.js
opengever/meeting/browser/resources/protocol.js
opengever/meeting/browser/resources/sticky_heading.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Fixes https://github.com/4teamwork/opengever.core/issues/1312
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/372

Implement collapsible metadata for protocolview.

---

docs/HISTORY.txt
opengever/dossier/tests/test_overview.py
opengever/meeting/browser/dossier/overview.py
opengever/meeting/dossier.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/query.py
opengever/meeting/tests/test_meeting_dossier_overview.py

Link meeting from meeting-dossier overview.

---

opengever/meeting/browser/meetings/templates/meeting.pt

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/375

Mark destructive buttons.

---

opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/templates/macros.pt

Set marker if no workflow actions are available for styling reasons.

---

opengever/meeting/browser/resources/Scrollspy.js
opengever/meeting/browser/resources/protocol.js

Scroll to the paragraph when selecting them in the navigation.

Javascript throws error when selecting a paragraph in the scrollspy.

---

opengever/meeting/browser/meetings/templates/protocol.pt

Put each proposal in a separate container for styling reasons.

---

opengever/meeting/tests/test_member_vocabulary.py
opengever/meeting/vocabulary.py

Sort member vocabulary by member fullname.

---

opengever/meeting/browser/templates/member.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

This PR adds a missing translation introduced due to a typo.

Add missing translations.

---

opengever/meeting/browser/committeecontainertabs.py
opengever/meeting/tests/test_committee_container.py

Sort committees alphabetically on overview.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/command.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_close.py
opengever/meeting/tests/test_protocol.py

Update/create protocol when closing a meeting.

---

opengever/meeting/browser/resources/protocol.js

Fixes https://github.com/4teamwork/plonetheme.teamraum/issues/381
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/386

Safari does not set the left offset automatically on fixed elements.

---

opengever/meeting/browser/resources/agendaitems.js

```event.target``` always refers to the dispatched object. So use ```event.currentTarget``` which refers to the event handler.

Controller action callback does not create the required target.

---

opengever/meeting/tabs/proposallisting.py

Fixes https://github.com/4teamwork/opengever.core/issues/934
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/391

Display container for proposal workflow state.

---

opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/resources/agendaitems.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Fixes #1346 
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/394

Implement proposals search.

---

opengever/meeting/command.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/generateddocument.py
opengever/meeting/model/meeting.py
opengever/meeting/model/proposal.py
opengever/meeting/protocol.py

This PR only refactor the meeting closing without any changes on the functionality. The changes should raise the readability and simplify the implementation for #1356.
@deiferni @lukasgraf please have a look ...

Refactor meeting closing

---

opengever/meeting/browser/resources/meeting.js

Fixes https://github.com/4teamwork/opengever.core/issues/1399
According to 84056e6 the filter functionality has been removed
accidentally.

Filter proposals is not working.

---

opengever/base/browser/resources/MessageFactory.js

Do not clean messages from plone.

Plone messges are not displayed.

---

opengever/meeting/browser/meetings/transitions.py
opengever/meeting/browser/resources/meeting.js
opengever/meeting/tests/test_close.py
opengever/meeting/tests/test_protocol.py

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/398, https://github.com/4teamwork/plonetheme.teamraum/pull/397

Close meeting asynchronously

---

opengever/base/browser/resources/Controller.js
opengever/base/browser/resources/Storage.js
opengever/meeting/browser/resources/Editbox.js
opengever/meeting/browser/resources/meeting.js

The editbox now shows error messages when adding an agendaitem with an empty title using the callback validation hooks.
The editbox is now reacting with messages when hitting enter to add a new agendaitem.

Use controller pattern for editbox to define callback validation hooks.

---

opengever/meeting/browser/resources/meeting.js

The autosize got accidentally removed by 84056e6

Use autosize for proposals views.

---

opengever/meeting/tabs/proposallisting.py

Add column property to avoid modifying class attribute.

---

opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/opengever.base.pot
opengever/base/locales/plone.pot
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/profiles/default/types/opengever.meeting.committeecontainer.xml
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/to4626.py

Fixed translation for the add-member menu.

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Rename secretary for german translations

---

opengever/meeting/browser/resources/Scrollspy.js
opengever/meeting/browser/resources/protocol.js

Fixes https://github.com/4teamwork/opengever.core/issues/1431
Define body as root for scroll origin. See http://stackoverflow.com/questions/16475198/jquery-scrolltop-animation for more information.
Focus the anchor when scroll animation has finished.

	Unable to scroll on some devices.

---

docs/HISTORY.txt
opengever/meeting/browser/committeeforms.py
opengever/meeting/committee.py
opengever/meeting/tests/test_committee.py

Fix an issue with repo-folders not stored persistently on committee after create.
Closes #1476.

Fix repo-folder not stored on committee on create.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_unit_agenda_item.py
sources.cfg

Fixes #1018 
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/404

Show difference between proposals and other agendaitems when deleting them

---

docs/HISTORY.txt
opengever/base/browser/resources/Storage.js
opengever/meeting/browser/meetings/protocol.py
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/resources/protocol.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_locking.py

Fixes #1405 
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/402
The user gets a hint when editing the protocol which produces local changes.

Implement user hint for local changes.

---

docs/HISTORY.txt
opengever/setup/locales/fr/LC_MESSAGES/opengever.setup.po

Add french translation for "My portal" action.

---

versions.cfg

Moving forward towards 0.0.19.

Move dev sablon pinnings to kgs.

---

docs/HISTORY.txt
opengever/base/browser/templates/gever-macros.pt
opengever/base/browser/templates/macros.pt
opengever/base/configure.zcml
opengever/base/templates/trix_input.pt
opengever/base/tests/test_widget.py
opengever/base/tests/views/configure.zcml
opengever/base/tests/views/z3cforms.py
opengever/base/widgets.py
opengever/base/widgets.zcml
opengever/core/testing.py
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/proposalforms.py
opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
opengever/meeting/browser/resources/protocol.js
opengever/meeting/profiles/default/jsregistry.xml
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/profiles/4629/jsregistry.xml

Fixes https://github.com/4teamwork/opengever.core/issues/1522
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/409

Use trix widget for proposals form.

---

opengever/meeting/browser/meetings/protocol.py
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/tests/test_protocol.py

Don't render proposal fields for agenda items without proposals.

---

opengever/meeting/browser/resources/protocol.js

The synchronizer is not properly configured. Restrict change detection
to content section.

Synchronizer: Detects changes when typing in search input field.

---

docs/HISTORY.txt
opengever/base/browser/resources/Controller.js
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/resources/Editbox.js
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Fixes https://github.com/4teamwork/opengever.core/issues/1429

Message is visible when deciding the first proposal.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Displays hint that no documents have been generated yet.

---

docs/HISTORY.txt
opengever/base/browser/resources/SelectAutocomplete.js
opengever/base/profiles/default/jsregistry.xml
opengever/base/profiles/default/metadata.xml
opengever/base/upgrades/configure.zcml
opengever/base/upgrades/profiles/4608/jsregistry.xml
opengever/meeting/browser/resources/protocol.js

Fixes https://github.com/4teamwork/opengever.core/issues/1483
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/406

Implement autocomplete select.

---

opengever/meeting/tabs/meetinglisting.py

@lukasgraf plz have a look
*CL entry not necessary, the bug was added since the last release*

Fix encoding issue when displaying meeting state.

---

docs/HISTORY.txt
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/hooks.py.bob

Update policy templates: Creates meeting portlet if enable_meeting_feature is true.

---

docs/HISTORY.txt
opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Rename "Kommission" to more generic "Gremium"

---

docs/HISTORY.txt
opengever/meeting/browser/resources/protocol.js

Fixes https://github.com/4teamwork/opengever.core/issues/1549
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/411

Use autoselect for proposal's create and edit view.

---

docs/HISTORY.txt
opengever/base/browser/resources/Storage.js
opengever/base/browser/resources/datetimepicker.js
opengever/base/profiles/default/jsregistry.xml
opengever/base/profiles/default/metadata.xml
opengever/base/upgrades/configure.zcml
opengever/base/upgrades/profiles/4611/jsregistry.xml
opengever/base/viewlets/configure.zcml
opengever/base/viewlets/language.py
opengever/meeting/browser/resources/datetimepicker.js
opengever/meeting/browser/resources/protocol.js
opengever/meeting/profiles/default/jsregistry.xml
opengever/meeting/profiles/default/metadata.xml
opengever/meeting/upgrades/configure.zcml
opengever/meeting/upgrades/profiles/4634/jsregistry.xml

Closes #1073 
Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/403

Implement SPV datetime picker.

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/resources/Scrollspy.js
opengever/meeting/browser/resources/protocol.js
opengever/meeting/tests/test_protocol.py

Fixes https://github.com/4teamwork/opengever.core/issues/1557

Reduce complexity for traversing the scrollspy navigation tree

---

sources.cfg

Should have been done with the first theme-PR after a release.

Re-add plonetheme.teamraum to sources.

---

docs/HISTORY.txt
opengever/meeting/proposal.py
opengever/meeting/tabs/proposallisting.py

Ein Antrag ist nun mit dem Gremium verlinkt.
closes #1455

Link vom Antrag nach Gremium

---

opengever/base/browser/resources/Controller.js
opengever/meeting/browser/resources/Editbox.js
opengever/meeting/browser/resources/meeting.js
opengever/meeting/browser/resources/protocol.js

Fixes https://github.com/4teamwork/opengever.core/issues/1598
Use explicit object configuration of actions instead of string notation.

Registering action on controllers has grown in complexity.

---

opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/configure.zcml.bob
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob

This PR fixes two minor issues in the policy templates.

Fix issues in policy templates

---

docs/HISTORY.txt
opengever/activity/interfaces.py
opengever/core/testing.py
opengever/examplecontent/profiles/default/registry.xml
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob

Aktiviert das Benachrichtigungssystem standardmässig.
closes #1257

Activate notification-center by default.

---

opengever/base/browser/resources/Controller.js
opengever/meeting/browser/resources/meeting.js

Fixes https://github.com/4teamwork/opengever.core/issues/1598
/cc @deiferni

Add documentation for controller.

---

opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini

Einige kleinere Anpassung der Defaultwerte für Policytemplates.
@deiferni

Adjust policytemplate default values

---

opengever/locking/info.py

@lukasgraf 
Change log not necessary, this is a fix for changes not yet released, see https://github.com/4teamwork/opengever.core/pull/1622

Fix lock info viewlet for webdav locks which seem to have no lock-type.

---

opengever/examplecontent/profiles/4teamwork-ldap/ldap_plugin.xml
opengever/testing/builders/ldap.py

Also don't forget to adapt your `~/.opengever/ldap/...` stuff.

Switch to new ldap branch for local development.

---

sources.cfg

Übernimmt die Änderungen von PR https://github.com/4teamwork/plonetheme.teamraum/pull/415
closes #1367

Checkout plonetheme.teamraum from source

---

docs/HISTORY.txt
opengever/meeting/browser/resources/datetimepicker.js

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/418

Allow blank end date for rangetimepicker.

---

docs/api/docs_changelog.rst
docs/api/index.rst

Add a "Changelog" chapter for the API documentation.

API docs: Add changelog.

---

docs/HISTORY.txt
opengever/meeting/model/member.py
opengever/meeting/tests/test_unit_member.py

Fix an issue with e-mail addresses that contain non-ascii characters.

---

docs/intern/index.rst
docs/intern/meta.rst

Add some documentation about how to build, work on and publish Sphinx Documentation for GEVER.
(see https://intern.onegovgever.ch/meta/)

Docs: Add meta docs on how to build / work on docs.

---

docs/api/conf.py
docs/intern/conf.py

Nur noch 4teamwork AG verlinken.
[ci skip]

Footer angepasst, so dass nur noch 4teamwork verlinkt ist.

---

sources.cfg

Changes in https://github.com/4teamwork/plonetheme.teamraum/pull/420

Add plonetheme.teamraum to development packages.

---

opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/ftw.tabbedview.pot
opengever/base/locales/opengever.base.pot
opengever/disposition/browser/listing.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_listing.py
opengever/repository/profiles/default/types/opengever.repository.repositoryroot.xml
opengever/repository/upgrades/20160425161154_add_disposition_tab_action/upgrade.py

Add new disposition listing tab to the repositoryroot.

---

docs/HISTORY.txt
opengever/meeting/browser/sablontemplate.py
opengever/meeting/protocol.py
opengever/meeting/tests/test_protocol_json_data.py

Exclude email from sablon variable fullname and add a email variable instead.

---

opengever/core/configure.zcml
opengever/core/layout.py
opengever/core/testing.py
opengever/core/tests/test_layout.py
opengever/document/browser/layout.py
opengever/meeting/browser/layout.py
opengever/tabbedview/browser/bumblebee_gallery.pt
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/browser/bumblebee_previews.pt
opengever/tabbedview/browser/generic_with_bumblebee_viewchooser.pt
opengever/tabbedview/browser/personal_overview.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview.pot
opengever/tabbedview/tests/test_bumblebee_gallery.py
opengever/task/layout.py
sources.cfg

Dieser PR fügt die Gallerie-Ansicht für die Tabs "Meine Dokumente" und "Dokumente" hinzu.
closes #1665

Add gallery view

---

opengever/disposition/disposition.py
opengever/disposition/tests/test_disposition.py

Add: date_of_submission = today
Remove: date_of_submission = None
Fixes #1756

Upate date_of_submission when adding/removing a dossier to a disposition

---

opengever/disposition/disposition.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot

Fixed disposition title: contains now the translated disposition label.

---

opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/ftw.tabbedview.pot
opengever/base/locales/opengever.base.pot
opengever/bumblebee/__init__.py
opengever/bumblebee/tests/test_utils.py
opengever/dossier/upgrades/20160429161120_use_documents_proxy_view/upgrade.py
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/browser/personal_overview.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/tests/test_bumblebee_gallery.py
opengever/tabbedview/tests/test_personaloverview.py

Die letzte geöffnete Bumblebeeansicht wird pro Benutzer in einem Cookie gespeichert:
closes #1773

Letzte Bumblebeeansicht wird gespeichert

---

opengever/disposition/disposition.py
opengever/disposition/tests/test_disposition.py
opengever/disposition/tests/test_listing.py

Include admin_unit abbreviation and creation year in the disposition title

---

docs/intern/kurzreferenzen/administration.rst

These changes have been introduced in https://github.com/4teamwork/opengever.core/pull/1751 and https://github.com/4teamwork/opengever.core/pull/1709

Update docs about new/changed sablon template variables.

---

opengever/bumblebee/profiles/default/jsregistry.xml
opengever/bumblebee/upgrades/20160503231329_install_ftw_showroom/jsregistry.xml

Package organization was improved and files were
renamed, see
https://github.com/4teamwork/ftw.showroom/pull/6.

Catch up with minor refactoring in ftw.showroom

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay_templates/bumblebeeoverlayview.pt

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/426
Depends on https://github.com/4teamwork/ftw.showroom/pull/8

Introduce previous and next functionality.

---

opengever/base/browser/search.pt
opengever/base/browser/search.py
opengever/base/contentlisting.py
opengever/base/tests/test_contentlisting.py
opengever/base/tests/test_search.py
opengever/bumblebee/__init__.py
opengever/bumblebee/tests/test_utils.py
opengever/core/testing.py

Open links for bumblebeeable types in an overlay on the search page 

---

opengever/base/browser/search.pt

Wrap every search result item to have a responsive table like layout.

Prepare HTML structure for visual search styling.

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js
opengever/dossier/tests/test_documents_tab.py
opengever/tabbedview/helper.py
opengever/tabbedview/tests/test_document_helper.py
sources.cfg

This change affects all document listings/tabs:
- listing in any dossier
- my-documents tab
- inbox

Open links in document listings in an overlay.

---

opengever/api/tests/test_content_creation.py
opengever/api/tests/test_summary.py
opengever/core/testing.py
opengever/ogds/base/tests.zcml

 Add some basic tests for content creation via API

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js
opengever/bumblebee/browser/resources/fallback.svg

Replace source of preview image with a fallback image if loading failed.

Implement broken image fallback.

---

opengever/bumblebee/browser/resources/bumblebee.js
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/tests/test_bumblebee_gallery.py
sources.cfg

Dieser PR fügt das Filtern in der Galerieansicht hinzu.

Filtern in der Galerieansicht

---

opengever/bumblebee/service.py

See https://github.com/4teamwork/ftw.bumblebee/pull/80
Changelog not necessary (Bumble Integration is part of the current release).
@lukasgraf or @deiferni

Update Geverbumblebeeservice service with the newest adjustments from `ftw.bumblebee`

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/meeting.py
opengever/meeting/tests/test_meeting.py

Redirect to meeting tab when a meeting has been created.

---

docs/HISTORY.txt
opengever/advancedsearch/advanced_search.py
opengever/advancedsearch/tests/test_search.py

Dont quote advanced search parameters twice.

---

docs/HISTORY.txt
opengever/tabbedview/browser/tasklisting.py
opengever/tabbedview/locales/de/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/tabbedview/locales/opengever.tabbedview.pot

Fixed label for the pending statefilter on task listings.

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js
sources.cfg

Fixes https://github.com/4teamwork/opengever.core/issues/1836
Add support for single showroom item.

Support single showroom item.

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/tests/test_overlay_adapter_document.py

Fix links to checkin actions from overlay.

---

README.rst
sphinx.cfg

Rename build / publish docs script to avoid conflicts with the bin/instance script.

---

docs/HISTORY.txt
opengever/dossier/browser/overview_templates/overview.pt
opengever/portlets/tree/treeportlet.pt

Make sure references to spinner.gif are absolute URLs.

---

docs/HISTORY.txt
opengever/dossier/base.py
opengever/dossier/deactivate.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/resolve.py
opengever/dossier/tests/test_base.py
opengever/dossier/tests/test_deactivate.py
opengever/dossier/tests/test_resolve.py

Fixes #1752 .
Additionally I've cleaned up the tests and some method names.
@deiferni please have a 👀

 Disallow closing or deactivating a dossier which contains active proposals.

---

docs/HISTORY.txt
opengever/tabbedview/browser/generic_with_bumblebee_viewchooser.pt

Fixes #1947.
@deiferni  or @elioschmutz please have a 👀

Fixed translation of the bumblebee gallery/list icons.

---

docs/HISTORY.txt
opengever/bumblebee/service.py
opengever/document/configure.zcml

⚠️  merge https://github.com/4teamwork/ftw.bumblebee/pull/95 first ⚠️ 
The bumblebee events changed. So we have to change this in opengever.core too.

Adjust registered bumblebee-events.

---

docs/HISTORY.txt
opengever/base/browser/templates/gever-macros.pt
opengever/meeting/browser/meetings/templates/protocol.pt
opengever/meeting/browser/resources/Scrollspy.js
opengever/meeting/browser/resources/protocol.js
opengever/meeting/browser/resources/sticky_heading.js

⚠️  Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/436
Closes https://github.com/4teamwork/opengever.core/issues/1882
Complex refactoring of the `sticky_headings.js` so we are able to support stacked sticky elements.
Huge thank you @deiferni 💛

Implement sticky toolbar.

---

docs/HISTORY.txt
opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/ftw.tabbedview.pot
opengever/bumblebee/__init__.py
opengever/dossier/profiles/default/types/opengever.dossier.businesscasedossier.xml
opengever/dossier/profiles/default/types/opengever.dossier.templatedossier.xml
opengever/dossier/tests/test_trash_tab.py
opengever/dossier/upgrades/20160623093106_use_trash_proxy_view/upgrade.py
opengever/inbox/hooks.py
opengever/inbox/profiles/default/types/opengever.inbox.inbox.xml
opengever/inbox/upgrades/20160623093055_use_trash_proxy_view/upgrade.py
opengever/meeting/profiles/default/types/opengever.meeting.meetingdossier.xml
opengever/tabbedview/browser/bumblebee_gallery.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/helper.py
opengever/tabbedview/interfaces.py
opengever/tabbedview/tests/test_bumblebee_gallery.py

This PR implements the Gallery-View for the Trash-Tab.
closes #1814

Add gallery view for trash tab

---

docs/HISTORY.txt

and fixed underline for the 4.10.0 chapter
@lukasgraf

Update changelog after 4.9.1 backport release.

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js
sources.cfg

https://github.com/4teamwork/ftw.showroom/pull/31
This PR configures an offset for the showroom overlay when opened from a (batched) document listing.
Closes #1874.

Configure offset for showroom overlay in document listing.

---

opengever/contact/upgrades/20160630155228_add_sql_model_for_new_contact_implementation/upgrade.py

Because the profile `opengever.contact` is already installed, we had to hardcode the current model in to the upgradestep, otherwise the upgradestep doesn't work with feature changes on the model.
Fixes #2008 

Fixed contact SQLModel creation upgradestep.

---

docs/HISTORY.txt
opengever/contact/models/__init__.py
opengever/contact/models/contact.py
opengever/contact/models/participation.py
opengever/contact/models/participation_role.py
opengever/contact/tests/test_participation.py
opengever/contact/upgrades/20160707151808_add_participation_model/upgrade.py
opengever/testing/builders/sql.py

This PR adds the model to let contacts participate in dossiers.
Closes #1934

Add participation model

---

docs/HISTORY.txt
opengever/base/browser/search.pt
opengever/base/browser/search.py
opengever/base/tests/test_search.py
opengever/bumblebee/browser/resources/bumblebee.js
sources.cfg

Dieser PR passt das Markup für das neue Feature in https://github.com/4teamwork/ftw.showroom/issues/23 an.
Todo:
closes #1846

Fixt falsche Nummerierung in Overlay bei Suchergebnissen

---

docs/HISTORY.txt
opengever/bumblebee/browser/configure.zcml
opengever/bumblebee/browser/open_pdf.py
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/events.py
opengever/bumblebee/interfaces.py
opengever/bumblebee/tests/test_overlay_adapter_document.py
opengever/bumblebee/tests/test_overlay_adapter_mail.py
opengever/journal/handlers.py
opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/opengever.journal.pot
opengever/journal/tests/test_bumblebee_events.py

Add a redirector view that creates journal entries when downloading PDFs from bumblebee.
Closes #2019.

Journalisierung PDF-Download

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/resources/bumblebee.js
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/interfaces.py
opengever/bumblebee/tests/test_overlay_adapter_document.py
opengever/bumblebee/tests/test_overlay_view.py

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/444, https://github.com/4teamwork/ftw.showroom/pull/35
Closes https://github.com/4teamwork/opengever.core/issues/2011
Closes https://github.com/4teamwork/opengever.core/issues/1834

Adjust overlay according to customer feedback

---

docs/HISTORY.txt
opengever/document/tests/test_document_link_widget.py
opengever/document/widgets/document_link.pt
opengever/document/widgets/document_link.py
opengever/dossier/tests/test_documents_tab.py
opengever/dossier/tests/test_overview.py
opengever/dossier/tests/test_trash_tab.py

Change document linking to document overview, instead of the bumblebee overlay.

---

docs/HISTORY.txt
opengever/base/browser/resources/tooltip.js
opengever/bumblebee/browser/resources/bumblebee.js
opengever/document/widgets/document_link.pt
opengever/document/widgets/tooltip.pt

Link preview-thumbnail in the document toolip to the bumblebee overlay.

---

docs/HISTORY.txt
opengever/contact/browser/configure.zcml
opengever/contact/browser/layout.py
opengever/contact/browser/organization.py
opengever/contact/browser/templates/organization.pt
opengever/contact/browser/templates/person.pt
opengever/contact/contactfolder.py
opengever/contact/interfaces.py
opengever/contact/models/organization.py
opengever/contact/tests/test_organization.py
opengever/contact/tests/test_organization_unit.py
opengever/contact/tests/test_organization_view.py
opengever/contact/tests/test_person_view.py
opengever/contact/wrapper.py

- Add organization view closes #1933
- Link persons and organizations to the corresponding detail view
@deiferni 
Styling in [separate PR](https://github.com/4teamwork/plonetheme.teamraum/pull/447) in plonetheme.teamraum.

Add first version of the organization view.

---

docs/HISTORY.txt
opengever/document/behaviors/metadata.py
opengever/document/tests/test_document.py

Fix FileOrPaperValidator in case where the file gets removed in the edit form.

---

docs/HISTORY.txt
opengever/base/utils.py
opengever/contact/browser/configure.zcml
opengever/contact/browser/mail.py
opengever/contact/browser/person.py
opengever/contact/browser/resources/contact.js
opengever/contact/browser/templates/person_edit.pt
opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/opengever.contact.pot
opengever/contact/models/contact.py
opengever/contact/models/mailaddress.py
opengever/contact/profiles/default/jsregistry.xml
opengever/contact/tests/test_mail_addresses_view.py
opengever/contact/upgrades/20160718132536_add_contact_js/jsregistry.xml
opengever/contact/upgrades/20160718132536_add_contact_js/upgrade.py
opengever/meeting/browser/resources/meeting.js
sources.cfg

🚧   MERGE https://github.com/4teamwork/plonetheme.teamraum/pull/448 FIRST 🚧 
Dieser PR fügt das E-Mailformular im Edit-Form einer Person hinzu.
TODO:

Emailformulare für Personen

---

opengever/meeting/browser/resources/meeting.js

Unfortunately the fix #2052 have been reverted from a earlier pullrequest #2038.
So we have to reapply it.
@lukasgraf

Reapply fix sticky heading in order to a refactoring of the baseclass.

---

docs/api/authentication.rst
docs/api/basics.rst
docs/api/batching.rst
docs/api/docs_changelog.rst
docs/api/examples/index.rst
docs/api/examples/login.json
docs/api/examples/login_renew.json
docs/api/examples/logout.json
docs/api/examples/search.json
docs/api/index.rst
docs/api/searching.rst

Some more updates to API docs:
- Remove generated index, it's hardly useful
- Add chapter "Suche"
- Include section about JWT Tokens in `Authentication` chapter
- Extract authentication into its own chapter

Update API docs some more

---

sources.cfg

See https://github.com/4teamwork/ftw.tabbedview/pull/54, https://github.com/4teamwork/plonetheme.teamraum/pull/446

Checkout ftw.tabbedview

---

opengever/document/browser/overview_templates/overview.pt
opengever/document/tests/test_bumblebee.py

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/456.
Closes #2104.

Increase thumbnail size on document overview.

---

opengever/base/default_values.py

Before the `get_persisted_value_for_field()` function assumed that there would only ever be `AttributeStorage` or `AnnotationStorage` in play.
However, since we're also using other custom storages, we need to deal with those as well.
The new function docstring basically describes how we need to handle those:
> What we need to do here is basically to decide whether the storage implementation used for the given field on this context has any **fallbacks** (to default or missing value) in place. If it does, we need to **bypass** them and only return the actually persisted value, or raise an AttributeError.
@phgross

Handle non-standard storages in get_persisted_value_for_field()

---

docs/HISTORY.txt
opengever/contact/browser/organization_listing.py
opengever/contact/browser/person_listing.py
opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/opengever.contact.pot
opengever/contact/tests/test_person_listing.py
opengever/tabbedview/helper.py

Besides I extract and improve the linked method in contact listings to a separate tabbeview helper, which now also prevent XSS.
@lukasgraf

Add organizations column to the person listing.

---

docs/HISTORY.txt
opengever/contact/browser/organization.py
opengever/contact/browser/person.py
opengever/contact/browser/templates/organization.pt
opengever/contact/browser/templates/person.pt
opengever/contact/tests/test_organization_view.py
opengever/contact/tests/test_person_view.py

This PR sorts the person listing in the organization detail view and the organization listing in the person detail view alphabetically.
@lukasgraf

Sort related persons and organizations alphabetically in contact detail views.

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js
sources.cfg

Closes https://github.com/4teamwork/opengever.core/issues/2111

[showroom] Support ftw.showroom 1.2.2 version

---

docs/HISTORY.txt
opengever/meeting/browser/resources/protocol.js

The synchronizer is not able to handle the same event twice.
So refresh the pin items in the trix synchronizer callback instead of creating a new synchronizer.

Fix hint for local changes

---

opengever/examplecontent/contacts.py

Data for example content is chosen randomly, so errors were not triggered immediately 🙈 .

Fix an indentation error in setup.

---

docs/HISTORY.txt
opengever/document/widgets/configure.zcml

Fixed permission declaration for the documents tooltip view.

---

docs/HISTORY.txt
opengever/contact/browser/templates/organization.pt
opengever/contact/browser/templates/person.pt
opengever/contact/models/contact.py
opengever/contact/tests/test_organization_view.py
opengever/contact/tests/test_person_view.py

- Link mail addresses and URLs 
- Only display archived-info collapsible header if archived information exists.
@deiferni

Contact detail views improvements

---

docs/HISTORY.txt
opengever/contact/tests/test_vocabularies.py
opengever/contact/vocabularies.py

Prevent creating participations for inactive contacts.

---

docs/HISTORY.txt
opengever/contact/browser/configure.zcml
opengever/contact/browser/participations.py
opengever/contact/models/org_role.py
opengever/contact/models/participation.py
opengever/contact/tests/test_participation.py

Include OrgRole participations in organizations and persons participation listing

---

docs/HISTORY.txt
opengever/contact/browser/organization_listing.py
opengever/contact/browser/person_listing.py
opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/opengever.contact.pot
opengever/contact/models/contact.py
opengever/contact/tests/test_archive_tables.py
opengever/contact/tests/test_organization_listing.py
opengever/contact/tests/test_person_listing.py
opengever/contact/upgrades/20160914150923_add_former_contact_id_column/upgrade.py
opengever/contact/vocabularies.py

https://basecamp.com/2768704/projects/12330648/todos/270859677

Add new column former contact id to the contact listings.

---

opengever/advancedsearch/locales/fr/LC_MESSAGES/opengever.advancedsearch.po
opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po

As discussed, won't squash this for now.

Weblate translations

---

docs/HISTORY.txt
opengever/policytemplates/hooks.py

and without any templates.
@deiferni

Fix policytemplate when creating a policy with disabled meeting feature

---

docs/HISTORY.txt
opengever/base/browser/resources/Controller.js
opengever/base/browser/resources/MessageFactory.js
opengever/base/browser/resources/tooltip.js
opengever/base/browser/resources/trix-custom.js
opengever/meeting/browser/meetings/agendaitem.py
opengever/meeting/browser/resources/meeting.js
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

⚠️  Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/462
Closes https://github.com/4teamwork/opengever.core/issues/1990
This new behaviour of the controller makes it possible to turn a button in a loading button.

Add loading option to controller

---

docs/HISTORY.txt
opengever/contact/models/mailaddress.py
opengever/contact/models/phonenumber.py
opengever/contact/models/url.py
opengever/contact/tests/test_mail_addresses_view.py
opengever/contact/upgrades/20160930155932_make_mail_address_required/upgrade.py
opengever/contact/upgrades/20160930171159_make_url_required/upgrade.py
opengever/contact/upgrades/20160930173828_make_phone_number_required/upgrade.py

Make mailaddress, url and phone_number required

---

docs/intern/kurzreferenzen/administration.rst

This PR updates the documentation with the new doc-properties added in #2186.
The updated documentation is already published and can be viewed online.

Update doc-property documentation, add list of new properties.

---

docs/HISTORY.txt
opengever/journal/tab.py
opengever/journal/tests/test_journal_tab.py

Fix sorting in the journal listing.

---

docs/HISTORY.txt
opengever/meeting/browser/proposaloverview_templates/proposaloverview.pt
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py

According to the issue #2085 I've double checked all `tal:content="structure` statements and found this XXS issue.
closes #2085 

Fix XSS vulnerability in proposal overview.

---

docs/HISTORY.txt
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob

Add bumblebee-flag option to policytemplates.

---

opengever/meeting/tabs/proposallisting.py
sources.cfg

Prepare the workflow state cells for styling

Mark workflow state with css classes

---

docs/HISTORY.txt
opengever/dossier/browser/overview.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_overview.py

This also fixes #2250.
@deiferni

Add participations box implementation to dossier overview for the new contact implementation.

---

docs/HISTORY.txt
opengever/journal/tab.py
opengever/journal/tests/test_journal_tab.py

Filtering now also works properly for `comments` and `actor` fields.

Fix filter box for journal entries

---

docs/HISTORY.txt
opengever/bumblebee/browser/resources/bumblebee.js
opengever/document/browser/overview_templates/overview.pt

Closes https://github.com/4teamwork/opengever.core/issues/2262

Fix document preview size

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/interfaces.py
opengever/bumblebee/tests/test_overlay_view.py
opengever/bumblebee/upgrades/20161108092305_add_link_options/registry.xml
opengever/bumblebee/upgrades/20161108092305_add_link_options/upgrade.py

* Adds a registry attribute into IGeverBumblebeeSettings for opening links to PDF files in a new tab/window
* Adds tests for the view
* Implements the new view functionality
Fixes #2213

Add configuration option to open links to PDF files in a new tab/window

---

docs/HISTORY.txt
docs/public/api/schemas/ftw.mail.mail.inc
docs/public/api/schemas/opengever.document.document.inc
docs/schema-dumps/ftw.mail.mail.json
docs/schema-dumps/opengever.document.document.json
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/opengever.dossier.pot

* Gettext locale update
* Api schema regeneration
* Documentation regeneration
Fixes #2211

Update the german localization for opengever.document help_document_date

---

docs/HISTORY.txt
opengever/meeting/browser/templates/macros.pt
opengever/task/tests/test_response_descriptions.py
opengever/task/tests/test_workflow.py
opengever/task/viewlets/actionmenu_templates/actionmenuviewlet.pt

Closes https://github.com/4teamwork/plonetheme.teamraum/issues/469
⚠️  Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/476

Prepare HTML for flat buttons

---

docs/HISTORY.txt
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py

Fix dossier links in proposal overviews.
Fixes #2260

Fix dossier link escape issues in the overview.

---

opengever/meeting/tests/test_toc.py
opengever/meeting/toc/alphabetical.py

This somehow got lost, but is a crucial requirement for https://github.com/4teamwork/opengever.core/pull/2273.

Query agenda-items based on their date.

---

opengever/task/viewlets/actionmenu_templates/actionmenuviewlet.pt

> Changelog entry not necessary (its a fix of a previous commit)

Prepare HTML stucture of actionbutton

---

docs/public/api/schemas/ftw.mail.mail.inc
docs/public/api/schemas/opengever.document.document.inc
docs/schema-dumps/ftw.mail.mail.schema.json
docs/schema-dumps/opengever.document.document.schema.json

- field `archival_file_state` has been added to documentish types
- label for `archival_file` has been changed.

Update schema dumps after merging 'disposition' feature.

---

opengever/base/schemadump/__init__.py
opengever/base/schemadump/schema.py

Some small refactorings to the schema dump stuff, before I implement more features.

Refactor schema dump code a bit

---

docs/schema-dumps/oggbundle/documents.schema.json
docs/schema-dumps/oggbundle/dossiers.schema.json
docs/schema-dumps/oggbundle/repofolders.schema.json
docs/schema-dumps/oggbundle/reporoots.schema.json
opengever/base/schemadump/__init__.py
opengever/base/schemadump/config.py
opengever/base/schemadump/helpers.py
opengever/base/schemadump/schema.py
setup.py

This is a basic implementation of JSON schema dumps that describe the content types that make up an OGGBundle.
@deiferni

Create JSON schema dumps for OGGBundle.

---

docs/HISTORY.txt
opengever/core/testing.py
opengever/meeting/configure.zcml
opengever/tabbedview/browser/personal_overview.pt
opengever/testing/configure.zcml
sources.cfg

* Fixed missing i18n_domain related UserWarnings
* Squelched log levels DEBUG and INFO from bleeding onto the test output
* Added changelog entries
Fixes #2288

Clean up test output

---

docs/HISTORY.txt
opengever/disposition/browser/latex_templates/removal_protocol.tex
opengever/disposition/browser/overview.py
opengever/disposition/browser/removal_protocol.py
opengever/disposition/disposition.py
opengever/disposition/history.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_overview.py
opengever/disposition/tests/test_removal_protocol.py
opengever/disposition/validators.py
opengever/latex/listing.py
opengever/latex/tests/test_listing.py

Closes #2347 
Styling: https://github.com/4teamwork/plonetheme.teamraum/pull/485
@deiferni

Add removal protocol PDF export for dispositions.

---

opengever/base/behaviors/translated_title.py
opengever/base/schemadump/schema.py
opengever/base/tests/test_translated_title.py
opengever/setup/sections/constructor.py
opengever/setup/sections/resolveguid.py
opengever/setup/tests/__init__.py
opengever/setup/tests/test_section_constructor.py
opengever/setup/tests/test_section_resolveguid.py
opengever/setup/transmogrifier.zcml
opengever/testing/__init__.py

See https://github.com/4teamwork/opengever.core/issues/2308.
This PR adds a transmogrifier section that constructs instances.
*CL will follow in a later PR*

Add custom constructor section for oggbundle.

---

docs/HISTORY.txt
opengever/journal/configure.zcml
opengever/journal/handlers.py
opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/opengever.journal.pot
opengever/journal/tests/test_zipexport_events.py
sources.cfg

* Use the new export events from ftw.zipexport
* Make use of the new write whitelisting from ftw.journal
* Add journal entries into
* Originating / calling Dossier (AKA 'the view from which this triggers')
* Each file exported
Fixes #2212

Journalize ZIP downloads of Dossiers

---

docs/HISTORY.txt
opengever/policy/base/profiles/default/registry.xml
opengever/policy/base/upgrades/20161206170627_add_tasks_as_zip_exportables/registry.xml
opengever/policy/base/upgrades/20161206170627_add_tasks_as_zip_exportables/upgrade.py
opengever/task/tests/test_overview.py

* Create an upgrade step for the zipexport interface setting
* Add the interface
* Add tests for the export actions being there

Enable zip exports for tasks.

---

sources.cfg

In preparation of the upcoming release.

Remove released packages from sources

---

docs/HISTORY.txt
opengever/contact/browser/byline.py
opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po
opengever/contact/locales/opengever.contact.pot
opengever/contact/tests/test_byline.py

Display former contact id in the byline of contacts.

---

docs/public/api/schemas/ftw.mail.mail.inc
docs/public/api/schemas/opengever.document.document.inc
docs/schema-dumps/_opengever.contact.models.Address.schema.json
docs/schema-dumps/_opengever.contact.models.MailAddress.schema.json
docs/schema-dumps/_opengever.contact.models.OrgRole.schema.json
docs/schema-dumps/_opengever.contact.models.Organization.schema.json
docs/schema-dumps/_opengever.contact.models.Person.schema.json
docs/schema-dumps/_opengever.contact.models.PhoneNumber.schema.json
docs/schema-dumps/_opengever.contact.models.URL.schema.json
docs/schema-dumps/_opengever.ogds.models.group.Group.schema.json
docs/schema-dumps/_opengever.ogds.models.user.User.schema.json
docs/schema-dumps/opengever.contact.contact.schema.json
opengever/base/schemadump/config.py
opengever/base/schemadump/field.py
opengever/base/schemadump/schema.py

This PR includes the string length constraints of all fields in schema dumps.
Closes #2364.

Inlcude string length contraints in schema dumps

---

docs/HISTORY.txt
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/tests/test_dossier_listing.py

and hide it for subdossier listings. Fixes #2390

Show expired filter for managers and record managers only

---

sources.cfg

Closes https://github.com/4teamwork/opengever.core/issues/2440

Checkout plonetheme teamraum

---

docs/HISTORY.txt
opengever/document/base.py
opengever/document/browser/overview.py
opengever/dossier/browser/configure.zcml
opengever/dossier/browser/overview.py
opengever/dossier/browser/tabbed.py
opengever/dossier/dossiertemplate/behaviors.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/dossiertemplate/tabs.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/profiles/default/types/opengever.dossier.dossiertemplate.xml
opengever/dossier/templatedossier/tabs.py
opengever/dossier/tests/test_dossier_template.py
opengever/dossier/tests/test_overview.py
opengever/dossier/upgrades/20161208173649_add_tabbed_view_as_default_view_for_dossier_template/types/opengever.dossier.dossiertemplate.xml
opengever/dossier/upgrades/20161208173649_add_tabbed_view_as_default_view_for_dossier_template/upgrade.py
opengever/tabbedview/tests/test_bumblebee_gallery.py

Dieser PR fügt dem Typ `Dossiertemplate` die Tabbedview hinzu:
closes #2359 
see #2143

Fügt einem Dossiertemplate die Tabbedview hinzu

---

opengever/base/viewlets/footer.pt

Footer: Spell our own domain name right

---

opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/deployment-theta-+base.deployment_number+-+base.domain+.cfg.bob
opengever/policytemplates/policy_template/opengever.+package.name+/deployment-theta-XX-+base.domain+.cfg.bob
opengever/policytemplates/policy_template/opengever.+package.name+/development.cfg.bob

- add bumblebee configuration when bumblebee feature is selected
- ask for deployment number, used in deployment file name and deployment number configuration

Extend policy template

---

sources.cfg

Drop released product from sources.

---

docs/HISTORY.txt
opengever/base/viewlets/footer.pt

Review and update footer links so that they point to onegovgever.ch where it makes sense.
Also fixed some minor things.

Update footer links.

---

docs/intern/development/index.rst
docs/intern/glossar.rst
docs/intern/index.rst
docs/intern/kurzreferenzen/bumblebee.rst
docs/intern/kurzreferenzen/index.rst
docs/intern/meta.rst
docs/intern/operations/index.rst
docs/intern/operations/saas.rst
docs/intern/releasemanagement/index.rst
opengever/base/schemadump/config.py

This PR adds a short description about our SaaS deployments on `theta` and on how to update them on the server.

Fix docs and short SaaS/theta update description

---

README.rst

Use brew services to start the postgres db

Updates the README SQL Database section

---

docs/HISTORY.txt
opengever/disposition/browser/excel_export.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_excel_export.py

Fix label translation and improve readability of the values in appraisal column in the excel export of a disposition.
Closes #2512

Disposition excel export improvments

---

opengever/bundle/report.py

This includes more metadata fields in the XLSX report:
**Repofolders**
- Parent GUID
- Description
- Full reference number
**Dossiers**
- Parent GUID
- Full reference number
- Responsible
- Description
- Start
- End
- Review state
**Documents / Mails**
- Parent GUID
- Filename
- Document date
@deiferni

OGGBundle reports: Extend metadata with more fields.

---

docs/public/user-manual/glossary.rst

Glossar erweitert (insgesamt rund 80 Begriffe, von Thomas S.).

Erweiterungen Glossar von TS eingebaut.

---

docs/HISTORY.txt
opengever/dossier/dossiertemplate/form.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot

First step:
Second step:
closes #2559

Rename dossiertemplate wizard button from "save" to "continue".

---

docs/HISTORY.txt
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot

Adjust german translation for dossier template

---

docs/HISTORY.txt
opengever/dossier/browser/save_comments_entpoint.py
opengever/dossier/tests/test_dossier_byline.py

Reindex SearchableText (dossier) after changing the comment thru the overlay

---

docs/HISTORY.txt
opengever/disposition/browser/overview.py
opengever/disposition/browser/templates/overview.pt
opengever/disposition/tests/test_overview.py
opengever/repository/repositoryfolder.py
opengever/repository/tests/test_repositoryfolder.py

- Sort repositories alphabetically (on the basis of the reference number)
- Display the archival_value for each repository
- Display dossiers collapsible 
Closes #2515 
Styling: https://github.com/4teamwork/plonetheme.teamraum/pull/499

Disposition overview improvements

---

docs/HISTORY.txt
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/opengever.bumblebee.pot

Translate missing "open detail view" in bumblebee-overlay.

---

opengever/dossier/dossiertemplate/form.py
opengever/dossier/tests/test_dossier_template.py

Fix keywordwidget manipulation from the dossier template wizard.

---

docs/HISTORY.txt
opengever/disposition/browser/removal_protocol.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_removal_protocol.py
sources.cfg

Merge https://github.com/4teamwork/ftw.pdfgenerator/pull/48 first.
The PDF is now named "Removal protocol for {disposition title}".
Closes #2511.

Improve removal protocol title.

---

docs/HISTORY.txt
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/resources/edit_note.js
opengever/dossier/viewlets/templates/note.pt

Needs https://github.com/4teamwork/plonetheme.teamraum/pull/512
Closes #2609 
Closes #2610 
Closes #2611
Closes #2612 
Closes #2613
Closes #2614
Closes #2615

Several improvments according to the feebdack of @phabegger

---

opengever/bundle/report.py

Pure refactoring of XLSX report generation classes.

Refactor XLSX report classes in OGGBundle reports.

---

docs/HISTORY.txt
opengever/document/static/officeconnector.js

Remove an unnecessary JSON parse step from OC JS.

---

docs/public/user-manual/glossary.rst

Ph glossary ergaenzung

---

docs/HISTORY.txt
opengever/bundle/cfgs/oggbundle.cfg
opengever/bundle/loader.py
opengever/bundle/report.py
opengever/bundle/sections/post_import_validation.py
opengever/bundle/sections/resolveguid.py
opengever/bundle/tests/test_section_resolveguid.py
opengever/bundle/transmogrifier.zcml

Validate max nesting depth for repositoryfolders and dossiers. Failure to validate will be logged in validation report, but otherwise doesn't affect import.
@deiferni

OGGBundle import: Validate max nesting depth

---

opengever/document/configure.zcml
opengever/document/forms.py
opengever/document/tests/test_forms.py

Implement file upload form for documents

---

docs/public/user-manual/glossary.rst

Add TERMDAT footnotes in glossary as requested by @phabegger
[ci skip]

add footnotes

---

docs/HISTORY.txt
opengever/repository/tests/test_repositoryfolder_byline.py
opengever/repository/viewlets/byline.py

Display archival value in the repositoryfoder byline.

---

docs/HISTORY.txt
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

Set preserved as paper to false for generated journal pdfs.

---

docs/HISTORY.txt

This is only for CL entires way down the line, so should not conflict 🙏 .

Bring latest releases' CL entries home to mama.

---

docs/HISTORY.txt
opengever/dossier/activate.py
opengever/dossier/base.py
opengever/dossier/resolve.py
opengever/dossier/tests/test_activate.py
opengever/dossier/tests/test_reactivate.py

Closes #2667
Additional I've added missing tests for the dossier reactivation.

Reset end date when reactivate a resolved or activate an inactive dossier.

---

docs/HISTORY.txt
opengever/document/events.py
opengever/document/interfaces.py
opengever/document/subscribers.py
opengever/journal/configure.zcml
opengever/journal/handlers.py
opengever/journal/locales/de/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/journal/locales/opengever.journal.pot
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api.py

* Interface
* Event
* Handler
* ZCML registration
* Notify from the the `plone.rest` service
* i18n
* Tests
Closes #2717

Add a journal event for attaching documents to emails via OfficeConnector

---

docs/HISTORY.txt
opengever/dossier/browser/overview.py
opengever/dossier/tests/test_overview.py
opengever/private/tests/test_dossier.py

Show keywords on overview tab.

---

docs/HISTORY.txt
setup.py

Next release will be 2017.1.0.

---

.gitignore
opengever/private/viewlets/configure.zcml
test-docs-public.cfg
test-xml-convention.cfg

~~wait for https://github.com/4teamwork/ftw-buildouts/pull/72~~
This PR adds tests that assert that the xml code-conventions are met.

Add tests for xml convention.

---

opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/resources/edit_note.js
opengever/dossier/viewlets/templates/note.pt

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/521
Closes #2755

Dossier note: Aufofocus + Delete button

---

opengever/base/viewlets/footer.pt

Adjust footer-viewlet links.
Adjust footer-viewlet left. It affects all the installations, not only new ones
closes #2769

Adjust footer viewlet links

---

opengever/bumblebee/converter.py
opengever/bumblebee/overrides.zcml

Don't attempt to store versions for mails, mails should not have
versions ever. In some cases they do nevertheless and then iterating
over versions may fail utterly.

Don't store versions for mails, ever.

---

docs/public/user-manual/glossary.rst

Added "free decimal classification" or in german "freie Zehnergliederung" to the glossary

add one term to glossary

---

opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/plone.pot

Add missing translation for the journal entry when offering a dossier

---

docs/public/admin-manual/aussonderung.rst

Update documentation about configuration possiblities in the disposition process

---

docs/HISTORY.txt
opengever/disposition/browser/templates/overview.pt
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot

Disposition overview: Differs beetween singular/plural on the dossier(s) label.

---

docs/HISTORY.txt
opengever/base/browser/resources/tooltip.js
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/document/browser/templates/file.pt
opengever/document/static/officeconnector.js
opengever/document/widgets/tooltip.pt
opengever/officeconnector/tests/test_templates.py

Fix tooltip overlay links and simplify OfficeConnector JS

---

.gitattributes
README.rst
docs/HISTORY.txt

Merge-Konflikte im Changelog sind mühsam, da oft deswegen alle Pull-Requests rebased werden müssen. Die lange Testdauer macht das ganze noch mühsamer.
Daher möchte ich erneut die `union`-Merge-Strategy thematisieren, die wir bereits in #1265 eingeführt und in #1329 wieder entfernt haben. Das Problem war, dass nach einem automatischen Merge die leeren Zeilen gefehlt haben, sowie der Autor (`[name]`), wenn der Autor mehrere aufeinanderfolgende Einträge gemacht hat.
Diese Probleme lösen wir, indem wir das Format des Changelogs ändern, sowie die Regeln wie neue Einträge gemacht werden.
Daher enthält dieser Pull-Request:
- Aktivierung der `union`-Merge-Strategy für `docs/HISTORY.txt`
- Dokumentation in README, wie neu das Changelog gepflegt werden muss
- Umformatierung aller Einträge der …

Merge-Konflikte in Changelog verhindern

---

docs/HISTORY.txt
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py
opengever/latex/dossierjournal.py
opengever/latex/listing.py
opengever/latex/locales/de/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/fr/LC_MESSAGES/opengever.latex.po
opengever/latex/locales/opengever.latex.pot
opengever/latex/tests/test_dossierjournal.py

Adjust title and label of dossiers journal PDF representation.

---

docs/HISTORY.txt
opengever/disposition/browser/latex_templates/removal_protocol.tex
opengever/disposition/browser/removal_protocol.py
opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
opengever/disposition/locales/opengever.disposition.pot
opengever/disposition/tests/test_removal_protocol.py

 Improve title and TeX template for removal protocol

---

docs/HISTORY.txt
opengever/base/viewlets/footer.pt

This PR adds the API-link to the footer viewlet.
closes #2803

Add api-link to footer viewlet.

---

docs/HISTORY.txt
opengever/officeconnector/service.py
opengever/officeconnector/tests/test_api.py

* Add the document title to the OC attach payloads

Add the document title to the OC attach payloads

---

docs/HISTORY.txt
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot

Closes #2842.
See #2795 for further information.

Update and fix recently changed translation for the Journal PDF translation.

---

opengever/latex/profiles/default/actions.xml
opengever/latex/upgrades/20170412152602_don_t_show_pdf_actions_on_private_dossier/actions.xml
opengever/latex/upgrades/20170412152602_don_t_show_pdf_actions_on_private_dossier/upgrade.py
opengever/private/tests/test_dossier.py

No longer show export as pdf actions on private dossiers.

---

opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/tasktemplates/locales/de/LC_MESSAGES/opengever.tasktemplates.po

Some more minor translation fixes.
I'll update already existing translations afterwards using the Weblate UI.

Fix some more minor translation issues

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/service.py
opengever/base/tests/test_api.py

Added a document status JSON REST endpoint

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/document/browser/actionbuttons.py
opengever/document/browser/download.py
opengever/document/browser/overview.py
opengever/document/browser/versions_tab.py
opengever/document/tests/test_download.py
opengever/mail/tests/test_mail_download_copy.py

Fix mail downloads by demanding a context to be passed into DC helpers.

---

opengever/base/portlets.py
opengever/contact/configure.zcml
opengever/contact/handlers.py
opengever/contact/tests/test_contactfolder.py
opengever/contact/upgrades/20170502101517_ensure_portlet_configuration_for_contactfolders/upgrade.py
opengever/dossier/templatefolder/configure.zcml
opengever/dossier/templatefolder/subscribers.py
opengever/dossier/tests/test_templatefolder.py
opengever/dossier/upgrades/20170502101926_ensure_portlet_configuration_for_templatefolders/upgrade.py
opengever/examplecontent/hooks.py
opengever/inbox/configure.zcml
opengever/inbox/subscribers.py
opengever/inbox/tests/test_inbox.py
opengever/inbox/tests/test_inbox_container.py
opengever/inbox/upgrades/20170502101718_ensure_portlet_configuration_for_inboxes_and_inboxcontainers/upgrade.py
opengever/meeting/configure.zcml
opengever/meeting/handlers.py
opengever/meeting/tests/test_committee_container.py
opengever/meeting/upgrades/20170502104540_ensure_portlet_configuration_for_committeecontainers/upgrade.py
opengever/policy/base/upgrades/20160923114424_install_opengever_private/upgrade.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/hooks.py.bob
opengever/private/configure.zcml
opengever/private/subscribers.py
opengever/private/tests/test_root.py
opengever/private/upgrades/20170502101306_ensure_portlet_configuration/upgrade.py
opengever/setup/hooks.py
opengever/setup/profiles.zcml
opengever/testing/test_case.py

Currently the portlet configuration of default content is done in profilehooks. Wich has been copied all over the policies. 
This PR fix this situation, by adding EventHandlers for content with a special portlet configuration. So it doesn't matter if the content is created by og.setup, OGGBundle or the API the portlet configuration is always as expected. Closes #1214
Short overview:
**Personal overview**: No context assignments, Inheritance active
**Inbox**: Navigation portlet, Inheritance blocked
**InboxContainer**: Navigation portlet, Inheritance blocked
**TemplateFolder**: Navigation portlet, Inheritance blocked
**Sub-TemplateFolder**: No context assignments, Inheritance active
**Contactfolder**: No context assignments, Inheritance blocked
**Sitzungen**: No context assignments, …

Ensure portlet configuration for default content

---

opengever/base/subscribers.py

The bin/upgrade command line tool does not authorize via PAS and thus
issues anonymous request which are later authorized.
Therefore the request must be allowed in our anonymous request
protection.

Allow upgrades-api access through command line tool.

---

docs/HISTORY.txt
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_close.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposalhistory.py

Fix typo in method name: resolve_sumitted_proposal -> resolve_submitted_proposal

---

docs/HISTORY.txt
opengever/meeting/committeeroles.py
opengever/meeting/tests/test_committee_roles.py
opengever/meeting/upgrades/20170516133120_fix_local_roles_string_type/upgrade.py
opengever/testing/builders/dx.py

Fix local roles string type

---

development.cfg
opengever/base/browser/templates/gever-macros.pt

Chameleon seems to have nuancedly different ideas of how the i18n namespacing propagates. No idea as to why, will ask the author. Fixed the issue at hand for now.
This pull request also properly enables chameleon for development.

Chameleon i18n difference fixes

---

docs/HISTORY.txt
setup.py

and update changelog after hotfix release 2017.2.2.

Bump version of next release to 2017.3.0

---

development.cfg
sphinx-standalone.cfg
sphinx.cfg

See https://github.com/4teamwork/ftw-buildouts/pull/81 and https://github.com/4teamwork/gever-buildouts/pull/19.
Cleanup the buildout a but, bit not yet able to make sure the parts += stuff actually works without re-including lost parts. Hopefully might get there in another step though.

Cleanup buildout, attempt to work around extends problem. 

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/resources/bumblebee.js
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/opengever.bumblebee.pot
opengever/bumblebee/tests/test_overlay_view.py
opengever/core/profiles/default/cssregistry.xml
opengever/core/upgrades/20170601103051_remove_default_showroom_styles/cssregistry.xml
opengever/core/upgrades/20170601103051_remove_default_showroom_styles/upgrade.py
sources.cfg

Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/536
Depends on https://github.com/4teamwork/ftw.showroom/pull/44
Closes https://github.com/4teamwork/opengever.ftw/issues/21
Closes #2893
Screenshots der finalen Umsetzung:

Improve visual search

---

docs/HISTORY.txt
opengever/dossier/tests/test_templatefolder.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/tests/test_document_listing.py

Reference column in documents listings

---

docs/HISTORY.txt
opengever/dossier/templatefolder/form.py
opengever/dossier/tests/test_templatefolder.py

Do not list templates without a file in the document from template form

---

docs/HISTORY.txt
opengever/base/configure.zcml
opengever/base/redirector.py
opengever/base/tests/test_redirector.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20170621113908_include_redirector_etag_to_cache_rules/registry.xml
opengever/core/upgrades/20170621113908_include_redirector_etag_to_cache_rules/upgrade.py

Flush cache when preparing a download via Redirector adapter.
Fixes #3026

Implement and enable redirector eTag adapter.

---

docs/HISTORY.txt
opengever/meeting/tests/test_toc.py
opengever/meeting/toc/alphabetical.py

This PR fixes an issue with TOCs and limits the results to a committee instead of always displaying all agenda-items.

Fix meeting TOC, correctly limit TOC to committee.

---

opengever/repository/tests/test_repository_root.py
opengever/repository/tests/test_repository_workflow.py
opengever/testing/fixtures.py

Provide the site owner as ``self.manager`` in integration test cases.

Testing: provide self.manager as site owner.

---

docs/HISTORY.txt
opengever/journal/entry.py
opengever/journal/tests/test_journal_tab.py

Resolves: https://github.com/4teamwork/opengever.ftw/issues/32

Fix XSS vulnerability for manual journal entries

---

docs/HISTORY.txt
opengever/base/browser/navigation.py
opengever/base/tests/test_navigation.py
opengever/portlets/tree/resources/tree.js
opengever/repository/repositoryfolder.py

Closes https://github.com/4teamwork/opengever.core/issues/2875
- Enrich node data with active state

Provide active state on repository folders tree items.

---

opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/meeting/browser/meetings/templates/meeting.pt
opengever/meeting/browser/memberships.py
opengever/meeting/browser/proposaltransitions.py
opengever/meeting/browser/views.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_members.py
opengever/officeatwork/locales/fr/LC_MESSAGES/opengever.officeatwork.po

Add french translations for `opengever.meeting` and some additional translations in different modules.

French translations update

---

docs/HISTORY.txt
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_sql_task.py
opengever/tabbedview/browser/tabs.py
opengever/tabbedview/browser/tasklisting.py
opengever/tabbedview/helper.py
opengever/tabbedview/tests/test_tasklisting.py
opengever/task/browser/configure.zcml
opengever/task/browser/redirector.py
opengever/task/tests/test_redirector.py

Add links to the containing main dossier and the subdossier of a task in task-listings.
closes #3013

Add dossier and subdossier link in task listings

---

README.rst
development-multi-admin.cfg

This PR adds a buildout to setup a multi-admin development environment.

Add a multi-admin-unit buildout.

---

docs/HISTORY.txt
opengever/dossier/resources/init_tree.js
opengever/portlets/tree/resources/tree.js

Closes https://github.com/4teamwork/opengever.core/issues/3089
Just the selected dossier is expanded with this new behaviour.

Change dossier tree behavior.

---

docs/HISTORY.txt
opengever/mail/browser/mail.py
opengever/mail/browser/templates/file.pt
opengever/mail/tests/test_mail_download_copy.py

Always download MSG file if available.

---

docs/HISTORY.txt
opengever/portlets/tree/resources/tree.js

Closes https://github.com/4teamwork/opengever.core/issues/3129

Expand current subdossier in subdossier tree.

---

docs/HISTORY.txt
opengever/base/browser/configure.zcml
opengever/base/browser/copy_items.py
opengever/base/tests/test_copy_paste.py
opengever/base/tests/test_pasting_allowed.py
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20170718083059_add_copy_action_for_single_documents/actions.xml
opengever/core/upgrades/20170718083059_add_copy_action_for_single_documents/upgrade.py

Please take a look at the tests and let me know if more tests are needed.
The second commit is a mere "translation" from `grok.View` to `BrowserView`.
Resolves: #3058

Copy single documents

---

README.rst

A round of trivialities which caught my eye.

Minor documentation polish

---

opengever/base/locales/de/LC_MESSAGES/plone.po

Harmonize german translation for "info" portal messages.

---

docs/HISTORY.txt

The release has been created from the 2017.3-stable branch.

Cleanup changelog after bugfix release 2017.3.2.

---

docs/HISTORY.txt
opengever/mail/configure.zcml
opengever/mail/tests/test_zip_export.py
opengever/mail/zipexport.py
opengever/testing/fixtures.py

Export msg in OGmail zip representation if the original_message is available.

---

docs/public/_static/disqus.js
docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
docs/public/dev-manual/api/schemas/opengever.contact.contact.inc
docs/public/dev-manual/api/schemas/opengever.document.document.inc
docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc
docs/public/user-manual/aufgaben/index.rst
docs/public/user-manual/dokumente/index.rst
docs/public/user-manual/dossiers/index.rst

- **API docs: Update schemas:**
After the actual schemas (JSON schema `.json` files) have been updated in #3178, the auto-generated `.inc` files in the API docs now also need to be rebuilt :man_facepalming:  
- **Add missing disqus directives to index pages of restructured sections:**
This makes sure customer's comments are included in the same places as they were made before
- **Include customized copy of disqus.js in static folder:**
Needed to fix an issue with disquis JS load order

Minor updates to docs

---

docs/HISTORY.txt
opengever/contact/syncer/object_syncer.py
opengever/contact/tests/test_object_syncer.py

The new implementation does no longer use the ORM but use SQLAlchemy core functionality and  bulk inserts/updates. This leads to a essential performance win.

Reworked contact syncer functionality to reduce duration time

---

docs/HISTORY.txt
opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po

Improve warning when opening an old version of a document

---

README.rst
opengever/testing/tests/test_dump_fixture_structure.py

A test dumps the fixture structure into the readme. When the fixture changes, the test has to be run and the changes in the readme committed.

Testing fixture: auto-document fixture in readme.

---

docs/HISTORY.txt
opengever/base/browser/search.pt

Highlight search terms after fetching new search results per ajax.

---

opengever/activity/browser/configure.zcml
opengever/activity/browser/resolve.py
opengever/activity/configure.zcml
opengever/activity/handlers.py
opengever/activity/model/__init__.py
opengever/base/browser/configure.zcml
opengever/base/browser/resolveoguid.py

⚠️  needs #3239 
This PR removes grok from opengever.activity.
See #3205

Remove grok from opengever.activity

---

opengever/bumblebee/browser/configure.zcml
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/configure.zcml
opengever/bumblebee/document.py
opengever/bumblebee/events.py
opengever/bumblebee/service.py

Ungrok opengever bumblebee

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_helper.py

related to: https://github.com/4teamwork/plonetheme.teamraum/pull/570#pullrequestreview-55457708
closes #3260

Show mimetype-icon of proposaltemplate in bumblebee-listing.

---

docs/HISTORY.txt
opengever/contact/locales/de/LC_MESSAGES/opengever.contact.po

Fix typo in contact detail view.

---

opengever/disposition/browser/configure.zcml
opengever/disposition/browser/removal_protocol.py
opengever/disposition/configure.zcml
opengever/disposition/validators.py
opengever/latex/configure.zcml
opengever/latex/listing.py

related to #3205 
Cross-Discussion in #3264

Ungrok opengever disposition

---

docs/HISTORY.txt
opengever/core/profiles/default/types/opengever.meeting.sablontemplate.xml
opengever/core/upgrades/20170810105607_make_sablon_templates_i_bumblebeeable/types/opengever.meeting.sablontemplate.xml
opengever/core/upgrades/20170810105607_make_sablon_templates_i_bumblebeeable/upgrade.py
opengever/dossier/browser/tabbed.py
opengever/dossier/templatefolder/configure.zcml
opengever/dossier/templatefolder/tabs.py

This PR adds the bumblebee-gallery view to the sablontemplate tab.
closes #3259

Add bumblebee gallery view for sablontemplate.

---

opengever/globalindex/browser/configure.zcml
opengever/globalindex/browser/report.py
opengever/globalindex/configure.zcml
opengever/globalindex/model/__init__.py
opengever/globalindex/model/task.py

Remove grok from opengever.globalindex.

---

opengever/locking/configure.zcml

Remove grok from opengever.locking.

---

opengever/journal/configure.zcml
opengever/journal/handlers.py

Remove grok from opengever.journal.

---

docs/HISTORY.txt
opengever/latex/configure.zcml
opengever/latex/dossiercover.py
opengever/latex/dossierdetails.py
opengever/latex/dossierjournal.py
opengever/latex/dossierlisting.py
opengever/latex/layouts/configure.zcml
opengever/latex/layouts/default.py
opengever/latex/layouts/landscape.py
opengever/latex/opentaskreport.py
opengever/latex/tasklisting.py
opengever/latex/testing.py
opengever/latex/tests/test_dossiercover.py
opengever/latex/tests/test_dossierdetails.py
opengever/latex/tests/test_dossierjournal.py
opengever/latex/tests/test_dossierlisting.py

Remove grok from opengever.latex.

---

test-pyflakes.cfg

I had an errant placment of an echo statement there.
It also now handles the case of 'no unignored python files changed'.

Robusitfy the pyflakes CI script

---

test-pycodestyle.cfg

Only runs for unignored incoming changes.

Add a script to run pycodestyle with our config for incoming changes

---

opengever/sharing/configure.zcml
opengever/sharing/utilities.py

Remove grok from opengever.sharing.

---

bin/pyflakes-ci

@Rotonen just fixed this on my machine and i'll steal the contribution 😈 .

Fix pyflakes-ci script. Correctly call pyflakes with file arguments.

---

docs/HISTORY.txt
opengever/mail/browser/templates/attachments.pt
opengever/mail/browser/templates/extract_attachments.pt
opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
opengever/mail/locales/opengever.mail.pot
opengever/mail/tests/test_mail_overviewtab.py
sources.cfg

* Added a new file action button for extracting mail attachments
* Added a new class to plonetheme.teamraum for the paperclip icon 4teamwork/plonetheme.teamraum#574
* Added a new i18n label for the action
* Could not figure out how to combine with the existing form value hack
* Amended the tests
* Added a changelog entry
Closes #3309

Add a file action button for extracting mail attachments

---

docs/intern/kurzreferenzen/index.rst
docs/intern/kurzreferenzen/ubersetzungen.rst

Vermutlich noch nicht vollständig 😉 , aber vorerst mal alles was mir bekannt ist. Soll als Erinnerungshilfe dienen.

Add simple chapter about the translations to the intern docu.

---

docs/HISTORY.txt
opengever/contentstats/configure.zcml
opengever/contentstats/providers.py
opengever/contentstats/tests/test_content_stats_integration.py

This provider lists **MIME types for files** (of documents and mails).

Add content stats provider for file mimetypes.

---

docs/HISTORY.txt
opengever/meeting/browser/documents/proposalstab.py
opengever/meeting/tests/test_proposal_listings.py

Also display a proposals decision number in the proposal listing.

Display decision number in proposal listings.

---

README.rst
docs/HISTORY.txt
opengever/base/browser/templates/gever-macros.pt
opengever/dossier/base.py
opengever/dossier/browser/overview.py
opengever/dossier/browser/save_comments_entpoint.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/tests/test_overview.py
opengever/meeting/tests/test_meeting_dossier_overview.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Closes #3372
This PR also convert the dossier_overview tests in to IntegrationTests 😅

Format line breaks and links in the dossier overview comment and description box.

---

docs/HISTORY.txt
opengever/core/upgrades/20170919144003_replace_is_subdossier_field_index_with_a_boolean_index/upgrade.py
opengever/dossier/indexers.py
opengever/dossier/tests/test_indexer.py

- Fix and update the is_subdossier replacement upgradestep and change it so that all objects get reindexed.
- Add an additional is_subdossier indexer for dossiertemplates.
Further information and closes #3392

Fix is_subdossier replacement (Field- to BooleanIndex) 

---

docs/HISTORY.txt
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/proposalforms.py

Ungrok proposal add form in order to make subclassing easier.

Ungrok proposal add form.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot

Make sure that transitions and states are all capitalized, so that we have a consistent appeareance.

Consolidate proposal workflow translations.

---

opengever/dossier/behaviors/dossier.py
opengever/dossier/browser/configure.zcml
opengever/dossier/browser/forms.py
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/meetingdossier_forms.py
opengever/meeting/dossier.py
opengever/private/browser/configure.zcml
opengever/private/browser/forms.py
opengever/private/configure.zcml

Remove grok from opengever.private

---

docs/intern/releasemanagement/nicht-entwicklungsarbeiten.rst

...mit neuen Link zu Mailchimp.

Anpassung Prozess Release (nicht technische Anpassung) 

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Resolves https://github.com/4teamwork/gever/issues/121

Fix ad hoc agenda item template label translation

---

opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/committeecontainer.py

A field can still be required when its hidden, but it cannot be required when its omitted. In order to fix the required problem we now omit the fields instead of hiding them.

Omit feature-flaged committee container fields instead of hiding them.

---

docs/HISTORY.txt
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/configure.zcml.bob

This PR ungroks `opengever.plicytemplates`.
related to #3205

Ungrok opengever.policytemplates

---

docs/HISTORY.txt
opengever/base/sqlsyncer.py
opengever/core/upgrades/20171027135623_add_title_columns_to_proposal_sql_model/upgrade.py
opengever/core/upgrades/20171027160114_sync_submitted_proposal_title_to_sql/upgrade.py
opengever/globalindex/handlers/task.py
opengever/meeting/browser/committeetabs.py
opengever/meeting/browser/documents/proposalstab.py
opengever/meeting/configure.zcml
opengever/meeting/handlers.py
opengever/meeting/model/proposal.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_listings.py
opengever/meeting/tests/test_submitted_proposal.py
opengever/tabbedview/sqlsource.py
opengever/testing/builders/dx.py

Allow to filter and sort proposals by their title/submitted_title in proposal listings. The following listings are improved:
- my proposals
- dossier proposal listing
- committee submitted proposal listing
This is implemented by once again syncing the proposal and submitted proposal titles to sql. The sql table should be thought of as a read-only index though, the primary data remains in plone.
The migration consists of two steps, first the model is changed then data is migrated.
_Theoretically this would run on multiple plone sites even though in practice it is not used that way :smile:._
Closes https://github.com/4teamwork/gever/issues/66.
⚠️  Unlocks https://github.com/4teamwork/gever/issues/120.

Allow filtering/sorting by proposal title.

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/tests/test_overlay_view.py
opengever/testing/integration_test_case.py

* Exclude the latest version in the bumblebee versioning warning logic
Closes #3572

Exclude the latest version in the bumblebee versioning warning logic

---

docs/HISTORY.txt
opengever/task/handlers.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/response.py
opengever/task/response_description.py
opengever/task/tests/test_team_tasks.py

Make responsible change, when accepting a team task visible in the response.

---

docs/intern/operations/saas.rst

See also https://github.com/4teamwork/opengever-deployments/pull/8

Add short description about updating policies.

---

docs/HISTORY.txt
docs/schema-dumps/opengever.dossier.businesscasedossier.schema.json
opengever/base/tests/test_default_values_for_types.py
opengever/bundle/schemas/dossiers.schema.json
opengever/core/profiles/default/types/opengever.dossier.businesscasedossier.xml
opengever/core/tests/test_relations.py
opengever/core/upgrades/20171030195512_add_protect_dossier_behavior/types/opengever.dossier.businesscasedossier.xml
opengever/core/upgrades/20171030195512_add_protect_dossier_behavior/upgrade.py
opengever/dossier/behaviors.zcml
opengever/dossier/behaviors/protect_dossier.py
opengever/dossier/browser/forms.py
opengever/dossier/configure.zcml
opengever/dossier/handlers.py
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/tests/test_protect_dossier.py
opengever/ogds/base/sources.py
opengever/ogds/base/tests/test_sources.py
opengever/testing/integration_test_case.py

Dieser PR fügt die "Dossier schützen" Funktion für "Dossier Manager" hinzu.
closes #3491

Ogip 23 issue 3491 extend add and edit form

---

docs/public/user-manual/posteingang.rst

Anpassung Titel Posteingang in Eingangskorb

---

docs/HISTORY.txt
opengever/core/upgrades/20171114104010_add_date_of_submission_to_proposal/upgrade.py
opengever/core/upgrades/20171114105533_get_submission_date_from_proposal_history/upgrade.py
opengever/meeting/browser/createsubmittedproposal.py
opengever/meeting/browser/documents/proposalstab.py
opengever/meeting/browser/rejectproposal.py
opengever/meeting/command.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/proposal.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_listings.py
opengever/meeting/tests/test_submitted_proposal.py

With this PR we add date_of_submission field to proposals (and submitted proposals). Whenever a proposal is submitted the field is automatically set to the current date. When the proposal is rejected the field is emptied again. Also add a new column displaying the date to the following proposal listings:
- in a dossier
- in a committee
- in my proposals
Closes https://github.com/4teamwork/gever/issues/120.

Add date of submission to proposals.

---

README.rst
docs/HISTORY.txt
opengever/bundle/tests/test_oggbundle_pipeline.py
opengever/meeting/browser/committee.py
opengever/meeting/browser/templates/overview.pt
opengever/meeting/committee.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/query.py
opengever/meeting/tests/test_committee_overview.py
opengever/meeting/tests/test_meeting_listings.py
opengever/testing/fixtures.py

Old:
New:
Resolves https://github.com/4teamwork/gever/issues/158

Add concluded meetings to committee overview tab

---

opengever/tasktemplates/tests/test_trigger.py
opengever/testing/fixtures.py

This PR also fixes the currently broken master ...

Fixed and convert TaskTemplateTrigger tests to integration tests.

---

opengever/contact/tests/test_contactfolder.py
opengever/tabbedview/browser/generic_with_filters.pt

Closes #3632, which has been introduced with #3629, therefore there is no changelog.

Fix an issue on catalog listings without a filterlist available

---

opengever/base/upgrades/20170411113233_fix_subject_index__use_unicode_consistently/upgrade.py
opengever/core/upgrades/20170919144003_replace_is_subdossier_field_index_with_a_boolean_index/upgrade.py
opengever/document/upgrades/20160601180404_reindex_object_provides_after_adding_i_bumblebeeable_interface/upgrade.py
opengever/dossier/upgrades/20161125103319_let_archivist_see_offered_and_archived_dossiers/upgrade.py
opengever/dossier/upgrades/20170201140251_update_retention_period_calculation/upgrade.py
opengever/dossier/upgrades/20170301235934_add_new_destroy_dossier_permission/upgrade.py
opengever/dossier/upgrades/20170328131435_set_task_comment_permission/upgrade.py
opengever/mail/upgrades/20160606081024_reindex_object_provides_after_adding_i_bumblebeeable_interface/upgrade.py

In the context of the [planned release](https://github.com/4teamwork/opengever.zug/issues/259)  we reworked or merged some long running  upgradesteps. 
The current branch has been successfully tested on two production copies.

Upgradestep optimizations

---

docs/HISTORY.txt
opengever/meeting/browser/resources/meeting.js
opengever/meeting/model/agendaitem.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_sql_index.py

Resolves https://github.com/4teamwork/gever/issues/160

Fix renaming of agenda items with proposal

---

docs/HISTORY.txt
setup.py

Version and changelog cleanup after hotfix relase 2017.6.5 from `2017.6-stable` branch.

2017.6.5 release cleanup

---

docs/HISTORY.txt
opengever/document/extra_mimetypes.py
opengever/policy/base/profiles/mimetype/mimetypes.xml
opengever/policy/base/upgrades_mimetypes/20171122193716_add_onenote_mimetype/mimetypes.xml
opengever/policy/base/upgrades_mimetypes/20171122193716_add_onenote_mimetype/upgrade.py
opengever/policy/base/upgrades_mimetypes/configure.zcml

The icon will be available with https://github.com/4teamwork/plonetheme.teamraum/pull/598

Add mimetype for MS OneNote.

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_contentlisting.py
opengever/document/tests/test_document_link_widget.py
opengever/dossier/tests/test_documents_tab.py
opengever/dossier/tests/test_dossier_template.py
opengever/dossier/tests/test_trash_tab.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_task_css_class.py
opengever/globalindex/tests/test_task_link.py

And update css classes for special task icons: 
- remote tasks
- subtasks

 Define empty document as mimetype icon empty

---

docs/HISTORY.txt
opengever/core/upgrades/20171113145923_remove_deactivate_state_for_private_dossiers/upgrade.py
opengever/core/upgrades/20171113145923_remove_deactivate_state_for_private_dossiers/workflows/opengever_private_dossier_workflow/definition.xml
opengever/private/tests/test_deactivate_action.py
opengever/private/tests/test_dossier.py

OGIP19: Remove private dossiers' inactive status

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Emasculate meeting participants.

---

docs/schema-dumps/_opengever.ogds.models.group.Group.schema.json

After increasing the group id length (see #3691).

Update ogds group schema dumps.

---

opengever/meeting/browser/meetings/debug.py

Fix unicode error

---

opengever/base/tests/test_anonymous.py
opengever/base/tests/test_base_behavior.py
opengever/base/tests/test_breadcrumb_by_uid.py
opengever/base/tests/test_casauth.py
opengever/base/tests/test_classification.py
opengever/base/tests/test_command.py
opengever/base/tests/test_contentlisting.py
opengever/base/tests/test_copy_paste.py
opengever/base/tests/test_default_view.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py

Should help to shorten the test duration.

Porting a first part of the og.base tests to integrationtests.

---

opengever/contentstats/tests/test_content_stats_integration.py

This test should be on the FunctionalLayer as it is particularly sensitive to changes in the fixture.
I wrote a small "fixture" just for this test and grouped the tests so that the fixture gets executed just once. This makes the test 4 times faster, at the cost of not being able to execute each test separately.
This is part of #3726

Moved test_content_stats_integration to FunctionalLayer.

---

opengever/quota/configure.zcml

Profilemerge seems to have messed with whitespaces.

Fix indent. Entropy seems to have increased :).

---

docs/HISTORY.txt
docs/public/dev-manual/oggbundle/index.rst
opengever/base/schemadump/schema.py
opengever/bundle/report.py
opengever/bundle/schemas/repofolders.schema.json
opengever/bundle/schemas/reporoots.schema.json
opengever/bundle/sections/map_local_roles.py
opengever/bundle/tests/assets/basic.oggbundle/repofolders.json
opengever/bundle/tests/test_oggbundle_pipeline.py

This PR extends the OGGBundler with the `DossierManager` role.
closes #3672

Extend OGGBundle with the DossierManager role.

---

opengever/dossier/tests/test_protect_dossier.py
opengever/repository/tests/test_sharing.py
opengever/testing/integration_test_case.py

Not sure why sharing the repository for reading also gives `DossierManager` rights.

Change repository sharing tests to IntegrationTestCase

---

opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po

resolves https://extranet.4teamwork.ch/support/edk/tracker-support-gever-edk/83

Change french translation for E-mail attachments

---

opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po

Change copy-paste message.

---

docs/HISTORY.txt
opengever/bumblebee/browser/overlay.py
opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/opengever.bumblebee.pot

Add filename and filesize to bumblebee overlay

---

opengever/core/profiles/default/types/opengever.workspace.workspace.xml
opengever/core/upgrades/20171220143920_configure_tabbedview_as_default_view_for_workspace/types/opengever.workspace.workspace.xml
opengever/core/upgrades/20171220143920_configure_tabbedview_as_default_view_for_workspace/upgrade.py
opengever/dossier/behaviors/dossiernamefromtitle.py
opengever/dossier/sequence.py
opengever/workspace/behaviors/configure.zcml
opengever/workspace/behaviors/namefromtitle.py
opengever/workspace/browser/configure.zcml
opengever/workspace/browser/tabbed.py
opengever/workspace/configure.zcml
opengever/workspace/interfaces.py
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/sequence.py

- Add a minimal tabbedview integration for the Workspace based on the Dossier tabbedview
- Make task addable
- Add Workspace specific sequence and `namefromtitle` behavior
- Revert Workspace specific implementation in opengever.dossier

Implement tabbedview for Workspace + Revert some conditions implemented in the dossier type for the workspace

---

docs/HISTORY.txt

Releases has been made from stable branches as hotfix release

Cleanup changelog after hotfix release 2017.7.5 and 4

---

docs/HISTORY.txt
opengever/trash/trash.py

This PR adds partial reindexing of objects being trashed or untrashed.
closes #3390

Add partial reindex optimization for trashing and untrashing objects.

---

opengever/testing/fixtures.py

The fixture is segmented into hours where things happen. Each call to ftw.builder's create function will move the frozen time forward. When a segment calls the builder more than 29 times, the frozen time is in the next hour, which may already be controlled by the next segment. So time will go backwards and we have a mess in the intids, which are patched to be based on the current time.
An assertion on segment tear down will verify that the segment didn't took too long.
Some segments are split up into more segments in order to fix such issues and give us more room in the future.

Fixture: prevent overlapping freezed times in fixture segments.

---

docs/HISTORY.txt
opengever/tabbedview/helper.py
sources.cfg

Prepare HTML structure for dossier title alignment.

---

opengever/base/browser/templates/content.pt
opengever/base/tests/test_base_behavior.py
opengever/document/tests/test_document.py

⚠️ Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/552
Closes https://github.com/4teamwork/opengever.core/issues/327

Improve semantic meaning of dossier detail view.

---

docs/HISTORY.txt
opengever/portlets/tree/resources/init_tree.js

Closes https://github.com/4teamwork/opengever.core/issues/3397

Save current tree portlet index in localstorage.

---

docs/intern/conf.py
docs/public/conf.py

Maybe do something fancy with `date.today()` … next year 😉 .
Closes #3865.

Use current year in docs footer copyright.

---

docs/HISTORY.txt
opengever/core/upgrades/20180116103227_add_configuration_option_for_documents_tab_on_repository_folder/registry.xml
opengever/core/upgrades/20180116103227_add_configuration_option_for_documents_tab_on_repository_folder/upgrade.py
opengever/core/upgrades/20180116143325_add_configuration_option_for_tasks_tab_on_repository_folder/registry.xml
opengever/core/upgrades/20180116143325_add_configuration_option_for_tasks_tab_on_repository_folder/upgrade.py
opengever/repository/browser/configure.zcml
opengever/repository/browser/tabbed.py
opengever/repository/browser/tabs.py
opengever/repository/interfaces.py
opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/opengever.repository.pot
opengever/repository/tests/test_repositoryfolder_tabs.py
opengever/testing/integration_test_case.py
opengever/testing/pages/tabbedview.py

At the moment it is not possible to list all documents or all tasks for a specific repository folder. This is especially annoing when trying to figure out how many / which tasks are open in a specific area of the repository. As user I'm sometimes looking for a document but I'm not sure in which dossier it is stored, for example because I'm not responsible / used to this area of the repository.
Adding the tabs "documents" and "tasks" on the repository folders will resolve that problem and give the users more flexibility. It also helps users to navigate faster because there is no need to open the dossier first.
- Both tabs can be individually disabled with feature flags. The tabs are enabled by default and will be automatically enabled on update.
- The documents tab has a new dossier …

Show documents and tasks on repository folders.

---

docs/HISTORY.txt
opengever/bumblebee/browser/configure.zcml
opengever/bumblebee/browser/revive_preview.py
opengever/bumblebee/configure.zcml
opengever/bumblebee/locales/de/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/locales/opengever.bumblebee.pot
opengever/bumblebee/permissions.zcml
opengever/bumblebee/tests/test_revive_bumblebee_preview.py
opengever/core/lawgiver.zcml
opengever/core/locales/de/LC_MESSAGES/ftw.lawgiver.po
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/ftw.lawgiver.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20180122090342_add_revive_bumblebee_preview_action/actions.xml
opengever/core/upgrades/20180122090342_add_revive_bumblebee_preview_action/rolemap.xml
opengever/core/upgrades/20180122090342_add_revive_bumblebee_preview_action/upgrade.py

This PR adds the possibility to revive a bumblebee document.
See #3619 for more information.
closes #3619

Add action to revive bumblebee previews.

---

docs/HISTORY.txt
opengever/meeting/browser/committeecontainer_forms.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/command.py
opengever/meeting/committee.py
opengever/meeting/committeecontainer.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/committee.py
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_committee_container_word.py
opengever/meeting/tests/test_committee_word.py

Generated file previous to change:
[protokoll-kommission-fur-rechtsfragen-19-01-2018.docx](https://github.com/4teamwork/opengever.core/files/1642920/protokoll-kommission-fur-rechtsfragen-19-01-2018.docx)
Generated file after changes:
[protokoll-kommission-fur-rechtsfragen-19-01-2018 (3).docx](https://github.com/4teamwork/opengever.core/files/1642922/protokoll-kommission-fur-rechtsfragen-19-01-2018.3.docx)
Resolves #3877
Needs backport to `2017.7`.

Add header and footer to proposals

---

docs/HISTORY.txt
opengever/tasktemplates/content/tasktemplate.py
opengever/tasktemplates/sources.py
opengever/tasktemplates/tests/test_tasktemplate.py

Make teams available as tasktemplate responsibles.

---

docs/HISTORY.txt
opengever/core/locales/de/LC_MESSAGES/plone.po
opengever/meeting/committee.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_committee.py
opengever/meeting/tests/test_committee_word.py

Change label and description to:
Closes #3325.

Improve description for committee group label.

---

opengever/dossier/command.py

2 things were broken here. 
* First the `_get_additional_attributes` only returned the fields from the main form (`IDossierTemplate`), not the ones from behaviors. Somehow the iteration over the schemas did not pick up the others.
* Second, the object creation function handled all `**kwargs`as coming from the main form, so setting them as attributes of the object, not using the appropriate interface.
As we also need to map the interfaces between the template and object, I chose not to change the basic implementation of object creation (`createContentInContainer` in `opengever/base/monkey/patches/default_values.py`), instead, I am setting the values for these fields directly in the `CreateDossierFromTemplateCommand`
resolves #3711

Fix transfer of fields from template when creating subdossiers.

---

docs/public/user-manual/dokumente/bearbeiten.rst

@deiferni wäre super wenn wir das heute noch mergen könnten, muss morgen drum eine info zum OC rauslassen wo ich auf die doku referenzieren möchte :)

Updates zu OC

---

opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20180131154543_fix_java_script_dependency_order/jsregistry.xml
opengever/core/upgrades/20180131154543_fix_java_script_dependency_order/upgrade.py
opengever/disposition/browser/resources/disposition.js

Closes https://github.com/4teamwork/opengever.core/issues/3899

 Fix JavaScript dependency order

---

docs/HISTORY.txt
opengever/meeting/browser/sablontemplate.py
opengever/meeting/proposal.py

Sort attachments for proposal and submitted proposal alphabetically

---

docs/HISTORY.txt
opengever/base/browser/resources/logoutClient.js
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20180202161908_move_logout_overlay_after_logout_client/jsregistry.xml
opengever/core/upgrades/20180202161908_move_logout_overlay_after_logout_client/upgrade.py
opengever/document/static/logout_overlay.js

Closes https://github.com/4teamwork/opengever.core/issues/3930

Fix logout overlay when used with cross tab logout.

---

opengever/base/browser/resources/logoutClient.js

Follow up of https://github.com/4teamwork/opengever.core/pull/3931

Fix logout client.

---

docs/HISTORY.txt
opengever/base/browser/resources/generateToc.js
opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20180201155223_install_toc_generate_controller/jsregistry.xml
opengever/core/upgrades/20180201155223_install_toc_generate_controller/upgrade.py

Closes https://github.com/4teamwork/opengever.core/issues/2280
⚠️ Depends on https://github.com/4teamwork/plonetheme.teamraum/pull/608

Implement TOC generate spinner.

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po

Rename "Abgeschlossene" to "Vergangene"

---

docs/HISTORY.txt
opengever/meeting/browser/committee.py
opengever/meeting/committee.py
opengever/meeting/model/committee.py
opengever/meeting/tests/test_committee_overview.py

Query members instead of members.
Resolves #3905

Sort members by last name

---

test-i18n-de.cfg

Added an extra grep for 'fuzzy' to before and after compiling the locales.
Closes #2506

Catch fuzzy translations

---

docs/HISTORY.txt
opengever/meeting/browser/meetings/zipexport.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/meeting.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_zipexport.py
opengever/meeting/wrapper.py
opengever/testing/integration_test_case.py

Exports a meeting with a metadata file.
This is the generated ZIP from the video:
[Kommission fur Rechtsfragen- 17.01.2018.zip](https://github.com/4teamwork/opengever.core/files/1635223/Kommission.fur.Rechtsfragen-.17.01.2018.zip)
Resolves #3752 #3765

Add json to export action

---

versions.cfg

Add version pin for `ftw.recipe.solr = 1.1.0`

Add version pin for ftw.recipe.solr = 1.1.0

---

opengever/activity/digest.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po

Update german translations for daily digest: `Daily Digest` -> `Tageszusammenfassung`.
_(No changelog since introduced and fixed in the same release)._

Update german translations for daily digest: Daily Digest -> Tageszusammenfassung

---

opengever/activity/digest.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/mailer.py
opengever/activity/templates/digest.pt
opengever/activity/tests/test_digest.py

- Remove the image from mails, we can't customize
- Adapt styling so it works better in Outlook
- Add date to mail subject
- Add username to mail heading
As per https://basecamp.com/2768704/projects/12554551/todos/341869981.

Adapt digest mail. Drop logo et al.

---

docs/HISTORY.txt
versions.cfg

Fixes review_state for content with no workflow.

Bump plone.app.contentlisting

---

docs/intern/kurzreferenzen/ogip.rst

@lukasgraf  habs nun anders gelöst resp. die beiden grauen Felder weggelassen. musst also nichts mehr dran "pröbeln".

Prozess OGIP aktualisiert und erweitert

---

bin/mtest

An example of a normal run failure output:
https://ci.4teamwork.ch/builds/149436/tasks/235825

Enhance debug output of mtest

---

opengever/examplecontent/profiles/default/registry.xml

As always no upgrade step is provided for our dev profile.

Enable new officeconnector features by default for local development.

---

docs/HISTORY.txt
opengever/api/configure.zcml
opengever/api/repositoryfolder.py
opengever/api/tests/test_serializer.py

Also include reference number.

Include 'is_leafnode' in serialization of repository folder

---

sources.cfg

Follow up of https://github.com/4teamwork/opengever.core/pull/4067

Checkout plonetheme.teamraum

---

docs/HISTORY.txt
opengever/base/browser/resources/tooltip.js
sources.cfg

Closes https://github.com/4teamwork/opengever.core/issues/4079

Implement tooltip backdrop.

---

opengever/api/config.py
opengever/api/favorites.py
opengever/api/tests/test_config.py
opengever/api/tests/test_favorites.py
opengever/base/__init__.py
opengever/base/browser/resources/Favorites.js
opengever/base/configure.zcml
opengever/base/favorite.py
opengever/base/interfaces.py
opengever/base/model/favorite.py
opengever/base/tests/test_favorite.py
opengever/base/tests/test_favorite_action.py
opengever/base/viewlets/configure.zcml
opengever/base/viewlets/favorite_action.pt
opengever/base/viewlets/favorite_action.py
opengever/core/profiles/default/jsregistry.xml
opengever/core/profiles/default/registry.xml
opengever/core/profiles/default/viewlets.xml
opengever/core/upgrades/20180411141431_add_favorite_js/jsregistry.xml
opengever/core/upgrades/20180411141431_add_favorite_js/upgrade.py
opengever/core/upgrades/20180411154945_order_favorite_action_viewlet/upgrade.py
opengever/core/upgrades/20180411154945_order_favorite_action_viewlet/viewlets.xml
opengever/core/upgrades/20180412151656_enable_favorite_e_tag/registry.xml
opengever/core/upgrades/20180412151656_enable_favorite_e_tag/upgrade.py
opengever/core/upgrades/20180413150422_add_favorites_feature_flag/registry.xml
opengever/core/upgrades/20180413150422_add_favorites_feature_flag/upgrade.py
opengever/core/upgrades/20180417150332_add_unique_constraint_for_the_favorites_table/upgrade.py
opengever/testing/integration_test_case.py

This PR adds an additional viewlet for the `Above contenttitle`-manager with the new favorite action (star-icon): 
- The requests to add or delete a favorite is done by an ajax call to the API (see #4133)
- Multiple clicks are handled and ignored during a request.
- The viewlet is only visible if the newly introduced feature-flag is enabled and the content supports oguid (dexterity objects)
- Caching of the viewlet is handled by a separate eTag adapter.
Styling in a separate PR in plonetheme.teamraum https://github.com/4teamwork/plonetheme.teamraum/pull/627
Closes #4103

Add favorite action viewlet

---

docs/HISTORY.txt
opengever/document/document.py
opengever/document/tests/test_document.py

Make office connector mimetype check case insensitive

---

docs/public/admin-manual/forcecheckin.rst
docs/public/admin-manual/rollenmanager.rst

(Basis: https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/30)

Ergänzung Globale Rollen gemäss Marco

---

docs/HISTORY.txt
opengever/task/browser/overview.py
opengever/task/tests/test_task.py

Fix unicode error in task description

---

docs/HISTORY.txt

Update changelog after 2018.2.x bugfix releases.

---

docs/HISTORY.txt

Update changelog after 2018.2.4 bugfix release.

---

opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt

There has been added an additional document in the meantime (#4250).
Should fix the failing master.

Fix Oneoffix Connect XML tests.

---

docs/HISTORY.txt
opengever/base/browser/helper.py
opengever/base/tests/test_helper.py

Styling in https://github.com/4teamwork/plonetheme.teamraum/pull/629
Closes #4130.

Add is_checked_out icon-addition.

---

docs/HISTORY.txt
opengever/examplecontent/profiles/municipality_content/opengever_content/01_initial_dossiers.json
opengever/examplecontent/profiles/municipality_content/opengever_content/07_tasktemplates.json

That makes it way easier to test and try out the tasktemplate feature on a local deployment.
Besides that I also add the missing responsible values for dossiers from the municipality_content profile. Dossiers without a responsible are invalid and lead to several problems.

 Add a simple tasktemplatefolder to GEVER examplecontent.

---

docs/HISTORY.txt
opengever/meeting/browser/resources/meeting.js

This seems to have been the only function of `CommitteeController()` so I yanked the whole thing out.
Closes #4185

Yank javascript for injecting the current date into the meeting title

---

docs/public/user-manual/aufgaben/aufgaben-workflow.rst
docs/public/user-manual/aufgaben/erstellen.rst
docs/public/user-manual/aufgaben/index.rst

Input durch Kommentar Heinzer in Doku
rst-Unbenennung da unter Dev-Manual ebenfalls ein rst workflow heisst

Verlinkung Aufgabenworkflow mit Kapitel Aufgabe erstellen

---

docs/HISTORY.txt
opengever/ogds/base/browser/templates/userdetails.pt
opengever/ogds/base/tests/test_userdetails.py

Omit parentheses when no abbreviation available

---

docs/HISTORY.txt
opengever/contact/tests/test_contactfolder.py
opengever/core/profiles/default/types/opengever.contact.contactfolder.xml
opengever/core/upgrades/20180531144505_amend_team_add_action_permission/types/opengever.contact.contactfolder.xml
opengever/core/upgrades/20180531144505_amend_team_add_action_permission/upgrade.py

Cherry-picked and amended the changelog.

Backport Administrator team add action visibility to 2018.3

---

docs/HISTORY.txt

Update changelog on `master` after releasing `2018.3.2` hotfix release.

Update changelog on master after releasing 2018.3.2 hotfix release.

---

docs/HISTORY.txt
opengever/base/browser/resources/Favorites.js
opengever/base/locales/de/LC_MESSAGES/opengever.base.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/base/locales/opengever.base.pot
opengever/base/tests/test_favorite_action.py
opengever/base/viewlets/favorite_action.pt
opengever/base/viewlets/favorite_action.py

Display the tooltip and javascript toggle behaviour.
Resolves #4353

Display tooltip on favorite action

---

docs/HISTORY.txt
solr-conf/managed-schema
solr-conf/solrconfig.xml

Fix handling of decomposed unicode (aka NFD, NFKD) in Solr

---

opengever/task/handlers.py
opengever/task/tests/test_transition_actions.py

Continuing from: https://github.com/4teamwork/opengever.core/pull/4319
My bad, sorry.

Fixups for missed code review points on #4319

---

docs/HISTORY.txt
opengever/document/browser/overview.py
opengever/document/browser/templates/keywords.pt
opengever/document/tests/test_overview.py
opengever/document/tests/test_overview_missing_fields.py
opengever/meeting/tests/test_overview_meeting_links.py

Add keywords to the document overview

---

opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po

> Folgende Meldungen müssen angepasst werden:
> 
> Traktandum einfügen:
> Freitext erfolgreich hinzugefügt -> Traktandum erfolgreich hinzugefügt
> 
> Sitzung abschliessen:
> Die Sitzung [NAME] wurde erfolgreich abgeschlossen, die Protokollauszüge wurden generiert und an die Urprungsdossiers zurückgespielt. -> Die Sitzung [NAME] wurde erfolgreich abgeschlossen.
Resolves #4254

Improve status messages

---

opengever/meeting/tests/test_agendaitem_list.py

Part of https://github.com/4teamwork/opengever.core/issues/4399.
_Follow up of https://github.com/4teamwork/opengever.core/pull/4397. No separate CL entry necessary IMO._

Port agenda item list test to integration.

---

opengever/meeting/tests/test_agendaitem.py

Part of https://github.com/4teamwork/opengever.core/issues/4399.
_Follow up of https://github.com/4teamwork/opengever.core/pull/4397. No separate CL entry necessary IMO._

Port agenda item test to integration.

---

opengever/base/behaviors/translated_title.py
opengever/base/browser/translated_title.py
opengever/base/tests/test_translated_title.py
opengever/dossier/dossiertemplate/behaviors.py
opengever/meeting/committeecontainer.py
opengever/meeting/tests/test_committee_container.py
opengever/repository/repositoryfolder.py
opengever/repository/repositoryroot.py

Puts all fields in the common tab (by adding the fields to the common field group).
Resolves #4344

Combine standard and general

---

opengever/core/profiles/default/jsregistry.xml
opengever/core/upgrades/20180613102451_readd_pin_js/jsregistry.xml
opengever/core/upgrades/20180613102451_readd_pin_js/upgrade.py
opengever/meeting/browser/resources/Pin.js

Has been removed by mistake with #4397. Cherry picked from https://github.com/4teamwork/opengever.core/pull/4443.
_CL not required as this is a fix for changes of the currently developed release._

Readd Pin.js.

---

docs/HISTORY.txt
opengever/base/browser/exposator.py
opengever/base/viewlets/colorization.pt
plonetheme/teamraum/resources/rules.xml

This removes a diazo rule that was responsible for **duplicating** some `<script />` elements, which lead to strange errors and unnecessary performance hits during page rendering.
---
The removed rule copied all  `<script />` (and `<style />`) elements from `#portal-top` (content) into `#portal-top (theme)`. However, because almost all elements from `#portal-top` [get copied explicitely](https://github.com/4teamwork/opengever.core/blob/a21f67952a7834a2778f5b14317f7b6165e7426f/plonetheme/teamraum/resources/rules.xml#L81-L114) by some more specific rules, this lead to duplication for scripts and styles that were inside elements that already got copied.
Specifically, this affected scripts for
- **favorites menu**
- **notifications menu**
- **recently touched menu**
At this point it's unclear …

Theme: Remove diazo rule that duplicated some JS scripts.

---

docs/HISTORY.txt
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20180625101451_add_ms_publisher_to_oc_editables/registry.xml
opengever/core/upgrades/20180625101451_add_ms_publisher_to_oc_editables/upgrade.py

Add MS Publisher to the list of OC editables

---

docs/HISTORY.txt
opengever/meeting/tests/test_committee_vocabulary.py
opengever/meeting/vocabulary.py

Also make active committee vocabularies sorted by title

---

opengever/base/tests/test_default_values_for_types.py

This adds default value tests for content creation via `plone.restapi`.
This is in preparation for bumping `plone.restapi` to a 3.x release, which contains significant changes to how content creation is done. Because `plone.restapi` will not use `invokeFactory` any more, it's to be expected that we need to patch it in order to get the correct default value behavior. 
*(No changelog, testing-only change)*

Tests: Add default value tests for REST API content creation.

---

docs/public/dev-manual/api/schemas/ftw.mail.mail.inc

Seems like the inc file for `ftw.mail.mail` was not up to date.

Update documentation for E-mail schema.

---

opengever/core/upgrades/20180704075330_add_new_meeting_notification_settings/upgrade.py

Upgrade step for notification settings was missing in PR #4367.
resolves #4540

Upgrade step for missing notification settings.

---

docs/HISTORY.txt
opengever/core/upgrades/20180703144847_register_watchers_for_proposals/upgrade.py
opengever/meeting/activity/helpers.py
opengever/meeting/activity/watchers.py
opengever/meeting/browser/createsubmittedproposal.py
opengever/meeting/browser/proposalforms.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_activites.py

Handle watchers for proposals.
⚠️ `get_users_by_group` is very slow. Is there another way, how to get all users of a group? Is it cached somewhere?
closes #4416

Register watchers

---

docs/HISTORY.txt
opengever/activity/__init__.py
opengever/activity/browser/resolve.py
opengever/activity/hooks.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/tests/test_resolve.py
opengever/core/upgrades/20180709110245_fix_proposal_activity_settings_defaults/upgrade.py
opengever/meeting/activity/activities.py
opengever/meeting/browser/createsubmittedproposal.py
opengever/meeting/browser/submitdocuments.py
opengever/meeting/command.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/model/proposal.py
opengever/meeting/proposal.py
opengever/meeting/proposalhistory.py
opengever/meeting/tests/test_activites.py

This PR is a retry of PR https://github.com/4teamwork/opengever.core/pull/4527
It does not use the connector-class but hacks into several places to trigger the activities.
It's not nice and not really maintainable but it does not introduce new complexity.
Belongs to: https://github.com/4teamwork/opengever.core/pull/4527
Closes #4415.

Record activities v2

---

docs/HISTORY.txt
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/mail.py
opengever/activity/tests/test_mail.py

Adjust activity mail subject to a more generic text.
closes #4585

Adjust activity mail subject to a more generic text.

---

docs/public/release-notes/index.rst

Docs: Fix ordering of release notes in TOC.

Docs: Fix ordering of release notes in TOC.

---

docs/HISTORY.txt
opengever/tasktemplates/browser/trigger.py
opengever/tasktemplates/tests/test_trigger.py

and validated correctly.
The required validation in `z3c.form.field` needs an empty list as
missing_value, when having a list field in combination with the checkbox widget.
Closes #4597

Make sure selecting at least one task template is required

---

opengever/disposition/tests/test_appraisal.py

The gain here is not that important, as we still have to make several state transitions, build dossiers and so on (went from 25s to 11s). 
On the tests themselves, I modified `test_added_dossiers` and `test_is_updated_when_editing_the_dossier_list` to actually test which dossiers are in the disposition. Seemed to make more sense that way. For the rest, it's just adapting the tests to the integration layer.
This is part of #3857

Move appraisal tests to integration layer.

---

README.rst
development-solr.cfg
opengever/api/configure.zcml
opengever/api/livesearch.py
opengever/api/tests/test_livesearch.py

- Support for Plone Catalog
- Support for Solr (Untested)
- Add solr development cfg

Implement restapi @livesearch endpoint

---

docs/HISTORY.txt
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/preview.rst
opengever/api/bumblebee.py
opengever/api/configure.zcml
opengever/api/tests/test_bumblebee.py

Endpoint for bumblebee session

---

docs/HISTORY.txt
docs/public/dev-manual/api/docs_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/navigation.rst
opengever/api/configure.zcml
opengever/api/navigation.py
opengever/api/tests/test_navigation.py

Customize the `@navigation` endpoint to return the repository tree

Gever-UI Navigation

---

docs/public/admin-manual/img/media/img-standardablauf-30.png
docs/public/admin-manual/img/media/img-standardablauf-31.png
docs/public/admin-manual/standardablauferstellen.rst
docs/public/user-manual/aufgaben/aufgaben-workflow.rst
docs/public/user-manual/aufgaben/empfangene_bearbeiten.rst
docs/public/user-manual/aufgaben/erstellen.rst
docs/public/user-manual/img/media/img-aufgaben-workflow-1.png
docs/public/user-manual/img/media/img-standardablauf-3.png
docs/public/user-manual/img/media/img-standardablauf-32.png
docs/public/user-manual/img/media/img-standardablauf-33.png
docs/public/user-manual/img/media/img-standardablauf-34.png
docs/public/user-manual/img/media/img-standardablauf-35.png
docs/public/user-manual/img/media/img-standardablauf-36.png
docs/public/user-manual/img/media/img-standardablauf-37.png
docs/public/user-manual/img/media/img-standardablauf-38.png
docs/public/user-manual/img/media/img-standardablauf-4.png
docs/public/user-manual/img/media/img-standardablauf-5.png
docs/public/user-manual/img/media/img-standardablauf-6.png
docs/public/user-manual/standardablaeufe.rst

@phgross hier die Doku zu OGIP 26. Bitte diesen Beitrag aufmerksam durchlesen, danke!

Sequentielle Abläufe

---

docs/HISTORY.txt
plonetheme/teamraum/importexport.py
plonetheme/teamraum/tests/test_importexport.py

Fix styles import export

---

docs/HISTORY.txt

Cleanup changelog after hoftix release 2018.3.6.

---

docs/HISTORY.txt
opengever/meeting/browser/proposaloverview.py
opengever/meeting/browser/templates/proposaloverview.pt
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_proposal_overview.py

A trivial template change.
Closes #4279

Move excerpts to the file info box on proposal overviews

---

docs/HISTORY.txt
opengever/meeting/proposal.py
opengever/meeting/tests/test_agendaitem.py

Did not quickly find an elegant way to sort on insert, so sorting on fetch.
Closes #4643

Sort excerpts by title

---

opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/bumblebee/locales/fr/LC_MESSAGES/opengever.bumblebee.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/tasktemplates/locales/fr/LC_MESSAGES/opengever.tasktemplates.po

Update French translations.

---

docs/public/_static/img/img-release-notes-3.3-1.png
docs/public/_static/img/img-release-notes-3.3-2.png
docs/public/release-notes/archiv/release-3.3.rst

Ich habe die Release-Notes 3.3 zu den Docs hinzugefügt.

Add Release-Notes "3.3" to Docs

---

docs/public/_static/img/img-release-notes-3.5.3-1.png
docs/public/release-notes/archiv/release-3.5.3.rst

Ich habe die Release-Notes 3.5.3 zu den Docs hinzugefügt.

Add Release-Notes "3.5.3" to Docs

---

docs/public/release-notes/archiv/release-3.6.rst

Ich habe die Release-Notes 3.6 zu den Docs hinzugefügt.

Add Release-Notes "3.6" to Docs

---

docs/public/release-notes/archiv/release-3.7.rst

Ich habe die Release-Notes 3.7 zu den Docs hinzugefügt.

Add Release-Notes "3.7" to Docs

---

docs/public/release-notes/archiv/release-3.2.rst

Ich habe die Release-Notes 3.2 zu den Docs hinzugefügt.

Add Release-Notes "3.2" to Docs

---

docs/public/_static/img/img-release-notes-3.8-1.png
docs/public/_static/img/img-release-notes-3.8-2.png
docs/public/_static/img/img-release-notes-3.8-3.png
docs/public/_static/img/img-release-notes-3.8-4.png
docs/public/_static/img/img-release-notes-3.8-5.png
docs/public/_static/img/img-release-notes-3.8-6.png
docs/public/release-notes/archiv/release-3.8.rst

Ich habe die Release-Notes 3.8 zu den Docs hinzugefügt.

Add Release-Notes "3.8" to Docs

---

docs/public/_static/img/img-release-notes-3.9-1.png
docs/public/_static/img/img-release-notes-3.9-2.png
docs/public/_static/img/img-release-notes-3.9-3.png
docs/public/_static/img/img-release-notes-3.9-4.png
docs/public/_static/img/img-release-notes-3.9-5.png
docs/public/_static/img/img-release-notes-3.9-6.png
docs/public/release-notes/archiv/release-3.9.rst

Ich habe die Release-Notes 3.9 zu den Docs hinzugefügt.

Add Release-Notes "3.9" to Docs

---

docs/public/_static/img/img-release-notes-2018.4-1.png
docs/public/_static/img/img-release-notes-2018.4-2.png
docs/public/_static/img/img-release-notes-2018.4-3.png
docs/public/release-notes/index.rst
docs/public/release-notes/release-2018.4.rst

Ich habe die Release-Notes 2018.4 zu den Docs hinzugefügt.

Add Release-Notes "2018.4" to Docs

---

docs/public/_static/img/img-release-notes-3.10-1.png
docs/public/_static/img/img-release-notes-3.10-2.png
docs/public/release-notes/archiv/release-3.10.rst

Ich habe die Release-Notes 3.10 zu den Docs hinzugefügt.

Add Release-Notes "3.10" to Docs

---

docs/public/release-notes/archiv/release-3.11.rst

Ich habe die Release-Notes 3.11 zu den Docs hinzugefügt.

Add Release-Notes "3.11" to Docs

---

opengever/document/tests/test_quickupload.py

Ended up porting these tests as a side effect of poking into https://sentry.4teamwork.ch/sentry/onegov-gever/issues/7234/

Port document quickupload tests to integration tests

---

docs/HISTORY.txt
opengever/base/browser/resources/Controller.js
opengever/base/browser/resources/Favorites.js
opengever/portlets/tree/resources/tree.js

Dieser PR behebt zwei Probleme bei der Favoriten-Auswahl:
1. Wenn sich der Benutzer ein Dossier anschaut und im Ordnungsbaum die aktuelle Ordnungsposition als Favorit markiert, wird das aktuelle Dossier ebenfalls (nur optisch) im Haupt-Inhalt neben dem Titel als Favorit markiert:
Vorher:
Nachher:
2. Wenn sich der Benutzer eine Ordnungsposition anschaut und diese Ordnungsposition im Ordnungsbaum als Favorit markiert, wird die Ordnungsposition im Haupt-Inhalt neben dem Titel ebenfalls als Favorit markiert. Wenn der Benutzer nun versucht, die Favoriten-Markierung neben dem Haupt-Titel anzuklicken um die Markierung wieder aufzuheben, war dies nicht mehr möglich. Es fehlte die Information, um welchen Favoriten es sich genau handelt.
Vorher:
Nachher:
ℹ️ All diese Probleme wären mit einem …

Fix broken favorites state

---

docs/HISTORY.txt
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing.py

extend ROLES_ORDER with meeting and workspace roles. Fixes #4789

Fix sharing view on committecontainer,

---

docs/HISTORY.txt
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po

Change wording for "Return Excerpt"

---

docs/HISTORY.txt
opengever/tabbedview/browser/base_tabs.py
opengever/tabbedview/browser/listing.py
opengever/tabbedview/browser/personal_overview.py
opengever/tabbedview/browser/tasklisting.py
opengever/tabbedview/tests/test_tasklisting.py

* Bit of cleanup work
* Bit of OO cleanup
* Configure the task checkbox columns properly
Closes #4761

 Disallow grouping tasks by the checkbox column in list views

---

docs/HISTORY.txt
opengever/core/upgrades/20180907153824_fix_dossier_journal_entries_of_broken_titled_meeting_excerpts/upgrade.py

Seems our saga with the protocol excerpt titles was not yet done.
@phgross @deiferni a candidate for a backport?
Closes #4587

Add an upgrade step to fix broken-by-broken-protocol-excerpt journal entries on dossiers

---

docs/HISTORY.txt
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20180820141043_add_a_registry_flag_for_proposal_tabs/registry.xml
opengever/core/upgrades/20180820141043_add_a_registry_flag_for_proposal_tabs/upgrade.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob
opengever/repository/browser/tabbed.py
opengever/repository/interfaces.py
opengever/repository/locales/de/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/repository/locales/opengever.repository.pot
opengever/repository/tests/test_repositoryfolder_tabs.py
opengever/tabbedview/browser/configure.zcml
opengever/tabbedview/browser/tabs.py
opengever/testing/integration_test_case.py

* Add a registry flag
* Add the tab
Closes #4411

Add proposal tabs to repository folders

---

docs/HISTORY.txt

Update changelog after bugfix release 2018.3.7.

---

docs/HISTORY.txt
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/core/upgrades/20180717140218_add_reminder_settings_table/upgrade.py
opengever/globalindex/model/__init__.py
opengever/globalindex/model/reminder_settings.py
opengever/globalindex/tests/test_reminder_setttings.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/reminder/__init__.py
opengever/task/tests/test_reminder.py
opengever/testing/builders/sql.py

Dieser PR erstellt das SQL-Objekt für die `ReminderSettings`.
issuer: #4205 
Based on PR: https://github.com/4teamwork/opengever.core/pull/4609

Add ReminderSetting SQL Model

---

docs/HISTORY.txt
opengever/activity/__init__.py
opengever/activity/base.py
opengever/activity/locales/de/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/activity/locales/opengever.activity.pot
opengever/activity/mailer.py
opengever/activity/tests/test_digest.py
opengever/activity/tests/test_plone_center.py
opengever/task/activities.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/tests/test_activities.py

Dieser PR erstellt das Activity-Objekt für Aufgaben-Erinnerungen.
issuer: #4205 
Based on PR: https://github.com/4teamwork/opengever.core/pull/4619

Add TaskReminderActivity object.

---

docs/HISTORY.txt
solr-conf/solrconfig.xml

Bump Lucene version used in Solr to 7.3.1

---

docs/HISTORY.txt
opengever/document/tests/test_overview.py
opengever/meeting/browser/createsubmittedproposal.py
opengever/meeting/browser/proposalforms.py
opengever/meeting/command.py
opengever/meeting/proposal.py
opengever/meeting/tests/test_proposal.py
opengever/meeting/tests/test_submit_additional_documents.py
opengever/task/localroles.py
opengever/task/tests/test_localroles.py
opengever/testing/builders/dx.py
opengever/testing/integration_test_case.py
opengever/testing/test_case.py

Preserve proposal document title for proposal documents of submitted proposals

---

docs/HISTORY.txt

Has been released from `2018.4-stable` branch.

Update changelog after hotfix release 2018.4.7.

---

opengever/core/upgrades/20181012203011_make_oneoffixx_textline_configs_optional_so_they_can_be_unset/registry.xml
opengever/core/upgrades/20181012203011_make_oneoffixx_textline_configs_optional_so_they_can_be_unset/upgrade.py
opengever/oneoffixx/interfaces.py

Make Oneoffixx TextLine configs optional so they can be unset

---

docs/HISTORY.txt
opengever/activity/dispatcher.py

Send notification dispatch exceptions to Raven

---

docs/HISTORY.txt
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/base/tests/test_default_values_for_types.py
opengever/core/upgrades/20181009133200_add_is_private_column_to_task_sql_model/upgrade.py
opengever/core/upgrades/20181010095235_add_private_task_feature_flag/registry.xml
opengever/core/upgrades/20181010095235_add_private_task_feature_flag/upgrade.py
opengever/core/upgrades/20181012105107_persist_is_private_attribute_to_tasks/upgrade.py
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_task_sql_syncer.py
opengever/task/__init__.py
opengever/task/browser/forms.py
opengever/task/interfaces.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/localroles.py
opengever/task/task.py
opengever/task/tests/test_localroles.py
opengever/task/tests/test_private_task.py
opengever/task/tests/test_task_byline.py
opengever/task/viewlets/byline.py
opengever/testing/integration_test_case.py

Dieser PR implementiert das neue Feld für Aufgaben: `is_private`
Issuer: #4763

Additional task field: is_private

---

docs/HISTORY.txt
opengever/task/activities.py
opengever/task/locales/de/LC_MESSAGES/opengever.task.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/task/locales/opengever.task.pot
opengever/task/tests/test_activities.py

Adjust activity label for personal tasks

---

docs/HISTORY.txt
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/notifications.rst
opengever/activity/model/notification.py
opengever/api/configure.zcml
opengever/api/notifications.py
opengever/api/tests/test_notifications.py

This PR implements a GET and a PUT endpoint for notifications.
closes: #4787

REST-API notifications endpoint

---

opengever/task/locales/fr/LC_MESSAGES/opengever.task.po

Just stumbled on these two french translations that begged for improvement.

Improve french translations for task responses.

---

docs/HISTORY.txt
opengever/document/browser/overview.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_overview.py
opengever/document/tests/test_overview_missing_fields.py
opengever/meeting/tests/test_overview_meeting_links.py

Add creation and modification date to document overview.

---

docs/HISTORY.txt
opengever/api/listing.py
opengever/api/serializer.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_repository.py
opengever/api/tests/test_serializer.py

This PR provides the physical_path for serialized contents.
fixes #4979

Include physical path to item and container serialization

---

docs/HISTORY.txt
opengever/sharing/browser/admin_list.py
opengever/sharing/tests/test_blocked_local_roles_listing.py

Amended the protected objects admin view links to contain the sequence numbers.
Closes #5032

Add reference numbers to protected items admin view links

---

opengever/oneoffixx/browser/connect_xml.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt

* Add an xml type and encoding declaration
* Encode in UTF-8
* Use all of the user, dossier and document doc properties
Closes #5025

Add all docproperties to Oneoffixx XML payloads

---

docs/HISTORY.txt
opengever/core/upgrades/20180123155812_checkout_edit_only_for_office_connector_editable/registry.xml
opengever/core/upgrades/20181113161216_add_open_xml_visio_to_mimetype_registry/mimetypes.xml
opengever/core/upgrades/20181113161216_add_open_xml_visio_to_mimetype_registry/upgrade.py
opengever/core/upgrades/20181113161333_fix_content_type_for_open_xml_visio/upgrade.py
opengever/core/upgrades/20181113185421_add_open_xml_visio_drawings_to_officeconnector_editable_types/registry.xml
opengever/core/upgrades/20181113185421_add_open_xml_visio_drawings_to_officeconnector_editable_types/upgrade.py
opengever/document/extra_mimetypes.py
opengever/policy/base/profiles/mimetype/mimetypes.xml

Add Open XML Visio to extra mimetypes and the mimetype registry. Also add a deferrable upgrade to fix the `getContentType` and `getIcon` metadata so that icons are displayed correctly in GEVER.
The  upgrade step to update the mimetype registry is in registered in opengever.core and not in opengever.policy.base to prevent ordering issues as the mimetype registry *must* be upgraded before objects reindexed. Otherwise the `getIcon` metadata won't be filled correctly and thus the icons won't show up as expected.
A list of possible file extension has been found at microsoft (https://docs.microsoft.com/en-us/office/client-developer/visio/introduction-to-the-visio-file-formatvsdx) and the corresponding mimetype names has been taken from apache tika …

Add Open XML Visio mimetypes.

---

docs/HISTORY.txt

release has been released from `2018.4-stable` branch

Update changelog after 2018.4.10 hotfix release.

---

docs/HISTORY.txt
opengever/task/browser/overview.py
opengever/task/browser/templates/task_reminder_selector.pt
opengever/task/tests/test_reminder.py

Don't display the reminder selector on tasks where it would not work

---

docs/HISTORY.txt
opengever/inbox/forwarding.py
opengever/inbox/tests/test_forwarding.py
opengever/task/browser/forms.py

Respect private_task feature flag also in forwarding forms.

---

docs/public/_static/img/img-release-notes-2018.5-1.png
docs/public/release-notes/index.rst
docs/public/release-notes/release-2018.5.rst
docs/public/user-manual/aufgaben/pendenzenkontrolle.rst
docs/public/user-manual/aufgaben/stellvertretung.rst

Achtung, ich habe auf Bilder von anderen Branches verlinkt, welche noch nicht publiziert wurden --> wird daher wohl Konflikte geben!! Weiter fehlt noch der SPV-Teil.

Erstellung  Release Notes 2018.5

---

docs/HISTORY.txt
setup.py

Unlocking the merge lock for 2019.1 PRs

Bump next version to 2019.1.0

---

docs/HISTORY.txt
opengever/base/browser/templates/favorites.pt

Remove the now-unnecessary js files from the favorites template

---

docs/intern/kurzreferenzen/solr.rst

Nach der gemeinsamen Besprechung mit Maik und Fäbu, waren noch einige Anpassungen(https://github.com/4teamwork/opengever.maintenance/pull/155) an den Scripts und dementsprechend auch an der Doku notwendig.

Some adjustments on the activate solr documentation.

---

docs/public/user-manual/img/media/img-sitzungs-app-1.png
docs/public/user-manual/img/media/img-sitzungs-app-10.png
docs/public/user-manual/img/media/img-sitzungs-app-2.png
docs/public/user-manual/img/media/img-sitzungs-app-3.png
docs/public/user-manual/img/media/img-sitzungs-app-4.png
docs/public/user-manual/img/media/img-sitzungs-app-5.png
docs/public/user-manual/img/media/img-sitzungs-app-6.png
docs/public/user-manual/img/media/img-sitzungs-app-7.png
docs/public/user-manual/img/media/img-sitzungs-app-8.png
docs/public/user-manual/img/media/img-sitzungs-app-9.png
docs/public/user-manual/index.rst
docs/public/user-manual/sitzungs-app/aktualisieren.rst
docs/public/user-manual/sitzungs-app/benachrichtigen.rst
docs/public/user-manual/sitzungs-app/herunterladen.rst
docs/public/user-manual/sitzungs-app/hochladen.rst
docs/public/user-manual/sitzungs-app/index.rst
docs/public/user-manual/sitzungs-app/notizen.rst
docs/public/user-manual/sitzungs-app/zusammenstellen.rst

Hier das Kapitel Sitzungs-App auf Basis von Sus Inputs.

Ergänzung Kapitel Sitzungs-App

---

opengever/advancedsearch/tests/test_search.py
opengever/testing/integration_test_case.py

Convert all opengever.advancedsearch tests to integration test.

---

opengever/testing/integration_test_case.py
opengever/trash/tests/test_catalog.py
opengever/trash/tests/test_remove.py
opengever/trash/tests/test_remove_conditions.py
opengever/trash/tests/test_trash.py

I finished the conversion for the trash modul tests (part of the FeDeX-Day work)

Convert trash tests to integration tests

---

docs/HISTORY.txt
opengever/meeting/activity/activities.py
opengever/meeting/activity/helpers.py
opengever/meeting/tests/test_activites.py

Fix a circular import in meeting activities

---

opengever/core/sqlite_testing.py

As `z3c.saconfig` holds a module level dictionary as a cache of scoped sessions we must pop our known-named session off this cache as otherwise our `create_session()` will not do what we expect it to do on other layers.
Additionally sqlalchemy itself also holds a cache of sessions and engines, so we also need to remove the session from them, which also drops the engine and connection so our ZCML declared events for `z3c.saconfig.interfaces.IEngineCreatedEvent` actually fire as intended upon the first `create_session()` of the next layer.
Closes https://github.com/4teamwork/opengever.core/issues/5104

Plug an sqlalchemy session registry leak in the standalone memory db layer

---

docs/public/_static/img/word_mergefield.png
docs/public/admin-manual/meeting/mergefields.rst

Add a bit more details and a explanatory screenshot to the sablon section in order to help fresh users to figure out how to add new fields to an existing or new sablon document.
Please verify that this actually correct 😉

Improve sablon mergefields documentation.

---

opengever/core/upgrades/20181214121838_migrate_agenda_item_numbers_from_strings_to_int/upgrade.py

It can be None apparently.

---

README.rst
docs/HISTORY.txt
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/webactions.rst
opengever/api/configure.zcml
opengever/api/tests/test_webactions.py
opengever/api/webactions.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20190127214610_add_web_action_manager_role/rolemap.xml
opengever/core/upgrades/20190127214610_add_web_action_manager_role/upgrade.py
opengever/core/upgrades/20190131140809_initialize_web_actions_storage/upgrade.py
opengever/sphinx/gevertheme/static/gevertheme.css
opengever/testing/builders/__init__.py
opengever/testing/builders/webactions.py
opengever/testing/fixtures.py
opengever/webactions/configure.zcml
opengever/webactions/exceptions.py
opengever/webactions/interfaces.py
opengever/webactions/permissions.zcml
opengever/webactions/schema.py
opengever/webactions/storage.py
opengever/webactions/tests/test_webactions_storage.py
opengever/webactions/validation.py

Adds an implementation for a **WebActions storage and a REST API** according to [OGIP 42](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2622/document-23827).
**Review Notes**
- A rendered **[preview of the documentation](https://docs.onegovgever.ch/webactions-docs-preview/dev-manual/api/webactions/)** has been published. I recommend starting with this to get a high-level overview of what the idea is here.
- There are certain deviations from what exactly is specified in OGIP 42. I will update it accordingly once the details have been settled. Some of the obvious ones are:
- Added `enabled` field
- Split `icon` field into `icon_name` and `icon_data`
- Renamed the display location `icon` to `title-buttons`
- Added a server-generated `modified` timestamp (in addition to `created`) …

WebActions: Implement storage and REST API

---

docs/HISTORY.txt
opengever/oneoffixx/browser/form.py
opengever/oneoffixx/locales/de/LC_MESSAGES/opengever.oneoffixx.po
opengever/oneoffixx/locales/fr/LC_MESSAGES/opengever.oneoffixx.po
opengever/oneoffixx/locales/opengever.oneoffixx.pot

* Using a translated label for the default for selecting a template group
Closes #5322

Better label the Oneoffixx template selection dropdown default value.

---

docs/intern/_static/img/grob-ablauf-ogip-1.png
docs/intern/_static/img/grob-ablauf-ogip-2.png
docs/intern/kurzreferenzen/ogip.rst

(Habe auch die Status angepasst, da wir viel zu viele hatten, welche nicht gepflegt wurden. Die OGIP-Vorlage im GEVER habe ich entsprechend angepasst und auch das Excel im teamraum sowie im FAQ des FF ist es bereits einheitlich.) Und nein, das zweite Bild bekomme ich nicht besser hin ;)

Aktualisierung Doku OGIP-Prozess

---

docs/intern/releasemanagement/nicht-entwicklungsarbeiten.rst

Anpassung Links und generell Prozess

Aktualisierung Release-Arbeiten (nicht technische)

---

docs/HISTORY.txt
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

Skip creation of the tasks pdf on resolve for dossiers without tasks.

---

README.rst

I know, it's kind of minor. I hope you don't mind. xD

Fixed typo: Producion to Production

---

docs/HISTORY.txt
opengever/tabbedview/browser/base_tabs.py
opengever/tabbedview/tests/test_base_tabs.py

Fix subject-filter for personal overview.

---

docs/public/_static/img/img-release-notes-2019.1-1.png
docs/public/release-notes/index.rst
docs/public/release-notes/release-2019.1.rst
docs/public/user-manual/benachrichtigung.rst
docs/public/user-manual/dossiers/durchsuchen.rst
docs/public/user-manual/dossiers/index.rst
docs/public/user-manual/img/media/img-benachrichtigungs-einstellungen-5.png
docs/public/user-manual/img/media/img-dossier-durchsuchen-0.png
docs/public/user-manual/img/media/img-dossier-durchsuchen-1.png
docs/public/user-manual/img/media/img-dossier-durchsuchen-2.png

🚧 Printscreen zu Filter Schlagwortbaum fehlt noch, ansonsten m.E. vollständig

Doku Release 2019.1

---

opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/core/locales/fr/LC_MESSAGES/plone.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/officeconnector/locales/fr/LC_MESSAGES/opengever.officeconnector.po
opengever/oneoffixx/locales/fr/LC_MESSAGES/opengever.oneoffixx.po
opengever/tabbedview/locales/fr/LC_MESSAGES/opengever.tabbedview.po
plonetheme/teamraum/locales/de/LC_MESSAGES/plonetheme.teamraum.po
plonetheme/teamraum/locales/fr/LC_MESSAGES/plonetheme.teamraum.po

I did not add a CL, as I think this is just expected for a software shipped in 2 languages...

Add French translations for release 2019.1.

---

README.rst

Make longtest happy by fixing underline length.

---

docs/HISTORY.txt
opengever/core/upgrades/20190307102922_reindex_dossier_end_date/upgrade.py
opengever/dossier/base.py
opengever/dossier/resolve.py
opengever/dossier/tests/test_activate.py
opengever/dossier/tests/test_resolve.py
opengever/testing/integration_test_case.py

⚠️ do not merge, missing upgrade ⚠️ 
resolves #5458

Make sure end date is reindexed when resolving/reactivating a dossier.

---

docs/HISTORY.txt
opengever/core/upgrades/20190307102922_reindex_dossier_end_date/upgrade.py
opengever/core/upgrades/20190307132714_fix_task_and_journal_pdf_object_provides/upgrade.py
opengever/dossier/resolve.py
opengever/dossier/tests/test_resolve.py

after resolving a dossier.
Wow, that looks like a 🐷 worthy one for me! I actually did the reindexing manually in the tests! Really not sure why I thought it was normal to have to reindex in the tests... Probably just too new to plone back then
resolves #5473

Make sure task and journal PDFs object_provides index is up to date

---

docs/intern/operations/allgemein.rst

Set example execution time to something usually used in production.
Correct typo and clarify description.

Update gever cronjob docs.

---

docs/HISTORY.txt
opengever/globalindex/model/task.py
opengever/tabbedview/browser/personal_overview.py
opengever/tabbedview/filters.py
opengever/tabbedview/tests/test_personaloverview.py

Added a new filter for the 'My Tasks' tab.
Closes https://github.com/4teamwork/opengever.core/issues/5202

Do not list resolved tasks as pending in the 'My Tasks' tab

---

docs/public/dev-manual/api/docs_changelog.rst
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/listings.rst

Add docs for listing endpoint

---

opengever/api/listing.py
opengever/api/tests/test_listing.py

Put filter queries in braces to properly support OR operations.

Fix filtering by multiple values in Solr

---

docs/HISTORY.txt
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/journal.rst
opengever/api/configure.zcml
opengever/api/journal.py
opengever/api/tests/test_journal.py

Add restapi /@journal endpoint to add journal entries

---

docs/HISTORY.txt
docs/public/dev-manual/api/journal.rst
opengever/api/configure.zcml
opengever/api/journal.py
opengever/api/tests/test_journal.py

This PR implements the GET `@journal` endpoint for getting a batched list of journal entries.
Closes #5428

Add restapi @journal endpoint to get journal entries.

---

docs/HISTORY.txt
opengever/api/tests/test_vocabularies.py
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20190423103930_allow_members_and_contributors_to_access_plone_vocabularies_through_restapi/rolemap.xml
opengever/core/upgrades/20190423103930_allow_members_and_contributors_to_access_plone_vocabularies_through_restapi/upgrade.py

Allow members to access plone vocabularies through restapi.

---

docs/HISTORY.txt
docs/public/dev-manual/api/listings.rst
opengever/api/listing.py
opengever/api/tests/test_listing.py
opengever/testing/fixtures.py

Issuer: https://github.com/4teamwork/gever-ui/issues/19

Extend @listing endpoint with `workspace_folders`-listing.

---

docs/HISTORY.txt
docs/public-fr/_static/img/img-notification1.png
docs/public-fr/_static/img/img-notification2.png
docs/public-fr/_static/img/img-notification3.png
docs/public-fr/_static/img/img-notification4.png
docs/public-fr/_static/img/img-notification5.png
docs/public-fr/_static/img/img-notification6.png
docs/public-fr/_static/img/img-notification7.png
docs/public-fr/chapitre4-notifications.rst
docs/public-fr/index.rst

I took over @andresoberhaensli 's branch and made a new PR, as it seems that the snapshots were not being stored through our git lfs.

Translate chapter 4 of documentation to French.

---

opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po

https://basecamp.com/2768704/projects/12554551/todos/386632425

Harmonize deadline label between task form and task reports.

---

docs/public/user-manual/img/media/img-protokollgenehmigung-1.png
docs/public/user-manual/img/media/img-protokollgenehmigung-2.png
docs/public/user-manual/img/media/img-protokollgenehmigung-3.png
docs/public/user-manual/img/media/img-protokollgenehmigung-4.png
docs/public/user-manual/spv/index.rst
docs/public/user-manual/spv/protokollgenehmigung.rst

https://basecamp.com/2768704/projects/13482340/todos/381949023

Added docu for the recently introduced feature Protokollgenehmigung.

---

docs/HISTORY.txt
opengever/document/browser/report.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/tests/test_reporter.py
opengever/globalindex/browser/report.py
opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/opengever.globalindex.pot
opengever/globalindex/tests/test_reporter.py

With #5500 the document export gets forgotten. This PR adds now the same functionality we have for dossier and task to the document export.
Besides that I fixed some labels of the task and document excel export.
closes #5469

Respect tabbedview settings when generating an documents excel export.

---

docs/public/release-notes/index.rst
docs/public/release-notes/release-2019.2.rst

Note: Su hat die Release Notes bereits korrigiert und überarbeitet.
@lukasgraf muss beim Publizieren von neuen Release Notes noch etwas zusätzliches beachtet werden?

Add release notes for the 2019.2 release.

---

opengever/core/upgrades/20190313154510_remove_meeting_tempaltes_from_committee_containers/upgrade.py

Add a safeguard in case the attributes are not present on the committee_container.

Fix upgrade step migrating templates from committee_container to committee.

---

docs/HISTORY.txt
setup.py

So we can start merging 2019.3 features now!

Bump next version to 2019.3.

---

docs/HISTORY.txt
docs/intern/operations/saas.rst

Mainly added some info on the two step process of the update with first the non-deferrable and then the deferrable upgrade steps.

Update documentation for update of SaaS deployments.

---

docs/HISTORY.txt

_You might wanna take care when rebasing existing pull requests._

Update changelog after hotfix release 2019.2.3.

---

docs/public/user-manual/spv/sitzung-vorbereiten.rst

See https://basecamp.com/2768704/projects/13482340/todos/389396851.

Add note to meeting docu about Seitennummerierung von Protokollen.

---

docs/HISTORY.txt

Update changelog after hotfix release 2019.2.4.

---

docs/public/release-notes/index.rst
docs/public/release-notes/release-2019.3.rst

Da es sich um einen kleineren Release handelt, sind auch die Release Notes kürzer ausgefallen.
_Wurden bereits durch Su reviewed_

Add release notes for the 2019.3 release.

---

docs/HISTORY.txt
opengever/api/configure.zcml
opengever/api/tests/test_users.py
opengever/api/users.py
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20190704115754_adjust_access_plone_user_information_permission/rolemap.xml
opengever/core/upgrades/20190704115754_adjust_access_plone_user_information_permission/upgrade.py

 Allow Readers,Member and Managers to access users information for all users

---

docs/HISTORY.txt
opengever/repository/configure.zcml
opengever/repository/deleter.py
opengever/repository/interfaces.py
opengever/repository/subscribers.py
opengever/repository/tests/test_deletion.py
opengever/repository/tests/test_reference_prefix_manager.py

Resolves undisclosed security issue #4909 
resolves #4909

Fix undisclosed security issue

---

docs/public/dev-manual/api/schemas/ftw.mail.mail.inc
docs/public/dev-manual/api/schemas/opengever.document.document.inc
docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc
docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc

Seems like the update of the schemas in the docs were forgotten in https://github.com/4teamwork/opengever.core/pull/5896

Update api schemas in the documentation.

---

docs/HISTORY.txt
opengever/api/listing.py
opengever/api/tests/test_listing.py

Solr test actually catches that encoding issue, even if it's a not so useful mock test.
For https://github.com/4teamwork/opengever.core/issues/5922

Fix unicode error in listing endpoint.

---

docs/HISTORY.txt

Hotfix created via stable branch.

Update changelog after hotfix release 2019.3.4.

---

docs/HISTORY.txt
docs/public/dev-manual/api/documents.rst
docs/public/dev-manual/api/serialization.rst

We add documentation for the `@cancelcheckout` endpoint and improve the overall documentation of the endpoints for documents.
For https://github.com/4teamwork/opengever.core/issues/5947

Add documentation for the cancelcheckout endpoint.

---

.github/pull_request_template.md

As discussed in our retro we add a link to the DoD from our PR template

Link definition of Done in pr template.

---

opengever/core/upgrades/20191108143533_migrate_proposal_history_to_proposal_responses/upgrade.py

It seems that records are missing the text attribute in certain cases. I think the origin of the missing text is in the upgrade from SQL to plone: https://github.com/4teamwork/opengever.core/blob/e3046d8adbc8f5c06f9dd9d788a41b152ad7cfce/opengever/core/upgrades/20170704112234_migrate_sql_proposal_history_to_plone/upgrade.py
We do not seem to set the text there...
For https://github.com/4teamwork/opengever.core/issues/5934

Fix ProposalHistory migration to Response.

---

docs/HISTORY.txt
setup.py

With the merge of #6085, we're working now on the 2019.5 release.

Bump next version to 2019.5.

---

docs/HISTORY.txt
setup.py

Bump version for upcoming release to `2020.1.0`.

Bump version for upcoming release to 2020.1.0.

---

docs/HISTORY.txt

Update CL with release 2019.6.3

Update changelog after 2019.6.3 hotfix release.

---

docs/HISTORY.txt
docs/public/dev-manual/api/index.rst
docs/public/dev-manual/api/linked_workspaces.rst
opengever/api/configure.zcml
opengever/api/linked_workspaces.py
opengever/api/tests/test_linked_workspaces.py
opengever/core/profiles/default/types/opengever.dossier.businesscasedossier.xml
opengever/core/tests/test_relations.py
opengever/core/upgrades/20200214082558_remove_linked_workspaces_behavior/types/opengever.dossier.businesscasedossier.xml
opengever/core/upgrades/20200214082558_remove_linked_workspaces_behavior/upgrade.py
opengever/testing/integration_test_case.py
opengever/testing/test_case.py
opengever/workspaceclient/client.py
opengever/workspaceclient/configure.zcml
opengever/workspaceclient/interfaces.py
opengever/workspaceclient/linked_workspaces.py
opengever/workspaceclient/tests/__init__.py
opengever/workspaceclient/tests/test_client.py
opengever/workspaceclient/tests/test_linked_workspaces.py

Issuer: #6154 
Dieser PR implementiert einen neuen Endpoint `@create-linked-workspace`
Der Endpoint erstellt ein neuer Arbeitsraum und verknüpft diesen mit dem Dossier, auf welchem der Request abgesetzt wurde.

Add linked workspace

---

opengever/api/linked_workspaces.py
opengever/api/tests/test_linked_workspaces.py
opengever/workspaceclient/exceptions.py
opengever/workspaceclient/session.py
opengever/workspaceclient/tests/test_session.py

Issuer: #6154 
Dieser PR behandelt die Fehlerbehandlung bei der Kommunikation mit dem Teamraum-Deployment. 
Umsetzungsdetails: https://github.com/4teamwork/opengever.core/issues/6154#issuecomment-584641272

WorkspaceClient Error handling

---

docs/public/release-notes/index.rst
docs/public/release-notes/release-2019.5-6.rst
docs/public/release-notes/release-2020.1.rst

Draft of the release notes for the latest releases.
- We need to discuss what we do with Teamraum stuff...

Add release notes for 2019.5, 2019.6 and 2020.1.

---

opengever/workspaceclient/session.py
opengever/workspaceclient/tests/test_session.py

Issuer: #6282 
This PR fixes an issue where the user got a 401 if the users access token is expired.
Please see the details in the issue #6282

Always obtain a new access token on a 401 http error in the workspace client session

---

docs/public/conf.py
docs/public/release-notes/index.rst
docs/public/release-notes/release-2019.2.rst
docs/public/release-notes/release-2020.1.rst
docs/public/release-notes/release-2020.2.rst

With this PR we add release notes for the release `2020.2` to the public documentation.
I also did a minor cleanup of the `2020.1` notes.

Add release notes for release 2020.2.

---

opengever/base/helper.py
opengever/base/helpers.py
opengever/meeting/browser/meetings/meeting.py

There is no reason to have two different helper modules here, this only clutters the repository.
This is just some cleanup, no associated issue and also did not add a changelog for that.

Merge base.helper and base.helpers files.

---

docs/HISTORY.txt

Update history in `master` with the `2019.6.4` bugfix release made for https://github.com/4teamwork/opengever.zug/issues/392.
_Alles muss gemacht/angehakt werden._

Update history with 2019.6.4. bugfix release.

---

opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/bootstrap.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default_content/opengever_content/01-initial-structure.json.bob

While generating a new GEVER policy as requested in https://4teamwork.atlassian.net/browse/GEVER-98, we identified some shortcomings in the policy generator wizard.
Please see each commit for the reason of the change.

Improve the policy generator

---

README.rst
docs/intern/policies/deployment.rst
docs/intern/policies/policy.rst
docs/intern/policies/repository.rst

When running through the steps with a novice policy creator we discovered that many steps are not covered by the docs. With this PR we make one step towards improving the docs a bit.
_Many more steps will be required though._
For https://4teamwork.atlassian.net/browse/GEVER-98
_Alles muss gemacht/angehakt werden._

Improve docs about creating policies.

---

opengever/base/model/__init__.py
opengever/globalindex/model/__init__.py
opengever/globalindex/model/task.py
opengever/meeting/model/agendaitem.py
opengever/meeting/model/committee.py
opengever/meeting/model/meeting.py
opengever/meeting/model/proposal.py

While working on the Jira issue https://4teamwork.atlassian.net/browse/GEVER-122, my mentor @deiferni asked me to refactor one of the constants used for the database schemata.
The reason for this change is to have all constants at the same place.

Refactoring constants.

---

.github/pull_request_template.md

As discussed, PRs should be in english, therefore the checklist should also be in english.
I translated the checklist and also tried to make it a bit more concise.

Translate PR checklist to english.

---

.github/pull_request_template.md

Remove stray underscore from PR checklist.
_It annoyed me all along and now it's gone._

Remove stray underscore from PR checklist.

---

opengever/api/task.py
opengever/api/tests/test_task.py

This is a follow-up of https://github.com/4teamwork/opengever.core/pull/6387 and resolves the regression reported in [GEVER-312](https://4teamwork.atlassian.net/browse/GEVER-312).

Switch GET request of tasks to folderish.

---

opengever/core/upgrades/20200508163417_populate_filename_column_in_favorites/upgrade.py

The upgrade step to populate the favorites table was broken because filename is `Missing.Value` for non document type brains, which will make the update of the table fail when trying to set the filename value. I probably only had favorited documents locally when I executed the upgrade. 
For https://4teamwork.atlassian.net/browse/GEVER-138

Fix upgrade populating filename column in favorites table.

---

docs/intern/kurzreferenzen/teamraum.rst
docs/intern/policies/index.rst
docs/intern/policies/saas_policy.rst
docs/intern/policies/teamraum_policy.rst

Dieser PR fügt eine Dokumentation für das erstellen einer Teamraum-Policy hinzu.
Zu diesem PR gehört das neue Jira-Template: https://4teamwork.atlassian.net/browse/TEMP-8
Jira-Issue: https://4teamwork.atlassian.net/browse/GEVER-195

Teamraum policy Kurzreferenz

---

docs/public/user-manual/img/media/img-sitzungs-app-11.png
docs/public/user-manual/sitzungs-app/index.rst
docs/public/user-manual/sitzungs-app/sitzungsunterlagen.rst

Ergänzung der Sitzungs-App Dokumentation um ein neues Kapitel zur Hinterlegung einer Beschreibung in einer Sitzung.
Jira Issue: https://4teamwork.atlassian.net/browse/DJANGO-249

Addition of the grimlock documentation

---

opengever/core/upgrades/20200518084137_cleanup_catalog_indexes_and_metadata/upgrade.py

Names must be deleted in reverse order

Fix removing of metadata

---

opengever/api/tests/test_watchers.py

`test_delete_watchers_for_inbox_forwarding` was flaky, failing systematically in cached mode and sometimes failing on CI (e.g. https://ci.4teamwork.ch/builds/335741/tasks/561628)
Problem was that the notification center uses the reference to the `Subscription`s on a `Resource` to get the `Subscription`s (https://github.com/4teamwork/opengever.core/blob/master/opengever/activity/center.py#L104-L112). This reference is not always up to date during tests, and the `Resource` first needs to be refreshed.
thanks @deiferni for the help!

Make sure SQL references are up to date in watchers test.

---

opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/configure.zcml.bob

This PR makes some policy template fixes/adjustments.
The updated policy template is the most used configuration. So it makes sense to use it as the default. 
Related to Jira-Issue: https://4teamwork.atlassian.net/browse/GEVER-79

Fix policy template

---

docs/public/dev-manual/api/schemas/opengever.task.task.inc

This is a followup PR to https://github.com/4teamwork/opengever.core/pull/6475. The task schema in the documentation was not updated after a new field was added. This will now be done.
Jira: https://4teamwork.atlassian.net/browse/GEVER-31

Update task schema in dev documentation.

---

docs/HISTORY.txt
docs/public/dev-manual/api/searching.rst
opengever/api/listing.py
opengever/api/solr_query_service.py
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py

This PR implements the missing batching functionality for the `@solrsearch` endpoint.
Jira: https://4teamwork.atlassian.net/browse/GEVER-472

Implement batching for the @solrsearch endpoint

---

docs/HISTORY.txt
opengever/dossier/locales/de/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/opengever.dossier.pot
opengever/dossier/move_items.py

The error message was formulated too technically. In addition, the error message appears when an object is moved, not copied.
Jira: https://4teamwork.atlassian.net/browse/GEVER-117

Update translations of error messages when moving objects.

---

docs/HISTORY.txt
docs/public/dev-manual/api/tasks.rst
opengever/api/configure.zcml
opengever/api/task.py
opengever/api/tasktree.py
opengever/api/tests/test_summary.py
opengever/api/tests/test_task.py
opengever/api/tests/test_tasktree.py
opengever/api/tests/test_watchers.py
opengever/base/browser/navigation.py
opengever/task/tests/test_revoke_permissions.py

Used to display a task hierarchy in the frontend if a task has subtasks.
See: https://github.com/4teamwork/gever-ui/pull/1158
JIRA: https://4teamwork.atlassian.net/browse/GEVER-419

Include task tree in task serialization

---

opengever/task/locales/fr/LC_MESSAGES/opengever.task.po

This is a follow-up of https://github.com/4teamwork/opengever.core/pull/6529 and belongs to the Jira issue https://4teamwork.atlassian.net/browse/GEVER-607

Add missing French translation.

---

docs/public/dev-manual/api/schemas/opengever.dossier.businesscasedossier.inc

The schema seems to be out of date.

Update businesscasedossier schema in dev documentation.

---

docs/HISTORY.txt

For https://4teamwork.atlassian.net/browse/GEVER-168

Update changelog after backport to 2020.4.1.

---

docs/HISTORY.txt
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py

The url is needed in the frontend to add a menu item in the user menu to go to the portal.
For https://4teamwork.atlassian.net/browse/GEVER-579
- API change:
- If breaking:

Add portal_url to configuration endpoint and view.

---

docs/HISTORY.txt
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/metadata.xml
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/profiles/default/registry.xml.bob

The policy creation did not work properly. It was also out of date.
Jira: https://4teamwork.atlassian.net/browse/GEVER-460

Improve policy creation.

---

README.rst

Update how to create multi admin unit setup with the following points:
- Document how to make authentication work again
- Make sure solr is started, too
For https://4teamwork.atlassian.net/browse/GEVER-439
- ~~[ ] Changelog entry~~

Update multi admin unit setup documentation.

---

docs/HISTORY.txt
opengever/policytemplates/hooks.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/deployment-+base.server_name+-+base.deployment_number+-+base.domain+.cfg.bob
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/ldap/ldap_plugin.xml.bob

This PR updates the policy generator with the newest knowledge after generating a teamraum policy.
- removes unused questions for the teamraum deplyoment
- sets useful default values for some teamraum deployment questions
- do ask for the full base-ldap name instead only the last part of it
- adds a useful help message for the base-ldap name
- add the admin-unit id to the client-policy in the buildout.cfg to properly load the client policy
- adds an additional questions for the `ogds_name`
- adds an additional questions for the `bumblebee_app_id`
- adds an additional questions for the `bumblebee_secret`
- adds an additional questions for the `workspace_secret`
Jira: https://4teamwork.atlassian.net/browse/GEVER-675
_Everything has to be done/checked. Checked but not present means the …

Update policy generator

---

docs/HISTORY.txt

Jira: https://4teamwork.atlassian.net/browse/GEVER-725

Update changelog after backport to 2020.8.1.

---

docs/HISTORY.txt
docs/public-fr/conf.py
docs/public/conf.py
opengever/sphinx/gevertheme/layout.html

⚠️ DO NOT MERGE OR DEPLOY TILL 2. OCTOBER ⚠️ 
Replace chatlio with the HubSpot Chat. Also add link to our Privacy Policy.
The HS Chat isn't activated yet. To test it append `?hschat=true` to the url
**Report time here**
```
[3.1.3.1.] Einführung neues CRM Hubspot
Konfiguration und Einrichten
Notiz: Chat
```
Link to the original chat implementation https://github.com/4teamwork/opengever.core/pull/6400
(Jira Ticket doesn't exist. Report time as given above.)
- API change:
- If breaking:
- DB-Schema …

Replace chatlio with HubSpot Chat.

---

opengever/base/utils.py

This PR removes an accidentally committed print statement from the PR #6648

Remove accidentally committed print statement

---

docs/HISTORY.txt

For https://4teamwork.atlassian.net/browse/CA-950

Correct changelog after backport to 2020.11.1.

---

opengever/core/testing.py

This enables customizing and reusing the layer in policies. See https://github.com/4teamwork/opengever.phvs/pull/161 for an example where this will be used.
Jira: https://4teamwork.atlassian.net/browse/CA-950

Provide factory method for fixture.

---

opengever/wopi/tests/test_validation.py

When running on Jenkins we don't have an interactive terminal.

Fix WOPI validator tests

---

README.rst
opengever/base/tests/test_contentlisting.py
opengever/contentstats/tests/test_content_stats_integration.py
opengever/document/tests/test_copy_document.py
opengever/document/tests/test_document.py
opengever/document/tests/test_indexers.py
opengever/dossier/tests/test_templatefolder.py
opengever/officeconnector/tests/test_api_dossier_oneoffixx.py
opengever/oneoffixx/tests/assets/oneoffixx_connect_xml.txt
opengever/testing/fixtures.py
opengever/workspace/tests/test_todolist.py

This PR extends the workspace testing fixture with:
- an email within a workspace
- a document within a folder
Jira: https://4teamwork.atlassian.net/browse/NE-124

Extend the workspace testing fixture.

---

opengever/api/dossier_participations.py
opengever/dossier/participations.py

During the review of the refactoring of the participations (https://github.com/4teamwork/opengever.core/pull/6655) a new endpoint for possible participants was added (https://github.com/4teamwork/opengever.core/pull/6675). This is a follow up PR to also use the Participation handlers in that endpoint.
For https://4teamwork.atlassian.net/browse/NE-90 or maybe https://4teamwork.atlassian.net/browse/CA-17

Use ParticipationHandler in possible participants endpoint.

---

opengever/activity/locales/fr/LC_MESSAGES/opengever.activity.po
opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/inbox/locales/fr/LC_MESSAGES/opengever.inbox.po
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/readonly/locales/fr/LC_MESSAGES/opengever.readonly.po
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
opengever/wopi/locales/fr/LC_MESSAGES/opengever.wopi.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po

Seems we had not taken care of the French translations in a while... I added all the missing translations and will try to do it every sprint in the future.
For https://4teamwork.atlassian.net/browse/CA-1110

Add missing French translations.

---

docs/public/dev-manual/api/schemas/opengever.workspace.workspace.inc
docs/public/user-manual/suchen.rst

I have removed the not longer actual part about operators, currently
they are not supported.
https://4teamwork.atlassian.net/browse/CA-727

Update and fixed search chapter in the user manual.

---

README.rst

Fix the readme, get rid of errors and warnings that managed to sneak in and lead to Solry sync section not being displayed correctly.
Jira: https://4teamwork.atlassian.net/browse/CA-1214

Various readme fixes.

---

docs/HISTORY.txt

For https://4teamwork.atlassian.net/browse/CA-1214

Update changelog after backport to 2020.14.2.

---

docs/HISTORY.txt

For https://4teamwork.atlassian.net/browse/CA-1297

Update changelog after release of 2020.14.4.

---

opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspaceclient/locales/fr/LC_MESSAGES/opengever.workspaceclient.po

For https://4teamwork.atlassian.net/browse/CA-1110

Add French translations for release 2020.15.0.

---

docs/HISTORY.txt

Jira: https://4teamwork.atlassian.net/browse/CA-1216

Update changelog after release of 2020.14.5 and 2020.15.1.

---

development.cfg

By extracting it into a configuration variable when can override the variable in anything that extends from development.cfg. This has become necessary when one wants to run the dockerized bumblebee locally.
- ~~[ ] Changelog entry~~
- ~~[ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)~~

Make bumblebee internal plone url overwriteable.

---

opengever/wopi/locales/de/LC_MESSAGES/opengever.wopi.po
opengever/wopi/locales/fr/LC_MESSAGES/opengever.wopi.po
opengever/wopi/locales/opengever.wopi.pot

Follow up for #6790 🙈
Jira: https://4teamwork.atlassian.net/browse/NE-446

Add translation.

---

docs/HISTORY.txt

For https://4teamwork.atlassian.net/browse/CA-1395

Update changelog after hotfix release 2020.14.6.

---

opengever/advancedsearch/locales/en/LC_MESSAGES/opengever.advancedsearch.po
opengever/advancedsearch/tests/test_search.py

Clean up English og.advancedsearch translations.

Clean up English og.advancedsearch translations.

---

opengever/bumblebee/locales/en/LC_MESSAGES/opengever.bumblebee.po
opengever/bumblebee/tests/test_overlay_view.py
opengever/bumblebee/tests/test_revive_bumblebee_preview.py

Clean up English `og.bumblebee` translations.

Clean up English og.bumblebee translations.

---

opengever/quota/locales/en/LC_MESSAGES/opengever.quota.po
opengever/quota/tests/test_quota_container.py
opengever/quota/tests/test_usage_view.py

Clean up English `og.quota` translations.

Clean up English og.quota translations.

---

opengever/private/locales/en/LC_MESSAGES/opengever.private.po
opengever/private/tests/test_viewlets_quotawarning.py

Clean up English `og.private` translations.

Clean up English og.private translations.

---

opengever/journal/tests/test_integration.py
opengever/sharing/locales/en/LC_MESSAGES/opengever.sharing.po

Clean up English `og.sharing` translations.

Clean up English og.sharing translations.

---

opengever/activity/tests/test_handlers.py
opengever/activity/tests/test_mail.py
opengever/activity/tests/test_plone_center.py
opengever/api/tests/test_task.py
opengever/base/tests/test_default_values_for_types.py
opengever/base/tests/test_indexers.py
opengever/inbox/tests/test_workflow.py
opengever/latex/tests/test_dossiertasks.py
opengever/meeting/tests/test_proposal_overview.py
opengever/officeconnector/tests/test_api_task_checkout.py
opengever/task/locales/en/LC_MESSAGES/opengever.task.po
opengever/task/tests/test_activities.py
opengever/task/tests/test_assign.py
opengever/task/tests/test_assign_to_dossier.py
opengever/task/tests/test_deadline_modification.py
opengever/task/tests/test_delegate.py
opengever/task/tests/test_overview.py
opengever/task/tests/test_private_task.py
opengever/task/tests/test_redirector.py
opengever/task/tests/test_reminder.py
opengever/task/tests/test_reminder_model.py
opengever/task/tests/test_reminder_storage.py
opengever/task/tests/test_resolve.py
opengever/task/tests/test_response.py
opengever/task/tests/test_response_descriptions.py
opengever/task/tests/test_revoke_permissions.py
opengever/task/tests/test_sequential_task_process.py
opengever/task/tests/test_task.py
opengever/task/tests/test_task_byline.py
opengever/task/tests/test_team_tasks.py

Clean up English `og.task` translations.
For overall comments on the process, please see PR #6806

Clean up English og.task translations.

---

docs/HISTORY.txt
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/interfaces.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20210115102607_add_hub_spot_feature_flag/registry.xml
opengever/core/upgrades/20210115102607_add_hub_spot_feature_flag/upgrade.py
opengever/policytemplates/policy_template/.mrbob.ini
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob

If the HubSpot feature is enabled, the HubSpot chat is integrated in the new frontend.
Jira: https://4teamwork.atlassian.net/browse/NE-224
- API change:

Add HubSpot feature flag.

---

opengever/disposition/locales/en/LC_MESSAGES/opengever.disposition.po
opengever/disposition/tests/test_activities.py
opengever/disposition/tests/test_disposition.py
opengever/disposition/tests/test_ech0160export.py
opengever/disposition/tests/test_excel_export.py
opengever/disposition/tests/test_history.py
opengever/disposition/tests/test_listing.py
opengever/disposition/tests/test_overview.py

Clean up English `og.disposition` translations.

Clean up English og.disposition translations.

---

opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot
opengever/workspace/workspace_meeting.py

Simple autocomplete list field for meeting participants.

Add participants field to workspace meeting.

---

opengever/workspace/workspace_meeting.py

JSON Fields

---

opengever/mail/locales/en/LC_MESSAGES/opengever.mail.po
opengever/mail/tests/test_extract_attachments.py
opengever/mail/tests/test_mail_overviewtab.py
opengever/mail/tests/test_mail_previewtab.py
opengever/mail/tests/test_senddocument.py
opengever/trash/tests/test_trash.py

Clean up English `og.mail` translations.

Clean up English og.mail translations

---

opengever/base/tests/test_classification.py
opengever/document/tests/test_download.py
opengever/journal/locales/en/LC_MESSAGES/opengever.journal.po
opengever/journal/tests/test_document_journalization.py
opengever/journal/tests/test_integration.py
opengever/journal/tests/test_manual_entry.py
opengever/journal/tests/test_zipexport_events.py
opengever/mail/tests/test_mail_download_copy.py
opengever/repository/tests/test_reference_prefix_manager.py
opengever/trash/tests/test_remove.py

Clean up English `og.journal` translations.

Clean up English og.journal translations.

---

opengever/tasktemplates/locales/en/LC_MESSAGES/opengever.tasktemplates.po
opengever/tasktemplates/tests/test_activities.py
opengever/tasktemplates/tests/test_sources.py
opengever/tasktemplates/tests/test_tasktemplate.py
opengever/tasktemplates/tests/test_trigger.py

Clean up English `og.tasktemplates` translations.

Clean up English og.tasktemplates translations.

---

opengever/api/tests/test_accept_remote_task.py
opengever/api/tests/test_complete_successor_task.py
opengever/api/tests/test_dossier_participations.py
opengever/api/tests/test_listing.py
opengever/api/tests/test_task_predecessor.py
opengever/api/tests/test_task_successor.py
opengever/contact/tests/test_participation.py
opengever/contact/tests/test_participation_tab.py
opengever/document/vdexvocabs/document_types.vdex
opengever/dossier/tests/test_archiver.py
opengever/dossier/tests/test_participation.py
opengever/dossier/vdexvocabs/container_types.vdex
opengever/dossier/vdexvocabs/participation_roles.vdex
opengever/dossier/vdexvocabs/type_prefixes.vdex
opengever/globalindex/tests/test_reporter.py
opengever/journal/vdexvocabs/manual_journal_entry_categories.vdex
opengever/latex/tests/test_listing.py
opengever/propertysheets/tests/test_assignment.py
opengever/repository/tests/test_repositoryfolder_tabs.py
opengever/task/tests/test_overview.py
opengever/task/tests/test_private_task.py
opengever/task/vdexvocabs/bidirectional_by_reference.vdex
opengever/task/vdexvocabs/unidirectional_by_reference.vdex
opengever/task/vdexvocabs/unidirectional_by_value.vdex

Clean up English translations in VDEX vocabularies.

Clean up English translations in VDEX vocabularies.

---

docs/HISTORY.txt
opengever/base/locales/de/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/de/LC_MESSAGES/plone.po
opengever/base/locales/en/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/en/LC_MESSAGES/plone.po
opengever/base/locales/fr/LC_MESSAGES/ftw.tabbedview.po
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/base/locales/ftw.tabbedview.pot
opengever/base/locales/opengever.base.pot
opengever/base/locales/plone.pot
opengever/base/tests/test_copy_paste.py
opengever/oneoffixx/tests/test_oneoffixx.py
opengever/tabbedview/locales/en/LC_MESSAGES/opengever.tabbedview.po

This fixes some minor translation issues.
Screenshots depict the old state (to be fixed).
---
---
---

Minor translation fixes

---

opengever/workspace/browser/registration.py

LDAPUserFolder needs acquisition

Fix OGDS self registration

---

opengever/api/solr_query_service.py
opengever/core/upgrades/20210121170444_reindex_meeting_participations/upgrade.py
opengever/workspace/configure.zcml
opengever/workspace/indexers.py

To filter meetings a specific user is participating on.

Index meeting participants

---

development.cfg
docker-compose.yml
opengever/core/locales/de/LC_MESSAGES/opengever.core.po
opengever/core/locales/en/LC_MESSAGES/opengever.core.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/locales/opengever.core.pot
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20210122111713_add_meeting_minutes_pdf_action/actions.xml
opengever/core/upgrades/20210122111713_add_meeting_minutes_pdf_action/upgrade.py
opengever/workspace/browser/configure.zcml
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt

Uses WeasyPrint for PDF generation from HTML.
WeasyPrint is integrated as dockerized a web service.

Create PDF of meeting minutes

---

opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/wopi/locales/fr/LC_MESSAGES/opengever.wopi.po

Update translations for new release
For https://4teamwork.atlassian.net/browse/CA-1110

Add missing French and English translations.

---

docs/public/dev-manual/api/propertysheets.rst

Fix an error in the custom property docs.

Fix nesting in custom property docs.

---

docs/public/dev-manual/api/api_changelog.rst

Fix a typo in the api changelog.

Fix typo in api changelog.

---

docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/schemas/opengever.repository.repositoryfolder.inc
docs/public/dev-manual/api/schemas/opengever.repository.repositoryroot.inc
docs/public/dev-manual/api/schemas/opengever.workspace.root.inc

Jira: https://4teamwork.atlassian.net/browse/CA-1305

Minor fixes for api docs, have consistent changelog, include title_en in type docs.

---

opengever/document/tests/test_document.py
opengever/propertysheets/storage.py
opengever/propertysheets/tests/test_document_default_view.py
opengever/propertysheets/tests/test_document_forms.py
opengever/propertysheets/tests/test_mail_default_view.py
opengever/propertysheets/tests/test_mail_forms.py
opengever/propertysheets/tests/test_schema_definition_delete.py
opengever/propertysheets/tests/test_schema_definition_get.py
opengever/propertysheets/tests/test_schema_definition_post.py
opengever/propertysheets/tests/test_schema_endpoint.py
opengever/propertysheets/tests/test_storage.py
opengever/testing/fixtures.py

This helps E2E tests as they will contain test-cases where custom properties are required.
Jira: https://4teamwork.atlassian.net/browse/NE-367

Add two property sheets to fixture.

---

docs/HISTORY.txt
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default_content/opengever_content/03_committees.json.bob

Seems these were forgotten in the policy templates.
For https://4teamwork.atlassian.net/browse/CA-984

Also set title_en and title_fr for meetings in policy templates.

---

opengever/base/tests/test_default_values_for_types.py
opengever/propertysheets/tests/test_schema_definition_delete.py
opengever/propertysheets/tests/test_schema_definition_get.py
opengever/propertysheets/tests/test_schema_definition_post.py
opengever/testing/fixtures.py

Used by frontend e2e tests, see https://github.com/4teamwork/gever-ui/pull/1689#pullrequestreview-622154384
https://4teamwork.atlassian.net/browse/CA-1493

Add property sheets to testing fixture

---

opengever/contact/locales/fr/LC_MESSAGES/opengever.contact.po

Closes https://4teamwork.atlassian.net/browse/CA-717

Fixed french translation for "salutation"

---

opengever/core/upgrades/20210325095837_reindex_missing_searchable_text/upgrade.py

Sorry this upgrade step was not working, as the logging was messed up. There is no CL as this change is unreleased.
For https://4teamwork.atlassian.net/browse/CA-1361

Fix broken upgrade step reindexing missing searchable text.

---

changes/CA-2135.feature
opengever/base/reporter.py
opengever/globalindex/browser/report.py
opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/en/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/opengever.globalindex.pot
opengever/globalindex/tests/test_reporter.py

Jira: https://4teamwork.atlassian.net/browse/CA-2135

Add description to task report and link title to task.

---

changes/CA-2281.bugfix
opengever/meeting/model/agendaitem.py
opengever/meeting/tests/test_agendaitem.py

Fix for https://4teamwork.atlassian.net/browse/CA-2281

Fix deleting agenda_items when document is already trashed.

---

opengever/core/upgrades/20210519102848_fix_inbox_workflow_policy_assignment/upgrade.py

Follow up for https://github.com/4teamwork/opengever.core/pull/7028 and a fix for one of the possible code branches.
✅  I have now manually stepped through the upgrade to verify it works.
Jira: https://4teamwork.atlassian.net/browse/CA-2262

Fix upgrade step placeful workflow assignment.

---

versions.cfg

Add forgotten version pinning for clamd.
For https://4teamwork.atlassian.net/browse/CA-1504

Add version pin for clamd.

---

changes/CA-2125.bugfix
opengever/api/tests/test_task.py
opengever/base/default_values.py
opengever/base/tests/test_default_values_for_types.py
opengever/core/upgrades/20210609114623_persist_deadline_on_tasks/upgrade.py
opengever/core/upgrades/20210609114639_persist_document_date/upgrade.py

With this PR we fix an issue where default values do not get persisted on objects created over the API. The problem arose only when setting as value the `default_value` for the field, as in that case our `set_default_values` method would skip setting the default for that field as the user has explicitly passed a value, but that value would then be ignored in the deserializer as it is equal to the default value (https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/deserializer/dxcontent.py#L137-L139).
Because we cannot easily check whether the passed value matches the default value in `set_default_values` (because we have the raw value, not yet deserialized), there were two choices:
- Monkey patch the `DeserializeFromJson.get_schema_data` 
- modify `set_default_values` to …

Fix persisting default values for objects created over API

---

changes/CA-2375.other
opengever/mail/browser/mail.py
opengever/mail/mail.py

While working on fixing eml attached to E-mails I found some inefficiencies in the code on the Gever side, that I fix here.
For https://4teamwork.atlassian.net/browse/CA-2375

Minor optimization of mail attachment code.

---

docs/public/dev-manual/api/api_changelog.rst

Add missing API changelog entry

---

.github/pull_request_template.md

Replace XXXX with ticket number to link pr to jira ticket.

Update pull request template.

---

HISTORY.rst

Also include missing 2021.13.1 changelog section.
For https://4teamwork.atlassian.net/browse/CA-2553

Update changelog after backport to 2021.13.2.

---

changes/CA-2371.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/serializer.py
opengever/api/tests/test_serializer.py

For [CA-2371](https://4teamwork.atlassian.net/browse/CA-2371)
- API change:

Add sequence_number to all API object serializers.

---

docs/public/dev-manual/api/api_changelog.rst

Sorry forgot to update the api changelog after the release
For [CA-2494]
[CA-2494]: https://4teamwork.atlassian.net/browse/CA-2494

Update API changelog after release.

---

changes/CA-2674.bugfix
opengever/core/upgrades/20210802134316_update_one_note_mimetype/mimetypes.xml
opengever/core/upgrades/20210802134316_update_one_note_mimetype/upgrade.py
opengever/policy/base/profiles/mimetype/mimetypes.xml

We include application/msonenote as mimetype for OneNote.
For [CA-2674]
[CA-2674]: https://4teamwork.atlassian.net/browse/CA-2674

Update OneNote Mimetype.

---

changes/CA-2366.feature

Sorry... 😅 
For [CA-2366]
[CA-2366]: https://4teamwork.atlassian.net/browse/CA-2366

Add forgotten changelog.

---

opengever/document/forms.py
opengever/dossier/filing/form.py
opengever/dossier/move_items.py
opengever/mail/browser/send_document.py
opengever/meeting/committee.py
opengever/repository/behaviors/referenceprefix.py
opengever/task/browser/accept/existingdossier.py
opengever/task/browser/accept/main.py
opengever/task/browser/assign.py
opengever/task/browser/close.py
opengever/task/transition.py
opengever/virusscan/validator.py

I've gone through the validators double-checking if things are validated properly. I am leaving some comments for future readers so that we don't have to double-check again.
For [CA-2156](https://4teamwork.atlassian.net/browse/CA-2156)

Add comments to validator indicating usage.

---

changes/CA-1269.other
opengever/setup/sections/xlssource.py

I'm fed up with trying to transform numbers to Text format in Excel, which is simply broken. And I don't want to replace "ja" with "Ja" or the opposite depending on the column. So here it is...
For [CA-1270]
[CA-1270]: https://4teamwork.atlassian.net/browse/CA-1270

Make import of repository excel files more robust.

---

changes/CA-2606.feature
opengever/core/profiles/default/registry.xml
opengever/core/upgrades/20210916140008_add_ku_b_settings/registry.xml
opengever/core/upgrades/20210916140008_add_ku_b_settings/upgrade.py
opengever/kub/__init__.py
opengever/kub/client.py
opengever/kub/configure.zcml
opengever/kub/interfaces.py
opengever/kub/tests/test_kub_client.py
opengever/kub/tests/test_kub_configuration.py

We add KUB integration. Setup for local development against KUB is described in https://github.com/4teamwork/kub/pull/48
For [CA-2606]

Add KUB configuration and client.

---

opengever/core/upgrades/20211105142527_make_workspace_meetings_timezone_aware/upgrade.py

Well it seems the hack in the upgrade did not work always work, maybe when executed together with other upgrades. I now instead unindex all the meetings first, make sure the indexing queue is processed and then reindex them. I also made the upgrade step deferrable.
For [CA-3150]
[CA-3150]: https://4teamwork.atlassian.net/browse/CA-3150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix upgrade making workspace meeting start and end timezone aware.

---

opengever/dossier/move_items.py

A pdb sneaked in with  #7235 🙈🙈🙈

Remove pdb.

---

changes/CA-2278.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/substitutes.rst
opengever/api/configure.zcml
opengever/api/substitutes.py
opengever/api/tests/test_substitutes.py
opengever/ogds/base/substitute.py
opengever/ogds/models/substitute.py

The endpoint is needed to determine for whom a user is the substitute.
For [CA-2278]
- API change:
[CA-2278]: https://4teamwork.atlassian.net/browse/CA-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add @substitutions API endpoint

---

changes/CA-2405.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_workspace.py
opengever/api/tests/test_workspace_folder.py
opengever/api/workspace.py
opengever/api/workspace_folder.py

For [CA-2405]
- API change:
[CA-2405]: https://4teamwork.atlassian.net/browse/CA-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include email address in workspace and workspace folder serialization

---

opengever/api/tests/test_linked_workspaces.py

For [CA-1686]
[CA-1686]: https://4teamwork.atlassian.net/browse/CA-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix flaky test, introduced with PR 7307.

---

.github/pull_request_template.md

Update review checklist with points about
- SQL operations in Upgrade-Steps
- Resolving Sentry issues when fixing bugs
For [CA-3574](https://4teamwork.atlassian.net/browse/CA-3574)

Update review checklist

---

changes/CA-3583.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/searching.rst
opengever/api/solrsearch.py
opengever/api/tests/test_solrsearch.py

Implements new filter-queries for the `@solrsearch` endpoint according to https://github.com/4teamwork/opengever.core/pull/7299/commits/a65022472c3f7996bf8eed18c3cfb8a13d8fa7e1
It implements these two new filter queries:
- `url_parent`
- `@id_parent`
The filter-queries works like the `path_parent` filter but can be used with an url instead a relative path.
For [CA-3583]
- API change:
- If breaking:
- Bug fixed:
[CA-3583]: https://4teamwork.atlassian.net/browse/CA-3583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …

Add a url_parent/@id_parent filter for the @solrsearch endpoint

---

README.rst
changes/testserver.feature
docker-compose.testserver.yml
docker/testserver/Dockerfile
docker/testserver/docker-entrypoint.sh

The goal is to make it easier to run the gever testserver with docker compose when working on third party projects (such as ris and vertragsmanagement) because using docker is much simpler when not working directly on opengever.core.
This pull request basically adds a working, minimal docker compose example only containing the testserver and adds some convenience.
Changes:
- A `docker-compose.testserver.yml` is provided, so that it can be copied to other projects. It contains a minimal working example with everything needed for the testserver. It also contains a commented example of how to mount a fixture module using a volume, because that's what third party projects usually do.
- The testserver image is extended to have sane defaults for service `ENV`s using the common service names and …

Testserver: add docker-compose example

---

changes/CA-3857.bugfix
opengever/api/tus.py
opengever/document/base.py
opengever/document/document.py
opengever/document/quick_upload.py
opengever/meeting/tests/test_proposal.py

Fixes [CA-3857]
[CA-3857]: https://4teamwork.atlassian.net/browse/CA-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix docx upload validator, make docx mandatory only for the proposal document.

---

changes/CA-3725-4.feature
opengever/api/process.py
opengever/api/tests/test_process.py

This PR is a follow-up PR for #7416 which extends the `ITaskContainer` schema with a deadline.
This allows us to optionally set the deadline for a task container or main task through the api which was already possible with the old `@trigger-task-template` endpoint.
We do not change the current behavior of deadlines based on the subtasks if no deadline is provided.
For [CA-3725]
- API change:
- If breaking:
- Bug fixed:
[CA-3725]: https://4teamwork.atlassian.net/browse/CA-3725?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

@process endpoint also accepts a deadline for task folders.

---

opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/workspaceclient/locales/fr/LC_MESSAGES/opengever.workspaceclient.po

Add missing french translations.
Slack: https://4teamwork.slack.com/archives/C01BHEGBVU1/p1649836363595599
For [CA-4011]
[CA-4011]: https://4teamwork.atlassian.net/browse/CA-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing french translations

---

opengever/api/tasktree.py

This is a follow-up PR for https://github.com/4teamwork/opengever.core/pull/7432 wich implements the suggestions of @njohner.
This PR mainly increases readability and makes it more clear by rewording comments and function names.
For [CA-3725]
- API change:
- If breaking:
- Bug fixed:

Refactoring @tasktree endpoint to make the implementation more clear.

---

docs/public-fr/user-manual/chapitre14-depot.rst
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/tests/test_checkout.py
opengever/base/locales/fr/LC_MESSAGES/plone.po
opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
opengever/core/upgrades/20220419134503_modify_title_fr_of_private_repository_root/upgrade.py
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po
opengever/examplecontent/profiles/default_content/content_creation/01_default_content.json
opengever/journal/locales/fr/LC_MESSAGES/opengever.journal.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default_content/opengever_content/01-initial-structure.json.bob
opengever/repository/locales/fr/LC_MESSAGES/opengever.repository.po
opengever/setup/profiles/default_content/content_creation/01_default_content.json
opengever/task/locales/fr/LC_MESSAGES/opengever.task.po

For [CA-3930]
[CA-3930]: https://4teamwork.atlassian.net/browse/CA-3930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve French translations

---

opengever/dossier/configure.zcml
opengever/dossier/handlers.py
opengever/dossier/tests/test_indexer.py

Follow up for #7442 
For [CA-3970]
[CA-3970]: https://4teamwork.atlassian.net/browse/CA-3970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make sure dossiers searchableText gets reindexed when comment is added.

---

opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/tests/test_linked_workspaces.py
opengever/api/tests/test_task.py
opengever/workspaceclient/locales/en/LC_MESSAGES/opengever.workspaceclient.po
opengever/workspaceclient/locales/fr/LC_MESSAGES/opengever.workspaceclient.po

For [CA-2646]
[CA-2646]: https://4teamwork.atlassian.net/browse/CA-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing and improve existing French and English translations.

---

changes/CA-4306.feature
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/dossier_participations.rst
opengever/api/dossier_participations.py
opengever/api/tests/test_dossier_participations.py
opengever/core/upgrades/20220623153114_add_primary_participation_roles_setting/registry.xml
opengever/core/upgrades/20220623153114_add_primary_participation_roles_setting/upgrade.py
opengever/dossier/interfaces.py

Participants with these roles are listed separately on the dossier overview in the new UI.
For [CA-4306]
- API change:
[CA-4306]: https://4teamwork.atlassian.net/browse/CA-4306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add primary_participation_roles

---

changes/CA-4208.bugfix
changes/CA-4208.other
opengever/ogds/base/browser/templates/userdetails_table.pt
opengever/ogds/base/browser/userdetails.py
opengever/ogds/base/tests/test_userdetails.py
opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default_content/opengever_content/01-initial-structure.json.bob

For [CA-4208]
[CA-4208]: https://4teamwork.atlassian.net/browse/CA-4208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove contact folder from policy template

---

changes/CA-4422.bugfix
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tests/test_actors.py
opengever/ogds/base/actor.py

For [CA-4422]
- API change:
[CA-4422]: https://4teamwork.atlassian.net/browse/CA-4422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Also handle groupids with group prefix in @actors endpoint

---

solr-conf/solrconfig.xml

This is needed for reindexing Solr with the data import handler.
For [CA-4241](https://4teamwork.atlassian.net/browse/CA-4241)

Enable langid processor in data import handler

---

changes/CA-4096.feature
opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt
opengever/workspace/tests/test_meeting_minutes.py

For [CA-4096]
[CA-4096]: https://4teamwork.atlassian.net/browse/CA-4096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include links to related items in the teamraum meetings pdf.

---

changes/CA-4280.other
opengever/bumblebee/tests/test_overlay_view.py
opengever/core/profiles/default/actions.xml
opengever/core/upgrades/20190726084602_add_document_actions_for_api/actions.xml
opengever/document/browser/templates/macros.pt
opengever/document/browser/versions_tab.py
opengever/document/checkout/manager.py
opengever/document/checkout/revert.py
opengever/document/locales/de/LC_MESSAGES/opengever.document.po
opengever/document/locales/en/LC_MESSAGES/opengever.document.po
opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
opengever/document/locales/opengever.document.pot
opengever/document/tests/test_checkout.py
opengever/document/tests/test_versions_tab.py

For [CA-4280]
[CA-4280]: https://4teamwork.atlassian.net/browse/CA-4280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rename action to restore a document version

---

changes/CA-3998.other
opengever/task/browser/transitioncontroller.py
opengever/task/tests/test_transitioncontroller.py

We allow the responsible to directly close a task of direct execution type.
For [CA-3998]
[CA-3998]: https://4teamwork.atlassian.net/browse/CA-3998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow responsible to directly close tasks for direct execution.

---

HISTORY.rst

Fix changelog RST syntax before release.
For [CA-4085](https://4teamwork.atlassian.net/browse/CA-4085)

Fix changelog RST syntax before release.

---

opengever/mail/browser/inbound.py

To avoid fuzzy matches when looking up the user by email address for inbound mails, the `pas_search` call [was extended with `exact_match=True`](https://github.com/4teamwork/opengever.core/commit/28d28fda2c1753d81662a4639eff123c86b0938e) to accomplish this.
However, it turns out that the `ActiveDirectoryMultiPlugin` [refuses to do searches](https://github.com/4teamwork/Products.LDAPMultiPlugins/blob/3c8a9aeaa125e23de919312891942bb07ead5ffb/Products/LDAPMultiPlugins/ActiveDirectoryMultiPlugin.py#L341-L348) with `exact_match=True`, unless the query criteria contain the user's id or login. For the `LDAPMultiPlugin` this [works fine](https://github.com/4teamwork/Products.LDAPMultiPlugins/blob/3c8a9aeaa125e23de919312891942bb07ead5ffb/Products/LDAPMultiPlugins/LDAPMultiPlugin.py#L188-L205), but …

Fix user lookup by email for inbound mail

---

opengever/document/activities.py
opengever/workspaceclient/linked_workspaces.py
test-qa.cfg

Prior to this change only the exit code of isort was used and flake8 violations were not reported as failures.
For [CA-XXXX]

Fix exit code of QA tests

---

opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po

For [CA-4088]
[CA-4088]: https://4teamwork.atlassian.net/browse/CA-4088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing english translations.

---

opengever/workspace/participation/templates/invitation_mail.pt

Follow up for https://github.com/4teamwork/opengever.core/pull/7598
The structure leads to an error in the translations. When running `bin/i18n-build opengever.workspace` an error was thrown and the mail translations were removed from the po files. This way it doesn't happen anymore.
```
File "/Users/tinagerber/.buildout/cache/eggs/i18ndude-4.4.0-py2.7.egg/i18ndude/extract.py", line 523, in tal_strings
parser.parseFile(filename)
File "/Users/tinagerber/.buildout/cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/htmltalparser.py", line 122, in parseFile
self.parseString(data)
File "/Users/tinagerber/.buildout/cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/htmltalparser.py", line 128, in parseString
self.feed(data)
File …
```

Fix workspace invitation mail

---

changes/CA-5004.other
opengever/api/tests/test_complete_successor_task.py
opengever/task/validators.py

There is no reason to restrict this to documents only.
For [CA-5004]
[CA-5004]: https://4teamwork.atlassian.net/browse/CA-5004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Also allow to deliver mails back to the predecessor task.

---

changes/CA-4934.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/operations.rst
opengever/api/templatefolder.py
opengever/api/tests/test_dossiertemplate.py
opengever/api/tests/test_templatefolder.py
opengever/base/tests/test_default_values_for_types.py
opengever/core/upgrades/20221128095428_remove__comments__field_for_dossier_templates/upgrade.py
opengever/dossier/base.py
opengever/dossier/browser/overview.py
opengever/dossier/command.py
opengever/dossier/dossiertemplate/behaviors.py
opengever/dossier/dossiertemplate/dossiertemplate.py
opengever/dossier/tests/test_dossier_template.py
opengever/dossier/utils.py

Remove comments field for dossier templates, and any associated code/tests.
For [CA-4934](https://4teamwork.atlassian.net/browse/CA-4934)
- API change:

Remove comments field for dossier templates

---

changes/CA-5149.bugfix
opengever/globalindex/model/task.py
opengever/globalindex/tests/test_reporter.py
opengever/globalindex/utils.py

Task listing excel and PDF exports were failing with Oracle with the error `DatabaseError: (cx_Oracle.DatabaseError) ORA-00932: inconsistent datatypes: expected - got CLOB`. This is due to path queries, which we need to convert to CHAR first. This issue had already been fixed once in https://github.com/4teamwork/opengever.core/pull/4884.
For [CA-5149]
[CA-5149]: https://4teamwork.atlassian.net/browse/CA-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix task listing export to excel and PDF for Oracle.

---

changes/CA-4097.feature
opengever/api/configure.zcml
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/save_minutes_as_pdf.py
opengever/api/tests/test_save_minutes_as_pdf.py
opengever/base/context_actions.py
opengever/workspace/actions.py
opengever/workspace/tests/test_actions.py

Add new `@save-protocol-as-pdf` API endpoint and `save_protocol_as_pdf` action.
For [CA-4097]
[CA-4097]: https://4teamwork.atlassian.net/browse/CA-4097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new @save-minutes-as-pdf API endpoint.

---

changes/CA-5697.bugfix
opengever/disposition/ech0160/model/additional_data.py
opengever/disposition/tests/test_model.py

For [CA-5697]
[CA-5697]: https://4teamwork.atlassian.net/browse/CA-5697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support date custom fields in ech0160 export.

---

README.rst

No changelog entry, we just update the documentation.
For [CA-5463]
[CA-5463]: https://4teamwork.atlassian.net/browse/CA-5463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update README to include information about creating solr image.

---

changes/CA-5963.bugfix
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po

For [CA-5936]
[CA-5936]: https://4teamwork.atlassian.net/browse/CA-5936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust french translation in invitation mail title.

---

clamav/clamd.conf
docker-compose.yml

As we already did for our shared service, it makes sense to use the same container configuration for local development.
Detected during analysis of [CA-5961]
[CA-5961]: https://4teamwork.atlassian.net/browse/CA-5961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch clamav container to official docker image.

---

changes/CA-5602.other
opengever/policytemplates/policy_template/opengever.+package.name+/.gitignore
opengever/policytemplates/policy_template/opengever.+package.name+/compose-+base.server_name+-+base.deployment_number+-+base.domain+.yml.bob

New SaaS deployments should have the frontend dockerized.
For [CA-5602]
[CA-5602]: https://4teamwork.atlassian.net/browse/CA-5602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add docker-compose file to policytemplates.

---

opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po

No CL.
For [CA-6075]
[CA-6075]: https://4teamwork.atlassian.net/browse/CA-6075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix french translation for ToDo commented by.

---

changes/CA-5662.other
docs/public/dev-manual/api/api_changelog.rst
opengever/officeconnector/configure.zcml
opengever/officeconnector/helpers.py
opengever/officeconnector/service.py
opengever/officeconnector/testing.py
opengever/officeconnector/tests/test_api_is_mail_fileable.py

Add endpoint to check if OC attach mail can be filed.
For [CA-5662](https://4teamwork.atlassian.net/browse/CA-5662)
- API change:
[CA-5662]: https://4teamwork.atlassian.net/browse/CA-5662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add endpoint to check if OC attach mail can be filed.

---

README.rst

Update README for local policyless deployment.
For [CA-6039](https://4teamwork.atlassian.net/browse/CA-6039)
[CA-6039]: https://4teamwork.atlassian.net/browse/CA-6039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update README for local policyless deployment.

---

changes/CA-6039-6.feature
opengever/base/schemadump/config.py
opengever/base/schemadump/schema.py
opengever/bundle/browser/import_bundle.py
opengever/bundle/importer.py
opengever/bundle/initial_content.py
opengever/bundle/loader.py
opengever/bundle/schemas/inboxes.schema.json
opengever/bundle/sections/bundlesource.py
opengever/bundle/sections/constructor.py
opengever/bundle/sections/resolveguid.py
opengever/bundle/tests/test_initial_content_factory.py
opengever/bundle/tests/test_oggbundle_pipeline_policyless.py

Policyless bundle import: Add support for creating initial content if none was provided in the policyless bundle.
Example snippet from import log:
```
...
2023-08-21 17:48:34 INFO opengever.bundle.loader Raw items in bundle <Bundle /var/folders/_n/v5scd65x73982lwk77v07wr40000gn/T/ttw-bundle-dAhVhd.oggbundle>
2023-08-21 17:48:34 INFO opengever.bundle.loader ================================================================================
2023-08-21 17:48:34 INFO opengever.bundle.loader repofolders.json     3
2023-08-21 17:48:34 INFO opengever.bundle.loader reporoots.json       1
2023-08-21 17:48:34 INFO opengever.bundle.loader
2023-08-21 17:48:34 INFO opengever.bundle.progress Starting migration (4 raw items total in bundle)
2023-08-21 17:48:34 INFO opengever.bundle.resolveguid
2023-08-21 …
```

Policyless bundle import: Add support for creating initial content

---

opengever/api/tests/test_tus.py

Defer TUS upload lock test by another 2 months.

---

changes/CA-5695.other
opengever/base/warmup.py

It's a bit of a quick and dirty fix, but should be fine IMO.
For [CA-5695]
[CA-5695]: https://4teamwork.atlassian.net/browse/CA-5695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix @@warmup view for Teamraum and PloneSites owned by anonymous.

---

docs/public/dev-manual/oggbundle/index.rst

we have French speaking customer who also need the bundle specification. IMHO english is ok for such a technical documentation.

Translate OGGBundle specification to english.

---

opengever/ogds/models/tests/test_user.py
opengever/ogds/models/user.py
opengever/ogds/models/utils.py

Introduce cached mappings from username to userid and vice-versa.
For [CA-6237]

Add mappings for username to userid and vice-versa.

---

opengever/api/tests/test_tus.py

Bump TUS lock token test yet again.

Bump TUS lock token test yet again.

---

changes/CA-6418.bugfix
docker/core/entrypoint.d/create_solr_zcml.py

For [CA-6418](https://4teamwork.atlassian.net/browse/CA-6418)
[CA-6418]: https://4teamwork.atlassian.net/browse/CA-6418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix configuring Solr base URL in Docker container

---

opengever/document/subscribers.py
opengever/document/tests/test_document.py

For [CA-6237]
~- [ ] Changelog entry~

Let document_author resolving also work for usernames.

---

opengever/disposition/ech0160/sippackage.py

according to the customer need.
For [CA-6302]
~- [ ] Changelog entry~ not necessary, changelog exists for the feature in this release.
[CA-6302]: https://4teamwork.atlassian.net/browse/CA-6302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disposition csv exports: quote all values,

---

changes/CA-6401.bugfix
opengever/disposition/reports.py
opengever/disposition/tests/test_sippackage.py

Backport to 2023.15 needed
For [CA-6401]
[CA-6401]: https://4teamwork.atlassian.net/browse/CA-6401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix unicode error in disposition csv export.

---

.github/workflows/docker-image.yml
docker-compose.yml
docker/README.md
docker/core/Dockerfile
docker/testserver/Dockerfile

We now require a Gitlab token for building the Docker image.

Fix building Docker image

---

opengever/tabbedview/tests/test_dossier_listing.py

Fix flaky test.

---

changes/CA-6237.other
opengever/api/tests/test_dossier.py
opengever/api/tests/test_task.py
opengever/ogds/base/sources.py

Use username in title of Users sources.

---

changes/CA-6280.other
docs/public/dev-manual/api/api_changelog.rst
opengever/api/tasktree.py
opengever/api/tests/test_tasktree.py

Include responsible_actor in tasktree response.
For [CA-6280](https://4teamwork.atlassian.net/browse/CA-6280)
- API change:
[CA-6280]: https://4teamwork.atlassian.net/browse/CA-6280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 Display (name/avatar) of the responsible user in the tasktree

---

docker/core/Dockerfile

Patch certifi certs to address CVE-2023-37920

---

opengever/dossiertransfer/tests/test_token.py

Fix failing dossier transfer token tests.
Because the token creation time was frozen to `datetime(2024, 2, 18, 15, 45)`, but not the token *validation* times, these tests started failing on `master` as of today. Also freezing time during token validation fixes this.

Fix failing dossier transfer token tests.

---

opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po

Follow-up PR of: Add ability to restrict workspace mails and documents actions for guests #7909
For [CA-6417]
[CA-6417]: https://4teamwork.atlassian.net/browse/CA-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove leading space in french translation

---

changes/TI-13.feature
opengever/base/listing_actions.py
opengever/globalindex/browser/configure.zcml
opengever/globalindex/browser/report.py
opengever/globalindex/locales/de/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/en/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/fr/LC_MESSAGES/opengever.globalindex.po
opengever/globalindex/locales/opengever.globalindex.pot
opengever/globalindex/tests/test_reporter.py
opengever/ogds/base/actions.py
opengever/ogds/base/configure.zcml

Add Users excel export. 
For [TI-13](https://4teamwork.atlassian.net/browse/TI-13)
- API change:
- If breaking:
- Bug fixed:
[TI-13]: https://4teamwork.atlassian.net/browse/TI-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Users Excel export 

---

.github/pull_request_template.md

The stories came now from the TI team.

Update JIRA reference in pull_request_template.md

---

changes/TI-12.feature
opengever/base/listing_actions.py
opengever/globalindex/browser/report.py
opengever/workspace/actions.py
opengever/workspace/configure.zcml
opengever/workspace/report.py

Provide User excel export for workspace users
For [TI-12](https://4teamwork.atlassian.net/browse/TI-12)
- API change:
- If breaking:
- Bug fixed:
[TI-12]: https://4teamwork.atlassian.net/browse/TI-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide excel download for workspace users

---

opengever/dossiertransfer/api/perform.py
opengever/dossiertransfer/tests/test_api_perform.py

For [TI-161](https://4teamwork.atlassian.net/browse/TI-161)
[TI-161]: https://4teamwork.atlassian.net/browse/TI-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix typo: typeId -> typedId

---

changes/TI-156.feature
opengever/globalindex/browser/report.py
opengever/workspace/configure.zcml
opengever/workspace/report.py

Implement Endponit  for exporting workspace participants to Excel format.
For [TI-156](https://4teamwork.atlassian.net/browse/TI-156)
[TI-156]: https://4teamwork.atlassian.net/browse/TI-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide Excel Export for workspace participants

---

opengever/globalindex/browser/report.py

The Changes related to the PR [Workspace export participants](https://github.com/4teamwork/opengever.core/pull/7950/files).
We exclude any non ogds user from the Excel export

Remove any non ogdsuser from User excel export

---

opengever/base/context_actions.py

Rename function from `maybe_export_workspace_user` to `maybe_export_workspace_users`

Rename function to maybe_export_workspace_users

---

changes/TI-330.other
development.cfg
opengever/core/docker_testing.py
opengever/core/testing.py
opengever/core/testserver.py
opengever/redis/client.py
opengever/redis/tests/test_redis_client_manager.py

This PR integrates redis into gever by using the newly introduced redis-docker image from #7979 and providing a redis client manager class which can be used to optain a preconfigured redis client.
For [TI-330]
[TI-330]: https://4teamwork.atlassian.net/browse/TI-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Redis integration

---

changes/TI-710.other
opengever/dossiertransfer/api/post.py
opengever/dossiertransfer/locales/de/LC_MESSAGES/opengever.dossiertransfer.po
opengever/dossiertransfer/locales/en/LC_MESSAGES/opengever.dossiertransfer.po
opengever/dossiertransfer/locales/fr/LC_MESSAGES/opengever.dossiertransfer.po
opengever/dossiertransfer/locales/opengever.dossiertransfer.pot
opengever/dossiertransfer/tests/test_api_post.py

Create a `journal entry` in the `source` Dossier after dossier `transfer`.
For [TI-710](https://4teamwork.atlassian.net/browse/TI-710)
**Before:**
**After:**
[TI-710]: https://4teamwork.atlassian.net/browse/TI-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Create Journal entry in source dossier after transfer

---

changes/TI-336.bugfix
opengever/api/solr_query_service.py
opengever/api/tests/test_solrsearch.py

For [TI-336](https://4teamwork.atlassian.net/browse/TI-336)
[TI-336]: https://4teamwork.atlassian.net/browse/TI-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix handling of single special chars in search queries

---

README.rst
docker-compose.yml

This updates the compose file so that groups are configured properly for the local `ianus-backend` service, and documents all the necessary steps to actually use it. 
For [TI-503](https://4teamwork.atlassian.net/browse/TI-503)
[TI-503]: https://4teamwork.atlassian.net/browse/TI-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix and document setup with local Ianus portal

---

changes/TI-571.other
docs/public/dev-manual/api/config.rst
opengever/api/tests/test_config.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20240730133329_add_office_connector_plugin_check_feature_flag/registry.xml
opengever/core/upgrades/20240730133329_add_office_connector_plugin_check_feature_flag/upgrade.py
opengever/officeconnector/helpers.py
opengever/officeconnector/interfaces.py
opengever/officeconnector/tests/test_feature.py
opengever/testing/integration_test_case.py

Add Office Connector check feature flag
For [TI-571](https://4teamwork.atlassian.net/browse/TI-571)
[TI-571]: https://4teamwork.atlassian.net/browse/TI-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add office connector Extention check feature flag

---

docs/public/dev-manual/api/schemas/opengever.workspace.meeting.inc
docs/public/dev-manual/api/schemas/opengever.workspace.meetingagendaitem.inc
docs/public/dev-manual/api/schemas/opengever.workspace.workspace.inc
docs/schema-dumps/opengever.workspace.meetingagendaitem.schema.json
opengever/base/schemadump/config.py

For [TI-961](https://4teamwork.atlassian.net/browse/TI-961)
[TI-961]: https://4teamwork.atlassian.net/browse/TI-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes missing pointed bracket in Docs for VOCAB_OVERRIDES

---

changes/TI-658-2.other
docker/core/etc/site.zcml
opengever/base/context_actions.py
opengever/base/tests/test_utils.py
opengever/base/utils.py
opengever/core/lawgiver.zcml
opengever/core/profiles/default/rolemap.xml
opengever/core/upgrades/20240718143656_add_sign_permission/rolemap.xml
opengever/core/upgrades/20240718143656_add_sign_permission/upgrade.py
opengever/document/actions.py
opengever/document/tests/test_actions.py
opengever/readonly/tests/test_all_roles_and_permissions_mapped.py
opengever/sign/configure.zcml
opengever/sign/permissions.zcml

This PR adds the sign ui actions for documents if the sign-feature is enabled.
For [TI-658]
For [TI-659]
[TI-658]: https://4teamwork.atlassian.net/browse/TI-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TI-659]: https://4teamwork.atlassian.net/browse/TI-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sign actions

---

changes/GH-8029.bugfix
docker/core/Dockerfile

Persist content stats log file in Docker deployments

---

opengever/workspace/browser/meeting_pdf.py
opengever/workspace/browser/templates/meeting_minutes.pt
opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/en/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
opengever/workspace/locales/opengever.workspace.pot

All ToDos now have a checkbox that shows if they are completed or not.
For [TI-917]
[TI-917]: https://4teamwork.atlassian.net/browse/TI-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add checkbox to ToDos to show if they are completed

---

changes/GH-8065.other
docker/solr/Dockerfile
solr-conf/solrconfig.xml
versions.cfg

Latest available bugfix release for 8.11:
https://solr.apache.org/news.html#apache-solrtm-8114-available

Bump Solr to version 8.11.4

---

changes/TI-1261.bugfix
opengever/wopi/discovery.py
opengever/wopi/tests/test_discovery.py

Make WOPI discovery more robust regarding network or XML parsing failures.
For [TI-1261](https://4teamwork.atlassian.net/browse/TI-1261)
[TI-1261]: https://4teamwork.atlassian.net/browse/TI-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make WOPI discovery more robust.

---

opengever/globalindex/browser/configure.zcml
opengever/globalindex/browser/report.py
opengever/globalindex/tests/test_reporter.py

**This PR:**
changes the group memberships endpoint name 
For [TI-1476](https://4teamwork.atlassian.net/browse/TI-1476)
[TI-1476]: https://4teamwork.atlassian.net/browse/TI-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change the group memberships export endpoint name

---

changes/TI-1543.other
docs/public/dev-manual/api/api_changelog.rst
docs/public/dev-manual/api/role_assignment_reports.rst
opengever/api/configure.zcml
opengever/api/role_assignment_reports.py
opengever/api/tests/test_role_assignment_reports.py

This PR :
Introduces a new API endpoint `GET` `@role-assignment-report` that provides necessary information for generating role assignment reports in the new UI. It does not impact the existing `@role-assignments `and` @role-assignment-reports `endpoints, which will continue to function as they currently do.
For [TI-1543](https://4teamwork.atlassian.net/browse/TI-1543)
- API change:
- If breaking:
- Bug fixed:
[TI-1543]: https://4teamwork.atlassian.net/browse/TI-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

Provide Endpoint for role assignment to retrieve specific permissions

---

opengever/core/testserver.py
opengever/core/testserver_selftest.py
opengever/testing/builders/dx.py

This PR adds some new documents related to the signing process to the testing fixtures.
For [TI-1495]
[TI-1495]: https://4teamwork.atlassian.net/browse/TI-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend test fixtures

---

changes/TI.2100.feature
docs/public/dev-manual/api/api_changelog.rst
opengever/api/invitations.py
opengever/api/locales/de/LC_MESSAGES/opengever.api.po
opengever/api/locales/en/LC_MESSAGES/opengever.api.po
opengever/api/locales/fr/LC_MESSAGES/opengever.api.po
opengever/api/locales/opengever.api.pot
opengever/api/tests/test_config.py
opengever/api/tests/test_invitation.py
opengever/base/configuration.py
opengever/base/tests/test_configuration_adapter.py
opengever/core/upgrades/20250226083714_add_workspace_invitation_feature_flag/registry.xml
opengever/core/upgrades/20250226083714_add_workspace_invitation_feature_flag/upgrade.py
opengever/testing/integration_test_case.py
opengever/workspace/__init__.py
opengever/workspace/interfaces.py

This PR implements a new feature flag to disable workspace invitations.
For [TI-2100]
[TI-2100]: https://4teamwork.atlassian.net/browse/TI-2100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add feature to disable workspace invitations

---

changes/TI-2336.other
opengever/dossier/locales/en/LC_MESSAGES/opengever.dossier.po
opengever/dossier/locales/fr/LC_MESSAGES/opengever.dossier.po

Update Translations for 2025.6.0 Release.
English Translation: Rakhym
French Translation: Serge
For [TI-2336]
[TI-2336]: https://4teamwork.atlassian.net/browse/TI-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update translations before 2025.6.0 release

---

docker-compose.yml
docker/solr/Dockerfile
docker/solr/create_and_update_cores.sh
opengever/base/tests/test_solr.py
opengever/core/solr_testing.py
solr-conf/lang/compound_stems_de.txt
solr-conf/managed-schema.xml
solr-conf/solrconfig.xml
versions.cfg

This upgrades Solr from version 8.11.4 to the currently latest available version 9.8.1.
Beside using the new Solr version, the main configuration files `solrconfig.xml` and `managed-schema.xml` (renamed from `managed-schema`) have been updated. 
`solrconfig.xml` was taken from the techproducts sample config and the following customizations were reapplied:
- Use `SearchableText` as default query field
- Set default query operator to AND
- Enforce eDisMax parser with boosting of specific fields
- Detect language and map text to language specific fields (SearchableText, Description, Title)
- Enable text extraction with Tika (Solr Cell)
- Add replication handler for making backups in tests
- Add Data Import Handler for reindexing from another Solr instance
- Add JavaScript engine and script …

Upgrade Solr to version 9.x

---

changes/TI-2294.other
opengever/meeting/browser/configure.zcml
opengever/meeting/browser/templates/periods.pt
opengever/meeting/browser/toc.py
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/en/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po
opengever/meeting/locales/opengever.meeting.pot
opengever/meeting/tests/test_periods.py
opengever/meeting/tests/test_toc.py
opengever/meeting/toc/decision_sequence_number.py

This PR:
- Provides TOC download for decision sequence number.
For [TI-2294](https://4teamwork.atlassian.net/browse/TI-2294)
**Before:**
**After:**
[TI-2294]: https://4teamwork.atlassian.net/browse/TI-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide Toc download for decision sequence number

---

changes/TI-2959.bugfix
opengever/document/base.py

Return None if document has relation with RISProposal in get_proposal()
For [TI-2959]
- API change:
- If breaking:
- Bug fixed:
[TI-2959]: https://4teamwork.atlassian.net/browse/TI-2959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Return None if SubmittedProposal is RisProposal
